### ISSUE TITLE
First contract transaction not confirmed

### ISSUE THREAD

**Issue by Jacck** [ethereum/mist#100]
I just follow "Ethereum in practice part 1". It seems that I can not finish my first contract. Now it is 3h and no confirnation so far (0 out of 12). I have restarted Wallet. I have generated previously same contract (11h of processing now, same result). The source code, contract data are following the post contract configuration set-up. What should I do? I have not created any wallet, but the walled note says: "Accounts can't list incoming transactions, please create a wallet to store ether". It was not said to create any walled before the first contract. 

![image](https://cloud.githubusercontent.com/assets/5294193/12141486/1f8bd8e8-b470-11e5-94ea-3f1c9f0f88cb.png)

**Comment by alexvandesande** [comment]
If you are on the testnet it's probable that there wasn't any other available mining node: try mining it yourself.

If you are not on the testnet, how many peers did you have?

**Comment by Jacck** [comment]
Mining myself is working fine. Just sometimes in order to start is it needed to re-load (start with mainnet and back to testnet).

**Comment by tpc-coin20** [comment]
i am facing same issue. contract creation transaction is not confirmed from past 2 days . Please help anybody if found solution for this.
