### ISSUE TITLE
Can't switch to German with `view > change language`

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/mist#1000]
Node type: geth
OS: linux
Network type: main/test
Mist version: 0.8.1
branch: develop

![2016-07-20 00 20 54](https://cloud.githubusercontent.com/assets/3391420/16957654/d98ccbce-4e0f-11e6-8269-3b9415ab03b2.png)

Can't switch to German with `view > change language`. At the first glance, the `TAPi18n.setLanguage("de")` is not behave normally.
@luclu

**Comment by luclu** [comment]
Thanks @ChihChengLiang, I linked it in your post.

**Comment by ChihChengLiang** [comment]
`de` is not compiled in here https://github.com/ethereum/meteor-dapp-wallet/tree/master/app/public/i18n

**Comment by ChihChengLiang** [comment]
`de` and `es` ignored in [this commit](https://github.com/ethereum/meteor-dapp-wallet/commit/de96abeddb2b4d126f587007cb222299e492f149#diff-a084b794bc0759e7a6b77810e01874f2R8). why?
@frozeman

**Comment by luclu** [comment]
Tschusch! I even fixed this today in this PR https://github.com/ethereum/meteor-dapp-wallet/pull/246/files

**Comment by chevdor** [comment]
Dup of #945 ?

**Comment by luclu** [comment]
Related, this stated to happen after @alexvandesande rebased your PR. 
Your new PR has already partly fixed it for...

**Comment by ChihChengLiang** [comment]
Check if the `de` and `es` generated by changing cdn_path from `"cdn_path" : "i18n"` to `"cdn_path" : "/i18n"` in `project-tap.i18n`. It works on my computer.
reference: https://github.com/TAPevents/i18n-bundler/issues/2#issuecomment-174462279

**Comment by luclu** [comment]
I updated the `project-tap.i18n' files for both repos, but still the only languages that work for me are `en`, `fr`, `pt` and `ch`. With or without your bugfix. I will recheck if I miss something in my setup later today.

**Comment by ChihChengLiang** [comment]
This issue is actually unrelated to my bugfix. Instead, it's because the json in meteor-dapp-wallet `app/public/i18n` is not updated. If you run `TAPi18n.setLanguage("de").fail()`, it will show a JSON parse error which is because it fails to load `de.json` in  `app/public/i18n`.
Meteor should rebuild the public i18n files on startup, it should be configured somewhere in TAPevents/i18n-bundler .
