### ISSUE TITLE
'mist --mode wallet' empty screen, no meteor-wallet-dapp

### ISSUE THREAD

**Issue by chevdor** [ethereum/mist#1004]
Node type: geth
OS: osx
Network type: main
Mist version: 0.8.1

Running:
`./Mist --mode wallet
`

The wallet starts but once the splash popup is gone, the wallet dialog is totally empty. The console shows no error.

**Comment by luclu** [comment]
@alexvandesande same problem you fixed for `--mode mist` where icon on the splash is broken. 
Plus no meteor running the DApp.

**Comment by frozeman** [comment]
This seems to be connected to the new loki.js @hiddentao any idea? removing the mist folder seems to fix it for people, but this also removes wallets.

**Comment by hiddentao** [comment]
This is about starting up Mist, not the Wallet, am I right?

**Comment by chevdor** [comment]
This is just confusing as we used to have only the ethereum wallet and the --mode flag.

As I see now, there is both "Mist" and the "Ethereum Wallet", coming as 2 separate binaries.

Unless I am mistaken, the --mode flag no longer makes sense and if so, the flag could be removed (or a message added pointing to the other binary) and this issue closed.

**Comment by hiddentao** [comment]
Note: You can still run Mist when using Ethereum Wallet by using `--mode mist` but no the other way round.

**Comment by chevdor** [comment]
@hiddentao thanks for the info, that´s good for people who want both and want a single binary.

A simple fix would be to display a message for **--mode wallet** saying that this way is no longer working and the new binary should be used.

**Comment by hiddentao** [comment]
Long-term plan is to just release Mist and allow people to load the wallet from within Mist like just any other DApp. You can already access the Wallet Dapp at https://wallet.ethereum.org


On 9 August 2016 at 19:18:50, Chevdor (notifications@github.com) wrote:

@hiddentao thanks for the info, that´s good for people who want both and want a single binary.

A simple fix would be to display a message for --mode wallet saying that this way is no longer working and the new binary should be used.

**Comment by alexvandesande** [comment]
fixed the issue on last update
