### ISSUE TITLE
Can't locate daoFork file in Windows 

### ISSUE THREAD

**Issue by robbmcmahan** [ethereum/mist#1005]
Node type: geth
OS: windows
Network type: main
Mist version: 1.4.10
The release notes mention a daoFork that can be set to yes or no but I don't see it in the Windows version. 

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment]
`%appdata%\Mist\daoFork`
