### ISSUE TITLE
Compiler Error always defaults to 'e.message.replace is not a function'

### ISSUE THREAD

**Issue by egzumer** [ethereum/mist#1007]
Node type: geth
OS: windows
Network type: main
Mist version: 0.8.1

I try to deploy a contract, but when insert it to the contract deploy window in ethereum wallet (or mist) I get **e.message.replace is not a function** error. The problem here are parts referring to **amIOnTheFork** variable (I have no idea why). When I comment it out error disappears. I also managed to make it compile but the procedure is weird and I guess it shouldn't be doing that.

[Screen Capture](https://drive.google.com/file/d/0B4hSzONfReq8cFBjSXBHSEJiU2M/view?usp=sharing)

```
contract ReplaySafeProxy {
    // Tracks if the contract should work on this chain or not.
    bool enabled = false;
    // Fork oracle to use
    AmIOnTheFork amIOnTheFork = AmIOnTheFork(0x2bd2326c993dfaef84f696526064ff22eba5b362);
    address target;
    // _target is the address this contract will forward all funds to.
    // forked specifies if it should work on ETH (true) or ETHC (false)
    // Any value transfer to this contract will fail on the other network.
    function ReplaySafeProxy (address _target, bool forked) {
        if (amIOnTheFork.forked() == forked) {
            enabled = true;
        }
        target = _target;
    }
    // Forward value transfers.
    function() {
        if (enabled == false || msg.value == 0 || !target.send(msg.value)) {
            throw;
        }
    }
}
```

**Comment by luclu** [comment]
Thank you for reporting this @egzumer 
Mist's compiler error output is broken and always defaults to:
```javascript
Error: e.message.replace is not a function
```

---

[Browser Solidity](https://ethereum.github.io/browser-solidity/#version=soljson-latest.js) (Solidity version: `0.3.5-427deb43`) outputs:
```javascript
Untitled:5:5: Error: Identifier not found or not unique.
    AmIOnTheFork amIOnTheFork = AmIOnTheFork(0x2bd2326c993dfaef84f696526064ff22eba5b362);
    ^----------^
```

You will have to define the contract `AmIOnTheFork`.
Also `forked` inside the if clause is most likely missing its quotation marks.

**Comment by frozeman** [comment]
Is this closable? i didn't test this.

**Comment by luclu** [comment]
It works! ;)
