### ISSUE TITLE
Contract wallets not showing in Mist Browser

### ISSUE THREAD

**Issue by mbradm** [ethereum/mist#1011]
Node type: geth
OS: osx
Network type: main
Mist version: 0.8.1

My contract wallets do not load in the Mist Browser. Everything is fine in the wallet but not the browser (both wallet in browser mode and browser app have the same issue).

**Comment by evertonfraga** [comment]
Back in time, an update disrupted the local storage path. So all wallets vanished from the view. You can see what wallet contracts your accouts have created — using http://etherscan.io — and watch them again.

Issue closed due to inactivity. Please reopen if needed.
