### ISSUE TITLE
8 hours since last block (and counting)

### ISSUE THREAD

**Issue by jarredwalton** [ethereum/mist#1012]
Node type: geth
OS: windows
Network type: main
Mist version: 0.8.1

My wallet seems to have stalled at block 1927306, so it made it to the hard fork and a bit beyond and then stopped syncing. I've restarted Mist, rebooted the PC, still no luck. Anyone else seeing this problem?

**Comment by luclu** [comment]
Could you please paste your log from `%appdata%\Mist\node.log`?

**Comment by jarredwalton** [comment]
Strange... it suddenly picked back up and is now synced. One would think eight hours of sitting around falling behind wouldn't happen and then suddenly self-correct, but it did. Sorry for the false alarm. Or maybe my restarting the wallet just took a while to fix the issue. Anyway, here's where things apparently went wrong:

`I0721 08:41:45.797021 core/blockchain.go:963] imported 0 block(s) (1 queued 0 ignored) including 0 txs in 8.0214ms. #1926538 [0e8e20be / 0e8e20be]
I0721 08:41:46.399655 core/blockchain.go:963] imported 0 block(s) (1 queued 0 ignored) including 0 txs in 8.0208ms. #1926538 [0e8e20be / 0e8e20be]
I0721 08:41:48.250212 core/blockchain.go:963] imported 0 block(s) (0 queued 3 ignored) including 0 txs in 8.5236ms. #1926537 [3b2b2cc3 / eb82cabd]
E0721 08:41:50.730456 core/blockchain.go:1127] Bad block #1926538 (0x0e8e20be76169916ca40a959606f29f9cb688aee14848e4ca89e2795677e6414)
E0721 08:41:50.730456 core/blockchain.go:1128]     uncle[0](6d6c0cfd) header invalid: nonce for #1926534 [6d6c0cfd9b25778170fae417dcce3591e02ef04b24ff8fa6ee29709a76aa9c34…] is invalid (got 5104928618278262579)
I0721 08:41:54.975064 core/blockchain.go:963] imported 0 block(s) (0 queued 1 ignored) including 0 txs in 9.0277ms. #1924646 [02264935 / 02264935]
E0721 08:41:55.720088 core/blockchain.go:1127] Bad block #1926538 (0x0e8e20be76169916ca40a959606f29f9cb688aee14848e4ca89e2795677e6414)
E0721 08:41:55.720088 core/blockchain.go:1128]     uncle[0](6d6c0cfd) header invalid: nonce for #1926534 [6d6c0cfd9b25778170fae417dcce3591e02ef04b24ff8fa6ee29709a76aa9c34…] is invalid (got 5104928618278262579)
I0721 08:41:56.821084 core/blockchain.go:963] imported 0 block(s) (0 queued 29 ignored) including 0 txs in 35.0917ms. #1924675 [7be73fc2 / 06a4a38b]
E0721 08:42:00.730738 core/blockchain.go:1127] Bad block #1926538 (0x0e8e20be76169916ca40a959606f29f9cb688aee14848e4ca89e2795677e6414)
E0721 08:42:00.730738 core/blockchain.go:1128]     uncle[0](6d6c0cfd) header invalid: nonce for #1926534 [6d6c0cfd9b25778170fae417dcce3591e02ef04b24ff8fa6ee29709a76aa9c34…] is invalid (got 5104928618278262579)`

I get many lines of 'bad block' messages -- about 3MB worth, give or take.  Then this was one restart:

`I0721 18:56:54.251760 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to C:\Users\Jarred\AppData\Roaming\Ethereum\chaindata
I0721 18:56:55.270493 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------
I0721 18:56:55.270493 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0721 18:56:55.271496 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0721 18:56:55.271496 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0721 18:56:55.271496 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0721 18:56:55.276509 ethdb/database.go:169] closed db:C:\Users\Jarred\AppData\Roaming\Ethereum\chaindata
I0721 18:56:55.283528 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to C:\Users\Jarred\AppData\Roaming\Ethereum\chaindata
I0721 18:56:55.343691 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to C:\Users\Jarred\AppData\Roaming\Ethereum\dapp
I0721 18:56:55.347701 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0721 18:56:55.347701 eth/backend.go:201] Blockchain DB Version: 3
I0721 18:56:55.348704 core/blockchain.go:206] Last header: #1927306 [10ef75c8…] TD=39918441442044031355
I0721 18:56:55.348704 core/blockchain.go:207] Last block: #1927306 [10ef75c8…] TD=39918441442044031355
I0721 18:56:55.348704 core/blockchain.go:208] Fast block: #1927306 [10ef75c8…] TD=39918441442044031355
I0721 18:56:55.348704 eth/handler.go:116] blockchain not empty, fast sync disabled
I0721 18:56:55.348704 p2p/server.go:313] Starting Server
I0721 18:56:56.427645 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-IP1
I0721 18:56:56.499335 p2p/discover/udp.go:217] Listening, enode://198f0e77deb330171379b280537f887d0e51905909af486c97ced5e03dcf0b8fb5bd197c76e6291f0639f1b9c941f063011e41efb910ded5b5f006a9e5217dc5@73.11.198.119:30303
I0721 18:56:56.500338 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc
I0721 18:56:56.500840 p2p/server.go:556] Listening on [::]:30303
I0721 18:56:56.530920 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-IP1
I0721 18:57:14.953013 eth/handler.go:295] Peer 1118980bf48b0a36 [eth/63]: timed out DAO fork-check, dropping
I0721 18:57:18.541279 eth/handler.go:295] Peer a979fb575495b8d6 [eth/63]: timed out DAO fork-check, dropping
I0721 18:57:20.115562 eth/handler.go:295] Peer f1df486f9a8e4525 [eth/63]: timed out DAO fork-check, dropping`

And here's another where it gets back on track:

`I0721 19:36:28.693814 cmd/utils/flags.go:678] You're one of the lucky few that will try out the JIT VM (random). If you get a consensus failure please be so kind to report this incident with the block hash that failed. You can switch to the regular VM by setting --jitvm=false
I0721 19:36:28.693814 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to C:\Users\Jarred\AppData\Roaming\Ethereum\chaindata
I0721 19:36:28.787062 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------
I0721 19:36:28.787062 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0721 19:36:28.787062 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0721 19:36:28.787062 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0721 19:36:28.787062 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0721 19:36:28.790071 ethdb/database.go:169] closed db:C:\Users\Jarred\AppData\Roaming\Ethereum\chaindata
I0721 19:36:28.796086 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to C:\Users\Jarred\AppData\Roaming\Ethereum\chaindata
I0721 19:36:28.848225 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to C:\Users\Jarred\AppData\Roaming\Ethereum\dapp
I0721 19:36:28.855243 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0721 19:36:28.855243 eth/backend.go:201] Blockchain DB Version: 3
I0721 19:36:28.857249 core/blockchain.go:206] Last header: #1927306 [10ef75c8…] TD=39918441442044031355
I0721 19:36:28.857249 core/blockchain.go:207] Last block: #1927306 [10ef75c8…] TD=39918441442044031355
I0721 19:36:28.857249 core/blockchain.go:208] Fast block: #1927306 [10ef75c8…] TD=39918441442044031355
I0721 19:36:28.858252 eth/handler.go:116] blockchain not empty, fast sync disabled
I0721 19:36:28.862262 p2p/server.go:313] Starting Server
I0721 19:36:30.811455 p2p/discover/udp.go:217] Listening, enode://198f0e77deb330171379b280537f887d0e51905909af486c97ced5e03dcf0b8fb5bd197c76e6291f0639f1b9c941f063011e41efb910ded5b5f006a9e5217dc5@[::]:30303
I0721 19:36:30.812458 p2p/server.go:556] Listening on [::]:30303
I0721 19:36:30.815467 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc
I0721 19:36:34.892398 p2p/discover/ntp.go:58] --------------------------------------------------------------------------------
I0721 19:36:34.892398 p2p/discover/ntp.go:59] System clock seems off by -10.757393149s, which can prevent network connectivity
I0721 19:36:34.892398 p2p/discover/ntp.go:60] Please enable network time synchronisation in system settings
I0721 19:36:34.892398 p2p/discover/ntp.go:61] --------------------------------------------------------------------------------
I0721 19:36:55.961832 eth/handler.go:295] Peer a979fb575495b8d6 [eth/63]: timed out DAO fork-check, dropping
I0721 19:37:55.087596 eth/handler.go:295] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping
I0721 19:38:23.515552 eth/handler.go:295] Peer 1118980bf48b0a36 [eth/63]: timed out DAO fork-check, dropping
I0721 19:41:03.411266 eth/handler.go:295] Peer f1df486f9a8e4525 [eth/63]: timed out DAO fork-check, dropping
I0721 19:42:48.768475 eth/handler.go:295] Peer a979fb575495b8d6 [eth/63]: timed out DAO fork-check, dropping
I0721 19:48:56.957724 eth/handler.go:295] Peer a979fb575495b8d6 [eth/63]: timed out DAO fork-check, dropping
I0721 19:49:59.532626 eth/handler.go:295] Peer f1df486f9a8e4525 [eth/63]: timed out DAO fork-check, dropping
I0721 19:54:04.606456 eth/handler.go:295] Peer f1df486f9a8e4525 [eth/63]: timed out DAO fork-check, dropping
I0721 19:55:12.638396 eth/handler.go:295] Peer a979fb575495b8d6 [eth/63]: timed out DAO fork-check, dropping
I0721 19:58:13.848814 eth/handler.go:295] Peer f1df486f9a8e4525 [eth/63]: timed out DAO fork-check, dropping
I0721 20:01:10.398550 eth/handler.go:295] Peer a979fb575495b8d6 [eth/63]: timed out DAO fork-check, dropping
I0721 20:05:12.354337 eth/handler.go:295] Peer f1df486f9a8e4525 [eth/63]: timed out DAO fork-check, dropping
I0721 20:06:48.568279 eth/handler.go:295] Peer f1df486f9a8e4525 [eth/63]: timed out DAO fork-check, dropping
I0721 20:07:19.189607 eth/handler.go:295] Peer a979fb575495b8d6 [eth/63]: timed out DAO fork-check, dropping
I0721 20:07:23.134363 eth/handler.go:295] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping
I0721 20:08:11.567265 eth/downloader/downloader.go:320] Block synchronisation started
I0721 20:08:20.491017 core/blockchain.go:963] imported 3 block(s) (0 queued 0 ignored) including 7 txs in 1.0823817s. #1927309 [9fd96321 / 04bb1035]
I0721 20:08:21.499261 core/blockchain.go:963] imported 3 block(s) (0 queued 0 ignored) including 10 txs in 40.1111ms. #1927312 [b3626b1d / 269db273]
I0721 20:08:23.204904 core/blockchain.go:963] imported 4 block(s) (0 queued 0 ignored) including 5 txs in 47.1296ms. #1927316 [7a555db1 / 039807b1]
I0721 20:08:26.107305 core/blockchain.go:963] imported 8 block(s) (0 queued 0 ignored) including 30 txs in 156.9215ms. #1927324 [fdb0ecc0 / 45bae084]
I0721 20:08:28.273702 core/blockchain.go:963] imported 10 block(s) (0 queued 0 ignored) including 116 txs in 287.778ms. #1927334 [a8955383 / f66b33f6]`
