### ISSUE TITLE
lost ether when updated Mist to hard fork!

### ISSUE THREAD

**Issue by sharipeach** [ethereum/mist#1016]
Opened my wallet today- had 123 ether.
Closed the wallet.

Updated wallet from github download - balance is now zero ether.  :(

Please help!  Where did it go?

**Comment by luclu** [comment]
Please use a blockchainexplorer like https://etherscan.io to verify your account balance. Give me a heads-up on the outcome. It might be a problem with the wallet.
Also please post the `%appdata%\Mist\node.log`'s output.

**Comment by luclu** [comment]
Basically check if https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide#my-transaction-is-not-confirmed applies.

**Comment by luclu** [comment]
Please have a look at https://github.com/ethereum/mist/issues/1028
