### ISSUE TITLE
Ethereum not showing in wallet but etherscan says it has deposited...

### ISSUE THREAD

**Issue by i22662247420** [ethereum/mist#1017]
<img width="704" alt="screen shot 2016-07-22 at 11 51 44 pm" src="https://cloud.githubusercontent.com/assets/20605950/17076463/65494d32-5067-11e6-9db9-d2130fe88ef5.png">

There's the proof of one of the transactions but no deposit is showing and it's been over 15 hours now.... I did about 100 more ether as well but haven't screenshot them yet. Please help. A little upsetting...

I'm on a mac btw and running latest version of mist wallet. geth

**Comment by gerardorz** [comment]
Same issue...it's been more than 15 hours...wallet still in zero...any help please?

**Comment by gerardorz** [comment]
I updated the wallet as suggested but still not working...

**Comment by i22662247420** [comment]
has been 24 hours now and there is still nothing in my account.... please help with this. I'm new to this technology and this Mist wallet is leaving a bad taste in my mouth. Not sure if I want to continue with this service...

**Comment by i22662247420** [comment]
do I need to sync the mist wallet? how do I do that on mac? I'm running the latest version of geth but nothing is working... tried using the terminal with command "./geth --fast" and did not work...

**Comment by luclu** [comment]
Please do the following to have your situation resolved: 

1. Make sure your node is fully synced with the network.
2. Furthermore due to the recent Hard Fork you have to run at least version `0.8.1`.
3. Compare the latest block number to the ones shown on http://fork.ethstats.net. Should you find yourself on the non-fork chain you will have to remove the `%APPDATA%\Ethereum\chaindata` folder and do a full resync.

**Comment by luclu** [comment]
Moved from https://github.com/ethereum/meteor-dapp-wallet/issues/251, @sakis123: 
> Hi i have many problems with the wallet.
I make yesterday a transaction from my wallet to another account which i have , i see until now from the wallet 5.000 Confirmations but the coins never go to my other account. i did not make any mistake to the address.
I see from the etherchain that my balance is 22 ether but from my wallet i don't see this balance.
I create a second address from the wallet i make a transaction from the 1st address to the 2nd the coins transfered but from the etherchain i get the message for the 2nd address: Error: Account not found!
what happened ?
Sorry for my English

**Comment by i22662247420** [comment]
Omg this is so confusing.... it says i have 773 ether in my account but only shows 614 and I have no idea how to do any of the stuff mentioned above.... Can somebody please help me out from brother to brother? If not please help me out and I can pay you ether... this is crazy intense and I'm not really competent in in-depth computer functions.

**Comment by i22662247420** [comment]
how do you make sure your node is fully synced with the network?

**Comment by i22662247420** [comment]
like I said above, I am running the most recent version of geth.... don't know how to find version 0.8.1

**Comment by i22662247420** [comment]
Okay Im running on a mac and I have no idea what Im doing. If someone can create me a youtube video showing me how to do everything I need to know I will pay you $50

**Comment by i22662247420** [comment]
I have the most recent version of geth.... just download this AFTER the fork and both ether AFTER the fork.... it says I'm synced when the app opens... why is it not working :(
'

**Comment by luclu** [comment]
@i22662247420 please upload a screenshot of your Ethereum-Wallet GUI

**Comment by i22662247420** [comment]
<img width="1089" alt="screen shot 2016-07-23 at 1 39 36 pm" src="https://cloud.githubusercontent.com/assets/20605950/17080194/fa7994f2-50da-11e6-975d-e65c1ae481cd.png">

**Comment by i22662247420** [comment]
uploaded

**Comment by luclu** [comment]
Your node synced you onto the non-HF chain. As stated [above](https://github.com/ethereum/mist/issues/1017#issuecomment-234735982) :point_up: you can verify this this way: 
> Compare the latest block number to the ones shown on http://fork.ethstats.net. Should you find yourself on the non-fork chain you will have to remove the %APPDATA%\Ethereum\chaindata folder and do a full resync.

Your current block resembles the one of the non-HF chain as you can see it on http://fork.ethstats.net.

**Please** do the following:

1. Close Ethereum-Wallet
2. Remove the folder `%APPDATA%\Ethereum\chaindata`
3. Download version `0.8.1`
4. Restart and let the software resync the whole chain

**Comment by i22662247420** [comment]
I have version 0.8.1 do I still need to re-download it?

Also, where do I find the folder %APPDATA%\Ethereum\chaindata ?

I just searched all of the folders and couldn't find it.... thanks for your help man

**Comment by luclu** [comment]
> I have version 0.8.1 do I still need to re-download it?

Yes
>Also, where do I find the folder %APPDATA%\Ethereum\chaindata ?

Just paste this in the windows explorer navigation bar.

**Comment by i22662247420** [comment]
typed it in and nothing came up except for my mail messages... damn

**Comment by i22662247420** [comment]
I'm on a mac

**Comment by i22662247420** [comment]
not sure why this is more complicated then you're making it seem to be.

**Comment by i22662247420** [comment]
<img width="771" alt="screen shot 2016-07-23 at 2 06 58 pm" src="https://cloud.githubusercontent.com/assets/20605950/17080300/c1aedb9c-50de-11e6-9dc0-1dc2ae692da5.png">

**Comment by luclu** [comment]
1. open Ethereum-Wallet `0.8.1`
2. menu -> accounts -> backup -> application data
3. go to parent folder
4. remove `chaindata`

**Comment by i22662247420** [comment]
I did that... really hoped it was gonna work... downloaded mist wallet 0.8.1 as well and it had to resync with 1,9xx,xxx nodes but still didn't show my actual balance :/

**Comment by i22662247420** [comment]
still shows 614

**Comment by TkxPT** [comment]
Hi everyone.
I'm going to join i22662247420 on this one.
Had issues with synching and discovered I was on the non-HF chain following your suggestions luclu.
Deleted all the data on chain data and re-synched from scratch. I'm still missing my latest transaction of ether (~15ETH): https://etherscan.io/address/0xc961dbb0c20b30b645158619e3dead5ce201e128

Days before, the first two (~9 + ~10) were quick and almost instantaneous but when I purchased the last 15, these were not delivered although the transaction shows as valid and complete...
Help?
I have the latest version, etc etc.
Can't understand why it's not showing?
Thanks for your time!

**Comment by luclu** [comment]
Please have a look at https://github.com/ethereum/mist/issues/1028

**Comment by i22662247420** [comment]
dude i did all of those steps.... i deleted the chaindata yesterday so its not even showing under "parent folder".... i did everything exactly like you said.... why is this still not working.... I'm probably going to cash out when/if I ever get my tokens back because this technology just doesn't seem worth it smh

**Comment by i22662247420** [comment]
I just don't understand how it could not be working.... I deleted "daofork" today; and "chaindata" folder yesterday. when i opened ethereal again it gave me the option of which one i wanted to sync to well i chose one and it did work so i did it all again and chose the other option and it still didn't work!! this is ridiculous!!!

**Comment by i22662247420** [comment]
I couldn't even find the folder for chaindata this time and I looked in the exact same space I found it and deleted it in yesterday before I re-downloaded mist and re-synced.... please help... very upsetting.

**Comment by i22662247420** [comment]
finally worked thank you for your patience and help....

**Comment by gerardorz** [comment]
Hello,

I updated and synchronized my wallet and I got the following window. It is
going to be almost a week since I sent some ETH from Poloniex.

The transaction has been confirmed as states the last picture.

What do you recommend should I do please?

Regards,

Gerard

[image: Images intégrées 1]

[image: Images intégrées 1]

2016-07-26 5:18 GMT-04:00 Luca Zeug <notifications@github.com>:

**Comment by luclu** [comment]
@gerardorz please don't necrobumb closed issues. 
As your screenshots are not displayed presume that your nodes is on the non-fork.
Please refer to this guide to verify if you are affected and get your situation resolved: https://github.com/ethereum/mist/issues/1028

**Comment by jfpalngipang** [comment]
I have version 0.8.8. I just funded my account with bitcoin but my wallet still says 0.00 ether. what to do?

**Comment by luclu** [comment]
@jfpalngipang please use the search function if your issue isn't resolved by now.
