### ISSUE TITLE
My password wont work i wrote it down but...could there be two one for each network?

### ISSUE THREAD

**Issue by keznerve** [ethereum/mist#102]
I got mist working , i was asked for a password which i gave and confirmed, i was on the test network.
I shut down and the next day  i went on to the main network was prompted for a password and i put a new one with a slight deviation to the original it asked me to confirm , so i presumed that it was one password for test and one for the main , i got some ether and when i tried to set up the wallet it said 'wrong password' it is infuriating because neither work? The second one may have been done in haste , but why doesnt my original password work? any ideas

**Comment by frozeman** [comment]
Which platform are you on?
When "asked for a password", you mean when you clicked "create account"?

Did you use special chars and spaces in the password?

**Comment by frozeman** [comment]
I just tested on a windows VM, creating an account with the password "! 2e" and i could unlock fine after.

**Comment by keznerve** [comment]
hi thanks for the reply , its on a mac os 
i used no special chars. I am a bit confused as i think it opened the dialog box when i first started mist, i dont remember clicking anything , but i may have. I was careful to write the password down. I was on the test net, when i switched to the main network to get some eth i was prompted again and i put in a new password,  now neither works.  I can start again with the whole process. i only had $20 of eth which is not too bad , it is more the seting up and being so close!

**Comment by keznerve** [comment]
Do i just re install my wallet?

**Comment by frozeman** [comment]
oh ok, then you started the wallet with the `eth` node, which requires a master password. I mainly develop with geth, and didn't test eth fully, as there are some minor problems.

Please switch to the `geth` node, in the top develop menu, if you can't then go to the `~/Library/App..Support/Mist/node` file and change the content from `eth` to `geth`

**Comment by keznerve** [comment]
thanks for the reply , so i am in the main network under the develop pull down on the menu, which is fine but when i go to add a wallet it asks for a pasword for the transaction and it says password wron when i enter the password i started mist with. Am i missing something ?

**Comment by frozeman** [comment]
The master password you set on the beginning, has nothing to do with the account passwords, you're asked to type in when confirming a tx.

try using no password, as it could be that the account has not password set. (so leave it empty)

**Comment by keznerve** [comment]
OK

**Comment by keznerve** [comment]
Still says wrong password.... ?

**Comment by frozeman** [comment]
can you create another account and give it a password? then try unlocking this account when you send a tx. (you need ether on that account to do so). Does this then unlock?

**Comment by keznerve** [comment]
Hi sorry about the slow reply , my macbook died when trying to analyse blocks ....so i have to get it looked at! Im not sure if it was the things id downloaded or not, i shall find out! Then i will be back on it, i want to put my N.P.O(charity) on ethereum , make it transparent  by creating a DAO..... will get there soon i hope.

**Comment by fineartcommodities** [comment]
Hi, some kind of same problem. I was playing with Ethereum Wallet v.4 for the first time. I set up 3 account and one wallet contract. All was running fine. I was able to transfer ETH between account and wallet and to external accounts and wallets. The same with latest v.5 Ethereum Wallet realize. I have written all the password but somehow I don't find and I don't remember the master password necessary for some tasks. I have backed up account and data. How can I do to setup another instance (on same PC windows 7) of Ethereum Wallet, and setup a new master password? I plan than to import account, but accounts will import the old master password?

**Comment by keznerve** [comment]
i thought that updating my wallet may change things , it has not , any ideas.

**Comment by Oliver7580** [comment]
Hello everyone i am a new member,with a sad reason to join here :(
I have got the problem  that all my ether is stuck in account 2,i can´t send it because it says my password is wrong,but that can´t really be.I wrote my password first in a Text Document and saved it,then i typed it in for the account setup 2 times and it was ok,I mean it is 26 characters long and it would be very curious if i typed the same failure 2 times.I restarted the wallet several times but i had no luck.
This wallet should have the option to export your password like it is after you set it.Since you can not see what you are writing,big shit the whole thing.What can i do?

**Comment by frozeman** [comment]
@Oliver7580 can you open the console (menu -> develop -> toggle console...) and see if you see any IPC errors?
This could show that you disconnected from the node.

Or does the gas estimation shows 0? That would be the same signal...

Otherwise your password was certainly wrongly typed. did you change your keyboard layout? did you have your caps lock on?

**Comment by Oliver7580** [comment]
Hello
THX for the quick answer.I am not at home now,but i know the gas wasn't zero.
I didn't changed my keyboard layout and capslock was not enabled.I tried the password with capslock on and off,also i replaced every downletter with high and every high with down.
I will open the console when i am home.
When this won't solve the Problem,have i lost 1032Ethers,or is there a Chance to do anything?

**Comment by frozeman** [comment]
There is no chance to fix that if you mistyped your password, but i can try to help you in skype if i find time: "frozeman.de"

**Comment by Oliver7580** [comment]
Oh man that sounds terrible,i won't get it in my head,i just can't believe it,typed the same failure two times in 26characters,this is like a Jackpot in Lotto of crap.
Pyethrecover won't work for me either?

**Comment by frozeman** [comment]
i would first try to enter the password using the geth console. e.g. run `geth attach` after you started the wallet

**Comment by Oliver7580** [comment]
Sending ether with the mainbase account works fine,another Bad sign?

**Comment by Oliver7580** [comment]
It is in Windows 7 wäre do i find gern?

**Comment by frozeman** [comment]
Hier: `...wallet/resources/node/geth/geth.exe`

**Comment by Oliver7580** [comment]
Fabian do you speak german?

**Comment by frozeman** [comment]
Yes, we can do that over skype: "frozeman.de" but probably not today

**Comment by Oliver7580** [comment]
Oh thanks you so much.i am at work i will call you.Thanks man

**Comment by rafajafar** [comment]
I'm 100% certain I'm using the correct password, but after upgrading from 5.1 to 6.2, my password wont work. Tried so many times, so many ways, restarted the computer, recreated the chaindb, everything. It says wrong pass word every time. Windows 10.

**Comment by tyeegeoff** [comment]
The password function for mist does not work for me either.  I use a long nine word nemonic password and it fails every time... Can you explain what is happening?  Thanks

**Comment by rafajafar** [comment]
Yeah I still have no solution to this, either. I'm resigned to thinking my
eth is in a black hole.

On Fri, May 13, 2016 at 3:07 PM, tyeegeoff <notifications@github.com> wrote:

> The password function for mist does not work for me either. I use a long
> nine word nemonic password and it fails every time... Can you explain what
> is happening? Thanks
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/mist/issues/102#issuecomment-219133036>
>



-- 
 Any fool can write code that a computer can understand. Good programmers
write code that humans can understand.
--Martin Fowler

**Comment by keznerve** [comment]
I have  the wrong password message problem all round creating wallets, contracts and sending ETH , i tried to re-install mist import my key file, but the settings where the same as the old mist.I was also triying to send eth on my terminal (osx) but it proved problematic. There must be a way if you install mist and import the key file? I really want to get some DAO tokens before the end of the crowdsale...its stressful! i have alot of ETH i bought in December in my wallet?!

**Comment by isaacmao** [comment]
I met the same issue not in transaction, but running a contract function. 
![image](https://cloud.githubusercontent.com/assets/81030/16374261/4dcdb816-3c88-11e6-81ca-166b1c969df4.png)

Apparently it's not really wrong in password as I can assure it's correct with all other functions(sending coin, etc.)

**Comment by m0a0r0i0a0n** [comment]
I got the same problem, can someone help us???
Thank you

**Comment by timoffei** [comment]
Have same problem

**Comment by luclu** [comment]
The current "wrong password" alert is broken, as the error string emitted by geth did change.
Possible errors are as following https://github.com/ethereum/mist/issues/664:
>
 - `could not decrypt key with given passphrase` (wrong password)
 - `multiple keys match address` (multiple copies of the same account)
 - `Insufficient funds for gas * price + value` (not enough ether in etherbase account to invoke contract transaction)
 - `Unable to connect to socket: timeout` (node terminated, etc; used to be `CONNECTION ERROR`)

The ongoing PR is https://github.com/ethereum/mist/pull/959 and will be available in version `0.8.1`.

In future releases we propose to use [error codes](https://github.com/ethereum/wiki/wiki/JSON-RPC-Error-Codes-Improvement-Proposal) to ensure consistency and compatibility to other nodes.
