### ISSUE TITLE
issue loading mist on new laptop

### ISSUE THREAD

**Issue by g022362** [ethereum/mist#1020]
Anyone ever seen anything like this. I've been trying to load wallet for last few days with no luck. It usually gets about 100,000 blocks downloaded and then stops. I've left it for days but it doesn't move. I'm not very good at this and just want to be able to access my ether and DGD tokens. I,ve tried some of the syncing fixes (that I understand!!!) without luck. I'm nearly a week trying to load a wallet now!!!!Please help but keep it simple!!!thanks

![image](https://cloud.githubusercontent.com/assets/20611400/17077763/59abbb78-50d4-11e6-961d-c9b84ce1fc83.png)

**Comment by luclu** [comment]
Judging from the error message your `chaindata` seems to seems to be corrupted, i.e. some file is miss. 
Remove the folder `%appdata%\Ethereum\chaindata` and do a full resync.

I'm closing this as I'm certainly sure this is the only thing that will help.
