### ISSUE TITLE
Mist wallet node sync error. Please help!

### ISSUE THREAD

**Issue by amitpk** [ethereum/mist#1024]
Node type: geth/eth
OS: windows
Network type: main
Mist version: 0.8.1

![unbenannt-1](https://cloud.githubusercontent.com/assets/10135872/17092777/1ff30176-5245-11e6-96ed-e1b4089ed36e.png)

**Comment by bbbolongx** [comment]
I got the same problem, and I forgot to back the wallet.

**Comment by luclu** [comment]
@amitpk @bbbolongx could you please upload the logs?

> - Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log` 
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by amitpk** [comment]
[nodes.zip](https://github.com/ethereum/mist/files/381275/nodes.zip)

**Comment by luclu** [comment]
@amitpk you ended up in the wrong folder there. ;)

**Comment by amitpk** [comment]
What do you mean?

**Comment by luclu** [comment]
The file I need lies is `%APPDATA%\Mist\node.log`
rather than `%APPDATA%\Ethereum\nodes\`.

**Comment by amitpk** [comment]
Can I email it to you?

**Comment by luclu** [comment]
Paste its content in here.

**Comment by amitpk** [comment]
Is it safe to post here?

**Comment by luclu** [comment]
Most likely. But you can go to https://gitter.im/ethereum/mist and PM if you want.

**Comment by luclu** [comment]
Closed as of inactivity.
