### ISSUE TITLE
I want to sync to the HF chain but ended on the non-fork chain; Ether is missing

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#1028]
## What did happen?

With the recent [Hard Fork](https://blog.ethereum.org/2016/07/20/hard-fork-completed/) the network [split in to chains](http://fork.ethstats.net). The **HF** chain and **non-fork** chain:

![the-moment-ethereum-historically-hardforked](https://cloud.githubusercontent.com/assets/10135872/17083287/4ebd273e-519b-11e6-8bef-db402b68ab61.jpg)
### There is the possibility that you are on the **non-fork** chain.

This could have happened if:
- you didn't update **Etherum-Wallet** to `0.8.1`.
- you updated to `0.8.1` and chose to oppose the HF (instructing **Ethereum-Wallet** to sync with the non-fork chain)
## Am I affected?

You are affected if you didn't update to `0.8.1` before **Ethereum-Wallet** synced past block `1,920,000`.
#### Please compare the **block-number** in Ethereum-Wallet:

![unbenannt-7](https://cloud.githubusercontent.com/assets/10135872/17084156/2d7ff0f8-51b7-11e6-941d-1fb25a9d7331.jpg)
#### With the ones found on http://fork.ethstats.net:

![unbenannt-8](https://cloud.githubusercontent.com/assets/10135872/17084157/2d811f78-51b7-11e6-9a1a-af2cb2631598.jpg)
## What can I do?

You will have to delete or rename the `chaindata` folder. (If you still have plenty of storage you are better off with renaming it so that you can switch back - if there was need - without having to do a full resync again.)
#### Please do only one step at a time:
1. download **Ethereum-Wallet** `0.8.1` ([link](https://github.com/ethereum/mist/releases))
2. open **Ethereum-Wallet** `0.8.1` 
3. go to `menu -> develop -> "The DAO" Fork -> Support DAO Fork`
4. go to `menu -> accounts -> backup -> accounts`
5. switch to the parent folder, you should be able to find the `chaindata` folder
6. close **Ethereum-Wallet**
7. remove or rename the `chaindata` folder
8. open **Ethereum-Wallet** - you will now be syncing to the chain of your choice

**Comment by mamba911** [comment]
help..

![error geth](https://cloud.githubusercontent.com/assets/20615808/17175446/9304b1fa-53d5-11e6-8e4f-348a47989fcf.jpg)

**Comment by Denis9555** [comment]
So when I got this 
 
https://cloud.githubusercontent.com/assets/232662/16900179/a7705a00-4c1d-11e6-8027-dfb072f89810.png

What I have to do? I wanna only ETH wallet not ETH,ETC 

Di I have to click YES or NO ?

**Comment by Doncharly** [comment]
Yees Bot I Can,t When Put My Mouse In Yess Don,t Garet

Cuando pongo el     raton en si, no  permite  nada solo sale la lupa y hace
grande la imagen
ᐧ

2016-09-04 11:40 GMT-05:00 Denis9555 <notifications@github.com>:

**Comment by Denis9555** [comment]
@Doncharly 
Ok I will try I am already en 900.000 block

**Comment by Denis9555** [comment]
Nothing I can even chose...
