### ISSUE TITLE
Cant open ethereum or mist wallets after installing version 8.0 then upgrading to 8.10

### ISSUE THREAD

**Issue by Jasminrice** [ethereum/mist#1032]
mac OS on Macbook pro with 10 gig memory left 
Version: `10.10.5`
Node type: `geth(default)`

![screen shot
[Screen Shot 2016-07-25 at 6.37.49 pm.png.pdf](https://github.com/ethereum/mist/files/381057/Screen.Shot.2016-07-25.at.6.37.49.pm.png.pdf)
 2016-07-25 at 6 37 49 pm](https://cloud.githubusercontent.com/assets/20367943/17095277/04e7395e-5297-11e6-9742-17e84ba663d3.png)

```
Fatal: Could not open database: read /Users/david/Library/Ethereum/chaindata/264999.log: result too large
```

**Comment by luclu** [comment]
This seems to be an OS X data corruption: https://discussions.apple.com/thread/974231?tstart=0

Please check and repair your filesystem or remove the `~/Library/Ethereum/chaindata` folder and do a full resync.
