### ISSUE TITLE
Localization failed to apply on built wallet

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/mist#1037]
#### System information
``````
Version: `0.8.1`
OS & Version: osx
Node type: `geth`
branch: develop
``````

Tschusch! It seems `tap:i18n-bundler` exists for some reason, sorry I removed it in https://github.com/ethereum/mist/pull/1018 . The removal of `tap:i18n-bundler` works on develop mode, but fails on the built mode.

When switched the language with `view > change language`, the text on the meteor-dapp-wallet failed to localize. 

<img width="1104" alt="screen shot 2016-07-26 at 8 55 23 pm" src="https://cloud.githubusercontent.com/assets/3391420/17138904/eb6f77dc-5374-11e6-8ac8-f7e5690ba4e2.png">

In develop mode the i18n JSONs can be fetched with DDP from server to client, while in built mode the `meteor-build-client` forces the files fetched with `file:` protocol. I believe the simplest fix is to add the `tap:i18n-bundler` package back and make sure every i18n JSONs are generated in the `public` folder properly.

**Comment by luclu** [comment]
I tried to play around with symlinks but that doesn't seem to suffice as `tap:i18n-bundler` also merges all of them into one file which seems to be necessary.

Seems like reverting to it would be the best for now.

**Comment by luclu** [comment]
Reverted to use `tap:i18n-bundler` (https://github.com/ethereum/mist/pull/1093).
