### ISSUE TITLE
not correctly displays the status of the account

### ISSUE THREAD

**Issue by oip90** [ethereum/mist#1038]
#### System information
``````
Version: `0.8.1`
OS & Version: windows 7
Node type: `geth(default)`
``````

![1](https://cloud.githubusercontent.com/assets/6263047/17145401/a845cc34-5362-11e6-9261-906ec32fd4c9.png)
![2](https://cloud.githubusercontent.com/assets/6263047/17145402/a8485544-5362-11e6-8743-828f26b72acd.png)
![3](https://cloud.githubusercontent.com/assets/6263047/17145403/a8485cba-5362-11e6-84ef-2ce20ade8029.png)
NODE.LOG:
```
I0726 18:44:25.239232 ethdb/database.go:82] Allotted 512MB cache and 1024 file handles to C:\Users\vasya\AppData\Roaming\Ethereum\chaindata
I0726 18:44:25.416250 cmd/utils/flags.go:849] ------------------------------------------------------------------------------------------------
I0726 18:44:25.416250 cmd/utils/flags.go:850] Geth is currently configured to SUPPORT the DAO hard-fork!
I0726 18:44:25.416250 cmd/utils/flags.go:851] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0726 18:44:25.416250 cmd/utils/flags.go:852] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0726 18:44:25.416250 cmd/utils/flags.go:853] ------------------------------------------------------------------------------------------------
I0726 18:44:25.416250 ethdb/database.go:169] closed db:C:\Users\vasya\AppData\Roaming\Ethereum\chaindata
I0726 18:44:25.418250 cmd/geth/main.go:309] instance: Geth/1.5.0-unstable/go1.6.2/windows
I0726 18:44:25.418250 ethdb/database.go:82] Allotted 512MB cache and 1024 file handles to C:\Users\vasya\AppData\Roaming\Ethereum\chaindata
I0726 18:44:25.515260 ethdb/database.go:82] Allotted 16MB cache and 16 file handles to C:\Users\vasya\AppData\Roaming\Ethereum\dapp
I0726 18:44:25.523260 eth/backend.go:184] Protocol Versions: [63 62], Network Id: 1
I0726 18:44:25.526261 core/blockchain.go:204] Last header: #1951740 [141104dd…] TD=39544463583721820320
I0726 18:44:25.526261 core/blockchain.go:205] Last block: #1951740 [141104dd…] TD=39544463583721820320
I0726 18:44:25.526261 core/blockchain.go:206] Fast block: #1951740 [141104dd…] TD=39544463583721820320
I0726 18:44:25.527261 eth/handler.go:113] blockchain not empty, fast sync disabled
I0726 18:44:25.528261 p2p/server.go:313] Starting Server
I0726 18:44:27.431451 p2p/discover/udp.go:217] Listening, enode://66c6ad62395a680313b0115023e2f85fd0852b0363ac7bfb83d3d0f4ea51d45fb614bf77741a178eb6bed2f3ad6cf687840045c1ee2976a44af09702e0351b41@0.0.0.0:30303
I0726 18:44:27.432451 p2p/server.go:556] Listening on [::]:30303
I0726 18:44:27.433451 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc
I0726 18:44:47.433451 eth/downloader/downloader.go:307] Block synchronisation started
I0726 18:45:39.155623 eth/handler.go:294] Peer 4331c98bb65c7b14 [eth/63]: timed out DAO fork-check, dropping
I0726 18:46:22.361943 eth/handler.go:294] Peer 4331c98bb65c7b14 [eth/63]: timed out DAO fork-check, dropping
I0726 18:56:11.195821 eth/handler.go:294] Peer 4331c98bb65c7b14 [eth/63]: timed out DAO fork-check, dropping
```
This bug begin after hard fork and i resync chaindata...
https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide#my-transaction-is-not-confirmed
But it not helpd me.

**Comment by luclu** [comment]
The balances on blockchain explorer and your node differ as it is not synced - it's like you are looking into the past with your local node.

Please be patient and let it settle for ~20min (sometimes there are NAT related issues). As soon as it is fully synced compare the blocknumber with [these](http://fork.ethstats.net/) to see if you are on the correct fork.

**Comment by oip90** [comment]
I said the problem has been observed for more than 5 days and on different computers.  Where in mist i can see blocknumber?

**Comment by oip90** [comment]
At this moment (see attach). Somthing going wrong....
![4](https://cloud.githubusercontent.com/assets/6263047/17182428/21b9ea18-542c-11e6-8b50-3bbf433bfb38.png)
![5](https://cloud.githubusercontent.com/assets/6263047/17182429/21bd0554-542c-11e6-9818-a8bf2c1f332f.png)

Have any idea?

**Comment by luclu** [comment]
Judging from the blocknumbers your nodes synced to the non-fork chain.
Please refer to this guide to get your situation resolved: https://github.com/ethereum/mist/issues/1028
I will close this for now, but feel free to ask any questions should you encounter problems during the procedure.

**Comment by oip90** [comment]
Thanks a lot. Guide [https://github.com/ethereum/mist/issues/1028](url) helped. Previous times i'm sync chaindata "Support DAO"
