### ISSUE TITLE
Interface messed up

### ISSUE THREAD

**Issue by enriquefynn** [ethereum/mist#104]
Hello, I installed ubuntu as a VM with a macbook with retina display (that's probably where the bug comes from) and the interface is completely messed up like in the figure above:

<img width="1440" alt="screen shot 2016-01-07 at 19 48 46" src="https://cloud.githubusercontent.com/assets/278786/12179761/fcb0dfb2-b578-11e5-85f1-02c1d91812cf.png">

The mouse also doesn't work properly, I tried with gnome3, unity and dwm, with dwm is more usable but still there's a giant white rectangle sitting in the middle of every screen.

No error is shown in terminal

**Comment by frozeman** [comment]
Never had such an exotic issue. Could you try if you find something of this issue related with [electron](https://github.com/atom/electron), because thats what we are using.

**Comment by winsvega** [comment]
Seems like openGl issues. I had similar when running windows as a VM on Ubuntu.

**Comment by enriquefynn** [comment]
Yes... It's complete crap, running linux vm on a mac. Sorry

**Comment by frozeman** [comment]
I use virtual box and it works fine.
