### ISSUE TITLE
Stuck looking for peers...

### ISSUE THREAD

**Issue by larrysmith1000** [ethereum/mist#1041]
Hi -

I just upgraded from Win 64 7.5 to 8.1.  I selected Hard Fork.  Then I am stuck on entry screen "waiting for peers..."  (I've waited for over an hour).  
![capture](https://cloud.githubusercontent.com/assets/19583370/17162009/f174fea8-5366-11e6-99b8-8ed2ef990554.PNG)

Last sync was on 07/16.  Thoughts?

Is there a way to just open geth to sync to the Hard Fork?  What command do I specify to select the hard fork?

Thanks!

**Comment by larrysmith1000** [comment]
So I ran it in geth without mist:
`geth --support-dao-fork`
and I keep getting
`[eth/63]: timed out DAO fork-check, dropping`

Is this because not enough people have upgraded yet?  geezz its been days.

Any suggestions?  Should I down grade to sync up to 1919999, and then upgrade?

**Comment by martinbuberl** [comment]
I have the same issue as @larrysmith1000 above. Stuck on the entry screen "forever" looking for peers or if I launch the application "0 peers | 1,902,720 | 9 days since last block".

My version is 0.8.1 on OS X.

**Comment by martinbuberl** [comment]
@larrysmith1000 I looked into the log file and it complained that the system time is off by a bit. Synced my system time, closed/opened the Ethereum-Wallet and it's downloading now.

**Comment by larrysmith1000** [comment]
@martinbuberl Thanks, but I tried the system time sync, and I am still have the same issue

**Comment by elsesiy** [comment]
Same issue here, after upgrading to 0.8.1. with the latest geth version running from Terminal the Mist wallet doesn't seem to properly sync the network (Doesn't work standalone either). There're multiple hundreds of `timed out DAO fork-check, dropping` entries in the console and it takes up to 8 hours until the actual block synchronization starts if at all.

**Comment by AlphaQUp717** [comment]
same thing is with my wallet. it has been looking for peers for sometime now and the thing is I have funds going to my wallet from poloniex and it was taking a long time to come in. So I decided maybe it was because my wallet needed an update that maybe the reason why it has not come in. But now I feel I may never get my funds because I cant even get into the wallet because of the whole looking for peers thing...I am a noob at all of this. plz help

**Comment by luclu** [comment]
Due to some windows ntp anomaly you might need to disable and enable the time-sync again [issuecomment-235475578](https://github.com/ethereum/mist/issues/1041#issuecomment-235475578).
I will close this for now, please report if you still encounter this issue.

**Comment by samnet** [comment]
I have this same issue, with Mac, and on the testnet. I have tried resync the time. This did not help. Any other solution(s)?

**Comment by zhenchaochen** [comment]
same here, mac, stuck in 'looking for peers'

**Comment by Drago99** [comment]
Synchronize Your Windows Clock With Internet Time Server

http://www.guidingtech.com/3119/windows-clock-sync/

**Comment by jesobreira** [comment]
Same here. On my node.log I get a lot of:

```
Error: invalid mix digest
##############################
 
WARN [09-12|15:31:19] Synchronisation failed, dropping peer    peer=20c9ad97c081d633 err="retrieved hash chain is invalid"
ERROR[09-12|15:31:28] 
########## BAD BLOCK #########
Chain config: {ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Metropolis: 9223372036854775807 Engine: ethash}

Number: 1657897
Hash: 0x824a47006ed5f0fadc853b28115cbc93ef6862985d3955bfdfd6d1b660be14e1


Error: invalid mix digest
##############################
 
WARN [09-12|15:31:28] Synchronisation failed, dropping peer    peer=6ce05930c72abc63 err="retrieved hash chain is invalid"
ERROR[09-12|15:31:50] 
########## BAD BLOCK #########
Chain config: {ChainID: 3 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 10 EIP158: 10 Metropolis: 9223372036854775807 Engine: ethash}

Number: 1657897
Hash: 0x824a47006ed5f0fadc853b28115cbc93ef6862985d3955bfdfd6d1b660be14e1
```

**Comment by Winglessss** [comment]
This worked for me I synced my clock with internet time after running a virus scan and then deactivating my antivirus.  AVAST

**Comment by DimitriVZR** [comment]
Hi guys, I've noticed that when I put my firewall on  max protection it blocks the ports that GETH needs to sync. So lowering the protection level could help.

**Comment by ekkis** [comment]
I have the same issue with Mist 0.10.0 on OSX 10.11.6.  I've googled till I'm blue in the face, I don't even see any recent articles, nor any solutions.  it's really disappointing that after all this time the software cannot handle its basic necessities.  it's useless, and support in Gitter in basically non-existent.  very disappointing

**Comment by EddieOne** [comment]
For windows 10, search `change time` in the start menu and toggle the time settings off and back on.

![image](https://user-images.githubusercontent.com/1835156/38218272-66343612-368e-11e8-9fac-8c014dfe6a31.png)

**Comment by romanzagorowski** [comment]
Seriously, guys... I just switched from Bitcoin software to Ethereum to check is it worth anything. And I got some splash screen saying "Looking for peers..." for hours. Why the Hell Open Source must always mean some crapy software, please? Is any one testing this "software" before releasing to users, please? I hope the Uninstall option will work...

**Comment by romanzagorowski** [comment]
Oh, boy... This is exactly what I mean. Normal softwar will report to a user in frendly manner if some problem occures instead showing him some crappy splash screen for hours.
BTW. The uninstall process has left some icon on my desktop. Needed to remove it manualy...
