### ISSUE TITLE
I have updated to 0.8.1 AFTER block 1,920,000 and i'm still in the HF blockchain

### ISSUE THREAD

**Issue by vatcave** [ethereum/mist#1045]
I don't get it..how's that even possible?
I thought i was supposed to re-download the whole thing from the beginning.
I have never deleted the "chaindata" folder inside the "Ethereum" folder. 
Just left it untouched and somehow i stayed in the HF chain..

**Comment by vatcave** [comment]
To be more exact i have updated from 0.7.5 to 0.8.1 like 3 hours after the fork occured. I left the downloaded chain as it is. And i can verify from forkstats that i am in the HF side.. How could that be?

**Comment by luclu** [comment]
The point in time at which you updated to `0.8.1` is not as important as the point in time that your client synced past block 1,919,999. If you synced block 1,920,000 using `0.8.1` you are on the HF chain.

**Comment by vatcave** [comment]
awesome, thank you for clearing things out!
