### ISSUE TITLE
Wallet 0.3.7 (Beta 4)

### ISSUE THREAD

**Issue by Maks42** [ethereum/mist#105]

**Comment by Maks42** [comment]
it is the fastest wallet and my account in etherscan, + translation why?
![505587150 2](https://cloud.githubusercontent.com/assets/8115373/12195403/80098804-b629-11e5-85d4-10c958219dc6.png)
![505587527](https://cloud.githubusercontent.com/assets/8115373/12195405/86e25f84-b629-11e5-8177-8b1c48606ddf.png)
![505587612](https://cloud.githubusercontent.com/assets/8115373/12195407/8b276be8-b629-11e5-8109-e278d28ba758.png)
![505587654](https://cloud.githubusercontent.com/assets/8115373/12195409/8eb10936-b629-11e5-903e-8562ef5eb9be.png)

**Comment by frozeman** [comment]
You're on the testnet and you compare that to etherscan.io, which is main net if i'm right

**Comment by Maks42** [comment]
Yes test, but I can't run the main mining. how to run mining major, can I earn etherium on the CPU, and that will be a test of etherium?

**Comment by Maks42** [comment]
if possible, please with pictures, ATO I don't understand I try to start mining

**Comment by frozeman** [comment]
the mining doesn't work on the main net, as mining with a CPU brings you nothing (the difficulty is already to high).

If you want to mine with GPU you need to use a dedicated miner. see here: https://ethereum.gitbooks.io/frontier-guide/content/gpu.html

And you need to be familiar with the command line and probably need to install c++ ethereum

**Comment by Maks42** [comment]
on the graphics card I can't get too, too weak just 512 MB, but I realized I would not be able to mine etherium? yeah and my budget allows me to buy only Tetris(

**Comment by frozeman** [comment]
If you want ether you need to buy them, and thats probably anyway the best decision, except you're planning to create a huge mining farm ;)
