### ISSUE TITLE
Unable to import existing multisig wallet contract on non-fork chain 

### ISSUE THREAD

**Issue by bamos01** [ethereum/mist#1052]
MAC os-

The balance shows in top corner but it is frozen and says "importing" on the wallet contract section

**Comment by luclu** [comment]
Could you kindly fill out this information and upload a screenshot of your GUI.

Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`

**Comment by bamos01** [comment]
Yes- here it is

Version 0.8.1
osx
geth

[image: Screenshot 2016-07-28 18.16.47.png]

**Comment by bamos01** [comment]
closing issue- it worked - it just took a really long time for some reason
