### ISSUE TITLE
No balance

### ISSUE THREAD

**Issue by HolstenSA** [ethereum/mist#1054]
### Hello
Transfers never show up in my wallet
I do not know what the problem is

--------------------------------------------------------
Date	Amount	Transaction
29 Jul, 11:46	0.10020218	0x8968313e0b4e6c60824d83fad1a53d1e00a42743631eac367ab021f3217ca440
29 Jul, 04:23	0.10751910	0x24efaa9e948f9a7168e8efc0afe933090fde0c2042add2bda30e3e17f7e818b4
27 Jul, 15:46	0.22977735	0xd83f2dc3f48056f546a2ee661b177effea725d74f2334201126c6bc42411c045
27 Jul, 00:38	1.01491170	0x65102004c0d85a8add6fc94af8d2e085fbe2af20bb545976357c45cb4095a379

**The Ethereum Blockchain Explorer** 
http://prntscr.com/bza9eg
**Last payouts**
http://prntscr.com/bza8vl
**ethereum wallet**
http://prntscr.com/bza8q5

**Comment by luclu** [comment]
Here is your solution!
>  I want to sync to the HF chain but ended on the non-fork chain; Ether is missing #1028 

Feel free to ask any questions should you get stuck.
