### ISSUE TITLE
Stuck downloading Blocks

### ISSUE THREAD

**Issue by jt888** [ethereum/mist#1055]
Hello I've been trying to open up my wallet for the past week and it always gets stuck at block 1,965,404. I've tried restarting a number of times & reinstalled a few time to with no luck. Any ideas? 

And I'm not the most tech savvy so if you're able & willing to help please feel free to dumb things down as much as possible! ;)

Thanks in advance!!!

&Happy Bday!

#### System information
``````
Version: Ethereum-Wallet-win64-0-8-1
OS & Version: Windows 10, 64bit
Node type: `?
``````

![1](https://cloud.githubusercontent.com/assets/20744307/17272335/9d2be912-5648-11e6-998a-7b652e8206f9.PNG)

![console](https://cloud.githubusercontent.com/assets/20744307/17272339/ab2e3312-5648-11e6-94e3-361e8d60cc7f.PNG)

**Comment by holiman** [comment]
I get the exact same thing. It's not actually stuck loading blocks, but when I eventually start the application,  the Mist UI is grey, and there's the same error in the console. 

![image](https://cloud.githubusercontent.com/assets/142290/17272842/ba3b7cb2-56a1-11e6-827a-a18c7140cce0.png)

I run the release Mist-Linux64-0-8-1 on Ubuntu.

**Comment by altrano** [comment]
Same problem.. Not syncing.

`I0731 09:33:42.864817 eth/handler.go:295] Peer cb556a86069900b8 [eth/63]: timed out DAO fork-check, dropping`

**Comment by luclu** [comment]
Could you kindly upload your `node.log`?
> 
 Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log` 
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by altrano** [comment]
Here is my node.log
[node.log.zip](https://github.com/ethereum/mist/files/392335/node.log.zip)

**Comment by luclu** [comment]
@altrano Thank you, could you please repeat this after letting your Mist settle for about 5min?
The current `node.log` does not yet display any sync related info as the session it logs did just start.

**Comment by luclu** [comment]
@altrano please backup (just rename) the `~/Library/Ethereum/chaindata` folder and retry.
After some minutes pleas upload all `node.log` files (`node.log.1`, etc).

**Comment by altrano** [comment]
Same shit!!

Trying anything and always the same. And now is my 7 months work lost??

It seems it is a connection problem. Before updating from OS X El Capitan to macOS Sierra it always works.

Hopefully ethereal wallet will be supported on macOS Sierra soon. If there a change when I install the wallet for example on linux and import the keystore, have I access to that accounts??

Anyway here are the log files
[logs.zip](https://github.com/ethereum/mist/files/392410/logs.zip)

**Comment by jt888** [comment]
FOr some reason I can't get a .zip to upload, so had to upload here: http://www.megafileupload.com/7gb6/nodelog.zip

Thanks for taking the time to look into this @luclu!

**Comment by altrano** [comment]
Need help... Can i simply restore my accounts with the key files on a new Wallet?

**Comment by luclu** [comment]
Judging from your logs your node (geth) never starts to sync with the network.
Did you try to remove the `~/Library/Ethereum/chaindata` folder as I recommended?

> Need help... Can i simply restore my accounts with the key files on a new Wallet?

You can always just copy the keyfiles over to another computer that works.

**Comment by altrano** [comment]
yes, i try anything, after hours of research, i found out that the problem can be in libc or something, i try to install Xcode, but that helps nothing.

So i must wait until this is fixed, and backup my accounts on another computer.

Thanks for all anyway...

**Comment by luclu** [comment]
> yes, i try anything, after hours of research, i found out that the problem can be in libc or something, i try to install Xcode, but that helps nothing.

@altrano please don't hunt ghosts!

Do one of the following two things:

- use another computer or [virtual-box](https://www.virtualbox.org/) to install a clean copy of [Ethereum-Wallet](https://github.com/ethereum/mist/releases)
- use https://www.myetherwallet.com instead. You will be able to import your keyfiles and redeem your mined ether

**Comment by jt888** [comment]
So I'm still unable to get past block #1,965,404. I was hoping the issue would resolve itself with this newest version of mist (0.8.2), but no luck. It seems like the thing to do is to just delete this all and do a clean install. 

If I do that is anyone able to walk me through the steps? Is it correct that I just need to be sure to keep the  keystore files? What would I need to do to delete everything else? And when I re-install do I just paste the old keystore files accordingly?

Thanks!

**Comment by luclu** [comment]
@jt888 for a start please backup (just rename) the `%APPDATA%/Ethereum/chaindata` folder, retry if you are able to sync the complete chain now.

**Comment by luclu** [comment]
Closed as of inactivity.

**Comment by MorgothCreator** [comment]
The same issue:
runtime: out of memory: cannot allocate 134217728-byte block (1039073280 in use)
fatal error: out of memory.

runtime stack:
runtime.throw(0xc6c852, 0xd)
	C:/go/src/runtime/panic.go:596 +0x7c
runtime.largeAlloc(0x8000000, 0x1c0401, 0x2c)
	C:/go/src/runtime/malloc.go:809 +0xdb
runtime.mallocgc.func1()
	C:/go/src/runtime/malloc.go:702 +0x31
runtime.systemstack(0x1206aa80)
	C:/go/src/runtime/asm_386.s:337 +0x5e
runtime.mstart()
	C:/go/src/runtime/proc.go:1132

Alienware, W10 Proffesional 64Bit, 16GB ram.
