### ISSUE TITLE
Transaction from ethereum wallet contract to external account ended up in lost ethers. 

### ISSUE THREAD

**Issue by wschiedo** [ethereum/mist#1056]
Hello,

My balance in my mist wallet dropped from 62 ethers to 0 but i didn't receive it on my external account at coinbase. I don't now were to start to solve this end i am absolutely a retard in this world. Is there anyone who is able en willing to guide me true the possible solution? I am willing to give a reasanoble fee for the time needed to help me. Looking forward to some reply. 

Kind regards,
Wouter
#### System information

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
```
#### Please check the **already existing** issues to keep duplicates at a minimum.

Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:
- Screenshots
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log` 
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by luclu** [comment]
Please fill out as much info as you can:
> 
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````
>
#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).
>
If possible add the following to your report:
>
- Screenshots
>
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
>
- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log` 
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by wschiedo** [comment]
Hello Luca,

Thx for you're reply.

Previous i had contact with the Coinbase support team, it might give some more insight en is placed below in RED.

Request at Coinbase;
As i told you i am not sure which figure is the Hash (ID).
I am a rooky in virtual valuta languae.

The coinbase adress where its send to is:
0xB3703a893511Ba99F6c80809670e4F7224357902 <file:///send/0xB3703a893511Ba99F6c80809670e4F7224357902 <file:///send/0xB3703a893511Ba99F6c80809670e4F7224357902>>

Maybe this will help:
Block;	1963564 <http://etherscan.io/block/0xfab134169dd2889c314c2b4bf8f51fca01eb4db20c9a3e5b03746fdc2a8a9091 <http://etherscan.io/block/0xfab134169dd2889c314c2b4bf8f51fca01eb4db20c9a3e5b03746fdc2a8a9091>>
 <http://etherscan.io/block/0xfab134169dd2889c314c2b4bf8f51fca01eb4db20c9a3e5b03746fdc2a8a9091 <http://etherscan.io/block/0xfab134169dd2889c314c2b4bf8f51fca01eb4db20c9a3e5b03746fdc2a8a9091>>
0xfab134169dd2889c314c2b4bf8f51fca01eb4d…                              <http://etherscan.io/block/0xfab134169dd2889c314c2b4bf8f51fca01eb4db20c9a3e5b03746fdc2a8a9091 <http://etherscan.io/block/0xfab134169dd2889c314c2b4bf8f51fca01eb4db20c9a3e5b03746fdc2a8a9091>>

Parent Hash: 0xc4e66c9cfa825cc62642aa619d04278ea2a99473a0e27ca35e2ae47ba49da37a <http://etherscan.io/block/0xc4e66c9cfa825cc62642aa619d04278ea2a99473a0e27ca35e2ae47ba49da37a <http://etherscan.io/block/0xc4e66c9cfa825cc62642aa619d04278ea2a99473a0e27ca35e2ae47ba49da37a>>

Or these?:
Block: 1963564 <http://etherscan.io/block/1963564 <http://etherscan.io/block/1963564>>

Parent TX hash: 0x8b2ab26062ed94c4fcdf78d68ea5ce46bdb834142bdd2936a6c3c34d8864098e <http://etherscan.io/tx/0x8b2ab26062ed94c4fcdf78d68ea5ce46bdb834142bdd2936a6c3c34d8864098e <http://etherscan.io/tx/0x8b2ab26062ed94c4fcdf78d68ea5ce46bdb834142bdd2936a6c3c34d8864098e>>

Send from: 0xfc42e1ea240ecf9ecb3b0ed2b6594b0ba40acd5e <http://etherscan.io/address/0xfc42e1ea240ecf9ecb3b0ed2b6594b0ba40acd5e <http://etherscan.io/address/0xfc42e1ea240ecf9ecb3b0ed2b6594b0ba40acd5e>>
Send to: 0xb3703a893511ba99f6c80809670e4f7224357902 <http://etherscan.io/address/0xb3703a893511ba99f6c80809670e4f7224357902 <http://etherscan.io/address/0xb3703a893511ba99f6c80809670e4f7224357902>>

Coinbase Reply:
0xb3703a893511ba99f6c80809670e4f7224357902 does appear to be one of your Coinbase-associated addresses. 
You can confirm this by navigating to https://www.coinbase.com/addresses <https://www.coinbase.com/addresses> and clicking your ETH Wallet. 
However, there does not appear to be any transactions which have gone to that address.

Answers to you're question:
I am using the ethereum mist wallet version 0.8.1
The wallet is installed on a MacBook Pro and is working on OS X El Capitan Version 10.11.6
I don’t know what you mean with this question -> Node type: `eth/geth(default)`




Hopefully this will shed some light on this issue.

Looking forward to you're reply

Kind regards,
Wouter

**Comment by wschiedo** [comment]
Anyone?

**Comment by luclu** [comment]
Thank you Wouter,

In the second screenshot you sent ([this](<img width="618" alt="schermafbeelding 2016-07-31 om 13 46 09" src="https://cloud.githubusercontent.com/assets/20744678/17276323/7334c06e-5726-11e6-97fc-eabfeb7d0231.png">)) the top is missing/cropped. It contains a blue link which is the transaction id in question. 
Please send this one over to coinbase's support.

**Comment by wschiedo** [comment]
Hello luclu,

Do you mean that i have to send the complete adres of the WCDJ link to coinbase? 

Grtz wouter

**Comment by wschiedo** [comment]
Hello luclu,

Do you mean that i have to send the complete adres of the WCDJ link to coinbase?

Grtz wouter

**Comment by luclu** [comment]
> In the second screenshot you sent (this) the top is missing/cropped. It contains a blue link which is the transaction id in question.
Please send this one over to coinbase's support.

Hope that helps!

**Comment by wschiedo** [comment]
Luclu,

Thanks for the reply.
In previous conversations with coinbase i have send the transaction ID in question.

In a short recap, there final conclusion was that they are not able to solve it.

Any thoughts? 

Grtz Wouter

**Comment by luclu** [comment]
hmm, would you mind posting the transaction id here so I can have a second look at your situation?

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
