### ISSUE TITLE
Several transactions appear to fail; trigger all at once upon additional transaction

### ISSUE THREAD

**Issue by brandoncurtis** [ethereum/mist#1057]
#### System information
``````
Version: Geth/v1.4.10-stable-5f55d95a/linux/go1.6.2
OS & Version: Ubuntu 16.04.1
Node type: `geth`
``````
#### Situation
I created a Wallet Contract and attempted to send ether to it from my Etherbase.  I set the transaction slider to several different positions and attempted to send; the transactions showed zero confirmations and disappeared from the Mist GUI within a few minutes.  The transactions did not appear in the blockchain or Mist and I assumed they had failed.

The following day, I attempted additional transactions between the same Etherbase and Wallet Contract.  The initial send (no change to tx fee slider) (nonce 4) went through, but two subsequent transactions (moved the tx fee slider) failed and disappeared as before.  Using `geth attach` I looked at the pending transactions and found the two transactions that had just failed:
``````
  pendingTransactions: [{
      blockHash: null,
      blockNumber: null,
      from: "0x7c468346f38261f26974575595b1ece2636d6c17",
      gas: 122423,
      gasPrice: 16528925619,
      hash: "0x44685b42cc196792012cd45b3a97164fb1de7e0cf5d4bc573461f7f75a5732a9",
      input: "0x",
      nonce: 5,
      to: "0x92fb112698b377023f3d076007b04608c03cf9d0",
      transactionIndex: null,
      value: 4000000000000000000
  }, {
      blockHash: null,
      blockNumber: null,
      from: "0x7c468346f38261f26974575595b1ece2636d6c17",
      gas: 122423,
      gasPrice: 20000000000,
      hash: "0x7713d4af08060e770bc65506b03ae65535134263e217c04db5475a35df712d97",
      input: "0x",
      nonce: 6,
      to: "0x92fb112698b377023f3d076007b04608c03cf9d0",
      transactionIndex: null,
      value: 4000000000000000000
  }],
``````

I also checked txpool.inspect:
``````
txpool
{
  content: {
    pending: {
      0x1c4a10b09f54c2a2601b71e7644124efefd2cd7b: {
        886: [...]
      },
      0x40ce7569d555dbf939e58867be78fd76142df821: {
        12186: [...]
      },
      0x7c468346f38261f26974575595b1ece2636d6c17: {
        5: [...],
        6: [...]
      },
      0x99ac31b82c8b83f50e234db91b863f2601732dd3: {
        0: [...]
      },
      0xb2d9e357b70993184cee01cd7a01a4013ce5df40: {
        68: [...]
      },
      0xea674fdde714fd979de3edf0f56aa9716b898ec8: {
        348364: [...]
      },
      0xed059bc543141c8c93031d545079b3da0233b27f: {
        62830: [...]
      },
      0xf34a762291e2578b79646cbf296abf4f5a242b3d: {
        1897: [...]
      },
      0xfe94da661114033b8bc053681292c73d1ef87408: {
        11: [...]
      }
    },
    queued: {
      0xb5dfdb8dc5459203deb740c9825745bba352e789: {
        2: [...]
      },
      0xb6497945bccf628d897f4e6bdefc684b09c95ce7: {
        106: [...]
      }
    }
  }
``````
I could not determine how to clear the pending transactions, so I restarted `geth`.  After restarting and resyncing, I attempted the same transaction that had just failed.  To my surprise, not only did it succeed (nonce 5), but one of its failed pre-restart brethren (nonce 6) succeeded and two failed transactions from yesterday (nonce 7,8) popped out of nowhere and were also confirmed on the blockchain:
https://live.ether.camp/account/92fb112698b377023F3d076007B04608c03CF9d0
![contract-avalanche](https://cloud.githubusercontent.com/assets/2591290/17275855/a8d26e52-56cb-11e6-93f6-e06f2039176f.png)

I know that nonces allow a series of transactions to be manually sequenced, but I don't understand what's going on here.  Is some sort of nonce collision or mis-sequencing causing some of my transactions to stage somewhere, and they are triggered at some arbitrary time in the future by the success of other transactions that bridge the 'nonce gap'?  If transactions (nonce 7,8) were out there waiting to be triggered in some manner, then why didn't they appear in the blockchain when I sent them yesterday and why didn't they appear as 'pending' or 'queued' when I called `txpool.inspect`?

**Comment by brandoncurtis** [comment]
Upon further research, this has already been reported as ethereum/mist#931.

**Comment by luclu** [comment]
closed as duplicate
