### ISSUE TITLE
Downloading block 832,500 of 840,240.

### ISSUE THREAD

**Issue by dobcrypto** [ethereum/mist#106]
Downloading block 832,500 of 840,240...
And stop on it =(
Win x64.

**Comment by frozeman** [comment]
Please wait, its processing the state

**Comment by dobcrypto** [comment]
Thx... still waiting.

**Comment by dobcrypto** [comment]
Hm... I had wait more then 1.30hour, and nothing... =(

**Comment by frozeman** [comment]
hm, not sure whats happening. It normally would download the state at last. currently without info and the  start the app.

Please restart and try again

**Comment by dobcrypto** [comment]
Restart help me - http://prntscr.com/9ow9pq
