### ISSUE TITLE
Mist Wallet doesn't showing ETC balance in Classic Wallet.

### ISSUE THREAD

**Issue by keuge** [ethereum/mist#1063]
![screenshot-945](https://cloud.githubusercontent.com/assets/7301484/17363627/39853bd6-5984-11e6-9fb7-ec474f0ca253.jpg)
![screenshot-944](https://cloud.githubusercontent.com/assets/7301484/17363628/3cc5e944-5984-11e6-821c-880d448f27a5.jpg)
But i have 1.9 ETC on balance.
http://gastracker.io/addr/0x2c7aa4f686ba09447547c09f17e931f8f86b4553
What's wrong?

**Comment by dejandon** [comment]
i hawe same problem

**Comment by luclu** [comment]
Sorry, we don't support ETC in Mist.
Please head over to https://github.com/ethereumproject/mist for any questions.
