### ISSUE TITLE
Show Error message instead of Blank page on DNS failure

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/mist#1066]
When I enter an URL with a domain that doesn't exist (like www.mistgivesblankpage.com), Mist shows a blank page (see screenshot beelow).

![screenshot 2016-08-04 13 31 28](https://cloud.githubusercontent.com/assets/620959/17400414/ff17f6c2-5a47-11e6-9a4b-8d34e2d9ac74.png)

Instead I would expect to see some kind of DNS error page like how Chrome does:

```
This site can’t be reached

www.mistgivesblankpage.com’s server DNS address could not be found.
Search Google for misty gives blank page
ERR_NAME_NOT_RESOLVED
```
#### System information

```
Version: `0.8.1`
OS & Version: osx
Node type: `geth(default)`
```

**Comment by morelazers** [comment]
I think this might be related to a problem I am having, even though the page does exist (I can visit it in Chrome for example).

Is there any news on this issue?

**Comment by frozeman** [comment]
We currently don't have error page for that case, but it certainly makes sense to add one!

**Comment by frozeman** [comment]
Here is the PR https://github.com/ethereum/mist/pull/1559
