### ISSUE TITLE
i havent upgraded my wallet, still have 8.0 , missing payments

### ISSUE THREAD

**Issue by itredd** [ethereum/mist#1067]
i am missing many incoming payments
i have win 7, mist 8.0
i can though send out ether, but all receiving transaction are missing

**Comment by luclu** [comment]
This means you ended up on the non-fork chain. Don't worry nothing bad happend.
Please install version `0.8.1` and follow the tutorial in this [link](https://github.com/ethereum/mist/releases/tag/0.8.1). You will have to do a full resync though.

I will close this for now as there are many duplicates of this in the issue tracker.
Feel free to search them or come back to me were you in the need of assistance.
