### ISSUE TITLE
Remove Prefork "Main Account" Address

### ISSUE THREAD

**Issue by larrysmith1000** [ethereum/mist#1068]
This is a two part question.

I used the safe split contract to collect my ETC and ETH at two virgin addresses on the two post fork chains.  I have since sold all of my ETC to purchase ETH into my post fork ETH address (I think everyone will eventually do this).  In mist, my pre-fork address is still being recognized as the "Main Account", which now has a zero balance.  Even if I reinstall mist, it reverts back to considering it my "Main Account" (perhaps it considers the oldest account the main account?).  Anyways, here are my questions:

1. Is there any harm/risk in using my prefork address?  If not, I will just move funds back into that address.
2. How do I remove an account?  Should I just remove it from my key store?  I'll keep it backed up somewhere, just in case it entitles me to something later (You never know the way things have been this last month).

Thanks for all your hard work this last month.  It must have been crazy!  You did a great job!

Larry

**Comment by luclu** [comment]
Hi Larry,

1. You will only be able to reuse a prefork address saftely after you split and refund the address in question **on only one chain** and never use it on the other chain again.
2. You are spot on. Keep the backup just in case.
