### ISSUE TITLE
"Red" Wallet contract

### ISSUE THREAD

**Issue by pietdion** [ethereum/mist#1071]
#### System information

```
Version: `0.8.1`
OS & Version: OSX 10.11.5
Node type: `geth 1.4.10`
```

I am running Ehtereum wallet.   Everything appears ok -- updating, balances, send/receive etc. No problems, except for one.

I have a wallet contract that shows "RED" containing ETH.  
When I click on the "RED" wallet contract  it it advises in a red banner 
       "This smart contract has outdated code ... "
When I click on this message I understand it is supposed to take me to a contract that allows me to replace the old contract with a new one.  

However nothing happens.   The program drops me straight back to the main Ethereum wallet screen.

Have tried to kill the wallet contract.   Nothing happens.   Have tried to move funds out of contract, but nothing seems to work.

Any suggestions?

**Comment by frozeman** [comment]
It should bring you to the create wallet page actually. The whole process i described here: https://github.com/ethereum/mist/releases/tag/0.7.6

Can you describe why you can't move funds?

**Comment by pietdion** [comment]
Thanks for your help.

I did try  the steps outlined at 
https://github.com/ethereum/mist/releases/tag/0.7.6

Here are the steps:

1.  Check which wallets are vulnerable
-- ok -- I see my own "Red" wallet

2.  Click the red notification to create a new wallet
-- not ok -- when I click on the red notification I am dropped back in the original main menu

Have tried rebooting etc etc but always get stuck at 2.

**Comment by pietdion** [comment]
Still cannot solve moving funds out of "Red" wallets.
Here is what I see in Mist

![screen shot 2016-08-06 at 3 16 52 pm](https://cloud.githubusercontent.com/assets/6823175/17459390/2088c8ce-5bea-11e6-9481-95ffe7299cb6.png)

When I click on the "Red wallet" I get this

![screen shot 2016-08-06 at 3 17 17 pm](https://cloud.githubusercontent.com/assets/6823175/17459394/4a3cb482-5bea-11e6-80a9-b20208f47418.png)

The above is different from what I should see according to https://github.com/ethereum/mist/releases/tag/0.7.6

When I click on the red banner it just drops me back  to the first screen.

Any  help gratefully appreciated
