### ISSUE TITLE
How to change password of already created account?

### ISSUE THREAD

**Issue by MrBrighty** [ethereum/mist#1074]
#### System information
``````
Version: `0-8-1
OS & Version: windows
Node type: geth(default)
``````

Hello all,

I'm using Main Account. And now I'd like to change password for Main Account in order to improve security level. But I couldn't find a button (f.e. change password for account). Do I have a possibility to do it?

Thanks.

P.S. Hope it's not a duplicate topic - I tried to find similar one.

**Comment by luclu** [comment]
This is possible using the following commands in geth:
```
geth account list
geth account update
```
