### ISSUE TITLE
Tx unconfirmed in Mist wallet/parity

### ISSUE THREAD

**Issue by nerdralph** [ethereum/mist#1075]
Accidentally opened it under the wiki project.
Parity was fully sync'd (25 peers) up to the current block.
https://github.com/ethereum/wiki/issues/86

>
Using the mist wallet bundled with Parity 1.2.3. None of my tx get confirmed, even with maximum gas/tx fee. The highest I could choose for tx fee was .00067641, however the actual fee paid showing when I click on the tx was .00338205, with 105,000 gas used and .03221 eth per million gas.
The tx was a simple eth transfer from one account to another, no added data.
I had tried 3 other transactions previously with lower tx fees and none of them completed either.
>
p.s. I meant to open this against mist, and don't see any way of deleting it so I'll open an issue under mist and link to this.

**Comment by luclu** [comment]
Hi @nerdralph, could you kindly post a link to the download?

**Comment by nerdralph** [comment]
@luclu Here's the package I installed:
https://github.com/ethcore/parity/releases/download/v1.2.3/parity-1.2.3-install-win64.exe

**Comment by oktaryn** [comment]
I have the same issue. I can't send any ETH from my Parity wallet. Transactions don't get confirmed.

**Comment by luclu** [comment]
Please post this issue against [parity's issue-tracker](https://github.com/ethereum/mist/issues/1075) as Mist currently doesn't officially support parity as a backend.
I will subscribe to that issue to stay in the loop, though I will close this one for now.
