### ISSUE TITLE
Use Multi Signature Account as Mist account

### ISSUE THREAD

**Issue by anrodon** [ethereum/mist#1076]
Hey there,
I need to use a multi signature account to execute transactions in Mist, and I can't (or I don't find how to do it). That would be a really good enhancement to the browser.

If the feature exists, would be awesome to have documentation about it.

**Comment by luclu** [comment]
@anrodon please try the contract wallet. You will be able to set daylimits and n-of-m multisig for transactions.

**Comment by anrodon** [comment]
I'm using a multi signature account like the one you can initialise with the Ethereum Wallet. Is that what you're saying?

**Comment by brandoncurtis** [comment]
@anrodon, Mist has a Wallet Contract that you can deploy with multiple owners, daily withdrawal limits, and an m-of-n multisig confirmation structure.  I've started collecting some information about this multisig wallet contract here: https://github.com/ethereum/mist/wiki/Wallet-Contract

Is this what you're looking for?  Comments, corrections, and contributions appreciated!
