### ISSUE TITLE
Local Development: Connecting A local Test Node - How ?

### ISSUE THREAD

**Issue by hookercookerman** [ethereum/mist#1079]
#### System information
``````
Version: `0.8.0` Mist Beta
OS & Version: osx
Node type: `geth(default)`
``````
One is doing to some development on a Dapp and I wish to use my own local testnet (geth) and connect it to Mist; seems like a thing that should be easy and already done. It seems like it always wants to start its own node

however I have searched the web for the answer and there does not seem to be one.

I have tried sym linking the geth.ipc however that does not work (the only solution currently on the web)

Any suggestions would be most welcome. What not have normally posted here but it seems like no one knows the answer to this one; Thanks

**Comment by luclu** [comment]
Please consider the [Readme.md](https://github.com/ethereum/mist/blob/develop/README.md) and Mist's as well as geth's `--help`.

Start geth with the appropriate flags for `datadir, network-id`, etc and let Mist connect to it. Should you need to change the IPC-path you will have to specify it for both. Also it is possible to pass those flags to geth via Mist.

**Comment by hookercookerman** [comment]
@luclu thanks for reply; in a nut shell I did not want to start Mist via electron etc. kind of wanted preferences for a private network in UI itself. But I can just symlink to a running geth node via ipc, and actually putting it in the correct location not like I was doing previously :man: :gun: so one convinced themselves it did not work, and actually further investigation in the mist code itself I can see it will look for geth.ipc first. thanks

**Comment by lyricalpolymath** [comment]
@hookercookerman 
found the solution to connect Mist to a local testNet on Mac.

assuming you have already created a localTest net and run it
or that you have simply done
`geth --dev`

You can now run MIST from the command line like this
**(remember to specify the right path)**

`open -a /Applications/Mist.app --args --rpc /path/to/geth.ipc`

if you have started geth with the --dev flag
at the end of the geth initialization you will have a line stating where the ipc can be found; something like this:
`IPC endpoint opened: /var/folders/y1/jynwfrwj411bxck8whqgcbr00000gq/T/ethereum_dev_mode/geth.ipc`

then your the command line to have MIST connect to the local network is
```
open -a /Applications/Mist.app --args --rpc /var/folders/y1/jynwfrwj411bxck8whqgcbr00000gq/T/ethereum_dev_mode/geth.ipc
```
