### ISSUE TITLE
Etherbase adress changes... How it can be?

### ISSUE THREAD

**Issue by dobcrypto** [ethereum/mist#108]
After fist run Ethereum-Wallet-win32-x64-0-3-7 I had skip synchronization and create Etherbase Account and wallet give me adress 0x16d7f78b1...
http://prntscr.com/9owrzt

I had change node to Eth, wait the full synch and my Etherbase Account changes to 0x00f0...
http://prntscr.com/9owrlj
Ho it can be?

I had alredy send 0.25939672 Ether to my first Etherbase Account 0x16d7f78b1... and now I lost it?
How do I return the first address in my wallet?

**Comment by dobcrypto** [comment]
I am undestand, on each node different adress...

**Comment by frozeman** [comment]
Yes they both have different key stores.

Please note, that `eth` is not fully tested with so be aware, but thanks for trying it!

**Comment by dobcrypto** [comment]
Only eth node are good full synch on my PC.
Geth don't wont to synch =( 
Don't know why...
