### ISSUE TITLE
"Deposit Bitcoin" while on classic fork buys ETH instead of ETC

### ISSUE THREAD

**Issue by weissjeffm** [ethereum/mist#1080]
#### System information
``````
Version: `0.8.1`
OS & Version: Fedora 23
Node type: `eth/geth(default)`
``````
#### How to reproduce
When starting EthereumWallet choose the classic fork (do not support DAO fork). Then when the sync is done and wallet starts choose "Deposit bitcoin". The shapeshift.io page that comes up is actually buying ETH, not ETC, so whatever a new user buys there will never show up in his wallet.

**Comment by luclu** [comment]
Sorry, we don't support ETC in Mist.
Please head over to https://github.com/ethereumproject/mist for any questions.

**Comment by weissjeffm** [comment]
You don't have to support ETC, just disable the button when on the "don't support DAO" fork.

**Comment by luclu** [comment]
The next version will ship without the "don't support DAO" option.

**Comment by weissjeffm** [comment]
:+1:
