### ISSUE TITLE
Ether not showing up in wallet?

### ISSUE THREAD

**Issue by chaddybox026** [ethereum/mist#1081]
#### System information
``````
Version: `0.8.1`
OS & Version: Windows 8.1 Pro
Node type: `geth(default)`
``````
I recently sent 0.005 btc to my ether wallet through Shapeshift.io and it shows on etherscan that the ether has been recieved.

![etherscan](https://cloud.githubusercontent.com/assets/17581094/17564497/16f50144-5ef9-11e6-8462-0e105c767ae8.PNG)

But the ether has not shown up in my wallet.

![mist](https://cloud.githubusercontent.com/assets/17581094/17564486/0fbcf094-5ef9-11e6-9079-e9aac83aead5.PNG)

Here is the most recent node.log.

[node.zip](https://github.com/ethereum/mist/files/411763/node.zip)

Any help will be thanked.

Chad

**Comment by chaddybox026** [comment]
accidental duplicate.

please close

**Comment by GUYBER71** [comment]
i hav ethe same problem 27 eth lost !! we need help here !!
