### ISSUE TITLE
Can't compile contracts using parity + memleak

### ISSUE THREAD

**Issue by D-Nice** [ethereum/mist#1082]
#### System information

```
Version: `0.7.6-0.8.1`
OS & Version: Windows 7 64-bit SP1
Node type: `geth(default) using parity in geth mode`
```

The ethereum wallet, both standalone and the one included with parity, does not seem to be able to deploy contracts. It returns an error indicating there's not enough ether in the account, even though there is plenty, to estimate gas costs. Even trying to deploy it by force, and manually enter a maximum gas limit, deployment fails, indicating incorrect account password, even though the account password is indeed correct. It has no issue deploying bytecode using parity and the same accounts.
- Screenshots
  ![walletbug](https://cloud.githubusercontent.com/assets/2888248/17569878/16780c2e-5f18-11e6-9804-4f576f1faabb.png)
  ![walletlog](https://cloud.githubusercontent.com/assets/2888248/17569895/21bb0014-5f18-11e6-9cc6-584e9b1c77fe.png)

**Comment by D-Nice** [comment]
Hmm, I left the wallet running (0.7.6) after taking those screenshots, and ended up with a major memory leak: 

![walletmemleak](https://cloud.githubusercontent.com/assets/2888248/17571656/1f1f49f8-5f1f-11e6-9547-626b924bdaf4.png)

**Comment by luclu** [comment]
@D-Nice could you kindly cross post this to parity's repo?

**Comment by CyberNano** [comment]
I am also having the same issue. However I could not compile contracts in parity when using the http://localhost:8080 that parity provides either. It could be an issue with Parity.

**Comment by evertonfraga** [comment]
Probably fixed.
