### ISSUE TITLE
Broken wallet adress

### ISSUE THREAD

**Issue by gks84** [ethereum/mist#1084]
from July 19, the wallet does not come ethereum. Transaction confirmed, but the wallet is empty. How to be?

#### System information
``````
Version: `0.8.1`
OS & Version: windows 7 x64
Node type: `geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log` 
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by luclu** [comment]
Please have a look at this guide:
>  I want to sync to the HF chain but ended on the non-fork chain; Ether is missing #1028 

You might have ended up on the non-fork chain after the recent Hardfork.

**Comment by gks84** [comment]
Thanks
