### ISSUE TITLE
Downloading block 74,761 of 444,484.....forever

### ISSUE THREAD

**Issue by casslechat** [ethereum/mist#109]
Hi there,

Every time I go to install Ethereum, the wallet gets stalled on download the blocks at 74, 761. Any clues as to how I can fix this? :)

Thanks!

**Comment by frozeman** [comment]
It could be that you don't have peers or can't connect right. Normally it should work.
See this issue here #106

**Comment by obscuren** [comment]
@casslechat running windows?

**Comment by atonra7** [comment]
same problem (eth). 
geth - all ok.

**Comment by casslechat** [comment]
Running Windows, yes.

Sent from my Sony Xperia™ smartphone

---- Jeffrey Wilcke wrote ----

**Comment by casslechat** [comment]
Restarting doesn't help. Seen any other tips?

Sent from my Sony Xperia™ smartphone

---- Fabian Vogelsteller wrote ----

**Comment by 5chdn** [comment]
well first hint: mist is just a 'browser', a frontend, and can't technically get stuck on any block, only the client in the back can.

what backend client are you using? geth or eth? if you have trouble with eth, try to switch to geth or vice versa.

**Comment by casslechat** [comment]
It's the wallet client.

Sent from my Sony Xperia™ smartphone

---- Afri Schoedon wrote ----

**Comment by frozeman** [comment]
Please run the `wallet/resources/nodes/geth/geth.exe` in the command line tool and see what errors your get.

**Comment by Bubleek** [comment]
Yesterday in the database Wallet download process is interrupted several times on different blocks. In the end, I realized that this is likely to occur due to the darkening of the screen to save the laptop battery. Restarting wallet helped, if not give fire a low-power mode. OS windows7x64.

**Comment by luclu** [comment]
Please update to 0.7.4. and check if this issue still occures. Please ping me back on this!
As geth 1.4.4 (bundled) should have fixed this I will close for now.

**Comment by artyma** [comment]
The same issue. Mist wallet freezes downloading blocks on many occasions. I use the latest release for Windows 64bit.

Any help?

**Comment by ArthurvdMolen** [comment]
I have same issue, stalled at  94,435 of 100,925, reinstalled software, same issue...
