### ISSUE TITLE
Account do not want to be created

### ISSUE THREAD

**Issue by Nikky45** [ethereum/mist#1095]
Hi everyone,

I have two issues. 
1) I cant create an account in my wallet, downloaded from here. I do everything what the programm says, like "enter a password" and "reenter a password". It only shows "creating an account, and then just nothing, it just says "please, create an account".
2) It do not want to download chains and blocks. Every time I try to reload it, it just stops.

Thanks.

**Comment by luclu** [comment]
Hi @Nikky45, please provide as much information as you can dechipher:
> #### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````
>
#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).
>
If possible add the following to your report:
>
- Screenshots
>
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
>
- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log` 
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by chevdor** [comment]
Same issue here but there is no major issue.
What seems to happen is that the 'Creating account' popup stays displayed forever.
If you kill Mist and restart it, you will see that the new account has been created.
