### ISSUE TITLE
Method eth_sendTransaction is not allowed

### ISSUE THREAD

**Issue by shubrich76** [ethereum/mist#1096]
#### System information
``````
Version: `0.8.1`
OS & Version:osx el capi 10.11.5
Node type: `geth 1.4.10

`
``````

I have checked the known issues with this and I can't seem to find a thread on it. Also, it says my password is wrong and when I close the transaction window the above error message comes up. I cannot send my ETH! Please help!

I know my password is correct beyond a shadow of a doubt.

Here is my node log file

[node.log.zip](https://github.com/ethereum/mist/files/421169/node.log.zip)

**Comment by kmajor** [comment]
same exact problem...

**Comment by vandenbergmp** [comment]
Having this problem as well. Node 1.6.0

**Comment by ondratra** [comment]
Any reason why this ticket is closed without explanation of what was actuall problem?
