### ISSUE TITLE
Wallet 0.3.8 (Beta 5) doesn't open on OSX 10.11.2

### ISSUE THREAD

**Issue by frewsxcv** [ethereum/mist#110]
Double clicking shows the logo, then it disappears and nothing happens. I also tried this:

```
coreyf@frewbook-pro /A/E/C/MacOS> ./Electron
CONNECT to IPC PATH: /Users/coreyf/Library/Ethereum/geth.ipc
NODECONNECTOR ERROR { [Error: connect ENOENT /Users/coreyf/Library/Ethereum/geth.ipc]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '/Users/coreyf/Library/Ethereum/geth.ipc' }
Node type:  geth
Network:  main
Start node from /Applications/Ethereum-Wallet.app/Contents/Resources/node/geth/geth
Stopping nodes...
Starting geth node...
UNCAUGHT EXCEPTION [Error: This socket is closed.]
Stopping nodes...
```

**Comment by frozeman** [comment]
Hm, something seems wrong with the node, not starting or so.

Could you open the package contents of the app and go to `Contents/Resources/node/geth` and start the `geth` binary from the terminal?

**Comment by frewsxcv** [comment]
```
coreyf@frewbook-pro /A/E/C/R/n/geth> ./geth
dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /Applications/Ethereum-Wallet.app/Contents/Resources/node/geth/./geth
  Reason: image not found
fish: './geth' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by frozeman** [comment]
There you go, gmp is missing.
@obscuren @tgerring didn't we want to remove that as dependency? Is is it removed in the latest 1.3.3?

**Comment by frewsxcv** [comment]
> There you go, gmp is missing.

At the very least, the user should be prompted to install it if it's something that the user is expected to have installed

**Comment by frozeman** [comment]
I understand, but its normally never a problem and an edgecase. As far as i understood we rove it as a dependency anyway

**Comment by frewsxcv** [comment]
:+1:

**Comment by gonchs** [comment]
I'm getting the same (gmp) error on v0.3.8, OSX 10.11.2

**Comment by frozeman** [comment]
This dependency will be removed in the future

**Comment by frewsxcv** [comment]
Wouldn't it be appropriate to leave this open until it's fixed?

**Comment by frozeman** [comment]
Its fixed in go develop, so will be merged with the next feature release (not the homestead one).

If i keep it open, i forget to close them later and we will stack up issues, so i rather close them when they are technically resolved. Google still finds them, even if closed..

**Comment by ankushnarula** [comment]
I can't open the ethereum-wallet.app binary for the same reason.  Is there a nightly build?  Thx

**Comment by frozeman** [comment]
Your problem is `Library not loaded: /usr/local/lib/libgmp.10.dyli` i guess

**Comment by ankushnarula** [comment]
Yes @frozeman - exactly

**Comment by frozeman** [comment]
This will be fixed in future versions (AFTER homestead release) of geth
