### ISSUE TITLE
Contract providers should be able to customize the UI

### ISSUE THREAD

**Issue by phiferd** [ethereum/mist#1102]
An auto-generate UI is fine for simple contracts, but it would be nice the the contract creator could also provide a more user friendly UI to be rendered within the ethereum wallet.  Even simple hints (such as the order or the grouping of functions) would be helpful.  

I recognize that having a full webpage (including importing content from external sites) would be a security risk, but I'm wondering if there is a safe way to provide some markup or hints.  Also, the user should have the option to revert to the auto-generated UI at any time.

Here's the flow I'm thinking of:

1: user imports the contract using address and interface
2: user has an option on the contract page to attach a UI, which allows them to paste in a snippet provided by the contract owner.
3: the updated UI shows, but the user has an option to revert to the auto-generated one.
4: All actions take through the new UI still trigger the same confirmation windows.  

Here's a bare bones example of a markup of a hypothetical contract with function "BuyTokens", "SellTokens", "VoteOnProposal", "PropseNewProject", "ChangeMyVote":

ICO Functions: [BuyTokens, SellTokens]
Voting: [VoteOnProposal, PropseNewProject, ChangeMyVote]

Note that the markup would not allow an adversary to wire the "ProposeNewProject" to a different function, like "BuyTokens", or hardcode any function parameters.

**Comment by phiferd** [comment]
Oh, and I should include customization of the layout for all of the public read-only values that a contract might expose.  Right now, I'm not sure how the ordering is controlled, but they seem to be in a random order.

**Comment by alexvandesande** [comment]
That's the purpose of the Mist browser: we want to allow contract providers to offer total customisation, including their own html, javascript and css.

**Comment by phiferd** [comment]
ok.  Sorry, I missed that.  I thought Ethereum Wallet was just also called Mist.  Maybe a few sentences on the difference might help clarify things.  I get that you aren't at v1 yet, but you'll probably keep getting this question over and over.  (either that, or I'm just slower than everyone else.)
