### ISSUE TITLE
Can't connect to Node

### ISSUE THREAD

**Issue by qauntumspirit** [ethereum/mist#1103]
![ethereum node error](https://cloud.githubusercontent.com/assets/21143276/17831889/165a78ac-66ee-11e6-8b10-8e28d1bc059d.JPG)

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log` 
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by luclu** [comment]
@qauntumspirit please fill out as much information as you can decipher.

**Comment by qauntumspirit** [comment]
What information do you require?

**Comment by luclu** [comment]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log` 
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by qauntumspirit** [comment]
There are four files labelled node.log.0, node.log.1, node.log.2, node.log.3, node.log.3, node.log.4. Which one do I upload?

**Comment by luclu** [comment]
The 'nose.log.0' should suffice.

**Comment by qauntumspirit** [comment]
[node.log.0.zip](https://github.com/ethereum/mist/files/450124/node.log.0.zip)

**Comment by luclu** [comment]
Are there any other `node.log.X` files?
Also I need the information I requested before. At least the system information block.

**Comment by qauntumspirit** [comment]
[node.log.0.zip](https://github.com/ethereum/mist/files/453411/node.log.0.zip)
[node.log.1.zip](https://github.com/ethereum/mist/files/453410/node.log.1.zip)
[node.log.2.zip](https://github.com/ethereum/mist/files/453409/node.log.2.zip)
[node.log.3.zip](https://github.com/ethereum/mist/files/453408/node.log.3.zip)
[node.log.4.zip](https://github.com/ethereum/mist/files/453407/node.log.4.zip)

What other information do you need?

**Comment by luclu** [comment]
I appended the logs content to your comment.
Judging from the error message you geth can't recover from a database corruption which necessitates you to reset the database.
You can do this by ether issuing the following command or by manually removing this folder:
 -  run `geth removedb` or
 -  remove `%APPDATA%\Ethereum\chaindata`

**Comment by rivaderci88** [comment]
How is this ever going to become mainstream, when I want to access my "Wallet" and I get a series of numbers and letters telling me the "node cannot be found."

It's incredibly frustrating to feel as though you have to have a programming background to participate in cryptocurrency.  It's been 3 days since I can access my wallet and I don't understand any of the instructions on how to "fix" this issue 

Node type: geth
Network: main
Platform: darwin (Architecure x64)

...INFO [08-19|16:04:09] Starting peer-to-peer node instance=Geth/v1.6.0-stable-facc47cb/darwin-amd64/go1.8.1
INFO [08-19|16:04:09] Allocated cache and file handles database=/Users/robertriva/Library/Ethereum/geth/chaindata cache=1024 handles=1024

**Comment by mcna72** [comment]
I agree! 
There is now real fix to solve this problem. The wallet will not start so you cannot turn back the settings from test network to main network. Why did they put the 'test network' option in the menu if it makes the wallet crash!?
