### ISSUE TITLE
Hibernating while synching results in private net test transactions being applied to Frontier

### ISSUE THREAD

**Issue by uc-one** [ethereum/mist#1105]
#### System information
``````
Version:  Ethereum wallet win64-0-8-1, Geth/v1.4.11-stable/windows/go1.6.2
OS & Version: windows 10 x64
Node type: geth 
``````
#### 

Firstly. apologies if this is a duplicate. I did perform a search, but was unable to get any hits using the keywords from the title above.

Issue
====
Restarting the OS after the geth node connected to the Frontier network failed to resume from a forced OS hibernation, the Ethereum Wallet client displayed test transactions that had been originally created and confirmed on a private test network. Consequently the geth node passed these test transactions to the Frontier network where the transactions were confirmed.

What happened?  How is this transaction transference possible?  My understanding is that a private net blockchain and incumbent transactions are permanently sand boxed from any other blockchain network.

Details
====
During slow syncing of a new wallet with a new account, the host computer OS running a Frontier network geth node went into hibernation. Reawakening the OS the geth node blockchain syncing refused to resume.  The Ethereum wallet client continued to run.

Attempting to re-engage blockchain syncing, the Frontier network geth node was restarted reusing the command "geth console".  Syncing did not restart (see log extract below).  The named pipe \\\\.\\pipe\\geth.ipc appeared to unresponsive which prevented the node syncing. The Ethereum Wallet client would also not start, reporting "Fatal: Could not open database: The process cannot access the file because it is being used by another process."

Once the OS was restarted, geth was restarted successfully, where blockchain syncing resumed.  The Ethereum Wallet client connected to the Frontier network geth node. The client now mysteriously displayed some recent test transactions as unconfirmed. These test transactions had been previously and successfully processed in a private net.  

The transactions were subsequently confirmed by the Frontier network which is a surprise as none of the test wallets and test accounts are present in the Frontier network. These transactions are presumably now permanently part of Frontier network's blockchain.

Geth console extract when not syncing:
======================
C:\Users\xxxx\Desktop\apps\geth-64-latest>geth console
I0821 20:20:44.381412 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to C:\Users\xxxx\AppData\Roaming\Ethereum\chaindata
I0821 20:20:45.006430 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------
I0821 20:20:45.006430 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0821 20:20:45.006430 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0821 20:20:45.006430 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0821 20:20:45.006430 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0821 20:20:45.022057 ethdb/database.go:169] closed db:C:\Users\xxxx\AppData\Roaming\Ethereum\chaindata
I0821 20:20:45.037664 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to C:\Users\xxxx\AppData\Roaming\Ethereum\chaindata
I0821 20:20:45.568920 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to C:\Users\xxxx\AppData\Roaming\Ethereum\dapp
I0821 20:20:45.615812 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0821 20:20:45.615812 eth/backend.go:201] Blockchain DB Version: 3
I0821 20:20:45.615812 core/blockchain.go:206] Last header: #2108996 [5a832a40.] TD=50294305992059596152
I0821 20:20:45.615812 core/blockchain.go:207] Last block: #2108996 [5a832a40.] TD=50294305992059596152
I0821 20:20:45.615812 core/blockchain.go:208] Fast block: #2108996 [5a832a40.] TD=50294305992059596152
I0821 20:20:45.631435 p2p/server.go:313] Starting Server

NOTE: the connection to the ipcpath was not established in the log

Private test net
=========
The private test net to which the test transactions belong was setup between two win10 PCs on a local class C subnet, each PC running a geth node and the Ethereum wallet client.  Both nodes were set up as peers. One node was nominated as the miner and was activated to mine Wallet Contract and Token transactions.  It is these transactions that then were "transferred" to the Frontier network as described above. 

The private net geth nodes were configured as:
geth --networkid "999999" --identity "TestNode1" --genesis C:\Users\xxxx\Desktop\projects\TestNet1\CustomGenesis.json --datadir "C:\Users\xxxx\Desktop\projects\TestNet1\TestChain1" --nodiscover --port "30301" console
... and...
geth --networkid "999999" --identity "TestNode2" --genesis C:\Users\xxxx\Desktop\projects\TestNet1\CustomGenesis.json --datadir "C:\Users\xxxx\Desktop\projects\TestNet1\TestChain2" --nodiscover --port "30302" console

Both used the same CustomGenesis.json, which referenced the main account on TestNode1.

**Comment by luclu** [comment]
@uc-one please excuse my late reply.
As this issue is geth related could you kindly reopen it on [geth's issue tracker](https://github.com/ethereum/go-ethereum)?
I will close this one for now.
