### ISSUE TITLE
Etherum node connection error - sync issues

### ISSUE THREAD

**Issue by mtdr66** [ethereum/mist#1106]
#### System information
``````
Version: `0.8.1`
OS & Version: windows 10
Node type: `eth/geth(default)`
``````

After trying to start the wallet, it stopped syncing after reaching final stages of the progress bar.
After that I received the message in the screenshot and I cannot do anything else than close the wallet and repeat the process with the same results.

What can I do to fix the issue and access my wallet again?

**Comment by luclu** [comment]
@mtdr66 your screenshot didn't seem to make it to github. Could you please upload it or post its message?
Could you also please upload your logs located under `%APPDATA%\Mist` as described [here](https://github.com/ethereum/mist/issues/new)?

**Comment by luclu** [comment]
Closed as of inactivity.
