### ISSUE TITLE
Missing account in keystore folder

### ISSUE THREAD

**Issue by allmails888** [ethereum/mist#1107]
Hi,

I switched to using parity after fork to run mist wallet and created a new account. However i noticed in the keystore folder, this new account is not there hence i cannot back it up. When i run mist using geth, i suddenly do not see this account just today which gave me a fright. Only running it via parity do i see this account again. How can i backup this account keys if it is not found in the keystore folder? 

edit - I tried creating another new account (via parity) and the keystore of this new account cannot be found in the keystore folder. Only the accounts created via geth are there. Something about mist and parity i believe is the issue. This is highly dangerous as ppl may not check and count key files when backing up just the keystore as a folder - if they reinstall their pc o/s later or install parity/mist on another pc, they may find missing accounts later after restoring from their keystore folder.

I am also getting panic errors in parity 1.3.0 whenever i launch mist wallet 0.8.1 and my mist wallet cannot connect to any nodes for the past week. I am trying to use parity 1.2.4 now but it seems to be re-downloading the entire blockchain again. fingers crossed
#### System information

```
Version: `0.0.0`
OS & Version: windows 10
Node type: `eth 1.3.0 /geth(1.4.11)`
```

**Comment by allmails888** [comment]
realized when using parity to run mist, it looks up earlier keystore accounts from /ethereum/keystore folder and stores those in the .parity/keys folder. however when you re-run using geth, mist does not look at this parity/key folder hence will miss out any new keys created when used with parity. I think to be consistent, when running mist via geth, mist should also copy new keys from parity folder over to ethereum/keystore folder to be consistent and prevent ppl from missing out keystores when performing backups.

**Comment by islandBilly** [comment]
I am running Mist 0.8.9 and geth v1.5.5-stable-ff07d548/linux/go1.7.4
I created a second account in Mist, but cannot see it when I go to the geth console, and nodejs scripts using web3 are unable to use the account. It is not in the keystore. Perhaps Mist stores its accounts and keys in a sql database? Anyway, it should write them into the keystore too, don't you think?

**Comment by evertonfraga** [comment]
We have no plans to manipulate Keystores from directory to directory. 
It could be implemented by go-ethereum, though.
