### ISSUE TITLE
Unable to view keystore folder from menu

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/mist#1111]
I saw some reports of that and it happens to me as well. I'm filing here to keep track of it.

start and go to menu -> accounts -> backup -> accounts.

#### System information
``````
Version: `0.8.1`
OS & Version: osx
Node type: `geth`
``````

**Comment by luclu** [comment]
Ev, is this related to https://github.com/ethereum/mist/issues/1100?

**Comment by evertonfraga** [comment]
@luclu possibly. I'll close it, didn't see #1100.
