### ISSUE TITLE
DAO fork-check dropping, Ethereum Wallet wont start syncing

### ISSUE THREAD

**Issue by chalachala** [ethereum/mist#1112]
OSX El Capitan 10.10.5
``````
Version: 0.8.2 and 0.8.1

Node type: `geth 1.4.10 (Go)
``````
DAO FORK CHECK DROPPING..... in the log

I get the window that says DOWNLOADING BLOCKS but then it never actually starts to download. Was hoping the new 0.8.2 version would fix this but same problem persists with both .8.1 and .8.2

Been trying now for 2 days  but still same block 2,124.030

- 
![screen shot 2016-08-25 at 6 21 36 am](https://cloud.githubusercontent.com/assets/18206874/17955713/cfb57008-6a8c-11e6-9506-1d3a46581cd3.png)

![screen shot 2016-08-27 at 6 35 49 am](https://cloud.githubusercontent.com/assets/18206874/18032073/1f5f420a-6d03-11e6-8593-1e45bbceaf72.png)

**Comment by doppio** [comment]
Can you attach a log?

**Comment by chalachala** [comment]
how do I do that?

**Comment by chalachala** [comment]
![screen shot 2016-08-27 at 6 35 49 am](https://cloud.githubusercontent.com/assets/18206874/18024936/a14701e2-6c20-11e6-8e37-da0ae4633219.png)

**Comment by evertonfraga** [comment]
Go to Develop > Logs, if I recall. i'm AFK right now

**Comment by chalachala** [comment]
just posted it

**Comment by chalachala** [comment]
DAO fork check dropping.....

**Comment by doppio** [comment]
@chalachala, I think you just need to download the latest version of the wallet.

**Comment by chalachala** [comment]
Im using 0.8.2

**Comment by chalachala** [comment]
I see now others have posted the same problem with DAO FORK CHECK DROPPING but it seems no fix has been made yet.  Anyone help??

**Comment by chalachala** [comment]
is anyone looking at this?  Even an acknowledgement that you are aware of the problem and working on it would do wonders for my nerves.

**Comment by islander777** [comment]
I cannot believe noone from EF is trying to fix this huge issue...

Chalachala, Did you have any luck fixing this issue? I have excactly same issue in Win10 64. Spent few hours in google, tried every possible fix I could find - nothing works. Everything worked perfectly in 0.8.1... Mist wallet won't sync now, everything stuck at block 2,058,533. Really hope someone is working on a fix. the Mist wallet is unusable as is :(

**Comment by chalachala** [comment]
no nothing yet.  Im quite frustrated

**Comment by islander777** [comment]
Ok, it looks like I found a solution which worked for me. I'll post it in case others having same issues.

From this discussion https://github.com/ethereum/mist/issues/1036 this post helped me:

> **usukan** commented 4 days ago
> To fix this I deleted my "chaindata" folder - and did a complete resync of the blockchain. The full sync was faster than the catchup syn taking about 2 hrs. I suspect the structure of the chaindata file has changed over time and on old chaindata there is some conflict with the latest wallets.
> I have resynced all my wallets now and syncs are fast and without issues in 0.8.2 Ethereum Wallet
> Be sure to ONLY delete the "chaindata" folder - and always have a backup of your "keystore" folder.

So I deleted my "Chaindata" folder in C:\Users\"your username"\AppData\Roaming\Ethereum
 and then reinstalled/started Mist 0.8.2. After about 8-10 minutes of nothingness it started to resync very fast (faster than ever!). The full new blockchain downloaded in less than 3 hours and everything appears to work normal so far.
**As mentioned above - make sure you don't delete (and do backup!) your ''keystore'' folder.**

Indeed it looks like the structure of the chaindata file has changed and it conflicts with the latest wallets.
The old chaindata folder was >17Gb before I deleted it. The new downloaded chaindata folder is only less than 7Gb  .
 
I'm surprised noone from official Ethereum developers/foundation has officially published this info/warning, as it appears to be a huge problem, especially for new inexperienced users. When I googled this issue it looks like many people experience the same/or very similar tech issues, after the release of new wallet. We can't expect mass adoption, while issues like this exist. Releasing new version of the wallet without proper and thorough testing is very unwise. Again, it's not just a few small bugs, it's a huge tech issue which makes the wallet 100% unusable for many users.

**Comment by chalachala** [comment]
islander777 thank you for posting this.  One question I am confused on.  One post says to just delete the chain data folder but then another post says to completely re-install 0.8.2.  Which one did you do?

**Comment by chalachala** [comment]
hi


So when I open 0.8.2 and go to Accounts - Backup - Accounts, I see the
Chain Data folder.


Should I just delete that from there and re-launch??

**Comment by islander777** [comment]
Chalachala,

Yes, 
1. Start your Mist and go to **Accounts -> Backup.** (to be safe I would copy/backup your "keystore" folder)
2. From there you can delete (or just rename it to something else) your "**chaindata**" folder.
3. **Re-launch Mist**. (ignore my post about reinstalling it - it looks like it's not required)
4. The Mist will create new **chaindata** folder and should start syncing and downloading full blockchain from scratch. 
Make sure you don't turn off your computer for the next few hours. That's it. Well at least it solved my issues.

Just remember - that losing your "keystore" folder = losing your accounts and money - Always back it up to multiple safe places!

**Comment by chalachala** [comment]
thank you!  trying that  out now

**Comment by chalachala** [comment]
![screen shot 2016-09-09 at 4 15 50 pm](https://cloud.githubusercontent.com/assets/18206874/18378580/c473ed3c-76a8-11e6-890b-80d80978f34b.png)

**Comment by chalachala** [comment]
island777 I am trying to redownload the logfile but getting frozen after 20 seconds or so.  Now Im getting error messages on the log saying "corruption on data block" and "checksum mismatch"

**Comment by islander777** [comment]
Sorry to hear this mate... Yes I agree this is huge mess. They definitely should have tested this more thoroughly, before releasing new versions of wallet.
Sorry I can't help much - I'm semi-noob myself. The only thing I would probably try to do is to back up the "keystore" files and reinstall the whole thing completely. I mean delete ethereum from computer, delete all the ethereum folders and download a fresh copy of 0.8.2 and install from scratch. If this doesn't help I have no idea what will. I really hope someone is working on a fix for this :(

**Comment by chalachala** [comment]
![screen shot 2016-09-09 at 6 25 24 pm](https://cloud.githubusercontent.com/assets/18206874/18382212/fd251da6-76ba-11e6-81fc-f5d1f9543212.png)

Here is a new error message Im getting.  Perhaps someone can see what the issue is here?  Sorry that its all going over my head.

**Comment by chalachala** [comment]
kept getting corruption errors so I gave up on my MAC, went out bought a new one and it works just fine now having started from scratch.  I guess it was an issue with my old MAC

**Comment by islander777** [comment]
Great! Glad to hear everything is working now!

**Comment by luclu** [comment]
I will close this as "resolved". Feel free to stay and discuss!
