### ISSUE TITLE
could not connect to node error ethereum wallet

### ISSUE THREAD

**Issue by JDMorrison75** [ethereum/mist#1115]
my wallet was working fine but was taking forever syncing so I opened command prompt used the remove block chain command and then used geth --fast but now im getting a error could not connect to node db corrupt could not find block 0 
![wallet](https://cloud.githubusercontent.com/assets/21248196/17982896/7afcc67c-6acf-11e6-947e-aa8372c9b2fe.JPG)

**Comment by luclu** [comment]
Make sure to update Ethereum Wallet as well as your local installation of geth.
As your chaindata seems to be irrecoverable corrupt you might want to delete the `%APPDATA\Ethereum\chaindata` folder. Let me know on the outcome!

**Comment by luclu** [comment]
Closed as of inactivity.

**Comment by jebuscraisp** [comment]
Hi, 

First time installing the ehtereum wallet , got that error deleted the folder and the app , restart and nothing , any suggestions?
