### ISSUE TITLE
Ethereum Wallet/Mist does not sync; Ether from Shapeshift.io transferred, but lost

### ISSUE THREAD

**Issue by Manatee-Outlaw** [ethereum/mist#1118]
#### System information

```
Wallet Version: `0.8.2`
OS & Version: Windows 10, 64bit
Node type: geth
Router Port Forwarded UDP port 3030
```

It all started when I tried to transfer some bitcoin into ether via shapeshift.io. I updated my ethereum wallet - I was a few, uh, hundred thousand blocks behind, and once everything was updated I sent over two small transactions of BTC through shapeshift into my ETH account.

Nothing happened.

So I waited... about an hour. Nothing happened again, yet, my client was updating happily as if everything was just danimals. So I checked through the blockscanner, and lo and behold the transaction went through. I _have_ ether in my wallet, it's just that my node doesn't show it at all.

So I figured, heck. Maybe I just need to uninstall and reinstall? That's the IT equivalent of turning it off and on again, so I gave that a shot. Now I've got new and exciting problems!

Turns out my ethereum wallet - and mist, for what it's worth - refuse to update the blockchain. It's been 3 hours, and they've not done a dang thing. They just sit there, looking for peers, all alone.

It's sad, but mostly it's infuriating. What's going on?

Screenshots attached.
![this is my life now](https://cloud.githubusercontent.com/assets/10366984/17989309/5b2d3090-6afa-11e6-87ac-d70d1afeb9c0.jpg)
![i don t know you tell me](https://cloud.githubusercontent.com/assets/10366984/17989310/5b31a8c8-6afa-11e6-8a22-73d2f4f6cec5.jpg)
![it speaks in riddles](https://cloud.githubusercontent.com/assets/10366984/17989308/5b2d12a4-6afa-11e6-8eb7-f0a3d2ad4ddf.jpg)

**Comment by Faf7** [comment]
I have exactly the same problem

**Comment by luclu** [comment]
@Manatee-Outlaw please excuse the late reply.
Firstly as long as you have the private key (json-keystore file) to that address you have ownership over the Ether. You can access them using other nodes or services like https://www.myetherwallet.com/ anytime.

The screenshots you posted do not give any reason for concern. They show ordinary behaviour.

> Maybe I just need to uninstall and reinstall?

Did you also remove these folders during your reinstall or only the folder containing the binary?
 - `%APPDATA%\Mist` (contains Mist related config like watched contracts, settings)
 - `%APPDATA%\Ethereum` (contains synced blockchain and all the **private keys** to your accounts) **Be careful**, always backup the `keystore` folder.

Could you kindly provide the address in question (mind the privacy concerns) and the `node.log.X` files as described [here](https://github.com/ethereum/mist/issues/new)?

**Comment by luclu** [comment]
I will close this.
