### ISSUE TITLE
Mist crashes each time on open

### ISSUE THREAD

**Issue by funktrust** [ethereum/mist#1119]
#### System information

```
Version: 0.8.2
OS & Version: osx
Node type: geth
```

Each time Mist loads, it finds my geth node, then I click launch application and it crashes, I have provided a screenshot below of the crash and it seems it doesn't like com.github.electron.framework. I have tried to troubleshoot and have done a number of things and searched but nothing seems to work.

I need Mist so I can execute my smart contracts and I have no way of fixing this without something radical like me formatting.

**I have done the following:**
- Deleted the entire /users/admin/Library/Ethereum folder then opened Mist, it would then take me through the wizard in setting up the account, connecting to a node and then download the Ethereum blockchain. Clicked launch and the application crashes.
- Opened Mist and connected to a testnet, once clicking launch application it crashes again
- Updated Mist to version 0.8.2
- Deleted the entire /user/Library/Ethereum folder again then ran geth console and let the Ethereum blockchain sync up again. 
- I have installed geth and let the node sync up

**Screenshots**
Mist Crash
![image](https://cloud.githubusercontent.com/assets/8413458/17993674/252466e4-6b95-11e6-8dac-ad0740497e26.png)

**Geth console**
![image](https://cloud.githubusercontent.com/assets/8413458/17993713/80728882-6b95-11e6-823e-2cb3a7772390.png)

**Mist node.log file**
[node.log.zip](https://github.com/ethereum/mist/files/438503/node.log.zip)

**Comment by jeanbapt** [comment]
Got the same. Don't know how to fix it. Ethereum Wallet works fine though.

**Comment by btsfav** [comment]
I get https://ipfs.pics/ipfs/QmPes2MxFH6KAsHd2Y67HtHSjux1YZsMFP25Tg61u5eRzS - links to the release post, but there's no instruction how to actually fix it.

**Comment by mrcybermac** [comment]
Same issue.  Mist 8.2 crashes on startup each time around the time it connects the node.

**Comment by chevdor** [comment]
Hello, from your description, I guess that you installed *Ethereum Wallet* and try running Mist from there. I did not try Ethereum Wallet but it would be interesting to see if it helps installing *Mist* (Separate download) as well. I am using Mist 0.8.2 on OSX and did not experience any crash so far (for what it is worth).

**Comment by chevdor** [comment]
@btsfav your issue is that you are on the Classic chain and since 0.8.2, Classic is no longer supported by Mist. As mentioned, you need to see with the Classic folks how to get a client that works if this is what you want. Things should work for you as well with 0.8.1.

If you are trying to use Ethereum core, you can type the following:
```
geth export whatever_filename
geth removedb
geth --rpc --fast console 
```

and wait until the blockchain is updated.

**Comment by mrcybermac** [comment]
I've installed both Ethereum Wallet and Mist both 0.8.2.  Ethereum Wallet loads fine, Mist crashes every time.

**Comment by chevdor** [comment]
May I ask how you start Mist? In other words, do you start the standalone Mist or the one coming with the Ethereum Wallet?

**Comment by mrcybermac** [comment]
I'm on osx.

I run geth separately from terminal.  I've also tried stopping geth and letting Mist load it's own node.  No difference... still crashes.

To start it I just double click on the application icon, then the splash screen comes up.  I use Little Snitch firewall (tried with it off and on).  I can see Mist on startup connect to:

api.github.com
then
min-api.cryptocompare.com
then it says:
"Ethereum Node Connected"
then it crashes

**Comment by chevdor** [comment]
I would suggest to:
- start geth on its own as you have done already
- start Mist using the following command: /Applications/Mist.app/Contents/MacOS/Mist 

and see if the log in the console may tell something useful (you can paste it here). I am talking about the Mist logs, not geth.

**Comment by luclu** [comment]
> start Mist using the following command: /Applications/Mist.app/Contents/MacOS/Mist 

You can try to increase the loglevel, too with: `--loglevel debug`

**Comment by jeanbapt** [comment]
Thx @luclu I just did that and it runs smoothly Until : 

[2016-09-03 09:53:07.343] [INFO] (ui: mist) - Initialise Mist
[2016-09-03 09:53:07.343] [DEBUG] (ui: mist) - Setting language
[2016-09-03 09:53:07.607] [DEBUG] (ui: mist) - Finished reloading collection from backend:  tabs
Segmentation fault: 11

Got a seg fault. 
I am running fine with wallet, both Eth  etc. 

JB

**Comment by luclu** [comment]
pinging @hiddentao @frozeman @evertonfraga

**Comment by hiddentao** [comment]
Segmentation faults are really hard to pin down as they're coming from within the Electron executable and not our code.  

@jeanbapt could you please try with `--loglevel trace` so that we can get more detail on exactly where it's crashing.

**Comment by evertonfraga** [comment]
I am closing this issue upon inactivity. **Please feel free** to reopen should you still have any considerations about it.
