### ISSUE TITLE
please log geth stderr output to a file

### ISSUE THREAD

**Issue by fjl** [ethereum/mist#112]
When there is an issue with the node running in the background, it will be much easier to troubleshoot
if the log is available. It would be even nicer if logs from the past 10 runs were retained.

**Comment by frozeman** [comment]
These logs can become larger very fast.
When would you save them to a file?
As it stands in geth, all output is send to stderr, ideally this wouldn't be the case, so then i could create a file as soon as an error output comes.

**Comment by fjl** [comment]
I meant that log output should be streamed to the file immediately, e.g. 

```js
var file = fs.openSync("geth.stderr", "w");
geth.stderr.on('data', file.write);
```

With the default verbosity settings, geth doesn't output a lot of text.
