### ISSUE TITLE
What's the difference between the Ethereum Wallet and the Mist Wallet?

### ISSUE THREAD

**Issue by firecentaur** [ethereum/mist#1122]
Hi there, on the new 8.2 download page, there are Mist Download links and An Ethereum Wallet download links - can you please explain the difference? And also update the docs to explain to others?

Kind regards

**Comment by evertonfraga** [comment]
Sure! We're planning an overhaul on our Readme.md.

The Wallet zip is the wallet standalone application, whereas Mist Browser (in beta version) is more complete and allows you to navigate on many Dapps (Decentralized Applications) throughout the internet. Worth noticing that Mist bundles the Wallet.

Both share the same codebase, but Mist is still in beta version, with a schedule release for December: https://github.com/ethereum/mist/milestone/5

Also, you could perfectly download both, you'll have only one set of accounts and one same blockchain files to download and interact with.
