### ISSUE TITLE
Timeout  Github (updateChecker.js)

### ISSUE THREAD

**Issue by esdrasedu** [ethereum/mist#1124]
#### System information

```
Version: `0.8.2` (develop)
OS & Version: linux 4.7.2-1-ARCH x86_64
Node type: `geth 1.4.11`
```

Hello, I am having timeout for checking update, because the timeout setting is 3s (https://github.com/ethereum/mist/blob/develop/modules/updateChecker.js#L30), but in Brazil (where I am) github don't responds in 3s!

I think will be nice if change for 10s, because others countries the internet not is so good!

**Comment by esdrasedu** [comment]
Will be nice if user receive return of timeout too!

**Comment by evertonfraga** [comment]
Ok @esdrasedu! O Luca vai cuidar disso. 

Por acaso era algum problema de proxy, ou timeout apenas?

**Comment by esdrasedu** [comment]
Não estava usando proxy, apenas wifi mesmo (que piora um pouco a performance).
Acho q 3 segundos é pouco para request em países que possuem internet de baixa qualidade!
Seria legal poder ter uma notificacão do timeout, pois a impressão para usuário final é que "atualização" travou!

@luclu Do y understand portugues? Do y need translates for this?

**Comment by luclu** [comment]
Thank you @esdrasedu. I get the gist! :)

**Comment by luclu** [comment]
PR: https://github.com/ethereum/mist/pull/1157
