### ISSUE TITLE
Mist 0.8.2 fails all outgoing tasks without error

### ISSUE THREAD

**Issue by rpsdhillon** [ethereum/mist#1127]
#### System information
``````
Windows 10 Ultimate 64bit
``````
Creating a Wallet Contract Fails after running for a while, but no error is displayed.
Send Ether fails after a while and no error is displayed ( it stays on 0 of 12 confirmations for a while and then fails )

**Comment by luclu** [comment]
@rpsdhillon could you kindly upload your node's logs as a zip? You will find them under `%APPDATA%/Mist` ([desciption](https://github.com/ethereum/mist/issues/new)).

**Comment by jordanmack** [comment]
I was also having a problem with transactions not going through. I'm also using Windows 10 x64 with Mist 0.8.2. I restarted my client so I could get a clean log and then it started working again.

**Comment by luclu** [comment]
Closed as of inactivity.
