### ISSUE TITLE
App fails to start - can't connect to nod

### ISSUE THREAD

**Issue by maraciuca66** [ethereum/mist#1129]
The wallet fails to start and give me this error. The problem has apear after i restart the pc.
I use Win 10 x64. How can i fix this?
I have try to delete the forders from appdata, got the same problem. Solved: i have moved the files on my laptop.
![err1](https://cloud.githubusercontent.com/assets/21320612/18067521/dacb8c68-6e45-11e6-8bcf-3e1a9815392a.JPG)

**Comment by luclu** [comment]
I will close this for now as you seem to have solved it by yourself.
> Solved: i have moved the files on my laptop.

Feel free to ask further questions should you still need help.
