### ISSUE TITLE
Menu item 'Mist > About Mist' does not work.

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#113]
This might be a minor issue but I'm the package maintainer vor the mist package in the archlinux user repositories. I just tried to figure out which version of the mist browser is installed. 

The menu item 'Mist' > 'About Mist' does not work, nothing happens after clicking it. What is supposed to happen there?

![screenshot at 2016-01-18 10 42 54](https://cloud.githubusercontent.com/assets/15729797/12388038/baf6ab78-bdd0-11e5-9707-bf18e55661cb.png)

I'm using the 'Ethereum-Wallet' binary from the pre-release tags here on github. System is ArchLinux with kernel 4.3.3-2-ARCH x86_64 GNU/Linux. Backend is the included geth node version 1.3.3.

Is there any other way to see the version of the current mist browser installed?

**Comment by frozeman** [comment]
Yes this only works on mac OS X by default, for all others we would have to make a custom about window..which has quite a low priority :)

**Comment by luclu** [comment]
Fixed in current versions!
