### ISSUE TITLE
Wallet problem I cant recive my ETH [non-fork chain]

### ISSUE THREAD

**Issue by Denis9555** [ethereum/mist#1132]
I am with this problem 1 month I have mined 40.49492753 Ether but in my Wallet account I have only 28,72 ETH I syn every day the wallet and still nothing..

There are pics of my problem:

http://prntscr.com/cc7im9
http://prntscr.com/cc7is1

How to fix that? 
Thanks in advance!

**Comment by jordanmack** [comment]
@Denis9555 Looks to me like your wallet is set to the Ethereum Classic chain.

**Comment by Denis9555** [comment]
@jordanmack  how i can change it?

**Comment by jordanmack** [comment]
@Denis9555 What is your client version?

**Comment by Denis9555** [comment]
@jordanmack with the Ethereum-Wallet-win64-0-8-1

**Comment by luclu** [comment]
@Denis9555 here are two tutorials on how to switch to the hard-forked (ETH) chain: https://github.com/ethereum/mist/issues/1136
