### ISSUE TITLE
always fail to view web site

### ISSUE THREAD

**Issue by huchhong** [ethereum/mist#1134]
#### System information
``````
Version: `0.8.2`
OS & Version: windows
Node type: `geth`
``````

I use mist to view site, including web 2.0 and dapp sites. It always failed with a blank page, why?

**Comment by huchhong** [comment]
It is some proxy problem, close issue.

**Comment by morelazers** [comment]
Hi @huchhong, could you elaborate on the proxy issue? I am able to view my site in Chrome, but in Mist it is a completely white screen.

**Comment by morelazers** [comment]
@frozeman When I check the network tab there's nothing going to or coming from the URL I'm trying to load. When I check in the console I can see some `dom-ready` events, but the DOM is completely empty save for the standard Html, and empty Head and Body tags.
