### ISSUE TITLE
Mist wallet does not recognise existing chaindata folder

### ISSUE THREAD

**Issue by FergusLemon** [ethereum/mist#1137]
``````
Version: `0.8.2`
OS & Version: osx
Node type: `geth(default)`
``````
I have had the full chain stored on my laptop for months now, the directory at ~/Library/Ethereum/chaindata contains what seems like the whole chain (37GB and >19,000 items).  Yet when I launch the Mist wallet it now says that I need to download the chain and starts downloading blocks from the beginning.

When I launch the application all of my wallet contracts are greyed out with zero balances and my accounts show incorrect balances, they seem to be the balances from months ago.

Is there any reason why the Mist wallet is not recognising the existing chaindata?

**Comment by luclu** [comment]
Could you kindly upload the `node.log.X` files as described [here](https://github.com/ethereum/mist/issues/new)?

**Comment by luclu** [comment]
I will close this for now as of inactivity.
