### ISSUE TITLE
Automatic updatedb?

### ISSUE THREAD

**Issue by jackokring** [ethereum/mist#1139]
#### System information
``````
Version: `0.8.2`
OS & Version: windows
Node type: `geth(default)`
``````

Is it possible to make geth drop back into updatedb mode when "mining" and sync is not effective. I was in the position of the chain being 2000+ blocks behind. It require a ctrl+C, geth updatedb, ctrl+C, geth --mine.

Also is it common for geth to output nothing for 4 hours with the last line saying "checking DAG"? Maybe related, don't know the internals well enough.

**Comment by luclu** [comment]
@jackokring please make sure your system installation of **geth** is up-to-date.
What does `geth version` output?

**Comment by jackokring** [comment]
Geth
Version: 1.4.10-stable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.6.2
OS: windows
GOPATH=
GOROOT=c:\go

I conclude it's geth as I am also running Monero block chain too, and it has no problem yet.

**Comment by luclu** [comment]
Are these two problems persistent and reproducible for you?

**Comment by jackokring** [comment]
I am using the bundled geth. The loss of sync happens quite frequently, and sometimes I wake up and the system is a few hundred blocks behind, and committing work ...

The checking DAG hang has only happened once, and I have not got a repeat.

**Comment by jackokring** [comment]
The output below seems to be a no peers issue, but this does not explain why when peers come back online, that sync does not happen before mining attempts.

I0902 19:07:53.917569 p2p/server.go:313] Starting Server
I0902 19:07:55.705072 p2p/discover/udp.go:217] Listening, enode://d59b0347f71a1323f05f794f4600a781cfe6bd83454195a644a507881ef725494148206fa01e16b9d608ee4efb483b57e20304d58c49a785daecac4dedbbf78e@[::]:30303
I0902 19:07:55.711076 p2p/server.go:556] Listening on [::]:30303
I0902 19:07:55.713077 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc
I0902 19:07:55.717081 node/node.go:366] HTTP endpoint opened: http://localhost:8545
I0902 19:08:25.711185 eth/downloader/downloader.go:320] Block synchronisation started
I0902 19:08:30.104419 eth/handler.go:295] Peer d04df7f39792f3d8 [eth/63]: timed out DAO fork-check, dropping
I0902 19:08:31.076087 eth/handler.go:295] Peer fec03476503431eb [eth/63]: timed out DAO fork-check, dropping
I0902 19:08:32.525127 eth/handler.go:295] Peer 1118980bf48b0a36 [eth/63]: timed out DAO fork-check, dropping
I0902 19:08:40.083486 eth/handler.go:295] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping
I0902 19:09:08.165885 eth/handler.go:295] Peer 562796b19d43d79d [eth/63]: timed out DAO fork-check, dropping
I0902 19:09:39.247448 eth/handler.go:295] Peer de471bccee3d0422 [eth/63]: timed out DAO fork-check, dropping
I0902 19:10:50.293665 eth/handler.go:295] Peer b02d4cee47de189d [eth/63]: timed out DAO fork-check, dropping
I0902 19:11:22.606541 eth/handler.go:295] Peer 7ced285d49b21e03 [eth/63]: timed out DAO fork-check, dropping
I0902 19:11:46.374030 eth/handler.go:295] Peer 522af88b556fe141 [eth/63]: timed out DAO fork-check, dropping
I0902 19:11:49.669729 eth/handler.go:295] Peer ab07238ec2bb0ab6 [eth/63]: timed out DAO fork-check, dropping
I0902 19:12:27.589727 eth/handler.go:295] Peer 9b034fde747960fe [eth/63]: timed out DAO fork-check, dropping
I0902 19:12:46.945817 eth/handler.go:295] Peer fec03476503431eb [eth/63]: timed out DAO fork-check, dropping
I0902 19:13:11.275187 eth/handler.go:295] Peer fd3af7c243f1b0e7 [eth/63]: timed out DAO fork-check, dropping
I0902 19:13:18.126102 eth/handler.go:295] Peer 8b08d5435809dbf5 [eth/63]: timed out DAO fork-check, dropping
I0902 19:13:34.459719 eth/handler.go:295] Peer 1637a970d987ddb8 [eth/63]: timed out DAO fork-check, dropping
I0902 19:13:45.197506 eth/downloader/downloader.go:299] Synchronisation failed: no peers to keep download active
I0902 19:14:20.376300 eth/handler.go:295] Peer 1b7b67b06425da03 [eth/63]: timed out DAO fork-check, dropping
I0902 19:14:21.374120 eth/handler.go:295] Peer 07943c6c079090eb [eth/63]: timed out DAO fork-check, dropping
I0902 19:14:29.679744 eth/handler.go:295] Peer 2c2fabac9ef11438 [eth/63]: timed out DAO fork-check, dropping
I0902 19:15:11.543185 eth/handler.go:295] Peer 24a0e954bad23171 [eth/63]: timed out DAO fork-check, dropping
I0902 19:15:16.602472 eth/handler.go:295] Peer 2b4ae107c2fbd1ba [eth/63]: timed out DAO fork-check, dropping
I0902 19:15:30.618140 eth/downloader/downloader.go:1087] Peer f3c6ee3bce3bc18d [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: head header set (item 0) broke chain ordering: requested 1919809, got 2186722
I0902 19:15:42.565274 eth/handler.go:295] Peer fec03476503431eb [eth/63]: timed out DAO fork-check, dropping
I0902 19:16:16.936466 eth/handler.go:295] Peer 53368afb96ab78d4 [eth/63]: timed out DAO fork-check, dropping
I0902 19:16:53.478069 eth/handler.go:295] Peer cb556a86069900b8 [eth/63]: timed out DAO fork-check, dropping
I0902 19:16:53.579141 eth/handler.go:295] Peer d8caad3212c52007 [eth/63]: timed out DAO fork-check, dropping
I0902 19:16:53.979665 eth/handler.go:295] Peer e6406e36711e1259 [eth/63]: timed out DAO fork-check, dropping
I0902 19:17:10.208264 eth/handler.go:295] Peer 1637a970d987ddb8 [eth/63]: timed out DAO fork-check, dropping
I0902 19:17:25.515213 eth/handler.go:295] Peer 30dc547dbd116454 [eth/63]: timed out DAO fork-check, dropping
I0902 19:17:46.188292 eth/handler.go:295] Peer 4dc9f19d8f1b36d9 [eth/63]: timed out DAO fork-check, dropping
I0902 19:19:36.214804 eth/downloader/downloader.go:1087] Peer 8cc43cb0e342e009 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: head header set (item 0) broke chain ordering: requested 1919809, got 2186775
I0902 19:19:41.820793 eth/handler.go:295] Peer 53368afb96ab78d4 [eth/63]: timed out DAO fork-check, dropping
I0902 19:20:13.628898 eth/downloader/downloader.go:1087] Peer 562796b19d43d79d [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: head header set (item 0) broke chain ordering: requested 1919809, got 2186778
I0902 19:20:48.568325 eth/handler.go:295] Peer 24a0e954bad23171 [eth/63]: timed out DAO fork-check, dropping
I0902 19:21:14.093214 eth/handler.go:295] Peer b2802a653ca7095a [eth/63]: timed out DAO fork-check, dropping
I0902 19:21:50.039728 eth/handler.go:295] Peer 335bc9e2955d7e3d [eth/63]: timed out DAO fork-check, dropping
I0902 19:22:51.394853 eth/handler.go:295] Peer 77e6a5959a5e0529 [eth/63]: timed out DAO fork-check, dropping
I0902 19:23:20.301403 eth/handler.go:295] Peer 53368afb96ab78d4 [eth/63]: timed out DAO fork-check, dropping
I0902 19:23:28.966286 eth/handler.go:295] Peer 24a0e954bad23171 [eth/63]: timed out DAO fork-check, dropping
I0902 19:23:31.618922 eth/downloader/downloader.go:299] Synchronisation failed: no peers to keep download active

**Comment by jackokring** [comment]
Oh, a sync

I0902 19:26:01.273386 eth/handler.go:295] Peer 79e694a4f278d5f1 [eth/63]: timed out DAO fork-check, dropping
I0902 19:26:15.276310 core/blockchain.go:963] imported 3 block(s) (0 queued 0 ignored) including 38 txs in 4.6456158s. #2183818 [2626c9ab / d3f27b83]

**Comment by jackokring** [comment]
#2184126 ... when ethstat is at #2,186,818 and this is common.

**Comment by jackokring** [comment]
Makes me wonder... What happens if a modified source client has the habit of passing on ETC peers to push ETH peers out of the pool? An effective way to obtain 51%?

**Comment by jackokring** [comment]
I'll try 1.4.11 for a few days.

**Comment by luclu** [comment]
How many average peers do you get?
This looks familiar to https://github.com/ethereum/go-ethereum/issues/2533.

**Comment by luclu** [comment]
I will close this for now as of inactivity. Feel free to reopen should you still encounter this issue.
