### ISSUE TITLE
How to bundle ethereum wallet from source?

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#114]
I tried to reproduce how you create binaries for the mist browser. The docs seem very outdated.

Could you tell me a working build process (I'm on Linux.) or point me to some more recent docs?

Thanks.

(By the way what's missing for the 32 bit builds, only the geth node?)

**Comment by frozeman** [comment]
The 32bit builds work, but the geth node is missing.

The docs should be uptodate, whats not working for you?

**Comment by 5chdn** [comment]
Yes, sorry it's working like described in the docs. Sorry, I don't know what I've smoked that day. ;-)
