### ISSUE TITLE
mining ethereum / password 

### ISSUE THREAD

**Issue by evfrizen** [ethereum/mist#1142]
Good afternoon friends!
Yesterday found myself on a mac purse etherum.
After downloading the blocks and transactions it has started and it immediately appeared purse , I did not create .
Then I found a button in the panel mining , ran it and forgot about the process .
An hour later, back to the purse and then produced 25 esters .
Explain please , I namaynil these ethers ? can we remove them ?
I tried to get them , a password is required to confirm the transaction , and where I will take your password if I do not create a purse .
Thanks in advance!
![2016-09-01 21 55 54](https://cloud.githubusercontent.com/assets/21701059/18193561/2f80d33a-70f8-11e6-9042-4555edbca5c6.png)

**Comment by luclu** [comment]
@evfrizen you might have been using **geth** beforehand which will present you with some old accounts.
As on the screenshot indicated by the red label your node is configured to use the **test-net**. This test-Ether is not worth anything - though I'm always happy to have plenty to play around. :D 

Go to the develop-menu and switch back to main-net.

**Comment by evfrizen** [comment]
Thank you very much for the answer!
I'm new to this business .
please tell me whether it is possible to produce Ethereum from the computer , the native graphics card ?
it productively ?
there are any articles or videos on this subject?

**Comment by luclu** [comment]
Yes, it is possible. Head over to https://www.reddit.com/r/ethermining to get instructions and support in this regard.
