### ISSUE TITLE
Cleanup package.json

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#1144]
`package.json` seems to be significantly outdated. 
```javascript
  "engines": {
    "node": ">4.3.0",
    "electron": "1.0.1",
    "atom-shell": „0.36.2“ 
  }
```
Also considering we are using `npm-shrinkwrap.json` now, I wonder if the dependencies subschema could be removed altogether?

The current situation is rather confusing, see: https://github.com/ethereum/mist/pull/1138

**Comment by hiddentao** [comment]
The `engine` key doesn't do much to be honest. It's only really for other packages which include Mist, which none will do. I'll remove it in `develop`.

**Comment by hiddentao** [comment]
See #1150
