### ISSUE TITLE
Node connection and Mist problems 

### ISSUE THREAD

**Issue by majorleeblunt** [ethereum/mist#1145]
Trying to update from previous version before July to 0.8.2

having a few issues and cannot seem to find workaround 

please can someone help with this issue?

have tried installing older wallets just incase, played around with geth commands but no joy :(

```
Version: `0.8.2`
OS & Version: windows 7 x64
Node type: `geth`
```
- Screenshots
  ![screen shot 09-03-16 at 10 18 pm](https://cloud.githubusercontent.com/assets/21976858/18227694/6eefccaa-7225-11e6-8813-f74d94f9704d.PNG)
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

*\* Cannot work this part out
- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):

```
I0903 22:17:45.913983 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to C:\Users\BLUNT\AppData\Roaming\Ethereum\chaindata
I0903 22:17:45.933984 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------
I0903 22:17:45.933984 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0903 22:17:45.933984 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0903 22:17:45.933984 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0903 22:17:45.933984 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0903 22:17:45.934984 ethdb/database.go:169] closed db:C:\Users\BLUNT\AppData\Roaming\Ethereum\chaindata
I0903 22:17:45.936984 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to C:\Users\BLUNT\AppData\Roaming\Ethereum\chaindata
I0903 22:17:46.003988 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to C:\Users\BLUNT\AppData\Roaming\Ethereum\dapp
I0903 22:17:46.010988 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0903 22:17:46.011988 eth/backend.go:201] Blockchain DB Version: 3
I0903 22:17:46.011988 core/blockchain.go:206] Last header: #0 [d4e56740…] TD=17179869184
I0903 22:17:46.011988 core/blockchain.go:207] Last block: #0 [d4e56740…] TD=17179869184
I0903 22:17:46.011988 core/blockchain.go:208] Fast block: #0 [d4e56740…] TD=17179869184
I0903 22:17:46.012988 p2p/server.go:313] Starting Server
```

**Comment by luclu** [comment]
Try to backup the `%APPDATA%\Ethereum\chaindata folder and check if this improves your situation.

**Comment by majorleeblunt** [comment]
> Try to backup the `%APPDATA%\Ethereum\chaindata folder and check if this improves your situation

how exactly do i do that? i did try removing this data onto another drive and rebuildng the chain

**Comment by majorleeblunt** [comment]
![screen shot 09-04-16 at 03 58 pm](https://cloud.githubusercontent.com/assets/21976858/18231730/6c230bde-72b8-11e6-81b3-7a3377e20e5f.PNG)

**Comment by Doncharly** [comment]
NO PASA NADA     NO SE COMO  HACERLO
ᐧ

2016-09-04 9:58 GMT-05:00 majorleeblunt <notifications@github.com>:

**Comment by majorleeblunt** [comment]
> NO PASA NADA     NO SE COMO  HACERLO

no hablo amigo

**Comment by majorleeblunt** [comment]
what would i need to do to make a new wallet on another machine and transfer my data over so i dont lose my ETH and DAO?

**Comment by islander777** [comment]
I have excactly same issue in Win10 64. Spent few hours in google, tried every possible fix I could find - nothing works. Everything worked perfectly in 0.8.1... Mist wallet won't sync now, everything stuck at block 2,058,533. Really hope someone is working on a fix. the Mist wallet is unusable as is :(

**Comment by haenkmaen** [comment]
the same here on OS X 10.11.6.
Mist wallet won't sync.

**Comment by majorleeblunt** [comment]
i hope someone in the community can help

**Comment by majorleeblunt** [comment]
so why wont it connect to the node?

**Comment by chrisVrsaljko** [comment]
I have the same issue, i also tried older versions and changing it up but it still never starts to sync win64 8.2

**Comment by majorleeblunt** [comment]
thought someone would have been able to suggest a work around or help with the issue

**Comment by luclu** [comment]
@all could you please run Ethereum-Wallet via the terminal?
```
Ethereum-Wallet{.exe} --loglevel trace
```
Trying to pinpoint a possible connection to https://github.com/ethereum/mist/issues/864.

**Comment by majorleeblunt** [comment]
is that not linux? sorry if not!

on WIN 7 x64 here

**Comment by luclu** [comment]
@majorleeblunt please post the output here, as it contains helpful information.

**Comment by majorleeblunt** [comment]
![screen shot 09-30-16 at 03 21 pm](https://cloud.githubusercontent.com/assets/21976858/18994874/af817f64-8721-11e6-97f6-389a8eead458.PNG)

**Comment by porobov** [comment]
Had the same looking error when tried to connect to a running geth node started with command 
`geth --testnet --ipcpath "$HOME/.ethereum/testnet/geth.ipc"`

Tried to replicate the error but got a little different result now:
![Error connecting to node ubuntu](http://i.imgur.com/cRiyFsk.png) 

Using Ubuntu 14.04, Ethereum Wallet 0.8.6

Hope it helps! Thank you for your software!

**Comment by porobov** [comment]
My bad. Had to use:
`geth --testnet --ipcpath "$HOME/.ethereum/geth.ipc"`

**Comment by majorleeblunt** [comment]
![screen shot 10-22-16 at 12 14 pm](https://cloud.githubusercontent.com/assets/21976858/19615808/41cab5c6-9851-11e6-9811-b94b25e4f2c5.PNG)

**Comment by majorleeblunt** [comment]
should i go back to a version before i did the updates that stopped my ETH wallet from loading, have DAO and ETH coins on this and dont want to loose them!

**Comment by majorleeblunt** [comment]
something different...
![screen shot 10-22-16 at 12 19 pm](https://cloud.githubusercontent.com/assets/21976858/19615875/51aa62ce-9852-11e6-89e2-32523a6d2d2e.PNG)

**Comment by majorleeblunt** [comment]
does anyone have any idea how i can get back my ETH coins?

**Comment by luclu** [comment]
@majorleeblunt could you please upload the `node.log`s?
> - Log files 
>   - go to `menu -> accounts -> backup -> application data`
>   - zip and upload `node.log` and all other `node.log.X` files 
 
In the meantime you can use https://www.myetherwallet.com/ to access your funds (Go to `menu -> accounts -> backup -> accounts` to access your keyfiles).
