### ISSUE TITLE
Empty Mist screen due to javascript error 'opts undefined'

### ISSUE THREAD

**Issue by RinzeCats** [ethereum/mist#1147]
#### System information
``````
Version: `0.8.2`
OS & Version: Ubuntu 16.0.4
Node type: `pyethapp`
``````
The problem: when starting Mist my screen is empty, the menu's are there but no interface. This is caused by a javascript error, where opts is undefined when checking for opts.network on line 293 of accounts.js 
~~~~
   if (!opts.network) {
        throw new Error('Network id not given');
   }
~~~~ 
If I set this manually and reload, everything works. 

I am running a private cluster and tried using the --node-networkid flag to pass the parameter, but it doesn't work and neither does --networkid. Any idea what's going on? I'm connecting to a local node, start commands are below:
pyethapp node
~~~~
pyethapp -c eth.network_id=1337 -b 'enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@bootstrap:30303' -m 50 -c eth.genesis_hash=283bd9430c5f3114872f93beefe99d6626980b3a4a18a44ddd27749cd89688f2 run --fake
~~~~
mist
~~~~
 electron . --mode mist  --rpc /tmp/pyethapp.ipc --networkid 1337 --node-datadir /root/.config/pyethapp/
~~~~

side note; when I manually set opts.network using the javascript console, it actually keeps working after restarts. Not sure why. Cookie maybe?

**Comment by luclu** [comment]
Just to be clear, do you use eth (at system information) or pyethereum as backend?

**Comment by RinzeCats** [comment]
Hi, sorry. I was using pyethereum as a backend. I will check this and report back. Might take some time, as I moved my cluster to geth. This also had to do with the fact that I could not a geth node to my pyethereum backend, it kept reporting 'useless node'when trying to peer up.

**Comment by evertonfraga** [comment]
I'm closing this for now. @RinzeCats please reonpen if needed.
