### ISSUE TITLE
Replace Kraken as single source of pricing, add historical data

### ISSUE THREAD

**Issue by alexvandesande** [ethereum/mist#115]
* Adding a weighted average of the price in multiple markets would eliminate issues when a single exchange fails or is offline. 

* Consider using bitcoin price as an intermediary price when there isn't any liquidity for a specific currency

* On the transaction logs, use the historical price for that period (maybe a 24h average in unliquid markets?), not the current price

* Study Criptocompare as a possible source, since their devs have been forward with all these issues. 

Examples:
https://www.cryptocompare.com/api?shell#-api-data-coinsnapshot-
https://www.cryptocompare.com/api/data/coinsnapshot/?fsym=ETH&tsym=USD 
https://www.cryptocompare.com/api/data/coinsnapshot/?fsym=ETH&tsym=BTC  
https://www.cryptocompare.com/api/data/coinsnapshot/?fsym=BTC&tsym=USD  
minute : https://www.cryptocompare.com/api#-api-data-histominute-
hour : https://www.cryptocompare.com/api#-api-data-histohour-
day : https://www.cryptocompare.com/api#-api-data-histoday-
https://www.cryptocompare.com/api/data/histominute/?aggregate=15&e=CCCAGG&fsym=ETH&limit=96&tsym=BTC (for 1 days of data aggregated each 15 minutes so that would be 96 intervals of 15 minutes = 1140 minutes = 24 hours)
https://www.cryptocompare.com/api/data/histominute/?aggregate=1&e=CCCAGG&fsym=ETH&limit=60&tsym=BTC (for the last hour each minute)
https://www.cryptocompare.com/api/data/histohour/?aggregate=12&e=CCCAGG&fsym=ETH&limit=62&tsym=BTC (for the last month each 12 hours, 12*62 = 744 hours = 31 days)
https://www.cryptocompare.com/api/data/histoday/?aggregate=1&e=CCCAGG&fsym=ETH&limit=93&tsym=BTC (daily for the last 93 days approx 3 months)
https://www.cryptocompare.com/api/data/histominute/?aggregate=15&e=CCCAGG&fsym=ETH&limit=96&tsym=GBP

**Comment by vcealicu** [comment]
Feel free to contact me directly if you need any help. My skype is vlad.cealicu.

**Comment by frozeman** [comment]
reminder: https://www.cryptocompare.com/api/data/histoday/?aggregate=1&e=CCCAGG&fsym=ETH&limit=0&tsym=USD&toTs=1448928000

**Comment by vcealicu** [comment]
Good news, after talking to Fabian, i did an api that would better suit your needs.

You can find the api documentation here:
https://www.cryptocompare.com/api/#-api-data-price-
https://www.cryptocompare.com/api/#-api-data-pricehistorical-


Examples:

Live: https://www.cryptocompare.com/api/data/price?fsym=ETH&tsyms=BTC,USD,EUR

Historical: https://www.cryptocompare.com/api/data/pricehistorical?fsym=ETH&tsyms=BTC,USD,EUR&ts=1452470400

**Comment by frozeman** [comment]
fixed in 81d2130
