### ISSUE TITLE
ETH goes to a different account than the one I assign

### ISSUE THREAD

**Issue by Dynamo77** [ethereum/mist#1152]
Hi,

I've tried to send ETH to my coin base account a few time, but when I go to confirm the transaction with password a different account shows up to the one I assign just previous to that. Anyone know why its choosing a different account?

![screen shot 2016-09-08 at 2 47 35 pm](https://cloud.githubusercontent.com/assets/7570518/18352044/a5f698a2-75d4-11e6-9c27-33b41d33407a.png)
![screen shot 2016-09-08 at 2 48 08 pm](https://cloud.githubusercontent.com/assets/7570518/18352046/a61b94fe-75d4-11e6-91e5-9df163fa62a9.png)
![screen shot 2016-09-08 at 2 48 41 pm](https://cloud.githubusercontent.com/assets/7570518/18352045/a616d57c-75d4-11e6-9c05-466133c7a8e2.png)

**Comment by Haryx** [comment]
Same thin happened to me
![image](https://cloud.githubusercontent.com/assets/22085672/18366960/6a7dba1a-7621-11e6-9c18-ec8bb0497b97.png)
Original destination was 0xeE08c65e0eEc4502Bd6959484D9c8227ad1e529a
and the worst part is that this transaction does not appear in the transaction list in the wallet ui
what can i do?

**Comment by luclu** [comment]
This happens if you are using the ReplayProtection function ("SplitContract" @ `0x1ca4a86bba124426507d1ef67ad271cc5a02820a`) - see [send.js#L453](https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/client/templates/views/send.js#L453) as you will send the ether to the splitcontract rather than directly to the recipient account.

The confirmation popup will be more verbose as the ["New Confirmation Pane PR](https://github.com/ethereum/mist/pull/1141) is merged.

I will close this for now. Feel free to ask any questions.

**Comment by Dynamo77** [comment]
Hi, thanks for the reply, but this doesn't help me much. I followed the instructions as documented online, to send ETH and ETC to different accounts, but neither the ETH landed in my coinable account  and ETC went to the different account as you tried to explain. However what I would like to know, is a: how do I rectify things so, the coins go to the accounts I designate and b: how do I get the coins back that have gone missing? and to the split contract account?

**Comment by Dynamo77** [comment]
any response to the above?

**Comment by luclu** [comment]
> Hi,

>I'm opening up a new issue for this as I still have not received an answer to help me resolve it. Please refer #1152 for the screen shots.

>I've tried to send ETH to my coin base account a few time, but when I go to confirm the transaction with password a different account shows up to the one I assign just previous to that. Anyone know why its choosing a different account?

@Dynamo77 should you use the *replaySplit*  feature as listed in #1152, try to split to a new account and send to coinbase from that one instead of directly splitting to coinbase.
