### ISSUE TITLE
Can't find Ethereum folder in library on mac

### ISSUE THREAD

**Issue by mtmurp02** [ethereum/mist#1158]
#### System information
``````
Version: `0.8.2`
OS & Version: osx
``````
When I go to the library folder on Mac OX X El Capitan I cannot find the Ethereum folder.

**Comment by dodgers76** [comment]
Try opening your Ethereum Wallet, then go to Accounts > Backup > Accounts

This should open your keystore folder within the Ethereum folder.

**Comment by mtmurp02** [comment]
Ok I can see that now. How do I know which key file is my wallet? I have two wallets on mist and only one has ether in it.

**Comment by luclu** [comment]
Thank you @dodgers76.

@mtmurp02 The keyfiles in the geth's `keystore`-folder will have the accounts address in its name. Please backup both files - just in case - as this is good practice anyway.
