### ISSUE TITLE
Time travel synchronization 

### ISSUE THREAD

**Issue by indigopsy** [ethereum/mist#1160]
#### System information
``````
Version: last
OS & Version: linux
Node type: geth
``````
I stated geth 48h ago.
In Mist browser it was -32,722 blocks left to full sync.
48h after starting sync it's now -32,801

So my question is: **Do I need to travel back in time to sync whole block?**

**Comment by luclu** [comment]
This can happen if your node's synchronization stalls (ex. when the database corrupts during a powerloss). Your node will still receive information about new blocks being created on the network - it simply does not sync them, thus the counter is growing.

Are you using version `0.8.2`? Also are you using the bundled version of geth?

Please upload the log files as described [here](https://github.com/ethereum/mist/issues/new).

**Comment by indigopsy** [comment]
sorry for reporting.
i will be back when you implement online node.
don't want anymore to sync 50k blocks for 2 weeks

issue closed since eth is deleted from my pc
