### ISSUE TITLE
Accidently added WATCH TOKEN for REP before its active and now wallet doesnt SYNC

### ISSUE THREAD

**Issue by chalachala** [ethereum/mist#1164]
Accidently added Watch Token for REP before its active and suddenly ETH wallet wont sync.

Im assuming this is not a coincidence.  However I cant delete the Watch Token as its grey and non-active.

Can someone help?!

**Comment by luclu** [comment]
Duplicate of https://github.com/ethereum/mist/issues/864#issuecomment-248021268
