### ISSUE TITLE
How to replace Geth Binary with Hotfix

### ISSUE THREAD

**Issue by Raindownchips** [ethereum/mist#1166]
Hello I want to learn how to patch this up using the hotfix instead of waiting for the new 0-8-3 release tomorrow.  If anyone can help me out I would really appreciate it. 

Thanks!

**Comment by luclu** [comment]
1. download the binaries of geth `1.4.12` from [here](https://bintray.com/karalabe/ethereum/geth/1.4.12-stable-421df86/view)
 - [linux64](https://bintray.com/karalabe/ethereum/download_file?file_path=geth-1.4.12-stable-421df86-linux-amd64.tar.bz2)
 - [linux32](https://bintray.com/karalabe/ethereum/download_file?file_path=geth-1.4.12-stable-421df86-linux-386.tar.bz2)
 - [win64](https://bintray.com/karalabe/ethereum/download_file?file_path=geth-1.4.12-stable-421df86-windows-4.0-amd64.exe.zip)
 - [win32](https://bintray.com/karalabe/ethereum/download_file?file_path=geth-1.4.12-stable-421df86-windows-4.0-386.exe.zip)
 - [mac](https://bintray.com/karalabe/ethereum/download_file?file_path=geth-1.4.12-stable-421df86-darwin-10.6-amd64.tar.bz2)

2. rename the binary to `geth` (for linux, mac) / `geth.exe` (for win)
3. replace the old bundled version of geth:
 - for win: `Ethereum-Wallet-winXY-0-8-2\resources\node\geth\geth.exe`
 - for linux: `Ethereum-Wallet-linuxXY-0-8-2/resources/node/geth/geth`
 - for mac: `Ethereum-Wallet-macosXY-0-8-2/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth`

**Comment by alxcarrasco** [comment]
@luclu Thanks a lot!

**Comment by Raindownchips** [comment]
@luclu Thanks however I am having issues with it downloading any blocks.  It seems to just be frozen?

**Comment by alxcarrasco** [comment]
@luclu Do we have to remove the chaindata folder to make it work again?

**Comment by alxcarrasco** [comment]
@luclu I replaced the geth file, then restarted my Mac, it's working now, thanks!

**Comment by MrBrighty** [comment]
Geth was replaced to 1.4.12, but it's still impossible to sync. Take a look please at first screen: here is a date of geth creation - 19/09/2016 (as an evidience, that it's actual file)
Second screen shows the failure.

Is there any option to continue syncing without usage 0.8.3 installer?
Thanks a lot.


![2016-09-21 21 53 30](https://cloud.githubusercontent.com/assets/19168046/18722597/03d2db02-803e-11e6-9256-97b9fbc86da9.png)
![2016-09-21 21 53 14](https://cloud.githubusercontent.com/assets/19168046/18722610/1135a98c-803e-11e6-8d6a-542df030f76f.png)

**Comment by luclu** [comment]
@karalabe this looks odd to me ^^^
