### ISSUE TITLE
Remove OSX-related menu items from win/linux versions

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#1168]

**Comment by tomachinz** [comment]
Which OS X related menu items do you refer?

**Comment by luclu** [comment]
Linux, Windows:
 - remove:
   - `Services`
   - `Hide __app__`
   - `Hide Others`
   - `Show All`
 - move to new "Help" tab:
   - `About __app__`
   - `Check for updates...`

**Comment by evertonfraga** [comment]
@luclu what does the beginner tag stands for?

**Comment by luclu** [comment]
It was chosen to signal easy task, that can be tackled by interested users/new-comers to open-source dev world. :)

**Comment by evertonfraga** [comment]
interesting idea :)

**Comment by luclu** [comment]
But now its gone 💃
