### ISSUE TITLE
0.8.3 still uses Geth 1.4.10 - Not 1.4.12  - still stuck at block 2283415

### ISSUE THREAD

**Issue by Giladio** [ethereum/mist#1169]
#### System information
``````
Version: `0.8.3`
OS & Version: osX.10.5
Node type: `geth`
``````
Node is still 1.4.10 and not 1.4.12 as mentioned in the release - My wallet is still stuck at block 2,283,415 and will not sync further. 

Please advise, 

Thanks!

![screen shot 2016-09-20 at 12 38 34 pm](https://cloud.githubusercontent.com/assets/22317851/18665351/81be6258-7f2f-11e6-9260-61d04bd851cb.png)

**Comment by evertonfraga** [comment]
I'll check right now.

Have you dragged Mist.app to /Applications folder?

**Comment by Giladio** [comment]
Yep. Though up to this version is versino I had Mist located inside a folder within /Applications along with 5 other files (AUTHORS, LICENSE, License.chromium.html, README.txt and version). The installer for 0.8.3 did not include these files and had only the Mist app, which I dragged into /Applications

**Comment by LourensThalen** [comment]
I've got the same thing. 
```
Geth
Version: 1.3.3
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.3
```
How do I switch to the new Geth?

**Comment by luclu** [comment]
@LourensThalen you seem to be running an ancient version of geth as your system installation. 
Please follow [these installation instructions](https://github.com/ethereum/go-ethereum/wiki/Building-Ethereum) to be able to use the ethereum main-net again.

Alternatively you can use `0.8.3`'s bundled version of geth instead of the externally started system installed.

**Comment by evertonfraga** [comment]
Ok @Giladio, there are two proper ways to troubleshoot this. Could you help executing these?

What's the output of this command (running from terminal):
```$ /Applications/Mist.app/Contents/nodes/geth/mac-x64/geth version```
This ensures the geth version being bundled with the DMG. This is the output we're looking for:

```Geth
Version: 1.4.12-stable-421df866
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
```

In Mist, go past the splash screen, open developer console (Develop > Toggle Developer Tools > Mist UI) and run this on the console:

```
web3.admin.nodeInfo.name
```

This is the output we're looking for:
> "Geth/v1.4.12-stable-421df866/darwin/go1.7"


If by any chance you're getting an earlier version on the Mist console, make sure there's no external instances running. But please let me know those outputs

**Comment by Giladio** [comment]
Thanks @evertonfraga,

It looks like I'm getting the expected outputs, but Geth is still set to 1.4.10 and wallet cannot sync.

**Terminal:**
Version: 1.4.12-stable-421df866
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
OS: darwin

**Mist Ui:** 
"Geth/v1.4.12-stable-421df866/darwin/go1.7"

**Comment by mbxck** [comment]
Hi All,

I'm having the same issue. But curiously my wallet is stuck on block 2,283,425

I've tried the following:

-- Downloaded new Mist 0.8.3 (was supposed to have new Geth bundled with?)
-- Downloaded hotfix/geth 1.4.12 separately and overwrote the node directory in the above install as per instructions.
-- Applied new geth/hotfix to older Mist wallet 0.8.1

Rebooted several times, tried turning off windows firewall etc and all to no avail. Quite frustrating as I can't send/receive any Ether. CPU and Memory ramping up to 99% on local machine.

Am I missing something here? Can someone confirm where Geth is meant to be stored on Win 64 bit?

**Comment by mbbyc** [comment]
stop at 2283415 after double click on Ethereum Wallet Setup 0.8.3..

**Comment by DripsukCal** [comment]
@evertonfraga, I m getting the same problem ..wallet wont sync ..getting the correct output on Mist Ui: 
"Geth/v1.4.12-stable-421df866/darwin/go1.7"

But still shows I am running on node Geth 1.4.10 (Go) same as @Giladio

**Comment by evertonfraga** [comment]
@mbbyc @mbxck @DripsukCal

Ok, I've got a report from a reddit user stating that it went past the bugged block, after a while it went past that block. @luclu told me something interesting here. After that bug, much less nodes had past this block number. So it might take longer than usual to sync past this particular block.

If none of that works, a full resync should do the job (and that's proven already).

**Comment by mbxck** [comment]
@evertonfraga 

Hey - thanks for the quick reply - so basically leave it running and see what happens? Just to clarify, how do I do a full recync? Remember I can't launch the app, so I'm guessing it's deleting some files somewhere?

**Comment by woodaxed** [comment]
ok im thick as a brick when it comes to this  i downloaded ethereum.wallet.setup0.8.3.exe.zip
there is nothing in the zip other than the setup exe  theres no geth etc  so how do i sort this out 
i only mine and a small investor so atm im completely stuck
any help would be great

**Comment by mbbyc** [comment]
how can i get the geth.exe 1.4.2 windows 64 bits version?

**Comment by DripsukCal** [comment]
This is what my block sync is showing ..show you think If I just leave it ...It will eventually sync ? 

![capture](https://cloud.githubusercontent.com/assets/22319469/18668622/5a16c174-7f2e-11e6-84c6-12be03f73490.JPG)

**Comment by mbxck** [comment]
@mbbyc 

If you are uncertain, I wouldn't try replacing the geth manually. I've just checked and the new Mist wallet 0.8.3 IS syncing as @evertonfraga said it would - just very slowly and consuming quite a bit of memory. I'm going to leave it and see if it gets through the blocks before I do anything drastic. Will report back.

**Comment by luclu** [comment]
Please be patient until the network adjusts during the next hours.
>@luclu told me something interesting here. Since only a small portion of the nodes updated most nodes won't have the newer blocks available. This means up-to-date nodes are highly saturated and it might take some time to receive a useful peer. So it could take longer than usual to sync past this particular block.

**Comment by DripsukCal** [comment]
@evertonfraga @luclu 
I installed the "Ethereum.Wallet.Setup.0.8.3.exe.zip" update ..is this the correct update for Win64bit ..or should I have installed "Mist.Setup.0.8.3.exe.zip"

**Comment by mbxck** [comment]
The above sounds about right. From what I am experiencing it keeps jumping forward 100 blocks at a time, albeit slowly. It was also having trouble finding/connecting to peers before it started syncing.

**Comment by mbxck** [comment]
@DripsukCal 

That's the correct version for Win64bit you've installed.

**Comment by DripsukCal** [comment]
thanks @mbxck ...I leave for a few hours and see what happens

**Comment by woodaxed** [comment]
its been sat like this forever  
Downloading block 2,283,426 of 2,293,955

**Comment by mbxck** [comment]
@woodaxed 

When you say forever? How long? Mines about 30% the way through and it's been at least an hour. It also regularly stops for ages at a time.

**Comment by woodaxed** [comment]
its been stuck on that number since the attack on the nodes  i restarted  about an hour ago and its still not moved the bar at the bottom is empty and  i dont think its connected to any peers

**Comment by mbxck** [comment]
@woodaxed 
Are you definately running the new version? I.E. you've unzipped ethereum.wallet.setup0.8.3.exe.zip and you've run the main program? The other thing you need to be aware of, is as the version of geth.exe is new and will be executed from a new location to the older Mist wallet your Windows Firewall might block it.

**Comment by mbxck** [comment]
To clarify, to default location of the new Mist wallet on Win64 is 

%localappdata%\Mist\app-0.8.3\

The start menu for some reason I read isn't getting updated. So to make sure, restart your computer and past the above into Windows Explorer and run it from there.

**Comment by gfunksound** [comment]
I also have the same problem on Mac. I did all the terminal and console commands in Mist and got the correct outputs: I am running Geth 1.4.12 etc etc. Now the Mist app is just stuck with 12 peers and behind 10,659 blocks.

I also tried importing my contract wallets and they are stuck in the "importing" phase. Will the import complete once the blockchain syncs?

Thanks

**Comment by woodaxed** [comment]
i dont have windows explorer on my pc

**Comment by mbxck** [comment]
Hi, you must have Windows Explorer if you're running any version of the Windows OS. Can you paste that path into RUN or the address bar when you're in "Computer" or "My PC"?

**Comment by woodaxed** [comment]
ok found it in the end i seem to have 2 copies of it  both the same

**Comment by mbxck** [comment]
Happy to report I've now got the new Mist wallet fully sync'd and I've tested it by sending myself some Eth. So I guess many issues here can be put down to slow network responses today. Not having access to the Mist wallet has reminded me how important it is to ensure you're wallet is backed up properly. You should also make sure you remember your wallet password and test it from time to time by sending a fraction of an Eth to an exchange or whatever.

**Comment by woodaxed** [comment]
ok rebooted pc  found the right wallet exe and now its  Downloading block 2,283,474 of 2,294,300 so i think its now working  so many thanks mbxck  and sorry i sounded so thick

**Comment by mbxck** [comment]
@woodaxed 

Hey - no problem. I'm sure you have already but make sure you have good backups and store them in different places

@evertonfraga @luclu New Mist Wallet syncing great now thanks, but just a note. The geth version still appears to be labelled up wrong? See screengrab below.

![geth version](https://cloud.githubusercontent.com/assets/22319041/18673330/54027bce-7f43-11e6-8f81-5f25e0ed3944.png)

**Comment by gfunksound** [comment]
@mbxck I'm still stuck on block 2,283,417. I have all the latest versions of Geth and Mist. Should I just leave it here for a few hours?

**Comment by mbxck** [comment]
@gfunksound mine probably took about 3 hours all in all and seemed to take up a lot of memory whilst it was doing it (I've got a fairly fast machine on a good fibre connection here). Are you sure you are executing the correct Mist Wallet (the new one which presumably you've downloaded today). The reason I ask is because it sticks it in a new location and doesn't update any icons - very confusing for me at first.

**Comment by gfunksound** [comment]
@mbxck Yes, I am sure I am using the correct Mist Wallet, the one I downloaded today. I've just let my machine run for like 3 hours, and still no advancement beyond 2,283,417. Very frustrating. I'm trying to split my ETC from a contract wallet (why I need mist) so I can dump it before it goes to zero!

**Comment by adamvp** [comment]
My

**Comment by mbxck** [comment]
I'm not sure guys. Frustrating I know. Probably best to wait for one of the team to answer. All I can suggest (and what I did) is:

-- Make sure your firewall is switched off (it may not have a rule for the new geth.exe process and may be blocking it).
-- Restart your PC or kill the processes for "ethereum", "ethereum wallet" and "geth".
-- Ensure you are running "ethereum wallet" from %localappdata%\Mist\app-0.8.3\ which is where the latest version is installed.

**Comment by hautdoge** [comment]
Same issue. Windows 10 x64. 
Got the latest 0.8.3 and still having trouble since last night.
I tried 0.8.2 with the new geth, I tried a cross-compiled version that was out today and this latest one. Same results.
"Downloading block 2,283,424 of 2,298,056"

**Comment by gfunksound** [comment]
@mbxck are you sure I need to turn my firewall off? I've always had Mist and the wallet syncing with it on. I'm on a Mac, and I'm concerned about security turning it off

**Comment by mbxck** [comment]
@gfunksound  The advice I was giving was just for windows users and based on what I experienced. The problem was that the new geth.exe process was not recognised by my firewall and was silently blocked, preventing it access to the internet.

**Comment by CaptainSkywave** [comment]
I am running Ethereum Wallet directly from the folder app-0-8-3
It has synchronized from my previous chaindata folder, but is now stuck on 2,283,474/2,299,505
Also I have my keystore folder in the same folder as the chaindata, dapp and nodes folder, but when I Launch Application none of my wallets/accounts from the keystore folder is showing up. Matter of fact it launches as a blank account overview (You have no accounts yet) 
Also it is Geth 1.4.10 (Go) eventhough I have added geth.exe from app-0-8-3/nodes/geth/win-x64 to the firewall.
How do I get my keystore accounts/wallets to display? 

Further: I have now closed down 0-8-3 and opened 0-8-2 with all my wallets showing correctly.
So now I'll wait for further/new info or bug fixes to 0-8-3 to solve the stuck block issue and the keystore/wallets issue.

**Comment by adamvp** [comment]
In my case it takes over 10hours, despite of using --fast flag 0.o
0.8.2 with replaced geth

**Comment by gfunksound** [comment]
@adamvp how do you replace geth on 0.8.2? I am on a Mac

**Comment by usukan** [comment]
The new Ethereum Wallet won't sync past ....415 using the bundled Geth.  The bundled Geth alone won't sync - says issue with DAO fork verification and drops.

The new wallet works fine with Parity

I'll just wait till the bugs are fixed and use Parity in the meantime.

**Comment by bowjol** [comment]
@usukan how to use wallet with Parity?

**Comment by usukan** [comment]
@bowjol  there is a good video on how to use Mist/Ethereum Wallet with Parity

https://www.youtube.com/watch?v=sta-p5d1blQ

**Comment by bowjol** [comment]
@usukan thanks for the link

**Comment by luclu** [comment]
Please download the [`0.8.4` release](https://github.com/ethereum/mist/releases) - it comes bundled with geth `1.4.14`. Its sync speed will increase with time as the new caches are filled.

I will close this chapter for now. ;)
