### ISSUE TITLE
Node already in use?

### ISSUE THREAD

**Issue by LourensThalen** [ethereum/mist#1170]
Ethereum Wallet says (after I updated Geth) there already is an instance running. It's not, at least, not that I know of. 

#### System information
``````
Version: `0.8.3`
OS & Version: osx
Node type: `eth/geth(default)`
``````
Node log
``````
...o:169] closed db:/Users/lourens/Library/Ethereum/chaindata
I0920 12:38:34.555429 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to /Users/lourens/Library/Ethereum/chaindata
I0920 12:38:34.789713 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /Users/lourens/Library/Ethereum/dapp
I0920 12:38:34.793391 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0920 12:38:34.793599 eth/backend.go:201] Blockchain DB Version: 3
I0920 12:38:34.800108 core/blockchain.go:206] Last header: #2283417 [0b5e0167…] TD=62361310490897901759
I0920 12:38:34.800133 core/blockchain.go:207] Last block: #2283417 [0b5e0167…] TD=62361310490897901759
I0920 12:38:34.800140 core/blockchain.go:208] Fast block: #2283417 [0b5e0167…] TD=62361310490897901759
I0920 12:38:34.802958 eth/handler.go:113] blockchain not empty, fast sync disabled
I0920 12:38:34.816759 p2p/server.go:313] Starting Server
Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use
``````

**Comment by evertonfraga** [comment]
What's the result of `ps aux | grep geth`?

/Applications/Mist.app/Contents/nodes/geth/mac-x64/geth --testnet --fast --ipcpath /Users/ev/Library/Ethereum/geth.ipc

Maybe you could do a one-time process kill and start the 0.8.3 Mist version again.

**Comment by LourensThalen** [comment]
```
lourens           338  91.4  7.5 557122896 631932   ??  U    12:37PM 298:35.58 /usr/local/opt/ethereum/bin/geth -datadir=/usr/local/Cellar/ethereum/1.4.12/.ethereum
lourens          8579   0.0  0.0  2444056    780 s006  S+    7:14PM   0:00.00 grep geth
```

**Comment by luclu** [comment]
@LourensThalen as Ethereum-Wallet will try to connect to the default ipc path at `~/Library/Ethereum/geth.ipc` (if not changed via `--ipcpath`) it will think that no geth is running - as your datadir changed on the running system installation of geth:
```
/usr/local/opt/ethereum/bin/geth -datadir=/usr/local/Cellar/ethereum/1.4.12/.ethereum
```
Thus Ethereum Wallet will try to take control of the node management and start geth on its on which will, however, fail as the default udp port 30303 is already being used by the externally evoked geth instance.

So you will either have to change geth's `--datadir` to its default (you can simply omit it) or evoke Ethereum Wallet using the adjusted `--ipcpath` flag.
To accomplish the first you might have to edit geth's launchagents plist file as [this](https://github.com/ethereum/homebrew-ethereum/blob/master/ethereum.rb) suggests.

**Comment by luclu** [comment]
Closed as probably resolved.

**Comment by tcsiwula** [comment]
+1. I get the following from: ps aux | grep geth:
`=>ps aux | grep geth
timsiwula         2861   0.0  0.0  2424188    460 s000  R+    8:23AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn geth`
