### ISSUE TITLE
0.8.2 > 0.8.3 Wallets not showing

### ISSUE THREAD

**Issue by mehtaman** [ethereum/mist#1172]
#### System information
``````
Version: 0.8.2 > 0.8.3
OS & Version: Windows 10 x64
Node type: default
``````

Hi All,

Previously I have just downloaded the zip file, extracted to my desktop and run the Ethereum Wallet.
This new version (0.8.3) comes with an installer (which has installed fine for me).

I know that the .exe is now in the %localappdata%\Mist\app-0.8.3\ folder
When I open the app, none of my wallets have moved over to the new version.

When I check the GETH menu it still shows (1.4.10) - I believe this is a known issue.

How can I migrate my previous wallet info to the new app?

**Comment by mehtaman** [comment]
Rather quick update:
I just copied the app-0.8.3 folder from %localappdata%\Mist\app-0.8.3\ to my Desktop folder and the wallet now works... currently downloading the remaining blocks.

There must be a path variable still pointing to my Desktop folder in the GETH install.

**Comment by got3nks** [comment]
Same happening on OS X

**Comment by mrowles** [comment]
+1

**Comment by got3nks** [comment]
>  Edit: after updating blocks and restarting app once or twice, wallet now appears. 
Confirmed

**Comment by mehtaman** [comment]
what about any contract accounts?

**Comment by luclu** [comment]
Duplicate, closed in favour of https://github.com/ethereum/mist/issues/1174

---

> When I check the GETH menu it still shows (1.4.10) - I believe this is a known issue.

This is a [known issue](https://github.com/ethereum/mist/releases):
> Mist Menu still lists geth as 1.4.10 but it has been updated
