### ISSUE TITLE
which file to use for OSX

### ISSUE THREAD

**Issue by chalachala** [ethereum/mist#1173]
I need to download 0.8.3 as my sync is stuck like everyone else but I dont know which file is for OSX.  All past releases showed this clearly but now I have no idea.  Sorry for the IT challenged post.
<img width="827" alt="screen shot 2016-09-20 at 9 55 06 pm" src="https://cloud.githubusercontent.com/assets/18206874/18670969/2ee85d60-7f7d-11e6-810c-73b211a70284.png">

**Comment by SingularDTV** [comment]
dmg is for OSX.

**Comment by chalachala** [comment]
thank you.  what about the two Ethereum Wallet Setup zip folders?  Do I need to open one of them as well?

**Comment by ntpeters** [comment]
Nope. Just download the DMG, open it, drag the app into your Applications folder, and you're good to go!

**Comment by luclu** [comment]
Updated file names for clarity: https://github.com/ethereum/mist/releases/tag/0.8.3
