### ISSUE TITLE
Latest update doesn't carry over watched contracts and tokens.

### ISSUE THREAD

**Issue by danielmcclure** [ethereum/mist#1174]
#### System information
``````
Version: `0.8.3`
OS & Version: osx
Node type: `geth`
``````

The latest OSX update doesn't pull over watched contracts and tokens. Perhaps a path has changed somewhere? When I open 0.8.3 I only see Unicorns, however when I open the previous versions, even afterwards I see all of the custom tokens and contracts I've worked with. 

If this change is intentional there should probably be some warning or migration tool.

**Comment by sant9ga** [comment]
Win 8.1 - same issues.
1) missing all the accounts names (if 0.8.2 running it appears);
2) missing all watch token contracts;
3) mist and ethereum wallet installers installs the apps in the same folder and replaces each other, I was made to rename "Mist" folder in appdata after each installation.

**Comment by arjandeboer** [comment]
Win 10. same issue here. tnx for suggestion renaming mist folder.

**Comment by yrrv1980** [comment]
Hi Same Issue, 

  OSX 10.11.6, I can also see the contract in 0.8.2, but not on 0.8.3.

**Comment by MRGiacalone** [comment]
Same for the Windows version.
Previously, I had version 0.8.2 configured (Using --node-<geth switch>) so that the wallet uses another drive for the chain data and the keystore files.

In the "Mist" folder create a shortcut of "Ethereum Wallet.exe" click properties and in the target field after the last " at the end of the address, add --node-keystore=<address where your keystore is>

Example: "........./Ethereum Wallet.exe**"--node-keystore=C:\Users\UserName\AppData\Roaming\Ethereum**

**Comment by luclu** [comment]
I can confirm this to happen on macOS.
Pinging @hiddentao

**Comment by ntpeters** [comment]
I'm also seeing this issue on macOS 10.12 (missing account names and watch tokens).

The account names that I have set do not show in the wallet in Mist, but when clicking "Connect" the names are shown correctly in the account selection window. Selecting and authorizing an account doesn't change anything in the main UI; the names remain at their default values.

**Comment by luclu** [comment]
This issue has been identified. It is caused by the new installer which required to setup separate config folders for Ethereum Wallet and Mist - only retaining Mist's config folder used by both in release `<0.8.3`.
> Finally this the new installer split the config-folder into separate ones for **Ethereum Wallet** and **Mist**. As a result Ethereum Wallet won't display any previous *watched custom contracts and token* as well as *contract wallets* and *wallet names*. Although they are still available in Mist and Ethereum Wallet `< 0.8.3` you will need to re-added them manually to Ethereum Wallet `>= 0.8.3`.

**Comment by Dynamo77** [comment]
Right so, I'm a total idiot so feel free to treat me like one, but can you lay out a step by step guide to resolve then issue? I'm using OSx 10.11.6

**Comment by luclu** [comment]
I'm sorry @Dynamo77, here you go:

1. [download](https://github.com/ethereum/mist/releases) and open Ethereum Wallet `0.8.2`
2. Copy in a text-editor any of the following you are interested in keeping:
 - [wallet tab]
   - **accounts:** names
    - **contract wallet:** address and name
 - [contract tab]
   - **watched contracts:** address and ABI (interface)
    - **watched token:** address, name, symbol and decimal places
3. open Ethereum Wallet `0.8.4` and paste/import:
 - [wallet tab]
   - **accounts:** names
    - **contract wallet:** *add -> import*
 - [contract tab]
   - **watched contracts:** *watch contracts*
    - **watched token:** *watch token*

**Comment by Doncharly** [comment]
https://kiboplatform.net/DonKibo

https://kiboplatform.net/es/advantages.html

http://huaco2016.wixsite.com/kibo-ingledoncharly

*KIBO. Loto Registracion Only 10 Ethereum Unique Pay*
*Skype Carlos.Silva522*

2016-10-01 7:26 GMT-05:00 Luca Zeug <notifications@github.com>:

**Comment by Dynamo77** [comment]
thank you
