### ISSUE TITLE
0.8.3 Not working at all on my win 10 pc

### ISSUE THREAD

**Issue by wxyzsupermod** [ethereum/mist#1177]
#### System information
``````
Version: `0.8.3
OS & Version: windows
Node type: `eth/geth(default)`
``````
No app-mist.8.3 folder in %appdata%/Mist/
this is causing the blockchain not to sync at all as far as I can tell I have parity installed on the system not sure if that is the problem

**Comment by luclu** [comment]
Please try out the environment variable `%localappdata%`  instead of `%appdata%`.

**Comment by wxyzsupermod** [comment]
that was right where it was thanks but I still cant sync the blockchain and it isn't because it is slow I have left it for 8 hours and it is stuck on block  2,278,704

**Comment by evertonfraga** [comment]
Are you able to run geth separately?


--
Everton Fraga
21 999-279-999

**Comment by wxyzsupermod** [comment]
yes it gives me an unhandled trie error missing trie node bad block #2278705

**Comment by evertonfraga** [comment]
@wxyzsupermod interesting. I've opened an issue on go-ethereum repo, and I kindly ask you to give more details there, following their issue guideline.
