### ISSUE TITLE
New .deb installers cause Ethereum Wallet to wipe out Mist and vice versa

### ISSUE THREAD

**Issue by TrevorHilder** [ethereum/mist#1178]
#### System information
``````
Version: `0.8.3`
OS & Version: linux
Node type: `(default)`
``````
Under Ubuntu 16.04 LTS, the .deb installers cause Mist & Ethereum Wallet to wipe each other out in the /opt installation directory. This means you cannot have both of them installed at the same time.

Mist also shows with a ? in the icon in the dock, whereas Ethereum Wallet looks normal.

**Comment by SeanBannister** [comment]
Confirmed that this also happens in Windows.

**Comment by luclu** [comment]
fixed with https://github.com/ethereum/mist/releases/tag/v0.8.4
