### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by behazin** [ethereum/mist#1179]
I get time out in geth.

![geth-time-out](https://cloud.githubusercontent.com/assets/210366/18709533/7e686bb0-800d-11e6-8534-f6e2c36e43e6.PNG)

**Comment by luclu** [comment]
@behazin the timeout message you find in the terminal output is actually unrelated to the stalling synchronization.

---
Crosspost from https://github.com/ethereum/mist/issues/1169#issuecomment-248276331:

Please be patient until the network adjusts during the next hours.
>  @luclu told me something interesting here. Since only a small portion of the nodes updated most nodes won't have the newer blocks available. This means up-to-date nodes are highly saturated and it might take some time to receive a useful peer. So it could take longer than usual to sync past this particular block.
