### ISSUE TITLE
Mist 0.8.3 Status gets stuck saying elapsed time since last block is 2 hours

### ISSUE THREAD

**Issue by TrevorHilder** [ethereum/mist#1183]
#### System information

```
Version: `0.8.3`
OS & Version: linux
Node type: `geth`
```

I am running Mist under Ubuntu 16.4 LTS, having started up geth from terminal with the same command line as Mist would have used, syncing on the Morden Test-Net.

The status in the bottom left corner updates all values correctly except Elapsed Time Since Last Block. This keeps getting stuck as 2 hours, even though everything else is working perfectly and the blockchain is properly synced:
![mist status](https://cloud.githubusercontent.com/assets/3775879/18744694/f436174e-80b6-11e6-9211-96202212809c.png)

**Comment by zenflower** [comment]
same here. stuck at 'one day' or actually 'een dag' in Dutch.

Mist 0.8.7 / Geth / Windows 10

**Comment by evertonfraga** [comment]
Should be fixed in v0.8.x series. If that persists, please open a new issue.
