### ISSUE TITLE
[Noob here] Can't get ethers out of the"etherbase" deskptop wallet. 

### ISSUE THREAD

**Issue by victor900** [ethereum/mist#119]
somenoe told here people could help me with my problem: i have 119 ethers on this wallet. 

this is what happend. I  download and start the wallet, the latest version. I did not programmed anything (if i did i dont remember) keep in mind this happened last week.  after everything was install i decided to buy some ethers, i bought a few and sended them to my desktop wallet address [Ethebase]. after a few days i wanted it to send a few ethers to a online wallet but i couldn't because it was asking me for password, a password that i never created. so my ethers are trap in my desktop until someone help understand how to get them out. 

Thanks and excuse my English.

**Comment by ColinAllmanGame** [comment]
1: Have you verified the funds have arrived in the target address?
2:Try using a blank password to unlock.
3:Make sure your desktop node is up to date with the current block. ~885,000

**Comment by frozeman** [comment]
If the password question comes up when you start the wallet, then youre using the CPP node in the background, which requires a Masterpassword (which can also be empty).

Otherwise your accounts should have a password when you created them

**Comment by victor900** [comment]
@ColinAllmanGame yes i did verify that. i tried the blank password long ago it did not work, my node is the thing that its always loading when you open the wallet right? then yes its up to date. @frozeman no the password question come up when i want to send eths to another address. Could a password still be created after the initiation of the wallet if I never created one? or may be there is a chance that i did make a pasword and just forgot about it. in that case could I still recover those eths.? Thanks both you. hopefully we can recover those eth.. if not it just will be another learning experience. peace :+1:

**Comment by frozeman** [comment]
Try creating another account and send some funds there...

**Comment by victor900** [comment]
@frozeman so i guess my eths will be lost them because i wont be able to send the eths because it will ask for a password.

**Comment by victor900** [comment]
@frozeman so sorry i just forgot the password. sorry again bro. it was my sister fault but thats another story. I have one last question, i just tried to send an eth to another address, nothing happened and it has been 1 hour and counting. it says "0 out 12" confirmations.  why you think this is happening? thankss

**Comment by frozeman** [comment]
It depends on the network speed, but normally it should not take more than 1minute for the first block. The other confirmations will take 12 blocks, so 17s * 12
