### ISSUE TITLE
0.8.3 - No Linux zip files, only deb

### ISSUE THREAD

**Issue by emelbardis** [ethereum/mist#1190]
This release dropped Linux .zip files from the release and now provides .deb files. I run Fedora and it was really easy to extract the .zip and move the directory to home and change my launcher. Is there a specific reason why you switched from zip to deb?

**Comment by luclu** [comment]
As the current situation for rpm packages requires conversion via tools like alien - which is a hassle, native rpm packages can and should be available via https://www.npmjs.com/package/electron-builder starting with the next version.

**Comment by kixi** [comment]
Could you also provide the compiled linux .zip files again, (additionaly to .deb and .rpm)?

**Comment by luclu** [comment]
@kixi yes! This is planned: https://github.com/ethereum/mist/issues/1182

**Comment by luclu** [comment]
Zips are available now again. https://github.com/ethereum/mist/releases/tag/v0.8.4
