### ISSUE TITLE
HELP — ethereum trapped in Mist contract

### ISSUE THREAD

**Issue by pietdion** [ethereum/mist#1191]
In March 2016 created a smart contract/wallet contract in Mist (I’ll call it a “contract” from now).  
I endowed  the contract with about 1  ETH.   The aim was for me to “experiment” to try and understand how these things work.

In August, after one of the Mist wallet updates  I got the  following message in RED

**This smart contract wallet has outdated code and is subject to phishing attacks**

I tried to follow the linked instructions to “update” this contract but was unsuccessful.

I then posted a question at https://github.com/ethereum/mist/issues/1071

The response I got did not solve my issue as there was nothing to “click” on in my system:

Version: `0.8.1`
OS & Version: OSX 10.11.5
Node type: `geth 1.4.10`

Anyway, I let it rest, hoping the issue would resolve itself with new updates to Mist etc.

I recently downloaded Mist 0.8.3 but in this version I don’t even see the contract.

I’ve used the blockchain explorer at  https://etherchain.org and typed in the contract address.
The blockchain explorer confirms the balance and previous transactions, as I remember them.

Can anybody point me to how I recover the funds inside this contract.  I have the Mist keys etc which created the original contract.  Other accounts in my Mist wallet (ie non contracts) work ok.

I don’t care about the small amount of  ETH trapped inside the contract but I would like to understand this issue more.   Inexplicably and unexpectedly  losing ETH inside Mist does not inspire confidence.

**Comment by alexvandesande** [comment]
Hi, we're sorting through old issues and only now I found saw yours. I hope you have sorted it by now, but if you didn't, it's still possible to do it:

Go through your old accounts on etherscan.io and find the one creating your wallet, this will have your old address. Then go to https://wallet.ethereum.org/account/new and add import wallet. Then you'll be able to move your money out to a newer account elsewhere.

**Comment by pietdion** [comment]
Thank you!   Much appreciated.
