### ISSUE TITLE
Mist 0.8.3 sync stuck at 2,315,527 of 2,316,661

### ISSUE THREAD

**Issue by molitar** [ethereum/mist#1195]
#### System information
``````
Version: `0.8.3`
OS & Version: windows 7 ultimate
Node type: `eth/geth(default)`
``````
Due to sync failing again I deleted the chaindata with geth --removedb and than re-launched MIST and it started syncing from scratch.  It reached 2,315,527 and has been stuck there for over 15 minutes now not moving.

- Screenshots
https://i.sli.mg/DS4pEp.png

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
https://i.sli.mg/mlWw8D.png

[node.zip](https://github.com/ethereum/mist/files/491002/node.zip)

**Comment by behazin** [comment]
I have same issues, How to fix it?
![mist-11](https://cloud.githubusercontent.com/assets/210366/18807010/8997ca10-8249-11e6-8b5b-dd3efcd3eb8b.png)

**Comment by marienuac** [comment]
i cant even connect to peers this update wtf?

**Comment by mbxck** [comment]
Same problem. Deleted the chaindata, started again - it looked like it was going to sync all the way, but now stopped at 2,318,975 of 2,320,153. The mist wallet doesn't seem to have been the same since the memory leak problem last week.

:(

**Comment by maraciuca66** [comment]
Same here, stuck at Downloading block 2,321,754 of 2,322,943.

**Comment by marienuac** [comment]
i deleted blockchain, opened port 30303 and ran geth with `geth --datadir "E:\Ethereum" --fast --cache 1024 --targetgaslimit 1500000 --gasprice 20000000000 --maxpeers 50` waited like a min till i saw "started blockchain sync". Without port 30303 open it would not even begin to sync........

then i started wallet with: `"ethereum wallet.exe" --fast --cache 1024 --node-datadir="E:\Ethereum" --node-keystore="E:\Ethereum"` waited overnight, because it would get stuck at completly random blocks like 400,000~ 1.6m~ etc. and viola the dam thing is fully synced.

However i closed/opened the wallet again and waited a bit and its at 1.77GB mem usage ??? still its not 8 freakin gb like last time lol.

**Comment by EtherTravels** [comment]
Version: `0.8.3`
OS & Version: macOs Sierra
Node type: GetH 1.4.10 (Go)

I have a similar same problem. Ethereum Wallet downloads the blocks very fast until a certain block and then it is moving forward very slow (one block every 5 minutes) and the node.log shows a lot of timed out DAO:

**I0925 21:49:57.284871 eth/handler.go:290] Peer 38d300dfc40cde37 [eth/63]: timed out DAO fork-check, dropping**

![bildschirmfoto 2016-09-25 um 21 48 37](https://cloud.githubusercontent.com/assets/22428169/18815687/2af8d4fa-836a-11e6-8737-05a4f97f9d4b.png)

Would it make sense to change the Ethereum Node Setting to **ETH 1.3.0 (C++)**

**Comment by alxcarrasco** [comment]
Same here ... Spent whole day downloading previous blocks and moving amazingly slow ... after almost 8 hours trying to catch up with the remaining blocks still not there. Not finishing syncing even when "chaindata" was deleted and started sync from zero.

Anyone knows what's going on?

Thanks.

![screen shot 2016-09-26 at 7 28 05 pm](https://cloud.githubusercontent.com/assets/22308325/18832674/77c46a32-841f-11e6-95bc-4c6027f0e0c9.png)

**Comment by karalabe** [comment]
There's a new attack ongoing. It has been averted in Geth 1.4.13. If you're running Linux or OSX, you can replace your bundled geth from the wallet with one from https://github.com/ethereum/go-ethereum/releases/tag/v1.4.13 . Windows builds are coming soon too.

**Comment by alxcarrasco** [comment]
@karalabe Appreciated Man! It's working normally now. Thanks!

**Comment by subfactory** [comment]
Any solution or trick to solve this.
I'm stuck in 2,283,416 of 2,335,913

**Comment by luclu** [comment]
Uh, wait for now. We should be able to push a fixed installer + the new-new geth today.

**Comment by Mordong** [comment]
passed through 2.335.000 but really slowly with geth 1.4.13

**Comment by EtherTravels** [comment]
Same here. I could get through the blocks which recently made trouble but it is still really slow with geth 1.4.13

**Comment by cryptojunky** [comment]
Still an ongoing issue. Yesterday I deleted chaindata. Re-downloaded block chain and everything was working fine. Start up today and stuck again. Same message in log file. Timed out DAO fork-check, dropping.

**Comment by luclu** [comment]
@/all please download and try the `0.8.4` release - it comes bundled with geth `1.4.14`. Its download speed will increase with time as the new caches are filled.

**Comment by cryptojunky** [comment]
Its the same issue with 0.8.4

**Comment by marienuac** [comment]
im having no trouble with 0.8.4/1.4.14 release

try syncing with --fast option but delete old chain first

**Comment by luclu** [comment]
Good to hear that, @marienuac. Also Mist/Ethereum Wallet internally uses the `--fast` flag. Though it only works for the first run on an empty `chaindata` folder - see [here](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555).
