### ISSUE TITLE
No node connection over TOR

### ISSUE THREAD

**Issue by octaviogordonNRW** [ethereum/mist#1197]
Lots of people that uses cryptocurrency does uses TOR and so do I, currently it is not possible connect to any nodes and so download blockchain.

**Comment by D-Nice** [comment]
This is moreso an issue between ethereum clients using UDP and TOR not supporting UDP. One alternative is to use a light client like metamask over the browser with TOR.

**Comment by luclu** [comment]
I will close this in favour of https://github.com/ethereum/mist/issues/455.
