### ISSUE TITLE
 We can't estimate your gas usage properly, as you need at least 1 ether in your account.

### ISSUE THREAD

**Issue by newmzy** [ethereum/mist#1207]
I'm using the 0.8.3 wallet and I can't send any ETH at all. The main account has over 300 ETH in it. If I look at the developer console there is an error and I think it's this one:

 Failed to load resource: file:///sockjs/info?cb=ts8lntuekr  :ERR_FILE_NOT_FOUND

I could never get Geth to run in WIndows properly so I'm using parity in "geth mode"

```
Version: 0.8.3
OS & Version: windows 10
Node type: Parity in Geth mode
```

**Comment by luclu** [comment]
Could you please upload the [node.log](https://github.com/ethereum/mist/issues/new) (as well as a screenshot of the wallet interface)?

**Comment by newmzy** [comment]
![node_log](https://cloud.githubusercontent.com/assets/17661766/18832307/24b23a9c-841d-11e6-8a41-9cc9ba160935.jpg)
![wallet01](https://cloud.githubusercontent.com/assets/17661766/18832313/2c96bfda-841d-11e6-9541-d49e4ad6be64.jpg)
![wallet02](https://cloud.githubusercontent.com/assets/17661766/18832317/322c3f6a-841d-11e6-8a47-2e24536d4d79.jpg)
![wallet03](https://cloud.githubusercontent.com/assets/17661766/18832319/37b9d852-841d-11e6-9e32-3738c1e3bac3.jpg)

I hope these screen shots are what you need - If the node.log exists as a file somewhere rather than just that window screenshot, where is it?

**Comment by woodaxed** [comment]
Im having the same problem  with  0.8.3   and also now 0.8.4  windows 7  i was using geth but it became impossible to sync so switched to parity  i normally empty my wallet and now im having to hold a least 1 eth in it  makes the send all button useless

**Comment by newmzy** [comment]
I have over 300 in my wallet but it still doesn't send anything.
I tried 0.8.4 tonight and it's just the same problem.
Are any developers going to respond to this?

**Comment by woodaxed** [comment]
i just synced my wallet with parity and it wouldnt send any coins shut parity down and restarted my wallet and it showed i was around 5,000 blocks behind as if its not been syncing for the last few days  since i prolly switched to using parity

**Comment by Kozzi07** [comment]
Use latest parity 1.3.2. Bug is fixed.
