### ISSUE TITLE
Node tries to install modules for mac and win on linux.

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#1208]
#### System information
``````
Version: `0.8.3`
OS & Version: linux `4.7.4` (ArchLinux)
``````

Running `npm install` on a linux host, tries to install the 7zip binary packages for mac and win which are not supported:

    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^1.0.0 (node_modules/7zip-bin/node_modules/7zip-bin-win):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
    npm WARN tslint@3.15.1 requires a peer of typescript@>=1.7.3 but none was installed.
    npm ERR! Linux 4.7.4-1-ARCH
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
    npm ERR! node v6.6.0
    npm ERR! npm  v3.10.8
    npm ERR! code EBADPLATFORM

    npm ERR! notsup Unsupported platform for 7zip-bin-osx@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    npm ERR! notsup Valid OS:    darwin
    npm ERR! notsup Valid Arch:  any
    npm ERR! notsup Actual OS:   linux
    npm ERR! notsup Actual Arch: x64

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/user/some/path/mist-git/npm-debug.log

I'm running `npm install` because I want to run a `gulp mist --platform linux` afterwards. I am not interested in windows or macos binaries. Thanks.

Tail of `npn-debug.log`:

    49079 silly runTopLevelLifecycles Starting
    49080 silly install runPreinstallTopLevelLifecycles
    49081 silly preinstall Mist@0.8.3 /home/user/some/path/mist-git/Mist-b7135eb3
    49082 info lifecycle Mist@0.8.3~preinstall: Mist@0.8.3
    49083 silly lifecycle Mist@0.8.3~preinstall: no script for preinstall, continuing
    49084 silly executeActions Starting
    49085 silly install executeActions
    49086 silly doSerial global-install 0
    49087 silly doParallel fetch 823
    49088 silly rollbackFailedOptional Starting
    49089 silly rollbackFailedOptional Finishing
    49090 silly runTopLevelLifecycles Finishing
    49091 silly install printInstalled
    49092 warn optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@^1.0.0 (node_modules/7zip-bin/node_modules/7zip-bin-win):
    49093 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@1.0.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
    49094 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    win32
    49094 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
    49094 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
    49094 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
    49095 warn tslint@3.15.1 requires a peer of typescript@>=1.7.3 but none was installed.
    49096 verbose If you need help, you may report this error at:
    49096 verbose     <https://github.com/npm/npm/issues>
    49097 verbose stack Error: Unsupported platform for 7zip-bin-osx@1.0.0: wanted {"name":"7zip-bin-osx","description":"7-Zip OS X binary","version":"1.0.0","license":"MIT","repository":{"type":"git","url":"git+https://github.com/develar/7zip-bin.git"},"files":["7za","index.js"],"os":["darwin"],"readme":"ERROR: No README data found!","readmeFilename":"README.md","bugs":{"url":"https://github.com/develar/7zip-bin/issues"},"homepage":"https://github.com/develar/7zip-bin#readme","_id":"7zip-bin-osx@1.0.0","_shasum":"25fa84ebe9a30bb646a065d83e47e1e456ff79a9","_resolved":"https://registry.npmjs.org/7zip-bin-osx/-/7zip-bin-osx-1.0.0.tgz","_from":"7zip-bin-osx@>=1.0.0 <2.0.0","_inCache":true,"_requested":{"raw":"7zip-bin-osx@https://registry.npmjs.org/7zip-bin-osx/-/7zip-bin-osx-1.0.0.tgz","scope":null,"escapedName":"7zip-bin-osx","name":"7zip-bin-osx","rawSpec":"https://registry.npmjs.org/7zip-bin-osx/-/7zip-bin-osx-1.0.0.tgz","spec":"https://registry.npmjs.org/7zip-bin-osx/-/7zip-bin-osx-1.0.0.tgz","type":"remote"},"_spec":"7zip-bin-osx@https://registry.npmjs.org/7zip-bin-osx/-/7zip-bin-osx-1.0.0.tgz","_where":"/home/user/some/path/mist-git","_args":[[{"raw":"7zip-bin-osx@https://registry.npmjs.org/7zip-bin-osx/-/7zip-bin-osx-1.0.0.tgz","scope":null,"escapedName":"7zip-bin-osx","name":"7zip-bin-osx","rawSpec":"https://registry.npmjs.org/7zip-bin-osx/-/7zip-bin-osx-1.0.0.tgz","spec":"https://registry.npmjs.org/7zip-bin-osx/-/7zip-bin-osx-1.0.0.tgz","type":"remote"},"/home/user/some/path/mist-git"]],"_shrinkwrap":null,"dependencies":{},"devDependencies":{},"optionalDependencies":{}} (current: {"os":"linux","cpu":"x64"})
    49097 verbose stack     at checkPlatform (/usr/lib/node_modules/npm/node_modules/npm-install-checks/index.js:45:14)
    49097 verbose stack     at thenWarnEngineIssues (/usr/lib/node_modules/npm/lib/install/validate-args.js:41:5)
    49097 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
    49097 verbose stack     at checkEngine (/usr/lib/node_modules/npm/node_modules/npm-install-checks/index.js:10:20)
    49097 verbose stack     at module.exports.isInstallable (/usr/lib/node_modules/npm/lib/install/validate-args.js:38:3)
    49097 verbose stack     at actions.(anonymous function) (/usr/lib/node_modules/npm/lib/install/actions.js:52:14)
    49097 verbose stack     at execAction (/usr/lib/node_modules/npm/lib/install/actions.js:114:7)
    49097 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    49097 verbose stack     at Array.forEach (native)
    49097 verbose stack     at /usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    49098 verbose pkgid 7zip-bin-osx@1.0.0
    49099 verbose cwd /home/user/some/path/mist-git
    49100 error Linux 4.7.4-1-ARCH
    49101 error argv "/usr/bin/node" "/usr/bin/npm" "install"
    49102 error node v6.6.0
    49103 error npm  v3.10.8
    49104 error code EBADPLATFORM
    49105 error notsup Unsupported platform for 7zip-bin-osx@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
    49106 error notsup Valid OS:    darwin
    49106 error notsup Valid Arch:  any
    49106 error notsup Actual OS:   linux
    49106 error notsup Actual Arch: x64
    49107 verbose exit [ 1, true ]

**Comment by luclu** [comment]
@5chdn could you please give https://github.com/ethereum/mist/pull/1194 a try?

**Comment by 5chdn** [comment]
@luclu #1194 fixes this. but re-introduces this:

     ERROR: YOUR NODES NEED TO BE UPDATED run $ gulp update-nodes

see here: https://github.com/ethereum/mist/issues/987#issuecomment-235411229

**Comment by luclu** [comment]
Merged.
