### ISSUE TITLE
New geth version will not accept --nat=none

### ISSUE THREAD

**Issue by newmzy** [ethereum/mist#1209]
#### System information
``````
Version:  latest
OS & Version: windows 10
Node type: geth
```
For a long time the only way for me to use the Mist wallet has been to run geth first with (at least) the switches 

--nat=none --rpc

...then run the wallet. 

Since all the problems with attacks and the resulting releases of new versions, if I try using the --nat=none switch, Geth will not run properly at all, and I get all the crazy output in the attached photo.

I have (as described in a probably related issue) tried syncing with Parity in Geth mode (because I don't understand how to send ETH using Parity itself), but then I can't actually send any ETH from my Mist wallet because it can't work out the gas price (or something).... This is driving me crazy.
![geth_output](https://cloud.githubusercontent.com/assets/17661766/18840315/bfea21b4-8440-11e6-9089-bd23c0d5685e.jpg)

**Comment by luclu** [comment]
@newmzy you seem to encounter some bug in geth. Please repost this on the [geth repo](https://github.com/ethereum/go-ethereum/issues) and add it's version string.

**Comment by newmzy** [comment]
I did report this on the geth repo and no one seems interested

**Comment by luclu** [comment]
Let it sit there for some while, the go-team is quite busy atm. Please try the new [`0.8.4` release](https://github.com/ethereum/mist/releases)? It comes bundled with geth `1.4.14`.

Though I will close your issue on this bug-tracker, as geth's tracker does fit it way better.

**Comment by newmzy** [comment]
Actually the problem I was trying to solve ultimately was solved by a Parity bug fix.
