### ISSUE TITLE
ethereum wallet 0.8.3 can't compile multisignature contract

### ISSUE THREAD

**Issue by rmeruane** [ethereum/mist#1218]
#### System information

```
Version: 0.8.3
OS & Version: osx
Node type: geth
```

This version of ethereum wallet can't compile multisignature contract (https://raw.githubusercontent.com/ethereum/dapp-bin/master/wallet/wallet.sol)

You get the following error:

```
 Return value of low-level calls not used.
            _to.call.value(_value)(_data);
            ^---------------------------^
, 
```

<img width="1196" alt="screen shot 2016-09-23 at 3 42 47 pm" src="https://cloud.githubusercontent.com/assets/711836/18886917/5efceae8-84c8-11e6-91ee-11d08133fa18.png">

**Comment by evertonfraga** [comment]
might be related to https://github.com/ethereum/mist/pull/1239

**Comment by luclu** [comment]
@rmeruane is there any relieve with release `0.8.6`?

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
