### ISSUE TITLE
After wallet/geth update my eth is 0 (zero)

### ISSUE THREAD

**Issue by zerosflavio** [ethereum/mist#1220]
``````
Version: `0.8.3`
OS & Version: windows 10
Node type: `geth(1.4.13)`
``````

After update my wallet my ether is 0.
(im kind new at forum but i have been mining for about 1month already).

Is it because i had to start sync my blockchain again and yet not sync? (i guess this is not the case because my wallet has nothing to do with the blockchain right?)

i checked my eth at etherscan.io and my eth is there but why is it missing on my wallet?

![image](https://cloud.githubusercontent.com/assets/22486843/18897888/2ebddfc2-8504-11e6-9585-b68688bde723.png)

Thanks alot and sorry if for any trouble. (Sorry my english is a lil rusty.)

**Comment by obscuren** [comment]
If downloaded a new geth and removed your chain directory (did you?) it
is the reason why you're seeing at Ether balance of 0. For it to give
you an accurate number in your account, the node must by fully synced
with the network.

**Comment by zerosflavio** [comment]
After i updated the wallet and the geth (1.4.13), my blockchain started from zero (dont know why though). 
The funny thing is the "dao timeout" on blockchain after those timeouts, the sync goes too slow so i had to start the fast sync 3 times from the beginning.

Like i said im still new on mining (1month is barely nothing), i search alot about mining but i didnt find anything about this (0 eth "problem") and i found that those "dao timeout" problems are "normal".
I closed the  thread coz i was having trouble to find why my wallet was 0,but after talking to some friends they explain to me what was it.

Thanks for reply anyway!!!
