### ISSUE TITLE
Stalled at Block 2,306,336

### ISSUE THREAD

**Issue by coorce** [ethereum/mist#1221]
#### System information
``````
Version: `0.8.3`
OS & Version: osx
Node type: `eth/geth(default)`
``````

I hadn't opened 0.8.2 for a few days. When I did, I saw a message about 0.8.3. I downloaded the OSX version and installed. Rather than overwriting 0.8.2, it created a new install, with new accounts. I was able to get past the last stall, but now I'm stalled at 2,306,336. Neither 0.8.2, which has my ETH, nor 0.8.3, which has no ETH in it, can get past that block, for several days now.

Any suggestions?

**Comment by luclu** [comment]
Please download the [`0.8.4` release](https://github.com/ethereum/mist/releases) - it comes bundled with geth `1.4.14`. Its sync speed will increase with time as the new caches are filled.
