### ISSUE TITLE
ETH goes to a different account than the one I assign ref: #1152.

### ISSUE THREAD

**Issue by Dynamo77** [ethereum/mist#1235]
Hi,

I'm opening up a new issue for this as I still have not received an answer to help me resolve it. Please refer #1152 for the screen shots.

I've tried to send ETH to my coin base account a few time, but when I go to confirm the transaction with password a different account shows up to the one I assign just previous to that. Anyone know why its choosing a different account?

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log` 
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by luclu** [comment]
@Dynamo77 should you use the *replaySplit*  feature as listed in #1152, try to split to a new account and send to coinbase from that one instead of directly splitting to coinbase.
