### ISSUE TITLE
Cannot send from Mist wallet

### ISSUE THREAD

**Issue by pimmesz** [ethereum/mist#1237]
I seem to be unable to send DGD from my mist wallet. It shows an empty 'from' adres and I cant sellect any of my wallets! Does anyone know what could cause this issue?

![dyi50mf](https://cloud.githubusercontent.com/assets/7393354/18993332/f844aaa4-8722-11e6-8e1c-8bf25b8bcbc1.jpg)
#### System information

```
Version: `0.8.4`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
```
#### Please check the **already existing** issues to keep duplicates at a minimum.

Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:
- Screenshots
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
- Log files (Go to `menu -> accounts -> backup -> application data` and upload as zip-archive):
  -   osx: `~/Library/Application Support/Mist/node.log` 
  -   windows: `%APPDATA%/Roaming/Mist/node.log`
  -   linux: `~/.config/Mist/node.log`

**Comment by luclu** [comment]
pinging @hiddentao

**Comment by edwinoonk** [comment]
Same problem here trying to send ether from wallet contract. The from field cannot be populated. I'm using 0.8.7

**Comment by evertonfraga** [comment]
Closing upon inactivity and lack of details from OP. Please reopen if needed.

**Comment by Redgar13** [comment]
Same problem here. Mist 0.9.3, win64, web3.personal.listAccounts returns all the addresses I have.
