### ISSUE TITLE
Fix the installer it installs like malware would!

### ISSUE THREAD

**Issue by molitar** [ethereum/mist#1238]
Right now I think this software installer could be technically called a malware! 

No disclaimer that you are going to install software with no choice of where to install it!  No agreement to continue or cancel it just starts to install.  No install log so can not even see what did install and it does not even show up in the installed programs list.  This is the same type of practice that malicious malware uses!  

I can't trust this installer and did a system restore!  This installer for all I know could install anything behind the scenes and I would not know!  This is a horrible practice and will make anyone that practices security shy away from this software!

Give us back a zip file or fix the installer because as someone that works in the IT industry I can not safely install this software!

**Comment by SteffenIvanhoe** [comment]
I can only agree. Mist currently is unusable. Trust is no longer possible!

**Comment by Doncharly** [comment]
https://kiboplatform.net/DonKibo

https://kiboplatform.net/es/advantages.html

http://huaco2016.wixsite.com/kibo-ingledoncharly

*KIBO. Loto Registracion Only 10 Ethereum Unique Pay*
*Skype Carlos.Silva522*

2016-10-02 5:23 GMT-05:00 SteffenIvanhoe <notifications@github.com>:

**Comment by larrysmith1000** [comment]
An installer is a good first step forward toward usability by novice users.  However, I agree that there is a major trust issue here.  The integrated approach makes things much less transparent.  That doesn't mean it shouldn't be an integrated installer; it just means some steps should be taken to assure the user of what is being installed where.  I think there should be at a minimum (even for pre-release):

1. a way to uninstall
2. a dialog indicating what is going to be installed.
3. a dialog that allows the user to specify location of installation
4. if geth is integrated, there should be a way to access geth from the command line, and an option to run geth independently of ethereum wallet.

E Wallet developers are doing great work, and I trust them, but if I were new to the wallet project, I would not touch this thing the way the installer has been packaged to execute.

**Comment by evertonfraga** [comment]
Fixed on 0.8.9.
