### ISSUE TITLE
How to uninstall my old Mist browser and install a new one from scratch as i lost my password.

### ISSUE THREAD

**Issue by keznerve** [ethereum/mist#124]
i have lost the password for mist , i am happy to dump that wallet and get more gas, but when i download a new wallet and install it, i have the same problem , it asks for my password , i want to start again from scratch. 

Thanks

**Comment by frozeman** [comment]
delete the `~/Library/Application Support/Mist` folder, or on windows `%APPDATA%/Roaming/Mist`

**Comment by keznerve** [comment]
thanks

**Comment by murtyk** [comment]
Delete all the files in ~/Library/Ethereum/testnet/keystore

**Comment by evertonfraga** [comment]
Just a reminder, for the internet citizens: 

IF YOU DELETE YOUR KEYSTORE FOLDER, YOUR ACCOUNTS WILL BE THROWN AWAY.
