### ISSUE TITLE
Ethereum-Wallet 0.8.4 Re-Add Account

### ISSUE THREAD

**Issue by RongxinZhang** [ethereum/mist#1240]
#### System information

```
Version: `0.8.4`
OS & Version: osx
Node type: `geth`
```
#### How to Re-Add Accounts and contracts to Ethereum-Wallet 0.8.4

Might be a noob question, but I just downloaded the latest Ethereum-Wallet 0.8.4.

It stated in the release that we will need to _Re-Add_ our accounts in order to see them.
https://github.com/ethereum/mist/releases/tag/v0.8.4

How would I do this?

Thank you 👍

**Comment by luclu** [comment]
@RongxinZhang, please follow these steps:

1. [download](https://github.com/ethereum/mist/releases) and open Ethereum Wallet `0.8.2`
2. Copy in a text-editor any of the following you are interested in keeping:
 - [wallet tab]
   - **accounts:** names
    - **contract wallet:** address and name
 - [contract tab]
   - **watched contracts:** address and ABI (interface)
    - **watched token:** address, name, symbol and decimal places
3. open Ethereum Wallet `0.8.4` and paste/import:
 - [wallet tab]
   - **accounts:** names
    - **contract wallet:** *add -> import*
 - [contract tab]
   - **watched contracts:** *watch contracts*
    - **watched token:** *watch token*

**Comment by RongxinZhang** [comment]
@luclu Thanks, will give this a try ✌️ 

*Note:*
- I was transferring from `0.8.1`
- I also found that accounts from `0.8.1` showed up in `0.8.4` after creating a new account with a "secure" password in `0.8.4`

**Comment by evrotrash** [comment]
where is the import function in ethereum wallet win64??

**Comment by Doncharly** [comment]
https://kiboplatform.net/DonKibo

https://kiboplatform.net/es/advantages.html

http://huaco2016.wixsite.com/kibo-ingledoncharly

*KIBO. Loto Registracion Only 10 Ethereum Unique Pay*
*Skype Carlos.Silva522*

2016-10-02 16:54 GMT-05:00 evrotrash <notifications@github.com>:

**Comment by gcolbourn** [comment]
"open Ethereum Wallet 0.8.4 and paste/import:
[wallet tab]
accounts: names
contract wallet: add -> import"

How exactly do you do this? I can't see an import button or menu option.

**Comment by cryptojunky** [comment]
Try selecting Develop - Ethereum Node - Geth even if its selected already. It seemed to bring the wallet address & balance back up.

**Comment by gcolbourn** [comment]
Thanks, that works, but all the account names are gone, they are just "Account 1", "Account 2" etc. Good job I made a note of them before, otherwise I'd be stuck!

**Comment by prashantprabhakar** [comment]
I am facing same issue in latest 0.8.5 version of Ethereum wallet. Previous transactions and accounts are not visible, even if I create a new account,it does not appear in Mist. However if I check console of Mist and check 

> web3.eth.accounts , It displays all my accounts including newly created account. I could not find any import tab in this version. How to manually add accounts and transactions in 0.8.5?

**Comment by UMLAUTaxl** [comment]
Is this also working if I upgrade from 0.8.2 to 0.8.10? Or do I need 0.8.4?
My eth are shown in 0.8.2 but not in 0.8.10. Name and address of account are exactly the same.
(Blockchain is not yet up to date.)
