### ISSUE TITLE
Wallet 0.8.4 with latest geth got really slow again

### ISSUE THREAD

**Issue by Mordong** [ethereum/mist#1244]
#### System information
``````
Version: `0.8.4`
OS & Version: Windows10 x64
Node type: `geth`
``````
Again sync become very slow and taking eventually up to 99% of CPU for geth process

![clipboard01](https://cloud.githubusercontent.com/assets/17006970/19020037/1aa8e504-88a6-11e6-8b22-9121073527da.jpg)

**Comment by Mordong** [comment]
another error
![clipboard01](https://cloud.githubusercontent.com/assets/17006970/19020159/d0baa45c-88a8-11e6-84b4-a80b9aee4274.jpg)

**Comment by Doncharly** [comment]
https://kiboplatform.net/DonKibo

https://kiboplatform.net/es/advantages.html

http://huaco2016.wixsite.com/kibo-ingledoncharly

*KIBO. Loto Registracion Only 10 Ethereum Unique Pay*
*Skype Carlos.Silva522*

2016-10-02 6:02 GMT-05:00 Mordong <notifications@github.com>:

**Comment by evertonfraga** [comment]
@Doncharly I kindly ask you to prevent this auto-responder, in order to prevent spamming our issue tracker. I've detected more than 8 similar messages coming from you.

Thank you.

**Comment by Mordong** [comment]
ban him pls for spam and add-flood

**Comment by Mordong** [comment]
and again this morning - just 2500 blocks taking already an hour with little progress...

![clipboard01](https://cloud.githubusercontent.com/assets/17006970/19028653/320c9c1c-8947-11e6-9898-b4c5d543ce43.jpg)

**Comment by marienuac** [comment]
5.6gb usage and extremely slow after figuring out why it took 3 minutes to remote into my box.....

**Comment by evertonfraga** [comment]
This is due to recent DoS attacks on Ethereum network. Please refer to the [Go-Ethereum repo](https://github.com/ethereum/go-ethereum/releases/tag/v1.4.15) to an updated geth version. 

We'll release soon an updated Mist version with geth 1.4.15 bundled.
