### ISSUE TITLE
Wallet 0.8.4 cannot connect to testnet

### ISSUE THREAD

**Issue by stueynet** [ethereum/mist#1246]
#### System information
``````
Version: `0.8.4`
OS & Version: osx 10.11.6
Node type: `geth(default)`
``````
Swithced to testnet after upgrading to 0.8.4 and I get this error. Now I cannot switch back as this error freezes the wallet.

```
Node type: geth
Network: main
Platform: darwin (Architecure x64)

...71] closed db:/Users/stueynet/Library/Ethereum/chaindata
I1002 13:14:08.068907 ethdb/database.go:83] Alloted 512MB cache and 1024 file handles to /Users/stueynet/Library/Ethereum/chaindata
I1002 13:14:08.315224 ethdb/database.go:83] Alloted 16MB cache and 16 file handles to /Users/stueynet/Library/Ethereum/dapp
I1002 13:14:08.317496 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I1002 13:14:08.317631 eth/backend.go:201] Blockchain DB Version: 3
I1002 13:14:08.319499 core/blockchain.go:214] Last header: #2335186 [1302b641…] TD=66125627535242412248
I1002 13:14:08.319519 core/blockchain.go:215] Last block: #2335186 [1302b641…] TD=66125627535242412248
I1002 13:14:08.319527 core/blockchain.go:216] Fast block: #2335186 [1302b641…] TD=66125627535242412248
I1002 13:14:08.319696 eth/handler.go:113] blockchain not empty, fast sync disabled
I1002 13:14:08.321098 p2p/server.go:313] Starting Server
Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use
```

Screenshot:
http://d.pr/i/HCTb

**Comment by stueynet** [comment]
Restart fixed this.

**Comment by Doncharly** [comment]
https://kiboplatform.net/DonKibo

https://kiboplatform.net/es/advantages.html

http://huaco2016.wixsite.com/kibo-ingledoncharly

*KIBO. Loto Registracion Only 10 Ethereum Unique Pay*
*Skype Carlos.Silva522*

2016-10-02 15:14 GMT-05:00 Stuart Starr <notifications@github.com>:

**Comment by evertonfraga** [comment]
Nice to see that @stueynet.

For future reference, please check if there's any other instance running `$ ps aux | grep geth`

Sometimes people install geth using Homebrew and have it running in the background. To ensure no homebrew version is running, do: `brew services list`.
