### ISSUE TITLE
Possibility to clean "cache" and wipe pending transactions?

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#125]
I'm not sure whether this is a mist issue, but I was recieving a small amount of 0.12 ETH on my account while mist was running. Here is the transaction.

https://etherchain.org/tx/0x11b71afadeff95f278df9c47474ba5704e008553bffdfcbea1d0116986fc90a7

And this is the reciever account.

https://etherchain.org/account/0xa1c24c9da4c206c6785517308945a17a9374c000

Immidiatly after I recieved the transaction, something spawned around 100 outgoing transactions which I do not fully understand.

https://etherchain.org/account/0xa1c24c9da4c206c6785517308945a17a9374c000#txsent

Example tx:

https://etherchain.org/tx/0xfec5291236310fb1abf722abef03229683bc0c2ad54729e84f96c19dfd8dc398 

And the balance remains untouched, the 0.12 ETH are ... I have no idea where they are!

Good thing, I was just playing round with small amounts. Just wondering, what did just happened?

**Comment by 5chdn** [comment]
Using Mist from latest develop. And geth from latest develop. Both built from source. On ArchLinux.

**Comment by 5chdn** [comment]
Ok it seems the reciever of the 100 transactions is the contract at etherid.org. I remember using it a while a go and eventually ran out of ETH to pay the fees. Aren't transactions cancelled if an account is empty? The transactions got created 18 days ago. I already forgot about them.

Is there any way to clean the "cache" and wipe pending transactions?

**Comment by frozeman** [comment]
@obscuren can you help here?
"Is there any way to clean the "cache" and wipe pending transactions?"

**Comment by luclu** [comment]
I see you found [this](https://ethereum.stackexchange.com/questions/2600/how-can-i-cancel-a-not-yet-pushed-transaction-in-mist/2870#2870) already. ;)
AFAIK there is currently no way to do so using Mist/web3.js - I'm only aware of [this](https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#ethpendingtransactions) method to query the node for pending transactions.
