### ISSUE TITLE
Mist for Mobile

### ISSUE THREAD

**Issue by hiddentao** [ethereum/mist#1252]
I'm creating this issue just to jot some notes down on how a mobile version of Mist might work, based on conversations we've had as a team and my own thoughts.
## Basic architecture
- **Platforms:** Android and iOS. it must support both of these platforms
- **Tech:** [React-native](https://github.com/ethereum/mist/pull/1228). Note that a [WebView](https://facebook.github.io/react-native/docs/webview.html) is available.
- **Node:** Geth [light-client library](https://github.com/ethereum/go-ethereum/wiki/Mobile-Clients:-Libraries-and-Inproc-Ethereum-Nodes). 

The UI needs to be designed for portrait and landscape modes, and perhaps with a slightly different layout for phablet/tablet-sized screens, though this isn't strictly necessary.
## Need to solve
- _Account mgmt_ - Whatever we choose to do here, we should eventually make it possible to keep your desktop and mobile mist accounts in sync. Initially I think it's ok if they were totally separate, to allow people to atleast get used to mobile Mist.
- _Web3 connections_ - We need to ensure we can start a Geth RPC server listening interface so that Dapps can connect to it. I'm sure this is easily possible but needs to be investigated (for all platforms)
- _Swarm_ - We will need a bundled native lib for accessing Swarm; not heard anything in this front yet.
## Roadmap to Alpha
1. Design a UI and interaction system that works well - maybe use [Framer](https://framerjs.com/)?
2. Choose a platform (e.g. Android) and get a basic react-native app working
3. Integrate Redux data-driven architecture
4. Integrate GethDroid lib and get the light client hooked up and working
5. Get a Dapp working in a WebView
6. Add account management mechanism (use the simplest method possible for now)
7. Initialy alpha release

**Comment by RongxinZhang** [comment]
@hiddentao This sounds like an great project!

What type of help are you looking for? ✌️ 

### Questions:
- Would all functionalities within the desktop version need to be ported over?
- What is the timeline?

### Suggestions:
- In terms of design, it will be easier to stick with one device, as tablets and phones have very different layouts requirements.

**Comment by gnujoow** [comment]
looks good i can help you out! @hiddentao

**Comment by preetkatari** [comment]
I would like to help.

**Comment by 4d11** [comment]
I'd be interested in working on this too.

**Comment by evertonfraga** [comment]
I am closing this now, as there are already enough alternatives to such project, and our team is at capacity at this moment.
