### ISSUE TITLE
On block 2376500 geth (1.4.15) taking all available RAM memory and crashing

### ISSUE THREAD

**Issue by Mordong** [ethereum/mist#1254]
#### System information
``````
Version: `1.4.15`
OS & Version: windows10 x64
Node type: `geth`
``````
On block 2376500 geth (1.4.15) taking all available RAM memory and crashing

**Comment by Mordong** [comment]
#https://github.com/ethereum/go-ethereum/issues/3069

**Comment by Mordong** [comment]
#https://github.com/ethereum/go-ethereum/issues/3069

**Comment by Raindownchips** [comment]
Can I still send ether?  My client keeps crashing and running out of memory.

**Comment by Mordong** [comment]
Workaround is to use Parity as a backbone - https://ethcore.io/parity.html

Parity to be started with key --geth from shortcut, after sync started, it's Ok to launch wallet, it will connect to parity.
Only bad thing here - chain will be downloaded all over again. Original chain data for geth will stay intact and can be used when geth fixed. the good think - download are much faster then geth
![clipboard01](https://cloud.githubusercontent.com/assets/17006970/19100273/f4453ba2-8ac5-11e6-979e-2515f1988936.jpg)

![clipboard01](https://cloud.githubusercontent.com/assets/17006970/19100301/391e56dc-8ac6-11e6-8d4b-15c18b8127af.jpg)

**Comment by Raindownchips** [comment]
Thank you

**Comment by Mordong** [comment]
anyway - would be there any official fix for wallet?
3 days - quite a long time

**Comment by evertonfraga** [comment]
Yes. geth 1.4.15 was just launched. we'll pack it with Mist and release
really soon

**Comment by Mordong** [comment]
got it, already found in releases - https://github.com/ethereum/go-ethereum/releases
thanks

**Comment by Sjors** [comment]
Is there any way to tell how much space that is?

I had to close my laptop after about 5 minutes of syncing. When I reopened it a few hours later, I kept getting this error:
<img width="570" alt="schermafbeelding 2016-10-07 om 14 40 26" src="https://cloud.githubusercontent.com/assets/10217/19180930/106004b6-8c9c-11e6-88d5-89ca9153b792.png">

`version Parity/v1.3.4-beta-a618dca-20161006/x86_64-macos/rustc1.12.0`. I have 35.9 GB available.

**Comment by luclu** [comment]
@Sjors best you ask this question over at https://gitter.im/ethcore/parity.

**Comment by mamija** [comment]
I have the same issue. I couldn't solve. Sync is always stopped. I have no balance right now, I am little bit disappointed about the hole system, this is ridiculous how hard to handle just one account . 
I hope somebody could give me a solution . THX

**Comment by MasterJames** [comment]
Parity would not install. Win 8 error api-ms-win-crt-stdio-l1-1-0.dll is missing from your computer.
Getting mist to work (not jam out downloading chain) sounds like a better idea.
