### ISSUE TITLE
Mist wallet takes approx 2 hours to sync each day.

### ISSUE THREAD

**Issue by mbxck** [ethereum/mist#1255]
#### System information
``````
Version: `1.4.14`
OS & Version: Windows 10 Pro x64
Node type: `eth/geth(default)`
``````
I am experiencing incredibally slow sync on the mist wallet despite using the new version. Apologies if this is an obvious issue. Can anyone suggest any fixes? It takes approximately 2 hours even though I sync it every day. Log file screenshot as follows.

![logfile](https://cloud.githubusercontent.com/assets/22319041/19070584/ec51e136-8a23-11e6-8171-12be433996a1.png)

-- Is this just because many of the nodes aren't using the new geth yet?
-- I've heard about fast sync. Do I need to delete/rename my chaindata folder and restart?
 
It's very difficult and totally un-user friendly to use an Eth wallet that doesn't sync quickly. Because you feel like your currency is locked away indefinately and you can't easily spend it if the software takes hours each day to come online. 
I am incredibally grateful for the time and skills spent on Mist by this software community and I'm understanding of the greater problems encountered by the network recently but this sort of thing must be quickly overcome for Ethereum to be able to hit the main stream.

**Comment by frozeman** [comment]
There is an attack ongoing on the network, where an attacker deployed processing heavy contracts. The team is working on fixing those bottle necks and make Ethereum more resilient. Best is to wait until this is over and then update to the version we will release.

**Comment by mbxck** [comment]
@frozeman ah OK! Didn't realise sorry. There's nothing about the latest attack on the ethereum blog. What's the best source of news? reddit?

**Comment by frozeman** [comment]
https://ethstats.net

**Comment by frozeman** [comment]
We are working on it, as i write.
