### ISSUE TITLE
Missing Ether in Wallet but Address shows balance.

### ISSUE THREAD

**Issue by davidchua** [ethereum/mist#1261]
#### System information
``````
Version: `0.8.4`
OS & Version: linux
Node type: `eth/geth(default)`
``````

Hi guys,

I'm running Ethereum-Wallet on Linux and I restored my previously backup keystore. I look like I have access to my account but I have no contracts and my ETH balance is $0.

I've checked etherchain and it looks like I'm supposed to have a balance of 42 ETH
https://etherchain.org/account/0xD6B21De3e915542c963b39B4F7f858EEb8B8Fc3d

I've followed the suggestion in #915 to look for contracts but there's no outgoing transaction from my account.

**Comment by frozeman** [comment]
you have to re-add the contracts yourself. Apart from that it is possible that you are on the ETC chain. So re-syncing would help

**Comment by davidchua** [comment]
I'm not sure if I've created a contract previously because on the
blockchain scan, I am unable to find any transactions out to a contract.

**Comment by davidchua** [comment]
Closing because after leaving it for a night, my ethers came back.

Sorry for the false alert! Thanks guys.
