### ISSUE TITLE
Couldn't connect to node? See the logs for more

### ISSUE THREAD

**Issue by oneala** [ethereum/mist#1262]
#### System information

```
Version: `0.8.4`
OS & Version: windows 10
Node type: `eth/geth`
```

Tried to update my wallet but when i open i get this error. Also i cannot start previous versions.

screenshot: https://gyazo.com/f4b0ed392811878e50279af7479e274d

Any thoughts ?

thank you!

**Comment by Mordong** [comment]
See workaround here - #https://github.com/ethereum/mist/issues/1254

**Comment by Mordong** [comment]
https://github.com/ethereum/go-ethereum/releases

**Comment by luclu** [comment]
@oneala could you please upload the full log? You seem to have stumbled into a geth panic (possible bug).
> 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by prashantprabhakar** [comment]
I am also facing the same issue on Linux but with latest version 0.8.6 ,getting error `Fatal: Could not open database: write /home/gemini/.ethereum/chaindata/029001.ldb: no space left on device`. 
and `Couldn't connect to node? See the logs for more`
I even tried adding swap memory, but it also didn't help.

**Comment by oneala** [comment]
"no space left on device" is your hdd out of space? i am waiting for hard fork to finish and then ill try again.

**Comment by luclu** [comment]
@oneala do you still encounter this issue?

**Comment by oneala** [comment]
@luclu i had to backup mist and then to delete everything and to do a fresh install for mist, had to download again blockchain etc.. i am facing a nother problem now, the sync is again very very slow, my hdd is working at 100% performance and i barely get 1,2,3 blocks :(

**Comment by moooooooo** [comment]
the sync for me used to nice and quick - i have a 1Gb internet connection here in NZ, but in the last week it is so SLOW:
I1130 20:24:28.303855 core/blockchain.go:1042] imported 3 blocks,    33 txs (  2.408 Mg) in   10.222s ( 0.236 Mg/s). #2397243 [e65013c2… / ae574dc7…]
I1130 20:24:50.218927 core/blockchain.go:1042] imported 104 blocks,   663 txs ( 22.327 Mg) in   21.915s ( 1.019 Mg/s). #2397347 [ae574dc7… / 53ae8fa6…]
I1130 20:25:15.844518 core/blockchain.go:1042] imported 55 blocks,   266 txs ( 10.340 Mg) in   25.625s ( 0.404 Mg/s). #2397402 [53ae8fa6… / 686e2bd0…]
I1130 20:25:30.449727 core/blockchain.go:1042] imported 9 blocks,   111 txs (  4.240 Mg) in   14.605s ( 0.290 Mg/s). #2397411 [686e2bd0… / 57df2eac…]
I1130 20:25:40.700246 core/blockchain.go:1042] imported 11 blocks,    86 txs (  2.909 Mg) in   10.250s ( 0.284 Mg/s). #2397422 [57df2eac… / 3500d740…]
I1130 20:25:48.784295 core/blockchain.go:1042] imported 33 blocks,   559 txs ( 17.282 Mg) in    8.084s ( 2.138 Mg/s). #2397455 [3500d740… / 6aa060fd…]

so i've deleted everything and will wait a week before resyncing.

**Comment by luclu** [comment]
@oneala @moooooooo I'm sorry to hear this.
The current situation is that HDDs are very slow, so you are adviced to switch to a SSD instead or use `paritiy --warp-sync` or `geth --light`.
Also this morning the state-clearing did finish, thus the default initial fast sync with geth should be fast again (It is <1h for me using a SSD). Please try to follow the former advice (look it up on http://ethereum.stackexchange.com if you don't know what to do) or try to sync from scratch to regain the [new speed from the state-clearing](https://www.reddit.com/r/ethereum/comments/5fob4s/state_clearing_100_complete/).

**Comment by oneala** [comment]
@luclu how do i set `geth --light` ?

**Comment by merket** [comment]
I also get this error, with the current latest version.

**Comment by ndsvw** [comment]
Removing all the files from C:\Users\Your name\AppData\Roaming\Ethereum\geth\chaindata and/or from C:\Users\Your name\AppData\Roaming\Ethereum\geth\lightchaindata and re-downloading it again solved my problem.
