### ISSUE TITLE
IPC connection ‣ AssertionError: expected undefined to equal -32601

### ISSUE THREAD

**Issue by LinkItUp** [ethereum/mist#1263]
#### System information
``````
Version: `0.8.4`
OS & Version: Kubuntu 16.04
Node type: `eth/geth(default)` Idk :x
``````

If possible add the following to your report:

![spectacle z13044](https://cloud.githubusercontent.com/assets/22104634/19147659/69e331fe-8bb9-11e6-97dc-ab0aded94937.png)

The Wallet won't sync anymore. I appreciate your help :)

**Comment by luclu** [comment]
@LinkItUp please excuse the late reply, could you kindly update your post to contain as much information as you can extract from [this instruction](https://github.com/ethereum/mist/issues/new)?

**Comment by LinkItUp** [comment]
I reinstalled Kubuntu and now it works.
