### ISSUE TITLE
Very slow and stucking sync after block 2391361 Mist 0.8.4 when geth is not called in the console

### ISSUE THREAD

**Issue by jensamberg** [ethereum/mist#1268]
#### System information
``````
Version: `10`
OS & Version: Windows 10
Node type: `geth(default)`
``````
Very slow and stucking sync after block 2391361 Mist 0.8.4 when geth is not called in the console
with --fast Option.

**Comment by mxclene** [comment]
i've meet similar problem at 2376828, what's more, geth uses abnormally large memory space, it starts from 2 GB and after few minutes deploys to 7.9 GB crashing my pc

**Comment by Mordong** [comment]
guys... really I've switched to Parity
they reacting on DDOS fast and efficient

https://ethcore.io/parity.html

**Comment by evertonfraga** [comment]
@jensamberg probably your geth version is outdated. Please try running geth separately, from v1.4.16 and above. It seemed to fix all those stuck issues.
https://github.com/ethereum/go-ethereum/releases
