### ISSUE TITLE
WALLET DON'T SHOW MY CURRENT ETH BALANCE

### ISSUE THREAD

**Issue by wasakaka** [ethereum/mist#1272]
Hello my wallet don't show my current balance, and I can't use it,.

Please help.

![ethwallet](https://cloud.githubusercontent.com/assets/22718531/19216531/c7656e8e-8d8d-11e6-903e-285ee9355c80.jpg)

![etherscan](https://cloud.githubusercontent.com/assets/22718531/19216548/93d71b2a-8d8e-11e6-94cc-aa5e5ce6050e.jpg)

**Comment by luclu** [comment]
Duplicate of https://github.com/ethereum/mist/issues/1185#issuecomment-249104680
> Be patient. Resyncing is timetraveling.
