### ISSUE TITLE
Link to Private Net

### ISSUE THREAD

**Issue by milyInzhoop** [ethereum/mist#128]
It's possible to add, as well as "public network" and  "testnet", the ability to connect to a private net? Maybe with a popup where you can type in the launch parameters of geth "i.e.: --networkid 12345 - ipcdisable --port 30303" and save these configurations.

**Comment by frozeman** [comment]
Its possible, but im pretty dumped right now, so this gets quite low priority..

**Comment by milyInzhoop** [comment]
sure! Thanks

**Comment by hiddentao** [comment]
Am trying to do this right now by running geth separately in a private chain created via a single geth instance. Mist gets stuck at the peer search phase. Presumably it expects geth to connect to other peers.

**Comment by luclu** [comment]
We could implement this beforehand:  
> All Mist/Wallet data should be stored per-network #797

**Comment by 3esmit** [comment]
#70
