### ISSUE TITLE
Geth 1.4.17 does not syncronice

### ISSUE THREAD

**Issue by Lucky7111** [ethereum/mist#1285]
#### System information
``````
Version: `1.4.17`
OS & Version: windows
Node type: `eth/geth(default)`
``````
Start wallet with geth1.4.17 no block will be syncroniced after about 3 h.

**Comment by luclu** [comment]
@Lucky7111, we just published [release `0.8.6`](https://github.com/ethereum/mist/releases/tag/v0.8.6) which will download **geth** `1.4.18` on-the-fly. 
*Please* update to easily roll with the upcoming [Hard Fork](https://blog.ethereum.org/2016/10/13/announcement-imminent-hard-fork-eip150-gas-cost-changes/) on Tuesday.
