### ISSUE TITLE
Wrong password ! I lost my Ether coins?

### ISSUE THREAD

**Issue by tfanget** [ethereum/mist#129]
I quiet sure at 100 % that I have not set a password. I can't create a wallet , always the same answer " wrong password" .
Is there a way to recover or define a new password.?

Many thanks for your help

**Comment by frozeman** [comment]
please contact me in skype ('frozeman.de') and i'll try to help you tomorrow 11am CET.

**Comment by tfanget** [comment]
What a shame for me. I have finally  found my password. 
My account was well set with a password.I'm so sorry....

Thank you very much to frozeman.

He spent some time to help me by taking remotly access to my computer to make several test

He was sure that I have set a password.

So I test several basic password, and I I have finnaly unlocked my account

So sorry again...I' m feel like so stupid.... 

Thanks again to Frozeman, this guy is very nice, we can trust in him

**Comment by pro-respirator** [comment]
I'm having the exact same problem, tfanget is the only way to solve this to just guess the password at random?
