### ISSUE TITLE
Linux 64 Wallet 0.8.6 zip doesn't contain geth

### ISSUE THREAD

**Issue by emelbardis** [ethereum/mist#1307]
Downloaded and there is no geth folder under nodes. Also the zip extracted as directory "linux" when I would have expected the directory to be named "Ethereum-Wallet-linux64-0-8-6"

edit- just downloaded x64 Mist and saw the same, Extracted dir is called "Linux" and doesn't contain geth. Test run of both results in failure to sync

**Comment by luclu** [comment]
Starting with release `0.8.6` geth will be automatically updated. On Linux you will always find the latest copy in:
-`~/.config/Ethereum Wallet/binaries/Geth/unpacked/geth` for Ethereum Wallet
-`~/.config/Mist/binaries/Geth/unpacked/geth` for Mist

**Comment by hiddentao** [comment]
I'm thinking we should auto-check for newer versions of Geth whilst Mist is running. Same goes the newer versions of Mist itself. Because some people (esp. Mac users for example) probably don't ever restart Mist. They just wanna leave it running and have it constantly sync up.

**Comment by luclu** [comment]
Good call. As a mean to notify the user I would prefer some small, coloured update button next to the network status (like https://www.gitkraken.com uses).

**Comment by romanrm** [comment]
This is so unfortunate. Back in 0.8.4 I was able to replace geth with a shell script that runs parity instead:
<pre>$ cat eth084/nodes/geth/linux-x64/geth
#!/bin/bash
/usr/local/bin/parity --geth</pre>
This ran splendidly with no issues whatsoever and with no need to manually run parity before wallet. Now, no such possibility anymore? Why people always have to make software "smarter" than it needs to be...

**Comment by luclu** [comment]
@romanrm you can easily write a new script:
```bash
#!/bin/bash
/usr/local/bin/parity --geth
./Mist
```
