### ISSUE TITLE
Lost coins!

### ISSUE THREAD

**Issue by kosoizayc** [ethereum/mist#1309]
I created the wallet
 0xbe1B654C5efac5D09f6Ea71B666Ee9cDAa0EBe50 
![trans](https://cloud.githubusercontent.com/assets/22880144/19426854/1556b908-946a-11e6-96a3-228942b78c05.PNG)
but in the wallet 0 eth! What do I do?
![0](https://cloud.githubusercontent.com/assets/22880144/19426885/4a22409e-946a-11e6-8a1c-064c5a5b9145.PNG)

**Comment by luclu** [comment]
Please be patient, your node is still syncing.

**Comment by kosoizayc** [comment]
how long to wait?

**Comment by luclu** [comment]
Depending on your setup:
- SSD ~10-30min
- HDD ~0.5-5h

Those are just guesses.

**Comment by kosoizayc** [comment]
Already 14 hours passed!
![14 hour](https://cloud.githubusercontent.com/assets/22880144/19437409/830919ac-949f-11e6-8f8b-6a8b6d701b96.PNG)

**Comment by kosoizayc** [comment]
![01](https://cloud.githubusercontent.com/assets/22880144/19437429/9e6c5aba-949f-11e6-957f-e8970e12b773.PNG)

**Comment by luclu** [comment]
@kosoizayc make sure you are running release `0.8.6`!

**Comment by kosoizayc** [comment]
![8 6](https://cloud.githubusercontent.com/assets/22880144/19438131/946e41ec-94a2-11e6-8c6b-6eea60c9e389.PNG)

**Comment by luclu** [comment]
Are you on HDD or SSD?

**Comment by kosoizayc** [comment]
![default](https://cloud.githubusercontent.com/assets/22880144/19443148/050fc3ae-94b6-11e6-9ce6-c4b79ae562ce.PNG)

**Comment by kosoizayc** [comment]
я переустановил кошелек на другом компьютере перенес аккаунт C:\Users\1\AppData\Roaming\Ethereum\keystore и 0 монет,что делать, куда пропали мои деньги?
![new mashine](https://cloud.githubusercontent.com/assets/22880144/19443944/b789d432-94b8-11e6-8268-52c4b52f8530.PNG)

**Comment by luclu** [comment]
You have to wait for the sync to complete.
