### ISSUE TITLE
Password problem

### ISSUE THREAD

**Issue by craigrant** [ethereum/mist#131]
today I was trying to send some ether and it kept telling me wrong password, and I was 100% sure the password was right, I tried multiple times and it kept saying it was wrong, the password worked for me less than 8 hours before for a prior transaction. Then I closed the mist and restarted it, and then the password worked. My question is, if the wallet gets this problem again and it's permanent, what steps do I take to retrieve my ether from the blockchain?

**Comment by frozeman** [comment]
This might be an issue with the connection with the underlying node. So restarting should always fix it.
If you really need to recover your funds, you can simply start `geth` from the command line and follow the tutorials https://ethereum.gitbooks.io/frontier-guide/content/sending_ether.html

**Comment by craigrant** [comment]
thank you, this helps
