### ISSUE TITLE
Go back to .zip instead of .exe install for Windows

### ISSUE THREAD

**Issue by housemobile** [ethereum/mist#1311]
The .exe install puts folders and files in unknown locations. To manually update geth.exe have to jump through hoops to find out where it installed the file.

It was much easier with the .zip install because you could put the folder wherever you want and know you can find what you need in /resources/node/geth

**Comment by luclu** [comment]
@housemobile we abolished the bundling of geth with our `0.8.6` release. 
geth will now be downloaded on-the-fly and automatically updated to the latest version.

**Comment by housemobile** [comment]
@luclu Is that an option or is auto-update forced on the user?

**Comment by resurtm** [comment]
Same for GNU/Linux version please!
Current *.deb files are not compatible with my Debian GNU/Linux installation.

**Comment by resurtm** [comment]
I even not able to install EXE files for MS Windows. It stays at "Checking network..." window forever.

**Comment by Fossius** [comment]
Yea, return .zip

**Comment by luclu** [comment]
@housemobile Mist/EW still connects to any external node, so you can write a script to start your own node followed by Mist/EW.

@resurtm 
- re linux: zips are available on the release page
- re win: please help debugging this issue: https://github.com/ethereum/mist/issues/1314

**Comment by resurtm** [comment]
@luclu Thanks!

**Comment by luclu** [comment]
Zips did return. Customizable NSIS installer for windows is in the making: https://github.com/ethereum/mist/pull/1499
