### ISSUE TITLE
Minor: version display when new version is available: vv0.8.6

### ISSUE THREAD

**Issue by chevdor** [ethereum/mist#1312]
#### System information
``````
Version: `0.8.6`
OS & Version: osx
Node type: `other`
``````
Since 0.8.5, the 'new version available' dialog shows:

> Download vv0.8.6

Notice the double 'v'

**Comment by luclu** [comment]
@chevdor thank you very much! We updated the string in this release: https://github.com/ethereum/mist/commit/d650e21068cff8950e6d92602d377097bfa6dab3
So this shouldn't pop-up with `>=0.8.6`.
