### ISSUE TITLE
Mist 0.8.6 win32 upgrade breaks geth install

### ISSUE THREAD

**Issue by wil611** [ethereum/mist#1314]
#### System information

```
Version: `0.8.6`
OS & Version: windows 10 -  32bit
Node type: `geth`
```

Upgrade from Mist 0.8.5 win32 to Mist 0.8.6 win32 removes geth and doesn't install new version of geth.  Mist client 0.8.6 continuously shows "searching for client binaries"

**Comment by evertonfraga** [comment]
Even after restarting Mist?

Do you have any log entries to share with us? `Develop > Show log file...`

**Comment by luclu** [comment]
@wil611 please also try to launch Mist via the terminal with debug loglevel.
Open the terminal via `Win+R`, navigate to the folder via `cd` and run:
```
Mist.exe --loglevel debug
```

**Comment by wil611** [comment]
Yes even after restarting Mist. I can’t go to Develop  > Show log because the client doesn’t have the “Start application” option on the splash screen. It stays on “Scanning for client binaries…”  “Checking network…”. 

 

The only log file I can find is the SquirreISetup.log and that doesn’t show any obvious errors. 

 

I just ran Mist with the following command and attached the log.

 

Mist –node geth --logfile Mist-0.8.6.log --loglevel debug

 

Don’t know why it’s looking for eth.exe when I specified geth.

 

Thanks 

Wil

**Comment by luclu** [comment]
Please use github.com to attach logs.

**Comment by wil611** [comment]
Attached are the log files you requested.

[Mist-0.8.6.txt](https://github.com/ethereum/mist/files/534694/Mist-0.8.6.txt)
[launch.log.txt](https://github.com/ethereum/mist/files/534696/launch.log.txt)

**Comment by nikosv** [comment]
I am facing the exact same issue.
