### ISSUE TITLE
Mist crashes soon after starting

### ISSUE THREAD

**Issue by songproducer** [ethereum/mist#1315]
#### System information

```
Version: Mist-win32-0-8-6.exe
OS & Version: win32 (Architecture ia32)
Node type: `eth/geth(default)`
```

Warning: No etherbase set and no accounts found as default

![goekay7](https://cloud.githubusercontent.com/assets/10135872/19619067/8d5561ba-985d-11e6-98c8-faf015dc5a45.png)

**Comment by luclu** [comment]
@songproducer please start Mist via the terminal:
```
Mist.exe --loglevel debug
```

**Comment by songproducer** [comment]
Starting Mist via cmd does not yield any information.

http://imgur.com/a/G2ld1

**Comment by luclu** [comment]
@songproducer `Mist-win32-0-8-6.exe` is the installer not the Application binary itself. I will setup a VM and investigate!

**Comment by Fejuto** [comment]
I have the same issue with both mist and wallet. When I start wallet I get that same error message. 

I1027 17:02:35.221361 ethdb/database.go:83] Alloted 512MB cache and 1024 file handles to C:\Users\fejuto\AppData\Roaming\Ethereum\chaindata
I1027 17:02:35.247364 cmd/utils/flags.go:837] ------------------------------------------------------------------------------------------------
I1027 17:02:35.247364 cmd/utils/flags.go:838] Geth is currently configured to SUPPORT the DAO hard-fork!
I1027 17:02:35.247364 cmd/utils/flags.go:839] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I1027 17:02:35.247364 cmd/utils/flags.go:840] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I1027 17:02:35.247364 cmd/utils/flags.go:841] ------------------------------------------------------------------------------------------------
I1027 17:02:35.252364 ethdb/database.go:176] closed db:C:\Users\fejuto\AppData\Roaming\Ethereum\chaindata
I1027 17:02:35.253364 cmd/utils/flags.go:590] WARNING: No etherbase set and no accounts found as default
I1027 17:02:35.254364 ethdb/database.go:83] Alloted 512MB cache and 1024 file handles to C:\Users\fejuto\AppData\Roaming\Ethereum\chaindata
I1027 17:02:35.330876 ethdb/database.go:83] Alloted 16MB cache and 16 file handles to C:\Users\fejuto\AppData\Roaming\Ethereum\dapp
I1027 17:02:35.339052 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I1027 17:02:35.339052 eth/backend.go:201] Blockchain DB Version: 3
I1027 17:02:35.340050 core/blockchain.go:214] Last header: #0 [d4e56740…] TD=17179869184
I1027 17:02:35.340050 core/blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I1027 17:02:35.340050 core/blockchain.go:216] Fast block: #0 [d4e56740…] TD=17179869184
I1027 17:02:35.341050 p2p/server.go:313] Starting Server

**Comment by luclu** [comment]
Do you still encounter this issue with the latest version of Mist?

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
