### ISSUE TITLE
Ethereum Wallet (win 32bit) cannot start

### ISSUE THREAD

**Issue by resurtm** [ethereum/mist#1318]
Version: Ethereum Wallet 0.8.6
OS & Version: MS Windows 7 Ultimate Service Pack 1

Downloaded Ethereum-Wallet-win32-0-8-6.exe file, launched it, and window with "Scanning for client binaries..." and "Checking network..." staying forever.

Screenshot:
![capture](https://cloud.githubusercontent.com/assets/100198/19471254/3604b814-9544-11e6-9915-4fe4bcd4a68e.PNG)

Console (Ctrl+Alt+I):

```
Web3 already initialized, re-using provider. @ file:///C:/Users/z/AppData/Local/EthereumWallet/app-0.8.6/resources/app.asar/interface/a9937a6cd93a5d79cd8de8f368032a8586fe93f1.js:249:47
Reload collection from backend:  tabs @ C:\Users\z\AppData\Local\EthereumWallet\app-0.8.6\resources\app.asar\modules\syncMinimongo.js:97:13)
Finished reloading collection from backend:  tabs @ C:\Users\z\AppData\Local\EthereumWallet\app-0.8.6\resources\app.asar\modules\syncMinimongo.js:176:17
Check network type... @ file:///C:/Users/z/AppData/Local/EthereumWallet/app-0.8.6/resources/app.asar/interface/a9937a6cd93a5d79cd8de8f368032a8586fe93f1.js:265:39)
Failed to load resource: net::ERR_FILE_NOT_FOUND
```

Log files are not available since I'm not even managed to launch Ethereum Wallet software.

**Comment by resurtm** [comment]
I'm also having issues with go-ethereum under Debian GNU/Linux. Check it here: https://github.com/ethereum/go-ethereum/issues/3146

**Comment by doublehops** [comment]
@resurtm, how do you even start Ethereum wallet on Linux? I see that I've installed it (dpkg -l | grep ethererum) but wherever it installed is not in the path. I'm running on Ubuntu 14.04.

**Comment by luclu** [comment]
@doublehops the executable won't added to the PATH, but integrated in the desktop shell via `/usr/share/applications/Ethereum Wallet.desktop`.
The executable itself resides in `/opt/Ethereum Wallet/`.
To have it added to your terminal's PATH EV add this line to the corresponding profile:
```
export PATH=$PATH:/opt/Ethereum Wallet
```

**Comment by jobspierings** [comment]
@luclu Having the same issue on Windows 10 / 32 bit. Following the above steps result in:

1. running `"Ethereum Wallet.exe" --loglevel debug` hangs
    * feedback from CLI in attached text file [geth_cli.txt](https://github.com/ethereum/mist/files/546339/geth_cli.txt)
    * popup `error while setting up environment for the application. choose 'close' to terminate the application` 

![errorwhile](https://cloud.githubusercontent.com/assets/5601623/19626356/0169f462-9930-11e6-9d51-2b9cfe2d58f7.png)

2. file `node.log` cannot be found...

**Comment by luclu** [comment]
@jobspierings I encountered the same issue on my win7 32bit VM. Seems like there is some incompatibility with its terminal. Instead I created a shortcut to the `Ethereum Wallet.exe` and appended `--loglevel debug --logfile <somePath>`.
Though the geth binary will not be downloaded for some reason. I will investigate this during the next days.

**Comment by jobspierings** [comment]
@luclu any progress or luck with this issue to be expected - otherwise I'll have to look for another way to access the wallet.

**Comment by luclu** [comment]
Sorry @jobspierings I had some problem with my primary workstation. I'm currently rebuilding it and won't be able to startup the VM until then.

**Comment by 1SERZH1** [comment]
Какой нужно скачивать и устанавливать кошелёк на win7-32bit-sp1 для успешного ввода/вывода ETH !??

**Comment by luclu** [comment]
Merging issues:
@qubit1729 [wote](https://github.com/ethereum/mist/issues/1400#issue-188374564):
> Hi,
Obviously nobody is testing the software.
The reason of the crash is a 32bit exe running on a 64bit architecture.
Header of .exe shows 32bit compiled with Microsoft Visual C++ 8 which is pretty old...
regards, qubit1729

**Comment by qubit1729** [comment]
Ticket has been closed. What does that mean ?
Is there no running version for Windows 10 64 bit ?

**Comment by qubit1729** [comment]
Is this a 32bit issue ?
It looks like there is a connection problem:
![connection error mist](https://cloud.githubusercontent.com/assets/7703590/20277333/5e220cd6-aaa0-11e6-8b4b-5842e3c75f93.png)
Turned off Kaspersky antivir still crashes.

Logfiles show:
I1114 19:20:58.828518 ethdb/database.go:83] Alloted 512MB cache and 1024 file handles to C:\Users\leopo\AppData\Roaming\Ethereum\chaindata
I1114 19:20:58.869685 cmd/utils/flags.go:837] ------------------------------------------------------------------------------------------------
I1114 19:20:58.869685 cmd/utils/flags.go:838] Geth is currently configured to SUPPORT the DAO hard-fork!
I1114 19:20:58.869685 cmd/utils/flags.go:839] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I1114 19:20:58.869685 cmd/utils/flags.go:840] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I1114 19:20:58.869685 cmd/utils/flags.go:841] ------------------------------------------------------------------------------------------------
I1114 19:20:58.874678 ethdb/database.go:176] closed db:C:\Users\leopo\AppData\Roaming\Ethereum\chaindata
I1114 19:20:58.874678 cmd/utils/flags.go:590] WARNING: No etherbase set and no accounts found as default
I1114 19:20:58.878399 ethdb/database.go:83] Alloted 512MB cache and 1024 file handles to C:\Users\leopo\AppData\Roaming\Ethereum\chaindata
I1114 19:20:58.946579 ethdb/database.go:83] Alloted 16MB cache and 16 file handles to C:\Users\leopo\AppData\Roaming\Ethereum\dapp
I1114 19:20:58.957610 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I1114 19:20:58.957610 eth/backend.go:201] Blockchain DB Version: 3
I1114 19:20:58.958613 core/blockchain.go:214] Last header: #0 [d4e56740…] TD=17179869184
I1114 19:20:58.958613 core/blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I1114 19:20:58.958613 core/blockchain.go:216] Fast block: #0 [d4e56740…] TD=17179869184
I1114 19:20:58.959630 p2p/server.go:313] Starting Server

**Comment by luclu** [comment]
Problem has been identified, PR is up.
