### ISSUE TITLE
Ethereum Wallet does synchronize and send transactions but doesn't show it.

### ISSUE THREAD

**Issue by porobov** [ethereum/mist#1319]
#### System information

```
Version: `0.8.6`
OS & Version: 'linux'
Node type: 'geth(default)`
```
1. It looks like the synchronization is stopped, but if I close the wallet and open geth right after it it shows that the network is up to date (the last block is the same as shown at https://testnet.etherscan.io/)
2. The same is for transactions. I've sent several transactions to a contract and can see them at etherscan, but the wallet doesn't show any changes. 

Using it with morden (testnet).

**Comment by evertonfraga** [comment]
It should be fixed, as this was an IPC connection problem.
