### ISSUE TITLE
@ symbols when commented out cause contracts not to complie

### ISSUE THREAD

**Issue by GriffGreen** [ethereum/mist#132]
I was trying to follow the commenting style in https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format but the @ symbols cause the browser to not compile, even though it was commented out! i got this error:

Could not compile source code.
Error: Docstring Parsing Error: Unknown tag title: encountered

**Comment by frozeman** [comment]
@chriseth

**Comment by luclu** [comment]
This seems to be resolved - tested with geth 1.4.6.

Current behaviour:
"@" like "@param" like any uncomplete statement will just leave the Wallet compilation indicator in floating state.

So I guess this is ok.
