### ISSUE TITLE
quick send to own accounts

### ISSUE THREAD

**Issue by arnonuem** [ethereum/mist#1320]
Feature Request:

regarding the wallet it would be nice to have like a quick selection of own accounts instead of pasting the address when sending ether. AutoSuggestion on Account-names would be cool. Thanks :)

**Comment by luclu** [comment]
@arnonuem you can simply open the account you want to be the receiver and click the `deposit` button on the right. :)

Proper account management and an address book will be added in the mid-term future.

I will close this. 
Feel free to subscribe to https://github.com/ethereum/meteor-dapp-wallet/issues/201
