### ISSUE TITLE
Ethereum Wallet / Syncs fully, then restarts

### ISSUE THREAD

**Issue by basjee** [ethereum/mist#1322]
#### System information

```
Latest version of Ethereum Wallet/Mist (v0.8.6)
Latest geth client (v1.4.18)
OS & Version: osx sierra
Node type: `eth/geth(default)`
```

Hi there, my Ethereum Wallet app takes around 6 hours to fully sync, then completely re-starts the sync. No idea why. Any help is appreciated. Thank you. 

PS: just removed the complete app and re-installed it (2nd time), will post the log as soon as it has happened again.

**Comment by basjee** [comment]
Tried this: 

geth removedb
geth --fast --cache=1024

same problem, sync re-starts from scratch as soon as it's almost done

**Comment by basjee** [comment]
Attached the log.txt of geht... thanks for any help! 
[log.txt](https://github.com/ethereum/mist/files/542251/log.txt)

**Comment by luclu** [comment]
Thank you @basjee 
pinging @karalabe @fjl, this looks interesting

**Comment by mista66** [comment]
Same issue with ubuntu 

Latest geth client (v1.4.18)

**Comment by prashantprabhakar** [comment]
I also have same issue on my linux machine. I can verify the issue. After full syncing, it started resyncing, the size of chaindata has increased around 30.2 GB current block is 1662264.

**Comment by hh3755** [comment]
Same issue with mac sierra

**Comment by CaptainSkywave** [comment]
After one week trying to sync with 1.4.18 I have now given up. (WINDOWS)
I have done numerous deletions and syncs from scratch - it won't work - always hangs there at the end unable to get over the hump to retrieve the last ~1000 blocks, as well as my wallets showing 0 balances (keystore is in the folder)
This morning (european time) I decided to make a new sync with parity 1.3.8 - goes slow (~46k blocks to go), but advances steadily, and balances shows correctly.

**Comment by basjee** [comment]
I "fixed" it by syncing --fast with a ssd hd macbook, moved all my ether to a nano ledger s wallet and done... not a real fix but at least I can access my coins again ;-)

**Comment by neerven** [comment]
Same issue here with Mist under OSX El Capitan. I deleted the chain data folder to escape being stuck, but now have basjee 's problem...

**Comment by evertonfraga** [comment]
Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for syncing troubleshooting steps.

**Comment by evertonfraga** [comment]
That specific behavior was fixed on Geth.
