### ISSUE TITLE
ETH vanished (or never received after BTC purchase)

### ISSUE THREAD

**Issue by confirmationbias** [ethereum/mist#1324]
On October 5th, I used the updated ETH wallet program to purchase ETH using BTC. I transferred BTC to the address provided by the wallet. I can see that the BTC has been transferred on the BTC blockchain, and I can see a confirmation of the transaction on the Ethereum blockchain here:

https://etherscan.io/address/0xE929B402aA7A788E30C126B947e01A462E9dcB6e

But my ETH wallet for that account still says 0.00

Note I also have a screenshot of my ETH wallet confirmation from October 5th.

**Comment by luclu** [comment]
Make sure to run the latest version `0.8.6`. Do a full sync and compare the blocknumber and -hash to [[1]](https://fork.codetract.io/) or [[2]](https://ethstats.net/).

**Comment by luclu** [comment]
I will close this as I expect it to be resolved.
