### ISSUE TITLE
0.8.6 Wallet is attaching old Testnet tokens to Mainnet keys

### ISSUE THREAD

**Issue by agnewpickens** [ethereum/mist#1325]
IBM Lenovo Thinkcentere with 8GB RAM

```
Version: 0.8.6
OS & Version: Windows 7 Pro
Node type: Geth 1.4.18
```

Going to try to upload node.log, but had trouble before.  My mainnet has not been able to
complete a full sync but Testnet tokens I created months ago and watched from Morden
are showing balances on Mainnet and attaching themselves to account keys on Main.  The
balances showing are two constants I used in my Testnet algo.

All these tokens with a balance of 365 or 366 were created on Testnet.

![main 085 constants on tokens](https://cloud.githubusercontent.com/assets/18013756/19502888/d05cb48c-957d-11e6-9ba4-16fc5a749ed4.PNG)

**Comment by agnewpickens** [comment]
Have noticed the icons attaching themselves to account keys during sync.

**Comment by evertonfraga** [comment]
Have to check if that still applies to the wallet. 

Mind sharing any of the addresses?
