### ISSUE TITLE
Latest Wallet does not sync

### ISSUE THREAD

**Issue by grosminou** [ethereum/mist#1327]
#### System information

```
Version: `0.8.6`
OS & Version: windows/linux/osx  Ubuntu 14.04   (I5 8G m  320G HD)
Node type: `eth/geth(default)`  
```

Wallet does not sync
Disk usage is  HIGH , Computer is very slow
and geth is in a loop
E1019 11:36:59.347665 core/blockchain.go:1170] Bad block #2462925 (0xe6fc3019799c54d1a229d45a58f5a3cd091cd6e8f30313d70cf59d8af7e51929)
E1019 11:36:59.347690 core/blockchain.go:1171]     gas used error (456627 / 448787)

**Comment by luclu** [comment]
I will close this for now. Should there still be problems please follow this:
>Please try to do a fresh re-sync now that the [state-clearing](https://www.reddit.com/r/ethereum/comments/5fob4s/state_clearing_100_complete/) did finish. 
>
>Doing a fresh sync will reduce the blockchain replica on your computer to ~10G and won't take much longer than 1h on a SSD.
>
>Please make sure to have the [latest version of Mist / Ethereum Wallet](https://github.com/ethereum/mist/releases) installed and follow [this how-to](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555) to reset the chaindata folder and initiate the fresh sync.
