### ISSUE TITLE
Ethereum Wallet synchs extremely slowly

### ISSUE THREAD

**Issue by mdbtaa** [ethereum/mist#1328]
LENOVO TOWER
AMD A8-3850 APU 64-bit 8G RAM

```
Version: `0.8.6`
OS & Version: Windows 10 Home
Node type: `Geth 1.4.18`
```

I have been attempting to synch my Ethereum Wallet. It requires too many system resources to leave it running in the background while I work so I run it at night. Even so, it is synching VERY slowly with no more than 2% of 73,146 blocks in a 9 hour period.

I have included the following as requested.

![image](https://cloud.githubusercontent.com/assets/22939632/19526274/c155a876-95d8-11e6-8182-2a6e7d6cf896.png)

[Ethereum Wallet node.log files.zip](https://github.com/ethereum/mist/files/539504/Ethereum.Wallet.node.log.files.zip)

**Comment by Lucky7111** [comment]
I have the same problem - so slow that you think it will stuck. One Block in hours

**Comment by mbxck** [comment]
This post might help from Buterin just now:

https://www.reddit.com/r/ethereum/comments/58bnef/if_you_are_running_a_geth_node_try_refastsyncing/

People saying it's successful, I'm trying it now. The wallet really needs menu options coding in to allow the user to switch to "fast mode" or "delete chaindata".

**Comment by mdbtaa** [comment]
For those who aren't programmers, go to the Console (click on Develop>Toggle Developer Tools>Wallet UI) and then click on the "console" tab and enter: geth removedb and press Enter. Then enter: 
geth --fast --cache=1024 and press Enter. Your wallet will begin synching again from block 1 and will synch MUCH more quickly.

**Comment by luclu** [comment]
@mdbtaa using the developer console to invoke geth is not possible. You will have to use your OS's terminal instead.

**Comment by mdbtaa** [comment]
**@luclu** THANK YOU for the heads up! and, forgive my ignorance as I'm not a developer . . so, how would I access the "terminal" of my OS (Windows 10)? Is it the Command Prompt (Admin) or DOS prompt, or is there a specific application window?

Another question . . I executed the "geth removedb" command from the developer console and then  executed "geth --fast --cache=1024" from the developer console and it seems to have worked. My wallet is now almost fully synched. However, now all the ETH I had stored in the Main Account (Etherbase) are gone. So, even though they appear to be identical, I replaced the existing "keystore" directory with my backed up "keystore" directory, yet my ETH are still not showing up. What to do?

**Comment by Lucky7111** [comment]
Work realy good quite fast But my Ether are also gone

**Comment by luclu** [comment]
@Lucky7111 @mdbtaa please check your addresses using https://etherscan.io. You will most likely find that your Ether is not gone, but your node just not **fully synced** yet. Please be patient while crunching through the recent spam blocks.

**Comment by Lucky7111** [comment]
I sync now until 1000 Blocks - no ether is back. bought ether about 20 days ago - should sync last blocks bring my ether back? I do not think so...

**Comment by Lucky7111** [comment]
If I search here https://etherscan.io/address/0x20523a1c5013e00689C36B7fbf62eb4e042Ec0a0 no ether is there - should be about 10 Ether

**Comment by Lucky7111** [comment]
I am sorry I took the wrong account - ether seems to be there

**Comment by luclu** [comment]
I will close this as it seems resolved. Should there still be problems follow this:
>Please try to do a fresh re-sync now that the [state-clearing](https://www.reddit.com/r/ethereum/comments/5fob4s/state_clearing_100_complete/) did finish. 
>
>Doing a fresh sync will reduce the blockchain replica on your computer to ~10G and won't take much longer than 1h on a SSD.
>
>Please make sure to have the [latest version of Mist / Ethereum Wallet](https://github.com/ethereum/mist/releases) installed and follow [this how-to](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555) to reset the chaindata folder and initiate the fresh sync.
