### ISSUE TITLE
Mist on private-net can't send request API.

### ISSUE THREAD

**Issue by edwardmelody** [ethereum/mist#1329]
#### System information
Version: `0.8.6`
OS & Version: windows
Node type: `geth`

- Screenshots
[https://s12.postimg.org/7a7h2kpod/report.jpg](https://s12.postimg.org/7a7h2kpod/report.jpg)

I have geth private-net on ubuntu in my private network. Then I ran Mist.exe with "mist.exe --rpc http:/ubuntuip:rpcport", it will be great but when i wanna add a new account or send transaction, it's throwing error "the ... method doesn't exist/is not available." as the screenshot.

**Comment by luclu** [comment]
Please post the complete commands you used to invoke geth as well as Mist.

**Comment by edwardmelody** [comment]
geth --identity "Ubuntu V1 Main" --port "30303" --rpc --rpcaddr "192.168.1.11" --rpcport "8000" --rpccorsdomain "*" --datadir "/home/sorasak/ethereum_data/chains" --nodiscover --ipcapi "admin,db,eth,debug,miner,net,shh,txpool,personal,web3" --rpcapi "db,eth,net,web3" --etherbase 7c2339d96cb5e2544dc236df094003f9870eff96 --fast --networkid 6969 console

**Comment by edwardmelody** [comment]
I found my mistake on --rpcapi "db,eth,net,web3" without personal API. It will be work when i add it correctly.
