### ISSUE TITLE
WINDOWS shortcut Target string? Fast Sync

### ISSUE THREAD

**Issue by CaptainSkywave** [ethereum/mist#1330]
#### System information

```
Version: `0.8.6`
OS & Version: WIN SERVER 2012 R2
Node type: `geth 1.4.18`
```

In WINDOWS, after deleting the chaindata folder, can I do like this in a shortcut Target in order to sync quicker and reduce the chaindata size?:

`"C:\Users\xxxxx\AppData\Local\EthereumWallet\app-0.8.6\Ethereum``Wallet.exe" geth --fast``--cache=1024`

..or do I need 'geth' to be there? ..so like this:

`"C:\Users\xxxxx\AppData\Local\EthereumWallet\app-0.8.6\Ethereum``Wallet.exe" --fast``--cache=1024`

?

**Comment by luclu** [comment]
To display the command-help screen invoke Ethereum Wallet with `--help`:

```
Usage: Ethereum Wallet --help [Mist options] [Node options]

Mist options:
  --mode, -m              App UI mode: wallet, mist.
                                                   [string] [Standard: "wallet"]
  --node                  Node to use: geth, eth       [string] [Standard: null]
  --network               Network to connect to: main, test
                                                       [string] [Standard: null]
  --rpc                   Path to node IPC socket file OR HTTP RPC hostport (if
                          IPC socket file then --node-ipcpath will be set with
                          this value).                                  [string]
  --gethpath              Path to Geth executable to use instead of default.
                                                                        [string]
  --ethpath               Path to Eth executable to use instead of default.
                                                                        [string]
  --ignore-gpu-blacklist  Ignores GPU blacklist (needed for some Linux
                          installations).                              [boolean]
  --reset-tabs            Reset Mist tabs to their default settings.   [boolean]
  --logfile               Logs will be written to this file in addition to the
                          console.                                      [string]
  --loglevel              Minimum logging threshold: trace (all logs), debug,
                          info, warn, error.         [string] [Standard: "info"]
  --version, -v           Display Mist version.                        [boolean]

Node options:
  -  To pass options to the underlying node (e.g. Geth) use the --node- prefix,
     e.g. --node-datadir

Optionen:
  -h, --help  Hilfe anzeigen                                           [boolean]
```

Note the **Node options** section.

Although as this is a [one time command (Reddit.com)](https://www.reddit.com/r/ethereum/comments/58bnef/if_you_are_running_a_geth_node_try_refastsyncing/), you can simple start **geth.exe** from the terminal with:
```
geth.exe removedb
geth.exe --fast --cache 1024
```
Note:
- the `--fast` flag only works once. Should you stop the sync half way through, the flag won't have any effect anymore
- on machines with >=16GB memory try to use `--cache 4096`
- as soon as you are past the pre-HF attack blocks with a clean `--fast` sync your chaindata folder will be significantly smaller and any further sync faster again

**Comment by CaptainSkywave** [comment]
Thank you luclu

**Comment by mbxck** [comment]
I second the above comment. The wallet is stuggling to keep up with the pace as blocks are mined. Obviously this can't be normal performance - is there still an attack on the network?

At the moment I'm checking my ether balance by using etherscan.io... can't really do much else! Very frustrating :(

**Comment by luclu** [comment]
Please try to do a fresh re-sync now that the [state-clearing](https://www.reddit.com/r/ethereum/comments/5fob4s/state_clearing_100_complete/) did finish. 

Doing a fresh sync will reduce the blockchain replica on your computer to ~10G and won't take much longer than 1h on a SSD.

Please make sure to have the [latest version of Mist / Ethereum Wallet](https://github.com/ethereum/mist/releases) installed and follow [this how-to](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555) to reset the chaindata folder and initiate the fresh sync.
