### ISSUE TITLE
Geth won't sync fast when using 'fast' switch. Can't use wallet.

### ISSUE THREAD

**Issue by mbxck** [ethereum/mist#1332]
```
Version: `0.8.6`
OS & Version: Windows 10 Pro / 64bit
Node type: `geth 1.4.18`
```

I'm using the latest version of geth with the --fast sync as specified here:

https://np.reddit.com/r/ethereum/comments/58ectw/geth_super_fast/d8zq6u7

Yes - I did the removedb command first and yes I included the cache switch as well. But it won't fast sync! 

I left the geth running in the command prompt over night (approx 10 hours) and it's still going on 2,306,234 and taking forever. Other people are saying that the fast sync only takes 2 hours and also significantly shrinks their chaindata folder. My chaindata folder is on 32.5GB and increasing. Before I fast sync'd it was only on about 9! So I'm guessing this fast sync command doesn't work on my PC.

Also there are two geth versions in my unpacked directory:

'geth.exe' and 'geth-1.4.18-stable-c72f545-windows-4.0-amd64.exe'. Should I run the fast switch on the first or second executable? It's unclear from the instructions.

![geth fast sync](https://cloud.githubusercontent.com/assets/22319041/19590353/59ea45b0-9769-11e6-9ea8-95066be37bab.png)

**Comment by luclu** [comment]
@mbxck I'm afraid that you will need a SSD to experience a full synchronization within 2h. My guess on HDDs is currently 10-20h. Please be patient.

Although there the upcoming [lightclient feature](https://github.com/zsfelfoldi/go-ethereum/wiki/Light-Ethereum-Subprotocol-(LES)) (2-8 weeks) will be a relief.

**Comment by mbxck** [comment]
@luclu Thanks for the update, but I have a solid state drive. My computer is only 4 months old. I've got an Intel i-7 processor, 8GB of Ram and an SSD.  Also your response doesn't explain how I am using the geth fast sync, but it appears to be downloading 30GB of chaindata when others using geth --fast are downloading much less.

**Comment by luclu** [comment]
@mbxck my oversight, judging from your screenshot your geth does not do a fast sync.
Please follow [these instructions](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555).

**Comment by mbxck** [comment]
@luclu Thanks for the advice. But that link simply gets me to delete the chaindata folder and run geth --fast. I've done this twice already. It's not fast and it downloads 30GB of data which is not a fast sync. My issue is I don't think geth --fast is working on my PC. See the screenshot in my original post, I'm definately running geth with the recommended fast switch.

**Comment by Mklueh** [comment]
Tried deleting chaindata and run normal sync ->~70% after two days
Deleted chaindata again and run with fast mode -> 96% after two days. The first 50-60% were really fast, now very slow.

Balances are still 0 ETH

**Comment by mbxck** [comment]
@Mklueh a number of people on reddit experiencing the same problem, fast sync works up until the last blocks then slows right down.

**Comment by mbxck** [comment]
... and doesn't finish.

**Comment by BADC0FF33** [comment]
I have the same issue, with the same symptoms. Configuration: Win 8.1, Intel i7, 16 Gb RAM

**Comment by Mklueh** [comment]
@mbxck and I guess there is no solution yet? I´m wondering why this happens only to "some" users?!

**Comment by BADC0FF33** [comment]
@Mklueh I don't think so. Many users don't know about this bug tracker. Many of users are not programmers or something like that.

**Comment by mbxck** [comment]
@mklueh Tonight I'm trying again. I've done a _geth removedb_ and then I'm just running Mist to see what it does (ignoring advice to run commands such as _geth --fast_ etc.) 
I'm now 1000 blocks away from a full sync and Mist appears to be progressing well as it's now 15m through the estimated 31m in bloated chain structure. If it completes, it will be the first time I've had a full sync in weeks.

**Comment by mbxck** [comment]
It sync'd finally! I still believe executing geth --fast manually doesn't work on some computers though. Definately didn't work on mine and many more people experiencing the same problem.

**Comment by ivaf** [comment]
Yes, I have a same problem (like in first post) too.

**Comment by luclu** [comment]
I will close this as it seems resolved. Should there still be problems follow this:
>Please try to do a fresh re-sync now that the [state-clearing](https://www.reddit.com/r/ethereum/comments/5fob4s/state_clearing_100_complete/) did finish. 
>
>Doing a fresh sync will reduce the blockchain replica on your computer to ~10G and won't take much longer than 1h on a SSD.
>
>Please make sure to have the [latest version of Mist / Ethereum Wallet](https://github.com/ethereum/mist/releases) installed and follow [this how-to](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555) to reset the chaindata folder and initiate the fresh sync.
