### ISSUE TITLE
Account doesn't show ethers

### ISSUE THREAD

**Issue by prashantprabhakar** [ethereum/mist#1333]
#### System information
``````
Version: `Ethereum Wallet 0.8.6`
OS & Version: linux
Node type: `eth/geth(default)`
``````
I was downloading blockchain using` --fast --cache=1024 `options. I have downloaded till 2414530 blocks, I have imported my UTC files to keystore folder. But I am facing 2 issues:

1. Mist doesn't shows account properly. After restarting many times I am able to see my account in Mist but once you restart it's gone again. This issue is already open [Accounts are not showing up](https://github.com/ethereum/mist/issues/1308)

2. geth shows all accounts that are under keystore folder but on checking balance it shows 0 ethers. However I can verify from exchanges like etherscan.io that I have ethers in my account.(Note: I have synced to block in which my account received balance).

I am on main-network.

[logs.txt](https://github.com/ethereum/mist/files/543817/logs.txt)

**Comment by luclu** [comment]
Thank you @prashantprabhakar, (2) is most likely due to a incomplete sync, although it might be related to (1).
Please open the developer console via `CTRL+ALT+i` and post the output of following commands:
```
web3.version
web3.admin.nodeInfo.name
web3.eth.blockNumber
web3.eth.getBlock(2463000).hash
web3.eth.syncing
```

**Comment by prashantprabhakar** [comment]
- web3.version
     Object {api: "0.15.3"}
     api: "0.15.3"

- web3.admin.nodeInfo.name
     "Geth/v1.4.10-stable-5f55d95a/linux/go1.6.2"

- web3.eth.blockNumber
    2447702

- web3.eth.getBlock(2463001).hash
     uncaught TypeError : Cannot read property of 'hash' of null

- web3.eth.syncing
     currentBlock: 2445637
     highestBlock:2480977
    knownStates: "0xda61:
    pulledStatesL "0x6cd7"
    startingBlock:2443523

**Comment by luclu** [comment]
Ah, there we go, your geth node is stell on version `1.4.10`, which is not HF compatible.
Please update to geth `1.4.18` or let Ethereum Wallet `0.8.6` handle the node internally (it will always download the latest version of geth since release `0.8.6`.

**Comment by prashantprabhakar** [comment]
Ooops. sorry I guess I opened Mist 0.8.1 accidentally or has geth `1.4.10` running which let my wallet to connect to this version.  I re-verified above data I am on latest version of geth `1.4.18` and Ethereum-Wallet 0.8.6. Still when I add accounts a new file is generated in keystore but account does not appear on Wallet. I am providing details again:

- web3.version
    Object {api: "0.15.3"}
    api: "0.15.3"

- web3.admin.nodeInfo.name
   "Geth/v1.4.18-stable-c72f5459/linux/go1.7

- web3.eth.blockNumber
    2452219

- web3.eth.getBlock(2463001).hash
   uncaught TypeError : Cannot read property of 'hash' of null
'

- web3.eth.syncing
   currentBlock: 2449913,
   highestBlock: 2482012, 
   knownStates: "0x314", 
   pulledStates: "0x2a3",
   startingBlock: 2449554
