### ISSUE TITLE
How to (pls) creating Smart Contracts

### ISSUE THREAD

**Issue by MichelDiz** [ethereum/mist#134]
I need to create a "ticket app" as part of my study on Ethereum. So, I want to create a token who I can create more supply after few processes. linked to multiple signatures. Founders signatures and client.

Shortly, I want create a Ticket that I can "inflate" based on "our" own rules. Such, cliente wants more tickets and with his authorization, mine and one more admin we can insert more supply. Based in multiple signature.

I'm work on http://chriseth.github.io/browser-solidity/?gist=20c8b5658349b003b08d #

**Comment by linagee** [comment]
This seems like a question better suited for http://ethereum.stackexchange.com/

This section of git is for issues with Ethereum Mist.
