### ISSUE TITLE
Four wallets listed on body of mist window, only three show up on left hand list of wallets.

### ISSUE THREAD

**Issue by tjayrush** [ethereum/mist#1342]
#### System information

```
Version: `0.8.6`
OS & Version: osx 10.10.5
Node type: `geth` 
```

If possible add the following to your report:
- Screenshots

<img width="1257" alt="screen shot 2016-10-24 at 6 42 45 pm" src="https://cloud.githubusercontent.com/assets/5417918/19666800/b813cea0-9a1a-11e6-9f00-7249b74a42f1.png">
## Super simple bug to report on interface:

The main panel of the mist wallet correctly shows four wallets. The left hand side list of wallets shows only three. A bit disconcerting. The list of wallets should expand to display as many wallets on the left hand side as are displayed in the panel, and scroll if needed. I greyed out parts of the image, that's why it looks weird.

**Comment by evertonfraga** [comment]
The sidebar was refactored, this problem should be solved by now.

Issue closed due to inactivity. Please reopen if problem persists.
