### ISSUE TITLE
I cannot sync in Windows 10 ( 64 bits binary distribution)... after 2 days sync the process is restarting!!! The same happens in Win7 and in MacOSX

### ISSUE THREAD

**Issue by rpelaez** [ethereum/mist#1344]
I cannot sync in Windows 10 ( 64 bits binary distribution)... after 2 days sync the process is restarting!!! The same happens in Win7 and in MacOSX
#### System information

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
```
#### Please check the **already existing** issues to keep duplicates at a minimum.

Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:
- Screenshots
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment]
Mist is now many versions ahead. This problem should be fixed. 

Issue closed due to inactivity. Please reopen if problem persists.
