### ISSUE TITLE
Download Wallet is very slowly from China

### ISSUE THREAD

**Issue by 350050183** [ethereum/mist#1357]
#### System information
``````
Version: `0.8.6`
OS & Version: osx
Node type: `geth(default)`
``````

In China,Download the Wallet installer (https://github.com/ethereum/mist/releases/download/v0.8.7/Ethereum-Wallet-macosx-0-8-7.dmg) is very slowly, and always interrupted by time-out exception.
I have tried many times.
It seems the AWS clouds do not optimized for China users, only 17 kb/s downloading rate.
Any suggestions?

**Comment by evertonfraga** [comment]
Hi! I've been trying to get this answer for you on the last day. 

ETHfans have an ethereum download mirror page. They don't have all the binaries combinations yet (wallet + mist), but that'll probably be fixed. 

Here's the link of the latest version (0.8.7)
http://ethfans.org/wikis/Ethereum-Wallet-%E5%9B%BD%E5%86%85%E9%95%9C%E5%83%8F%E4%B8%8B%E8%BD%BD

Worth noticing that you can also download from guthub at higher speeds using a VPN.

**Comment by beenhero** [comment]
@350050183  Due to the GFW, you may need a VPN for better speed. Or you can download from our ethfans.org mirror.
http://ethfans.org/wikis/Ethereum-Wallet-%E5%9B%BD%E5%86%85%E9%95%9C%E5%83%8F%E4%B8%8B%E8%BD%BD

**Comment by 350050183** [comment]
@beenhero 谢谢，之前也注意到了，但看到没有及时更新新版才到这里问。另外，同步节点非常慢有没有什么办法？
