### ISSUE TITLE
crash on tx execution

### ISSUE THREAD

**Issue by emosto** [ethereum/mist#136]
Sometimes Wallet (since ver 0.3.9) crashes after typing in the password and hitting Confirm to execute a transaction.

I am attaching the log collected immediately after a crash:

[node - after crash.txt](https://github.com/ethereum/mist/files/110887/node.-.after.crash.txt)

**Comment by Bubleek** [comment]
So i think you use testnet without sincing with blockchaun data base. You need synchronize before start tx. Just start mist wallet and don't push Skip peer search.

**Comment by emosto** [comment]
Hi,

Not really. The crash is really occasional, after performing several
successful transactions on an up to date blockchain.

Regards,
Emil
На 13.02.2016 01:07 "Alex" <notifications@github.com> написа:

**Comment by Bubleek** [comment]
Ok. But you blockchain.go still importing new blocks. I think you need do few transactions in comand line of geth. Just use --verbosity 6 flag when you do tx inside geth console. Copy/paste result here.

**Comment by frozeman** [comment]
The node doesn't show anything unusual.

I assume its an issue of the Mist app.

could you start Mist for [development](https://github.com/ethereum/mist#deployment) and tell me what the log in the terminal says once it crashes?

@Bubleek the importing of 1 block at a time is normal when he reached the highest block, but thanks for helping!

**Comment by Bubleek** [comment]
@frozeman Ok, understand.

**Comment by luclu** [comment]
How is version 0.7.4 (with geth 1.4.4) behaving for you? There have been considerable improvements under the hood!

**Comment by emosto** [comment]
OK, using the last version of the wallet showed no crashes so far. Thanks.

**Comment by luclu** [comment]
Good to hear, I will close then.
