### ISSUE TITLE
Ethereum Wallet 0.8.7 - icon not showing in about dialog box

### ISSUE THREAD

**Issue by sathishvj** [ethereum/mist#1361]
#### System information

```
Version: `0.8.7`
OS & Version: osx
Node type: `(default)`
```

Issue: Not seeing the ethereum wallet icon in the about dialog.  I saw the same issue with mist 0.8.7 also.  
- Screenshots
  ![screen shot 2016-10-28 at 7 38 12 pm](https://cloud.githubusercontent.com/assets/415647/19809272/3bd502ee-9d46-11e6-98e5-be3651a05fcb.png)

**Comment by luclu** [comment]
Turned out to be some build problem. This doesn't occur on current dev/internal-builds.
Thanks @sathishvj!
