### ISSUE TITLE
My Mist/Electron wallet is not showing the correct ETH ammount

### ISSUE THREAD

**Issue by ETHCOINZ** [ethereum/mist#1364]
Hello,

I have a problem and i cant seem to find the way to fix it. When i look up my account on etherscan.io i see that my account has atleast 1 ETH on it. But when i look at my wallet it says the amount is 0.0018 ETH I wonder what is wrong with my wallet and how do i fix it?

Also in my wallet it says one month since last block (that cant be correct I think) but it is not updating either. But the problem above also excisted when the wallet was up to date. I just downloaded the latest version of mist but same problem there as on the electron wallet.

Here are some screenshots of etherscan and my wallet

![etherscan](https://cloud.githubusercontent.com/assets/23138560/19830686/3a111792-9dfd-11e6-96c7-9a4294e822fb.jpg)
![wallet](https://cloud.githubusercontent.com/assets/23138560/19830688/3ec1f77a-9dfd-11e6-92bb-f20e014b86bd.jpg)

If anyone knows what I have to do please let me know thank you in advance

**Comment by luclu** [comment]
Judging your screenshot you still have to wait for the sync to complete. 
Do you still encounter this issue if the node is fully synced?

**Comment by luclu** [comment]
I will close this as a full sync should resolve this issue.

**Comment by ETHCOINZ** [comment]
It also happens when i am synced

**Comment by ETHCOINZ** [comment]
So the problem is not solved in any way

**Comment by luclu** [comment]
@ETHCOINZ please open the developer console via `CTRL/CMD+ALT+i` and post the output of following commands:
```
web3.admin.nodeInfo.name
web3.eth.accounts.length
web3.eth.blockNumber
web3.eth.getBlock(2463001).hash
web3.eth.syncing
```

**Comment by ETHCOINZ** [comment]
will try this

**Comment by luclu** [comment]
@ETHCOINZ, my bad you have to execute the commands line-by-line (hit return).

**Comment by ETHCOINZ** [comment]
Will try it again and get back with the result thank you
