### ISSUE TITLE
adding account does not work

### ISSUE THREAD

**Issue by HuguesDohmen** [ethereum/mist#1365]
#### System information

```
Ethereum wallet
Version: `0.8.7`
OS & Version: windows10 (64 bit°
Node type: `geth 1.4.18 (GO)
```

I seems not be possible to add an account to my wallet. I see "You have no accounts yet. You need to create at least one account with a strong password."
When I click on the "add account" icon I get a small window "create account" where I have to enter a password. After entering a paswword I click on OK. I see a new smal window saying creating account but this dissapears after about 10sec. and that's it. still no new account.

How do I solve this problem?

**Comment by luclu** [comment]
@HuguesDohmen 10s is way too long. Please open the developer console via `CTRL/CMD+ALT+i` and post the output of following commands:
```
web3.admin.nodeInfo.name
web3.eth.accounts.length
web3.eth.blockNumber
web3.eth.getBlock(2463001).hash
web3.eth.syncing
```

**Comment by tjayrush** [comment]
I am seeing this consistently on 10.10.5 (Yosemite). It happens on both testnet and mainnet. It happens both through the Accounts | New Account menu and the link in the browser. 

Mist opens the new account password page, asks me to confirm the password on the next page, and then simply hangs. If I kill Mist and look in the folder where my keys are kept, I see a new account. If I then re-start Mist, the new account is there. Pretty consistent. Didn't used to happen, but I haven't created a new account for many months until now.

Geth:
Version: 1.4.18-stable-ef9265d0
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.1
OS: darwin
GOPATH=/Users/jrush/src.GitHub/go
GOROOT=/usr/local/Cellar/go/1.7.1/libexec

Mist:
0.8.7

**Comment by luclu** [comment]
Please provide the information here ☝️ https://github.com/ethereum/mist/issues/1365#issuecomment-258022737. Also make sure to use the latest version of Mist/geth.

**Comment by evertonfraga** [comment]
Issue closed due to inactivity. Please reopen if problem persists.

**Comment by x-hovo-x** [comment]
Same for me...
![screenshot 2018-01-26 10 11 03](https://user-images.githubusercontent.com/5663153/35432726-40b28e48-0281-11e8-95ec-b9bca37dadc7.png)

**Comment by jyaltma** [comment]
I am experiencing the same issue using Windows 10 in Parallels, using Ethereum 0.10.0. Here is the output to the following commands:

**web3.admin.nodeInfo.name**
VM96:1293 Uncaught Error: No callback given, sync calls are not possible anymore in Mist. Please use only async calls.
    at EthereumProvider._addResponseCallback (<anonymous>:1293:13)
    at EthereumProvider.send (<anonymous>:1337:10)
    at s.send (2a3fe1c….js:187)
    at Object.e [as nodeInfo] (2a3fe1c….js:187)
    at <anonymous>:1:11
EthereumProvider._addResponseCallback @ VM96:1293
send @ VM96:1337
s.send @ 2a3fe1c….js:187
e @ 2a3fe1c….js:187
(anonymous) @ VM167:1
784VM96:1211 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('file://').

**web3.eth.accounts.length**
VM96:1293 Uncaught Error: No callback given, sync calls are not possible anymore in Mist. Please use only async calls.
    at EthereumProvider._addResponseCallback (<anonymous>:1293:13)
    at EthereumProvider.send (<anonymous>:1337:10)
    at s.send (2a3fe1c….js:187)
    at r.e [as accounts] (2a3fe1c….js:187)
    at <anonymous>:1:9
EthereumProvider._addResponseCallback @ VM96:1293
send @ VM96:1337
s.send @ 2a3fe1c….js:187
e @ 2a3fe1c….js:187
(anonymous) @ VM169:1
12VM96:1211 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('file://').

...And so on and so forth. How can I create an account (test network)? As with the OP, I've "created" about five on the test network, and they show up under Backup-->Accounts-->testnetwork\keystore, but not in the Ethereum app itself. It always just says "You have no accounts."
