### ISSUE TITLE
Can Ethereum Wallet using the same database with geth(Go client) and eth(C++ client)?

### ISSUE THREAD

**Issue by 350050183** [ethereum/mist#1366]
#### System information
``````
Version: `0.8.7`
OS & Version: osx
Node type: `eth/geth`
``````
I am using the latest Ethereum Wallet app (version 0.8.7)  in my Mac OS X system, when select the menu: Develope-Node- Geth or eth, it seems using different local database.
How can i config to use the same database? and are the two client's database structures compatiable?
Thanks!

**Comment by luclu** [comment]
@350050183 no, the databases (state, blocks) are not compatible - every node implementation has its manages its own backend. 

Currently also the keystore is seperated from node to node, although this will change long-term.
