### ISSUE TITLE
No Ok Button on Windows 7

### ISSUE THREAD

**Issue by eburgel** [ethereum/mist#137]
On my Windows 7, there is no **Ok** button, to make the save

**Comment by frozeman** [comment]
Save what?

**Comment by eburgel** [comment]
Sorry, I mean 
Backup Accounts
Backup App Data

**Comment by frozeman** [comment]
Yes it opens the folder and youre supposed to backup these wherever you want.

Im closing this as this features is right now like this, we might add a better backup in the future, i just sneaked that in for now to give people an possibility to backup easily
