### ISSUE TITLE
ethereum wallet attaching to a started ethereum node

### ISSUE THREAD

**Issue by TUTUBIG** [ethereum/mist#1371]
I started the ethereum node and i want start the ethereum wallet attaching to this node ,but how cant do ?   both of them are running on the same PC (Windows 10)

**Comment by luclu** [comment]
@TUTUBIG what version of the node as well as the wallet are you using?
Also is it windows 10 32bit or 64bit?

Please provide:
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

**Comment by TUTUBIG** [comment]
@luclu thanks for your help,this problem has got disappeared
