### ISSUE TITLE
Terrible UX and money lost

### ISSUE THREAD

**Issue by yhnavein** [ethereum/mist#1373]
#### System information
``````
Version: `0.8.7`
OS & Version: linux
Node type: `eth/geth(default)`
``````

Because of the UX of the Mist application I've apparently lost around 7 ETH.

I am quite new to the party however I've created my wallet some time ago. 

And just recently I've first time really used it and that was a big mistake. I have 7 ETH on my account and I am unable to send it anywhere because the password to my account is wrong.

Well, probably I am just stupid from your perspective, that I could not remember or write the initial password down (which is kinda funny, because I saved it in 2 different places to the given account and it's not working).

Well, ok, maybe I did something wrong, but here comes the real fuckup of the Mist UI:

This is the last time I had been using the password for the Account:
![image](https://cloud.githubusercontent.com/assets/516709/19944982/51b7660a-a13e-11e6-8521-2762d7730bbf.png)

And as I said earlier, I wasn't using this account (or eth in general) for some time and when the time has come, well, there was no way to **check** my password (at the beginning I had account balance around 0 ETH). I had to trust my gut, that I saved my password right and I would be able to use it.

Because your client ask for the account password **ONLY** when you want to **SEND** ETH anywhere!

If I knew that my password is fucked up, I would just delete my almost empty account and create a new one with a password (this time I would store it in 3 places and print a fucking screenshot of the Create account window with my password visible).

The situation I presented is an example of the terrible User Experience followed by user grief and anger.

What are some possible fixes for that? I have no idea, but some option for **CHECK** account authorization would be a real life saver.

Thanks

PS. There is one thing good about the whole situation - I was about to deposit on this account much more coins. So now I will just put it on Poloniex and sell instead :)

**Comment by yhnavein** [comment]
Just a side note: `geth --unlock "ACCOUNT NUMBER"` could not decrypt it either using my password, but I would not expect using terminal for validating my account, having the UI open with the same account

**Comment by jones-in-the-fast-lane** [comment]
This.

I think password should need to be entered every time you want to "look" at your wallet. If anything it will help with muscle memorizing your password. The downside is more opportunity for keyloggers.

**Comment by evertonfraga** [comment]
Please check related issues. Some people have built a password cracker to solve this.
https://github.com/ethereum/mist/issues/396#issuecomment-308381562
