### ISSUE TITLE
Wallet won't sync

### ISSUE THREAD

**Issue by Roomec3** [ethereum/mist#1374]
Could someone advice me on what to do, my wallet is saying "one month since last block".

I've been away and just got back to this.

I'm trying to send some coins but my wallet won't send, presumably because it hasn't updated.

Does any one know what i should do?

Thanks

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by Roomec3** [comment]
![screen shot 2016-11-02 at 22 24 13](https://cloud.githubusercontent.com/assets/23201865/19949951/8207ac58-a14c-11e6-9bc3-b136e0edbe98.png)
this is a screen grab of the wallet

**Comment by luclu** [comment]
@Roomec3 please open the developer console via `CTRL+ALT+i` and post the output of following commands:
```
mist.version
web3.admin.nodeInfo.name
web3.eth.blockNumber
web3.eth.getBlock(2463001).hash
web3.eth.syncing
```

**Comment by Roomec3** [comment]
Many thanks Luclu, I think you mean put the code in here, i did that but got this message

![screen shot 2016-11-02 at 22 47 27](https://cloud.githubusercontent.com/assets/23201865/19950313/931f9d78-a14e-11e6-8e07-e33a9db6a003.png)

**Comment by luclu** [comment]
Please paste them one-by-one / each line as a seperate command, hit return.

**Comment by Roomec3** [comment]
Ok so I tried that and it looked good until:

web3.eth.getBlock(2463001).hash

Sorry about this!


![screen shot 2016-11-02 at 22 54 38](https://cloud.githubusercontent.com/assets/23201865/19950451/7e03d69c-a14f-11e6-9433-e2d3f67eb157.png)

**Comment by luclu** [comment]
Could you also please provide the ouput of
```
web3.eth.getBlock(2358930).hash
```

**Comment by Roomec3** [comment]
![screen shot 2016-11-02 at 23 00 21](https://cloud.githubusercontent.com/assets/23201865/19950565/31857dba-a150-11e6-9c7f-86243650e527.png)
This is what it said, should i try all lines of code again, could you advise?

**Comment by luclu** [comment]
There we go!
You seem to be on an old fork according to https://etherscan.io/block/2358930 (compare the hash).
This could be caused by updating to a HF-compatible version of geth/Ethereum Wallet **after** syncing **past** the critical block. 

Please provide the output of
```
web3.eth.getBlock(2350000).hash
```
to confirm this.

Also make sure your firewall is not blocking Ethereum Wallet, as your screenshots suggest (cryptocompare).

**Comment by Roomec3** [comment]
Ah ok Many thanks!!!!

Here is what he latest code said.

I will check my firewall now too, thank you so much

![screen shot 2016-11-02 at 23 10 27](https://cloud.githubusercontent.com/assets/23201865/19950802/aaeb064c-a151-11e6-95cb-34b1c312222a.png)

**Comment by luclu** [comment]
You are welcome.
Unfortunately you might need to do a full resync. Please follow [these instructions](http://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569).
