### ISSUE TITLE
Ethereum-Wallet does not quit when geth started with certain cmdline params

### ISSUE THREAD

**Issue by sathishvj** [ethereum/mist#1375]
#### System information
``````
Version: `0.8.7`
OS & Version: osx
Node type: `geth`
``````

I started geth on the command line with
```
./geth --testnet --networkid 42 --nodiscover --rpc --rpccorsdomain "*" console
``` 

Then I started ethereum-wallet to see if it would connect (hopefully with the testnet enabled).  However, it did not connect.  Then I tried to quit ethereum-wallet, but it refuses to quit.  (It finally quit after quite a few force quits.)

<img width="724" alt="ethereum-wallet not quitting" src="https://cloud.githubusercontent.com/assets/415647/19963434/6314aefe-a1e2-11e6-862b-f20a51245983.png">

**Comment by luclu** [comment]
@sathishvj I'm having trouble to reproduce this. 
Please try to change the `networkid` to 2 or just leave out if you want to connect to the public testnet (morden). Also try to it  append `--rpc ~/Library/Ethereum/geth.ipc` to the geth flags.

**Comment by luclu** [comment]
I will close as I expect this to be resolved.
