### ISSUE TITLE
No linux 32 bit release

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#138]
There is no linux 32 bit release anymore. I'm maintaining packages for archlinux and wont be able to upgrade the PKGBUILD to 0.3.9 ... will 32 bit be dropped in the future releases too?

**Comment by frozeman** [comment]
I didn't put the 32bit release on there as it has no geth packaged. 

Will do now

Liebe Grüße,
Fabian

[frozeman.de]

**Comment by 5chdn** [comment]
thanks
