### ISSUE TITLE
Adding HTTP Proxy Support for Mist (via global-tunnel module?)

### ISSUE THREAD

**Issue by ivica7** [ethereum/mist#1385]
There has already been a ticket on this, which is closed now, however, the reason I am resubmitting this issue: within larger corporate networks, it is often obligatory that http requests have to go through a HTTP proxy. Currently, it's not possible to configure Mist / Ethereum Wallet to use a corporate proxy, which results in errors when Mist tries to fetch the client configuration or when it tries to download the newest geth binary. It makes it difficult to experiment with it within larger corporations.

The problem could be easily fixed, by adding something like global-tunnel(?) module.

**Comment by luclu** [comment]
There are two pieces that have to be proxyfied:
- Mist
- the client (geht, parity, etc) if no external http-rpc node is enabled

#### ethereum client
Geth [does not have](https://github.com/ethereum/go-ethereum/issues/1855) proxy functionlity implemented.
I'm not sure about eth or parity.

#### Mist
According to https://www.npmjs.com/package/electron you should be able to use Mist with a proxy [by creating those environment variables](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables). Perhaps this could be leveraged to create a command-line flag.

**Comment by ivica7** [comment]
You're referring to the request module. As far as I understand the code, Ethereum Wallet / Mist is using the got module (https://www.npmjs.com/package/got). On the same got page you can find:

> You can use the tunnel module with the agent option to work with proxies

**Comment by stritti** [comment]
> According to https://www.npmjs.com/package/electron you should be able to use Mist with a proxy by creating those environment variables. Perhaps this could be leveraged to create a command-line flag.

I use these variables for different tools (like node.js) already, but they are ignored by Mist.

**Comment by Katiyman** [comment]
Currently facing same issue. Connection is getting timed out due to proxy. setting the proxy variables dint help
Any solution/workaround?

**Comment by alexvandesande** [comment]
is it not possible to set your connection globally? I feel this is not desired in a simple user facing app

**Comment by ivica7** [comment]
> I feel this is not desired in a simple user facing app

@alexvandesande this depends on the users you wish to target. I understand Mist as a browser with web3 support targeting the whole world. Lot of interested people (like me) experimenting with the technology are sitting behind corporate proxy servers. As a serious browser, it should offer the possibility to configure a http proxy.
