### ISSUE TITLE
untitled

### ISSUE THREAD

**Issue by mxclene** [ethereum/mist#1386]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files 
 

---

have loaded and run wallet 8.0.7 (the newest one) as it was with previous versions too and can not sync my node, after some experiences with ethereum, especially with posibility of node sync as followed with incaility of use my ethers I think that all that the whole ethreum project is a fraud, i'm not a specialist in software, however i am using the newest recommneded version of the ethereum mist and wallet sofware, my question is if any of the etheum gurus has encountered such problems, i think that it is not their problem, they can exchange their ethers with no limits

**Comment by mxclene** [comment]
thx for your assistance
pls find below information, i don't know why i could ot to attach zip file made with winrar, i bpassed it changing extension to pdf and when attached i'vechanged it back to zip
bw
mclene (chris)  
system windows 7
node eth/geth

![mist_console](https://cloud.githubusercontent.com/assets/22316057/20029367/3f2b89b8-a34a-11e6-83b6-ccf8b4e3f416.jpg)



[nodes.pdf](https://github.com/ethereum/mist/files/573123/nodes.zip)

**Comment by luclu** [comment]
@mxclene your node does not seem to be fully synced. Please open the developer console via `CTRL/CMD+ALT+i` and post the output of following commands:
```
web3.admin.nodeInfo.name
web3.eth.accounts.length
web3.eth.blockNumber
web3.eth.getBlock(2463001).hash
web3.eth.syncing
```

**Comment by mxclene** [comment]
thx for your assistance, i'll do it all according to your hints, sorry about delay, but i've spent some days in the wild forest with no mobiles, no net, no credit cards, no insurance ...
bw
Chris (mclene)
![mistconsole_2016113](https://cloud.githubusercontent.com/assets/22316057/20245340/a172a3e4-a99f-11e6-8731-81bf38017c89.jpg)

**Comment by luclu** [comment]
Pinging @karalabe @fjl, how is it possible that the `web3.eth.blockNumber != web3.eth.syncing.currentBlock`?

**Comment by mxclene** [comment]
i've started using the parity, and after ca. 2 days my mist/wallet are synchronized

**Comment by mxclene** [comment]
however, there is another problem (as described in issue #1365), both wallet and mist do not allow to add account, they require to create a new account

web3.eth.blockNumber returns last synced block number, at present 2642399
 
mist/ethereum wallet 0.8.7
Windows 7
node synchronized with parity (parity.exe --geth)
bw
Chris (mxclene)

**Comment by luclu** [comment]
@mxclene until Mist gets its own account management, you can simply copy the *keyfile* into the client's *keystore* folder:
- geth: `%APPDATA%\Ethereum\keystore`
- parity: `%USERPROFILE%\.parity\keys` (I *think*)

**Comment by mxclene** [comment]
thx, i'll try, however, as described in issue #1365, thee is a problem with creating a new acount, i'll try to do so in about 3-4 hours, not now
bw
Chris

**Comment by mxclene** [comment]
thx, mist sees the main account
bw
Chris

**Comment by luclu** [comment]
Great, I will close this then!
