### ISSUE TITLE
Can't Sync Ethereum Wallet 0.8.7 on Macbook Running OSX Sierra (going on 9 hrs now)

### ISSUE THREAD

**Issue by cjremus** [ethereum/mist#1387]
#### System information
``````
Version: `0.8.7`
OS & Version: osx sierra
Node type: `eth/geth(default)`
``````
Hi Everyone,

This is my first issue posting on Github, so bear with me if I don't get it right the first time!

I've been unable to sync my Ethereum Wallet v0.8.7 on my Macbook running OSX Sierra, for weeks now, on the production network. Today I left my Macbook running, as I was out doing other things, for a full 9 hours and the Wallet still hasn't synchronized.

I tried 0.8.6, then upgraded to 0.8.7. I've deleted the /chaininfo folder a couple times. No matter what I do, I can't seem to sync.

Please help, thanks!

Chris

P.S. - The screen shots are taken after trying to sync for over 9 hours.

![screen shot 2016-11-04 at 7 36 11 pm](https://cloud.githubusercontent.com/assets/6430200/20025607/42482e50-a2c6-11e6-8572-212de947c543.png)

![screen shot 2016-11-04 at 7 36 36 pm](https://cloud.githubusercontent.com/assets/6430200/20025591/1f74dc52-a2c6-11e6-8984-95554c78e9ff.png)

![screen shot 2016-11-04 at 7 36 49 pm](https://cloud.githubusercontent.com/assets/6430200/20025589/1a543236-a2c6-11e6-9545-a0e03b502ce0.png)

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
@cjremus sorry for the inconvenience right now. Many people are currently unable to sync and many nodes are in bad shape. [EIP 158](https://github.com/ethereum/EIPs/issues/158) - which might implemented in two weeks - will resolve these issues. 

The only "workaround" yet is to use a SSD. I did a fully resync today on my Macbook Pro (SSD) in under 3h (perhaps even faster as I've been AFK).

Please upload your `node.log` should there be another issue. Also do you already use an SSD?

**Comment by Stigermann** [comment]
I have the same issue and I am using a 2013 imac with slightly better specs.  I am using a hard drive and not an SSD.  I have not been able to completely sync for several weeks now.  I have been letting my computer run for several days now starting with deleting chain data and I am on block 2,306,170.  Should I try to add an external SSD?

**Comment by luclu** [comment]
@Stigermann I'm not sure if the interfaces are fast enough (latency-wise). You could also try to play with parity's new warp-sync (haven't tried it myself) until the state cleaning HF [is done](https://fork.codetract.io/).

**Comment by 1ranger** [comment]
Is there any update on this? Same issue here.

**Comment by luclu** [comment]
@1ranger only these advices: https://github.com/ethereum/mist/issues/1397#issuecomment-260213007

**Comment by 1ranger** [comment]
@luclu That was no help.  I'm stuck on a single block for the last 12 days.  I updated to the latest version. I'm on El Capitan. 
I missed a ICO because of this. pretty frustrating that there isn't a stable mist platform yet.

**Comment by jetlej** [comment]
+1 I also cannot sync

**Comment by wllmkn** [comment]
here same too. I waited  patiently for more than 4 weeks now. My node is in bad shape.

**Comment by Stigermann** [comment]
I have been trying to sync again with Parity and I am stuck on 2,642,498 best block.  I can't find enough peers to sync.  It seems like ethereum won't sync unless you have a late model computer with an ssd.

**Comment by luclu** [comment]
Could you please try this and give me heads up on the outcome?
>Please try to do a fresh re-sync now that the [state-clearing](https://www.reddit.com/r/ethereum/comments/5fob4s/state_clearing_100_complete/) did finish. 
>
>Doing a fresh sync will reduce the blockchain replica on your computer to ~10G and won't take much longer than 1h on a SSD.
>
>Please make sure to have the [latest version of Mist / Ethereum Wallet](https://github.com/ethereum/mist/releases) installed and follow [this how-to](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555) to reset the chaindata folder to initiate the fresh sync.

**Comment by wllmkn** [comment]
It worked for me within a few hours, thank you!

**Comment by luclu** [comment]
Thank you @wllmkn 
I will close this issue for now.

**Comment by Hummelpups** [comment]
For me changing the NTP Server in TimeSettings from 
- AppleEuropa (time.euro.apple.com)
to
- Apple Amerika (time.apple.com)
did the trick for me.
