### ISSUE TITLE
Bad color scheme, not readable fonts

### ISSUE THREAD

**Issue by alfons66** [ethereum/mist#139]
The fonts in the wallet are very difficult to read. Lightgray fonts on white or lightblue on white. What about other color schemas?

![3aoh2ko](https://cloud.githubusercontent.com/assets/15959312/12724954/a8b10666-c910-11e5-923c-f88afb02809d.png)

**Comment by evertonfraga** [comment]
@alexvandesande Perhaps we should reconsider if we'll keep two themes? Could one of your twitter polls assert that?

**Comment by evertonfraga** [comment]
As it was such hard to mantain a dark theme, and several problems reported, we'll discontinue the dark theme from 0.8.8 onwards. PR: #1362
