### ISSUE TITLE
Cannot open Mist OR Ethereum Wallet on Mac OS 10.11.6 (15G31)

### ISSUE THREAD

**Issue by dskvr** [ethereum/mist#1391]
#### System information
``````
Version: `0.8.7`
OS & Version: Mac OS 10.11.6
Node type: `eth/geth(default)`
``````

I cannot open either Mist or Ethereum Wallet. Right Click and "Open" does not work either. It never opens. Nothing in console matching what I would expect as Ethereum output. I checked existing issues, and all existing Mac issues seem to center around syncing. The application will not even open. 

_Sidenote: I need to execute a contract, are there any alternative wallets that are capable of managing Ethereum Tokens?_

_Screenshots_

It doesn't open. 

_Log files_ 

It doesn't open.

**Comment by dskvr** [comment]
Immediately after opening this issue, I went to show package contents -> contents -> macos and right clicked "Open" approved the "unidentified developer" alert, and it the Mist application opened, but it's not functioning. Seeing empty application windows when anything is selected from menu. Still non-functional.

**Comment by luclu** [comment]
@dskvr this looks interesting. Please backup/rename the folder `/Users/dskvr/Library/Application Support/Mist` and retry to expulse any other system related issues.
Please don't delete the folder if this resolves your problem (yet) - it might be useful to debug the issue.

**Comment by avatar-lavventura** [comment]
I do have the same issue, do you have any suggestion to fix it? @luclu

**Comment by luclu** [comment]
@avatar-lavventura could you please specify what does/doesn't happen? Appending a log like @dskvr did would help very much! To do so, open the terminal an run `/Applications/Mist.app/Contents/MacOS/Mist` (assuming you have Mist copied to the Applications folder.

**Comment by avatar-lavventura** [comment]
Sure please see on https://github.com/ethereum/mist/issues/1686 @luclu

**Comment by luclu** [comment]
@dskvr I will close this issue for now. Please check if you can replicate it with the latest release (currently `v0.8.9`).

**Comment by dskvr** [comment]
@luclu I cannot, Mist is working wonderfully. However, admittedly, I use MetaMask like a fiend 😈
