### ISSUE TITLE
Vicious Circle. How to deposit the only initial(main) account (which can't display incoming transactions by deafult) if you don't have enough GAS on it for making Contract Wallet?

### ISSUE THREAD

**Issue by safrongo** [ethereum/mist#1393]
(sorry for my english grammar)

the case:
I've sent 1 ETH from Poloniex to my Etherium Wallet main account, but I have not recieved it due to the status of the initial account "main account can't display incoming transactions" 
A bit later I found out that only Contract Wallets can display all the transactions, but I can't create the Contract Wallet coz I dont have enough GAS on my main account for creating it....

1st question: 
where is the 1 ETH wich is hang on the way from Polo to my main wallet account adress?

2nd question:
How or where I need to deposit some GAS amount to create the Contract Wallet?
or pls advice me any other way to use my main account without creating the Contract one

for any info Thanks in advance!

**Comment by Lewik8** [comment]
У меня тоже самое

**Comment by evertonfraga** [comment]
Issue closed due to inactivity. Please reopen if problem persists.
