### ISSUE TITLE
Multi-sig Wallet Contract "From" Account Key Missing

### ISSUE THREAD

**Issue by lowend** [ethereum/mist#1399]
![fromerror](https://cloud.githubusercontent.com/assets/16262947/20122501/a835d216-a5c4-11e6-8e66-2ad575348166.png)

Basically, no account information is pulled over only the icon no keys.

This specific account is a mult-sig wallet contract.

When I go to press 'send' nothing happens!

#### System information
``````
Version: latest
OS & Version: linux x64
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
Thank you @lowend, please head over to https://github.com/ethereum/mist/issues/1237. I will close this as a duplicate.
