### ISSUE TITLE
Saved ABI definitions

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/mist#140]
It'd be nice to be able to save ABI definitions for re-use.

Additionally, it would be nice to be able to apply these saved ABI definitions to address types returned by `constant` functions.  That way when viewing a tracked contract which has a constant function which returns an address you could theoretically just click into this address and view it using one of the saved ABI definitions.

**Comment by frozeman** [comment]
I don't fully understand. You have the ABI/JSON Interface button on the right already.
What you say should happen when clicking an address?

**Comment by pipermerriam** [comment]
So for example, Here is the return value of one of the function of the alarm service.  It returns the address of a contract that represents the next scheduled call.

<img width="530" alt="screen shot 2016-02-05 at 3 12 49 pm" src="https://cloud.githubusercontent.com/assets/824194/12861816/fa347600-cc1a-11e5-8ad2-1e72439d4967.png">

This contract was deployed by the Alarm service and has a known ABI.  Currently, If I wanted to introspect that contract I would need to copy/paste the address and add it as a new contract I am watching.  Since these contracts are *ephemeral* I don't exactly want to watch them as much as just inspect their state.

Ideally, I could save the ABI, and then associate it with this function.  The return value could then have a link next to it (or be a link itself) that would let me view the contract as if I was watching it.

**Comment by frozeman** [comment]
How you would link the son Interface to any arbitrary address?

The main issue right now is, that actually the contract stuff will move into its own dapp and my work is focused on mist and web3.js right now.

I keep this open as idea.

**Comment by pipermerriam** [comment]
I could imagine having saved some commonly used contract ABI's and it having a "view as" dropdown next to it that let you select the appropriate ABI.  If you wanted to get really fancy you could go as far as comparing the code at that address to the known 4-byte signatures and potentially narrowing that list down to a single ABI.

**Comment by frozeman** [comment]
This might be useful once i work on the contract registry.

**Comment by alexvandesande** [comment]
Currently it shows you a link to the contract, if you are watching it. Does this solve this issue?

**Comment by pipermerriam** [comment]
It's not practical to *watch* all of them as there are potentially 100's of these contracts.  

Think of an on-chain exchange where every order was represented by it's own contract.  Nobody want's to watch every order.  Instead they'd want to be able to browse each order with the UX knowing somehow what the ABI it should use to display the contract.
