### ISSUE TITLE
Mist-win64-0-8-7.exe crashes 

### ISSUE THREAD

**Issue by qubit1729** [ethereum/mist#1400]
Hi,
Obviously nobody is testing the software.
The reason of the crash is a 32bit exe running on a 64bit architecture.
Header of .exe shows 32bit compiled with Microsoft Visual C++ 8 which is pretty old...
regards, qubit1729

**Comment by luclu** [comment]
Closed in favour of https://github.com/ethereum/mist/issues/1318
