### ISSUE TITLE
Updating meteor breaks mist 0.8.7

### ISSUE THREAD

**Issue by giacecco** [ethereum/mist#1402]
#### System information
``````
Version: `0.8.7 from sources`
OS & Version: `linux (Fedora 24)`
Node type: `geth`
``````

Starting meteor in mist's ```interface``` folder suggests upgrading it...

```
[giacecco@giaceccos-linux interface]$ meteor
[[[[[ ~/Downloads/mist-0.8.7/interface ]]]]]  

=> Started proxy.                             
=> Started MongoDB.                           
=> Meteor 1.4.2.1 is available. Update this project with 'meteor update'.
=> Started your app.              
(...)
```

... but if you do, it causes https://github.com/ethereum/mist/issues/1401 . 

Reinstalling from scratch fixes it.

The full meteor upgrade process is shown at https://gist.github.com/giacecco/44547b06c585592f21846970ba4667fe in case it can suggest what exact component does the damage.

**Comment by frozeman** [comment]
Thanks for the gist.
You shouldn't update meteor yourself, it will surely break some dependencies
