### ISSUE TITLE
mac OS  how connect private chain

### ISSUE THREAD

**Issue by jwter** [ethereum/mist#1403]
#### System information
``````
Version: `0.8.7`
OS & Version: osx
Node type: `eth/geth(default)`
``````
I create a private chain on mac OS... and start server with 
"geth --identity "SMYetherum" --datadir "ethData" --rpc --rpccorsdomain "*" --rpcapi "db,eth,net,web3"  console 2"
all right.   output "Welcome to the Geth JavaScript console!"
now, I want to deploy a contract with ethereum wallet.
but report a error 
"Starting Server Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use"
when  launch ethereum wallet...
so  if i want deploy a contract with ethereum wallet how to config or do something  ?

**Comment by luclu** [comment]
@jwter this happens because Ethereum Wallet tries to look for a socket file at `~/Library/Ethereum/geth.ipc`. As this is not available it will start its one node listening on the same default port.

Simply append this flag to your geth command: `--ipcpath ~/Library/Ethereum/geth.ipc`

**Comment by jwter** [comment]
OK... I want connect private chain by Ethereum Wallet  deploy contract.. 
could you tell me . to do something  ?

**Comment by luclu** [comment]
I'm not sure if I understand your intent. As soon as your private chain is initiated and at least one node is mining you will be able to deploy contracts. Please refer to this guide if you are unsure how to proceed. http://ethdocs.org/en/latest/network/test-networks.html?highlight=private#id3

Be aware that the `--genesis` flag has been dropped in favour of `geth init`. I created a PR for those changes to be reflected in the docs.
