### ISSUE TITLE
Awaiting Exchange - Shifty

### ISSUE THREAD

**Issue by naskarbi** [ethereum/mist#1412]
Deposited bitcoin to open ethereum wallet but the status is still Awaiting Exchange after10 hrs period of wait.

**Comment by luclu** [comment]
@naskarbi please follow the troubleshoot at https://github.com/ethereum/mist/issues/687

**Comment by naskarbi** [comment]
Hi,
Here is the story after waiting for almost week my ethereum blockchain not
downloaded completely however I made the payment on Shifty around 3.77 *μbtc
*.

Now as my computer halted I deleted all the ether folders and started
reinstalling again on different drive.
However it seems I lost the payment which I made on Shifty.

Could you please help recover the amount.

Below are the details where I made the payment.

Send 0.0037656   Bitcoin to
1QDQ5ZFNwZNnxG7R7bE83pk3NuX3BW3jUi

It will be converted into 0.25  Ether, and sent to
0x19cde32890c736c72f0babee4024c67b74ebcd5a

Regards,
Bijoy

**Comment by luclu** [comment]
@naskarbi do you still have a backup of the account's keyfile? On Windows you will find the file under `%APPDATA$\Ethereum\keystore`. You can always use another wallet that does not require syncing like http://myetherwallet.com.

**Comment by naskarbi** [comment]
No I don't , made a shift+delete as this enormous volume of files crippled
my laptop.

I need help to open ethereal wallet.
Did I lose the invested btc ?

Rewards,
Bijoy

**Comment by luclu** [comment]
Unfortunately yes. You can try out a recovery software to restore it, but for 0.25 ETH it probably not worth the trouble.

**Comment by luclu** [comment]
@naskarbi I will close this for now.
