### ISSUE TITLE
installation problem on ubuntu 16

### ISSUE THREAD

**Issue by max-l** [ethereum/mist#1418]
## Ubuntu version : 

4.4.0-45-generic
max@max-desk:~/pdev/chartaleth$ 
max@max-desk:~/pdev/chartaleth$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

I ran dpkg with : 

     dpkg --install /home/max/Downloads/Ethereum-Wallet-linux32-0-8-7.deb 

and got : 

```
Selecting previously unselected package ethereumwallet:i386.
(Reading database ... 407052 files and directories currently installed.)
Preparing to unpack .../Ethereum-Wallet-linux32-0-8-7.deb ...
Unpacking ethereumwallet:i386 (0.8.7) ...
dpkg: dependency problems prevent configuration of ethereumwallet:i386:
 ethereumwallet:i386 depends on libappindicator1.
 ethereumwallet:i386 depends on libnotify-bin.

dpkg: error processing package ethereumwallet:i386 (--install):
 dependency problems - leaving unconfigured
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Errors were encountered while processing:
 ethereumwallet:i386

```

**Comment by mirandole** [comment]
I had this issue too.

Try to install gconf2
`sudo apt install gconf2`

Then do a purge of the pkg installation with
`sudo dpkg --purge --force-depends`

and try to install Ethereum Wallet again with
`sudo dpkg -i Ethereum-Wallet-linux32-0-8-7.deb`

If it doesn't work try
`sudo dpkg -i --force-all Ethereum-Wallet-linux32-0-8-7.deb`
