### ISSUE TITLE
proposal of setting private key path

### ISSUE THREAD

**Issue by franklili3** [ethereum/mist#1419]
Private key is the most important file, hacker usually steal the private key. So for the security of ether, I suggest setting private key path in the mist, user can set U disk as the path of private key. After user extracts U disk, there is no private key in the computer, so hacker can not steal the private key.

**Comment by luclu** [comment]
@franklili3 could you please elaborate on what a "U disk" is? Do you refer to USB Sticks/Flash drives or hardware authentication modules?

**Comment by Nogreedy** [comment]
I think he only wants to transfer private key "elsewhere"... perhaps HDD or USB stick...
It's a very good suggestion.
Is there a simple way to indicate Mist keystore directory is on an other device (HDD or USB) on Windows 10 and then to change default location %APPDATA%/Ethereum/keystore ?
--keystore CLI option (perhaps)?

**Comment by luclu** [comment]
From a security perspective this might only help to mitigate against Ethereum targeting malware **with hard-coded paths for keyfiles**.
This won't help against any other sophisticated malware. 

Though you should be able to accomplish it by passing the follow flag to Mist/Ethereum Wallet:
```
--node-keystore <path>
```

**Comment by evertonfraga** [comment]
could you set aliases from U to the keystore directory and have this solved?
