### ISSUE TITLE
Uncaught Exception: Error: Failed to set path

### ISSUE THREAD

**Issue by tymat** [ethereum/mist#142]
![screen shot](http://i.imgur.com/pTmnp1M.png)

```
Uncaught Exception:
Error: Failed to set path
    at Error (native)
    at Object.<anonymous> (/Applications/Ethereum-Wallet.app/Contents/Resources/atom.asar/browser/lib/init.js:143:5)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:151:18)
    at node.js:1005:3
```

**Comment by frozeman** [comment]
Some details would help. Like os. When it happened. 

Looks like electron could determine some path. Do you have any custom library paths it so?

**Comment by tymat** [comment]
OS X El Capitan.  Latest (beta 6) of Mist.  

No custom library paths.

This happens when starting up Mist for the very first time.  This is a new macbook with a fresh install of the OS, homebrew, etc...

**Comment by frozeman** [comment]
Strange issue. The error is thrown [here](https://github.com/atom/electron/blob/master/atom/browser/api/atom_api_app.cc#L285-L294), but seems to be electron internal.

I have the same system and no problems.

Could be related to: https://github.com/atom/electron/issues/3447

**Comment by tymat** [comment]
Running electron-prebuilt works fine on this machine.

**Comment by frozeman** [comment]
can you create basic app and use 
```js
const app = require('app'); 

global.path = {
    HOME: app.getPath('home'),
    APPDATA: app.getPath('appData'),
    USERDATA: app.getPath('userData')
};
```
Maybe this throws the error then

**Comment by tymat** [comment]
![Gets the same error](http://i.imgur.com/Tuog2vH.png)

Same error.

**Comment by frozeman** [comment]
I thought so, so its a problem with electrons path detection..

**Comment by tymat** [comment]
This was an issue with not being able to write to the ~/Library/Application Support folder due to some underlying issue with El Capitan.

**Comment by owenayres** [comment]
Just like to leave my two cents incase anyone has the same issue and this does not solve it.

> I had this problem and the issue was because of special/not-allowed characters inside the name property of my app's package.json file. 

Inside my package.json file for my app (that is bundled with the app source), the name property had a colon inside it. This was causing this exact issue. Removing the colon from the name stopped this issue from happening and launched the app normally again.
