### ISSUE TITLE
eth. wallet empty

### ISSUE THREAD

**Issue by lumicon** [ethereum/mist#1429]
#### System information
``````
Version: `0.0.0`
OS & Version: windows7 64
Node type: `eth/geth(default)`
``````
hi, by opening my ethereum wallet after a while, suddenly no account in there anymore.
please, how to get my account in there again?  i've got an appdate ethereum backup and my password...
thank you!

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
@lumicon can you please upload the `node.log` files?

**Comment by lumicon** [comment]
where is it pls? 
thank you!

**Comment by lumicon** [comment]
there are severals; node.log.1, node.log.0 and node

**Comment by lumicon** [comment]
now i put my appdata backup into appdata and there are my two accounts again, but EMPTY! ooops where are my ethers?

**Comment by luclu** [comment]
Make sure that your client is fully synced. You can use a blockchain explorer to check the "current state" of your account: etherscan.io/

**Comment by lumicon** [comment]
ok, thank you! ..it's still working; 31% - after 1 hour -- seems very strange

**Comment by lumicon** [comment]
let it run the whole night but it seems to be frozen, nothing changes, got stuck at 75%

**Comment by luclu** [comment]
Try to restart it. You can also use http://myetherwallet.com to transfer the Ether.

**Comment by lumicon** [comment]
thank you! tried this, but besides the option of creating a ne wallet i don't find any possibility to open or load my existing wallet/ethers...?

**Comment by lumicon** [comment]
solved

**Comment by ASardar** [comment]
Hi Lumicon, how did you solve this? I just opened my wallet and everything is empty.
