### ISSUE TITLE
Транзакции

### ISSUE THREAD

**Issue by Lewik8** [ethereum/mist#1430]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by Lewik8** [comment]
Я послал 0.5 ETH  к моему Etherium Wallet основного счета, но я не получил его из - за статуса первоначального счета "основного счета не может отображать входящие транзакции"  Чуть позже я узнал, что только Договор бумажники может отображать все транзакции, но я не могу создать кошелек контракта сог я не имею достаточно газа на основном счете для его создания ....  вот ссылка отправлено:(https://etherscan.io/address/0x06722Be69a4b74dD4a2054E11cB16e3A210254b4) в кошельке не отоброжаеться. вопрос:  Как и где мне нужно внести некоторое количество газа , чтобы создать кошелек контракт?  Или Pls советы мне любой другой способ использовать свой основной счет без создания договора один  за любую информацию Спасибо заранее!

**Comment by luclu** [comment]
@Lewik8 please use english or add a translation.

**Comment by Lewik8** [comment]
I sent my 0,5 ETH Etherium Wallet mist test, but I did not get sent here is the link: (https://etherscan.io/address/0x06722Be69a4b74dD4a2054E11cB16e3A210254b4) not otobrozhaetsya purse What I do like to return to the main pereotpravit or purse Network ? for any information Thanks in advance!

**Comment by luclu** [comment]
@Lewik8 please be patient. Your node needs to be **fully** synced.

**Comment by evertonfraga** [comment]
Issue closed due to inactivity. Please reopen if needed.
