### ISSUE TITLE
Delete Smart Contract

### ISSUE THREAD

**Issue by fraspadafora** [ethereum/mist#1434]
#### System information
``````
Version: `0.8.7`
OS & Version: windows
Node type: `geth(1.4.18)`
``````

There is no possibility to delete Smart Contracts that I don't want to watch anymore in the "Contract" area.
Is there any possibility to add a button to remove a watched Smart Contract?

Thank you.

**Comment by luclu** [comment]
There is a rather obscured button that will appear as you hover the contracts name (in detail view).

**Comment by evertonfraga** [comment]
Issue closed due to inactivity. Please reopen if problem persists.
