### ISSUE TITLE
Is there a REAL update from Geth with Mist?

### ISSUE THREAD

**Issue by Nogreedy** [ethereum/mist#1437]
Version: Ethereum Wallet Beta 0.8.7
OS & Version: windows 10/64 bits
Node type: `geth`

Please, answer a simple question : Is there really Geth update when you update Mist Wallet?
It seems it's very important to use latest geth client (v1.5.2) to succeed November 22 ETH hard fork.

https://blog.ethereum.org/2016/11/18/hard-fork-no-4-spurious-dragon/

It's indicated from Ethereum Wallet and Mist Beta 0.8.6 : Changes : "Also, 0.8.6 adds a possibility to update the underlying ethereum client automatically, without need of a new Mist version. ".
What is a "possibility to update"?

People are saying on reddit that it doesn't work well...
https://www.reddit.com/r/ethereum/comments/5dpd9e/hard_fork_no_4_spurious_dragon_ethereum_blog/da6j9f3/

I checked myself and I use Ethereum wallet 0.8.7 BUT with Get 1.4.18 (Go) and it's *not* the last Geth version ... geth last version is 1.5.2...

Can you confirm, please? manual or automatic Geth update in Mist?
Thank for your great work.

**Comment by luclu** [comment]
@Nogreedy thank you for inquiry, as we wanted to directly jump to `1.5.x` the decision was made against `1.4.9`. But as `1.5.0` was basically a rewrite of many modules we preferred to wait some more days in case there were issues with the release.
Now that `1.5.2` is available and no major issues did surface, we prepared are making an update available: see https://github.com/ethereum/mist/pull/1436
ETA: monday morning

**Comment by Nogreedy** [comment]
Thanks for your answer... but, yes, there is now a major issue in geth 1.5.2...
https://blog.ethereum.org/2016/11/25/security-alert-11242016-consensus-bug-geth-v1-4-19-v1-5-2/
Please auto-update to geth 1.5.3
https://github.com/ethereum/mist/blob/develop/clientBinaries.json

**Comment by luclu** [comment]
`1.5.3`is life. Please restart to update.
