### ISSUE TITLE
If IPv6 is available Mist only listens to IPv6

### ISSUE THREAD

**Issue by anonCo** [ethereum/mist#1439]
#### System information
Version: `0.8.7`
OS & Version: linux

I have a home network which is ipv6 capable (internal network and WAN). Real ipv6 and no ipv6 over ipv4 tunneling. Mist does only listen to incoming ipv6 connections but no ipv4 connections. It does connect to ipv4 addresses but only listens for incomming ipv6 connections but not ipv4. I think it should listen to both by default.

Usecase: Start Mist, have a very slow sync. Open your firewalls and router for port 30303 to help speedup things. Nothing happens. You find out that you are only listening for ipv6 connections.
Downgrade your whole network to ipv4? No way.

**Comment by luclu** [comment]
@anonCo as this is related to geth, please head over to their issue tracker at https://github.com/ethereum/go-ethereum/issues and reopen it!
I tried to locate any related issue there but could find any.
I will close this here.
