### ISSUE TITLE
Creating a contract using a wallet contract doesn't work

### ISSUE THREAD

**Issue by ferni** [ethereum/mist#144]
So, using the "Deploy contract" interface, and using a multisig wallet contract as a source, does not seem to work. Some transaction happens, and I see it in the history as:

**Multi Wallet →  0x0000000000000000000000000000000000000000**

Which is different than when creating directly from an account. Also, the new contract does not appear on the Custom Contracts section.

**Comment by frozeman** [comment]
Yes i think deploying a contract through another contract doesn't work right now..

**Comment by luclu** [comment]
Keep an eye on blog.ethereum.org and the [Ethereum Improvement Proposals](https://github.com/ethereum/EIPs) for now. There is currently nothing we (in Mist) can do about it.
