### ISSUE TITLE
Mist Wallet Balance for Subtokens EUR/USD/BTC

### ISSUE THREAD

**Issue by awrelll** [ethereum/mist#1440]
Hello guys,
I was thinking that a nice feature would be a value count for subtokens also (i.e. REP, GNT, DGD, ICN etc.).
Hope to see this in some future Mist version, depending on the team's priority list 👍

**Comment by luclu** [comment]
remotely related: 
>  Have Ether balance shown in GBP (Enhancement) #1415

**Comment by evertonfraga** [comment]
Added GBP, EUR and BRL.
