### ISSUE TITLE
Wallet 0.8.7 Transaction dissipated. 

### ISSUE THREAD

**Issue by FotG** [ethereum/mist#1442]
#### System information
``````
Wallet 0.8.7 x64
Windows 10 x64
``````

I created a transaction and sent a couple ETH. After a couple hours nothing had happened and I noticed it had not received any block updates for 7 hours, a common issue fixed by restarting the client. I restarted the client and found the transaction had disappeared. There is no record I attempted to send any ETH.

**Comment by evertonfraga** [comment]
Issue closed due to inactivity. Please reopen if problem persists.
