### ISSUE TITLE
No matter what, I can't create a wallet inside Mist/Ethereum...

### ISSUE THREAD

**Issue by palex9** [ethereum/mist#1449]
E. is fully synced, I have created a couple accounts, over 2 Ether total available.
Have restarted the mac and apps several times already and every time I try to create a wallet contract I get the exceeds gas block error. Not even attempting to run my own or some downloaded program just the ADD WALLET CONTRACT feature....

**Comment by frozeman** [comment]
The current issue is that the gas limit is pushed down to 2M by miners and the wallet contract needs 1.8M or more..
We will update the wallet contract to a cheaper one at some point, until then we need to wait until miner move the limit up again, which should happen now after this fork

**Comment by khovratovich** [comment]
If you recompile the contract with Solidity of version 0.4.4 or higher, it will fit into 2M of gas.

**Comment by palex9** [comment]
I am just a user who wants to check this out, no interest in having to recompile, program, etc. If the wallet contract is part of the installation is should just work.....!

**Comment by evertonfraga** [comment]
Issue closed due to inactivity. Please reopen if problem persists.
