### ISSUE TITLE
Add a copy/paste context menu

### ISSUE THREAD

**Issue by ferni** [ethereum/mist#145]
I think it's pretty common for GUIs to have this functionality, and expected by the user.

**Comment by evertonfraga** [comment]
@ferni your intention is to copy addresses or anything else?

**Comment by luclu** [comment]
I speak out against this as a **globally activated** feature as this introduces an UX-element that breaks the simple and minimal UX.
But I like to see this on input-fields as many non-tech users historically know about the right-click context-menu, but not about shortkeys.

**Comment by ferni** [comment]
@evertonfraga Mostly addresses, but there's also the "Deploy Contract" section, where you may want to copy/paste Solidity code, and the JSON interface on the "Watch Contract" section.
