### ISSUE TITLE
Missing Ether - Wallet Mist

### ISSUE THREAD

**Issue by eeonee** [ethereum/mist#1451]
#### System information
``````
Version: `0.8.7`
OS & Version: windows
Node type: eth/geth
``````

Hi,

I have encountered a few issues.

When i first made my ether account i can not remember the password ( nor do i remember setting a password ).
My coins dont display correct in my account.
Id appriciate it if someone can help me solve this.

I know it sounds stupid - but i can not remember setting a password - i did read the net for how to go about it using GETH and a few other things like Myetherwallet but it does say its encrypted.

To go onto the next point, my http://ethermine.org/miners/d069D5786fc3b69F7De0a41F0acC86450e173B33/payouts payout balance should be way more than 5 as it shows in my account - but on my miner i know i have mined 10 + . Why is my ethereum wallet not showing the correct ether?

I have full access to my wallets but they also show wrong figures, i created another wallet under this address : 0x6D7e5C89d779D9bEDB8937f09C9007238CFC19E0

My balance shows as 0 still, am puzzled - not sure what to do. Here a SS of my wallet :
![image](https://cloud.githubusercontent.com/assets/23699070/20560584/02ba5f1e-b172-11e6-9ebf-999fc51716dd.png)

Please if someone can help me?

**Comment by evertonfraga** [comment]
That could have been either a sync or a display issue. From your account history, I can check the  that it matches what you were expecting.

**Comment by eeonee** [comment]
@evertonfraga why have you closed this?
