### ISSUE TITLE
wallet stopped downloading blocks

### ISSUE THREAD

**Issue by HuguesDohmen** [ethereum/mist#1456]
#### System information
``````
Version: Ethereum wallet V 0.8.7
OS & Version: windows 10
Node type: `geth 1.5.2`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:
![afbeelding](https://cloud.githubusercontent.com/assets/23154595/20604908/22161054-b269-11e6-88a9-76e57ac1ca7a.png)

![afbeelding](https://cloud.githubusercontent.com/assets/23154595/20605007/81d69cb6-b269-11e6-83c7-4cec19f5b27e.png)

![afbeelding](https://cloud.githubusercontent.com/assets/23154595/20605056/b00ab504-b269-11e6-98bf-2d1e2d90c574.png)

![afbeelding](https://cloud.githubusercontent.com/assets/23154595/20605085/d0450324-b269-11e6-9e0a-5053fa395594.png)

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files 
 
[NodeLogfiles.zip](https://github.com/ethereum/mist/files/611801/NodeLogfiles.zip)

**Comment by HuguesDohmen** [comment]
The wallet stopped downloading the blocks.
I tried via prompt command: same result.

**Comment by luclu** [comment]
@HuguesDohmen please restart the app to update to geth `1.5.3`. This should fix it.
