### ISSUE TITLE
ethereum node needs to sync - download always starts from block 0 

### ISSUE THREAD

**Issue by hansvde** [ethereum/mist#146]
Hi
When i start the ethereum wallet () it needs to sync the ethereum node. The download of the blocks start from zero. Is the history not stored locally?

**Comment by frozeman** [comment]
I guess this is because you never relly fully sync up. The first sync is a fast sync, which can only complete once its fully synced to the last block.

Make sure you let it sync and don't loose the internet connection.

**Comment by hansvde** [comment]
yeah yesterday it took again 3 hours, but since then it added the blocks.
works fine now

**Comment by hansvde** [comment]
but fast? first sync took me 12 hours i guess :-(

**Comment by frozeman** [comment]
You're on windows? maybe you had no peers? no internet?

**Comment by kylanhurt** [comment]
It has also taken me several hours and it's not complete yet. I'm on Windows (only because I don't want to try installing stuff on a Linux Virtual Machine), but I'm curious what part that would play.
