### ISSUE TITLE
Mist sync very slow after hard fork

### ISSUE THREAD

**Issue by More-decentral** [ethereum/mist#1464]
``````
Version: `0.8.7`
OS & Version: Mac osx 10.12.1
Node type: `geth 1.5.3`
``````

My Mist sync has become very slow since the recent hard fork.  Should I delete my chain data file and re-sync the chain from the genesis block (again)?

In the past, whenever a new Mist version is installed, the sync became very slow.  I had to delete the chain data in order to speed up the sync process.  Wish for a light client for Mac to save me from time consuming sync.

**Comment by Nogreedy** [comment]
IMHO state clearing on the way...
https://www.reddit.com/r/ethereum/comments/5es5g4/a_state_clearing_faq/

**Comment by mdbtaa** [comment]
Based on what has already been written, I'm running an Ethereum wallet (V 0.8.7, Windows 10 Home, Geth 1.5.3) and I'm experiencing the same VERY slow synching. Based on the state clearing article I take it I should just be patient and wait for all the empty accounts to be removed?

**Comment by TrevorHilder** [comment]
I now find that geth 1.5.3 under Ubuntu 16.04 LTS is falling further and further behind trying to sync the public blockchain. To all intents and purposes, it is useless. I have deleted the chaindata twice and fast sync only took a few hours, but, once fast sync turned itself off, I have never been less than a hundred blocks behind. After a few days, I am now only on block 2,705,740. and therefore over 3,200 blocks behind.

It looks like I have two alternatives:
1) Wait patiently, hoping that the state clearing finishes and everything speeds up again.

2) Change to Parity.

Any other ideas?

Regards,
  Trevor

**Comment by frozeman** [comment]
Im not sure if parity is faster. But yes 1 is the only real solution.

**Comment by TrevorHilder** [comment]
@frozeman I installed Parity on the Ubuntu 16.04 LTS machine yesterday evening. By this morning, it was fully synced to the public blockchain :-)

**Comment by chalachala** [comment]
Syncing is so slow it wont keep up and I get farther and farther behind with Ether Wallet Sync.  When is this going to be fixed?  Completely useless right now

**Comment by More-decentral** [comment]
Now the state cleaning is over.  I have deleted the chaindata file and re-synced the whole chain.  Very fast.

**Comment by chalachala** [comment]
can you please teach me how to find the chaindata file?

**Comment by MELCHEZEDEK776** [comment]
Yes I would like to know how to find the chaindata file as well.

**Comment by More-decentral** [comment]
I only know where Chaindata file is on Mac: ~Library/Ethereum/Geth/chaindata

Note that Library is a hidden folder for security reason.  Make sure you don't accidentally delete any other files there.  To  temporarily reveal the ~/Library folder is to open Finder. On the menu bar, at the top, select Go to reveal the drop-down menu and then hold down the Option key (marked ALT) and you will see the ~/Library folder appear.

**Comment by evertonfraga** [comment]
Issue closed due to inactivity. Please reopen if needed.
