### ISSUE TITLE
Cannot use storage type pointer

### ISSUE THREAD

**Issue by Chillli** [ethereum/mist#1467]
When I want to publish a smart contract, Mist shows it cannot be compiled.

![image](https://cloud.githubusercontent.com/assets/15898679/20652850/ed17a700-b501-11e6-88d4-19f0c225157e.png)

But the same contract can be created throw browser-solidity.

**Comment by frozeman** [comment]
Mist is always a bit behind with the  solc compiler. We will update solc with the next release

**Comment by luclu** [comment]
@Chillli FYI 
>  [npm] update solc to 0.4.4 #1469
