### ISSUE TITLE
Ether not showing up in account after deposit. 0.8.7, WIN 10, freshly Synced 

### ISSUE THREAD

**Issue by tontobob** [ethereum/mist#1472]
#### Windows 10   64 bit
``````
Version: `0.8.7`
OS & Version: Windows 10  64 bit 
Node type: `eth/geth(default)`
``````

#### I Tried to fund my main "EtherBase" account after downloading yesterday and syncing nodes 100% today. I sent just .005 BTC or .408 Ether from my Electrum Acct. to fund my main ether account for a wallet. I used the " Fund with Bitcoin" button. Everything seemed to work just fine, when finished it said "0.005 BTC was converted to 0.040844737 ETH and sent to 0xddC730A02a5aC656D433FDC11B118C57b9f962c0" Then I checked my main account and had a 0 ETH and 0 BTC balance. I should have 0.040844737ETH. I have tried closing and opening mist 2 times and it has been almost 2 hours and I am still yet to have my ETH show up in my account. Like I said, I literally finished syncing nodes TODAY.  Why did my money disappear? How can I get it to show up? Thank you!

PICS:

![img_2190](https://cloud.githubusercontent.com/assets/24235512/20689523/d9f76c18-b593-11e6-80d5-c54613b28490.JPG)
![img_2191](https://cloud.githubusercontent.com/assets/24235512/20689526/e081428e-b593-11e6-9fdf-ed75401e24f4.JPG)
![img_2192](https://cloud.githubusercontent.com/assets/24235512/20689527/e28c0ef6-b593-11e6-9db9-049fc0859c45.JPG)
 
![img_2193 1](https://cloud.githubusercontent.com/assets/24235512/20689657/8f210d60-b594-11e6-96ec-a15d23b4ddde.JPG)

**Comment by luclu** [comment]
@tontobob please follow [this small troubleshoot-guide](https://github.com/ethereum/mist/issues/687), feel free to ask any question.

**Comment by tontobob** [comment]
UPDATE: I got the problem fixed, it was not a problem with ethereum program or code, it was a problem with shapeshift. I contacted shapeshifts customer service and was sent my ether in less than a day!!!

**Comment by luclu** [comment]
Good to hear this resolved! :)
