### ISSUE TITLE
When Mist running, Geth running in light mode will have Synchronisation failed issue

### ISSUE THREAD

**Issue by pplwjd** [ethereum/mist#1474]
#### System information
Version: Geth`1.5.3` , Mist 0.8.7
OS & Version: windows 8.1 64bit
Node type: `geth`

First I ran Geth in light mode, everything was ok. Then I started Mist and Geth cannot sync any more. Geth console display as follow: 
> I1129 12:51:24.024564 core/headerchain.go:331] imported 2 headers in   6.002ms. #2713814 [f95c8f9b… / 7b881efd…]
I1129 12:51:24.584106 eth/downloader/downloader.go:1198] Rolled back 2 headers (LH: 2713814->2713812, FB: 0->0, LB: 0->0)
I1129 12:51:24.585104 eth/downloader/downloader.go:305] Synchronisation failed: block body download canceled (requested)
I1129 12:51:58.665624 eth/downloader/downloader.go:305] Synchronisation failed: receipt download canceled (requested)
I1129 12:52:24.321210 eth/downloader/downloader.go:305] Synchronisation failed: state data download canceled (requested)
I1129 12:52:56.721830 eth/downloader/downloader.go:305] Synchronisation failed: receipt download canceled (requested)
  
When I closed Mist, Geth sync was ok again. 
-- Check the console, of Mist :  
![mist_console](https://cloud.githubusercontent.com/assets/5856591/20698748/226ef45c-b63e-11e6-91af-053b9bc2fea7.png)

**Comment by pplwjd** [comment]
The files of node.log.X have nothing updated.

**Comment by frozeman** [comment]
The wallet does a lot of complex filter and log retrials. I didn't tested it myself yet, but im sure this is the reason why its failing.

Also the light client is in alpha.

Will take a look at this when i get to it.

**Comment by evertonfraga** [comment]
We've enabled the Light Client on Mist 0.9.1, under Develop menu. 

Thanks for reporting.
