### ISSUE TITLE
How do I delete blockchain files and fastsynch?

### ISSUE THREAD

**Issue by mdbtaa** [ethereum/mist#1475]
#### System information
``````
Version: `0.8.7`
OS & Version: Windows 10
Node type: geth(default)`
``````
I've been told to run the following commands to clear my blockchain files and fast synch.

>geth removedb
>geth --fast --cache=1024

But from where do I run these commands? I tried the Wallet Console but just get error msgs.

**Comment by luclu** [comment]
@mdbtaa you can simply follow [this guide](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555) or issue those commands in the OS's terminal.

I will close this for now, though don't hesitate to ask any question.
