### ISSUE TITLE
What's a usual "expected time" for Wallet creation?

### ISSUE THREAD

**Issue by wappinghigh** [ethereum/mist#148]
Using Win 0.3.5 version of Mist/Wallet
An Etherbase Account has been set with a password
Going onto the set up of a simple wallet, what is the expected time for the blockchain to do this?

Under a minute? Couple minutes? Couple hours?

Seems real slow. Like hours... I'm using a 2-3 yr old laptop with AMD 1.4 Dual Core 4 RAM. Standard but reliable WIFI Anything gives here? Thanks

**Comment by wappinghigh** [comment]
Ok It finally went thru in like 3-4 hours. Set up is confusing. Says you need to have at least one ether to confirm a wallet yet you can't receive ether into your account before you set up a wallet! What is that all about? Thanks.

**Comment by frozeman** [comment]
This message comes only when youre on a non-synced main chain, testnet or private net.
are you sure you synced to the last 900k block?

**Comment by wappinghigh** [comment]
nope.. So let the sync happen?..that takes hours...

**Comment by frozeman** [comment]
The contract wallet is a contract and can only be mined if youre on the latest blog.

**Comment by alexvandesande** [comment]
Just a FYI you don't actually need a wallet in order to store ethers, its just extra security

**Comment by vuemaster** [comment]
I have the same Issue and have 0.5 Ether on my account, but my wallet takes already 3 days to be created. You said that it needs to be mined? how can I do that?

**Comment by sfmskywalker** [comment]
Same issue here. It's been creating for several hours now.

**Comment by datduong** [comment]
I am having the same problem. Jan 2018. Problem is not fixed yet.

**Comment by evertonfraga** [comment]
Hi @datduong @sfmskywalker,

The expected time is 30s to 5min. The time until the transaction is accepted and included on a block can vary according to the gasPrice paid in the transaction.

But there's a known bug in the Ethereum Wallet 0.9.2, when syncing with the Light Client that prevents the wallet creation. If that's the case, please update to latest (0.9.3).

Either way, there's a chance your wallet was indeed created. Head to https://etherscan.io and search for your account address. See if there were any recently created contracts. Then, copy the created contract and heading back to the wallet use the "Import Wallet" feature.
