### ISSUE TITLE
OSX not syncing

### ISSUE THREAD

**Issue by 1ranger** [ethereum/mist#1487]
#### System information
``````
Version: `0.8.7`
OS & Version: osx 10.12.1
Node type: `eth/geth`
``````
Ethereum Wallet will not sync over a month now. I am stuck on block 2,527,063. I've tried multiple internet connections. removed it, reinstalled the latest version. I've let it sit for hours.  Peers bounce between like 0 and 4.  
![screen shot 2016-12-01 at 17 40 06](https://cloud.githubusercontent.com/assets/23440513/20800192/51694c70-b7ed-11e6-8432-6d33cd6741d4.png)
![screen shot 2016-12-01 at 17 13 33](https://cloud.githubusercontent.com/assets/23440513/20800204/5ac6ca7c-b7ed-11e6-928d-fdb413ed2439.png)

**Comment by luclu** [comment]
@1ranger please try to resync from scratch. This should relieve your syncing-pains. Just follow [this guide](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555).
