### ISSUE TITLE
Wallet tab losing attributes

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/mist#1489]
Wallet tab loses its transparent nav bar, tab name and other attributes after a while.

![image](https://cloud.githubusercontent.com/assets/47108/20807387/d2fc2210-b7e5-11e6-8d1e-c9880a74dd88.png)

Debugged as: `Tabs.find({_id: 'wallet'}).fetch()`

Damaged wallet tab object:
```
{
    id : "wallet"
    badge : "22.46 ETH"
    menu : Object
    permissions : Object
    position : 1
    url : "https://wallet.ethereum.org"
}
```

After hit reload, a healthy wallet tab object:
```
{
    _id: "wallet"
    appBar : "transparent"
    badge : "22.46 ETH"
    icon : "https://wallet.ethereum.org/wallet-icon.png"
    menu : Object
    name : "Ethereum Wallet"
    nameFull : "Ethereum Wallet"
    permissions : Object
    position : 1
    url : "https://wallet.ethereum.org"
    webviewId : 21
}
```

#### System information
``````
Version: `0.8.7`
OS & Version: osx
Node type: `geth`
``````

**Comment by frozeman** [comment]
I guess the issue comes from the way the wallet tab is added. By overwriting the existing one. We definitely need to change that. 

Simply add a `$set: {...}` to the initial wallet adding. 

We can talk about that tomorrow
