### ISSUE TITLE
Reinstalling homebrew, Mist not opening any more.

### ISSUE THREAD

**Issue by taotech4096** [ethereum/mist#149]
Hello, i reinstall homebrew to try to fix issues with the web-three-umbrella, and now that i reinstall, my Mist does not start. 
I deleted all files from home brew, i thought homebrew was just needed to install Mist, but not after.
Any suggestions? can i recover my wallet?

thanks

**Comment by frozeman** [comment]
Any errors?, did you run the binary build version, or from the command line?
please any more info than "not working"

**Comment by taotech4096** [comment]
This is what i see at the console:
Process:               geth [93415]
Path:                  /Applications/Ethereum-Wallet-darwin-x64-0-3-7/Ethereum-Wallet.app/Contents/Resources/node/geth/geth
Identifier:            geth
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        Electron [93396]
Responsible:           geth [93415]
User ID:               502

Date/Time:             2016-02-08 14:09:58.971 +0100
OS Version:            Mac OS X 10.11.3 (15D21)
Report Version:        11
Anonymous UUID:        7E959EEC-31A9-6D1D-AD46-D863543BB01B

Sleep/Wake UUID:       640AC235-8866-4356-88FB-C0720CDA1A93

Time Awake Since Boot: 160000 seconds
Time Since Wake:       160000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /Applications/Ethereum-Wallet-darwin-x64-0-3-7/Ethereum-Wallet.app/Contents/Resources/node/geth/geth
  Reason: image not found

Binary Images:
    0x7fff6489d000 -     0x7fff648d4007  dyld (360.19) <9D05FDF4-65CE-3B53-86D4-ABE1A5BF35F3> /usr/lib/dyld
    0x7fff93f36000 -     0x7fff93f37ffb  libSystem.B.dylib (1226.10.1) <5A4257EF-3145-3BB3-87A4-0D2404A9462D> /usr/lib/libSystem.B.dylib

**Comment by taotech4096** [comment]
I have almost 0 experience with command line, unix code, homebrew. I thought of time machine as a last option, but i would like to understand more about Mist and it´s relation with homebrew and the command line.

**Comment by taotech4096** [comment]
Also important thing to add is that i just updated to El Capitan.

**Comment by frozeman** [comment]
There is none.. at least from the build version. i assume you geth node with comes bundled doesn't start because of some incompatibility. i assume it the crash at start issue, due to the missing `gmp` dependency. Try installing this through homebrew.

**Comment by frozeman** [comment]
Please look for the right issue and close this one then, as i think its a duplicate

**Comment by taotech4096** [comment]
I will try installing through homebrew again.  
Thanks!
