### ISSUE TITLE
Ethereum-Wallet-linux64-0-8-7.zip hacked?

### ISSUE THREAD

**Issue by flenning** [ethereum/mist#1491]
I downloaded Ethereum-Wallet-linux64-0-8-7.zip and compared the checksums. Everything ok but as I send my Ether, Mist changed the address. Same letters as original but some small changed to big letters, at the moment  I pressed send. How did the hacker do that? I am new to Linux Mint Sarah and I have no Idea. Help me please to find the hack on my system. I lost 624 Ether. 
The Ether was send from this address to another where a lot of Ethers arrive, think I am not alone. See the pictures I attached.
![2016-12-03 14 36 21](https://cloud.githubusercontent.com/assets/24357211/20860593/f4ebcd34-b97b-11e6-8900-289a04c54932.jpg)
![2016-12-03 14 44 33](https://cloud.githubusercontent.com/assets/24357211/20860594/f718bf2c-b97b-11e6-8d5a-1db9ca463e64.jpg)
0xc8EdB99b84fe077C582fecAAFA362910Ae4B54Bb the address my money was send to
0x209c4784AB1E8183Cf58cA33cb740efbF3FC18EF the address of the bad guy or girl

**Comment by flenning** [comment]
How is it possible, that the hacker uses the same address just with big letters?

**Comment by flenning** [comment]
ok it took very long but the money arrived at my account, seems to be a software bug

**Comment by luclu** [comment]
@flenning capital and non-capital letters in addresses are handled as the same address. AFAIK capital letters were introduced as as an [error detecting code](https://en.wikipedia.org/wiki/Error_detection_and_correction).

I will close this as it looks like you owned both addresses:
> 0xc8EdB99b84fe077C582fecAAFA362910Ae4B54Bb the address my money was send to
0x209c4784AB1E8183Cf58cA33cb740efbF3FC18EF the address of the bad guy or girl

> ok it took very long but the money arrived at my account, seems to be a software bug
