### ISSUE TITLE
Withdrew my ETH and its not in my wallet where i sent it. ETH is fuckin bs

### ISSUE THREAD

**Issue by sgtshankers** [ethereum/mist#1494]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by 3esmit** [comment]
Can you provide more information?

**Comment by sgtshankers** [comment]
I went to the send in my eth account that had .88 eth in it and copy and pasted my exchange eth deposit address in and it sent it. it came up saying it was sending and I seen confirmations. then it disappeared after awhile like my token I made recently before that. the eth never ended up in my exchange account. idk y. first time I've had a problem sending any coin ever. I had huge problems even getting the eth wallet to sync. kept not downloading and I would have to restart it constantly.  took over a week and me restarting it at least 300 times or more. when it finally was synced. I put 1 eth on there used a bit to make a coin called Flash and it disappeared shortly after being made just like the eth did shortly after sending. I can't see the transaction anywhere in my eth account. it's just gone



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by 3esmit** [comment]
Can you verify you account balance in etherscan.io and verify the account balance where you send the tokens? 
It might be an issue with the exchange were you sent the tokens. 
About the transaction not showing in your account, sometimes it don't show in the UX because it was not saved locally, I am not developer of mist, so I can't tell why it is not showing but happened for me once, anyway, the transaction happened and was shown in etherscan.io (block explorer).

**Comment by sgtshankers** [comment]
Thanks for the offer, I'm not worried about it tho. It was only 1 ETH.  That being said, I would never screw around with ETH again. I've dealt with bitcoin and other alt coins for a few years and never had a problem till now.

________________________________

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
