### ISSUE TITLE
ETH based token is not showing up in my ETH Wallet

### ISSUE THREAD

**Issue by Andi29** [ethereum/mist#1495]
#### System information
``````
Version: `0.8.5
OS & Version: windows 7 64 bit
Node type: `eth wallet
``````
Hello,

my ETH based token (VCAPS) is not showing up in my ETH Wallet.

Is it necessary that my ETH Wallet is complete synchronized?
Do I need to add up some ETH (by BC) to see and control ETH based tokens?
Or is another thing to do?

It would be great if someone can help me out with my issue.

Thank you very much in advance.

Ensclosed are screenshots of my main Ethereum Wallet and my contract section where I have already created the VCAP token under "custom tokens".
![ehterum wallet 1](https://cloud.githubusercontent.com/assets/24397608/20904023/0a1173da-bb3e-11e6-97f2-3f5eff26542c.png)

![ehterum wallet 2](https://cloud.githubusercontent.com/assets/24397608/20903988/eae7fbfa-bb3d-11e6-92bb-010393a7e240.png)

Yours sincerely,

Andreas Zweck

**Comment by luclu** [comment]
Andreas, judging from your empty progress bar in the screenshots, your node does not seem to be fully synced. 

Until your node is fully synced you can use https://etherscan.io to display your current balances and https://myetherwallet.com to interact with it

**Comment by evertonfraga** [comment]
Issue closed due to inactivity. Please reopen if needed.
