### ISSUE TITLE
Bitcoin Lost

### ISSUE THREAD

**Issue by rapadron1** [ethereum/mist#1496]
#### Ethereum Waller for Mac
``````
Version: `0.8.7`
OS & Version:o sx
Node type: 
``````
I dowloaded Ethereum Waller for the first time on my MBP out of curiosity. The installation wizard asked me to transfer some coins (Bitcoins or Ethers) to start the account. I transfered from my MultiBit wallet, the transaction was completed on MultiBit but never got to my Ether Wallet.

**Comment by 3esmit** [comment]
Can you verify your account in this site etherscan.io? It takes some time to sync the blockchain, so your funds might take some time to show in your Ethereum Wallet.

**Comment by frozeman** [comment]
This service is provided by Shapeshift.io, please contact them

**Comment by luclu** [comment]
@rapadron1 Please follow these instructions: https://github.com/ethereum/mist/issues/687

I will close this for now.

**Comment by rapadron1** [comment]
Good afternoon, I am still trying to recoup my 0.0298 BTC that I lost few months ago. I don’t know why my case was close, can you please help me with this? I know is not too much but is the only Bitcoins I have.
