### ISSUE TITLE
Bad Block #2759120

### ISSUE THREAD

**Issue by larrysmith1000** [ethereum/mist#1498]
#### System information
``````
Version: `0.8.7`
OS & Version: windows 10
Node type: `geth(default)`
``````

I am receiving a bad block at #2757943.  The most recent block that successfully downloaded was later (#2759121).  I did a fast sync using geth --fast, and the bad block was imported with the fastsync process.

I also have the following message mixed in occasionally: 

"geth 1.4.18 seems older than the last upstream release 1.5.4"

I assume the error above is the fix, but why does Mist Wallet have an older version of mist in "Ethereum Wallet\binaries\Geth\unpacked"

**Comment by luclu** [comment]
@larrysmith1000 it seems your node (geth) update has some problem.
Please restart Mist/Ethereum Wallet without geth running externally and open the developer console via `CTRL+ALT+i`. Type `web3.admin.nodeInfo.name` and post the output.

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
