### ISSUE TITLE
False notification of received ether

### ISSUE THREAD

**Issue by RCasatta** [ethereum/mist#150]
Some hour ago I installed the Mist ethereum wallet 0.3.9 binaries on Mac OS X
I created a test wallet contract 0xd317e60ff948bf1216eb4e2657401cd4a1f398f3
A while ago I received a notification of 299.99 Ether received on the created wallet contract. I wasn't expecting any payment.
The transaction was 0xd317e60ff948bf1216eb4e2657401cd4a1f398f3 sent by 0x32be343b94f860124dc4fee278fdcbd38c102d88, my contract wasn't the receiver.
The balance never updated to reflect the incoming transaction, after restarting the app the transaction disappeared.

**Comment by 5chdn** [comment]
can confirm this behaviour with my wallet 0.3.9 on linux. it said i got 10 eth in one of my (unused) contract wallets, but checking out the transaction showed me totally different contract addresses. not sure why that happens.

**Comment by frozeman** [comment]
I assume something is wrong with the filters, will investigate. Thanks for reporting

**Comment by luclu** [comment]
What is the current state on this one? I assume it to be solved?
