### ISSUE TITLE
Not able to install Mist-win64-0-8-7 on windows 10

### ISSUE THREAD

**Issue by ranjanmanishr** [ethereum/mist#1504]
#### System information
``````
Version: `0.8.7`
OS & Version: windows 10
Node type: `eth/geth(default)`
``````
![error2](https://cloud.githubusercontent.com/assets/11875047/21081591/478fe08a-bf98-11e6-8e13-0142c2e38d50.PNG)
![error1](https://cloud.githubusercontent.com/assets/11875047/21081592/49943336-bf98-11e6-91bc-23319c2d3881.PNG)

[Mist.zip](https://github.com/ethereum/mist/files/644595/Mist.zip)

**Comment by luclu** [comment]
@ranjanmanishr what is the current status of this issue? Were you able to resolve it?

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
