### ISSUE TITLE
Can not connect to ethereum node

### ISSUE THREAD

**Issue by herzoga** [ethereum/mist#1505]
![image](https://cloud.githubusercontent.com/assets/9218956/21096215/465eb85e-c05f-11e6-9e96-189ac9db2a6e.png)

#### System information
``````
Version: `0.8.7`
OS & Version: windows 10 
``````

**Comment by ranjanmanishr** [comment]
i am getting the exact same error. Lets wait for some expert to rescue us. I have tried installing other versions, all of them ended with same error.

**Comment by vngn** [comment]
I s there any update on this ? I have exactly the same thing. I have tried installing - reinstalling, nothing works. 
![error](https://cloud.githubusercontent.com/assets/21106794/21620824/d866058a-d1fe-11e6-9516-9735eea863f6.jpg)

**Comment by ranjanmanishr** [comment]
I could not get it working on windows 10.  Then i tried on Ubuntu and windows 7, it worked on both of them.

**Comment by vngn** [comment]
@ranjanmanishr thanks will try later today.

**Comment by frozeman** [comment]
Can you start via cmd.exe and see the console output?

**Comment by vngn** [comment]
@frozeman thanks for your attempt to assist. First things first, I am not a developer and it takes some time for me to understand how to deal with Ethereum wallet.  Sometimes it was not synchronizing, so I updated databaese  --geth removedb, and previous wallet updates were smooth. 

So, I tried to launch the wallet and received messages as per screenshot above. After your comment I launched wallet via cmd , the wallet though 0.8.7 and I have received the following result:

- it looks like it started to download the blocks, but it still asking me to download wallet 0.8.8.
- before I would simply click install and that's it. 
![launch](https://cloud.githubusercontent.com/assets/21106794/21639566/702b9676-d279-11e6-97a7-e4fe6d561126.jpg)

**Comment by frozeman** [comment]
Ok so looks like its downloading blocks. looks fine to me.
If it tells you a new version is available, the download the new one from https://github.com/ethereum/mist/releases
Seems like you run an older version

**Comment by vngn** [comment]
Strange though that it started to download from the scratch... previously I left off on 2.2 mil blocks.. Shall I wait until all blocks downloaded and then to update?

**Comment by frozeman** [comment]
Best is to download the new wallet version, rename the chain data folder ans sync from scratch.
The chain data folder is in `%APPDATA%\Ethereum\chaindata`
Best rename it to: `%APPDATA%\Ethereum\chaindata_old`

**Comment by vngn** [comment]
@frozeman actually, I tried to launch the wallet from Ethereum-Wallet-win64-0-8-8 now and everything works as before. The trick launching it through cmd seems to resolve the issue.

Appreciate your help!

**Comment by LoseTheQuit** [comment]
At the top of the in Ethereum Wallet - in the menu bar there is the "Develop".  Will the options within Ethereum Node and Network (Geth 1.6.6 & Main Network/ Testnet ) become available when I finish downloading the blockchain. I can't use those options and I'm stuck with only 173 blocks left and those options are yet available.
