### ISSUE TITLE
stuck coins. 

### ISSUE THREAD

**Issue by casay** [ethereum/mist#1507]
#### System information
``````
Version: `0.5.1`
OSX 10.12.1
Node type: `geth`
``````

- Screenshots
<img width="417" alt="screen shot 2016-12-12 at 12 13 56 pm" src="https://cloud.githubusercontent.com/assets/24528853/21108897/c64816e6-c064-11e6-8f06-93435bfc36ab.png">

I can't move my coins from the wallet. any help would be greatly appreciated, thanks.

**Comment by frozeman** [comment]
Looks like your geth crashed. Please restart and try again. Should the same issue appear please copy the log files from ~/Library/Application Support/Mist into a gist.github.com

Kind regards,
Fabian Vogelsteller

**Comment by casay** [comment]
this is what i got from the logs. the problem is still persisting. not sure if this is exactly what your looking for. if theres anyother info i can provide to make it easier let me know. 
thanks 
I1213 13:36:19.866867    3482 database.go:71] Alloted 433MB cache to /Users/casayyamazaki/Library/Ethereum/chaindata
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x41627648c242 pc=0x4054d1e]

runtime stack:
runtime.throw(0x4b9f8e0, 0x2a)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.(*gcWork).tryGet(0xc82001c720, 0x81f1f68)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/mgcwork.go:114 +0x5e
runtime.gcDrainN(0xc82001c720, 0x6115)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/mgcmark.go:775 +0x6b
runtime.gcAssistAlloc.func1()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/mgcmark.go:232 +0x172
runtime.systemstack(0xc82001ca00)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:216 fp=0xc8201ba710 sp=0xc8201ba708
runtime.gcAssistAlloc(0x30, 0xc8204ba001)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/mgcmark.go:272 +0x1f8 fp=0xc8201ba770 sp=0xc8201ba710
runtime.mallocgc(0x30, 0x47e3ec0, 0xc800000001, 0xc8201ba8f0)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/malloc.go:711 +0x535 fp=0xc8201ba840 sp=0xc8201ba770
runtime.newarray(0x47e3ec0, 0x28, 0xc8201bae98)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/malloc.go:777 +0xc9 fp=0xc8201ba880 sp=0xc8201ba840
runtime.makeslice(0x47c6660, 0x28, 0x28, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/slice.go:32 +0x165 fp=0xc8201ba8d0 sp=0xc8201ba880
github.com/syndtr/goleveldb/leveldb.(*sessionRecord).readBytes(0xc8201bae98, 0x4a98af0, 0xe, 0x81f0a80, 0xc8200a30c0, 0x0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/session_record.go:222 +0x11c fp=0xc8201ba948 sp=0xc8201ba8d0
github.com/syndtr/goleveldb/leveldb.(*sessionRecord).decode(0xc8201bae98, 0x81f0a58, 0xc8200a30c0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/session_record.go:299 +0xcc9 fp=0xc8201bac50 sp=0xc8201ba948
github.com/syndtr/goleveldb/leveldb.(*session).recover(0xc82026a160, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/session.go:146 +0xc85 fp=0xc8201baf48 sp=0xc8201bac50
github.com/syndtr/goleveldb/leveldb.Open(0x81f0530, 0xc8200a0540, 0xc8201bb0b8, 0x0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:163 +0xd5 fp=0xc8201baf98 sp=0xc8201baf48
github.com/syndtr/goleveldb/leveldb.OpenFile(0xc8202470e0, 0x2f, 0xc8201bb0b8, 0x0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/db.go:199 +0x97 fp=0xc8201baff0 sp=0xc8201baf98
github.com/ethereum/go-ethereum/ethdb.NewLDBDatabase(0xc8202470e0, 0x2f, 0x1b1, 0x4107b71, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/ethdb/database.go:78 +0x2f6 fp=0xc8201bb1f0 sp=0xc8201baff0
github.com/ethereum/go-ethereum/eth.New.func1(0xc8202470e0, 0x2f, 0x0, 0x0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/eth/backend.go:281 +0x54 fp=0xc8201bb240 sp=0xc8201bb1f0
github.com/ethereum/go-ethereum/eth.New(0xc820096900, 0xc8200a3000, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/eth/backend.go:285 +0x1f5 fp=0xc8201bb758 sp=0xc8201bb240
main.run(0xc820258240)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:411 +0xea fp=0xc8201bb800 sp=0xc8201bb758
github.com/codegangsta/cli.(*App).Run(0xc820258120, 0xc82000a240, 0x4, 0x4, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:180 +0x1028 fp=0xc8201bbe88 sp=0xc8201bb800
main.main()
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:373 +0x93 fp=0xc8201bbf30 sp=0xc8201bbe88
runtime.main()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc.go:111 +0x2b0 fp=0xc8201bbf80 sp=0xc8201bbf30
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8201bbf88 sp=0xc8201bbf80

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
github.com/ethereum/go-ethereum/logger/glog.(*loggingT).flushDaemon(0x50fcdc0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:897 +0x67
created by github.com/ethereum/go-ethereum/logger/glog.init.1
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/logger/glog/glog.go:428 +0x6f

goroutine 34 [select]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/logger/sys.go:81 +0x624
created by github.com/ethereum/go-ethereum/logger.init.1
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/logger/sys.go:60 +0x2b

goroutine 7 [chan receive]:
github.com/ethereum/go-ethereum/p2p/nat.discoverUPnP(0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:129 +0x112
github.com/ethereum/go-ethereum/p2p/nat.Any.func1.1(0xc8200181e0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:155 +0x18
created by github.com/ethereum/go-ethereum/p2p/nat.Any.func1
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:155 +0x63

goroutine 36 [chan receive]:
github.com/ethereum/go-ethereum/logger.sysLoop(0x81f04b8, 0xc820292280, 0xc8200c5b00, 0xc8200da000)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/logger/sys.go:117 +0x51
created by github.com/ethereum/go-ethereum/logger.dispatchLoop.func1
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/logger/sys.go:77 +0xdb

goroutine 20 [chan receive]:
github.com/ethereum/go-ethereum/p2p/nat.Any.func1(0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:158 +0xcf
github.com/ethereum/go-ethereum/p2p/nat.(*autodisc).wait.func1()
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:242 +0x47
sync.(*Once).Do(0xc8202849d0, 0xc820026f78)
	/usr/local/Cellar/go/1.5.1/libexec/src/sync/once.go:44 +0xe4
github.com/ethereum/go-ethereum/p2p/nat.(*autodisc).wait(0xc8202849c0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:244 +0x65
created by github.com/ethereum/go-ethereum/p2p/nat.startautodisc
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/p2p/nat/nat.go:203 +0xb1

goroutine 50 [IO wait]:
net.runtime_pollWait(0x5ea51f8, 0x72, 0xc820010130)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202d0060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202d0060, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).readFrom(0xc8202d0000, 0xc820306000, 0x800, 0x800, 0x0, 0x0, 0x0, 0x5ea0050, 0xc820010130)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_unix.go:259 +0x2a5
net.(*UDPConn).ReadFromUDP(0xc8202d6000, 0xc820306000, 0x800, 0x800, 0x3, 0x4, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/udpsock_posix.go:61 +0x117
net.(*UDPConn).ReadFrom(0xc8202d6000, 0xc820306000, 0x800, 0x800, 0x3, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/udpsock_posix.go:79 +0x116
github.com/huin/goupnp/httpu.(*HTTPUClient).Do(0xc8202d8000, 0xc8202e0000, 0x7d2b7500, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/httpu/httpu.go:92 +0xbc3
github.com/huin/goupnp/ssdp.SSDPRawSearch(0xc8202d8000, 0x4bb0220, 0x31, 0x2, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/ssdp/ssdp.go:53 +0x66c
github.com/huin/goupnp.DiscoverDevices(0x4bb0220, 0x31, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/goupnp.go:66 +0x114
github.com/ethereum/go-ethereum/p2p/nat.discover(0xc8202bc000, 0x4bb0220, 0x31, 0x4ca9050)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:140 +0x3d
created by github.com/ethereum/go-ethereum/p2p/nat.discoverUPnP
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:115 +0x84

goroutine 51 [IO wait]:
net.runtime_pollWait(0x5ea5138, 0x72, 0xc820010130)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202d4060, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202d4060, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).readFrom(0xc8202d4000, 0xc820308000, 0x800, 0x800, 0x0, 0x0, 0x0, 0x5ea0050, 0xc820010130)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_unix.go:259 +0x2a5
net.(*UDPConn).ReadFromUDP(0xc8202da000, 0xc820308000, 0x800, 0x800, 0x47e3ec0, 0x800, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/udpsock_posix.go:61 +0x117
net.(*UDPConn).ReadFrom(0xc8202da000, 0xc820308000, 0x800, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/udpsock_posix.go:79 +0x116
github.com/huin/goupnp/httpu.(*HTTPUClient).Do(0xc8202de000, 0xc8202e6000, 0x7d2b7500, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/httpu/httpu.go:92 +0xbc3
github.com/huin/goupnp/ssdp.SSDPRawSearch(0xc8202de000, 0x4bb0260, 0x31, 0x2, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/ssdp/ssdp.go:53 +0x66c
github.com/huin/goupnp.DiscoverDevices(0x4bb0260, 0x31, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/huin/goupnp/goupnp.go:66 +0x114
github.com/ethereum/go-ethereum/p2p/nat.discover(0xc8202bc000, 0x4bb0260, 0x31, 0x4ca9058)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:140 +0x3d
created by github.com/ethereum/go-ethereum/p2p/nat.discoverUPnP
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/p2p/nat/natupnp.go:127 +0xc7

goroutine 21 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc8202760e0)
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x271
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/Users/frozeman/Developer/go/src/github.com/ethereum/go-ethereum/Godeps/_workspace/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x26b

**Comment by luclu** [comment]
I will close this for now.
