### ISSUE TITLE
mist.requestAccount does not execute the callback

### ISSUE THREAD

**Issue by miderose** [ethereum/mist#1511]
#### System information
``````
Version: `0.8.7`
OS & Version: Windows 7 Enterprise - SP1
Node type: `geth v1.5.4`
``````

It seems the mist.requestAccount does not execute the callback...

this function:
```javascript
    mist.requestAccount(
        function (e, account) {
            console.log("done");
            console.log(e, account);
        }
    );
```
shows the accounts modal, but never execute the callback after I choose or create an account...

**Comment by frozeman** [comment]
That will be fixed in the next release 0.8.8. Thanks for pointing out.
