### ISSUE TITLE
Upgrade alert notice for the average end user?

### ISSUE THREAD

**Issue by taoteh1221** [ethereum/mist#152]
Not sure if you all have had time yet to think about or already have implemented this: Some type of minimally centralized / least intrusive way to get upgrade alerts out to Mist, so those users who don't care to keep track of upgrades stay informed of them? I can foresee this potentially becoming a big issue if mass adoption takes place, and critical upgrade patches are released. Your normal everyday internet user may _never upgrade_ unless they get an alert that it's highly recommended for there own safety. 

One idea might be a 'check for updates' link, which would be most minimally intrusive...or have Mist automatically perform a request upon startup to a URL via JSON or something similar.

**Comment by frozeman** [comment]
@alexvandesande we could create a contract for that.

**Comment by hiddentao** [comment]
As a temporary measure, it could check the Github releases page for a newer version.

**Comment by karalabe** [comment]
Having release the Geth Release Oracle, you might want to look into using that too:

 * Source: https://github.com/ethereum/go-ethereum/blob/develop/release/contract.sol
 * Live: http://etherscan.io/address/0xFA7B9770Ca4cb04296Cac84F37736d4041251CDF#code

**Comment by luclu** [comment]
Maybe some basic firewall check as proposed in https://github.com/ethereum/mist/issues/165 could be added while tackeling this?

**Comment by hiddentao** [comment]
PR #707 implements an upgrade alert notice.

**Comment by taoteh1221** [comment]
Cool.
