### ISSUE TITLE
Wrong Password Error while restoring with UTC- file  and password

### ISSUE THREAD

**Issue by bitcoinsSG** [ethereum/mist#1521]
#### System information
``````
Version: `0.0.0`
OS & Version: linux
Node type: `eth/geth(default)`
Geth
Version: 1.5.5-stable
Git Commit: ff07d54843ea7ed9997c420d216b4c007f9c80c3
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=[censored]
GOROOT=/usr/lib/go-1.7

``````

This is a separate issue as I have looked at a few other wrong password issues:

Trying to restore a friends ethereum wallet,
1) I have the UTC--2016-03-10T11-11-* file and the password used during initial setup in MIST. I have tried restoring it by copying it to the ~/.ethereum/keystore dir and executing a send command with the password. The error message I get is "wrong password"
2) I have also tried geth account update (see geth version) this is the output
Fatal: Failed to unlock account [pkh]  (could not decrypt key with given passphrase)
3) I have also tried https://www.myetherwallet.com/ (offline mode)
similar error message
I still get wrong password. 

The wallet was created in MIST in 2016-03-10, what am I doing wrong? Was he supposed to save something other than the UTC file and password?

**Comment by seesix** [comment]
Did you resolve this, I have a similar issue?

**Comment by bitcoinsSG** [comment]
no

**Comment by evertonfraga** [comment]
See related issues.
https://github.com/ethereum/mist/issues/396
https://github.com/ethereum/mist/issues/982
https://github.com/ethereum/mist/issues/2910

**Comment by rriot** [comment]
I have the same issue. My passphrase unlocks every address in my wallet except for the one labeled "Etherbase". I have tried to unlock using Mist, geth command line, and myetherwallet.com
