### ISSUE TITLE
Checksum incorrect

### ISSUE THREAD

**Issue by lienertch** [ethereum/mist#1527]
#### System information
``````
Version: `0.8.8`
OS & Version: linux ubuntu 16.04 LTS
``````
After downloading Ethereum-Wallet-linux64-0-8-8.zip and control the checksum (md5sum), I've got a complete different checksum. Make the same with Ethereum-Wallet-linux64-0-8-8.deb with the same wrong result. Here the terminal copy:

pc@pc:~/Schreibtisch$ md5sum Ethereum-Wallet-linux64-0-8-8.zip
6eb519781121f5e70f7ceea90cf3af83  Ethereum-Wallet-linux64-0-8-8.zip
pc@pc:~/Schreibtisch$ md5sum Ethereum-Wallet-linux64-0-8-8.deb
2b532628777aca514c337b9752416bde  Ethereum-Wallet-linux64-0-8-8.deb
pc@pc:~/Schreibtisch$

The sum must have:
Ethereum-Wallet-linux64-0-8-8.deb
386abbd14ed1ef28cb1c7d8c6589fa39e3b5b02b563c1e5f720f592206a56d52
Ethereum-Wallet-linux64-0-8-8.zip
9a67c9a84202186907eb0d2c7c648937848195295f99a8804c308233cd86310a

Any idea? Thanks for any answers.

**Comment by luclu** [comment]
Try to create sha256 checksums locally - they should match the currently advertised ones.

**Comment by lienertch** [comment]
Dear luclu. Perfect answer! I install GtkHash and have got the correct sha256 sum (and md5, sha1). Many thanks for your time and help.

**Comment by luclu** [comment]
Great! Thank You for your open eyes and helping hand! 👍

**Comment by evertonfraga** [comment]
I suspect that if the connection drops while downloading geth, the
connection wouldn't get restored, and the checksum would fail.
