### ISSUE TITLE
How do I transfer old account to wallet?

### ISSUE THREAD

**Issue by qauntumspirit** [ethereum/mist#1528]
I have recently had to reinstall everything on my computer. How do I transfer my old Ethereum wallet address to my Ethereum wallet?

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
@qauntumspirit you can simple import the account keyfiles via `menu -> accounts -> import accounts`.

**Comment by qauntumspirit** [comment]
On the 'accounts' menu there is only an option for pre-sale accounts. 

    On Tuesday, 14 March 2017, 18:14, Luca Zeug <notifications@github.com> wrote:
 

 @qauntumspirit you can simple import the account keyfiles via menu -> accounts -> import accounts.—
