### ISSUE TITLE
Password no longer working after new install

### ISSUE THREAD

**Issue by indepth2** [ethereum/mist#1535]
Complete newb here. Mist wouldn't open without the update, so I installed 0.8.8.

Mist opens, connects and views the wallets fine now.

But when trying to send Eth, I'm getting a wrong password error.  I'm very diligent with my passwords and I know I'm not typing it incorrectly.  Is there a file from the old installation I need to copy over?  Something else I'm missing?  Is there a way to reset the password hash?

#### System information
``````
Version: `0.8.8`
OS & Version: windows 64bit
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by frozeman** [comment]
You can simply download a older version and see if you can send with that one. But from my experience it's 100% always the user mistyping or wrong keyboard settings or wrong password. 

But please try an older version. They are all on the GitHub release page.
