### ISSUE TITLE
Not synchronized version 0.8.8 wallet / Version 0.8.7 wallet error

### ISSUE THREAD

**Issue by VyacheslavTr** [ethereum/mist#1544]
#### System information
``````
Version: `0.8.8`
OS & Version: windows 7 x64
Node type: `eth/geth(default)`
``````
Not synchronized version 0.8.8 wallet, immediately starts the application.
Version 0.8.7 wallet when you run an error (...flag provided but not defined: -support-dao-fork)

![1](https://cloud.githubusercontent.com/assets/24712635/21419423/941cd932-c838-11e6-9c24-ac90b626a057.JPG)
![2](https://cloud.githubusercontent.com/assets/24712635/21419427/974a7646-c838-11e6-85dd-6f4920bbdf88.JPG)
![3](https://cloud.githubusercontent.com/assets/24712635/21419433/9b83d284-c838-11e6-849a-00942834a5d0.JPG)

**Comment by tinodesigns** [comment]
same issue here how did this get resolved?
When I open EtherumWallet 0.8.8 the blocks are gone (it needs to fully resync and wallets are not showing up)
