### ISSUE TITLE
0.8.8 sync speed issue

### ISSUE THREAD

**Issue by lowlanda** [ethereum/mist#1548]
#### System information
``````
Version: `0.0.0`
OS & Version: windows 7
Node type: `geth(default)`
``````

Been syncing for 2 days, only 26%

Am I doing it wrong?

**Comment by luclu** [comment]
Please try to do a complete resync. You can follow this guide to do so: [ethereum stackexchange](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555).

Note: HDDs have been found to be very slow during the initial sync. To improve performance consider using a SSD or switch to http://myetherwallet.com or http://ledgerwallet.com until light client functionality is ready in Mist/Ethereum Wallet.

**Comment by lowlanda** [comment]
Ok thanks luclu, I've deleted the chaindata folder and restarted MIST, hopefully in fast sync mode

2,237,331 blocks to go :)

**Comment by lowlanda** [comment]
Update:

Fully sync'd and I can seee my full balance within a couple hours of taking luclu's advise

Cheers
