### ISSUE TITLE
Mist not using latest solidity compiler version 0.4.7

### ISSUE THREAD

**Issue by coderwithattitude** [ethereum/mist#1549]
i am unable to compile solidity code with compiler version 0.4.7 it only supports 0.4.6 and i want to use the latest version.

**Comment by evertonfraga** [comment]
Yes, sorry about that. The Solidity 0.4.7 was released right after we had Mist 0.8.8 built.

**Comment by evertonfraga** [comment]
Updated to 0.4.8. Will be online very soon, along with Mist 0.8.9
