### ISSUE TITLE
WALLET DOES NOT DOWNLOAD BLOCKS

### ISSUE THREAD

**Issue by HuguesDohmen** [ethereum/mist#1550]
#### System information
``````
Version: `0.8.8`
OS & Version: windows 10
Node type: `geth 1.5.5(go
[NodeLogfiles.zip](https://github.com/ethereum/mist/files/673345/NodeLogfiles.zip)
)`
``````
I see 10 to 12 nodes connected but it says also 1,062,590 blocks left and this does not change.
These number of blocks is correct because I already downloaded more than 2,000,000 blocks via command line.

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by baobabKoodaa** [comment]
I also have the same issue on Windows 10, stuck at 558,174 blocks left and doesn't change even when connected to 10 peers.

**Comment by starfannnn** [comment]
I also have the same issue on windows 10. The app starts downloading a few blocks (a few hundred), then stops at a certain amount of blocks left. It shows that it is connected to 12 peers.

**Comment by luclu** [comment]
I will close this issue as it might be outdated.
Please update to the latest version as check if this fixes your issue.

**Comment by seanmacentee** [comment]
Came across something similar just now on windows 10. 

Looks like it was some sort of issue with virtualbox, which I had running in the background. Shutting down virtualbox did the trick and blocks are now downloading. If anyone is facing the same issue and running virtualbox, try shutting down virtualbox.
