### ISSUE TITLE
Transaction stuck at Zero confirmations in wallet - chain is synced

### ISSUE THREAD

**Issue by joekercom** [ethereum/mist#1551]
#### System information
``````
Version: `0.8.8`
OS & Version: osx Sierra
Node type: `geth go 1.5.5`
``````

For some reason the latest transaction sent to me from my mining pool is stuck at zero confirmations.  It's over 13 hours old on the blockchain with thousands of confirmations, but stuck at 0 in my wallet.  https://etherscan.io/tx/0xbb100f0467eab821ed540ae70b701b153c710499b6b3163e83d8e2b38670d456

I am synced with the chain.  
![image](https://cloud.githubusercontent.com/assets/24796352/21504786/6f475d6a-cc27-11e6-91e4-d94d20407ec4.png)

The transaction is showing as: 
![image](https://cloud.githubusercontent.com/assets/24796352/21504798/862f567c-cc27-11e6-9458-17a91bf1f201.png)

Sorry, I'm sure I'm missing something simple.

**Comment by joekercom** [comment]
Now 2nd transaction stuck in my wallet.

**Comment by chriswanaka** [comment]
Did you sort it in the end? I'm having the same problem

**Comment by joekercom** [comment]
No I have no idea how to fix this, and now have third transaction stuck in my wallet.  I've pretty much given up on this wallet and am storing my ETH at Coinbase.
