### ISSUE TITLE
I have created a Ethereum wallet, but cannot have not recieved the coins to the address in the wallet. Please advice

### ISSUE THREAD

**Issue by lwinther8899** [ethereum/mist#1556]
I am totally new to cryptocurrency and need help. I have via Bitpanda bought some Ethereum coin. I have created a Ethereum wallet, but cannot have not recieved the coins to the address in the wallet. Via Etherscan I can see the transaction is done. Can anybody advice what Im doing wrong or need to do? Please advice

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by akltcode** [comment]
Did you use test-net account ? or Main net account?
I used test-net account and got the same situation w/ you. 
It see that I lost an ETH from my friend.

Is there anyone meet the same issue ?

**Comment by Yorick111** [comment]
I have the same problem. I bought Ether with anycoin and etherscan confirmedthe payment. but I haven't received anything on my account.

**Comment by akltcode** [comment]
@Yorick111, 
as my experience in first time using Mist, Pls use cmd line 
$geth --fast   #it take about 3-4hour depend on your computer.
then launch Mist after its finish to update transaction.

**Comment by lwinther8899** [comment]
Hi @Yorick111, pls advice; how do I do that  (Pls use cmd line
$geth --fast #it) - I am not a technical guy. And I use Mac!

**Comment by akltcode** [comment]
@lwinther8899 
Pls refer : 
https://github.com/ethereum/go-ethereum/wiki/
https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Mac

**Comment by lwinther8899** [comment]
Thanks. Now its updating. Lets see if it finishes

**Comment by lwinther8899** [comment]
Follow the directions above from akltcode. It has gotten me some of the way. However now I run into other errors - not yet there. Its two steps forward and one step back.

**Comment by AmesEla** [comment]
I had this problem. You need to allow the wallet to update with the current ledger. It is in fast mode when you first install, and if your computer goes to sleep or you turn it off, the wallet updates in slow mode. If you haven't done much I would back up, delete the wallet and reinstall then let all the ledgers update. 

This made me crazy for days, until I had the patience to allow it to update the ledgers and learned about the fast mode and slow mode. You can also search fast on this forum and glean some insights.

good luck!

**Comment by Zumminer** [comment]
You should use online [wallet](https://zumminer.com/), i dont have a problem.
