### ISSUE TITLE
Account missing after upgrading

### ISSUE THREAD

**Issue by conixit** [ethereum/mist#1557]
I am relatively new to mining- and after upgrading my Ethereum Wallet to 0-8-8 my account that I had mined about 36 ETH in (https://ethermine.org/miners/235684b554500a3192561dE58769F8B85cB3F04E) has disappeared from my C:\Users\MYUSER\AppData\Roaming\Ethereum\keystore folder- the only thing in there now is a "new" account I created today in the new 0.8.8 program.  I tried to unlock the account using the command geth --unlock "0x235684b554500a3192561dE58769F8B85cB3F04E" --password "C:pass.txt" and I get the error (no key for given address or file) - which of course is right- the keystore for that account is missing in   C:\Users\MYUSER\AppData\Roaming\Ethereum\keystore.  There has to be a way to retrieve these ETH.

**Comment by JeezNuts** [comment]
I presume you didn't do a backup of the keystone.  I am not sure why the keystore would be wiped out if an upgrade was done.

**Comment by evertonfraga** [comment]
An update wouldn't cause that. But I can't walk about other software you might have had running.
