### ISSUE TITLE
Watch Token addresses disappear

### ISSUE THREAD

**Issue by housemobile** [ethereum/mist#1558]
I'm running 0.8.8 on Windows 7.

I previously ran 0.8.7 and updated to this. All my watch token addresses are gone. I re-added them all and it worked fine.

Then I closed the client. When I re-opened I see the watch token addresses are all gone again.

This is frustrating. Where are they saved? 

I think I will reinstall 0.8.8 clean and redownload the chaindata.

**Comment by evertonfraga** [comment]
This was fixed in the subsequent version.
