### ISSUE TITLE
Add command-line parameters like --help, --version

### ISSUE THREAD

**Issue by gcarq** [ethereum/mist#156]
Would be nice if we can add common CLI parameters like --help and --version.

**Comment by 5chdn** [comment]
i second that, would be a good idea to be able to pass command line arguments to the underlying ethereum node, too.

but that's a design decision that should be carefully discussed. i can not assess the impact on security for instance.

**Comment by frozeman** [comment]
How you start mist using the command line?

**Comment by gcarq** [comment]
`$ /usr/bin/mist`

which is symlinked against:
`-rwxr-xr-x 1 root root 61887528 Feb  9 16:42 /usr/share/mist/Ethereum-Wallet`

**Comment by frozeman** [comment]
This package is not maintained by me. As this has to be cross OS compatible i have to look if its possible. 
Ill keep this as a reminder.

**Comment by frozeman** [comment]
BTW the node is in `/usr/share/mist/Ethereum-Wallet/resoucres/node/geth/`, where you can simply start it before with your own options and then start the wallet, it will then use the running node.

**Comment by hiddentao** [comment]
PR in #393

**Comment by 5chdn** [comment]
I like the existing flags as merged in https://github.com/ethereum/mist/pull/443 already. But I have some more on my wishlist.

    --ipcpath     # which ipc path to connect to (e.g., if you connect to
                  # a client with non standard parameters, ...)
    --datadir     # allow storing the blockchain in different locations
                  # (pass this to the client)
    --testnet     # run mist on testnet

ref. http://ethereum.stackexchange.com/q/3518/87

**Comment by 5chdn** [comment]
Or to add another thought, (and to simplify the approach), why not simply passing any flag from mist to geth/eth. For instance, if you run `mist --dev` it will run a client in dev mode. Just an idea.

**Comment by gcarq** [comment]
@5chdn I like that idea. `mist --dev` could also be `mist --` to signify the end of *mist* options like bash does, and all following arguments are passed to the underlying node.

**Comment by hiddentao** [comment]
PR in #689

**Comment by luclu** [comment]
This will be available in version 0.7.5.
