### ISSUE TITLE
Unable to launch Ethereum Wallet and Mist 0.8.8 on Debian stable

### ISSUE THREAD

**Issue by pelmato** [ethereum/mist#1562]
### Description
I'm not able to launch Ethereum Wallet and Mist in version 0.8.8. I never had problem with previous version. Checksum of downloaded .deb are correct.

`$ sudo dpkg -i Ethereum-Wallet-linux64-0-8-7.deb`
`$ Ethereum\ Wallet`
Works fine !

But:
`$ sudo dpkg -i Ethereum-Wallet-linux64-0-8-8.deb`
No error during installation.

`$ Ethereum\ Wallet`
`zsh: command not found: Ethereum Wallet`
`zsh: exit 127   Ethereum\ Wallet`

`$ ethereumwallet`
`zsh: command not found: ethereumwallet`

#### System information
Operating System: Debian GNU/Linux 8 (jessie)
Kernel: Linux 3.16.0-4-amd64
Architecture: x86-64

**Comment by pelmato** [comment]
Version 0.8.9 solved the problem for me. Thanks!

**Comment by evertonfraga** [comment]
Glad to hear that!
