### ISSUE TITLE
Ethereum Wallet .exe hanging in background

### ISSUE THREAD

**Issue by lowlanda** [ethereum/mist#1565]
#### System information
``````
Version: `0.8.8`
OS & Version: windows 7
Node type: `geth(default)`
``````

Ethereum Wallet does not close properly, and I find multiple .exe instances in task manager when it runs normally (4 instances).

I notice this when trying to use wallet, as none of the interface buttons work (menus work). When this happens, I have to bring up task manager and kill any .exe instances that are hanging, then relaunch.

Cheers

**Comment by lowlanda** [comment]
Out of interest, how many instances of Ethereum Wallet do other people have running in task manager?

**Comment by evertonfraga** [comment]
No problem with multiple instances. It's like google chrome, that has one parent process and many other child ones.
