### ISSUE TITLE
Ethereum wallet - Test net

### ISSUE THREAD

**Issue by morenovel** [ethereum/mist#1566]
Hello

I downloaded the Ethereum wallet but it is always in the Test-net version and I'm not able to go in the real wallet. How can I exit from the test version?

Version: `0.8.8`
osx 10.12.2
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by sathishvj** [comment]
Does the menu item not work Develop->Network->Testnet?

If not, you could probably check my responses here: #2375

**Comment by charly37** [comment]
Could it be the same issue than: 
https://github.com/ethereum/mist/issues/2392
Do you have the same error than the screen capture in the other ticket ?

**Comment by evertonfraga** [comment]
Try this: https://github.com/ethereum/mist/issues/2392#issuecomment-317854364
