### ISSUE TITLE
Edge-case offline-startup error

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#1569]
Currently Mist will error-out on the splash screen if (i) no internet connection is available and (ii) the downloaded version of geth differs from the one advertised in the bundled clientBinaries.json.

From https://github.com/ethereum/mist/pull/1534:
>There seems to be a case where this fix does not suffice.
>
>If the default config - shipped with ethereum-client-binaries - differs from the current version (e.g. of geth), I think it will try to download the older version (see clientBinaryManager.js#L181-L184). Also we can't keep the default config up-to-date on shipped installations.

#### Proposals

1. Disable version check of already downloaded node if clientBinaries.json can't be received from github
2. Store version of currently downloaded version in local DB

I would prefer (1).

**Comment by evertonfraga** [comment]
afaik, Mist also saves the clientBinaries.json on `Library/Mist`. You could
use that version to check against the geth version
