### ISSUE TITLE
Updating Ethereum Wallet - Need Better UX

### ISSUE THREAD

**Issue by SmarticusRex** [ethereum/mist#1577]
Hey There,

Just wanted to post that I think the user experience of updating Ethereum Wallet could be improved. 

What I dont like:

When launching my wallet, it doesn't load and instead says "There is a newer version" or something similar. I then go to a webpage, download the new version, open a zip that extracts by default to my Downloads folder. There are no instructions. Do I replace my old files with these files? Do I erase my old files? What do I do with these files? I cant even open the readme file. Also, when I run the updated wallet, all the tokens I was watching are erased and I have to look up all the ICO addresses to add them to my watch list again. It's a pain. For mainstream adoption, it needs to be idiot proof for idiots like me. 

What would be better:

Load the wallet like normal. Once in wallet, get a pop up that says "a newer version is available" with a button that says "update now". It senses my current version, and downloads the newest applicable version for my OS. It installs the new version, rewriting the applicable files that need to be replaced automatically. My settings and watch lists are kept intact. 

That's it. Thanks!

**Comment by willnwhite** [comment]
I agree. I replaced my old version with the new one because [they told me to on Gitter](https://gitter.im/ethereum/welcome?at=589c7b3b872fc8ce621326ae), and now I'm having to download blocks and set passwords like the whole thing has been reset and I've lost any accounts I had.

**Comment by alexvandesande** [comment]
Thanks for the comments. We indeed believe the upgrade process could be better, but tokens and contracts should not disappear on the latest versions
