### ISSUE TITLE
Re: sending eth but keep receiving error   currently using Etheruem Wall 8.8

### ISSUE THREAD

**Issue by knowingit** [ethereum/mist#1581]
#### System information
``````
Version: `0.8.8` Latest i belive
OS & Version: windows 7
Node type: `eth/geth(default)`
``````

i keep getting "Exceeds Block gas limit"  how do i correct this problem . can you show me step by step how to solve this problem?

**Comment by evertonfraga** [comment]
Solved: https://github.com/ethereum/mist/issues/1660

Related:
https://ethereum.stackexchange.com/questions/1832/cant-send-transaction-exceeds-block-gas-limit-or-intrinsic-gas-too-low
