### ISSUE TITLE
Ethereum Wallet v0.8.8 incompatable with geth client 1.5.6

### ISSUE THREAD

**Issue by ethminer1** [ethereum/mist#1582]
#### System information
``````
Version: `0.88`
OS & Version: windows10
Node type: `geth v1.5.6`
``````

When using this node client ver with ethereum wallet, the wallet is unable to estimate gas costs and warns on every transaction:

![vdice1](https://cloud.githubusercontent.com/assets/25091038/21912752/adce0568-d8dc-11e6-97a3-f8040c6180d2.png)

If you try to send the transaction anyhow, when confirming the transaction with the password, even when the correct password is used, you get an error making sending any transaction impossible.

![vdice2](https://cloud.githubusercontent.com/assets/25091038/21912766/cd497436-d8dc-11e6-82fa-3c890fb26ed5.png)

Workaround: Change back to geth node v 1.5.5, or disable external node and let the wallet launch it's internal node client.

**Comment by luclu** [comment]
Thank you @ethminer1!
For further updates please follow it's sibling issue at https://github.com/ethereum/meteor-dapp-wallet/issues/334.

**Comment by luclu** [comment]
Fixed (https://github.com/ethereum/meteor-dapp-wallet/issues/334).
