### ISSUE TITLE
Not syncing. I'm a noob and don't know how to do fast sync

### ISSUE THREAD

**Issue by Yorick111** [ethereum/mist#1584]
PLease help. Can someone explain on a very simple level how i can fix the sincing problem. It always get stuc around 2%. I deleted the chaindata a few times but it keeps getting stuck at 2 or 3%. I know there is a way to fast sinc but i don't know how to do it. 

Do i just need to type " Geth--fast" in the command prompt or something?

Sorry for being a nood. 

Thanks!

![knipsel](https://cloud.githubusercontent.com/assets/25053919/21928849/7002ecf6-d98d-11e6-89b4-7d563c94e430.JPG)

**Comment by luclu** [comment]
@Yorick111, please try to follow this guide and by any chance do yourself a favour in using a SSD instead a HDD.

**Comment by Yorick111** [comment]
What guide do you mean?

**Comment by luclu** [comment]
Oh sorry ;)
[This one](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555).

**Comment by Yorick111** [comment]
I followed the step in the guide, but it is still stuck at 2%. Should i wait because it is (super slowly) syncing or is it just stuck? 
Why does it take this long for syncing? Online wallets let you acces your account immediatly.. 

Thanks for the quick respons btw!

**Comment by frozeman** [comment]
It might be your firewall which slows down syncing if you are on windows

**Comment by Yorick111** [comment]
I turned of my firewall but it is still not working. It is always syncing but it always stops at 2%...

**Comment by luclu** [comment]
@Yorick111 could you please provide the following:
- type of storage device (SSD or HDD)
- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files 
- check the console (type `CTRL/CMD + ALT + i`) 
  - take a screenshot
  - post the output of the following commands:
    - `web3.admin.peers.length`

**Comment by Yorick111** [comment]
I have HDD :(

Node files in this link:
https://www.dropbox.com/s/v734pmr0e50g1cf/Node%20log%20x.zip?dl=0

![schermopname 194](https://cloud.githubusercontent.com/assets/25053919/21935757/ff40c976-d9ae-11e6-9e67-e8b8d3a48e1e.png)

**Comment by luclu** [comment]
Your computer seems to be running out of memory while processing the state.
```
I0113 16:21:47.410794 eth/downloader/downloader.go:966] imported 384 state entries in 878.586ms: processed 235712, pending at least 74499
I0113 16:21:47.523869 eth/downloader/downloader.go:966] imported 384 state entries in 516.343ms: processed 236096, pending at least 74596
I0113 16:21:48.012196 core/blockchain.go:792] imported 2048 receipts in    1.763s. #212294 [eeccff64… / 84a8f3c0…]
I0113 16:21:48.016198 eth/downloader/downloader.go:966] imported 281 state entries in 211.141ms: processed 236377, pending at least 74309
I0113 16:21:48.724671 eth/downloader/downloader.go:966] imported 384 state entries in 654.437ms: processed 236761, pending at least 74708
I0113 16:21:49.228007 eth/downloader/downloader.go:966] imported 384 state entries in 738.493ms: processed 237145, pending at least 74666
I0113 16:21:50.044552 eth/downloader/downloader.go:966] imported 384 state entries in 973.649ms: processed 237529, pending at least 74510
I0113 16:21:50.582911 eth/downloader/downloader.go:966] imported 384 state entries in    1.528s: processed 237913, pending at least 74245
I0113 16:21:50.616933 core/headerchain.go:331] imported 1984 headers in    6.146s. #226436 [1db1fe78… / 2e075e3f…]
I0113 16:21:51.214331 eth/downloader/downloader.go:966] imported 384 state entries in    1.164s: processed 238297, pending at least 74204
I0113 16:21:51.239349 core/blockchain.go:792] imported 2048 receipts in    3.217s. #214342 [df24738c… / 55cdb9af…]
runtime: out of memory: cannot allocate 268435456-byte block (856358912 in use)
fatal error: out of memory
```

**Comment by Yorick111** [comment]
Only 8 Gb of ram, but i'm running indesign and other programs. So if i close them it should work?

**Comment by luclu** [comment]
Hmm 8Gb is plenty, I think even 2Gb should be enough (at least on simple linux boxes). 
Please give it a try.

**Comment by Yorick111** [comment]
Still stuck at 2%... 

![image](https://cloud.githubusercontent.com/assets/25053919/21936842/f600a79c-d9b2-11e6-8fca-693561dd89a9.png)

**Comment by luclu** [comment]
Please try to reboot to have a "cleaner" execution environment and monitor the available memory until the crash. (Before the crash is important as after it the memory should be freed again)

**Comment by Yorick111** [comment]
Doesn't work. Still stops with syncing at 2%. memory was never over 40%

**Comment by evertonfraga** [comment]
What do the logs show now, that memory doesn't seem to be the problem?

**Comment by Yorick111** [comment]
https://www.dropbox.com/sh/qn4e33evwtob5vw/AACI2UtbxBk-T0kq0JNY6qi7a?dl=0

Here are the log files

**Comment by Yorick111** [comment]
https://www.dropbox.com/sh/qn4e33evwtob5vw/AACI2UtbxBk-T0kq0JNY6qi7a?dl=0

Here are the log files

**Comment by Yorick111** [comment]
![image](https://cloud.githubusercontent.com/assets/25053919/21957127/2fa6069e-da90-11e6-9a79-dd8a9336ee71.png)

**Comment by Yorick111** [comment]
@luclu It's still not working. Any idea on how to fix it?

**Comment by Yorick111** [comment]
![image](https://cloud.githubusercontent.com/assets/25053919/22156402/5ebc759c-df33-11e6-9157-e5b9744a5a54.png)

**Comment by luclu** [comment]
@Yorick111 just a quick check, does updating to version `0.8.9` help?

**Comment by Yorick111** [comment]
no it didn't work. I just installed it on an other computer and copied my key to that wallet. It worked and now i have send it to an other wallet.

**Comment by senarvi** [comment]
I'm experiencing a pretty identical problem. I also have 8 GB of RAM and 64-bit Windows 10. I just updated to 0.8.10.

    runtime: out of memory: cannot allocate 268435456-byte block (806813696 in use)
    fatal error: out of memory

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
