### ISSUE TITLE
Unable to access Ether in Mist Wallet

### ISSUE THREAD

**Issue by supercals** [ethereum/mist#1591]
Guys, I had some ether in my personal mist wallet.

I backedup my accounts (including Keystore) and upgraded mist. Some other changes were also made on my Mac. Since my mist wallet was not syncing; i deleted the Ethereum folder and started a new sync.

Now that the wallet is finally synced; I copied back my keystore into the new ethereum folder. The wallet shows up in Mist but there is no ether balance. When i check the wallet address on etherscan.io; i can see the correct ETH balance. But there is no ether in my wallet on my Mac.

Out of ideas... any suggestions.

**Comment by luclu** [comment]
@supercals please check if your local node is completely synced. What is the current block-number that you are presented in the network-info area?
