### ISSUE TITLE
Ethereum wallet 0.8.8 not showing balance?

### ISSUE THREAD

**Issue by zephyraijunzo** [ethereum/mist#1592]
As title states. Please help. thanks

**Comment by luclu** [comment]
@zephyraijunzo could you pease verify the balance using http://etherscan.io und check if your node is completely synced? Should you encounter any issues while syncing, please follow this guide: https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to
