### ISSUE TITLE
How can I sync Mist on a connection with a firewall?

### ISSUE THREAD

**Issue by rajlego** [ethereum/mist#1594]
#### System information
``````
Version: `0.8.8`
OS & Version: Ubuntu Gnome 16.10
Mist Wallet
``````

[Node Log Files.zip](https://github.com/ethereum/mist/files/707917/Node.Log.Files.zip)

My issue is that I can't sync Mist on my school network which has a firewall in place, though I can access it perfectly fine at home. How can I make Mist use ports that aren't blocked and how can I find what ports aren't blocked? I don't want to use a VPN or system proxy since I usually just use browsec for chrome when I need to bypass the firewall. I'd also prefer to use the Mist client rather than using any web clients for ethereum.

**Comment by evertonfraga** [comment]
See this answer on SO: https://ethereum.stackexchange.com/questions/6996/which-firewall-settings-should-i-use-for-geth-as-a-non-miner-using-linux-ubuntu
