### ISSUE TITLE
Duplication in naming sub-accounts

### ISSUE THREAD

**Issue by mightywurlitzer** [ethereum/mist#1597]
When making multiple accounts in a wallet, if you rename one, hit enter, then select another account, all account names will have in their name the text you just entered, including the account you just named, in duplicate.

Example:

if you start with three accounts:

main
account1
account2

then rename 'main' to 'master', hit enter and then select account1, all accounts will have the following names:

mastermaster
masteraccount1
masteraccount2

#### System information
``````
Version: `0.8.8`
OS & Version: linux mint 17.1 rebecca
Node type: `eth/geth(default)`
``````

**Comment by evertonfraga** [comment]
Couldn't reproduce here. Please confirm if this still happens on latest Wallet.
