### ISSUE TITLE
Cannot get past connecting to nodes OS X

### ISSUE THREAD

**Issue by CraigglesO** [ethereum/mist#1602]
PROBLEM: 

Node type: geth
Network: main
Platform: darwin (Architecure x64)

```
...lotted 1024MB cache and 1024 file handles to /Users/connor/Library/Ethereum/geth/chaindata
I0119 21:25:04.531956 ethdb/database.go:176] closed db:/Users/connor/Library/Ethereum/geth/chaindata
I0119 21:25:04.532971 node/node.go:176] instance: Geth/v1.5.5-stable-ff07d548/darwin/go1.7.4
I0119 21:25:04.533001 ethdb/database.go:83] Allotted 1024MB cache and 1024 file handles to /Users/connor/Library/Ethereum/geth/chaindata
I0119 21:25:04.883717 eth/backend.go:191] Protocol Versions: [63 62], Network Id: 1
I0119 21:25:04.884134 eth/backend.go:219] Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}
I0119 21:25:04.891815 core/blockchain.go:219] Last header: #192 [723899e8…] TD=3453055867795
I0119 21:25:04.892304 core/blockchain.go:220] Last block: #0 [d4e56740…] TD=17179869184
I0119 21:25:04.892330 core/blockchain.go:221] Fast block: #55 [eb5889a2…] TD=969114770607
I0119 21:25:04.894372 p2p/server.go:342] Starting Server
```

Not sure what to do ehre. Keep getting an error connecting. Says I am connected to a node and then it won't keep moving on. I have a redis (db) daemon running. Is that a problem?

**Comment by luclu** [comment]
@CraigglesO your redis deamon shouldn't be a problem. Also from your log there is no problem obious, only that the sync did start yet.
Could you please add versions to your system information and check if this is a firewall issue?

**Comment by CraigglesO** [comment]
Version 0.8.8
License GPL-3.0
Github.com/ethereum mist. All though I downloaded from the website not from the mist repo and I also downloaded the mist repo with no success.

If it is a fire wall issue, What would I look for in the router? I haven't set any safety parameters for my firewall so I don't know what would be blocking this when I use Bittorents all the time.

**Comment by evertonfraga** [comment]
Would you start geth with these specific params? 
https://github.com/ethereum/mist/wiki#unable-to-find-peers

I'm closing this issue upon inactivity. Please reopen if needed.
