### ISSUE TITLE
Contract for token creation fails since updating to Geth 1.5.7

### ISSUE THREAD

**Issue by agnewpickens** [ethereum/mist#1605]
IBM Thinkcentre 8GB RAM
``````
Version: `0.8.8`
OS & Version: Windows 7 Pro
Node type: Geth 1.5.7
``````

Contract creation issues have been reported with Geth 1.5.7 in go-ethereum channel but this appears to be a Mist issue since updating to Geth 1.5.7.  Basic token contract now fails because data being deployed is missing 0x.  Thanks!

If possible add the following to your report:

![blob](https://cloud.githubusercontent.com/assets/18013756/22198417/7b769800-e124-11e6-8b73-3838f7cd7c64.png)
![mist contract issue](https://cloud.githubusercontent.com/assets/18013756/22198430/84c6aea4-e124-11e6-8528-a852fd42371f.PNG)

**Comment by luclu** [comment]
Thank you @agnewpickens for bringing this issue to awareness.

**Comment by SitiBanc** [comment]
same issue here  (mist version: 0.8.9 + geth 1.5.7)
workaround: downgrade to geth 1.5.5

**Comment by luclu** [comment]
@SitiBanc please use geth `>=1.5.8`. I highly recommend to use the lastest version `1.5.9`.

I will close this issue as it has been addressed.
