### ISSUE TITLE
Want to change Multisig Daily Limit

### ISSUE THREAD

**Issue by taoteh1221** [ethereum/mist#162]
I'm trying to change my daily limit in a test multisig wallet in Mist on the live network, under "Show Contract Info". I can't seem to figure out how to do it? I am trying to change from 1 ETH daily over to 2 ETH daily. I have it requiring 2 account signatures.

**Comment by frozeman** [comment]
Thats not easy right now, rather wait until we support this feature "natively" in the wallet

**Comment by taoteh1221** [comment]
Ok, thanks for the information.

**Comment by CJentzsch** [comment]
I guess this is your problem: https://github.com/ethereum/meteor-dapp-wallet/issues/157

**Comment by taoteh1221** [comment]
Bummer, guess it will be awhile before that's sorted out.

**Comment by frozeman** [comment]
Its easier for now to just create a new one and move the funds.

**Comment by taoteh1221** [comment]
Yes, I already did that awhile ago.
