### ISSUE TITLE
Block chain is lost after reinstall Ethereum Wallet

### ISSUE THREAD

**Issue by schwitin** [ethereum/mist#1621]
#### System information
``````
Version: `0.8.8`
OS & Version: debian testing
Node type: `geth(default)`
``````

Steps to reproduction:
- install Mist
- install Ethereum Wallet
- run Mist create account start sync
- stop Mist start Ethereum Wallet continue sync
- stop Ethereum Wallet  at 12% sync
- uninstall Mist with apt-get remove mist
- uninstall Ethereum Wallet  with apt-get remove ethereumwallet
- install Ethereum Wallet with dpkg -i ...
- start Ethereum Wallet 

Expected:
- sync is 12%
- sync shod be continued

Current:
- sync is 0% and starts from new

Improvement:
- The block chain should be removed with apt-get purge

**Comment by luclu** [comment]
@schwitin this is most likely related to geth internally resetting the database after a corruption.

Issuing `apt-get remove mist/ethereumwallet` shouldn't remove `~/.ethereum` as that folder is not related to mist/ethereumwallet package but created by geth.

Please post the output of `ls -l ~/.ethereum`.

**Comment by schwitin** [comment]
drwxr-xr-x 4 stalker stalker 4096 Jan 28 11:23 geth
srw------- 1 stalker stalker    0 Jan 30 07:36 geth.ipc
drwx------ 2 stalker stalker 4096 Jan 28 13:59 keystore

**Comment by evertonfraga** [comment]
It seems you didn't have the `geth` or `chaindata` folder. This should be fixed on Geth newest releases.
