### ISSUE TITLE
Having issue creating a hello world contract.

### ISSUE THREAD

**Issue by kunalbansal92** [ethereum/mist#1627]
Documentation at https://www.ethereum.org/greeter specifies to setup solidity compiler. But there is no specific tutorial for that.

It says
Use this command: eth.getCompilers()

But where and how?

**Comment by kunalbansal92** [comment]
May be I missed it. We need to use 

"geth compiler"

to start the compiler to write our commands in.

Thanks

**Comment by luclu** [comment]
Hi @kunalbansal92, you can simply use `Mist/Ethereum Wallet -> contracts -> deploy contract` to compile and deploy any code.

If you want to do it via geth's console these links might be useful:
- https://ethereum.stackexchange.com/questions/5840/solidity-is-installed-but-is-not-working-within-geth-on-ubuntu-16-04
- https://forum.ethereum.org/discussion/2628/web3-eth-compile-solidity-not-working
