### ISSUE TITLE
ETH transfer

### ISSUE THREAD

**Issue by iakmaral** [ethereum/mist#1628]
Hello! I posted yesterday on the wallet 0x5c1dBc672aBA971706886026A9393A2708adE995 0,3ETN through the exchange of currency https://bankcomat.com . ethereum not received, it passed 20 hours. Tell me what's the problem? Thank you!

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by alexvandesande** [comment]
please check if your transaction happened on etherscan.io and if your wallet is synced up
