### ISSUE TITLE
How to RECOVER Accounts Balance Lost after re-install Mist Ethereum ? 

### ISSUE THREAD

**Issue by Tektonike** [ethereum/mist#1636]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by Tektonike** [comment]
I Have Backuped Keystore and reinstall Mist Ethereum al chaindb restored, accounts also, but all accounts with ZEROES whilw into Block Chain its rave positive balance. 
What to do, to recover my money?

**Comment by evertonfraga** [comment]
If you search for the address in a block explorer (eg: http://etherscan.io) and can check your balances, no worries! It can be just a normal out-of-sync issue.

Please check that you're looking at the Main net (`Develop > Network > Main net`) and that you are fully synced.

**Comment by Tektonike** [comment]
hi ! I saw on etherscan.io is there  but Ethereum Sistem didnt atualize tgeir balance

**Comment by Tektonike** [comment]
0x51E48c08a7B965D41e77Ed537606cAC659f4cDa4
NovaEthereum	0.1 Ether
  	0x120575b375C146E310668440638bF90001a0E575
TekEthStore	0.014 Ether
  	0x50538796Db2fFBA7E5054a5181082dAbA96C41b1
Tektonike Acc 3 Nova	0 Ether
  	0x41bDDd10A982Cd8C10BC242Bea8e32b5D9268be2
Tektonike Main Acc Nova	0 Ether
  	0x6FaF5b9960BBAAC5A2998f1cd594b2907218a4Ed
Tektonike3	0.1 Ether
  	0x199Cc7c9D9A73C632039154452Da003963a34964
Tektonike2	0.1 Ether
  	0x13C1CD172B656d4b7bE202B786DfB9F45b396690
Account2	0.1 Ether
  	0xdf895464E9ba935E93b87D8aABF4e423Bb87f804
ACCOUNT3	0.13893297 Ether
  	0xAECd12865c877894531a8601E02cF7f976faeDdB
MASTER	0.06174492 Ether

**Comment by Tektonike** [comment]
TxHash: 	0xf17265a15a7308fe0128d7941476a03012707037c193031f29b6bd453155a5c7
  Block Height: 	2761101 (410570 block confirmations)
  TimeStamp : 	67 days 20 hrs ago (Dec-07-2016 12:07:16 AM +UTC)
  From: 	0x50538796db2ffba7e5054a5181082daba96c41b1
  To: 	0x41bddd10a982cd8c10bc242bea8e32b5d9268be2
  Value: 	0.191989316092 Ether ($2.18)
  Gas: 	21000
  Gas Price: 	0.000000018 Ether
  Gas Used By Transaction: 	21000
  Actual Tx Cost/Fee: 	0.000378 Ether ($0.0043)
  Cumulative Gas Used: 	404209
  Nonce: 	4

**Comment by Tektonike** [comment]
Address  0xAECd12865c877894531a8601E02cF7f976faeDdB

    Home Normal AccountsAddress 


Overview
ETH Balance: 	0.061744927 Ether ($0.70)
Mined:  	0
No Of Transactions: 	20 txns

**Comment by Tektonike** [comment]
0xF3538c87433d9f40D7954620431fA3b552ad0e8A
Ethereum
0.050
ETH

**Comment by Tektonike** [comment]
0xAECd12865c877894531a8601E02cF7f976faeDdB
TxHash 	Block 	Age 	From 		To 	Value 	[TxFee]
0xd27185e1341d3499d659ec9c0a0737ef7ecad91063e72f878e779f72b079a19c	2300157	144 days 8 hrs ago	0x41bddd10a982cd8c10bc242bea8e32b5d9268be2	  IN  	0xaecd12865c877894531a8601e02cf7f976faeddb	0.01 Ether	0.00042
0xf3523545d108ea8e0baee5d370e55301fc5560c4747eb68e4171291f2682ec57	2220795	157 days 10 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0x199cc7c9d9a73c632039154452da003963a34964	0 Ether	0.00106998
0x8605a71ee55ca20b74ceae10bf16e6666c4851c401b889f2ca668c32c32c7549	2220793	157 days 10 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0x199cc7c9d9a73c632039154452da003963a34964	0 Ether	0.00106998
0x67da016a6272ff58ce1779d8ca357687039a55a84cd2915ea66462ea24a9b27f	2220790	157 days 10 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0x199cc7c9d9a73c632039154452da003963a34964	0 Ether	0.00106998
0x2411ce1411711e3f228c6acd8736001d7989d65dc45c8d59b24dc29370a98b83	2220788	157 days 10 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0xdf895464e9ba935e93b87d8aabf4e423bb87f804	0.0289 Ether	0.00067641
0x5cdd1b15736ea689fa3a798519f96fc64e6b60f4cd8ade4b3f32086a50dc616d	2220788	157 days 10 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0x199cc7c9d9a73c632039154452da003963a34964	0 Ether	0.00139298
0xaa508c0291585cd23de16bfdf384dd98fc5f0a5520cf33a7d22f5ab999ccb16f	2209667	159 days 6 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	 Contract Creation	0 Ether	0.03924478
0xb72bbed2e7105877732ba918a604b0b2d73e60148ef3cb3bfbc426bd9a05f0e2	2206212	159 days 20 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0x199cc7c9d9a73c632039154452da003963a34964	0 Ether	0.00111633
0xe7dbe4394f6e188f78cd703934d305f2eb367642b489fe9d9797bded95c3782d	2206206	159 days 20 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0x199cc7c9d9a73c632039154452da003963a34964	0 Ether	0.00111633
0x0eb5375da1ea932040de781c3f5862300949634bb7707cc3ab4432a39fbcda3d	2206021	159 days 21 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0x199cc7c9d9a73c632039154452da003963a34964	0 Ether	0.00111633
0xfab059de7f33dfeb8e8cba9b6451c06466da4a65d56145c8922feeb5e7bd9b7c	2205804	159 days 22 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0xdf895464e9ba935e93b87d8aabf4e423bb87f804	0.1 Ether	0.00067641
0x2b1a05fcdacb38cf1669be4894fd8f13cb24877ef577240edbf31235df6f76b3	2205497	159 days 23 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0xdf895464e9ba935e93b87d8aabf4e423bb87f804	0.1 Ether	0.00026077
0xdba429f790bbc814ff0c4513a99c236f627da20ce3ef54f504a2a8f103630d4e	2205325	160 days 7 mins ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0x13c1cd172b656d4b7be202b786dfb9f45b396690	0.1 Ether	0.00067641
0x68e5dfbf23cc38ba585d238f197ce4ff3778b25fec60f8a1cd3df103149cdfd6	2204341	160 days 4 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0x6faf5b9960bbaac5a2998f1cd594b2907218a4ed	0.1 Ether	0.00072224
0xf8df7c8983bd97c8582576899b3b59ea259fc9f054758521af817625a7712d60	2204335	160 days 4 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0x199cc7c9d9a73c632039154452da003963a34964	0 Ether	0.00111633
0x171d8b9f302969f6ccf88f4c1e6ed25f1eec7f37f7982009154d69122f9e6908	2204309	160 days 4 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	 Contract Creation	0 Ether	0.03924478
0xff900641ad3c53f93908321f4a2f1b74819bad428e9b53dc8ede48f064eae284	2204291	160 days 4 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	0x199cc7c9d9a73c632039154452da003963a34964	0.1 Ether	0.00072224
0x817bdb3cc5ec68fa10e6c355336e84408fd7f84ff3fca132efa17da9ca5fbb1a	2204234	160 days 4 hrs ago	0xaecd12865c877894531a8601e02cf7f976faeddb	OUT	 Contract Creation	0 Ether	0.03924478
0x01684b74d92c00edb5726a04d43b233dc7b4557fc77ab70627770b1f0fb7b36b	2204225	160 days 4 hrs ago	0x9e6316f44baeeee5d41a1070516cc5fa47baf227	  IN  	0xaecd12865c877894531a8601e02cf7f976faeddb	0.66951192 Ether	0.00042
0x2f7e5f850470db6fa4f3ac156402de356cb5acca2762c4284e8971e3253f089c	2202307	160 days 12 hrs ago	0x9e6316f44baeeee5d41a1070516cc5fa47baf227	  IN  	0xaecd12865c877894531a8601e02cf7f976faeddb	0.04167012 Ether	0.00042

**Comment by Tektonike** [comment]
I Thunk that I make a mistake !
Instead BUY MONEY
I Wrote Bye bye Money !
rsrsrsrsr

**Comment by kingburrito666** [comment]
Can you help me I have the same issue!

**Comment by luclu** [comment]
@Tektonike could you please summurize the current status? I'm not quite sure if I can follow you.

@kingburrito666 you can simply use Ethereum Wallet/Mist and go to `menu->account->import` to import your back up of the json (keystore) file.

**Comment by Tektonike** [comment]
@kingburrito666  Tks , but Option available only to PreSale Accounts

**Comment by Tektonike** [comment]
@luclu  Tks ! 
Some  Accounts created since 2016   
I Made BKP of KeyStore   and after install a new version  i copy KeyStore to Original Application drive from External HD to Program Ethereum\keystore 
Start Mist and it recover all DB during some days ! 
All Balances was Lost, is ZERO,  but on Etherscan-io acconts Shows Funds .
CONTRACTS WAS NOT RECOVERED and FUNDS dont Atualize Accounts Balances !

**Comment by Tektonike** [comment]
@kingburrito666  sorry ,  I dont have solution yet !  And dont have Time to stay Traying and Trayng again and wait day to recover DB All ways !

**Comment by evertonfraga** [comment]
Fernando, faça o seguinte: 

1) sincronize com a blockchain inteira - pode levar um bocado de tempo, mas funciona.

2) vá no https://etherscan.io/, procure pelo endereço de onde você criou seus contratos.
2.1) Procure pelos endereços dos contratos que você criou.
2.2) Na wallet, vá em Contracts > Watch Contracts, e cole o Endereço do contrato criado, e no campo JSON ABI, cole isto: 
```
[{"constant":false,"inputs":[{"name":"_owner","type":"address"}],"name":"removeOwner","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"_addr","type":"address"}],"name":"isOwner","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":true,"inputs":[],"name":"m_numOwners","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[],"name":"m_lastDay","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[],"name":"version","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[],"name":"resetSpentToday","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"m_spentToday","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"_owner","type":"address"}],"name":"addOwner","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"m_required","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":false,"inputs":[{"name":"_h","type":"bytes32"}],"name":"confirm","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":false,"inputs":[{"name":"_newLimit","type":"uint256"}],"name":"setDailyLimit","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"},{"name":"_data","type":"bytes"}],"name":"execute","outputs":[{"name":"_r","type":"bytes32"}],"type":"function"},{"constant":false,"inputs":[{"name":"_operation","type":"bytes32"}],"name":"revoke","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"_newRequired","type":"uint256"}],"name":"changeRequirement","outputs":[],"type":"function"},{"constant":true,"inputs":[{"name":"_operation","type":"bytes32"},{"name":"_owner","type":"address"}],"name":"hasConfirmed","outputs":[{"name":"","type":"bool"}],"type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"}],"name":"kill","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"}],"name":"changeOwner","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"m_dailyLimit","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"inputs":[{"name":"_owners","type":"address[]"},{"name":"_required","type":"uint256"},{"name":"_daylimit","type":"uint256"}],"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"owner","type":"address"},{"indexed":false,"name":"operation","type":"bytes32"}],"name":"Confirmation","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"owner","type":"address"},{"indexed":false,"name":"operation","type":"bytes32"}],"name":"Revoke","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"oldOwner","type":"address"},{"indexed":false,"name":"newOwner","type":"address"}],"name":"OwnerChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"newOwner","type":"address"}],"name":"OwnerAdded","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"oldOwner","type":"address"}],"name":"OwnerRemoved","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"newRequirement","type":"uint256"}],"name":"RequirementChanged","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"from","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Deposit","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"owner","type":"address"},{"indexed":false,"name":"value","type":"uint256"},{"indexed":false,"name":"to","type":"address"},{"indexed":false,"name":"data","type":"bytes"}],"name":"SingleTransact","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"owner","type":"address"},{"indexed":false,"name":"operation","type":"bytes32"},{"indexed":false,"name":"value","type":"uint256"},{"indexed":false,"name":"to","type":"address"},{"indexed":false,"name":"data","type":"bytes"}],"name":"MultiTransact","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"operation","type":"bytes32"},{"indexed":false,"name":"initiator","type":"address"},{"indexed":false,"name":"value","type":"uint256"},{"indexed":false,"name":"to","type":"address"},{"indexed":false,"name":"data","type":"bytes"}],"name":"ConfirmationNeeded","type":"event"}]
```
