### ISSUE TITLE
Way to import private keys/wallet backup/.json?

### ISSUE THREAD

**Issue by CryptoAmanda** [ethereum/mist#164]
Hi, just wondering if Mist offers the capability to "sweep" private keys created from other wallets. I've looked around it and didn't see anything like that, but I may have missed it.

Thank you for your time.

**Comment by frozeman** [comment]
Hi amanda,

the next version will have a way to import the perusal wallet, but not a export or import function for private keys.
For this simply go to menu "Backup - > backup keys" and copy the key files in and out.
