### ISSUE TITLE
Couldn't connect to node

### ISSUE THREAD

**Issue by Feb0** [ethereum/mist#1646]
#### System information
``````
Version: `0.8.9`
OS & Version: windows7
Node type: `eth/geth(default)`
``````
I was able to access wallet 10 days ago, now with 0.8.9 get this when try to open it

![d3aa2fdd69524fe581bc5d8d8553ebab](https://cloud.githubusercontent.com/assets/25586185/22649087/c4db3c84-ec79-11e6-9bd4-107384a49df6.png)

**Comment by BernyMY** [comment]
i have the same thing. Anyone can help ?

**Comment by luclu** [comment]
Could you please check if any external instance of geth has been launched?

**Comment by luclu** [comment]
Could you please check if https://github.com/ethereum/mist/issues/1715 applies (instructions in the links I posted there)?

**Comment by buddytheguy** [comment]
Has anybody fixed the issue? I'm still having the same problem.

**Comment by evertonfraga** [comment]
This is due to a timeout while Mist expects an answer from Geth and it's silent for too long. Running as administrator also helps, because Geth opens several ports for p2p communication.

Should be fixed as Geth had several versions since then.
