### ISSUE TITLE
How i can setup proxy(username and pass) when mist working under proxy?

### ISSUE THREAD

**Issue by Bubleek** [ethereum/mist#165]
Hello to all!
Now i want setup proxy for geth becouse internet connection on my work is under proxy. Any ideas about setup proxy(user name and pass) for geth?

**Comment by luclu** [comment]
@Bubleek for now you will have to rely on your (global) OS-config-tools. Depending on your OS there might be possibilities to specify this on a per application-base.

**Comment by ivica7** [comment]
Would this be possible on Win7 with "netsh winhttp set proxy ..."?
