### ISSUE TITLE
0 Eth in pre-sale wallet

### ISSUE THREAD

**Issue by CaptainCynical** [ethereum/mist#1651]
Hello,

I've purchased ETH during the pre-sale and the pre-sale wallet that was sent to me is empty:   a3ea6c4e45dfc6ddfe701e02d75d23a3d8319518.  

Date of email from confirmation@sale.ethereum.org: Sat, Aug 2, 2014 at 4:27 AM...

Can someone point me in the right direction with respect to who I have to talk to in order to get this sorted out?

Thank-you

**Comment by luclu** [comment]
Try to contact https://www.reddit.com/user/Souptacular, he should be able to help you or get you in contact with the right person.
