### ISSUE TITLE
Bytecode generated by the compiler

### ISSUE THREAD

**Issue by pacifics** [ethereum/mist#1655]
Version: `0.8.9`
OS & Version: windows 10 x64
Node type: `eth/geth(default)`  I have to install geth? Doesn't ethereum wallet include that?

When I deploy the next contract :
pragma solidity 0.4.8;
contract MyContract {function MyContract() {int i = 0;} }

the raw data generated by Mist is: 
0x6060604052346000575b60005b505b603580601b6000396000f30060606040525b60005600a165627a7a72305820ac54f0a645fedba61332d7cdee7580297218e979a87c64c5a0783b204bbf6cfc0029

With the online complier solidity version 0.4.8+commit.60cc1668, the bytecode generated is:
0x6060604052346000575b60005b505b603580601b6000396000f30060606040525b60005600a165627a7a72305820b47c5064358fa2c057435bf7577f611ea8fe768de10e63fb08873c306ff10e8d0029

So different results. Is it normal ?

**Comment by luclu** [comment]
>  I have to install geth? Doesn't ethereum wallet include that?
Yes, at default geth is bundle with Mist/Ethereum Wallet.

> So different results. Is it normal ?
The outputs differ as the wallet enables compiler optimizations by default, whereas http://remix.ethereum.org has them disabled by default.
