### ISSUE TITLE
Confirmation window is to large

### ISSUE THREAD

**Issue by frozeman** [ethereum/mist#1656]
This happens when making a tx from a wallet contract and another tx has to confirm.

I think we change the height automatically somewhere

<img width="1267" alt="screen shot 2017-02-12 at 15 50 49" src="https://cloud.githubusercontent.com/assets/232662/22864159/63549fe6-f14c-11e6-8b2b-4b6e2abccc1e.png">

**Comment by luclu** [comment]
Fixed in https://github.com/ethereum/mist/pull/1665.
