### ISSUE TITLE
No ethereum available. Except in etherscan

### ISSUE THREAD

**Issue by kingburrito666** [ethereum/mist#1658]
#### System information
``````
Version: `0.8.9`
OS & Version: osx
Node type: `eth/geth(default)`
``````
I have multiple transactions into my account. My ethereum wallet shows that I still have 0 ether. **I've been everywhere** and **tried everything** to solve this problem. It's been 26 days since my first transaction which displays that it _did_ go through, but doesn't show up in my account at all. My account is here:
[https://etherscan.io/address/0x516976ce81751ebe077ca01c57b97c9665b0e10b](url)
Please help me, i've contacted coinbase, ethereum-support, and... reddit. 

-My console: **something's wrong?**
![screenshot 2017-02-12 16 26 17](https://cloud.githubusercontent.com/assets/17525596/22867612/33b4fa4e-f140-11e6-9d11-c66046907fe9.png)

- Log files 
[logs.zip](https://github.com/ethereum/mist/files/769792/logs.zip)
(will send ethereum to helper) 
Again: **WILL SEND ETHER TO HELPER**

**Comment by bas-vk** [comment]
According to the logs the wallet isn't synced with the blockchain. That causes the wallet to show an outdated balance. I'm not sure if you have mist running for the last 2 days and it has caught up. If not I recommend doing a fresh sync from scratch and let that run until it has caught up (usually a couple of hours).

**Comment by undergroundbase** [comment]
How you do a fresh sync from the scratch   :)

**Comment by undergroundbase** [comment]
i HAVE THE SAME PROBLEM  

https://etherscan.io/address/0xd1a7c8acdad36ce580a24bb27c530c4ae131ac8d
