### ISSUE TITLE
Exceed Block Gas Limit

### ISSUE THREAD

**Issue by xquizts** [ethereum/mist#1660]
Hello,

I tried sending some Ethereum to another wallet through Mist. However every time i tried sending, it kept having this error: "Exceed Block Gas Limit". 

I have tried googling for the solution, but most of them are adding some lines/codes into the other ethereum system. I am using Mist now, it does not seem to have any area/field for me to adjust Gas or something like that. 

Can anyone please help?
Thanks in advance.

Kev

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by frozeman** [comment]
On the confirmation window you can change the blue number of the provided gas. Tho i would like to see a repro which i can test. Do you have steps how to reproduce?

**Comment by xquizts** [comment]
Hello Fabian,

Thank you for your quick response.

In response to your question:
I cannot change the blue number of the provided gas, or any numbers for
that matter (please see attached).

The steps I took are:
After opening the software Mist, I click on "Wallet" tab
Then I click on the "Send" tab
Then I pasted the destination account address under the "To" field.
After that, under the "Amount" field I keyed in the amount I wanted to
transfer which i input 1 Eth
Then, I scroll all the way down and click "Send"

Another window popped up showing this

[image: Inline image 1]

I entered the password and click "Send Transaction"
And then the error "Exceeds block gas limit" showed

I have no idea how to bypass this problem.
Please help and advise.

Many thanks,
Kev

**Comment by xquizts** [comment]
Hello Fabian,

Thank you for your quick response and advise.

I have tried changing the blue number as you have advised. However I
realised that any figure above 5000 I will get an error of "Exceed Block
Gas Limit" but 500 and below I will get an error of "Intrinsic gas too low"

The steps I took are:
After opening the software Mist, I click on "Wallet" tab
Then I click on the "Send" tab
Then I pasted the destination account address under the "To" field.
After that, under the "Amount" field I keyed in the amount I wanted to
transfer which i input 1 Eth
Then, I scroll all the way down and click "Send"

Another window popped up showing this

[image: Inline image 1]

I entered the password and click "Send Transaction"
And then the error "Exceeds block gas limit" showed.
If I change the numbers in blue to "5000" or below I get "Intrinsic gas too
low" error instead.

I have no idea how to bypass this problem.
Please help and advise.

Many thanks,
Kev

**Comment by dhh2106** [comment]
I am having a similar issue in Ethereum Wallet. Every transaction I try (at all points in the sliding scale) returns the "Exceeds block gas limit" error. This is true even for transactions that are very small.

**Comment by xquizts** [comment]
@dhh2106 , I managed to transfer now. You will have to wait for the nodes and blocks to completely update and download. Once it's completed, the transactions should go through smoothly. It works for even small transaction amounts or fees.

**Comment by bikelis** [comment]
How long you wait until nodes and blocks completely download? i am waiting about few hours, and it moves very slowly... only small % of all downloaded now.

**Comment by xquizts** [comment]
@dhh2106 , i left the computer switched on at night when i sleep. It took a few days to complete downloading. Yes it is really slow. But when i works in the end, it is worth it. 

I hope the developer would do something about it, the downloading is too slow and is frustrating especially for new users who can absolutely find no answers online. Even the administrators cannot answer or solve this problem when I asked it. This is one very negative point about Ethererum for now.

**Comment by solSpec** [comment]
@xquizts, How much did you use at the "blue numbers" gas to make your transaction work?  I still having the same problem that you had. Is it different for every transaction or did you use 5001 or below or above.

You right that there are no information about this problem on the net. Really frustrating!

Thanks for finding the solution.

**Comment by xquizts** [comment]
@solSpec , i left it at default. You will have to leave the software open and have it download the nodes and blocks completely first. If not nothing we do will work at all. I tried it many times. 
Yes, indeed very frustrating

**Comment by solSpec** [comment]
@xquizts , Thanks for replying. I am about to leave the computer for days to make it download all the blocks. If you interrupt the downloading do you resume where you left or do you have to start at the beginning again? Thanks!

**Comment by xquizts** [comment]
@solSpec , no problem. It will continue from where you left off. So it's okay to switch off and switch on again when you are ready.

**Comment by solSpec** [comment]
At last everything seems to work. I had a couple of problems.

First my computer need to sync the time "time.windows.com"

I use the CLI to sync fast using the following command: geth.exe --fast --cache 1024

After leaving my computer for almost 24 hrs my mist wallet was fully synch. Now I can send/ spend my ethers .... at last!

See this link if others are having problems to: https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide

A big thanks @xquizts

**Comment by xquizts** [comment]
You're welcome @solSpec , glad things finally worked well for you! :)

**Comment by luclu** [comment]
I will close this issue for now as resolved.
