### ISSUE TITLE
Unable to find checksum for mist-win64-0-8-9.zip file. 

### ISSUE THREAD

**Issue by mbbyc** [ethereum/mist#1667]
Can someone provide mist-win64-0-8-9.zip checksum file?

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
@mbbyc I added the missing checksums to the release page: https://github.com/ethereum/mist/releases/tag/v0.8.9

**Comment by evertonfraga** [comment]
That was my bad.
