### ISSUE TITLE
Accounts appear lost whilst updated Ethereum Wallet is downloading blocks

### ISSUE THREAD

**Issue by willnwhite** [ethereum/mist#1668]
#### System information
``````
Version: `0.8.9`
OS & Version: osx 10.10.5
Node type: `eth/geth(default)` How do I find out?
``````

I downloaded Ethereum Wallet 0.8.9 from https://github.com/ethereum/mist/releases, and dragged it to my Applications folder.

![screen shot 2017-02-09 at 14 18 36](https://cloud.githubusercontent.com/assets/8081877/22974263/6b55c308-f379-11e6-88d1-e7deb54ba861.png)

I clicked "Replace". When I opened the new application, I get this screen:

![screen shot 2017-02-15 at 11 45 52](https://cloud.githubusercontent.com/assets/8081877/22974304/9a3d2648-f379-11e6-98c8-54485e1a9885.png)

and it wants me to set passwords as if I've never had an account before (I have had an account before):

![screen shot 2017-02-15 at 12 24 36](https://cloud.githubusercontent.com/assets/8081877/22974348/c01b7d2e-f379-11e6-9f3c-cef3c23a70b2.png)

I didn't make any new accounts. I went to: 

![screen shot 2017-02-15 at 11 46 12](https://cloud.githubusercontent.com/assets/8081877/22974371/e5dff17a-f379-11e6-8211-ba1cde2f92aa.png)

And chose Accounts. It took me to the keystore folder, which is empty.

I was using Ethereum Wallet several months ago and I remember having a balance in a testnet account. Then I opened it up a couple of weeks ago and it said there was a new version available, and I got:

![screen shot 2017-02-09 at 14 12 22](https://cloud.githubusercontent.com/assets/8081877/22976019/e21d8bc2-f380-11e6-97a7-7c1dddd4e12b.png)

and 

![screen shot 2017-02-09 at 14 14 31](https://cloud.githubusercontent.com/assets/8081877/22976035/ee94aa20-f380-11e6-97d3-0c49d4a5aea9.png)

and it wouldn't go any further. I had to force quit it to exit. So in actual fact I haven't seen my accounts working in Ethereum Wallet for several months.

**Comment by willnwhite** [comment]
The "Downloading blocks" screen is now gone and **I've got my account back**:

![screen shot 2017-02-15 at 15 31 13](https://cloud.githubusercontent.com/assets/8081877/22981264/e2da265c-f393-11e6-9c9d-ca74bbaf4bb7.png)

I'll leave this issue open because the UX still needs improving, i.e. it shouldn't look as if accounts are gone when it's downloading blocks. 

Also, I found out that there is a testnet folder and that testnet/keystore is where the testnet keys are kept. There should be a separate menu command for them, i.e. Accounts:Backup:Testnet Accounts, if all it does it take you to the folder in the Finder.

**Comment by aliyathoummavongsa** [comment]
Readme

**Comment by luclu** [comment]
@willnwhite, thank you for summarizing your experience.
You seem to have surfaced the following edge-case:
1. When starting Mist that onboarding-screen will only be shown if no accounts where found in the keystore folder of the currently configured network (main-, test-, any private-net)
2. As we refactored backend logic the old configuration of the selected network (in your case: testnet) did not get read.
3. As a fallback/default the mainnet was assumed as you restarted `v0.8.9`, which triggered the onboarding-screen again as your mainnet keystore must be empty.

Could you please check if (3) is the case? If not there might be some other bug.

**Comment by willnwhite** [comment]
Yes, my mainnet keystore is and was empty.
