### ISSUE TITLE
issue with OS X install: nam install -g electron-prebuilt

### ISSUE THREAD

**Issue by geigerzaehler242** [ethereum/mist#167]
when i follow the instructions and try to install on OS X it i get the error below with electron. 

if something changed with electron then maybe the instructions need to be updated.

sudo npm install -g electron-prebuilt

/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

electron-prebuilt@0.36.7 postinstall /usr/local/lib/node_modules/electron-prebuilt
node install.js
sh: node: command not found
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "electron-prebuilt"
npm ERR! node v5.6.0
npm ERR! npm v3.6.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron-prebuilt@0.36.7 postinstall: node install.js
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.36.7 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

**Comment by fonzarely** [comment]
Worked fine with node v4.1.2
What is your version ?

**Comment by frozeman** [comment]
I think thats has more to do with how or if your installed node properly. so i close this.
`sh: node: command not found`

Best is your configure you node so you don't need to use sudo
