### ISSUE TITLE
How to specify IPC path to connect?

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/mist#1670]
#### System information
``````
OS & Version: osx
Node type: `eth/geth(default)`
``````

node
```
geth --ipcpath ~/Library/Ethereum/geth2.ipc --datadir "./privatechain4" --networkid 1234 --port="33334" console
```

running by
```
/Applications/Ethereum\ Wallet.app/Contents/MacOS/Ethereum\ Wallet --rpc ~/Library/Ethereum/geth2.ipc 
```

**Comment by luclu** [comment]
Yes, this is valid - as stated in the Readme. 
I will close this for now.

**Comment by EasonWang01** [comment]
no,the problem is sometimes this not works

**Comment by lavoiee** [comment]
@EasonWang01 do the following:

modify this in your arguments to geth --ipcpath "~/geth.ipc"

and then when you invoke mist pass it this --rpc "~/geth.ipc"

I followed these instructions and then had to figure out the above to make it work. It works now.
http://chainskills.com/2017/03/10/part-3-setup-the-private-chain-miners/

Good luck. Hope you get it to work.
