### ISSUE TITLE
"Exceed Block Gas Limit" and "Intrinsic gas too low". Nothing In between. Cannot send Etherue

### ISSUE THREAD

**Issue by xquizts** [ethereum/mist#1671]
Hi All,

I tried sending some ethereum but it kept giving me an error "Exceed Block Gas Limit" when i tried sending by default settings.

And then I have tried changing the blue numbers. However I realised that any figure above 5000 I will get an error of "Exceed Block Gas Limit" but 5000 and below I will get an error of "Intrinsic gas too low".

Can anyone help? It's really frustrating, and I cannot send my ethereum anywhere. It's stuck!
Please help.

Many thanks in advance.
Kev

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment]
Probably fixed in newer Geth versions.
