### ISSUE TITLE
Not receiving Ethers in Mainnetwork Account

### ISSUE THREAD

**Issue by ncoinshop** [ethereum/mist#1675]
i have transfered many ethers to my account. i have not received it. for over 5 hours. what is the problem?

**Comment by undergroundbase** [comment]
Same problem here any advise 
https://etherscan.io/address/0xd1a7c8acdad36ce580a24bb27c530c4ae131ac8d ?

**Comment by solartrader** [comment]
Same problem here. How do we fix this?

**Comment by ProMensch** [comment]
same here!!

**Comment by luclu** [comment]
Please make sure that your wallet/Mist is completely synced. If there should be any problem you can reset the synchronization via https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to - **note that this will trigger a time-consuming full resync.**

**Comment by ProMensch** [comment]
Thanks, i worked my through already! Cheers, nico

Am 01.03.2017 21:42 schrieb "Luca Zeug" <notifications@github.com>:

**Comment by marpen3** [comment]
Hello, Yesterday I bought 10 ETH with BTC but I didn't receive any ETH in my main ether account. I reset the synchronization as luclu posted above but without any changes in my ETH ballance. Could somebody help me to fix this problem? I will attach some printscreen with transaction
![btc_ether](https://cloud.githubusercontent.com/assets/26159114/23570899/514de124-005e-11e7-9bfc-d680168332cc.jpg)
![ethereum](https://cloud.githubusercontent.com/assets/26159114/23570908/5a9fd2dc-005e-11e7-8e82-5a8a442817e0.jpg)

Thanks

**Comment by marpen3** [comment]
It looks like the transaction has never been processed by blockchain. Can anyone explain me where are my coins stuck? For me it looks that they are stuck into deposit address. What is that deposit address?

**Comment by luclu** [comment]
Please make sure you use the latest version of the wallet and your wallet is fully synced. Check your funds using http://etherscan.io/.

**Comment by undergroundbase** [comment]
Fixed thanksss!!!
