### ISSUE TITLE
geth.exe memory leak

### ISSUE THREAD

**Issue by artemzwinger** [ethereum/mist#1676]
![image](https://cloud.githubusercontent.com/assets/25799082/23162006/63829cb4-f83d-11e6-90ea-03f46c35c4cc.png)

**Comment by luclu** [comment]
@artemzwinger please run the following command the next time could encounter such a high memory consumption:
```
geth --exec 'debug.stacks()' attach > geth.stacks
```

**Comment by luclu** [comment]
I will close this for now as stalled.
