### ISSUE TITLE
I Have not received my Eth in Main Account...What do I do?

### ISSUE THREAD

**Issue by solartrader** [ethereum/mist#1677]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by meracapital8** [comment]
I have the same problem. Could you please look at:
System: windows 7
Node type: Geth 1.5.9

Console:
![noname](https://cloud.githubusercontent.com/assets/26039148/23339264/9e357804-fc2f-11e6-88eb-6073200b531e.jpg)

Log files:
[Ethereum Wallet.zip](https://github.com/ethereum/mist/files/801907/Ethereum.Wallet.zip)

**Comment by luclu** [comment]
@solartrader please use http://etherscan.io/ to verify if the transaction did succeed as there could also be a sync issue with your local node. Please give heads up on the outcome!

**Comment by solartrader** [comment]
@luclu Thank you very much for the recommendation. The ETH has been credited to my mani account after rebooting and updating the MIST browser. Problem solved. Thank you!
