### ISSUE TITLE
About installing and the found of Mist Data Folder

### ISSUE THREAD

**Issue by h2002al** [ethereum/mist#168]
Hello,

Maybe this is not the place for the problems which will be written by me but I don't know where to ask about those. So I am obligated to ask there. But I am sure that can help even others that are at my level and want to go further.

First I want to know if the latest version of the wallet can be installed as an update to an previous one (installed previously from me) or must be uninstalled the previous one and then installed the new last version.

Then I cannot find in any place the Mist Data Folder. I have windows 10,. Can someone show me the path to find this folder?

Thanks to whom will answer and will help me.

**Comment by Bubleek** [comment]
On win7 for me it placed here:
C:\Users\ASUS\AppData\Roaming\Ethereum
If you have installed lastest vesion mist just open it without sinking blochain data(push skip peer searching) then push Backup button on top main menu then push Account backup and mist data folder should be open in you computer.

**Comment by h2002al** [comment]
Thanks Bubleek. I found the Mist at "Backup" and then "Backup App Data" and not at "Backup Account". Anyhow without your help this "find" wouldn't be possible. :)

**Comment by ericterpstra** [comment]
Hi @h2002al 
Also be sure to check http://ethereum.stackexchange.com/ if you have any more questions.  It's a Q&A site dedicated to Ethereum, and people are very responsive.

**Comment by h2002al** [comment]
Hi @ericterpstra
Thanks for the suggestion. I will do that.

**Comment by frozeman** [comment]
I'll also added it to the readme 57d4744
