### ISSUE TITLE
Haven't receive Ethers in Mainnetwork Account

### ISSUE THREAD

**Issue by NavyBean** [ethereum/mist#1685]
https://etherscan.io/tx/0x04c9c3255cc7a9f5fb12a6b3840b0a03d72dbbc26f78d0d60703fa95a76ffd48
Ethereum wallet is still empty.... what to do?

**Comment by luclu** [comment]
@NavyBean please make sure your Wallet is completely synced to the network. Should you encounter any issue your can reset the synchronization follow this guide: https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to

**Comment by NavyBean** [comment]
thank you! it works!
