### ISSUE TITLE
Mist connected to `geth` but its window closed right after start up and quit the app

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/mist#1686]
- OS: Mac OS X El Capitan Version 10.11.1
 - geth:  1.5.7-stable-da2a22c3

I have followed the installation guide on the link: https://github.com/ethereum/mist

When I try to run the `Mist` I have face with the following error that the mist's window closed and also show up as blank window. Please note that `Mist` was able to successfully connect into `geth.ipc`.

    $ cd mist
    $ electron .

`Mist`'s blank window:

<img width="194" alt="screen shot 2017-03-01 at 10 05 05" src="https://cloud.githubusercontent.com/assets/18537398/23451350/3fb69890-fe68-11e6-9a68-510cc3ece453.png">

**Error Message:**

    main - Running in production mode: false
    Secp256k1 bindings are not compiled. Pure JS implementation will be used.
    main - Starting in Mist mode
    Db - Creating db: undefined
    Db - Loading db: undefined
    Windows - Creating commonly-used windows
    Windows - Create secondary window: loading, owner: notset
    updateChecker - Check for update...
    Windows - Create primary window: main, owner: notset
    Windows - Create primary window: splash, owner: notset
    ipcCommunicator - Backend language set to:  en-US
    ClientBinaryManager - Initializing...
    ClientBinaryManager - Resolving path to Eth client binary ...
    ClientBinaryManager - Eth client binary path: /Users/avatar/mist/nodes/eth/mac-x64/eth
    lientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
    updateChecker - App is up-to-date.
    ClientBinaryManager - No "skippedNodeVersion.json" found.
    ClientBinaryManager - Initializing...
    ClientBinaryManager - Resolving platform...
    ClientBinaryManager - Calculating possible clients...
    ClientBinaryManager - 1 possible clients.
    ClientBinaryManager - Verifying status of all 1 possible clients...
    ClientBinaryManager - Verify Geth status ...
    ClientBinaryManager - Checking for Geth sanity check ...
    ClientBinaryManager - Checking for Geth sanity check ...
    ClientBinaryManager - Checking sanity for Geth ...
    ClientBinaryManager - Checking sanity for Geth ...
    ClientBinaryManager - Sanity check failed for Geth Error: Unable to find "1.5.9" in Geth output
      at Promise.resolve.then.then.then (/Users/avatar/mist/node_modules/ethereum-client-binaries/src/index.js:635:17)
    Sockets/node-ipc - Connect to {"path":"/Users/avatar/Library/MyEthereumEbloc/geth.ipc"}
    Sockets/node-ipc - Connected!
    NodeSync - Ethereum node connected, re-start sync
    NodeSync - Starting sync loop
    Sockets/3 - Connect to {"path":"/Users/avatar/Library/MyEthereumEbloc/geth.ipc"}
    main - Connected via IPC to node.
    Sockets/3 - Connected!
    NodeSync - No more sync necessary
    main - Loading Interface at http://localhost:3000
    NodeSync - Sync loop ended
    Sockets/2 - Connect to {"path":"/Users/avatar/Library/MyEthereumEbloc/geth.ipc"}
    Sockets/2 - Connected!
    Windows - All primary windows closed/invisible, so quitting app...
    main - Defer quitting until sockets and node are shut down
    Sockets - Destroy all sockets
    Sockets/2 - Disconnecting...
    Sockets/3 - Disconnecting...
    Sockets/node-ipc - Disconnecting...
    main - About to quit...
    Windows - All primary windows closed/invisible, so quitting app...

Thank you for your valuable time and help.

  [1]: https://i.stack.imgur.com/N95bZ.png

**Comment by luclu** [comment]
Hello @avatar-lavventura, this is most likely the result of a missing meteor instance "filling the void". Does running `cd mist/interface && meteor` prevent this problem as described in https://github.com/ethereum/mist#run-mist?

**Comment by avatar-lavventura** [comment]
Yes it is fixed thank you :)

**Comment by luclu** [comment]
Great! :)
