### ISSUE TITLE
Require options for D drive storage. I got 256SSD and is now filling up 90%

### ISSUE THREAD

**Issue by mbbyc** [ethereum/mist#1687]
This is an ongoing request from a lot of users. I want to know if development team can provide firm ETA to make Ethereum wallet/Mist available to store the blockchain data on other drive apart from C drive? If there is no plan to do so please also let us know so we can give up the hope and look for alternative wallet.

**Comment by luclu** [comment]
Currently there is no GUI option for this. But you can either use symbolic links within your OS (For windows use `mklink /J C:\Users\Rewire\Ethereum D:\Ethereum`) or append this flag to the executable/shortcut: `--node-datadir D:\Ethereum`.
