### ISSUE TITLE
Mist window is empty

### ISSUE THREAD

**Issue by RussianNeuroMancer** [ethereum/mist#169]
Binary build from Ethereum-Wallet-linux64-0-3-9.zip archive from github project releases page.
Mist window is empty: http://imgur.com/N3ZJpDs Log: http://paste.ubuntu.com/15031041/

I tried to setup Mist on three laptops, but it's working only on one laptop, on two others there is just such empty window with working menu. Choosing fullscreen or window resize make window content black instead of white.
On first laptop where Mist working there is Kubuntu 15.10 amd64, on two others Kubuntu 15.10 amd64 and Kubuntu 16.04 amd64. Indeed, there is some difference between this laptops that make Mist work on one setup and doesn't work on another, but I just doesn't know where to look for something that break Mist.

**Comment by Bubleek** [comment]
Yes this is a bug on ubuntu. I think this is a bug with video drivers installed in you ubuntu.
Read this issue here: Window completely white #75

**Comment by RussianNeuroMancer** [comment]
That great, --ignore-gpu-blacklist did the trick! I close this one since this is clearly duplicate.
