### ISSUE TITLE
Mist not connecting to running geth

### ISSUE THREAD

**Issue by mcqj** [ethereum/mist#1693]
#### System information
``````
Version: `0.8.9`
OS & Version: macOS Sierra
Node type: `geth 1.5.9`
``````
When starting Mist with geth already running, Mist will not connect. The attached screen shots show the error and the console. Unfortunately, Mist will not allow me to resize at this point in the start cycle, so I can't get a larger screen shot of the console window.
When this happens, Mist will not exit gracefully and will not respond to quit. It must be forcibly killed from Activity Monitor. If geth is not already running, Mist will start up without any problem and will exit normally too.

[node.zip](https://github.com/ethereum/mist/files/814087/node.zip)

<img width="401" alt="screen shot 2017-03-02 at 14 23 07" src="https://cloud.githubusercontent.com/assets/5565612/23511106/ff9d0e5a-ff53-11e6-8cab-cbc8b993b6e7.png">
<img width="419" alt="screen shot 2017-03-02 at 14 16 43" src="https://cloud.githubusercontent.com/assets/5565612/23511107/0048c77c-ff54-11e6-99d3-b304221efa3f.png">

**Comment by luclu** [comment]
Could you please check if there is any instance of geth running in the background?

**Comment by mcqj** [comment]
There is a version of geth running. That is precisely the point - I want Mist to connect to the geth instance that is already running.

**Comment by luclu** [comment]
In this case please make sure the IPC paths match: https://github.com/ethereum/mist/issues/1666#issuecomment-283467107

**Comment by mcqj** [comment]
Looks like that was the problem for me.

When using "testnet it seems that" geth defaults to putting geth.ipc at `~/Library/Ethereum/testnet/geth.ipc` while Mist defults to putting it at `~/Library/Ethereum/geth.ipc`

Running geth with the option `--ipcpath ~/Library/Ethereum/geth.ipc` solved the issue for me.

Thanks

**Comment by ernest-m** [comment]
**Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use**

When this pops up using Mist on Mac while opening your private network, then you have to specify the exact path to the ipc file. The exact path is printed when geth is started in the command line!

**For GETH:**

`geth attach ipc:/path/to/the/file/geth.ipc`

**For MIST:**

`/Applications/Mist.app/Contents/MacOS/Mist --rpc <path to chaindata>/geth.ipc`

**Comment by fidenz-chim** [comment]
Step by step article of connecting Mist with Geth on a locally running network (in MacOS X) can be found [here](https://medium.com/@chim/ethereum-how-to-setup-a-local-test-node-with-initial-ether-balance-using-geth-974511ce712). Might be useful if you want to connect via RPC instead of IPC.
