### ISSUE TITLE
Cannot compile due to missing "scenarios" (yarn?)

### ISSUE THREAD

**Issue by nolash** [ethereum/mist#1694]
#### System information
``````
Version: 7ff3f284
OS & Version: linux 4.4.0-45-generic
``````
trying to follow install instruction for mist as specified in the repo README, after the "yarn" step I get: 

ERROR: There are no scenarios; must have at least one.

@agnewpickens in gitter suggested:

" You might try deleting your mist.lokidb file in Roaming\Mist.  Mist regenerates it, it seems to help to generate a new one when you are getting weird errors like this."

However no paths with *lokidb or *Roaming* exist in the repo.

**Comment by luclu** [comment]
Make sure yarn is up-to-date.
The lokidb is unrelated to this.

**Comment by nolash** [comment]
did update, have:
node 6.9.3
yarn 0.21.3
it's not enough?

**Comment by luclu** [comment]
Did it help?

**Comment by evertonfraga** [comment]
@nolash it seems you're using another `yarn` command, contained in [`cmdtest`](https://www.apt-browse.org/browse/ubuntu/trusty/universe/all/cmdtest/0.10-1/file/usr/bin/yarn).

please uninstall `cmdtest` and install the right one on https://github.com/yarnpkg/yarn
