### ISSUE TITLE
Ether Mist wallet password recovery/change

### ISSUE THREAD

**Issue by LeyFi** [ethereum/mist#1695]
System Mac OS 10.11 El Capitano

Unfortunately i cant send Ether from my Mist Destop Wallet to another Ether Wallet. 
The Wallet says that the password i wrote down is wrong. Now there are 120$ waiting to picked up.
I cant remember that i have another Password for the Mist Wallet. Now i try all passwords i remember but no success:/

I read a few Issues before, and be happy about there is a chance to get my Ether out of the Wallet with changing the password with the keystore file, homebrew and geth link: https://steemit.com/cryptocurrency/@tokyo3/how-to-change-your-ethereum-accounts-password-wallet-mist-geth
 Does it work?

 I try to install geth but i stock in the process to install it. 

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Searching online for the Command Line Tools
==> /usr/bin/sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progres
password:

Der Apple-Softwareaktualisierungsserver hat nicht geantwortet.
==> Installing 
==> /usr/bin/sudo /usr/sbin/softwareupdate -i 
Software Update Tool
Copyright 2002-2015 Apple Inc.

: No such update
No updates are available.
==> /usr/bin/sudo /bin/rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
==> /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
xcode-select: error: invalid developer directory '/Library/Developer/CommandLineTools'
Failed during: /usr/bin/sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
unknownA45E60B8B1BB:~ $ brew tap ethereum/ethereum
-bash: brew: command not found

Command not found? But Why? Can anyone help me with that please?

What should i do next? 

i will send you 20$ in Btc or ETH. I really appreciate every help. Thank you

**Comment by JohnEther** [comment]
Hello,

May be I can help you. I have a tools to try to recovery your password (mist, cold wallet). I need your utc file and some words or character present in your password. The results is not 100% but it's better than nothing. If you are ok with this, just reply (my apologize for my english, i'm french).

**Comment by janx69** [comment]
JohnEther 
I need your help: maybe you can help me in my stuggle
how can i reach you in MP ?

**Comment by JohnEther** [comment]
Hello,

You can send me a email to info@passwordwalletrecovery.com

Thx

**Comment by garretlaxton** [comment]
I wouldn't recommend anyone send their keystore files to the users email above..

**Comment by joorlove** [comment]
Hi everyone, I have a sort of same problem. I want to send Ethers for the first time and when I click on Send, I have to give a password. When I create a new account, it accepts my password, but when I try the same to send, it says it's the wrong one. What can I do? I already installed the latest version of the wallet..

**Comment by nlhuykhang** [comment]
Hi guys,

I have the same problem. I can only send ether/token from my main account, other accounts keep saying my password is wrong which I am pretty sure is right.

Please help.

**Comment by alexvandesande** [comment]
We have multiple "wrong password" threads and I suggest taking a look at them, as Ill merge this into that one: https://github.com/ethereum/mist/issues/3513

But some suggestions:

* Try using Myetherwallet.com or MyCrypto.com to unlock the password and see if it's a geth/mist issue.
* DO NOT SEND WALLET TO ANYONE BY EMAIL unless you trust them totally and have searched for reviews. If they are able to unlock it, they might claim all the money in it and you'll be without luck
