### ISSUE TITLE
I put $5 in to do a test mode to understand the contract feature (using my credit card) but my account doesn't reflect any contribution. Advice?

### ISSUE THREAD

**Issue by Schinnere** [ethereum/mist#1696]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
Hi @Schinnere, make sure that your wallet is completely synced with the network and use https://etherscan.io to check any balance on the mainnet or testnet.

Furthermore you don't have to spend money on mainnet Ether, but can simply use the Testnet or a private Network.

**Comment by luclu** [comment]
I will close this for now assuming it to be resolved.

**Comment by Schinnere** [comment]
I’ve been out of town and hadn’t had a chance to figure this out. I’m still not clear, where did my $5 go? Sorry that I’m not understanding this process.

Yvonne R. Castillo, Esq.
Vice President & Director, Risk Management
Victor O. Schinnerer & Company | Two Wisconsin Circle | Chevy Chase, MD 20815
Phone (301) 951-5438 | Mobile (301) 318-7783 | Fax (301) 951-5444 | Yvonne.Castillo@schinnerer.com<mailto:Yvonne.Castillo@schinnerer.com>
____________________________________________________________
specialty property/casualty | management liability | professional liability
[cid:image003.jpg@01D2982C.1CDAA5C0]<http://www.schinnerer.com/>     [cid:image004.jpg@01D2982C.1CDAA5C0] <http://www.schinnerer.com/60years>

**Comment by Schinnere** [comment]
I’m reading my emails from the last few days backwards and seeing this. Let me noodle around on this and I’ll get back to you if I need additional help. Thank you,

Yvonne R. Castillo, Esq.
Vice President & Director, Risk Management
Victor O. Schinnerer & Company | Two Wisconsin Circle | Chevy Chase, MD 20815
Phone (301) 951-5438 | Mobile (301) 318-7783 | Fax (301) 951-5444 | Yvonne.Castillo@schinnerer.com<mailto:Yvonne.Castillo@schinnerer.com>
____________________________________________________________
specialty property/casualty | management liability | professional liability
[cid:image001.jpg@01D29833.18D545F0]<http://www.schinnerer.com/>     [cid:image002.jpg@01D29833.18D545F0] <http://www.schinnerer.com/60years>

**Comment by luclu** [comment]
@Schinnere were you able to resolve the issue you had?

**Comment by Schinnere** [comment]
I haven’t had a chance yet to go back and look at this. I’m sorry. If you need to close this out, please feel free and I’ll try to get to this as soon as I can.

Yvonne R. Castillo, Esq.
Vice President & Director, Risk Management
Victor O. Schinnerer & Company | Two Wisconsin Circle | Chevy Chase, MD 20815
Phone (301) 951-5438 | Mobile (301) 318-7783 | Fax (301) 951-5444 | Yvonne.Castillo@schinnerer.com<mailto:Yvonne.Castillo@schinnerer.com>
____________________________________________________________
specialty property/casualty | management liability | professional liability
[cid:image003.jpg@01D29CE6.C8319730]<http://www.schinnerer.com/>     [cid:image004.jpg@01D29CE6.C8319730] <http://www.schinnerer.com/60years>

**Comment by luclu** [comment]
Ok, don't worry!
Though I will close it for now, trying to get the bug tracker a little bit more managable.
