### ISSUE TITLE
How long does it take to recieve Tether?

### ISSUE THREAD

**Issue by Zales92** [ethereum/mist#1697]
I buy teher with bitcoins on Mist wallet and i don´t recieve them yet. I want to ask how long does it take?
Thanks for your help.

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
@Zales92 unfortunately the testnet is currently in bad shape due to 3rd pary misuse (note, that it doesn't have the same security and robustness as the mainnet). Please be patient until this situation is resolved or setup a private network for testing purposes.

**Comment by Zales92** [comment]
Ok. And after resolving this situation ether will be on my wallet?

**Comment by Zales92** [comment]
Or is it possible to refund the payment? Thanks for your help.

**Comment by luclu** [comment]
Hmm, Testnet Ether shouldn't be traded as it doesn't have any momentary value. You might simple acquire huge amounts for testing by asking: https://www.reddit.com/user/Souptacular

**Comment by Zales92** [comment]
Is it possible to explain it to me? i don´t know what testnet ether is? Thanks :)

**Comment by luclu** [comment]
Sure, don't worry! Ether is the name for the cryptographic token on the main network ("the public blockchain"), TEther or Test Ether is the token on the test network - for testing purposes.

Now, did you acquire Ether or TEther? ;-)

**Comment by Zales92** [comment]
Thanks. And can i ask where i can get Ether acquire? 
Sorry for my questions I buying them for the first time.

**Comment by alexvandesande** [comment]
@Zales92 there was a confusion, @luclu thought you were talking about Test Ether. There is no "Tether", the currency is called "ether". You should have received it already but it's possible that your wallet is not synced.

**Comment by Zales92** [comment]
Thanks for your reply. And can i ask how to synce my mist wallet? :) 
Thanks :)

**Comment by luclu** [comment]
@Zales92 please follow [this guide](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569). I will close this issue for now, though please ask any remaining questions.
