### ISSUE TITLE
Not sure how I screwed up - painfully slow syncing (on 2nd day)

### ISSUE THREAD

**Issue by fitch263** [ethereum/mist#1703]
Hi,

I'm not sure how I screwed this up, but I had a few hundred ether in my mist wallet and then, two days ago, it disappeared. I was told by someone at shapeshift.io that I needed to resync my wallet. I've started doing that I'm on my second day. I'm not trying to mine, but I'm not sure what I can do at this point to speed things along. Any guidance would be appreciated. thanks!

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
Dont't worry @fitch263, first of you can check your balance using https://etherscan.io.

Please make sure you are running the latest version of the wallet (`0.8.9`). 
What is the current blocknumber you can see? (Or how many blocks are still left?).
Furthermore are you using an SSD or HDD? The later one will be painfully slow (10-20h instead of 1-2h).

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
