### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by HuguesDohmen** [ethereum/mist#1705]
I am getting sick of all these updates. It costs weeks to sync the wallet. Than every few months there is a wallet update. After every update the wallet sync is lost and I have to sync the complete wallet starting from zero. Again 3 weeks of work. Is there no other modern way to do updates? It looks like we are back in 1975.

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by MaSansky99** [comment]
Totally agree. For me Ethereum lost its significance due to the very poor support structure and applications

**Comment by luclu** [comment]
Thank you for voicing your concerns, I understand your frustration.
Please keep in mind that Ethereum is still in its development stage, the Wallet/Mist still in alpha, no production ready light-client yet, breaking changes on several layers of the stack. 

Ethereum is projected to be accessible by network users with the upcoming Metropolis release stage (https://blog.ethereum.org/2015/03/03/ethereum-launch-process/).

**Comment by HuguesDohmen** [comment]
Luclu, thanks but it is a 2 year old article.

**Comment by alexvandesande** [comment]
Thanks for your feedback @HuguesDohmen we agree that the download issue is really one of the biggest pain points of the ecosystem, but it is not related to Mist updates: updating the app should not affect your blockchain sync in any way
