### ISSUE TITLE
Deposit Issues

### ISSUE THREAD

**Issue by CodyApollo** [ethereum/mist#1709]
hello, i recently bought some ethereum after downloading the ethereum wallet and creating an account.  i bought them off the option that says "fund with a credit card" and have been waiting for awhile but nothing has shown, but it has taken the money out of my bank account. does it take a couple days for it to show in my wallet? did i do something wrong in making the account? 

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
Hi @CodyApollo, most likely your wallet is not yet synchronized to the network, i.e. to see your wallet must be completely synchronized. Use https://etherscan.io to check your account in the meantime.

**Comment by alexvandesande** [comment]
@CodyApollo please check in ether chain if the deposit is there. If it's not, contact coinbase.

**Comment by CodyApollo** [comment]
Dear Luca, 
Sorry for the newbie question, but do you know any videos on how to fully synchronize it? Or how I can?

**Comment by luclu** [comment]
You can try to follow [this guide](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569).
