### ISSUE TITLE
downloader.go Synchronisation failed: no peer s to keep download active...

### ISSUE THREAD

**Issue by Bubleek** [ethereum/mist#171]
I0213 16:32:59.161355    6424 blockchain.go:1243] imported 256 block(s) (0 queue
d 0 ignored) including 450 txs in 40.3023052s. #832548 [3782f1f0 / c07868ed]
I0213 16:32:59.162355    6424 downloader.go:267] Synchronisation failed: no peer
s to keep download active
OS win7x64. 2 days already i'm try do synchronisation but still can't over it.
Any ideas?

**Comment by frozeman** [comment]
Thats more an issue of github.com/ethereum/go-ethereum

can you re-open there?
