### ISSUE TITLE
Buying Ethereum

### ISSUE THREAD

**Issue by dcpolanco** [ethereum/mist#1710]
I purchased some ethereum on a credit card.  it hasn't posted to my account, and it's been more than 24 hours.  I have also been trying to create a wallet, and it's taking forever.  I had to close out of the program and give up on it.
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
@dcpolanco it seems that your wallet is not yet fully synchronized, thus not showing your balance. In the meantime you can use http://etherscan.io/ to check your balance. 
I will close this for now.
