### ISSUE TITLE
wallet problem

### ISSUE THREAD

**Issue by orkobar** [ethereum/mist#1714]
downloaded version 0.8.9 wallet and sent 0.5 eth from poloniex as a first try

ı tracked my transaction from etherchain.org and it shows eveything is ok

But i cant see on my wallet nearly 2 hours.

Also ı couldnt create any contract, it is says creating nearly 2 hours

Can anybody help me? What should i do?

![image](https://cloud.githubusercontent.com/assets/26259327/23674584/07e94b26-037f-11e7-8214-3e7b16514f1b.png)

Thanks

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by frozeman** [comment]
you aren't fully synced, as you can see with the blue bar on the top of your wallet.
If you are stuck then consider deactivating your firewall, or sync from scratch, by deleting the chaindata folder (only!) in `%APPDATA%\Ethereum\chaindata`

**Comment by orkobar** [comment]
Dear frozeman, thanks for quick reply, i tried to solve problem with your guidance but still have issues.

first i closed windows firewall and reopen the wallet and blue bar is more slower than previous, couldnt even come to %1 

than tried to give permission to app. and again couldnt come to %1

finally try to delete chain data folder from "%APPDATA%\Ethereum\chaindata" but there is no chain data folder.

what do you recommend ? can i moved this wallet to another computer and how :(

thanks again

**Comment by orkobar** [comment]
somehow, blue bar finished and my balance is ok now 👍 

am i need to create a contract? what is it and how works?

Sorry i am brand new in ethereum :(

thanks

**Comment by louiskonig** [comment]
I am having a similar issue.  The blue bar isn't moving at all.  I just downloaded and funded using the GUI, and it appears my funds went nowhere.  Can anyone assist?

**Comment by orkobar** [comment]
Dear louiskonig, as frozeman said, give a permission for app in firewall

**Comment by luclu** [comment]
@louiskonig were you able to resolve your issue?

@orkobar you don't need to create a contract [wallet]. Have a look at [this FAQ](http://ethdocs.org/en/latest/frequently-asked-questions/frequently-asked-questions.html?highlight=wallet%20contract#what-s-the-difference-between-account-and-wallet-contract).
> am i need to create a contract? what is it and how works?

**Comment by louiskonig** [comment]
Yes, I resolved it by downloading Parity, and then opened up Mist, and it was there!  Thx
