### ISSUE TITLE
Accounts not generating

### ISSUE THREAD

**Issue by Deekor** [ethereum/mist#1716]
Just downloaded the wallet for the first time. Clicked to add an account and typed in the password. The wallet popped up a window saying Generating Account and then it disappeared and I still have no accounts in my overview. I've tried this several times along with restarting the application.

Any ideas?

**Comment by frozeman** [comment]
@luclu thats the issue with not poping up accounts while syncing i guess. This should be fixed in the next release.

**Comment by luclu** [comment]
This is correct. As a workaround you will have to restart the application to get the accounts displayed.

**Comment by Deekor** [comment]
I restarted the application several times and they never displayed.

**Comment by luclu** [comment]
Could you please copy and fill out the information as described in: https://github.com/ethereum/mist/issues/new?

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
