### ISSUE TITLE
When I create an account it doesn't show up!

### ISSUE THREAD

**Issue by ThommyBoy** [ethereum/mist#1721]
#### System information
``````
Version: `0.8.9`
OS & Version: windows 10
Node type geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
![image](https://cloud.githubusercontent.com/assets/26357752/23830450/1594c8b8-0703-11e7-90c1-6542293a6e52.png)

As the title states nothing happens when I create and account.  I add a password and it does nothing after that.

**Comment by luclu** [comment]
Could you please check the following:
1. Were keyfiles created? (Go to `menu -> backup -> accounts` and check if there are any files in the `keystore` folder)
1. Do the accounts show up when restarting Mist/Ethereum Wallet?
1. What is the output of the this console command: `web3.personal.listAccounts.length`

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
