### ISSUE TITLE
Report of node.js dll outdated version and possible security issue

### ISSUE THREAD

**Issue by pascalvanhecke** [ethereum/mist#173]
A Reddit user testing the Windows version of the Wallet backed of because he reported an outdated (and according to him, insecure) version of  node.dll.

Source conversation: https://www.reddit.com/r/ethereum/comments/45kl8h/newbie_question_best_way_to_buy_and_hold_coins/

The conversation was a bit heated, and the user deleted some comments of his own that contained the technical information, I will copy-paste the relevant parts:

> 1) Download wallet, goto 'node.dll', right click, goto Properties then "Details". Has node.js signatures.
> Take note of version and the compare here: https://nodesecurity.io/advisories
> no concerns? Those are official advisories from the node.js team.

> 2) start wallet
>  run namp from external host.
>  notice anything funny?

>  3) Seems really shady that you deny node is bundled with wallet and seems even shadier that it has known security issues, opens ports and goes against node.js "best practices" in regards to security. If you guys want to use node, just be honest about it and configure it correctly. This is a user wallet, not development branch.

And:

> Download the wallet, it has an outdated (and with known security vulnerabilities) version of node.dll that binds to external interfaces. Run a port scan, it's not just local. This is from the wallet: Ethereum-Wallet-win64-0-3-9.zip
> edit: also look in %USERPRIFLE%\AppData\Roaming\Mist
>  it's shitting node debug logs all over the place.

**Comment by frozeman** [comment]
Hm.
So electron (the desktop hybrid app container we use for Mist) alters node a it as far as i know, so this would explain 1.

2. A bit more explanation would be fine. I don't start any kind of server anyone could access and i don't think this node instance either.

Concerning the log files, they are not from node(js) but from the node(geth) and we generate max 5 on purpose..
