### ISSUE TITLE
Is ethereum wallet available for Vista?

### ISSUE THREAD

**Issue by ashiyr** [ethereum/mist#1731]
Im having a problem installing the ethereum wallet. My error: missing SHELL2.dll

**Comment by luclu** [comment]
@ashiyr currently we are only testing on Windows 7 and Windows 10. Could you please try to download and launch the `zip` version of Mist/Ethereum Wallet and give me a ping back? It might be that the installer has some issue with (specific versions of) Vista.

**Comment by thiagowebx** [comment]
I have the same problem
![snap 2017-03-17 at 12 16 24](https://cloud.githubusercontent.com/assets/10249852/24049767/c5bc3ca6-0b0b-11e7-97fc-41e844a114e2.png)
![snap 2017-03-17 at 12 17 18](https://cloud.githubusercontent.com/assets/10249852/24049768/c5c120ea-0b0b-11e7-93dd-ab2c9eb33f50.png)

**Comment by luclu** [comment]
Unfortunately we can not support Windows Vista as its Extended support ends on 11 April 2017 and our dependency Electron/libchromium decided against adding it:
> We don't have plan to support Vista. ([source](https://github.com/electron/libchromiumcontent/issues/66)).

I advice you to update Vista to an update-supported OS to mitigate security risk.

**Comment by ashiyr** [comment]
Thank you for the information

**Comment by thiagowebx** [comment]
where is the error? i can not compile anything
![snap 2017-03-19 at 10 02 36](https://cloud.githubusercontent.com/assets/10249852/24081100/5287cac6-0c8b-11e7-9d62-b50b9b04809b.png)
