### ISSUE TITLE
Contract won't compile and wallet shuts down

### ISSUE THREAD

**Issue by GriffGreen** [ethereum/mist#174]
I am trying to play with the Slock.it Smart Contracts in the EW and it keeps crashing :-/. It is a huge contract, but I don't know why it crashes the EW. If I leave out a } and the contract doesn't compile, it doesn't crash it gives me the error.

I have tried to isolate it, but none of the contracts individually crash the wallet, only the combination of the four contracts. 

I am combining these 4 contracts:

https://github.com/slockit/smart-contract/blob/master/Crowdfunding.sol
https://github.com/slockit/smart-contract/blob/master/Token.sol
https://github.com/slockit/smart-contract/blob/master/ManagedAccount.sol
https://github.com/slockit/smart-contract/blob/master/DAO.sol

https://gist.github.com/frozeman/98824681c1bde1e880f3

**Comment by GriffGreen** [comment]
Oh and I forgot to mention that I am on the test network, I tried the main network and it also crashes

Here's my log file:

I0214 09:23:02.479227   13624 database.go:71] Alloted 16MB cache to C:\Users\griff\AppData\Roaming\Ethereum\testnet\chaindata
I0214 09:23:02.632337   13624 database.go:71] Alloted 16MB cache to C:\Users\griff\AppData\Roaming\Ethereum\testnet\dapp
I0214 09:23:02.641844   13624 backend.go:314] Protocol Versions: [63 62 61], Network Id: 2
I0214 09:23:02.643345   13624 genesis.go:89] Genesis block already in chain. Writing canonical number
I0214 09:23:02.645347   13624 backend.go:362] Blockchain DB Version: 3
I0214 09:23:02.645848   13624 blockchain.go:214] Last header: #409852 [8c9612d6…] TD=1930171545533
I0214 09:23:02.645848   13624 blockchain.go:215] Last block: #409852 [8c9612d6…] TD=1930171545533
I0214 09:23:02.645848   13624 blockchain.go:216] Fast block: #409852 [8c9612d6…] TD=1930171545533
I0214 09:23:02.646847   13624 handler.go:92] blockchain not empty, fast sync disabled
I0214 09:23:02.654852   13624 cmd.go:114] Starting Geth/v1.3.3/windows/go1.5.1
I0214 09:23:02.654852   13624 server.go:311] Starting Server
I0214 09:23:05.177187   13624 nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-IP1
I0214 09:23:05.787121   13624 udp.go:204] Listening, enode://fa6a8df9fe005841c3a7b71d973c9fd3428d73a01d8e501e8d4b082b260747e2785132bf01ea336f4b784698300efaf5ace84c71db0853cac4153dfe8eb6506f@73.53.57.231:30303
I0214 09:23:05.787607   13624 backend.go:526] Server started
I0214 09:23:05.787607   13624 ipc.go:112] IPC service started (\\.\pipe\geth.ipc)
I0214 09:23:05.788107   13624 server.go:552] Listening on [::]:30303
I0214 09:23:05.796615   13624 nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-IP1
I0214 09:23:25.789619   13624 downloader.go:288] Block synchronisation started
I0214 09:23:29.711763   13624 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 1.9180642s. #409853 [1c944c7b / 1c944c7b]
I0214 09:23:29.735779   13624 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 9 txs in 23.5147ms. #409854 [8aa53214 / 8aa53214]
I0214 09:24:04.646617   13624 blockchain.go:1243] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 5.0062ms. #409855 [b85152de / b85152de]

**Comment by frozeman** [comment]
The node doesn't seem to crash. Can you explain when it crashes? Maybe when you want to compile?

Your question isn't clear " contract doesn't compile, it doesn't crash it gives me the error."

What error?

I assume the solc javascript compiler is overwhelmed with these large contracts, try to compile them here: https://chriseth.github.io/browser-solidity/

Ps. its EVM (Ethereum Virtual Machine) not EM

**Comment by GriffGreen** [comment]
EW= Ethereum Wallet
It compiles on chriseth's compiler, that is where I am combining the 4 contracts.

The bug I am reporting is exactly that, the solc javascript compiler becoming over whelmed and then the ethereum wallet freezes and crashes.

The wallet doesn't crash if I paste in the contract with an error (like leaving out a "}" that is required, instead it reports the error in the code and says that I need the "}"  but then when I  add the "}" and the wallet tries to compile the large contract the wallet will crash.

My goal is to make a tutorial/video using our Slock.it contracts so that people who don't feel comfortable with command line programming can follow it and see the creation of our DAO.

But the Wallet crashes when it tries to compile the massive contract...

**Comment by frozeman** [comment]
I moved your contract into a gist, can reproduce the error. will take a look now.

**Comment by frozeman** [comment]
I updated to the latest solc version and now it does not crash anymore. so its fixed in the next release

**Comment by GriffGreen** [comment]
:-) Awesome!
