### ISSUE TITLE
lost mist wallet please help

### ISSUE THREAD

**Issue by janx69** [ethereum/mist#1741]
Hello

Excuse me i m a true noob to ETH and i really need some help.
Someone stole my laptop with my Mist wallet inside and i would like to recover it in my new laptop.

Unfortunately i ve only got the public adress and the password noted on a piece of paper as i was bulglarized and "they" stoled also my backup HDD and USB key where was a backup of the wallet.

There's also something strange noted on that piece of paper: a seed phrase ...
I don t know if it belongs to the wallet or something else maybe another wallet
(but as far as i know Mist doesn't work with any seed phrase or something like that and
i don t remember using another wallet than Mist for my ETH, where do this phrase comes from ?)...
From what i understand, i think i'm screwed.

I really loved ETH and the concept, and i've really got no more money to invest in.
Please help me (i can reward the person who help me if necessary) 

thanks

**Comment by luclu** [comment]
Hi @janx69,

if you used Mist/Ethereum Wallet/geth to create your account you will need the corresponding keyfile and the password. ([Here are examples](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition#pbkdf2-sha-256) for a keyfile).

> There's also something strange noted on that piece of paper: a seed phrase ...

Perhaps you instead used another service like https://www.myetherwallet.com? In that case you might be able to use the seed phrase to recover the accounts.

**Comment by janx69** [comment]
Thanks a lot for your answer luclu

Unfortunaltely i never used myetherwallet, i really don't know where this phrase comes from.
To my knowledge only jaxx and myetherwallet have a seed phrase function.
Let's forget it for the moment ...

All i'm know for sure is my ETH were stored in Mist (i only knew this wallet before).
From what i understand the keyfile aka JSON or UTC is the private key 
But, oh god ...  it's the thing i'm missing (it's in my stolen laptop hdd)

Fortunately, I found some interesting infos

According to the first answer of this thread:
https://www.reddit.com/r/ethereum/comments/4ah6hb/logging_into_account_using_public_key_and_password/
->The private key (encrypted with the password) is saved in the keystore file. 
    The private key derives the public key which derives the address. 

According to the last answer of this thread:
https://forum.ethereum.org/discussion/6605/how-do-you-see-my-private-key
-> knowing the password is knowing the private key

Is there something like the procedure in the link below to recover the keyfile from the password and the public adress ?
https://ethereum.stackexchange.com/questions/2535/how-can-i-import-accounts-created-by-quorumwallet-into-ethereum-wallet-mist/2538#2538

**Comment by luclu** [comment]
@janx69 to my best knowledge, this is unfortunately not possible:
> 'Knowing the password = Owning the private key ([source](https://forum.ethereum.org/discussion/comment/58859/#Comment_58859))

Also this does only applies if you used the Quorum fork of Ethereum (I doubt you did): 
> What is the algorithm used to create my account?
>
>It is fairly simple:
>
>seed = String(passphrase) + String(userid);
privatekey = PBKDF2(seed, seed, 2000, 32, 'sha256');

The `userid` should be the email or username you used to register. See https://ethereum.stackexchange.com/questions/2793/how-can-i-generate-a-v3-of-the-ethereum-wallet-file-format-in-js-from-strings.

**Comment by janx69** [comment]
hi luclu

ok thanks for the input !
your'e right, i never used Quorum fork ...

I will try to find some more infos, but i don't really know if it's possible 
and my knowledge about it is limited at the moment.

This story hurts me so bad, i don't want to give up ...
my life is really a pain at the moment, i lost too much $ in ETH
and more important, the hope of a bright future. 

Sadly, i'll never be able to afford the amount of ETH lost.
this make me a knot in my stomach each time i think about it

**Comment by janx69** [comment]
found this about the subject:
https://ethereum.stackexchange.com/questions/3542/how-are-ethereum-addresses-generated/3619#3619

**Comment by luclu** [comment]
@janx could you please describe the seed phrase that you found in detail?
- how many characters?
- alpha/numeric?
- sequence of words?
- only special characters like `0123456789ABCDEF`?
- upper/lower case?

Perhaps we could try to find its origin.

**Comment by janx69** [comment]
ok great thanks for your help 

it's a sequence of 6 english words with only letters 
with space between them and no uppercase 

there's a 7 th "word" written below with another pencil 
but it's not a word but more a 10 random letter 
i don't know if it belongs to the 6 word phrase.

damn, my memories are so shady about this 
i'm really upsetted about that sorry ...

**Comment by luclu** [comment]
So far I could only gather the following props of some wallets:
- [icebox](https://github.com/ConsenSys/icebox#new-wallet): 12 word seed phrase
- [jaxx](https://jaxx.io): 12 word seed phrase
- [metamask](https://metamask.io/terms.html): 12 word seed phrase
- [ledger](https://www.ledgerwallet.com): 24 word seed phrase
- [myetherwallet](https://www.myetherwallet.com/): private key (256 bit/32 byte/64 hex characters) + passphrase
- [quorum](http://quorumwallet.com/faq#account): passphrase + userid

Perhaps a 6 word seed phrase was used in the early days of on the services, although I really doubt that.

You could try to figure out the time you created that piece and ask for that 6 word seed phrase at https://ethereum.stackexchange.com or https://www.reddit.com/r/ethereum - perhaps someone knows more.

**Comment by janx69** [comment]
Hi luclu

Thanks for thoses infos, according to your infos this 6 word seed seems very odd
I can't remember much more about it for now, it's a shame. 
Moreover at the time i only knew Mist and i'm sure my ETH are in a Mist wallet.
Thanks for your help anyway, i'll try also https://ethereum.stackexchange.com or https://www.reddit.com/r/ethereum.
But i'm starting to think it's all over, and getting mad about this ...
damn

**Comment by luclu** [comment]
@janx69 I just stumbled upon [https://live.ether.camp](https://live.ether.camp/)'s brainwallet feature. Could you by any chance have used this? You will find it on the top left -> "Get address".

**Comment by sandrorivera** [comment]
@janx69 Hi there, I was wondering if you could finally find a solution? I'm in a very similar situation and don't know what to do... Thanks and good luck!

**Comment by samos123** [comment]
I'm in a similar situation where I have a 16 word seed phrase and a password written down on a paper that I remember was needed for Ethereum. I do not have the json wallet. Looking at the pyethsale tool it allows you to generate a wallet using a seed.

Anyone pointers on how I can regenerate the wallet using a 16 word seed and a password?

**Comment by janx69** [comment]
hi all 

thanks for your inputs, sorry but i was away from the crypto scene very busy for work 
I must admit that with the last answers i gave up the thing and try to not think about it as it 
really makes me feel bad ...

your messages  re give me interest in the subject but actually i not found any solution 
sorry about that
I hope there's one but i don't have the knowledge and the time to work on it 
Maybe Vitalik and his friend could help us ... haha

The last input from samos123 gave me a new info that may be  worth trying:
https://github.com/ryepdx
there is a tool called keyphrase wich is a A CLI utility that converts a private key expressed in hexadecimal to a phrase, with each word representing as close to 16 bits in your private key as your key's length allows. **Also converts phrases back to their hexadecimal equivalents.**

I doubt that this work for me because i'm 98% sur that i used Mist and it doesn't work any mnemonic phrase. So i think for me the only real soultion is to find a tool to recover a private key from a public key and a password ... 

if someone has an idea please, oh god, please help !

**Comment by janx69** [comment]
samos123, if you have your private key and password you're done ! 
sorry i forgot how to do it but i think the myetherwallet online tool will help you 
to get the wallet file ... maybe Mist also can do it ?

**Comment by sandrorivera** [comment]
Thanks for your message @janx69 

Hopefully in the future someone will find a solution to this. I wonder how much money is actually stuck in unaccessible wallets... it's ridiculous! If you lose your computer and your back ups (if you get robbed at home)... you lose your crypto wallet! It doesn't sound very safe... I wonder if it's not safer to have your money in a bank or even under the mattress... I would call this issue the "crypto paradox". 

I think there must be a way to recover it, maybe not now, but there must be one in the future. I do believe that having the public key and the password should be enough to certify that it belongs to you. 

I also hope someone here can actually tell me that I'm wrong, so I can learn something new.
