### ISSUE TITLE
[shorted] accounts not showing up

### ISSUE THREAD

**Issue by algroat** [ethereum/mist#1742]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

wallet refusing to accept accounts despite redownloading and refreshing...add password...says "Generating Account"then nothing..tried multiple times over twodays..nothing in the keystore file...Downloaded Geth..no different...please help ,got some ETH in a beta online wallet  ,a 

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
Did the initial sync already complete? (What blocknumber do you see in the interface?)

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
