### ISSUE TITLE
Issue with Ethereum Wallet - Failing to load/makes me re-download

### ISSUE THREAD

**Issue by brstraka** [ethereum/mist#1745]
#### System information
``````
Version: 0.8.9
OS & Version: Windows 64
Node type: geth
``````

I've had the Ethereum Wallet on my computer for the last year or so, but every time I go to open it, it says that there is an "Ethereum node connection error :'(" and then it says that there is a new version available for download (0.8.9). So I download it, allow time for the blocks to sync, and then it opens fine. But then when I shut down my computer, turn it back on, and re-open the Wallet, the same error message pops up and I have to download 0.8.9 all over again. My friends who also use the Wallet have not heard/encountered this issue. Right now I can't even get the wallet to load. That error message just pops up (see below).

Any insight would be helpful. For reference, I have a Windows 64-bit OS and I'm running Windows 10.

![image](https://cloud.githubusercontent.com/assets/26450578/23981155/d39041a6-09da-11e7-9762-b7b2c43c9a0d.png)

**Comment by luclu** [comment]
Could you please upload the `node.log`s?
You can find an instruction [here](https://github.com/ethereum/mist/issues/new):
> - Log files 
>   - go to `menu -> accounts -> backup -> application data`
>   - zip and upload `node.log` and all other `node.log.X` files

**Comment by brstraka** [comment]
I could be missing something, but I'm not even sure I can access the menu. Nothing loads beyond the screenshot above. Is it possible access it somewhere else?

**Comment by luclu** [comment]
You are right on Windows the menu will only show up after passing the splashscreen.
Alternatively you can open the windows explorer and paste `%appdata%\Mist` in the location bar.

Also I noticed that you put into the system info that you used eth instead of geth as the node.
If this is correct, are you running an external instance or the one bundled with Mist, which is currently broken?

(To switch to geth, open the `node` file in the same folder and change `eth` to `geth`.)

**Comment by brstraka** [comment]
Sorry for the confusion - that was an error on my part. I downloaded Mist this morning and this is what came up:

![image](https://cloud.githubusercontent.com/assets/26450578/24045182/950b2d04-0af4-11e7-84e1-dc92dfd829b7.png)

**Comment by evertonfraga** [comment]
Unfortunately this error screen doesn't tell us much. I kindly ask you to send us the log file, as @luclu stated.

You can also try to start a geth instance separately https://github.com/ethereum/go-ethereum

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
