### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by stanfordjesse1** [ethereum/mist#1746]
My apologizes if that has been resolved, but I didn't see the solution and looked through the guide. I have not opened Mist in a few months but I did try updating. See error below:

Node type: geth
Network: mainnet

...I0316 05:42:59.896355   58957 database.go:71] Alloted 433MB cache to /Users/Jesse/Library/Ethereum/chaindata

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

**Comment by stanfordjesse1** [comment]
I downloaded the latest version of Mist. This is the error I am getting now. What else do you need?

Node type: geth
Network: main
Platform: darwin (Architecure x64)

...I0317 02:04:46.513698 ethdb/database.go:83] Allotted 1024MB cache and 1024 file handles to /Users/Jesse/Library/Ethereum/chaindata

**Comment by stanfordjesse1** [comment]
<img width="388" alt="screen shot 2017-03-17 at 2 05 37 am" src="https://cloud.githubusercontent.com/assets/2432185/24030990/50c73e32-0ab6-11e7-89b7-7036bc0ea6aa.png">

**Comment by stanfordjesse1** [comment]
New error now:

I haven't done anything differently. I restarted my computer before getting this error.

Node type: geth
Network: main
Platform: darwin (Architecure x64)

..._upgrade.go:53] Upgrading chain database to use sequential keys
I0317 05:15:29.039843 eth/backend.go:187] Protocol Versions: [63 62], Network Id: 1
I0317 05:15:29.056109 eth/backend.go:215] Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}
E0317 05:15:29.101978 trie/secure_trie.go:74] Unhandled trie error: Missing trie node 100d50cb349fa37e96e0cc34033e78ac302ad6691b92e6ed141763543d9524f9
I0317 05:15:29.104878 core/blockchain.go:219] Last header: #2348245 [3ec2c6a5…] TD=42980460004862578582
I0317 05:15:29.104899 core/blockchain.go:220] Last block: #2348245 [3ec2c6a5…] TD=42980460004862578582
I0317 05:15:29.104909 core/blockchain.go:221] Fast block: #2348245 [3ec2c6a5…] TD=42980460004862578582
I0317 05:15:29.111402 eth/handler.go:119] blockchain not empty, fast sync disabled
I0317 05:15:29.116380 p2p/server.go:340] Starting Server
Fatal: Error starting protocol stack: listen udp :30303: socket: too many open files

**Comment by frozeman** [comment]
@bas-vk what does Fatal: Error starting protocol stack: listen udp :30303: socket: too many open files mean?

**Comment by evertonfraga** [comment]
For future references: 

You can solve it by increasing your file descriptor size, using `ulimit` or other tools.

FYI, here's an extensive list of ways to solve that: http://stackoverflow.com/questions/19981065/nodejs-error-emfile-too-many-open-files-on-mac-os


Closing upon inactivity. Please reopen if needed.
