### ISSUE TITLE
Issue with account creation

### ISSUE THREAD

**Issue by ghost** [ethereum/mist#1747]
Hi. I have installed Etherium Walletall went fine. Now I am trying to create an account but nothing happens. After clicking "Add account" system required to type password and then repeat. Afterwards, window just closes and no actions. What should I do with such issue?

**Comment by luclu** [comment]
Hi @iZozz, there has been a bug up to version `0.8.9` that caused newly created accounts not to show up until after the sync did finish. You can also try to restart the App and look into the keystore folder (`menu -> accounts -> backup -> accounts`).

**Comment by Babwe91** [comment]
I am having the same issue. Tried restarting App and following the steps above but no luck.

**Comment by luclu** [comment]
@Babwe91 are there any files in your keystore folder?

**Comment by DaveL485** [comment]
Same problem here, brand new download and install this morning and wont create a wallet, or sync the blockchain.  No files in keystore.

**Comment by DaveL485** [comment]
Showing error...

Uncaught Error: Unable to connect to socket: timeout(…)

**Comment by luclu** [comment]
@Babwe91 I added the issue template to your last comment, please fill out as much info as possible.

**Comment by Babwe91** [comment]
Originally there were no files in keystone. But after restarting my pc and the app, attempting to create a wallet was successful.

**Comment by evertonfraga** [comment]
Please try with up to date software, as it seems to be fixed.

Should you still encounter the same issue, reopen or create a new one.
