### ISSUE TITLE
My Ether not recived

### ISSUE THREAD

**Issue by JamesKimKR** [ethereum/mist#1748]
Version: `0.8.9`
OS & Version: windows7
Node type: `eth/geth(default)`

If possible add the following to your report:

I am currently using Ethereum MIST 0.8.9.

I sent 40 Ethereum from MIST account into my ethereum market(exchange) Ethereum account.

But I cannot get confirmation from other ethereum market, saying "it does not exist in transaction log". Therefore I am asking you about this.

eth.getTransaction("0x7aceff6dab9928544eb8f8e109ddf389b19654f33758f10b28342ae59a72ab9a")
{
blockHash: "0x22e00d7652997c4d4eaae2c2875eddb5f09a82e0adb8ffdefce8ed8882efdbbc",
blockNumber: 3344571,
from: "0xd4d1774d7c0683b3384c5705249db29e00531804",
gas: 183368,
gasPrice: 20000000000,
hash: "0x7aceff6dab9928544eb8f8e109ddf389b19654f33758f10b28342ae59a72ab9a",
input: "0xb61d27f6000000000000000000000000252f1a00ca448e3fce83b90fbebdb460e4e69bed0000000000000000000000000000000000000000000000022c7fd18a852a0000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
nonce: 2,
r: "0xe59efb73f7b8d911e5416e02ea63f2dd8300e6746d202a65333ab4b13d19febb",
s: "0x7cc2c8d0f1ba3528ae77a72c78b9058f244d0aaa0ea53b656fa2432c24051c50",
to: "0x5b2a91c0ad992426da28e0438dd2bf35afdd2d33",
transactionIndex: 38,
v: "0x26",
value: 0
}
Ethereum market says it is not processed because value is showing 0 like below log.

I wonder whether this is problem of mist, or receiving ethereum market.

and what is the "value" of the transaction log?

**Comment by luclu** [comment]
>  Ethereum market says it is not processed because value is showing 0 like below log.

What do you mean by "Ethereum market"?

https://etherscan.io/address/0xd4d1774d7c0683b3384c5705249db29e00531804 doesn't show anything related to a 40 Ether transaction.

**Comment by JamesKimKR** [comment]
"Ethereum market" is my ethereum exchange webpage like poloneix. ( which is https://www.bithumb.com )

I can confirm 40 Ether transaction like this:
![image](https://cloud.githubusercontent.com/assets/26408414/24024320/dcfe433e-0af5-11e7-8e0f-9d824283ee0b.png)
( This page is https://etherscan.io/address/0xd4d1774d7c0683b3384c5705249db29e00531804 )

TxHash Link: https://etherscan.io/tx/0x7aceff6dab9928544eb8f8e109ddf389b19654f33758f10b28342ae59a72ab9a

**Comment by luclu** [comment]
The 40 Ether were transfered to this account: https://etherscan.io/address/0x252f1a00ca448e3fce83b90fbebdb460e4e69bed.

**Comment by JamesKimKR** [comment]
thanks luclu~

Thanks for giving me a reply.

Can you confirm one more thing?

what is the "value" of the transaction log?

**Comment by luclu** [comment]
> An internal transaction is not a real transaction - it has no signature and is not included in the blockchain. It is the result of a contract initiating a value transfer, or calling another contract, typically using the CALL opcode.

See:
- https://ethereum.stackexchange.com/questions/6429/normal-transactions-vs-internal-transactions-in-etherscan/7366#7366
- https://ethereum.stackexchange.com/questions/8315/confused-by-internal-transactions

**Comment by JamesKimKR** [comment]
1. If the internal transaction is not a real transaction, for what reason is ether missing from my MIST wallet?

2. Recovered(restore?) ether from my wallet? Is there no way to do it?
