### ISSUE TITLE
ether wallet has had a broadcast issue and 49.9 ether disapeared from block 996404

### ISSUE THREAD

**Issue by craigrant** [ethereum/mist#175]
Account 0x381efe236b4f1673ccdfa30d3cd777d4162a0197 (ShapeShift deposit address)

[live.ether.camp shows](https://live.ether.camp/account/381efe236b4f1673ccdfa30d3cd777d4162a0197) 49ETH

[etherscan shows](http://etherscan.io/address/0x381efe236b4f1673ccdfa30d3cd777d4162a0197) 49ETH

[ether chain](https://etherchain.org/account/0x381efe236b4f1673ccdfa30d3cd777d4162a0197) shows account not found

—
~~~~~~~~~~~~~~~
Emily (ShapeShift)
Feb 13, 21:54

Hi, there. It looks like your ether wallet has had a broadcast issue because as you can see there are no funds attached to it on the ether explorer:https://etherchain.org/account/0x381efe236b4f1673ccdfa30d3cd777d4162a0197

You will need to reach out to your wallet provider and tell them what has happened that your funds never made it to the address and show them that above link and they will be able to help you recover your funds.

Have a great day!
	
Craigrant3
Feb 13, 14:35

sent deposit for shift 
http://etherscan.io/tx/0xedecd14c410c39ee05d6e961c4772295316f5c980dca973c073f4d34459f8c19

Shift Status says awaiting deposit
https://shapeshift.io/status.html?depoAddr=0x381efe236b4f1673ccdfa30d3cd777d4162a0197&withAddr=1Hr88YB8ZSgd4EDvrBUhZ2zbYdrE5dTeTB&coinInShort=ETH&coinOutShort=BTC&coinIn=Ether&coinOut=Bitcoin

**Comment by nic-f** [comment]
Hey, I have the same issue. Did you manage to sought it out?

**Comment by luclu** [comment]
Transactions might be delayed if a very low fee was chosen. For now please use the pretty low default fee. https://github.com/ethereum/meteor-dapp-wallet/issues/214

**Comment by luclu** [comment]
@nic-f please create a new issue and fill out the basic information. For now I will delete your post on other ones issues.
