### ISSUE TITLE
was buy Ethererum for 1.5 BITCOINS but the now showing me on my Wallet i dont know why 

### ISSUE THREAD

**Issue by MergimHasani91** [ethereum/mist#1755]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````
here is the Screenshot from my Wallet: http://prntscr.com/ekza8w, see not ETHER arriwd im very afraid ...

here is the Screenshot from the Transfer: https://shapeshift.io/?gclid=CPK5nc_k29ICFcUp0wod6V0KKQ#/status/dd35228e-e135-4f42-808d-551d9f84da90

Please u must help i dont know what to do.. i lost so much Money

**Comment by luclu** [comment]
Please be patient while the wallet is undergoing its inital sync. This can take quite a long time (1-20h). Once finished your balance will show up.

In the meantime you can use http://etherscan.io to check your funds.

I will close this for now, but feel free to ask any questions.
