### ISSUE TITLE
more details about not having my eth where it should be.

### ISSUE THREAD

**Issue by kiakhh** [ethereum/mist#1757]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

![screenshot 2017-03-16 23 04 13](https://cloud.githubusercontent.com/assets/26477986/24033027/205a1f48-0aa8-11e7-8a82-25da032bd8a6.png)
![screenshot 2017-03-17 00 21 18](https://cloud.githubusercontent.com/assets/26477986/24033028/205cab00-0aa8-11e7-9994-3b70250fddce.png)

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
Please follow this advice: https://github.com/ethereum/mist/issues/1755

I will also close this issue for now, but feel free to give heads up and ask any questions.
