### ISSUE TITLE
Ethereum node connection error

### ISSUE THREAD

**Issue by boeckboeck** [ethereum/mist#1758]
Hi,

please see issue below when installing latest version of Mist for Win64.
i've tried on several networks.

![afbeelding](https://cloud.githubusercontent.com/assets/26480055/24036117/7a2b808e-0af8-11e7-8ca1-05a43325f131.png)

![afbeelding](https://cloud.githubusercontent.com/assets/26480055/24036107/71ba7126-0af8-11e7-80c0-aed7b1036653.png)

**Comment by luclu** [comment]
The ethereum node (geth) seems to have crashed. Could you please upload the `node.log` as described [here](https://github.com/ethereum/mist/issues/new)?

**Comment by boeckboeck** [comment]
Hi,

I don't see any menu bar. I unrar, open the Ethereum Wallet.exe file, and then after 30sec of checking network, the error appears. 

Is it to be found with ctrl+alt+i ?
Can you give a more detailed route to the node.log ?

![afbeelding](https://cloud.githubusercontent.com/assets/26480055/24042993/bb963f7a-0b14-11e7-9289-55b2b5c33969.png)

**Comment by luclu** [comment]
You are right, the menu will only show up after passing the splash screen on windows. Please open an explorer and go to `%APPDATA%\Mist` to find the `node.log` files.

**Comment by boeckboeck** [comment]
Also not possible...

![afbeelding](https://cloud.githubusercontent.com/assets/26480055/24043276/3606936c-0b16-11e7-83a0-fa07d94402d5.png)

**Comment by boeckboeck** [comment]
Is it possible the installation is blocked by a firefwall connection?

**Comment by boeckboeck** [comment]
Can I provide information via other ways?
Or are there alternative installation processes?

**Comment by boeckboeck** [comment]
@luclu issue is still on request information :) can you help me out ?

**Comment by boeckboeck** [comment]
solution found : Dell driver was block connection. Uninstalled driver & working.

**Comment by differdange** [comment]
boeckboeck, can you please write me which driver did you uninstall? I have the same problem as you.
Thank you in advance!
