### ISSUE TITLE
No peers, no blocks and no ether showing :(

### ISSUE THREAD

**Issue by Forrest51** [ethereum/mist#1759]
Hi - my ether wallet only ever finds one or two peers and says waiting for blocks. As a result my account is showing a balance of zero, but if i check using etherscan i can see i have ether.

Can anyone help? I am a noob with no coding experience

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
Please make sure that no firewall is blocking the app. For further help:
- fill out the system information
- follow the instructions and upload the log files and 
- create a screenshot of the interface

**Comment by Forrest51** [comment]
Thanks...
1) Checked no firewall is blocking app successfully
2) Filled out system info
3) uploaded log files
4) screen shot done

Hopefully it's an easy fix...

**System information**

Version: Ethereum Wallet 0.8.9
OS & Version: macOS Sierra, 10.12.3
Node type: Geth 1.5.9 (Go)


[Node Log.docx](https://github.com/ethereum/mist/files/850640/Node.Log.docx)

<img width="1262" alt="screen shot 2017-03-17 at 13 18 19" src="https://cloud.githubusercontent.com/assets/26482793/24044686/3e192e2c-0b14-11e7-83d1-41c4d5141c8f.png">
