### ISSUE TITLE
Mist Wallet hardly downloads Blocks

### ISSUE THREAD

**Issue by Ch3i7** [ethereum/mist#1760]
Hi everyone,
I downloaded the Mist Wallet  0.8.9 from here : https://github.com/ethereum/mist/releases
It is syncing but after 1% it stops and is not downloading anymore or extreme slow
it is running on OSX. I´ve an other wallet on the same PC on an Windows Partition an there it works.
Problem is I already bought some ETH not knowing that the Wallet first needs to download all the Block so I need it to download could you help me?

**Comment by evertonfraga** [comment]
Sure. Could you try to delete the `~/Library/Ethereum/chaindata` folder, and open Wallet again? 
This will enforce the use of `geth --fastSync`, which needs to run from a clean database.

⚠️ **Make sure you back up your `keystore` folder, they contain your accounts!**

**Comment by evertonfraga** [comment]
Also tell me two things: 

1) Which version are you using
2) Do you use Solid State or Hard Disk drives on your mac?

**Comment by Ch3i7** [comment]
Thanks for the quick response.
I´m useing SSD Mist Wallet 0.8.9 and geth 1.9.5 
Oh and I don´t have a Ethereum folder in my Library...

**Comment by Ch3i7** [comment]
Yes definitely faster than before thank you very much for the help!

**Comment by Ch3i7** [comment]
It stopped again what now?

**Comment by Ch3i7** [comment]
When i delete the Chaindata it works for a while and then stops downloading (at 40-65%)

**Comment by kvarengi** [comment]
same thing here v0.5.2

**Comment by Ch3i7** [comment]
Know it works. I had to delete the Chaindata several times and after it didn't´t work completely i restarted the wallet a few times after that it suddenly worked.

**Comment by luclu** [comment]
I will close this as resolved.

Note that the next version fixes an ugly issue and should resolve the sync issues of many users.

@kvarengi please update to the latest version `0.8.9`.

**Comment by victorengel** [comment]
I'm seeing the same thing. I recently downloaded latest 0.8.9. How to I see the geth version? My first attempt to sync resulted in a stall without about 200 blocks to go. I followed the steps here, and although it's going now as I type, it sometimes seems to stall for long periods of time. What's actually going on when this happens?
