### ISSUE TITLE
Sent Ether not showing up in wallet

### ISSUE THREAD

**Issue by gibesa** [ethereum/mist#1762]
#### System information
``````
Version: 0.8.9
OS & Version: Windows 10 Home, Version 1511
Node type: Geth 1.5.9 (Go)

[node.log.zip](https://github.com/ethereum/mist/files/850846/node.log.zip)

``````

Hi. I'm new to the cryptocurrency market and seem to have lost my Ether.

As you can see in these first two screenshots, I successfully transferred 6.17403263 Ether to address 0x2b916a6455ABe83D03d7310f405C8641B368a306.  

![capture 4](https://cloud.githubusercontent.com/assets/26486356/24048468/64d4dbc0-0aff-11e7-8f23-c0e50e6f707c.PNG)
![capture 1](https://cloud.githubusercontent.com/assets/26486356/24048054/0915e1d6-0afe-11e7-9554-d59447b68ea3.PNG)

However, the Ether is not showing up in that account in my Ethereum Wallet:

![capture 3](https://cloud.githubusercontent.com/assets/26486356/24048056/0916bdcc-0afe-11e7-9235-ee98efd8b7d1.PNG)

(I have also attached the node.log as requested.)

Either I have missed a step in this process, or something is not working right.  Can you please help me out or point me in the right direction to get help?

Thank you!!!

Gibesa

**Comment by gibesa** [comment]
Hello.  Is anybody there?  Please respond.

**Comment by garretlaxton** [comment]
Have you let your wallet fully sync?

**Comment by gibesa** [comment]
I think so.  I have reloaded it several times since Friday.

**Comment by garretlaxton** [comment]
I'm sure a developer will respond to us all tomorrow on Monday, but make sure you backup your account

**Comment by gibesa** [comment]
This might help... got some errors when loading my wallet...

![capture_5_-_console](https://cloud.githubusercontent.com/assets/26486356/24089373/72882614-0d0c-11e7-9d97-b8a75525e4e1.png)

**Comment by Anna-Marthe** [comment]
I'm experiencing the same issue. I successfully made a transaction to my wallet, and it's not showing up. 
<img width="933" alt="screen shot 2017-03-20 at 16 05 06" src="https://cloud.githubusercontent.com/assets/5310896/24092079/055f107c-0d87-11e7-86b7-219ff4e941ba.png">

System info:
MacOSSierra 10.12.3

**Comment by Theoneb** [comment]
Same Problem here....Two transactions (shapeshift/anycoin) are not showing up

**Comment by keysersoze1977** [comment]
I have the same issue.  Transfered from bitpanda on friday but nothing showing in wallet.  what now?

**Comment by mohammad1899** [comment]
I have this problem too. please help!

**Comment by keysersoze1977** [comment]
Use mist instead of wallet.  Works!

**Comment by mohammad1899** [comment]
I'm still having problems

**Comment by gibesa** [comment]
This is ridiculous.  Day 11, and still no ether in my account.  For all I know, this whole thing is a big racket.
I guess I'm just supposed to kiss my ether goodbye and tag this loss as "tuition paid and lesson learned."
Thanks to all of you for your support.  Too bad we didn't get an answer.

**Comment by lujke324** [comment]
I have had the same issue after shapeshifting BTC from Coinbase to ETH in my Ethereum Wallet. Considering the many promising applications in store for ethereum it is disheartening to find that so many have trouble with the local wallet.

**Comment by luclu** [comment]
Hi, some generic advice, please make sure you are running the [latest version](https://github.com/ethereum/mist/releases) and your node is **fully** synced.
Although this may take between 1h (SSD) and 10 hours (HDD) you should be able to see a progress bar on the *splash-screen* or in the *main-window*.

Some recommendations: 
- check your account's balance using http://etherscan.io
- make a backup of all account's keyfiles via `menu -> accounts -> backup -> accounts`
- should the initial sync take very long, consider following [these instructions](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569) to speed it up
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com in the meantime

If this didn't solve your issue, please follow [these instructions](https://github.com/ethereum/mist/issues/new) and upload the `node.log` files:
> - Log files
>   - go to menu -> accounts -> backup -> application data
>   - zip and upload node.log and all other node.log.X files

**Comment by DustinWehr** [comment]
@gibesa did you get it figured out? I was in the same position, and have just transferred my balance to a myetherwallet.com wallet.

**Comment by Raisyz** [comment]
I can't get this wallet to fully sync.  Have tried 5 times.  Currently it is at 99% which took over 24 hours.  It keeps showing blocks between 95-150 and goes up and down in blocks left to sync.  Just checked it again and it has STARTED ALL OVER AGAIN syncing from the very beginning.  What is up with this wallet?  It has to be the worst wallet of all crypto.
It never showed the ether I sent to it 4 days ago though etherscan shows it as in the wallet.  Please help.  I have the latest version of the Mist wallet

**Comment by Raisyz** [comment]
Please help with this wallet it will not sync.  I've tried 5 times.  This last time it got to 99% and then started over from the beginning for no reason.

**Comment by rube08** [comment]
@gibesa I think you can fully access your ether. Do you need the help.  I can show you step by step.  Did you backup your wallet in Mist?

**Comment by gibesa** [comment]
Hi rube08!  Yes, I still need help with this.  No, I did not back up my
wallet... this was my first (& only) transaction... there was nothing to
back up.  Please send me the steps.  Thank you!



*Asante!*

*G**ina* *G**rubb      *

**Comment by Raisyz** [comment]
@gibesa I have a copy of the keystore.  I never backed up the wallet any other way because it never would sync.  I just want to move that ether to my other wallet but I do not know how to access it

**Comment by rube08** [comment]
@gibesa  Try these steps if you have your keystore wallet.
[ether wallet instructions.docx](https://github.com/ethereum/mist/files/1066208/ether.wallet.instructions.docx)

**Comment by Raisyz** [comment]
@gibesa   Thank YOU and @rube08.  I have my ether transferred to my other wallet

**Comment by Theoneb** [comment]
So yesterday I tried to sync. Nothing worked. Im tired of this. Is there any possibility to get my Ether somehow? 
I read the Thread, but I'm not really into this stuff so I didn't get exaclty what to do. 
Actually I just created an etherwallet on myetherwallet.com
Can I get my ether from the Ether Wallet Desktop application on myetherwallet.com (or is it maybe the same)?
Is it possible to send my Ether from the Desktop Application Wallet to another wallet although it never synced? 
I got a new Laptop, can I transfer my Ether Wallet (Desktop Application) from my old Laptop to the new one, cause I think the sync will work there?
Help would be nice.

I'm really annoyed and don't understand why there is so much trouble with this sh... you know what I mean.
Its peoples money we are talking about. I am mad.

**Comment by Theoneb** [comment]
These are my node files. Hope it works.

I just tried gibesas transfer tut. but I forgot my Password. Can I restore it?

**Comment by Theoneb** [comment]
[node.zip](https://github.com/ethereum/mist/files/1107751/node.zip)

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Comment by Theoneb** [comment]
So how do I restore my Account if I download it?

**Comment by Theoneb** [comment]
I am sorry that was a dumbass question cuz you told us how to do it.

Another question, I have a new Laptop, is it possible to restore the Account? I have all the transaction data and account data if needed.

**Comment by evertonfraga** [comment]
@Theoneb copy your keystore files (`Account > Backup > Accounts...`) over to your new computer.

**Comment by great999** [comment]
this must be the worst wallet ever! 
they have tons of money and beta version for ethereum wallet! 
greedy and lazy!

**Comment by voltmoe** [comment]
I'm in the same boat. Etherscan says it's in, funds gone from the original location, and I got nothing in Parity.. Nodes always get stuck....
