### ISSUE TITLE
Sync very slow, has worked once but no ether transferred

### ISSUE THREAD

**Issue by mountbr1** [ethereum/mist#1763]
#### System information
``````
Version: `0.8.9`
OS El captain
Node type: `eth/geth(default)`
``````
First time use of wallet, sync very slow, usually just hangs on one block, has worked once but no ether transferred.  i have deleted the chain data folder and this did help a lot.  sometimes is works for about 20% but then it actually gains blocks!
#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by Ch3i7** [comment]
Hey, same Problem here tried to start fast geth but could find any geth files in Contents.
By the way I´m running my Wallet on a MAC with OSX.

**Comment by mountbr1** [comment]
Hi,

no progress still stuck, am using a mac with OSX as well  

you should be able to find the chainmail folder under library.  I deleted this any it speeded the whole process up but still did not work

**Comment by Ch3i7** [comment]
Isn´t there an option to download the Chaindata separate  and integrate it in the Programm later?

**Comment by Ch3i7** [comment]
I bought an Ledger Nano S anyway but at the moment i would still like it to work

**Comment by mountbr1** [comment]
i got 80% of the way and it reset to 20%!

Excuse my ignorance but what is a Ledger Nano S.  i am willing to try anything at this stage!

**Comment by Ch3i7** [comment]
It is a Stick where you can Transfer your Bitcoin Ethereum and other Cryptos to it cost approximately 70$ and you do not have to download any Chaindatas the Wallet is still on Your PC it works in addition to it.

**Comment by mountbr1** [comment]
thanks

so it is not a work around i.e. you still have to synch to get it to work,

**Comment by Ch3i7** [comment]
Well, you don´t have to download anything as far as i know (except the Wallet itself) but you have to sync like any wallet

**Comment by Ch3i7** [comment]
Did you already buy any Coins on your Wallet?

**Comment by Ch3i7** [comment]
Oh my god 90 % so close

**Comment by Ch3i7** [comment]
It finished

**Comment by mountbr1** [comment]
I’m jealous!

I got to 86% and it went back to 24% for some reason

**Comment by Ch3i7** [comment]
I think in my case it downloaded so because of the Avast Ativirus Software

**Comment by mountbr1** [comment]
Hi,

i also have AVAST antivirus.

I just noticed today that it showed that it blocked an infection to my etheream wallet  during download so i am thinking of turning it off.

**Comment by Ch3i7** [comment]
Does it work now without Avast?

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
