### ISSUE TITLE
Disappearing Wallet Contract

### ISSUE THREAD

**Issue by Mbembem** [ethereum/mist#1765]
``````
Version: `0.8.9`
OS & Version: OSX 10.11.6
Node type: `eth/geth(default)`
``````

Let me pre-apologize if this is redundant. I did not find anything exactly characterizing this series of events...

In July '16, I traded for 86 Ether, and moved them to a Wallet Contract in the Ethereum client. In January '17 I went to access it, but as I waited for the chain to sync the wallet contract and its transaction record were greyed out and inaccessible (see below). After updating to a post-fork client, the contract wallet and transaction record no longer even appeared. Etherscan shows that the contract still exists with all its contents. I still have the UTC keys from July, but it is unclear to me how to import the contract into the client or an account. I am guessing this is related to the fork?? How to proceed?

![screen shot 2017-03-18 at 12 24 54 am](https://cloud.githubusercontent.com/assets/26493942/24068957/166b02a2-0b72-11e7-929e-abdabbbbae9f.png)

**Comment by evertonfraga** [comment]
For future reference, if you know the account that created the contract first place, you can head to a blockchain explorer like https://etherscan.io/, search using your account address, and it'll show all contracts created by the account.

By knowing the address, you can put that contract back into mist heading to Watch Contract, putting both the address and ABI json interface.
