### ISSUE TITLE
Can't broadcast transactions from Ethereum Wallet, UI feedback very scarce about this

### ISSUE THREAD

**Issue by leafcutterant** [ethereum/mist#1769]
#### System information
``````
Version:
   Geth: `1.5.9`
   Ethereum Wallet: `0.8.9`
OS & Version: windows 7 x64
Node type: `geth(default)`
Client mode: `lightclient`
``````

#### Problem description
Ethereum Wallet can't broadcast my transactions. I'm having a stable (4-5 peers) and low-latency connection to the network via the light-client protocol. I'm up-to-date. I'm sending from an address with sufficient funds, with sufficient fees included. Password approved, then the tx shows up at the bottom, grayed out. It stays there for 5-10 minutes with 0 confirmations. During this time, the transaction doesn't get included even in the tx pool (checked via block explorers). After this, it just disappears from the client. Once I got a yellow pop-up in the corner that the transaction can't be executed. Maybe it was displayed every time and I missed it.

No log files found at the location where the issue template suggested (maybe because it's Ethereum Wallet, not Mist). The Geth command-line window acknowledges that a transaction had been sent, but nothing else (not even about the failing of the transaction/tx broadcast).

**Comment by leafcutterant** [comment]
Tried the same with Mist; same result. Also no log files found here.

**Comment by luclu** [comment]
@leafcutterant the lightclient mode is not reliable ATM. Please refrain from using it for production purpose for now.
