### ISSUE TITLE
Lost transacton in test net...

### ISSUE THREAD

**Issue by Bubleek** [ethereum/mist#177]
Yesterday I made a transaction at an address known to me. The transaction took place and received over 6 confirmations. Today, this transaction is no longer in the list of committed transactions. Esters have not reached to the destenation address, but they already going out from my address. Link to the transaction: http://testnet.etherscan.io/tx/0x80ecde140c6f0d1419db4ae71db1f9aa7f43be24feaab332f85ac6d516e846f2
Image source also attached.
![ethereum lost tx](https://cloud.githubusercontent.com/assets/13541942/13050377/09cc2aea-d404-11e5-8f2a-d7c92fa6562a.jpg)

**Comment by Bubleek** [comment]
Excellent! Now we have two of the same account in the test network and the global. I want send 150 ethers to account of the global network, but sent it to the test network. What do we do?
Screen1: https://yadi.sk/i/bcZe0E1Zp2pe2
Screen2: https://yadi.sk/i/cVD_v4N1p2phf

**Comment by frozeman** [comment]
I don't understand the problem. You can;t send ether from the testnet to the main net.

**Comment by Bubleek** [comment]
Yes' i can't send ether from testnet to mainnet. And now we have 2 same acc in testnet and mainnet. Is it possible? Is it not a bug?

**Comment by alexvandesande** [comment]
Are you using mist? Sometimes Mist takes a longer time to realize you switched networks and hide  your other accounts

**Comment by Bubleek** [comment]
Yes, i'm using mist with geth. Now i'm talking about 2 acc. See screebs from links:
Screen1: https://yadi.sk/i/bcZe0E1Zp2pe2
Screen2: https://yadi.sk/i/cVD_v4N1p2phf
This screens from ethereum blockchain for mainnet and for testnet. It look like big bug! 2 same acc in different nets.
And ofcourse i don't understand why i can't send ether from testnet to mainnet? I just want try how senders algoritms works and got zero result(transactions not working correctly).

**Comment by alexvandesande** [comment]
What I guess happened here: you sent a transaction from one network and then switched to the other. Mist took longer than it should to update the on screen information allowing you to send a transaction from the same account. If you open mist now, does it still show the account? If you switch networks, for how long does it still shows it?

**Comment by Bubleek** [comment]
When i open mist it show me last opened account(when i close mist in testnet acc it show me testnet acc and when i close mist in mainnet acc it show me mainnet acc)
When i start swithing networks i still see on the screen last opened account while sincrhonisation don't over.
So this time to swithing accounts depends from many factor:
1. How many blocks mined in net where you want to swith.
2. What you internet speed(to download blocks).
3. What speed you hdd or ssd to update blockchain files.
And may be more factors.
But when i push button to swith from one account to other acc i loose control and can't do nothing. I'm should wait when synchronization over. While i wait i see on the screen last opened account.

**Comment by frozeman** [comment]
I guess this is more, that the wallet internally gets bombarded with new blocks requests and this keeps the interface frozen for a while, so it can't change the accounts. I guess thats the case here. But i still didn't understood your first problem.

**Comment by frozeman** [comment]
You can have two accounts with the same address imported, yes thats possible

**Comment by Bubleek** [comment]
@frozeman So, ok, understand i can have many acc and i have 2 acc(0xc2a2c4df47a4fef4a023139fb570d42ebbcf3512 in mainnet and 0x2f4af484604ad062debd5c23ffa88e01953bb335 in testnet). About first problem:
I'm send ethers from 0x2f4af484604ad062debd5c23ffa88e01953bb335 to 0xc2a2c4df47a4fef4a023139fb570d42ebbcf3512(in main net) and this ethers still don't reached to the destenation address. Where this ethers stored now? Ansver: This ethers stored in 0xc2a2c4df47a4fef4a023139fb570d42ebbcf3512(in testnet).
But now i know we have one more plus acc in testnet, this acc is 0xc2a2c4df47a4fef4a023139fb570d42ebbcf3512(in testnet) and i never createв this and this is not my acc. How it possible two acc in different net with one adress? How i can understand now which one acc   get ethers in next time(when i do next tx to 0xc2a2c4df47a4fef4a023139fb570d42ebbcf3512)?
Understand? Or maybe i do something wrong?

**Comment by alexvandesande** [comment]
I'm sorry I have a hard time understanding what's happening. Look, ignore the testnet thing, here's my recommendation: backup your keystone folder, remove everything else and reinstall mist, it seems it's a big mess there now..

**Comment by alexvandesande** [comment]
> I'm send ethers from 0x2f4af484604ad062debd5c23ffa88e01953bb335 to 0xc2a2c4df47a4fef4a023139fb570d42ebbcf3512(in main net) and this ethers still don't reached to the destenation address(Ok, understand this is not possible). Where this ethers stored now? Ansver: This ethers stored in 0xc2a2c4df47a4fef4a023139fb570d42ebbcf3512(in testnet).

So you are sending ether from account `0x2f` and the ether haven't reached the destination. You are asking if it's possible they are stored on the main net? No, it's not. Have they arrived now in `0xc2`? 

You have an issue with sending transactions and whatever you are telling about the testnet is just confusing everything, ignore the testnet.

**Comment by Bubleek** [comment]
@alexvandesande Thanks for you advice. I'll wait @frozeman answer. Maybe he understand what happen with my accounts. And i understand the ethers from testnet can't be send to main net. I don't want ignore testnet becouse i just want try how it working(sending, contracts and more functions). Now i don't understend why etheres sended from 0x2f4af don't returned back to 0x2f4af inside testnet?

**Comment by frozeman** [comment]
If you send ether to an address and you provide enough gas, then they ARE on the address you send it to.

If you send from  0x2f4af48460 to 0xc2a2c4d, then the ethers are on 0xc2a2c4d on the main net.

If you have the private key for this account on the testnet, than simply copy the keystore file from the `%APPDATA%/Romaing/Etheruem/testnet/keystore` to `%APPDATA%/Romaing/Etheruem/keystore` 

BTW this account seems to have money on the main net, so it arrived: http://etherscan.io/address/0xc2a2c4df47a4fef4a023139fb570d42ebbcf3512

I'm closing this, as this is not really an issue, but more of an understanding problem on your side.

I hope my explanation help you to clarify it a bit.

**Comment by Bubleek** [comment]
@frozeman Thanks for you help! 
My problem still don't solved. I don't have private key for 0xc2a2c4d on the test net and i don't create this acc in testnet. I'm create acc 0xc2a2c4d in main net and this acc is same as in test net . Nobody don't want understand it...
Ofcourse my acc 0xc2a2c4d in main net have some ethers becouse i'm use my acc as i want.
But i still lost my trabsaction becouse my mist app don't show me this transaction  more http://testnet.etherscan.io/tx/0x80ecde140c6f0d1419db4ae71db1f9aa7f43be24feaab332f85ac6d516e846f2 Maybe i make mistake when i do this transaction but it still lost...
Ok. This story now closed. 
Thanks for help to all!

**Comment by frozeman** [comment]
You definitely lost nothing expect you send it to an address you don't control.

Though when you have keys in the testnet, you can copy them to use them on the main net as well, as i described above ( simply copy the keystore file from the `%APPDATA%/Romaing/Etheruem/testnet/keystore` to `%APPDATA%/Romaing/Etheruem/keystore`)

I really don't understand you problem.

**Comment by Bubleek** [comment]
@frozeman Ok. If you don't understand may be this is problem with my english? But i want to tell you simpe story about my problem but in another area. This story just for example:
I went to the bank to transfer the money to the account №123456789. When I sent the money to this account, it was found that this account have two people, one of them whom I sent the money, and another owner of the same account number, I do not know. After a while, he got in touch with me, to whom I sent the money, and said that he did not get anything. Then I called the bank and asked where they transferred the money that I sent? In response, the bank sent me a receipt that says that money has been successfully transferred to the account №123456789. But the truth is that the one to whom I would like to transfer money because they never received.
Do you understand this story?

**Comment by frozeman** [comment]
The account number is derived from the private key. If you have the private key for the account, you have the access to this account. No matter on which network you are!
But

1. you shouldn't use the same account in two different networks (as you can't send money across!)
2. if you send money to this account, simply import the account in the other network and send it back

**Comment by Bubleek** [comment]
@frozeman Thanks! I'll try copy my keystore file from main net to test net and get control to acc 0xc2a2c4d in test net then send ethers back to my acc in test net.

**Comment by Bubleek** [comment]
I'm try to do copy my keystore from main net to test net and now i finally send ethers from 0xc2a2c4d(test net) to 0x2f4af48460(in same test net). Transfer now fully completed! Thanks for all!

**Comment by AlphaQUp717** [comment]
Bubleek how did you copy and past the key store if main net and test net seem to be the same keys... reason, why I ask, is because I am having the same issue. I can mine but I can't send the ETH I received from mining to any other ETH accounts and or any exchange. It would be a really big help to get some feedback.

**Comment by Bubleek** [comment]
I'm just copy key store from one folder to other folder as as frozeman says:
"If you have the private key for this account on the testnet, than simply copy the keystore file from the %APPDATA%/Romaing/Etheruem/testnet/keystore to %APPDATA%/Romaing/Etheruem/keystore
"
So and don't forget you can't send nothing from a test net to main network. All exchangers and all trading markets working with main net. And you should create you transactions to this markets only from main net!  And of course you wallet should be already synchronized with main net.
