### ISSUE TITLE
Sent ETH haven't recieved & taking forever to sync.. HELP Now "Ethereum node connection error"

### ISSUE THREAD

**Issue by garretlaxton** [ethereum/mist#1770]
So I sent ETH to my wallet yesterday at 4pm & haven't gotten it.. I thought I sent it to a wrong address or something but the ETH blockchain says it's in my wallet.. https://etherscan.io/address/0x0eaac528770cfeeabbc835ac654903334ffe65c4 I did some searching to see I have to sync my wallet before it shows in their? I'm guessing the blocks left is how long till sync is complete? This has been taking forever.. I have to keep closing and reopening to only get a thousand or so blocks before it stops & been doing this for almost 12 hours only got about 300k blocks & 2.7 million more to go... Wish I known this before I sent my ETH to my wallet.. This is gonna take another like 2 days of opening & closing just to see my ETH... wtf

**Comment by cdian** [comment]
Same issue here. Sent ETH and nothing on my wallet. Version 0.8.9.

**Comment by moerphay** [comment]
I have the same issue. My wallet does not sync and the transaction is not being verified.

**Comment by garretlaxton** [comment]
Now I'm getting "Ethereum node connection error"when I try opening..

**Comment by garretlaxton** [comment]
Okay I've somewhat fixed my problem.. First thing I did was backup my wallet, then I uninstalled/reinstalled the app and imported my wallet. It's downloading blocks much faster and I don't have to keep restarting the application, blocks stay syncing.. I'm at 40% and started about a hour ago, so now I'm just waiting on the syncing to complete. If anyone else is having trouble like me try and reinstall the app, BUT MAKE SURE YOU BACKUP YOUR WALLET FIRST BEFORE UNINSTALLING!!!

**Comment by garretlaxton** [comment]
Yasssssssss
[img]http://i.imgur.com/fOyFTzQ.png[/img]

**Comment by garretlaxton** [comment]
IT WORKED!! Got my ETH!
