### ISSUE TITLE
Wallet will not sync.

### ISSUE THREAD

**Issue by keysersoze1977** [ethereum/mist#1776]
#### System information
``````
Version: `0.0.0`
OS & Version: windows 64bit
Node type: `eth/geth(default)`
Latest wallet from ethereum.org installed
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files 

I have turned firewall off.  Does not want to sync and eth not arrived.  transaction completed by bitpanda on friday.  Its just stuck on 0%

What else can I try?

**Comment by keysersoze1977** [comment]
seems to be working after installing mist.

**Comment by wizzsleeve** [comment]
1 | 2
-- | --
0
        down vote | I have been trying for a week now with the same issues. Uninstalling 
,reinstalling, deleting blockchain over and over for the testnet.Main 
network would never download.
Used geth --fast and it told me my time was out by 57.something seconds.
 I had tried gist.gov and Microsoft time over and over. When i went in 
and changed the clock manually by around 57 secs, the blocks started 
pouring in.
I believe yours and everyone else's problem is the timing sync not the 
wallet software or config.
Try geth --fast and see what your response is in regard to the time 
warning. I would bet its the same as my issue.

A week people, but i persevered,tried every possible combination of 
answers here but it was the clock all along. Good luck everyone. Hope 
this helped.
