### ISSUE TITLE
Only 80 blocks to sync but can't never really get there before block #s increase again

### ISSUE THREAD

**Issue by DavDub** [ethereum/mist#1785]
``````
Mist Version: `0.8.9`
Geth 1.5.9
OSX Sierra 10.12.3 
Node type: unsure
``````

It took 5 days to go through most of the wallet sync.   Now there is between 75 and 148 blocks left.  Although it seems like blocks are being synced, I can never quite complete the sync.  Please help, I don't want to resync the whole thing from scratch if I don't have to.

FYI:  Peers are fluctuating between 5 and 25
Node File looks ok (no errors that I can see)

Also two errors in UI /sources:

1.Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError
2.Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by DavDub** [comment]
Also two errors in UI /sources:

1.Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError
2.Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097

**Comment by Cobbs95** [comment]
I have downloaded Mist v 0.9.2 with Geth 17.2 and on both OS and Windows it reaches around 100 blocks left to sync then doesn't move and never syncs??

I have tried deleting chaindata and going to light client but same issue happens.
Really need to send some Eth to and exchange but cant access any....
so far I believe I have done everything all the Github chat rooms have said but it always gets stuck on the last 100 blocks....

Look forward to some help!
Cheers,
SC

**Comment by brainyclown10** [comment]
I'm having the same issue on Mist v0.9.3 with Geth 1.7.2, and I'm stuck at 128 blocks left, with 25 peers. I'll give it until tonight to see if I can make any progress, but when I enable light client, I get 0 peers, waiting for blocks. I'm using macOS Sierra 10.12.6. Any help would be appreciated. Thanks!

**Comment by ethbugs** [comment]
Yep, light client never finds enough peers to sync properly.  Fast sync stops 100-2-- blocks before the end and chain structure download infinitely way past the number of blocks.

**Comment by evertonfraga** [comment]
Hi @ethbugs, actually the sync doesn't "stop". 

While `fast` sync reaches 100-200 blocks behind, it downloads the state entries. Currently, there are over 70M of state entries to be downloaded. Please be patient.

If you need better reporting, please start `geth` manually and follow "Imported xxx state entries".

See https://github.com/ethereum/mist/issues/3097 for more information.
