### ISSUE TITLE
Multilingual Support

### ISSUE THREAD

**Issue by GoopyAspirin** [ethereum/mist#1786]
You also need to develop a set of languages ​​that support multiple languages.

I can contribute to multilingual (language).

Korean, English, Chinese and Japanese.

**Comment by luclu** [comment]
Hi @GoopyAspirin, thank you for your offer, it's very welcome!

Please have a look at the corresponding files:
- https://github.com/ethereum/mist/tree/develop/interface/i18n
- https://github.com/ethereum/meteor-dapp-wallet/tree/develop/app/i18n

Note that there are several issues that might prevent the translation from being applied: https://github.com/ethereum/mist/issues/1735. 
I will try to fix them for the `0.8.10` release.
