### ISSUE TITLE
Sent eth to account instead of Wallet

### ISSUE THREAD

**Issue by Xiribi** [ethereum/mist#1789]
Hello,
I made a transfer of eth to my account but used to account number instead of the "wallet contract" number.
Later on I saw that I had to make a Wallet and that the account did not show transactions...
Problem is also that I cannot create a wallet because there are no funds in it.
Anyone knows where it is?
Transactions does show in Etherscan so it is OK

**Comment by garretlaxton** [comment]
You don't need to create a contract to receive funds in the wallet, you just have to let your wallet fully sync in order to see your ETH. It can take up to 1 to 20 hours for your wallet to sync.

**Comment by Xiribi** [comment]
Thank you for the info!

**Comment by luclu** [comment]
@Xiribi were you able to solve your issue?
