### ISSUE TITLE
From Bitcoin to Etherum 

### ISSUE THREAD

**Issue by olayinkasola** [ethereum/mist#1797]
Hi
I installed my mist for Etherum yesterday and I transferred from Bitcoin into it since yesterday night. The transaction was confirmed and bitcoin deducted from my bitcoin account but till now i can find the fund in mist etherum wallet, Can somebody assist, please.

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by petertrain** [comment]
Hi,
I suspect this is the wrong forum for your request.
How did you transfer from your bitcoin wallet to your ETH  wallet?
To do this, I presume you need to find someone who is prepared to trade bitcoin for ETH, transfer the bitcoin to them and rely on them to transfer the ETH to you.
Did you use an exchange to do this?  If so, post an issue to the exchange to help you resolve.
Perhaps there is a bitcoin wallet that I am not aware of that does all of this transparently?  If so, I would post the question to a forum relating to that wallet.

If you were not aware that you needed to use an exchange, perhaps you have actually done a bitcoin to bitcoin payment.  However this would surprise me as I would have thought your bitcoin wallet wouldn't have recognosed your ETH address as valid.  Perhaps you could try to verify this by checking https://blockchain.info/address/[your eth address].  You would probably need to change the way your eth address is encoded / formatted to be recognised as a valid bitcoin address by blockchain.info.  if this is what has happened, I don't know if there is a way to recover your funds.  You would need to investigate whether something could be done by importing your eth private key into a bitcoin wallet.

**Comment by petertrain** [comment]
Assuming you did a bitcoin payment using the Ethereum address:
My curiosity was peeked and I tried to make a bitcoin payment to an Ethereum address.  blockchain.info does indeed accept an Ethereum address as valid - it treats the Ethereum address as a different encoding of the address, but accepts it.  I put in one of my ETH addresses without the "0x" at the beginning and blochain.info accepted it (obviously showing a 0 balance).  Also note that the ethereum address corresponds to the hash 160 field presented by blockchain.info and not the address field.  After this, I transferred a small amount of bitcoin to this address and see that the transaction succeeded and blockchain.info shows a balance against that address.

I have no idea how you would recover those funds - or if it would indeed be possible.  I am aware that both bitcoin and Ethereum start off with a random 256 bit private key.  I think they both use the same ECC algorithm to derive a public key relating to that private key.  At this stage, I think there is a different process for deriving an address from the public key.   Bitcoin involves use of SHA256 hash and Ethereum involves use of Keccak-256 hash.  My guess is that the addresses have a similar structure, but relate back to the private key in a different way.

If this is what happened, I hope you find a way to recover your bitcoin and if not, I hope it was not a significant amount that you lost.

**Comment by olayinkasola** [comment]
I used Mist, and I read it there that i can fund my Etherum with Bitcoins and as i did it it generated a bitcoin address 18aWhq3WhXTJEntVp9eUdMyZExYBKMtWTY  . I was told it will convert it to etherum .



Kind regards,

Adesola A Olayinka
sola@bytesconsults.com<mailto:sola@bytesconsults.com|www.bytesconsults.com>|www.bytesconsults.com|


IN GOD WE TRUST

________________________________

**Comment by petertrain** [comment]
Okay.  I wasn't aware that Mist wallet had this capability.  Google search indicates that ShapeShift offers a service like this integrated into Mist wallet.

I would start by checking the balance for your ETH address on https://etherchain.org/account/[your eth address].  If you see your ETH there, then there is a problem with your Mist wallet (perhaps the blockchain hasn't finished synchronising yet?  

If etherchain doesn't reflect the funds, you should probably take this up with ShapeShift (or whoever offers the service that you used).

**Comment by evertonfraga** [comment]
Thanks for your answer @petertrain. And for the sake of precision, there's a CoinBase widget inside mist, that does the operation, instead of shapeshift.

**Comment by olayinkasola** [comment]
Must I talk to CoinBase then, I still have not received the transferred $90. can someone assist with correct contact for such, please.


Kind regards,

Adesola A Olayinka
sola@bytesconsults.com<mailto:sola@bytesconsults.com|www.bytesconsults.com>|www.bytesconsults.com|


IN GOD WE TRUST

________________________________

**Comment by scottcox975** [comment]
I bought bitcoins from liviacoins.com best service I have ever seen, super fast and low charges!

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Comment by rubyw6602** [comment]
I trade (that is, buy and sell bitcoins) anonymously from liviacoins.com My last trade with LiviaCoins was completed in 30 minutes.
