### ISSUE TITLE
I used Mist, and I read it there that i can fund my Etherum with Bitcoins and as i did it it generated a bitcoin address 18aWhq3WhXTJEntVp9eUdMyZExYBKMtWTY  . I was told it will convert it to etherum . Since yesterday till now my wallet has not shown any etherum.

### ISSUE THREAD

**Issue by olayinkasola** [ethereum/mist#1801]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by olayinkasola** [comment]
Can someone tell me how to backup etherum account, please

**Comment by evertonfraga** [comment]
Having Mist opened, you can go to `Accounts > Backup > Accounts`, then you copy those files to a safe place.

**Comment by olayinkasola** [comment]
Thanks. Done.

**Comment by olayinkasola** [comment]
I used Mist, and I read it there that i can fund my Etherum with Bitcoins and as i did it it generated a bitcoin address 18aWhq3WhXTJEntVp9eUdMyZExYBKMtWTY . I was told it will convert it to etherum . Since yesterday till now my wallet has not shown any etherum.

**Comment by olayinkasola** [comment]
Thanks Guys, i saw it online @ etherscan.oi but am working on how to link it to mist. any idea, please.

**Comment by olayinkasola** [comment]
Can someone lead me on how to unlook my account, please. I have an account when I installed mist but never function. I transferred to the account and I can only see the money on etherscan never show on the mist

**Comment by garretlaxton** [comment]
You need to let your wallet sync before you can see your ETH

**Comment by olayinkasola** [comment]
How do I go about account synchronization, please.

Adesola A. Olayinka
sola@bytesconsults.com
+27 610640200

On Mar 30, 2017 13:36, garretlaxton <notifications@github.com> wrote:

You need to let your wallet sync before you can see your ETH

**Comment by garretlaxton** [comment]
Try watching this video https://youtu.be/wXmRdnyKKqg

**Comment by olayinkasola** [comment]
Thanks, solved
