### ISSUE TITLE
Ethereum-Wallet-win64-0-4-0.zip contains duplicate files in the archive and is double the size

### ISSUE THREAD

**Issue by xcgabriel** [ethereum/mist#181]
Looking inside the official 0.4.0 windows archive I see that each file is duplicated. So the achive is twice the size and you get a warning during unpacking since it want to overwrite existing files.

**Comment by housemobile** [comment]
This.

http://s17.postimg.org/50eujcwnz/mist.png

**Comment by frozeman** [comment]
haha, i already wondered why it was twice as large. i upload a new one
