### ISSUE TITLE
Mist splash screen ("Starting Ethereum node...") remains frozen on Mac

### ISSUE THREAD

**Issue by voikol** [ethereum/mist#184]
Issue could be a dependency with Geth that has already been fixed but was not merged due to homestead changes

**Comment by ddsjangster** [comment]
i have the same problem. what to do?

**Comment by hiddentao** [comment]
I got a geth error message too.

**Comment by hiddentao** [comment]
I fixed my issue by installing ethereum via homebrew - https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Mac

**Comment by frozeman** [comment]
The best is to provide the log files, which you can find in the Menu -> backup -> app data -> all *.log files

**Comment by flexliv** [comment]
same here, osx el capitan. Geth wont start:
node.log :
dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth
  Reason: image not found

**Comment by frozeman** [comment]
@flexliv you issue is #163

**Comment by flexliv** [comment]
ok so what is the solution? I looked in #163 but you say that is also a duplicate.

**Comment by ddsjangster** [comment]
maybe we wait for Ethereum to release the next Beta update?

**Comment by frozeman** [comment]
The gmp issue is already fixed in geth#develop branch, but will take time before released. For now it helps to install ethereum via command line `bash <(curl https://install-geth.ethereum.org -L)`

**Comment by flexliv** [comment]
Ok, but that means the mac pack is broken? Should maybe say before download.

**Comment by ddsjangster** [comment]
Frozeman, is the mac pack broken? When will the final production/live mac version of MIST be launched?

**Comment by frozeman** [comment]
You mac is not broken :) Either your read all the comments on the linked issue or you better wait..

Mist will still take a few months, i'm currently on person working on web3.js, Mist the wallet and other stuff..

**Comment by maverick3000** [comment]
`bash <(curl https://install-geth.ethereum.org -L)`

This worked. How do I use the command line to update to latest version? Beta 7 and open the UI version of the wallet please

**Comment by elwhizard** [comment]
Same with @hiddentao. Fixed by installing ethereum via homebrew.

**Comment by alexvandesande** [comment]
This is a duplicate of https://github.com/ethereum/meteor-dapp-wallet/issues/109
