### ISSUE TITLE
No more peers after wallet was open for some time

### ISSUE THREAD

**Issue by kienerj** [ethereum/mist#186]
If I leave the wallet open for some time (hours) I will not have any peers anymore and hence not receive any new blocks or rewards from mining pool. The issue can only be fixed by restarting the application.

I read about the clock sync issues and have setup time sync (Windows). Did not affect the issue. It sill happens.

**Comment by frozeman** [comment]
Might be windows closing down the connection of geth? @fjl

**Comment by kienerj** [comment]
I don't think so as I mining using the same geth instance works fine. (Pool mining with ether-proxy + geth and I'm getting rewards).

**Comment by frozeman** [comment]
I need to debug this on windows myself. But i don't have windows :)

**Comment by frozeman** [comment]
This is an issue with windows, which is fixed in geth#develop branch. This fix will come in the over-next release of geth

**Comment by luclu** [comment]
Please update to version 0.7.4 bundled with geth 1.4.4 which should include this fix.
I will close for now. Feel free to reopen, if you still encounter this issue!
