### ISSUE TITLE
Mist is crashing on startup 

### ISSUE THREAD

**Issue by primehat23** [ethereum/mist#189]
I get this error
```
" C:\Users\jeff\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
						throw(ex);
						      ^
Error: ENOENT, no such file or directory 'C:\Users\jeff\mist\interface\.meteor\local\build\programs\server\undefined\public'
    at Object.fs.mkdirSync (fs.js:654:18)
    at Package (packages/tap_i18n-bundler/packages/tap_i18n-bundler.js:25:1)
    at C:\Users\jeff\mist\interface\.meteor\local\build\programs\server\boot.js:249:5
Exited with code: 8
Your application is crashing. Waiting for file change."
```
I followed the tutorial online  I get as far as https://github.com/ethereum/mist run mist

Im not too sure if it is because I used 2 commands to write cd mist/interface && meteor  windows 7 does not seem to like the && function. How does one get windows to accpect the && 

How am I supposted to install brew on windows? I could not generate this binary 
"brew install Caskroom/cask/xquartz"

I would love it if I could get some clear answers.

**Comment by frozeman** [comment]
did you run `npm install` from inside the mist folder?

**Comment by alexvandesande** [comment]
Is there a specific reason you want to build it from source? Have you tried the binaries? https://github.com/ethereum/mist/releases/latest

**Comment by primehat23** [comment]
meteor says exit with code 8 I have no idea what this means. Ill try the binaries.

**Comment by luclu** [comment]
@primehat23 were you able to run the Wallet with the binaries as @alexvandesande recommended?
