### ISSUE TITLE
Unable to import wallet after it disappeared from Mist - MacOS

### ISSUE THREAD

**Issue by jeffdoubleyou** [ethereum/mist#190]
Hello,

I created a wallet using an older version 0.2.6.

I was using the wallet on the latest version 0.4.0 just fine. 

However, yesterday when I looked, the wallet was simply missing.  It wasn't listed at all.

I have tried to import the wallet, but it's not working.  It just says "importing" forever.  It does however display the balance from my wallet.

I've tried adding a new wallet and that's not working either, it is just stuck at "Creating".  I had created another wallet the day that my old wallet disappeared, that wallet is gone as well.

One thing I've noticed is that the block chain status isn't changing after I open the app.  When I open it up, it says that the last block is X seconds ago, but it never sees changes. 

I'd love to include some logs, but I'm not sure where they are or if they are being created.  The only file I can find with a log extension is:

Library/Application Support/Mist//IndexedDB/file__0.indexeddb.leveldb/000003.log

`Jeffs-MacBook-Pro:~ jeffweitz$ find Library/Application\ Support/Mist/ -name '*log*'
Library/Application Support/Mist//IndexedDB/file__0.indexeddb.leveldb/000003.log`

How can I recover my wallet?

**Comment by jeffdoubleyou** [comment]
Update!  Sorry for the noise.  I upgraded geth and the wallet is there.

**Comment by alexvandesande** [comment]
happy ending then!
