### ISSUE TITLE
About Mist button not working

### ISSUE THREAD

**Issue by pablox43** [ethereum/mist#192]
Whenever I click on the Mist button, nothing happens.

Mist version: Wallet 0.3.7 (Beta 4)
OS: Microsoft Windows 7
![2016-02-20 1](https://cloud.githubusercontent.com/assets/8853151/13199242/141cf78e-d7ee-11e5-96f7-99aaebc954c4.png)

Note that when I try downloading a new version, the old version always opens regardless if I click on the new version icon. I'm probably having a rookie moment. :)

**Comment by frozeman** [comment]
Thanks for your detailed report. The about window is currently not added for windows.

**Comment by pablox43** [comment]
Thanks Frozeman!!
