### ISSUE TITLE
Windows Wallet, Beta 7, stuck at 460,000 out of 663,000?

### ISSUE THREAD

**Issue by TonyMcCarp** [ethereum/mist#193]
http://ethereum.stackexchange.com/questions/1521/windows-wallet-beta-7-stuck-at-460-000-out-of-663-000

Any help much appreciated, just to add it is windows 64

**Comment by alexvandesande** [comment]
https://github.com/ethereum/mist/issues/195#issuecomment-187128777
"This is a problem in the windows geth version. We fixed it already in develop, so either build from develop branch yourself or wait :)

Sorry for the inconvenience"

**Comment by luclu** [comment]
@TonyMcCarp please update to version 0.7.4 as this should cointain a fix for your issue.
I will close for now, but feel free to stay and discuss your issue with me!
