### ISSUE TITLE
Ethereum-Wallet-win64-0-4-0 (Beta 7), stuck at Downloading block 1,016,972 of 1,039,937 for two days?

### ISSUE THREAD

**Issue by igorkiev36** [ethereum/mist#195]
Ethereum-Wallet-win64-0-4-0 (Beta 7), stuck at Downloading block 1,016,972 of 1,039,937 for two days?

windows 7 64
antivirus and firewall   disabled
correct system time on the computer
after upgrading wallet synchronization has started and then stopped

wallet/resources/nodes/geth/geth.exe   
Synchronisation failed
```
I0222 00:21:34.026492    4872 backend.go:314] Protocol Versions: [63 62 61], Net
work Id: 1
I0222 00:21:34.027492    4872 backend.go:362] Blockchain DB Version: 3
I0222 00:21:34.030492    4872 blockchain.go:214] Last header: #1016972 [67d98e3d
:] TD=7350649782798922171
I0222 00:21:34.030492    4872 blockchain.go:215] Last block: #1016972 [67d98e3d:
] TD=7350649782798922171
I0222 00:21:34.030492    4872 blockchain.go:216] Fast block: #1016972 [67d98e3d:
] TD=7350649782798922171
I0222 00:21:34.045492    4872 cmd.go:114] Starting Geth/v1.3.3/windows/go1.5.1
I0222 00:21:34.045492    4872 server.go:311] Starting Server
I0222 00:21:36.131492    4872 udp.go:204] Listening, enode://5bc23fca9e58e249021
7f5b670354074872c1bba0c80da1603b9d39828ac9f61f30c8f5aef4dc197b895975441019283cb2
af5b4b738d2b23d5464c3b0bbaf3c@0.0.0.0:30303
I0222 00:21:36.136492    4872 backend.go:526] Server started
I0222 00:21:36.137492    4872 server.go:552] Listening on [::]:30303
I0222 00:21:36.137492    4872 ipc.go:112] IPC service started (\\.\pipe\geth.ipc
)
I0222 00:21:46.139492    4872 downloader.go:288] Block synchronisation started
I0222 00:22:08.929492    4872 downloader.go:267] Synchronisation failed: leveldb
/table: corruption on data-block (pos=510574): checksum mismatch, want=0xc066720
0 got=0x9a05c83a [file=063517.ldb]
I0222 00:22:20.447492    4872 downloader.go:267] Synchronisation failed: leveldb
/table: corruption on data-block (pos=510574): checksum mismatch, want=0xc066720
0 got=0x9a05c83a [file=063517.ldb]
```
Any help much appreciated.

**Comment by frozeman** [comment]
This is a problem in the windows geth version. We fixed it already in develop, so either build from develop branch yourself or wait :)

Sorry for the inconvieninve

**Comment by igorkiev36** [comment]
Thank you. I'll wait. Hopefully the corrected windows version will soon be.

**Comment by Codes4Fun** [comment]
If you don't want to wait, setup a linux VM or linux computer and just copy the keystore over and restart. That is what I ended up doing.

**Comment by adibas03** [comment]
+1

**Comment by frozeman** [comment]
Please all try the latest version 0.5.0 http://github.com/ethereum/mist/releases

**Comment by DaR1DdL3R** [comment]
this wallet is garbage

**Comment by DaR1DdL3R** [comment]
never gets all the blocks and i noticed you little key logger in it. good try

**Comment by Snorlock** [comment]
@DaR1DdL3R could you refer to line?

**Comment by luclu** [comment]
I will close this for now as version 0.7.4 should contain a fix for this issue.
Please give me a small-ping back if you still encounter this problem!

**Comment by igorkiev36** [comment]
Hello, Luca.

I have the same problem

version 0.7.4

Synchronisation failed: leveldb/table: corruption on data-block (pos=80535): checksum mismatch, want=0xb7c9ca20 got=0xc50902e5 [file=040636.ldb]

-- 
Best regards,
Igor                       mailto:friendru32@gmail.com




I will close this for now as version 0.7.4 should contain a fix for this issue.
Please give me a small-ping back if you still encounter this problem!

**Comment by luclu** [comment]
@igorkiev36 please delete that file located under `%appdata%\roaming\Ethereum\chaindata\` as geth was not able to recover it. If this is not working please delete all files under `chaindata`.

**Comment by igorkiev36** [comment]
Hello, Luca.

After deleting the file [file=040636.ldb] and run the wallet

please look attached file

ps: I delete files chaindata sixth time.

- 
Best regards
 Friendru32                          mailto:friendru32@gmail.com



@igorkiev36 please delete that file located under %appdata%\roaming\Ethereum\chaindata\ as geth was not able to recover it. If this is not working please delete all files under chaindata.
—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub



-

**Comment by artyma** [comment]
The same issue. Mist wallet stopped downloading blocks at 495 237 (4 days download). 0.7.4 (Beta 18) Windows 64bit

Any help?

**Comment by luclu** [comment]
@artyma please tryout the latest version of **geth** [(link)](https://github.com/ethereum/go-ethereum/releases).

**Comment by lumicon** [comment]
same problem, any working solution yet? 
thanks!
