### ISSUE TITLE
A misty lullaby

### ISSUE THREAD

**Issue by twalphin** [ethereum/mist#196]
Beta 7
Does the mist browser maintain its connection to peers  while the computer is in sleep mode? The download was eight tenths complete as I walked out the door. Upon return I woke the CPU to happily note a mere one tenth remained yet something seemed askew. Alas, I'd lost all eleven peers! 
Simply waiting it out accomplished nada. The solution: quit mist and restart it.  I gratefully watched as business resumed at the same level from which it had originally been stopped. What might we make of this, maybe deem it as a minor bug of some odd sort? 
- Twalphin

**Comment by frozeman** [comment]
This is fixed in geth develop branch, will be in the node in the over next release.

**Comment by luclu** [comment]
Fixed in version 0.7.4. as geth 1.4.4 is included.
