### ISSUE TITLE
Mist not starting up

### ISSUE THREAD

**Issue by brian2121** [ethereum/mist#197]
I am no programmer but have basic computer skills. I have just started using Ether. I have 25 Ether in my Mist wallet but now I cannot access my wallet. I am currently getting the alert message,

' Couldn't start an Ethereum node! Are you already running a node? Make sure your IPC path is set to the default: $ geth --ipcpath \.\pipe\geth.ipc '

I am at my wits end as to what to do any help would be most appreciated.

**Comment by frozeman** [comment]
Can you check if you have already a node process running? please kill that process and restart.

**Comment by brian2121** [comment]
Hi. As i said i am no computer expert i am only using ether for investing purposes. Having said that as far as i know i dont have any program running. I have restarted my pc and also shut it down. If it is possible that I still have a node running please tell me how I can shut it down. Thank You.
Please pardon my ignorance.

**Comment by alexvandesande** [comment]
@brian2121 which system are you running? Is it windows 32 bit?

**Comment by brian2121** [comment]
Windows 10 64bit

**Comment by frozeman** [comment]
We have some issue with the windows node binary, which is already fixed in geth#develop
Not sure if thats related to your problem.

You can contact me in skype (frozeman.de) and we can make a team viewer session, so i can figure out whats wrong on your end.

**Comment by luclu** [comment]
Assuming this to be solved in 0.7.4. 
Please feel free to reopen if you still encounter this issue!
