### ISSUE TITLE
Price ticker opt out 

### ISSUE THREAD

**Issue by frozeman** [ethereum/mist#199]
Adda opt out in the on boarding process to disable the there price ticker requests.

**Comment by vcealicu** [comment]
If/when this gets implemented we can start working on a dashboard, i'm happy to also exclude tracking of any sort from the price server as well (through a param).

We don't track anything at the moment.

Also if/when we start working on a dashboard (how many people are active now, have been active in the past x days, maybe general location information, language etc) I'll make the API server public on Github. All it does is connect to Redis and ask for pricing info or connect to the Postgres db where we store historical to get the price at a certain point in time. It's Nodejs so it would be easy for everyone to read through. Also, request validation aside (make sure all the params exist, etc), there are less than 50 lines of code.

**Comment by luclu** [comment]
Also price ticker should not be shown on test- or privatenets.
