### ISSUE TITLE
 Ethereum-Wallet-win64-0-4-0 does not start in windows 10

### ISSUE THREAD

**Issue by jamespotkukelkka** [ethereum/mist#202]
Hi!
I have wallet in C:\Users\Jarkko\Desktop\Ethereum-Wallet-win64-0-4-0

When I click the Ethereum-Wallet nothing happens.

**Comment by jamespotkukelkka** [comment]
This was the first attempt to launch the wallet

**Comment by nwfella** [comment]
Also having an issue with 0-4-0 win64 bit version on windows 10.  Now seemingly unable to load up my previous 0-3-9 version now either :/

**Comment by frozeman** [comment]
Can you go to `%APPDATA%/Roaming/Mist/` and copy the `*.log` files here?

**Comment by nwfella** [comment]
Could you be more specific?  I'm seeing a 1kb node.log, as well as a 122kb 000003.log, and finally a LOG file that's also only 1kb.

**Comment by jamespotkukelkka** [comment]
I don'f find "mist" folder in C:\Users\Jarkko\AppData\Roaming

**Comment by frozeman** [comment]
Give me all log files please. You can also look inside and see if you find your issue ;)
@jamespotkukelkka Thats odd, this means Mist never really started to create the folder i guess.

**Comment by Simiswitzerland** [comment]
Hi frozeman

I do have the same problem.
When I start mist, it only shows "Ethereum node needs to sync, please wait..." & "Looking for peers..."
I just created an account here on github especially for this problem.
How can I send you the log files (I do have node.log.0 - node.log.4?

**Comment by frozeman** [comment]
I think you can just drag and drop them into the comments field. if not open them and add the content to a gist in http://gist.github.com

**Comment by Simiswitzerland** [comment]
https://gist.github.com/Simiswitzerland/71163acc22d4d852d5ce

**Comment by nwfella** [comment]
<script src="https://gist.github.com/nwfella/bdab117c9e8e4327548c.js"></script>

**Comment by nwfella** [comment]
https://gist.github.com/nwfella/bdab117c9e8e4327548c

**Comment by frozeman** [comment]
I think that has to do with a know windows bug, please wait for the version after the homestead version

**Comment by h2002al** [comment]
I have windows 10 and at my laptop and the last version of wallet: Ethereum-Wallet-win64-0-4-0 is opened without problem. I copied this version to the previous version and every time want to open the wallet click the exe file of this last one. Everything goes ok always except the fact that during the download of the new blockchain (the blocks created after the last time where was opened) it is not showed the tutorial. Everything else goes smoothly. I have 500 ether in this wallet and even to them was not happened nothing.

**Comment by frozeman** [comment]
Its very cryptic what you wrote.

The on boarding comes only if you have no accounts, after that it wont show again.
In menu ->  accounts -> import presale you can still import.

**Comment by Undland** [comment]
Windows 8.1 x64 same trouble. Two clicks and nothing.

**Comment by luclu** [comment]
Please update to version 0.7.4 as issues should be solved.

**Comment by Undland** [comment]
0.7.4 nope!
