### ISSUE TITLE
Ubuntu 14.04.4 Ethereum wallet display a white window with only menu bars

### ISSUE THREAD

**Issue by NicolasMassart** [ethereum/mist#203]
on Ubuntu 14.04.4 64bit, after the window that enable to select the testnet or mainnet and after the sync is finished, the main window opens and it's blank with only window borders and the menu options.
See attached screenshot.

![capture du 2016-02-23 01 03 35](https://cloud.githubusercontent.com/assets/4677568/13237104/5aea6b42-d9c9-11e5-9777-13f359d59fc9.png)
s

**Comment by frozeman** [comment]
This is a duplicate of #75
