### ISSUE TITLE
Mist wallet 0.4.0 not launching on Mac OS X 10.11.3

### ISSUE THREAD

**Issue by Mr-Beetroot** [ethereum/mist#204]
This is the dialog that the application throws out upon opening:

geth cannot be opened because of a problem.

Check with the developer to make sure geth works with this version of OS X. You may need to reinstall the application. Be sure to install any available updates for the application and OS X.

Click Report to see more detailed information and send a report to Apple.

**Comment by frozeman** [comment]
Can you copy the `*.log` files from `~/Library/Application Support/Mist`. I have the same system and it works for me.

**Comment by maverick3000** [comment]
Hi Frozenman. I am also having the same issue of the wallet not launching it just gets to the initial popup starting window then freezes.

Can you confirm the files structure is ok and there is not duplicate node files by mistake etc

Thanks.

[http://ctrlv.in/716567](url)

**Comment by frozeman** [comment]
@maverick3000 i can't access the page, gives me a github 404.
please post you log files here. The log file duplication is on purpose..

I assume your issue is #65

**Comment by maverick3000** [comment]
Apologies for ignorance. What directory / name are the log files in please?

**Comment by frozeman** [comment]
You are in the folder, please copy the *.log and *.log.x files

**Comment by maverick3000** [comment]
Apologies frozenman. I do not see .logs file in the following directory (see above screenshot also)

`~/Library/Application Support/Mist`

**Comment by frozeman** [comment]
You don't see the `node.log` and `node.log.1` etc??

**Comment by maverick3000** [comment]
No not in that directory.

**Comment by maverick3000** [comment]
'Absolute ignorance'. Its been a long day!

Node.log
`dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /Users/scotttrowbridge/Desktop/Crytocurrency/Ethereum/Ehtereum Wallet/Ethereum-Wallet-macosx64-0-4-0/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth
  Reason: image not found`

**Comment by frozeman** [comment]
I thought so, thats #65

**Comment by maverick3000** [comment]
I read through but could not really see an end solution. Am I overlooking again? (Thanks for your help btw)

**Comment by frozeman** [comment]
Install ethereum via command line first: `bash <(curl https://install-geth.ethereum.org -L)`
