### ISSUE TITLE
Menu bar misbehaving with standalone geth

### ISSUE THREAD

**Issue by klmoney** [ethereum/mist#205]
In Ubuntu 14.10, when I connect the wallet app to a running, standalone geth (geth 1.3.3, go 1.4.2), the new “Accounts” menu does not display in the menu bar. When I run the app with its bundled geth, the Accounts menu displays.

I have not tested this on Mac/Windows.

Note also, that when connected to a standalone geth, the menu bar can sometimes be missing the first “Mist” menu, and at times even show 2 “Mist” menus.

Lastly, just a query: Both the Pre-sale import window and the ShapeShift window include the app’s menu bar. Is this the desired effect? The only drawback I can see with this setup is that a user may (though unlikely) click on the “Quit Mist” option in the window and inadvertently close the app.

**Comment by frozeman** [comment]
For the first two cases a screenshot is appreciated. Concerning the new account, this only shows when you load th dapp in mist, e.g. the node connection in mist works properly.

Concerning the last point. This is actually wanted, as a user may shift to the to a different network.

Though i didn't check in windows, as there its probably in the window itself, which is not desired, youre right.

**Comment by klmoney** [comment]
With standalone geth:
Accounts menu is always(?) missing:
![noaccountsmenu2](https://cloud.githubusercontent.com/assets/11975185/13283743/a06f0ac6-db2a-11e5-8263-18a63b821e97.jpg)

The menu bar can be “unstable”:
![misbehavingmenubar](https://cloud.githubusercontent.com/assets/11975185/13283789/eae27c00-db2a-11e5-8348-a10384bb56ad.jpg)

![5menusonly](https://cloud.githubusercontent.com/assets/11975185/13283801/039fd350-db2b-11e5-878b-26528d4bd33e.jpg)


With bundled geth:
Menu bar stable and with Accounts menu:
![bundledgethmenubar](https://cloud.githubusercontent.com/assets/11975185/13283826/1d2c4f60-db2b-11e5-900b-2a7dfb2382d0.jpg)

**Comment by frozeman** [comment]
Thanks for the screens.

Currently we don't show the accounts menu, when the node is not started by geth. i can activate that actually.

The last bug, seems more like an electron bug on ubuntu, i have to look into this

**Comment by klmoney** [comment]
Thanks for the reply @frozeman

**Comment by luclu** [comment]
@klmoney are you still experiencing this bug with 0.7.3?
