### ISSUE TITLE
Shifty Timeout?

### ISSUE THREAD

**Issue by andyman27** [ethereum/mist#206]
Sent bitcoin worth of 1 ether as prompted in the Shifty screen and the time ran out before confirmation. What happens to my bitcoin? I am now unable to get back to the screen as the Ethereum node needs to sync...

I am confused as to where my coins are, any help would be appreciated.

Thanks!

**Comment by frozeman** [comment]
Problems with the shape shift tools should be reported to them.
But here are some hints:

- copy the transaction id and give it to them
- look at your ether address in a block explorer like http://etherscan.io
