### ISSUE TITLE
Not recive ETH.  my adress 0xfF07621Fdae16fa36BeE77C19058fCa2d2BC792f no eth

### ISSUE THREAD

**Issue by nik2392** [ethereum/mist#2069]
I send ETH from Poloniex to a Account and i didnt receive Eth.

**Comment by luclu** [comment]
Hi @nik2392, please make sure you are running the [latest version](https://github.com/ethereum/mist/releases) and your node is **fully** synced.
Although this may take between 1h (SSD) and 10 hours (HDD) you should be able to see a progress bar on the *splash-screen* or in the *main-window*.

Some recommendations: 
- check your account's balance using http://etherscan.io
- make a backup of all account's keyfiles via `menu -> accounts -> backup -> accounts`
- should the initial sync take very long, consider following [these instructions](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569) to speed it up
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com in the meantime

If this didn't solve your issue, please follow [these instructions](https://github.com/ethereum/mist/issues/new) and upload the `node.log` files:
> - Log files
>   - go to menu -> accounts -> backup -> application data
>   - zip and upload node.log and all other node.log.X files

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
