### ISSUE TITLE
Start geth with `--cache 512` by default

### ISSUE THREAD

**Issue by alexvandesande** [ethereum/mist#207]
As per @karalabe suggestions, Mist would be much faster if be started geth with ``--cache 512``. It's not on by default for Geth because Geth is targeted at much slower computers, which wouldn't be able to run Mist anyway.

I tried doing it myself by altering `ethereumNodes.js` with the following code, but then an error would prevent mist from starting.

```js
args = (type === 'geth') ? ['--fast', '--cache 512'] : ['--unsafe-transactions', '--master', pw];
```

**Comment by mariusdarila** [comment]
Spawning geth with `['--fast', '--cache', 512]` works.

**Comment by alexvandesande** [comment]
I've solved it with ['--fast', '--cache=512']. It's going to be merged soon

On Mon, Feb 29, 2016 at 6:32 AM, Marius Darila <notifications@github.com>
wrote:

> Spawning geth with ['--fast', '--cache', 512] works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/mist/issues/207#issuecomment-190122416>.
>



-- 

Alex Van de Sande
UX Designer
