### ISSUE TITLE
Recommendation: Move wallet.ethereum.org to github.io page

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/mist#2071]
Hey, it looks like the wallet is being hosted on wallet.ethereum.org. I think it would be good security idea to move to a github page. Its much less likely someone is able to take hold of a page hosted by github than on wallet.ethereum.org.

**Comment by luclu** [comment]
Thank you for this suggestion, @aakilfernandes!
Currently we use gh-pages to host the wallet, `wallet.ethereum.org` is only a CNAME.
Furthermore using gh-pages is only a temporary measure until swarm is [integrated in Mist (PR)](https://github.com/ethereum/mist/pull/1702) and ENS is deployed on the mainnet.
