### ISSUE TITLE
ETH stuck in test-net wallet.

### ISSUE THREAD

**Issue by casay** [ethereum/mist#2075]
#### System information
``````
Version: `0.5.1`
OS & Version: osx 10.12.3
Node type: geth(default)`
``````
A while I go I started a ETh wallet on my computer without really knowing all the details. Now I have coins I would like to get out stuck in the test-net. When I start the application I have to skip searching for peers since even after being left to run for more than 24hrs it was unable to find any. I have tried updating to the most recent software but it only creates a new application and the balance of my wallet will not transfer. 
Could anyone explain to me at least what the issue is and whether there is a way to retrieve my coins. 
thanks

**Comment by luclu** [comment]
Do the following:
1. use http://etherscan.io to check the addresses in question
1. backup the concerning keyfile (menu -> account -> backup)
1. switch to mainnet (menu -> develop -> network)
1. make sure no firewall is blocking and wait until fully synchronized

Alternatively you can use http://myetherwallet.com after step 2.

**Comment by casay** [comment]
thanks, 
I tried checking the status of the wallet using etherscan but it says I have nothing in there, even though mist wallet says I have coins. is there any way to resolve this? or do I not actually have the coins it says I have.

**Comment by luclu** [comment]
If it is the on the testnet please use the corresponding version https://ropsten.etherscan.io.

**Comment by casay** [comment]
thanks, just gave it a check. still, says I have no ETH coins even though my wallet says I do. the wallet has been unable to connect to any peers, could that be the problem?  
I've tried uploading the wallet backup file to the newest software but it also read a balance of zero. 
I am willing to try anything to retrieve these coins, or at least figure out what happened to them.

**Comment by luclu** [comment]
Sorry, I might be confused here. Do you claim to have Ether or "Testnet Ether", thus:
1. does checking via http://etherscan.io show any funds?
1. does checking via http://ropsten.etherscan.io show any funds?

**Comment by casay** [comment]
I didn't know that there were two different types. I am pretty sure I have Ether since originally I purchased them through poloniex or shapeshift. but neither of the websites provided said I had any balance on the wallet address.

**Comment by AmesEla** [comment]
I have ether in Test-net and it doesn't shpw on the ropsten.ethernetscan.ip nor on test-net.etherscan.io

please see my post https://github.com/ethereum/mist/issues/2142 with screen shots.

**Comment by billwilson12** [comment]
Pillar ICO had a bunch of people put ETH on test at this address https://etherscan.io/tx/0xe97cd77f7a9143da183408a4f39e18224ea14aeb6e8003ac2d9496482e53ac6f can they themselves get back using this procedure?

**Comment by evertonfraga** [comment]
@billwilson12 what do you mean by "ETH on test"?

If they have access to they keystore (account), then yes.

**Comment by billwilson12** [comment]
The Pillar ICO gave people this address it was put on the testnet by them by mistake. They are telling all this people in that wallet / address that yes our mistake, but your loss we can not get it out. And today all the ETH sent there is still there saw your write-up and thought you may have some better insight than someone rushing a contract design.

**Comment by evertonfraga** [comment]
@billwilson12 can you link any official statement from them?

The account can be used both on mainnet and testnet, as long as they put the keystore in the right directory, while using geth. 

From `./Ethereum/testnet/keystore` to `./Ethereum/keystore`.
