### ISSUE TITLE
Transfer Main Account to Another Machine

### ISSUE THREAD

**Issue by stewjj** [ethereum/mist#2076]
My Main Account on an old iMac was never able to sync and I have ETH waiting that I cannot get to.  How do I switch the account to a new Windows 10 PC? Thanks
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
Hi @stewjj, 
simply make a backup of all account's keyfiles via `menu -> accounts -> backup -> accounts` and copy them to the new computer.

#### Here is some more generic advice:

Please, make sure you are running the [latest version](https://github.com/ethereum/mist/releases) and your node is **fully** synced.
Although this may take between 1h (SSD) and 10 hours (HDD) you should be able to see a progress bar on the *splash-screen* or in the *main-window*.

Some recommendations: 
- check your account's balance using http://etherscan.io
- make a backup of all account's keyfiles via `menu -> accounts -> backup -> accounts`
- should the initial sync take very long, consider following [these instructions](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569) to speed it up
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com in the meantime

If this didn't solve your issue, please follow [these instructions](https://github.com/ethereum/mist/issues/new) and upload the `node.log` files:
> - Log files
>   - go to menu -> accounts -> backup -> application data
>   - zip and upload node.log and all other node.log.X files

**Comment by stewjj** [comment]
Thanks to you Misters and Gethers. The answer for me was to create a new base account on a new faster computer, letting it sync, and then transferring over the old account from the old slow iMac that wouldn't sync.  MY ETH appeared instantly. Reading all the issues was helpful.
