### ISSUE TITLE
no ether received adress 0xFF480A7d34DFCdC44c155D36D6a58a5cEC7FCD46 on linux ethereum wallet

### ISSUE THREAD

**Issue by vpascoate** [ethereum/mist#2079]
![captura de tela de 2017-03-28 22-24-57](https://cloud.githubusercontent.com/assets/26754779/24434480/34f7fcb0-1406-11e7-98ea-c93dfff0e1ee.png)
#### System information
``````
Version: `0.8.9`
OS & Version: linux mint 18.1
Node type: `eth/geth(default)`


`````

**Comment by garretlaxton** [comment]
You need to let the wallet fully sync, once it's at '100%' at the top you'll see your ETH & be able to send it.

**Comment by vpascoate** [comment]
Oh man thanks very much for answer I.... I was going crazy here with the
thought that it was all lost... Thank you man really no words

Em 29 de mar de 2017 7:56 AM, "garretlaxton" <notifications@github.com>
escreveu:

**Comment by garretlaxton** [comment]
@vpascoate It also can take 1-20 hours to sync depending on your system specs.

**Comment by vpascoate** [comment]
today it finally showed uṕ! thanks for all the quick and good answers...
!!you guys are great team!

2017-03-29 8:05 GMT-03:00 garretlaxton <notifications@github.com>:
