### ISSUE TITLE
No eth node binary found, please start manually on win64 after powercut

### ISSUE THREAD

**Issue by fusenn** [ethereum/mist#208]
all was well when i had a power cut, tried to start up the wallet after reloading windows and I get this msg.

**Comment by frozeman** [comment]
Please provide the log files in `%APPDATA%/Roaming/Mist`

node.log and node.log.x

**Comment by fusenn** [comment]
Both are 0kb files. They are empty.

**Comment by fusenn** [comment]
I deleted the Mist folder and it still doesn't start. "Are you already running a node? Make sure your IPC path is set to the default: $ geth --ipcpath \\.\pipe\geth.ipc"

In node.log: "I0301 09:50:45.435667    6356 database.go:71] Alloted 16MB cache to C:\Users\hive\AppData\Roaming\Ethereum\chaindata
Fatal: blockchain db err: leveldb/storage: corrupted or incomplete CURRENT file"

**Comment by frozeman** [comment]
@fusenn you need to delete the Ethereum folder, which contains your blockchain.
Make sure you backup your `keystore` folder inside first..

**Comment by fusenn** [comment]
I'll give it a try frozeman, i prsume you mean the eth folder in appdata yes?

**Comment by frozeman** [comment]
the ethereum folder in `%APPDATA%/Romaing/Ethereum`

**Comment by fusenn** [comment]
deleted that eth folder, program started(yay), downloaded blockchain again but the program stuck on processing blocks so trying it another way now.

**Comment by frozeman** [comment]
This is a know windows issue, which will be fixed in the over-next release

**Comment by MarinAngelo** [comment]
Hi, I have the same issue, but after deleteing the Ethereum Folder the wallet still does not start.

**Comment by frozeman** [comment]
@MarinAngelo what  os and mist version youre using?

**Comment by MarinAngelo** [comment]
Windows 10, Wallet 0.5.1

**Comment by frozeman** [comment]
Please update to the latest 0.6.1 and try again

**Comment by MarinAngelo** [comment]
How should I update? Just install it in the same directory as the old one, or in a seperate directory?

**Comment by MarinAngelo** [comment]
I have installed the 0.6.2 now seperately, but I can not start it pu as well.

**Comment by rajwcg** [comment]
Please delete everything from %APPDATA%/Roaming/Mist and restart wallet app

**Comment by KywDuploM** [comment]
@rajwcg Hi, having the same problem. Tried that. Didn't work either.
