### ISSUE TITLE
Blockchain is too large to save locally, need clear instructions

### ISSUE THREAD

**Issue by xlcrr** [ethereum/mist#2081]
Hi guys,

I am really excited to start coding with Solidity and getting more stuck into this ecosystem.

However, I am running on a macbook air and I am currently suffering from incredibly limited data storage.  I cannot afford to download the blockchain and sync with the network.

I would like to save the blockchain and the wallet on an external disk, but I am having trouble relocating the folders with commands

If someone could outline some step by step instructions about how to achieve this, it would be a really great help

**Comment by frozeman** [comment]
start geth yourself using `geth --datadir /myother/volume/Ethereum --ipcpath ~/Library/Ethereum/geth.ipc`

**Comment by xlcrr** [comment]
Thank you. That has created the geth and keystore files and its syncing them, but when I need to open the wallet in the future can I open the wallet client as normal? Do I have to change some config in the wallet to point to these files? How will the wallet know to use the blockchain I am saved externally?

**Comment by frozeman** [comment]
you would either need to start the node at all times before or start mist with `mist --node-datadir ... --node-ipcpath ...`

**Comment by xlcrr** [comment]
If I set --datadir to external disk and try to open up Wallet I get 

Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use

If I run geth in another window which I believe normally opens up a node I get the same error

How can I set --datadir and open the wallet or do I have to wait to download it? Do I then have to set the path in config?

**Comment by luclu** [comment]
@xlcrr you will also need to add the `--rpc` flag like:
`mist --node-datadir /some/path --rpc /some/path/geth.ipc` Replace `/some/path` with the designated path. You won't need to append `--node-ipcpath ...`.
