### ISSUE TITLE
Wallet returns 404 error opening contracts

### ISSUE THREAD

**Issue by jeremygmiller12** [ethereum/mist#2083]
Through mist and through ethereum wallet the only thing that will show is my accounts, clicking on them does nothing, clicking on contracts does nothing, in mist it returns a 404 error then returns to the default screen.

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
@jeremygmiller12 could you kindly fill out as much information as possible? This will make it easier to figure out the issue.

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
