### ISSUE TITLE
Fund with CC to coinbase not working

### ISSUE THREAD

**Issue by carlostbanks** [ethereum/mist#2085]
#### System information
``````
Version: `0.8.9`
OS & Version: windows
Node type: `eth/geth(default)`
``````

I purchased 1 ETH using the "Fund with CC" button on Ethereum Wallet. I have the receipt saying the transaction went through but I have not received the ETH. 

I then transferred 1 ETH from my coinbase account to my Ethereum Wallet and the 1 ETH was taken from my coinbase account, but I have not received anything in my Ethereum Wallet.

If anyone needs to see anything to help me out, I will gladly provide necessary information.

Thank you

**Comment by garretlaxton** [comment]
Your wallet needs to fully sync in order to see the ETH in your wallet.

**Comment by carlostbanks** [comment]
Thanks for the comment garretlaxton. 

Is there a preferred method to help my wallet sync other than leaving my laptop on for a long time?

When this first started, I had 6 seeds, 3 million blocks left, and 1% complete. I left my laptop on all day today while I was at work, and as of right now it says 3 seeds, 1.7 million blocks left, and 1% again. Do I just repeat this until the blocks finish up?

Thanks again !

**Comment by garretlaxton** [comment]
Yes, once it gets to 0 blocks you will see your ETH. It can take a while to sync depending on your system specs.

**Comment by carlostbanks** [comment]
okay, that was my next question. What factors influence the download speed. 

I figured it had to do with either my internet speeds, physical location (lack of # of seeds), or my computer specs. 

I'll search online for recommended computer specs to accelerate my blockchain download time. 

Thanks again

**Comment by luclu** [comment]
@carlostbanks the main factor is the type of storage device. A full sync takes from 1h (SSD) up to 20h (HDD).

Furthermore make sure you are doing a "fast" sync: https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
