### ISSUE TITLE
Account disappeared from Mist

### ISSUE THREAD

**Issue by baobabKoodaa** [ethereum/mist#2086]
#### System information
``````
Version: `0.8.9`
OS & Version: windows
Node type: `geth`
``````

When I opened Mist today, the account which had all my ETH had disappeared and I had to load it again from backup. Here's what I suspect caused this:

I have a previous installation of Ethereum Wallet, with old accounts and old chain data. Before I opened Mist, I opened a new installation of Ethereum Wallet 0.8.9, which showed old accounts & that chain data was 6 months behind. So it was accessing data from the old installation. Then I closed it and opened Mist, it was now also showing old data. So I think opening Ethereum Wallet (which was configured for old data) somehow reconfigured data locations for Mist as well, essentially causing Mist to forget where the new data was stored.

**Comment by luclu** [comment]
@baobabKoodaa are you sure this didn't accidentally happen while removing the `chaindata` folder?
Also this behaviour can occur when switching networks as geth uses different `keystore` folder for mainnet and testnet.

Mist/Ethereum Wallet itself does not have access to the keystore folder but relies on geth (the communication is accomplished via web3.js).

**Comment by baobabKoodaa** [comment]
I didn't remove the chaindata folder at any point. I also didn't switch networks.

**Comment by evertonfraga** [comment]
Please try with up to date software, as it is probably fixed.

Should you still encounter the same issue, reopen or create a new one.
