### ISSUE TITLE
Mist won't open on Mac 8.9 OSX

### ISSUE THREAD

**Issue by jonpspitz** [ethereum/mist#2089]
It bounces on my bar at the bottom of the screen, stops, then goes away. Was working fine. Ethereum Wallet works fine. Help :(

#### System information
``````
Version: `0.8.9`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
@jonpspitz please provide the log files!

**Comment by jonpspitz** [comment]
How do I do that? It won't even open?
ᐧ

Best,

*Jon P Spitz*
Tel: 1+585-613-6168
jonpspitz@gmail.com
<http://www.linkedin.com/in/jonpspitz>  <http://twitter.com/jonpspitz>

**Comment by luclu** [comment]
In this case please remove the Mist config folder and retry, depending on your OS it is:
- Windows `%APPDATA%\Mist`
- macOS `~/Library/Application Support/Mist`
- Linux ` ~/.config/Mist`

Also you should find the `node.log` in there once Mist started successfully.

**Comment by evertonfraga** [comment]
Did it work? 

Closing upon inactivity. Please reopen if needed.
