### ISSUE TITLE
Issue with transferring from wallet contract to another person's main account.

### ISSUE THREAD

**Issue by jellbell** [ethereum/mist#2090]
3 Days ago I transferred funds from my contract wallet to my girlfriends main account. 

The transaction looks like it's all been confirmed but she has not received the funds. 

https://etherscan.io/tx/0x39502c44aa43a448e00f141a069119076f038e067c24f3d2ef6e3714b4ff502b

Yes...she's all synced up to the blockchain.

Thanks!

**Comment by luclu** [comment]
@jellbell as you send the Ether to the account https://etherscan.io/address/0x7b1812fdf6744382d596c32ef3b20a7e265320f5, please make sure you/your girlfriend has access to this account.

**Comment by jellbell** [comment]
@luclu Yes, this is the address of her main account when she first set the application up.

**Comment by jellbell** [comment]
@luclu Does she need to action anything on her side?

**Comment by luclu** [comment]
@jellbell were you able to solve it?
