### ISSUE TITLE
macOS Sierra Ethereum wallet and Mist don't sync past 1%

### ISSUE THREAD

**Issue by eul2017** [ethereum/mist#2095]
I can't get Ethereum wallet and Mist to sync on macOS Sierra

They go to 1% max and fluctuate between 3000000 to 2000000 blocks.

I need some help because I just bought some Ether and I want to have them stored safely.

Thank you.

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
Hi @eul2017, could you kindly fill out as much information as possible? Especially the log files will be relevant in figuring out this issue.

**Comment by eul2017** [comment]
Hopefully this helps

Console
<img width="556" alt="screen shot 2017-04-01 at 12 25 55" src="https://cloud.githubusercontent.com/assets/26816732/24577860/7150e910-16d6-11e7-8ea8-3f4c56acff93.png">

Screenshot
<img width="356" alt="screen shot 2017-04-01 at 12 27 43" src="https://cloud.githubusercontent.com/assets/26816732/24577881/a24dbb9c-16d6-11e7-8db1-48edb9729294.png">

Node zip
[node.log.zip](https://github.com/ethereum/mist/files/887536/node.log.zip)
