### ISSUE TITLE
Implement the Browser Bar

### ISSUE THREAD

**Issue by alexvandesande** [ethereum/mist#21]
The purpose of the bar is to:

* Allow the user to manage which keys are visible for the Ðapp
* Allow the user to add and remove Ðapps to the sidebar
* Allow the user to navigate a Ðapp 
* Show information about the current Ðapp
* Show information about the network (that is relevant to his current navigation)

**Comment by evertonfraga** [comment]
Mostly solved at #814. If there are any uncovered matters, we can create new issues.
