### ISSUE TITLE
unable to start Ethereum Wallet for macOS 10.12.4, 10.12.5, unable to download Geth

### ISSUE THREAD

**Issue by lexab65** [ethereum/mist#2102]
#### System information
MacBook Pro, Ethereum Wallet
Version: `Ethereum Wallet 0.8.9`
OS & Version: macos 10.12.5, 10.12.4
Node type: Ethereum Wallet
/Library/Application Support/Ethereum Wallet/binaries/Geth/archive.tar have 0 bytes

looks like Ethereum Wallet unable to download Geth from blob.db5prdstr03a.store.core.windows.net

<img width="626" alt="screen shot 2017-04-02 at 12 12 39" src="https://cloud.githubusercontent.com/assets/26850564/24585894/c169da66-179d-11e7-8c30-2df32ee1fb38.png">
``````at start i get the following errors:
"Error running downloaded binary."
after this
"Ethereum node connection error :'("


- Log files -unable to get logs there is no node.log file in directory

**Comment by evertonfraga** [comment]
Thanks for reporting. Isn't it any network restriction, like firewall preventing your download?

Please let me know if this still happens.
