### ISSUE TITLE
Can't send my Ether

### ISSUE THREAD

**Issue by JanBeijer** [ethereum/mist#2103]
When i try to send my Ether to another address, then it says:

Multiple keys match address, please remover duplicates from keystore (menu > accounts > backup > accounts).

When i go to menu > accounts > backup > accounts im in map with geth en keystore.. what do i have to do now?

Thanks in advance

**Comment by JosLazet** [comment]
Open the keystore map, there should be a duplicated keystore file. Backup both of them, delete one and reopen wallet. Everything should be working again.

**Comment by luclu** [comment]
Thank you @JosLazet!
