### ISSUE TITLE
Password characters show/hide option

### ISSUE THREAD

**Issue by Haxtro** [ethereum/mist#2105]
#### System information
``````
Version: `0.8.9`
OS & Version: OSX
Node type: `eth/geth(default)`
``````

It seems like something weird is going on with allowed and non-allowed characters when creating a new Account. I cannot access or send any ETH due to this bug. When creating a new account and the input for password is given, using characters that are not allowed (such as ' " ^) are not accepted, so not shown. However, while checking the "Show password" option, it is certainly allowed to use these characters.

When trying to send ETH and filling in my KeePassX generated password, it won't work. I tried leaving out the above mentioned characters and all possible combinations, but I can't seem to make it work. It seems like my ETH is lost forever..

Any suggestions?

Thank you.

**Comment by sathishvj** [comment]
I don't think characters like ' " ^ are not allowed.  Pretty much anything should be acceptable.  

Have you backed up the keystore file?  Can you attempt to open it via MEW?

**Comment by evertonfraga** [comment]
Hi, we've consolidated the password discussions to a single place. Please let's keep the discussion on this place: #3513 

Thanks.
