### ISSUE TITLE
Cannot sync new Ethereum Wallet 0.8.9 install

### ISSUE THREAD

**Issue by thaistar** [ethereum/mist#2106]
Two ago I installed Ethereum Wallet 0.8.9 and have been waiting for it sync up. I've seen it get to 22% and then the progress bar disappears and after a while it starts from zero again. I've seen messages saying my time is not synced but I don't believe it. I have Time Sync set to every minute.
No idea what Mist is.
[nodes.zip](https://github.com/ethereum/mist/files/888971/nodes.zip)
Version: 0.8.9
OS & Version: Win7-64
Node type: Geth 1.5.9 (Go)
![image](https://cloud.githubusercontent.com/assets/7033982/24595204/438fcf82-17e9-11e7-93c7-d9a763b40fd0.png)

**Comment by rionnox** [comment]
I'm suffering from the exact same problem;
Version: 0.8.9
OS & Version: Win7-64
connected to 7 peers - 1,795,477 blocks left 3% 

Any help or advice appreciated? I've no firewall either.

Thanks :-)

**Comment by thaistar** [comment]
I just saw it drop back from 58% to 36%. Does this wallet even work???

**Comment by luclu** [comment]
Hi @plasma26, please make sure you are running the [latest version](https://github.com/ethereum/mist/releases) and your node is **fully** synced.
Although this may take between 1h (SSD) and 10 hours (HDD) you should be able to see a progress bar on the *splash-screen* or in the *main-window*.

The %-progress does indicate the status of the current synchronization session, thus with ~1 million blocks left your node is already over 70% synced (of the full size of the chain).

Some recommendations: 
- check your account's balance using http://etherscan.io
- make a backup of all account's keyfiles via `menu -> accounts -> backup -> accounts`
- should the initial sync take very long, consider following [these instructions](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569) to speed it up
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com in the meantime

If this didn't solve your issue, please follow [these instructions](https://github.com/ethereum/mist/issues/new) and upload the `node.log` files:
> - Log files
>   - go to menu -> accounts -> backup -> application data
>   - zip and upload node.log and all other node.log.X files

I will close this for now as you should be fine as soon as your node is fully synced.

**Comment by plasma26** [comment]
Dear Luca Zeug

Thank you for your help.
However, my computer could not synchronization for all blocks until now.
It is not easy due to very low speed.
I have found my account's balance at that site using my wallet address.
How can I use my wallet by finishing sync with all blocks?
The attached file is node.log files(zip), could you check it for me?

Thank you for your kindness and help,

From plasma26

2017-04-03 22:55 GMT+09:00 Luca Zeug <notifications@github.com>:

**Comment by luclu** [comment]
Hi @plasma26 you might have to use github.com to upload the `node.log` files! :)
