### ISSUE TITLE
hello everyone i am new to github and cant see transfered funds

### ISSUE THREAD

**Issue by 2002stoke** [ethereum/mist#2108]
![screenshot 1](https://cloud.githubusercontent.com/assets/26865403/24598339/d33e078a-1842-11e7-97d2-bbbb27e03afa.png)
hello I downloaded ethereum wallet for windows yesterday and I sent some funds from my coinbase account to my new ethereum wallet but the funds didn't arrive and they still show £0 can you please help and explain if I am need to do something else.
my wallet address I sent to was  0A56d7c70856Cd1956145c6a3C0c65e0E45789479.

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

![screenshot 1](https://cloud.githubusercontent.com/assets/26865403/24598410/22b91f7a-1843-11e7-9dfd-68813ffaf6a8.png)

 - Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files 
[node.log.zip](https://github.com/ethereum/mist/files/889172/node.log.zip)

**Comment by luclu** [comment]
@2002stoke please be patient until your node is fully synchronized to the network. You can see the progress at the top. I will close this for now, as you should be fine as soon as your are synced.
