### ISSUE TITLE
Computer Shut Down accidentaly and download of blockchain startes all over again.

### ISSUE THREAD

**Issue by lordofangels** [ethereum/mist#2110]
Good Morning. I was downloading the blockckain of Ether with Command Line Tools and I had trouble with a lack of energy. Then I put the command again build/bin/geth and when I open the Mist 0.8.9, It apperas 0% of downloaded blockchain and it was in 40%. Is it possible to "sync" it again or to recover the download and synchronization of blockchain?

Thank You.

Ps.: Operational System OS X - Mac
 
![captura de tela 2017-04-03 as 09 26 56](https://cloud.githubusercontent.com/assets/26870657/24609159/1930f3d0-1850-11e7-9623-a3ecd54a3a82.png)

**Comment by luclu** [comment]
Hi @lordofangels, the percentage only refers to the current synchronization session, thus with ~1mil blocks left (on mainnet) your node is already over 70% synced (as in the full size of the chain).
So you should be alright, no need for any user interaction.

**Comment by lordofangels** [comment]
Thank you @luclu. I have another question: how do I do to "find the blockchain" in my Hard Disk? Mac OS X. Or the path to it?
