### ISSUE TITLE
etherum problem

### ISSUE THREAD

**Issue by kimoatef** [ethereum/mist#2112]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files 
 

i got a transaction from a mining site but my account balance still  saying balance equal zero plzz hellp  
![capture](https://cloud.githubusercontent.com/assets/26902557/24663136/559da978-1957-11e7-8b39-b0723bec293f.PNG)
![3](https://cloud.githubusercontent.com/assets/26902557/24663158/68f16a50-1957-11e7-838c-56b5e495e076.PNG)

**Comment by garretlaxton** [comment]
You need to let the wallet fully sync before you'll see your ETH.

**Comment by luclu** [comment]
Thank you @garretlaxton!
