### ISSUE TITLE
Missing Ethereum from my Wallet

### ISSUE THREAD

**Issue by movaisgaditek** [ethereum/mist#2113]
I initiated a transfer from BTC to ETH but before I could make a transfer, the transaction expired on Mist and now I have lost BTC and ETH did not arrive into my account.

**Comment by luclu** [comment]
@movaisgaditek some generic advice:

Please, make sure you are running the [latest version](https://github.com/ethereum/mist/releases) and your node is **fully** synced.
Although this may take between 1h (SSD) and 10 hours (HDD) you should be able to see a progress bar on the *splash-screen* or in the *main-window*.

Further recommendations: 
- check your account's balance using http://etherscan.io
- make a backup of all account's keyfiles via `menu -> accounts -> backup -> accounts`
- should the initial sync take very long, consider following [these instructions](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569) to speed it up
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com in the meantime

If this didn't solve your issue, please follow [these instructions](https://github.com/ethereum/mist/issues/new) and upload the `node.log` files:
> - Log files
>   - go to menu -> accounts -> backup -> application data
>   - zip and upload node.log and all other node.log.X files

**Comment by skrzynip** [comment]
0x69c77c5866faac8ab9e66af59bbbd213ae0eff37a0534240d8d98dd0dfe1138c
sent 31 eth and now the transaction is nowhere to be found and i am out 31 ETH
![image](https://cloud.githubusercontent.com/assets/15710571/24973044/3a76a098-1f72-11e7-8b22-9050a30936ea.png)

**Comment by skrzynip** [comment]
i zipped up the logs and cant post them here.

**Comment by movaisgaditek** [comment]
Luclu,

I checked the account balance and it is reflecting the correct balance.

What I did before reading your comments is that is I cleaned up the chain data files and let the wallet update. Right now I see that even the coins which I had earlier in my wallet are gone.

I then downloaded the latest version of the wallet and let it synced completely, but even then the number of coins in my wallet did not move from zero and now the coins which I had earlier as well are gone.

Could you please advise if I should continue to use the old version and let it sync completely? Or I should move to the updated wallet. In any case, I would also like to know how am I supposed to get my coins back in my wallet.

**Comment by movaisgaditek** [comment]
I deleted my chain data and tried updating my wallet again. It is now close to getting completely updated and yet there are no signs of my ETH. Although the balance is reflected in my account balance using http://etherscan.io but no sign of coins in my wallet.

Is there a remedy to it like I can get my coins somehow to the brand new wallet?

**Comment by skrzynip** [comment]
this is some awesome support. fuck ETH and the team. i lost over $1k in ETH and the stupid ethereum project site tell me to go here for help. waiting for 4 days to hear from anyone about what happen to my transaction, why it disappeared and where is my 31 ETH. fuck ETH never going anywhere with this support. going back to BTC and burstcoin.
