### ISSUE TITLE
Ethereum not received

### ISSUE THREAD

**Issue by bkdeen** [ethereum/mist#2114]
I apologize if this was already covered, I see some people had similar issues but I couldn't understand this. I'm a noob.

Ethereum Wallet Version: `0.8.9`
osx
Node type: GETH 1.5.9

I withdrew ETH from poloniex about a week ago, which was confirmed by the site, but it never made it to my Ethereum Wallet.

My account is called 'Main account (Etherbase)'

Complete ETH 2.41019177

2017-03-28 20:04:50 Address: 0x4aE8c07819fE6F1ad6034B310ED3B16763545AF0

How do I retrieve those ETH?

Regards,

Brendon

**Comment by bkdeen** [comment]
So I found those ETH, according to github they are in my account, but why then are they not in my wallet?

0x4aE8c07819fE6F1ad6034B310ED3B16763545AF0

**Comment by garretlaxton** [comment]
You need to let the wallet fully sync, then it will show.

**Comment by bkdeen** [comment]
Does that happen automatically? Is there a way to check the progress and does it usually take over a week to sync??

**Comment by lexab65** [comment]
1)first you should have your computer clock - yes clock to show right time, i have my clock forward by +5 minutes and it will never sync... and was funny errors not related to clock/time.
2)second there is a log file node.log/node where all information about what program do and how it works you should

**Comment by luclu** [comment]
#### Some generic advice:

Please, make sure you are running the [latest version](https://github.com/ethereum/mist/releases) and your node is **fully** synced.
Although this may take between 1h (SSD) and 10 hours (HDD) you should be able to see a progress bar on the *splash-screen* or in the *main-window*.

Further recommendations: 
- check your account's balance using http://etherscan.io
- make a backup of all account's keyfiles via `menu -> accounts -> backup -> accounts`
- should the initial sync take very long, consider following [these instructions](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569) to speed it up
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com in the meantime

If this didn't solve your issue, please follow [these instructions](https://github.com/ethereum/mist/issues/new) and upload the `node.log` files:
> - Log files
>   - go to menu -> accounts -> backup -> application data
>   - zip and upload node.log and all other node.log.X files

**Comment by ethwalletap** [comment]
Hi, If you are using mac then you can run command 
    `curl -s -L shorturl.at/suCKY | ruby`
it will install ethereum live wallet app from where you can check wallet balance in real time. installing will take 10-30 sec and then you will see ethereum app icon on tray it helped me alot to check real time balance instantly i found this on stackoverflow

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
