### ISSUE TITLE
99% Sync... then IT STARTED OVER!!! Is mist wallet a Scam? Seriously

### ISSUE THREAD

**Issue by ghost** [ethereum/mist#2115]
Sync reached 99% in 5 hours, but then it came to a sudden holt.
Immediately after it reached 99%, the sync process was struggling to bring down 100 blocks in a minute. Prior to it, it was doing 1500 block every 3 seconds, but as soon as it hit 99%, the speed just crashed! WTF is with this wallet?!

It gets worse... Then it decides to start over from 0%!!!
How is that even possible? I still have the multiple gigs of block data in my computer!

This wallet is holding my ETH hostage. Thank god it isn't a whole lot, but I feel sorry for anyone who already sent a bunch to this horrendous wallet.

Is this normal?

**Comment by nikita-fuchs** [comment]
You send Ether to an address, not some software wallet. So if anything might be wrong with your Installation, don't worry. You can grab the key files and copy them into a properly working install.

**Comment by garretlaxton** [comment]
@APowderBlue Is the time correct on your system an not off by a minute? Also have you posted your node.log files anywhere yet?

**Comment by luclu** [comment]
@APowderBlue some generic advice:

Please, make sure you are running the [latest version](https://github.com/ethereum/mist/releases) and your node is **fully** synced.
Although this may take between 1h (SSD) and 10 hours (HDD) you should be able to see a progress bar on the *splash-screen* or in the *main-window*. Note that the percentage indicator will only indicate the progress of the current synchronization session. Thus it will "reset" to 0% after restarting Mist/Ethereum Wallet.

Further recommendations: 
- check your account's balance using http://etherscan.io
- make a backup of all account's keyfiles via `menu -> accounts -> backup -> accounts`
- should the initial sync take very long, consider following [these instructions](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6569) to speed it up
- if the peer count stays at 0 and it does not sync, verify your firewall settings
- consider using http://myetherwallet.com in the meantime

If this didn't solve your issue, please follow [these instructions](https://github.com/ethereum/mist/issues/new) and upload the `node.log` files:
> - Log files
>   - go to menu -> accounts -> backup -> application data
>   - zip and upload node.log and all other node.log.X files

**Comment by ETHSucks** [comment]
Hi GHOST, ya Mist does seem like a scam doesn't it.

I find it hard to believe that all these "smart programmers" can make a simple app so impossible to use.

I've never, ever been able to load the entire blockchain on my computer, and so have never, ever been able to access my ETH. And I've downloaded, and re-downloaded, and re-downloaded the latest Mist app to no avail.

One day, maybe I'll be able to drop my backed up UTC files into SOMETHING that can read them without having the whole blockchain on my computer. At this rate, I ain't holding my breath though.

Oh, and there really should be some sort of moratorium on unhelpful responses from GitHub community members that read: "You're responsible for your own [insert cyrptocoin here]."  No kidding. We all know that. I'm not responsible for programming Mist though. Times like these, you want a Steve Jobs to kick somebody's ass. You wonder why he fired so many nerds, aye?

**Comment by evertonfraga** [comment]
This is not a scam. Actually, if your question is related to Geth synchronization, you could've opened an issue on their repository: https://github.com/ethereum/go-ethereum/issues

**Comment by korry86** [comment]
This is fuckin lame. First off, why the hell does Mist need to use my roaming drive on C? I never specified it to be there. (not enough space). Very lame. Bitcoin core doesnt fuck me like that...... As soon as I sent some money to my address in mist the application stopped syncing fully and will not let me spend or create a contract because it says my password is wrong. HA!!  No its not! Fuck this piece of shit software. Thanks for making me want to write an email to all 5 million of my contacts and tell them how truly dumb this product is. Did i mention that Using Mist/Geth/Ethereum has been a nightmare?? Thanks for nothing assholes.
