### ISSUE TITLE
Etherum Walet sync problem

### ISSUE THREAD

**Issue by zolkom** [ethereum/mist#2116]
#### System information
``````
Version: `0.8.9`
OS & Version: linux
Node type: `eth
``````

I have problem with synchronising Etherum Walet, since weeks now I think.
I have sent some Eth, my my EtherumWallet, but as I understand correctly, ETH will not arive into my wallet if there Etherum Wallet will not fully synchronise with network. I have tryied Linux and Windows version, but on neither one I'm not able to synchronise it always stuck and few %. 
Please assist or let me know how I can recover my ETH which was sent to Etherum Wallet address.

Regards
Michael

**Comment by Stealth-Ether** [comment]
I have this problem too. Sent small amounts twice now and not showing up in my wallet.
Shifty have went through the transaction and confirmed both went.

So cn nyone on the ethereum project let me know how to sync my wallet to show the funds or does it start getting a bad name by not answering help requests?

**Comment by luclu** [comment]
@zolkom in case you are currently using the `eth` node as you stated in the system information, please switch to `geth` as `eth` is currently now supported and will be removed from Mist/Ethereum Wallet until the `eth` team releases a updated, working version.

**Comment by Stealth-Ether** [comment]
Well mine showed up in my wallet after a full blockchain sync. Moral of the story? Be patient and wait. Sorry guys.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
