### ISSUE TITLE
Unable to create a wallet contract. Pl help asap. I just purchased ethereum coins on bitpanda on my account address. But it is not reflecting in my wallet as the wallet contract is not getting created. 

### ISSUE THREAD

**Issue by kalyanmeduri** [ethereum/mist#2118]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by garretlaxton** [comment]
Has your wallet fully synced? Also have you checked etherscan.io to see if your coins are in your account?

**Comment by kalyanmeduri** [comment]
No, I am unable to create a wallet contract. Can you pl check and help me
create a wallet contract. I need this to store my ether I purchased at
etherscan.io.

Thanks

Best Regards
Kalyan
0643953379


<https://in.linkedin.com/pub/kalyan-shankar-meduri/0/a64/b07>

Everything u've ever wanted is on d other side of fear. *Do it !!!*

**Comment by garretlaxton** [comment]
You don't need to create a contract to receive ETH. You just need to let your wallet fully sync, once it's complete your ETH will reflect in your wallet then you can send it.

**Comment by kalyanmeduri** [comment]
I am sorry I synced but it is still not reflecting in my ehtereum wallet.
Can you pl help me?


<https://in.linkedin.com/pub/kalyan-shankar-meduri/0/a64/b07>

Everything u've ever wanted is on d other side of fear. *Do it !!!*

**Comment by garretlaxton** [comment]
Do you see your ETH in your account on etherscan.io?

**Comment by kalyanmeduri** [comment]
Yes I see in etherscan but not in ethereum wallet :(

**Comment by garretlaxton** [comment]
If you see the transaction & the ETH in your account on etherscan.io, you most likely haven't let your wallet fully sync. 

What I would recommend you do is provide a screenshot of your wallet & post your node.log files.

**Comment by kalyanmeduri** [comment]
Pfa screenshot of my wallet:
[image: Inline image 1]

[image: Inline image 2]

Attaching node.log files below. Can you pl help me get my ether in my
wallet? thanks




<https://in.linkedin.com/pub/kalyan-shankar-meduri/0/a64/b07>

Everything u've ever wanted is on d other side of fear. *Do it !!!*

**Comment by kalyanmeduri** [comment]
Awaiting your feedback on my wallet sync issue.

Best Regards
Kalyan


<https://in.linkedin.com/pub/kalyan-shankar-meduri/0/a64/b07>

Everything u've ever wanted is on d other side of fear. *Do it !!!*

**Comment by kalyanmeduri** [comment]
No response yet. Very poor customer service on ethereum, which explains why the pace of investment is not as strong as on bitcoins.

**Comment by kalyanmeduri** [comment]
Hi
Can you pl help me cancel my transaction and get my money back at the
existing ether price. Nobody from mist / ethereum seems to be able enough
to help me fix it. I want to tap out of this mess now. Can you pl help?
Best Regards
Kalyan


<https://in.linkedin.com/pub/kalyan-shankar-meduri/0/a64/b07>

Everything u've ever wanted is on d other side of fear. *Do it !!!*

**Comment by evertonfraga** [comment]
@kalyanmeduri It seems your previous messages aren't complete. No images or node.log were uploaded.

Without those information, it's more likely that your wallet hasn't synced until the transaction you've made. And you don't need to create a wallet contract in order to receive ether. an account already does the job.

**Comment by kalyanmeduri** [comment]
Pfa attachments again. Alternatively, can you pl help me cash out of
ethereum in any other way. I am not interested in investing in ethereum
considering the poor quality of response / support

<https://in.linkedin.com/pub/kalyan-shankar-meduri/0/a64/b07>

Everything u've ever wanted is on d other side of fear. *Do it !!!*

---------- Forwarded message ----------
From: Kalyan Meduri <kalyanmeduri@gmail.com>
Date: Tue, Apr 11, 2017 at 1:07 PM
Subject: Re: [ethereum/mist] Unable to create a wallet contract. Pl help
asap. I just purchased ethereum coins on bitpanda on my account address.
But it is not reflecting in my wallet as the wallet contract is not getting
created. (#2118)
To: ethereum/mist <
reply@reply.github.com
>
Cc: ethereum/mist <mist@noreply.github.com>, Author <
author@noreply.github.com>


Pfa screenshot of my wallet:
[image: Inline image 1]

[image: Inline image 2]

Attaching node.log files below. Can you pl help me get my ether in my
wallet? thanks




<https://in.linkedin.com/pub/kalyan-shankar-meduri/0/a64/b07>

Everything u've ever wanted is on d other side of fear. *Do it !!!*

**Comment by luclu** [comment]
@kalyanmeduri you will need to use the web frontend of github.com to upload attachements.

**Comment by kalyanmeduri** [comment]
[Files.zip](https://github.com/ethereum/mist/files/949283/Files.zip)
Uploaded my node logs from web frontend. Can you pl check and help my wallet sync up completely? Thanks

**Comment by kalyanmeduri** [comment]
[Files (1).zip](https://github.com/ethereum/mist/files/949309/Files.1.zip)
Sorry pfa zip file with all node files. Thanks

**Comment by kalyanmeduri** [comment]
Can you access the log files now? and let me know why my ethereum has not synced not even once yet?

**Comment by kalyanmeduri** [comment]
Today even my ethereum node stopped getting connected :( It is gone worse from bad. Can anyone help. This is pathetic !!!
![image](https://cloud.githubusercontent.com/assets/13646701/25447004/b9a6f362-2ab3-11e7-9532-e8e2de068e73.png)
![ethereum node connection error](https://cloud.githubusercontent.com/assets/13646701/25447018/c660c36c-2ab3-11e7-898f-e22607d91c7f.jpg)

**Comment by garretlaxton** [comment]
You can upload your backup file here https://myetherwallet.com/ & send it.

**Comment by kalyanmeduri** [comment]
Can you please share exact link and format of backup file I need to upload?
Thanks


<https://in.linkedin.com/pub/kalyan-shankar-meduri/0/a64/b07>

Everything u've ever wanted is on d other side of fear. *Do it !!!*

**Comment by kalyanmeduri** [comment]
Yes I could finally see my wallet info. How can I convert it into Euros?

**Comment by sushilraghav** [comment]
@kalyanmeduri @garretlaxton @evertonfraga @luclu @fjl  ///   How much money you charge or Is there someone who can help me or can create a cryptocoin based on ETH Fork or BTC Fork or X11 or IOAT Fork ? Contact me at skype : sushilraghav or email is bitcoinemxmx@gmail.com.

**Comment by evertonfraga** [comment]
You should use a crypto exchange for that. I can't recommend any, but it's easily findable on google.
