### ISSUE TITLE
My wallet never updates !!!

### ISSUE THREAD

**Issue by af71229** [ethereum/mist#2119]
I extremelly disappointed with this wallet I left my notebook for more than 24hs updating the blocks, but after reach 99% the app came back to 0% and my wallet wasn t update and still with 0 ETH. I received the blockchain line and I can check the transation there but I can t see it on my notebook wallet. What can I do ?
Tks
Alessandro.

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by garretlaxton** [comment]
Is your time correct on your system and not off by a minute? I've seen many peoples time off by a small amount & it doesn't sync properly. Also, post your `node.log` files.

**Comment by af71229** [comment]
I ve checked my time and difference is something around 6 or 7 seconds, now
nothing more than 1 second than a "official time". Im attaching all the
node logs. If I need to do anything else let me know.
Tks !
AF



2017-04-08 21:39 GMT-03:00 garretlaxton <notifications@github.com>:

**Comment by af71229** [comment]
Hi Guys,
     I still with the same problem . Is there any other workaround to sync
my desktop wallet ?
Tks
AF

2017-04-10 14:54 GMT-03:00 Alessandro Figueiredo <
alessandro.figueiredo@gmail.com>:

**Comment by evertonfraga** [comment]
Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.
