### ISSUE TITLE
'Intrinsic Gas Too Low' error when executing default contract from Mist Wallet

### ISSUE THREAD

**Issue by Bschuster3434** [ethereum/mist#2122]
#### System information
``````
Version: `0.8.9`
OS & Version: Windows
Node type: `eth/geth(default)`
``````

I am attempting to create a custom token on the main network using the standard code available through the mist browser. When I execute the contract, I get an error, stating "Intrinsic Gas Too Low". I have attempted to raise the fee to the highest level in the IDE, but I still get this error.

What is the work around for this particular issue?

**Comment by luclu** [comment]
@Bschuster3434 could you please describe the exact steps to reproduce this issue?

**Comment by Bschuster3434** [comment]
Actually, I just attempted to do the custom token when I noticed I made a change to the code. I thought I was just changing a name, but apparently I did something to cause it to error out.

I'll review my code and close this issue. Thank you.
