### ISSUE TITLE
Can't mine on Test-net - 0.0 KH/s always

### ISSUE THREAD

**Issue by PatchRanger** [ethereum/mist#2132]
#### System information
``````
Version: `0.8.9`
OS & Version: linux (Xubuntu 16.04)
Node type: `mist`
``````

Neither already existing issues nor [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide) helped.

After I enable Mining on Test-net mining is able to start but seems to be not working:
- Mining icon appears but always shows "0.0 KH/s"
- Waiting for 20 minutes doesn't help at all, nothing changed - am I supposed to wait more?
 
Attached logs: 
[2132.zip](https://github.com/ethereum/mist/files/913120/2132.zip)

**Comment by luclu** [comment]
@PatchRanger unfortunately CPU mining on the "Ropsten" Testnet is not feasible anymore due to the past attacks. We will update the menu to remove the entry soon.

For now you could use a faucet like http://faucet.ropsten.be:3001/ to get some Testnet Ether.

**Comment by PatchRanger** [comment]
@luclu Thank you for your answer. Please don't remove entry before reading my comment!) I left my notebook for a whole night with mining turned on - and now I have 20,014.79 Finney ~= 20.01 Ether. Also I've noticed that mining power (at bottom left corner) showed 30-60 KH/s - I don't know whether it is high or low for my environment. Looks like it is still works somehow - no idea how)
My issue is solved - so I think it is time to close the issue. Nevertheless I want the situation about mining at Test-net to be clarified: is it really working or not?)

**Comment by luclu** [comment]
Currently the UX when mining on the ropsten testnet is bad. This is due to the previous GPU mining attacks. Altough they ended the network is currently secured by honest GPU miners, making CPU mining (as Mist is capabale of) extremely difficult.
I created https://github.com/ethereum/mist/issues/2138 to track the progress on the UX aspect.

**Comment by PatchRanger** [comment]
Ok, got it, thank you.
