### ISSUE TITLE
Link to txns on testnet are wrong

### ISSUE THREAD

**Issue by GriffGreen** [ethereum/mist#2133]
<img width="578" alt="screen shot 2017-04-11 at 1 30 48 pm" src="https://cloud.githubusercontent.com/assets/14945613/24929563/3ed7d7c2-1ebb-11e7-89a3-1044c4de7745.png">

this link and probably all links on https://wallet.ethereum.org/ for the testnet need to change from: 

https://testnet.etherscan.io/[blah blah blah]

to

https://ropsten.etherscan.io/[blah blah blah]

Love you guys, thank you soooo much for making Ethereum contracts fun to use!

Hugs and kisses!
Griff

**Comment by luclu** [comment]
Muchas muchas muchatsas!! >D
