### ISSUE TITLE
Can't send any Ether? 

### ISSUE THREAD

**Issue by k1ngsta** [ethereum/mist#2134]
i'm totally new to this, but i bought 1.00 Ether over a year ago and now want to send it to another wallet. But everytime i get "Unable to connect to socket: timeout" when i press "Send". Sometimes the window pops up where i have to type my password, but meanwhile it disconnects or somesthing in the backround.

THANKS

edit: couldn't connect node to IPC comes when i need to type in password
"CONNECTION ERROR: Couldn't connect to node on IPC."

#### System information
``````
Version: `0.8.9`
OS & Version: windows 7
Node type: `default ethereum wallet`
``````

-

**Comment by k1ngsta** [comment]
anybody active here? do you guys need more information?

**Comment by renwang1612** [comment]
Hi, I was just experiencing the same issue and saw this. I then figured out through trial and error:
After sync and the mist GUI popped up, you need to click on the account which holds your ETH. There is a line underneath in this account, asking you to create a wallet contract. 
I then send from my account (somehow the wallet just need to be created but the actual account is used) to my destiny wallet address. I was prompted to enter the password I set a year ago. 
I did a few transactions to make sure. And encountered the IPC error once, so closed the app and reconnected. It then worked again.
Each transaction was shown in the app, where 12 out of 12 confirmation from other nodes are required. It took a few minutes each. 
Finally, the coins show up in my coinbase as pending, and I think it's successful.

**Comment by renwang1612** [comment]
Just a side note: you need to use some ETH as transaction fees.

**Comment by LancerLunatic** [comment]
I realized this from trial and error as well.
