### ISSUE TITLE
Failed to start Ledger hub, disabling: libusb: not found [code -5]

### ISSUE THREAD

**Issue by Ksuleyman** [ethereum/mist#2135]
#### System information
``````
Version: `0.8.9`
OS & Version: windows 10
Node type: geth
``````

If possible add the following to your report:

- Screenshots
![image](https://cloud.githubusercontent.com/assets/27309710/24932457/4e1aaa52-1f1a-11e7-8c4e-6dd8aa580ccf.png)

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

I0412 00:47:55.824374 node/config.go:445] Failed to start Ledger hub, disabling: libusb: not found [code -5]
I0412 00:47:55.895927 cmd/utils/flags.go:613] WARNING: No etherbase set and no accounts found as default
I0412 00:47:55.895927 ethdb/database.go:83] Allotted 1024MB cache and 1024 file handles to C:\Users\Krasimir\AppData\Roaming\Ethereum\geth\chaindata
I0412 00:47:55.912938 ethdb/database.go:176] closed db:C:\Users\Krasimir\AppData\Roaming\Ethereum\geth\chaindata
I0412 00:47:55.913939 node/node.go:176] instance: Geth/v1.5.9-stable/windows/go1.7.4
I0412 00:47:55.913939 ethdb/database.go:83] Allotted 1024MB cache and 1024 file handles to C:\Users\Krasimir\AppData\Roaming\Ethereum\geth\chaindata
I0412 00:47:56.092841 eth/backend.go:187] Protocol Versions: [63 62], Network Id: 1
I0412 00:47:56.092841 eth/backend.go:215] Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000}
I0412 00:47:56.093841 core/blockchain.go:219] Last header: #0 [d4e56740…] TD=17179869184
I0412 00:47:56.093841 core/blockchain.go:220] Last block: #0 [d4e56740…] TD=17179869184
I0412 00:47:56.093841 core/blockchain.go:221] Fast block: #0 [d4e56740…] TD=17179869184
I0412 00:47:56.094843 p2p/server.go:340] Starting Server

- Log files

**Comment by Discov3ry** [comment]
I have the same error in the log file "Failed to start Ledger hub, disabling: libusb: not found [code -5]". When I first start the Ethereum Wallet, the blocks start to move and I get connected to some peers (like 3 usually) and then it gets stuck at 2%. I have already tried the fast method of synchronization by removing the "chaindata" folder, but did not help. Also I checked the console and I got two errors, both "Failed to load resource: net::ERR_FILE_NOT_FOUND", which I read, that I should ignore. So to me it looks like the problem is with the node.

**Comment by DanCassidy** [comment]
Is there any further advice on this issue as I'm getting exactly the same issues and log file entries as Ksulyman, with no peer connection or block movement.
Fresh Install, Win 8.1, running Mist for the first time.
[node.log.zip](https://github.com/ethereum/mist/files/956910/node.log.zip)

**Comment by Discov3ry** [comment]
Hey, what I did is download and instal geth 1.6 and that fixed the problem. I did a fresh new sync from 0.

**Comment by drodsou** [comment]
The 32 bit installer on the main page of Ethereum.org was giving me this error. Uninstalled and installed the 64 bit version in https://github.com/ethereum/mist/releases and all just went ok.

**Comment by evertonfraga** [comment]
Mist spawns a Geth instance, responsible for syncing with the blockchain and signing transactions. Please refer to their repository in order to get help directly from the source.

https://github.com/ethereum/go-ethereum
