### ISSUE TITLE
Etherum Walet sync problem

### ISSUE THREAD

**Issue by TheGreatWhatsIt** [ethereum/mist#2139]
#### System information
``````
Version: 0.8.9
OS & Version: windows
Node type: geth
``````
According to the Logs the Ledger Hub fails. From there it doesn't seem to connect to network and my peers stay at 0. I tried renaming chaindata folder to prompt a refresh of the blockchain, but it doesn't work.

I also notice that in several areas the address is presented in all lowercase, but in the main account screen my address is mixed case like I'd expect.

![image](https://cloud.githubusercontent.com/assets/6682253/24968021/e0dce7ba-1f79-11e7-92d0-0878ed22fae1.png)

[node.log.zip](https://github.com/ethereum/mist/files/917187/node.log.zip)

**Comment by evertonfraga** [comment]
Please try this guide. It may have something to do with your router settings.
https://github.com/ethereum/mist/wiki#unable-to-find-peers

Make sure to update to latest software.

> I also notice that in several areas the address is presented in all lowercase, but in the main account screen my address is mixed case like I'd expect.
This does not pose any problem.

I am closing this for now, feel free to reopen.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
