### ISSUE TITLE
When sending tokens, the amount of tokens get added to the estimated fees

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/mist#214]
https://ipfs.pics/Qmc9tZBpgHVcQRhXev3HxN1yjUwXJaGKJeN1ArK7kVrRM6

**Comment by frozeman** [comment]
@alexvandesande maybe something you changed?

**Comment by alexvandesande** [comment]
Will take a look at that bug

On Mon, Feb 29, 2016 at 7:14 AM, Fabian Vogelsteller <
notifications@github.com> wrote:

> @alexvandesande <https://github.com/alexvandesande> maybe something you
> changed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/mist/issues/214#issuecomment-190139919>.
>



-- 

Alex Van de Sande
UX Designer
