### ISSUE TITLE
Wallet fails to launch with SSD as datadir

### ISSUE THREAD

**Issue by jdsutton** [ethereum/mist#2147]
#### System information
``````
Version: 0.8.9
OS & Version: Linux Mint 18 Cinnamon 64-bit 3.0.7
Node type: geth
``````

The wallet was not making any sync progress even with 13 peers. Following some advice I read, I re-generated the blockchain on my SSD using `geth --fast` and tried to launch the wallet using this data. 

Here are the results of trying to run ethereumwallet with data from the SSD: https://pastebin.com/MtV5SwXp

And here are the logs: https://pastebin.com/LX1iwPdS

**Comment by alexvandesande** [comment]
Have you tried the sync with light client on version 0.10? It's much better now. Also, if you want to change geth settings and datadir then it becomes almost as much geth troubleshooting as Mist's
