### ISSUE TITLE
Sending ETH, UI improvements

### ISSUE THREAD

**Issue by faraggi** [ethereum/mist#2149]
Mist keeps a config file with addresses names which we've changed manually. This is a great UI feature, and really helps human-readability.

When sending ETH from one account to another, ideally, if the address already has a name:

- choose from a dropdown list to the address we want to send (like when choosing the from address)
- if we copy paste the address and it is known, show the internal name.

I believe this will help a lot. Currently the UI makes doing simple inter-account transfers complicated and copy pasting send addresses and form addresses passwords back and forth.

current screenshot:
http://imgur.com/a/WIXNq

basic mockup:
http://imgur.com/a/iGxma

**Comment by evertonfraga** [comment]
It is a good suggestion, it's on our radar.
