### ISSUE TITLE
Wrong master password

### ISSUE THREAD

**Issue by Erchard** [ethereum/mist#215]
I'm created account.
When i input master password programm say "Wrong password"
I'm created other one account. 
But too "Wrong password"

**Comment by donald-circuit** [comment]
Same here: "Wrong password" if I want to generate a Wallet contract. I have only the main account yet.
If I use the command line geth interface, I can unlock the wallet successfully with that password.
Any idea what is wrong with mist?

**Comment by donald-circuit** [comment]
I also checked: I can send transaction using the geth Javascript console. So at least my ether are not lost.
But when trying to do a transaction using mist: "Wrong password". I use win64 version 0-4-0
My password ist 40 characters long, has lower and upper characters, numbers and a "." and a ",". Is that a problem? I tried both copy & paste and typing it manually... Always the same.
So ein Mist ;)

**Comment by donald-circuit** [comment]
I found the solution:
I had given my account a name like "My_account". Now I changed the account name to the eth address and voila: I can send transactions!
PLEASE FIX THIS BUG! Thanks!

**Comment by frozeman** [comment]
I'm pretty sure this is not fixing any issue :)
But i assume there is a problem with mist and the connection to the node. Please try the new version coming.

**Comment by donald-circuit** [comment]
You might be right. I changed back to the other name, and it is still working. From now on it seems to work... but this is a bit discomforting -_-

**Comment by nimchak** [comment]
I created an account with a complex password 65 Characters long.  I then created a wallet contract and sent the account funds to the wallet contract. Now when I try to send money out of the wallet contract I get incorrect password.  Would this be the account password?
Please fix :'''(

**Comment by nimchak** [comment]
I restored an older version of the client and was able to perform my transaction.  Seems to be an issue with version 0.4

**Comment by frozeman** [comment]
We will release a new version very soon, please check with this one then

**Comment by frozeman** [comment]
please try the latest release

**Comment by capthowdyaur** [comment]
Yesterday i downloaded Mist ,  but i have no password for the Main Account !!(never created it myself, now i got 1.99ETH on that account and cannot send it anywhere because it asks for password . i created a second account , for which i got my password written down.

**Comment by capthowdyaur** [comment]
Please help !!

**Comment by frozeman** [comment]
@capthowdyaur you definitely created it at some point. Maybe you had a geth node installed before. Please try to remember your password you used back then.

Also try restarting as sometimes the unlocking functionally breaks on windows.

**Comment by Jukebox99** [comment]
Have "wrong password" message, when trying to send coins. 
Used 0.3.8 from start, have correct transactions to poloniex.
Tried to use 0.4.0, 0.5.1 bilds.
Rebooted many times.
Tried to use wallet on notebook. 
Used different internet providers. 

Error stay the same. Balance is shown correct.
Password starts with " symbol - can it be the reason?

**Comment by luclu** [comment]
Please have a look at this and report back here! #669

**Comment by luclu** [comment]
I will close this for now, but will stay here to assist you in problems regarding Mist/geth.
Also make sure to try this update of #669:
> if you still can't unlock your account try this service: https://www.myetherwallet.com (they implemented a "wallet viewer" following the official wallet-specs; it's client-side; source-code)

**Comment by ihatecreatingaccounts** [comment]
frozeman you fucking retard, youre playing with other peoples money here, just look how many people lost their money bc of passwords they didnt set...
seems to be ALWAYS the users problem as he forgets the passwords,.....
youre working for jihan, right? fucking thief and saboteur.
aber hey, berlin ist nicht weit, ein metallbasi kostet nicht viel.
vll fahr ich mal ein problem fixen
