### ISSUE TITLE
Very slow sync with 1 or 2 peers on iMac

### ISSUE THREAD

**Issue by More-decentral** [ethereum/mist#2151]
Since the latest version 0.8.9 update, my Ethereum wallet syncs very slow with only 1 or two peers connected even after 30 minutes running.

Any solutions beside re-downloading the whole chain?  Thank you.

#### System information
``````
Version: `0.8.9`
OS & Version: macOS Sierra version 10.12.14
Node type: `geth node 1.5.9 (go)`
``````

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Geth 1.7.0 and Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
