### ISSUE TITLE
ShapeShift does transfer my ethers to my ether wallet.

### ISSUE THREAD

**Issue by mertimiks** [ethereum/mist#2153]
I funded my ether wallet with $15 worth bitcoin yesterday, where ShapeShift.io receives my bitcoins, converts to ether, and then transfers to my ether desktop wallet. But I did two seperate transactions yesterday, first one 5 dollars worth, and today 10 dollars worth, but non of them were transferred to my ether wallet. So what is going on?

![capture](https://cloud.githubusercontent.com/assets/19364945/25114626/9b7d0400-2408-11e7-9447-a914f1de3ad0.PNG)

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment]
Hello @mertimiks. Using a blockchain explorer, I can see that you have those funds secured: https://etherscan.io/address/0xe5631f191158a7d9c5baab5638ed24ce4e9bd850

In order to see balances and transact with ethereum network, your Mist should be synced.

**Comment by mertimiks** [comment]
one more question, why sometimes I receive this error when I open my
wallet? thanks

Best regards,

Mert Konrat

**Comment by vandergone** [comment]
In order to see balances and transact with ethereum network, your Mist should be synced.? how do i do that?
