### ISSUE TITLE
Where is my ethereum? Please help

### ISSUE THREAD

**Issue by frenzy1980** [ethereum/mist#2157]
#### System information
``````
Version: `0.8.9`
OS & Version: windows 10
Node type: `eth/geth(default)`
``````

Hi ,

the Wallet doenst want to sync properly and only finds up to 4 peers. I've already deleted the chaindata, left the pc on over night, but the download stoped at 3484166 blocks. Please help me.

Node Logs and Screenshots of the wallet are attached.

![wallet](https://cloud.githubusercontent.com/assets/27759044/25165459/f0eb215a-24d6-11e7-8f97-8838135cc182.png)
![wallet2](https://cloud.githubusercontent.com/assets/27759044/25165498/20e37178-24d7-11e7-9c5c-c8f4e8c7b483.png)
[Ethereum Wallet node log.zip](https://github.com/ethereum/mist/files/931974/Ethereum.Wallet.node.log.zip)

**Comment by frenzy1980** [comment]
Here is the prove btw, that it should be transfered:

https://etherscan.io/address/0x4d94C24fadEef1Cd96e08A50466d7316f0dB18Bb

**Comment by Tungsten69** [comment]
I am having the same problem. My ether doesn't appear and Sync stops at 1%. What to do?

**Comment by louisbala** [comment]
I am having the same problem, with the same 0.8.9 version.

Here you can see my transactions:
 https://etherchain.org/tx/0xbee8a3557c3a8b5fd361fe6ee8d57b29f9e44d1fe59209639417a051ba98c22a
 https://etherchain.org/tx/0x0426b52a5e3491c51792574a1935485d271db3d5812742140d7a9836cd3cc620

The amount is not in my account, as you can se in the attached screenshot.
![ethereum](https://cloud.githubusercontent.com/assets/4193770/25432620/877b27da-2a5b-11e7-8847-df21ee52cf19.png)

**Comment by DustinWehr** [comment]
@frenzy1980 @Tungsten69 @louisbala I had the same problem. Transferring to a myetherwallet.com wallet was not hard. You'll use the file that you get to through Accounts --> Backup --> Accounts

**Comment by frenzy1980** [comment]
DustinWehr Sound interesting. I would like to have more details.

Best regards

Francois

**Comment by vandergone** [comment]
where is my ethereum? https://etherscan.io/tx/0x2808e70c727764ad193eaedfd62c25912f713c574436902fa185bff87ba2ce68
help me pls :)

**Comment by DustinWehr** [comment]
@frenzy1980 @vandergone in retrospect there isn't actually a need to transfer your coins to a new address, provided you still have your password-protected wallet file on your hard drive, and the password you used to encrypt it. The file name for mine starts with "UTC" and contains a long random looking string.

You can verify that you have control over your coins by transferring a small amount to some address, e.g. one of the donation addresses for some ethereum project. Note they have the  https://myetherwallet.com/#offline-transaction option if you don't want to have to trust the myetherwallet developers. I used the simpler https://myetherwallet.com/#send-transaction

**Comment by frenzy1980** [comment]
Hi Dustinwehr,

thank you very much for helping and sorry for asking further questions, but I dont fully understand it yet. I do not have any ether on my etherium wallet. So I cant verify, that I have control over my account. So do I just copy and paste the old File into myetherium wallet?

Could you maybe bring more detail in it by telling us step by step?

Best regards

Francois

**Comment by evertonfraga** [comment]
@frenzy1980 yes, you can access https://myetherwallet.com, and follow the instructions to quickly move your funds and test passwords.
