### ISSUE TITLE
Payments do not appear in the Wallet

### ISSUE THREAD

**Issue by rycky21** [ethereum/mist#216]
Hi 
The internal payment etherbase on the wallet works well.
External payment does not appear in wallet

Payments do not appear in the Wallet
Tx: 0x7558d829829affc6072fa74c586b8e0eefcd95aeb2a17b5056f13008b1f3148d

    Block: 1062736
    Time: 2016-02-26 11:55:33 (a day ago)
    From: 0x1699333a4e46093e15a94b4a213b88eb8a963834
    To: 0x3538f39300ddbef072bf06d756dbc4a45043beb7
    Amount: 0.24538345 Ether
    Account Nonce: 72
    Gas Price: 5e-8 Ether
    Gas Used: 21,000
    Tx Price: 0.00105 Ether
    Payload:

    0x (ASCII: )

Tx: 0x698799739e96bd1be9796b8011eb14eed8622e2e7520f07f5e4a70b40502aa12

    Block: 1067742
    Time: 2016-02-27 11:50:40 (8 hours ago)
    From: 0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98
    To: 0x3538f39300ddbef072bf06d756dbc4a45043beb7
    Amount: 0.33382649 Ether
    Account Nonce: 5518
    Gas Price: 5e-8 Ether
    Gas Used: 22,229
    Tx Price: 0.00111145 Ether
    Payload:

    0x (ASCII: )

**Comment by frozeman** [comment]
I assume the external payment is not providing enough gas, you need at least 35k

**Comment by rycky21** [comment]
Thank you
