### ISSUE TITLE
Cannot find module 'underscore' on Windows

### ISSUE THREAD

**Issue by mwtsai** [ethereum/mist#2160]
#### System information
``````
Version: `0.8.9`
OS & Version: windows
Node type: `eth/geth(default)`
``````

Uncaught Exception:
     Error: cannot find module 'underscore'

 Because of the bug of mist with gas missing 0x, I deploy Mist with gulp on ubuntu. It works successfully on linux. But when I work on Windows(deploy by gulp --win), it has an JavaScript error in the main process.

And I find it exist in my Mist's node_modules, I don't know how to solve this problem.

Thanks.

**Comment by evertonfraga** [comment]
Could you upload your `yarn.lock` file?
Also, can you confirm that you've performed all required steps described [here](https://github.com/ethereum/mist#development)?

**Comment by luclu** [comment]
@mwtsai could you please try out this PR https://github.com/ethereum/mist/pull/2163?

**Comment by mwtsai** [comment]
It's my `yarn.lock` file. 
https://gist.github.com/mwtsai/248098a2a767b23c69d21c9560355c37
And I deploy mist step by step described there.
