### ISSUE TITLE
Fix for Mist Wallet 0.4.0 not opening

### ISSUE THREAD

**Issue by kpierce77** [ethereum/mist#217]
Hi,
Just wanted to share with everyone (if it hasn't already been shared) that I found a fix for the Mist wallet (all versions) not opening on Mac OSX Yosemite.  After downloading and unzipping, and after double clicking the icon to launch, the launch window would come up, however nothing would happen after that. (i.e. wallet would never launch, would never connect to peers, etc.)  It just stayed on that launch screen.  After a few attempts of this, and after a laptop reboot, eventually a crash log came up that said  "libgmp.10.dylib not found", even though it was searching in the correct directory.  After a google search, I came upon these commands in a Ruby on Rails forum where libgmp.10.dylib wasn't found on a ROR install: Open terminal and type "brew update && brew install gmp" without quotes and hit Enter.  After install of brew, I was then able to launch the Mist wallet without any problems.  Just thought I'd share.

**Comment by frozeman** [comment]
Its a known bug, thanks
