### ISSUE TITLE
Will not open on mac

### ISSUE THREAD

**Issue by goldenboy2** [ethereum/mist#2170]
Having trouble opening my Ether wallet on my mac. Sorry if this is a bad question I'm very new to this

http://imgur.com/a/pjP4U

**Comment by evertonfraga** [comment]
Hello, it seems some things got wrong on the inside :)
I'd recommend you the following:

1) Back up your keys
- Go to Finder, `Cmd + Shift + G (go to folder)`, paste `~/Library/Ethereum` and back up the `keystore folder`. This is where your private files live. 

2) Delete `~/Library/Ethereum/chaindata` directory. It will reset your downloaded blockchain.

That should work. I'll close the issue, anything you have, just reopen here.
