### ISSUE TITLE
Adding Token with whitespace in address results in "invalid address" error

### ISSUE THREAD

**Issue by MidnightLightning** [ethereum/mist#2173]
#### System information
``````
Version: `0.8.9`
OS & Version: windows 10
Node type: `geth`
``````

When using the "Watch Token" button to add a new contract to watch, if you fill in the address of a token with whitespace at the beginning, it will properly pull in the token information into the dialog box, but after clicking Save, it shows an "invalid address" error instead of adding the token:

![token1](https://cloud.githubusercontent.com/assets/250250/25481538/3c71b930-2b13-11e7-92b5-0fd3309c80c0.png)

![token2](https://cloud.githubusercontent.com/assets/250250/25481543/4106bd88-2b13-11e7-8d8c-d2e51990b2e4.png)

In the first screenshot, note my cursor is at the beginning of the input field, and there's a whitespace gap to the beginning of the address.

No additional lines added to the console as a result of this action, and if you remove the whitespace, it adds just fine. 

I got into this issue because I was copy/pasting addresses from the Etherscan page about that token, which puts the details in an HTML table, which got translated to a tab character when I copy/pasted.

**Comment by luclu** [comment]
Thank you @MidnightLightning for bringing this to awareness!
I created a fix-PR at https://github.com/ethereum/meteor-dapp-wallet/issues/370.
