### ISSUE TITLE
same problem: Couldn't connect to the node, did it crash in the background? when entering password

### ISSUE THREAD

**Issue by dlepold** [ethereum/mist#2174]
2017 version 0.8.9 , win 8.1 
![image](https://cloud.githubusercontent.com/assets/6764649/25483523/9bdb9a12-2b2c-11e7-8ddf-3c5571f4a6e2.png)

![image](https://cloud.githubusercontent.com/assets/6764649/25483414/14ee51c0-2b2c-11e7-922f-bc98569e68a4.png)

![image](https://cloud.githubusercontent.com/assets/6764649/25483391/f9f26f78-2b2b-11e7-9326-896d5be4d39a.png)

file:///C:/Program%20Files%20(x86)/ethereum_wallet/resources/app.asar/interface/fonts/SourceSansPro.otf Failed to load resource: net::ERR_FILE_NOT_FOUND

Failed to load resource: net::ERR_FILE_NOT_FOUND

![image](https://cloud.githubusercontent.com/assets/6764649/25483587/d7fb2ec2-2b2c-11e7-8505-e93a4327bae5.png)

I already did restart.

**Comment by evertonfraga** [comment]
Should be fixed in latest Geth and Mist combo. 

Please let me know if it still happens.
