### ISSUE TITLE
Private key permission issue when importing in the Ethereum Mist

### ISSUE THREAD

**Issue by joowh85** [ethereum/mist#2176]
When I import the private key with the Ethereum Mist it generates permission with -rw-r--r-- in the MacOS X.
I think that it may possible to attack by other account and it should be -rw-------

**Comment by luclu** [comment]
Thank you @joowh85 for this idea, unfortunately that would require geth to be running as root.
Although one could create a specific user group, give the keystore some 660 permission and run geth within as a user belonging to that group, this would be rather messy if we where trying to do this by default - from UX as well as system hygiene perspective.

On the other hand there are ongoing efforts to restructure the account management, making it pluggable and moving it from the node layer into Mist.
