### ISSUE TITLE
Could not connect in TestNet

### ISSUE THREAD

**Issue by milyInzhoop** [ethereum/mist#2177]
#### System information
``````
Version: `0.8.9`
OS & Version: windows
Node type: `geth 1.6.0`
``````
Mist runs ok in mainNet but when I try to switch to the testnet (from menù) it says "Could not connect, please see log".

here the log:
```

INFO [04-28|10:31:50] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/windows-amd64/go1.8.1
INFO [04-28|10:31:50] Allocated cache and file handles         database=C:\\Users\\MYUSER\\AppData\\Roaming\\Ethereum\\geth\\chaindata cache=128 handles=1024
```

it seems that it does not search testnet chaindata in the correct folder.It's possible?
 How to fix?

**Comment by itisBaga** [comment]
+1

**Comment by rahulrumalla** [comment]
Arghhh same here on Windows 10 !

**Comment by DaGitNah** [comment]
Same, win 10... more like lose so much time trying to get this to work!

**Comment by nickf24** [comment]
+1

**Comment by tfleck** [comment]
+1 Win10

**Comment by AndersRassner** [comment]
+1 for windows 10. As the first poster says, the search path seems incorrect. 

I can sync to the testnet by directly running geth.exe -testnet so the problem seems to be with mist.

http://i.imgur.com/UkghOlQ.png

**Comment by liusy182** [comment]
I also encountered the same issue and found a workaround:

1. start geth mannually: `geth --testnet console`

2. [create an account on testnet](https://ethereum.stackexchange.com/questions/12824/different-way-of-creating-account)

3. Once blocks are fully synced, keep the cmd running and start mist browser. It will connect to `testnet` automatically

**Comment by evertonfraga** [comment]
Workaround by @liusy182 makes sense, and I'll explain why these errors happen:

Mist considered the connection was timed out due to geth inactivity. It was unsuccessfully searching for peers.

There's already a retry button in place that should fix this behavior.
