### ISSUE TITLE
How to import data from crashed pc / asks for password

### ISSUE THREAD

**Issue by nvomedia** [ethereum/mist#2179]
#### System information
``````
Version: `0.8.8`
OS & Version: Windows 10
Node type: `geth`
``````

Hi,

My PC decided to crash this week, and after a few days. I realized that I didn't have my ETHER. After a search on the files, I have the full AppData folder.

So I installed MIST, opend once, and copied the files of the old directory into the new folder, and I was able to see my ether again.

But, when I want to send some ether, I was asked to enter a password which I have never set. So, I did a search and I found an topic where I read something like this: When you copied the files, a new key is generated with a password you didn't know'. 

So, I have removed mist again, and I want to import my data via the import function but I can't find a wallet file. 

Can somebody tell me, what I can do, to use my ether again?

**Comment by nvomedia** [comment]
How, stop, wait!

He is still syncing, so maybe it's is coming back later. I will let you know.

**Comment by nvomedia** [comment]
Hmm, imported the file, waited when my wallet was up to date, but he asks again for a password. Can anybody help me?

**Comment by garretlaxton** [comment]
When you first make an account in the wallet it asks for a password before creating that account like below:
![1](https://cloud.githubusercontent.com/assets/16290508/25547874/aad6489e-2c37-11e7-9188-87954933340e.png)

**Comment by nvomedia** [comment]
It is on my 'Main account'. Can I create an account and send the Ether from that account?

**Comment by garretlaxton** [comment]
You can't create a 'Main Account' without setting a password for it first. You will also need that password to send ETH from your account.

**Comment by nvomedia** [comment]
I never remind me that screen, but he keeps asking me for a password, so I used my password manager to try every password 1 ever used, and yes, the third password was correct! Ow yeah!
