### ISSUE TITLE
issues with sync with the latest 0.89 mist wallet

### ISSUE THREAD

**Issue by unknown1233333** [ethereum/mist#2183]
#### System information
``````
Version: `0.8.9`
OS & Version: windows 7 64 bit
Node type: `eth/geth(default)`
``````

Problems getting the wallet to sync.  After syncing for a while it just stops completely.  I noticed the geth.exe process has completely disappeared in the task manager.  Restarting the mist wallet does not help the issue.  The geth.exe either crashes or disappears a couple of minute after the mist wallet restarts.

Once that happens the mist wallet sync process stops completely.

The last error in the log stated:
[04-29|22:34:57] Imported new state entries               count=384  elapsed=29.001ms  processed=1492024 pending=66503
CRIT [04-29|22:34:58] Failed to store block total difficulty   err="leveldb/table: corruption on data-block (pos=377452): checksum mismatch, want=0xc6438451 got=0xe0c19be5 [file=001182.ldb]"

CAN THIS ERROR BE FIXED PLEASE!!!
THIS APP IS COMPLETELY UNUSABLE!  I have spend hours trying to get this working.  It seems every time I try mist wallet I get stuck on some syncing issues.

**Comment by davedavis** [comment]
Same issue on Windows 10. Did you find a solution?

**Comment by Smooth0n3** [comment]
Seems like it runs fine until 1-2% and for no reason the geth.exe just shuts off.. I have been watching in task manager.. And each time @ 1-2% it just shuts off with out me doing anything.. Then have to restart the wallet and repeat.. Ive deleted the chainfile several times to if that would work ,but has not..

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
