### ISSUE TITLE
Mist: Cannot access Testnet or Main Network (greyed out)

### ISSUE THREAD

**Issue by tuckertranslator** [ethereum/mist#2184]
#### System information
``````
Version: `0.8.9`
OS & Version: mac osx
Node type: `eth/geth(default)`
``````
I could not manage to get the Application data per this forum's recommendation, but I have screenshots of the issue below. The problem is that I cannot connect to either the Testnet or the Main Network. The options are blurred out. I am running a geth sync in the background on my mac terminal, and the blockchain is fully synced. Any ideas? I have tried to look around several forums for answers but to no avail. Hope someone can help. Thank you. 
![captura de pantalla 2017-04-30 a las 11 03 00](https://cloud.githubusercontent.com/assets/26937470/25566841/de3668a8-2d96-11e7-806e-207d040e3949.png)
![captura de pantalla 2017-04-30 a las 11 20 15](https://cloud.githubusercontent.com/assets/26937470/25566850/07bb99fa-2d97-11e7-97ae-3fbfa590dbc0.png)

**Comment by evertonfraga** [comment]
Hola!

When you are running an external `geth` node, Mist loses its ability to manage it's starting flags. If you want to change networks, you should stop geth and run `geth --testnet` or `geth`.

thanks.
