### ISSUE TITLE
can't login Parity

### ISSUE THREAD

**Issue by boldekrol** [ethereum/mist#2188]
Hi, 

I have a big problem.
All i wanted to do was to buy Lunyr ICO via Parity.
So i installed and transfert ETH to my Parity account.
Now i didn’t manage to buy Lunyr because the site always blokked and my mouse changed into a spinning wheel (mac)

i am a complete noob about all this. Don’t even now what a Parity Node is. What do i have to do to fix this?
I can’t get to my account.

I thank you in advanced to take time to help me out here.

**Comment by evertonfraga** [comment]
Hi @boldekrol, it seems you are on the wrong place :)

But Parity has its own method for backing up accounts: https://github.com/paritytech/parity/wiki/Backing-up-&-Restoring

Anything else you need, hop into their issue tracker: https://github.com/paritytech/parity/issues
