### ISSUE TITLE
Wallet not updating

### ISSUE THREAD

**Issue by Comacs44** [ethereum/mist#2189]
My wallet is not updating despite having the latest version 0.8.9.
I am stuck at block 1,925,656 from 9 months ago.

I can see my last transaction from Kraken (see below) but it doesn't appear on my wallet
[https://etherscan.io/address/0x2397C995D401322681Bf9b8E8454a7C92d78DCC7](url)

How can I have my wallet up to date?

Thanks

![ethereum wallet screenshot](https://cloud.githubusercontent.com/assets/28274395/25595689/90eb563a-2ebd-11e7-967b-6bcd7c1457f3.jpg)

**Comment by gntimus** [comment]
I also have the same issue

**Comment by Evlam26** [comment]
I also seem to be having the same issue. The first 2,000,000 blocks were fine but it's taken 3 days to get 100,000 blocks and I still have 900,000  left. On Mac is there the option to do the geth--fast? If so where about's do you run this command, in terminal?

**Comment by sagunms** [comment]
@Evlam26 
**On MacOS:**
From your Terminal, go to path where you Ethereum Wallet is located (you can drag-drop your app to Terminal to know the path) and find Geth binary inside the .app package.
Say `<ETHEREUM WALLET PATH>` = `~/Library/Application\ Support/Ethereum\ Wallet`
Then, `<GETH PATH>` = `<ETHEREUM WALLET PATH>/binaries/Geth/unpacked`

Make sure you update to latest version of Geth from within Ethereum Wallet app.
```
<GETH PATH>/geth version
```
You should see something like the following:
```
Geth
Version: 1.6.0-stable
Git Commit: facc47cb5cec97b22c815a0a6118816a98f39876
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: darwin
GOPATH=
GOROOT=/usr/local/go
```

Delete existing chain data that's taking too long. 
```
rm ~/Library/Ethereum/chaindata/*
```

Run Geth in Fast mode
```
<GETH PATH>/geth --fast --cache=1024 console
```

**Comment by Comacs44** [comment]
@Sagunms:
You seem to be knowledgeable. Any idea how I (OP) can resolve my issue on Windows?
Thanks!

**Comment by Evlam26** [comment]
@sagunms Thanks heaps! 

Your solution worked well. Only issue I had was getting terminal to recognise the geth Path but once that was working it updated within a day :)

**Comment by samideluxe** [comment]
Hello, i'm facing a similar problem. Since i switched to the new 0.8.9 Wallet, my ether is not appearing anymore.
Guys told me to synch everything and the eth would appear again, but after syncing some 3million blocks it funnily remains blocked at block 254 and then suddenly started back at the last block needing to sync 3million and + blocks agaain!!

**Comment by evertonfraga** [comment]
I'm sorry to heat that.

There are known issues syncing on windows32, which could be solved by running geth separately, just like @sagunms told here. These issues are fixed on Mist/Wallet v0.8.10 (https://github.com/ethereum/mist/releases/tag/v0.8.10), though.

If you have an pretty old chaindata, it's possible that you're on some old chains, because we had some forks back in time.

Either way, resetting it and syncing from scratch, on this new version, may solve this issue. Please let me know otherwise.

**Comment by Comacs44** [comment]
@evertonfraga Thanks for the answer.
I downloaded v0.8.10 and it says that Ethereum node needs to sync which I believe is good.
However it seems to be looking for peers (and every so often for 1 sec or 2 says "connecting to 2 peers").
See attached.

Is it actually synchronising?

Thanks again

![looking for peers](https://cloud.githubusercontent.com/assets/28274395/25867760/7f6c716a-34f2-11e7-9912-589c5181d6f7.jpg)

**Comment by Comacs44** [comment]
Anyone on this that could help? 
Thanks

**Comment by Comacs44** [comment]
Sorted it out, I'm closing it.

**Comment by jjc12** [comment]
@Comacs44 How exactly did you sort it out? Don't leave us hanging.

**Comment by Comacs44** [comment]
@jjc12 I removed the chaindata directory and started sync and didn't have any problems.
I found the page below really helpful:
https://theethereum.wiki/w/index.php/Ethereum_Wallet_Syncing_Problems

**Comment by robba420** [comment]
@sagunms: I am trying to run these commands in terminal but am complete newbie, after I dragged app into terminal and then say <ETHEREUM WALLET PATH> I get   '-bash: syntax error near unexpected token `newline''

> On MacOS:
> From your Terminal, go to path where you Ethereum Wallet is located (you can drag-drop your app to Terminal to know the path) and find Geth binary inside the .app package.
> Say <ETHEREUM WALLET PATH> = ~/Library/Application\ Support/Ethereum\ Wallet
> Then, <GETH PATH> = <ETHEREUM WALLET PATH>/binaries/Geth/unpacked
> 
> Make sure you update to latest version of Geth from within Ethereum Wallet app.
> 
> <GETH PATH>/geth version
> You should see something like the following:
> 
> Geth
> Version: 1.6.0-stable
> Git Commit: facc47cb5cec97b22c815a0a6118816a98f39876
> Architecture: amd64
> Protocol Versions: [63 62]
> Network Id: 1
> Go Version: go1.8.1
> Operating System: darwin
> GOPATH=
> GOROOT=/usr/local/go
> Delete existing chain data that's taking too long.
> 
> rm ~/Library/Ethereum/chaindata/*
> Run Geth in Fast mode
> 
> <GETH PATH>/geth --fast --cache=1024 console
