### ISSUE TITLE
which version of Ethereum Wallet is usable

### ISSUE THREAD

**Issue by wmira** [ethereum/mist#2191]
eats huge amount of cpu on linux Ubuntu 14.04 and is not able to update the blocks for a very long time (36hrs ish) which version should we use? newbie here.

**Comment by garretlaxton** [comment]
Make sure you have a backup of your account, you can use this to access your ETH. https://myetherwallet.com/

**Comment by wmira** [comment]
I backed up my old .ethereum folder and restarted the wallet. it has manage to quickly sync the node and was not consuming huge amount of cpu. I think it was a mix of data with before the fork that was causing the issue
