### ISSUE TITLE
Blockchain of Ether - How do I find in my Mac? - Start mining with synchronization

### ISSUE THREAD

**Issue by lordofangels** [ethereum/mist#2192]
Good afternoon. How do I do to find the blockchain of ether that I am downloading through command line in the system OS X El Capitan? Another question: basicaly what is the composition of a blockchain of Ether?

**Comment by evertonfraga** [comment]
Hello, if I understood it correctly, you want to know where your blockchain is located at?

If so, as you are using Mac, you can access like this:
In finder, press `Cmd + Shift + G (Go to Folder)`, and paste this directory name: `~/Library/Ethereum/geth/`

Please note that your private key file is stored at `~/Library/Ethereum/keystore`. Make sure NOT to delete/tamper with it.

Anything you need, reopen this issue.

**Comment by lordofangels** [comment]
Oi, evertongraga, você é brasileiro? Estava vendo no seu perfil que é do Rio de Janeiro, sou do Paraná. Eu e meu amigo somos matemáticos e estamos estudando cripto moedas e mineração cibernética. Queremos contribuir para o projeto Ethereum. Acompanho a Ethereum.org há alguns meses, assim como outras plataformas. Operacionalmente, estamos com algumas dificuldades para minerar utilizando o Geth/ Go e fiz uma print da tela. Sobre o download do blockchain, estamos realizando há semanas, sem o quadro evoluir como esperávamos. Não deixei o tempo todo o Mist aberto, somente o terminal, mas precisaria concluir o download do blockchain, tê-lo sincronizado para testar os algoritmos e dar andamento na nossa contribuição. No final de abril, tínhamos em torno de 900.000 blocos remanescentes. Hoje, está em 1.000.000 para a sincronização. Outro colega do github fez a conta em abril (há pouco mais de 30 dias) e chegamos ao coeficiente de que havia feito 70% do download. Sobre localizar a pasta, como havia feito na pergunta, o Finder dá "A pasta não foi encontrada". Tentei digitar em português, também não consegui, provavelmente porque não finalizou o download. Você consegue nos ajudar? O que precisar da nossa ajuda, pode contar conosco. Abraços e desculpas se o texto aqui ficou longo, mas realmente queremos contribuir. As dados dos printscreen's estão no nome do arquivo.
![captura de tela 2017-03-23 as 15 21 39](https://cloud.githubusercontent.com/assets/26870657/26054766/36b4c2b4-3944-11e7-9166-a7b1d99d98a8.png)
![captura de tela 2017-03-23 as 15 28 56](https://cloud.githubusercontent.com/assets/26870657/26054767/36b6dedc-3944-11e7-9d1c-240e6b93c4c4.png)


![captura de tela 2017-05-15 as 07 45 13](https://cloud.githubusercontent.com/assets/26870657/26054703/e3c5592e-3943-11e7-96c9-432309711d5a.png)
![captura de tela 2017-05-15 as 07 45 28](https://cloud.githubusercontent.com/assets/26870657/26054705/e3cb15b2-3943-11e7-8b65-39cb916fad3b.png)
![captura de tela 2017-05-15 as 07 45 35](https://cloud.githubusercontent.com/assets/26870657/26054704/e3c8b826-3943-11e7-9ed6-d0baeb56878d.png)
![captura de tela 2017-05-02 as 10 59 47](https://cloud.githubusercontent.com/assets/26870657/26054722/fed4fff8-3943-11e7-9f1a-e55b4bbe8fa0.png)
![captura de tela 2017-04-03 as 09 26 56](https://cloud.githubusercontent.com/assets/26870657/26054737/10e0d870-3944-11e7-991c-5a5d139a2022.png)

**Comment by lordofangels** [comment]
Em vez de "As dados dos prints..." é As datas*, na última linha do meu texto

**Comment by evertonfraga** [comment]
Oi, tudo bem? 

Me parece que você colocou o caminho errado. Faltou uma `/` logo após o `~`. 
Apenas copie e cole este caminho do Finder: `~/Library/Ethereum/` ou `~/Biblioteca/Ethereum`. O diretório `geth` contém toda a blockchain que você já baixou. Tem algumas formas de agilizar essa sincronização.

1. Para continuar a baixar a blockchain, você pode iniciar o geth com mais cache. O padrão é 16MB. esse comando aumenta o cache para 1GB: 
`geth --cache=1024`.

2. Caso não melhore tanto, talvez você queira começar de novo. Aí você pode deletar ou mover a pasta `~/Library/Ethereum/geth`, e iniciar usando a flag `--fast`. Costuma ser notavelmente mais rápido.
`geth --fast --cache=1024`

Note que dependendo da sua memória livre, você pode aumentar para `2048`, etc.

Vale notar também que a sincronização é potencialmente mais lenta se você usa disco rígido, ao invés de armazenamento SSD.

Mais informações (em inglês): https://ethereum.stackexchange.com/questions/392/how-can-i-get-a-geth-node-to-download-the-blockchain-quickly/4210

Me avise se funcionou. Boa sorte!

**Comment by evertonfraga** [comment]
Aliás, se certifique que você esteja usando softwares atualizados:
- geth: http://geth.ethereum.org
- mist: https://github.com/ethereum/mist/releases

**Comment by lordofangels** [comment]
Bom dia, tudo bom? Obrigado pelas informações. Uma dúvida. Como faço para atualizar a implementação GO. Para colocar o Geth 1.6.1, no caso? Porque na página Installation Guide, a parte do OS X está em branco. Devo seguir novamente o procedimento de instalação da Geth? Sobre a sincronização, você recomenda iniciar novamente?
![captura de tela 2017-05-18 as 08 55 47](https://cloud.githubusercontent.com/assets/26870657/26201217/4652a1bc-3ba8-11e7-9c63-dd604042af48.png)
![captura de tela 2017-05-18 as 08 56 00](https://cloud.githubusercontent.com/assets/26870657/26201225/51681d48-3ba8-11e7-854e-8b4f42779435.png)

**Comment by lordofangels** [comment]
Outro detalhe. Eu coloquei depois --jitvm, pois segundo os comentários poderia ajudar, como já comecei o blockchain.

**Comment by evertonfraga** [comment]
Baixa pela url https://geth.ethereum.org/downloads/

![image](https://cloud.githubusercontent.com/assets/47108/26206469/4c808d20-3bbb-11e7-85e1-a4385d77ea96.png)

Sobre a sincronização, tenta mover o diretorio `chaindata` pra outro lugar, e começar de novo usando:
`geth --fast --cache=1024`
Fiz isso ontem a noite e sincronizou tudinho em ~4h

**Comment by lordofangels** [comment]
Boa tarde. Eu havia baixado por essa URL. Mas a parte operacional dessa atualização, como fica? Por linha de comando, substituindo o executável Unix?
Aí sobre o diretório, é também sobre linha de comando ou entro na Biblioteca do Finder, removo e trago de volta? Obrigado

**Comment by evertonfraga** [comment]
@lordofangels sim, você pode substittuir o executável.

pra ver onde fica o geth, execute: `which geth`. Depois substitua o executável lá.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
