### ISSUE TITLE
UX improvements on connection timeout window

### ISSUE THREAD

**Issue by cjdowner** [ethereum/mist#2193]
#### System information
``````
Version: `0.8.9.1372`
OS & Version: Mac OS 10.12.4
``````

**Summary:**
Connection error view can be improved to include a <kbd>Retry</kbd> button.

**Steps to Reproduce:**
- Launch Ethereum Wallet on Mac
- Turn Wi-Fi off or something so the node can't connect/sync

**Actual Results:**
Error title, with no message or method to go back or retry. I had to quit the app and re-launch it so I could connect.
![screen shot 2017-05-02 at 20 35 43](https://cloud.githubusercontent.com/assets/2099705/25636781/61980f78-2f7a-11e7-8b11-d137da00cbb6.png)

**Expected Results:**
For there to be a way for me to retry to connect to the mode from this view, without needing to relaunch the app.

**Notes:**
Sounds pretty minor, but it would make a nice touch to improve the UX. I was connected to the internet at this time, so perhaps a minor summary could be added below the error title. eg `Please check your connection and try again.`, etc.

**Comment by evertonfraga** [comment]
Yes, makes a lot of sense. I'm tagging this issue for better tracking.

**Comment by ballardt** [comment]
I'll take this on. It seems like a gentle introduction to Mist development.

**Comment by evertonfraga** [comment]
Great! much appreciated.

**Comment by evertonfraga** [comment]
Fixed by @ballardt.
