### ISSUE TITLE
Warning! An error occured during contract execution

### ISSUE THREAD

**Issue by aguy2083** [ethereum/mist#220]
I have some ETH in limbo. Downloaded Mist client 0.4.0 and set up a contract wallet. Added ETH with the handy Shapeshift function without issue. Tried so send ETH from my Jaxx android wallet and web wallet but my Mist balance did not update. Etherchain.org provided not clues. Sending ETH via Jaxx to Etherbase worked. Checked etherscan.io and all the transactions with issues have the following error: Warning! An error occured during contract execution 
I can provide additional details if needed.
Any help would be greatly appreciated!

**Comment by frozeman** [comment]
Its probably that the jaxx wallet doesn't send enough gas, so the transaction gets reverted

**Comment by aguy2083** [comment]
My ethereumwallet.com did the same thing. Below is my address. 
https://etherscan.io/address/0xa4248ebbf74cff99d03db5806cfb55814bd70e25

**Comment by frozeman** [comment]
Thats a problem of ethereumwallet.com, they seem not to credit transactions coming from contracts. Please contact them. You can also refer them to here.

**Comment by kitOl** [comment]
I have a similar problem with the transfer on Bter.com. I did the three translations from the Mist Wallet Contract to 0xb60cdcc05d0fcb2d1e88b6b25dd6f9d810360921. They refuse to transfer funds to my trading account (2.3 ETH) justifying this by saying that they do not see the  transaction received there https://etherchain.org/account/0xb60cdcc05d0fcb2d1e88b6b25dd6f9d810360921#txreceived.
But there http://etherscan.io/address/0xb60cdcc05d0fcb2d1e88b6b25dd6f9d810360921#Top I can see all three Contract Invoked Transactions.

**Comment by ShawnKimble** [comment]
I have a similar problem, sending a transaction via Jaxx wallet, which I assume means I sent it without enough gas and the transaction is now stuck?  The address doesn't reflect the value in the balance, but the value is also now gone from the original wallet.   Does this mean I lost the coins, unless the contract has a kill (suicide) function?

**Comment by simonhowell** [comment]
Simon from Jaxx here - we're working on new features designed to facilitate working with contracts. You can expect them in an update in the near future.

**Comment by luclu** [comment]
Closed as these issues have to be fixed in Jaxx/myethereumwallet.com.
