### ISSUE TITLE
Restoring the Mist wallet with only my passphrase

### ISSUE THREAD

**Issue by fesic** [ethereum/mist#2201]
Hi Guys,

My old compute (windows) is dead and the mist wallet on there is gone. So from reading other post it seems that you need to backup the keystore file, which I didnt do. I do however have the very long seed passphrase of something like 20+ words. Is there any chance that I can recover my mis wallet with just the seed passphrase alone (mnemonic). 

Thanks for the the help.

**Comment by sathishvj** [comment]
Can you try using the mnemonic on myetherwallet.com and accessing the account?  If it works, you can at least create a new account and then transfer everything to that.

This time, please remember to backup your keystore file.

**Comment by alexvandesande** [comment]
Mist doesn't use a 20 words mnemonic. Are you sure you didn't create it on metamask? If not, you cannot recover Geth accounts without the proper backup

Sorry for the delay, we are looking into old unanswered issues.
