### ISSUE TITLE
''Wrong Password''

### ISSUE THREAD

**Issue by caomhanmcm** [ethereum/mist#2206]
Hey guys,

I couldnt find an answer in the below thread and really need your help. For some reason i cannot transfer ETH out of my wallet - it says 'wrong password' when i try to make a transaction but i know the password is correct. Is this something that happens frequently? 

Any advice here would be appreciated as this has been going on for 2 months. Happy to transfer ETH to person good enough to help me out :-)

Kind Regards,
Caomhan

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by tripolskypetr** [comment]
I have same error

**Comment by agnewpickens** [comment]
I have same error as well, not the first time the Turing changed my security icon indicating a password change, have not been able to get at my etherbase eth on one keystore since last fall.
