### ISSUE TITLE
Wrong Password - ETH reward

### ISSUE THREAD

**Issue by caomhanmcm** [ethereum/mist#2207]
Hey guys,

I couldnt find an answer in the below thread and really need your help. For some reason i cannot transfer ETH out of my wallet - it says 'wrong password' when i try to make a transaction but i know the password is correct. Is this something that happens frequently? 

Any advice here would be appreciated as this has been going on for 2 months. Happy to transfer ETH to person good enough to help me out :-)

Kind Regards,
Caomhan

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by sathishvj** [comment]
First, have you backed up your keystore file?  If not, please do that first. 

Then use the keystore file at myetherwallet.com and see if you can correctly authorize it.  If that is ok, then you can also do any transfers there.  If you're unable to authorize it, you probably have your password wrong.

**Comment by ihatecreatingaccounts** [comment]
what should i do if the password is in fact NOT wrong but it says it is. i used the same password before to make a transaction, its copypasted from the same file as before which is readonly.
its driving me insane, i lost 3 eth because of this.

**Comment by sathishvj** [comment]
I don't know if I'll be able to help you retrieve it, but we can at least try.  Btw, I don't work for this project or the ethereum foundation and you shouldn't be giving me any private keys or passwords.  I'm just a general ethereum citizen trying to help.  And you are entirely responsible for any lost funds and the safety/security of your account.

Again, without any guarantees, if you want you can skype me at 'sathishvj' (probably in about an hour) and we can try.  Chances are less that you'll get it back, but if you do, i suggest you move out all the ether into an other account immediately.

**Comment by caomhanmcm** [comment]
hey @sathishvj - sure, when would you be free?

**Comment by sathishvj** [comment]
am online now.

**Comment by fort9520** [comment]
I am having this same issue. Wrong password but I'm 100% sure it's not wrong.

**Comment by sathishvj** [comment]
Do you have any non ascii characters in it?  Did you generate the password with a password generator that uses unicode?  (There was an issue raised regarding unicode chars in the password.)

Can you check the keystore file?  Does it have proper content?  If you backed it up as soon as you created it, can you compare it to see if there are any changes?

**Comment by evertonfraga** [comment]
To reproduce this issue and help you guys, I, please ask you to answer this set of questions, so we can outline the problem and move on. Please fill out the form thoroughly.
https://goo.gl/forms/jznmHV6Fpui7Ijds1

Let's move the conversation to this single place: #3513 Thank you.
