### ISSUE TITLE
BTC Transfer did not work

### ISSUE THREAD

**Issue by bartaman** [ethereum/mist#2210]
My transfer from Bitcoin wallet to Ethereum Wallet on my iMac did not word yet.
I sent BTC´s 3 Days ago!  

![bildschirmfoto 2017-05-05 um 15 03 21](https://cloud.githubusercontent.com/assets/28414239/25746498/0c0567dc-31a4-11e7-982f-29d75a23a1da.png)
![bildschirmfoto 2017-05-05 um 15 06 21](https://cloud.githubusercontent.com/assets/28414239/25746576/6f6a78c6-31a4-11e7-90ef-e4e78d8e030e.png)
![bildschirmfoto 2017-05-05 um 15 06 13](https://cloud.githubusercontent.com/assets/28414239/25746575/6f692ca0-31a4-11e7-8e3b-b7dac0ddbfdf.png)

does anybody know what that could be?
thx Manfredd

**Comment by sathishvj** [comment]
You sent Bitcoin directly to an Ethereum Wallet?  You can't do that.  Ethereum Wallet only takes Ethers.

If you used a tool like shapeshift to convert BTC to ETH, it will show up only when the entire blockchain is synced (or at least as far as the block in which that transaction was mined).  In the meantime, you can check the balance of your account at etherscan.io/address/0x...

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
