### ISSUE TITLE
The ether do not appear on the wallet

### ISSUE THREAD

**Issue by JRtoujours** [ethereum/mist#2215]
Hallo, I send some ether to my new installed Etherum Wallet and main Account 40 days ago. but they dont yet appear on the wallet. what should I do?. I am totally new in cryptocurrency. Thank you.

**Comment by JETBYE** [comment]
same with me    hope someone can help

**Comment by mohmul15** [comment]
Same with me too

**Comment by mohmul15** [comment]
What can we do about it?
Are they gone?

**Comment by garretlaxton** [comment]
You need to let your wallet fully sync before seeing funds, you can also import your backup file or private keys & access your coins instantly at https://www.myetherwallet.com

**Comment by cosminrdt** [comment]
does fully sync mean when all the blocks are downloaded ?

**Comment by Hirbod** [comment]
@cosminrdt yes

**Comment by samideluxe** [comment]
Hello, i'm facing a similar problem. Since i switched to the new 0.8.9 Wallet, my ether is not appearing anymore.
Guys told me to synch everything and the eth would appear again, but after syncing some 3million blocks it funnily remains blocked at block 254 and then suddenly started back at the last block needing to sync 3million and + blocks agaain!!

**Comment by samideluxe** [comment]
Found a good solution and easy solution:
If you need access to your Ether you can always extract the wallet file and open it in myetherwallet.com
On a mac your wallet is in ~/Library/Ethereum/keystore (~ being your home folder)
1) Once you have your keystore file, generate a wallet.
2) Select the file and password you used when creating your ethereum wallet
3) You access your wallet and are in control of checking balance, receiving or sending ether

Remember to download and print out all the passwords and keys and store them on a safe place like a usb or external hard disk etc...

**Comment by evertonfraga** [comment]
Those issues you guys are having are most likely related to an out-of-sync situation. I know that syncing 3M blocks sometimes can be a pain. Mist is moving towards a light client - or external secure provider, that could show those information almost instantly. 

For now, I'd second @samideluxe's suggestion if you need immediate access/transaction, in case your Mist isn't synced. You can also check your balances at a blockchain explorer, such as https://etherscan.io.

Yesterday I've created a pull request on the wallet (https://github.com/ethereum/meteor-dapp-wallet/pull/374) stating this sort of out-of-sync issue, and also a shortcut to see your address at etherscan. While we don't have an super quick solution for syncing, people must at least be aware of the problem.

welcome to crypto, I hope you understand it's an always-evolving world.
