### ISSUE TITLE
Ich bin  im Test und komme nicht mehr auf mein Konto

### ISSUE THREAD

**Issue by Kristin78** [ethereum/mist#2216]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
Klicke einfach im Menü auf `develop -> network -> mainnet`. 
Falls es ausgegraut sein sollte, läuft ein node im Hintergrund, den du beenden solltest.

**Comment by Kristin78** [comment]
Hallo und vielen Dank für ihre Antwort.

 

Leider weiß ich nicht was ein node ist und wie ich es beenden kann.

Bevor ich in diesen Statuts kam, hatte ich noch kein Backup.

 

Hier ein Screenshot:



 

Vielen Dank im Voraus für Ihre Unterstützung.

 

K. Lissek

 

 

Von: Luca Zeug [mailto:notifications@github.com] 
Gesendet: Montag, 8. Mai 2017 12:30
An: ethereum/mist <mist@noreply.github.com>
Cc: Kristin78 <k.lissek@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [ethereum/mist] Ich bin im Test und komme nicht mehr auf mein Konto (#2216)

 

Klicke einfach im Menü auf develop -> network -> mainnet.
Falls es ausgegraut sein sollte, läuft ein node im Hintergrund, den du beenden solltest.
