### ISSUE TITLE
during syncing of wallet cpu becomes overheated

### ISSUE THREAD

**Issue by s1zo** [ethereum/mist#2217]
mist wallet 0.8.8
os: windows 7 - 64b
node type: default (geth 1.6.0)

Hi ,

Im new to this and i need a solution for the following problem;

When syncing my wallet the cpu usage goes way up and my cpu temperature becomes to high.
Just want to use the wallet , no mining needed. 

may be some noob question, i hope its something simple. :)

p.s. (yes, the computers inside is clean)

Thanks in advance.

**Comment by joe1234555** [comment]
same problem here. Can't sync and can't see my funds because haven't synced yet. The CPU nearly fried my computer. In fact my mac powered off and wouldn't turn on for 20 minutes until i took it apart and put it back together =-(

**Comment by joe1234555** [comment]
...I am trying an app CPU reducer softer and seems to be working

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
