### ISSUE TITLE
Transferring from old Ethereum Wallet to new Ethereum Wallet (not Mist)

### ISSUE THREAD

**Issue by adamabyss** [ethereum/mist#2221]
Hello there,

My wallet won't update on my old computer, been trying for months so I have installed Ethereum Wallet on my new computer.

I have three questions.

1. How do I transfer my old account to my new wallet on the new computer? I have the JSON etc. I don't want to make a crucial mistake and lose all my balance. I know I have to use 'Add Account' first of all on the new wallet (on the new computer) but after that will I be able to import my old account into the new wallet using the JSON and my password?

2. I have a contract on the old wallet, which I don't seem to have the JSON for (for example, I cannot use MyEtherWallet to send funds from this contract) so how do I get the balance on the contract across to the new wallet, with the regular account? Will it just come over with the JSON of the main account? Because on my wallet on my old computer I can see my full balance - i.e. 75% in main account, 25% in contract - it's just that I can't do anything from there because the computer will never update - it's too old.

3. Related to above, I can use MyEtherWallet to send from my main account but in the event that my wallet on my new computer also stops working (these wallets don't see to work very well, although they do LOOK good - way better than the old QT wallets), then how would I be able to send funds from the contract part of my old wallet using MyEtherWallet? Like I say, I can get into the main account of the old wallet on MyEtherWaller (75% of my funds) to send funds etc. but I can't get into the contract part (25% of my funds).

Thanks in advance.

PS. I find it very confusing that people ask questions about Ethereum Wallet and then in the middle of their question (or some of the replies) people switch over to talking about Mist. From what I can see on the download page, they are two different applications. What is the difference? I tried to download Mist once but couldn't make head nor tail of it. Thanks.

**Comment by adamabyss** [comment]
Does no one bother answering questions on here?

**Comment by samideluxe** [comment]
Hello, i'm facing a similar problem. Since i switched to the new 0.8.9 Wallet, my ether is not appearing anymore.
Guys told me to synch everything and the eth would appear again, but after syncing some 3million blocks it funnily remains blocked at block 254 and then suddenly started back at the last block needing to sync 3million and + blocks agaain!!

**Comment by samideluxe** [comment]
Found a good solution and easy solution to getting your unaccessible ether back into your control and use if you cannot deal with the ethereum wallets:
If you need access to your Ether you can always extract the wallet file and open it in myetherwallet.com
On a mac your wallet is in /Library/Ethereum/keystore ( being your home folder)

Once you have your keystore file, generate a wallet.
Select the file and password you used when creating your ethereum wallet
You access your wallet and are in control of checking balance, receiving or sending ether
Remember to download and print out all the passwords and keys and store them on a safe place like a usb or external hard disk etc...
