### ISSUE TITLE
How to upgrade on Mac?

### ISSUE THREAD

**Issue by bradleydavidgood777** [ethereum/mist#2222]
Hi,

I am using Ethereum-Wallet 0.7.6 and it tells me that there is an upgrade available which is 0.8.9.  

I downloaded the file for Mac but I wanted to check how to upgrade so that I don't lose my Ether some how along the way.  I am afraid that the new version will clobber the old and I will lose my coins.  Just checking that it will all be OK if I just run the downloaded file:
Ethereum-Wallet-macosx-0-8-9.dmg

Thanks

**Comment by luclu** [comment]
You are doing fine, just replace the app with with new version. Your account's keyfiles are stored in `~/Library/Ethereum/keystore`. Please do yourself the favour and create a backup of those files.

**Comment by bradleydavidgood777** [comment]
Great, thank you!  So those files are all I need to restore from total loss of computer?

**Comment by garretlaxton** [comment]
Yes, the files in your keystore folder are what you need to restore your account. I keep my backup files on a USB, I'd recommend you keeping a backup somewhere safe as well.

**Comment by bradleydavidgood777** [comment]
Awesome, thank you!  Got it on USB in a safe place, and also under a subfolder in Documents on the Mac, so it gets to the Time Machine backup drive regularly too.

**Comment by bradleydavidgood777** [comment]
I downloaded the new version and installed it - it went to the applications folder.  It took a long time to sync.  The wallet says zero.  
I closed the new version and opened the old version.  It shows my balance fine.
The old version of the app is in a subfolder of applications called crypto.
I would love to get rid of the old version and move the new version to this subfolder.
However, with the new version showing zero, I am reluctant to do anything.
The idea I have are to send my balance from the old one to the new one, then move the new one on top of the old one.  

Sound like a plan?

Can I move the app to a subfolder in the applications folder and all will be OK?  I must have done that before because the old version is in a subfolder.

Thanks

**Comment by CoderXpert** [comment]
I am in the same situation. I have a question if I keep my keystore files in `~/Library/Ethereum/keystore` and install the new app will it use my old keystore files or will it create new.

And what if I take backup of those files and delete old app, then install a new app and change keystore files, will new app going to use my old keystore and will I get my balance correct.

@bradleydavidgood777 can you please share your experience? did your plan worked at the end?

**Comment by bradleydavidgood777** [comment]
Hi CoderXpert,

I have not moved forward since my last post since I have not heard anything.  When I have encountered upgrade issues with Bitcoin, my standard practice is to install some new brand "B" of wallet and transfer my coins from the "A" wallet to the B wallet.  Then remove the original A wallet software and install the newest version of the A wallet software.  Then move the coins from B to A.  I am not sure if Ethereum has another brand of wallet and we could do that in this situation.  I haven't looked at this in a while.  

I am still on the old version and my coins are there.

**Comment by CoderXpert** [comment]
@bradleydavidgood777 thanks for replying. I have gone through the upgrade process, and it worked fine.

**Comment by bradleydavidgood777** [comment]
So you installed the new version while the old version was still on the mac right?

And then did your new version show your coin balance?  

And the old version was gone?

I think my whole issue is that my old version is in a subfolder of the Applications folder.

**Comment by CoderXpert** [comment]
@bradleydavidgood777 Yeah that what I did and it worked well. Keystore files are enough to get your account back. I installed Ethererum wallet into another mac and copied over the Keystore files from Ethererum wallet from a different computer, and it worked, I can see my balance right.

So as far as you have your Keystore files, you are safe.

**Comment by bradleydavidgood777** [comment]
Ah, that is a good idea.  I may install on a different mac and move my
coins there, then fix up my mac and move them back.  Thanks for the idea!
