### ISSUE TITLE
"Keep a copy of the "keystore" folder where you can't loose it!" typo

### ISSUE THREAD

**Issue by StefanBRas** [ethereum/mist#2228]
Running the Ethereum-Wallet-linux64-0-8-10.deb installer, there is the following typo:
"Keep a copy of the "keystore" folder where you can't loose it!"
Where "loose" should be "lose".
![typo](https://cloud.githubusercontent.com/assets/28559054/25843296/3bc4bef4-34a7-11e7-83e3-c5d9c56a011a.png)

**Comment by evertonfraga** [comment]
Whoa, thanks! 
it's fixed on https://github.com/ethereum/mist/pull/2233
