### ISSUE TITLE
From wallet Contract to account

### ISSUE THREAD

**Issue by lechatnieger** [ethereum/mist#223]
Hi,
i'm trying to send eth, from a wallet contract to an account,
even if i try to send 1 eth, i receive the message "Insufficient funds for gas * price + value" or Mist hangs out exiting. The wallet contract has positive balance.

The strange thing is that, in the form where i have to put the password for confirming the transaction, the  address in the from value, is not the one of the wallet contract, and the transferred value is 0 eth, the address in the from value is the one of another account inside mist.

**Comment by lechatnieger** [comment]
https://github.com/ethereum/mist/issues/71

already solved, i'll try!!!!

**Comment by frozeman** [comment]
because you pay from the owner amount the gas. and you need to type the password of the owner account. Also this transaction is an "instruction" to the contract to move money, its not send form the owner account...

**Comment by DSofter** [comment]
@lechatnieger silly question: how do I send ETH from my contract wallet to account? Thanks!
