### ISSUE TITLE
MIST (Application) won't start on Mac

### ISSUE THREAD

**Issue by Frankee72** [ethereum/mist#2231]
#### System information
``````
Version: `0.8.9`
OS & Version: osx 10.12.4
Node type: `eth/geth(default)`
``````

This morning, i tried to start my MIST and it doesn't start anymore. I can click the icon, but the software doesn't start. i tried to install 0.8.9 again, nothing worked. i can't actually find the 0.9 version on github for mac.

the program won't start. the icon jumps, the black dot is under the icon but disappears and nothing happens.

the problem is, that i'm bidding on ens for names and i need to reveal the bids soon, or i'm loosing my funds.

i tried to on another computer to install mist with my keystore-files, that worked, but the bids are gone, these are separate files...

how can i retrieve these bidding files from the installation?

can anyone help me please?

**Comment by evertonfraga** [comment]
Well, there are a number of possibilities out there. Let's start to explore.

1. just a sanity check: is your HD/SSD full?

2. Can you start Mist from the command-line, and paste here the log output? 
`/Applications/Mist.app/Contents/MacOS/Mist`

3. Additionally, could you provide the `geth` node output that runs underneath Mist?
`cat ~/Library/Application\ Support/Mist/node.log`

**Comment by Frankee72** [comment]
here is the log from terminal: 

[2017-05-09 16:11:26.556] [INFO] main - Running in production mode: true
[2017-05-09 16:11:26.670] [INFO] main - Starting in Mist mode
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[2017-05-09 16:11:26.760] [INFO] Db - Loading db: /Users/hengartner/Library/Application Support/Mist/mist.lokidb
[2017-05-09 16:11:26.771] [ERROR] Db - SyntaxError: Unexpected token } in JSON at position 16040
    at Object.parse (native)
    at Loki.loadJSON (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/lokijs/src/lokijs.js:1370:42)
    at loadDatabaseCallback (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/lokijs/src/lokijs.js:2120:20)
    at readFileCallback (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/lokijs/src/lokijs.js:1997:15)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
[2017-05-09 16:11:26.783] [ERROR] main - Error: Error instantiating db
    at autoloadCallback (/Applications/Mist.app/Contents/Resources/app.asar/modules/db.js:43:32)
    at loadDatabaseCallback (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/lokijs/src/lokijs.js:2123:15)
    at readFileCallback (/Applications/Mist.app/Contents/Resources/app.asar/node_modules/lokijs/src/lokijs.js:1997:15)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
[2017-05-09 16:11:26.784] [INFO] main - Defer quitting until sockets and node are shut down
[2017-05-09 16:11:26.784] [INFO] Sockets - Destroy all sockets
[2017-05-09 16:11:26.785] [INFO] Sockets/node-ipc - Disconnecting...
[2017-05-09 16:11:26.787] [ERROR] main - Error shutting down sockets
[2017-05-09 16:11:27.289] [INFO] main - About to quit...

**Comment by Frankee72** [comment]
geth node output: 

INFO [05-09|10:28:37] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/darwin-amd64/go1.8.1
INFO [05-09|10:28:37] Allocated cache and file handles         database=/Users/hengartner/Library/Ethereum/geth/chaindata cache=1024 handles=1024
INFO [05-09|10:28:38] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Engine: ethash}"
INFO [05-09|10:28:38] Disk storage enabled for ethash caches   dir=/Users/hengartner/Library/Ethereum/geth/ethash count=3
INFO [05-09|10:28:38] Disk storage enabled for ethash DAGs     dir=/Users/hengartner/.ethash                      count=2
INFO [05-09|10:28:38] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [05-09|10:28:38] Loaded most recent local header          number=3672141 hash=a9735c…74305f td=251199366203967046856
INFO [05-09|10:28:38] Loaded most recent local full block      number=3672141 hash=a9735c…74305f td=251199366203967046856
INFO [05-09|10:28:38] Loaded most recent local fast block      number=3672141 hash=a9735c…74305f td=251199366203967046856
WARN [05-09|10:28:38] Blockchain not empty, fast sync disabled 
INFO [05-09|10:28:38] Starting P2P networking 
INFO [05-09|10:28:38] Mapped network port                      proto=udp extport=30303 intport=30303 interface=NAT-PMP(10.0.1.1)
INFO [05-09|10:28:38] RLPx listener up                         self=enode://42dc975f030971bc1394d2422d6f5f1cf153134271dc623a17b6c2cf62e01dc24caeec3a0e7878b8751e6978ad597087dbff37238cca93170989c5a0d7bc728f@77.56.189.86:30303
INFO [05-09|10:28:38] IPC endpoint opened: /Users/hengartner/Library/Ethereum/geth.ipc 
INFO [05-09|10:28:38] Mapped network port                      proto=tcp extport=30303 intport=30303 interface=NAT-PMP(10.0.1.1)
2017/05/09 10:28:40 ssdp: got unexpected search target result "upnp:rootdevice"
2017/05/09 10:28:40 ssdp: got unexpected search target result "uuid:2f402f80-da50-11e1-9b23-00178820b5ff"
2017/05/09 10:28:40 ssdp: got unexpected search target result "urn:schemas-upnp-org:device:basic:1"
2017/05/09 10:28:40 ssdp: got unexpected search target result "upnp:rootdevice"
2017/05/09 10:28:40 ssdp: got unexpected search target result "uuid:2f402f80-da50-11e1-9b23-00178820b5ff"
2017/05/09 10:28:40 ssdp: got unexpected search target result "urn:schemas-upnp-org:device:basic:1"
INFO [05-09|10:28:58] Block synchronisation started 
INFO [05-09|10:29:24] Imported new chain segment               blocks=2 txs=23 mgas=1.016 elapsed=614.461ms mgasps=1.653 number=3672143 hash=0a8d41…30ca70
INFO [05-09|10:29:27] Imported new chain segment               blocks=3 txs=29 mgas=0.892 elapsed=797.861ms mgasps=1.118 number=3672146 hash=6b9ab3…53d779
INFO [05-09|10:29:28] Imported new chain segment               blocks=2 txs=68 mgas=2.395 elapsed=785.299ms mgasps=3.050 number=3672148 hash=c9a618…f5ab48
INFO [05-09|10:29:51] Imported new chain segment               blocks=39 txs=627 mgas=27.852 elapsed=8.269s    mgasps=3.368 number=3672187 hash=0276df…1f3268
INFO [05-09|10:30:00] Imported new chain segment               blocks=42 txs=1095 mgas=48.588 elapsed=8.808s    mgasps=5.516 number=3672229 hash=731ec4…790b04
INFO [05-09|10:30:08] Imported new chain segment               blocks=31 txs=999  mgas=38.915 elapsed=8.367s    mgasps=4.651 number=3672260 hash=0a8b79…376ec2
INFO [05-09|10:30:16] Imported new chain segment               blocks=45 txs=973  mgas=53.002 elapsed=8.037s    mgasps=6.594 number=3672305 hash=0200d3…01991d
INFO [05-09|10:30:25] Imported new chain segment               blocks=44 txs=1124 mgas=85.881 elapsed=8.306s    mgasps=10.339 number=3672349 hash=c71bae…78196e
INFO [05-09|10:30:33] Imported new chain segment               blocks=56 txs=1220 mgas=41.183 elapsed=8.127s    mgasps=5.067  number=3672405 hash=b4065e…4ee8f8
INFO [05-09|10:30:41] Imported new chain segment               blocks=67 txs=1311 mgas=45.952 elapsed=8.004s    mgasps=5.741  number=3672472 hash=4638a8…1497a2
INFO [05-09|10:30:49] Imported new chain segment               blocks=48 txs=1724 mgas=67.675 elapsed=8.520s    mgasps=7.943  number=3672520 hash=d2b79f…db89db
INFO [05-09|10:30:50] Imported new chain segment               blocks=5  txs=264  mgas=5.497  elapsed=579.594ms mgasps=9.484  number=3672525 hash=f7effd…3b2398
INFO [05-09|10:30:58] Imported new chain segment               blocks=11 txs=450  mgas=15.097 elapsed=8.421s    mgasps=1.793  number=3672536 hash=4d3828…c107f2
INFO [05-09|10:31:06] Imported new chain segment               blocks=78 txs=1496 mgas=68.586 elapsed=8.000s    mgasps=8.572  number=3672614 hash=8644dd…2ea816
INFO [05-09|10:31:14] Imported new chain segment               blocks=58 txs=1477 mgas=47.738 elapsed=8.124s    mgasps=5.876  number=3672672 hash=2bd852…941224
INFO [05-09|10:31:25] Imported new chain segment               blocks=47 txs=1430 mgas=51.180 elapsed=10.203s   mgasps=5.016  number=3672719 hash=786fe7…e60030
INFO [05-09|10:31:34] Imported new chain segment               blocks=49 txs=1310 mgas=57.478 elapsed=8.907s    mgasps=6.453  number=3672768 hash=3f7c80…9d2441
INFO [05-09|10:31:42] Imported new chain segment               blocks=62 txs=1243 mgas=34.762 elapsed=8.825s    mgasps=3.939  number=3672830 hash=548be8…4b9728
INFO [05-09|10:31:51] Imported new chain segment               blocks=44 txs=1144 mgas=32.759 elapsed=8.295s    mgasps=3.949  number=3672874 hash=f166d8…b2da1e
INFO [05-09|10:31:59] Imported new chain segment               blocks=48 txs=1112 mgas=38.902 elapsed=8.011s    mgasps=4.856  number=3672922 hash=705f98…75ebc3
INFO [05-09|10:32:07] Imported new chain segment               blocks=53 txs=1313 mgas=43.832 elapsed=8.165s    mgasps=5.368  number=3672975 hash=aec0d6…d1781e
INFO [05-09|10:32:15] Imported new chain segment               blocks=39 txs=1151 mgas=38.893 elapsed=8.207s    mgasps=4.739  number=3673014 hash=2b2012…86df9a
INFO [05-09|10:32:23] Imported new chain segment               blocks=54 txs=1541 mgas=45.912 elapsed=8.248s    mgasps=5.566  number=3673068 hash=91c2b1…c1f5af
INFO [05-09|10:32:32] Imported new chain segment               blocks=65 txs=1169 mgas=39.687 elapsed=8.246s    mgasps=4.812  number=3673133 hash=2f94fc…eba8b2
INFO [05-09|10:32:40] Imported new chain segment               blocks=42 txs=1127 mgas=41.166 elapsed=8.254s    mgasps=4.987  number=3673175 hash=5b4c16…614149
INFO [05-09|10:32:48] Imported new chain segment               blocks=50 txs=1152 mgas=52.629 elapsed=8.099s    mgasps=6.498  number=3673225 hash=f23933…9a5716
INFO [05-09|10:32:56] Imported new chain segment               blocks=76 txs=1206 mgas=50.688 elapsed=8.079s    mgasps=6.273  number=3673301 hash=146a9b…d4c9a2
INFO [05-09|10:33:04] Imported new chain segment               blocks=55 txs=1501 mgas=52.570 elapsed=8.228s    mgasps=6.389  number=3673356 hash=1fbdde…d86715
INFO [05-09|10:33:13] Imported new chain segment               blocks=86 txs=1554 mgas=54.280 elapsed=8.258s    mgasps=6.572  number=3673442 hash=7765c2…3f7c96
INFO [05-09|10:33:21] Imported new chain segment               blocks=15 txs=1292 mgas=27.603 elapsed=8.269s    mgasps=3.338  number=3673457 hash=507240…d6ee64
INFO [05-09|10:33:29] Imported new chain segment               blocks=21 txs=1139 mgas=27.544 elapsed=8.323s    mgasps=3.309  number=3673478 hash=f1218a…8b5673
INFO [05-09|10:33:37] Imported new chain segment               blocks=41 txs=1285 mgas=45.465 elapsed=8.143s    mgasps=5.583  number=3673519 hash=c95931…2af0c7
INFO [05-09|10:33:45] Imported new chain segment               blocks=59 txs=1044 mgas=38.059 elapsed=8.040s    mgasps=4.733  number=3673578 hash=8b2baa…d6dcce
INFO [05-09|10:33:53] Imported new chain segment               blocks=50 txs=857  mgas=31.402 elapsed=8.054s    mgasps=3.898  number=3673628 hash=fa47a0…af7de0
INFO [05-09|10:34:03] Imported new chain segment               blocks=56 txs=961  mgas=33.647 elapsed=9.278s    mgasps=3.627  number=3673684 hash=96e299…025538
INFO [05-09|10:34:12] Imported new chain segment               blocks=33 txs=984  mgas=31.643 elapsed=9.384s    mgasps=3.372  number=3673717 hash=ca8dc0…1ba150
INFO [05-09|10:34:20] Imported new chain segment               blocks=42 txs=937  mgas=34.056 elapsed=8.021s    mgasps=4.245  number=3673759 hash=f0b461…5819d5
INFO [05-09|10:34:28] Imported new chain segment               blocks=46 txs=1042 mgas=41.767 elapsed=8.140s    mgasps=5.131  number=3673805 hash=fafc12…12aab0
INFO [05-09|10:34:37] Imported new chain segment               blocks=43 txs=1066 mgas=42.035 elapsed=8.615s    mgasps=4.879  number=3673848 hash=e21613…e030ea
INFO [05-09|10:34:45] Imported new chain segment               blocks=46 txs=927  mgas=36.355 elapsed=8.466s    mgasps=4.294  number=3673894 hash=bdfb4e…b8a955
INFO [05-09|10:34:53] Imported new chain segment               blocks=52 txs=854  mgas=34.650 elapsed=8.074s    mgasps=4.291  number=3673946 hash=079170…b905b9
INFO [05-09|10:35:01] Imported new chain segment               blocks=50 txs=1121 mgas=36.203 elapsed=8.039s    mgasps=4.503  number=3673996 hash=e42105…78ce47
INFO [05-09|10:35:09] Imported new chain segment               blocks=82 txs=1217 mgas=49.119 elapsed=8.071s    mgasps=6.086  number=3674078 hash=4728ce…494284
INFO [05-09|10:35:17] Imported new chain segment               blocks=72 txs=1241 mgas=45.618 elapsed=8.042s    mgasps=5.672  number=3674150 hash=b3f8fb…99a4ad
INFO [05-09|10:35:26] Imported new chain segment               blocks=64 txs=1028 mgas=35.910 elapsed=8.093s    mgasps=4.437  number=3674214 hash=8505a9…10fa3f
INFO [05-09|10:35:34] Imported new chain segment               blocks=64 txs=1058 mgas=48.075 elapsed=8.335s    mgasps=5.768  number=3674278 hash=599838…716723
INFO [05-09|10:35:42] Imported new chain segment               blocks=76 txs=1301 mgas=57.317 elapsed=8.016s    mgasps=7.150  number=3674354 hash=a368e9…7a9052
INFO [05-09|10:35:50] Imported new chain segment               blocks=49 txs=924  mgas=36.827 elapsed=8.377s    mgasps=4.396  number=3674403 hash=d4ad67…7dfad2
INFO [05-09|10:35:59] Imported new chain segment               blocks=53 txs=1086 mgas=46.007 elapsed=8.406s    mgasps=5.473  number=3674456 hash=291c28…7f4da6
INFO [05-09|10:36:07] Imported new chain segment               blocks=66 txs=1401 mgas=55.237 elapsed=8.039s    mgasps=6.871  number=3674522 hash=84c0d7…8c8e3c
INFO [05-09|10:36:14] Imported new chain segment               blocks=51 txs=1028 mgas=48.406 elapsed=6.764s    mgasps=7.156  number=3674573 hash=6702f1…88a89e
INFO [05-09|10:36:22] Imported new chain segment               blocks=11 txs=151  mgas=17.425 elapsed=8.074s    mgasps=2.158  number=3674584 hash=e39eb4…b5ab73

**Comment by evertonfraga** [comment]
That's interesting. It seems your internal database has a syntax error. If you didn't tampered with it, which I think is a far-fetched idea, we have a potential problem here. 

You can move your mist.lokidb file to another name/directory. It'll reset your current tabs, then you can add them later. 
`/Users/hengartner/Library/Application Support/Mist/mist.lokidb`

Would you mind sending me this file, so I can inspect it and assert the problem at more depth?
ev@ethereum.org

**Comment by evertonfraga** [comment]
Thanks! I'm glad it worked. I'll investigate the error on another thread.
