### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by clien88** [ethereum/mist#2232]
Hello, I downloaded the ethereum wallet last week (5-5-2017), but it doesn't seem synced. I tried to update, but it didn't work. How do I sync to the most up-to-date version?

Regards,
Carlien

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
