### ISSUE TITLE
8.10 release isn't signed and mac dmg doesn't have md5 hash listed

### ISSUE THREAD

**Issue by andrewmoroz** [ethereum/mist#2236]

**Comment by sraosha9** [comment]
I get wrong MD5 for Mac version of 8.10.

**Comment by luclu** [comment]
Thank you for raising awareness!

This was caused by some unexpected behaviour of our build system/process.
We fixed the issue and undertook additional steps to prevent this from happening again.

**Comment by hwinkler** [comment]
Not feeling confident enough to install 0.8.10 -- have you guys lost your certificate or something? What is going on?
