### ISSUE TITLE
Sidebar is not scrollable

### ISSUE THREAD

**Issue by theophoric** [ethereum/mist#2237]
#### System information
``````
Version: `0.8.9`
OS & Version: osx
Node type: `geth`
``````
Sidebar is not scrollable on my version of mist (`0.8.9`).  This is a pressing issue for Dapps like the ENS registrar, which appends a user's bids to the sub-menu along with a countdown to the reveal period.  There is no other way through the dapp interface to access these bids, other than searching for them individually.  Because the user can't scroll in the sidebar, once a wallet has submitted a certain number of bids, additional bids will be unaccessible.
![screenshot 2017-05-10 07 58 57](https://cloud.githubusercontent.com/assets/322054/25905520/14cc6e5e-3557-11e7-96b1-42f2139b9313.png)

**Comment by evertonfraga** [comment]
Please update do 0.8.10. We have completely redesigned the sidebar, and it
scrolls as it should.

**Comment by theophoric** [comment]
So it does.. very slick update.

Closing this issue out, but just in case anyone else has this problem with the sidebar in this version and comes across this issue:

Just update this value to `scroll`
![screenshot 2017-05-10 08 22 19](https://cloud.githubusercontent.com/assets/322054/25906806/800b6294-355a-11e7-86f1-3fc4f63c6eb4.png)
