### ISSUE TITLE
Coinbase sent .55 ETH but when the deposit showed up it was only .51 ETH. Why the 10% short?

### ISSUE THREAD

**Issue by SigmundFreud2049** [ethereum/mist#2239]
#### System information
``````
Version: `0.8.10`
OS & Version: MacOS
Node type: `eth/geth(default)`
``````
<img width="255" alt="screenshot 2017-05-10 15 38 00" src="https://cloud.githubusercontent.com/assets/28607373/25917695/efd272ca-3596-11e7-8149-ddd09902866f.png">

![screenshot 2017-05-10 15 37 34](https://cloud.githubusercontent.com/assets/28607373/25917772/39935bea-3597-11e7-9637-4be8b3cfbcac.png)

- Screenshots

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
