### ISSUE TITLE
Any risks importing pre-sale wallet using mist?

### ISSUE THREAD

**Issue by donald-circuit** [ethereum/mist#224]
I am quite paranoid about importing my pre-sale wallet and didn't dare to do it so far. Maybe one of you can help me anwering this question:

Is there any possibility that I can lose the funds importing it with mist?

Or being more specific:
Assumed that my mist wallet is backed up and safe from hackers, if mist crashes during the importation, can I always either get my funds using another importing tool (if the crash was before importing) or via my mist wallet private key (if the crash was after the import)? Or is there the slightest possibility that mist destroys the funds forever?
Thanks!

**Comment by tageeboy** [comment]
Hate to ask, but same question here. Scared to death to import the .json file anywhere so far LOL. I assume the wallet needs to fully sync before import is possible? It seems like I am hung at 1084708
of 1086057, is it possibly hung or just takes a while?

**Comment by frozeman** [comment]
The funds are on the address of the presale wallet. Mist will only import that address, it doesn't move the funds. So even if mist crashes you funds are still on that address..

@tageeboy sometimes it takes a while
