### ISSUE TITLE
Wallet not syncing, problems with blocks

### ISSUE THREAD

**Issue by Fthku** [ethereum/mist#2241]
Hi,
I had recently purchased a number of Ether coins, and had completed a transaction from Poloniex. This was over a day ago, and so far I see no ether in my Ethereum Wallet. I don't know how this works exactly, it says that it's downloading blocks, and has been doing so since yesterday and is only at 66%- it's even regressing! was previously at 67% and the block number seems to be rising again. As I'm typing it just jumped to 91% and back to 66%?
I can see the transaction on https://etherscan.io/ , but obviously doesn't show on my wallet.
Also, don't know if this is also related, but I tried to press create contract, and it has been "creating" since yesterday.

I'm on Windows 10, using version 0.8.9 and for what it's worth, I have a pretty fast internet connection.

I'd appreciate any help.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
