### ISSUE TITLE
Enhancement: estimated time to sync, progress increase in % per hour, and data sync rate

### ISSUE THREAD

**Issue by jamesray1** [ethereum/mist#2249]
#### System information
``````
Version: 0.8.9
OS & Version: windows 10 64 bit
Node type: geth
``````

#### 

Provide more information on syncing, like Bitcoin Core, e.g. the estimated time to sync, progress increase in % per hour, data sync rate, last block time and how far behind the network.

- Screenshots
![2017-05-12 21_10_44-mist](https://cloud.githubusercontent.com/assets/16969914/25995942/fe611d7e-3757-11e7-930d-1fad39c43a60.png)
![2017-05-12 21_14_46-bitcoin core - wallet](https://cloud.githubusercontent.com/assets/16969914/25995955/11fcdd50-3758-11e7-94fa-414b1b425b38.png)

**Comment by luclu** [comment]
Although this might be a good idea, it is not as easily doable as with bitcoin due to Ethereum's different block dynamics. Eventually this will be solved once light-clients have matured which is projected to happen during the next months.

**Comment by jamesray1** [comment]
OK.

**Comment by evertonfraga** [comment]
Hi @jamesray1, I came here just to say that our Light Client integration is now live. 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
