### ISSUE TITLE
Send/Deploy new contract screens are blank

### ISSUE THREAD

**Issue by jeremyellis** [ethereum/mist#225]
Clicking on the send tab produces a blank screen. The toolbar at the top is still visible but the rest of the screen is white. "Deploy new contract" also shows the same blank white screen. Nothing is printed in ~/.config/Mist/node.log

Versions:

Runing on Arch Linux 4.4.1-2-ARCH.

Build from source using mist-git AUR package, currently using git develop branch, commit 0ac211...

node version v5.7.0

**Comment by frozeman** [comment]
this has most likely to do with your non-propertary graphics card driver and chromium. See #75

**Comment by jeremyellis** [comment]
@frozeman Thanks for the quick reply. Sorry for the repeated issue, I did search related issues but must have missed that.
