### ISSUE TITLE
Not possible to run mist with "dev chain" or Rinkeby

### ISSUE THREAD

**Issue by 3esmit** [ethereum/mist#2250]
I tried to run geth into different networks than the configurable by Mist UI or CLI flag. 
When I run geth with --dev seems like mist cannot find geth ipc.
I didn't tried to mist with Rinkeby but I might need in future.

Are there any workarounds for running mist in 'dev chain' or other geth chains?

**Comment by 3esmit** [comment]
I'm working using `mist --rpc /my/geth.ipc` and in  `geth --dev --ipcpath /my/geth.ipc` or `geth --rinkeby --ipcpath /my/geth.ipc`.

**Comment by luclu** [comment]
@3esmit I tried to reproduce the issue with Mist `0.8.10` and geth `1.5.9` and `1.6.1` but it worked as expected.

This said I'm on macOS 10.12. Could you please specify your OS and application versions?

**Comment by 3esmit** [comment]
Seems like now is working.
