### ISSUE TITLE
"Unable to connect."

### ISSUE THREAD

**Issue by chefcaribou** [ethereum/mist#2252]
#### System information
``````
Version: Ethereum-Wallet-win64-0-8-10
OS & Version: windows 10
Node type: `geth(default)` 
``````

Hello,
I have some issues with Ethereum wallet.
This week, I downloaded the entire chain data.
But now, when I try to launch the app, I can't.

![ethereum problem2](https://cloud.githubusercontent.com/assets/25887768/26008161/e4a87f1c-3743-11e7-856d-171182da7fa0.PNG)

 I have no idea what it means. I don't have any command-line-interface bu I can dowload one if necessary.
I'am afraid because I haven't open the software for almost a year ...
Thanks in advance for the help !

Elise

**Comment by Kyniska** [comment]
same issue

**Comment by mg0716** [comment]
Yep. Same.
