### ISSUE TITLE
Mist crashes if left open every 2-3 days on MacOS 10.12.4

### ISSUE THREAD

**Issue by Idealist42** [ethereum/mist#2255]
#### System information
``````
Version: `0.8.10`
OS & Version:MacOS 10.12.4
Node type: `geth(default)`
``````
Mist will reliably crash every two days if I leave it running.  I have 8 of these crash logs, but I just attached the most recent 2.

[CrashLogs.zip](https://github.com/ethereum/mist/files/998284/CrashLogs.zip)

**Comment by luclu** [comment]
@Idealist42 thank you for the report.
This is an issue with electron, upstream reports are [available](https://github.com/electron/electron/issues?utf8=%E2%9C%93&q=is%3Aissue%20EXC_BAD_INSTRUCTION%20(SIGILL)) and being worked on.
We will continue to update electron to the latest version which will hopefully solve this issue rather soon.

As we can not do anything else than update the the latest electron version I will close this issue for now.
