### ISSUE TITLE
Ethereum Wallet sync always stuck at 60,000 blocks

### ISSUE THREAD

**Issue by kingcryptos** [ethereum/mist#2256]
Hi all,

I have been trying to sync my Ethereum wallet for 3 months now but to no avail. Being the Eth noob that I was, I sent my Eth to my wallet without syncing the blocks. 

Now I keep trying to sync but it is always stuck at 1%, after about 60,000 blocks. (which leaves me over 3 million blocks left to sync). I have tried clearing chain data multiple times with the same results.

If it helps, I have about 55gb of hard disk space, if this might be the cause of the issue.

And yes, the Eth is in my wallet as shown when checked on etherscan.io

I would really like to have access to my Eth once again. Thank you

Please kindly assist, help would be greatly appreciated.

**Comment by ValentinZalogo** [comment]
i have the same problem

**Comment by Burlyneo** [comment]
i have the same problem

**Comment by Peter-Henk** [comment]
Same problem here

**Comment by Jfaler** [comment]
Try using `geth --fast --cache=1024`

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
