### ISSUE TITLE
If/When initial sync stops/freezes progress bar seems to reset to zero

### ISSUE THREAD

**Issue by phonikg** [ethereum/mist#226]
A small bug only:

- geth was installed and sync was started
- Mist was then installed, but sync ended up frozen/stalled at block ~500,000 (progress bar showed 50%)
- geth was stopped
- Mist was restarted(this time I let mist start geth in the backround) and it continues to sync, however progress bar started back at 0% I am now at block ~800,000 and progress bar represents ~50% of full sync instead of ~80%

![image](https://cloud.githubusercontent.com/assets/7241066/13482053/1f8ba818-e0b8-11e5-8428-c7b516bfb612.png)

**Comment by frozeman** [comment]
Thats normal, as we use fast sync, which only process the chain after it downloaded all the headers..

**Comment by phonikg** [comment]
Thanks Fabian,... and did not realize Mist utilizes --fast by default!
