### ISSUE TITLE
Blockchain keeps re-syncing

### ISSUE THREAD

**Issue by gorilla2112** [ethereum/mist#2262]
I had a fully synced blockchain that I was using for a long time. Then for some reason, it started back at 3mil blocks to go. So I erased my chain data (that was still there) and did a "geth --fast" in CMD. 10 hours later I stopped CMD and opened Wallet to see progress. I had 700k blocks left. I left it alone for an hour or two and when I came back it was back up to 3mil blocks left. Thoughts?!

``````
Version: `0.8.10`
OS & Version: windows 10
Node type: `eth/geth(default)`
``````

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
