### ISSUE TITLE
ethereum node connection error version 8.10 win 64 

### ISSUE THREAD

**Issue by bit888** [ethereum/mist#2263]
#### System information
``````
Version: `8.10`
OS & Version: windows
Node type: `eth/geth(default)`
``````

![e2](https://cloud.githubusercontent.com/assets/28691071/26036929/4104be0e-38f9-11e7-9131-9e8ac6a01999.PNG)
![e3](https://cloud.githubusercontent.com/assets/28691071/26036930/45622662-38f9-11e7-87ed-fda68157d6e8.PNG)

I am new, I am not a programmer, how to fix it and get the node connected and go open the wallet

**Comment by ajthub** [comment]
I am getting the same same error as above. 

I am using the latest versions of (Mist v0.8.10) and Ethereum wallet and geth 1.6

Should we use the old version?

**Comment by luclu** [comment]
Could you please upload the node.log files as described [here[(https://github.com/ethereum/mist/issues/new)?

**Comment by bit888** [comment]
pls see the zip file with node.log

**Comment by bit888** [comment]
INFO [05-16|01:51:51] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/windows-386/go1.8.1
INFO [05-16|01:51:51] Allocated cache and file handles         database=C:\\Users\\ONYX\\AppData\\Roaming\\Ethereum\\geth\\chaindata cache=1024 handles=1024


these are node.log info

**Comment by ajthub** [comment]
Similar issue here...
 `I0515 00:27:09.346757 ethdb/database.go:83] Alloted 512MB cache and 1024 file handles to C:\Users\joe\AppData\Roaming\Ethereum\chaindata
I0515 00:27:09.634949 cmd/utils/flags.go:842] ------------------------------------------------------------------------------------------------
I0515 00:27:09.634949 cmd/utils/flags.go:843] Geth is currently configured to SUPPORT the DAO hard-fork!
I0515 00:27:09.634949 cmd/utils/flags.go:844] You can change your choice prior to block #1920000 with --support-dao-fork or --oppose-dao-fork.
I0515 00:27:09.634949 cmd/utils/flags.go:845] After the hard-fork block #1920000 passed, changing chains requires a resync from scratch!
I0515 00:27:09.634949 cmd/utils/flags.go:846] ------------------------------------------------------------------------------------------------
I0515 00:27:09.638952 ethdb/database.go:171] closed db:C:\Users\joe\AppData\Roaming\Ethereum\chaindata
I0515 00:27:09.639954 cmd/utils/flags.go:592] WARNING: No etherbase set and no accounts found as default
I0515 00:27:09.640955 ethdb/database.go:83] Alloted 512MB cache and 1024 file handles to C:\Users\joe\AppData\Roaming\Ethereum\chaindata
I0515 00:27:09.769039 ethdb/database.go:83] Alloted 16MB cache and 16 file handles to C:\Users\joe\AppData\Roaming\Ethereum\dapp
I0515 00:27:09.774042 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I0515 00:27:09.775042 eth/backend.go:201] Blockchain DB Version: 3
I0515 00:27:09.776044 core/blockchain.go:214] Last header: #384 [d3d5d5c1…] TD=7225953107849
I0515 00:27:09.776044 core/blockchain.go:215] Last block: #384 [d3d5d5c1…] TD=7225953107849
I0515 00:27:09.776044 core/blockchain.go:216] Fast block: #384 [d3d5d5c1…] TD=7225953107849
I0515 00:27:09.776044 eth/handler.go:113] blockchain not empty, fast sync disabled
I0515 00:27:09.777044 p2p/server.go:313] Starting Server
I0515 00:27:11.775646 p2p/discover/udp.go:217] Listening, enode://2bb137e172e50d5f1132cbd3fb22a95f4e1f52199c9b9a2b76fe8e2aeb18f71e23954aaf09e4b1994a686cfe4a0fcdf18c57092f23b2096a4c179c5100a4e470@68.190.242.17:30303
I0515 00:27:11.775646 p2p/server.go:556] Listening on [::]:30303
I0515 00:27:11.776647 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc
I0515 00:27:21.776106 eth/downloader/downloader.go:319] Block synchronisation started
`

**Comment by ajthub** [comment]
**Here is my 2nd computer running Mist**

INFO [05-14|22:43:47] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/windows-amd64/go1.8.1
INFO [05-14|22:43:47] Allocated cache and file handles         database=C:\\Users\\USERNAME HERE\\AppData\\Roaming\\Ethereum\\geth\\chaindata cache=1024 handles=1024
INFO [05-14|22:43:47] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Engine: ethash}"
INFO [05-14|22:43:47] Disk storage enabled for ethash caches   dir=C:\\Users\\USERNAME HERE\\AppData\\Roaming\\Ethereum\\geth\\ethash count=3
INFO [05-14|22:43:47] Disk storage enabled for ethash DAGs     dir=C:\\Users\\USERNAME HERE\\AppData\\Ethash                          count=2
INFO [05-14|22:43:47] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [05-14|22:43:48] Loaded most recent local header          number=1326269 hash=ade014…c5007b td=13361508401431437613
INFO [05-14|22:43:48] Loaded most recent local full block      number=0       hash=d4e567…cb8fa3 td=17179869184
INFO [05-14|22:43:48] Loaded most recent local fast block      number=1313071 hash=e4309b…825b95 td=13010175627787633898
INFO [05-14|22:43:48] Starting P2P networking
INFO [05-14|22:43:50] RLPx listener up                         self=enode://c8fcebb35d4d17ea206b69046208e1b8d57db26c3f4610a902ad800f38f80de1cf0922b6c28709204f15c92645e39ab550580c56f8829fbb1e60e95033d00d2a@[::]:30303
INFO [05-14|22:43:50] IPC endpoint opened: \\.\pipe\geth.ipc
INFO [05-14|22:44:10] Block synchronisation started
INFO [05-14|22:44:12] Imported new state entries               count=1 elapsed=595.034ms processed=1 pending=17
INFO [05-14|22:44:13] Imported new state entries               count=2 elapsed=701.540ms processed=3 pending=49
INFO [05-14|22:44:18] Imported new block headers               count=0 elapsed=31.001ms  number=1313263 hash=75cea5…f981f1 ignored=192
INFO [05-14|22:44:19] Imported new state entries               count=6 elapsed=6.206s    processed=9 pending=145
INFO [05-14|22:44:22] Imported new block headers               count=0 elapsed=127.006ms number=1313455 hash=c56ee2…6f9586 ignored=192
INFO [05-14|22:44:25] Imported new state entries               count=7 elapsed=4.983s    processed=16 pending=257
INFO [05-14|22:44:25] Imported new block receipts              count=3 elapsed=698.039ms number=1313074 hash=64744d…54fe92 ignored=0
INFO [05-14|22:44:28] Imported new block headers               count=0 elapsed=40.001ms  number=1313647 hash=408d68…e92c06 ignored=192
INFO [05-14|22:44:29] Imported new state entries               count=9 elapsed=3.945s    processed=25 pending=395
INFO [05-14|22:44:32] Imported new state entries               count=10 elapsed=2.894s    processed=35 pending=552
INFO [05-14|22:44:36] Imported new state entries               count=15 elapsed=3.919s    processed=50 pending=783
INFO [05-14|22:44:40] Imported new state entries               count=19 elapsed=3.609s    processed=69 pending=1077
INFO [05-14|22:44:43] Imported new state entries               count=26 elapsed=2.643s    processed=95 pending=1478
INFO [05-14|22:44:46] Imported new state entries               count=38 elapsed=3.104s    processed=133 pending=2057
INFO [05-14|22:44:49] Imported new block receipts              count=174 elapsed=2.560s    number=1313248 hash=333525…4771a2 ignored=0
INFO [05-14|22:44:51] Imported new state entries               count=43  elapsed=4.114s    processed=176 pending=2723
INFO [05-14|22:44:53] Imported new block receipts              count=134 elapsed=1.812s    number=1313382 hash=719d65…91f71f ignored=0
INFO [05-14|22:44:56] Imported new state entries               count=51  elapsed=4.541s    processed=227 pending=3511
INFO [05-14|22:44:58] Imported new block receipts              count=245 elapsed=1.850s    number=1313627 hash=733414…8c64a1 ignored=0
INFO [05-14|22:45:03] Imported new state entries               count=61  elapsed=6.923s    processed=288 pending=4032
INFO [05-14|22:45:04] Imported new block receipts              count=20  elapsed=1.526s    number=1313647 hash=408d68…e92c06 ignored=0
INFO [05-14|22:45:15] Imported new state entries               count=55  elapsed=10.378s   processed=343 pending=4230
INFO [05-14|22:45:15] Imported new state entries               count=1   elapsed=11.535s   processed=344 pending=4229
INFO [05-14|22:45:28] Imported new state entries               count=2   elapsed=704.039ms processed=346 pending=4507
INFO [05-14|22:45:28] Imported new state entries               count=46  elapsed=12.828s   processed=392 pending=4506
INFO [05-14|22:45:55] Imported new state entries               count=31  elapsed=10.544s   processed=423 pending=4797
INFO [05-14|22:45:55] Imported new state entries               count=41  elapsed=26.723s   processed=464 pending=4796
INFO [05-14|22:46:21] Imported new state entries               count=25  elapsed=7.904s    processed=489 pending=4946
INFO [05-14|22:46:32] Imported new state entries               count=33  elapsed=11.446s   processed=522 pending=5057
INFO [05-14|22:46:32] Imported new state entries               count=32  elapsed=35.696s   processed=554 pending=5056
WARN [05-14|22:46:32] Synchronisation failed, dropping peer    peer=9d735af0e1bc9e17 err="retrieved hash chain is invalid"
INFO [05-14|22:47:31] Imported new state entries               count=1   elapsed=10.000ms  processed=555 pending=17
INFO [05-14|22:47:31] Imported new state entries               count=4   elapsed=17.999ms  processed=559 pending=81
INFO [05-14|22:47:32] Imported new state entries               count=33  elapsed=548.028ms processed=592 pending=595
INFO [05-14|22:47:36] Imported new block headers               count=0   elapsed=58.005ms  number=1313839 hash=fe9053…96fec3 ignored=192
INFO [05-14|22:47:59] Imported new state entries               count=101 elapsed=26.415s   processed=693 pending=1468
INFO [05-14|22:48:06] Imported new block headers               count=0   elapsed=53.004ms  number=1314031 hash=be5975…3220ee ignored=192
INFO [05-14|22:48:42] Imported new state entries               count=88  elapsed=43.026s   processed=781 pending=1761
INFO [05-14|22:48:44] Imported new block receipts              count=2   elapsed=1.462s    number=1313649 hash=7cf0a9…9cdae7 ignored=0
INFO [05-14|22:48:48] Imported new block headers               count=0   elapsed=37.998ms  number=1314223 hash=b33e04…a730e5 ignored=192
INFO [05-14|22:49:08] Imported new state entries               count=84  elapsed=24.595s   processed=865 pending=2033
INFO [05-14|22:49:10] Imported new block receipts              count=2   elapsed=1.651s    number=1313651 hash=256d27…8319ab ignored=0
INFO [05-14|22:49:11] Imported new state entries               count=86  elapsed=1.614s    processed=951 pending=3340
INFO [05-14|22:49:14] Imported new block headers               count=0   elapsed=29.002ms  number=1314415 hash=e12213…99bfbd ignored=192
INFO [05-14|22:49:21] Imported new state entries               count=131 elapsed=9.592s    processed=1082 pending=5025
INFO [05-14|22:49:23] Imported new block receipts              count=4   elapsed=2.347s    number=1313655 hash=e9866a…b097ad ignored=0
INFO [05-14|22:49:57] Imported new state entries               count=138 elapsed=35.554s   processed=1220 pending=5352
INFO [05-14|22:49:58] Imported new block receipts              count=2   elapsed=964.056ms number=1313657 hash=c8ca47…e188a8 ignored=0
INFO [05-14|22:50:20] Imported new state entries               count=119 elapsed=21.853s   processed=1339 pending=5667
INFO [05-14|22:50:52] Imported new state entries               count=127 elapsed=31.171s   processed=1466 pending=6036
INFO [05-14|22:51:05] Imported new block headers               count=0   elapsed=299.018ms number=1315183 hash=61ce01…7c4fbd ignored=768

**Comment by ajthub** [comment]
**Here is one of my computers running Mist I used an older version because the new on on May 08 didn't work.** 

[mist windows.zip](https://github.com/ethereum/mist/files/1002821/mist.windows.zip)

**Comment by ajthub** [comment]
Here is one of my computers running Mist I used an older version because the new on on May 08 didn't work.
[mist windows.zip](https://github.com/ethereum/mist/files/1002823/mist.windows.zip)

**Comment by piercosta** [comment]
Same problem, only with testnet

#### System information
``````
Version: `0.8.10`
OS & Version: Windows 10 64 bit
Node type: `geth`
``````

![image](https://cloud.githubusercontent.com/assets/664328/26155700/62df53aa-3b14-11e7-839b-edf6fd678409.png)


INFO [05-17|15:17:36] Starting peer-to-peer node               instance=Geth/v1.6.0-stable-facc47cb/windows-amd64/go1.8.1
INFO [05-17|15:17:36] Allocated cache and file handles         database=C:\\Users\\Pier\\AppData\\Roaming\\Ethereum\\geth\\chaindata cache=128 handles=1024

**Comment by bit888** [comment]
same error, question is how to resolve it

**Comment by jamesray1** [comment]
I get the  same error.

Win 10 64 bit OS x64 processor 
![2017-05-18 22_29_36-ethereum node connection error version 8 10 win 64 issue 2263 ethereum_mist](https://cloud.githubusercontent.com/assets/16969914/26202128/93381748-3c19-11e7-97a7-ecd01c443a2b.png)

I am unable to copy and paste the text in this error window.

While I can't open Mist as it is stuck on this screen:

![2017-05-18 22_33_10-mist](https://cloud.githubusercontent.com/assets/16969914/26202246/06043586-3c1a-11e7-92d8-f9a0ec1c97d2.png)

I can access the data in my home directory under (Home Drive for Users which is usually C but which I have set to an external hard drive) > Users > User (your name may vary) > AppData > Roaming > Mist >node.log Text doc and node.log.x where x is 0-3. 
[node.log (2).zip](https://github.com/ethereum/mist/files/1010867/node.log.2.zip)

**Comment by piercosta** [comment]
Any workaround?

**Comment by jamesray1** [comment]
@frozeman @luclu @evertonfraga

**Comment by marcelo-lipienski** [comment]
:+1: 

Trying to change to testnet on both Mist and Ethereum Wallet throws same error.
Running both at version 0.8.10 on Windows 7 x64

**Comment by Jay991** [comment]
Same problem on Mac OS 
![screen shot 2017-08-23 at 1 39 20 pm](https://user-images.githubusercontent.com/25933983/29612103-c1ff5510-8808-11e7-9799-c4d836d7df03.png)

**Comment by manuelbieh** [comment]
Same problem here on Windows 10, Geth 1.7.2 and Mist 0.9.2. Only occurs when I try to connect to rinkeby or ropsten. Main network works fine.

**Comment by evertonfraga** [comment]
This happens after expiring the 30s connection timeout during connection bootstrap.

Try restarting Mist in order to get active peers.

**Comment by evertonfraga** [comment]
This happens after expiring the 30s connection timeout during connection bootstrap.

Try restarting Mist in order to get active peers.
