### ISSUE TITLE
How to figure out which wallet was used (know address and password)

### ISSUE THREAD

**Issue by Terrambo** [ethereum/mist#2265]
hi,
I started mining Eth just over a year ago, then due to a bad hard drive I stopped. I had actually forgotten about my Eth balance, just recently cleaning up my office I found a piece of paper with my address and checked to see I have 25 Eth on that account mined over a year ago. When I check the status etherscan.io it shows me my balance.
Is there any way to recover the balance and move it to a new account? I have forgotten which wallet I used and do not know how to transfer that balance into a new account. Any help would be appreciated. I am certain I remember the password to the old account, can I trick a new wallet into the old address?

**Comment by evertonfraga** [comment]
Hi @Terrambo, 

You definitely need the keystore file (`UTC-xxxx.json`). Don't you have any back up?
