### ISSUE TITLE
Mouse goes nuts (hard to control-moves places randomly) with Ethereum Wallet running even after synching.

### ISSUE THREAD

**Issue by nrhirsch** [ethereum/mist#2268]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by luclu** [comment]
Hello @nrhirsch, this is most definitely an issue with your hardware or some other software interfering with the mouse cursor placement. Could you kindly check if using a different mouse helps to resolve your issue?

I will close this for now.

**Comment by nrhirsch** [comment]
Ok but it's the only program (of many) that causes the issue and as soon as I exit the program all is good again.

**Comment by evertonfraga** [comment]
Hi @nrhirsch, did you manage to fix that problem? 
What OS were you using back then? 

thanks

**Comment by nrhirsch** [comment]
Gave up on mist and used metamask.
