### ISSUE TITLE
ENS: Don't find my bids...even after import 

### ISSUE THREAD

**Issue by Frankee72** [ethereum/mist#2269]
#### System information
``````
Version: `0.8.10`
OS & Version: osx 10.12.4
Node type: `eth/geth(default)`
``````
today, i updated to 8.10 and started mist. everything worked fine, it shows my watchlist. it fully syncs. 

but when i click on a ens name, it doesn't show the correct status of the bid (that i'm bidding on it and the amount of the bid). i then tried to import the bids and it still didn't show them. 

i went back to 8.9/8.8 and i'm back now to 8.10 - all the same bug. 

all other functions work so far. 

thank you for your help. 

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files 

[Node.zip](https://github.com/ethereum/mist/files/1001728/Node.zip)

**Comment by evertonfraga** [comment]
please open this issue at https://github.com/ethereum/ens-registrar-dapp/
