### ISSUE TITLE
The Mist UI can't process pre-sale password containing "$"

### ISSUE THREAD

**Issue by HeaTeR** [ethereum/mist#227]
I've got a wallet backup with password containing letter "$", and I've got a password error message.

I could simply import my wallet using geth successfully. Hopefully there's a bug.

**Comment by mhodgson** [comment]
I can confirm I am having the same problem.

**Comment by frozeman** [comment]
It seems like there is a issue with the geth connection, could you please let me know what OS youre using?

**Comment by mhodgson** [comment]
I’m on Mac OS X (10.11.2). Let me know if I can help. I’m relatively new to Ethereum but happy to dig in.

**Comment by frozeman** [comment]
@mhodgson im also on mac and it works fine for me. If you can empty this presale file (e.g. kraken) and give me the file + password i can try finding out whats wrong.

**Comment by mhodgson** [comment]
@frozeman ok. I haven’t bitten the bullet and moved my ether to an exchange yet. I’ll let you know once I do.

**Comment by alexvandesande** [comment]
It's not related to `$` character, but a general bug: https://github.com/ethereum/mist/issues/182

This is a duplicate

**Comment by alexvandesande** [comment]
@mhodgson @HeaTeR could you please download the [latest Wallet release, 0.5.2](https://github.com/ethereum/mist/releases/tag/0.5.2) and tell me if the problem persists?

**Comment by edwolf** [comment]
@alexvandesande I can confirm that this issue also persists with 0.5.2.  I successfully loaded my presale onto a PC, but wont work with Mac...really freaked me out at first.  Would there be any issue with transferring my balance from PC to Mac wallet? I know that seems like a stupid question but this whole thing made me pretty nervous.
