### ISSUE TITLE
0.8.10 not signed, and insecure checksum given in release

### ISSUE THREAD

**Issue by VoidingWarranties** [ethereum/mist#2272]
Part of this has already been brought up in #2236, but I don't think the issue was sufficiently addressed.

I have two concerns:
1. For 0.8.10, MD5 checksums were listed for the prebuilt binaries instead of SHA256.
2. The 0.8.10 tag was not signed, when the previous 4 release tags have been signed.

Why the sudden discrepancy in the release process?

**Comment by evertonfraga** [comment]
@luclu can you change our build server to generate SHA256 checksums again?

**Comment by luclu** [comment]
@evertonfraga with pleasure, I will update also update them for the geth bins as the sha256 checking routine has now been included for over 5 releases.

**Comment by hwinkler** [comment]
Weird this hasn't been fixed yet. Nobody should install an unsigned binary, that's a bad habit to get into where valuable data is at stake. Can you please escalate? It would be good to see the signing become well established as part of your build process, and unquestioned.

**Comment by paulfreeman** [comment]
What is the status of this issue?  Mac OSX version 8.10 has incorrect file name <unsigned> associated with MD5 checksum.  Version for download is not named 'unsigned'' and downloaded version **is** actually signed.

**Comment by hwinkler** [comment]
Lack of response gives me an uncomfortable feeling about Ethereum processes.

**Comment by evertonfraga** [comment]
As promised, `v0.8.10` tag is now signed and its corresponding builds have SHA-256 checksums.

https://github.com/ethereum/mist/releases/tag/v0.8.10

**Comment by evertonfraga** [comment]
@hwinkler we had a huge amount of issues opened in the last weeks, due to increasing attention drawn to ethereum. That slowed down our ability to cope with the issues, but we're working on this.

I am closing this, thanks.

**Comment by evertonfraga** [comment]
SHA-256 checksums are back on our build process: https://github.com/ethereum/mist/pull/2917

Also, they are listed on v0.9.0 release. Thanks.
