### ISSUE TITLE
Lost ETH

### ISSUE THREAD

**Issue by Quellwasser** [ethereum/mist#228]
Hi guys,
I had 15 (but I only found a picture with 10 eth) mining reward one my etherbase Account but my Mist wallet wasn't synced. Today it finally synced and my Balance is 0eth. There are no transactions. I also tried to Check Balance with the console it also shows 0 ETH what did I miss? I just started mining about 3 days ago, and havn't done anything with ETH yet. Would I see if someone hacked into my Account and transferred some ETH? 

![74ysccdsllru](https://cloud.githubusercontent.com/assets/17612127/13489180/e6981e60-e125-11e5-9d32-d94c66ec910f.png)
![lzes7no25g9l](https://cloud.githubusercontent.com/assets/17612127/13489189/efbb139e-e125-11e5-9d1f-ffcdb5a64534.png)

**Comment by frozeman** [comment]
You can't mine if you haven't synced your node. Then you will mine your own chain and once it syncs up, geth will disregard your own chain as invalid and syncs up to the real one...

next time sync up first.

Also be aware that mining is not that easy anymore , even with graphic cards

**Comment by Quellwasser** [comment]
Ok, that's bad news. But thank you for letting me know. Not exactly sure why you are telling me that mining isn't easy anymore ^^
