### ISSUE TITLE
Did not received my Ether

### ISSUE THREAD

**Issue by jaylimix** [ethereum/mist#2281]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

![image](https://cloud.githubusercontent.com/assets/6631965/26209480/7aeb4af6-3c1f-11e7-8f7e-235ab003c1cc.png)

As you can see from the picture, my computer has already downloaded past this block, but my wallet has yet to show any Ether.

**Comment by reminiscethis** [comment]
Having the same issue.

**Comment by jaylimix** [comment]
I have received my Ether now after waking up from sleep
