### ISSUE TITLE
Preferences to change data and keystore folder - please!!!

### ISSUE THREAD

**Issue by mpuz** [ethereum/mist#2285]
Dear developers, please add the possibility to change folder where data and keystore is stored from the GUI, using "Preferences" menu as it is used in thousands of apps.

**Comment by rstormsf** [comment]
pelase

**Comment by alexvandesande** [comment]
We are trying to remove complexity from the interface and IMHO I believe users would be better served by not having to worry about the data folder, which should be made better with remote nodes and light sync.
