### ISSUE TITLE
sync taking extremly long time

### ISSUE THREAD

**Issue by chrisj214** [ethereum/mist#2286]
#### System information
``````
Version: `0.8.9`
OS & Version: osx
Node type: `eth/geth(default)`
``````

 For the past few weeks I have been trying to sync my ethereum wallet with the blockchain, ive left my laptop on for over 4 days and still to no avail. Ive tried delteing the chain data and doing geth --fast in terminal but i get the error "-bash: geth: command not found".currently running a macbook pro mid 2012 with 4gb ram.

screenshot of console : https://gyazo.com/f5cd15bb5806e08ec2ebb783856a036a

**Comment by chrisj214** [comment]
changed to "8 hours since last block" and then went back to syncing again. I dont know how anyones going to take this currency seriously when you cant even access your wallet its a joke.

**Comment by reminiscethis** [comment]
I agree it's very disconcerting to not be able to access your wallet.

**Comment by reminiscethis** [comment]
I have deleted the chaindata as was recommended by someone and it resulted in a little more action, but now I am stalled again at 
Downloading block 53,750 of 3,733,351, 
Downloading chain structure 606,889 of 629,616

**Comment by reminiscethis** [comment]
Is this really the only venue for support? Because I'm not feeling supported.

**Comment by reminiscethis** [comment]
Turning off my anti-virus software did the trick. I hope that's useful to you chrisj214.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
