### ISSUE TITLE
Can not connect to node.

### ISSUE THREAD

**Issue by alexpantyukhin** [ethereum/mist#2288]
On the checking network I got a following error:

#### System information
``````
Version: `0.8.10`
OS & Version: windows
Node type: `geth(default)`
``````

![eth_error](https://cloud.githubusercontent.com/assets/6513121/26238944/436047fe-3c8c-11e7-8591-ccb2a6b485f6.png)

**Comment by BENGiiii** [comment]
i got the sam issue, is it working allready??
