### ISSUE TITLE
Old Layout with 0.8.10

### ISSUE THREAD

**Issue by Hirbod** [ethereum/mist#2292]
#### System information
``````
Version: `0.8.10`
OS & Version: osx
Node type: `eth/geth(default)`
``````

I've updated with the pre-release of 0.8.10 verifying the dmg-hash, but I still do have the old layout. (not a sidebar at all, still the old tabs) I've reinstalled two times, but I can't switch nor see the new design of the wallet.

I am on MBP 2012 Retina, everything in-sync (latest macOS Sierra installed)

Any idea why a friend of mine with an identical setup and MBP does see the new layout but I don't?

**Comment by Hirbod** [comment]
anybody?

**Comment by proehlen** [comment]
Had exactly the same issue.  Only just discovered that I need to start mist with ` --mode mist`.  Beats me why it isn't the default mode.

**Comment by Hirbod** [comment]
How did you pass that parameter? I am opening the App from OSX Application folder. @proehlen

**Comment by proehlen** [comment]
I'm on Linux but this link explains how apparently:

https://wpguru.co.uk/2016/11/how-to-launch-a-mac-app-with-command-line-parameters-from-the-dock/

**Comment by evertonfraga** [comment]
Hi, you two should have experienced different root causes. 

I'm sorry it's taken too long to respond, we had a huge influx of issues as the ethereum ecosystem grew a lot recently. I'll keep my eyes open to that issue — it is an interesting one — although it was the first report of this sorts.
