### ISSUE TITLE
Deleted Chaindata folder to fast sync - Ether all gone - Help

### ISSUE THREAD

**Issue by alextimberlake** [ethereum/mist#2293]
Hello,

I had about 42 ETH in my Mist wallet. I wanted to move this to another address, but I had not kept geth synced. Therefore, I deleted the chaindata folder because I read that was required to use geth--fast--cache 1024 in the command window. I believe I am fully synced now, but I see 0 ETH in my wallet. I can't be certain I am 100% synced because the status bar in the lower left hand corner does not look like it is working.

If you check Etherscan.io you will see I had 42.19869531 Ether in my wallet. Someone please help. I'm freaking out a little.

I had backups saved to multiple locations, but when I open all of these, they all still show 0 ETH.

![image](https://cloud.githubusercontent.com/assets/28819389/26272875/f0e82980-3ce8-11e7-8928-dcfc25979947.png)

![image](https://cloud.githubusercontent.com/assets/28819389/26272881/09c65562-3ce9-11e7-9fff-822529bb173a.png)

![image](https://cloud.githubusercontent.com/assets/28819389/26272892/1e70155c-3ce9-11e7-8ffd-d0b2f60030b0.png)

**Comment by jspindel95** [comment]
It doesn't look like you are synced with the blockchain at all. if etherscan shows the ether in your account then it is there so you don't have to worry about it "disappearing" but just about how to get your blockchain to sync

**Comment by alextimberlake** [comment]
Thanks for the reply. I agree with your assessment. I downloaded the newer
version of Mist and started over and it worked.... just annoying that it
takes almost an entire day to sync... alas

**Comment by mnmglobalgit** [comment]
@jspindel95 I have the same problem with AVG.  Did you just turn it off to correct?

**Comment by jspindel95** [comment]
Yeah I thing I just added mist as an approved program in the settings

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
