### ISSUE TITLE
Typo found after creating new account

### ISSUE THREAD

**Issue by BeerMan81** [ethereum/mist#2297]
#### System information
``````
Version: `0.8.10`
OS & Version: windows
Node type: `eth/geth(default)`
``````

I just created a new account using Ethereum Wallet. After confirming my password the following prompt shows up.
![image](https://cloud.githubusercontent.com/assets/28826285/26276405/bfc3061e-3d3c-11e7-9d79-f0e5fd5ee7ba.png)

"loose" should say "lose"

Thank you.

**Comment by alexvandesande** [comment]
Fixed it. Thanks

We are reviewing at old unanswered issues, sorry it took so long to reach yours, it's a long backlog
