### ISSUE TITLE
Account balance not updating [TEST-NET]

### ISSUE THREAD

**Issue by kristianheljas** [ethereum/mist#2301]
#### System information
``````
Version: `0.8.1`
OS & Version: Windows 10
Node type: `geth 1.6.0`
``````

I made a transaction half an our ago and my client is fully updated, but the account balance is still zero although etherscan shows the balance. 

Similiar thing happened when i tried to copy my keyfile from another PC and it was not showing my balance, that's why i tried to transfer at first place.

![image](https://cloud.githubusercontent.com/assets/11139388/26283001/bb66fad6-3e26-11e7-89c3-fb84801237d9.png)

What can i do?

**Comment by EternalDana** [comment]
Exact same problem - who can I contact to help resolve this. My ether has vanished, but its written onto the blockchain.

**Comment by DarkRsing** [comment]
Exact same problem as me too

**Comment by garretlaxton** [comment]
Your wallets most likely needs to sync. Kristian, your wallet looks to be running in the `test-net` which is probably the problem.

**Comment by EternalDana** [comment]
Phew, I hope that's the case.

Is that just a matter of leaving the computer to sync for a while?

I must sound clueless.

**Comment by kristianheljas** [comment]
@garretlaxton As you see from the image (bottom left corner of Mist app), my data was in sync..

And yes, i'm aware that i am using testnet, i even pointed it out in the title.

However a few uninstalls/installs and re-downloading the chain again i finally see my balance in the mist app.

Maybe the blockchain was corrupted either by network issues or anti-virus software..

**Comment by pablolarrimbe** [comment]
Hello,

I'm having the exact same issue.  I made a transfer through bitcoin 16 hours ago. 

My account shows 0 balance:
![image](https://user-images.githubusercontent.com/16912443/27761637-dc55026c-5e68-11e7-881d-d1f9b25705f0.png)

However, etherscan sees the transaction and shows the wallet as having balance:

![image](https://user-images.githubusercontent.com/16912443/27761636-d36a37ee-5e68-11e7-9491-5ec4e5b96cca.png)

I'm not on the test network and I'm on 0.8.10 with client fully synced.

I'd like to know what's going on and how to fix.

Thanks,
Pablo.

**Comment by pablolarrimbe** [comment]
Seems like it might have been a sync issue for me although I was already all synced when I reported this.  Anyways, it's fixed now.
