### ISSUE TITLE
my system crashed i i didn't do backup. Help!

### ISSUE THREAD

**Issue by nik2392** [ethereum/mist#2302]
my system crashed i i didn't do backup  .I dont know what to do. I know only my address.

**Comment by alexvandesande** [comment]
We are looking at older issues that didn't get answered and just found yours. It's a very terrible thing to happen indeed! Without a private key you cannot recover your ether, but a system crash doesn't mean data loss. If you haven't erased the disk and kept the old machine around, if you give the hard drive to a specialist they will be able to recover data from it. Good luck!
