### ISSUE TITLE
The new update 0.8.10 is so very slow & peer connections stops a lots of time

### ISSUE THREAD

**Issue by super83** [ethereum/mist#2305]
#### System information
``````
Version: `0.8.10
OS & Version: windows 10
Node type: `eth/geth(default)`
``````

Please fix this new wallet version 0.8.10.
It too slow and it took me forever to download the blocks and chains.

Problems i have with 0.8.10 version:
1. Downloading the blocks & downloading the chains took forever...this new update is so slow.
2. Peer connections are sometime stop or frequently loosing peer connections while downloading the chains and blocks.

Please improve Ethereum wallet sycn......ETHEREUM NEED TO HAVE FAST WALLET SYNC EVERY TIME WE OPEN THE WALLET......NOT JUST DURING THE START OR DURING FIRST INSTALLED !!!

PLEASE ETHEREUM DEVS.....WE NEED THIS TO BE DONE SOON.

Regards,
Ethereum fan

**Comment by grazi177** [comment]
I need help, I downloaded Ethereum wallet a while ago , 2 years ago, invested 200 dollars in it, I did open the wallet a few times and it started the node upload stuff. Today I started to run the wallet and i get an error saying  Could not start Etheureum node, If you installed Geth, use this command to run it :

**Comment by grazi177** [comment]
win32 x64    Fatal: blockchain db err : The process cannot access the file because it is being used by another process.

**Comment by davedavis** [comment]
Hi @super83 
Have you tried playing with your system time settings? 
I unchecked "Automatic Daylight Savings" and shifted my clock back an hour (not ideal I know) and this corrected the speed issue. 

There's still a ton of problems and it never fully syncs in the UI but it's makes the node usable. 
This troubleshooting guide is actually pretty useful: https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide

Try starting Geth at the command line manually and see if any errors or warnings are shown. It might help diagnose any issues you're having.

**Comment by super83** [comment]
Thanks @davedavis,
I'm not playing with my time setting yet....because my wallet is open and been sync over 24 hours and overnight, and it still now finished snyc the blocks and chains yet....it took forever to download this chain.

And it seem it getting slower and slower by hours downloading this chain :(
I don't know how long it been, but i know it been over 24 hours since i start fresh installed my wallet...but this fast sync is just not fast enough in this new 0.8.10 update.

It might took me several days to download this chain and block....even with this fast sync mode

**Comment by GitSpree23** [comment]
I am working on a seminar on Ethereum and I hastily used `geth --testnet` to sync. But then I turned off my computer, and am now unable to start sync. Nothing happens after the `IPC endpoint opened ....` line.

**Comment by udovdh** [comment]
As the bitcoin blockchain syncs considerably faster there _is_ work to be done.

**Comment by evertonfraga** [comment]
Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.
