### ISSUE TITLE
No blocks downloading

### ISSUE THREAD

**Issue by rkorebrits** [ethereum/mist#2312]
Hi guys, 
Another post about blocks not downloading. I'm on Windows 10 and I've installed the latest Windows executable (`Ethereum-Wallet-installer-0-8-10.exe`) both at home and at work, and in both cases the blocks aren't downloading, even though I'm connected to quite a few peers.

I have read several posts (incl "Mist Troubleshooting Guide") that haven't helped me so far. Block download for a few seconds to a few minutes, but then they just stop. Some things I've done:
- Virtualbox is not active (PC rebooted)
- There is no firewall blocking (download does start before stopping)
- removed chaindata folder
- Several other things

I've bought 3.0ETH yesterday, but now I can't access it (luckily made a backup of the wallet straight away). It's quite disappointing to be honest and have never had such issues with BTC, LTC or RPX. Where is the error feedback for the user? If this is such a common issue, surely this must be improved, either error handling or reporting.

(screenshots are from 2 different attempts)
![image](https://cloud.githubusercontent.com/assets/3765592/26320895/f2d2f278-3f24-11e7-84c8-efa3bac9814b.png)
![image](https://cloud.githubusercontent.com/assets/3765592/26321340/bbcdeda8-3f26-11e7-9e13-fe97d9cd24ff.png)

Attached zip archive of node.log
[node.log.zip](https://github.com/ethereum/mist/files/1019698/node.log.zip)

**Comment by garretlaxton** [comment]
If you need to access your ETH instantly you can use myetherwallet.com

**Comment by rkorebrits** [comment]
Thanks Garret, I've read mixed reviews about myetherwallet. Not sure if I want to try that. I mainly want to confirm that the ETH I've purchased are actually in my wallet, and otherwise just want the program to be operational \0/ If the software is so unreliable, this will clearly be in the way of adaptation.
I'm new to ETH, but Mist seems to almost be done downloading blockchain. Not sure what Mist even is, but looks promising nonetheless.

**Comment by rkorebrits** [comment]
Mist has now downloaded the whole chain and the ethereum wallet is also operational now... No idea what changed.
