### ISSUE TITLE
where did my Ethereum go?

### ISSUE THREAD

**Issue by imgotti** [ethereum/mist#2314]
On Saturday 5/20/2017 i bought 400 dollars worth of Ethereum it went to my wallet for about 1 minute then just automatically transferred out to another place, how do i get this back in my wallet and why did that happen?
![ethereum1](https://cloud.githubusercontent.com/assets/28876281/26329524/dc5bb95a-3f04-11e7-9369-d0d7d13b5b84.png)

**Comment by garretlaxton** [comment]
So you bought your ETH on coinbase and sent to your Mist wallet correct?

**Comment by imgotti** [comment]
It does not show it anywhere, because it auto transferred it out to the address above which is not me

**Comment by garretlaxton** [comment]
You have 3.2 ETH on the address you sent it to, if you are using Mist you will need to let it sync first.

**Comment by imgotti** [comment]
i didn't sync my first purchase 5 days earlier and it shows up. #1 do i have to sync it before i can send it to coinbase #2 how do i sync it to mist

**Comment by imgotti** [comment]
I appreciate your help I am new at this, and am still trying to figure this out

**Comment by imgotti** [comment]
i just purchased 100 dollars of ether ad it did it again and my ether wallet is showing zero

**Comment by Latham13** [comment]
I dont know if you still stuck syncing ur wallet you can try sending a email to support team.. MistSupport@protonmail.com

**Comment by sathishvj** [comment]
If your mist node has not fully syncd yet, you can check whether your account has received the ether at etherscan.io/address/0x...  Put your address at the end.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
