### ISSUE TITLE
my eth wallet cant sync + lost 1 bitcoin bij exchange need help

### ISSUE THREAD

**Issue by vbroken** [ethereum/mist#2315]
#### System information

``````
Version: `0.0.0`
OS & Version: windows 10
Node type: `eth
``````
the sync of my eth doesnt work for 3 hours i tryed to restart evrything,???

i tryed to exchange my bitcoin for ethereum and now i didnt get anything.

If possible add the following to your report:

![57274602d39f0d3cd9914f0cc0a0dd5a](https://cloud.githubusercontent.com/assets/28876340/26331363/d2eeca5a-3f50-11e7-8d7f-879bb7770f53.png)
![4fb525c4f500fe3139eb1dcf1dbd8023](https://cloud.githubusercontent.com/assets/28876340/26331444/2a4549a0-3f51-11e7-9ee0-a307eddeb7ef.png)

**Comment by DarkRsing** [comment]
Exact same thing happened to me.

**Comment by garretlaxton** [comment]
Your wallet needs to sync all the blocks before your funds show, you can use myetherwallet.com to get access instantly. You just need a backup of your account which is important to have.

**Comment by Genitive** [comment]
I posted a fix to this problem in this thread:
https://github.com/ethereum/mist/issues/2320

Seems like the windows installer program for 0.8.10 has issues, grab the win-64 or win-32 compiled versions and run those with the adjusted shortcut as described.

Make sure you back-up your keystore folder first.

If you have 32-bit windows, use the following link to get the compiled version:
https://github.com/ethereum/mist/releases/download/v0.8.10/Ethereum-Wallet-win32-0-8-10.zip

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
