### ISSUE TITLE
Syncing Issue Mist 0.8.10

### ISSUE THREAD

**Issue by Wyrmbeard** [ethereum/mist#2320]
#### System information
``````
Version: `0.8.10`
OS & Version: Windows 10 64Bit
Node type: geth(default)
SSD
``````

I know this is asked a lot, I'm having trouble syncing the mist ethereum node

![untitled](https://cloud.githubusercontent.com/assets/28241923/26343034/c9292f50-3fdd-11e7-9806-01ddff95ca7d.jpg)

It Syncs to around here ^ before it stops; unless I restart the program it won't sync any further (I've waited 24 hours before restarting).

I've checked the other posts and nothing seems to be helping.

I did send some ether to this wallet so I would really like to know if I can send that ether elsewhere while I figure this out or if I need to get this working before I can do that.

Any help is greatly appreciated, thank you.

**Comment by Genitive** [comment]
I had the same problem, as have others... 

I did some troubleshooting and eventually managed to fix it on my own.

Seems like the Mist windows installer program doesn't run properly, it must be badly compiled.

Don't panic, we can rescue the blockchain image and the wallet file, by doing the following steps.

In Win 64 bit, download this file:
https://github.com/ethereum/mist/releases/download/v0.8.10/Ethereum-Wallet-win64-0-8-10.zip

After unzipping it, create a shortcut of 'Etherum Wallet.exe' in the 'win-unpacked' folder and then right-click and view properties on the shortcut.

At the end of the Target input section, put a space after the last character and the following: 

-datadir=C:\Users\Autoltra\AppData\Roaming\Ethereum 

Or change the folder in the above phrase to match the chosen data folder when you installed Ethereum Wallet if different.

Make sure the installer version of Ethereum wallet,exe is not running, and then double click the shortcut.

It should load up, connect to nodes, show the blockchain image updating and then load the wallet properly.

Hope this resolves the problems!

**Comment by Wyrmbeard** [comment]
Hey,

Thanks for your help, I seemed to have solved the issue however by just running the geth (1.6.1) on its own and left it to sync. Took hours but it never halted.

**Comment by dleth72** [comment]
I got the same problem with the OS version. Any help on this topic?

**Comment by RiotAkt** [comment]
Hey Genitive,

I took the steps you mentioned. It did help but the sync still freezes. I get longer until it freezes but it's still getting stuck. Any other suggestions?

**Comment by Genitive** [comment]
I got it wrong for the fix, you need to run geth.exe from the resources folder until it is all sync then start ethereum wallet. It will take a day or so. The -dir flag for ethereum wont work, if you are using alternative data folder use flag on geth.exe as follows:--dir "R:/data/ethereum/"On 24 May 2017 7:08 pm, RiotAkt <notifications@github.com> wrote:Hey Genitive,
I took the steps you mentioned. It did help but the sync still freezes. I get longer until it freezes but it's still getting stuck. Any other suggestions?

**Comment by RiotAkt** [comment]
I don't have geth.exe in the resources folder.

**Comment by RiotAkt** [comment]
So I've downloaded geth.exe, do I move it to resources folder, then just run the Eth wallet?

**Comment by james2432** [comment]
Same problem on Arch linux.

**Comment by Genitive** [comment]
The OP is for Windows 10 problems, haven't seen the linux folders, but suggest checking for the latest version of geth from github, it got updated after the 0.8.1 was released.On 24 May 2017 8:20 pm, Jamie <notifications@github.com> wrote:Same problem on Arch linux.

**Comment by RiotAkt** [comment]
Geth is forcing sync. Thanks

**Comment by RiotAkt** [comment]
Sorry to post again. Geth was running fine up until around 1,300,000 blocks, now it's running very very slow. As in one block a second slow. I notice on Task Manager it puts my disk space usage to 100%. 

Is there an easier way to sync the wallet and access my ETH?

**Comment by garretlaxton** [comment]
@RiotAkt syncing can take 1-20+ hours, you can import your backup to myetherwallet.com if you'd like to access your ETH instantly.

**Comment by GitSpree23** [comment]
@garretlaxton myetherwallet.com hangs everytime I try to unlock it.
I am having the same sync problem. No peers found.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
