### ISSUE TITLE
Add receiver wallet name to receiver address when swapping balances internally.

### ISSUE THREAD

**Issue by ghost** [ethereum/mist#2324]
The Ethereum Wallet has named addresses in the main screen.
However, when transferring balances into a named wallet address (Wallet #1,2,3,4 etc)  it only shows the known address wallet name from the sending address and not the receiving address.

To help aid users, if the receiver address name (an internal wallet address that is named) can also be shown alongside the receiver address number, then the user will be less confused.

Image shows how sender named wallet is shown but only receiver address is shown even though receiver address is also a named local wallet..
 
![image](https://cloud.githubusercontent.com/assets/2097179/26367651/344f1f0e-3fa4-11e7-91d9-667984a914cd.png)

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
