### ISSUE TITLE
Can't send

### ISSUE THREAD

**Issue by azulmarino** [ethereum/mist#233]
Wallet 0.5.0
OS : El Capitan

Can't send funds from wallet , when I select send nothing happens. Closed some apps ... is this version using more memory ? Now when I try to send seems there is a msg in a white box below the send button ... whatever it is it isn't readable as it is behind the main frame. Click back on wallets and hangs.

**Comment by ymarcus93** [comment]
I am also experiencing this problem on Yosemite with 0.5.0

**Comment by bamos01** [comment]
me too on Yosemite

**Comment by bamos01** [comment]
Actually- mine started working - you need to let it sit after starting up until it finds enough peers >8.  then it works as expected.  if you click send too quickly on the first start up - the program hangs

**Comment by azulmarino** [comment]
Started working this morning , however send when one wallet is open takes me to the primary wallet. The wallet I'm trying to send from has 0.10 ETH but that wasn't a problem before. Is there a minimum ?, anywhere it shouldn't just go to another wallets send screen,

**Comment by frozeman** [comment]
The hanging has to do with a lot of requests to the node which are happening in the background. Is it possible that you not yet synced up and presses the "Skip peers" on the splash screen?

**Comment by frozeman** [comment]
The send button is always different when you are on an account page, it will use this account as the primary selected one, which you were on before.

**Comment by azulmarino** [comment]
Didn't press "skip peers". At this moment only connected to 2 peers , but block count is fine (running Geth). Previously I connected to 12 peers.
Definite lag, did you check memory usage for this and last version ? 
Last version seemed a lot more responsive.

**Comment by frozeman** [comment]
My memory is ~120MB, which is totally acceptable.

I dont experience any lag.
Maybe you write down your wallet contract account addresses.

Then remove the Mist folder in `~/Library/App...Supp../Mist`, after restart the wallet and re-import your wallets in "add wallet" -> import

**Comment by azulmarino** [comment]
Write down ?
Is it not better to backup somewhere else , the re-import will pick up the backed up files or do I need to manually enter the addresses I "wrote" down. BTW I would only be writing the public address ... the one we see in the wallet ?

**Comment by frozeman** [comment]
write == copy somewhere.

and yes you only need to have the public address of the wallet contracts

**Comment by azulmarino** [comment]
In process ... thanks for your guidance.

**Comment by azulmarino** [comment]
I can see changes here. Previously we could select a wallet and then send and that wallet is selected. Now we select send and the primary wallet is selected ... we can click on this wallet and select other wallets. This is new and no indication on the screen of this functionality.
Other change we can use click/scroll to set amount to send ... dangerous , I moved my mouse down the screen to the send button and the amount increased (as scroll still on this field).

My wallet names have been lost since I deleted mist and restarted.

**Comment by azulmarino** [comment]
Also anyway to get pwd for secondary accounts ?

**Comment by frozeman** [comment]
I see the bug, with the selection, will fix.

**Comment by azulmarino** [comment]
Would be useful to have some indication if we click on account we will see multiply accounts ? Or have a scroll button ? What do you think ? May be it will be obvious for newer users.

**Comment by azulmarino** [comment]
Off topic ... when will you have a method to import paper wallets ? Use of QR code ?

**Comment by frozeman** [comment]
The wallet is still in the making and many things will come like account management and paper wallets etc. But you need to give it time as we need to allocate more resources towards Mist.

**Comment by frozeman** [comment]
The select account issue and the scrolling amount input will be fixed in the next release.

**Comment by azulmarino** [comment]
Thanks , keep up the good work , appreciated.

Dean
