### ISSUE TITLE
Lost Password to Ethereum Wallet 

### ISSUE THREAD

**Issue by dingley207** [ethereum/mist#2331]
I have forgot my password for my Ethereum Wallet, I have read about pyethrecover is there a guide to how to make it work anywhere?

Thanks in advance

**Comment by alexvandesande** [comment]
Hi, we are going through old unanswered issues, sorry it took so long to reach yours.

If you forgot your password but has a good idea on what it could be, then I recomend using a brute force method or a wallet recovery service, but I cannot recommend any one in particular.

If you're sure you have the correct password but it still won't unlock, take a look at this thread and fill up that form: https://github.com/ethereum/mist/issues/3513

I'll close this issue, feel free to reopen if you still have questions.

**Comment by anormore** [comment]
Hey @alexvandesande  maybe you could come over to #3513 and join the community -- as we have a repeatable bug and NO RESPONSE from the developers. There's a fire starting there, and you guys are ignoring it....
