### ISSUE TITLE
Asking for password - never set up password

### ISSUE THREAD

**Issue by trubble** [ethereum/mist#2334]
#### System information
``````
Version: `0.8.10`
OS & Version: osx 10.11.6
Node type: `eth/geth(default)`
``````

When attempting to send eth it asks for a password which I don't remember setting up. when I try sending with password or without password it says "wrong password." When I cancel, a red bar pops up in the corner and either says "transaction not confirmed" or "Method eth_sendTransaction not allowed"

further, when I try to troubleshoot, I go looking for the application support and can't find it in ~/Library/Application_Support/Mist/binaries/geth, and terminal tells me no such directory exists, in fact there is no Mist folder at all in application support, and in fact no ethereum or mist folder in my library at all. Am I completely lost in the woods here?

**Comment by garretlaxton** [comment]
Before you create your account it asks you to set a password.

**Comment by smitzlabs** [comment]
I'm having the same problem, and I don't remember ever setting up a password. I've been buying and sticking ether into the wallet, and I was going to start day trading it considering how large my wallet has become and how predictable some of the movements are.. but when I went  I tried to sell it asked for a password which I had never seen before. Now I have more money than I care to admit locked in a wallet that I have open, but I can't take any money out?

**Comment by trubble** [comment]
I remember setting up a master password but that was before I even created any accounts. Luckily I found the keystore folder and the password file, on to trying to learn python to use one of the recovery scripts I guess...

**Comment by smitzlabs** [comment]
You say there's a password file? I have my full installation and open wallet.. I just can't remember the password and I'm just trying not to light enough money to buy a new car on fire.

**Comment by trubble** [comment]
yeah in the wallet if you click Accounts -> Backup -> Accounts it takes you to the folder containing a file that should start with "UTC". from there there is a python script that allows you to brute force the password based on a number of guesses you provide. Unfortunately I don't know enough about programming to do it myself. Nothing like, as you say, enough money to buy a new car as motivation to learn python.

**Comment by orkobar** [comment]
Same problem for me. Never set up a password.

My etherwallet cannot sycronized, loooking for peers, just waiting...

ı tried to get my ethers from myether.com. İt said it is password protected but never set up a password

Please help us

**Comment by orkobar** [comment]
ı was wrong, remember my password and solve my pronlem and reach my account from myetherwallet.com.

good luck for eveyone

**Comment by divine07** [comment]
I have the same issue! When I first created a wallet on Mist, it didn't ask for a password and I sent some ETH. But then when I tried to send the Ether out, it asked for the password, I deleted the Mist and re-downloaded it, but again, it didn't ask for a password and I still don't have access to the account. Please help!!

**Comment by orkobar** [comment]
dear divine,

sorry for your situation, there must be pass somewhere, i remember my
password after 2 hours try, and fixed the problem.

Try your mostly used password.

Good luck

2017-06-07 7:20 GMT+03:00 divine07 <notifications@github.com>:

**Comment by trubble** [comment]
Yeah my password ended up flashing through my brain while I was driving. Had I been able to get this recovery tool to work though, it would have found my password: https://github.com/ryepdx/pyethrecover

**Comment by orkobar** [comment]
sorry couldnt understand,

option 1: you used this and you recovered your password

Option 2: You will try this for recovery.

if it is one, could you please tell me how you did it.

İf it is two, did you read all comments, suggest if you recovered,
immediately transfer your eth/etc to another adress

good luck

2017-06-09 17:16 GMT+03:00 trubble <notifications@github.com>:

**Comment by trubble** [comment]
I tried to use it and couldn't get it to work. Once I got everything up and running and running through the code correctly it kept getting hung up on not understanding an input, which is unfortunate because the input was the first word in my password guesses. I'm not a programmer in the slightest and only learned basic basic python to be able to get it to run at all. 

I just ended up remembering my password on my own. it took a week or so since the brain can process many fewer password guesses per second than a computer.

**Comment by orkobar** [comment]
yeah you are right but, computer tries random passwords, but might be easy
to try your passwords own

2017-06-12 17:15 GMT+03:00 trubble <notifications@github.com>:

**Comment by divine07** [comment]
Yah, I wasn't able to remember any passwords. I'm hoping the Mist team can figure something out.

**Comment by CoincoinNico** [comment]
Guys,

Can you help me telling more regarding your stories? I'm almost certain I hit "Skip" when Mist requested the password. Then I was able to send some Eth for an ICO and now it is requesting a password, and none of the one I used is working.

What are the options: a) if I did hit skip, is that possible that Mist doesn't ask for the password at beginning or were you wrong thinking this? b) If I lost password, everything is lost right?

Best

**Comment by Madebyivan** [comment]
It happens to me the same, I'm in mac osx

**Comment by orkobar** [comment]
Dear Friends

It seems it all happened to us. I solved mine that i found my pass. During
set up everything is familiar and maybe we are not fully concantrate what
we are doing and setting a regular (one of our most used) password.

Later we face to a problem and confused why? We didnt set a password even!!

but %99 we did.

That is how ı solved, used many of my common passwords and password
algorithms.

Hope you will solve.

regards

2017-12-02 18:37 GMT+03:00 Madebyivan <notifications@github.com>:

**Comment by CoincoinNico** [comment]
Same for me, in fact I had set up one, I was about to give up but one combination of password helped. I was 100% sure I hadn't set up one. But I had.

**Comment by evertonfraga** [comment]
Hi all, I'm one of the developers of the project. I've just tried to reproduce this issue without success in the following setups. When skipping it didn't create any account.

- MacOS - mist 0.9.3
- Linux - mist 0.9.3

While trying to reproduce this issue and help you guys, I please ask you to answer this set of questions, so we can outline the issue and move on. Please fill out the form thoroughly.
https://goo.gl/forms/jznmHV6Fpui7Ijds1

Let's move the conversation to this single place:  https://github.com/ethereum/mist/issues/3097

Thank you.
