### ISSUE TITLE
Cannot connect on startup

### ISSUE THREAD

**Issue by TimmaahhhH** [ethereum/mist#2335]
``````
Version: current
OS & Version: windows
Node type: `eth/geth(default)`
``````
Okay so last night, I finally got everything up and running. Made a new account, set the password in the command line, mist was working after taking forever to download the entire block chain. This morning when I woke up my computer was on the login screen for whatever reason. Now I've mined through NiceHash, and I know my overclocks and mods are stable. So now, I cannot even download the block chain. Mist is stuck at 0%, peers are found. I cannot download it via the command line, because it rejects the peers. I have no idea how to unlock my account. I remember my password. But nothing prompts me to enter it. Completely counter-intuitive. I have no idea what to do or where to start. My computer was mining perfectly fine last night. And now this issue. It's always SOME kind of issue. 

I'm using claymore, I have rx 480s, latest Mist wallet installed, firewalls have exceptions for mist and geth and everything. 

What do I do. 

-Cannot open Geth when Mist is up. The command line pops up for a second then goes away.

- Log files 
  web3 issue

**Comment by TimmaahhhH** [comment]
shouldn't allow RegExp (possible XSS) ‣
AssertionError: expected [Function] to throw error including 'Payload, or some of its content properties are invalid. Please check if they are valid HEX with \'0x\' prefix.' but got 'Payload, or some of its content properties are invalid. Please check if they are valid HEX with 0x prefix.'
    at Context.<anonymous> (file:///C:/Geth/Wallet/win-unpacked/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:122:117)
    at Test.Runnable.run (file:///C:/Geth/Wallet/win-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4281:32)
    at Runner.runTest (file:///C:/Geth/Wallet/win-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Geth/Wallet/win-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Geth/Wallet/win-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Geth/Wallet/win-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Geth/Wallet/win-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Geth/Wallet/win-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Geth/Wallet/win-unpacked/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)

**Comment by TimmaahhhH** [comment]
file:///C:/Geth/Wallet/win-unpacked/resources/app.asar/interface/fonts/SourceSansPro.otf Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///sockjs/info?cb=ef_ertyt6l Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by TimmaahhhH** [comment]
So Im able to mine right now, That is working fine, I just cannot access Mist at this time.

**Comment by TimmaahhhH** [comment]
<img width="960" alt="untitled" src="https://cloud.githubusercontent.com/assets/28928907/26414866/503a2d14-4065-11e7-8993-2d363868e15f.png">
<img width="960" alt="untitled2" src="https://cloud.githubusercontent.com/assets/28928907/26414867/529ba556-4065-11e7-8e18-4cbb598c29c1.png">
<img width="960" alt="untitled3" src="https://cloud.githubusercontent.com/assets/28928907/26414868/53fe561e-4065-11e7-9ee1-d69f3467fbb0.png">

**Comment by TimmaahhhH** [comment]
When I initially open mist, It is stuck on finding the node, and i have to close out of it and reopen to make it go past that. once it does it stays at trying to find peers, and Ive had as many as 24 peers and it doesn't download.

**Comment by TimmaahhhH** [comment]
And also another question:

Do i need to have my wallet on my mining computer? Or is it fine to just have Claymore on my miner, and have my wallet and address elsewhere? Because if that is the case, I can just uninstall mist and hook my wallet address up to my startup file and bypass this whole issue entirely.

**Comment by alepri93** [comment]
I have the same error. did you got to fix it?

**Comment by WendyCoin** [comment]
I HAVE this issue also.  Please help.

**Comment by TimmaahhhH** [comment]
I had eth wallet working on another computer so I'm using that. Not sure why I am having trouble downloading this on a different computer. 

I don't get why it needs to slow the speed if you exit out. It should prioritize the download regardless.

**Comment by migtc** [comment]
Any resolution here?

**Comment by JPatMoss** [comment]
Still having this problem while running tests. THe sync seems pretty slow too. 

`var add = '0x0000000000000000000000000000000000000000';
expect(function () { web3.eth.sendTransaction({ from: add, to: add, data: new RegExp('') }); }).to.throw('Payload, or some of its content`

Then it cuts off.

**Comment by alexvandesande** [comment]
Lots of things going on this thread. First, don't try to use Mist for mining, you should download a command line client for that. 

@JPatMoss not sure where this error comes from, can you provide more information on a separate thread?

The sync issues are typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
