### ISSUE TITLE
can't connect to node

### ISSUE THREAD

**Issue by ethlover** [ethereum/mist#2336]
#### System information
``````
Version: `0.8.10`
OS & Version: osx
Node type: `eth/geth(default)`
``````

I get an error that says Ethereum node connection error :'(

Towards the end of the error code, it says WARN blockchain not empty, fast sync disabled. Then the next line is fatal: error starting protocol stack: too many files open

I was using ethereum wallet, got that issue, tried updating and the issue persisted. I then went and downloaded mist, it opened once no problem. Quit the app, tried to re-open mist, and now i get this error here also.

**Comment by MyBitDev** [comment]
Having the same issue as well.

**Comment by evertonfraga** [comment]
That's a problem heavily augmented by MacOS. I had this myself in the past and quickly managed to fix it: https://github.com/ethereum/mist/issues/1746#issuecomment-327030174

Cheers.
