### ISSUE TITLE
How do I sync ETH sent from COinbase to Ethereum wallet on myst? balance is still zero

### ISSUE THREAD

**Issue by cryptonewbie** [ethereum/mist#2338]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by readspear** [comment]
I have the same problem. I am synced to latest block, have multiple confirmations as indicated on Coinbase, but my ETH is not appearing in my wallet. No problems occurred on the previous transfer. Of course, I am a complete NOOB to this, so I'm expecting to have some problems. Read a previous thread whereby the same problem was resolved by dumping the chain data. No clue how to do that (MacOS), and cannot find a clue on this forum. I'll give it another 24 hours. Only half an ETH, but still...

**Comment by cryptonewbie** [comment]
Thanks! Still no resolution, but I'm hoping for some help through Coinbase support. Waiting for reply. I have a record of transaction. Just no idea where it went.

**Comment by BicycleGuy** [comment]
You can see if the transaction occurred on Coinbase's Acocunts page--just click the transaction for all the detail. I resolved my problem, which was a decimal error that I made--the software worked as it should.

**Comment by cryptonewbie** [comment]
How do I know if I'm synced?

**Comment by cryptonewbie** [comment]
I can see that the transaction occurred on my Coinbase account page.  Still zero in my ethereum wallet though

**Comment by BicycleGuy** [comment]
There are a number of sites that track the blockchain. Try ethstats.net

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
