### ISSUE TITLE
Why am I not getting any peers to update my blocks?

### ISSUE THREAD

**Issue by mike37769** [ethereum/mist#2339]
Hi, iv been trying to sync my wallet for 2 days now and stuck with millions of blocks remaining.

**Is there a certain time when more peers are online?
Is there any way to speed it up?**

Bought 0.5 Ethereum and still nothing in my wallet, im concerned iv sent it to the wrong place.

**Is there any way i can check the transaction is still pending?**

**Comment by Comacs44** [comment]
I can't answer your first questions as I am in a similar situation like many people (I also have an open issue)
However you can check that it has reached your wallet there: [https://etherscan.io/address/insert your address here](url)

**Comment by mike37769** [comment]
@Comacs44 Do you know an easy way I can transfer my Ethereum out of this wallet into another wallet provider, without syncing this service first?

**Comment by Comacs44** [comment]
You can send ether without having to download the whole blockchain by using myetherwallet.com
I've never done it so I can't help any further but that's what I gathered by reading some other posts.
GL

**Comment by mike37769** [comment]
@Comacs44 just tried it, uploaded the keystore file and website just crashes

**Comment by evertonfraga** [comment]
Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.
