### ISSUE TITLE
Unable to receive Ether

### ISSUE THREAD

**Issue by onesunbeingnow** [ethereum/mist#234]
Hi, 

I recently downloaded the Ethereum Wallet and a few days ago I sent 1 test ETH to the ETHERBASE address in the Ethereum Wallet from my Poloniex account and it shows it has been sent from there. Also it shows it has been sent on: https://www.etherchain.org/account/0x42a3f2ca2566633dbfa1395de0f9305b4bb2058a#txreceived

My question is: why does it not show up in my wallet?

Would appreciate some ideas on this issue.

Many thanks, Onesun.

**Comment by chek2fire** [comment]
it is a know bug in the wallet. Sent another eth and i think will appear and the previous eth

**Comment by onesunbeingnow** [comment]
Nope, tried again and it didn't work. Can someone please tell me where my ETH has gone please, this is unacceptable.

**Comment by frozeman** [comment]
They are on the account, no need to worry.
Have you synced up the chain, are you on block 1097397?
Do you have peers?

**Comment by onesunbeingnow** [comment]
Hmm I still cannot see them in the balance. I have peers, but how do I check what block i'm on?

**Comment by frozeman** [comment]
Its written in the top bar, between "Send" and "Contracts"

**Comment by onesunbeingnow** [comment]
It says I am on the TESTNET on block 499,429. If I change to Main Network then I need to create a new account.

**Comment by frozeman** [comment]
"This is unacceptable", that you didn't knew you where not even on the main net ;)

To copy your account to the main net, copy the file with you account name inside `%APPDATA%/Romaing/Ethereum/testnet/keystore` to `%APPDATA%/Romaing/Ethereum/keystore`

If your on a mac its: `~/Library/App..Supp../Romaing/Ethereum/testnet/keystore` to `~/Library/App..Supp../Romaing/Ethereum/keystore`

**Comment by onesunbeingnow** [comment]
It did not know it was on the TestNet until just now, i simply used the address provided when I opened the wallet for the first time.

I have no idea how to do what you just mentioned.

**Comment by frozeman** [comment]
Just copy the file with you account address in the file name from this one folder to the other, as described...

Are you on windows?

**Comment by onesunbeingnow** [comment]
Hmm. Yes, I am on Windows 10. 

Where do I find the this file with my account address in it and how to transfer it to the one you mention?

**Comment by frozeman** [comment]
Type this in your explorer bar: `%APPDATA%/Roaming/Ethereum/testnet/keystore`

**Comment by onesunbeingnow** [comment]
Explorer bar?

**Comment by onesunbeingnow** [comment]
Look, I know nothing about computers. If you didn't guess already hahaha

**Comment by frozeman** [comment]
Then you might be totally wrong here... Cutting edge cryptocurrencies... i guess you need to know how to use your PC

Maybe google these things for a bit, i can't give support one this level, or we don't get anywhere with the wallet/mist and web3.js ;)

**Comment by onesunbeingnow** [comment]
By explorer bar do you mean a internet browser bar?

**Comment by onesunbeingnow** [comment]
So you are saying you cannot help me then. Thanks.

**Comment by frozeman** [comment]
I did help you. You have all the information, but i don't have the time to take you by the hand and explain how to use a PC, I'm sorry. Google will help.

**Comment by onesunbeingnow** [comment]
Hmm, sure.

I tried copying %APPDATA%/Roaming/Ethereum/testnet/keystore into the search bar next to the start menu but no files on my PC came up, just web searches.

**Comment by frozeman** [comment]
Its the windows explorer not internet explorer.

Your file browser....

**Comment by onesunbeingnow** [comment]
You know frozeman, its the mark of someone really intelligent to be able to explain anything to anyone in simple terms they can understand, not just waste words fobbing them off.

**Comment by onesunbeingnow** [comment]
I need to install a file browser apparently...

**Comment by frozeman** [comment]
Ok i will try be more helpful.

I meant this here blue number 4. 
http://windows.microsoft.com/en-us/windows-8/files-folders-windows-explorer

**Comment by onesunbeingnow** [comment]
Okay, thank you. I will delete the word 'unacceptable', perhaps that was a little rash. I was a little underwhelmed when my ETH didn't show up, you know :)

It says 'Windows can't find - %APPDATA%/Roaming/Ethereum/testnet/keystore' when I search in the file browser bar...hmm

I also checked manually, and no files with this name.

**Comment by onesunbeingnow** [comment]
okay, I found these two file when looking manually again:
UTC--2016-03-01T23-12-49.187612100Z--42a3f2ca2566633dbfa1395de0f9305b4bb2058a &
UTC--2016-03-02T02-39-04.767965200Z--6de763cc4214b0c0bc0c6855535c7025b2d965d8

what to do now?

**Comment by onesunbeingnow** [comment]
However, when I look for the file location: AppData/Romaing/Ethereum/keystore to copy my accounts into, it is not there. I back out as far as the AppData/Romaing/Ethereum, but there is no folder for keystores apart from the one in the /Testnet folder...

This is bizarre indeed, did I perhaps miss something when installing. I know the wallet is synced as I can see the peer counter and blockchain change in real time...

I appreciate you helping and your patience.

**Comment by frozeman** [comment]
If you have no `keystore` folder in the `Ethereum` folder, then please copy the `keystore` folder from `Ethereum/testnet` to `Ethereum`

Thats it

**Comment by onesunbeingnow** [comment]
You know what, I was going to do that...but I closed the window, now I cannot find the folder location again...

**Comment by onesunbeingnow** [comment]
This is really frustrating...I seriously cannot find the folder I was previously looking at...this is ridiculous...it is nowhere now, and I cannot remember how I found it the first time...

**Comment by onesunbeingnow** [comment]
okay, I have done that, it should would now then right?

**Comment by onesunbeingnow** [comment]
Are there more steps to take? I have changed from Testnet to Mainnet on the Wallet but still zero balance is shown
