### ISSUE TITLE
Sent bitcoin to wallet and never got it please help

### ISSUE THREAD

**Issue by JETBYE** [ethereum/mist#2341]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by JETBYE** [comment]
14A1tCMB4dfA7U8WomdqCEbCyYFNjHxQwW is where i sent it but never got it

**Comment by garretlaxton** [comment]
Your wallet probably needs to fully sync.

**Comment by BicycleGuy** [comment]
JETBYE, any luck resolving your probem? I am having the same problem--my wallet is FULLY synced. Sent coin from coinbase to Ethereum Wallet 0.8.9 (Mac OS X) May 24, still not showing. Previous transfer happened quickly.

**Comment by JETBYE** [comment]
na no luck mate yea same with me 😞 ill let you know if i do get it


________________________________

**Comment by JETBYE** [comment]
it is and nothing


________________________________

**Comment by BicycleGuy** [comment]
Thanks for letting me know. I'm still looking for a solution--will let you know if I find one.

**Comment by JETBYE** [comment]
sweet thanks


________________________________

**Comment by BicycleGuy** [comment]
Definitely a wallet problem. You can check Etherscan and see if your transaction has been confirmed. Mine has--10,865 times.

**Comment by BicycleGuy** [comment]
Well, here goes... computational error on MY BEHALF. All the coin is there. I am merely an idiot.

**Comment by JETBYE** [comment]
i still can't see mine where did you go to see if its cleared?


________________________________

**Comment by BicycleGuy** [comment]
Coinbase has all the transaction detail on the account page. Not sure which exchange you used.

**Comment by garretlaxton** [comment]
@JETBYE @BicycleGuy You can upload your backup to https://www.myetherwallet.com and access your ETH  if you're having trouble with Mist.

**Comment by JETBYE** [comment]
i sent from coinjar its an Australian wallet  it sent but i never got it


________________________________

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
