### ISSUE TITLE
Takes too long to download blockchain

### ISSUE THREAD

**Issue by MCTyler** [ethereum/mist#2344]
#### System information
``````
Version: `any`
OS & Version: linux
Node type: `eth/geth(default)`
``````
Can you guys look into the way the Electrum Wallet works. It's impracticable for a home user to download the entire blockcahin in order for this wallet to work.

**Comment by ejccna72** [comment]
Like you can even think about downloading this bloated POS at home. IT DOES NOT WORK!!!! PERIOD!!! TANK ETH AND MOVE ON!!

**Comment by elsesiy** [comment]
@MCTyler I suggest you use any of the available syncmodes rather than downloading the full chain with all block information. See the new cli flags --syncmode=light or --syncmode=fast for reference.
