### ISSUE TITLE
OS X EyeConnect.app appears to simultaneously mirror client Ethereum Wallet synchronization with unknown IP addresses (multiple hosts)

### ISSUE THREAD

**Issue by versatec95** [ethereum/mist#2345]
#### System information
``````
Version: 0.8.10
OS & Version: osx 10.11.6
Node type: geth
``````
Mac HD/Library/Application Support/EyeConnect/EyeConnect.app runs automatically and concurrently with Ethereum Wallet and sends outbound traffic (only) to multiple unknown IP hosts.  Mac HD/Library/Application Support/EyeTV Helper.app also runs intermittently. This activity was observed with Little Snitch Network Monitor and terminated with Application Monitor. The Elgato EyeTV device these applications are supposed to support was retired several years ago, and such network activity by EyeConnect.app was not observed until initial Ethereum Wallet synchronization commenced today.

[EyeConnect.app.zip](https://github.com/ethereum/mist/files/1028760/EyeConnect.app.zip)
[EyeTV Helper.app.zip](https://github.com/ethereum/mist/files/1028761/EyeTV.Helper.app.zip)

**Comment by evertonfraga** [comment]
Maybe that's something related to EyeTV discovery protocol. And certainly, it's not needed for blockchain syncing. You may uninstall if not being used.
