### ISSUE TITLE
Node Crashed - Mist Wallet 0.5.0 (Beta 8) - Windows 7 

### ISSUE THREAD

**Issue by imar2016** [ethereum/mist#235]
I cannot start Any Mist Wallet on my PC. This PC is pretty freshly built, Windows 7 64 bit and is only used when i have cryptocurrency related things to do. I cannot get ANY of the mist Wallets to ever start past the "starting ethereum node" , including previous builds. I was waiting for the new release to see if it would work but no. I have another PC which works on it just fine, however im reluctant to run anything on that daily use PC.
![crash](https://cloud.githubusercontent.com/assets/17636073/13519832/4cf564ba-e22f-11e5-819d-a37c7521a617.jpg)
![crash2](https://cloud.githubusercontent.com/assets/17636073/13519861/7e39f59a-e22f-11e5-8248-ebc8f77d6be0.jpg)

**Comment by frozeman** [comment]
It looks like it didn't open the IPC named pipe connection on windows. This can also be that i set the timeout for this window to appear to low (30s)

If you wait longer, does than a message with `IPC Server started...` appear? in the commanline tool

**Comment by imar2016** [comment]
Also on the working pic which is much less powerful that screen disappears after a few seconds. Both have same Windows build also, only difference is the hardware in each pic

**Comment by frozeman** [comment]
If the CMD.exe window disappears than thats a sign that this node crashed. Andy idea @karalabe

**Comment by imar2016** [comment]
The cmd window does not close

**Comment by frozeman** [comment]
Ok, which screen disappears then?

**Comment by karalabe** [comment]
Someone reported a while back that their Windows instance froze at that point and it turned out that the UPnP lookup froze up for some reason. Could you please make sure that Windows firewall isn't blocking something? It has the tendency of "blocking" network calls until the user selects something, nether succeeding nor failing until then. Could you maybe try running geth directly with `--nat=none`?

**Comment by imar2016** [comment]
Nothing dissapears at all. Both screens as attached will remain there until i close them. Longest i have left them is 3 hours each

Date: Fri, 4 Mar 2016 01:15:15 -0800

**Comment by frozeman** [comment]
Ok then your answer "Also on the working pic which is much less powerful that screen disappears after a few seconds", was very unclear.

So it never started the named pip connection then, which is weird. @bas-vk any idea?

Can you also try what @karalabe suggested?

**Comment by imar2016** [comment]
Apologies, What i meant was  on the working pc (which has windows firewall turned on) that splash screen saying starting ethereum node dissapears and moves on to opening the wallet in a matter of seconds. have tuned off all firewall
![crash3](https://cloud.githubusercontent.com/assets/17636073/13523119/a42ad5e0-e247-11e5-955c-20597297f998.jpg)

**Comment by karalabe** [comment]
Ok, so your command you just sent is a bit messed up. You inserted the nat disabling code as your IPC path. Please try `geth --nat=none` only.

**Comment by imar2016** [comment]
yes this has fixed it, its working now. ran the CMD line as you suggested and opened the Ethereum-Wallet.exe and the block is being downloaded. So am i assuming i need to do this each time i start ?

Date: Fri, 4 Mar 2016 01:31:01 -0800

**Comment by SteffenIvanhoe** [comment]
Without following the discussion I just want to say that I had exactly the same crash as reported above on the first start of the new wallet on my windows machine. A second try is (as happened very often with the previous version, too) hanging in with "Looking for peers" and nothing happens.

**Comment by karalabe** [comment]
@imar2016 We'll try to look into why certain Windows machines don't like our UPnP discovery code, but until we manage to fix this, if you do encounter this issue again than yes, please disable NAT as above.

@SteffenIvanhoe Please try the above fix (`--nat=none`).

**Comment by frozeman** [comment]
I guess thats whats happening.
Because he doesn't start connecting he is not starting the IPC server (as this would come after) and the wallet thinks the node is not started up.

**Comment by karalabe** [comment]
Just for the reference, I've opened up an upstream issue for geth: https://github.com/ethereum/go-ethereum/issues/2291. Please leave this one open too until we can sort them both out.

**Comment by imar2016** [comment]
Thankyou to all involved. Great Devs and community A+

Date: Fri, 4 Mar 2016 01:43:41 -0800

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
