### ISSUE TITLE
Node after 2 days nonstop syncing only 70%

### ISSUE THREAD

**Issue by ibart7** [ethereum/mist#2350]
#### System information
``````
Version: `0.8.10`
OS & Version: macOS 10.12.4 (Sierra) 2,6 Ghz Quadcore I7, 16GB DDR3
Node type: `eth/geth 1.6.1`
``````

After I installed Mist, the Node sync job started. At first it the process went very fast, but every hour the blocks per second drops. Currently is about ~1 block per second. Considering I need to sync 1M more blocks, it will take forever to sync it. What's causing this? 

<img width="393" alt="schermafbeelding 2017-05-25 om 22 46 34" src="https://cloud.githubusercontent.com/assets/28965625/26469926/0e2d1c3c-419c-11e7-9e27-18ba7c7223e5.png">

Beside that I'm seeing that my Chaindata folder keeps extending. Currently it's 92GB, but I'm only at 70% of the sync process. Is there something wrong? Or is it normal to have a wallet which is ~100GB?

<img width="392" alt="schermafbeelding 2017-05-25 om 22 54 52" src="https://cloud.githubusercontent.com/assets/28965625/26470296/76965346-419d-11e7-9853-2dac525bb70c.png">

**Comment by MCTyler** [comment]
Yea, I already posted this issue....

**Comment by ejccna72** [comment]
This BC is a COMPLETE POS!!! The wallet is even worse. It doesn't work with GETH nor does it work with Parity. WHAT THE FUCK IS GOING ON????? OVER A FUCKING WEEK INTO THIS POS!!!

**Comment by evertonfraga** [comment]
Hello. i don't know what POS is, but this amount of data implies that you
are syncing on the full mode.

Please delete your `~Library/Ethereum/geth/chaindata` and start geth like
this:

`geth --fast --cache=1024`

you can download geth on http://geth.ethereum.org. Then you can start Mist.
It should take on average 2h, maximum 4h.

**Comment by MCTyler** [comment]
I'm guessing POS is (Peice of Shit), Not a way to get issues resolved :(

**Comment by ibart7** [comment]
@evertonfraga that worked perfectly. Thanks you so much. I know finally see my Eth in my wallet.

PS. For the people with similar issues: [This youtube movie](https://www.youtube.com/watch?v=OTck7SLXTH) helped me to start geth in fast mode.
