### ISSUE TITLE
FAQs?

### ISSUE THREAD

**Issue by Comacs44** [ethereum/mist#2351]
#### System information
``````
Version: `0.8.10`
OS & Version: windows 10
Node type: `eth/geth(default)`
``````
It seems like a lot of people are having the same problems of not seeing their ETH in the wallet, not being able to sync, looking for peers, stuck at some blocks, how to delete chain data etc...

Same issues keep being opened and a lot of the time not sorted.

Is there any FAQs or instructions on how to do all these things?

Thanks

**Comment by evertonfraga** [comment]
Here it is: https://github.com/ethereum/mist/wiki

For additional syncing information, refer to https://github.com/ethereum/mist/issues/3097
