### ISSUE TITLE
Transferring Ethereum Balance to different wallet without syncing

### ISSUE THREAD

**Issue by mike37769** [ethereum/mist#2353]
Hello, Ethereum Wallet feels pretty dull and non-developed. Is there anyway I can transfer my Ethereum to another wallet service without having to sync the block chain first, so I don't have to tell ethereum wallet to send it to another Ethereum account number? Because lets be honest, its pretty shite at getting the block chain data and by the sounds of it ill just never get to access my Ethereum otherwise.

**Comment by RiotAkt** [comment]
Bumping this.

Did you figure out how to do this @mike37769? I want to move my funds to coinbase.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
