### ISSUE TITLE
Can I download the block chain as a file from a website and paste it into the GETH directory manually?

### ISSUE THREAD

**Issue by mike37769** [ethereum/mist#2354]
Can I download the block chain as a file from a website and paste it into the GETH directory manually? Because this sync part of the Ethereum wallet clearly isn't working

**Comment by richardforrestbarker** [comment]
Is it taking forever for you too?

**Comment by SLiX-KAOS** [comment]
Same here just stop syncing after a while and never goes up tried deleting the "chaindata" folder located in the
"C:\Users\"YOURUSERNAME"\AppData\Roaming\Ethereum\geth"

and then relauching the wallet and still same issue.

anyone found a repyutable source for the chain data to be downloaded sepreratly and then simply copying into the location?

**Comment by richardforrestbarker** [comment]
I think there may be a way to point the wallet to another geth server that has the full chain. I'm not sure though.

**Comment by evertonfraga** [comment]
> Can I download the block chain as a file from a website and paste it into the GETH directory manually? Because this sync part of the Ethereum wallet clearly isn't working.

Highly not recommended. Please use services like Myetherwallet for that.
In the near future, the Light clients will drastically improve sync quality. See you there :)

**Comment by jayman2989** [comment]
"in the near future" is ridiculous. This system isn't scalable or production ready, in fact it's a joke.
