### ISSUE TITLE
For imported presale wallets on Mist 0.5

### ISSUE THREAD

**Issue by tobysterling** [ethereum/mist#236]
Is the password for the new Mist account supposed to be the same as the password used to import the presale wallet?

After some troubleshooting the node is running fine and the account shows the correct amount of presale ether, but it won't let me use the presale password to sign transactions ('wrong password')

I don't recall setting any password when the Mist account was created ...

**Comment by frozeman** [comment]
It is supposed to be the same.
Can you please restart and try again?

**Comment by tobysterling** [comment]
?!?! I had restarted it 10 times, but somehow restarting it just now did the trick. You have a magic touch.

I will say: when transactions were failing, the transaction fee was reading 0 gas. After the restart, it filled in a small nonzero amount. Perhaps useful to know for others -- if you're not showing any fee, there's something wrong.

Also, I'd like to echo other users: the account vs. wallet distinction is confusing at first.

But to be clear: I'm very pleased with the layout and look of Mist, and almost everything worked well. The other hitch I had was not finding peers initially. Fixed that by synchronizing the clock to 'time.nist.gov' 

Keep up the good work, sir.

**Comment by frozeman** [comment]
Thanks,

yes for some reason sometimes the node connection doesn't work, which causes the "wrong password" message, and also prevents the proper gas estimate.

I need to look into this.

Are you on windows?

**Comment by tobysterling** [comment]
Yes, I'm on a Windows machine (windows 10 64 bit). Note that I just restarted Mist again and tried to send a transaction quickly and it failed in the same way ('wrong password'). After waiting for more node connections, and retrying, the transaction worked.

**Comment by frozeman** [comment]
@bas-vk there seems to be an issue with windows named pipe connections. I see this issue popping up often

**Comment by alexvandesande** [comment]
@tobysterling could you please download the [latest Wallet release, 0.5.2](https://github.com/ethereum/mist/releases/tag/0.5.2) and tell me if the problem persists?
