### ISSUE TITLE
--geth fast is slow. Any other way to recover my Eth?

### ISSUE THREAD

**Issue by lukecti** [ethereum/mist#2360]
#### System information
``````
Version: `0.8.10`
OS & Version: osx
Node type: `eth/geth(default)`
``````

Hi,

My eth dissapeared from Mist, so I'm assuming it is because it was struggling to sync, so I'e been attempting -geth fast for the last few days and after 2300000 block it has gone super slow, like 5 blocks every 5 minutes.

Is there any other way to recover my Eth?

Thank you

**Comment by lukecti** [comment]
Hi,

My eth dissapeared from Mist, so I'm assuming it is because it was struggling to sync, so I'e been attempting -geth fast for the last few days and after 2300000 block it has gone super slow, like 5 blocks every 5 minutes.

Is there any other way to recover my Eth?

Thank you

**Comment by michaelsproul** [comment]
You could try light mode. I use this all the time and it's pretty good. Just run geth like this in a terminal:

```
$ geth --syncmode "light"
```

Then open Mist and it will connect to that instance.

**Comment by lukecti** [comment]
I have cancelled my current sync (which did not finish) and my balance has corrected but it it stuck creating a wallet. I'm assuming this is also because it hasn't synced. 

I'm very sorry but I'm not great with the terminal commands. Is anyone able to show me the full sequence of running light mode or point me in the right direction?

& thank you Michael for pointing out light mode to me. Something else to try!

**Comment by nicolman** [comment]
Very awesome & fast with geth --syncmode "light" ! Thanks

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
