### ISSUE TITLE
Etherum wont synch after 36 hours

### ISSUE THREAD

**Issue by fabiorem** [ethereum/mist#2363]
Installed Ethereum Geth. Funded 0.25 ETH with bitcoins. 

Never saw the 0.25 ETH coming into place, because as already happens with Bt-Core, it needs to synch with the network. But whereas Bitcoin can synch fast, Ethereum is taking forever. After 36 hours it completed merely 16% of synch, and I closed it by accident. When I restarted the program, it come back to 0%, that is, impossible to synch, since I will have to turn my computer off sometime. Solutions?

**Comment by matthewleising** [comment]
I'm having a similar situation with my new ethereum project wallet. It is taking forever to download all the blocks. In the meantime, a small amount of eth I sent from my gemini account isn't showing up. When I sent a small amount of eth to a wallet I made at myetherwallet.com, it showed up.

does anyone know if the blockchain has to be done downloading on the ethereum project wallet before it receives transactions, i.e., before my ethics's will show up from my gemini account? thanks for any help.

**Comment by paddycy** [comment]
Same issue.....

**Comment by adrian69** [comment]
Same here ...

**Comment by Silviu-Muntean** [comment]
Hello to the community,
Same problem here, no solution
 Node doesn't sync.   Tried geth --fast,tried restarting Windows 7 and notting happens.
Usually it gets stuck at around 3,4 million. Sometimes it syncs 1 block per 5 minutes.
RAM memory is usually very high,probably pagefile.sys is big too... Could this be a RAM-issue?  
Tried for the past 5 days to sync with everything i've read on github.
Any advices are welcome.. Thanks!

**Comment by tagoreghanta** [comment]
Same Issue - Sync has been hung for past 3 hours and . Test Ethers sent to my account is not reflecting after 15+hours

**Comment by fabiorem** [comment]
After four days with computer on all the time, I tried to use Geth instead of the standard Ethereum wallet. I used the command --fast --cache=4056 (I have 16gb of RAM), but still, it passed nine hours already and only 9.8gb were downloaded. In the other blockchain (from the standard wallet, I made of backup of it) there is 38gb, downloaded during the four days. By what I have read in foruns, I can't mix both blockchains. The Geth chain failed two times, I'm still trying to use the --fast --cache=4056 command, but is stuck at 9.8gb since two hours ago. How we can use the currency if we can't synch our computers to the network? I wont use online wallets, I dont think they are safe for the long term.

**Comment by matthewleising** [comment]
I still have this same problem. I'm not sure I trust myetherwallet.com, it just seems flighty. Anyone have experience with myetherwallet.com? 

I'd really like to use the Ethereum foundation wallet but no one there seems to care that none of us can enable it. What's up with that?

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
