### ISSUE TITLE
Geth crashes at 700 MB RAM - sync stops

### ISSUE THREAD

**Issue by Tryggvason** [ethereum/mist#2365]
#### System information
``````
Version: `0.8.10`
OS & Version: Windows 10 x64
Node type: `Ethereum Wallet`
``````
Hi, 
79 days 9 hrs ago I bought some Ethereum Coins and since then I can't get the Ethereum Wallet to fully sync. 

Today I tried again: I installed the latest x64 update (v0.8.10), deleted the '%AppData\Roaming\Ethereum\geth\chaindata'-folder as somebody explained in a YouTube video and started it all over again. I googled  for other solutions but they have failed all the time.

I allowed geth.exe and ethereum wallet.exe through my firewall and opened the following ports in the router: 
Protocol TCP from Port 30303 to Port 30303 to MyComputer Port 80
Protocol UDP from Port 30303 to Port 30303 to MyComputer Port 80
Protocol UDP from Port 30304 to Port 30304 to MyComputer Port 80

I start Ethereum Wallet, it connects to peers and starts synchronisation, which it did even without the port and firewall adjustments, so that shouldn't be the problem.  

After a short time I see in the Task Manager that geth.exe has started. It starts at around 150 MB of memory usage and after a minute or two it has reached 600 MB and at around 750 MB geth.exe crashes (just vanishes from the Task Manager) and syncing stops at the following points: 

Downloading block 86,098 of 3,778,121, 
Downloading chain structure 199,214 of 341,952

What can I do now? I just want it to sync, dammit! :(

I have made a backup of the following files:  
'%AppData\Roaming\Ethereum\keystore' and '%AppData\Roaming\Ethereum Wallet'

My rig: 
CPU: Intel iCore i7-3770 CPU @ 3.40GHz
RAM: 16 GB DDR3 RAM

Please tell my how to get this done. Thank you.

**Comment by paddycy** [comment]
me TOOOOOOO HELLPPPPPPPP

How will we attract the masses if we cannot help ourselves....?

**Comment by solarin** [comment]
I had the same problem, i sorted it out just opening geth.exe from its path, without using Ethereum Wallet. once the synch is done, you can use ethereum wallet. 
see my full answer here: https://github.com/ethereum/mist/issues/2595#issuecomment-310786624

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
