### ISSUE TITLE
Missing progress indicator for 'processing blocks'

### ISSUE THREAD

**Issue by jonnor** [ethereum/mist#237]
Importing the chain has a nice progress bar. However after importing (at least when using --fast), it goes to a "processing blocks" step which also takes a long time. In the geth console output I can see progress
like `1159 downloader.go:1340] imported 225 state entries in 10.580784ms: processed 117949 in total`.

But in Mist it just stays on 0% progress for many many minutes, making the user unsure if something is broken...

Mist 0.5.0 on Arch Linux, with geth 1.3.5

**Comment by jonnor** [comment]
If possible these two stages should be combined into one progress bar. Cause it is quite dissapointing as a user when I reach 100% just to find out that I'm only around halfway...

**Comment by frozeman** [comment]
We will do, but for this we need to update the node API first.
