### ISSUE TITLE
Ethereum-wallet should default to light client mode

### ISSUE THREAD

**Issue by jtoomim** [ethereum/mist#2372]
When launching ethereum-wallet, the default mode should be to run geth in light client mode. There are a few main reasons for this:

1. Running a full node with a complete state trie is only useful to advanced users, and advanced users know how to change configuration options. Casual users need to have default options that address their needs with as little UX friction as possible.

2. Applications should be configured to use the minimum amount of system resources possible by default until directed by the user that greater functionality is needed. 

3. Going from 100 MB of data to 10 GB of data means that a lot of people simply can't run ethereum-wallet with its default configuration as it would cause them to run out of disk space. 

4. There are no good easy-to-use light client options for ethereum wallets with decent encryption of wallet files and open source code. Ethereum-wallet is pretty close, but the need to run it with special command line options in order to not make it use a ton of memory means that I can't just tell my mom to download and run it.

**Comment by paddycy** [comment]
I agree with this guy. It is ridiculous to have a 10gb download for a wallet. I CANNOT sync the wallet for over  a week now

**Comment by housemobile** [comment]
What flags can you input to sync EW or Mist in light mode?

**Comment by jtoomim** [comment]
Usually, with `./ethereum-wallet --node-light`. However, light mode got borked in the most recent release of Ethereum-wallet due to some changes in the geth command line options in 1.6.0. That should be fixed by the next mist/ethereum-wallet release, though.

https://github.com/ethereum/mist/issues/2254

**Comment by MaximRunev** [comment]
Full node (ethereum wallet) let normal sync only on SSD hard drive.

**Comment by User195** [comment]
I also vote to set light mode as default

**Comment by jtoomim** [comment]
https://github.com/ethereum/mist/pull/1547

**Comment by pparent76** [comment]
Unfortunately the light client mode don't seem to work better in 0.9 than it was working on 0.8.9

**Comment by muten85** [comment]
Same issue here. Not working on MIST 0.9

**Comment by pparent76** [comment]
I had it working with this staring script:

```
#!/bin/bash

ps -ae | grep geth
if [ "$?" -ne "0" ]; then
	geth  --syncmode "light"  &
	sleep 10;
fi
ethereumwallet --light-node
```

**Comment by evertonfraga** [comment]
Light client still has some way to go in regards to logs (events). We're closely following this subject.

**Comment by forest-hermit** [comment]
I hope so, my wallet uses 118 GB right now, this is unsustainable for most of users.

**Comment by rodgermoore** [comment]
Thanks @pparent76 ! This works for Mist

> I had it working with this staring script:

```` 
#!/bin/bash

ps -ae | grep geth
if [ "$?" -ne "0" ]; then
	geth  --syncmode "light"  &
	sleep 10;
fi
mist --light-node

**Comment by alex-miller-0** [comment]
I got around this by running geth at the command line:

    geth --light

And then opening the Ethereum wallet. It should automatically find your `geth` client by RPC.

But I very much agree with this issue. Ethereum Wallet should be doing light syncing by default.

**Comment by HaleTom** [comment]
As a work-around for linux users, based on [@pparent76's script](https://github.com/ethereum/mist/issues/2372#issuecomment-318395351), I came up with:

```
#!/bin/bash
# Work around for issues:
# https://github.com/ethereum/mist/issues/2254
# https://github.com/ethereum/mist/issues/2372
# https://github.com/ethereum/mist/issues/2999
set -eu # For script robustness
geth=$(which geth)
mist=$(which mist) # Change to explicit path if you call this script "mist"

# Use pidof as procps' pgrep is broken:
# sleep 1& pgrep -ax '^sleep$' should return null
if ! geth_pid=$(pidof geth); then
  echo "Starting $geth."
  "$geth" --syncmode light &
else
  echo "Geth is already running with PID(s): $geth_pid"
fi

if ! mist_pid=$(pidof mist); then
  echo "Starting $mist."
  "$mist" --light-node
else
  echo "Mist is already running with PID(s): $mist_pid"
fi
```

Call the script "emist" so it doesn't recursively call itself :)

**Comment by evertonfraga** [comment]
From Mist 0.9.1 on, there's a light client option under `Develop` menu. 

Please note there are still some bugs on the wallet when using Light Client. It will be reassessed when fixed.

**Comment by jacktang** [comment]
I have download 110G+ data, and I want to change light client mode, can I clean the data under geth or any script to clean the data?

**Comment by alex-miller-0** [comment]
@jacktang The light client will create a different directory for the new data. Find the location of your Ethereum directory (see [here](https://ethereum.stackexchange.com/questions/6550/how-can-i-find-my-chaindata-folder)) and navigate to `/yourpath/Ethereum/geth`. You will see two directories: `chaindata` and `lightchaindata`. If you only plan on using the light client from now on, you can remove `chaindata` and that should free up your 110GB 👍

**Comment by mahmoudilyan** [comment]
Does light client gets updated with the network?and can I do all the basic stuff inside it?

**Comment by solderzzc** [comment]
The chaindata is 167GB for now, it was taking 30+ days for me for the sync, if the procedure done faster, I would end up to sell them at $300...

**Comment by mrspiderbrain** [comment]
This would really help, the default install process looks all pretty but will fail on many people's hardware, or appear to fail due to the massive time required to sync.

**Comment by cloudzhong** [comment]
totally agree, meaningless for a wallet to sync so big data, it is not an node.

**Comment by evertonfraga** [comment]
The Light Client's discovery protocol is defective at this very moment, making it almost unusable. It is treated as "highly experimental" by its own developers. 

Here in Mist we're coming up with some solutions, that include a remote node integration (like INFURA), which you can follow on this branch: https://github.com/ethereum/mist/tree/layered-nodes

We'll keep you all posted about this progress.

**Comment by danielocdh** [comment]
@evertonfraga where are you keeping us posted? thanks
