### ISSUE TITLE
Can't switch between test and main network

### ISSUE THREAD

**Issue by johnnycheadshot** [ethereum/mist#2375]

**Comment by sathishvj** [comment]
This is not an official answer, but I can tell you of something that worked for me.

1. You can start geth separately and use command line options [geth cli options](https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options) to make it start on your preferred network.

2. You can change the default network in your Mist/Ethereum settings.  I don't know if it is recommended, but I did and it worked.
  - Find the folder where the Mist settings are stored.  On Mac it is under ~/Library/Application Support/Ethereum Wallet.  On windows maybe it is something like C:\users\app data\roaming\Mist.
  - There was a file called 'network' here.  Back it up.
  - Then edit it.  There was only one line in the file - either _main_ or _test_.
  - On restarting, it started with the required network.

**Comment by beuted** [comment]
For me the network file was showing "rinkeby" I had to restart my mac to open mist on rinkeby at start again :/
