### ISSUE TITLE
Mist 0.5.0 (OSX): Stuck on "Looking for peers..." bug

### ISSUE THREAD

**Issue by nhoggard** [ethereum/mist#238]
0.4.0 didn't work either.
0.3.9 worked fine before, but reinstalling it it no longer works.

I synced my clock, but no effect.

**Comment by frozeman** [comment]
can you try 0.5.0?

**Comment by nhoggard** [comment]
I've tried 0.5.0 (read the headline ;) )
Den 4 mar 2016 3:23 em skrev "Fabian Vogelsteller" <notifications@github.com

**Comment by winzig** [comment]
Having the same issue on 0.5.1 running on OS X 10.11.3

**Comment by frozeman** [comment]
Works fine for me and others, do you have a firewall on? Or a protected router?

**Comment by nhoggard** [comment]
Probably a router with a firewall.

**Comment by winzig** [comment]
Yep, that was it. I thought I had already opened the necessary port but had a typo! 😬
