### ISSUE TITLE
Shifty ether classic deposit will not go through

### ISSUE THREAD

**Issue by emanbayani** [ethereum/mist#2382]
Hello,
I deposited 3.16256458 ether classic to 0xff56de1414209a6bc537a9ba02273c80fcd1aa08 and it is suppose to be converted to .25 ether and sent to address: 
0x11e83a2729648b762f668670fa48995a7d2161e0

and it is stuck in the awaiting exchange in shifty!  Please let me know why the deposit did not go through or I like to have my funds returned back to my to ether classic address:
0x23b1c281fdab8f39799b6154f7c5c96b6f43214b

Sincerely,
Eman Bayani

Please I like to my money back if shifty does not convert my 
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots
![image](https://cloud.githubusercontent.com/assets/29053688/26566607/29e73a40-44ba-11e7-8637-3824df7a158a.png)

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment]
Hi, this should be handled with Shapeshift support team.
