### ISSUE TITLE
Paid wallet fee twice / created two wallets with same name

### ISSUE THREAD

**Issue by uitty400** [ethereum/mist#2383]
#### System information
``````
Version: `0.8.9`
OS & Version: linux ubuntu 16.04
Node type: `eth/geth(default)`
``````

I recently created a new wallet and for some reason I confirmed the gas fee transaction twice for the same wallet. Or maybe I created two wallets with the same name but only one shows up. Now I have one wallet for double the fee.

**Comment by alexvandesande** [comment]
If you have paid gas twice then you have two wallets. Look for the second one on etherscan and add it.
