### ISSUE TITLE
Unsuccessful Ether Transfer

### ISSUE THREAD

**Issue by mhmseyda** [ethereum/mist#2385]
Hi, 

I started to use ethereum wallet and trasfered ether via shapeshift.

After the transaction i saw "Transfering succesfully complete"
But i could not see transfer on my ethereum wallet.
Sync complete and i am sure it is up to date.

Can anyone help, what is the problem.
muharremseyda@gmail.com 

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment]
1. What was the shapeshift transaction page? You can get that on your browser history.
2. Then double check the ethereum address you transfered to via shapeshift has gotten the right amount (you can check here: https://etherscan.io/)

**Comment by mhmseyda** [comment]
Hi, thank you so much for your support.

I check the links;

1- https://shapeshift.io/#/status/a07b387c-720a-4c8a-88b0-4218b8b7ece6
2- https://etherscan.io/address/0x8c1345a1219de9c2f230353ddbf7b2282244eff1

Best wishes,



2017-06-02 17:18 GMT+03:00 Ev <notifications@github.com>:

**Comment by jmath1** [comment]
Hi, I am not sure why I am being sent this. I have not recently made any
transactions on shapeshift. Can you tell me what this is from?

**Comment by mhmseyda** [comment]
Hi jmath1,

It is for exchange your cripto currency such as btc to etc, or any others.

2017-06-03 0:10 GMT+03:00 jmath1 <notifications@github.com>:

> Hi, I am not sure why I am being sent this. I have not recently made any
> transactions on shapeshift. Can you tell me what this is from?
>
