### ISSUE TITLE
Ethereum transfer doesn't show up on wallet

### ISSUE THREAD

**Issue by Jvl12** [ethereum/mist#2386]
Dear all,

The ethereum transfer I made was succesfull. I have got all the transaction information. However, it doesn't show up on my ethereum wallet, which is correctly linked. What to do? HELP!

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by jcantieri** [comment]
I have the same problem...transaction successful but doesn't appear in wallet. help!!

**Comment by garretlaxton** [comment]
Your wallet needs to fully sync all blocks first.

**Comment by robertheessels** [comment]
Same problem here. Fully synced. Fails since it auto updated to 0.8.10.

**Comment by jcantieri** [comment]
Once it fully syncs will the transfer appear?

**Comment by jcantieri** [comment]
My wallet has been really slow to sync but i'm afraid to do the fast sync correction because I had this transfer happening--not sure what i'm doing new to this all thanks for your help!
