### ISSUE TITLE
Sent more Bitcoins than limit

### ISSUE THREAD

**Issue by alexebrenz** [ethereum/mist#2387]
Unfortunatelly I sent 10 bitcoins to ethereum wallet. The limit is 1.32 bitcoins maximum limit.

What happens? I lost my bitcoins?

**Comment by garretlaxton** [comment]
Guessing you used shapeshift, I'd recommend you contact their support.

**Comment by evertonfraga** [comment]
Closing this. The service you used is the sole responsible for that. Thanks
