### ISSUE TITLE
Hangs with "Add Account" - Mist Wallet 0.5.0 (Beta 8) - Windows 7

### ISSUE THREAD

**Issue by SteffenIvanhoe** [ethereum/mist#239]
I tried to add an account. I enter the password and then do it again as a correctness check and after that everything freezes. The wallet does not take any more clicks. I had to abort it with the Windows Task Manager. After a restart the new account was there. I have not yet checked whether the passwort is correct.

**Comment by luclu** [comment]
Please update to version 0.7.4 (includes geth 1.4.4) and report back.
Also please have a look at this and report back here: #669
I will close this for now, but feel free to come back and discuss a solution!
