### ISSUE TITLE
Blockchain takes way too long to sync

### ISSUE THREAD

**Issue by Pac23** [ethereum/mist#2394]
It's been three days and my blockchain hasn't sync'd yet idk why its taking so long time i am on a 100/100 connection.

**Comment by MartijntenCaat** [comment]
I have the same issue, I even tried deleting the application and chaindata folder and installing it again. Same story, even with the geth --fast command it still takes several days to sync the whole chain.

**Comment by aleksre** [comment]
Same problem. The wallet is basically unusable right now. I have tried to delete chaindata several times and also tried many different geth commands, but each time it will stop at a new block. The only time I was able to get in with an updated wallet balance was when i tried to run geth --light overnight, then launched the wallet. However after closing and restarting the wallet the sync was restarted from 0 again.

**Comment by Pac23** [comment]
@aleksre @MartijntenCaat i have tried the same things you folks have,i hope this is fixed soon.

**Comment by NeunMalsechs** [comment]
Had the same problem for weeks now. No one is working on it. Seems that Ethereum requires an SSD as a system disc. Large disadvatage to bitcoin. Will create a lot of unhappy first (and last) time users.

**Comment by Pac23** [comment]
@NeunMalsechs Conspiracy theory but imo these people are trying to force others to store their eth on online wallets and at a later point in time steal the eth.

**Comment by DIESLTEK710** [comment]
same issue with me.. i have 2 machines ive been trying to load it up on. one is not an ssd and it downloaded 8-10hrs.. well up until 3,200,000 and change and then it freezes up... my other pc has an ssd but i dont want to dedicate my primary ssd on my primary pc to a wallet so i had the blockchain stored on a separate 10k drive and im on day 7 with 47,000 blocks left to go.... i do not understand this...

**Comment by burdo3417** [comment]
I have to run it in light mode. Full or fast is unusable even on SSD.
To run geth from the command line:
Go to the geth dir (default is C:\Users\YOUR_USER\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked) create a shortcut for geth.exe. Right click on it. On the "target" field add:
--syncmode=light 
Run the shortcut. Keep the command line window open.
Open the ethereum wallet as usual. It will sync in light mode. First time may take a little while. Next time is instant.

I dont know if there are any security issues with it or any additional problems. Perhaps someone else can comment on it.

**Comment by NeunMalsechs** [comment]
@burdo3417 Thanks for the hints. With this I could at least see my current balance. 

Nevertheless this is a best a workaround, feasible for a technician, nothing that can be asked from business user. 

And I fear that this is a problem of Ethereums architectural design. Especially since the developer community doesn't even respond to those reports. Will not be easy to fix. Despite the good marketing the Ethereum Foundation is doing, it will come back to haunt them.

I guess I will have to take another look at Lisk if I want useable Smart Contracts.

**Comment by Moorelife** [comment]
Elsewhere I saw the workaround described that works for me on a normal HD:
- install parity separately
- run it as 'parity.exe --geth'
- start up mist when synced
- keep both running....

**Comment by dfkthf125** [comment]
я вообще не могу кошелек открыть

**Comment by PatchRanger** [comment]
I guess, it is related to #2372 .

**Comment by tomtom87** [comment]
it's taking me 2 days to sync my mac book pro so far, it's always get stuck at the end the last few blocks never seems to finish. 

Windows clients all failed to sync so far last week and gave up

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097

**Comment by haikieu** [comment]
Mist app mostly freeze my PC, it always occupies 100% disk performance and also make it fragmented. 
My HDD now is almost burnt up and going to be broken down.

**Comment by Gasparunho** [comment]
Just use Exodus

**Comment by tomtom87** [comment]
+1 Exodus ftw or MEW if you cant install it

**Comment by danhnguyen01** [comment]
Hi. I am a newbie on smart contracts and have followed the Smart Contract Initiative but it has been running for more than two days and has not been completed. please kindly guide me more. thank you very much.
![screenshot 22](https://user-images.githubusercontent.com/33786762/32982207-2d1e09f6-ccb3-11e7-80ca-414d4577aff1.png)
