### ISSUE TITLE
MISSING ETH

### ISSUE THREAD

**Issue by shangguan1118** [ethereum/mist#2398]
Hi there

Please help me!

I'm new to MIST wallet and I was trying to participate some crowdsales via MIST.
I sent 120 ETH to my new MIST account from Poloniex, have not receive them yet.
Could you please help me to find my ETH? I wanted to participate the BAT crowdsale, but now just want my ETH back.
By checking this address on etherscan, I could see that 120ETH inside, however there is nothing in my wallet when I open the wallet from my PC.

The address below is my new MIST account 1, I send my 120 ETH to the address below
0xe598026b97418b988b1f5c1d39db8049d248040a

Info below is from my poloniex history.
Complete ETH 120.06018523
2017-05-30 15:14:08
Address: 0xe598026b97418b988b1f5c1d39db8049d248040a
Txid: 0x8c693da92a74093befc31e454dedbd644a646982e5d79b217190b148fa3215e3

The other one, main account, I have not try send any thing here yet.
Main account (Etherbase)
0x7eD67e4C23e490892e68EF8574Fc28CcEC29c694

Let me know what I should do please

Thank you very much
![00000](https://cloud.githubusercontent.com/assets/29077336/26660074/59e16ec0-462a-11e7-88d4-53776a5fcece.PNG)
![00001](https://cloud.githubusercontent.com/assets/29077336/26660075/5c323fec-462a-11e7-9eb7-3d6469b6a348.PNG)
![00002](https://cloud.githubusercontent.com/assets/29077336/26660079/5ed8b550-462a-11e7-8038-9c8d8f9e5349.PNG)

**Comment by GeekBoxIT** [comment]
I believe you need to wait for your wallet to finish syncing. See top right of your wallet with blocks left.

**Comment by garretlaxton** [comment]
Your wallet will need to sync all blocks before your ETH shows, you can use myetherwallet.com in the mean time.

**Comment by shangguan1118** [comment]
Thank you guys, GeekBoxIT and garretlaxton.
I reopened the wallet quite a few time.
This time, 5 mins ago, it looks like that, to me the blockchain is not working properly.
Anything I should do to correct it?
![00005](https://cloud.githubusercontent.com/assets/29077336/26660396/c4d6642c-462c-11e7-9c88-50c6405d3579.PNG)

**Comment by GeekBoxIT** [comment]
@shangguan1118 , it's syncing a lot of blocks, depending on connection it will take a few hours.

**Comment by shangguan1118** [comment]
@GeekBoxIT , do I have to keep the wallet open untill 100%, and if I shut it down while halfway, next time will have to redo the whole thing?

**Comment by GeekBoxIT** [comment]
Wallet needs to be open to sync, next time you open, it will sync new blocks but it won't have to re-do the old blocks it already synced.

**Comment by shangguan1118** [comment]
@GeekBoxIT 
So after sync 2,105,500 blocks, according to the wallet, I should be able to see my balance in the wallet?
THANK YOU from my heart.
Let's see what I got after the sync

**Comment by GeekBoxIT** [comment]
@shangguan1118 , that is correct. I do take tips ;)

**Comment by garretlaxton** [comment]
@GeekBoxIT correct but syncing time more depends on SSD or HDD, SSD being faster.

**Comment by GeekBoxIT** [comment]
@shangguan1118 Did everything finally sync up and work out?

**Comment by shangguan1118** [comment]
@GeekBoxIT
Good morning man
I always feel like my internet connection speed is decent
However I still have1.95M blocks to go
Seems like will take 3-5days.
YESTERDAY I kept the wallet running for like 5 hours, from 2.10M to 1.95M left, is that normal?



![00006](https://cloud.githubusercontent.com/assets/29077336/26682451/5b911afc-4695-11e7-95f6-efb251b89878.PNG)

**Comment by mvisconti** [comment]
any luck here?

**Comment by shangguan1118** [comment]
@GeekBoxIT
@mvisconti 

Hi mates, the blocks stopped syncing since yesterday
I still have 1.48M block to go
Any idea?

June 3rd, 2:30pm

![0007](https://cloud.githubusercontent.com/assets/29077336/26757179/11f24b20-4869-11e7-8447-1d051c51506a.PNG)

**Comment by evertonfraga** [comment]
Hi @shangguan1118, can you please check this section of the guide? [Unable to find peers.](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide#unable-to-find-peers)

Also, there's a known issuee regarding use of HDD (hard drive disk) along with Geth. It's taking indeed too much time.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Comment by shangguan1118** [comment]
The issue is fixed on June, thanks tho


Eason Shangguan


________________________________
发件人: Ev <notifications@github.com>
发送时间: 2017年9月28日 13:04
收件人: ethereum/mist
抄送: shangguan1118; Mention
主题: Re: [ethereum/mist] MISSING ETH (#2398)


Hi, we have just launched Mist v0.9.1<https://github.com/ethereum/mist/releases/v0.9.1>, with Light Client integration (beta).

What does that mean?

  *   Sync times reduced by an order of magnitude while staying safe.
  *   Much smaller storage required.

How to activate?
[30986199-ff885216-a468-11e7-82ec-e66aeb859ab8]<https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png>

I'm closing this issue. Should you have any trouble, please refer to these channels:

  *   Canonical issue regarding sync: #3097<https://github.com/ethereum/mist/issues/3097>
  *   Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

―
