### ISSUE TITLE
Cant create an Account

### ISSUE THREAD

**Issue by jp3492** [ethereum/mist#2399]
Everytime i want to create an account it tells me i should backup my files and then no account appears under my accounts.
Anyone has an idea what is causing this problem?

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment]
That's not cool, I know. If you restart Mist/Wallet, did the accounts show up there?

Are you using an external node? Geth or Parity?

**Comment by jp3492** [comment]
I did restart it a couple times and always the same error. i deleted it
from my laptop and reinstalled it with the lates exe file from github and
now it shows me this error message:
*see attached image*

**Comment by jp3492** [comment]
when i download the windows file on github, not the exe file, as before, I
can open the wallet but still cant create accounts. It always shows me this
message (attachment) and resumes with the wallet and only the base account

**Comment by jp3492** [comment]
Could you redirect me to someone that could support me in this case? i cant
find solutions online and my tech knowledge is not good enough to look into
my pc if there is something wrong.
Thanks a lot for a response
Jan-Philipp

**Comment by BearerOfHonesty** [comment]
I have the same problem.

When I try to create an account it asks for and confirms a password and then shows the message about backing up your keystore. A new file shows up in the keystore but no new accounts show up in the account list, either before or after restarting mist.

Mist: 0.8.10 (installed with the windows installer)
Ethereum node: Geth 1.6.5

**Comment by evertonfraga** [comment]
Please try with up to date software, as it is probably fixed. 

Should you still encounter the same issue, reopen or create a new one.
