### ISSUE TITLE
First time running Mist/Ethereum - "Couldn't connect to the node?"

### ISSUE THREAD

**Issue by D84G** [ethereum/mist#2400]
Any help would be appreciated. I've used the Mist installer - "Mist-installer-0.8.10.exe"

#### System information
``````
Version: `0.8.1`
OS & Version: windows 7 x64

[node.log.txt](https://github.com/ethereum/mist/files/1044427/node.log.txt)
[node.log.0.txt](https://github.com/ethereum/mist/files/1044426/node.log.0.txt)


Node type: `eth/geth(default)`
``````
![eth](https://cloud.githubusercontent.com/assets/29119932/26675943/1874f18e-4709-11e7-9540-f0fc4e64b1d9.png)
[developer console.txt](https://github.com/ethereum/mist/files/1044414/developer.console.txt)

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment]
Hi @D84G, can you please check this guide?
https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide#unable-to-find-peers

thanks!

**Comment by D84G** [comment]
Thanks @evertonfraga - I've tried that, and get the following (just sits there):

![geth_manual](https://user-images.githubusercontent.com/29119932/26877850-a9009c7a-4bce-11e7-9186-81c796267d0f.png)

I've also forwarded port 30303 just in case, and no firewall is running. I've just tried --nat=none and am now getting the following:

![get-natnone](https://user-images.githubusercontent.com/29119932/26877974-17b53112-4bcf-11e7-91cc-ac54027354f4.png)

I assume that means it is working?

**Comment by evertonfraga** [comment]
Yes, that's it.
