### ISSUE TITLE
ETH fails to send; Mist wallet fails to update balance

### ISSUE THREAD

**Issue by confirmationbias** [ethereum/mist#2401]
After trying for many months to download enough blockchain to access my ETH, I finally can see the balance in my Mist wallet. I immediately wanted to get it OUT of Mist, since it's so hard for me to access. i made three successful transfers in order to test the wallet, sending a total of 1.2 ETH in those three transactions. I confirmed with the recipient that these 3 transactions were successful and can see them on Etherscan.

But Mist won't update my balance. It's unchanged. And it shows ZERO confirmations for all three transactions, even though they have already completed.

Unfortunately, I can't seem to send any more ETH out of Mist now either. It's like the first 3 sort of worked (without updating my Mist balance) but every time I hit "send" now, nothing happens. Nothing is received on the other end, and there is no update on Etherscan for the additional transactions, as if they're not happening. Note, these transactions are well below my total remaining balance, after I deduct the 3 successful transactions, so there are enough ETH in my balance to send them. 

Any idea what's happening?

**Comment by evertonfraga** [comment]
Hi @confirmationbias, sorry to hear that. Are you using latest Mist and Geth? 

when you hit some hard walls like this, you can use your keystore (privatekey) to transfer funds using another wallet, such as the awesome MyEtherWallet.com. Make sure not to trust just any wallet. 

You can have access to your keystores opening Mist/EthereumWallet, `Accounts > Backup > Accounts`. So you'll see some files begining with `UTC-2016-...`.

Please let me know about it. Thanks

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
