### ISSUE TITLE
How can I connect Mist to an other node and to an other blockchain?

### ISSUE THREAD

**Issue by Nogreedy** [ethereum/mist#2402]
``````
Version: 0.8.10
OS & Version: windows 10 (64 bits)   - Linux Mint 18.1 (Xfce - 64 bits)
Node type: geth
``````
Hello,
I use Mist .... and I appreciate it so much...
I use Mist on my Windows 10 PC (192.168.0.1) and it works very well (blockchain OK and synced)... 
but now I have a new Linux PC on my local network (192.168.0.2)... and I'd like to use Mist also on this new PC (to use MultiSig...) ... but this new PC has a slow HDD and I can't download blockchain on this new PC.
Is there a concrete way to connect this Linux PC to my Windows 10 PC (192.168.0.1) to use only one blockchain (node?) ?
What is the correct CLI command and options (rpc or ipc options???) to use (geth?) to connect to an other blockchain?  
Thanks in advance for your answer.

**Comment by evertonfraga** [comment]
Hi @nogreedy. You can find this information on our Readme page: https://github.com/ethereum/mist/blob/develop/README.md
