### ISSUE TITLE
So do I have to wait for the wallet to sync completely before I can see my ETH, or just until it syncs past the block it was purchased on?

### ISSUE THREAD

**Issue by glad-zilla** [ethereum/mist#2403]
Block  #3689927
Home Blocks Block Information

Overview
Block Information
  Height:	< Prev   3689927   Next >
  TimeStamp:	20 days 19 hrs ago (May-11-2017 05:52:13 PM +UTC)
  Transactions:	45 transactions and 22 contract internal transactions in this block
  Hash:	0x775ccd13f2d90ee3d395756f2c14c841d47fcc39f598e597b26a9be7bedd0489
  Parent Hash:	0x8c10ae50dd7dcb3cde504d89f663f5756db4b8dba848fa740d5db9cc6d66f0be
  Sha3Uncles:	0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
  Mined By:	0xea674fdde714fd979de3edf0f56aa9716b898ec8 (Ethermine) in 19 secs
  Difficulty:	379,133,086,655,213
  Total Difficulty:	257,678,610,008,412,125,810
  Size:	6351 bytes
  Gas Limit:	4,307,503
  Gas Used:	2,416,348
  Nonce:	0x8844525420010aae5e
  Block Reward:	5.05095745 Ether (5 + 0.05095745)
  Uncles Reward:	0
  Extra Data:	ethermine - EU3 (Hex:0x65746865726d696e65202d20455533)

**Comment by sathishvj** [comment]
You can check the address on etherscan.  etherscan.io/address/0x....

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
