### ISSUE TITLE
Stuck at 2234730

### ISSUE THREAD

**Issue by lee-van-oetz** [ethereum/mist#2405]
#### System information
``````
Version: `0.8.10`
OS & Version: Ubuntu 16.10
Node type: `geth`
``````
I get stuck at block 2234730 and weirdly I'm shown of 2235020 while it was previously showing something close to current block count 3.8M+ as a target
![ethereum_stuck_2234730_of_2235020](https://cloud.githubusercontent.com/assets/7560923/26682964/881a295e-46e2-11e7-8818-b47f9b7d173b.png)

 Not sure what to do, syncing to that point took couple hours already.

**Comment by malinovskymax** [comment]
Same for me. Windows 10 X64.  But stuck at block 2,283,415 of 3,810,591. As I see in geth/chaindata directory, dowloaning continues, but counter stuck.

**Comment by dudezilla** [comment]
will not sync. Mist version 
Troubleshooting all week on Ubuntu 16.04.2 
Downloaded mist again.
And again... and again. 


unable to connect to socket... How do I convert this MIST wallet into something else as is contains Ether.
This is harsh.

I've  moved my eth folder and attempted using several different versions of Mist, updated Geth...

Geth is crashing with checksum mismatches...

INFO [06-02|21:50:58] Block synchronisation started 
INFO [06-02|21:51:15] Imported new state entries               count=1 elapsed=3.168ms processed=1 pending=17
INFO [06-02|21:51:29] Imported new state entries               count=2 elapsed=1.977ms processed=3 pending=49
INFO [06-02|21:51:38] Imported new state entries               count=2 elapsed=11.416ms processed=5 pending=81
WARN [06-02|21:52:08] Synchronisation failed, retrying         err="receipt download canceled (requested)"
WARN [06-02|21:52:29] Lied about chain head                    peer=43bf34f25123733f reported=245952 found=246128
WARN [06-02|21:52:29] Synchronisation failed, dropping peer    peer=43bf34f25123733f err="peer is stalling"


IPC Timeout after 1000 MS in 

------------------------------

WARN [06-02|21:53:38] Synchronisation failed, retrying         err="no peers to keep download active"
INFO [06-02|21:53:53] Imported new state entries               count=1 elapsed=1.510ms  processed=7 pending=17
INFO [06-02|21:53:53] Imported new state entries               count=2 elapsed=2.732ms  processed=9 pending=49
INFO [06-02|21:53:57] Imported new state entries               count=22 elapsed=21.209ms processed=31 pending=401
INFO [06-02|21:53:59] Imported new state entries               count=29 elapsed=26.090ms processed=60 pending=865
INFO [06-02|21:53:59] Imported new block headers               count=0  elapsed=8.553ms  number=1339308 hash=09a8d1…cd565e ignored=192
INFO [06-02|21:54:04] Imported new state entries               count=50 elapsed=40.906ms processed=110 pending=1666
INFO [06-02|21:54:06] Imported new block headers               count=0  elapsed=15.672ms number=1339692 hash=bb6db2…6af6c4 ignored=384
INFO [06-02|21:54:06] Imported new state entries               count=65 elapsed=50.201ms processed=175 pending=2705
INFO [06-02|21:54:09] Imported new state entries               count=110 elapsed=55.771ms processed=285 pending=4465
INFO [06-02|21:54:16] Imported new state entries               count=181 elapsed=97.385ms processed=466 pending=7361
INFO [06-02|21:54:19] Imported new state entries               count=209 elapsed=100.275ms processed=675 pending=10705
INFO [06-02|21:54:22] Imported new state entries               count=260 elapsed=137.992ms processed=935 pending=14866
INFO [06-02|21:54:29] Imported new state entries               count=333 elapsed=148.584ms processed=1268 pending=20193
CRIT [06-02|21:54:31] Failed to store block body               err="leveldb/table: corruption on data-block (pos=445498): checksum mismatch, want=0x8526e802 got=0xa7932930 [file=013288.ldb]"


The  new ETH currency is a complete copy of the block-chain itself. 


IS THERE A BINARY OF THE BLOCKCHAIN I CAN IMPORT!

**Comment by dudezilla** [comment]
INFO [06-02|22:18:05] Imported new block headers               count=0    elapsed=177.529ms number=1343994 hash=d166ef…ffc3fa ignored=2048
WARN [06-02|22:18:05] Rolled back headers                      count=356  header=0->0 fast=1339899->1339899 block=0->0
WARN [06-02|22:18:05] Synchronisation failed, dropping peer    peer=bc9eca35369ee79b err="retrieved hash chain is invalid"
INFO [06-02|22:18:15] Imported new state entries               count=1    elapsed=4.845ms   processed=69990 pending=17

It keeps doing this, until eventually it reports something along the lines of:

CRIT [06-02|21:54:31] Failed to store block body err="leveldb/table: corruption on data-block (pos=445498): checksum mismatch, want=0x8526e802 got=0xa7932930 [file=013288.ldb]"


I've got this block corruption - Is this a form of DOS attack, -  or is this a flaky software stack... 
A build problem or a problem in the underlying OS.

I have not bothered running a NODE in almost a year.
