### ISSUE TITLE
"could not unlock signer account" - Mist Wallet 0.5.0 (Beta 8) - Windows 7

### ISSUE THREAD

**Issue by SteffenIvanhoe** [ethereum/mist#241]
Trying to make a send from a test account (which I have used before to make sends) results in two messages of "wrong password" (hihgly unlikely, please allow for a visible password input!) and the third try results in a short "could not unlock signer account" message. A 4th try finally brings the send on its way.

For this test account the passwort is extremly simple. I can not really imagine to have it mistyped. But I would clearly prefer to have an option to see what I type!

**Comment by alexvandesande** [comment]
Merging this with #554
