### ISSUE TITLE
ether did not show up in my account

### ISSUE THREAD

**Issue by jessica45delta123456** [ethereum/mist#2410]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by garretlaxton** [comment]
Your wallet most likely needs to fully sync, then your ETH will show.

**Comment by mvisconti** [comment]
How can we sync faster? I am also experiencing this issue, first transfer to wallet...

**Comment by garretlaxton** [comment]
You can use myetherwallet.com to access your ETH while your wallet syncs.

**Comment by evertonfraga** [comment]
If you guys are in a hurry, you can use a service like MyEtherWallet.com to transfer your funds. 

The underlying ethereum node that runs along with Mist is currently having a hard time syncing on HDD (hard drive disks), so it takes longer than intended. 

I am closing this for now, feel free to reopen if needed. Thanks
