### ISSUE TITLE
Keep dropping Peers and won't sync.

### ISSUE THREAD

**Issue by jbitz** [ethereum/mist#2413]
#### System information
``````
Mist Wallet
Version: `0.8.10`
OS & Version: Windows 10 - 64bit
[Mist.zip](https://github.com/ethereum/mist/files/1046503/Mist.zip)

Node type: Geth 
![screenshot1](https://cloud.githubusercontent.com/assets/29135588/26708429/6754a742-4711-11e7-89f1-c42248a2a971.jpg)
I do have Malwarebytes Anti-malware exceptions set for:
C:\Users\Jason\AppData\Roaming\Mist\binaries\Geth\unpacked\geth.exe
Please Help. Thanks.

**Comment by jbitz** [comment]
It's finally syncing, I have no clue what the deal was. However I am still interested in finding out what the problem was.

**Comment by jbitz** [comment]
Well it didn't sync seems to be moving backwards now, Don't know what to do.

**Comment by sathishvj** [comment]
The seemingly "moving backwards" was probably because more blocks were mined since the previous time.

Even I've occasionally seen interference when there was a torrent tool or anti virus.  Try without that.

**Comment by evertonfraga** [comment]
You have more peers than usually needed, that's not the problem.

Do you use hard disk drives (HDD) or solid state drive (SSD)? It seems that geth has a hard time syncing with HD. some intense I/O operations.

**Comment by jbitz** [comment]
I have both but geth is on HDD, how can I change this?

**Comment by sathishvj** [comment]
Though there might be a speed difference, I don't think there is much impact because of that.  Your issues are likely to be elsewhere: is the disk full?  are you behind a proxy?  can you connect via a ethernet cable directly to the wifi access point and try?  is a restart of mist helping?  how about a restart of the computer?

I barely get a handful of peers where I am and my sync is reasonably fast.

**Comment by jbitz** [comment]
Tried moving Geth to SSD but it got corrupted, however with a fresh install on a new SSD I was able to download the blockchain pretty fast. Only issue that I had was my JSON file was not recognized so I had to import my my keystore manually.  Happy to say I got it all back up and running. Thanks for your help Sathishvj. :)
