### ISSUE TITLE
BackUp not working

### ISSUE THREAD

**Issue by Brixxlnator** [ethereum/mist#2414]
I cannot make a backup. Clicking on Account -> Backup -> Account does nothing. No window opens.
However, backing up the other data does open a window.

There is also no keystore-folder to be found on my PC.

How do I backup my files?

**Comment by garretlaxton** [comment]
If you're on Windows, you can go to `start menu` and in the search bar type & open `run`. Once `run` opens type `%appdata%` then `Ok`, you should have a folder titled `Ethereum` inside that folder will be your keystore folder with your backup.

**Comment by Brixxlnator** [comment]
Thank you for reply. I have searched AppData, there is no keystore folder. However, I changed the blockchain directory during the setup, and there I found the keystore folder. 

Since most posts link to %appdata%, I was somewhat confused as to why I could not find it there.

**Comment by evertonfraga** [comment]
Glad you made it @Brixxlnator. I am closing this for now
