### ISSUE TITLE
Couldnt start an ethereum node (Wallet)

### ISSUE THREAD

**Issue by oldpoison** [ethereum/mist#242]
This is the error that says when I open the wallet

if you installed geth use this command to run it.. 

geth --ipcpath \\.\pipe\geth.ipc

**Comment by dobcrypto** [comment]
@oldpoison see my solution https://github.com/ethereum/mist/issues/231

**Comment by oldpoison** [comment]
@dobcrypto Could you syn with ETH node ? i guess i try to open it.. but it says...1.000 million block left 
![image](https://cloud.githubusercontent.com/assets/17651457/13543049/d6ff6624-e239-11e5-883b-b452c9f74db0.png)

**Comment by dobcrypto** [comment]
@oldpoison with ETH node can't =(
only geth...

**Comment by oldpoison** [comment]
@dobcrypto but my wallet its on ETH node... i have no money in Geth... :/ They told you about if they will fix that ? .... witch network do you use ? main  or testnet ? whats the different ?

**Comment by dobcrypto** [comment]
@oldpoison main network, test is local.
Will wait, then they fix eth node on Win.
Or you can use older mist version, i think so.

**Comment by oldpoison** [comment]
@dobcrypto i have been trying from yesterday in this 3 versions 0.4.0 , 0.5.0 and 0.5.1 no one its working..!! i was guessing that I lose my money haha -.-!

**Comment by dobcrypto** [comment]
@oldpoison  wow =(
You can try to use myetherwallet.com/#send-transaction to see you eth balance and spend it.

**Comment by oldpoison** [comment]
@dobcrypto what about this site ? its safe ? sounds like you put your JASON and key,,, and bye bye Ether hahaha,,,

**Comment by dobcrypto** [comment]
@oldpoison You can try or not...

**Comment by oldpoison** [comment]
@dobcrypto do you try ? can you send me proof that this site its working for you ? .. i was reading that my account was not create before 31 december,, will work in this site ?

**Comment by dobcrypto** [comment]
@oldpoison now i start Ethereum-Wallet-win64-0-4-0 and it normal sync on eth node(i think on eth).
Waiting to complete sync
![zagn3au 1](https://cloud.githubusercontent.com/assets/16653151/13543787/cac78684-e27f-11e5-8410-5fe4744ce2f8.png)
.

**Comment by oldpoison** [comment]
@dobcrypto told me about if you can access to your wallet ... because I was trying in 0.4.0 and do the same.. it stop in 1018361 and not continue downloading the block..!!

**Comment by dobcrypto** [comment]
@oldpoison I was it!
Ethereum-Wallet-win64-0-4-0 has normal sync eth node and start.

**Comment by alexvandesande** [comment]
Were you able to run it? It seems so. For further reference, install the command line client manually: ethereum.org/cli
