### ISSUE TITLE
Mist wont complete sync with HDD's

### ISSUE THREAD

**Issue by Derkor** [ethereum/mist#2420]
Sync will get stuck at different intervals or will loop from the start.
Had this problems with 3 HDD's. Synced with them 24-36 hours each but no solution. 
Was extremely slow.
Used --fast --cache 2048.
There are low number of peers.
On SSD it synced fine.

**Comment by agrinevich** [comment]
Same problem: reached 97% and loop from the start. 
Uninstalled and removed blockchain files, installed Mist again, but problem persists.
Windows 10 (Home single language edition), HDD Toshiba DT01ACA100, Pentium G4400, RAM 8GB.

**Comment by dalexeyev** [comment]
geth --fast --cache 2048 also gets stuck and resets to block 0 randomly for me too.
Running on macOS, also using HDD.

**Comment by evertonfraga** [comment]
@fjl do you have a workaround for this?

There are some possible solutions found in other issues:
- https://github.com/ethereum/mist/issues/942#issuecomment-265830474

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
