### ISSUE TITLE
Ethereum Wallet vs Mist

### ISSUE THREAD

**Issue by Wat3v4** [ethereum/mist#2421]
Tried to find but couldn't :-(

What is the haven't used the wallet for a long time and before there was only 1 wallet, now its divided into two O_O 
Whats the difference between them?

Also How can I get access to my regular Ethereum and how to get access to my Ethereum classic? 
Thank you and sorry if its not the place, I just prefer only mist wallet since its the best wallet in the world :D

**Comment by sathishvj** [comment]
https://ethereum.stackexchange.com/questions/2690/what-is-the-relationship-between-mist-and-ethereum-wallet

**Comment by evertonfraga** [comment]
This seems to be the an ethereum classic web wallet: https://classicetherwallet.com/
Please note the *Ethereum Foundation* is not bound by any means with Ethereum Classic nor any of its products/softwares.

Thanks for getting in touch :)
