### ISSUE TITLE
account backup does not create new keystore / UTC-file

### ISSUE THREAD

**Issue by flosan** [ethereum/mist#2422]
Hello there,
A few days ago I created an etherreum account with the ethereum wallet v0.8.10.
Everything worked well (blockchain sync, transfer of ether to my account, backup...)

But since yesterday I cannot backup my account.
When I select Accounts -> backup -> accounts it will just open the Ethereum folder with the geth and keystore folders inside. The keystore folder only contains my last backup UTC-file.

To transfer ether to this account still works, but naturally I would like to backup my account.

Can anyone help me with this issue?

**Comment by evertonfraga** [comment]
Sure! and sorry for the misleading behavior.

Mist now shows you the directory, so you can back it up to your preferred destination: be it an external drive, a trusted backup service, or an SD card, and all...

I'm closing this for now, but feel free to contribute more if you like. Thanks

**Comment by AukeTembrink** [comment]
@evertonfraga I might have misunderstood this ticket, but I think i have got the same problem like @flosan . My Accounts do not get backed up when clicking Accounts -> Backup -> Accounts. It only shows the keystore folder with a single UTC... file in it. That UTC file does not really seem to be related to my Accounts in the Ethereum Wallet. I tried open the UTC file with MyEtherWallet.com and it shows a different Wallet.
So right now it looks like there is no way to backup my Wallets/UTC Files created/imported with Ethereum Wallet 0.8.10

**Comment by flosan** [comment]
@AukeTembrink My problem was that Ithought i could create a backup (keystore) of my "ethereum wallet" as often as I want. I thought I could do so after a transfer of ether there to keep them safe. But it seems like I could only backup (create a UTC file) once to keep the account itself safe, not the ammount of ethers. Anyways, I installed etherium wallet on a 2nd computer, copied the utc file which I created on the first computer in the keystore folder and it showed my account. As soon as the blockchain was up to date it showed all my ether correctly.

**Comment by dfkthf125** [comment]
а у меня вообще перестал комп ревгировать или вирус закинули или еще что то но я уже 5 дней не мог открыть браузер сегодня только через час открылся браузер хром и почта вот и пишу тоже не могу кошелек установить и увидеть счет хотя в браузере вижу но почему то и перестал работать ма

**Comment by AukeTembrink** [comment]
@flosan Was your UTC file located in the keystore folder? I do not really can find the UTC files created for the wallet. My Keystore folder only keeps a wallet i have created manually with geth.

**Comment by flosan** [comment]
@AukeTembrink I think the first time I clicked backup it showed the keystorefolder with the utc-file. now thiking about it might have been ther (the utc) rather than it was created by the backup. Because when I remove it and cliick backup it just opens the keystorefolder but there is no file in it. If I left the utc file I have in the keystore folder it will also just open the folder but will not create a new file or change something to the file that was allready there.
I am not sure if I am off any help...
