### ISSUE TITLE
I'm on testnet - why show transactions from the mainnet?

### ISSUE THREAD

**Issue by stefek99** [ethereum/mist#2425]
# Screenshot

![screen shot 2017-06-04 at 13 50 53](https://cloud.githubusercontent.com/assets/249703/26761745/732afa58-492d-11e7-857c-6f7cc1d8a942.png)

See the red section **TEST-NET**

See the address here: https://etherscan.io/address/0xDf94739Ad0768a29B60F8A0969A84D9640f15D44

It's **mainnet**.

My suggestion would be to not display **mainnet** transaction history on **TEST-NET**?

**Comment by evertonfraga** [comment]
You are correct, thanks for reporting @stefek99.

there've been a tentative pull request to solve that problem in the past, but it didn't went through. You may want to subscribe to this issue: https://github.com/ethereum/meteor-dapp-wallet/pull/276

I'll close this one, as the meteor-dapp-wallet repository is the proper place for this conversation. Thank you.

**Comment by stefek99** [comment]
> NOTE The wallet is not yet official released, can contain severe bugs!

(from the readme)
