### ISSUE TITLE
Still cannot copy and paste on my Mac.

### ISSUE THREAD

**Issue by McGrady00H** [ethereum/mist#2434]
#### System information
``````
Version: `0.8.10`
OS & Version: osx 10.12.3
Node type: `eth/geth(default)`
``````
I have downloaded the latest version of MIST and my os is also the latest one. However, I can not copy or paste anything on the Mist window.

**Comment by McGrady00H** [comment]
I have also tried the Ethereum Wallet. Cannot either.

**Comment by evertonfraga** [comment]
@McGrady00H Hi! Are you using the right button of the mouse, or the keyboard?
Can you please try to copy/paste using `Command+C` and `Command+V`?
