### ISSUE TITLE
ether transfer

### ISSUE THREAD

**Issue by nkwarciak** [ethereum/mist#2438]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files 

I sent ether as a test from kraken to my ethereum wallet application. it appears on my early access android app with the same address but not on my desktop.

**Comment by sathishvj** [comment]
How much is the ethereum wallet synced?  It will show up if it is synced at least as far as the block in which the transaction was picked up.

The android app is using a synced node on their server which is why it shows up there.

**Comment by BitmanLatam** [comment]
You have to reach the end bar so you measure the synchronization ...

![image](https://user-images.githubusercontent.com/21311047/26843243-2ecdaf3e-4ab5-11e7-8a50-f21612ee5959.png)

**Comment by evertonfraga** [comment]
Refer to this small guide. You can also check your balance at a block explorer like Etherscan.
https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide#ether-is-not-shown-in-the-wallet

I'm closing this for now, feel free to reopen should you have any other issue. Thanks
