### ISSUE TITLE
Noob Question - Chain is at 47 gb

### ISSUE THREAD

**Issue by Foen08** [ethereum/mist#2440]
#### System information
``````
Version: `0.8.10`
OS & Version: osx
Node type: `geth`
``````

Hello everybody,

the ethereum blockchain is eating up my storage on my mac. now there are 47gb locked for the ethereum Blockchain. How can i storage this more light? Will there be an update for an lighter amount of storage? I do not want to store the coins on a hot online wallet but in a few month i have no more options to store because my device is full?!

It would be pleasure if you can give some advices or tipps.

Thanks

edit: at gitter they recommended me to use parity?! is this safe and could this be an option for me?

**Comment by evertonfraga** [comment]
Hi @Foen08, there's a sync mode that stores less data than that, but still not being that lean.

For that, you could delete/move the `~/Library/Ethereum/geth` directory, and resync the mainnet using:
`geth --fast --cache=2048`

I did that two weeks ago and I have now 33GB of data, around 66% of the size of yours. In the future Mist will make use of Light Client, with a really small footprint on your computer.

Parity is also an option, and they have a Mist compatibility mode `(parity --geth` as far as I can remember. Feel free to try, and post here your impressions.

**Comment by PatchRanger** [comment]
Relevent to #2375.

**Comment by evertonfraga** [comment]
We've enabled the Light Client on Mist 0.9.1, under Develop menu. Please note this integration is still in beta phase.

Thanks for reporting.
