### ISSUE TITLE
Sent 2 ETH to address but not done downloading 

### ISSUE THREAD

**Issue by ericg320** [ethereum/mist#2443]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by sathishvj** [comment]
check that the 2ETH has actually been sent on etherscan.ion/address.

can you not export the account using Accounts->BackupAccounts.  If you have that key json file and you remember your password, you should be able to reopen it on any machine.

You can also view/use the account on MEW using the key file.

**Comment by BitmanLatam** [comment]
I did not resee the eth in my wallet Mist.

To me the same happened to me, I did not get to the wallet of ether mist, the transaction appears in my wallet jaxx and in the etherscan.io/address. But not in the ether mist wallet.

TxHash:
0xe6918bcbd51eef19c02489c2cf45d6d6834ed2eb6a057666a0432f1996736786

Block Height: 3825304 (4882 block confirmations)

![image](https://user-images.githubusercontent.com/21311047/26839183-e946b986-4aa7-11e7-8fb8-815c49903981.png)


Could you help me please

**Comment by sathishvj** [comment]
That's the target account. 
 https://etherscan.io/address/0x076206fbd6e246739606d50e52c64421014e4d2b

Your transaction hex shows that you haven't yet transferred 2 ETH there, but 0.404 ETH and that shows up.

Your Mist node is still a long way from syncing.  From the screenshot, it looks like at least 25% is left to sync. The 0.404 you sent will show up when it is fully synced.

**Comment by evertonfraga** [comment]
You are correct, @sathishvj. As your computer uses a local blockchain database to display data, it must be synced in order to show updated data.

I'll close this for now, if you need anything else, please reopen the issue.
