### ISSUE TITLE
Sent bitcoins to expired address

### ISSUE THREAD

**Issue by libertyhunter** [ethereum/mist#2444]
I'm really freaking out because I sent all my bitcoin to an address that I didn't realise was expired and it has already confirmed how do I get my bitcoin back?  The address was 1ET7HfNn67k3rEffhEngsWWtCmRKLWqby4 and the transaction ID is: 6186a91463264f3e0b475dd4386d95a995d22552e939e63690109fcb396dec0b-000

**Comment by sathishvj** [comment]
Are you in the wrong place with this question?  Mist is used for ethereum and not bitcoin.

**Comment by libertyhunter** [comment]
Yes. Sorry I didn't explain correctly I used shapeshift to try and transfer my bitcoin into ethereum but sent it after the time had expired so it was to an expired address.  I have tried getting in touch with shapeshift but they have not replied yet.  Is there any hope of getting my bitcoin back?

**Comment by evertonfraga** [comment]
Hi @libertyhunter in that case the Shapeshift service is the right touchpoint for you. They usually respond within 24h.

I'm closing this issue, if you need anything, just reopen here. cheers
