### ISSUE TITLE
I did not resee the eth in my wallet Mist.

### ISSUE THREAD

**Issue by BitmanLatam** [ethereum/mist#2446]
To me the same happened to me, I did not get to the wallet of ether mist, the transaction appears in my wallet jaxx and in the etherscan.io/address. But not in the ether mist wallet.

TxHash:
0xe6918bcbd51eef19c02489c2cf45d6d6834ed2eb6a057666a0432f1996736786

Block Height: 3825304 (4882 block confirmations)

Could you help me please

![image](https://user-images.githubusercontent.com/21311047/26839506-d461b47a-4aa8-11e7-92a3-0894300eef28.png)

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by sathishvj** [comment]
I've answered this in #2443

**Comment by evertonfraga** [comment]
Hi, this is mostly an out-of-sync issue. Make sure you are in sync. Look at the bottom left corner of your window.
I'm closing this for now, please feel free to reopen if needed.


![image](https://user-images.githubusercontent.com/47108/26843208-d20fe436-4ac5-11e7-9fec-1fa91b3505bc.png)
