### ISSUE TITLE
from new installed ethereum wallet send 1 BTC with shifty, no eth incoming

### ISSUE THREAD

**Issue by Begru** [ethereum/mist#2449]
Yesterday I installed the ethereum wallet, make passwort, let them fully synchronised. All looks easy. Then I choose the shifty to get eth. Send 1 BTC to the adress what is showing. After this the field Awaiting Deposit shows green. That was it. Since them no eth comes to my
[Ethereum Wallet.zip](https://github.com/ethereum/mist/files/1055967/Ethereum.Wallet.zip)
 wallet. Now I choose the help button on shifty and come now to here.
I saw where I send the btc, that a pool get this btc. 
What can I do next?
What files you need?

Begru

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx Win10 64bit
Node type: `eth/geth(default)`1.6.5
Ethereum Wallet 8.10
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by sathishvj** [comment]
If you just installed ethereum-wallet/mist, you need to let it sync.  It's only when it is pretty much entirely synced that your client (mist/ethereum-wallet) will update because your transaction is on a recent block.

You can still however check the balance on the ethereum address by checking it on the ethereum blockchain browser: etherscan.io/address/0x... put your address at the end.

**Comment by Begru** [comment]
I check it on the etherscan.io/address/0x..., but it shows me 0 (Zero ) eth. Same on my wallet.
my ethereum-wallet/mist are sync,, I can see the present node and the wallets are open. But where are my eth what I have changed from btc to eth with shifty?

**Comment by sathishvj** [comment]
In that case the transaction has not reached the Ethereum network and you should contact whichever exchange you used.  (and you could probably close this issue here)
