### ISSUE TITLE
sync stuck on the last few blocks.. downloading infinite chain structure

### ISSUE THREAD

**Issue by ricardiinhu** [ethereum/mist#2453]
Sorry if i´m asking a repetitive question! 
but i´m trying to sync my ethereum wallet for more than a week, and now that left only few blocks to finish, my ethereum wallet is downloading an infinite chain structure and i guess it will never end...
what should i do? 
thanks

**Comment by DAlperin** [comment]
Hello I am new to ethereum and I am trying to sync for the first time. And whenever I get near the end there are more blocks it is trying to download... Is that normal?

**Comment by DAlperin** [comment]
Apologies for my previous now deleted comment. I stupidly commented on the wrong repo. Sorry

**Comment by 2001blader** [comment]
Having the same issue. I'm trying to restart it now, maybe that will get me through this block.

**Comment by xtensa** [comment]
Have the same issue here. Is it normal? Anyone can comment? Is it normal? I deleted chaindata and started fresh sync with --fast option but still have the same result. Now I have more then 14mln on chaindata counter and it is growing.

**Comment by positivedefinite** [comment]
Encountered the same problem.
![image](https://user-images.githubusercontent.com/22936927/28490588-1c9f10e4-6ede-11e7-954e-c11fadd079e9.png)
![image](https://user-images.githubusercontent.com/22936927/28490589-23395cb6-6ede-11e7-9b61-b1e9dba05f79.png)
Chain structure download is stuck in a runaway loop.

Windows 10

Typing geth in cmd yields:

![image](https://user-images.githubusercontent.com/22936927/28490604-85537a8a-6ede-11e7-9fda-a71ba99160d8.png)

**Comment by ricardiinhu** [comment]
I solved it by giving up and using metamask, if helps you.

**Comment by emperor1412** [comment]
Mine still downloading chain structure at 11 millions

> I solved it by giving up and using metamask, if helps you.

@ricardiinhu  How can you test smart contract with metamask ??

**Comment by Jacke** [comment]
Same error, now it's 15 millions for chain data

**Comment by Klapeyron5** [comment]
![2017-08-01_13-03-18](https://user-images.githubusercontent.com/8626758/28821479-42feb1ee-76be-11e7-8096-4aa4995e4f5a.png)

the same problem.

**Comment by markmcgookin** [comment]
Same here on Mac

**Comment by danchismanberry** [comment]
Same problem here as well. I've been trying for about 3 weeks now, this is my second attempt, this time with fast sync. It's frustrating me beyond belief, to the point where I'm considering not getting involved with Ethereum full stop. I wonder how many other people have given up due to this. Not only this but there seems to be no valuable help from community in forums. I don't want to use myetherwallet, I want to complete the task I have been trying to do for th past 3 weeks!!

**Comment by peablog** [comment]
same issue on mac ..

**Comment by givacoin** [comment]
Same issue on Mac,linux,and windows.  Tried ssd, tried point to external drive.  Tried wifi as well as directly through ethernet cable.  Tried deleting chain data and resync, tried --fast as well as directly through the wallet. Just cannot get past the last 80-20blocks fluctuating.  Also tried moving chain data off to other machines.  New wallet or importing my keystone doesn't make a difference.  Rinkeby testnets is fine.  Just main net having issues. Same as everyone else. This is super frustrating.  I don't think devs have a solution to this.  

Any other ways to deploy contracts to main net without using eth wallet?

**Comment by leventsoner** [comment]
Same problem, chain structure is at 7 million and still goes on. Anybody reachs to the end?

**Comment by Sovxx** [comment]
Same problem with Ubuntu (8Gb RAM, SSD)...

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Comment by defaye** [comment]
@evertonfraga could you care to give any comment on whether this is an actual bug or if this is just impatience from users? I'm on block 4,897,500 and the chain structure is 17,090,000+ 17,100,000+ in a runaway state as well. It isn't helpful to close an issue offering a false solution without any explanation. Some users want to use the standard client, what do they do then?
