### ISSUE TITLE
Windows 10, can't get software to sync/boot, tried multiple fixes...

### ISSUE THREAD

**Issue by livejustine** [ethereum/mist#2455]
#### System information
``````
Version: `v0.8.10`
OS & Version: Windows 10 64bit
``````

I cannot get the "Ethereum Wallet" application to run on my PC. It gets to the point of syncing, then gets about a third of the way and gets stuck each time.

I have of course tried reseting the PC and running it fresh multiple times. I have tried both the 32bit and 64bit versions. I have tried running them from my SSD and traditional HDD, both of which have plenty of empty space. I have tried running "as administrator" and I have added exceptions in the Windows Firewall. I thought maybe I was being impatient, but I have literally left it for over 10 hours last night whilst sleeping and it still didn't move.

Does anyone please have any suggestions as to why this may be?

My PC specs are pretty high, i7 6400, 64GB RAM, GTX Titan X 12GTb, Fast PCI-E SSD... Windows 10 64 bit pro version fully legal and all up to date.

Many thanks in advance for anyone who can fix this, been into both mining and buying and hodling Ethereum for a while now, have many years experience in programming various languages, and want to get a headstart in Solidity.

**Comment by luciancerbu87** [comment]
I have the same issue, in a couple of hours I will make a transaction to my wallet, I'm very curious if it gonna work.

**Comment by CCCole** [comment]
Same issue. Sync starts and then stops about 1/3 of the way through on Win10. Deleting chaindata and restarting causes the wallet to go through syncing from the beginning and then stops at block ~800,000 (varies, sometimes it makes it to 900,000). I also tried leaving it on overnight, but the block count did not budge.

**Comment by clipartinc** [comment]
Same issue here. Please help I have transactions coming to this wallet address and I can't access it :\

**Comment by ch3mtrailinhaler** [comment]
The Windows Wallet is a joke. Has been since the first version. I would give up, dual boot Ubuntu, and then you'll have zero issues. Sometimes, somewhere, the Ethereum Team will get a REAL programmer to do the Windows side of things. That will be a huge step forward for them and the currency. It will never get the full attention like Bitcoin until that happens.

**Comment by livejustine** [comment]
Thank you for the response. I was considering dual booting Ubuntu anway as I was going to use it for mining (winodws 10 with my graphics card I have to fiddle with degraded drivers etc, and even then its janky). Annoyingly, for some reason I can't get this PC to boot from USB (no matter what I set in the bios, it always boots from my PCI-E SSD first... weird). When I have more time I will fiddle with it more, or I was considering just having a dedicated Ubuntu machine for mining etc anyway, I have several old PCs hanging around. Really a shame I haven't had a "proper" respnse to this question though, I would have thought something like this would be a high priority fix or that I was doing something obviously wrong...

**Comment by ch3mtrailinhaler** [comment]
I had the same issue with my USB stick, on two machines. I finally resorted to the OLD SCHOOL burning of a DVD and now it works like a charm. I'm building a new ZCash Rig, and I decided to just buy a stupid DVD drive so I don't have to play the USB Stick won't work game. If you want to do Windows 10, checkout the keys at www.scdkey.com ... I've bought 6 or 7 now and they call worked fine and are legit. 

I like Ubuntu for accessing my wallet, but find the controlling of multiple GPUs a lot easier in Windows as Claymore, Genoil and others are just so easy to use in Windows. Plus, the overclocking with AMD Afterburner has helped me suck an extra 10% out of each card.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
