### ISSUE TITLE
Synchronisation Blockchain takes around four days and is still running

### ISSUE THREAD

**Issue by phonkie** [ethereum/mist#2460]
Hello,

i try to synchronize the blockchain on my mac since four days and it is still running.
Beside this the blockchain has already more then 45gigas.

Can someone give me an idea if this is still ok?

please let me know

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
