### ISSUE TITLE
How long for sync to take place

### ISSUE THREAD

**Issue by harrowsmith** [ethereum/mist#2462]
I sent a bitcoin to my ethereum wallet. 16 hours later my Main account (Etherbase) still shows zero. 

I went to the etherscan and put in my address. To my relief I can see it is there but I really don't know what to do next, if anything. Will my Ethereum wallet show my balance at some point?

Can I put my ether into my ethereum wallet on Coinbase?

**Comment by slimcdk** [comment]
You can't simply not just send one type of currencies to another. They have their own blockchains.

**Comment by harrowsmith** [comment]
Ok thank you. But how can I now use the ethers?

**Comment by slimcdk** [comment]
Find someone who wants to trade them. Like you do with real money,

**Comment by harrowsmith** [comment]
Unfortunately, I still don't know how to trade them. If they're not in my wallet then how do I sell them?

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
