### ISSUE TITLE
Ubuntu: libgconf-2.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by jaafit** [ethereum/mist#2469]
#### System information
``````
Version: `0.8.10`
OS & Version: linux
Node type: [default from ethereumwallet install]
``````
I'm on Ubuntu 16.04 64-bit and I'm having trouble running ethereumwallet.  

Steps: 
* Install .deb 
* cd /opt/Ethereum Wallet
* ./ethereumwallet

Expected: ethereum wallet runs

Actual: ./ethereumwallet: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

Tried: "sudo apt-get install libgconf-2-4" 
Result: "libgconf-2-4 is already the newest version (3.2.6-3ubuntu6)."

**Comment by jaafit** [comment]
Whoops, I was using 32-bit wallet with 64-bit OS.  All good now.

**Comment by crclayton** [comment]
Yep, also installed a 32-bit software with a 64-bit OS. Thanks!
