### ISSUE TITLE
Ethereum-Wallet-win64-0-5-1 Crash on Startup

### ISSUE THREAD

**Issue by Flatulentfox** [ethereum/mist#247]
I was able to run a much earlier version of Mist. I turned off all firewalls. Any ideas? Thanks

![ethereum crash](https://cloud.githubusercontent.com/assets/17662533/13545364/e30be7cc-e256-11e5-83ca-28b2c299e92f.png)

**Comment by Doppelbock42** [comment]
I have one of these too.

![node crash](https://cloud.githubusercontent.com/assets/17707735/13576492/d2871884-e442-11e5-9ff7-b4a3a9c26a6d.JPG)

**Comment by frozeman** [comment]
@fjl @karalabe thats the NAT issue right?

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
