### ISSUE TITLE
SVP/Light client mode

### ISSUE THREAD

**Issue by pyalot** [ethereum/mist#2472]
It would be a good idea to include an SVP mode with the wallet so that users don't have to wait for a d/l of the entire blockchain before being able to use the wallet. Relevant wiki entry: https://github.com/ethereum/wiki/wiki/Light-client-protocol

**Comment by PatchRanger** [comment]
Thank you for suggestion! Should be closed in favor of #2372 - as it is explained in detailed manner.

**Comment by evertonfraga** [comment]
Duplicate of #2372
