### ISSUE TITLE
Uncaught exception when making account

### ISSUE THREAD

**Issue by TTN-** [ethereum/mist#248]
Hi all,

Mist crashes when I try to make an account after I have entered my passphrase.
OS: ubuntu 14.04 x64
I'm running from the unzipped release 0-5-0 and 0-5-1 both give the same error. I have the required dependencies installed but it didn't help. Here is the error message:

```
username@mypc:~/Scripts/Ethereum-Wallet-linux64-0-5-0$ ./Ethereum-Wallet 
CONNECT to IPC PATH: /home/username/.ethereum/geth.ipc
CONNECT to IPC PATH: /home/username/.ethereum/geth.ipc
NODECONNECTOR ERROR { [Error: connect ECONNREFUSED /home/username/.ethereum/geth.ipc]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/home/username/.ethereum/geth.ipc' }
Node type:  geth
Network:  main
Start node from /home/username/Scripts/Ethereum-Wallet-linux64-0-5-0/resources/node/geth/geth
Stopping nodes...
Starting geth node...
Saved standard node "geth" to file: /home/username/.config/Mist/node
Saved network type "main" to file: /home/username/.config/Mist/network
Geth connection FOUND
Checking node sync status...
Time between last block 285s
Sync finished, starting app!
Loading Interface at file:///home/username/Scripts/Ethereum-Wallet-linux64-0-5-0/resources/app.asar/interface/wallet/index.html
UNCAUGHT EXCEPTION [TypeError: Cannot read property 'send' of null]
Closing Socket  8
SOCKET 8 DESTROYED!
Closing Socket  10
SOCKET 10 DESTROYED!
Stopping nodes...
```

**Comment by TTN-** [comment]
I didn't get the account creation intro on linux like I did when I ran it on windows 7. I have a suspicion this may have something to do with the fact that I have geth already installed and an account made in it.

**Comment by TTN-** [comment]
Solved by deleting my ~/.ethereum folder. I didn't have any valuable data in there so its ok, but somehow having geth installed first cause mist to crash.

**Comment by TTN-** [comment]
No its still fucked up. Take a look:
![screenshot from 2016-03-06 09 43 58](https://cloud.githubusercontent.com/assets/6019316/13550327/0f11815e-e380-11e5-8518-19dceb88b0e1.png)

It has always looked like this for me.

**Comment by hauweg** [comment]
same problem using linux manajaro:

Loading Interface at file:///usr/share/mist/resources/app.asar/interface/wallet/index.html
UNCAUGHT EXCEPTION [TypeError: Cannot read property 'send' of null]
Closing Socket  8
SOCKET 8 DESTROYED!
Closing Socket  10
SOCKET 10 DESTROYED!
Stopping nodes...

deleting all related folders and new installation doesnt help. 

another person with same os has same problem :(

**Comment by hauweg** [comment]
directly after i enter a passwort for account creation, mist crashes with the code above.

but when i check my keystore folder, i can see that an account was created. (UTC-....)

when i choose this UTC file to "open with" mist, than mist opens, but does not show any account ...

**Comment by cameel** [comment]
Same here. Arch Linux x64. Crash on account creation, `UTC--...` files get created in `~/.ethereum/keystore/`.

Tried both 0.5.1 and building directly from `master`.

**Comment by hauweg** [comment]
i tried to new version 5.2. and wanted to run that script, that was adviced for the "white wallet page error", but it doesnt work, since all mist stays white and empty, als after choosing: menu > develop > toggle deveolper tools > wallet UI

is there any way to enter the script in the linux comand line?

**Comment by roland-c** [comment]
Same problem here on Ubuntu64 Trusty trying to run Ethereum-Wallet-linux64-0-5-2.
I get this error: 
Loading Interface at file:///opt/Ethereum-Wallet-linux64-0-5-2/resources/app.asar/interface/wallet/index.html
UNCAUGHT EXCEPTION [TypeError: Cannot read property 'send' of null]
Closing Socket  8
SOCKET 8 DESTROYED!
Closing Socket  10
SOCKET 10 DESTROYED!
Stopping nodes...
IPCSOCKET 8 CONNECTION ENDED undefined false
SOCKET 8 DESTROYED!

**Comment by hauweg** [comment]
finally it helped to start the programm (only if installed through pacman) via command line with this command:
`
**mist --ignore-gpu-blacklist**`

after that, i could see all the accounts which i had opened while all the crashes.
good luck fellows :)

**Comment by cameel** [comment]
Thanks! Works for me as well.

So... why is the blacklist causing a crash?

**Comment by roland-c** [comment]
Bingo! It works on my Ubuntu box with an Nvidia card now. Previously I used Nouveau as video driver which produced an 'empty screen' screen when Mist was started, also with the --ignore-gpu-blacklist switch. Apparently the content within the screen was not rendered properly and not visible, it was there though.  
After installing the Nvidia driver and blacklisting the Nouveau driver, which must be done in order to get the Nvidia driver functioning, I started Mist including the --ignore-gpu-blacklist switch and voila there it is, a functioning Mist. 
Concluding: a proper graphics rendering on Linux boxes with Nvidia card AND onboard graphics card (Nouveau) is needed for Mist to display. 
Thanks for sharing your trouble here folks! HTH.

**Comment by cameel** [comment]
> Concluding: a proper graphics rendering on Linux boxes with Nvidia card AND onboard graphics card (Nouveau) is needed for Mist to display. 

For the record, I have an AMD card (AMD Radeon HD 7730M + Intel HD Graphics 4000) and I'm using the open-source `radeon` driver. So apparently it's not just nVidia.

**Comment by TTN-** [comment]
Fantastic work @hauweg. It works just fine now. I have intel HD4000 and a blacklisted switchable AMD gpu that won't play nice with Ubuntu which is why its it is blacklisted and I use the HD4000 instead.

**Comment by luclu** [comment]
Make sure to have a look over here: https://github.com/ethereum/mist/issues/599
I will close this as duplicate for now.
