### ISSUE TITLE
Bitcoin transaction never went through due to "syncing" and now I lost $50

### ISSUE THREAD

**Issue by TopCatDaSuperVillain** [ethereum/mist#2488]
Ok guys. 1st off I just recently started investing in BTC, but have been buying/spending them for a while now. I'm extremely interested in Ethereum because of it's upside, so I installed this, transferred probably a little more than $50 in BTC to be converted into tokens (Is that the proper term) and now I'm stuck. Ig I should of waited for all the blocks to be installed but the program was working fine so I figured it was just some update or something. I've been stuck on 3-4% for hrs now and I'm scared I just lost $50. Please help me, I would like a refund or at least a diagnosis of the problem, then the BTC to be converted into the proper amount of tokens, 1 of the 2 please. Thank you guys. I have screenshots for verification, you guys can verify manually too, it says the deposit was received.

btw I forgot to put a return address, but I do have 1,

![ethereum refund](https://user-images.githubusercontent.com/29348497/27012983-d1f1c4e2-4ea8-11e7-9108-e5c75d4260fd.png)
![etherreum refund 1](https://user-images.githubusercontent.com/29348497/27012984-d1f980e2-4ea8-11e7-8bf3-9a28bfdcb633.png)
 Update: I left my laptop on all night and the "syncing" still got nowhere I'd like a refund. I'll just make a different Ethereum wallet, still going to support the movement though, can anybody help?

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment]
You haven't lost your money. It'll be sitting on your account, and will be accessible as long as you have the private key.

We have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
