### ISSUE TITLE
"eth" node wallet (Mist) stores

### ISSUE THREAD

**Issue by dobcrypto** [ethereum/mist#249]
Where i can find and back my "eth" node wallet(.json) from mist?
c:\users\app data\roaming\Mist - nothing.
c:\users\app data\roaming\Web3\keys\ - .json there, but my master pass don't decrypt it(on myetherwallet.com/#view-wallet-info), why?

With "geth" node all is good, i find file for backup and my master pass decrypt it on myetherwallet.com/#view-wallet-info site.

But my Eth in "eth" node wallet, i need access to it, but Ethereum-Wallet-win64-0-5-1 don't work with "eth" node. sad...

**Comment by luclu** [comment]
@dobcrypto make sure to use the latest version 0.7.4.
You are right about the path: `%AppData%\Roaming\Web3\keys`
Try to stick to `geth` for now: https://github.com/ethereum/mist/issues/607
Also have a look here: https://github.com/ethereum/mist/issues/669 
And try to copy the `json` over to geth's keystore.
I will close this for now.
