### ISSUE TITLE
no incoming BTC

### ISSUE THREAD

**Issue by organicnumbers** [ethereum/mist#2495]
I transfered some BTC to my recently created Ethereum Wallet on shifty. Shifty says "Awaiting Deposit" for hours. Please help me

edit: I saw the minimum desposit is a little highter than my payment. Too bad the window with that information was too small at the time.

**Comment by sathishvj** [comment]
This is a question that should be asked to Shifty.

**Comment by organicnumbers** [comment]
I also asked them the questions.

**Comment by sathishvj** [comment]
The Mist/Ethereum-Wallet team won't have any answers for this.  If you want to check if the target ethereum address received the ether, you can check at etherscan.io/address/0x... Put your address at the end.

**Comment by organicnumbers** [comment]
No income :(

**Comment by evertonfraga** [comment]
I'm afraid we can't help you on this @organicnumbers :(

closing this for now, if you need anything else, hit us here.
