### ISSUE TITLE
Transfer- ETH on no Sync ETH Wallet to another Wallet ?

### ISSUE THREAD

**Issue by IX902** [ethereum/mist#2502]
Dear Community,
is it Possible to Transfer my ETH which on my ETH Wallet to a another Wallet ? 

My ETH Wallet is not sync at the moment and Im not very happy with it. Only Problems and no Support.
I already try all Sync Guides and noone help.

So i want to transfer them all.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
