### ISSUE TITLE
Rounding problems on transfer amount calculations (win64-0.5)

### ISSUE THREAD

**Issue by piotrmb** [ethereum/mist#251]
I noticed that there are issues with transfer amount calculations. It is a bit scary, as it looks like you are using floating point numbers for this calculations - see attached screen-shot. Printed value itself is not a big case, but it seems to actually stop the transaction from execution.
![fee](https://cloud.githubusercontent.com/assets/17673547/13547796/04fe4b3e-e2e0-11e5-96a4-f47158db43d9.png)

**Comment by eyecikjou567** [comment]
I encountered this issue too, tho I do find this very worrying.

Financial calculations with floats? It's not exactly easy to find a number to transfer that isn't encountering this issue, so I can be safe to know that the amount specified gets transferred and not the slightly wrong float value.

**Comment by piotrmb** [comment]
@eyecikjou567 
I would say it is quite common situation - for example 0.1 and all of its multiples. But this is not the case - using floats for financial calculations shows lack of understanding in computer science fundamentals. This is something what definitely should not appear in this kind of project.

**Comment by alexvandesande** [comment]
We are not using floats, these are integer values with wei as base. I'll look into it.

**Comment by frozeman** [comment]
This is purely a display issue, will fix it.

**Comment by frozeman** [comment]
this will be fixed in the next version.
