### ISSUE TITLE
Ethereum nightmare key not recognized

### ISSUE THREAD

**Issue by Jack24244** [ethereum/mist#2512]
Not thinking I copied my mist and Ethereum folder's and installed a new O.S. realizing quickly when  I tried to bring Ethereum back from the folder that my keys weren't there.. I thought I had backed up the keys but they weren't on my External HDD.. SO I used a data recovery service and found my keys! 

Size for size they match perfectly with my newly made keys I believe it's 491kb (not in front of me) but as I soon realized Ethereum client can't recognize my recovered UTC-DATE-Wallet ID json file! When opening a good recently made key in a test file I quickly realized that my recovered key appears to be encrypted with funny shapes.. The good key shows simple letters and numbers.. I know the password to the key... 

Am I dead in the water here?

Tags: Ethereum keys import won't read UTC json

**Comment by evertonfraga** [comment]
First of all, I suppose you have moved your keys to the keystore directory, right?

Can you try to unlock your account using `geth`?
run `geth console`
then `personal.listAccounts`
see if your account appears there.

for more information, head to the `geth` repository
https://github.com/ethereum/go-ethereum

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
