### ISSUE TITLE
no eth in wallet sent 24 hr ago 

### ISSUE THREAD

**Issue by gnikomoy** [ethereum/mist#2519]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).
![image](https://user-images.githubusercontent.com/19855796/27162989-7d0cebee-5152-11e7-904b-d5be10436c3c.png)
where do it go? how much moneys duz i gets.

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files 
 
![image](https://user-images.githubusercontent.com/19855796/27162989-7d0cebee-5152-11e7-904b-d5be10436c3c.png)

**Comment by sathishvj** [comment]
With Mist/Ethereum-Wallet you are running a full local node that has the entire blockchain.  Your transaction (if it went through) is in a block way towards the end.  Therefore the entire node has to sync before your transaction will show locally.  

However, you can still check the status on the account on an online ethereum blockchain explorer like etherscan: etherscan.io/address/0x... Put your address at the end.

**Comment by gnikomoy** [comment]
thanks for sorting that out

**Comment by sathishvj** [comment]
You can close this issue if it is resolved.

**Comment by gnikomoy** [comment]
yes i can 

new i could
