### ISSUE TITLE
"Can't estimate gas" label displayed incorrectly (win64-0.5)

### ISSUE THREAD

**Issue by piotrmb** [ethereum/mist#252]
I have two accounts right now in Mist - on one of them there is around 0.5eth, on the second one around 21. When I want to do transfer from account with 21eth from time to time label is displayed as on screen-shot below. It looks like wrong account balance is checked.
![gas_usage_label](https://cloud.githubusercontent.com/assets/17673547/13547920/6903d95c-e2e3-11e5-9723-4f7ed209caf2.png)

**Comment by luclu** [comment]
This happened because the Etherbase account was checked for the balance of at least 1 Ether.

Seems to be resolved - tested with 0.7.4.
