### ISSUE TITLE
Not able to sync after days and days of trying

### ISSUE THREAD

**Issue by Masterfellow** [ethereum/mist#2524]
#### System information
``````
Version: `10`
OS & Version: windows
Node type: `geth`
``````

#### MY ISSUE 
After sending my money to Ethereum wallet, I read that the wallet needs to be synced up first. After days and days of trying to sync it up, I gave up. 
I had to quit the program and run it again multiple times so it's not stuck at one blockchain. 
Very bad experience considering other wallets with much better functions don't need such tinkering.

**Comment by sathishvj** [comment]
If you are using a full node app like Ethereum Wallet, you will have to wait for it to sync.  Meanwhile, make sure you back up your keystore file and remember your password.  Using the keystore file, you can still use it on an online service like myetherwallet.com to transact.

For issues with syncing, you can check a few online docs:
https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide
https://theethereum.wiki/w/index.php/Ethereum_Wallet_Syncing_Problems

Would suggest that you be connected to a fast network, that you are not behind a proxy, backup your keystore files and then remove existing chaindata and start again.

**Comment by Masterfellow** [comment]
I know that I have to wait, but that's my main issue. I already deleted the whole wallet so there's no point, but thank you. This may help someone in the future, as I see many people with this problem. 

Unfortunately I can't do anything with my connection, I have the best package which my ISP offers (ADSL 13/1 - yes, that's bad). Also, I'm not using any proxies.
