### ISSUE TITLE
Ethereum node needs to sync - stuck

### ISSUE THREAD

**Issue by Juicyhf** [ethereum/mist#2526]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files 
 

http://prntscr.com/fk8xnd

This is what it shows, and it get stucks there. I can close the app and restart and it works a little more then freezes again.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097

**Comment by dfalzetti** [comment]
geth kept failing every 10 - 15 minutes so in windows i created a sync.cmd file with the following and that took care of it.



C:
cd "C:\Users\Dan\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked"

:loop

 %@Try%

 call "geth.exe" --fast --cache=512 --datadir="D:\Ethereum-Wallet-win32-0-9-3"


 timeout 2

%@EndTry%
:@Catch
goto loop
:@EndCatch

goto loop
