### ISSUE TITLE
Wrong Checksum

### ISSUE THREAD

**Issue by turnkit** [ethereum/mist#2529]
The Mist-macosx-0-8-10.dmg SHA-256 checksum for the files available right now show:
3F85562AABF4B6FFF060CA67F61E3FF4223C9F3C1FDBB9969CBA62F817876D8D

I got that same result from command line: 
openssl sha -sha256 Mist-macosx-0-8-10.dmg
and from QuickHash.

https://github.com/ethereum/mist/releases shows the checksum should be:
Ethereum-Wallet-macosx-0-8-10.dmg
36c77908b9ec36c3aed41d0d161bbe6c4569379c96e6390f7fa405fa78d3aaea

Is it hacked?  Is it safe?

The Mist-macosx-0-8-9.dmg
3d09306f8e53e315da73571d52adf15adfd4c30e43a8b4251099bc5f7aeda986 
checksum IS CORRECT.

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by gk95** [comment]
Checksum of Mist-macosx-0-8-10.dmg is also correct. Ethereum-Wallet-macosx-0-8-10.dmg and Mist-macosx-0-8-10.dmg are different things. According to the [release page](https://github.com/ethereum/mist/releases) checksums should be:
- Mist-macosx-0-8-10.dmg: 3f85562aabf4b6fff060ca67f61e3ff4223c9f3c1fdbb9969cba62f817876d8d
-  Ethereum-Wallet-macosx-0-8-10.dmg: 36c77908b9ec36c3aed41d0d161bbe6c4569379c96e6390f7fa405fa78d3aaea
