### ISSUE TITLE
"Wrong password" label displayed for corrupted account file (win64-0.5)

### ISSUE THREAD

**Issue by piotrmb** [ethereum/mist#253]
As I used quite old Ethereum client before, I had to manually change account files in order to import them to Mist. It appeared that during this change i did small mistake - I forgot about comma between address value and "Crypto" label in JSON file. I did not notice it because account is displayed correctly in Mist. But when I tried to send some money from this account I got "Wrong password" message.

I did it on console with geth: geth.exe --unlock account_address
After 3 reties it gave me much more informative message:
Fatal: Unlock account 'xxxxxxx' (xxxxxx) failed: invalid character '"' after object key:value pair

It would be nice to improve feedback in Mist a bit in that case, for example "Corrupted account file" or similar instead of "Wrong password".

**Comment by luclu** [comment]
Please check if this behaviour still occurs on version 0.7.4 / geth 1.4.4 and report on the outcome!

**Comment by luclu** [comment]
I will close this for now, but will stay here to assist you in problems regarding Mist/geth.
Also make sure to try this update of #669:
> if you still can't unlock your account try this service: https://www.myetherwallet.com (they implemented a "wallet viewer" following the official wallet-specs; it's client-side; source-code)
