### ISSUE TITLE
<<Solved it>> thread #1025 revisited 'Unhandled trie error: Missing trie node'

### ISSUE THREAD

**Issue by dgn127** [ethereum/mist#2530]
#### System information
``````
Version: `0.8.10`
OS & Version: osx
Node type: `geth`
``````
I tried to post this in the "wallet stops syncing ('Unhandled trie error: Missing trie node') #1025" thread but i just noticed it was closed and I couldn't figure out where else it would fit, sorry!

I need to do this but my chaindata file is now in the geth folder should I still delete it? I am using the Ethereum Wallet Version 0.8.10 and I can't synch. The actual error from the log is:

INFO [06-15|20:05:06] Block synchronisation started
ERROR[06-15|20:05:08] Unhandled trie error: Missing trie node 3a1e82bc8304455d5afd30f690208cfbf2b849764f125f7fd76fb5259423597d

I really wanted to fix this myself, but it's been three days since I sent some Ether to jump on the ICO bandwagon, and I haven't had any confirmations because I can't synch.

Any help would be appreciated.
Thanks

![walletsplash](https://user-images.githubusercontent.com/6111221/27209281-15224aa4-5208-11e7-98a0-d1375f892855.jpeg)
![appsynchprogressbar](https://user-images.githubusercontent.com/6111221/27209283-1745d53a-5208-11e7-90a9-c534dffaadfc.jpeg)
![walletabout](https://user-images.githubusercontent.com/6111221/27209285-1dfafeb4-5208-11e7-8bb9-64ab56c72b33.jpeg)
[node.log.zip](https://github.com/ethereum/mist/files/1079570/node.log.zip)

**Comment by dgn127** [comment]
Okay, I made a copy of the _chaindata_ folder then renamed it. I started the Wallet again and now it's downloading the block and chain structure. So maybe I did solve my own problem. I'll add to this post if it works.
Thanks!

**Comment by dgn127** [comment]
Okay, I solved it. It downloaded the whole chain again and it did keep and confirm the transaction. I was a little nervous because it stated my wallet balance was 0.00 as it was downloading, but when it finished all of the numbers matched up. The quickest way to find the "chaindata" folder is to retrieve your log file by clicking on the "show log file" under the "Develop" tab and navigate backwards through Finder as the Library folder is hidden.

Thanks!

**Comment by Niknakflak** [comment]
I've encountered this a living ton while developing a DApp, if anyone runs into this problem, your literal best course of action is to just download the entire blockchain again.

It sucks that that's all I've figured out how to make it fix itself, but trust me, that's your best bet, and if anyone else out there has encountered this more and actually knows a better way to fix this issue, please ping me
