### ISSUE TITLE
BTC transferred but never arrived in Ethereum wallet. Wallet still loaded though. Can I get my $100 back?

### ISSUE THREAD

**Issue by wgwine** [ethereum/mist#2531]
#### System information
``````
Version: `0.8.10`
OS & Version: windows
Node type: `eth/geth(default)`
``````

I ran Ethereum wallet for first time and it forced me to add some ETH to run, so I transferred like .03 BTC to the address it gave me. It said the transaction completed and the wallet opened, but there is no ETH in it. Whats the deal?

[Screenshot from Electrum](http://i.imgur.com/NMY1Ndh.png)

[Screenshot of Ethereum wallet](http://i.imgur.com/GFrBojY.png)

TransactionId from Electrum: 409b6cf5b46eac7d16262909657d70cd98496cce28c4a7ddc008ff5e700d19cd

Message Copied from Ethereum wallet:

Send 0.03582152   Bitcoin to 
1F3eeVKbmAWAjCZHmdXrH5VgMWskKfRzgL

It will be converted into .25  Ether, and sent to
0x66e43b474423ac3b0e5d8d1a8646223307b551be

Destination 
0x66e43b474423ac3b0e5d8d1a8646223307b551be

**Comment by wgwine** [comment]
I found the BTC transaction on block explorer as well. I can see the BTC transferred out of the account I sent to. [https://blockchain.info/address/1F3eeVKbmAWAjCZHmdXrH5VgMWskKfRzgL](https://blockchain.info/address/1F3eeVKbmAWAjCZHmdXrH5VgMWskKfRzgL)

**Comment by sathishvj** [comment]
So what does it do?  It converts BTC to ETH and then sends it to the target address?  If you're trying to send BTC directly to the Ethereum address, that won't work.  If it converts to ETH and then sends, you will need to get the transaction id on the Ethereum network to check if it went through.  

So far, I'd guess that it hasn't hit the ethereum network at all and you should contact the electrum service.

**Comment by SirHardo** [comment]
Same thing happened to me

**Comment by wgwine** [comment]
@sathishvj What does what do? I send BTC to the BTC address that Mist gave me. My understanding is something in the Mist system(how would I know what? I don't work there) converts that BTC into Ether and sends it on to my ethereum wallet address. Thats what it told me it was doing anyway. And it looked like it succeeded because it proceeded with the installation of ethereum wallet. 

> you will need to get the transaction id on the Ethereum network to check if it went through.

Where do I get this id?

**Comment by sathishvj** [comment]
Mist does not give you a BTC address.  It gives you an Ethereum address.  They are completely different networks.  Sending BTC to an Ethereum address might result in you losing the BTC.  But that apart ... 

Where did you send the BTC from?  Which app or service?   If it's an outside service you'll have to contact whoever provided that service.

If you did it from the Mist UI itself it might be better you wait for an official answer because I don't know enough about the internals yet.

But I can give you some possibilities you can try in the meantime:
 * If you used the "Fund with Bitcoin" option, it is just a link to Shapeshift and you might be able to contact the shapeshift.io team.
 * If you used the "Fund with a Credit Card" option, it is handled by coinbase and you might be able to contact coinbase.com

**Comment by wgwine** [comment]
> sathishvj 

shapeshift.io, that's what it was. I will start hitting them up. Thanks. 

One thing that is confusing to me. What is Mist? Is that the name for ethereum wallet? The UI title just says "Ethereum Wallet" nothing says Mist on it.

**Comment by sathishvj** [comment]
This [ethereum wallet vs mist](https://ethereum.stackexchange.com/questions/2690/what-is-the-relationship-between-mist-and-ethereum-wallet) does a good job of explaining the difference.  A google search shows up a few others also.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
