### ISSUE TITLE
Ethereum balance is wrong - missing coins

### ISSUE THREAD

**Issue by silentrob** [ethereum/mist#2532]
#### System information
``````
Version: `0.8.10`
OS & Version: OSX
Node type: `eth`
``````
**This is not a syncing issue**
Transferred 0.10 ETH from Coinbase to Ethereum Wallet, and after syncing it showed up.
4 Days later I re-open (and re-sync) the Wallet and the Balance is now `0.058792981`. Where would the difference go?
<img width="1137" alt="screen shot 2017-06-15 at 9 52 17 pm" src="https://user-images.githubusercontent.com/15984/27212462-0c7ab7da-5215-11e7-8298-a37c613c9177.png">
<img width="316" alt="screen shot 2017-06-15 at 9 52 29 pm" src="https://user-images.githubusercontent.com/15984/27212463-0c89c18a-5215-11e7-8d46-c1e46d9e9d8b.png">

I'm a noob, so maybe I did something wrong.  ¯\_(ツ)_/¯

**Comment by sathishvj** [comment]
There is a fee taken by the network itself for the transaction, but it's unlikely to be that much.  Do you have the id of the transaction?  If yes, you can check it at etherscan.io/tx/0x... Put the transaction address at the end.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
