### ISSUE TITLE
Account displays 0.00 Eth, Online shows correct amount

### ISSUE THREAD

**Issue by firstdeathmaker** [ethereum/mist#2534]
#### System information
``````
Version: `0.8.1` to `0.8.10`
OS & Version: windows 7
Node type: `eth/geth(default)`
``````
After I updated to the current version, the balance of my Account displays 0.00 Eth. But when I check the balance online (https://etherchain.org/account/0x8a9E35663137bF9cD16066AA6FCEC6F010F7609F) I still see the correct amount for the account. I waited for the ethereium Wallet to fullly sync with the network.

I run the older versions again, but they now also show 0.00 Eth.

**Comment by SirHardo** [comment]
Same here

**Comment by iplaytiger** [comment]
Same Here

**Comment by spingee** [comment]
same here

**Comment by Decrayer** [comment]
Addition: I noticed, that the keyfiles in AppData/Roaming/Ethereum/keystore/ are still the old ones, they haven't been overwritten. I even checked it with an older backup that I took before I installed the newest version.

**Comment by sergiysh80** [comment]
same here...

**Comment by spingee** [comment]
So i can finally see it when my node fully synchronized... thats wierd behaviour

**Comment by garretlaxton** [comment]
Your wallet needs to fully sync in order for your ETH to show, you guys can use myetherwallet.com to access your ETH instantly.

**Comment by gk95** [comment]
Same here. Yesterday my wallet was fully synced, but now my `geth/chaindata` folder is empty!??? And it's not syncing at all. Another strange thing is that I connect to only 5 peers, when I usually connect to 12?

#### System information
``````
Version: `0.8.10`
OS & Version: osx
Node type: `eth/geth(default)`
``````

**Comment by iplaytiger** [comment]
Please advise how to sync, I couldnt find the place to do it, on the other hand, In try using myetherwallet.com, it asks me to find the my wallet file (MIST Keystore File (UTC / JSON)),  I am total newbie to this, could anyone help me to access my wallet and get my ETH back please.   Thanks alot.

**Comment by SirHardo** [comment]
Same

**Comment by iplaytiger** [comment]
under Develop Tab, I run the "TEST", and there is error message as below, I Have no idea what it means, could any expert brother tell me what is wrong with mine wallet?  I was trying to invest for dcorp.it.... thanks for helping!

web3 parameter validation
shouldn't allow RegExp (possible XSS) ‣
AssertionError: expected [Function] to throw error including 'Payload, or some of its content properties are invalid. Please check if they are valid HEX with \'0x\' prefix.' but got 'Payload, or some of its content properties are invalid. Please check if they are valid HEX with 0x prefix.'
    at Context.<anonymous> (file:///C:/Program%20Files/Mist/resources/app.asar/tests/mocha-in-browser/spec/permissions-spec.js:122:117)
    at Test.Runnable.run (file:///C:/Program%20Files/Mist/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4281:32)
    at Runner.runTest (file:///C:/Program%20Files/Mist/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4667:10)
    at file:///C:/Program%20Files/Mist/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4743:12
    at next (file:///C:/Program%20Files/Mist/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4592:14)
    at file:///C:/Program%20Files/Mist/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4602:7
    at next (file:///C:/Program%20Files/Mist/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4540:23)
    at file:///C:/Program%20Files/Mist/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:4569:5
    at timeslice (file:///C:/Program%20Files/Mist/resources/app.asar/tests/mocha-in-browser/lib/mocha.js:5613:27)

**Comment by isaac-art** [comment]
@iplaytiger If you click Accounts>Backup>Accounts it should show you your keystore files which you can then open in myetherwallet

**Comment by iplaytiger** [comment]
I have located the keystore file, but it ask me for the password, when I install MIST, I have no recall about my password..is there anyway possible to find my password?  it is embarrassing but please help!

**Comment by gk95** [comment]
@iplaytiger If you lost your password your account is lost.

**Comment by iplaytiger** [comment]
@gk95 but I can still launch my MIST app, just that my balance shows $0, the mist app suppose to sync my wallet.  It's so weird how thing work with MIST, is it possible to contact Mist support?  Thanks so much for giving me info

**Comment by iplaytiger** [comment]
@Spingee could you please share the info how to sync the wallet, i saw your comment about finally sync all data, apreciate ur help

**Comment by spingee** [comment]
Run Mist and wait for full sync. Progress is at bottom left

**Comment by SirHardo** [comment]
how long does a sync take? How much data am i using up? - I have expended 100GB of data already, and the blocks just keep adding to themselves. A perpetual sync methinks...

**Comment by SirHardo** [comment]
how long does a sync take? How much data am i using up? - I have expended
100GB of data already, and the blocks just keep adding to themselves. A
perpetual sync methinks...

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
