### ISSUE TITLE
Desktop Ethereum wallet not fully syncing so cant acces my coins

### ISSUE THREAD

**Issue by Markzaal100** [ethereum/mist#2537]
I have downloaded the Ethereum windows wallet, however it will not sync the last 200 blocks. This way my wallet will not be fully synced and now I cant acces my coins.

Is there an other way to access my coins?

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
