### ISSUE TITLE
listen udp :30303: bind: address already in use

### ISSUE THREAD

**Issue by scyclow** [ethereum/mist#2538]
I definitely don't have any other versions of Mist running, and I've uninstalled & reinstalled. All the solutions I've been able to find related to this issue suggested doing one of those two things.

#### System information
``````
Node type: geth
Network: main
Platform: darwin (Architecure x64)
``````
```
WARN [06-16|14:38:13] No etherbase set and no accounts found as default 
INFO [06-16|14:38:13] Starting peer-to-peer node               instance=Geth/v1.6.5-stable-cf87713d/darwin-amd64/go1.8.3
INFO [06-16|14:38:13] Allocated cache and file handles         database=/Users/pikelny/Library/Ethereum/geth/chaindata cache=1024 handles=1024
INFO [06-16|14:38:18] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Metropolis: 9223372036854775807 Engine: ethash}"
INFO [06-16|14:38:18] Disk storage enabled for ethash caches   dir=/Users/pikelny/Library/Ethereum/geth/ethash count=3
INFO [06-16|14:38:18] Disk storage enabled for ethash DAGs     dir=/Users/pikelny/.ethash                      count=2
INFO [06-16|14:38:18] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [06-16|14:38:18] Loaded most recent local header          number=95419 hash=1142e5…c938a0 td=152146762933695950
INFO [06-16|14:38:18] Loaded most recent local full block      number=0     hash=d4e567…cb8fa3 td=17179869184
INFO [06-16|14:38:18] Loaded most recent local fast block      number=83034 hash=74c0c9…0388f6 td=113044595616850647
INFO [06-16|14:38:18] Starting P2P networking 
Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use
```

**Comment by gpsuser** [comment]
from the command line, add the following port definition to the end of your command:      
  --port "30304"

**Comment by scyclow** [comment]
Would it make sense to have it try port 30304 if 30303 is already in use? It took me a while to find the command line executable (in `/Application\ Support/Ethereum\ Wallet/binaries/Geth/unpacked/geth`), which allowed me to do what you're suggesting and then open the application. But that solution was a pain to figure out, and might not be intuitive for a lot of users.

**Comment by gpsuser** [comment]
I agree -- its always better to not have to configure ports --- but if the default port is in use (firewall ?)  there is often no choice but to stipulate an alternative communication port -- otherwise the application wont run

**Comment by scyclow** [comment]
As far as I can tell, I don't have anything running on 30303.

I've also seen other applications as me if I want to use a different port if the default is in use.

**Comment by evertonfraga** [comment]
Hi @scyclow, 

please try this: https://github.com/ethereum/mist/wiki#bind-address-already-in-use
I wrote this section of the guide for you – and others that may run into the same problem :)

I'll close this for now, should you need anything, reopen this issue.

**Comment by carlgieringer** [comment]
Thanks @evertonfraga.  Unfortunately the suggestion (for Mac) didn't work for me.  When I check for processes bound to 30303, I also get nothing.  A couple questions: 1) the error message above (and the one I get from Bitcoin Wallet) mention UDP, but the wiki limits the `lsof` command to TCP (I checked both, but if it is supposed to be UDP, the wiki should reflect that) 2) does the user need to run the command as a privileged user (with `sudo`)?  (I did so, and still didn't get anything.)  Hopefully a system restart will help (when I can get everything saved for a restart!)  Thanks!

**Comment by nopslip** [comment]
Ran into this issue on Sierra 10.12.5. It appears that there is a hung socket. I can see this with:
```
netstat -an | grep '30303' 
udp46    511      0  *.30303 
```
but not: 
`lsof -i tcp:30303`
(no results)^^

```
sudo kill -9 511 
kill: 511: No such process
```
Unfortunately, I cannot restart my machine (or networking) at this time which I expect would resolve the issue of the hung socket. 

Similar to what @scyclow recommend, this approach worked for me to get Geth up and running: 

`/Users/nopslip/Library/Application\ Support/Ethereum\ Wallet/binaries/Geth/unpacked/geth --port 0`

Because I was running Mist I then opened another terminal and ran this which worked:
`/Applications/Ethereum\ Wallet.app/Contents/MacOS/Ethereum\ Wallet --mode mist`

Hope that helps someone else.

**Comment by evertonfraga** [comment]
Hi @carlgieringer and @nopslip. You may also want to try this to identify the process. I've udpated the wiki.

`lsof -i udp:30303`

https://github.com/ethereum/mist/wiki#bind-address-already-in-use

**Comment by tystr** [comment]
I'm getting this error as well, and nothing is running on `30303`.

Both of the following commands return no matches:
 
    $ lsof -i tcp:30303
    $ lsof -i udp:30303

I can start `geth` from the cli by passing `--port 0`, but without that it errors with the same `address already in use` error as mist.

**Comment by Zhengzihao980115** [comment]
close your mist and then run geth in terminal

**Comment by PratikSymz** [comment]
**How do I close an open port from the terminal on the Mac?**
ANSWER
https://stackoverflow.com/questions/12397175/how-do-i-close-an-open-port-from-the-terminal-on-the-mac?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by kyriediculous** [comment]
@evertonfraga  works for me on ubuntu 16.04 , thanks so much !
