### ISSUE TITLE
Ethereum Wallet Downloaded Lost Funds

### ISSUE THREAD

**Issue by redhawk610** [ethereum/mist#2539]
Hello Everyone,

I'm pretty confused and frustrated at the moment. I downloaded geth and ethminer. Running the mining software on a gtx 1060 for roughly 24 hours I went to check my balance.

So, I went to the geth attach console and checked my balance in ether, not wei, and it reported I had 80 ether. Wanting to manage the ether better I downloaded ethereum wallet and when it synced I launched the application only to find 0 ether as my funds.

Any idea what happened??

Thank you!

**Comment by garretlaxton** [comment]
Mining 80 ETH in 24 hours doesn't sound right, but if you see it on etherscsn.io then your wallet most likely needs to fully sync before you see your funds. 

You can use myetherwallet.com to access your ETH while your wallet syncs.

**Comment by jordanmack** [comment]
If you did manage to mine 80 ETH in 24 hours you must have done it on the testnet. That amount on the mainnet is virtually impossible.

**Comment by evertonfraga** [comment]
Hi @redhawk610, i know how frustrating this might be. Although, to mine 80 ether in 24h is something out of this world. 

Please point your ethermine to use the main network and let us know. 

Meanwhile, for curiosity sake: you can search for your address on the different networks just to make sure where these 80ETH are located at. 
https://ropsten.etherscan.io/ <-- should be here
https://rinkeby.etherscan.io/
https://etherscan.io/

I'm closing this for now. feel free to reopen if you want to keep the discussion.
