### ISSUE TITLE
Ethereum Wallet is blank

### ISSUE THREAD

**Issue by jameshaswon** [ethereum/mist#254]
I open Ethereum-Wallet.exe and this is what I see. Just a blank program - http://prntscr.com/abji90
I'm on windows 10. I looked through similar issues to this and what they did didn't fix mine or I have no idea how to do what they did.

**Comment by Phistr90** [comment]
I had an similar issue on ubuntu 15.04, totally blank loading screen. even no close button. had to reboot to resolve it.

**Comment by jameshaswon** [comment]
@Phistr90 tried rebooting, still have a blank screen when I start the wallet.

**Comment by linagee** [comment]
Can you try this? Ethereum-Wallet.exe --ignore-gpu-blacklist

**Comment by jameshaswon** [comment]
@linagee it's still blank.

**Comment by taoteh1221** [comment]
Try the proprietary video drivers instead, if you are using Linux "xorg" video drivers. That solved this issue for me.

**Comment by luclu** [comment]
Please refer to this issue for more information: https://github.com/ethereum/mist/issues/599
I will close this for now, but feel free to continue to discuss over here!
