### ISSUE TITLE
Why my geth/chaindata folder is empty?

### ISSUE THREAD

**Issue by gk95** [ethereum/mist#2540]
Yesterday my wallet was fully synced, but now my `geth/chaindata` folder is empty!??? And it's not syncing at all. Another strange thing is that I connect to only 5 peers, when I usually connect to 12?

#### System information
``````
Version: `0.8.10`
OS & Version: osx
Node type: `eth/geth(default)`
``````

**Comment by garretlaxton** [comment]
You can delete the chaindata folder which will re-sync the blocks, just make sure you have a backup of your account.

**Comment by gk95** [comment]
@garretlaxton Thanks for the advice. Now I'm curious how this happened in the first place. How this folder got empty?

**Comment by garretlaxton** [comment]
No idea, I couldn't tell you how it happened ..but if you need to access your ETH while your wallet syncs you can use myetherwallet.com

**Comment by gk95** [comment]
I think my issue is connected to [this one](https://github.com/ethereum/go-ethereum/issues/14638).   The geth procces exits with errors, number of blocks, that must be synced, is changing from ~500,000 to ~3,600,000. It's really weird. 
![screen shot 2017-06-17 at 1 52 33 am](https://user-images.githubusercontent.com/6297371/27247286-c9ab207a-52ff-11e7-8909-03e1dedb26f2.png)

**Comment by evertonfraga** [comment]
Hi @gk95 I really encourage you to open an issue on Geth repository, which is a more appropriate place for this problem: https://github.com/ethereum/go-ethereum/issues/new

Pinging @karalabe.

I'm closing this for now.
