### ISSUE TITLE
No ETH

### ISSUE THREAD

**Issue by 7achtel** [ethereum/mist#2544]
Hello, I have a problem.
Me my laptop crashed including all files. I could not save anything, no more backup.
What can I do? I make all new ,Dl Mist and ....

Thanks with kind regards Eric

i have just my Old 0x....... Adress

i try if and klick for import my Konto use my old wallet Adress from yesterday and they say i have no Contrakt with this adress.....im frustrated realy.....

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by jordanmack** [comment]
I'm having some trouble understanding your problem. You say your computer crashed and you lost every single thing? Do you have backups of your wallet files?

**Comment by 7achtel** [comment]
no i have no backups, thats the problem.....its all delete ....my harddisk too......one damage and i must all reset.....i can sent u a sreenshot pvt i can watching in my history from my adroid ....

but i transfer and open my mist /wallet in my computer /win10

**Comment by jordanmack** [comment]
I can see [your balance on Etherscan](https://etherscan.io/address/0x90b004f3efeb4cad2234e0cbcbdcc73b9a7cec18).

To restore your balance on Mist, put your old wallet files in the folder below. Replace <username> with your Windows 10 login username.

`C:\Users\<username>\AppData\roaming\Ethereum\keystore`

After you have restored your wallet files, your accounts should show up the next time Mist is started. Your balances should appear after the blockchain has synchronized completely.

**Comment by 7achtel** [comment]
thx for the help but i have no old files ,i dowlnoad all new .

**Comment by evertonfraga** [comment]
@7achtel don't you have any backup of your Keystore file? Without the file it's virtually impossible to recover your funds :(

You can try to recover your lost files going to a hard drive recovery service in your city, if the amount is significant. If they manage to recover your keystore file, then you should be able to have access to your funds again.

I'll close this for now, but feel free to reopen if needed. Thanks!
