### ISSUE TITLE
Blocked transaction 0 fee

### ISSUE THREAD

**Issue by terzai** [ethereum/mist#2545]
I believe I did a mistake while doing a transaction from a wallet contract on Mist wallet.

I wanted to do a transaction, but I did it with 0 fee, so of course the transaction never reached the blockchain.

I did an other transaction from the same wallet contract to same address previously used on the transaction with higher fee which went through. The first transaction is still stuck.

Is there anything I can do to cancel or fix the this transaction ?

**Comment by evertonfraga** [comment]
If you restart Mist the pending transaction it should be gone.

I'll close this for now, feel free to reopen the issue. Thanks!
