### ISSUE TITLE
Question regarding the initial password when installing the wallet

### ISSUE THREAD

**Issue by razvanct** [ethereum/mist#2546]
#### System information
``````
Version: `10.12.5`
OS & Version: osx
Node type: `geth(default)`
``````

Using version 0.8.10 of Ethereum wallet.
Problem:
I have lost the password that I've set when I first installed the app, I still have the keystore data.
Is there any way that I can still use that account?

**Comment by evertonfraga** [comment]
I am sorry, there's no password recovery service. 
Ideally you would keep both keystore file and password safe.
