### ISSUE TITLE
I am trying to watch contract events but the system is still working and no events are appearing

### ISSUE THREAD

**Issue by cjedani** [ethereum/mist#2554]
#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by alexvandesande** [comment]
The watch contract tab is not very reliable and requires a full sync. Are you sure you were in sync?

We are reviewing at old unanswered issues, sorry it took so long to reach yours, it's a long backlog.
