### ISSUE TITLE
bought 2 ethereums from bitpanda, did noob error and messed-up on setting up my wallet, please help

### ISSUE THREAD

**Issue by congaplayer** [ethereum/mist#2558]
#### System information
``````
Version: `0.0.0`
OS & Version: osx
Node type: `eth/geth(default)`
``````

**Comment by sathishvj** [comment]
how did you mess up?  there's not enough info here to help you.

**Comment by congaplayer** [comment]
Hello!  First of all, thank you for trying to help!

On A pril !4th, I purchased 2 Ethereums through Bitpanda (formelly known Austrian exchange as Coinmall). Unfortunalety, they do not carry Ethereum wallets so they told me to get a wallet myself and then purchase from them. 

I never did that before, donwnloaded an ethreum wallett from Ethereum.org <http://ethereum.org/>, then paid for my 2 Ethereums and it looked lie it showed up in my wallet but now found out it did not stay in the wallet as it was a TEST wallet, not for real transactions!

The only track I still have now is the etherscan page showing the dat of transactionm, address and the block number. 

With this etherscan data, can I still re-direct these @ ethereums to a real wallet?

Best, 
Jeroen

**Comment by sathishvj** [comment]
If it was an account on the Test network and you transferred Ether from the main network to it, then I think it is lost.

Can you paste a link to the transaction?

fyi: I don't yet know what you have done, so some early info.  Back up whatever wallet/keystore-file you have created on Mist.  Do not share the keystore file or password for it with any body.

**Comment by congaplayer** [comment]
Ok, I do not think it went through, as the adress it was sent to seems different than my ether wallett that was on test net. 

Here is a link of the transaction, I bought from Bitpanda (Asutria copany formerly known as coinmal) is it possible that it is their wallet? their support gave up pon trying to help me sort this out :(


https://etherscan.io/tx/0xc0837c03e6ab6997928c47cb69a0be8ad6a16b5451af9583d24f8c9e91687638 <https://etherscan.io/tx/0xc0837c03e6ab6997928c47cb69a0be8ad6a16b5451af9583d24f8c9e91687638>

**Comment by sathishvj** [comment]
Following that transaction, it appears that https://etherscan.io/address/0x234ee8942355a0e801bbbebd8037aefbe300f372 is your account and your 2 Ethers are there.

Is that not your account?  Are you not able to access it?

**Comment by congaplayer** [comment]
Yes, I think it must be but I have no idea how to access it. 

I do not remember having had to create a passord. I am such a noobee, I had no clue what to do, I only tried to create an account through ethereum.org <http://ethereum.org/> and then did the transaction with bitpanda. Is it possible to confirm the wallett copany , and get help from them?

**Comment by sathishvj** [comment]
There is no wallet company in this case who can sort it out for you.  Ideally you should have saved the wallet keystore file and remember the password.  Without that it will be impossible to recover.

Attempting to help you from here on would mean asking you for more information than you should give to any stranger on the net.  I would suggest you reach out to somebody you know who already has some knowledge on the subject and seek some assistance from them.

**Comment by congaplayer** [comment]
Thank you again! 

I have tried to handle this for 66 days now and know no-one who has ANY clue about this stuff, it is SO frustrating !

Could I pay you to help me recover them? 

If so, how much would it be fair? 

As they are same as lost without me knowing how to recover them, I am trusting you with all the data you will need to get them back.

**Comment by sathishvj** [comment]
I have lost way more ether just in the process of trying to learn a small portion of this.  So assuming that the payment would be only a portion of the 2 eth to be recovered here, I would say, no, it would definitely not work out for me monetarily.  But I'll still try to help you but its going to be entirely at your risk and you are advised to never use the account again even if we manage to recover the ether (chances of recovering any are very very low btw).

**Comment by congaplayer** [comment]
I undersand and really appreciate your help!  I totally agree that it is at my own risk.

What do you need from me in order to have a chance of success?

**Comment by sathishvj** [comment]
I'll have you do everything instead of me doing anything where you will have to give me credentials.  Please direct message me on my twitter at ```@sathishvj```.

**Comment by congaplayer** [comment]
ok, I don’t know how to instant message on twitter, I tweeted to you, did you get it?

**Comment by congaplayer** [comment]
I think you need to follow me to be able to instant message you, if this is the case, here is mine: 
@jeroenbeukers <https://twitter.com/jeroenbeukers>
