### ISSUE TITLE
Cannot Create Account

### ISSUE THREAD

**Issue by AshleyYakeley** [ethereum/mist#2559]
#### System information
``````
Version: 0.8.10
OS & Version: Linux 64 bit
Node type: geth on another machine, via --rpc
``````
Note that geth is fully synced.
1. Accounts -> New Account
2. Enter account password, and repeat, then OK

Results: nothing happens, no account created.

**Comment by AshleyYakeley** [comment]
Message in log:
```
[2017-06-18 17:58:51.601] [ERROR] ipcProviderBackend - Send request failed { code: -32601,
  message: 'The method personal_newAccount does not exist/is not available' }
```

**Comment by AshleyYakeley** [comment]
Never mind, it appears to be a deliberate security feature.

**Comment by IamGabrielWu** [comment]
why this issue has been closed ? @AshleyYakeley   It happened to me. And i tried to start geth node with ``` -rpcapi api,eth``` , still i got some error

**Comment by SachinJanani** [comment]
I am also facing the same issue but while running executing contract on private network? @AshleyYakeley  can you please explain
