### ISSUE TITLE
Install on MAC Updated with recent OS ( fresh )

### ISSUE THREAD

**Issue by michaelsomerville** [ethereum/mist#2561]
Hey guys, I am trying to open and load the application about we do the install. All we get is **“Ethereum Wallet” can’t be opened because it is from an unidentified developer.**

I have changed the settings, allowing for the "anywhere' and still nothing. Anyone else getting this ?

Not a noob here, lol.

**Comment by sathishvj** [comment]
This is to do with mac trying to make sure you know what you are doing and you trust the application.  You should bring up the context menu for the app (right click/ctrl-click) and then click Open.

**Comment by tobiv** [comment]
Correct but shouldn't it work as Mist is signed since 0.8.9?

**Comment by emiliano1** [comment]
LOL!

**Comment by michaelsomerville** [comment]
Ended up getting it ... takes forever to get he block though. lol
