### ISSUE TITLE
URGENT: endless stream of emails from shapeshift.io 

### ISSUE THREAD

**Issue by khazelton** [ethereum/mist#2569]
I am receiving a seemingly endless stream of identical emails from shapeshift.io, one every few seconds, as follows:

Hello ShapeShifter,

Thank you for your order.

Order Summary:
Order Number: 0323d09866
You Deposited: 0.13907326 BTC
You Received: 1.00000000 ETH
The exchange took 1147 seconds

Deposit Address: 1.....
Withdraw Address: 0x2.....
______________________________
View on the blockchain.

Please remember to follow us on Twitter!

-The Shapeshift Team

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by evertonfraga** [comment]
I'm sorry to say, but we are not associated with Shapeshift. Can you get in
touch with their support team to solve this?

Have a great week.
