### ISSUE TITLE
Node crash - 0.5.1

### ISSUE THREAD

**Issue by azulmarino** [ethereum/mist#257]
Node type: geth
Network: main
Platform: darwin

...d 433MB cache to /Users/Dan/Library/Ethereum/chaindata
I0305 20:51:51.029624    8782 database.go:71] Alloted 78MB cache to /Users/Dan/Library/Ethereum/dapp
I0305 20:51:51.049551    8782 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0305 20:51:51.322991    8782 backend.go:362] Blockchain DB Version: 3
I0305 20:51:51.948171    8782 blockchain.go:214] Last header: #1104585 [7ce446b4…] TD=8584818784677646283
I0305 20:51:51.948612    8782 blockchain.go:215] Last block: #1104585 [7ce446b4…] TD=8584818784677646283
I0305 20:51:51.948640    8782 blockchain.go:216] Fast block: #1104585 [7ce446b4…] TD=8584818784677646283
I0305 20:51:52.253708    8782 handler.go:92] blockchain not empty, fast sync disabled
I0305 20:51:52.807330    8782 cmd.go:114] Starting Geth/v1.3.5/darwin/go1.5.1
I0305 20:51:52.976203    8782 server.go:311] Starting Server
Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use (possibly another instance of geth is using the same port)

**Comment by azulmarino** [comment]
Closed previous wallet , so node shouldn't have been running , but will check ports.

**Comment by azulmarino** [comment]
netstat -a |grep 30303
udp46      0      0  *.30303                *.*

**Comment by azulmarino** [comment]
Rebooted and node/wallet comes up OK. Not sure why the port wasn't cleared ... perhaps due to using previous Mist version. I can now stop/start node and no further problems.

**Comment by alexvandesande** [comment]
Sometimes this happens. Nice t see its solved
