### ISSUE TITLE
Ethereum wallet-no update of Ether status

### ISSUE THREAD

**Issue by GoranM88** [ethereum/mist#2571]
Hi,

I have an Etherum Wallet Version 0.8.10, the problem is that I have done 3 Ether Transactions where two of them were successful and one wasn't, even though the address was correct. After waiting to update the blockchain on my Wallet, the amount of Ether in my wallet hasn't changed. I also tried sending some more Ether afterwards, however it seems it doesn't work anymore.

Has anyone had a similar issue? Thanks for the help.

Cheers,

GM

**Comment by gogopower** [comment]
I have the same problem, i send ETH to my ethereum wallet and while the transaction is finished, my wallet shows the same amount as before the transaction. My wallet is fully updated and synced. Also neither Etherscan shows my transaction or my wallets amount after the transaction.

**Comment by GoranM88** [comment]
Short update: my Ether amount in the Wallet now matches the one that I can see with Etherscan. But now, when I try sending Ether from the Wallet to another account it just doesn't go through meaning that I can't see the transaction with Etherscan. However, the supposed transaction can be seen under Last Transactions in the Wallet. Among one of desperate tries I also got an error message: Nonce too low. What is that? I tried looking for a solution but couldn't find anything that would really help.

I recently updated the Wallet, could that be the reason? How do I access my Ether now?

Please help!

**Comment by gogopower** [comment]
I m glad your wallet finally shows improvement. Mine isnt, my transaction is not even in the blockchain yet..Search nonce token in google. I don t think that is a wallet problem. Of what i read, there is an instability in ETH blockchain network, which i assume it costs the delays in transactions, confirmations, wallet amounts etc. I hope they resolve those problems fast.

**Comment by tibor** [comment]
Hi,

I have the same problem. I purchased 0.3980… Ether via cointed.com and transferred it to my Ethereum Wallet 22 days ago but it hasn’t shown up in the wallet yet.

I’m also wondering if I need a contract for this? The software mentions something like this but I don’t understand this completely and I haven’t created one yet.

**Comment by GoranM88** [comment]
I could get the transaction through (I can see it now with Etherscan). I was playing around with geth and used this command: personal.unlockAccount(eth.coinbase, "pwd here")

I'm not sure whether running this command caused the transfer or it was just that 'pending' transactions were somehow processed (no more ETH blockchain network stability?)

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
