### ISSUE TITLE
Unable to execute transaction - "Unable to locate transaction entry"

### ISSUE THREAD

**Issue by ghost** [ethereum/mist#2572]
#### System information
``````
Version: `0.8.10`
OS & Version: osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum. 
--> I did check it, but answers are missing or don't help

Latest Tx ID:
0x1952bc9c36de9d1ea413b096cd658ad57c7989d978eff506cfe4ab20cc0b0383

receiving address:
0x6de11646499d04779a24E42a9A10B9Ef6Da3cB2f

This is already the third try. Still didn't get through

![bildschirmfoto 2017-06-20 um 08 58 51](https://user-images.githubusercontent.com/29563153/27320917-829a78b6-5598-11e7-8126-3e8a0a8643c4.png)

![bildschirmfoto 2017-06-20 um 08 54 55](https://user-images.githubusercontent.com/29563153/27320924-8d59c27a-5598-11e7-902c-cbcd8a6e753b.png)

![bildschirmfoto 2017-06-20 um 08 57 12](https://user-images.githubusercontent.com/29563153/27320927-94691a3e-5598-11e7-9220-01dbc245770c.png)

![bildschirmfoto 2017-06-20 um 09 07 04](https://user-images.githubusercontent.com/29563153/27320911-79cc570e-5598-11e7-97ff-da33263f635f.png)

What can I do?

Please be so kind and help 
(in a way a non-computer-expert is able to understand)
Thank you very much

**Comment by sathishvj** [comment]
There has been a general congestion of the network for the past about 2 days and a lot of transactions are blocked.  I'd suggest you wait a bit (may a day or two) and if the transaction hasn't gone through, then you can try again.
