### ISSUE TITLE
CANNOT RECEIVE ETHER FROM FAUCET  USING ETHEREUM WALLET

### ISSUE THREAD

**Issue by testpuddle** [ethereum/mist#2573]
#### System information
``````
Version: `0.8.10`
OS & Version: windows 10
Node type: `geth(default)`
``````
I am not receiving Ether from the ROPSTEN FAUCET when I am on the TESTNET using the Ethereum Wallet.

I am on the TESTNET and fully sync'd

![image](https://user-images.githubusercontent.com/29495946/27329355-50fba326-5583-11e7-8dc8-7106677cf2a1.png)

My account shows ZERO ETH.

![image](https://user-images.githubusercontent.com/29495946/27328525-6e881558-5580-11e7-89fd-2f552bec17f3.png)

I used http://faucet.ropsten.be:3001/ to request 1 ETH

ROPSTEN.io shows balance of 1 ETH (internal transaction).

![image](https://user-images.githubusercontent.com/29495946/27328648-d016213e-5580-11e7-8dc7-6b521837b17e.png)

Transaction was made over 2 days ago on block 1139843.

Clock is sync'd to nist.gov and up-to-date

![image](https://user-images.githubusercontent.com/29495946/27328804-668d0dc6-5581-11e7-8088-edf20e5e644b.png)

- Log files are attached:

[nodezips.zip](https://github.com/ethereum/mist/files/1087864/nodezips.zip)

Any guidance would be appreciated.

**Comment by testpuddle** [comment]
I launched GETH in command mode and issued: 


geth --testnet removedb                   to delete the old blockchain database 
geth --testnet to resync

I now am showing 1 ETH.

![image](https://user-images.githubusercontent.com/29495946/27380823-a6fc1d0c-564e-11e7-912c-732522246ac4.png)

Not sure of the relationship between GETH and the Wallet.

**Comment by bebebebebebebebe** [comment]
Can anyone send me Ropsten testnet ether please?
0xb9aF6Ee39b9f43944d1732b7D34D13Ae25821969
