### ISSUE TITLE
dont recieved transaction of ETH

### ISSUE THREAD

**Issue by MihailH** [ethereum/mist#2576]
Hí, i tryed to Transit ETH from my JAXX to the EthereumWallet.
The Transaction is due:
Block Height 3902500 (1681 block confirmatioins)
Icant See the recieved payment on my EthereumWallet. 
there is still now 0,00ETH

See screenshots below
![ethwallet](https://user-images.githubusercontent.com/29568566/27346669-29bfd186-55ee-11e7-8030-52a4dcfa2ecc.PNG)
![jaxx](https://user-images.githubusercontent.com/29568566/27346671-2af7e674-55ee-11e7-8bd1-e1f937c63d4b.png)

**Comment by sathishvj** [comment]
The progress bar on top indicates that the blocks haven't synced yet.  You can still check the balance at etherscan.io/tx/0x... put your account address at the end.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
