### ISSUE TITLE
Backup doesn't work

### ISSUE THREAD

**Issue by metaphoricalstate** [ethereum/mist#2578]
#### System information
``````
Version: `0.8.10`
OS & Version: Windows 10
Node type: `geth`
``````
When I click Backup > Accounts it takes me to an empty keystore folder.

**Comment by evertonfraga** [comment]
Did you install Mist in another driver or directory?
I understand that Mist looks for the accounts at `%LOCALAPPDATA%` (usually C:\Users\user\AppData\Roaming), but if you chose a custom drive when installing Mist, you should look up there.

@metaphoricalstate please check https://github.com/ethereum/mist/issues/2541 for proposed solution.

That should work. Please reopen issue for if any further discussion is needed. Thanks!
