### ISSUE TITLE
Blockchain fully synced, balance still 0

### ISSUE THREAD

**Issue by shlomogoldblatt** [ethereum/mist#2584]
About a month ago bought some ether to test. Transaction checks out on etherscan. Wallet (both Ethereum and Mist) still show 0 balance. Re-installed a few times, re-downloaded blockchain (took me 1 week), still 0. Why? What can I do to fix this?
Address 0xf794fB00f06FBD673cE3DB5EB0339c1e78dD0c3b

<img width="568" alt="mistwallet" src="https://user-images.githubusercontent.com/29599977/27381580-a402db9c-5683-11e7-8f8f-8692fce90e02.PNG">

**Comment by evertonfraga** [comment]
Hi @shlomogoldblatt, let me help you debug that. 

One possibility is that the wallet missed some logs while syncing. Just to rule this out, please restart Mist. If that doesn't work, let's do this: 

1. download latest geth from here http://geth.ethereum.org/downloads/
2. run `geth console` on your terminal of choice
3. when the geth console is ready, run `web3.eth.getBalance('0xf794fB00f06FBD673cE3DB5EB0339c1e78dD0c3b')`

If it still displays zero balance, I'd ask you to open an issue at the Geth repo: https://github.com/ethereum/go-ethereum/issues?utf8=%E2%9C%93&q=is%3Aissue%20sync%20

If it displays a positive balance and the wallet still displays zero, let me know. 

Thanks for reporting.

**Comment by shlomogoldblatt** [comment]
Hi evertonfraga.

I've been restarting Mist many times, didn't help
As for geth. I downloaded, installed and ran it, now I see a small black screen (attached). But I'm unable to run anything as I do not understand how to do that. when I hover my mouse over it, it won't type in it

<img width="514" alt="gethscreen" src="https://user-images.githubusercontent.com/29599977/27411207-8657de80-56ec-11e7-8026-de58c1f092d6.PNG">

**Comment by alwayslookright** [comment]
I'm trying to do the same and upon running Geth and typing in the command for getBalance I get

"INFO [06-21|20:24:57] Block synchronisation started 
WARN [06-21|20:25:11] Synchronisation failed, retrying         err="block download canceled (requested)""

**Comment by shlomogoldblatt** [comment]
I also get this line about failed sync!

**Comment by alwayslookright** [comment]
I re-ran it and it seems to be doing something, getting a similar screen above that shows 'Imported new state entries'

**Comment by alwayslookright** [comment]
I don't know if it had anything on using the command geth removedb, followed that from here
https://github.com/ethereum/go-ethereum/issues/3585

**Comment by alwayslookright** [comment]
maybe the command geth upgradedb is better to use.

**Comment by shlomogoldblatt** [comment]
no help whatsoever. what a fucking disappointment that ethereum is

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
