### ISSUE TITLE
Enhancement: using a debit card for EFTPOS and ATM withdrawals

### ISSUE THREAD

**Issue by jamesray1** [ethereum/mist#2585]
Using a debit card for EFTPOS and ATM withdrawals would be a very useful feature that would increase the market adoption of Ethereum.

**Comment by evertonfraga** [comment]
Thanks for the suggestion! Now we have Coinbase integration with the Wallet, and certainly having more options in the future is a go. 

I have flagged as [enhancement] for future references.

**Comment by jamesray1** [comment]
Great, I'll check Coinbase out. I've used Poloniex, BTC Markets and Coinjar. NVO may be a good one too if it's possible to do this when it's running, although I think it's just a digital asset decentralised exchange, so it may not be suitable for using with debit cards.

**Comment by jamesray1** [comment]
Coinbase's fees are higher than BTCMarkets.net. Here's a list of links to exchanges ranked in ascending order of fees:

https://www.btcmarkets.net/fees
http://gdax.com/fees/
https://www.coinjar.com.au/
https://support.coinbase.com/customer/en/portal/articles/2109597

**Comment by alexvandesande** [comment]
Thanks for the suggestion. While I do believe credit/debit cards are part of solution for overall adoption, I don't think the Mist repository is the right place to discuss it, as it can't be a Mist feature. 

I'll have to close this to allow us to better use the repo to track software specific issues. Feel free to reopen if you feel it's still relevant/
