### ISSUE TITLE
URL from Mist gives different account online

### ISSUE THREAD

**Issue by PlantDr430** [ethereum/mist#2588]
#### System information
``````
Version: `0.8.10`
OS & Version: windows 10 Pro 64-bit
Node type: `geth`
``````

Hello,

So starting yesterday my syncing just suddenly stopped while it was syncing and has seen been able to connect to peers. I get peers appearing, but none seem to fully connect. I've tried many troubleshoots (clock syncing, firewalls, using a VPN, different computer, uninstall, reinstall, clearing chaindata) still nothing can get the syncing to start again. 

ALSO when I go to MIST and copy the "wallet.ethereum.org" URL for my account a different wallet with a different address appears in the website than what I imported into MIST.
![different wallets](https://user-images.githubusercontent.com/29610303/27399091-e78dbf54-5678-11e7-8f2e-dee2606c4350.png)

This is the data from my log file.
WARN [06-21|11:43:23] No etherbase set and no accounts found as default 
INFO [06-21|11:43:23] Starting peer-to-peer node               instance=Geth/v1.6.5-stable-cf87713d/windows-amd64/go1.8.3
INFO [06-21|11:43:23] Allocated cache and file handles         database=C:\\Users\\Stephen\\AppData\\Roaming\\Ethereum\\geth\\chaindata cache=1024 handles=1024
INFO [06-21|11:43:23] Writing default main-net genesis block 
INFO [06-21|11:43:23] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Metropolis: 9223372036854775807 Engine: ethash}"
INFO [06-21|11:43:23] Disk storage enabled for ethash caches   dir=C:\\Users\\Stephen\\AppData\\Roaming\\Ethereum\\geth\\ethash count=3
INFO [06-21|11:43:23] Disk storage enabled for ethash DAGs     dir=C:\\Users\\Stephen\\AppData\\Ethash                          count=2
WARN [06-21|11:43:23] Upgrading db log bloom bins 
INFO [06-21|11:43:23] Bloom-bin upgrade completed              elapsed=0s
INFO [06-21|11:43:23] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [06-21|11:43:23] Loaded most recent local header          number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [06-21|11:43:23] Loaded most recent local full block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [06-21|11:43:23] Loaded most recent local fast block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [06-21|11:43:23] Starting P2P networking 
INFO [06-21|11:43:26] UDP listener up                          self=enode://4516d853a65dd7ebffa95dc78c2907a5af350d3819d46af827f2587fde7057d625ba8ccc3d6cdeddc2b53adc84691c92b2815db88a46112b54c81fdd8f093813@[::]:30303
INFO [06-21|11:43:26] RLPx listener up                         self=enode://4516d853a65dd7ebffa95dc78c2907a5af350d3819d46af827f2587fde7057d625ba8ccc3d6cdeddc2b53adc84691c92b2815db88a46112b54c81fdd8f093813@[::]:30303
INFO [06-21|11:43:26] IPC endpoint opened: \\.\pipe\geth.ipc

**Comment by evertonfraga** [comment]
Hi @PlantDr430, let's tackle this by parts:

**address not showing on browser**
The wallet only shows accounts handled by its own instance. That's sort of wrong, I know. As the wallet works right now the url serves only as an internal route, not to see any other addresses. 

If you want to give permissions to the browser (assuming you are using MetaMask) you can export your account on Mist (`Accounts > Backup > Accounts`) and import it on MetaMask Chrome plugin. 

**node  stopped syncing**
that's not cool indeed. You may want to download the latest geth from [here](https://geth.ethereum.org/downloads/), close Mist, and start geth separately: 

`geth --fast --cache 2048`

If the problem persists, please refer to Geth repository for solutions, or open an issue there: https://github.com/ethereum/go-ethereum/issues?utf8=%E2%9C%93&q=is%3Aissue%20sync%20stuck


I'll close this for now, feel free to discuss Mist related issues here. Thanks!
