### ISSUE TITLE
Wallet Not Mining on Testnet

### ISSUE THREAD

**Issue by n23khan** [ethereum/mist#2589]
It's been 3 hours of mining and there's no ether being created.
Geth 1.6.5.
![ew](https://user-images.githubusercontent.com/5874698/27405002-f104ef7e-569d-11e7-8ad7-63ce1b9fb0a3.JPG)

**Comment by evertonfraga** [comment]
Hi @n23khan, you are probably using the Ropsten network, which had its difficulty level increased not so long ago. It may take some time to mine indeed. 

We have some options from here:

**first**
get some ether via an "ropsten faucet" (google this for more options)
http://faucet.ropsten.be:3001/

**second**
use Rinkeby, another test network, with its own faucet mechanisms. 
1. Go to https://www.rinkeby.io 
2. read the sections "Connect Yourself > Mist" and "Crypto faucet" to know how to proceed.

I'll close this for now. Thanks!

**Comment by zenos1337** [comment]
I'm also having the same problem.  For some reason, at first, it was working fine and managed to mine close to 200 Ether, then something happened and it started downloading the entire blockchain again and my balance went back to 0.  Now when I mine, nothing happens and it's been several hours.  I also tried http://faucet.ropsten.be:3001/ several times and still nothing... I double checked to see if my wallet was fully synced with the network and it definitely is.  I can't find any answers online.

**Comment by joseramz** [comment]
i have the same issue, i click on "Empezar a minar" (start to mining) but nothing happen. If i ask for ether from http://faucet.ropsten.be:3001/ nothing too

**Comment by inayat82** [comment]
I have same issue nothing happen

**Comment by sfiguereo** [comment]
I am having the exact same issue.  If any  one has solved this please advice.
