### ISSUE TITLE
still having problems with node ETH

### ISSUE THREAD

**Issue by oldpoison** [ethereum/mist#259]
my money still freeze :(  ![image](https://cloud.githubusercontent.com/assets/17651457/13550645/56185e82-e2d7-11e5-8732-e0126f4d01ff.png)

**Comment by oldpoison** [comment]
my plattform its 64 bits and it says 32bits

**Comment by alexvandesande** [comment]
Can you open the folder at `%APPDATA%/Ethereum/` and copy the files named `logs`?

**Comment by frozeman** [comment]
@oldpoison it seems like a connection error, do you have a firewall on?

concerning the "win32", thats what linux tells me, thats not the bit version thats the name for all windows platforms in node.js

**Comment by luclu** [comment]
Pooling with other issues regarding the `eth`-backend: https://github.com/ethereum/mist/issues/607
I will close this for now.
