### ISSUE TITLE
Danger!!! stragety for sending eth

### ISSUE THREAD

**Issue by jackyxie** [ethereum/mist#2591]
#### System information
``````
Version: `0.8.10`
OS & Version: linux
Node type: `ethereum wallet`
``````
The picture below shows two pending transactions, brocasting several minutes ago(current time: 2017-06-22 15:40 +GMT8), but autally I sending out these two tx yeasterday (time: 2017-06-21 11:18 +GMT8)
![20170622154253](https://user-images.githubusercontent.com/3347704/27422814-1e2c0b94-5762-11e7-906d-45e959a40a67.jpg)

It's very danger for user to use when the ethereum network is busy, and user will may lose their coins if they resend their eth to other people.

**Comment by evertonfraga** [comment]
Hi @jackyxie, thanks for the suggestion. Indeed, sending a transaciton is different from pushing a button on an electronic appliance, for instance. If it didn't went through at first, be cautious to send it again. 

We have improvements on pending transaction list in the near future. Tune up for those updates. 
 I'll close this for now, as it is being addressed. thanks!
