### ISSUE TITLE
Allow user to send a transaction of 0 eth (other wallets support this) 

### ISSUE THREAD

**Issue by mschueler** [ethereum/mist#2600]
Useful for fulfilling contracts, testing, doesn't violate standard/RFC/specs as far as I know.

Parity/Mews supports this

**Comment by Phoenix1969** [comment]
0 cost tx's = massive spam, and the network is already overloaded.

**Comment by alexvandesande** [comment]
You can send transactions with 0 ether if you add some data to it. If you want more fine grained control you can always create your own transactions using web3
