### ISSUE TITLE
How to pass command line options to geth?

### ISSUE THREAD

**Issue by ET-Bent** [ethereum/mist#2603]
#### System information
``````
Version: `0.8.10`
OS & Version: linux
Node type: `eth/geth(default)`
``````

As far as I know there are no config files for mist that allow to pass any command line arguments to geth. 

Is there any other way to pass command line arguments to geth when starting mist ("openning Ethereum Wallet")?

**Comment by evertonfraga** [comment]
It's on our Readme: https://github.com/ethereum/mist#passing-options-to-geth

Closing this for now. Thanks
