### ISSUE TITLE
Text in Ethereum-Wallet-linux64-0-5-1 on Ubuntu 15.10 looks messed up.

### ISSUE THREAD

**Issue by qm3ster** [ethereum/mist#261]
![image](https://cloud.githubusercontent.com/assets/10551234/13551314/f7b34b06-e33d-11e5-82ea-a389441f92c4.png)

Is there a font I need to install?

**Comment by Phistr90** [comment]
Whats wrong with it?

**Comment by qm3ster** [comment]
The problem is visible in the picture. Those are not compression artifacts, that's what the text actually looks like. It's partially covered with white flakes and is barely readable. No such problem on the same monitor under windows (the apparent size of text is the same)

**Comment by frozeman** [comment]
@alexvandesande the text is a bit to thin i'd say. (If everybody just would have a retina display :) )
Also the font rendering differs a lot on different OS

**Comment by alexvandesande** [comment]
I'll increase font weight in some cases then

**Comment by qm3ster** [comment]
Well, it's the same 2560x1440 monitor in both cases, and as I said, visually appears to be the same size.
