### ISSUE TITLE
Wrong password Ethereum wallet & Mist 

### ISSUE THREAD

**Issue by Lucianovd** [ethereum/mist#2610]
Hey guys/girls,

A week ago I started with the myethereum wallet downloaded from Ethereum.org. When I openend the app it asked me to insert a password and so I did. While it was syncing (what took a while) I already ordered my first ether and send it my wallet. This was the main account wallet, I changed the name of this wallet in the meanwhile a few times and added a wallet since I was playing and discovering the new app. Then I closed my laptop a few times since syncing took so long. In the end I started my laptop again and let it fully sync, the ether was stored in my wallet.

Now today I downloaded the mist wallet and on itself it added the wallets that I had stored on my computer, it recognised the keys on itself. Then it showed a error one time something had to with geth, I don't remember fully what it was. Now when I tried to transfer ether it said wrong password all the time. I am 99.99% sure I am not typing a wrong password. Does anyone know what I can/might be? Are there any known bugs with this problem? I have seen on some forums that more people have a similar problem, knowing for sure that they are not entering the wrong password.

Oh yeah I am running on a macOS Sierra

Thanks in advance!

#### System information
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth(default)`
``````

#### Please check the **already existing** issues to keep duplicates at a minimum.
Furthermore several **work-arounds** have been collected in the [Mist-Troubleshooting-Guide](https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide).

If possible add the following to your report:

- Screenshots

- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot

- Log files 
  - go to `menu -> accounts -> backup -> application data`
  - zip and upload `node.log` and all other `node.log.X` files

**Comment by account-archived-0** [comment]
lost my program-generated 100-length password too. really weird. I'm pretty sure it is the right password.

**Comment by zhangyongjiang** [comment]
Got the same problem.

**Comment by zhangyongjiang** [comment]
I got the same problem. But eventually it turns out that I was using the wrong password. After tried about 1000 passphases, I finally found the right password. I recognized the passphase.

**Comment by account-archived-0** [comment]
related: https://github.com/ethereum/mist/issues/2077

**Comment by sdiman** [comment]
I got the same with this wallet! I have MacOS. and i generated the pass with pass manager.

**Comment by sdiman** [comment]
Solved it.I sent my money finally from this wallet. If you using Mac OS, and have similar problem, contact me in skype (steals88). 
Im not sure about windows users

**Comment by Madebyivan** [comment]
@sdiman Do you know something that others who have water around their neck do not know ??? Could you please explain your knowledge, if you are so kind ???
Thank you

**Comment by evertonfraga** [comment]
Hi @sdiman, I am one of the developers of the project. Mind sharing how did you solve that?

@Lucianovd @archywilhes to reproduce this issue and help you guys, I, please ask you to answer this set of questions, so we can outline the problem and move on. Please fill out the form thoroughly.
https://goo.gl/forms/jznmHV6Fpui7Ijds1

Let's move the conversation to this single place: #3513

Thank you.
