### ISSUE TITLE
Internal Refund Trasnsfer Status ICO failure!!

### ISSUE THREAD

**Issue by Migson51** [ethereum/mist#2611]
Hi there, This is my seccond transaction to the Status ICO campaign. As you can see the 200000 gass is correct as well as the max 50 gwei. So there's no reason for the bouncing. Can anyone tell me why this contract blew up in my face and resulted in a refund (without return of fee)
Please let me know!

Kind regards,

Miguel Rewinkel

![dsc_0206](https://user-images.githubusercontent.com/29603732/27498322-d2b52fd0-585e-11e7-8f8f-f3b946659290.JPG)

**Comment by evertonfraga** [comment]
Hi @Migson51, 

That issue is about Status and their refund policies, and Mist has actually nothing to do with it :)
Please get in touch with their support. 

Thanks!
