### ISSUE TITLE
Send token button not working as expected

### ISSUE THREAD

**Issue by diegueins680** [ethereum/mist#2613]
``````
Version: `0.8.10`
OS & Version: osx
Node type: `geth`
Number of blocks synchronized: 3919863
``````
 -->
When I click on one of the send buttons of the tokens that I hold in my Mist wallet, I expect a dialogue ready to send that specific token. However, what's opened, is a dialogue ready to send ETH. This is very dangerous for the users.

For instance, today I meant to send some SNT tokens to my father, so I clicked on the send button next to SNT, and after the send dialogue opened, I punched in the amount of SNT I meant to send, and quickly proceeded to enter my password and send the transaction. However, I now realize that when you click on any of the send buttons next to the tokens' names, you get a dialogue with ETH as the selected currency you're gonna send. To my dismay, I discovered that I had sent a quite high value in ETH, instead of the comparatively small value in SNT. I was lucky that the recipient was my father, and that he returned the ETH to me. I'm scared to think how much money I would've lost if the recipient was an unknown/dishonest person who refused to return it.

In any case, you shouldn't need to click on the name of the token again if you already clicked on the send button next to the name of that specific token.

<img width="920" alt="greenshot 2017-06-23 16 56 34" src="https://user-images.githubusercontent.com/2753581/27501778-10d8811a-5835-11e7-8bea-fb0b555b3387.png">
<img width="752" alt="greenshot 2017-06-23 17 30 32" src="https://user-images.githubusercontent.com/2753581/27502506-21069536-583a-11e7-8775-22073f845f21.png">

**Comment by alexvandesande** [comment]
This issue has been solved. Thanks for the report.
We are reviewing at old unanswered issues, sorry it took so long to reach yours, it's a long backlog.
