### ISSUE TITLE
5 Ether never transferred from Poloniex

### ISSUE THREAD

**Issue by mitchjohnstonson** [ethereum/mist#2617]
3+ Days ago I finished downloading Ethereum Wallet, and immediately tried transferring Ether from Poloniex.  The address is correct, I received a confirmation email, and it's marked as complete in the trade history:

Complete	ETH	5.00500000
2017-06-21 13:32:53
Address: 0xAC2F96355756375E9cb81BFA2AD8220d951696cA
Txid: 0x92b98026e361ed3f15c22871d4bb221679dfe8fa6d05055289d0e4d64a5c2099
 
All the blocks have been sync'd and I've also sent 1 Ether from Coinbase, and that has come through.

All this happened during the Civic ICO, so the network was definitely experiencing some issues, but it should have gone through by now.  Does this mean my Ether are gone?

``````
Version: `0.8.10`
OS & Version: Mac OS Sierra
Node type: `ETH`
Number of blocks synchronized: 3,923,485
``````

**Comment by sathishvj** [comment]
From what I am seeing now, it looks that particular transaction failed for some reason (probably because the network was clogged then).  But transactions seems to have gone through since.  So, are you ok with this?

**Comment by mitchjohnstonson** [comment]
I just noticed yesterday that the coins have come through.  It took about 5
days.

**Comment by sathishvj** [comment]
Usually it is quite quick.  The reasons it might have been slow are because of a network congestion which has been around for the last few days or a very low gas price was set and miners took quite a while to get to it.  In any case, congratulations on getting them.  

Also, you can close this ticket if it is sorted out.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
