### ISSUE TITLE
What problem?

### ISSUE THREAD

**Issue by MasteSteve** [ethereum/mist#262]
![default](https://cloud.githubusercontent.com/assets/17682687/13552669/9ebdd344-e3a7-11e5-808b-4982ac77c5fd.PNG)
What problem?

**Comment by MasteSteve** [comment]
All the problem is solved! I deleted the entire folder "chaindata" i'm again download block-_-

**Comment by alexvandesande** [comment]
Duplicate of 
https://github.com/ethereum/mist/issues/263
