### ISSUE TITLE
Ethereum Wallet not showing current balance

### ISSUE THREAD

**Issue by cboos82** [ethereum/mist#2626]
``````
Version: `0.8.10'
OS & Version: windows/
Node type: `eth'
Number of blocks synchronized: 


I have transferred Ethereum from my coinbase account, to my wallet.  When i check the MyEthereumWallet website with my private key, my balance shows the transfer.  However when i check my actual wallet on my laptop, it never updates.  The account icon is the same, as well as the public key address for the account.  It just stays at zero.  What the hell am i missing?  This is really annoying, and i'm hoping i have a knowledge gap on how the local wallet on my machine works.  

* the wallet on my laptop has 2 accounts, both always show zero.

Thanks
Casey

**Comment by shlomogoldblatt** [comment]
same problem and no help/advice from ethereum support

**Comment by cboos82** [comment]
** Update ... the "blocks left" portion on start up is going so slow it will realistically never finish.  So the total blocks left is over 3 million.  I'm assuming since it does not have the latest block chain, that my balance is still showing the initial amount from back when i opened it.  

This is still taking forever for no reason, but i can't find any major consensus this is happening to lots of people.

**Comment by sathishvj** [comment]
The entire chaindata is very large running into tens of GBs.  So this will take time.  If you have specific issues, you can also try the ethereum troubleshooting guide: https://theethereum.wiki/w/index.php/Ethereum_Wallet_Syncing_Problems

In the meantime, you can always use the account via MEW: https://www.myetherwallet.com/

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Comment by sarafreijeh** [comment]
i used my ether wallet to send ethers to DGTX... I used the wrong address for DGX and the ethers deducted from my account but it's not showing any numbers in my wallet. and now i dont know how to track the token and i dont to know how to turn them back... Any help?
