### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by allmails888** [ethereum/mist#263]
http://s29.postimg.org/iw9rrs8o7/mist.png

**Comment by alexvandesande** [comment]
Looks like a Geth issue. @karalabe can you look into it?

**Comment by alexvandesande** [comment]
How much RAM do you have? Also can you please open the wallet, go to accounts > backup > app data and get the latest log on the `log` folder?

**Comment by allmails888** [comment]
I have 6gb of ram.

sorry cant see any log folder in the path led to

**Comment by obscuren** [comment]
We require more information in order to see what's going on. The amount of data captured by log capture thing should be increased. A suggestion would be to redirect all output on `stderr` and `stdout` to a file and have users upload that.

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
