### ISSUE TITLE
Waiting more than two days for Ether

### ISSUE THREAD

**Issue by Francois87** [ethereum/mist#2631]
I bought Ether on Friday 23 June with Bitcoins, today, 26 June it has still not shown up in my wallet. Is it still stuck somewhere?
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by peterplus1** [comment]
You probably have to wait for synchronization, but you can check your wallet with other services.

For example with https://myetherwallet.com :

- On the right side it says "Use your Keystore File (UTC / JSON) to access your account.".
- Find the file here: "C:\Users[your name]\AppData\Roaming\Ethereum\keystore" and select that.
- Enter your password if you enabled one, and you should see your wallet value.

**Comment by Francois87** [comment]
Thanks Peter

This wallet is up to date! I think the other program is a bit slow or unresponsive.

Kind regards
Francois-Jacques Malan

Brand Ambassador I Simonsig Wine Estate
Tel: +27 21 888 4934 I Cell: +27 72 658 4885 I Fax: +27 21 888 4909
PO Box 6, Koelenhof, Stellenbosch, 7605, South Africa
www.simonsig.co.za<http://www.simonsig.co.za>

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
