### ISSUE TITLE
Totally new at this and seeking advice.. Bought ether before sync and can't access wallet..

### ISSUE THREAD

**Issue by squibbler00** [ethereum/mist#2637]
``````
Version: `1.6.5`
OS & Version: OS El Capitan 10.11.6 & Window 10
Node type: `eth/geth`
Number of blocks synchronized: - 
``````
I've been trying for two weeks to figure this out and I think I found a solution, but I want a second opinion.  As I mention in the title, I bought an ether token using Mist before allowing it to sync, and I realize now that that was a mistake.  Mist is constantly getting stuck syncing, I've tried on my Mac and on Windows, and also with Parity in the background on Windows.  I've tried deleting the blockchain and starting over.  I've waited up to ten days, wherein over 40gb were downloaded and it was still showing only 30% and downloading at a snail's pace.  I'm a little frustrated, but here's what I want to do about it:

I created a wallet using MyEtherWallet, and when I put my backup keystore files from Mist in the MEW keystore folder, the ether shows up in the wallet.  That seems to me to solve the issue in some respect - Can I know send the ether from MEW, or will that cause a problem because the ether was never officially sent to that wallet in the blockchain?  If that is the case, is there any way to access my ether without having to sync Mist?

Please forgive my ignorance, I'm practically an infant when it comes to this stuff..

**Comment by sathishvj** [comment]
If the balance is showing on the account in MEW, then it is good.  You can also send from MEW.  

Mist runs a full node and has to sync the entire blockchain which could take time.  Yes, others also have faced similar starting issues.  But since there are tools like MEW, you don't necessarily need a full node to transact.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
