### ISSUE TITLE
Norton Power Eraser says mist.exe is bad

### ISSUE THREAD

**Issue by piaras88** [ethereum/mist#2638]
``````
Version: `0.0.0`
OS & Version: windows/linux/osx - Windows 10
Node type: `eth/geth` - eth
Number of blocks synchronized: 0
``````

**Comment by piaras88** [comment]
Brief: Attempting to find issue with ethminer.exe stop working on windows 10 (i.e. Windows found a problem and shut down ethminer.exe) the CLI stops at the point of "grabbing the DAG for #2228076..." 
This is a sudden unexpected result from a working system.

Did a Norton Power Eraser scan and it came back with mist .exe  "bad" and wants to remove it ?

Can you assist with either of these matters please?

**Comment by sathishvj** [comment]
I wouldn't know well about this but still ... Norton Power Eraser might not have whitelisted this app.  You could probably ask them to.  On the other hand, if you fully trust the app and you've verified the executable, then you might be able to whitelist the app yourself.  I would suggest you be cautious and careful in the latter case and do it only if you know what you are doing.

**Comment by evertonfraga** [comment]
Hi @piaras88, this project takes care of Mist browser and Ethereum Wallet. **ethminer** is not part of our responsibilities. Please get in touch with ethminer developers.

Thanks
