### ISSUE TITLE
Mist 0.5.1 synchronization problem on Windows

### ISSUE THREAD

**Issue by Zoelae** [ethereum/mist#265]
I'm running Mist on Windows 10. I have been trying to download the blockchain since two days ago and the process is too slow and cumbersome. I switched off the firewall and I set the clock and I started the client. Although, when I start the client I reach 10-20 peers, this number drops, and most of the time is between 0-4. I set again the clock, but this does not improve. Thus, I restart the client. Initially it was faster, now it seems to be very slow (< 25-256 blocks/min). Sometimes it gets stuck. No special error in Geth, only when the peer number drops to 0, it appears a synchronization error. Until now I got 772649 of 1108410. Any idea?

**Comment by frozeman** [comment]
@fjl @karalabe This is with the latest geth 1.3.5 under windows.

**Comment by luclu** [comment]
related: #439
Updating to SSD helped - though this might not be the real solution.

**Comment by luclu** [comment]
I will close for inactivity. Make sure to update to the latest version. Feel free to come back for further discussion.
