### ISSUE TITLE
Mist 0-8-10 sync since 19 days, yesterday 98 % today i have to start new?

### ISSUE THREAD

**Issue by Arnie8** [ethereum/mist#2652]
``````
Version: `0.8.10`
OS & Version: windows7 64bit
Node type: `eth/geth`
Number of blocks synchronized: today 98 % ,10 minutes later it started by 66 % again?

- After a restart of my pc, Mist dont start. 
![mistfail](https://user-images.githubusercontent.com/28608726/27648271-4f730cf4-5c2e-11e7-9bca-ee4ee6461e48.PNG)
- i started the node manually, like this:
    Open cmd.exe
    Navigate to geth directory by running cd %APPDATA%\Mist\binaries\geth and look for geth.exe
    Execute the following command: geth.exe --fast --cache 1024
- it worked
- now the applicaton starts also, i can see my 2 ETH, puh  :-)

question 1
- but 7,348 blocks left , and i see the cloud with 3 %, why 3 % ? 
In the beginning there were 33000 blocks or more to download, i think, but i m not sure.
I think i have maybe 70 % of the blockchain downloaded, is this correct?
question 2
why mist dont ask me for a password?

question 3
as i started the node in the cmd, i read in the beginning: warn, blockchain not empty, fast sync disabled. 
Is this because i have already downloaded a part of the blockchain? and can i change it to fast?

Thanks for help and sorry for my english

**Comment by avicena1** [comment]
use geth --fast

**Comment by Arnie8** [comment]
use geth --fast ?
Execute the following command: geth.exe --fast --cache 1024
i ve done this.  block 7000 to block 6000 my pc need 8 hours, is this fast or slow? Thx for comments

**Comment by Arnie8** [comment]
Hi, ok the only big problem was, i have a regular disk, 10 years old, 8MB/s, thats the reason for the slow sync. I go and buy a SSD HDD. :-)

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
