### ISSUE TITLE
I can't install ethereum wallet in my MAC , is been 8 days sync

### ISSUE THREAD

**Issue by luimon5** [ethereum/mist#2656]
Hi there, i've been downloading ethereum wallet for 8 days already and it never finishes syncing, i don't know what to do, there is a message
![screen shot 2017-06-28 at 11 20 50 pm](https://user-images.githubusercontent.com/29767068/27671474-915d6332-5c59-11e7-9e38-6e8d5dc66084.png)
 appearing after i click launch that says this>

![screen shot 2017-06-28 at 11 20 50 pm](https://user-images.githubusercontent.com/29767068/27671425-466ca806-5c59-11e7-9bf1-d9c1725189f6.png)

i am not computer engineer so i dont know whats is the IPC and were should i unlock or add this Geth. Please if someone can help me to do it i deeply appreciate it, i have some ETH sent to this wallet and i only check by etherscan.io.

thks a lot 
![screen shot 2017-06-28 at 10 14 47 pm copy](https://user-images.githubusercontent.com/29767068/27671516-e5dac1ca-5c59-11e7-92ea-c9fb47af2452.png)

``````
Version: `0.0.0`
OS & Version: windows/linux/osx> OSX EL CAPITAN
Node type: `eth/geth`
Number of blocks synchronized: 1750000

``````

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
