### ISSUE TITLE
New Wallet did not receive BTC transfer

### ISSUE THREAD

**Issue by bkjwashere** [ethereum/mist#2657]
Do I simply need to wait for the blocks to synchronize, or do I need to do something?

Version: `0.8.10`
Windows 10
Node type: `eth/geth`
Number of blocks synchronized: 808,622 if 3,946,238
``````
From GDAX:
withdraw
05:26:34 am - Jun 29, 2017 UTC
0.03202754Complete
Transfer ID: a774d2b5-71d7-4c42-947c-bf465f9b1a61
Estimated Payout:
01:58:19 am - Jun 29, 2017 UTC
BTC transaction hash: 4db7c571fcfcd0323d2a14a02d909b7c001a06c8decc860e581cccca16dafc4f

![deposit_window](https://user-images.githubusercontent.com/29713333/27673567-62afe8f0-5c6f-11e7-9463-cba71070980a.JPG)
[node.zip](https://github.com/ethereum/mist/files/1111022/node.zip)

**Comment by bkjwashere** [comment]
It appears the downloading of blocks is frozen.  It has been stuck on 808,622 for several hours.  Should I fix that first?  If so, how?

**Comment by zboneh** [comment]
New Wallet did not receive ETH transfer,
0x0eA415B4574F5204eBea642DD9430967A35b70A6

**Comment by bkjwashere** [comment]
I'm aware that it didn't receive it.  I'm wondering why?

**Comment by zboneh** [comment]
It's taken me 6 weeks to download and here is some screen shots of the two transaction and a shot of the wallet.
[Doc1.docx](https://github.com/ethereum/mist/files/1114030/Doc1.docx)
[Doc2.docx](https://github.com/ethereum/mist/files/1114031/Doc2.docx)
[Doc3.docx](https://github.com/ethereum/mist/files/1114033/Doc3.docx)

**Comment by peterplus1** [comment]
Your transactions are part of the end of the blockchain, so yes, you have to wait for synchronization. You can check your wallet with other services.

For example with https://myetherwallet.com :
- On the right side it says "Use your Keystore File (UTC / JSON) to access your account.".
- Find the location here: "C:\Users\[your name]\AppData\Roaming\Ethereum\keystore" and select that.
- Enter your password if you enabled one, and you should see your wallet value.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
