### ISSUE TITLE
Ethereum Wallet

### ISSUE THREAD

**Issue by IvanM1993** [ethereum/mist#2659]
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````
Hi all. For the second week is not a normal sync. To 2, 200, 500.... blocks are loaded very quickly. But now all the time.. screenshot below. Finds 2 peers, but then again looking for the past two weeks. Who that will advise? 
![default](https://user-images.githubusercontent.com/29419674/27695100-9e81ac4c-5cf6-11e7-9af3-8652deb82a23.png)

**Comment by kkaluza** [comment]
So it doesn't work? What are we to do?

**Comment by kkaluza** [comment]
I have the same problem?

**Comment by sathishvj** [comment]
You could try these pages:
https://github.com/ethereum/mist/wiki
https://theethereum.wiki/w/index.php/Ethereum_Wallet_Syncing_Problems
