### ISSUE TITLE
Downloading "appears" to be stuck close to the end.

### ISSUE THREAD

**Issue by klmoney** [ethereum/mist#266]
When doing a fresh installation of 0.4.0 and now 0.5.1, I notice the following behavior:
When the downloaded block number gets close to the end (about a couple thousand away), the downloading process appears to be stuck. The downloaded blocks indicator at the bottom right does not change (though peer count may vary slightly). But if you wait long enough, < 1 hour, the downloaded blocks indicator disappears, syncing is done, and the app is ready to launch. There is, otherwise, no indication that anything is going on, processing etc., during this “apparently stuck period”.

Is this the expected behavior?

I have observed this on Windows 7.

**Comment by klmoney** [comment]
Just saw this. Related?

http://ethereum.stackexchange.com/a/1800/192

**Comment by frozeman** [comment]
Yes thats the reason, we use fast sync which process state later and first downloads blocks.

We will improve the sync screen once i have a better api
