### ISSUE TITLE
Help: Transferring Ethereum Wallet Account from one PC to another

### ISSUE THREAD

**Issue by AndrasL** [ethereum/mist#2662]
Version: `0.0.0` (Newest I believe)
OS & Version: windows 10
Node type: `geth`
Number of blocks synchronized: 3,948,695

Question about transferring ethereum from Coinbase to an Ethereum Wallet. Any help or advice would be greatly appreciated!

Basically, I purchased Ether on Coinbase. I was advised to transfer this to a wallet on my computer, which I did. 

I downloaded Ethereum Wallet, and set up an account which provided me an address. This was all without completing the blockchain sync. I transferred the ether from Coinbase to my address. My ethereum wallet doesn't reflect this, however, when I checked with etherscan.io, the transfer is complete/verified.

Seemingly, the ethereum wallet just won't fully load on the computer.

So, I installed the ethereum wallet on another computer, on which I have been fully able to sync the Blockchain.

Thus, my question is, "how do I transfer the ethereum wallet account from one computer to another." I haven't been able to find a wallet file, nor any similar questions in the github repository.

Does anyone have suggestions as to how I could access this ether? Please let me know if there's anymore information I could provide that would be helpful.

**Comment by peterplus1** [comment]
I'm pretty sure you can just copy the keystore to your other computer, it can be found here: "C:\Users\[your name]\AppData\Roaming\Ethereum\keystore"

**Comment by AndrasL** [comment]
Perfect; I'll check that out and let you know if that works

**Comment by AndrasL** [comment]
There's no such folder as "AppData" on that computer.. Any other ideas?

**Comment by AndrasL** [comment]
Nevermind, I was able to access it thru Mist, thru Accounts -> Backup -> Accounts.. The folder might be hidden?

**Comment by sathishvj** [comment]
It's not hidden.  You can also browse to the dir.  Make sure you backup your keystore files (i.e. the files in that folder), without which you won't be able to recover the account details in case you lose the computer or something similar.
