### ISSUE TITLE
Ether not deposited but says successful withdraw from Kraken... 

### ISSUE THREAD

**Issue by tobydaniel2** [ethereum/mist#267]
I was wondering where my 101 Ether went. I copied my Mist wallet address and pasted it in Kraken. Did I do something wrong? Here are the photos of what I did. Thank you.
<img width="860" alt="screen shot 2016-03-06 at 8 57 20 am" src="https://cloud.githubusercontent.com/assets/17688853/13555589/41618910-e3bc-11e5-967f-633687a670e2.png">
<img width="559" alt="screen shot 2016-03-06 at 8 58 44 am" src="https://cloud.githubusercontent.com/assets/17688853/13555590/4166fef4-e3bc-11e5-8c26-8bb83598a76a.png">

**Comment by nicksavers** [comment]
I see that the amount was deposited on that account https://etherscan.io/address/0xb20c7f2d1aafd961b1faf1002c48cef3a06934b8 and has since been moved. This issue seems to be resolved @evertonfraga
