### ISSUE TITLE
Balance not showing

### ISSUE THREAD

**Issue by Slijferr** [ethereum/mist#2670]
``````
Version: `0.8.10`
OS & Version: windows 10
Node type: `geth`
Number of blocks synchronized: 3952758 and counting
``````
Hello, I have synced my ethereum wallet till the last block, and it is keeping up.
But I cannot see my balance, so far I have mined around 0.03 ETH, but my wallet still says 0.00 ETH.

Can you tell me how I can make my balance visible?

**Comment by cmashinho** [comment]
same problem

**Comment by Slijferr** [comment]
So what now? Nobody knows a thing about it?

**Comment by JesseBusman** [comment]
Same problem, also version 0.8.10

**Comment by sathishvj** [comment]
Are you mining on the main-net or the test-net?  Though it is not impossible, I would be suspect of the fact that you mined anything at all on the main net on you computer.  

Can you check the balance on etherscan.io/address/0x.... Put your address at the end.  If it is not there also, then your account does not have any balance.

**Comment by Slijferr** [comment]
@sathishvj hello,

When I check the etherscan.io I cannot see my balance (it says 0 ETH).

But when I check my pool, it does say I have balance.
I am mining with the alpereum pool. As you can see below:

![image](https://user-images.githubusercontent.com/10597470/27800486-e2d968be-6019-11e7-9d59-498e508f07e8.png)

**Comment by sathishvj** [comment]
In that case you should be checking with those who run the pool.  

But even so, from the image you posted it appears that they haven't paid it out to you - it's probably the balance that might be due to you in the future.  Paid is showing as 0.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
