### ISSUE TITLE
Can i take my money without sync ?

### ISSUE THREAD

**Issue by ShebanovVadim** [ethereum/mist#2671]
I started the synchronization on May 25.
For the second time, it fell to 0.
How can i transfer my money to normal wallet ?
``````
Version: `1.6.1`
OS & Version: windows
Node type: geth
Number of blocks synchronized: 8.000.000
``````

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
