### ISSUE TITLE
Sync wallet

### ISSUE THREAD

**Issue by IvanM1993** [ethereum/mist#2672]
``````
Version: `0.8.10`
OS & Version: windows
Node type: `eth/geth`
Number of blocks synchronized: 2, 414, 972
``````
Hi all. Why such a slow sync?? 8 hours. >100 block. Reinstalled the new version geth.exe nothing has changed, for 1 hour. 5 blocks very cool?:) for this I looked at the node.log file. When you restart Ethereum Wallet for a long time looking for peers? Tortured to wait.
![default](https://user-images.githubusercontent.com/29419674/27745309-8bd173c2-5dcb-11e7-90b3-395385dc9a0f.png)
![123](https://user-images.githubusercontent.com/29419674/27745320-911fd56c-5dcb-11e7-8dca-d069790f960a.png)

**Comment by arturosanz** [comment]
I have the same problem. It's even worse in Test-Net. It is impossible to synchronize the whole chain. I spend one week and still waiting.

**Comment by evryalos** [comment]
Same problem here. It usually freezes after a certain amount of time and have to close the program and open it again. Sometimes blocks counting lasts for some hours and some other times it lasts for some minutes only.

**Comment by Patrick-W-McMahon** [comment]
I can't get the wallet to sync on main or testnet

**Comment by cheddle** [comment]
same issue here - my wallet sits at 'Looking for peers' for some time, finds 1 or maybe 2-3 peers. then it begins to download blocks

I'm stuck at 2,447,024 out of 3,956,215

SORELY regret choosing this wallet... costing me...

**Comment by arturosanz** [comment]
It seems that either in main or in tesnet it is not able to sync more than 75%. The same happens in a torrent service when there are not enough seeders for a specific file. How can this happen to Ethereum?

**Comment by NicolasConstant** [comment]
Same here, needed to relaunch Mist multiples times to get it totally sync.

**Comment by monsunek** [comment]
I'm trying to sync it for two weeks now, i have cleared chain few times, i always stuck at 99%.

**Comment by ET-Bent** [comment]
Synching the whole chain takes about 4h on decent internet (100+ MBit/s downstream) and a decent HDD (~ 100MB/s).

The speed of synching is highly dependent on your IO too. The sync gets more and more intense at the end of the chain using up to 700 MB/s RW IO on an NVMe ssd.

To speed up the sync you can start the wallet using:

`ethereumwallet --node-maxpeers 256 --node-cache=6144`

to allocate more RAM as cache (6GB) and allow more peers.
(on Linux, Windows may vary)

In case you are stuck -> delete the whole chain (**don't delete your wallet!**) and start again.

**Comment by Arnie8** [comment]
@ET-Bent , hey thank you very much for this info!!  Do you know whre i can find my whole chain?

**Comment by ET-Bent** [comment]
@Arnie8 if you think that I am a trustworthy guy then I can send you a link to my mirrored chain as of today, block `3967621` that you can drop into your geth.

**Comment by sathishvj** [comment]
@Arnie8 chaindata folder for different operating systems: https://ethereum.stackexchange.com/questions/6550/how-can-i-find-my-chaindata-folder

**Comment by ET-Bent** [comment]
@Arnie8 you can find my dump of the chain from today here: [https://dl.ender.io/eth-chain/eth_chaindata_20170703_3967621.tar.gz](https://goo.gl/FsyFkX) (27.5 GB @ block `3967621`). 

If you want to validate your download [use this sha256sum](https://dl.ender.io/eth-chain/eth_chaindata_20170703_3967621.tar.gz.sha256)

**Comment by Arnie8** [comment]
@ET-Bent , yes i think you are a  trustworthy guy :-) Actualy i sync 71 %, (-3,318) block 3959645 , i think the sync will be end this night.  I think its better to wait. If it dont work ( last time it dont work, and i forgot the error massage, anything with pipe... ) i try to download your blockchain, thanks for that. I m not really a nerd :-( I tryed also the sha256linksum, but what i have to do? If i download (eth_chaindata_2017..) its only 104 bytes in the downloadfolder of my browser ?

**Comment by Arnie8** [comment]
@ET-Bent , on the other side, i have to wait for the error massege, cause I dont think mist will work correctly when i copy only the blockchain in the folder. How do you start mist? At first cmd and then the app?

**Comment by ET-Bent** [comment]
if you click this link here [https://dl.ender.io/eth-chain/eth_chaindata_20170703_3967621.tar.gz](https://goo.gl/FsyFkX) then it should immediately start downloading.

**Comment by ET-Bent** [comment]
Also what kind of HDD / SSD do you sync things on ? "How fast is it regarding read and write speeds?"

**Comment by Arnie8** [comment]
My HDD is regular and maybe 10 yaers old, if i start resource monitor i see 7 MB/sec in average :-(
thanks for help.

**Comment by Arnie8** [comment]
your downloading link work now, thx

**Comment by ET-Bent** [comment]
@Arnie8 oh dear. As I have initially written on my HDD with caching and about 150 MB/s RW, a full sync takes up to 8-12 hours. So yeah. With 7 MB/s ... and probably even worse IOPS this can literally take weeks. Even syncing the last few thousand blocks since my dump from today will take you hours.

If you have anything faster use that.

**Comment by Arnie8** [comment]
If the downloading is ready, i replace the files in the ethereum folder? thats all? then i start cmd and geth.exe and then the mist app, and then all things will be ok? :-)  - ah, ok, i see, i will buy a new ssd disk next week :-)

**Comment by ET-Bent** [comment]
after replacing your current chaindata folder with the one from the download you should just have to start Ethereum / Mist app which should run geth automatically.

**Make sure not to overwrite your wallet files, else everything will be lost :warning: **

Then after some time it should show that it's syncing about 2-3k blocks.

SSD :+1:

**Comment by Arnie8** [comment]
@ET-Bent Ok cool, know i know my problem, thank you for help. It is my old HDD. I have had one week befor a crash with mist. After a new start it only start when i open cmd, geth.exe, then i wait for 3 minutes, and then i start the mist app. Only this way :-)

**Comment by Patrick-W-McMahon** [comment]
I was getting out of memory errors my system has 8gig's

On Jul 3, 2017 2:52 PM, "krypto" <notifications@github.com> wrote:

@ET-Bent <https://github.com/et-bent> Ok cool, know i know my problem,
thank you for help. It is my old HDD. I have had one week befor a crash
with mist. After a new start it only start when i open cmd, geth.exe, then
i wait for 3 minutes, and then i start the mist app. Only this way :-)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/mist/issues/2672#issuecomment-312713510>, or mute
the thread

**Comment by ET-Bent** [comment]
@Patrick-W-McMahon most certainly because you added `--node-cache=6144` where `6144` stands for the `MB` for a system with `8 GB RAM (8192 MB)` I recommend using `3072 MB` cache.

**Comment by Patrick-W-McMahon** [comment]
Would be nice if there was a GUI setting to change the memory used by the
wallet.

**Comment by ET-Bent** [comment]
I think UX could be improved in general. But that's another story.

The fact that actually syncing the chain is so "hard" for most people is a major drawback that keeps this technology from triggering down to the masses, unfortunately. (IMHO)

**Comment by Patrick-W-McMahon** [comment]
my solution was open a terminal and run geth -rpc and keep this open. It's
not a great solution.

**Comment by Arnie8** [comment]
@ET-Bent , good morning, thanks fot the download of yort blockchain, it worked ! :-)
And the second thing, i have bought a 500 GB SSD HDD, now he run like a new i7 with 16 GB Ram .
And Mist starts perfectly and is very fast. JUHU :-)

**Comment by ET-Bent** [comment]
@Arnie8 excellent! Glad it worked. I will mirror my latest blockchain today again :)
