### ISSUE TITLE
node.log

### ISSUE THREAD

**Issue by IvanM1993** [ethereum/mist#2673]
``````
Version: `0.8.10`
OS & Version: windows
Node type: `geth`
Number of blocks synchronized: 2, 414, 972
``````
Faced the following problem. Who faced such problem?? 
Block synchronisation started 
WARN [06-30|19:57:24] Synchronisation failed, retrying         err="block download canceled (requested)"

**Comment by powpig** [comment]
I've been trying to get my 0.8.10 w Geth 1.6.6 to sync for the better part of a day,
It took off like crazy, super fast, but bogged down in the final couple hundred and now it just won't finish.
As suggested elsewhere I have tried Opening & Closing Geth on it's own but that hasn't really worked;.
Lots of:
**Node data write error
Stalling state sync, dropping peer
Synchronisation failed, retrying**

Sometimes it'll get past all that and rapid fire:
**Imported new state entries**
but I never get 
**Imported new block headers** 
except right in the first few minutes after I start Geth.

It's incredibly frustrating, I bought some ETH but I don't see it, can't send or spend it and doesn't look like I'll be making the progress I want anytime soon.

**Comment by sathishvj** [comment]
Mist/Ethereum-Wallet requires a full node sync before you can use it.  But you can always use the keystore file (remember to back it up first) on MEW (myetherwallet.com) and transact.

For sync issues, you can try these links:
https://github.com/ethereum/mist/wiki
https://theethereum.wiki/w/index.php/Ethereum_Wallet_Syncing_Problems
