### ISSUE TITLE
BTC to ETH completed but ETH not show in Mist wallet 

### ISSUE THREAD

**Issue by kleetran** [ethereum/mist#2677]
Hi everyone. I'm a newbie in ETH market and seem to have lost my ETH in the first transaction with Shifty on Mist wallet.
I open a new Mist wallet. I use "Fund with Bitcoin" button on my Mist wallet to exchange from  0.1080611 BTC to 1 ETH.

On Shifty, I sent  some BTC to BTC address.

This transaction was verified on BTC blockchain. Even though it is listed on https://etherscan.io is completed
But until now, ETH not show in my Mist wallet.

![4](https://user-images.githubusercontent.com/29796929/27759101-ce898eea-5e50-11e7-8e8e-ac0dd943e935.png)

I use Mist win 64 v0.8.10. The peer count stays at 0 and it does not sync after 2 weeks.

I'm really tired of problem in Mist wallet. I haven't ever get any trouble with another cryptocurrency Wallets. Hope it doesn't happen with everyone.

Pleaseeeeeeee to tell me what I should do to find my ETH. Is it possible to send my ETH from Mist Wallet to another wallet (myetherwallet.com or coinbase) although it never synced ? Thank you so much.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
