### ISSUE TITLE
wallet will not sync - sits at IPC endpoint opened

### ISSUE THREAD

**Issue by cheddle** [ethereum/mist#2678]
``````
Version: `0.8.10`
OS & Version: windows
Node type: ``
Number of blocks synchronized: 2,447,021
``````

as per title - after having my eth wallet closed for a few weeks I wanted to take a look at my Monaco tokens however on opening Mist I notice it claims to have connected to 1 or 2 peers however the remaining blocks is unchanged.  

using geth.exe to manually sync the wallet results in the cmd prompt sticking at "INFO [07-01|15:01:30] IPC endpoint opened: \\.\pipe\geth.ipc"

**Comment by arturosanz** [comment]
Almost everybody has the same problem :(((((

**Comment by teddoering** [comment]
I had the same issue, reinstalled mist and geth and now it's not giving this error and is synced up again. Make sure you have a backup of your keys.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Comment by fulldecent** [comment]
If an order of magnitude is not fast enough for you (INF minus 1 is INF) then check out https://github.com/ethereum/mist/issues/3476
