### ISSUE TITLE
Why private net auto detect functionality has been remove?

### ISSUE THREAD

**Issue by EasonWang01** [ethereum/mist#2679]
version: v0.8.10

Old version after I start private net by 
```
geth --ipcdisable --rpc --rpcport 8103 --datadir "./privatechain/04" --networkid 123 --rpcapi="db,eth,net,web3,personal" --nodiscover --port=30308 console
```
the mist will auto detect and connect to the node after click the mist launch icon.
But now we need to using `<mist path> --rpcport 8103`

**Comment by ucfyao** [comment]
How did you handle it，I can't connect to my private chain

**Comment by evertonfraga** [comment]
8103 and 30308 are not the default port read by Mist. 

They are 8545 and 30303 respectively.
