### ISSUE TITLE
Missing ETH from my wallet

### ISSUE THREAD

**Issue by mightynoosh** [ethereum/mist#2680]
I'm not very technical so please bear with me. I have a deposit missing from my wallet, that is showing up on EtherScan. I updated EthereumWallet today to v0.8.10. **Deleting the 'chaindata' file did not work.** Please, please help!

``````
Version: `0.8.10`
OS & Version: osx 10.12.5
Node type: `geth 1.6.6`
Number of blocks synchronized: ?
``````

**Comment by R3FR1DG3R4T0R** [comment]
I think you have to wait for the whole ting to sync. Then the coins show up

**Comment by mightynoosh** [comment]
<img width="402" alt="screen shot 2017-07-02 at 09 29 16" src="https://user-images.githubusercontent.com/18736510/27768347-f38875fe-5f08-11e7-98ed-63191db5030d.png">
20 hours later and the blocks have synced (I think) but now it won't progress past this 'Connecting to x peers' stage :-(

**Comment by mightynoosh** [comment]
Problem fixed. Just had to wait it out :-)

**Comment by mightynoosh** [comment]
Thank you, it worked once I waited!
