### ISSUE TITLE
Lost bitcoins

### ISSUE THREAD

**Issue by richardvanerp** [ethereum/mist#2685]
i lost bitcoins when i wanted to buy some ethereum how can i get it back or is it gone for ever

**Comment by ET-Bent** [comment]
This is completely unrelated to ethereum wallet.

short: > they are gone.

close?

**Comment by richardvanerp** [comment]
no its not i used the ethereum wallet to buy the ethereum.

so please dont close the ticket.


________________________________
Van: Bent <notifications@github.com>
Verzonden: maandag 3 juli 2017 11:01
Aan: ethereum/mist
CC: richardvanerp; Author
Onderwerp: Re: [ethereum/mist] Lost bitcoins (#2685)


This is completely unrelated to ethereum wallet.

short: > they are gone.

close?

**Comment by ET-Bent** [comment]
How did you buy ethereum using the ethereum wallet? The wallet just holds your ETH. And what have Bitcoins todo with your Ethereum?

**Comment by richardvanerp** [comment]
There is a option in the wallet to buy ETH you can use  paypal or your credit card or you can buy it with bitcoin. i took a picture from google so you can see what i mean.

if there are more things unclear just mail me.




________________________________
Van: Bent <notifications@github.com>
Verzonden: maandag 3 juli 2017 13:22
Aan: ethereum/mist
CC: richardvanerp; Author
Onderwerp: Re: [ethereum/mist] Lost bitcoins (#2685)


How did you buy ethereum using the ethereum wallet? The wallet just holds your ETH. And what have Bitcoins todo with your Ethereum?

**Comment by ET-Bent** [comment]
For me there is no PayPal option.

But if you used ShapeShift.io to do that then you might want to contact them.

**Comment by richardvanerp** [comment]
I will try that thank you very mutch

________________________________
Van: Bent <notifications@github.com>
Verzonden: maandag 3 juli 2017 13:56
Aan: ethereum/mist
CC: richardvanerp; Author
Onderwerp: Re: [ethereum/mist] Lost bitcoins (#2685)


For me there is no PayPal option.

But if you used ShapeShift.io to do that then you might want to contact them.

**Comment by sathishvj** [comment]
If you did 'Fund with Bitcoin', it is a link to the ShapeShift.io service.  It would be best to contact them.

But also, are you sure all the blocks are synced in your mist UI?  If you want to check if your address actually has the balance, you can check it at: etherscan.io/address/0x... put your address at the end.

**Comment by richardvanerp** [comment]
Thank you so mutch i have my ETH but how can i let the wallet sync?



________________________________
Van: sathishvj <notifications@github.com>
Verzonden: maandag 3 juli 2017 14:59
Aan: ethereum/mist
CC: richardvanerp; Author
Onderwerp: Re: [ethereum/mist] Lost bitcoins (#2685)


If you did 'Fund with Bitcoin', it is a link to the ShapeShift.io service. It would be best to contact them.

But also, are you sure all the blocks are synced in your mist UI? If you want to check if your address actually has the balance, you can check it at: etherscan.io/address/0x... put your address at the end.

**Comment by sathishvj** [comment]
It does take quite some time to sync the entire blockchain.  People have also faced intermittent issues in the process.  So you have to let it run for a while - as long as the synced blocks keep increasing, you are fine.

If not, you can check these:
https://github.com/ethereum/mist/wiki
https://theethereum.wiki/w/index.php/Ethereum_Wallet_Syncing_Problems

**Comment by richardvanerp** [comment]
so i just have to keep my Ethereum Wallet open and it wil sync automaticly

________________________________
Van: sathishvj <notifications@github.com>
Verzonden: maandag 3 juli 2017 15:06
Aan: ethereum/mist
CC: richardvanerp; Author
Onderwerp: Re: [ethereum/mist] Lost bitcoins (#2685)


It does take quite some time to sync the entire blockchain. People have also faced intermittent issues in the process. So you have to let it run for a while - as long as the synced blocks keep increasing, you are fine.

If not, you can check these:
https://github.com/ethereum/mist/wiki
https://theethereum.wiki/w/index.php/Ethereum_Wallet_Syncing_Problems

**Comment by sathishvj** [comment]
Yes, typically it should.  If it doesn't progress for some reason, please read up on those links I sent to get an idea of potential issues.

**Comment by richardvanerp** [comment]
How long do you think it will take to sync it

________________________________
Van: sathishvj <notifications@github.com>
Verzonden: maandag 3 juli 2017 15:11
Aan: ethereum/mist
CC: richardvanerp; Author
Onderwerp: Re: [ethereum/mist] Lost bitcoins (#2685)


Yes, typically it should. If it doesn't progress for some reason, please read up on those links I sent to get an idea of potential issues.

**Comment by sathishvj** [comment]
Many hours at best.

**Comment by richardvanerp** [comment]
ha ha ok ill just keep  it running then i guess.

thank you for the help.


________________________________
Van: sathishvj <notifications@github.com>
Verzonden: maandag 3 juli 2017 15:45
Aan: ethereum/mist
CC: richardvanerp; Author
Onderwerp: Re: [ethereum/mist] Lost bitcoins (#2685)


Many hours at best.

**Comment by ET-Bent** [comment]
or have a look at #2672 where I did provide a link to today's chain which will speed up the progress **a lot**.

**Comment by richardvanerp** [comment]
where do i have to put this command: ethereumwallet --node-maxpeers 256 --node-cache=6144

________________________________
Van: Bent <notifications@github.com>
Verzonden: maandag 3 juli 2017 17:59
Aan: ethereum/mist
CC: richardvanerp; Author
Onderwerp: Re: [ethereum/mist] Lost bitcoins (#2685)


or have a look at #2672<https://github.com/ethereum/mist/issues/2672> where I did provide a link to today's chain which will speed up the progress a lot.

**Comment by nicksavers** [comment]
@richardvanerp You enter this in the command line. For more information read this: https://www.davidbaumgold.com/tutorials/command-line/

By the way, if you want more support around Mist and the Ethereum Wallet, you can also use the Gitter channel https://gitter.im/ethereum/mist.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
