### ISSUE TITLE
Error (sudo npm install -g electron-prebuilt)

### ISSUE THREAD

**Issue by luthermarcus** [ethereum/mist#269]
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron-prebuilt/cli.js

> electron-prebuilt@0.36.10 postinstall /usr/local/lib/node_modules/electron-prebuilt
> node install.js

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! electron-prebuilt@0.36.10 postinstall: `node install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the electron-prebuilt@0.36.10 postinstall script.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.2.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "electron-prebuilt"
npm ERR! cwd /home/ubfox
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubfox/npm-debug.log
npm ERR! not ok code 0

**Comment by luthermarcus** [comment]
[npm-debug.log.zip](https://github.com/ethereum/mist/files/160575/npm-debug.log.zip)

**Comment by frozeman** [comment]
your node version is to old, as the errors say. please update

**Comment by luthermarcus** [comment]
I'm runing the latest stable node so that is not the problem.

**Comment by frozeman** [comment]
No if you read the error:
`wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.25","npm":"1.4.21"})`

**Comment by luthermarcus** [comment]
I'm sorry I may have misworded myself I upgraded the node after reading your comment even with the node updated I see the same error.

**Comment by frozeman** [comment]
I can't really help with this issue and it is not an mist issue. I think this is a problem with your node.js installation on your system. Maybe create an issue in the [electron-prebuilt repo](electron prebuilt github)
