### ISSUE TITLE
can´t send etherum to mist

### ISSUE THREAD

**Issue by ikerez** [ethereum/mist#2690]
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````
hello, i can not send ether to my mist wallet, it says error....

Transaction error: broadcastTx error: undefined: request to https://api.etherscan.io/api?address=0xa6ee685E49FF4c132D190A94a84e00CD4Be3087B&module=proxy&action=eth_getCode failed, reason: getaddrinfo ENOTFOUND api.etherscan.io api.etherscan.io:443

can you help me???

**Comment by sathishvj** [comment]
Are you using a tool to send this? Are you trying from some mobile/web/desktop app?  Or are you doing it directly from code?

**Comment by ikerez** [comment]
hello, its ok now, it was a problem from the exodus wallet, i sent from coinbase and it works now. thanks a lot for your answer....

**Comment by sathishvj** [comment]
Ok, you can close the ticket then.  Thank you.
