### ISSUE TITLE
i can't  complete create a wallet contract

### ISSUE THREAD

**Issue by alyfree** [ethereum/mist#2691]
``````
Version: `0.8.10`
OS & Version: windows 10
Node type: `eth
Number of blocks synchronized: 3.968.227
``````

6 month ago
i install the mist than uninstall it and get eth wallet that don' need to install and when open it i saw the address wallet than i start mining for my address and let the wallet making sync its long time don't done
than i make backup and delete it and get installing  version than also get long time any way
i looking on the tools to make password for the wallet no way now i have balance 0.6 eth when i need to make new contract or send eth i can't because it ask me password i don't make it yet
i try to import it get this message........... encoding/hex: invalid byte: U+007B '{'"
i am sure i don't get the message pop up to make password
and i have error in the wallet console 
please help to fix it
[Logs.zip](https://github.com/ethereum/mist/files/1119919/Logs.zip)
![walletcons](https://user-images.githubusercontent.com/6421928/27797883-8af23f86-600f-11e7-84b0-264da8cef9bb.jpg)

**Comment by sathishvj** [comment]
It is impossible to have created an account without giving the password.  It's the password that is used to encrypt the private key for your account.  So the password is the first (and usually the only) thing that is asked when creating an account.

If I remember right, the very first thing asked when you start Mist with no accounts is a password to create an account - it is not a password to the tool but for that account.  Try to recall what you used then.

**Comment by alyfree** [comment]
thank you Mr sathishvj
but i don't forget and i don't Lying i am remember from first time open the unpacked wallet its get to sync
and told me please wait and still wait 2 weeks but i was see the address than i let it to sync an i go to mining to the address so i need to lock my wallet by password but i don't find any method ...than get back up from the key store and delete  this and get the installing and i don't need to import it's open with my main account the same view than i red under the address line (Accounts can't display incoming transactions, but can receive, hold and send Ether. To see incoming transactions, create a wallet contract to store Ether.) i create one than it take long time to creating at once i see message you are about  (create contract ) it ask me password good i write the password after long time waiting so i will lock wallet to save ..but it say wrong password ..haw wrong it very strong ..but it ask me the pass of wallet .....


please i think that error i don't know maybe in the popup message.. what about  error console its normal? (Failed to load resource: net::ERR_FILE_NOT_FOUND      file:///sockjs/info?cb=0e8dp64d99)

don't There is a programing method to see if here password or not....please help

**Comment by alyfree** [comment]
why i see the popup message to make password when make new account on the same wallet but i don't see it at first tome with the main account?

**Comment by sathishvj** [comment]
I can't insist that you forgot, but it is just not possible to create an account in Mist/Ethereum-Wallet without giving the password.  You should probably try all the possible passwords you might have put.

The reason you see the password dialog when you create a new account is the same reason I mentioned - without it, you can't create an account.  It is a necessary step.

There is no way to change the password or recover it from anywhere.

**Comment by alyfree** [comment]
thank you Mr sathishvj
You can tell your opinion even if it is different from reality
But the problem has not been solved...now i make new account and i saw the password message making that i don't see at first time...any way i test more than 80 password i am sure is no way to success any one because the file text that have password of wallets just have five pass for btc and some other wallets and i am already created one for etherum but i don't use it only when i make the new account...again i am sure.
now i sent screen shoot to see the error in console maybe it's the reason . 
and This waiting sign appears on the screen all the time
it's follows me everywhere and I can not hide it
i don't want to uninstall this program and reinstall because thy sync will start from 0 block again 
the chaindata folder will go to 29GB 
what did you say...
thanks
![1](https://user-images.githubusercontent.com/6421928/27880244-9b1bdcbc-61c4-11e7-85ec-bb6790861ae3.jpg)
![2](https://user-images.githubusercontent.com/6421928/27880250-a0d510ce-61c4-11e7-9190-f2db49a5943f.jpg)
![3](https://user-images.githubusercontent.com/6421928/27880258-a74c3e8c-61c4-11e7-8748-a3dcd5d7c693.jpg)

**Comment by alyfree** [comment]
hello
now i created an account number 3 and 4 without password ...and i think it the same my main account but i don't know how i created the main account or what the error ..
the account 3 and 4 created by ( web3.personal.newAccount() ).
and don't popup any password message ....i ask now how to make a password for it.??
the accounts created auto locked without password.
![wp](https://user-images.githubusercontent.com/6421928/27951328-ce9240e0-6304-11e7-8689-fe488368e2b6.jpg)

**Comment by sathishvj** [comment]
https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#personalnewaccount

The new account method takes a password as a parameter. Tools typically have to have a minimum password length. 

If not that, use the Add Account UI button. That should prompt you to enter a password.

**Comment by alyfree** [comment]
ok please what the problem ?  we can make account in 2 methods 
1-web3.personal.newAccount()
2-web3.personal.newAccount("mypasswd")
the talking about method  1 ...because i was think i will create the password later so the address don't have password..
how to make password after the account created 
in method 1 it will create address without password

**Comment by slashusr** [comment]
Same here, rmcluesman

**Comment by user1711github** [comment]
I have the same problem as rmcluesman above

**Comment by j4ys0n** [comment]
Same issue - has said "Creating..." for more than a month. Is there a way to delete this?

**Comment by WurstCommander** [comment]
same here
![image](https://user-images.githubusercontent.com/5268576/35185626-01612d44-fe08-11e7-8e3b-881055a620fa.png)

**Comment by neilbodak** [comment]
i'm have the same same issue,
