### ISSUE TITLE
Start mining (Testnet Only) menu item is disabled.

### ISSUE THREAD

**Issue by vwu00000** [ethereum/mist#2695]
``````
Version: `0.8.10`
OS & Version: windows
Node type: `geth`
Number of blocks synchronized: 1,233,678


The app is synched and has 2 peers. But the Start mining (Testnet Only) menu item is disabled. I can't start mining.

**Comment by sathishvj** [comment]
Are you on the main-net or the test-net?  It will get enabled only if you are on the Test-net: Develop->Network->Testnet

**Comment by vwu00000** [comment]
I am on the test-net.

**Comment by sathishvj** [comment]
Did you start geth from the command line?  And later open Mist/EW?

**Comment by vwu00000** [comment]
No.  How to get geth? (the menu item says geth (1.6.6)

**Comment by sathishvj** [comment]
By default geth is the process that is run by Mist.  If you didn't start it yourself, you can ignore that as it will be taken care of automatically.

Do you have at least one account on the test net?  Maybe you can send a screenshot of your UI.  If not this also, then I do not know what the issue could be.

**Comment by vwu00000** [comment]
I saw geth.exe running in task manager. I have one account.
![image](https://user-images.githubusercontent.com/28719999/27868169-87d4fdc2-6161-11e7-8ac9-22ecd3f59475.png)

**Comment by sathishvj** [comment]
Can you download Mist and try it?  I see that Ethereum Wallet has no indication of mining happening but Mist does.  I think you should see it working with Mist.  It is working for me.

**Comment by vwu00000** [comment]
So Mist is different from Ethereum Wallet. Could you provide a link to Mist for Windows?

**Comment by sathishvj** [comment]
Ethereum Wallet is a Dapp.  Mist is a container that can contain Dapps, and in this case, by default contains Ethereum Wallet.  More here: https://ethereum.stackexchange.com/questions/2690/what-is-the-relationship-between-mist-and-ethereum-wallet

You can download Mist from the same place you download EW: https://github.com/ethereum/mist/releases
