### ISSUE TITLE
FileSave dialog in account backup has no OK or Cancel buttons.

### ISSUE THREAD

**Issue by vwu00000** [ethereum/mist#2696]
``````
Version: `0.8.10`
OS & Version: windows
Node type: `geth`
Number of blocks synchronized: 1,233,678
``````

FileSave dialog in account backup has no OK or Cancel buttons.

**Comment by sathishvj** [comment]
What is the FileSave dialog?  Can you post a screenshot of the menu item?  It is not there on a Mac and I can't quite imagine what it might be on Windows.

**Comment by vwu00000** [comment]
I go Accounts->Backup->Account and got this dialog (I can't save because no save or ok button):
![image](https://user-images.githubusercontent.com/28719999/27868267-d5c20728-6161-11e7-93df-9d3423c4f418.png)

**Comment by sathishvj** [comment]
That isn't a dialog.  It just opens up the folder where the keystore files are.  You have to back up the files in that keystore folder in a safe place.

**Comment by vwu00000** [comment]
So this option is to open keystore files not to save keystore files?

**Comment by vwu00000** [comment]
How to backup the keystore files?

**Comment by sathishvj** [comment]
This just shows you the location of the keystore files.

You can back it up like you copy any other file (copy-paste).  And put it in a safe place.  If you lose this (stolen laptop, hd crash, etc.), you need this file and your password to recover the account.  If not you'll lose everything.

**Comment by vwu00000** [comment]
I saw 3 folders: geth, keystore and testnet. geth size is almost 6 gb. keystore is empty. Should I backup all of them?

**Comment by vwu00000** [comment]
geth folder has 5.7mb. testnet has 6 gb.

**Comment by sathishvj** [comment]
You have to backup files within the keystore folder only.  But it cannot be empty if there are accounts.  

There would be different keystore folders though for the mainnet and the testnet in a folder structure similar to below.  You have to back up all the files in the keystore folders that you care about.

- keystore
- testnet
   - keystore

**Comment by vwu00000** [comment]
I see. There is only one file under keystore. The menu is very confusing, in my humble opinion. I should say "Account Keystore location and Application Data location".

**Comment by vwu00000** [comment]
Hi Sathishvj, is Mist Wallet for Windows OpenSource?

**Comment by sathishvj** [comment]
Yes.  See here: https://github.com/ethereum/mist/releases  It's coded and released by the same team as part of the same process.

**Comment by vwu00000** [comment]
But I didn't see any visual studio and c++ files.

**Comment by vwu00000** [comment]
Now I installed and launch Mist. It downloads blockchains from scratch. Should it use the existing blockchains?

**Comment by sathishvj** [comment]
It's not written in C++.  It uses Electron/JS.  

Yes, Mist and Ethereum Wallet refer to the same chaindata managed by geth.
