### ISSUE TITLE
Does block chain have to be updated to send ether?

### ISSUE THREAD

**Issue by backstageent** [ethereum/mist#2697]
``````
Version: `0.8.10`
OS & Version: osx 10.11.6
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

<!--

I have successfully sent 5 either in 2 previous transactions. But now I can not send any more.
My wallet contains way more than the amount I'm trying to send and the sends are showing as transactions, but never show up on the receiving account.

My blockchain is not sync'ed because I'm on a mac and hard drive doesn't have enough space. So I'm in process of putting the wallet on a windows computer with more HDD space. But when I move the keystore folder on to the windows box, my account balance is 0.. Is that because the chain is not sync'ed?

My question is how can I send some of these coins? I need to convert to BTC but I can't get anything to leave the wallet now..

thanks for your help!
MIke

**Comment by sathishvj** [comment]
Yes, if you are using Mist/Ethereum-Wallet.

You can still transact using a tool like myetherwallet.com which will maintain its own synced node.

**Comment by backstageent** [comment]
Would you have any information on how to import my current Etherwallet account to myetherwallet?

**Comment by sathishvj** [comment]
https://youtu.be/phht73IvUDI?t=2m5s  You can watch that from the time you have to import a keystore file.  Your keystore file can be found via: Accounts->Backup->Accounts.
