### ISSUE TITLE
Ethereum node needs to sunc please wait!!

### ISSUE THREAD

**Issue by Migson51** [ethereum/mist#2699]
Hi guys,

ever since the update my ethereum mist wallet seems to be in a permanent loop of node sync. I allready tried to enable automatic time and timezone since somebody mentioned that online. Unfortunately this didn't help. Could anyone please tell me what to do? Thanks a lot!!

Kind regards,

Miguel Rewinkel

**Comment by alyfree** [comment]
if you mean sync >>>it need to few days ...open the chaindata file and delete all blocks and restart wallet than let it to high speed sync don't close the pc if you can
good luck

**Comment by evertonfraga** [comment]
Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for syncing troubleshooting steps.
