### ISSUE TITLE
Make data directory changeable?

### ISSUE THREAD

**Issue by LGuappo** [ethereum/mist#270]
I'm running Mist on Ubuntu on a small laptop with very limited storage. I'd love to be able to store chaindata on an SD card so I can keep using this laptop after the blockchain gets too big to fit on my meager internal storage. Are there any plans to add an option to manually choose the blockchain storage location in Mist?

**Comment by frozeman** [comment]
Not yet. 

You can start the node manually with whatever options you want, as long as you set the `--ipcpath` to the default one you can run mist and mist will use that node.

**Comment by EddieOne** [comment]
+1 The installer needs a UI to select a download location.

**Comment by winsvega** [comment]
+1 My disc is exhosted too

**Comment by luclu** [comment]
Possible to do as **command-line flag** as of PR https://github.com/ethereum/mist/pull/689. This will be available in version 0.7.5.
Also requested in: https://github.com/ethereum/mist/issues/682

**Comment by luclu** [comment]
It is possible to pass commandline flags to geth in version 0.7.5: https://github.com/ethereum/mist/pull/689
