### ISSUE TITLE
i cn´t see my ether sent to the main account...

### ISSUE THREAD

**Issue by ikerez** [ethereum/mist#2700]
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````
hello, i have sent some ether to my main account but i don´t see them in my account

**Comment by sathishvj** [comment]
Can you see them at etherscan.io/address/0x... Put your address at the end.  If it's there but not seen locally, then it is probably just a sync issue.

**Comment by sathishvj** [comment]
If you are checking on etherscan.io, there is no need for you to sync it - it is expected to be synced always.  You only need to sync it if you are running a full node via Mist/EthereumWallet/geth/etc.

Based on the link you sent, there doesn't seem to be any transactions that you have made recently on that account.  The last you received anything there was about 25 days ago.  

In case you are sure that you have correctly sent something just now, there's probably a network delay and you will have to wait until it reflects.  If not, you've either not sent it, or you've sent it incorrectly, or maybe the transaction is lost for some reason.

**Comment by QconSling3r** [comment]
I'm saying my ether wallet shows 0.00. That transaction was the test and it's still not showing up

**Comment by sathishvj** [comment]
In that case your local wallet is probably not entirely synced.  Ideally your local node run by Ethereum Wallet should be synced to the latest block (see LAST BLOCK number on https://etherscan.io/).  How far has yours reached?

I've attached a screenshot as on my machine for your reference.  I just opened the app and the sync is just catching up again.

![image](https://user-images.githubusercontent.com/415647/27947664-76e9162e-6314-11e7-969c-8ce6c6047b89.png)

**Comment by QconSling3r** [comment]
sitting at 18%

**Comment by sathishvj** [comment]
Yup, so unless it is fully synced at least until the block where your transaction was mined, it won't show in your local node.

**Comment by QconSling3r** [comment]
and now he damn thing is just sitting at 18%

**Comment by QconSling3r** [comment]
https://etherscan.io/block/3858806
So the block was successfully mined but I can't sync, so my ether is just in lalaland?

**Comment by sathishvj** [comment]
Maybe I'm slightly wrong on when exactly it will show up.  But you aren't far from a fully sync.  Give it some time and it should show up.  

Once it does and it is ok, maybe you can also close this ticket.

**Comment by QconSling3r** [comment]
My ether is still not showing up in my wallet and I can not sync. It stops at 12-25% everytime.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
