### ISSUE TITLE
my password is wrong

### ISSUE THREAD

**Issue by ikerez** [ethereum/mist#2701]
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````
hello, i try to open an account contract so i can see the ther coins that i sent to the main accont but it says that my password is wrong, what can i do?? strange, the password should be right.....thanks

**Comment by sathishvj** [comment]
I've heard that there are issues with unicode characters in the password.  https://github.com/ethereum/mist/issues/2077 Could that be an issue?  Maybe there were different unicode chars that looks very much like regular ascii chars - which there are a few of.

**Comment by ihatecreatingaccounts** [comment]
why close this? others loose money bc of this, HELP THEM ASSHOLE

**Comment by account-archived-0** [comment]
@ihatecreatingaccounts Chill. When you sign up for Ethereum, you should be fully aware of risks like this. I lost money too because of this problem too. The key thing here is discussion, and maybe we can figure something out together. I want to get back the money I lost as well.
