### ISSUE TITLE
1. Go to the Assets tab in your imToken wallet. 

### ISSUE THREAD

**Issue by ikerez** [ethereum/mist#2702]
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````
hello, where is this assets tab in imtoken wallet, which is im Token wallet??

thsnkd

**Comment by sathishvj** [comment]
That's probably this: https://token.im/ and is not related to ethereum wallet.  You can close this ticket here.
