### ISSUE TITLE
Never completes blocks download

### ISSUE THREAD

**Issue by ukonline0** [ethereum/mist#2704]
``````
Version: `0.8.10`
OS & Version: windows/linux/osx linux mint
Node type: `eth/geth`eth
Number of blocks synchronized: 

wont complete block d/l  only 127 blocks left and stops and cannot receive any coins that have been sent  by network.

please help
``````

**Comment by ArcadeEngine78** [comment]
I am experiencing something similar. But I am frozen at the half way point of the node sync and it is just hanging. Have been waiting for the sync for several days now and also awaiting ETH to deposit in my wallet as a result.

Any advice, help would be greatly appreciated as this is making me nervous now.

**Comment by ukonline0** [comment]
hi im only 100 blocks away is so slow going the blocks are going up faster
than im  downloading its a nightmare others have same.

On Tuesday, July 4, 2017, ArcadeEngine78 <notifications@github.com> wrote:
> I am experiencing something similar. But I am frozen at the half way
point of the node sync and it is just hanging. Have been waiting for the
sync for several days now and also awaiting ETH to deposit in my wallet as
a result.
>
> Any advice, help would be greatly appreciated as this is making me
nervous now.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/IOz8R9eBmSl8j01RDIlqPRcgHDcL4vk4aQzlm-DgqrtIqhJf5hQPE1mjPz2MfYC7v2Un2o1bbdaWz1y2n1pA8tlm5muwS-hJFJh70WUDCi2KebYg6wGfqEk4Ckj9Dn2jKEU3JdLTZh-EybJDrvK904fHaXh4qQ=s0-d-e1-ft#https://github.com/notifications/beacon/AcgmLWU-n9BEQT_YCNYoqlyeeokA6vEcks5sKm7ogaJpZM4ONZpH.gif>

**Comment by alyfree** [comment]
open the chaindata file and delete all blocks and restart wallet than let it to high speed sync don't close the pc if you can
good luck

**Comment by sathishvj** [comment]
Even without the full chain data syncing, you can check the balance on the account at etherscan.io/address/0x... Put your address at the end.  You can also transact the ether on tools like MEW.  So there is no reason to be nervous about the sync not completing.

**Comment by LoseTheQuit** [comment]
At the top of the in Ethereum Wallet - in the menu bar there is the "Develop".  Will the options within Ethereum Node and Network (Geth 1.6.6 & Main Network/ Testnet ) become available when I finish downloading the blockchain. I can't use those options and I'm stuck with only 173 blocks left and those options are yet available.

**Comment by sathishvj** [comment]
If you started geth from the command line, they won't be enabled.  If you started Mist by itself (which started its own geth), then those options should be enabled

**Comment by ukonline0** [comment]
sorry can you tell me where i can find MEW tool i still cannot sync my
wallet.

thanks for any help

On Wednesday, July 5, 2017, sathishvj <notifications@github.com> wrote:
> Even without the full chain data syncing, you can check the balance on
the account at etherscan.io/address/0x... Put your address at the end. You
can also transact the ether on tools like MEW. So there is no reason to be
nervous about the sync not completing.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/h1JjOjVUnMbXQth0nwm9zAWWYNEXyws1nmLbN4SzKjOm7UVdvvgolcQyrbFmhQrqmZmTLu6Vr77dklCB4D7tc-Vbq5a0BEu77GLv2Cj3ZmuZNJy9XgA8QQnXDvdxo2OOOvoGmxcHByaQ4CfcmTFfIzRerHXyDg=s0-d-e1-ft#https://github.com/notifications/beacon/AcgmLQSg8cgjdmJUQEBjPSVIIGYsdGBIks5sKzwMgaJpZM4ONZpH.gif>

**Comment by ukonline0** [comment]
have you sync your wallet yet ?

not me just goes on and on its not sync ing

On Tuesday, July 4, 2017, ArcadeEngine78 <notifications@github.com> wrote:
> I am experiencing something similar. But I am frozen at the half way
point of the node sync and it is just hanging. Have been waiting for the
sync for several days now and also awaiting ETH to deposit in my wallet as
a result.
>
> Any advice, help would be greatly appreciated as this is making me
nervous now.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/IOz8R9eBmSl8j01RDIlqPRcgHDcL4vk4aQzlm-DgqrtIqhJf5hQPE1mjPz2MfYC7v2Un2o1bbdaWz1y2n1pA8tlm5muwS-hJFJh70WUDCi2KebYg6wGfqEk4Ckj9Dn2jKEU3JdLTZh-EybJDrvK904fHaXh4qQ=s0-d-e1-ft#https://github.com/notifications/beacon/AcgmLWU-n9BEQT_YCNYoqlyeeokA6vEcks5sKm7ogaJpZM4ONZpH.gif>

**Comment by sathishvj** [comment]
myetherwallet.com

**Comment by luizgustavoferreira** [comment]
gente socorro , estou com o mesmo problema . minha carteita mist não termina de sincronizar nunca . falta sempre 170 blocks . socorro , ja enviei eth pra minha carteira e não consigo retirar .

**Comment by evertonfraga** [comment]
Usa o https://MyEtherWallet.com
Localiza sua conta em Accounts > Backup, pra usar nesse site acima.

**Comment by luizgustavoferreira** [comment]
meu caro amigo , muiiitooooo obrigado . muiitooo muito muito obrigado . me salvou

**Comment by luizgustavoferreira** [comment]
4 meses sincronizando , e vc em alguns minutos me ajudou muiiitoooo . muito obrigado mesmo virei seu fa .

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Comment by group-1-engineering** [comment]
My mist last 120 blocks are not downloading, and that is preventing me from starting in the main network. Help anyone

**Comment by nolimitphil** [comment]
I am incredulous how an asset can have a "market capitalization" of $100 billion when its so-called "smart wallet" is inaccessible. (Would Facebook's valuation be $500 billion if users could not log into their accounts? ... for years?) 

83 blocks is the closest I have gotten to a complete sync.

- I deleted the "chaindata" folder and started the sync process over again. Did not work.
- I experimented with using different internet clock settings, e.g. time.nist.gov, time.windows.com, etc. Did not work.
- I switched to the "light" version. Did not work.
- I ran geth --fast in cmd. Did not work.
- I relocated my geth, binaries, and keystore folders to a 500GB SSD, and used an mklink /j command in cmd to create a junction from the original C:\Users\<computer name>\AppData\Roaming\Ethereum file directory to the SSD. Did not work.

The geth.exe program keeps running in cmd, constantly importing "new state entries". And 2MB .ldb files keep populating the chaindata folder while geth.exe runs. But the network never syncs. 

And apparently this issue dates backs a couple of years from what I've read on these forums...

At this point - all I care about is transferring my funds to a different wallet. Is this feasible without syncing? I have already been able to confirm my balance via etherscan.

**Comment by kudiaborm** [comment]
It's hard to imagine that this is working for anybody. Does everyone just use MyEtherWallet? This problem still exists and is worse on the lite client.

**Comment by evertonfraga** [comment]
@nolimitphil just to clarify, Geth downloads over 70M state entries on the background, just like "database records". It stops at `CurrentBlock - 100` while downloads for that great amount of state entries.

I am sorry about that, but you might try the `Develop > Sync with the Light Client`

**Comment by evertonfraga** [comment]
I invite you to the thread where we keep people posted about sync status. Soon we'll talk about our efforts towards a faster sync https://github.com/ethereum/mist/issues/3097
