### ISSUE TITLE
Ethereum sent from Coinbase and confirmed but still not received in Wallet

### ISSUE THREAD

**Issue by ArcadeEngine78** [ethereum/mist#2705]
``````
Version: `0.8.10`
OS & Version: OSX
Node type: eth
Number of blocks synchronized: 1,780,570 
``````
Sync has been hanging for almost a week and moves incredibly slow. Have sent several ETH to the wallet address and still have not seen it come through.

Any help would be supremely appreciated!

**Comment by ncsolar** [comment]
I would do "geth removedb" and then "geth --fast --cache=1024" That removes the old db files and start a fast Blockchain mode, more info here: https://www.reddit.com/r/ethereum/comments/58ectw/geth_super_fast/

**Comment by sathishvj** [comment]
To check that the ether has been received in the account, you can check at etherscan.io/address/0x... Put your address at the end.

Even without the full node syncing you can transact ethereum with tools like MEW.

**Comment by ArcadeEngine78** [comment]
Hey sathishvj both cases worked - thank you so much! Is there anyway I can send from the Ethereum wallet to MEW without the node syncing?

**Comment by sathishvj** [comment]
Afaik, that is not possible.  (But I should probably try it out because I'm suddenly not too sure.)

**Comment by evertonfraga** [comment]
It seems like a syncing problem. 

We have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
