### ISSUE TITLE
Mining on the Testnet

### ISSUE THREAD

**Issue by LoseTheQuit** [ethereum/mist#2707]
At the top of the in Ethereum Wallet - in the menu bar there is the "Develop" tab.  Will the options within Ethereum Node and Network (Geth 1.6.6 & Main Network/ Testnet ) become available when I finish downloading the blockchain. Are they supposed to be working now? I'm stuck with only 173 blocks left and those options are yet available. Without them, I can't mine on the testnet. 

EDIT:

there was a zip file in the folder ->appdata/roaming/ethereumwallet/binaries/geth

I unpacked it and now geth runs when I start the wallet, at first I would have to run them separately.
I kind of liked it that way because I could watch it get stuck and restart the process. Now it's just running in the background. Ethereum Node and Network (Geth 1.6.6 & Main Network/ Testnet ) are now available options - it's just when I select testnet - I get similar message to the one i would get if were to start the wallet without geth - before I figured out how to run them together. 

How can I change my geth.exe to always use --fast --cache 1024?
Can I create a new geth.exe?

``````
Version: `0.0.0`
OS & Version: windows
Node type: `geth 1.6.6`
Number of blocks synchronized: ~3976940
``````

**Comment by Menetar** [comment]
Hi! I just saw the zip and extracted it within the folder of appdata/roaming/ethereumwallet/binaries/geth and it still marks as error when running the Ethereum Wallet. I also have to start the geth separately. Can you tell me if you did anything else? I extracted the Geth and Copying files into that Folder

**Comment by LoseTheQuit** [comment]
I just want to say that I am by know means the real answer to this but this is what i do.. 
cd Users\dookiepookie\AppData\Roaming\Ethereum Wallet\binaries\Geth

and then run 

geth --syncmode=fast --cache=1024 

my folder structure is like this..
in the geth folder i have 
/archive (a folder)
/unpacked (a folder)
/archive.zip

**Comment by evertonfraga** [comment]
It'll be updated to `--syncmode=fast` to match Geth's latest specs. As for the cache, it auto detects your windows architecture (32 or 64bit) and sets the flag accordingly.

Closing upon inactivity. Please reopen if needed.
