### ISSUE TITLE
 My ETH did not sent to my mist wallet

### ISSUE THREAD

**Issue by plasma26** [ethereum/mist#2708]
Hello,
 My 5 ETH did not sent to my mist wallet by the following transaction.
Could I get it to my different wallet( nano s address: 0x1763375C3ea936Db46bFeBECf788Ce204cd32bDD )
Could you check it, please?
Thank you in advance,

TxHash:0x5ccd550eeebfb6dc2898776a63ea8f06f05056664f0e75374c466f04e2de8473Block Height:3450109 (527148 block confirmations)TimeStamp:96 days 3 hrs ago (Mar-31-2017 06:23:51 AM +UTC)From:0x167a9333bf582556f35bd4d16a7e80e191aa6476To:0x3e26284978f6df1dab6d88852c29240e38057320 Value: 5 Ether ($1,316.85) Gas Limit: 100000 Gas Price: 0.0000001 Ether (100 Gwei) Gas Used By Txn: 21000 Actual Tx Cost/Fee: 0.0021 Ether ($0.55) Cumulative Gas Used: 21000 Nonce: 9812

``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by sathishvj** [comment]
The transaction seems to have gone through fine.  And the target address also shows the 5ETH.

You can close this ticket if it's all good.

**Comment by plasma26** [comment]
Thank you for your answer.

I can not install mist program. It requires downloading all of blocks. I
have tried for about 1 month. Mist my wallet could not open until now.
is there any ways to install mist wallet?
Or Can you sent 5ETH to my different wallet?
Thank you again,


2017년 7월 6일 (목) 오후 2:27, sathishvj <notifications@github.com>님이 작성:

**Comment by sathishvj** [comment]
You can use myetherwallet.com to transact your ether.  Mist runs a full node and that is not necessary.

**Comment by plasma26** [comment]
Thank you for your kind help,


2017년 7월 6일 (목) 오후 2:36, sathishvj <notifications@github.com>님이 작성:

**Comment by QconSling3r** [comment]
Same issue as me: https://etherscan.io/address/0x1299DE9cbED583E8f0a1e813b86Efe0F00efdA8e I did a test and it never showed up in my wallet. Thoughts?

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
