### ISSUE TITLE
The Ethereum have not reached the wallet

### ISSUE THREAD

**Issue by 777David777** [ethereum/mist#2710]
Good day!
Final payment with nanopool did not reach my purse (Wallet Ethereum)2017-07-04 03:03:20
TxHash: 0x06a66e26e2ea2fe6e166879f0955bf2c8b52876974cd929b136d465d2986acf6
Need help

**Comment by sathishvj** [comment]
It seems to have gone through fine.  https://etherscan.io/tx/0x06a66e26e2ea2fe6e166879f0955bf2c8b52876974cd929b136d465d2986acf6

For it to show on Mist, all the blocks have to be synced. That typically takes hours.

**Comment by 777David777** [comment]
Good afternoon! Thank you very much. But unfortunately, I didn't receive money in the purse... There passed nearly a week.

**Comment by 777David777** [comment]
![1](https://user-images.githubusercontent.com/29919469/28037299-8bcc81fa-65c3-11e7-9d19-7cbe0e56bca0.jpg)

**Comment by sathishvj** [comment]
https://etherscan.io/address/0x979654d71abcce8dc8d78eb5dc3b733607387954 

There seems to have been multiple transactions to the account.  If you are expecting payment from somewhere else, like a mining pool, you should be checking with their support team.

**Comment by 777David777** [comment]
![Uploading 1.jpg…]()

**Comment by 777David777** [comment]
Thanks for your prompt reply. 
I wrote to Nanopool technical support, Here their response:
Hello,
if all the transactions were completed successfully (can be found in the on-line explorer), there is nothing we can do. Please, contact the exchange/web-wallet support.

https://etherscan.io/tx/0x06a66e26e2ea2fe6e166879f0955bf2c8b52876974cd929b136d465d2986acf6

Disturbs me that occurred as I can't be sure of success of the following transactions. Even I don't know where to address to receive the response about Priene of the incident. Perhaps, I do something not correctly?

https://etherscan.io/address/0x979654d71abcce8dc8d78eb5dc3b733607387954
I correctly understand that Ethereum arrived, and in 4 minutes was sent somewhere?
https://etherscan.io/tx/0x1a311a3ba6727025211fd57ae1d4497306ab88b727c79c25dc465b3f354382dd

**Comment by sathishvj** [comment]
Based on the transactions I'm seeing on that account, if you aren't the person moving out the received ether, then somebody else has access to your account.  You'd be better off creating a new account and using that.

Sharing the account address is ok, but never the keystore file and the password.  Also obviously never the private key.

**Comment by 777David777** [comment]
Thank you very much! I am very grateful for your help!

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
