### ISSUE TITLE
ETH sent from Jaxx

### ISSUE THREAD

**Issue by omniwoke** [ethereum/mist#2712]
``````
Version: 0.8.10 (version of Etherium)
OS & Version: windows 10
Node type: etj
Number of blocks synchronized: 0

ETH sent from Jaxx to Etherium wallet didn't come through.
Confirmed in block #151637 sent to ETH wallet 0x9EB5399dca299504326B737c50684eDd63479304
Confirmations: Jaxx shows +12

``````

**Comment by sathishvj** [comment]
https://etherscan.io/address/0x9EB5399dca299504326B737c50684eDd63479304

It is there in that account.  For it to show on Mist, all the blocks have to be synced.  That typically takes hours.

**Comment by omniwoke** [comment]
Thank you for the quick answer and great support.
That makes all the difference.

SINcerely,
omniwoke
Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by omniwoke** [comment]
I see it there but still not in my eth wallet (screenshot below).
Excuse my ignorance I'm a tad new at this.

**Comment by omniwoke** [comment]
Or do you mean the ETH wallet/program has to be open quite a few hours...until all the blocks are full?

SINcerely,
omniwoke
Sent with [ProtonMail](https://protonmail.com) Secure Email.

> -------- Original Message --------
> Subject: Re: [ethereum/mist] ETH sent from Jaxx (#2712)
> Local Time: July 6, 2017 8:08 AM
> UTC Time: July 6, 2017 1:08 PM
> From: omniwoke@protonmail.com
> To: ethereum/mist <reply@reply.github.com>
> I see it there but still not in my eth wallet (screenshot below).
> Excuse my ignorance I'm a tad new at this.
> Sent from ProtonMail Mobile
>

**Comment by sathishvj** [comment]
The EthereumWallet client has to be open for quite a long time for it to sync entirely if starting from the beginning.  The last block right now is about 3,983,221 and at the time of the attached screenshot, has to sync another 6000 blocks for me on my machine.  Yours could be at a different sync position and will take time accordingly.

![image](https://user-images.githubusercontent.com/415647/27913383-8fbc714c-627d-11e7-9012-d9730966de91.png)

p.s. your screenshot isn't showing up for me.

**Comment by omniwoke** [comment]
Mine has been sitting at 99% (273 blocks left) for over 5 hours now.
(Inline screenshot below)
I left the Etherium Wallet program open and running since yesterday morning.
Why would it be held up for so long?
And do I have to leave the program open and running?
[Screenshot (3).png]

SINcerely,
omniwoke
Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by sathishvj** [comment]
Your screenshots still don't show.

Anyways, try restarting the app.  Or check if there are any specific issues in the log.  Or maybe try from a different network. 

You can probably look at these also.

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
