### ISSUE TITLE
Deposit confirmed but wallet still shows as waiting.

### ISSUE THREAD

**Issue by ajgentile** [ethereum/mist#2714]
0x9edb621af7099371fd356afbb81499622c5a71be

Thanks guys. Looking forward to contributing...

``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by sathishvj** [comment]
https://etherscan.io/address/0x9edb621af7099371fd356afbb81499622c5a71be

There is 1 ETH there.  If it has to show on Mist, all the blocks have to sync, which typically takes hours.

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
