### ISSUE TITLE
Not the transaction took place from Nanopool on Ethereum Wallet

### ISSUE THREAD

**Issue by 777David777** [ethereum/mist#2715]
Hello! Need help. With Nanopool on Ethereum Wallet went the transaction never came. Where to go? Support Nanopoole said that the problem is on the side of the Wallet.
TxHash: 0x06a66e26e2ea2fe6e166879f0955bf2c8b52876974cd929b136d465d2986acf6
Block Height: 3970263
TimeStamp: 1 day 20 hrs ago (Jul-04-2017 12:03:20 AM +UTC)
From: 0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5 (Nanopool)
To: 0x979654d71abcce8dc8d78eb5dc3b733607387954

**Comment by sathishvj** [comment]
Transaction seems fine: https://etherscan.io/tx/0x06a66e26e2ea2fe6e166879f0955bf2c8b52876974cd929b136d465d2986acf6

Account seems to have deposit as expected: https://etherscan.io/address/0x979654d71abcce8dc8d78eb5dc3b733607387954

For it to show on Mist/EthereumWallet, all the blocks have to be synced. That typically takes hours.

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
