### ISSUE TITLE
Mining Away: Zero Balance in Mist Wallet, Etherchain and Zero Transactions

### ISSUE THREAD

**Issue by michaelstollaire** [ethereum/mist#2717]
``````
Version: `1.6.6`
OS & Version: Windows 10
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

So, just like several people here, I am mining away, but nothing shows in my Mist wallet, Etherchain, Etherscan, etc.

I decided to quit Mist and restart it, thinking info might be cached, and now, Mist won't even start.

I waited for the entire blockchain to sync before starting mining, doing everything by the book, and it is still broken.

Other than deleting chaindata and re-syncing the entire ETH blockchain, any ideas?

I am a n00b, so where are the logs located for geth, ethminer, Mist, etc.?

I am using the latest version of all three.

Thanks,

~ Mike

**Comment by sathishvj** [comment]
It is highly unlikely that you will get any ether by mining on your computer.  Today, there are others running many powerful computers that have a greater chance of winning a block.  So, what you are witnessing is normal.

Depending on your platform, the files are located at ... 
Mac: ~/Library/Ethereum
Linux: ~/.ethereum
Windows: %APPDATA%\Ethereum

**Comment by sathishvj** [comment]
Yes, geth will contain the info about your node and if you haven't changed it, it will also contain the entire blockchain data.

Keystore contains your keystore files which identify your account(s).  Remember to back this up in safe place as you can't recover your account without them.

For geth log files, you can find it by going to Develop->Show log file.  It will open the folder with node.log depending on your platform.  That should be the best starting point if you want to debug issues.  (I don't use ethminer so I do not know that.)  

The blockchain sync has shown issues for certain people and it does take quite a while.  You can consult these pages for more info:
https://github.com/ethereum/mist/wiki
https://theethereum.wiki/w/index.php/Ethereum_Wallet_Syncing_Problems

**Comment by michaelstollaire** [comment]
OK, thanks. I did confirm the blockchain full sync before starting mining, FYI.

I suppose what I am asking is, let's say against all odds, I actually mine some ether. Other than it hopefully appearing in my wallet, would I see files somewhere that would indirectly tell me I was successful, or I would see this via Develop -> Show Log File?

I sincerely appreciate your responses.

**Comment by michaelstollaire** [comment]
Update: The Develop -> Show Log File option is greyed out for me in the menu. See attached screen capture.
![show-log-file-greyed-out-07 06 2017](https://user-images.githubusercontent.com/29928924/27918826-f6e21d30-6224-11e7-9185-9622a010fb58.png)

**Comment by sathishvj** [comment]
From the minimum I can guess, you are better off uninstalling and then reinstalling the wallet.  Make sure you back up any keystore files of accounts you want.

afaik, there is nothing to show that you won the block creation - it just shows up against that account. At least that has been mine experience on the testnet. 

With ethminer it might be a different output though.  I haven't used that.

**Comment by michaelstollaire** [comment]
Fair enough. I'm trying what you said, uninstalling and re-installing the official Ethereum Wallet. It's currently synching to peers and downloading just under 4 million blocks. ;-)

I appreciate your advice and prompt feedback very much.

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
