### ISSUE TITLE
Bought ethereum on BitPanda but never received the Ethereum in my wallet.

### ISSUE THREAD

**Issue by Ruben555** [ethereum/mist#2718]
Hi, I bought ethereum on BitPanda but never received the Ethereum in my wallet. My Wallet number is 0xc68f725ebB24FEBE502A978f4509E90A0A1a1BA0. The transaction went through as it is reflected in etherscan. Could you please help? Thanks!

**Comment by sathishvj** [comment]
For it to show on Mist/EthereumWallet, all the blocks have to be synced. That typically takes hours.

**Comment by Ruben555** [comment]
Hi,


I bought this in March and still not showing up. Any other way I can fix this?


Thanks a lot

________________________________

**Comment by evertonfraga** [comment]
It is correctly shown at: https://etherscan.io/address/0xc68f725ebB24FEBE502A978f4509E90A0A1a1BA0

Please start geth separately in order to sync.
- `geth --syncmode light` 
- or head to https://MyEtherWallet.com, so you can move your funds elsewhere. 

Closing upon inactivity. Please reopen if needed.

**Comment by Ruben555** [comment]
Hi All,


Do you know how can I cash it out? I bought this Ethereum some time ago but not sure how to access to it anymore. Please help.


https://etherscan.io/address/0xc68f725ebB24FEBE502A978f4509E90A0A1a1BA0

Ethereum Account 0xc68f725ebB24FEBE502A978f4509E90A0A1a1BA0 Info <https://etherscan.io/address/0xc68f725ebB24FEBE502A978f4509E90A0A1a1BA0>
etherscan.io
The Ethereum BlockChain Explorer, API and Analytics Platform




Thanks!

________________________________
