### ISSUE TITLE
Cannot create a transaction in an onClick function 

### ISSUE THREAD

**Issue by adridadou** [ethereum/mist#272]
Hi,

I am currently working on a risk game using Ethereum. I am using mist as a dApp browser so I can interface with my ethereum node and create transactions. But I have the following issue. If I create a transaction in a function that is called by an event (for example onClick), then nothing happens.

To make sure it wasn't a coding issue, I tried outside of mist (in Chrome) and the function was correctly called. It seems to be some kind of protection. How should I make a button that will generate a transaction? How can I configure the protection?

Regards

**Comment by alexvandesande** [comment]
I've seen you are already discussing this on the gitter channel. Please come back and close this issue when it is resolved

**Comment by adridadou** [comment]
So I haven't found a solution yet but I have created a project to reproduce the issue.

It seems that it has something to do with serving the dApp trough 'truffle serve'

The project is : https://github.com/adridadou/mist-issue

All you need is the latest  truffle version, clone this project, do a truffle serve and access it through mist. 

Then there will be a button that does a console.log for each click. You will see that no logs are written.

If you access it directly in chrome you will see the console.log

**Comment by adridadou** [comment]
Ok so I made it work. But I would like some feedback to know if it should be simply closed or something should be done about it.

So first the main issue. It seems that if you run your application in Mist but you haven't added it, it won't work properly. By adding I mean that you click on the "plus" button to add it on the left. My guess is that while not being added, the web application is in a weird state and anything working in the background is lost somewhere. 

And the second issue is, I am positive that I could create a transaction by telling which account I should use. I did it by calling my function as such: mycontract.create(param1,param2,0,{from:account}) 
But I got invalid address. This has been solved by setting the default account. 

It seems that some documentation about it would help. I think I will write about my experience to help people who struggle with the same thing.

My open question is, what is going on if you access the web page without adding it? If this is an invalid situation and you shouldn't use it that way, I think it should be more obvious.

**Comment by evertonfraga** [comment]
You can either have an account added to the Browse tab, for browsing purposes. Once people add the Dapp to their sidebar, it's on a saved state, and no localStorage entries will be lost.

Issue closed due to inactivity. Please reopen if problem persists.
