### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by magooly** [ethereum/mist#2720]
``````
Version: `0.8.9`
OS & Version: windows 10
Node type: geth
Number of blocks synchronized: 227,420 to go
``````
Hi I am trying to send 1 eth to myself in a different wallet but although I can open my wallet I cannot send the coin as I'm asked for a password.
I have tried all the pw that I would have used but it says they are wrong.
How do I either recover my password or change it?

**Comment by sathishvj** [comment]
You cannot change the password anywhere.  There is no way but to somehow remember it.

**Comment by magooly** [comment]
Great! Thanks for the reply.
