### ISSUE TITLE
New To This

### ISSUE THREAD

**Issue by DarinBres** [ethereum/mist#2722]
``````
Hi,

I am new to this.  How long should it take to transfer of Ethereum from an exchange to a wallet?

D

``````

**Comment by sathishvj** [comment]
Usually under a minute. A block is mined every 10 or 12 seconds. 

But, it depends ...
* if you put a low fee (and there are many other txns paying higher fees), then yours could get picked up later.
* apart from your txn being picked up, the receiving wallet might wait for many confirmations (more blocks to be mined) before reflecting the balance in your wallet.  So if it needed 15 confirmations, it could be about 15*12 seconds later.
* if the network is clogged, it might be delayed.

**Comment by DarinBres** [comment]
Sathishvj,

Thank you so much for the response, I really appreciate it.  When I check my account on Etherscan, I can see it in my account, but it is still showing up as 0.00 in my Ethereum Wallet.  I keep trying to create a contract, but it keeps stalling out because I don't have enough for gas.  Any additional insight would be greatly appreciated.

D

**Comment by sathishvj** [comment]
Creating a contract costs you - a charge has to be paid to the network. This cost is measured in gas and paid in ether. So unless there is at least a minimal amount in your account, it will fail with the error you saw. 

Your transaction is part of a block. And with ethereum wallet you are running a full node that syncs the entire blockchain. Unless the block with your transaction is synced locally, you won't see the updated value locally.

**Comment by DarinBres** [comment]
Got it.  How can I check / set it up so it syncs up with up with me locally?

Thanks again,

D

**Comment by sathishvj** [comment]
When you start mist/ethereum-wallet it should automatically start the sync process. You'll see the block numbers updating.

**Comment by DarinBres** [comment]
Ok, I see that, just takes time since it is new and a low number, yes?

**Comment by sathishvj** [comment]
Yes. Many hours likely.

**Comment by DarinBres** [comment]
Copy that and thank you again.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
