### ISSUE TITLE
wallet synchronization since middle of june, 

### ISSUE THREAD

**Issue by Netharv** [ethereum/mist#2726]
Hi, I have problem with my wallet synchronization, it doesn't start. Problem exists since 3 weeks resulting in 120,148 blocks still pending to be processed.
Hence, no payment transaction are possible. how to proceed? 
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by sathishvj** [comment]
https://github.com/ethereum/mist/wiki

Check the log files if there is an issue.  Try from a different network, especially if you are behind a proxy right now.  See if any antivirus is blocking any ports.  etc.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
