### ISSUE TITLE
Big Problem here!

### ISSUE THREAD

**Issue by krijomi** [ethereum/mist#2728]
Hi all!

I really appreciate every soul, who spends time on helping solving problems. Newbies like me are in need of that :-)

On July 2nd I sent about 6,5 ETH from my Coinbase to my Ethereum Wallet. They are gone on Coinbase but not showing up in my wallet.

Where are the ETH, who has them now and how can I get them back?

My wallet looks like this (it never finishes loading, it is still at 0%)

![grafik](https://user-images.githubusercontent.com/29983641/27966805-4100c1bc-6349-11e7-940a-653803d66a5b.png)

**Comment by sunil75** [comment]
i am having same problem here...my wallet even after a week still loading...no ether in my account

**Comment by sunil75** [comment]
i think u should complete it..downloading of wallet

**Comment by sunil75** [comment]
this wallet is creating lots of problem..always syncing..too slow

**Comment by krijomi** [comment]
Thank you for that advice. I'll try it, the problem is only, that after 2 weeks of every day downloading for several hours it still shows less than 1 % as you can see..

Is there another solution? I surely want to change to a lighter version of a wallet, but first I need to get my ether...

**Comment by sunil75** [comment]
i think..let the developer answer this query..this wallet is recommended as its fast in transfer and feature rich...but this syncing and all is so sloowww and cumbersome...i lost my ether too..but whn i check my balance online its there in my wallet..that means..unless and until this wallet download every blockchain available ..it wont show anything...

waiting for developer or expert comment

**Comment by sunil75** [comment]
keep trying mate....ur ether in ur wallet..but u need to sync....so much to do

**Comment by sunil75** [comment]
i m trying since 3 days..still looking for peers...

**Comment by krijomi** [comment]
Ok. What are peers for and how can I find them? How do you make the sync faster?

**Comment by sunil75** [comment]
I have seen somewhere on this site.. U can transfer ur wallet from here to myetherwallet.. Go to account and make a back up copy.. Then go to myetherwallet. Com and upload it as backup.. See if it helps

**Comment by sunil75** [comment]
Wait i will give u link.. But dont know and sure of it

**Comment by sathishvj** [comment]
When you run Mist/EthereumWallet, you are running a full node.  In that case, the entire blockchain has to be synced before you will see the account balance updated.  As seen in your screenshot, your node has got about 3 million blocks left to sync.

In the meantime, you can check whether your account has balance at etherscan.io/address/0x... Put your address at the end.  If it shows up correctly there, it will show up in your mist/ethereum-wallet when the full chain data is synced.

In the meantime if you want to transact, you can do so at myetherwallet.com.

(Note: Always remember to backup your keystore files.)

**Comment by sunil75** [comment]
i would suggest u ..leave this wallet..endless syncing..endles searching for peers...go for another

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
