### ISSUE TITLE
Creating A Wallet Contract wil NOT complete

### ISSUE THREAD

**Issue by rmcluesman** [ethereum/mist#2729]
Ethereum Wallet Version: `0.8.10`
osx

I have created a wallet contract but no matter how long I wait, it will not complete. I need this to complete ASAP. Any help/insight would be appreciated.

**Comment by Patchou8** [comment]
I confirm I have this issue with version 0.9 as well. It's freshly installed with a new account. Only one thing not default: the data directory has been setup in D: (Windows 10).

**Comment by evertonfraga** [comment]
Should be fixed in 0.9.3.
