### ISSUE TITLE
How to backup accounts

### ISSUE THREAD

**Issue by yanik5** [ethereum/mist#273]
I want to save "cold wallet" or update wallet version. Simple coping **keystore** folder and remembering the password is enough? 

Thx

**Comment by frozeman** [comment]
You should also write down the wallet addresses, of the wallets you created.

**Comment by alexvandesande** [comment]
If you also save the "Mist" folder you'll be able to keep your watched contracts, watched tokens, wallet names etc. But if you just want the most important then the keystore folder and the address of any wallet is enough
