### ISSUE TITLE
Endless node sync after update

### ISSUE THREAD

**Issue by wllmkn** [ethereum/mist#2732]
Version: `0.8.10`
OS X EL Capitan version 10.11.6  8GB 1600 MHz DDR3 - 2,7 GHz
Node type: `geth`
Number of blocks synchronized:  Downloading block 3,783,037 of 3,937,174  - 1 block every ten seconds.

It's scary every time there is a new update for my Ether wallet, wether I'm going to agree or not. I had this issue for a few times now after updating. (Everything working well before) I will think twice before updating next time.

**Comment by sathishvj** [comment]
First, always remember to backup your keystore files.  All of this is still early software and you should ensure you have alternate ways to access your account.  Even if there is an issue with this tool, then you should be able to transact via MEW.

Apart from that, Mist/EthereumWallet is just a UI around the geth tool.  So if there are slow sync issues, you can check the log file to see if there is anything specific.  But you're right, every once in a while I've seen the update going slow (I don't know exactly why).  Yet, it's only some times for me and mostly goes through at a reasonable place.

**Comment by oolahru** [comment]
Same here.
0.8.10. Can't sync 40k blocks for 3 days already.

**Comment by oolahru** [comment]
May be it should be faster to get physical mail subscription with 2-4 usb sticks to send each other and import from a file?

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
