### ISSUE TITLE
No enough space on drive C:

### ISSUE THREAD

**Issue by Kim555** [ethereum/mist#2734]
Version: `0.8.10`
OS & Version: windows
Node type: `eth/geth`

There is no way to change the storage location. Make it possible to transfer them from the working folder of the C: drive to any other location.  The working folder is already 37 gigabytes, and the disk space is ending C:

Thank you

![2017-07-09_11-03-04 1](https://user-images.githubusercontent.com/30017123/27992186-4270db92-6496-11e7-9025-892be2b4a693.png)

**Comment by midas717** [comment]
same problem here

**Comment by alexvandesande** [comment]
Yes, a full node is unbearable for many people. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting. We are also developing a remote node option to make it faster and even less space.

We are merging all sync/full node issues on this thread: https://github.com/ethereum/mist/issues/3097
