### ISSUE TITLE
Enhancement: prompt whether to start Mist in light mode or full mode in the GUI when opening for the first time

### ISSUE THREAD

**Issue by jamesray1** [ethereum/mist#2735]
Enhancement: prompt whether to start Mist in light mode or full mode in the GUI when opening for the first time. This is an important enhancement, more so for end users who want to use Mist quickly, e.g. transferring funds from an exchange (which is important given the issues we've seen with exchanges like the GDAX flash crash, Mt. Gox hack with Bitcoin, and the [recent hack of Bithumb](https://motherboard.vice.com/en_us/article/bjxnjw/south-koreas-largest-ethereum-exchange-was-hacked)) and making transactions. It's also important for end users who aren't very tech- or developer-savvy.

**Comment by PatchRanger** [comment]
Relevant to #2372 .

**Comment by jamesray1** [comment]
This hasn't been done for v. 0.9.1.

**Comment by evertonfraga** [comment]
The light client is still an experimental feature. We’re closely following
this subject.

When it gets more reliable - with LES protocol v2, it’ll probably be the
default setting.

**Comment by jamesray1** [comment]
OK, fair enough, it does say beta in the menu.
