### ISSUE TITLE
mist wallet downloads a few blocks and chain structure then freezes

### ISSUE THREAD

**Issue by phaselinear** [ethereum/mist#2738]
``````
Version: `0.8.10`
OS & Version: windows 10 64bit
Node type: `eth/geth`
Number of blocks synchronized: 1947646
``````
so the problem im having is that the ethwallet app will load a few blocks and the chain structure. after about 30secs-1min it is no longer able to download anymore and freezes. at this point i cant click on the load application button, but if i click on load application within 30 sec after it has found peers then it will take me into the app but after a min the wallet wont download anything. i only noticed this issue after trying to send some eth to my wallet address, but after about an hour of not seeing my coins in the wallet i started looking into what could be causing me to not get my coins. it shows in the blockchain that it has been sent to my address but having to restart the app every min just to get the app to download a few thousand blocks is super annoying. not only that but now im worried once the wallet is all up to date if it will keep grabbing new blocks so that it doesnt disrupt minning.  all and all this coin's wallet is the most buggy and unstable wallet ive ever used (except the original dash wallet).

if there is anyway to get the ethwallet to automatically try to rescan every min i would really like to know.

**Comment by Latham13** [comment]
same here

**Comment by sathishvj** [comment]
if you want to transact with them, you can use https://www.myetherwallet.com while your full node is still syncing.

meanwhile for the node sync, check if there is an antivirus/firewall blocking you, check the log files, try from a different network (especially if you're now behind a proxy), etc.
