### ISSUE TITLE
lost password

### ISSUE THREAD

**Issue by PeterV13** [ethereum/mist#2739]
``````
Version: `10.0.0`
OS & Version: osx
Node type: `eth/geth`
Number of blocks synchronized: 3,999,907
``````
I am trying to transfer ETH into my personal account. It asks for the password. I can't remember....how can I change my password????

feeling dumb!

**Comment by sathishvj** [comment]
you cannot change the password.  it is directly connected to the private key.  You will have to remember the password.

**Comment by ihatecreatingaccounts** [comment]
well, it gives the option to SKIP the password creation, so what to do then?
fuck ether, really, lost 2.8 bc of this shit

**Comment by evertonfraga** [comment]
To reproduce this issue and help you guys, I, please ask you to answer this set of questions, so we can outline the problem and move on. Please fill out the form thoroughly.
https://goo.gl/forms/jznmHV6Fpui7Ijds1

Let's move the conversation to this single place: #3513

Thank you.
