### ISSUE TITLE
Where download Win32 Wallet 5.1 ?

### ISSUE THREAD

**Issue by Erchard** [ethereum/mist#274]
Not found win32 wallet 5.1

**Comment by frozeman** [comment]
I didn't put the windows32 binary up, as we don't have a geth node build for that. Did you build geth 32bit yourself?

**Comment by anfred** [comment]
I installed 3.8 since that is the last win32 version, no node there either.  Is there some instruction on how we can do this ourselves?  I would really like to use Eth Wallet on my win 10 tablet for traveling.

**Comment by luclu** [comment]
As of version 0.7.2 win32 builds are available. Hope that helps!
