### ISSUE TITLE
Wallet not recognising key files.

### ISSUE THREAD

**Issue by XDR01** [ethereum/mist#2741]
Hi All, 
Having issues with this wallet, I installed the wallet two weeks ago, worked fine. However opening it today it updated and did not recognise my key files. Now the wallet is in default mode, once I put key files it crashes.

Any ideas?

**Comment by Latham13** [comment]
have you tried uploading your keys manually?

**Comment by XDR01** [comment]
Yes on startup but that's when it crashed, seems solved now. 

Rebooted PC, then left it for a hour after it finished sync now it recognises the key file.
