### ISSUE TITLE
mist.requestAccount always prompts to create a new account

### ISSUE THREAD

**Issue by axic** [ethereum/mist#275]
Contrary to what the [manual](https://github.com/ethereum/mist/blob/master/MISTAPI.md) says ("Asks the user to provide, or create a new account."), it always prompts for a password for creating a new account.

At the same time `web3` doesn't contain the `defaultAccount` or `accounts` properties, not even if I've enabled an account already for that given site.

I am not sure if the "DApp browser" version of Mist ([0.3.6 released in November](https://github.com/ethereum/mist/releases/tag/0.3.6)) is still maintained or planned to be released in the future. Is that project shelved?

I see that the API is still present in the latest release (available through 'Toggle Developer Tools' console) and there's no change in behaviour.

**Comment by alexvandesande** [comment]
The project is very much active. The functionality for requesting accounts isn't done yet as we've built only the half that the wallet needs.

**Comment by frozeman** [comment]
`web3.eth.accounts` is what you want.

**Comment by axic** [comment]
@frozeman true true, I always mix them up.

However regarding `mist.requestAccount`: is that something still pursued or apps should rely on `accounts` / `defaultAccount` ?

**Comment by graup** [comment]
@alexvandesande @frozeman If `mist.requestAccount` doesn't work yet as described, maybe you could remove it from the [documentation](https://github.com/ethereum/mist/blob/develop/MISTAPI.md#mistrequestaccountcallback). It is very misleading.

**Comment by alexvandesande** [comment]
@graup this is part of this PR: https://github.com/ethereum/mist/pull/814

**Comment by graup** [comment]
Great, thanks! Looking forward to that feature.
