### ISSUE TITLE
How to send Tokens from Mist to a different address

### ISSUE THREAD

**Issue by simonease** [ethereum/mist#2757]
``````
Version: `0.8.10`
OS & Version: osx
Node type: `eth/geth`
Number of blocks synchronized: 4015620
``````

I would like to send out a specific Token (STORJ) out of my Mist to another address. Currently the Token appears under the contracts section. However it is not available under the Send section. So I can't choose it as an option to send out. 

Kindly provide an instruction on how to send a Token out of mist to a different address.

Thank you.

**Comment by sathishvj** [comment]
You might find it easier to do it with https://www.myetherwallet.com/

Also, do you have any ether at all in the account.  A minimum amount of ether is required to transact on the ethereum network (which is used by storj).

**Comment by simonease** [comment]
Yes I have ETH on the account. 
In the meantime I found the solution to my problem: I did not realize that the Tokens are listed inside my wallet too. By clicking in the wallet I was able to access and also send them. 
Thank you for your support.

**Comment by AIONjules** [comment]
Hi, i am having a problem sending some tokens...when i go to the account that contains the tokens, and then hover over the send, icon….the account then defaults to my ETH balance....
