### ISSUE TITLE
Freezes on some send attempts

### ISSUE THREAD

**Issue by housemobile** [ethereum/mist#276]
It's happened twice now on Windows64 version. I've hit send an the program freezes. It still runs, and the buttons are clickable, but nothing happens when I click them. I can't even exit the program. I had to ctrl-alt-del to force quit. 

I'm running Windows 7 Pro

**Comment by HelixiR** [comment]
+1
Windows 10 freezzzy to sometimes.

**Comment by jacogr** [comment]
Mac OS X - same issue. In my case it happens with all sends. Click send and it just sits there, not going to the next step.

When I exit the app (via the menu), it recovers before exiting. (Recovers: goes to the actual send page...)

I have managed once to get to the "send page", however couldn't enter any amounts whatsoever.

**Comment by luclu** [comment]
Do you still encounter this behaviour in version 0.7.5?

**Comment by luclu** [comment]
Closed as of inactivity.
