### ISSUE TITLE
Balance is not changing

### ISSUE THREAD

**Issue by Nordomus** [ethereum/mist#2763]
After few days of mining balance in wallet still shows 0.00 ETH. I'm using mining for the same adress as in Wallet. What can be wrong?

**Comment by sathishvj** [comment]
If you are mining on the main net, you're unlikely to get anything - others have more specialized hardware.

**Comment by Nordomus** [comment]
Soo I've been lied to? Where should I mine?

**Comment by sathishvj** [comment]
I'd suggest you read up more about blockchain, consensus, mining process, etc. Having a mining node is like having a pickaxe - whoever gave you the pickaxe isn't guaranteeing you'll dig up gold.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
