### ISSUE TITLE
No coins in Etherbase Wallet after 28days of syncing up blocks?

### ISSUE THREAD

**Issue by Chriskirk101** [ethereum/mist#2765]
![dsc_0107](https://user-images.githubusercontent.com/30176723/28211822-83e211fa-6896-11e7-8d3a-339510091cca.JPG)

``````
Version: `0.8.10`
OS & Version: windows 10
Node type: `eth/geth`
Number of blocks synchronized: 3,903,500
``````

I bought 2 Ether (ETH) 28days ago to this Ether wallet and have now synced up past the block height where I purchased them (Block 3,877,079) and my wallet is now synced to block 3,903,500 but is still showing '0' coins?
I've checked the transaction wallet keys and they both match and now I'm very concerned my ether coins have litterally gone into the Ether?!

**Comment by shlomogoldblatt** [comment]
I have the same problem for couple of months already. Bought some ether, synced the blockchain, the amount in the wallet is still 0 even though etherscan shows my original balance. No help from developers whatsoever

**Comment by abbasabba** [comment]
same

**Comment by pocroc** [comment]
I am having the same problem

**Comment by Chriskirk101** [comment]
Thanks for all the amazing help! One thing for sure I'm not going to waste any more money on ETHER coins!!! 
My advice to anyone thinking to invest in these....stay away!!

**Comment by uclnj** [comment]
Put some ETH in my wallet which two days ago showed up, the [balance list](https://etherscan.io/address/0x70d019f3b9dd416c7c821ecacd70bdcff1954011) shows the ETH still in there yet my wallet shows a balance of 0.00.

![screenshot 2017-07-17 19 42 18](https://user-images.githubusercontent.com/835685/28294434-3285d4c4-6b28-11e7-8187-44f6b6839a03.png)

Good thing I didn't take this coin seriously?

**Comment by pocroc** [comment]
I am trying invest in a few company's that only take ether.  What should I do?  I also want to register a .eth name

Warm Regards,

Alex Pell

On Jul 17, 2017, at 5:12 PM, Greg Merideth <notifications@github.com<mailto:notifications@github.com>> wrote:


Put some ETH in my wallet which two days ago showed up, the balance list<https://etherscan.io/address/0x70d019f3b9dd416c7c821ecacd70bdcff1954011> shows the ETH still in there yet my wallet shows a balance of 0.00.

[screenshot 2017-07-17 19 42 18]<https://user-images.githubusercontent.com/835685/28294434-3285d4c4-6b28-11e7-8187-44f6b6839a03.png>

Good thing I didn't take this coin seriously?

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
