### ISSUE TITLE
Ethereum block freezes while syncing

### ISSUE THREAD

**Issue by CookeisFlz** [ethereum/mist#2768]
Version: `0.8.10`
OS & Version: windows 7
Node type: `eth/geth`
Number of blocks synchronized:1,204,416
Ram: 32 GB

## Issue
The** ethereum node is constantly freezing after about 30 seconds of syncing

## Possible Issue or Fix
After investigation inside the task manager, I have found that "Geth*32 is constantly using more and more ram. At about 600k mb of ram usage, it crashes, but that doesn't crash the ethereum node- it just stops the syncing. I think that this is the cause for the repeated freezes while syncing and if someone could fix it, that would be greatly appreciated. 

## Another Issue
After closing the ethereum node, the task remains inside of the task manager so you have to manually close each processes inside of the task manager.  The more I restart the ethereum wallet/node, ther are more processes using more and more ram.

Using the node, i have successfully made it to 1 million blocks by restarting the node numerous times after the freezes. I have mistakenly transferred ethereum to the address by mistake before letting it sync which I will never do again.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
