### ISSUE TITLE
password gone jej super software now give back my money

### ISSUE THREAD

**Issue by ihatecreatingaccounts** [ethereum/mist#2769]
``````
Version: `8.10`
OS & Version: windows/
Node type: `geth`
Number of blocks synchronized: 0?? idk its fucking slow you retards
``````

i found millions with the problem, NOT ONE WAY TO SOLVE.
so what now? you kind of stole my money with this.

so the problem is:
no password chosen, somehow it gave me a mnenoic phrase as pw, which i used 1 time to transfer ether, it worked, then i transfered it back, voila, wrong password. its the best joke in the world, unless its your money.
i tried unlocking via console and myetherwallet, no success. i deleted the installation a few times, but my keyfile is still in the chainfolder, which i never deleted. 
is it possible the file was encrypted twice? sucks to loose 500 bucks

and LarsFronius is a faggot

**Comment by tageeboy** [comment]
I wonder if people posting these sorts of things actually think it motivates anyone to help? Considering that the development of this wallet is not paid its quite rude to attach the volunteer work done to help us and the overall ETH community. There is no double encryption. Its not possible to set up a wallet without a password. The wallet won't let you progress. So you have to remember what you entered and use that or the funds will remain in the wallet, secure as intended.

**Comment by ihatecreatingaccounts** [comment]
But theyre being paid. A Software Bug resulted in loss of 70Mio $ in ether.
Easiest thing for scammers. And youre just pure ignorant fanboy, talking to
You is senseless as only your opinion is right. Just like an
islamist,feminist or chemtrailfreak. I hope this wakes You from your dream

Am 21.07.2017 8:44 nachm. schrieb "tageeboy" <notifications@github.com>:

**Comment by evertonfraga** [comment]
@ihatecreatingaccounts 

First of all, if you want any kind of help, be nice.

**Comment by ihatecreatingaccounts** [comment]
There's nothing to help me, Software encrypted my wallet in a way making it
inaccessible, i tried every method i could find. And I know its the right
pw, i Made a transaction with it 2 Weeks prior

Am 21.07.2017 9:17 nachm. schrieb "Ev" <notifications@github.com>:

**Comment by evertonfraga** [comment]
Which mnemonic you saw are you talking about?
Are you using wallet or mist? What are the Keystore files modification dates?

**Comment by ihatecreatingaccounts** [comment]
well, thats what id like to know myself. i just know i copied everything that it gave me, and the mnemonic was somewhere in the application as password.
i will tell you the steps:
i downloaded the software from github, but never synched, so i deleted, downloaded other version, this worked better and synched. i try to remember as good as possible:
whenever it said select password and retype password, theres also the SKIP option which i used.
then i bought 2eth via btc payin, took long to be transferred, so i wanted to move them.
at some point the software told me to write smth down, which was a 29 word mnemonic. i c&p that
and saved it to text file.
then, when i wanted to move my ether to my mobile wallet, it prompted a password, i tried empty, tried my regular ones, nothing worked. i then used the 29 word mnemonic, and it worked.
now had my ether on mobile, but there were many issue too, so i wanted my money on polo to trade, which didnt work, as my mobile didnt allow to send to contracts, so i wanted to send it back to my desktop wallet, worked fine, but when i wanted to transfer it to polo and prompted the password, which i was very sure of would be the mnemonic, it told me wrong password. 
i tried geth console to manually unlock - no result.
i tried to access via myetherwallet - no result
i tried the ethrecoverpython script to bruteforce against known passwords - no result.
its 2.8 ether ( had 0.8 on mobile), sucks to loose, but well, if this is my learning money, okay.
ive been into bitcoins for several years, never had any problem like this, im not a retard or noob on this matter.

**Comment by evertonfraga** [comment]
> at some point the software told me to write smth down, which was a 29-word mnemonic

Mist does not have any mnemonic feature at this moment and never had. You are clearly talking about some other application.
