### ISSUE TITLE
Ethereum-Wallet-win64-0-5-1 can't install on Windows 10

### ISSUE THREAD

**Issue by jamespotkukelkka** [ethereum/mist#277]
I can't install this on Windows 10. When I click it, Norton 360 alerts, that it is not trustworthy. I dismiss alert, but then nothing happens.

**Comment by luclu** [comment]
Norton might disallow the installation because auf Mist's ability to mine on the Testnet. Some AVs are regarding this as malicous. Try to add an exception or deactivate Norton during the installation.
