### ISSUE TITLE
fcuk you ether

### ISSUE THREAD

**Issue by ihatecreatingaccounts** [ethereum/mist#2774]
fuck you hard, ether, your shit software doesnt work, as set passwords are CHANGED WHAT THE FUCK?!?!?!?!!?!??! my wallet is like encrypted with 10 pws which i never set, but yeah FUCK YOU, you wanted to be the next bitcoin huh? well SHIT youre not even doge

**Comment by tageeboy** [comment]
Outstanding demonstration of a novice user who lashes out at the tool he is unable to figure out how to use. The Mist wallet is the OG ETH wallet and is rock solid. Attacking the code because you can't figure out how to used it solidifies the fact that ETH is not for you.

**Comment by ihatecreatingaccounts** [comment]
Nope, i am far more experienced than You might think. The pw was changed
due to faulty Software, this happened several times now. Sure, it looks
like theyre all stupid and cant remember passwords, but not even
considering that there's smth wrong is just ignorant

Am 21.07.2017 8:41 nachm. schrieb "tageeboy" <notifications@github.com>:

**Comment by evertonfraga** [comment]
Closing this issue. Reason: inappropriate wording. Calm down and explain with more details here: https://github.com/ethereum/mist/issues/2769

**Comment by ihatecreatingaccounts** [comment]
There's nothing to help me, Software encrypted my wallet in a way making it
inaccessible, i tried every method i could find. And I know its the right
pw, i Made a transaction with it 2 Weeks prior

Am 21.07.2017 9:18 nachm. schrieb "Ev" <notifications@github.com>:

**Comment by anormore** [comment]
I 100% agree with your rage. There are **THOUSANDS** of users unable to access their wallet because of password issues. The dev team is really 'cool' about it, and we feel quite ignored. That's a good way to piss people off.

I suspect that there will be more and more of these kinds of posts

@evertonfraga  You guys might want to ramp up your fixes on this password issue. ASAP.
