### ISSUE TITLE
I'm trying to mine on testnet but something isn't working.

### ISSUE THREAD

**Issue by SwedishFox** [ethereum/mist#2777]
``````
Version: `1.6.6`
OS & Version: windows
Node type: `geth`
Number of blocks synchronized: 1312900
``````
I've been trying to Mine using the Mist geth client because I want to start tinkering with smart contracts. However My node gets out of sync very quickly and when I click on mine nothing happens. I toyed with this when it was first released and could have sworn a box popped up that you gave commands in and could see all details in. I have no idea what's wrong but I will say this, I did not allow firewall access as I was told by IT it was unnecessary.  Could this be an issue if so how do I fix it?

**Comment by sathishvj** [comment]
If you are using Ethereum Wallet, it is not showing the mining/hashrate indicator anymore (don't know why).  But you can try with Mist; that one shows.

If not that, you can check in the log file if there are any issues.  Develop -> Show log file.

**Comment by SwedishFox** [comment]
It's Working! Thank you so much.
