### ISSUE TITLE
Import wallet is freezing

### ISSUE THREAD

**Issue by naruemont** [ethereum/mist#2779]
``````
Version: `0.8.10`
OS & Version: windows
Node type: `geth`
Number of blocks synchronized: 4,033,421
``````

I tried to import Wallet Contracts but it is freezing more than a day. 
![image](https://user-images.githubusercontent.com/30225190/28256305-2eeb3616-6aeb-11e7-95f5-804be1619374.png)

[log.zip](https://github.com/ethereum/mist/files/1151675/log.zip)

**Comment by sathishvj** [comment]
Not seen this before.  Anyways, first backup the keystore file and make sure that it has some valid json in it.

Then you can restart the app and try to import again.
Else (after you've backed up all existing keystore files elsewhere) you can just drop it in into the keystore directory and then start the app.  It should be picked up.

**Comment by naruemont** [comment]
I tried restart the app many times but it has never been disappear. So, I reinstalled the application and the freezing wallets are gone. Thanks for you support :)
