### ISSUE TITLE
I loaded the account with BTC, now I've got 0 Ether!!!!!! It's a fraud.

### ISSUE THREAD

**Issue by SlowEtherbaseWallet** [ethereum/mist#2783]
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by sathishvj** [comment]
All blocks need to be synced before it shows up.  Meanwhile you can check the balance at etherscan.io/address/0x ... put your address at the end.

**Comment by evertonfraga** [comment]
Please check your balance at https://etherscan.io 

You must be synced with the network in order to see your balance.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
