### ISSUE TITLE
My account freezes up during syncing, never completes the process = 0 Ether

### ISSUE THREAD

**Issue by SlowEtherbaseWallet** [ethereum/mist#2784]
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by pocroc** [comment]
This is what happens to me.  the node downloads up to block 1.4 million or so and then fails

**Comment by sathishvj** [comment]
First make sure your keystore files are backed up.  If you corrupt them or lose them, you cannot regain your ether.

If you need to transact ether, you can use a service like https://www.myetherwallet.com while you wait for your full node to sync.

For sync issues, see if you can try on a different network, check if an antivirus or firewall issue is blocking, check log file for any issues.  You can also refer these docs:
https://github.com/ethereum/mist/wiki
https://theethereum.wiki/w/index.php/Ethereum_Wallet_Syncing_Problems

**Comment by pocroc** [comment]
Thank you

Warm Regards,

Alex Pellegrino
Sequoian Investments

On Jul 17, 2017, at 10:36 PM, sathishvj <notifications@github.com<mailto:notifications@github.com>> wrote:


First make sure your keystore files are backed up. If you corrupt them or lose them, you cannot regain your ether.

If you need to transact ether, you can use a service like https://www.myetherwallet.com while you wait for your full node to sync.

For sync issues, see if you can try on a different network, check if an antivirus or firewall issue is blocking, check log file for any issues. You can also refer these docs:
https://github.com/ethereum/mist/wiki
https://theethereum.wiki/w/index.php/Ethereum_Wallet_Syncing_Problems

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
