### ISSUE TITLE
I Need Help!  I Am getting started with Ethereum and the wallet wont sync

### ISSUE THREAD

**Issue by pocroc** [ethereum/mist#2785]
Hi Guys,

I am new to digital currency.  I went to ethereum.org  and downloaded the Ethereum Wallet for the Windows 32 bit.  I unpacked the zip, extracted the files and ran the program.  I then received a prompt saying that I need to have some ether.  The prompt sent me to shifty by shapeshift.io to convert some bitcoin to ether - which I did.  Then it had three additional prompts explaining the "Democracy" model and then lead me to the wallet.  The wallet then synced 1.4 mill of 4 million blocks and 5,600 of the 6300 chain structure.  I do not know where my coin is at and I cant get access.  Can someone please help me.  Thank you.

Version: I think it is the newest version 8.10 or something
OS & Version: windows/
Node type: `eth`
Number of blocks synchronized: Downloading block 1,465,474 of 4,037,906, 
Downloading chain structure 5,640 of 6,356
``````

**Comment by sathishvj** [comment]
First, always backup your keystore files.  If you corrupt/lose them, you will lose access to your account.

EthereumWallet/Mist runs a full node.  Unless it is fully synced it won't show any funds for your accounts.  

Meanwhile you can check your balance at etherscan.io/address/0x ... 
And if you want to transact, you can use https://www.myetherwallet.com by using the same keystore file.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
