### ISSUE TITLE
how to delete an account?

### ISSUE THREAD

**Issue by lumicon** [ethereum/mist#2786]
hi, i have 2 additional empty accounts in my wallet. would like to work only with main account.  how can i  delete these accounts?
thanks!

``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by sathishvj** [comment]
Technically, you can't "delete" an account on the blockchain.  But you can remove it from your list by removing the specific keystore file from the keystore folder.  ```Accounts->Backup->Accounts``` in the menu should open the keystore folder where you can find the keystore files.

Remember to first backup the keystore files you want.  If you lose or corrupt them you'll lose all access to your funds.

**Comment by lipangit** [comment]
Hello @sathishvj  How to delete solo account
