### ISSUE TITLE
Wallet cannot create; all blocks synced; 404 errors in console.

### ISSUE THREAD

**Issue by awilliamson** [ethereum/mist#2791]
Version: 0.8.10
OS & Version: 4.11.9-1-ARCH Arch Linux
Node type: geth
Number of blocks synchronized: 4,039,864

![Screenshot 1](http://i.imgur.com/VziKGup.png)
![Screenshot 2](http://i.imgur.com/NhnvrfO.png)

I've been having this issue where a newly created 'Single Owner' wallet contract never completes. I've redownloaded the entire blockchain several times, and even made a new Account from scratch to try this.

I decided to check the developer console and find that a 404 error occurs for wallets.

My question is whether or not this is affecting wallets, and how to resolve this issue as swiftly as possible so that I may have an accessible wallet. So far Mist has presented nothing but problems.

I can spawn geth myself, or let mist spawn it. No change.

As far as I'm aware this is not a duplicate, I have tried to provide as much information as possible of relevance to the issue.

**Comment by evertonfraga** [comment]
OK, thanks for the detailed info @awilliamson 

The 404 error refers to a font file — not the problem.

I'm looking into this now.

**Comment by evertonfraga** [comment]
Hi @awilliamson, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
