### ISSUE TITLE
Solidity compiler tab should not present warnings as errors

### ISSUE THREAD

**Issue by axic** [ethereum/mist#2797]
See https://github.com/ethereum/solidity/issues/2610.

If using the old compiler interface, each error message needs to be checked if it contains `Warning:`.

Using the new compiler interface (`solc.compileStandardWrapper()`) the severity is available as a field. See https://solidity.readthedocs.io/en/develop/using-the-compiler.html#compiler-input-and-output-json-description.

**Comment by jklepatch** [comment]
I can work on that one.
Is this the right place to start ?
https://github.com/ethereum/mist/blob/develop/modules/ipc/methods/eth_compileSolidity.js
