### ISSUE TITLE
Transfered real funds to a Test-Net account

### ISSUE THREAD

**Issue by Pyeskyhigh** [ethereum/mist#2798]
``````
Version: `0.8.10`
OS & Version: osx
Node type: geth
Number of blocks synchronized: 1 334 778
``````
Hey all,

Sent Ethereum to Ethereum Test-Net
I was just downloading the Ethereum Node software yesterday, and while waiting for the blocks to download, it offered me to start up quick and load my account using bitcoin. So through Shapeshift, I took money from my Coinbase account and sent it to the address that it told me to send it to on the Ethereum loading page. Once that was all done and I was loaded into my wallet, it brought me to the Test-Net page where I saw my account (Main Account (ETHERBASE)), but it did not have the funds that I had loaded into it, it was the address that Shapeshift said it had sent the funds too though... Is there anyone who can help me with this issue?
 
It then also shows this (uploaded image) on the Main account page. I tried to get a wallet contract but that costs ether to get (which doesn't make sense to me, since I can't get my Ether anyways). Let me know what you think!
 
Thanks.

![](https://cdn.cryptocurrencytalk.com/uploads/monthly_2017_07/596fae92851ed_ScreenShot2017-07-19at3_09_53PM.png.ab5b44541b9aa5bdb777d822ccd1111d.png)

**Comment by evertonfraga** [comment]
Can you confirm via https://etherscan.io that you've moved funds to that address?

If so, you just have to move/copy your keystore file, from `~/Library/Ethereum/testnet/keystore` to `~/Library/Ethereum/keystore`, and it should be fine.

**Comment by Pyeskyhigh** [comment]
Thanks @evertonfraga for the advice. It shows the transaction on etherscan.io. I tried that but it hasn't shown up yet. Should I assume that it may take a couple of days to show? or should I find a way to get a wallet contract? I appreciate the help. 

Best,
Pyeskyhigh

**Comment by evertonfraga** [comment]
Yes, it will only show up when your local Mist is in sync with the network, which can take quite some time.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
