### ISSUE TITLE
Created account but after reopening wallet, the account is gone

### ISSUE THREAD

**Issue by jakejoii** [ethereum/mist#2800]
``````
Version: `0.8.10`
OS & Version: windows 10
Node type: `eth`
Number of blocks synchronized: All blocks
``````

I created an account a couple days ago. I created a password and received my address and am successfully mining. However, after closing my wallet, I opened it a couple days later and had to redownload all blocks. After downloading and opening Mist, there was no account to be found and nowhere for me to input my password. Is there a way for me to access the account I created a couple days ago?

**Comment by evertonfraga** [comment]
Head to Accounts > Backup > Accounts, and see if a json file lies there. 

Otherwise, please check the network you've been syncing (mainnet, testnet). That can also be some source of confusion.

**Comment by jakejoii** [comment]
After following the steps you posted, I do not see any json files. However, I do have a keystore folder and the name of the file that is stored within that folder does have my address. 

I'm mining with nanopool, and when I check my account balance for nanopool, it does show that I have a balance. However, my balance has not transferred to my wallet yet. Would having an empty wallet affect my ability to access the wallet?

**Comment by evertonfraga** [comment]
Please check the following:

1) Network name (Develop > Network > ?) 
> You should be on mainnet. if not, perform the change

2) Make sure your JSON file is at `%appdata%\Ethereum\keystore`, and not `%appdata%\Ethereum\testnet\keystore`

**Comment by jakejoii** [comment]
Thank you for your help but I actually resolved the issue.

The wallet that was created on the Desktop was not in the same directory as the wallet I was using. Somehow I have two wallets, one located within the directory with all of my other mining files and one located on the Desktop.
