### ISSUE TITLE
Unable to connect to socket: timeout

### ISSUE THREAD

**Issue by wthhelp** [ethereum/mist#2801]
``````
Version: `0.0.0`
OS & Version: Windows 10
Node type: geth
Number of blocks synchronized: 4049283
``````

Hello,

I tried to send some ether but everytime I get an error saying "Unable to connect to socket: timeout".
What does it mean? How do I fix it?

thank you

**Comment by terenc3t** [comment]
Version: `0.0.0`
OS & Version: Mac OSX
Node type: geth
Number of blocks synchronized: 555533

I am seeing the same issue as well

**Comment by sathishvj** [comment]
Restarting the app or geth is your best bet.

Also check if there is an antivirus, firewall rule, or proxy blocking anything.

**Comment by wthhelp** [comment]
Thanks for the advice, 
I tried all of the following: restarting the app, restarting geth, checked firewall, checked antivirus, upgraded Wallet to 9.0 and yet the same error occurs.

**Comment by LancerLunatic** [comment]
@sathishvj how do i know what firewall rules to look for? I need to know the ports that would be blocked right? i'm having the issue. I've restarted multiple times. How do i restart geth? I don't think i'm using it. I"m using the EtherWallet Mist GUI client.

Windows 7
Ether Wal Version 0.8.10
678 blocks left atm but even when i'm all sync up it still can't connect.

Thanks!

**Comment by Jayhawk1901** [comment]
Same issue for me and I am trying to access 1.2 ETH in my Ethereum Wallet.  Anyone find a solution?

**Comment by mohsinmuneer** [comment]
Same issue for me i am deploying the code

**Comment by turtle977** [comment]
Any update? I am deploying as well

**Comment by evertonfraga** [comment]
Mist spawns a Geth instance, responsible for syncing with the blockchain. Please refer to their repository in order to get help directly from the source.

https://github.com/ethereum/go-ethereum

**Comment by mohsinmuneer** [comment]
We’re seeking a Blockchain Developer to join our Emmaculate team please send resume info@emmaculate.com

**Comment by debragail** [comment]
I'm having this issue as well with Ethereum Wallet 0.10.0

**Comment by matabyte** [comment]
same here
