### ISSUE TITLE
Do - minimize to the system bar icon and the minimize the window when closing.

### ISSUE THREAD

**Issue by DJMorgan** [ethereum/mist#2803]
``````
Version: `0.8.10`
OS & Version: windows 10 x64
``````

Do - minimize to the system bar icon and the minimize the window when closing wallet .
It would be very convenient.

**Comment by evertonfraga** [comment]
Thanks for the suggestion @DJMorgan. Here's a list of features you can follow and add more:
https://github.com/ethereum/mist/issues/1455
