### ISSUE TITLE
stack with 0 contributions

### ISSUE THREAD

**Issue by soma11soma11** [ethereum/mist#2805]
Using Mist wallet, I set up a private net. And I sent my Ether from account1 to account2, but it stacks with 0 contributions.

**Comment by evertonfraga** [comment]
The transactions you create have to be mined by someone. As the network is private, this someone is you :)

1. Open the dev console `Develop > Toggle Developer tools > Mist UI > [Console]`.
2. You can control mining by typing into the console: `web3.miner.start()` and `web3.miner.stop()`

have fun

**Comment by soma11soma11** [comment]
that is true. thank you for your quick response!
