### ISSUE TITLE
Couldn't connect to the node, did it crash in the background? - Unable to tell if password issue

### ISSUE THREAD

**Issue by joshuad31** [ethereum/mist#281]
When I attempt to send a transaction it says:
**CONFIRMING...**
Then I get this error:
![password](https://cloud.githubusercontent.com/assets/5976059/13584677/4869ab86-e47d-11e5-9624-ebb03fffd6e6.jpg)

Couldn't connect to the node, did it crash in the background?
Prompts me again for my password.  Unable to tell if this issue is caused by it not recognizing my password but node does not crash.
What does "couldn't connect to the node" mean?

**Comment by joshuad31** [comment]
I have always requested a better password management system for Mist but so far no luck.  What I would like is:
1. Ability to attempt to unlock any account without having to send a transaction just by right clicking on it and selecting "unlock" or selecting "unlock account" from a drop down once inside it.
2. The little key icon next to the account icon changing depending if its locked or unlocked
3. Ability to change passwords for accounts.

**Comment by frozeman** [comment]
It seems like your IPC connection to the node failed. We see this quite often on windows now and need to investigate. @bas-vk do you have any idea?

Thanks for the ideas. We are focusing right now on other things and Mist is a browser, so these features will be added but not to the wallet. Some of the ideas you have like changing password, would also require new node endpoints, which is not fast to add. So please be patient.

**Comment by Twaah** [comment]
I have the same issue :( What is causing this? It's a big and urgent problem (at least for me) as I cannot access my coins now.

**Comment by Twaah** [comment]
FYI: Restarting my computer solved the issue

**Comment by allmails888** [comment]
I just encountered this same error message today. Had send an earlier payment successfully but the recent one game me this same message when trying to send funds. I had to resort to using geth on dos to send eth instead (at least that went through ok). Even after rebooting PC, i still get the same message. I am using mist 0.6.2 on windows 8.1pro.

**Comment by luclu** [comment]
Hey @joshuad31, @Twaah, @allmails888 how is version 0.7.2 behaving on this?

**Comment by joshuad31** [comment]
@luclu no problem lets close this thread.

**Comment by radekradekradek** [comment]
Hi, 

I'm on version 0.7.2 and i'm having the same issue. Using geth directly on dos does work though, just not through the Mist UI. 

I'm also on Windows 8.1. 

Thanks in advance, 
radek^3

**Comment by piranha1** [comment]
mac 10.11 Having same problem.. Rebooting doesn't solve the issue. Neither does downgrading

**Comment by ironmau** [comment]
I have the same issue now. running  0.7.2 windows 10 pro.

**Comment by ironmau** [comment]
rebooting it just worked for me too. thanks

**Comment by luclu** [comment]
Please try out version 0.7.3 [link](https://github.com/ethereum/mist/releases) as that version cointains improvements tackling this timing issue.

**Comment by luclu** [comment]
We just released version 0.7.5 which contains a complete rewrite of the IPC connection handling. Please give me some feedback if this solves your problems.

**Comment by allmails888** [comment]
This version hangs - total blank interface when launched. Switching bck to 0.7.4

**Comment by ozothebozo** [comment]
On the latest version and i get this error message. Don´t know whats wrong, on Windows 10. 
![image](https://cloud.githubusercontent.com/assets/26300152/23762965/28aca0e0-04f8-11e7-8071-ba971f809f25.png)

**Comment by muradmustafayev** [comment]
Running Mist 0.8.9 on Win7.
Same issue but when I want to create new smart contract and adding password this error shows up

Any suggestions?

**Comment by techamazed** [comment]
i am running version 0.8.10 on mac, same issue. any help pls?
