### ISSUE TITLE
slow catching up blocks and HD torture

### ISSUE THREAD

**Issue by ernstMreicher** [ethereum/mist#2812]
Version: `0.8.10`
OS & Version: osx 10.12.6 (16G29)
Node type: geth
Number of blocks synchronized: 3.925.341

geth folder increase to over 64 GB
HD constantly working and heating up....
;-((
is this normal?????

at this block catching up speed I get up to date in days or weeks!?!?!?!?!

**Comment by Foxcor** [comment]
"is this normal?????"
Yes.

"at this block catching up speed I get up to date in days or weeks!?!?!?!?!"

There is a problem, at times the synchronization stops. If the blocks are not updated for a long time, restart the wallet

**Comment by evertonfraga** [comment]
This is a geth issue. Follow here: https://github.com/ethereum/go-ethereum/search?q=hdd+sync&type=Issues&utf8=%E2%9C%93
