### ISSUE TITLE
Miss my ETH when try to fund ETH official wallet with "Fund with Bitcoin"

### ISSUE THREAD

**Issue by Nikhsipe** [ethereum/mist#2813]
Hello,
I dowloaded Ethereum wallet for Mac OS from this web site: https://www.ethereum.org.
Than I created the wallet and tap «Fund it with Bitcoin».
![Uploading PastedGraphic-1.png…]()

Then I transferred the bitcoins to the wallet that was in the window: 137B9DkAghzBAXuWaBPbVNaaGkGuY61FqE and waited for the operation complete.
![Uploading IMG_5825.PNG…]()

The balance of my ETH wallet still 0. 
![Uploading PastedGraphic-2.png…]()

Could you help please?

**Comment by Foxcor** [comment]
Look, everything is synchronized blocks ???
![sync](https://user-images.githubusercontent.com/30261332/28526237-9c0e93ba-708f-11e7-88a4-6ced1100565b.jpg)

**Comment by sathishvj** [comment]
All the blocks need to be synchronized to see the funds.  But you can also check it at etherscan.io/address/0x... put your address at the end.

**Comment by Nikhsipe** [comment]
Hello,

Thanks you for fast reply. Not all. I ll synchronize all data and come with feed back.
С Уважением / Best Regards,

Михаил Епишкин/ Mikhail Epishkin
epishkinmv@gmail.com <mailto:epishkinmv@gmail.com>
+79169266585

**Comment by Nikhsipe** [comment]
Hello,

Many thanks for the reply. It is ok. Thanks!

С Уважением / Best Regards,

Михаил Епишкин/ Mikhail Epishkin
epishkinmv@gmail.com <mailto:epishkinmv@gmail.com>
+79169266585

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
