### ISSUE TITLE
Reinstallation of Mist

### ISSUE THREAD

**Issue by IvanM1993** [ethereum/mist#2814]
``````
Version: `0.8.10`
OS & Version: windows
Node type: `eth/geth`

Hi all. Is it possible when reinstalling Mist to keep the old chain of synchronization blocks(chaindata)? Or should I delete them?

**Comment by Foxcor** [comment]
Can.
We make a new synchronization as soon as the blocks begin to appear
![copy](https://user-images.githubusercontent.com/30261332/28526144-4b729f1e-708f-11e7-8426-b090be505cba.jpg)

Just copy the old files, do not replace !!!!

**Comment by IvanM1993** [comment]
Thank you very much.
