### ISSUE TITLE
Haven´t got my founds it has been 6 days now...!

### ISSUE THREAD

**Issue by linusj24** [ethereum/mist#2816]
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by Foxcor** [comment]
Look, everythin
![sync](https://user-images.githubusercontent.com/30261332/28525924-82b74a2a-708e-11e7-9b27-85f13aa9e712.jpg)
g is synchronized blocks ???

**Comment by sathishvj** [comment]
same as other ticket, so can you close this?
