### ISSUE TITLE
Ethereum wallet not showing transfer from coinbase or shapeshift transactions the ether trans was 12 day ago

### ISSUE THREAD

**Issue by deisel16** [ethereum/mist#2817]
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by Foxcor** [comment]
Look, everything is synchronized blocks ???
![sync](https://user-images.githubusercontent.com/30261332/28525888-63cac920-708e-11e7-8552-052ef22d5faa.jpg)

**Comment by sathishvj** [comment]
We cannot make any deductions without any info like the account address.

**Comment by deisel16** [comment]
I understand. How can I give address and be safe? Also I made a direct credit card purchase of 150 usd to my mist wallet and it hasn't shown up yet.

**Comment by deisel16** [comment]
I also transferred about 65 tenx or (PAY) into my mist.

**Comment by deisel16** [comment]
How do I give address and be safe at the same time

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
