### ISSUE TITLE
Missing Ether

### ISSUE THREAD

**Issue by keybagd** [ethereum/mist#2818]
Hello
I really hope someone will help :/

Im missing 5 ether
I mined them then transferred them to a regular network and they never arrived. I verified the addresses were correct, the blockchain has 2,001 confirms on the transfer but my wallet is empty

Pleases someone help!

<img width="1209" alt="screen shot 2017-07-24 at 7 22 24 am" src="https://user-images.githubusercontent.com/6887805/28527892-e03c02f6-7040-11e7-9745-038349d5e6b1.png">

https://ropsten.etherscan.io/tx/0xf0d47d9577eecb32c2c37bbfb005b96bf052acd446ce9ca0270128fc62386440

![img_0201](https://user-images.githubusercontent.com/6887805/28528022-551dd338-7041-11e7-8f57-d1081ca3404c.JPG)

![img_0202](https://user-images.githubusercontent.com/6887805/28528765-7fbf1ae6-7043-11e7-8611-61f18d39470f.JPG)

``````
Version: `0.8.10`
OS & Version: osx
Node type: `eth/geth`
Number of blocks synchronized: 1,363,192
``````

**Comment by sathishvj** [comment]
From what I can see, your mining was done on the test net and you have loaded the same account/address on the main net.  That won't work.  What is mined on the test net will only remain on the test net.

**Comment by keybagd** [comment]
So have I completely lost 5 ether? I'm so confused. I understand the test-net issue, but does that mean all coins mined on testnet are useless to the regular network? What can I do here? How to I get my coins back? I mined for a couple month to hit that block. It

**Comment by keybagd** [comment]
So have I completely lost 5 ether? I'm so confused. I understand the test-net issue, but does that mean all coins mined on testnet are useless to the regular network? What can I do here? How to I get my coins back? I mined for a couple month to hit that block. It
