### ISSUE TITLE
v0.9.0 seems to fail during initialization

### ISSUE THREAD

**Issue by peteski22** [ethereum/mist#2819]
``````
Version: `0.9.0`
OS & Version: Windows 10 (x64), 16GB RAM, i7 (mobile) CPU.
Node type: `eth/geth`
Number of blocks synchronized: 4066471 ?
``````
Running 'Ethereum Wallet.exe' results in an error attempting to connect to network.

[node.zip](https://github.com/ethereum/mist/files/1170211/node.zip)

**Comment by evertonfraga** [comment]
It seems you got an Out Of Memory error from geth. Pleasee try to update it to 1.6.7, as it was currently using 1.6.6.

thanks for reporting.

**Comment by peteski22** [comment]
@evertonfraga that solved the problem I reported, thanks for getting on that so quickly. Sorry I didn't think to look for updates to geth.

Without wanting to digress too much, any idea why it seems to take forever/hang downloading the blockchain? I'm on about 30.2GB but the Mist app doesn't seem to like downloading it or telling me what's going on. I resorted to using the geth console to get as much as I could.

Thanks

**Comment by evertonfraga** [comment]
that's a question for the go-ethereum team :)
But they are always working to optimise the chain download and storage size.
https://github.com/ethereum/go-ethereum/issues

i'm closing this now, but feel free to reopen should you have more mist questions.

**Comment by peteski22** [comment]
@evertonfraga sorry, but I've noticed that despite having Geth 1.6.7 now (in control panel and here: C:\Program Files\Geth) I seem to have issues starting the Mist wallet on it's own, I have to manually start geth via cmd prompt. Furthermore, the logs Mist has still refer to 1.6.6 and even in the app when it *works* it claims 1.6.6 is doing something for it.. any ideas what this is about?

![image](https://user-images.githubusercontent.com/487783/28594700-ca587dd6-7188-11e7-8934-d8495763c189.png)

Thanks

**Comment by peteski22** [comment]
It looks like under `%APPDATA%\Ethereum Wallet\clientBinaries.json` there are references to Geth 1.6.6, I'm unsure if this is generated somewhere or it's just for UI purposes, i.e. if I change:

`{
  "clients": {
    "Geth": {
      "version": "1.6.6",`

to:

`{
  "clients": {
    "Geth": {
      "version": "1.6.7",`

Would that update the version reported (in the above post) in the UI, not keen to just *try* it as it seems there's a number of links etc. as part of the JSON. 

Still have no luck running the wallet without manually starting geth from the command prompt though, maybe related issues.. hmmn.
