### ISSUE TITLE
'Watch Contract' or 'Add Wallet Contract' showing blank screen

### ISSUE THREAD

**Issue by eddieoz** [ethereum/mist#282]
When importing a wallet contract (multsig p. ex.) or a watching a contract (adding the address and ABI), Mist is showing a blank screen.

How to reproduce:
1) create a multisig wallet (add wallet contract)
2) write down the contract wallet address
3) delete the contract wallet
4) import the wallet using the address

The blank screen occurs when importing the contract or contract wallet on another machine too (without deleting)

If you dont delete the contract wallet and just import a new one using the same address, both is showing ok. But if you delete the first one, the imported one now is showing blank.

Mist version: 0.5.1

**Comment by frozeman** [comment]
A screenshot would help.

You normally import wallets using the "Add Wallet" -> import button in the wallet tab. Not the contract tab.

But please add a screenshot so i can see what is white

**Comment by eddieoz** [comment]
Hi!

Attached the screenshot.

The issue occurs when adding a multisig wallet from Wallets -> Add Wallet Contract -> Import Wallet ->  and contracts from Contracts -> Watch Contract 

When watching a Token Contract (from menu Contracts), it loads ok. But when watching any other contract (even a multisig contract deployed manually) the screen is blank too.

![captura de tela 2016-03-08 10 18 58](https://cloud.githubusercontent.com/assets/3277320/13602813/c5315d72-e517-11e5-912b-05e5ee444818.png)

**Comment by taoteh1221** [comment]
I encountered this same issue in v0.5.1 in _Ubuntu on my Laptop_ after importing an existing wallet. When you click on the wallet it takes you to a blank page..._but Ubuntu on my desktop PC did **not** have this issue with v0.5.1_. Same issue watching your "Ethereum Foundation Tip Box" contract address, just shows a blank screen instead of the contract information.

**Comment by eddieoz** [comment]
Don't know if it could help, but I've made a screen capture showing the problem. 
Trying to import the address and ABI (json interface) from a working voting contract.

[Watch contract.mov.zip](https://github.com/ethereum/mist/files/163953/Watch.contract.mov.zip)

**Comment by frozeman** [comment]
Thanks, i think it simply tries to redirect to a page which doesn't exist. Will take a look at some point. thanks!

**Comment by bamos01** [comment]
I am getting this same problem when I entered the contract info for the Ethereum Foundation Tip Box after following their instructions on webpage- I am seeing the balance of the contract correctly displayed on the contract page in mist but when I click on it, I am taken to blank page.  I have another contract on my watch list that displays correctly, so I dont know where the error is.

**Comment by MSeven** [comment]
@bamos01 @bpierre I have the same issue.
It seems to be related to the address being mixed case. If you re add the address in all lowercase the (new) contract link works.

**Comment by frozeman** [comment]
thanks, will fix

**Comment by zgorizzo69** [comment]
@MSeven thx  your trick is working ;)

**Comment by wchuan11** [comment]
I have 2 watch contracts (both at same address). 1 showing blank (from 0.5.2 OS X version) and 1 showing the correct contract details after adding in latest wallet version 0.7.2.

Is it possible to remove the contract showing blank anywhere?

Tried the trash button but it will trash the latter contract.

Anyone have success in this?

![screenshot 2016-05-02 19 15 10](https://cloud.githubusercontent.com/assets/467814/14953238/4afe3026-109a-11e6-870a-030bcf566796.png)

**Comment by luclu** [comment]
@frozeman did this receive some love of yours? :)

**Comment by frozeman** [comment]
I fixed that, as it was a wrong address formats being saved internal into minimongo. @alexvandesande can you confirm that this is fixed?

**Comment by luclu** [comment]
This works for me. I will close this for now.
Please give me a small ping-back if you still encounter this issue!
