### ISSUE TITLE
Wallet 0.9 Windows installer blocked by Windows 10 Defender

### ISSUE THREAD

**Issue by tmanthey** [ethereum/mist#2821]
``````
Wallet
Version: `0.9.0`
OS & Version: windows 10 

``````

Starting the installer triggers the Windows 10 Defender which blocks setup from continuation. 

Double click the installer will trigger the Windows 10 Defender:

"The computer has been protected by Windows 

The Windows Defender SmartScreen has blocked an unknown App from starting. The execution of this app may constitute a risk for the PC
App: 
Ethereum-Wallet-installer-0-9-0.exe 
Publisher: Unknown Publisher
"

German original text
"Der Computer wurde durch Windows geschützt
Von Windows Defender SmartScreen wurde der Start einer unbekannten App verhindert. Die Ausführung dieser App stellt u. U. ein Risiko für den PC dar.

App: 
Ethereum-Wallet-installer-0-9-0.exe 
Herausgeber:  
Unbekannter Herausgeber "

**Comment by robwent** [comment]
I get this too.

For anyone wanting to install it, you can click on the 'more info' link and a 'run anyway' button will appear.

**Comment by evertonfraga** [comment]
Thanks for solving that, @robwent, and for the heads up @tmanthey.

**Comment by tmanthey** [comment]
Guys that is not a good fix for a Wallet app. That is not the kind of app where you would accept such a security warning in the installation process. Speaking for myself I will not install Wallet 0.9 for that reason.

**Comment by robwent** [comment]
@tmanthey It's not a fix, it's a workaround for people who come here to report the issue.

I assume that 'Thanks for the heads up' means that they are now aware of the issue and can fix it.

**Comment by evertonfraga** [comment]
We used to have code signing in Windows and we're now aware it's not being signed anymore. It surely is now on our backlog for our following version.
