### ISSUE TITLE
How do we resync mist wallet to our new changed Ethereum directory?

### ISSUE THREAD

**Issue by yukiko97** [ethereum/mist#2824]
Version: 1.6.7
OS & Version: Mac OSX 10.12.5
Node type: geth
Number of blocks synchronized: 4029075

The size of Ethereum folders had gotten really huge, 62++GB at this point of my writting, i do not have much space in my SSD on my mac, so i decided to move the folder and change directory in geth using --datadir ... command, i succeessfully changed my directory. However when i start my ethereumwallet.app, it doesnt sync to my new datadir, anything i need to do to make the wallet works properly off my external drive where my Ethereum folder is in?

![screen shot 2017-07-24 at 5 14 32 pm](https://user-images.githubusercontent.com/20425284/28545098-a7bf2978-7093-11e7-984e-507555d25f00.png)

As you can see from my terminal my datadir and ipc path is my external drive

![screen shot 2017-07-24 at 5 15 46 pm](https://user-images.githubusercontent.com/20425284/28545167-f1af0788-7093-11e7-9875-b95090f8584c.png)

Thanks

**Comment by evertonfraga** [comment]
It looks like there's another process using the 30303 port. Please try to close all geth instances and start Mist again. 

Read the Wiki entry on this subject: 

**Bind: address aalready in use**
https://github.com/ethereum/mist/wiki#bind-address-already-in-use
