### ISSUE TITLE
Browser security warning when downloading 0.9.0

### ISSUE THREAD

**Issue by TeunVR** [ethereum/mist#2826]
``````
Version: `0.9.0`
OS & Version: macOS 10.12.5, Safari 10.1.1, Chrome 59.0.3071.115
``````

On OSX both Safari and Chrome give a security warning when downloading the 0.9.0 DMG.
Used DNS: 8.8.8.8, 8.8.4.4

![chrome](https://user-images.githubusercontent.com/69744/28564079-274eed60-7128-11e7-88cc-271b4f46287f.png)

![safari](https://user-images.githubusercontent.com/69744/28564080-2765a500-7128-11e7-8994-6235de56ea33.png)

**Comment by burrocampeador** [comment]
Same problem

**Comment by subcreator** [comment]
same on firefox, kubuntu 16.04

**Comment by AndersRassner** [comment]
Same on chrome, Windows 10 for the adress 
github-production-release-asset-2e65be.s3.amazonaws.com

**Comment by willvlad** [comment]
Same here! Please advise why this URL is listed as deceptive.

**Comment by evertonfraga** [comment]
Github uses amazon AWS to host releases. It might be blacklisted by the browsers, as Github is also used to spread malicious softwares.

It is ok to download from there, and before install, make sure the checksums 
 match! https://github.com/ethereum/mist/releases/tag/v0.9.0

**Comment by evertonfraga** [comment]
Also, people should be this attentive like you guys 👍

**Comment by remcoros** [comment]
Should be fixed now or soonish, a lot of repo's have this issue and I saw some reddit headlines about it.

**Comment by g17hu84cc7** [comment]
Was the download file recently updated? The MD5 checksum does not match for me after download, but this could be because the file was recently changed and the checksum not yet updated.

417eb91b23dbb23d208709adeae8f15b is listed on the download page
f19165e94dc1facba3289f43abcda58b is returned in terminal when checking

**Comment by TeunVR** [comment]
Looks ok now. Safari and Chrome are no longer complaining here.
md5 is ok.

**Comment by evertonfraga** [comment]
Thank you all. I'm closing the issue.
