### ISSUE TITLE
ECONNREFUSED and Blank Mist Screen

### ISSUE THREAD

**Issue by lazukars** [ethereum/mist#283]
I've cloned the latest version of Mist ( tag 0.5.1 ), and followed all of the build instructions here ( https://github.com/ethereum/mist/tree/0.5.1 ). However when running cd mist/interface && meteor this error occurs and the mist screen at localhost:3000 is completely grey and blank:
NODECONNECTOR ERROR { [Error: connect ECONNREFUSED /home/user/.ethereum/geth.ipc] code: 'ECONNREFUSED', errno: 'ECONNREFUSED', syscall: 'connect', address: '/home/user/.ethereum/geth.ipc' } Node type: geth
My OS is Ubuntu 14.04

**Comment by frozeman** [comment]
You need to start a `geth` yourself before with:

`geth --ipcpath /home/user/.ethereum/geth.ipc`
