### ISSUE TITLE
Wallet Contract missing/bug

### ISSUE THREAD

**Issue by nav1d** [ethereum/mist#2834]
``````
Version: `0.9.0`
OS & Version: Windows 7
Node type: `eth/geth` on 'light-mode'
Number of blocks synchronized: 4076100
``````
Hi,
yesterday(25-july-2017) i tried to create a simple wallet contract, i did everything correct and after a while, ~0.04 ETH was taken from my account due its gas/fee. but now after ~24 hours nothing happened on my wallet, i can not see any wallet contract.
also i should add that i'm sync and always on '--light-mode', i don`t know if its related to my problem or not.

thanks
Navid

**Comment by evertonfraga** [comment]
Hi @nav1d, the Wallet is not yet fully compatible with the light client, therefore this misbehaviour. 

But most likely your contract was created, and you have to just add it to your contract list. 

1. With your account address, search it on https://etherscan.io, and locate the transaction that created your contract.

2. on the wallet, go to Contracts > Watch contracts.

3. paste your wallet address, name it, and paste [this code](https://gist.github.com/evertonfraga/5791b2d698ab1d762e1f357c92ea484a/raw/ced352d6d2418cc80cfdfff2e7d93e600150769f/Wallet%2520ABI).

**Comment by nav1d** [comment]
@evertonfraga , yeah! thanks. i didn't know about these 3steps.

**Comment by Trollgaard-Sr** [comment]
I have the same problem on Windows 10 Pro, but I am not in light mode.
The contract was made and I can watch the wallet using the above method.

**Comment by DecentralizedIT** [comment]
A quick workaround

Open:
Develop -> Toggle developer tools -> Ethereum Wallet

In the console:
Wallets.find().fetch()
Wallets.remove("_id")

Done!

**Comment by insiderq** [comment]
Same issue here.
Workaround from @DecentralizedIT didnt work.
What has worked:
1 - `Create wallet contract`  Getting freeze at "Creating"
2 - Removing all files from  `File -> Backup -> Application Data ` 
3 - Restarting Mist
4 - Then `Create wallet contract -> Import wallet` (here you need to know the address of contract that in fact was created. I just got that from etherscan)
