### ISSUE TITLE
ETH still not on account ballance 

### ISSUE THREAD

**Issue by Nesbin** [ethereum/mist#2836]
``````
Version: `0.9.0`
OS & Version: Windows 7 Ultimate
Node type: `eth/geth`
Number of blocks synchronized: -491
``````
 -->

Hi, I did a transfer from Ethereum wallet early today, but ETH is still not on ballance on my kraken wallet, anyone can help?

**Comment by evertonfraga** [comment]
Please search for your account on https://etherscan.io and check if the funds really got out from it towards Kraken's account.

If it did, please get in touch with their support. Thanks.

**Comment by Nesbin** [comment]
I communicated also with kraken support, and it seems that after transaction fee was charged, the amount sent to Kraken account was lower than their minimum, which is 0.05. So I have to wait to mine another eth amount to send it to the same account number ot be above 0.05 in order to get it credited. Anyway thanks.
