### ISSUE TITLE
Multisig wallet not appearing

### ISSUE THREAD

**Issue by spiderworm** [ethereum/mist#2838]
``````
Version: `0.9.0`
OS & Version: Windows 10
Node type: geth
Number of blocks synchronized: 4,076,775
``````

Hello,

I created a multisig wallet in Mist, but it does not show up in the Wallet Contracts. .05 ether was deducted from my wallet for the transaction, however.

The only error I see in the console is: Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by evertonfraga** [comment]
Can you please check these steps? 
https://github.com/ethereum/mist/issues/2834

**Comment by evertonfraga** [comment]
That is a bug which we are aware of. Follow https://github.com/ethereum/mist/issues/2830 for updates. I'm closing here now. Thanks
