### ISSUE TITLE
gas price to low for network propagation

### ISSUE THREAD

**Issue by koeppelmann** [ethereum/mist#284]
I guess the cheapest setting a user can pick in the UI should still be a one that would be accepted by the network or at least the users own node. Currently this is not the case.

**Comment by frozeman** [comment]
The idea here is that miners can set their own min gasPrice, so the user should be able to send cheap tx and hope that some miner picks it up.

Currently our gasPrice market is not very dynamic as miners and users don't take advantage of that, but once we have nice interfaces which let miners set this value easily it will become dynamic, i assume.

We can keep this issue open for discussion.

**Comment by chfast** [comment]
Can I configure geth to allow lower fees?

**Comment by frozeman** [comment]
I don't know exactly how, but its an issue we are debating, if we should allow gas prices below the set limit and rather to propagate them or not.

@obscuren

**Comment by arhuaco** [comment]
I need to set a custom gas limit for Storj. I don't know how with the Ethereum wallet.
