### ISSUE TITLE
Mist 0.9.0 missing eth in web3

### ISSUE THREAD

**Issue by ropod7** [ethereum/mist#2841]
``````
Version: `0.9.0`
Mint (Debian x64) & linux
Node type: `geth` Ropsten testnet
Number of blocks synchronized: 1376815
``````

Connetcted to node perfect, logs are fine, but not web3 library.

![imag0043_1](https://user-images.githubusercontent.com/7129955/28641783-13eb40c0-7259-11e7-8139-3af5ddfaef20.jpg)

 -->

**Comment by slothbag** [comment]
According to their release notes Web3 is no longer injected in Mist 0.9.0.. only the current provider is there.

You have to bundle your own web3 library and instantiate your own web3 object.

**Comment by ropod7** [comment]
I am really don't understand. Why do we need Mist then? Do you have any docs somewhere?

**Comment by ropod7** [comment]
I can't declare own web3 instance, because:
`typeof Web3
"undefined"`

**Comment by evertonfraga** [comment]
Web3 is a js library to make it easy to interacr t with the ethereum provider. And Web3 can be included by each dapp developer. 
What Mist does is inject the ethereum Provider, a bridge to the blockchain. 

Hop into their channel for further help: https://github.com/ethereum/web3.js

thanks.

**Comment by ropod7** [comment]
Dear platform developers, would you like to provide every month global changes? As a dapp developers we need stability of principles.

thanks.
