### ISSUE TITLE
Bundled swarm uses lots of bandwidth

### ISSUE THREAD

**Issue by slothbag** [ethereum/mist#2843]
Version: `0.9.0`
OS & Version: windows
Node type: `geth`
Number of blocks synchronized: all

Mist now automatically starts swarm behind the scenes, Swarm appears to use a substantial amount of bandwidth.  Some users may not be aware of the additional bandwidth consumption from this process.

It would be great to disable swarm if I have no need for it.

**Comment by evertonfraga** [comment]
You can start Mist with the `--swarmurl` flag:

`C:\Program Files\Mist\Mist.exe" --swarmurl="http://swarm-gateways.net`

Closing this for now. Should you have any more questions, feel free to reopen.
