### ISSUE TITLE
Still missing eth in wallet from 45 days ago 

### ISSUE THREAD

**Issue by QconSling3r** [ethereum/mist#2844]
``````
Version: `0.9.0`
OS & Version: windows 7 64-bit
Node type: `eth/geth`
Number of blocks synchronized: 0
``````
As stated, still not seeing some eth i tested to the wallet after 45 days. Link to blockchain transaction: https://etherscan.io/tx/0xfc4d55cf6e2ee18f6e5a914ee0c1d96930a2bf7cd38e0cb3ac109e44f3e4d221
Also, every time I try to sync my wallet it always times out or stops.I would really love some answers.

**Comment by ncsolar** [comment]
You could import that wallet to https://www.myetherwallet.com/  if you are having issues with Mist

**Comment by QconSling3r** [comment]
Thank you. that worked.
