### ISSUE TITLE
Mist 0.9.0 wallet contract hangs on being "created" 

### ISSUE THREAD

**Issue by youguanxi** [ethereum/mist#2845]
```
Version: `0.9.0`
OS & Version: windows 7 x64
Node type: `geth`
Number of blocks synchronized: 4081324
```

I've created a wallet, set the gas price - got it substracted from my account, but the wallet is still being "created".
Please help!
'Failed to load resource: the server responded with a status of 404 (Not Found)
8b6a885….js:329 Connect to node...
8b6a885….js:333 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

**Comment by evertonfraga** [comment]
Hi @youguanxi that's seems like a bug indeed. 

But it turns out your wallet was probably created. Please follow these steps in order to have it displayed: https://github.com/ethereum/mist/issues/2834#issuecomment-318040401

**Comment by ianmdilick** [comment]
I have the same issue, but there is no transaction on etherscan that shows my wallet was actually created.

**Comment by Munzey** [comment]
is there a roadmap for what version this should get patched in? tried making a multi sig this morning got same issue, as mentioned it was created. thanks for tips to get it displayed!

**Comment by DecentralizedIT** [comment]
Also having this problem

**Comment by CakeBrewery** [comment]
I am having the same issue creating a wallet contract in the main network. It's stuck on "Creating...". 
Using Windows 10 64 bit on Ethereum Wallet 0.9.2.

**Comment by SnoopyDogy** [comment]
I meet same issue.
Mist 0.9.2

**Comment by SnoopyDogy** [comment]
I retry after uncheck Sync with light client Beta, now it works well on the Robsten Test Network.

**Comment by jontis** [comment]
I think my problem is different, because I'm almost certain that I was never presented with something letting me set a gas price.

**Comment by sqlambda** [comment]
It's really annoying, I'm not sure what to do to fix the current state. The wallet icon is flickering, the transaction shows as success and no solution showed here worked.

**Comment by evertonfraga** [comment]
Hi everyone, hang on, the fix is on its way.

The issue is: when using the light client, it currently does not return the address of the created wallet on `getTransactionReceipt` RPC call. 

This pull request (https://github.com/ethereum/mist/pull/3265) aims to fix that, and from preliminary tests, it works well. Now I'm tweaking the Wallet code to account for this change.

**Comment by evertonfraga** [comment]
Hi all, fix is on its way.

Please refer to this link for any further discussion: #3269.
