### ISSUE TITLE
Memory usage geth.exe

### ISSUE THREAD

**Issue by jovada** [ethereum/mist#2846]
I've installed 0.9.0 and noticed that the syncing is very slow (right now at block 4,061,160. Last sync was about a week ago.)
I opened my Task Manager and saw that geth.exe is taking more and more of my memory. Right now at 3 GB after about ten minutes and the amount keeps rising quickly.

**Comment by evertonfraga** [comment]
Please refer to `geth` repository for further help. 
https://github.com/ethereum/go-ethereum/issues

Thanks!
