### ISSUE TITLE
"Import accounts" Disabled in Mist 0.9.0

### ISSUE THREAD

**Issue by zilions** [ethereum/mist#2848]
The "Import accounts" button under the "File" menu is disabled for some reason.

[https://i.imgur.com/bPeQzML.jpg](https://i.imgur.com/bPeQzML.jpg)

Running on the live network, not Testnet/Ropsten. Chaindata is fully synced.

Why would this be?

**Comment by evertonfraga** [comment]
Thanks for the report @zilions!

**Comment by evertonfraga** [comment]
This will be fixed, and in the meantime, you can go to `Accounts > Backup > Accounts...`, and place your keystore (json file) on that same directory.

Sorry for the trouble.

**Comment by graph1994** [comment]
Hey is this currently being worked on? If not I'd like to try to fix it! :D

**Comment by evertonfraga** [comment]
Should be fixed already. 

Hey @graph1994, if you are still up for contributions, look for this label: https://github.com/ethereum/mist/issues?q=is%3Aopen+is%3Aissue+label%3Abeginner
