### ISSUE TITLE
Cannot find "delete" icon to delete contract in 0.9.0

### ISSUE THREAD

**Issue by hingjlee** [ethereum/mist#2849]
``````
Version: 0.9.0
OS & Version: windows 10
Node type: geth rinkeby / Main
Number of blocks synchronized: 612,958 / 4,083,449 
``````
I cannot find "delete" icon to delete contract.  Older version is next to the "edit" icon and type "delete" upon confirmation of deletion.

**Comment by evertonfraga** [comment]
Thanks @hingjlee.

**Comment by hingjlee** [comment]
Found how to delete.  The "delete" button will only appear when you scroll down such that the contract icon becomes mini icon on the top left hand corner AND move the mouse to the right hand side of the mini contract icon, a mini "delete" button will appear.

**Comment by josebrwn** [comment]
This should not have been closed. Delete function is now an Easter egg.
