### ISSUE TITLE
Navigating bzz from mist?

### ISSUE THREAD

**Issue by bsundman** [ethereum/mist#2852]
``````
Version: `0.9.0`
OS & Version: all
Node type: `geth`
Number of blocks synchronized: fully synced
``````
The release notes for Mist 0.9.0 ( https://github.com/ethereum/mist/releases/tag/v0.9.0 ) say that you can visit swarm urls.  When I try bzz://theswarm.eth I get a url not found error.  Is there something I'm missing or is this a bug?

**Comment by workfunction** [comment]
Here too. And I cannot find the `File > Upload to Swarm` option.
I'm on the macOS 10.12

**Comment by evertonfraga** [comment]
Wait, it doesn’t even show to you on the menu?
Are you sure you are on 0.9.0?

**Comment by bsundman** [comment]
Upload to swarm shows in the menu for me.  Now the error screen has changed to "404 page not found" instead of "url not found".

**Comment by workfunction** [comment]
Oops. Sorry I found that. But bzz URL still not working.

**Comment by bsundman** [comment]
After days of trying, multiple error messages and blank pages, it's finally working.  bzz://theswarm.eth/ is now showing the page I was expecting to see.  I didn't do anything different.  I'm guessing that ens resolution takes some time to find a connection to the data?
