### ISSUE TITLE
ALL my Coins have been taken away overnight

### ISSUE THREAD

**Issue by GC2012** [ethereum/mist#2853]
I started to report issues following the wallet upgarde, missing token ...
Yesterday the 28 July, I was able to see them all back. Now ALL my token are GONE, incl ETH.  What to do now ?

``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by GregoryChemin** [comment]
Any chance to report that account as Phishing ? or lock it ?
