### ISSUE TITLE
PHISING SCAM STORY $ 100 K +

### ISSUE THREAD

**Issue by GC2012** [ethereum/mist#2858]
Here is a sad story, do NOT follow instruction
Alert message received on the 17 of July via slackbot, see below
Inside an an internet link to redirect you to a FAKE internet site where you can increase protection of your wallet, it sounds great BUT this a BIG PHISING Scam, do NOT enter instruction. 

All my coins ETH and ICO were taken overnight and remaining balance = 0.00

What can be done ? can we report that address as "Phising address", get the thieve track ? ....
Would appreciate some support

------------------------------------------------------------------
PHISHING EMAIL 

slackbot View in the archives

slackbot 12:56 PM, July 17th 
@tomtom asked me to remind you “--- NOTICE! To all Ethereum holders --- 

Due to the increasing number of phishing attacks on MyEtherWallet, 
we decided to increase the security by implementing Two-Factor Authentication 
for all Ethereum wallets. 

Visit the link below to activate the Two-Factor Authentication on your Ethereum wallet: 

https://myetherwallet.com#activate-2fa-76638-843N7335-8773636 

Please be aware that you will not be able to access your Ethereum wallet anymore 
on MyEtherWallet without activating the new security protocol (Two-Factor Authentication). 

We are taking this measures to protect both you and our network from phishing and malicious attacks. 

Thank you for your cooperation and understanding. 

MyEtherWallet Team”.

``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by evertonfraga** [comment]
I've reported a couple of weeks ago: https://twitter.com/Paul__Walsh/status/892219603232800768

Thanks for the report!

**Comment by GC2012** [comment]
MyEtherWallet [1:01 PM] *=== MyEtherWallet UPGRADE Required ===*
Dear Gregory Chemin (@greg),
Due to the Hard Fork that will be happening at the end of this week, we decided to implement a number of security changes and improvements.All Ethereum wallets require to be manually upgraded, *otherwise they risk being unprotected and funds may be lost during the fork process*.
To upgrade your wallet to the latest security settings, please visit https://myetherwallet.com#view-wallet-info?upgrade
We are taking these measures to protect both you and our network from phishing and malicious attacks.
Thank you for your cooperation and understanding.
~MyEtherWallet
