### ISSUE TITLE
<script src="//www.anrdoezrs.net/am/8374948/include/joined/exclude/4332652/impressions/page/am.js"></script>

### ISSUE THREAD

**Issue by guidenbond** [ethereum/mist#2861]
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by guidenbond** [comment]
[<script src="//www.anrdoezrs.net/am/8374948/include/joined/exclude/4332652/impressions/page/am.js"></script>](url)

**Comment by guidenbond** [comment]
![2-1](https://user-images.githubusercontent.com/27285346/28764809-7d533ede-7595-11e7-97a9-d5613d56c14e.jpg)

**Comment by evertonfraga** [comment]
Cool story, bro.
