### ISSUE TITLE
No confirmations 11+ hours.

### ISSUE THREAD

**Issue by jaaneh** [ethereum/mist#2863]
I've been trying to publish a wallet contract, and it's stuck at loading.
The contracts were both sent 11+ hours ago, and have over 2000+ confirmations each.
http://i.imgur.com/K2PRlkl.png

![emyxf](https://user-images.githubusercontent.com/27323317/28802244-bfcb35da-7655-11e7-8fc4-52fb830cc813.png)

``````
Version: `0.9.0`
OS & Version: Windows 10
Node type: `geth`
Number of blocks synchronized: 4101200
``````

**Comment by tomtom87** [comment]
@jaaneh  I am also stuck syncing on the test net, it's super slow. Maybe this is because of the august 1 btc/bcc fork making the network so busy?

**Comment by BoBBer446** [comment]
If you dont have 100% network sync maybe this can help you:
https://github.com/ethereum/mist/issues/2874#issuecomment-319904958

You can only send and receive Coins if your wallet have 100% Synced to the Network!
