### ISSUE TITLE
Popup windows issue

### ISSUE THREAD

**Issue by mohamedGr** [ethereum/mist#2869]
``````
Version: `0.9.0`
OS & Version: Ubuntu 16.04
Node type: `eth/geth`
``````
Hi,

Popup windows seem not to be working in Mist. I am trying to use remix IDE from Mist and use the **At Address** button to test a specific contract that was already deployed in the blockchain but the button does not work. Is it because popup windows are blocked in Mist?

Thank you for your help!

**Comment by evertonfraga** [comment]
`window.prompt()` is blocked on Electron — framework Mist is built on. The
solution would come from Remix IDE, replacing `window.prompt()` call by an
input text in the HTML.




--
Everton Fraga
21 99927-9999
