### ISSUE TITLE
I don´t remember my Mist wallet password

### ISSUE THREAD

**Issue by wallethelp** [ethereum/mist#287]
Hello,

When I am trying to send ethers from my wallet it says wrong password. I am 95% sure that I have entered the right password but it says it isnt. I have another account there with the same password and it works well. Any ideas? Is there any possibility to reset/recover my password? I am using the latest version of mist wallet

Thank you for all the answers..

**Comment by frozeman** [comment]
There seems to be an issue with the node connection in windows, which sometimes prevents to unlock the account. please try to restart multiple times.

**Comment by wallethelp** [comment]
Thank you for your answer.

I have restarted multiple times and I can send Ethers from my other accounts which are in the same wallet. So it really seems to be that my password is incorrect. And I have no idea what is it then if it´s not the one I use "always". So is there any possibilities to recover/reset my password?

**Comment by frozeman** [comment]
No. As this is by design. Your keys are encrypted with this password and if you loose it you locked yourself out.. sorry.
