### ISSUE TITLE
How to send 0.0 ETH 

### ISSUE THREAD

**Issue by gtrider** [ethereum/mist#2871]
``````
Version: `9.0`
OS & Version: windows
Node type: `eth/geth`
Number of blocks synchronized: full sync 
``````

Hi,

I'm trying to send 0.0 eth + gas to kick off the contract to cash out my Prism (https://prism.exchange/), but it says i cant send a transaction of .0 eth.  Any idea how i can send zero eth? 

Thank you for your time and energy!

**Comment by evertonfraga** [comment]
Hi @gtrider, AFAIK that's not possible. You can send 1 wei to it, though.

**Comment by 4ntoine** [comment]
This may be not related, but how was 0 ETH sent in all that transactions? https://etherscan.io/address/0x0e9C4d8610Aa2cf0DaBDAbB19920A1C810B65720

**Comment by evertonfraga** [comment]
Hi Anton,

Those were contract executions, more specifically Token transfers. You can
verify that by clicking on one of the transactions:
https://etherscan.io/tx/0x43ea9965d5e62502f8727887a0cdcfcd6a09ba026f5abf99786bc309e68c9123

**Comment by evertonfraga** [comment]
Closing issue. Please reopen should you want to continue the discussion.

**Comment by khohariawan** [comment]
Pak bos kalau saldo di Etherscan mau ditransfer ke ethereum wallet gimana caranya mohon dijelasin
