### ISSUE TITLE
Chain data syncing is eating SSD's TBW enormously 

### ISSUE THREAD

**Issue by dennisyv** [ethereum/mist#2872]
``````
Version: `0.9.0`
OS & Version: windows 10 pro
Node type: `eth/geth` Mist-win64-0-9-0 
Number of blocks synchronized: ~3 700 000
``````

Context: I bought new SSD - Samsung 960 EVO 500gb; model is not really important but important the fact that it has 200 TBW guaranteed by manufacturer (which is approximately a max limit of written by SSD bytes). This could be considered an "SSD's lifetime".

Story: When I started syncing ETH via Mist first time I noticed that terabytes written is enormously increased and is about 50x-100x of chaindata folder size. Currently I got +1.5 TBW which means 1500 GIGA BYTES was written That is crazy huge. Which is about 0.5-1% of my SSD's life for just to download with fast sync. While chaindata itself is just ~15-20Gb. 
I'm not sure how will this continue with normal sync but I bet results are going to be even worse. 

After that I decided to move chaindata via symlink to another drive and I understood that there is another thing which is continuously killing my SDD and already eaten 1TBW from my SSD's lifetime. And this thing is Swarm. And all that crazy writes amounts are only to store about 13Gb of data which is the current size of 
C:\Users\ %USER% \AppData\Roaming\Mist\swarmjs\swarm\bzz-%ID%\chunks\ 

That is crazy. Crazy ineffective use of hardware. Not sure if it is theoretically possible but if so - it must be addressed. 
Do some caching, bigger batches during writes or whatever. You know better - I'm not an expert in how mist/geth works.

Moreover Mist got no GUI way to move chaindata/swarmdata somewhere to another drive/location.
AFAIK it is only possible via CLI.

Btw, Bitcoin Qt does same crazy drive eating. To be fair it is even worse - at least because its blockchain is already ~150Gb which, in practice, for me, means about +10 TBW.
So in few days in total these three geth/swarm/bitcoin-qt ate ~7% of my SSD's lifetime. 
In total they wrote about 13 000 GIGAbytes. While total size on disk is less than 200 gigabytes.
it is ~65 times more than total size. 
CRAZY-CRAZY-CRAZY

Hope that is going to be addressed soon.
Appreciate your help.

Sorry for my English.

**Comment by dennisyv** [comment]
btw: 
![image](https://user-images.githubusercontent.com/1744945/28860590-dbd939be-7765-11e7-873c-0aa8a7bdc071.png)

**Comment by xixou2** [comment]
I agree, the ethereum myst wallet is the worst out of 30 local wallets I have, it does a huge amount of ridiculous ssd writes, this needs to be addressed .. 
Also note that you better disable virtual memory and the anti virus to avoid a lot of extra reading/writting on top of it.

**Comment by xixou2** [comment]
Note that deleting an old fat +100 GB chaindata from an old myst wallet
and re-populated, it gets only 32GB in size now and populate/sync faster than before.
I think new myst wallet update should figure that out and delete the old chaindata when that is the case (are the data now compressed or fast synced with myst 0.9?).

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
