### ISSUE TITLE
QR-code generator swaps cases of some symbols 

### ISSUE THREAD

**Issue by ETYMOLOGIA** [ethereum/mist#2875]
``````
Version: `0.8.10`
OS & Version: windows
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

I've noticed that Ethereum Wallet v. 0.8.10 shows wrong QR-code. It swaps cases of some symbols. E becomes e after QR-code is processed back. How is that normal?

**Comment by evertonfraga** [comment]
Yes, it is normal. 

Addresses are case insensitive, and the only reason it is shown as mixed-case in your wallet is to adhere to a [checksum standard](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md), that would prevent an address to be mistyped in the wallet and compatible software. 

But hey, with [ENS](https://ens.domains) you could have an `etymologia.eth` name pointing to your ethereum address. It saves you from the hassle of distributing QR codes or long and confusing addresses. 

Closing as it's not an actual issue. Feel free to reopen should the discussion continue! :)
