### ISSUE TITLE
Minor UI bug, send value needs to be zeroed out when non-payable functions are selected

### ISSUE THREAD

**Issue by bravetarget** [ethereum/mist#2877]
Steps to reproduce from contract view: 
1.) select a payable function
2.) fill in an amount to send with execution
3.) change to non-payable function (this hides the send field)
4.) attempting to execute will assume failure due to previous, now hidden, amount entered.

**Comment by evertonfraga** [comment]
Cool suggestion. thanks!

For anyone wanting to contribute, here's the proper repository: https://github.com/ethereum/meteor-dapp-wallet
