### ISSUE TITLE
Can't start parity

### ISSUE THREAD

**Issue by TheAppleBoy** [ethereum/mist#2880]
i have installed parity on my windows 10  and when i change the property of the parity.exe target box, it gives me an error
 **_"The name "C:\Program Files\Ethcore \Parity\parity.exe"--geth' specified in the Target box is not valid. Make sure the path and file name are correct_**
Did i do something wrong?
Or i have to install something first

**Comment by evertonfraga** [comment]
Unfortunately, I can't help you much. Would you try to get some answers on Parity's repository or gitter room?

http://github.com/paritytech/parity
https://gitter.im/paritytech/parity?source=orgpage

Closing this for now. Should you have any Mist specific issue, please file a new one.
