### ISSUE TITLE
Double Spend Affecting the Wallet?

### ISSUE THREAD

**Issue by PsiBorger** [ethereum/mist#2883]
```
Version: `0.9.0`
OS & Version: windows 10
Node type: `geth`
Number of blocks synchronized: 4,114,772
```

Prior to uploading, wanted to point this out, and see if I need to provide more information.

On an Android App/wallet, I transferred ETH to my Poloniex account. It seemed to hang after the first attempt, so I hit it a second time (thinking the transaction cost more than I allowed for) at a slightly lower amount. Both transactions (one for .604, and another for .6 from a wallet with only .604 in it) can be seen here:
[https://etherchain.org/account/0x87d460880a211b9613e7ab6655dc03ea520752d0](https://etherchain.org/account/0x87d460880a211b9613e7ab6655dc03ea520752d0
)

My wallets still show .6 ether in it, no ether is in the Poloniex account and both transactions have been "verified" >8000 times. At what point will the later transaction get invalidated and the ether sent to the target account?  

Thanks!

**Comment by evertonfraga** [comment]
Double spending is a highly unlikely thing.

Taking a look on Etherscan, we can see that both transactions had a Out of Gas (OOG) error. So, that's not an issue :)

**Comment by PsiBorger** [comment]
I see...so re submit with a higher gas limit?


Sent from my Sprint Samsung Galaxy S7 edge.
-------- Original message --------From: Ev <notifications@github.com> Date: 8/4/17  7:58 AM  (GMT-08:00) To: ethereum/mist <mist@noreply.github.com> Cc: PsiBorger <psiborger80@gmail.com>, Author <author@noreply.github.com> Subject: Re: [ethereum/mist] Double Spend Affecting the Wallet? (#2883) 
Double spending is a highly unlikely thing.
Taking a look on Etherscan, we can see that both transactions had a Out of Gas (OOG) error. So, that's not an issue :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ethereum/mist","title":"ethereum/mist","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ethereum/mist"}},"updates":{"snippets":[{"icon":"PERSON","message":"@evertonfraga in #2883: Double spending is a highly unlikely thing.\r\n\r\nTaking a look on Etherscan, we can see that both transactions had a Out of Gas (OOG) error. So, that's not an issue :)"}],"action":{"name":"View Issue","url":"https://github.com/ethereum/mist/issues/2883#issuecomment-320270867"}}}
