### ISSUE TITLE
Mist and Ethereum-Wallet checksums for v0.9.0 are MD5 but should be SHA256

### ISSUE THREAD

**Issue by noman-land** [ethereum/mist#2887]
```
Version: 0.9.0
OS & Version: macOS 10.12
Node type: geth
Number of blocks synchronized: N/A
```

I read in [an earlier issue](https://github.com/ethereum/mist/issues/2272) that the checksums should be SHA256 but they are published as MD5s on the v0.9.0 tag. 

https://github.com/ethereum/mist/releases/tag/v0.9.0

![image](https://user-images.githubusercontent.com/27938023/28992613-5534c278-796f-11e7-8eb8-e63ce170e573.png)

**Comment by evertonfraga** [comment]
Updated release with SHA-256 checksums. Also on our build server, so it is solved for all future versions.

https://github.com/ethereum/mist/releases/tag/v0.9.0
