### ISSUE TITLE
Ethereum-Wallet-macosx-0-9-0.dmg checksum correct??

### ISSUE THREAD

**Issue by neodem** [ethereum/mist#2889]
Hello. I downloaded Ethereum-Wallet-macosx-0-9-0.dmg and my checksum didn't match what you had listed. Is it correct?

**Comment by neodem** [comment]
Here is what I get:
```
mandy:Downloads admin$ shasum Ethereum-Wallet-macosx-0-9-0.dmg 
b66cd34bac068f94b7302d3457b9b3e98406c1cc  Ethereum-Wallet-macosx-0-9-0.dmg
```

You list `f19165e94dc1facba3289f43abcda58b`

**Comment by bentrm** [comment]
Only md5 checksums are listet, see #2887.

**Comment by evertonfraga** [comment]
I've listed SHA-256 checksums on the release page: https://github.com/ethereum/mist/releases/tag/v0.9.0

Also, we're making sure our build server will generate the correct checksums in the future: https://github.com/ethereum/mist/pull/2917.
