### ISSUE TITLE
can't delete account from GUI

### ISSUE THREAD

**Issue by winsvega** [ethereum/mist#289]
is there a GUI option to remove account from MIST?

**Comment by MSeven** [comment]
open the contract view. Mouse over the contract name in the top, there is a delete icon there.

**Comment by alexvandesande** [comment]
We didn't add this option for accounts, but if you want to do it you can go to backup > accounts and then delete the files you want from there. **BE CAREFUL** if you delete the wrong account you won't be able to recover your ether
