### ISSUE TITLE
mist 0.9 "couldn't start swarm process" error

### ISSUE THREAD

**Issue by porfavorite** [ethereum/mist#2890]
``````
Version: `0.9.0`
OS & Version: linux
Node type: `testrpc`
``````

Trying to start Mist 0.9:
`mist --rpc http://localhost:8545`

Getting the error:

> [2017-08-05 19:47:06.246] [INFO] main - Running in production mode: true
> [2017-08-05 19:47:06.251] [WARN] main - CONNECTING TO A NODE VIA HTTP INSTEAD OF IPCMAIN. THIS IS LESS SECURE!!!!
> [2017-08-05 19:47:06.411] [INFO] main - Starting in Mist mode
> [2017-08-05 19:47:08.737] [INFO] Db - Loading db: /home/os/.config/Mist/mist.lokidb
> [2017-08-05 19:47:08.792] [INFO] Windows - Creating commonly-used windows
> [2017-08-05 19:47:08.793] [INFO] Windows - Create secondary window: loading, owner: notset
> [2017-08-05 19:47:08.874] [INFO] updateChecker - Check for update...
> [2017-08-05 19:47:15.345] [INFO] Windows - Create primary window: main, owner: notset
> [2017-08-05 19:47:15.471] [INFO] Windows - Create primary window: splash, owner: notset
> [2017-08-05 19:47:16.567] [INFO] ipcCommunicator - Backend language set to:  en
> [2017-08-05 19:47:18.597] [INFO] (ui: splashscreen) - Web3 already initialized, re-using provider.
> [2017-08-05 19:47:18.732] [INFO] (ui: splashscreen) - Meteor starting up...
> [2017-08-05 19:47:18.888] [INFO] ClientBinaryManager - Initializing...
> [2017-08-05 19:47:18.892] [INFO] ClientBinaryManager - Resolving path to Eth client binary ...
> [2017-08-05 19:47:18.894] [INFO] ClientBinaryManager - Eth client binary path: /opt/Mist/nodes/eth/linux-x64/eth
> [2017-08-05 19:47:18.896] [INFO] ClientBinaryManager - Checking for new client binaries config from: https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json
> [2017-08-05 19:47:19.359] [INFO] updateChecker - App is up-to-date.
> [2017-08-05 19:47:19.579] [INFO] ClientBinaryManager - No "skippedNodeVersion.json" found.
> [2017-08-05 19:47:19.585] [INFO] ClientBinaryManager - Initializing...
> [2017-08-05 19:47:19.585] [INFO] ClientBinaryManager - Resolving platform...
> [2017-08-05 19:47:19.586] [INFO] ClientBinaryManager - Calculating possible clients...
> [2017-08-05 19:47:19.588] [INFO] ClientBinaryManager - 1 possible clients.
> [2017-08-05 19:47:19.588] [INFO] ClientBinaryManager - Verifying status of all 1 possible clients...
> [2017-08-05 19:47:19.590] [INFO] ClientBinaryManager - Verify Geth status ...
> [2017-08-05 19:47:19.615] [INFO] ClientBinaryManager - Checking for Geth sanity check ...
> [2017-08-05 19:47:19.615] [INFO] ClientBinaryManager - Checking sanity for Geth ...
> [2017-08-05 19:47:19.740] [INFO] Sockets/node-ipc - Connect to {"hostPort":"http://localhost:8545"}
> [2017-08-05 19:47:19.783] [INFO] Sockets/node-ipc - Connected!
> [2017-08-05 19:47:19.791] [INFO] NodeSync - Ethereum node connected, re-start sync
> [2017-08-05 19:47:19.793] [INFO] NodeSync - Starting sync loop
> [2017-08-05 19:47:19.794] [INFO] Sockets/3 - Connect to {"hostPort":"http://localhost:8545"}
> [2017-08-05 19:47:20.258] [INFO] Sockets/3 - Connected!
> [2017-08-05 19:47:20.305] [INFO] (ui: splashscreen) - Network is privatenet
> [2017-08-05 19:47:20.314] [INFO] (ui: splashscreen) - Network is privatenet
> [2017-08-05 19:47:40.514] [ERROR] main - Error starting up node and/or syncing Error: Couldn't start swarm process.
>     at Timeout.error [as _onTimeout] (/opt/Mist/resources/app.asar/node_modules/swarm-js/lib/swarm.js:420:21)
>     at tryOnTimeout (timers.js:232:11)
>     at Timer.listOnTimeout (timers.js:202:5)
> [2017-08-05 19:49:19.909] [INFO] NodeSync - Sync has been skipped
> [2017-08-05 19:49:19.911] [INFO] NodeSync - Sync loop ended
> 

And then it is just stuck

**Comment by ValeryDubrava** [comment]
Workaround is set null as swarmurl: --swarmurl "null". Or your should specify URL explicitly, otherwise it use the default: "http://localhost:8500".
