### ISSUE TITLE
Very slow sync

### ISSUE THREAD

**Issue by rubensrocha** [ethereum/mist#2895]
``````
Version: Mist 0.9.0
OS & Version: Windows x64
Node type: eth/geth
Number of blocks synchronized: 2.915,000(Slowly increasing)
``````
24h with the computer on, and so far only synchronized 2,915,000 blocks out of a total of 4,124,177. And I always have to keep an eye out, because sometimes he just stops the blocks and I need to close and open the Mist again so that it can continue.

My internet is 15MB, and I downloaded a 22GB torrent in less than 24h. The first time I synchronized and created my wallet was very fast, but it's been almost 2 days that I'm waiting to synchronize so I can access my wallet and so far I have not been able to finish this process.

Does anyone know why it's taking so long to sync the blocks? Is it related to the Bitcoin fork?
![mist](https://user-images.githubusercontent.com/10297656/29003901-a9b5f322-7a95-11e7-853b-db57e9fe05a3.jpg)

**Comment by edstewbob** [comment]
I have this same problem too on Windows 10 and when I restart Mist I notice that the memory size of swarm.exe has grown to a very large value, 3-4 GB in size. After restarting the sync is still very slow a max of 1 block per second and usually .5 blocks per second. My CPU is only 20-30 % busy and my Internet speed is 60 Mbps.

**Comment by rubensrocha** [comment]
@edstewbob Same with me. Almost 2GB ram on swarm.exe. I'll delete the files a second time and try to start from scratch again to see if that works out.

**Comment by rubensrocha** [comment]
![mist](https://user-images.githubusercontent.com/10297656/29095447-32ae0c64-7c67-11e7-8574-56718b5dc789.png)

Waiting for a miracle.
Pc on since: yesterday(24h or more)

Don't finish, and don't let me use my pc for other things because excessive use of memory. :-(

**Comment by OlegSev** [comment]
@rubensrocha I have the same problem on my laptop HP Probook Windows 10x64 with last updates - never ending sync for more than 2 days with downloaded 32 gb. files and excessive use of disk(100%).
A warning from windows defender appears during it.
Looks like this software downloads Trojans from everywhere, i removed it permanently. )

**Comment by rubensrocha** [comment]
![mist2](https://user-images.githubusercontent.com/10297656/29122659-7b4eeb0a-7ce9-11e7-989e-f2c42ba0a7d6.png)

More than 12h stuck in this value. I'll give up this. On the next month i try again, with luck, i can get my money and transfer then to a exchange and won't use this sh@t again. Without support from devs, i can't do nothing.

**Comment by OlegSev** [comment]
For now I have been trying to sync on Mac OS under VMware virtual machine, second day with the same result - not ending sync.
IMO: using this blockchain platform you are in a big risk, you may lost everything accidentally, all your investments and money, with such software and support!

**Comment by OlegSev** [comment]
![tmp-cam--171787068](https://user-images.githubusercontent.com/30791868/29160158-64ef8f98-7ddb-11e7-908c-d4005cf36535.jpg)

**Comment by PatchRanger** [comment]
Probably relevent to #2372 .

**Comment by OlegSev** [comment]
Now the full blockchain's size is over 100 gb and fast growing, the other side of slow sync.
It already can't be used by most of users.

**Comment by rodgermoore** [comment]
Thanks to @pparent76 in #2372 ! 

Syncing under "light" mode was millions times faster :)

This works for Mist under Ubuntu / Linux (should work in OSX too).

> I had it working with this staring script:

```` 
#!/bin/bash

ps -ae | grep geth
if [ "$?" -ne "0" ]; then
	geth  --syncmode "light"  &
	sleep 10;
fi
mist --light-node

**Comment by emiliano1** [comment]
Run this command on your terminal and you should be fine after a few mins.

` geth --syncmode "light" --cache 4096 console`

**Comment by lnaie** [comment]
Super slow sync. Occasionally it crashes!

**Comment by evertonfraga** [comment]
No need to hack anymore!

We have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Comment by emiliano1** [comment]
@lnaie it is installed in root, but you can simply install it with homebrew.
https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Mac

**Comment by emiliano1** [comment]
$Geth is a mess and consumer over 125% of the CPU to sync this wallet. Something needs to be fixed!

**Comment by hawaii18k** [comment]
I have old laptop hard drive for use with ethereum mist.  After suffering over 5 days trying to sync, I finally found a way to complete the sync.  Trick was to defrag the hard drive with ether data.  I am guessing geth frag the shit outta hard drive and i/o speed crawls down.  After frag is over, it finished syncing in few hours.  good luck.

**Comment by fulldecent** [comment]
Adding data: using MacBook Air with 4GB / 256GB. Over 7 days and still at 30000000 / 40000000 blocks.

**Comment by emiliano1** [comment]
All of this is assuming you have geth in place etc and usually -v 1.7.2 or above. 

**ok it is final guys! This is the solution:**
1. $ cd ~/Libary/Ethereum/geth/
2. $ mv chaindata chaindata_backup
3. $ mkdir chaindata
4. $ geth --fast --cache=1024
5. open ethereum wallet but **DO NOT** click on Launch Application.
6. Wait and if it all works fine (after 100% sync) then, remove the chaindata_backup file by doing $ ~/Libary/Ethereum/geth/chaindata_backup

**Comment by divgo** [comment]
@emiliano1 - thanks for the walkthrough. your steps have worked and I was able to get up to sync in about 10 hours on my Mac. However, the sync never actually finishes. It continues to hover around about 99% complete and never gets over the finish line. Currently (1/1/2018) - the sync has been running for about 48 hours and my block count is: 4,834,097 of 4,834,265.

Also, Every few minutes, I get a message about downloading the chain structure, where the processing chain count rises quickly, but the target block count is also rising. The chain structure count is currently at 3,755,781 

My question is: is this expected?

**Comment by emiliano1** [comment]
Yes it is @divgo I waited a very long time and it all worked out - just patience! HoDL your ETH/BTC btw

**Comment by DCardosa** [comment]
I've been running for 24 hrs and I am at 4,559,000 or so.....it keeps timeing out no and then and giving a no sync error and then starts running again after a few minutes.  Will the above code fix that?

**Comment by emiliano1** [comment]
@DCardosa open ethereum wallet but DO NOT click on Launch Application and let it run there forever! Once done it will open the wallet for you automatically.

**Comment by DCardosa** [comment]
Thanks....now all I need to do is try to compile it for multichain.


-----Original Message-----

**Comment by emiliano1** [comment]
Then you might need to run the $geth on terminal

**Comment by DCardosa** [comment]
Been over 48 hrs and still hasn't finished.  It gets close...within 10,000 or so then it falls behind again.

**Comment by DCardosa** [comment]
I've been stuck on block number 4,860,023 of 4,868,606 for 2 days now.  Downloaded over 38,000,000 blocks of chain data but still not synchronized?  It's running and downloading chains of data but every once in a while gets stuck gives error messages about dropping the peer, searches for peers then restarts downloading again but never seems to become fully synchronized...is this normal?

**Comment by DCardosa** [comment]
I closed everything and then reopened the wallet...it jumped to 4,860,573.  It is still synching though it is closer.  When I open terminal there's nothing there...go ethereum command does nothing, updated brew and tried to rerun get -fast  says it is being used so I assume it is still running with the wallet synch even though I can't see it.

**Comment by DCardosa** [comment]
Well, it's been over a week now and still not finished.  It's close but never seems to rech the end although each day it seems to get closer and closer.  I started taking some online classes from block geeks, since I have no real experience other than I took BASIC and PASCAL 30 years ago. I wonder if I didn't load some code like son, roc, sole,  plus a few other things I can't remember.

**Comment by DCardosa** [comment]
That's what I'm seeing.  It gets close but never finishes and never catches up.  Block data and Chain data downloads but the  chain keeps increasing just as quickly and the blocks keep going to higher numbers..

**Comment by DCardosa** [comment]
3 weeks and still not synched.  It gets real close, within a couple of hundred block chains and a couple of thousand chains but can never get to the finish line.

**Comment by divgo** [comment]
I gave up on sitting and waiting for it to complete. I decided to toggle around with different geth settings to see if I could get something to click. 
After a while, I was able to get it to finish and have the app automatically open. I dont remember where I found the instructions, but what worked was opening a terminal (or command line) and cd-ing into the directory where geth is installed and running the following;

`
geth removedb
geth --cache=1024 --maxpeers 100 --syncmode "light"
`
after a few moments, the console will print something along the lines of;
`IPC endpoint opened: /Users/[user_name]/Library/Ethereum/geth.ipc`

At which point I open the Ethereum App and leave it alone. I do not click Launch Application. 
Eventually, the blockchain will begin downloading and the Ethereum App will show you the progress bar. Depending on how far behind gives you an idea of how long your going to wait. 

I posting this here for you @DCardosa because I too, like you, am tired of waiting for a Full Sync to never finish. This process, while not downloading the full complete chain, at least downloads enough information to get your wallet to open and view any ETH you might have. In my case I just wanted to see the whole process actually complete.

**Comment by DCardosa** [comment]
Thanks, I'll give that a try.

**Comment by DCardosa** [comment]
Ok...I got an error message but I don't know what it means...Incorrect usage:  flag provided but not defined: -cache

**Comment by divgo** [comment]
this is two separate commands;
`geth removedb`
`geth --cache=1024 --maxpeers 100 --syncmode "light"`

**Comment by DCardosa** [comment]
Thanks Sage.  I tried that and it's running...I still keep getting warning messages that sync is stalling and dropping peers.  Then, it starts up and runs again.  How long does sync usually take to finish?  I must have done something wrong.  This is my first time trying to code since PASCAL in the 80's.

**Comment by DCardosa** [comment]
Well, 1 month now and still can't finish.  Now I can't open the directory that is running geth either.  every time I try I get message that the matador is being used by another process.

**Comment by TheOriginalTrubador** [comment]
@DCardosa which OS are you using? If you're using Linux or MacOS, open a terminal and running something like 'kill $(ps | grep geth | awk '{print $1}')' which will kill any process with Geth in the title. On windows, Task Manager is probably the easiest route, although both PowerShell & CMD prompt offer similar solutions.

**Comment by DCardosa** [comment]
I am using high sierra OS.  What will that command do?..it is running and synching, just never catches up.  I am upgrading from a 75/35 bps network to a 500/500 bps network today to see is more download speed will help.

**Comment by TheOriginalTrubador** [comment]
@DCardosa The commands runs `ps` to get all running processes, uses `grep` to exclude anything that does not include `geth` in the arguments, and then only gets the Process IDs for those commands (one will be the actual ps command, but it doesn't matter)- it then passes that as a list to the `kill` command which will then kill each of those PIDs- ensuring every instance of `geth` on your machine is stopped. You can then run `ps aux | grep geth` to ensure that there are no current instances of `geth` running afterwards
