### ISSUE TITLE
pls help!! my etehreum mist wallet dosn't sync never the blocks are downloading and keeped from the last point when I close the wallet but the chain structure allways start from 0 and never end pls help!! : (

### ISSUE THREAD

**Issue by luck777sam** [ethereum/mist#2897]
``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by IvanM1993** [comment]
I have had this problem. try to remove all synchronization blocks. and reinstall the wallet. after these actions, I downloaded 4 000 000 units. on day 3 I got my ether. 
don't forget to make reserve keys

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
