### ISSUE TITLE
--node-light not working

### ISSUE THREAD

**Issue by winsvega** [ethereum/mist#2899]
when trying to pass --node-light argument to geth client 
mist comes into conflict cause it already start geth with --fastsync by default.

**Comment by dospunk** [comment]
Have you tried starting the geth client before starting Mist?

**Comment by winsvega** [comment]
thats right. if I start geth manually it will work. 
the issue is that mist feature of starting a node with custom arguments does not work with this particular option.

**Comment by evertonfraga** [comment]
Thanks, @winsvega. It'll be updated in favor of `--syncmode light`

**Comment by evertonfraga** [comment]
We've enabled the light client on Mist 0.9.1. 
Thanks for reporting @winsvega.
