### ISSUE TITLE
Ethereum Wallet 0.9.0 doesn't sync to the best block

### ISSUE THREAD

**Issue by gplgps** [ethereum/mist#2902]
``````
Version: `0.9.0` - Ethereum Wallet
OS & Version: windows 10 Home
Node type: `geth`
Number of blocks synchronized: 94 left at the moment
``````

Aparently, I can get connected to 4 or 5 peers (usually. Right now I'm connected to 9 peers) and it doesn't download to the best block. It seems that it only downloads in bulk (around 100 blocks per bulk), which I'll never get a complete sync (get the latest block).

It happens even if I leave the Ethereum Wallet open for more than 1 hour.

Can someone explain how to fix this issue?

Thanks in advance 🙂

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
