### ISSUE TITLE
Explicit "storage" keyword

### ISSUE THREAD

**Issue by quixotis** [ethereum/mist#2903]
``````
Version: `0.9.0`
OS & Version: linux/osx
Node type: geth
Number of blocks synchronized: 0
``````

Warning: Variable is declared as a storage pointer. Use an explicit "storage" keyword to silence this warning.

This is the warning I get when trying to compile the standard decentralized autonomous organization code from the ethereum website. I just want to test out a blockchain congress on a private test network but it will not compile and keeps throwing that error.

![compile error screen](https://user-images.githubusercontent.com/5288137/29050289-9f498ac8-7ba0-11e7-98e7-e2381b1f5d08.png)

**Comment by evertonfraga** [comment]
This warning is gone from Solidity compiler 0.4.14 up. Please update your software.

Thanks

**Comment by magonicolas** [comment]
Compiler 0.4.14 doesn't seem to work on my Mist, and It says I have the last version.
