### ISSUE TITLE
EMAIL SCAM ALERT - MIST SUPPORT

### ISSUE THREAD

**Issue by shubrich76** [ethereum/mist#2908]
I'd like to let everyone know that if you post a problem on here, someone from "Mist Support" may contact you via email and ask for your "wallet log ID"

I'm assuming in their broken English they mean login ID. I don't know why they would need that information but it strikes me as odd and phishy.

I have not replied with my ID, and I suggest that if you get an email like that you do not reply either. They were convincing up until they asked me for that!

It was from mistsupport@protonmail.com and I reported the phishing scam to them.

**Comment by alexvandesande** [comment]
Thanks for that report. We unfortunately don't have a Mist support team, and we don't contact users out of the blue unless for some very specific reasons (usually when they report a bug). Also, all our emails are with the domain Ethereum.org

So yeah, it's a scam. Isn't proton mail that one which was famous for its anonymity? I don't know what was their end goal, or what they meant by "Mist Log ID"

**Comment by shubrich76** [comment]
I didn't know what they meant either but I didn't send them any
information! Also, they were using the name "Alex".
--
Sara Hubrich
Operations Manager
Conceptopolis, Inc
@conceptopolis
http://facebook.com/conceptopolis
https://www.conceptopolis.com
sara@conceptopolis.com



On Wed, Aug 9, 2017, at 08:19 AM, Alex Van de Sande wrote:
> Thanks for that report. We unfortunately don't have a Mist support
> team, and we don't contact users out of the blue unless for some very
> specific reasons (usually when they report a bug). Also, all our
> emails are with the domain Ethereum.org> So yeah, it's a scam. Isn't proton mail that one which was famous for
> its anonymity? I don't know what was their end goal, or what they
> meant by "Mist Log ID"> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/ethereum/mist/issues/2908#issuecomment-321238769

**Comment by 409H** [comment]
I have opened communications with protonmail to try and get this account suspended. 

@shayanb do you have an e-mail from them you can share here (along with the email headers)?

**Comment by shubrich76** [comment]
Yes I do. I have also already forwarded this to protonmail and alerted
them to phishing
Hello,

Thank you. Here are the headers, I think:

Return-Path: <MistSupport@protonmail.com> Received: from compute3.internal (compute3.nyi.internal [10.202.2.43])   by sloti38d1t06 (Cyrus fastmail-fmjessie44689-15355-git-fastmail-15355) with LMTPA;   Mon, 07 Aug 2017 15:36:07 -0400 X-Cyrus-Session-Id: sloti38d1t06-1102670-1502134567-2-4153265803893865640 X-Sieve: CMU Sieve 3.0 X-Spam-known-sender: yes ("Address MistSupport@protonmail.com in From header is in addressbook"); in-addressbook X-Spam-score: 0.0 X-Spam-hits: BAYES_00 -1.9, FREEMAIL_FROM 0.001, HTML_MESSAGE 0.001, RCVD_IN_DNSWL_LOW -0.7, RCVD_IN_MSPIKE_H4 -0.01, RCVD_IN_MSPIKE_WL -0.01, SPF_HELO_PASS -0.001, SPF_PASS -0.001, LANGUAGES en, BAYES_USED user, SA_VERSION 3.4.0 X-Spam-source: IP='185.70.40.27', Host='mail4.protonmail.ch', Country='CH', FromHeader='com', MailFrom='com' X-Spam-charsets: plain='UTF-8', html='UTF-8' X-Resolved-to: sara@conceptopolis.com X-Delivered-to: sara@conceptopolis.com X-Mail-from: MistSupport@protonmail.com Received: from mx5 ([10.202.2.204]) by compute3.internal (LMTPProxy); Mon, 07 Aug 2017 15:36:07 -0400 Received: from mx5.messagingengine.com (localhost [127.0.0.1])  by mailmx.nyi.internal (Postfix) with ESMTP id 2D9B7C66C9  for <sara@conceptopolis.com>; Mon,  7 Aug 2017 15:36:07 -0400 (EDT) Received: from mx5.messagingengine.com (localhost [127.0.0.1]) by mx5.messagingengine.com (Authentication Milter) with ESMTP id 63D17361D83; Mon, 7 Aug 2017 15:36:07 -0400 Authentication-Results: mx5.messagingengine.com; dkim=pass (1024-bit rsa key sha256) header.d=protonmail.com header.i=@protonmail.com header.b=fb2L++Qq; dmarc=pass header.from=protonmail.com; spf=pass smtp.mailfrom=MistSupport@protonmail.com smtp.helo=mail4.protonmail.ch Received-SPF: pass (protonmail.com: Sender is authorized to use 'MistSupport@protonmail.com' in 'mfrom' identity (mechanism 'include:_spf.protonmail.ch' matched)) receiver=mx5.messagingengine.com; identity=mailfrom; envelope-from="MistSupport@protonmail.com"; helo=mail4.protonmail.ch; client-ip=185.70.40.27 Received: from mail4.protonmail.ch (mail4.protonmail.ch [185.70.40.27])  (using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))  (No client certificate requested)  by mx5.messagingengine.com (Postfix) with ESMTPS  for <sara@conceptopolis.com>; Mon,  7 Aug 2017 15:36:06 -0400 (EDT) Date: Mon, 07 Aug 2017 15:35:47 -0400 DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=protonmail.com;  s=default; t=1502134559;  bh=nvQnembUvgo5CQ2g3JlAVofg7e33Nc6IEXPF9xsAXvk=;  h=To:From:Reply-To:Subject:In-Reply-To:References:Feedback-ID:From;  b=fb2L++QqYfOkBbRecu334akqQco///UtnNy+HuO8mwOFLZ1/uSg/P6I06Lg9ndfSm   n9fPaKJlxlcIDiLctA0Upck+aNkhdR2/DJPJmAVlCwJdrCJGWetNjrLU0keWSTETC6   mjXN32RWDL/N+mvkh4wBrpDYdHeMkAtm+JkGPnLo= To: Sara Hubrich <sara@conceptopolis.com> From: Mist Wallet Support <MistSupport@protonmail.com> Reply-To: Mist Wallet Support <MistSupport@protonmail.com> Subject: Re: Ethereum Wallet Issue #2868 Message-ID: <5AOyxhlwnwQi_1stG7Mw07fIb2YQNfF4id1LIaZSRE3zgJVGNuZOSLcEP4Qr9FuC8mP4fudv01F-opWUadUSWAg5yvEqq3g-5sJ-q4tWMEY=@protonmail.com> In-Reply-To: <1502131612.735324.1065941648.5250D6A9@webmail.messagingengine.com> References: <GSZt9KMWmSxUCxl6YSMQCBmr-XS_gGgojHMj1aV1hps2ZfuFttWoFaFgcB3pvlhhVVvao0FDgq8sb_EQ-Ja80DYvrR7AODaBHMe-RFiWQec=@protonmail.com> <1502113951.670720.1065611416.6DFB6EF6@webmail.messagingengine.com> <qjaeo4Q4RM-66JAv2o3ExUJbXQ4L9zIIZemjrXz6sjJNJ7Vykqnw8IU7WSJ6-HNTjhpCN6xDflNzV8Sr1mnVwL0kknnu5rOOZYlDf4ad9Aw=@protonmail.com> <1502131612.735324.1065941648.5250D6A9@webmail.messagingengine.com> Feedback-ID: v60Yst-TObZ0_LFlKiDUFjUC3XWi9uOR75FbntYZh5kCbHPgk-CWerP7bO8PWWvapf19-BIpcEgknTlnFBhUkQ==:Ext:ProtonMail MIME-Version: 1.0 Content-Type: multipart/alternative;  boundary="b1_4d5394916ae0686c69b627a4bf2490ec" X-Remote-Spam-Status: No, score=0.3 required=5.0 tests=ALL_TRUSTED,DKIM_SIGNED,  DKIM_VALID,DKIM_VALID_AU,FREEMAIL_FROM,HTML_MESSAGE,MISSING_DATE autolearn=no  autolearn_force=no version=3.4.1 X-Remote-Spam-Checker-Version: SpamAssassin 3.4.1 (2015-04-28) on mail.protonmail.ch  This is a multi-part message in MIME format.  --b1_4d5394916ae0686c69b627a4bf2490ec Content-Type: text/plain; charset=UTF-8 Content-Transfer-Encoding: base64  SGkgU2FyYSwKV291bGQgeW91IG1pbmQgc2VuZGluZyB5b3VyIGxvZyBJRCBzbyB3ZSBjYW4gaWRl bnRpZnkgYW55IGlzc3VlcyB0aGF0IGNvdWxkIGJlIGNhdXNpbmcgeW91ciB3YWxsZXQgbm90IHRv IHN5bmNocm9uaXplLgoKUmVnYXJkcywKQWxleAoKPiAtLS0tLS0tLSBPcmlnaW5hbCBNZXNzYWdl IC0tLS0tLS0tCj4gU3ViamVjdDogUmU6IEV0aGVyZXVtIFdhbGxldCBJc3N1ZSAjMjg2OAo+IExv Y2FsIFRpbWU6IEF1Z3VzdCA3LCAyMDE3IDI6NDYgUE0KPiBVVEMgVGltZTogQXVndXN0IDcsIDIw MTcgNjo0NiBQTQo+IEZyb206IHNhcmFAY29uY2VwdG9wb2xpcy5jb20KPiBUbzogTWlzdCBXYWxs ZXQgU3VwcG9ydCA8TWlzdFN1cHBvcnRAcHJvdG9ubWFpbC5jb20+Cj4geWVzIEkgZG8gYnV0IEkg Y2FuIGhhcmRseSBydW4gaXQgb24gdGhpcyBvbmUuIFRoZSBjb21wdXRlciBnZXRzIHJlYWxseSBo b3Qgc28gaXQgaGFzIGEgbG90IHRvIHN5bmNoIHVwLi4uIGxpa2UgMS44IG1pbGxpb24gYmxvY2tz Cj4KPiAtLQo+IFNhcmEgSHVicmljaAo+IE9wZXJhdGlvbnMgTWFuYWdlcgo+IENvbmNlcHRvcG9s aXMsIEluYwo+IEBjb25jZXB0b3BvbGlzCj4gaHR0cDovL2ZhY2Vib29rLmNvbS9jb25jZXB0b3Bv bGlzCj4gaHR0cHM6Ly93d3cuY29uY2VwdG9wb2xpcy5jb20KPiBzYXJhQGNvbmNlcHRvcG9saXMu Y29tCj4gT24gTW9uLCBBdWcgNywgMjAxNywgYXQgMDI6MjcgUE0sIE1pc3QgV2FsbGV0IFN1cHBv cnQgd3JvdGU6Cj4KPj4gSGkgU2FyYSwKPj4gRG8geW91IGhhdmUgdGhlIHdhbGxldCBvbiB0aGUg Y29tcHV0ZXIgeW91IG9yaWdpbmFsbHkgaW5zdGFsbGVkIGl0IG9uPwo+Pgo+PiBSZWdhcmRzLAo+ PiBBbGV4Cj4+Cj4+PiAtLS0tLS0tLSBPcmlnaW5hbCBNZXNzYWdlIC0tLS0tLS0tCj4+PiBTdWJq ZWN0OiBSZTogRXRoZXJldW0gV2FsbGV0IElzc3VlICMyODY4Cj4+PiBMb2NhbCBUaW1lOiBBdWd1 c3QgNywgMjAxNyA5OjUyIEFNCj4+PiBVVEMgVGltZTogQXVndXN0IDcsIDIwMTcgMTo1MiBQTQo+ Pj4gRnJvbTogc2FyYUBjb25jZXB0b3BvbGlzLmNvbQo+Pj4gVG86IE1pc3QgV2FsbGV0IFN1cHBv cnQgPE1pc3RTdXBwb3J0QHByb3Rvbm1haWwuY29tPgo+Pj4gTm8gSSBoYXZlIG5vdC4gVGhlIGV0 aCBzdGlsbCBoYXMgbm90IHRyYW5zZmVyZWQgYW5kIEkgaW5zdGFsbGVkIHdhbGxldCBvbiBhbm90 aGVyIGNvbXB1dGVyIGFuZCBpdCdzIHNheWluZyB0aGF0IEkgaGF2ZSAwIGJhbGFuY2Ugd2hlbiBJ IHNob3VsZCBoYXZlIDEuNTV+IGV0aAo+Pj4KPj4+IC0tCj4+PiBTYXJhIEh1YnJpY2gKPj4+IE9w ZXJhdGlvbnMgTWFuYWdlcgo+Pj4gQ29uY2VwdG9wb2xpcywgSW5jCj4+PiBAY29uY2VwdG9wb2xp cwo+Pj4gaHR0cDovL2ZhY2Vib29rLmNvbS9jb25jZXB0b3BvbGlzCj4+PiBodHRwczovL3d3dy5j b25jZXB0b3BvbGlzLmNvbQo+Pj4gc2FyYUBjb25jZXB0b3BvbGlzLmNvbQo+Pj4gT24gTW9uLCBB dWcgNywgMjAxNywgYXQgMDI6MzIgQU0sIE1pc3QgV2FsbGV0IFN1cHBvcnQgd3JvdGU6Cj4+Pgo+ Pj4+IEhpIFNhcmEsCj4+Pj4gSSBoYXZlIHNlZW4geW91ciBHaXRIdWIgaXNzdWUgWyMyODY4XSho dHRwczovL2dpdGh1Yi5jb20vZXRoZXJldW0vbWlzdC9pc3N1ZXMvMjg2OCksIGhhdmUgeW91IGdv dHRlbiB0aGluZ3Mgc29ydGVkIG91dD8KPj4+Pgo+Pj4+IFJlZ2FyZHMsCj4+Pj4gQWxleA==   --b1_4d5394916ae0686c69b627a4bf2490ec Content-Type: text/html; charset=UTF-8 Content-Transfer-Encoding: base64  PGRpdj5IaSBTYXJhLDxicj48L2Rpdj48ZGl2Pjxicj48L2Rpdj48ZGl2PldvdWxkIHlvdSBtaW5k IHNlbmRpbmcgeW91ciBsb2cgSUQgc28gd2UgY2FuIGlkZW50aWZ5IGFueSBpc3N1ZXMgdGhhdCBj b3VsZCBiZSBjYXVzaW5nIHlvdXIgd2FsbGV0IG5vdCB0byBzeW5jaHJvbml6ZS48YnI+PC9kaXY+ PGRpdj48YnI+PC9kaXY+PGRpdiBjbGFzcz0icHJvdG9ubWFpbF9zaWduYXR1cmVfYmxvY2sgIj48 ZGl2IGNsYXNzPSJwcm90b25tYWlsX3NpZ25hdHVyZV9ibG9jay11c2VyICI+PGRpdj5SZWdhcmRz LDxicj48L2Rpdj48ZGl2PkFsZXg8YnI+PC9kaXY+PC9kaXY+PGRpdj48YnI+PC9kaXY+PC9kaXY+ PGRpdj48YnI+PC9kaXY+PGJsb2NrcXVvdGUgdHlwZT0iY2l0ZSIgY2xhc3M9InByb3Rvbm1haWxf cXVvdGUiPjxkaXY+LS0tLS0tLS0gT3JpZ2luYWwgTWVzc2FnZSAtLS0tLS0tLTxicj48L2Rpdj48 ZGl2PlN1YmplY3Q6IFJlOiBFdGhlcmV1bSBXYWxsZXQgSXNzdWUgIzI4Njg8YnI+PC9kaXY+PGRp dj5Mb2NhbCBUaW1lOiBBdWd1c3QgNywgMjAxNyAyOjQ2IFBNPGJyPjwvZGl2PjxkaXY+VVRDIFRp bWU6IEF1Z3VzdCA3LCAyMDE3IDY6NDYgUE08YnI+PC9kaXY+PGRpdj5Gcm9tOiBzYXJhQGNvbmNl cHRvcG9saXMuY29tPGJyPjwvZGl2PjxkaXY+VG86IE1pc3QgV2FsbGV0IFN1cHBvcnQgJmx0O01p c3RTdXBwb3J0QHByb3Rvbm1haWwuY29tJmd0Ozxicj48L2Rpdj48ZGl2Pjxicj48L2Rpdj48ZGl2 PnllcyBJIGRvIGJ1dCBJIGNhbiBoYXJkbHkgcnVuIGl0IG9uIHRoaXMgb25lLiBUaGUgY29tcHV0 ZXIgZ2V0cyByZWFsbHkgaG90IHNvIGl0IGhhcyBhIGxvdCB0byBzeW5jaCB1cC4uLiBsaWtlIDEu OCBtaWxsaW9uIGJsb2Nrczxicj48L2Rpdj48ZGl2Pjxicj48L2Rpdj48ZGl2PjxkaXYgY2xhc3M9 InNpZ25hdHVyZSI+LS08YnI+PC9kaXY+PGRpdiBjbGFzcz0ic2lnbmF0dXJlIj5TYXJhIEh1YnJp Y2g8YnI+PC9kaXY+PGRpdiBjbGFzcz0ic2lnbmF0dXJlIj5PcGVyYXRpb25zIE1hbmFnZXI8YnI+ PC9kaXY+PGRpdiBjbGFzcz0ic2lnbmF0dXJlIj5Db25jZXB0b3BvbGlzLCBJbmM8YnI+PC9kaXY+ PGRpdiBjbGFzcz0ic2lnbmF0dXJlIj5AY29uY2VwdG9wb2xpczxicj48L2Rpdj48ZGl2IGNsYXNz PSJzaWduYXR1cmUiPmh0dHA6Ly9mYWNlYm9vay5jb20vY29uY2VwdG9wb2xpczxicj48L2Rpdj48 ZGl2IGNsYXNzPSJzaWduYXR1cmUiPmh0dHBzOi8vd3d3LmNvbmNlcHRvcG9saXMuY29tPGJyPjwv ZGl2PjxkaXYgY2xhc3M9InNpZ25hdHVyZSI+c2FyYUBjb25jZXB0b3BvbGlzLmNvbTxicj48L2Rp dj48ZGl2IGNsYXNzPSJzaWduYXR1cmUiPjxicj48L2Rpdj48L2Rpdj48ZGl2Pjxicj48L2Rpdj48 ZGl2Pjxicj48L2Rpdj48ZGl2Pk9uIE1vbiwgQXVnIDcsIDIwMTcsIGF0IDAyOjI3IFBNLCBNaXN0 IFdhbGxldCBTdXBwb3J0IHdyb3RlOjxicj48L2Rpdj48YmxvY2txdW90ZSB0eXBlPSJjaXRlIj48 ZGl2PkhpIFNhcmEsPGJyPjwvZGl2PjxkaXY+PGJyPjwvZGl2PjxkaXY+RG8geW91IGhhdmUgdGhl IHdhbGxldCBvbiB0aGUgY29tcHV0ZXIgeW91IG9yaWdpbmFsbHkgaW5zdGFsbGVkIGl0IG9uPzxi cj48L2Rpdj48ZGl2Pjxicj48L2Rpdj48ZGl2PjxkaXY+PGRpdj5SZWdhcmRzLDxicj48L2Rpdj48 ZGl2PkFsZXg8YnI+PC9kaXY+PC9kaXY+PC9kaXY+PGRpdj48YnI+PC9kaXY+PGJsb2NrcXVvdGUg dHlwZT0iY2l0ZSI+PGRpdj4tLS0tLS0tLSBPcmlnaW5hbCBNZXNzYWdlIC0tLS0tLS0tPGJyPjwv ZGl2PjxkaXY+U3ViamVjdDogUmU6IEV0aGVyZXVtIFdhbGxldCBJc3N1ZSAjMjg2ODxicj48L2Rp dj48ZGl2PkxvY2FsIFRpbWU6IEF1Z3VzdCA3LCAyMDE3IDk6NTIgQU08YnI+PC9kaXY+PGRpdj5V VEMgVGltZTogQXVndXN0IDcsIDIwMTcgMTo1MiBQTTxicj48L2Rpdj48ZGl2PkZyb206IHNhcmFA Y29uY2VwdG9wb2xpcy5jb208YnI+PC9kaXY+PGRpdj5UbzogTWlzdCBXYWxsZXQgU3VwcG9ydCAm bHQ7TWlzdFN1cHBvcnRAcHJvdG9ubWFpbC5jb20mZ3Q7PGJyPjwvZGl2PjxkaXY+PGJyPjwvZGl2 PjxkaXY+Tm8gSSBoYXZlIG5vdC4gVGhlIGV0aCBzdGlsbCBoYXMgbm90IHRyYW5zZmVyZWQgYW5k IEkgaW5zdGFsbGVkIHdhbGxldCBvbiBhbm90aGVyIGNvbXB1dGVyIGFuZCBpdCdzIHNheWluZyB0 aGF0IEkgaGF2ZSAwIGJhbGFuY2Ugd2hlbiBJIHNob3VsZCBoYXZlIDEuNTV+IGV0aDxicj48L2Rp dj48ZGl2Pjxicj48L2Rpdj48ZGl2PjxkaXY+LS08YnI+PC9kaXY+PGRpdj5TYXJhIEh1YnJpY2g8 YnI+PC9kaXY+PGRpdj5PcGVyYXRpb25zIE1hbmFnZXI8YnI+PC9kaXY+PGRpdj5Db25jZXB0b3Bv bGlzLCBJbmM8YnI+PC9kaXY+PGRpdj5AY29uY2VwdG9wb2xpczxicj48L2Rpdj48ZGl2Pmh0dHA6 Ly9mYWNlYm9vay5jb20vY29uY2VwdG9wb2xpczxicj48L2Rpdj48ZGl2Pmh0dHBzOi8vd3d3LmNv bmNlcHRvcG9saXMuY29tPGJyPjwvZGl2PjxkaXY+c2FyYUBjb25jZXB0b3BvbGlzLmNvbTxicj48 L2Rpdj48ZGl2Pjxicj48L2Rpdj48L2Rpdj48ZGl2Pjxicj48L2Rpdj48ZGl2Pjxicj48L2Rpdj48 ZGl2Pk9uIE1vbiwgQXVnIDcsIDIwMTcsIGF0IDAyOjMyIEFNLCBNaXN0IFdhbGxldCBTdXBwb3J0 IHdyb3RlOjxicj48L2Rpdj48YmxvY2txdW90ZSB0eXBlPSJjaXRlIj48ZGl2PkhpIFNhcmEsPGJy PjwvZGl2PjxkaXY+PGJyPjwvZGl2PjxkaXY+SSBoYXZlIHNlZW4geW91ciBHaXRIdWIgaXNzdWUg PGEgcmVsPSJub3JlZmVycmVyIG5vZm9sbG93IG5vb3BlbmVyIiBocmVmPSJodHRwczovL2dpdGh1 Yi5jb20vZXRoZXJldW0vbWlzdC9pc3N1ZXMvMjg2OCIgdGl0bGU9IiMyODY4Ij4jMjg2ODwvYT4s IGhhdmUgeW91IGdvdHRlbiB0aGluZ3Mgc29ydGVkIG91dD88YnI+PC9kaXY+PGRpdj48YnI+PC9k aXY+PGRpdj48ZGl2PjxkaXY+UmVnYXJkcyw8YnI+PC9kaXY+PGRpdj5BbGV4PGJyPjwvZGl2Pjwv ZGl2PjxkaXY+PGJyPjwvZGl2PjwvZGl2PjxkaXY+PGJyPjwvZGl2PjwvYmxvY2txdW90ZT48ZGl2 Pjxicj48L2Rpdj48L2Jsb2NrcXVvdGU+PGRpdj48YnI+PC9kaXY+PC9ibG9ja3F1b3RlPjxkaXY+ PGJyPjwvZGl2PjwvYmxvY2txdW90ZT48ZGl2Pjxicj48L2Rpdj4=    --b1_4d5394916ae0686c69b627a4bf2490ec--
--
Sara Hubrich
Operations Manager
Conceptopolis, Inc
@conceptopolis
http://facebook.com/conceptopolis
https://www.conceptopolis.com
sara@conceptopolis.com



On Tue, Aug 8, 2017, at 10:13 AM, ProtonMail wrote:
> Hi,
> 
> Sorry for the inconvenience. Can you please send us the message
> headers so we can investigate this case?> 
> Best Regards,
> The ProtonMail Team
> 
> --
> https://twitter.com/ProtonMail
> https://facebook.com/ProtonMail
> 
> Want to support ProtonMail? You can upgrade or donate[1]!
> 
> 
> Sent with ProtonMail[2] Secure Email.
> 
>> -------- Original Message --------
>> Subject: Fwd: Re: Ethereum Wallet Issue #2868
>> Local Time: August 8, 2017 4:06 PM
>> UTC Time: August 8, 2017 2:06 PM
>> From: sara@conceptopolis.com
>> To: contact@protonmail.ch
>> 
>> Hello,
>> 
>> I'd like to report a scam that is using your email service.
>> 
>> Below is  a scammer, since they asked for my wallet login ID after
>> pretending to be Mist Support.>> 
>> I never contacted them, just posted my issues on GitHub. They got my
>> email from there.>> 
>> Thank you!
>> 
>> --
>> Sara Hubrich
>> Operations Manager
>> Conceptopolis, Inc
>> @conceptopolis
>> http://facebook.com/conceptopolis
>> https://www.conceptopolis.com
>> sara@conceptopolis.com
>> 
>> 
>> 
>> ----- Original message -----
>> From: Sara Hubrich <sara@conceptopolis.com>
>> To: Mist Wallet Support <MistSupport@protonmail.com>
>> Subject: Re: Ethereum Wallet Issue #2868
>> Date: Mon, 07 Aug 2017 17:00:15 -0400
>> 
>> Ha! no way.
>> 
>> --
>> Sara Hubrich
>> Operations Manager
>> Conceptopolis, Inc
>> @conceptopolis
>> http://facebook.com/conceptopolis
>> https://www.conceptopolis.com
>> sara@conceptopolis.com
>> 
>> 
>> 
>> On Mon, Aug 7, 2017, at 03:35 PM, Mist Wallet Support wrote:
>>> Hi Sara,
>>> 
>>> Would you mind sending your log ID so we can identify any issues
>>> that could be causing your wallet not to synchronize.>>> 
>>> Regards,
>>> Alex
>>> 
>>> 
>>>> -------- Original Message --------
>>>> Subject: Re: Ethereum Wallet Issue #2868
>>>> Local Time: August 7, 2017 2:46 PM
>>>> UTC Time: August 7, 2017 6:46 PM
>>>> From: sara@conceptopolis.com
>>>> To: Mist Wallet Support <MistSupport@protonmail.com>
>>>> 
>>>> yes I do but I can hardly run it on this one. The computer gets
>>>> really hot so it has a lot to synch up... like 1.8 million blocks>>>> 
>>>> --
>>>> Sara Hubrich
>>>> Operations Manager
>>>> Conceptopolis, Inc
>>>> @conceptopolis
>>>> http://facebook.com/conceptopolis
>>>> https://www.conceptopolis.com
>>>> sara@conceptopolis.com
>>>> 
>>>> 
>>>> 
>>>> On Mon, Aug 7, 2017, at 02:27 PM, Mist Wallet Support wrote:
>>>>> Hi Sara,
>>>>> 
>>>>> Do you have the wallet on the computer you originally installed
>>>>> it on?>>>>> 
>>>>> Regards,
>>>>> Alex
>>>>> 
>>>>>> -------- Original Message --------
>>>>>> Subject: Re: Ethereum Wallet Issue #2868
>>>>>> Local Time: August 7, 2017 9:52 AM
>>>>>> UTC Time: August 7, 2017 1:52 PM
>>>>>> From: sara@conceptopolis.com
>>>>>> To: Mist Wallet Support <MistSupport@protonmail.com>
>>>>>> 
>>>>>> No I have not. The eth still has not transfered and I installed
>>>>>> wallet on another computer and it's saying that I have 0 balance
>>>>>> when I should have 1.55~ eth>>>>>> 
>>>>>> --
>>>>>> Sara Hubrich
>>>>>> Operations Manager
>>>>>> Conceptopolis, Inc
>>>>>> @conceptopolis
>>>>>> http://facebook.com/conceptopolis
>>>>>> https://www.conceptopolis.com
>>>>>> sara@conceptopolis.com
>>>>>> 
>>>>>> 
>>>>>> 
>>>>>> On Mon, Aug 7, 2017, at 02:32 AM, Mist Wallet Support wrote:
>>>>>>> Hi Sara,
>>>>>>> 
>>>>>>> I have seen your GitHub issue #2868[3], have you gotten things
>>>>>>> sorted out?>>>>>>> 
>>>>>>> Regards,
>>>>>>> Alex
>>>>>>> 
>>>>>>> 
>>>>>> 
>>>>> 
>>>> 
>>> 
>> 
> 


--
Sara Hubrich
Operations Manager
Conceptopolis, Inc
@conceptopolis
http://facebook.com/conceptopolis
https://www.conceptopolis.com
sara@conceptopolis.com



On Thu, Aug 10, 2017, at 05:09 AM, H wrote:
> I have opened communications with protonmail to try and get this
> account suspended.> @shayanb[4] do you have an e-mail from them you can share here (along
> with the email headers)?> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[5], or mute the thread[6].> 


Links:

  1. https://protonmail.com/donate
  2. https://protonmail.com
  3. https://github.com/ethereum/mist/issues/2868
  4. https://github.com/shayanb
  5. https://github.com/ethereum/mist/issues/2908#issuecomment-321496038

**Comment by 409H** [comment]
Thanks @shubrich76 

For those wanting the above decoded;

```
Hi Sara,

Would you mind sending your log ID so we can identify any issues that could be causing your wallet not to synchronize.

Regards,
Alex


-------- Original Message --------
Subject: Re: Ethereum Wallet Issue #2868
Local Time: August 7, 2017 2:46 PM
UTC Time: August 7, 2017 6:46 PM
From: sara@conceptopolis.com
To: Mist Wallet Support <MistSupport@protonmail.com>

yes I do but I can hardly run it on this one. The computer gets really hot so it has a lot to synch up... like 1.8 million blocks

--
Sara Hubrich
Operations Manager
Conceptopolis, Inc
@conceptopolis
http://facebook.com/conceptopolis
https://www.conceptopolis.com
sara@conceptopolis.com



On Mon, Aug 7, 2017, at 02:27 PM, Mist Wallet Support wrote:
Hi Sara,

Do you have the wallet on the computer you originally installed it on?

Regards,
Alex

-------- Original Message --------
Subject: Re: Ethereum Wallet Issue #2868
Local Time: August 7, 2017 9:52 AM
UTC Time: August 7, 2017 1:52 PM
From: sara@conceptopolis.com
To: Mist Wallet Support <MistSupport@protonmail.com>

No I have not. The eth still has not transfered and I installed wallet on another computer and it's saying that I have 0 balance when I should have 1.55~ eth

--
Sara Hubrich
Operations Manager
Conceptopolis, Inc
@conceptopolis
http://facebook.com/conceptopolis
https://www.conceptopolis.com
sara@conceptopolis.com



On Mon, Aug 7, 2017, at 02:32 AM, Mist Wallet Support wrote:
Hi Sara,

I have seen your GitHub issue #2868, have you gotten things sorted out?

Regards,
Alex


```

**Comment by 409H** [comment]
I've just got word from ProtonMail and they've suspended the account. 

> Hi Harry,
> 
> Thank you for providing this information. We have suspended this account.
> 
> If you need further assistance, do not hesitate to contact us.
> 
> Best Regards,
> 
> ProtonMail Abuse Team
