### ISSUE TITLE
Wrong password but I'm sure it's ok!

### ISSUE THREAD

**Issue by Spartakkus** [ethereum/mist#2910]
Version: 0.9.0
OS & Version: windows

I everybody. I'm having a real bad time with ethereum wallet. Can't unlock from there, neither directly from geth node, neither from myetherwallet.

Could the key file be corrupted? I'm sure I'm using correct password!! I'm desperated, somebody please help. Most weird character I had on my password was a @, could special characters be a problem?

I have also tried with an offline backup file, but it doesn't work either

Help please!

**Comment by IvanM1993** [comment]
I have the same problem. decided to ether the password 100% correct, because I saved in Notepad. don't understand what the fuck . I'm pissed. the problem with this wallet. I have a second address in the wallet I tested it on myetherwallet.com everything works. a basic wallet problem

**Comment by ingo1970** [comment]
Having same problem. Created a second wallet without password and wallet created own password now can't access ether.

**Comment by IvanM1993** [comment]
has anyone solved this problem??

**Comment by Spartakkus** [comment]
everyone try this:

https://github.com/lexansoft/ethcracker

Worked for me, I, despite being sure, had put the password wrong...

**Comment by ingo1970** [comment]
I can access my wallet with password I created. My problem is I cant send funds from any account but main account in wallet. Very frustrating keep getting Version not supported: 2 message

**Comment by garretlaxton** [comment]
@ingo1970 If you know your account password, you can try sending with https://www.myetherwallet.com

**Comment by ingo1970** [comment]
That link takes me to create a new wallet. I can access main account in my Wallet and can send funds from main account.It just wont let me send ether from 2nd and 3rd account. Not sure how creating a new wallet will help.

**Comment by garretlaxton** [comment]
@ingo1970 You can send using the send option, just import your account you want to send from https://www.myetherwallet.com/#send-transaction

**Comment by ingo1970** [comment]
But it doesn't give me the option to import only send or select json file

**Comment by garretlaxton** [comment]
@ingo1970 your keystore files are json files, by selecting them you are importing them.

**Comment by ingo1970** [comment]
@garretlaxton amazing that worked! Thanks for your help. Its weird that you can't access the new accounts directly from inside the wallet.

**Comment by evertonfraga** [comment]
@ingo1970 can you provide a screenshot with this "Version not supported: 2" message?

**Comment by IvanM1993** [comment]
Spartakkus I used this link, something happened. I got to the section to install Go Language

git https://github.com/lexansoft/ethcracker clone
CD ethcracker.  After this step, I had ethcracker folders with the files. But I do not understand what this is for. There are keystore files.What to do next? Please give me some advice.

**Comment by Spartakkus** [comment]
Write in that post, the guy that wrote the code helped me a lot and quick. Very nice guy

**Comment by IvanM1993** [comment]
thank you

**Comment by evertonfraga** [comment]
Please reopen should you want to continue the discussion.
