### ISSUE TITLE
Mist not seeing my wallet keystore files. Cannot import old wallet

### ISSUE THREAD

**Issue by ShadowOak** [ethereum/mist#2911]
``````
Version: `0.8.10`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 4, 134, 410
``````
I had to reinstall Mist on a different hard drive. I accidentally deleted my keystore folder. But, I was able to recover my keystore files via Recuva. It said the files were in excellent condition. 

My new install of Mist is full synced but Mist cannot see my 2 old wallets. I created 2 new dummy wallets. It was able to see those even after I deleted it and but it back in to test it.
If I try to use Import accounts, it says the files cannot be recognized. When I try to do it with the new dummy wallet keystores, Mist just crashes.

I even placed a copy of the keystore folder in my Appdata folder besides the directly I installed the blockchain on.

![keystore](https://user-images.githubusercontent.com/30850365/29102044-46204376-7c6b-11e7-8699-d070b832b280.png)
[Mist.zip](https://github.com/ethereum/mist/files/1210066/Mist.zip)

**Comment by coinchon112** [comment]
what errors does it show when you try to send Ether?

**Comment by ShadowOak** [comment]
@coinchon112 Not sure what you are asking. I cannot send any because the balance is showing 0.  When I select Send, the 'From' box is blank, it only shows the little icon for it.

**Comment by garretlaxton** [comment]
Have you tried using https://www.myetherwallet.com?

**Comment by ShadowOak** [comment]
@garretlaxton I just tried it. It is saying they are not a valid file type. I am just assuming now that my keystores were corrupted.

**Comment by WimDeGroote** [comment]
Hello. One thing that kept me searching for a while is following. Say you purchased ETH using Mist on computer A. Now you are on a new computer, computer B. You install the Wallet and want to sell/send your ETH. You try to import your UTC files using either the "drag presales" screen or by copy/pasting your UTC files into the KeyStore directory on computer B. This will not work. If you purchased your ETH using MIST on computer A, also use Mist on computer B, not the Wallet. Once I started using Mist to create account/buy & also Mist to sell/send all went well :-) Good luck :-)

**Comment by alexvandesande** [comment]
It seems that you are talking about contract wallets. Those are not saved in the backup, but all you need is their address and you can still have access to the funds. Search on etherscan to figure out the address of your wallet, and then go to https://wallet.ethereum.org/account/new and import your old wallet
