### ISSUE TITLE
Ethereum wallet fails to connect to geth with no accounts set in keystore

### ISSUE THREAD

**Issue by winsvega** [ethereum/mist#2913]
``````
Version: `0.9.0`
OS & Version: linux
Node type: `geth`
Number of blocks synchronized: light
``````

```Error starting up node and/or syncing TypeError: Cannot read property 'timestamp' of undefined```

**Comment by PatchRanger** [comment]
Confirming.
The blockchain looks synchronized - and it continues updating. While accounts are totally not working at all:
- My old accounts were not loaded into.
- I have the only Etherbase account with 0 ETH in it.
- There is no accounts to choose from at New Contract screen: the select is simply empty, no option at all.

**Comment by cryzed** [comment]
Same proplem here, I would also like to see this fixed, as Mist is currently unusable for me: the full synchronization takes too long and the light synchronization is broken. However, even updating Geth to 1.6.7, as planned in the referenced issue, doesn't seem to fix the problem: at some point the Mist client throws the described error and the synchronization in geth slows to a crawl (a single block header every few seconds, instead of hundreds).

**Comment by winsvega** [comment]
to resolve the error I described, you could just manually add a private key to the keystore folder.

**Comment by cryzed** [comment]
Oh, I do have an account there, and geth even lists it -- I still get the error when attempting to synchronize the block chain in light mode when using mist. Towards the very end of the process an error is raised and geth's synchronization has a count of 1 every so often.

**Comment by winsvega** [comment]
This error message ```Error starting up node and/or syncing TypeError: Cannot read property 'timestamp' of undefined``` comes from the Mist. so it is not the issue in synchronization of geth. 
Try syncing geth standalone and then run Mist

**Comment by cryzed** [comment]
That seems to have worked, thank you.

**Comment by PatchRanger** [comment]
Thanks to the suggestions above, I was able to workaround the `timestamp` issue with this: I've replaced a comand under Myth icon from
```
"/opt/Mist/mist"
```
to
```
bash -c "geth --syncmode light --cache 512 --verbosity 4 & sleep 30 && /opt/Mist/mist"
```
Note that in one case single `&` is used while in the other - double (`&&`). Myth now starts successfully. But nevertheless the issue with accounts is still valid. I am going to somehow apply the @winsvega's workaround: to manually add a private key to the keystore folder.

**Comment by PatchRanger** [comment]
I've checked: keystore is not empty in my case.

Assuming that this concrete issue is dedicated to `timestamp` issue, I've created a new issue for my own case: #2938.

**Comment by HaleTom** [comment]
I noticed that `geth` was complaining with:

```
ERROR[09-29|13:00:24] Failed to retrieve current release       err="can't fetch trie key 5380c7b7ae81a58eb98d9c78de4a1fd7fd9535fc953ed2be602daaa41767312a: no suitable peers available" 
```

What worked for me was to:
1. Shutdown `geth`
1. rm -r ~/.ethereum/geth
1. Restart `geth`

However, next time I'd first try with `geth removedb`. 

This solved Mist's timestamp error for me.

**Comment by evertonfraga** [comment]
This is probably fixed, due to the combination of the huge refactor we did + several geth updates. 
**Please feel free** to reopen should you still have some considerations about it.
