### ISSUE TITLE
Till now i never seen transfered money to my account.

### ISSUE THREAD

**Issue by RGMV** [ethereum/mist#2914]
According from website Ethereum i must send money to address:
LRPHpZ1zN9yH6afn2oKsawhGLZNKXRv26m
and then they (Ethereum) send it to my Ethereum wallet at:
0xF2b90B005268C538FD48853bAD1A80C897054E4c

But till now i never seen the money.
So Ethereum, did i now lost my 2.59477633 LTC ?
(Transactie-ID: 583ce3713f63a50101cc6aaf046ba284df22671b5ff7e7b254cea8679a0a2925)
2222 comfirms (at this moment, 9-8-2017)

Can you check out what happend?
I like to hear from you..
``````
Version: `0.9.0`
OS & Version: Windows 7
Node type: `geth`
Number of blocks synchronized: all
``````

**Comment by garretlaxton** [comment]
Duplicate Post - Answered on [#2929](https://github.com/ethereum/mist/issues/2929)

**Comment by alexvandesande** [comment]
> According from website Ethereum i must send money to address:

I'm not sure what you meant, there's no such information on website ethereum. I suppose you meant the shapeshift website, where you came from using your ethereum wallet. Only they can solve shaopeshift issues.

We are reviewing at old unanswered issues, sorry it took so long to reach yours, it's a long backlog.
