### ISSUE TITLE
Wallet is getting too big (80+ GB and growing fast). Any way to reduce the size?

### ISSUE THREAD

**Issue by crutor0x** [ethereum/mist#2915]
``````
Version: `0.9.0`
OS & Version: macOS 10.12.5
Node type: `eth/geth`
Number of blocks synchronized: 4 136 000
``````
Is there any way to reduce the size of the Ethereum Wallet that's already been running few months? I've always been using just the native mac app to connect to the network. Just recently I learned that I can start the client in light mode using the geth shell and syncmode="light". This however doesn't work, it says that it can't run in light mode because I already have blocks downloaded.

So how can I reduce the size? Do I delete everything and then run the geth in light mode. Also I saw some open issue here that backups don't work properly, so I'm a little scared to reinstall it.

Any help much appreciated, I'm running out of space fast (I already deleted about 30-40 gigs of files just to make space for the wallet).

**Comment by evertonfraga** [comment]
That's actually a Geth issue, not Mist. But as of now, using geth, there is no way to prune your local database. Geth's core dev recommendation is to remove geth db and sync  again with `--fast` flag enabled.

Here's a safe way to do that:
```
$ geth removedb
$ geth --fast --cache=2048
```

`2048` results in 2GB cache, use whatever value you want.

Learn more:
> https://ethereum.stackexchange.com/questions/1940/how-to-reduce-chaindata-database-size
