### ISSUE TITLE
"Infinite Peer Search" for Ethereum wallet

### ISSUE THREAD

**Issue by underterri** [ethereum/mist#292]
Today I downloaded the wallet exe from ethereum.org main site.

Upon launching it it always hangs up on "Seeking peers". No progress is shown.

I disabled anti virus, I even uninstalled it. Then I disabled Firewall.

The Bitcoin wallet works fine.

**Windows version: Windows 7 Ultimate N, Service Pack 1
Ethereum wallet: 0.5.1**

**Comment by frozeman** [comment]
Can you try running the node inside the `wallet/resources/node/geth` folder with:

`geth.exe --nat=none`

And see if it starts downloading blocks?

You can the start the wallet after and it will connect to the running node.

**Comment by aerohorn** [comment]
Same problem
![screenshot_1](https://cloud.githubusercontent.com/assets/9201431/13612436/f3ee48fa-e580-11e5-8f96-273fecebe801.png)

How i can start with `geth.exe --nat=none`, what should i do?

**Comment by frozeman** [comment]
Use the cmd.exe of windows. Please google this.

**Comment by aerohorn** [comment]
I need to install Chocolatey for this?

**Comment by aerohorn** [comment]
Start geth with `geth.exe --nat=none`
![screenshot_2](https://cloud.githubusercontent.com/assets/9201431/13616077/c4483244-e591-11e5-949c-32df3e6477a2.png)

But nothing happens. Wait about 15 minutes.
Also start wallet with this geth and nothing happens as well

**Comment by D-Nice** [comment]
More likely than anything it's a firewall issue. Router or AV firewall.

**Comment by aerohorn** [comment]
i need to open 30303 port?

**Comment by aerohorn** [comment]
I just opened port 30303, but still can't sync my wallet

**Comment by aerohorn** [comment]
Solved. It was necessary to synchronize clock with "time.nist.gov" in windows time setting

**Comment by aerohorn** [comment]
Another question. Where i can change directory for eth "chaindata". I think my SSD can 
suffer from this

**Comment by D-Nice** [comment]
The following link shows all CLI arguments: https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

The one you're looking for is --datadir

For Windows, to do a different drive, you'd want to run the following for geth:
geth --datadir "d:\Some Folder\Chaindata"

**Comment by sebtymo** [comment]
ame issue on Mac. I'm a total noob to all of this and don't know any code. Any help would be appreciated.

**Comment by underterri** [comment]
I tried synchronising times several times, restarting the computer, removing firewall and anti virus and it does not work. Tell me what to do exactly to make it work. I downloaded a wallet program. I don't know how to do command line, etc...I just want the program to work.

**Comment by D-Nice** [comment]
Is there 0 synchronization, or have some blocks been downloaded, and now it's no longer syncing. One issue I've noticed is if a block gets corrupted in the chaindata you have, the wallet just won't sync.

Try deleting your chaindata folder, but make a backup first. It's located in C:\Users\Username\AppData\Roaming\Ethereum

Then, run the newest geth or run the geth from this wallet, located in the subdirectory Ethereum-Wallet-win64-0-5-1\resources\node\geth

with the following command line 

geth.exe --fast --cache 512 --maxpeers 100 --verbosity 5 console

if you get any errors there let us know

**Comment by aerohorn** [comment]
**underterri** try open 30303 port in setting of your router

**Comment by underterri** [comment]
How do I do that? I don't want to make my network vulnerable.

**Comment by frozeman** [comment]
Note: when you have already created accounts and you want to remove the `Ethereum` folder, make sure you backup the `keystore` inside first!

**Comment by underterri** [comment]
I don't have to go through all of this hassle to start Bitcoin core client. I think it is up to devs to fix this issue.

**Comment by cayblood** [comment]
@underterri You need to understand more about the underlying technology if you want to participate in ethereum at this relatively early stage of the game. There are still sharp edges. Firewall traversal is a difficult problem, especially in a serverless protocol. In many instances the configuration of your local network can make it impossible to do certain things, through no fault of the software. I would recommend finding someone who is more tech-savvy to help you troubleshoot the issue.

**Comment by underterri** [comment]
I disabled the firewall.

**Comment by cayblood** [comment]
There is probably still a misconfiguration somewhere on your local network. I would recommend connecting your computer to other networks and seeing if the problem remains.

**Comment by cayblood** [comment]
Just to clarify, there is a firewall configuration on your own computer, but your internet router most likely has one also. There are many other things that could be wrong with your network besides just the firewall also.

**Comment by underterri** [comment]
Alright, guys. Here is what I did. I deleted the chaindata folder as instructed above.

Then I opened cmd, went to the geth folder, run this command:
geth.exe --fast --cache 512 --maxpeers 100 --verbosity 5 console

Once I did that, numbers started flying (lots of text moving fast).

Then I launched Ethereum.exe while this was running in background.

Numbers stopped running in cmd so fast and instead it says:
[some numbers table.go:336] no seed nodes found

**Comment by alexvandesande** [comment]
@underterri has your issue been solved? If so, please close this one. We are going to put an bug fix to the time mist thing later.

**Comment by underterri** [comment]
It has not been solved, the issue remains.

**Comment by Joter85** [comment]
Same issue here. Firewall ports are open, I have tried it with:
geth --nat extip:xx:xx:xx:xx --maxpeers "100"
geth --nat=none --maxpeers "100"

Tried to manually add peers. Didn't help either. 

When I run with verbosity 5 I only see `10788 table.go:336] no seed nodes found`

**Comment by swt83** [comment]
Same issue.  Mac running 0.5.2.

**Comment by D-Nice** [comment]
I'm wondering if this has to do with ISPs and throttling, and them blocking P2P activity? Do you guys have issues with torrents as well or no?

**Comment by underterri** [comment]
No issues with ISP throttling, works fine on another computer (Mac), so it is clearly problem with the client running on windows.

**Comment by D-Nice** [comment]
I'll do more testing on this, because to be honest, my PC syncs perfectly, but my GF's PC keeps getting corrupted blocks and is unable to sync. Everything is the exact same, except that she has Avast AV on hers and her Windows 7 has no updates. 

Windows 7 basically runs in handicap mode if you don't, with constant crashes etc... And I've also disabled the AV on hers, and it still wouldn't sync, so I will try updating her Windows fully and see if that fixes it.

What Windows are you on and is it fully up to date?

**Comment by ruhigesPferd** [comment]
Thanks for your help with the "use command box to start the wallet".

Before it wasn't synchronising though it hat 2-5 peers when starting it over the .exe button.

After using the geth.exe --nat=none

and starting via dos-box, it was done after seconds and updated the wallet value <3

**Comment by swt83** [comment]
I can confirm that simply rebooting your computer solves this problem.

**Comment by richardsj** [comment]
Rebooting your computer is a hint at what is causing the problem but is not actually a solution.  This seems to be an extremely common problem

**Comment by luclu** [comment]
Could you kindly check how version 0.7.4 is behaving on this?

**Comment by luclu** [comment]
We just released version 0.7.5 which includes geth 1.4.7 with several minor improvements to the peer discovery. Please check if your situation got improved by this: https://github.com/ethereum/mist/releases

**Comment by myalcin81** [comment]
I have to same problem with mist 0.7.5. 
But I solved following this solution: https://github.com/ethereum/mist/issues/94#issuecomment-188112488

**Comment by luclu** [comment]
Issues of affected 0.7.5 users: https://github.com/ethereum/mist/issues/876, https://github.com/ethereum/mist/issues/840

Current workaround: 
change `--nat` flag to:
`--nat none` or `--nat extip:(YOUR_PUBLIC_IP)` as @myalcin81 suggested.

**Comment by MarinAngelo** [comment]
Same issue here. The cli comand geth.exe --nat=none doesn't do anything, the screen just remains the same for hours. As all worked fine last week and I did not change anything on my system I don't think it is a local problem.

**Comment by ORIELLY** [comment]
hi @luclu sorry for the delay. my problem persists. this is the printscreen of the splash screen you told me to do.

http://imgur.com/3EPydLf

Also I did start the wallet on the commandline with Ethereum-Wallet.exe -- --nat=none and I got this errors as soon as it started to run

http://imgur.com/xWUHsjF

should I delete/move/rename the whole chaindata folder and resync????

**Comment by punit167** [comment]
Here is what fixed my problem.
I'm running windows 7, 64 bit. 
Do you see the annoying little popup when windows says "do you want to allow this NEW SOFTWARE access to network"? Well since Mist is run as an exe, and is not officially installed, it never got access to the network as you never got that popup. 
From firewall settings, find "Allow programs through windows firewall". Go to Change Settings, and click "Allow another program". On the next popup, click Browse, and navigate to and select Mist.exe. The program got added as Electron in my system.

I ran Mist again.. and things were different immediately, I saw TEST-NET appearing on top and it started downloading blocks soon after.

Hope this helps.

**Comment by PatchRanger** [comment]
I confirm the issue. The restart helps to workaround it - though it is not a solution.
OS: Ubuntu 14.04
Ethereum Wallet: 0.8.1

**Comment by Nammalvar** [comment]
Same problem too with Mac OS X and eth wallets 7.6 to 8.1 . Solved by disabling temporarily my router FW, despite its UPnP configuration OK. Strangely the problem appeared after The DAO hack. Pure coincidence I think. Running geth with either --nat flag did not help. Re-enabling the router FW afterwards was ok too.

**Comment by Nammalvar** [comment]
OK here is an update with my issue. It's not an "infinite search" but a very very looooooong sync. And it's slowly getting better along the days. At launch (of wallet) nothing happens at first, can be so during 20 minutes. Then it randomly syncs, the HCI is responding for a while, and after some time again it freezes for a long time: "24 minutes since last block", can be "an hour since last block" (still working on my computer meanwhile). It seems the phenomenon is disappearing gradually (or its depending on the traffic ?). Still no idea of the root cause.

**Comment by tbrannt** [comment]
I have the same problem as decribed by Nammalvar with ubuntu and 0.8.1

**Comment by zzzman20** [comment]
So, I was having this same problem too, wallet stuck looking for peers on startup. I deleted everything from the C:\Users\XXXX\AppData\Roaming\Ethereum folder except for keystore, started Mist again, and it immediately started syncing. Hope this helps...

**Comment by kost** [comment]
More verbose logs:

I0924 16:11:04.803021 eth/downloader/downloader.go:1442] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0924 16:11:17.375227 p2p/discover/table.go:393] seed node (age 315h6m34.375209555s): enode://1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d89d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082@52.74.57.123:30303
I0924 16:11:17.375331 p2p/discover/table.go:393] seed node (age 316h29m24.3753246s): enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303
I0924 16:11:17.375405 p2p/discover/table.go:393] seed node (age 315h4m29.375399044s): enode://de471bccee3d042261d52e9bff31458daecc406142b401d4cd848f677479f73104b9fdeb090af9583d3391b7f10cb2ba9e26865dd5fca4fcdc0fb1e3b723c786@54.94.239.50:30303
I0924 16:11:18.377319 p2p/dial.go:263] dial tcp 52.16.188.185:30303 (a979fb575495)
I0924 16:11:18.377354 p2p/dial.go:263] dial tcp 54.94.239.50:30303 (de471bccee3d)
I0924 16:11:18.377352 p2p/dial.go:263] dial tcp 52.74.57.123:30303 (1118980bf48b)
I0924 16:11:23.674741 p2p/server.go:617] dyn dial conn 52.74.57.123:30303 faild enc handshake: read tcp 192.168.1.22:55676->52.74.57.123:30303: i/o timeout
I0924 16:11:24.803497 eth/downloader/downloader.go:1442] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0924 16:11:33.373143 p2p/discover/table.go:393] seed node (age 315h6m50.373126239s): enode://1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d89d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082@52.74.57.123:30303
I0924 16:11:33.373264 p2p/discover/table.go:393] seed node (age 315h4m45.373257291s): enode://de471bccee3d042261d52e9bff31458daecc406142b401d4cd848f677479f73104b9fdeb090af9583d3391b7f10cb2ba9e26865dd5fca4fcdc0fb1e3b723c786@54.94.239.50:30303
I0924 16:11:33.373348 p2p/discover/table.go:393] seed node (age 316h29m40.373341481s): enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303
I0924 16:11:44.803795 eth/downloader/downloader.go:1442] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0924 16:11:49.376563 p2p/discover/table.go:393] seed node (age 315h5m1.376545745s): enode://de471bccee3d042261d52e9bff31458daecc406142b401d4cd848f677479f73104b9fdeb090af9583d3391b7f10cb2ba9e26865dd5fca4fcdc0fb1e3b723c786@54.94.239.50:30303
I0924 16:11:49.376683 p2p/discover/table.go:393] seed node (age 316h29m56.376672232s): enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303
I0924 16:11:49.376758 p2p/discover/table.go:393] seed node (age 315h7m6.376747472s): enode://1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d89d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082@52.74.57.123:30303
I0924 16:11:57.335412 p2p/dial.go:263] dial tcp 52.74.57.123:30303 (1118980bf48b)
I0924 16:12:04.804025 eth/downloader/downloader.go:1442] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0924 16:12:05.378498 p2p/discover/table.go:393] seed node (age 315h5m17.37847758s): enode://de471bccee3d042261d52e9bff31458daecc406142b401d4cd848f677479f73104b9fdeb090af9583d3391b7f10cb2ba9e26865dd5fca4fcdc0fb1e3b723c786@54.94.239.50:30303
I0924 16:12:05.379128 p2p/discover/table.go:393] seed node (age 316h30m12.379111267s): enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303
I0924 16:12:05.379582 p2p/discover/table.go:393] seed node (age 315h7m22.379567105s): enode://1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d89d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082@52.74.57.123:30303
I0924 16:12:06.398736 p2p/dial.go:263] dial tcp 54.94.239.50:30303 (de471bccee3d)
I0924 16:12:06.398738 p2p/dial.go:263] dial tcp 52.16.188.185:30303 (a979fb575495)
I0924 16:12:21.375037 p2p/discover/table.go:393] seed node (age 315h5m33.375019473s): enode://de471bccee3d042261d52e9bff31458daecc406142b401d4cd848f677479f73104b9fdeb090af9583d3391b7f10cb2ba9e26865dd5fca4fcdc0fb1e3b723c786@54.94.239.50:30303
I0924 16:12:21.375160 p2p/discover/table.go:393] seed node (age 315h7m38.375149719s): enode://1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d89d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082@52.74.57.123:30303
I0924 16:12:21.375265 p2p/discover/table.go:393] seed node (age 316h30m28.375254311s): enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303
I0924 16:12:24.804280 eth/downloader/downloader.go:1442] Quality of service: rtt 20s, conf 1.000, ttl 1m0s
I0924 16:12:37.380254 p2p/discover/table.go:393] seed node (age 315h7m54.380236333s): enode://1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d89d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082@52.74.57.123:30303
I0924 16:12:37.380364 p2p/discover/table.go:393] seed node (age 316h30m44.380357883s): enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303
I0924 16:12:37.380442 p2p/discover/table.go:393] seed node (age 315h5m49.380436411s): enode://de471bccee3d042261d52e9bff31458daecc406142b401d4cd848f677479f73104b9fdeb090af9583d3391b7f10cb2ba9e26865dd5fca4fcdc0fb1e3b723c786@54.94.239.50:30303
I0924 16:12:44.804589 eth/downloader/downloader.go:1442] Quality of service: rtt 20s, conf 1.000, ttl 1m0s

**Comment by SmarticusRex** [comment]
I can confirm that deleting the contents of the aforementioned folder by zzzman20 (except the keystore) fixed the problem for me.

**Comment by Piste** [comment]
**zzzman20** unlocked me too. I was stuck in infinite peer search until I did the equivalent of this delete on Mac: I erased all things in ~/Library/Ethereum except for the **keystore** folder and the blockchain is downloading now.

**Comment by AMTQ** [comment]
unfortunately the workaround by @zzzman20 did not work for me. other suggestions?

**Comment by evertonfraga** [comment]
@AMTQ can you open a new issue describing exactly your problem? thanks!

**Comment by AMTQ** [comment]
@evertonfraga Nevermind, it had certainly something to do with the local network configuration. Now I'm on another network and it works fine. And myetherwallet works fine in the meantime ;)

**Comment by ProgrammingLife** [comment]
Same problem here. Nothing works.

**Comment by ProgrammingLife** [comment]
In my case --nat=none says:

```
←[32m[2017-07-17 04:22:07.813] [INFO] ClientBinaryManager - ←[39mChecking for new client binaries config from: https://raw.g
.json
←[32m[2017-07-17 04:22:08.496] [INFO] ClientBinaryManager - ←[39mNo "skippedNodeVersion.json" found.
←[32m[2017-07-17 04:22:08.498] [INFO] ClientBinaryManager - ←[39mInitializing...
←[32m[2017-07-17 04:22:08.498] [INFO] ClientBinaryManager - ←[39mResolving platform...
←[32m[2017-07-17 04:22:08.499] [INFO] ClientBinaryManager - ←[39mCalculating possible clients...
←[32m[2017-07-17 04:22:08.500] [INFO] ClientBinaryManager - ←[39m1 possible clients.
←[32m[2017-07-17 04:22:08.501] [INFO] ClientBinaryManager - ←[39mVerifying status of all 1 possible clients...
←[32m[2017-07-17 04:22:08.502] [INFO] ClientBinaryManager - ←[39mVerify Geth status ...
←[32m[2017-07-17 04:22:08.599] [INFO] ClientBinaryManager - ←[39mChecking for Geth sanity check ...
←[32m[2017-07-17 04:22:08.600] [INFO] ClientBinaryManager - ←[39mChecking sanity for Geth ...
←[32m[2017-07-17 04:22:08.685] [INFO] Sockets/node-ipc - ←[39mConnect to {"path":"\\\\.\\pipe\\geth.ipc"}
←[33m[2017-07-17 04:22:08.687] [WARN] Sockets/node-ipc - ←[39mConnection failed, retrying after 1000ms...
←[32m[2017-07-17 04:22:09.669] [INFO] updateChecker - ←[39mApp is up-to-date.
←[33m[2017-07-17 04:22:09.686] [WARN] Sockets/node-ipc - ←[39mConnection failed, retrying after 1000ms...
←[33m[2017-07-17 04:22:10.687] [WARN] Sockets/node-ipc - ←[39mConnection failed, retrying after 1000ms...
←[31m[2017-07-17 04:22:11.685] [ERROR] Sockets/node-ipc - ←[39mConnection failed (3000ms elapsed)
←[33m[2017-07-17 04:22:11.686] [WARN] EthereumNode - ←[39mFailed to connect to node. Maybe it's not running so let's start o
←[32m[2017-07-17 04:22:11.686] [INFO] EthereumNode - ←[39mNode type: geth
←[32m[2017-07-17 04:22:11.688] [INFO] EthereumNode - ←[39mNetwork: main
←[32m[2017-07-17 04:22:11.689] [INFO] EthereumNode - ←[39mStart node: geth main
←[32m[2017-07-17 04:22:11.690] [INFO] EthereumNode - ←[39mStart node using C:\Users\User\AppData\Roaming\Ethereum Wall
←[32m[2017-07-17 04:22:14.771] [INFO] EthereumNode - ←[39m3000ms elapsed, assuming node started up successfully
←[32m[2017-07-17 04:22:14.772] [INFO] EthereumNode - ←[39mStarted node successfully: geth main
←[32m[2017-07-17 04:22:14.774] [INFO] Sockets/node-ipc - ←[39mConnect to {"path":"\\\\.\\pipe\\geth.ipc"}
←[32m[2017-07-17 04:22:14.775] [INFO] Sockets/node-ipc - ←[39mConnected!
←[32m[2017-07-17 04:22:14.776] [INFO] NodeSync - ←[39mEthereum node connected, re-start sync
←[32m[2017-07-17 04:22:14.777] [INFO] NodeSync - ←[39mStarting sync loop
←[32m[2017-07-17 04:22:14.778] [INFO] Sockets/3 - ←[39mConnect to {"path":"\\\\.\\pipe\\geth.ipc"}
←[32m[2017-07-17 04:22:14.779] [INFO] main - ←[39mConnected via IPC to node.
←[32m[2017-07-17 04:22:14.792] [INFO] Sockets/3 - ←[39mConnected!
←[32m[2017-07-17 04:22:14.807] [INFO] (ui: splashscreen) - ←[39mNetwork is mainnet

```

what to do?

**Comment by sandeep47k** [comment]
Its a timing issue.......
Update your system time according to time.nist.gov

To update time
click on clock >  click on change date and time > click on internet time tab > Chage Setting  > select time.nist.gov from dropdown list of  server tab  > then click on update now......

It will start downloading nodes....


@ProgrammingLife @MarinAngelo

**Comment by VivinceTH** [comment]
should sync on one of below  (not just time.nist.gov)
time-a.nist.gov    129.6.15.28
time-b.nist.gov    129.6.15.29
time-c.nist.gov    129.6.15.30
time-d.nist.gov    2610:20:6F15:15::27

**Comment by zacheberhart** [comment]
I was having this same issue. But then I updated to the latest version of Ethereum Wallet (didn't work after doing just this) and then deleted everything in Ethereum folder except for the keystore (as per @zzzman20 and @Piste's instructions) and restarted the wallet. After about ten minutes it begun to sync.

**Comment by ism77** [comment]
I'm running Windows 10. zzzman20's Sept 9, 2016 posts solution worked like a charm for me as well. Thanks.

**Comment by ism77** [comment]
I am also running Kaspersky AV and also had to disable it's built in firewall and use the Windows firewall.

**Comment by andkom** [comment]
same issue (time is already synced)

**Comment by ynagarjuna1995** [comment]
**Version** : 0.9.3 
**Platform** : MAC
**Issue Resolved** : 
- SyncTime (Keep automatic time settings) somehow peers are connected based on this.
- Erased all things in ~/Library/Ethereum except for the **keystore** folder

**Comment by LouisWayne** [comment]
This is 2018 and it is still not working (using v0.10.0)

**Comment by unmisable** [comment]
windows 10 etherium wallet issue here also, if anyone can help?

**Comment by LouisWayne** [comment]
I figured out the solution:
When you sync your time with the time server, **do not close the wallet**.

**Comment by neokyol** [comment]
Still happening in v0.10.0 on OS X. The workaround is to start the node from the command line using geth.

**Comment by Libbzter** [comment]
Wallet was working fine until yesterday, now it is forever looking for peers. WTH?

**Comment by Oyshoboy** [comment]
Syncronized windows time, but still infinity "looking for peer" state:
![Image of Yaktocat](http://joxi.net/82QD0kGIjQ6eMm.jpg)

**Comment by kazoummt** [comment]
I have such a condition. And I have not figured out how to solve that problem. :(

**Comment by rpr1mera** [comment]
I was having this same issue. In my case I didn't try launching the geth node with the --nat option. I did synchronise to time.nist.gov servers, however I was still unable to find any peers, it sayed at 0 peers forever.

What did it finally for me was noticing that the option Develop -> Sync with Light client (beta) was checked by default, so I unchecked it and that fixed the problem in my case.

**Comment by LouisWayne** [comment]
FIX THIS!

**Comment by AndreiD** [comment]
like rpr1mera said...

**toggling Sync with Light client (beta) back & forth makes it find again peers.**

**Comment by rushabhmadhu2016** [comment]
admin.addPeer("enode://37bdc225f36b9bd53e155c68f266782b15e87a4db62d09bc0ee6a3b9d1bde055b10a19b21d0610c7adf419c5d7e13099bf2e8b8f1458b7c1e6930534b732d73c@74.65.200.57:1201"); admin.addPeer("enode://d9d964be91d7edc2227dfca0291b545a88f8ef4f7f236260735ba800a870b26865365c9d94cc4cd21e5a62dda8662c45cd2929126692f002bac3685ce7a57c30@108.19.163.171:30303"); admin.addPeer("enode://c60610d1700ea2842b5a3b06cc638f9c24cd77313369b04dcc2c8bb0b3b6a6d93d958f69503f76e64ab73e862421f532b7edad2283e698e602f9beb64054e1cb@37.142.103.9:59231"); admin.addPeer("enode://bb92307842ac217752aac185d7a77796a1c22ca2e9817fce65762aa2fe1a299dd805eec86073abe18e4cd0cbf4ba5cca3120a8ba906641dd60a334504e83e61c@54.79.49.179:30303"); admin.addPeer("enode://91787234ee198e612940e147f350652ffc6964956a1e4c4e6c24b2ffc2bb8681719b0762bd3ca100b98668186c9fdb16d6bb2b2438868d22d726d8fb735d5eb6@50.103.99.0:30303"); admin.addPeer("enode://6cfbf1d27fc8c65a5e622f796823cb48ab0e576bff7748de87aac0a2fb42fa388d51c9ef84bbe32ee099d8040e120282b9372f157e506dd69fc99fcfce684611@73.40.58.88:30303");

**Comment by Mongrin** [comment]
Hi guys,  Here is what fixed my problem (OS windows 7, 64 bit).

1) Update your system time according to time.nist.gov
To update time
click on clock > click on change date and time > click on internet time tab > Chage Setting > select time.nist.gov from dropdown list of server tab > then click on update now.

2) I unchecked it Develop -> Sync with Light client (beta).

3) Open the necessary ports in Firewall. In quotes my path to files is specified. You specify your.
Run cmd with administrator rules and paste this commands:

netsh advfirewall firewall add rule name="Ethereum Wallet (TCP - исходящий трафик)" dir=Out action=Allow profile=Private,Public program="C:\Users\Admin\Downloads\Ethereum-Wallet-win64-0-10-0\Ethereum Wallet.exe" protocol=TCP localport=1024-65535 remoteport=443

netsh advfirewall firewall add rule name="Geth (TCP - исходящий трафик)" dir=Out action=Allow profile=Private,Public program="C:\Users\Admin\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked\geth.exe" protocol=TCP localport=1024-65535 remoteport=any

Click Enter.

Try starting synchronization again. Hope this helps...
