### ISSUE TITLE
i cannot see my populous in my ethereum wallet

### ISSUE THREAD

**Issue by marc532** [ethereum/mist#2920]
I have bought some populous and I cannot see it in my ethereum wallet, I have checked etherscan and it is showing there so I know I have it.

I have tried adding a new watch contract in ethereum wallet for populous (ppt) using the address however I still cannot see it in my wallet.

Any help would be greatly appreciated.

``````
Version: `0.0.0`
OS & Version: windows/linux/osx
Node type: `eth/geth`
Number of blocks synchronized: 0
``````

**Comment by alexvandesande** [comment]
You need to add the Populous tokens to your watch token (not watch contract) list.

We are reviewing at old unanswered issues, sorry it took so long to reach yours, it's a long backlog.
