### ISSUE TITLE
New geth installation hangs up on block 2675000 and out of gas warning

### ISSUE THREAD

**Issue by merowland01** [ethereum/mist#2925]
I'm running the geth --fast for the first time and it runs for about 24 hours then aborts with following:
E0811 20:25:38.250618 core/blockchain.go:1170] Bad block #2675000 (0x58eff9265aedf8a54da8121de1324e1e0d9aac99f694d16c6a41afffe3817d73)
E0811 20:25:38.250618 core/blockchain.go:1171]     gas used error (1312529 / 1310649)
I0811 20:25:39.314500 eth/downloader/downloader.go:605] Peer 21c0225a00a2f95a [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 2s]: empty head header set
E0811 20:25:48.508031 core/blockchain.go:1170] Bad block #2675000 (0x58eff9265aedf8a54da8121de1324e1e0d9aac99f694d16c6a41afffe3817d73)
E0811 20:25:48.508031 core/blockchain.go:1171]     gas used error (1312529 / 1310649)
E0811 20:25:50.997195 core/blockchain.go:1170] Bad block #2675000 (0x58eff9265aedf8a54da8121de1324e1e0d9aac99f694d16c6a41afffe3817d73)
E0811 20:25:50.997195 core/blockchain.go:1171]     gas used error (1312529 / 1310649)

``````
Version: `0.0.0`
OS & Version: 'windows'
Node type: 'geth'
Number of blocks synchronized: ?
``````

**Comment by evertonfraga** [comment]
Hi @merowland01, this is a Geth issue, not Mist. For more information you can head to their repository: https://github.com/ethereum/go-ethereum

Meanwhile, just in case if you have an antivirus, try to whitelist the blockchain directory. Sometimes AVG messes with it.
