### ISSUE TITLE
LTC -> Ethereum via LRPHpZ1zN9yH6afn2oKsawhGLZNKXRv26m ?

### ISSUE THREAD

**Issue by RGMV** [ethereum/mist#2929]
According from website Ethereum i must send LTC to address:
LRPHpZ1zN9yH6afn2oKsawhGLZNKXRv26m
and then they (Ethereum) send it to my Ethereum wallet at:
0xF2b90B005268C538FD48853bAD1A80C897054E4c

But till now i never seen the money.
So Ethereum,.. did i now lost my 2.59477633 LTC ?
(Transactie-ID: 583ce3713f63a50101cc6aaf046ba284df22671b5ff7e7b254cea8679a0a2925)
4096 comfirms (at this moment, 12-8-2017)

Can Ethereum check what happend?
I like to hear from you..

**Comment by garretlaxton** [comment]
It sounds like your wallet isn't fully synchronized, you can check if you have received your ETH using https://etherscan.io

**Comment by RGMV** [comment]
Yes, transaction is oke.
Thanks for you answer!

Have a nice day.

Van: Garret Laxton 
Datum: zaterdag 12 augustus 2017 23:44
Aan: ethereum/mist 
Cc: RGMV ; Author 
Onderwerp: Re: [ethereum/mist] LTC -> Ethereum via LRPHpZ1zN9yH6afn2oKsawhGLZNKXRv26m ? (#2929)

It sounds like your wallet isn't fully synchronized, you can check if you have received your ETH using https://etherscan.io

**Comment by evertonfraga** [comment]
Closing this for now — feel free to reopen if needed!
