### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by PAND-or** [ethereum/mist#293]
1) binary from releases
2) version Ethereum-Wallet-win64-0-5-1
3) Windows 10 Home edition
4) Log
I0308 22:34:59.268318    8072 database.go:71] Alloted 433MB cache to C:\Users\Андрей\AppData\Roaming\Ethereum\chaindata

5) ![pic-20160308-223852](https://cloud.githubusercontent.com/assets/13902914/13613770/94a6c086-e57e-11e5-8363-7f7cd66a241e.png)

**Comment by darkoala** [comment]
my error says

Node type: geth
Network: main
Platform: linux

...I0308 15:51:31.932009   12117 database.go:71] Alloted 433MB cache to /home/angel/.ethereum/chaindata
I0308 15:51:31.942418   12117 database.go:71] Alloted 78MB cache to /home/angel/.ethereum/dapp
I0308 15:51:31.946498   12117 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0308 15:51:31.953437   12117 backend.go:362] Blockchain DB Version: 3
I0308 15:51:31.953784   12117 blockchain.go:214] Last header: #0 [d4e56740…] TD=17179869184
I0308 15:51:31.953806   12117 blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I0308 15:51:31.953816   12117 blockchain.go:216] Fast block: #0 [d4e56740…] TD=17179869184
I0308 15:51:31.959870   12117 cmd.go:114] Starting Geth/v1.3.5-34b622a2/linux/go1.6
I0308 15:51:31.960722   12117 server.go:311] Starting Server
Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use (possibly another instance of geth is using the same port)

also got eth and geth, and runing on wind 64bits

**Comment by i90rr** [comment]
Hi @darkoala please check #307

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
