### ISSUE TITLE
deb Packaging issue with Google Chrome and Slack

### ISSUE THREAD

**Issue by mudfly** [ethereum/mist#2930]
The deb package for ethereum wallet 9.0 wants to remove google chrome and slack client from my machine. I am running Linux Mint 18.1 but that really doesn't matter since both chrome and slack were downloaded from their respective websites and not installed through the debian repositories.

![ethereum-wallet-9 0](https://user-images.githubusercontent.com/1114761/29242578-e300513e-7f4c-11e7-9449-4f4d092dedf7.png)

**Comment by evertonfraga** [comment]
That's odd. I've noticed the first package it aims to remove is `ethereumwallet`. Are you trying to update it, or is it a first-time installation?

thanks for reporting

**Comment by mudfly** [comment]
I was trying to update ethereumwallet, but I uninstalled it manually after posting this bug report. It made no difference and the Deb package still wants to uninstall slack and chrome. My guess is a dependency on a shared library. 

I downloaded the tarball package without modifying libraries, and that runs with no issues.

**Comment by x13machine** [comment]
happened to me

**Comment by cavb** [comment]
Also happened to me, when by error I was trying to install the 32 bit version (on a 64 bit linux os). The 64 bit version installed correctly.

**Comment by evertonfraga** [comment]
I've got similar reports as this one, from people that have installed the Wallet for different architectures. 

I'm closing this. should any of you have other considerations about it, please reopen.
