### ISSUE TITLE
Not start mininig mist 0/9/0

### ISSUE THREAD

**Issue by jooboo** [ethereum/mist#2931]
Not start mining rinkeby.  Mist 0-9-0, win7-32. Unistall and install not fix.
![not start](https://user-images.githubusercontent.com/30958968/29248352-7d7b254e-8016-11e7-8898-34eb1859fe5d.png)

**Comment by evertonfraga** [comment]
Rinkeby is a Proof-of-Authority network, you don't mine on it. 

In order to get some test ether to use on it, please head to http://rinkeby.io, and click on `Crypto Faucet`.

Closing this for now, feel free to reopen.
