### ISSUE TITLE
Lost Ether from CEX.IO

### ISSUE THREAD

**Issue by CarlosBaker** [ethereum/mist#2932]
Hi guys,

I hope you can help here!

I have seen many people complaining about Etherium delays when transfer from CEX.io.

28 hours ago I withdrew my Ether from CEX to my Bitfinex wallet and it was deducted from CEX but never arrived to Bitfinex.

I have been trying to communicate with support@CEX with no replies!!!

On the other hand it is NOT showing up on https://etherscan.io

Obviously, Ether is losing it's value and I'm a trader where the time makes difference!

Appreciate your advice

**Comment by garretlaxton** [comment]
The problem isn't with the ethereum mist wallet so nobody here can help you, you're gonna have to contact CEX to solve this.

**Comment by CarlosBaker** [comment]
Thank you mate 

Ibrahim Baker 
M +905396808381
