### ISSUE TITLE
Can't Sync/ ERR File Not Found/ Uncaught invalid address

### ISSUE THREAD

**Issue by will2245** [ethereum/mist#2936]
``````
Version: `0.9.0`
OS & Version: windows 7 64 bit
Node type: geth 1.6.6
Number of blocks synchronized: All but the last 200 or so
``````

  

I can't seem to sync the last few hundred block or so with the Mist 0.9.0.  So far I have tried to the following, but these have not work:
*deleting the chaindata folder
*switching to a Solid State Hard Drive
*starting geth in command line using --fast --cache 1024 commands

I think the issue may be related to the an one of two errors that shows under the developer tools (see screen shot below) One states "Failed to load resource:: ERR File Not Found" and the other is "Uncaught Invalid Address".  

The Failed to load resource error refers to file: ///sockjs/info?cb=_qwlnok_g9

The Invalid Address error refers to file: ///C:/Program%20Files/Ethereum-Wallet-win64-0-9-0/win-unpacked/resources/app.asar/interface/wallet/3e2c5ebd8efbf7fc573dced0138d300ec5a4bff9.js

I am new to Ethereum Mist so I am not sure how to correct these errors or what I should do.  I would appreciate any help with issue.

![image](https://user-images.githubusercontent.com/30986776/29253269-25733d16-8046-11e7-8295-6f19acb8cf66.png)

**Comment by evertonfraga** [comment]
Let's isolate the problems, so we'll have a clear path to follow.

Would you install latest Geth (1.6.7) from https://geth.ethereum.org and run it in a standalone mode? Then watch if the synchronization goes through. 

Those ERR_FILE_NOT_FOUND does not pose any related problem, so ignore them.

`Uncaught: invalid address` concerns me a bit. Would you help giving more information about it?

**Comment by will2245** [comment]
I would like to help, but after posting that message, I left etheruem wallet running on my computer and it completed the initial synchronization some time later.  After the initial synchronization it appears to sync normally even after closing the program and restarting it hours later.  In the console log, I can no longer see the Uncaught Invalid Address notification.  I only see the ERR_File_Not_Found and the node start/restart notifications. So I assume the node is working correctly.

I don't think I can provide you with any more information then what I already provided, unless you want one of the log files.  If so please let me know what type of information or file you are looking for.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
