### ISSUE TITLE
Can I Erase? 

### ISSUE THREAD

**Issue by gtrider** [ethereum/mist#2943]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `9.0
new mac book pro
Node version: `geth 0.0.0` 
Number of blocks synchronized: 4M left to go 
```

I used my key store file to move my eth and erc20s to myethwallet.  Can i erase my ethereum wallet / mist now that the coins show up in myethwallet, or do i have to wait until the 4M blocks sync? 

Thank you for your help!

**Comment by evertonfraga** [comment]
MyEtherWallet by itself does not hold your keys. 

1. Make sure you have backed up the UTC files located in `Accounts > Backup > Accounts`
 (`~/Library/Ethereum/keystore` directory).
2. If you just want to free some space on your drive, you can delete your `~/Library/Ethereum/geth` directory.
3. After being 200% sure you've backed up your keys, you are good to remove Mist and Wallet
