### ISSUE TITLE
Wallet cannot download data.

### ISSUE THREAD

**Issue by nazimran** [ethereum/mist#2944]
Wallet cannot download data.

Downloading block 2,288,337 of 4,159,944 stopped

What can I do

**Comment by tomtom87** [comment]
Restart client and hope it works, I am getting exactly the same problems with this PoS

**Comment by nazimran** [comment]
thank you for the answer. I did it like you said.

**Comment by tomtom87** [comment]
@evertonfraga same problem on my client since monday now, restarting is not fixing it.

**Comment by nazimran** [comment]
I hope
Ethereum solves this problem.
big problem

**Comment by tomtom87** [comment]
@nazimran yes huge problem for my team, we are unable to deploy contract all this week.

Now I have deleted the chain data from advice in the ethereum-go repo and started resync with `geth --fast` and left it running in shell...

**Comment by evertonfraga** [comment]
Mist spawns a Geth instance, responsible for syncing with the blockchain. Please refer to their repository in order to get help directly from the source.

https://github.com/ethereum/go-ethereum
