### ISSUE TITLE
Ethereum Wallet source?

### ISSUE THREAD

**Issue by aphilsmith** [ethereum/mist#2947]
The source zip files are present for the Mist browser. Where are the source files for the Wallet?

**Comment by aunyks** [comment]
Per `main.js` in the root of the source tree (https://github.com/ethereum/mist/blob/develop/main.js), it appears that most of the locally developed source files are in the `modules` folder.

**Comment by evertonfraga** [comment]
The wallet source lives in another repo: https://github.com/ethereum/meteor-dapp-wallet
