### ISSUE TITLE
Eth token base not show up

### ISSUE THREAD

**Issue by modernduck** [ethereum/mist#2953]
Hi I have bought eth token base and try to claim it 

https://etherscan.io/address/0x109424275ffba8adf8ae752fa03d57c2380a1aa5#tokentxns

but i get 0 token on the otherhand other transaction got it token Any Idea?

**Comment by evertonfraga** [comment]
Would you please clarify your statement?

Where did you buy eth? What exactly is "eth token base"?

**Comment by tomtom87** [comment]
@modernduck  The link there is to EOS crowd sale. You must run the EOS contract and collect your tokens to your wallet. I used exodus.

**Comment by modernduck** [comment]
Hi there. it was EOS procedure that i need to do calimAll Action after 24 hrs. Sorry for super late reply
