### ISSUE TITLE
Ethereum Wallet never stops syncing (3 days still not synced!)

### ISSUE THREAD

**Issue by tomtom87** [ethereum/mist#2956]
I have been trying to sync the OSX ethereum wallet since monday, it is now Thursday. It's just 'downloading chain structure'

I am on a 100mb fibre connection. It just keeps downloading and downloading the chain. Never seems to be able to finish.

How to get this working? 

I notice many people complaining exactly the same problem here. Hard to believe this is used for finance. 

Apart from that tokens I sent on the rinkeby test net never arrived at the windows client. So I am 2 weeks into trying to use ethereum, all I have is issues and bugs.  What version should I be using to develop a contract in? 

```
Version: `0.9.0`
OS & Version: osx
Node version: `geth 1.6.6` 
Number of blocks synchronized: 4,166,981
```

**Comment by evertonfraga** [comment]
Would you please move your issue to Go-ethereum repository, as it's a Geth-specific issue?

https://github.com/ethereum/go-ethereum

**Comment by tomtom87** [comment]
@evertonfraga ok I have done that

**Comment by g2scott** [comment]
everyone here trying to supply rational answers to the plebs should shoot themselves in the head.  this is broken it will never sync, I'm a electrical engineer and I'm fucking lost.  this tech is a farce, and your all small part actors.
