### ISSUE TITLE
ETH don't sync all blocks

### ISSUE THREAD

**Issue by ProfPic** [ethereum/mist#2957]
Hey guys,

my eth wallet on my mac mini don't sync all blocks. The last 80 blocks on any transaction days, was not sync. The wallet is an failover to my wallet on my macbook pro. I like a change from my MBP to my MacMini. 

Thanks for help and sorry for my english :-)

**Comment by evertonfraga** [comment]
Can you tell precisely how many blocks have you sync so far?

Open `Developer > Developer Tools > Mist UI`, Console tab, and run: `web3.eth.blockNumber`

If it is slow at the very end of syncing, we'd recommend you to just give it a try, as it should be doing some final stuff.

Should this fail, I'd advise you to hop into the go-ethereum repository. That is the right place to get some help: https://github.com/ethereum/go-ethereum
