### ISSUE TITLE
Ethereum Wallet - Tokens are missing... 0.9.0

### ISSUE THREAD

**Issue by staticfrost** [ethereum/mist#2968]
where are my tokens gone!?

As well as all recent transactions.

**Comment by TheDarkCryptoMiner** [comment]
I also having this issue. I had PTOY tokens in a wallet contract, which previously was showing totals
and allowing me transfer them, now however, they are zero.

When looking at etherscan the token balance is there,

**Comment by tomtom87** [comment]
I'm having a issue where I cannot send tokens between wallets that are on windows to mac for example... might be unrelated but figured i'd share

**Comment by tinodj** [comment]
Same here, looks very much like #844 hits us again.

**Comment by TheDarkCryptoMiner** [comment]
Eventually the tokens showed up (even though I was sync'd) and now I get 'unknown account' when I try send eth or tokens

**Comment by tomtom87** [comment]
@TheDarkCryptoMiner I am unable to load my wallet or sync now on any network, including even a private network. I also have been sent ETH and sent my own token, both never arrived.

**Comment by staticfrost** [comment]
@evertonfraga is there anyway to see a timeline on when issues will be addressed?

Am I safe in going back to the previous version...?

**Comment by tomtom87** [comment]
Any ETA would be great, my investors are getting quiet concerned now about us not being able to sync n deploy to public mainnet

@staticfrost I tried the previous version but it wouldnt finish downloading the chain data for me on OSX

**Comment by staticfrost** [comment]
@evertonfraga Any updates be nice!.... How do we even get this labeled as a bug?

**Comment by staticfrost** [comment]
So it appears the issue is already reported - 2823

**Comment by enkidugabor** [comment]
Hello, how this site work? If I have an issue with my eth wallet how can I get help from here? Thank you.
