### ISSUE TITLE
I've  created a Contract Wallet /wo a Name - Stays greyed out /w status "creating..."

### ISSUE THREAD

**Issue by palasinio** [ethereum/mist#2974]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
No 
![eth](https://user-images.githubusercontent.com/31258581/29587969-05df6ae6-8790-11e7-8be9-dbd9ce362049.PNG)
![eth](https://user-images.githubusercontent.com/31258581/29588155-b16d6f34-8790-11e7-90ad-bd365157dcd7.PNG)

```
Version: `0.9.0`
OS & Version: windows
Node version: `geth 1.6.6` 
Number of blocks synchronized: 4,191,584
```

Hi there, as described in the subject: I accidentially added a Wallet Contract /wo naming it. The fee was charged and it seems, the transaction was successful.

![eth](https://user-images.githubusercontent.com/31258581/29588340-6dfd04de-8791-11e7-9b2e-d21cacb7cb94.PNG)

Do you have an idea?

**Comment by evertonfraga** [comment]
Hi, that behavior was fixed in 0.9.3.
