### ISSUE TITLE
Mist Browser 0.9.0 stops syncing/stuck at 99%

### ISSUE THREAD

**Issue by haroldrobbins** [ethereum/mist#2985]
I'm running Windows 10 Pro x64 and have a 50 mbps fiber connection and an SSD drive. My system clock is synced with my time zone (https://time.is).

I used 0.8.1 and 0.8.10 back in June and after downloading 99% of the blockchain data, it suddenly stopped syncing and just got stuck waiting for blocks. It has been like that for hours. I restarted the wallet app and since then the overall blockchain size has grown while downloading the blocks went slower. In the end it seems apparent that the download speed cannot keep up with the overall blockchain's growing size.  Why the app only runs in fast mode the first time it is executed and not on subsequent runs is a mystery to me. In frustration, I deleted all ethereum wallet data in my Apps folder and restarted the process all over again, with the same fucking result. These are the types of software errors that make a user go ballistic.

It's now August 25 and I'm trying 0.9.0 right now hoping that they fixed the  problems of previous versions. Nope. I'M STILL SITTING HERE WITH THE EXACT SAME ERRORS I HAD MONTHS AGO.

I hate this wallet with a vengeance. Why the Ethereum Foundation designated this as the official ETH wallet still escapes me.

[node_logs.zip](https://github.com/ethereum/mist/files/1251405/node_logs.zip)

```
Version: `0.9.0`
OS & Version: Windows 10 Pro x64 latest version
Node version: mist 0.9.0 with latest geth
Number of blocks synchronized: 4,114,499
```

**Comment by deisel16** [comment]
I have sync issues as well. I have to leave my wallet open 24/7 so it will sync. "Lately it will not".
I do not know what to do. I also went to linux version of the wallet and the exact same result. Please help me

**Comment by jrsikors** [comment]
no matter what I do and how long I leave it running, I always seem to be ~100,000 blocks behind.  I am watching my /geth/chaindata/ folder.  I can see the new ~2MB ldb files being generated almost every second.  

It doesn't make a lot of sense mathematically though.  I am 95,000 blocks behind.  If I leave it running for the next 48 hours, I will be 90,000 blocks behind.  If I just stop running my wallet for a week, i'll still only be 95,000 blocks behind.  

If the block was growing at a rate that was larger than what I could download, and I stopped sync'ing for a week .. i should be millions behind.  

The only thing that makes sense -- is that I really am sync'd .. and Mist is just way off in terms of displaying how close/far you are to being in sync.  As in -- don't trust what Mist is showing you.

I use a bat file to run Mist and Geth, and am on latest of both:
"d:\EthereumMist\mist.exe" --node-datadir=D:\EthereumData\ --gethpath "D:\EthereumGeth\Geth.exe"

**Comment by jrsikors** [comment]
my /geth/chaindata folder is 47.7 GB with 25,568 files (all LDB files).  Is that about right for being 90+%?

**Comment by jrsikors** [comment]
after leaving the computer on overnight -- my /geth/chaindata ...
Last Night: 47.7GB & 25,568 files
This morning: 48.9GB & 26,427 files

Last night I had "95,000 blocks to go" .  This morning I have "92,875 blocks to go"

**Comment by deisel16** [comment]
It should not be taking this long. I am wondering now if we need to update
the nodes, and where to do it?

**Comment by jrsikors** [comment]
does anyone know about how many files and/or what the size of a fully sync'd ethereum chain looks like in the \geth\chaindata folder?

the last one i downloaded was 1014808.ldb before i gave up trying.

**Comment by jrsikors** [comment]
So i did look at my nodes.log in my <AppData>\Roaming\Mist folder .. and compared it to the website etherscan.io

I think I can use this and monitor over the next 24 hours to determine if I'm gaining ground on the catching up to "Fully syncd" .. or if "Fully syncd" is just a dream and the best you can hope for is to always be about 100,000 blocks behind.

As long as Mist is not "Stuck", and I am moving forward, as annoying as that is, I think I'll survive.

> INFO [09-02|13:51:15] Imported new chain segment               blocks=1 txs=19  mgas=6.721  elapsed=14.74s    mgasps=0.456 number=4133602 hash=45f9b6…bf92eb
> 
> INFO [09-02|13:52:39] Imported new chain segment               blocks=2 txs=136 mgas=7.332  elapsed=1m23.475s mgasps=0.088 number=4133604 hash=d1a8e7…8eb494
> 
> INFO [09-02|13:53:29] Imported new chain segment               blocks=1 txs=50  mgas=4.909  elapsed=49.928s   mgasps=0.098 number=4133605 hash=bc1fed…074ab7
> 
> INFO [09-02|13:53:41] Imported new chain segment               blocks=1 txs=10  mgas=1.178  elapsed=12.464s   mgasps=0.095 number=4133606 hash=621137…a7f836
> 
> INFO [09-02|13:53:52] Imported new chain segment               blocks=1 txs=73  mgas=6.194  elapsed=10.846s   mgasps=0.571 number=4133607 hash=0ca639…9359de
> 
> INFO [09-02|13:54:12] Imported new chain segment               blocks=1 txs=51  mgas=4.189  elapsed=20.281s   mgasps=0.207 number=4133608 hash=74a2dd…aee17f
> 
> INFO [09-02|13:54:48] Imported new chain segment               blocks=1 txs=41  mgas=5.673  elapsed=35.132s   mgasps=0.161 number=4133609 hash=b8d321…d79e5c
> 
> INFO [09-02|13:55:02] Imported new chain segment               blocks=1 txs=67  mgas=3.471  elapsed=14.721s   mgasps=0.236 number=4133610 hash=a00a31…eeacbe
> 
> INFO [09-02|13:55:17] Imported new chain segment               blocks=1 txs=120 mgas=5.888  elapsed=14.702s   mgasps=0.400 number=4133611 hash=f15393…aac5a0
> 
> INFO [09-02|13:55:45] Imported new chain segment               blocks=2 txs=44  mgas=4.948  elapsed=28.317s   mgasps=0.175 number=4133613 hash=be69a9…99e7a9
> 
> INFO [09-02|13:56:37] Imported new chain segment               blocks=2 txs=130 mgas=7.786  elapsed=52.197s   mgasps=0.149 number=4133615 hash=9584f1…eb1d03
> 
> INFO [09-02|13:57:21] Imported new chain segment               blocks=2 txs=89  mgas=6.782  elapsed=43.627s   mgasps=0.155 number=4133617 hash=14c6b8…f28feb
> 
> INFO [09-02|13:57:43] Imported new chain segment               blocks=1 txs=46  mgas=6.683  elapsed=21.961s   mgasps=0.304 number=4133618 hash=b8ab39…94303f
> 
> INFO [09-02|13:57:55] Imported new chain segment               blocks=1 txs=77  mgas=3.007  elapsed=11.549s   mgasps=0.260 number=4133619 hash=72c348…947127
> 
> INFO [09-02|13:58:09] Imported new chain segment               blocks=4 txs=87  mgas=5.369  elapsed=14.473s   mgasps=0.371 number=4133623 hash=255d3f…119889
> 
> INFO [09-02|13:58:19] Imported new chain segment               blocks=1 txs=40  mgas=1.819  elapsed=9.923s    mgasps=0.183 number=4133624 hash=547736…999009
> 
> INFO [09-02|13:58:29] Imported new chain segment               blocks=1 txs=21  mgas=6.518  elapsed=9.898s    mgasps=0.659 number=4133625 hash=4a4d8e…f343c0
> 
> INFO [09-02|13:59:06] Imported new chain segment               blocks=1 txs=102 mgas=6.690  elapsed=36.653s   mgasps=0.183 number=4133626 hash=682d49…f279c0
> 
> INFO [09-02|13:59:19] Imported new chain segment               blocks=1 txs=94  mgas=6.613  elapsed=13.489s   mgasps=0.490 number=4133627 hash=b30e70…0cafc2
> 
> INFO [09-02|13:59:33] Imported new chain segment               blocks=2 txs=52  mgas=6.699  elapsed=13.636s   mgasps=0.491 number=4133629 hash=7a643d…d11208
> 
> INFO [09-02|13:59:52] Imported new chain segment               blocks=1 txs=66  mgas=6.545  elapsed=19.082s   mgasps=0.343 number=4133630 hash=4afa45…9b2918

**Comment by jrsikors** [comment]
after 18 hours of straight running .. I am @ block 4,137,576  .. so i downloaded 3,946 blocks in 18 hours.  However, the chain grew by 2,750 during that same time...
block at 2:00pm yesterday:  4,231,306
latest block:  4,234,056


> INFO [09-03|08:20:48] Imported new chain segment               blocks=1 txs=90  mgas=6.474  elapsed=25.713s   mgasps=0.252 number=4137574 hash=16028d…da610a
> 
> INFO [09-03|08:21:26] Imported new chain segment               blocks=1 txs=80  mgas=6.612  elapsed=38.15s    mgasps=0.173 number=4137575 hash=fc13b7…7cc4e7
> 
> INFO [09-03|08:21:36] Imported new chain segment               blocks=1 txs=42  mgas=1.503  elapsed=10.081s   mgasps=0.149 number=4137576 hash=888d85…9d413f

**Comment by remon-georgy** [comment]
Does this thing ever finisgh syncing? I mean did anybody manage to do that?

2 days ago I was 3M+ blocks behind. Yesterday I was at 90k,. Today I'm, at 2M+!!! WTF?!

**Comment by jrsikors** [comment]
after 9 more hours, i'm now at 4,139,031.   So I did another 1,455 blocks in 9 hours.  Have had 10+ peers all day, been sitting at 13 peers for a while.

Has to be more of a geth problem than a Mist problem?

My geth.exe is running with a --fast --cache 1024

> INFO [09-03|17:15:36] Imported new chain segment               blocks=2 txs=62  mgas=1.811  elapsed=9.945s    mgasps=0.182 number=4139025 hash=051d9c…ed86e7
> 
> INFO [09-03|17:15:46] Imported new chain segment               blocks=1 txs=84  mgas=3.257  elapsed=9.278s    mgasps=0.351 number=4139026 hash=8f83e9…ee9fc7
> 
> INFO [09-03|17:15:57] Imported new chain segment               blocks=1 txs=55  mgas=1.677  elapsed=11.366s   mgasps=0.148 number=4139027 hash=eaa5c5…8dcc24
> 
> INFO [09-03|17:16:34] Imported new chain segment               blocks=1 txs=160 mgas=5.088  elapsed=37.201s   mgasps=0.137 number=4139028 hash=1bfd36…6c2458
> 
> INFO [09-03|17:16:50] Imported new chain segment               blocks=2 txs=62  mgas=2.469  elapsed=15.7s     mgasps=0.157 number=4139030 hash=8ebaf5…8fc13e
> 
> INFO [09-03|17:17:05] Imported new chain segment               blocks=1 txs=77  mgas=1.716  elapsed=14.944s   mgasps=0.115 number=4139031 hash=df3c2a…4e2c50

**Comment by imar2016** [comment]
I am also having this syncing issue on 3 different PC's. All were running the previous 8.10 version with no issue. I upgraded them all and they all will never Sync as the many others have reported....ive left them on for weeks...they are still on. Can we get an official word from any Dev's acknowledging the issue and giving some indication that it might be fixed ? I have 6 other friends in the same boat, 2 others seem to be working ok. All on Windows 10 home (including 2 working), 1 on windows 10 pro (not working).

**Comment by deisel16** [comment]
I deleted my chaindata folder and started over. I am close "within 100
blocks" of it syncing.

**Comment by imar2016** [comment]
Ive tried that also. Gets stuck with 150 Blocks to go.... Other PC is too slow and the block times outpace the speed at which im downloading, the last PC just keeps getting close, then the block numbers start doing crazy things like dropping a million blocks, then going back up by some, then dropping again, up down   etc.. Let me know if you finally sync

**Comment by deisel16** [comment]
I woke up in the middle of the night to check. It wont get passed 150
blocks. Are you guys running on windows ten by any chance?

On Sep 4, 2017 1:11 PM, "imar2016" <notifications@github.com> wrote:

Ive tried that also. Gets stuck with 150 Blocks to go.... Other PC is too
slow and the block times outpace the speed at which im downloading, the
last PC just keeps getting close, then the block numbers start doing crazy
things like dropping a million blocks, then going back up by some, then
dropping again, up down etc.. Let me know if you finally sync

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/mist/issues/2985#issuecomment-327003852>, or mute
the thread

**Comment by imar2016** [comment]
Yep same issue as me and 4 other friends....150 blocks is the magic number, 150 blocks before full sync... Yes they are all running windows 10 home

**Comment by deisel16** [comment]
OK google how to run the --fast update command in CMD. I ran it and my
wallet synced with-in 20min. You will fis the issue

**Comment by imar2016** [comment]
Tried that and removed chain etc several times no change. 20 minutes? Wow never heard of a fast sync finishing in 20 mins. Mine usually take a few hours

On 6 Sep 2017, at 8:32 am, deisel16 <notifications@github.com<mailto:notifications@github.com>> wrote:

OK google how to run the --fast update command in CMD. I ran it and my
wallet synced with-in 20min. You will fis the issue

**Comment by deisel16** [comment]
The fast sync was after I deleted all the wallets and was stuck at 150
blocks for a couple days. It was the first block chain my computer thought.

**Comment by deisel16** [comment]
Idid need to change some firewall setting to allow geth to connect without
timing out. Have you tried this?

**Comment by deisel16** [comment]
Just trying to remember everything I did....

**Comment by imar2016** [comment]
I haven't tried uninstalling The wallet but I have used the removedb and manually deleted the chain an ran a --fast sync from scratch. Took me days to catch up on a 45mb link then for it to stop at 150 blocks short again. Friends have the same issue so I don't think it's my system? Btw it's a clean win 10 install with just the wallet installed. Made no diff

On 6 Sep 2017, at 8:53 am, deisel16 <notifications@github.com<mailto:notifications@github.com>> wrote:

The fast sync was after I deleted all the wallets and was stuck at 150
blocks for a couple days. It was the first block chain my computer thought.

**Comment by imar2016** [comment]
No I haven't touched any firewall settings. The 150 seems to be a magic number it refuses to pass, in. It sure if it's a timing out issue as it never times out while syncing until the 150 to go mark comes. I am willing to try anything so if you could let me know what other changes you made that would be great. Thanks again

On 6 Sep 2017, at 8:58 am, deisel16 <notifications@github.com<mailto:notifications@github.com>> wrote:

Just trying to remember everything I did....

**Comment by jrsikors** [comment]
I deleted my entire \geth\ folder ... and it flew through the first 4,000,000 blocks pretty quick.  Now I'm slowed down again trying to get the last ~100k

**Comment by deisel16** [comment]
I had comcast come out and my cable modem was throwing logs about it
timeing out. It ended up being a connection down the street. Not sure if
you use comcast or not but just a thought.

**Comment by jrsikors** [comment]
I know I have a slightly different issue than some of you .. but I did see this over at the GETH forum
https://github.com/ethereum/go-ethereum/issues/15057

**Comment by jrsikors** [comment]
So now I finally seem to have caught up after the 3rd full delete of \geth\ data folder... well caught up to you guys.  I'm 95 blocks away from being sync'd and it seems to have stopped.

However, now my ETH isn't showing up in my wallet account (yes it's the same wallet / address / keystore file) , and the ETH is showing up if i look at the address on etherscan.io.

I'm starting to believe this just a highly confusing way of getting sync'd with the blockchain.  I don't think Mist and Geth are doing a good job of explaining to common folk (And even fairly tech savvy people) what's REALLY going on and how far away % wise you really are from being sync'd.

If you read my previous post with the link to the go-ethereum forum, you will see him say that "you are supposed to download 4 million blocks super fast, then it will slow down and do a block by block import".

I think most people would just prefer to see a consistent % status.  I don't want to shoot up to 90% in 2 hours and then the last 10% will take 4 weeks.  Just balance it out and let me know how far away I really am.. because it just seems like we are "Stuck" and it's "broken".

Even though I'm "90 blocks away" .. if you actually look at your \geth\chaindata folder , i am still downloading 3x 2mb ldb files a second.  There's no way I should be downloading that much if I was really that caught up.

So again -- to sum it up -- I'm starting to wonder if the right question to be asking is "How far away are we from being fully sync'd?"

**Comment by jrsikors** [comment]
Oh just an update too .. since writing that.. i am now fully caught up.  But the "Time elapsed since last block is:  48 **YEARS** :)  .  and my ETH balance is still 0

**Comment by imar2016** [comment]
Nah im in Australia so its not a carrier issue. Plus the people affected and my other 2 PC's are all in geographically different places with different ISP's / connections. I have never had this issue before neither have my friends. My question is what in 0.9.0 has changed to start all these issues with Syncing ? Like i said the version previous, not a single problem of this nature.

**Comment by deisel16** [comment]
Since I synced up. 2 days ago. I have been downloading blocks at a slow
rate again. Cant even move my money. I am looking seriouly at a new
ethereum wallet if this dont change soon.

**Comment by wtfiwtz** [comment]
See this thread: https://github.com/ethereum/go-ethereum/issues/15001

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
