### ISSUE TITLE
Deposit on Ethereum Wallet/mist from Bittrex not recieved'/shown. 

### ISSUE THREAD

**Issue by Harkzilla** [ethereum/mist#2988]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.8.10
OS & Version: windows
Node version: `geth 1.6.6
Number of blocks synchronized: 987,212
```

**Comment by alexvandesande** [comment]
This is most likely a sync issue. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.


If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
