### ISSUE TITLE
Ether is not shown in the wallet

### ISSUE THREAD

**Issue by bsx1988** [ethereum/mist#2989]
- [Hi,
I installed Ethereum Desktop Wallet and bought some Ethereum with anycoin. They assured me, that it was dispatched and also to the correct adress I gave to them. I opened my wallet several times but after over one month there is no Ether. Unfortunately it was not yesterday, but I had some trouble.

Can you please help me?
Here some Data:
quantity: 1,60667584 ETH
coin-adress: 0xF761F2214C5F959F037F0e4611Cb926357930AF3
Tx id: 0xd6fd924cbcd084724da734f28eaf90abdf371a534c76ec93be383b5876a30d02

 ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.8.10`
OS & Version: win7 professional
Node version: `geth 0.0.0`  what does this means?
Number of blocks synchronized: 2428453 (maximum)
```

**Comment by publicocean0** [comment]
I have the same problem with changelly.com .... 
I send money to this wallet but the wallet continue to tell 0 eth. 
I tried to create a wallet contract .... it appear "creating" but it remains so ... until now.

**Comment by Kelmuppy** [comment]
same goes here from me i transferred ETH from bittrex is say the transfer is completed but untin now my ETH wallet appeared Zero any help from this?

![image](https://user-images.githubusercontent.com/31414704/29783118-ddf99ab4-8c27-11e7-8431-b003d0dc638c.png)

![image](https://user-images.githubusercontent.com/31414704/29783154-0031cdea-8c28-11e7-8310-6076c52ee5e7.png)

![image](https://user-images.githubusercontent.com/31414704/29783164-1218ed2c-8c28-11e7-83c8-3772577c91f5.png)

Blocks number already synch 
![image](https://user-images.githubusercontent.com/31414704/29783460-255f3b6a-8c29-11e7-8edf-3d43f8a47190.png)

**Comment by sicbb** [comment]
same here, wallet balance is still 0

**Comment by Harkzilla** [comment]
I have the same problem, have been waiting for a week now. My wallet is not downloading all blocks ass well.

**Comment by Kelmuppy** [comment]
what I did since I it's not showing on me mist Ether wallet , send it to my another wallet using  https://www.myetherwallet.com/

![image](https://user-images.githubusercontent.com/31414704/29875449-be86f894-8da2-11e7-87f6-6c93fb2475de.png)

**Comment by publicocean0** [comment]
thanks so much finally i solved. Anyway before to make available a software they need to make a test .

**Comment by ronaldare** [comment]
Hello , 
yeas same thing happend to me> Purchased Ether through coinbase> the option Ethereum wallet gave me> been two days says transfer complete but there is no ether in my wallet>  i checked 1000x and address is correct.. whats going on and what can i do?

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
