### ISSUE TITLE
Shifty on Mist Version 0.5.1. always stalls on "Awaiting Exchange" after deposit has been accepted

### ISSUE THREAD

**Issue by SteveLongoria** [ethereum/mist#299]
I have to run the older version of Mist (version just before 0.5.1.) to get my ETH to show up after making the purchase through Shifty on the latest version of Mist (0.5.1.). This has happened 3 times now.

Shifty deposit time limit expires, and Shifty notifies me of this expiration using a prompt. After which, it does nothing. I've waited over an hour on one attempt before closing out and just running the older version of Mist to see my ETH show up suddenly.

I'm running Linux Elementary OS Version: 0.2.1 "Luna" ( 64-bit )

**Comment by frozeman** [comment]
All shifty issues should be reported to shapeshift.io, mist has no influence on this
