### ISSUE TITLE
Ethereum Wallet will not sync

### ISSUE THREAD

**Issue by j1pvt** [ethereum/mist#2994]
[node copy.log.zip](https://github.com/ethereum/mist/files/1255393/node.copy.log.zip)

Version: `0.5.2
OS & Version: osx 10.10.5
Node version: `geth 0.0.0` 
Number of blocks synchronized: 2 527 080 out of 4 362 380

Ive had this wallet since presale
the ether I purchased reflects but the sync stage just hangs for days

![screen shot 2017-08-28 at 08 53 22](https://user-images.githubusercontent.com/31400835/29763599-19ebca96-8bd4-11e7-8e14-bba818e0477c.png)
![screen shot 2017-08-28 at 08 50 17](https://user-images.githubusercontent.com/31400835/29763601-19f5d414-8bd4-11e7-80d9-b7242303b563.png)
![screen shot 2017-08-28 at 08 50 05](https://user-images.githubusercontent.com/31400835/29763600-19f01fb0-8bd4-11e7-97b7-3a37bbb41b8f.png)
![screen shot 2017-08-26 at 11 28 16](https://user-images.githubusercontent.com/31400835/29763602-19f74312-8bd4-11e7-9956-3cce1e25928e.png)

**Comment by j1pvt** [comment]
Latest ether wallet actually shows my correct ether balance but cant even get past the peer search.
wtf etherereum ??

**Comment by AndyTrades** [comment]
Same problem, cannot get the wallet to sync. Did you resolve your issue?

**Comment by j1pvt** [comment]
Not a chance,
My recent attempts today I cant even get past 2 blocks on the download
Peer connections happens eventually
The funny thing is that my funds are there if I skip sync which is quite different to bitcoin but like I said this is a presale wallet that I purchased with bitcoin and have only looked at now.
![mist](https://user-images.githubusercontent.com/31400835/29825425-a55acf7c-8cd4-11e7-84b9-effd5a70f8dd.png)

**Comment by sicbb** [comment]
Same here ... my balance is 0

**Comment by j1pvt** [comment]
my funds are there if I skip sync
but those funds were purchased presale

**Comment by vic08** [comment]
I have the same issue, can't see my balance after reinstalling and resyncing the blockchain. I want to do some operations with my funds and contracts and I don't want to upload my private key anywhere!!! Seems like there are a lot of people with the same problem. Can anyone advice a solution?

**Comment by wtfiwtz** [comment]
Have you tried a newer version of the Ethereum Wallet? Mist is up to `v0.9.0`... maybe also consider importing your account in https://parity.io and using the light sync mode.

**Comment by vic08** [comment]
Yes I'm using the latest Mist. I want my wallet stay private, so not going to upload it anywhere. I had the problem, when I was using external HDD to store the blockchain. When I switched back to using my laptop's SSD, everything synced smoothly again. Any guesses, what can be the problem here? I would like to be able to store blockchain data on an external drive

**Comment by wtfiwtz** [comment]
@vic08 I'd imagine that its due to the intensity of the initial sync - a magnetic HDD is too slow. However, once the initial sync has finished it should be okay to use a magnetic as your data store in my opinion.

You could use a symlink to point to the external volume - just make sure the external drive is always connected or Mist will have an obscure error on startup because it can't access the blockchain files.

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Comment by j1pvt** [comment]
9.1 just crashes everytime I open it........

**Comment by AndyTrades** [comment]
@evertonfraga I am running Mist v0.9.1 and I don't see that option.
