### ISSUE TITLE
Can't move Ether from my Smart Contract back to Regular Account

### ISSUE THREAD

**Issue by JDSBali21** [ethereum/mist#2998]
Hello,

Please see the attached screen shot. I setup a smart contract wallet thinking it was just another wallet. 

I'm trying to move my Ether back to my regular account. Whenever I do that, the transaction never goes through.

I don't understand what I am doing wrong. The balance show's it is there, but when I send it to my main wallet it won't go through.

Thanks

OSX - Version 0.5.2

![ether pic](https://user-images.githubusercontent.com/30320299/29805763-e7550b72-8c48-11e7-9020-86ed5706160d.jpg)

- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx: **OSX**
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by JDSBali21** [comment]
Also here is the Etherscan address:

**Comment by joshksas11** [comment]
I can only offer about 3000. that's a lot of etherium

**Comment by JDSBali21** [comment]
Does no good if you can't access it!

**Comment by joshksas11** [comment]
try asking support you are probably over the max at least for week. would try splitting it half and selling have this week and have next week although that you over the monthly budget

**Comment by DMcgrw** [comment]
Okay I see the copy address option, send and wallet.
Do you have and external wallet linked to the ether wallet in the screen shot?

**Comment by DMcgrw** [comment]
I am not using an installed wallet, just and Address from my external wallet and it seems my ether has not reached my wallet

**Comment by JDSBali21** [comment]
I don't think it's "linked" per-say. Though I try to click the "send" link. I put in the Main Account wallet address, and send. 

Though it never goes through, it always acts as it's sending 0 coins.

**Comment by DMcgrw** [comment]
Okay, did it send or not send

**Comment by DMcgrw** [comment]
Are you using two different address's from the same wallet

**Comment by JDSBali21** [comment]
so the main account has one address, and then the smart contract wallet has another. 

I thought I was setting up a separate wallet. So I can organize my Ether. Like a little bit in my main wallet, and a then most of it in the grandkids wallet.

**Comment by DMcgrw** [comment]
Okay, do you have metamask installed

**Comment by JDSBali21** [comment]
I don't think so... I'm a bit of a noob on all this... sorry

**Comment by JDSBali21** [comment]
I am just using the standard Ethereum.org wallet... which I believe is MIST

**Comment by DMcgrw** [comment]
I have seen the wallet in the screenshot not so crazy about the interface, I found that metamask consumes less screen space and well organize and allow multiple wallet/account linking and send options

**Comment by DMcgrw** [comment]
Mist is okay, I think both wallets can cause too much confusion if you lose track of the how to send option

**Comment by JDSBali21** [comment]
Ya, I was going to move half into a ledger for offline, and the spread the rest out. I don't like the Ether.org wallet with the synch issues. 

Anyways, went to make the transfer and now can't!

**Comment by DMcgrw** [comment]
I am searching information now

**Comment by JDSBali21** [comment]
thanks!!!

**Comment by DMcgrw** [comment]
That is the case with many downloadable wallets sync is not always reliable.

**Comment by DMcgrw** [comment]
Here's my issue I created a gist using an address from external wallet only, now I am searching info pages for instructions on how to finalize the 3.0 ether transaction,

**Comment by DMcgrw** [comment]
Just thought I ask if you need any help

**Comment by JDSBali21** [comment]
thanks!

**Comment by DMcgrw** [comment]
I found a video that may be helpful.

**Comment by JDSBali21** [comment]
ok... is there a link?

**Comment by DMcgrw** [comment]
The video is titled. How to Transfer Money with Ethereum Mist Browser.

**Comment by JDSBali21** [comment]
I'll check it out, thanks

**Comment by DMcgrw** [comment]
You can type the title exactly in YouTube search.

**Comment by JDSBali21** [comment]
I'll watch it right now

**Comment by DMcgrw** [comment]
Just watched the video, its rather simple. If you are still experiencing issues after try to re-sync your wallet. Incase of any further issues there may be an issue with the sync script. There is also a video for that.

**Comment by DMcgrw** [comment]
Be careful not to make the mistake he made. Just take your time make sure you select the correct from and to account as not to pay unwanted transaction fees

**Comment by DMcgrw** [comment]
Brb

**Comment by DMcgrw** [comment]
Hello

**Comment by DMcgrw** [comment]
Have you completed your task.

**Comment by JDSBali21** [comment]
Hi...

I have to re-synch... It's probably going to take until tomorrow or the next day. 

When I get it down I will come back here and update.

Thanks

**Comment by DMcgrw** [comment]
Okay, that's a lot of confirmations for just one tranaction

**Comment by sushilraghav** [comment]
@JDSBali21 @joshksas11 @DMcgrw @evertonfraga @fjl  /// How much money you charge or Is there someone who can help me or can create a cryptocoin based on ETH Fork or BTC Fork or X11 or IOAT Fork ? Contact me at skype : sushilraghav or email is bitcoinemxmx@gmail.com.
