### ISSUE TITLE
Wallet cannot light sync

### ISSUE THREAD

**Issue by Swift42** [ethereum/mist#2999]
```
Version: `0.9.0`
OS & Version: windows/linux/osx
Node version: `geth 1.6.7` 
```

As "jtoomim" already pointed out in a comment for issue #2372:
The wallet cannot light sync since months.

The problem is that the wallet automatically calls geth with the fast sync parameter (--fast).
When I then call
ethereumwallet --node-light
then the wallet will, on the one hand, correctly use "--light" when starting geth, but it will also use "--fast"!
Using --fast AND --light conflicts and therefore geth will not be started.

Suggestion: When the wallet is called with "--node-light", don't use "--fast" when starting the geth instance.

Workaround until fixed: starting geth in advance with "--light". Then the wallet will use this geth instance and will correctly light sync.

**Comment by Swift42** [comment]
Sorry, I found out that this problem was already reported (#2254). 
This problem seems to be unfixed since 1.6.0, so please implement at least my easy solution (see above) in the next release. Thank you very much.

**Comment by HaleTom** [comment]
As a work-around for linux users, based on [@pparent76's script](https://github.com/ethereum/mist/issues/2372#issuecomment-318395351), I came up with:

```
#!/bin/bash
# Work around for issues:
# https://github.com/ethereum/mist/issues/2254
# https://github.com/ethereum/mist/issues/2372
# https://github.com/ethereum/mist/issues/2999
set -eu # For script robustness
geth=$(which geth)
mist=$(which mist) # Change to explicit path if you call this script "mist"

# Use pidof as procps' pgrep is broken:
# sleep 1& pgrep -ax '^sleep$' should return null
if ! geth_pid=$(pidof geth); then
  echo "Starting $geth."
  "$geth" --syncmode light &
else
  echo "Geth is already running with PID(s): $geth_pid"
fi

if ! mist_pid=$(pidof mist); then
  echo "Starting $mist."
  "$mist" --light-node
else
  echo "Mist is already running with PID(s): $mist_pid"
fi
```

Call the script "emist" so it doesn't recursively call itself :)

**Comment by evertonfraga** [comment]
We've enabled the Light Client on Mist 0.9.1, under `Develop` menu. 

Thanks for reporting.
