### ISSUE TITLE
Sub-module issues

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/mist#30]
Hi @frozeman!

See https://github.com/ethereum/go-ethereum/pull/1302.

I think it's related to http://stackoverflow.com/questions/4161022/git-how-to-track-untracked-content/4162672#4162672.

And is probably fixable by adding a .submodules.   I will try to make that change and construct a pull request.

You probably haven't seen it yet because all the commits are from a single author, not via forks of this master.

**Comment by bobsummerwill** [comment]
See https://github.com/ethereum/mist/pull/31.

**Comment by frozeman** [comment]
Thanks for that addition
