### ISSUE TITLE
Custom fee and limited number of transaction for contracts

### ISSUE THREAD

**Issue by yanik5** [ethereum/mist#300]
Is there a valid way to set custom re-sell fee for "custom currency", e.g. https://blog.ethereum.org/2015/12/03/how-to-build-your-own-cryptocurrency/ and limit this re-sells somehow?
For example:
1. first transaction A => B (0% custom fee, just ethereum network fee)
2. B => C (10% custom fee in ETH or preferable $ + ethereum network fee)
3. C => X -- transaction not allowed. 

I don't expect you to give me working approach, but tell if it is even possible with Ethereum.

Cheers!

**Comment by D-Nice** [comment]
Yes, but you'd have to do all that on the contract-side.

**Comment by alexvandesande** [comment]
Take a look at https://ethereum.org/token#automatic-selling-and-buying where there's an automatic sell function on your currency. You can add a sell function to the transfer function and have a custom fee.
