### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by MaroonBeret** [ethereum/mist#301]
First time started the program and crashes right away with the following info:

Node type: geth
Network: main
Platform: darwin

...60   48595 database.go:71] Alloted 433MB cache to /Users/Omer/Library/Ethereum/chaindata
I0309 12:47:17.623611   48595 database.go:71] Alloted 78MB cache to /Users/Omer/Library/Ethereum/dapp
I0309 12:47:17.626866   48595 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0309 12:47:17.626964   48595 backend.go:362] Blockchain DB Version: 3
I0309 12:47:18.193910   48595 blockchain.go:160] WARNING: Wrote default ethereum genesis block
I0309 12:47:18.194327   48595 blockchain.go:214] Last header: #0 [d4e56740…] TD=17179869184
I0309 12:47:18.194352   48595 blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I0309 12:47:18.194359   48595 blockchain.go:216] Fast block: #0 [d4e56740…] TD=17179869184
I0309 12:47:18.199881   48595 cmd.go:114] Starting Geth/v1.3.5/darwin/go1.5.1
I0309 12:47:18.200052   48595 server.go:311] Starting Server
Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use (possibly another instance of geth is using the same port)

**Comment by i90rr** [comment]
Hi @MaroonBeret please check #307

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
