### ISSUE TITLE
transactions unconfirmed \ wallet contracts pending creating \ custom tokens not updated? 

### ISSUE THREAD

**Issue by Klop89** [ethereum/mist#3012]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

Version: `0.9.0`
OS & Version: windows 10 pro
Node version: `geth 1.6.6` 
Number of blocks synchronized: 4223870

Dear all,

Thanks for helping out.

I will keep it short. See questions x.

I have tried all what is described in this wiki.

https://github.com/ethereum/mist/wiki.

Nothing that really helped. 

- Transactions remains unconfirmed, but actions succeeded as I have checked etherscan. 

- Wallet remains in creating mode...? 

- I made custom token, in which I should receive tokens from, according to etherscan, but it isn't there.

Q1: Based on above, can I conclude that my mist wallet is not syncing? 
Q2: When I start wallet, it syncs with all blocs. I assume hereafter my wallet should be updated? Why is this not? 
Q3: See screenshot. Online I cannot find how the interface v9.0.0 should look like? But this screenshot shows im not connected to any peers? (even though I did sync, see question 2).

![img_20170831_175630182](https://user-images.githubusercontent.com/31515085/29933470-01d129a0-8e78-11e7-9aaa-a8e8db24c552.jpg)

Q4: I tried the below, but it doens't work.

Windows

Open cmd.exe
Navigate to geth directory by running cd %APPDATA%\Mist\binaries\geth and look for geth.exe
Execute the following command: geth.exe --fast --cache 1024

Can someone explain me how to do this? I open cmd.exe, then I type cd %APPDATA%\Mist\binaries\geth, but nothing happens. I don't know how to read the 2nd line on navigate...cache 1024.

Q5: attached the logs. Please help me syncing this beautiful thing.

[node log.zip](https://github.com/ethereum/mist/files/1267775/node.log.zip)

Much appreciated!!

**Comment by Klop89** [comment]
![26846108-22f4fd2e-4acf-11e7-876d-8fa5e5c2d875](https://user-images.githubusercontent.com/31515085/29934281-d863c322-8e7a-11e7-99c1-359862b4ef0a.png)

Apologies, this is how it should like too, but it doesn't show up like this.

**Comment by Mwengole** [comment]
Stuck I cant create a contract, don't see my funds, transaction was done several days ago.

![image](https://user-images.githubusercontent.com/31520707/29945090-732f1aa2-8e65-11e7-9621-efd8742ae4c2.png)

I have already synced past my Block yet I don't see my ether have 600 USD in ether

Can some tell me how do I move my wallet to another wallet? thanks

**Comment by fructiv** [comment]
Same issues:
>> While adding Custom token (watch token) token name/token symbol/decimal fields are not updated automatically when the address is entered
>> Syncing gets stuck at some point and never starts back
>> Wallet contracts pending "creating"
>> Does not show the transactions and the balance of the custom tokens

**Comment by Klop89** [comment]
It surprises me that quite some people have problems. 

At the moment, I wouldn't recommend this program to anyone.

**Comment by Klop89** [comment]
It is working now. I guess network is down. Great job guys,

**Comment by donskalottle** [comment]
I am also having this issue, desperately needing some help.
