### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by incompletude** [ethereum/mist#3013]
I can't believe that a project of the size of Ethereum can't write a wallet that actually works. I have a Win10 x64 16GB HDD last mist version and the wallet doesn't sync up. Tried everything, a lot of versions. At some point it just get stuck.

That is dozens of reports everywhere of people with the same problem. Sorry guys, shitty job.

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com)

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
