### ISSUE TITLE
Awaiting Exchange

### ISSUE THREAD

**Issue by samadhiseeker** [ethereum/mist#3018]
Hi! At first application start it offered me to create an account. I choose to top up the balance using Lightcoin. 
I sent a small amount to ltc address. Deposit confirmed more than 1 day ago, but after that nothing changed. What's wrong?
![default](https://user-images.githubusercontent.com/31597908/30006352-549dc56a-90ff-11e7-83e3-1d3959369944.PNG)
![1](https://user-images.githubusercontent.com/31597908/30006353-549e3d9c-90ff-11e7-95a5-82a915f362cf.PNG)
[node_log.zip](https://github.com/ethereum/mist/files/1273217/node_log.zip)

Version: `0.9.0`
OS & Version: windows 10 x64
Node version: `geth 1.6.6` 
Number of blocks synchronized: 114,091

**Comment by JordonWHill** [comment]
Same issue for me, not a good feeling :(

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist
