### ISSUE TITLE
Haven't received my Ether!!!

### ISSUE THREAD

**Issue by jehupaulin** [ethereum/mist#302]
Just download the windows wallet and copied my main account (ETHERBASE) address. I then sent my ether from my current wallet (Ethereum Wallet by Kryptokit) to the ETHERBASE and have not recieved anything? Where is my Ether!?

**Comment by i90rr** [comment]
Could you please check again? Sometimes it could take like 3 hours to confirm the blockchain - by now you should have it in your wallet.

**Comment by jehupaulin** [comment]
Still not showing up, however my keystore file opens up with Ethereumwallet.com by Kryptokit and show the amount there. I feel a little better knowing its there but this wallet doesn't show the amount? Weird.

**Comment by alexvandesande** [comment]
The issue is that Kryptokit wallet did not send enough gas for the transaction. We've let them know and they will fix the issue on their side
