### ISSUE TITLE
I forgot the password of keystore, Can I get back it?!!! 

### ISSUE THREAD

**Issue by ben-xy** [ethereum/mist#3022]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by xy200362** [comment]
Please help me , a lot of Eth in this account.

**Comment by ncsolar** [comment]
You could give a try,  https://github.com/burjorjee/pyethrecover

**Comment by alexvandesande** [comment]
**It's not possible to recover ether without a password or change the password.** But some suggestions:

* Try using  [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com) to unlock the password and see if it's a geth/mist issue. If you can't there then it's really a password issue
* Mist never creates an account for you automatically. We do however use accounts from geth, so if you have previously installed Geth, and created an account there without thinking, that might be the one.
* If you can run python (or know someone who does) try the [Python Recovery tool](https://github.com/burjorjee/pyethrecover)
* If you can't do it yourself, you might consider hiring someone to brute force your password for you but make sure you find a reputable source. If they are able to unlock it, **they might claim all the money in it and you'll be without any legal recourse**.
