### ISSUE TITLE
Don't Run Geth at Mist Startup, Ditch Splash Screen

### ISSUE THREAD

**Issue by slate0** [ethereum/mist#3023]
I've been working for a while at getting my first sync done with Mist/geth.

From research I have done, it looks like I am not alone.

My understanding is that at launch, Mist will either execute its own version of geth with its own parameters, or attach to an existing geth node if one is already running.

The problem is, it looks like the initial sync can be a bit fiddly, and it looks like many users are using runarounds, such as changing the cache size.  Also there is full/fast/light sync mode.  My understanding is that resuming a sync with a different mode will convert your sync process to full mode.

In other cases, users pass command parameters to geth in order to change the chainblock directory.

In these cases, Mist can produce unsatisfactory results.  A user might have to throw out days of syncing if they get kicked over to full.  

Finally, when Mist is launched it automatically starts/resumes the sync process without a look at the GUI until this process.  My understanding is that the present reality is that this sync process takes a very long time for most users, until they get the initial sync done and they can keep their system up to date.

It appears that the GUI now provides all of the information from the syncing splash screen, so I do not see the point in keeping the splash and sync progress between the user and the app.

For these reasons, I propose that Mist launches directly to the GUI and that it not perform a geth sync by default.  There can be a setting added to allow geth to be run by default, and a large button provided to "start sync" with the default parameters.

**Comment by CaptJakk** [comment]
Right now it seems that Mist runs in full mode by default, with no way to change it from inside Mist. The best way I've found so far is to start geth at the command line (doesn't matter whether it's the geth that ships with Mist or one that you pulled down via your package manager), and then start Mist. This, imo, is not a user friendly solution at all for anyone who is trying to use Mist as a wallet. I think we should at least make this configurable from inside Mist.

**Comment by jrsikors** [comment]
I execute my Mist wallet with this command in a bat file:
"d:\EthereumMist\mist.exe" --node-datadir=D:\EthereumData\ --gethpath "D:\EthereumGeth\Geth.exe"

It seems to add the --fast and --cache 1024 parameters (every time I run the bat file) to my Geth if i look at my task manager command line.

I am also having crazy problems trying to sync which you can read about in the other issue posted:
https://github.com/ethereum/mist/issues/2985

I agree big time that Mist needs to be more user friendly.  I consider myself a very tech savvy person, but this is crazy complex !

**Comment by wtfiwtz** [comment]
This is due to issues with geth: https://github.com/ethereum/go-ethereum/issues/15001

I'm looking into this further...

**Comment by evertonfraga** [comment]
IMO sync should be fixed, instead of adding a "start syncing" button.

Thanks for the suggestion.
