### ISSUE TITLE
web3.eth.getAccounts does not work

### ISSUE THREAD

**Issue by mashsash** [ethereum/mist#3028]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.0`
```

I'm trying to get accounts async:

```
web3.eth.getAccounts(function(error, result) {
    if(error != null)
        console.log("Couldn't get accounts');
   console.log(result[0])
});

```

I'm getting the next error in the console:

```
app.js:5178 Uncaught TypeError: bytes.substr is not a function
SolidityType.decode @ app.js:5178(anonymous function) @ app.js:17889SolidityCoder.decodeParams @ app.js:17888SolidityFunction.unpackOutput @ app.js:41043(anonymous function) @ app.js:41071(anonymous function) @ app.js:7099(anonymous function) @ app.js:42371(anonymous function) @ VM92:665
```

UPDATE:
Okay, acutally the problem was from 
```
web3.version.getNetwork(function (error, network) {
});
```
But now when I'm trying to call

```
web3.eth.getAccounts(function(error, result) {
    if(error != null)
        console.log("Couldn't get accounts');
   console.log(result[0])
});

```

I get as a result something like: 
`console: 1
`
Or for result[1]
`console: 5`

I expected to get an account address..

**Comment by Pipeliner** [comment]
getAccounts still doesn't return accounts in 0.9.3

**Comment by Pipeliner** [comment]
It seems I needed to use "connect accounts" button appearing when I hover browser's favicon in the left pannel of Mist browser window. 
At least, that works with web3.js 1.0.0-beta28.

**Comment by alexvandesande** [comment]
```
 console.log("Couldn't get accounts');
```

You are opening it with a double quotes and closing it with a single quotes. 😉 

Tested this and it works:

```
web3.eth.getAccounts(function(err, res){ console.log(res); });
```

**Comment by ayushgupta0610** [comment]
@alexvandesande Can you please tell the version of web3 you're using? I'm trying to access my rinkeby accounts with the help of infura, but still end up getting empty array ( [] ).

**Comment by jozanza** [comment]
This still appears to be an issue in `0.10.0`:

![screen shot 2018-03-21 at 6 15 32 pm](https://user-images.githubusercontent.com/740794/37740387-e8ffdbd2-2d33-11e8-8adf-26cf371a5b6b.png)

I think this issue ought to be reopened.

**Comment by mqklin** [comment]
I connected it, but still `[]`
