### ISSUE TITLE
Not running setup Etherium wallet on Windows 7 x64!

### ISSUE THREAD

**Issue by Protey** [ethereum/mist#303]
I can not run the installation of the purse on Windows 7 x64!
nothing happens when you start the installation!
If you run the installation through the cmd.exe, here gives the following message:
C:\Ethereum-Wallet-win64-0-5-1>Ethereum-Wallet.exe
C:\Ethereum-Wallet-win64-0-5-1>CONNECT to IPC PATH: \\.\pipe\geth.ipc

Please, help!

**Comment by lookie21** [comment]
I think I am experiencing the same issue as you

**Comment by Protey** [comment]
Dear developers, the same problem with the new version 0.5.2
The program does not start!
In Task Manager can be seen that the program is started, with a description of the electron, and at once closes!
Please, help my!

**Comment by lookie21** [comment]
Instead of extracting if you press run on the Etherium wallet do you get an error ? saying node.dll is missing or something similar ?

**Comment by Protey** [comment]
> Instead of extracting if you press run on the Etherium wallet do you get an error ? saying node.dll is missing or something similar ?
any message does not jump out, as if I not launch the program

**Comment by luclu** [comment]
This works fine for me tested with 0.7.4. on win7 x64.
I will close this for now, feel free to discuss if you still encounter this issue.
