### ISSUE TITLE
Storage pointer issue

### ISSUE THREAD

**Issue by cafeespresso4** [ethereum/mist#3036]
Hi guys, I am trying to deploy this contract (the Blockchain congress) https://ethereum.org/dao#the-shareholder-association
but it throws an error every time on line 58. 

Could not compile source code.

Variable is declared as a storage pointer. Use an explicit "storage" keyword to silence this warning. 

                               string description;

**Comment by magonicolas** [comment]
Im having the same issue!

**Comment by mayukhdifferent** [comment]
having same issue

**Comment by alexvandesande** [comment]
We are reviewing at old unanswered issues, sorry it took so long to reach yours, it's a long backlog.

This issue has since been solved on the ethereum.org code
