### ISSUE TITLE
new account created via code but it is not showing in the mist browser

### ISSUE THREAD

**Issue by kannanog** [ethereum/mist#3039]
Hello everyone,

i am just using following codes to create account.

i am using ethereumjs-accounts.js and hooked-web3-provider.js

var Accounts = new Accounts();

var provider = new HookedWeb3Provider({
              host: "http://localhost:8545",
              transaction_signer: Accounts
            });
            web3.setProvider(provider);
            
            // Extend the web3 object
            Accounts.log = function(msg){console.log(msg);};
            
            console.log(Accounts.length);

           window.onload = function () {

	                // When 'Generate Account' is clicked
                $("new").onclick = function() {
                    console.log($("new_passphrase").value);
                    
                    var newAccount = Accounts.new($("new_passphrase").value);
                    $("new_result").innerHTML = JSON.stringify(newAccount, null, 2);
                };
           };

after i give some passphrase, account created, but it is not showing in the mist wallet.

what is the reason?

my task is simple i need to create several accounts from my code without going to mist wallet.

**Comment by alexvandesande** [comment]
Mist will only show the accounts on the geth node, not on external libraries. What are you trying to build exactly?
