### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by gcolbourn** [ethereum/mist#304]
Node type: geth
Network: main
Platform: darwin

...I0310 01:14:05.327651   72417 database.go:71] Alloted 433MB cache to /Users/Greg/Library/Ethereum/chaindata
I0310 01:14:05.564857   72417 backend.go:685] Old database detected, upgrading...

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
