### ISSUE TITLE
"Sorry, We are unable to locate the Transaction entry"

### ISSUE THREAD

**Issue by fintsi** [ethereum/mist#3043]
Several transaction I've done. Nothing on Etherscan. Please, help with solution!

**Comment by hollazzz** [comment]
Hi Fintsi, i have the same problem. 

i was trying to send from bittrex to mew. you too?

 i contacted the support center. and now i am waiting. 

Shall we stay in touch?

**Comment by fintsi** [comment]
Hello, yes, sure.

**Comment by hollazzz** [comment]
I still dont have it.. also still waiting for bittrex support centre. Whats your status?

Verstuurd vanaf mijn iPhone

Op 15 sep. 2017 om 09:51 heeft fintsi <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Hello, yes, sure.

**Comment by hollazzz** [comment]
Got them back. The support center found a solution. GL.
