### ISSUE TITLE
Please help! Can't succeed importing my presale wallet after many different tries.

### ISSUE THREAD

**Issue by lbg** [ethereum/mist#305]
Hey guys,

I started trying to import my presale wallet (.json file) on Windows 10 64 bit using Mist 0.5.1. After 
dragging the file and typing the password I got a window message saying “Importing…” and got stucked there for long minutes. No ‘wrong password’ messages!

Second try: Same Windows and Mist versions. Started Mist again and this time I got the same window message saying “Importing…” plus a spinning icon (indicating a kind of ‘processing”). No ‘wrong password’ messages either!

Third try: Linux Ubuntu 14.04 32 bit and Mist 0.5.1. I proceeded the same way as before and got the same results as the second try. No ‘wrong password’ messages either!

Fourth try: Windows 10 64 bit using command lines (DOS) and geth 1.3.5. I typed the following:

_geth.exe wallet import path/file.json_ and got **a very strange error message** as the attached picture:

![12829364_10153921477536192_1746291932945441010_o](https://cloud.githubusercontent.com/assets/8105455/13656796/dceea0f0-e648-11e5-9cdb-d41aa5eb151c.jpg)

I am starting to get worried about this. Mainly because this is my second presale wallet and with the first presale wallet I just tried the first step reported above and worked fine!

Also tried to import my first presale wallet using Windows command line as fourth try and it succeeded. That worries me even more!

Please support me!

One more thing: my password contains $ character (as I read somewhere here in the issues).

Cheers

**Comment by alexvandesande** [comment]
@bas-vk can you check this? Maybe we could ask @fjl or @karalabe instead?

**Comment by obscuren** [comment]
Taking a look at what could be wrong. @alexvandesande is there a known issue with `$` in the password that you are aware of?

**Comment by fjl** [comment]
The presale wallet decryption checks the password by looking at the derived address. 
This means you can get this error if the password is wrong.

**Comment by obscuren** [comment]
@fjl if there is an issue with $ signs (which I doubt) it could display a similar issue. @lbg Are you sure you're not confusing keys and mistakenly tried a wrong password?

**Comment by alexvandesande** [comment]
What is the log message for wrong password? Mist should have caught that.

**Comment by alexvandesande** [comment]
I don't think there's any issue with special characters. I've read those rumours running around but I think they are just confirmation bias because we have so many wrong password issues being filed up every day

**Comment by fjl** [comment]
There is no other log message for presale imports. (code is [here](https://github.com/ethereum/go-ethereum/blob/34b622a24853e1cf550238e8c8be6dfa4178cd35/crypto/crypto.go#L249) btw).

**Comment by fjl** [comment]
Actually there is, the other message is "Decryption failed: PKCS7Unpad failed after AES decryption".

**Comment by alexvandesande** [comment]
What's the difference between them?

**Comment by cayblood** [comment]
I think this is a real problem. @alexvandesande did you ever try out the password file I sent you on OSX?

**Comment by obscuren** [comment]
@fjl looking at the code I don't believe that second error is the error of wrong password. The `PKCS7Unpad` error is the error of a failed decryption attempt. That second error can only occur when the decryption was successful.

**Comment by frozeman** [comment]
@cayblood i just tried your presale file on OSX: 
![screen shot 2016-03-10 at 16 27 09](https://cloud.githubusercontent.com/assets/232662/13674220/f3c74c84-e6dc-11e5-8a51-d2f9b928572b.png)

works for me

**Comment by fjl** [comment]
@obscuren @alexvandesande Both checks are sanity checks to catch wrong passwords. In theory the first check for pkcs7 padding should catch most of them because it is unlikely that the result of decryption has valid padding. But it
can happen.

**Comment by cayblood** [comment]
@frozeman Strange. I had consistent failures until I used the command line.

**Comment by obscuren** [comment]
@fjl yeah you're right, it can. That second check actually makes sure the right key was derived and therefore checks the validity of the password.

**Comment by cayblood** [comment]
@frozeman Are you running the 0.5.1 release?

**Comment by frozeman** [comment]
yes

**Comment by cayblood** [comment]
@frozeman Not sure what the problem is, but after experiencing it myself, I'm convinced that many of the people posting this issue are running into something real. Many of them have claimed that they could import their presale wallet fine with geth, which leads me to believe that they are experiencing the same thing I did.

**Comment by frozeman** [comment]
Ok, thats the code of the import: https://github.com/ethereum/mist/blob/wallet/modules/ipcCommunicator.js#L63-L107

Not much to it, i run `geth wallet import file...`. I can improve the setTimout before i input something to the stdin

**Comment by obscuren** [comment]
@cayblood I don't believe your issue is similar to this. @lbg claims he can't import his wallet using the CLI either.

**Comment by cayblood** [comment]
@frozeman Could it be that somehow pasting the contents of the clipboard is not quite working right in Mist? I was using a password manager to copy my password to the clipboard and then paste it into the password field. @obscuren I'm not claiming my issue is the same as anyone in particular, but others have posted issues like mine. Sorry if I'm not posting this on the right issue.

**Comment by obscuren** [comment]
@cayblood There were issues with copy / pasting in to chromium's render window, not sure if they are still present. Could be related.

**Comment by cayblood** [comment]
@obscuren @frozeman I posted this same question (about the clipboard) on the right issue. Sorry for the confusion. Thanks for your help.

**Comment by frozeman** [comment]
@cayblood i just pasted yours and someone else presale password and it works in both accounts.
The copy and past issue is resolved.

I increase the timeout after which i write to the stdin, that may help.

**Comment by cayblood** [comment]
Thanks @frozeman. Do I need to uninstall anything to be able to test it again with the new release?

**Comment by alexvandesande** [comment]
@cayblood your issue is not related to the one on this thread, please move your discussion to another thread as you are derailing this particular issue

@lbg can you please double check your password and test some variations on it? It appears that the issue is that you got a wrong password error, but it just happens that the password you are trying triggers a rarer error log

@frozeman We caught a mist wallet bug, we need to add a catch for the second decryption error as well as the first one. Will do it later.

**Comment by cayblood** [comment]
@alexvandesande Sorry, I was just responding to @frozeman. I have already moved my discussion to the other thread.

**Comment by lbg** [comment]
Hey guys,

Thank you all for your attention and support! 

@obscuren you were right, my password was not exactly the right one, but as I got a different answer than the wrong password message ones, so I believed it was correct. After trying some variation of it then it worked! :) So relieved now!

@alexvandesande thank you for addressing and supporting the issue quite professionally.

I hope to have contributed for the bug fixes. Count on me for future tests on this issue.

Keep the good work guys!
