### ISSUE TITLE
Mist contract wallet address is not case sensitive!?

### ISSUE THREAD

**Issue by msam4444** [ethereum/mist#306]
Just created a contract wallet.  In a popup window, it said make sure you save your wallet address and had **all letters in the address in lower case**.  In the created wallet on main window, on the other hand, the contract wallet address had a mix of lower case and upper case letters as shown partially below.  It's just strange to see some letters uppercase and some lowercase.  

Both addresses apparently work just fine as I was able to transfer ETH to both formats. Identical addresses other than the second one has some letters turned into upper case!!  I thought addresses were case sensitive!

6ba2b0bfaef80742afa
6BA2B0Bfaef80742Afa

To clarify I created only one contract wallet but it was shown differently in the popup window and when listed under my wallets.

**Comment by taoteh1221** [comment]
They just implemented address checking (checksum) with that Upper/Lowercase format recently. Sending ETH seems case-insensitive in my tests, so I think they just need to update any dialogue that mentions lowercase only?

**Comment by alexvandesande** [comment]
This will be fixed on this PR: https://github.com/ethereum/meteor-dapp-wallet/pull/113

**Comment by taoteh1221** [comment]
@alexvandesande You may want to consider some type of all-lowercase alert in Mist (saying it can't verify a checksum when all lowercase formatting is entered), see this user issue typing an address _by hand_ all lowercase recently:

https://www.reddit.com/r/ethereum/comments/49x2be/lost_ether_any_ideas/

**Comment by alexvandesande** [comment]
@taoteh1221 We do have this: http://imgur.com/CgzepU5 a yellow alert when the address is not checksummed. The issue that that particular user was using a wallet version from before the checksum was implemented.

**Comment by taoteh1221** [comment]
@alexvandesande Sorry, I did not read the thread fully and see your response.

**Comment by msam4444** [comment]
Am I correct in understanding that the two addresses I mentioned above are distinct?  How was I able to send ETH to both and receive them in my wallet?

**Comment by alexvandesande** [comment]
Those are the same addresses. But if you put `6ba2b0bfaef80742afa` on the wallet it will not be able to check for any typos, while if you use `6BA2B0Bfaef80742Afa`, it will alert if a single char is out of place.
