### ISSUE TITLE
[Very low priority] Spanish translation error

### ISSUE THREAD

**Issue by ivanbalseirogarcia** [ethereum/mist#3061]
Hello, I have detected a few spanish translation errors which I will detail:

On the Ethereum wallet tab it should be Monedero Ethereum. Inside it in the submenu it says Dejar ethereum wallet, it should be: Salir del monedero ethereum.

Back to the tabs Arquivo should be Archivo. Inside Archivo there is also Upload to Swarm that it should be translated as Subir a Swarm.

In the help there is an English non translated things: Troubleshooting and Help should be Resolución de problemas y ayuda. Mist channel on Gitter should be: Canal Mist en Gitter. And finally report an issue on github should be: Informar de un problema en github.

About the functionality of the program it works perfect for me, thank you.

**Comment by alexvandesande** [comment]
We are reviewing at old unanswered issues, sorry it took so long to reach yours, it's a long backlog. Thanks for your contributions. I fixed some of these, others were already fixed. If you find any other error, feel free to correct it yourself by clicking one of these links:

* [Spanish Mist Translation](https://github.com/ethereum/meteor-dapp-wallet/edit/master/app/i18n/wallet.es.i18n.json)
* [Spanish Wallet Translation](https://github.com/ethereum/mist/edit/develop/interface/i18n/mist.es.i18n.json)
