### ISSUE TITLE
ERC20 Token Balance not showing up on Mist 0.9.0

### ISSUE THREAD

**Issue by GC2012** [ethereum/mist#3064]
Hi, 
I am running NEW Ethereum Wallet and Mist 0.9.0 (evertonfraga released this on 24 Jul )
https://github.com/ethereum/mist/releases
ERC 20 token balance is not showing up even if Watach contact is in place. 
On the other hand I can properly see ERC 20 token balance on my wallet using 
https://ethplorer.io
or
https://etherscan.io
ALL seems to be synch with the Wallet. Any thought ? 
ETH are OK, just ERC20 Token Missing

**Comment by paniccode** [comment]
same

**Comment by GC2012** [comment]
Thoughts for a FIX ? aware of anyone looking after that issue ? I can not move the coins around, nor use them. Just visible on Etherscan. Cheers

**Comment by alexvandesande** [comment]
It seems that the issue is that you are not yet fully synced. Please install the latest version of Mist and try syncing with the experimental Light Client: https://github.com/ethereum/mist/issues/3097
