### ISSUE TITLE
Eth NOT showing up

### ISSUE THREAD

**Issue by filiprashev** [ethereum/mist#3066]
About 20 h ago I made a transfer from btc-e.nz into Ethereum Wallet  and it is NOT showing up - even though it is listed on https://etherscan.io as completed. I can send you the link and a screen shot (still not sure of the security of publically sharing this info).
```
Version: `0.9.0`
OS & Version: windows 
Node version: `geth 1.6.5` 
Number of blocks synchronized: 336 555 block left 
```
hmm. I closed the Wallet and re open it it says: 425 740 blocks left??

I also dont see any peers..

Also I tryed to created a wallet contract.. but it says creating already for 20h

You'll find possible solutions for these common issues below on Mist Wiki: https://github.com/ethereum/mist/wiki.

- Ether is not shown in the wallet
- I send ether to the wallet contract but it doesn't show up
- Mist is synchronized but is stuck during the last part
- "Your computers time is out of sync!" error
- Unable to find peers
- My transaction is not confirmed
- Account can't be unlocked
- Unable to import pre-sale wallet
- Bind address already in use

**Comment by filiprashev** [comment]
hmm. I closed the Wallet and re open it it says: 425 740 blocks left??

**Comment by filiprashev** [comment]
I also dont see any peers..

**Comment by rwitchell** [comment]
your wallet will take a long time to sync with the network. allow around 40 hours to sync. Even during the time you are syncing, thousands of more transactions are being made, so once you get to the end, you'll find yourself syncing again. There is a point where you can at least open the wallet screen, and watch the sync occur at the top of the window. Once it processes the blocks with have your transaction, your wallet balance in the application will update.

**Comment by wtfiwtz** [comment]
See https://github.com/ethereum/go-ethereum/issues/15001

**Comment by Habol** [comment]
Hi there. I am from the Netherlands and have a serious problem with my Ethereum Wallet on my Mac mini with SSD. Wallet version 0.8.9. (updating the wallet as well as geth didn't solve my problems)
What is going wrong? I really hope that someone can help me. I stored 100 ether in my wallet. Another part of my problem is that I never had a JSON-file. 
Till the end of august everything was working fine. Every time the syncing was made in a few minutes till one hour when I activated the Ethereum Wallet.
From my log-file >>>
Error: invalid nonce: have 12738, expected 0
##############################
 
WARN [09-25|15:24:21] Synchronisation failed, dropping peer    peer=c5df7973471c2dc7 err="retrieved hash chain is invalid"
ERROR[09-25|15:24:29] Unhandled trie error: missing trie node ed860d5c0417624de8b47777e884d4f369e386850c13c638dd135f7bd6cc29c8 (path 040a) 
ERROR[09-25|15:24:29] Unhandled trie error: missing trie node ed860d5c0417624de8b47777e884d4f369e386850c13c638dd135f7bd6cc29c8 (path 040a) 
ERROR[09-25|15:24:29] 
########## BAD BLOCK #########
Chain config: {ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Metropolis: 9223372036854775807 Engine: ethash}

Number: 3845870
Hash: 0x768819c637d064a6dbddb5c3d31a60e79de3419357097cbb1376f96809d86e80


Error: insufficient balance to pay for gas
##############################
 
WARN [09-25|15:24:29] Synchronisation failed, dropping peer    peer=f43e8906dcdca9d4 err="retrieved hash chain is invalid"

**Comment by filiprashev** [comment]
oK, After 72h of non- stop downloading I managed to download nearly all blocks. But the last blocks are very difficult.. but the last about 120 blockss its very difficult. It does not move. I have to close the app down and restart.. But ETH still not show in the wallet?

**Comment by filiprashev** [comment]
30 blocks left. Still nothing. apperantly it is not due to the sycronisation. So what could be the issue. Anyone pls help. Thanks

**Comment by wtfiwtz** [comment]
@filiprashev keep trying to get to zero blocks outstanding, or switch a light mode client - Mist in light mode, or https://parity.io

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)

I'm closing this issue. Should you have any trouble, please refer to these channels: 

- Canonical issue regarding sync: https://github.com/ethereum/mist/issues/3097
- Gitter channel, where the community is, and can certainly help as well: https://gitter.im/ethereum/mist

**Comment by jcf16eth** [comment]
Hi, I downloaded Mist v0.9.1 and imported a wallet account (dragged the file) but the wallet account number that appears is another one I do not recognize (i don't know where that number came from). What happened here ?
Regards
