### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by craidoug** [ethereum/mist#307]
I have tried to open my ethereum wallet multiple times with no success.

I was told to copy this information:

Node type: geth
Network: main
Platform: darwin

... /Users/joeyb/Library/Ethereum/chaindata
I0309 22:07:35.440071   39661 database.go:71] Alloted 78MB cache to /Users/joeyb/Library/Ethereum/dapp
I0309 22:07:35.460251   39661 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0309 22:07:35.460532   39661 backend.go:362] Blockchain DB Version: 3
I0309 22:07:35.461802   39661 blockchain.go:214] Last header: #1125286 [a0652032…] TD=8945974313791894754
I0309 22:07:35.461832   39661 blockchain.go:215] Last block: #1125286 [a0652032…] TD=8945974313791894754
I0309 22:07:35.461848   39661 blockchain.go:216] Fast block: #1125286 [a0652032…] TD=8945974313791894754
I0309 22:07:35.462110   39661 handler.go:92] blockchain not empty, fast sync disabled
I0309 22:07:35.470082   39661 cmd.go:114] Starting Geth/v1.3.5/darwin/go1.5.1
I0309 22:07:35.470207   39661 server.go:311] Starting Server
Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use (possibly another instance of geth is using the same port)

**Comment by i90rr** [comment]
*I0309 22:07:35.470207 39661 server.go:311] Starting Server
Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use (possibly another instance of geth is using the same port)*

Seems a previous instance is already running, try killing it first like this:
```bash
$ pkill Ethereum-Wallet
```
Then try open your wallet again.

**Comment by craidoug** [comment]
where would I type that?

**Comment by i90rr** [comment]
That depends: if you're using a Unix-like OS like Linux, BSD or Mac OS X
just open a terminal and paste that.

If you're rather on Windows I believe an easy graphical way would be to
launch the Task Manager and manually kill the involved processes; I believe
this can also be done from the prompt or using powershell - but can't help
you there before researching how, it's been a while I don't touch a win...

**Comment by craidoug** [comment]
restarting my computer seemed to do the trick haha

**Comment by Amauche** [comment]
@i90rr i try to kill the process and restart it.... same problem

**Comment by Amauche** [comment]
Kill geth process and restart it. ;)
