### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by HaleTom** [ethereum/mist#3071]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `[2017-09-24 13:07:07.086] [INFO] main - 0.9.0`
OS & Version: `Linux svelte 4.9.47-1-MANJARO #1 SMP PREEMPT Sat Sep 2 07:29:38 UTC 2017 x86_64 GNU/Linux`
Node version: `instance=Geth/v1.7.0-stable-6c6c7b2a/linux-amd64/go1.9`
Number of blocks synchronized: I'm running `--light`
```

Does mist support reading default startup options from a configuration file?

[geth doesn't support configuration files](https://github.com/ethereum/go-ethereum/issues/2067), so when starting mist, I need to pass:

    --syncmode light --node-datadir "XDG_DATA_HOME/etherium"

I don't want to type this every time.

Does / could mist support a configuration file?

**Comment by evertonfraga** [comment]
This pull request enables the light client from the interface, and saves the state.

It'll be available possibly later this week.

**Comment by HaleTom** [comment]
@evertonfraga Which PR was that?

**Comment by alexvandesande** [comment]
We are reviewing at old unanswered issues, sorry it took so long to reach yours, it's a long backlog. Light client is already implemented so I'm closing this
