### ISSUE TITLE
Icos not showing in wallet

### ISSUE THREAD

**Issue by liberarbitru** [ethereum/mist#3074]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.8.10`
OS & Version: windows
Node version: `geth 0.0.0` 
Number of blocks synchronized: all minus 157
```

          Hi guys,

                    My ethers are not displayed in mist client. I syncronized all blocks. I also removed the db and resinced from command prompt, it ended succesfullay, but my ethers still not show up in console. If i use etherscan, my ethers are there. What can i do? Thank you,

Best regards,
George Nedelcu

Here is a printscreen of mist.
![image](https://user-images.githubusercontent.com/32241790/30783358-578b014c-a14a-11e7-96d4-01deed0a87c3.png)

**Comment by evertonfraga** [comment]
Hi @liberarbitru, 

can you see your account listed on the wallet?

**Comment by liberarbitru** [comment]
Hi @evertonfraga

             Yes, i see the wallet in mist. 

![image](https://user-images.githubusercontent.com/32241790/30794777-cf7de178-a1d2-11e7-8188-024cb91ee5d5.png)

        THank you,

**Comment by ronaldare** [comment]
I'm having the same issue.

**Comment by liberarbitru** [comment]
Guys, any news? Cu stima si respect,George Nedelcu 

    On Tuesday, September 26, 2017 1:23 AM, ronaldare <notifications@github.com> wrote:
 

 I'm having the same issue.—

**Comment by alexvandesande** [comment]
According to the screenshot the issue is that you are not yet synced. Please install the latest version of Mist and try syncing with the experimental Light Client: https://github.com/ethereum/mist/issues/3097
