### ISSUE TITLE
Mist does not showing created wallet

### ISSUE THREAD

**Issue by ars24pro** [ethereum/mist#3076]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
please help:
The contract is registered, the money was written off, but the Mist does not showing created wallet
Contract Address 0xD081749AC1ea771AA17b13E88251Ad32fA35a470 - 
http://disq.us/p/1mffbvf

```
Version: `0.9.0`
OS & Version: linux ubuntu 16.04 LTS
Node version: `geth v1.7.0` 
Number of blocks synchronized: 4 311 074
```
[Mist.tar.gz](https://github.com/ethereum/mist/files/1330395/Mist.tar.gz)
![1](https://user-images.githubusercontent.com/32275288/30823689-c3270ec8-a235-11e7-8902-8e98669b657c.png)

**Comment by evertonfraga** [comment]
Hi, fix is on its way.

Please refer to this link for any further discussion: #3269.
