### ISSUE TITLE
Node crashes

### ISSUE THREAD

**Issue by CryptoDJ** [ethereum/mist#308]
I got this message.  I have Ethereum in my wallet.  How do I extract my private key.  This is the error I got:

Node crashed, please create an issue in http://github.com/ethereum/mist/issues and supply the following information:

Node type: geth
Network: main
Platform: linux

...hain.go:889] imported 192 header(s) (0 ignored) in 69.836429ms. #384 [967642fd… / d3d5d5c1…]
I0310 00:31:54.429846   10102 blockchain.go:889] imported 192 header(s) (0 ignored) in 52.470115ms. #576 [bbb506ab… / 41a7466b…]
I0310 00:31:56.277398   10102 blockchain.go:889] imported 192 header(s) (0 ignored) in 53.046673ms. #768 [c4cee3bf… / 5cfe57c2…]
I0310 00:31:57.133657   10102 blockchain.go:1044] imported 33 receipt(s) (0 ignored) in 3.796445ms. #35 [3d612266… / 395005a5…]
I0310 00:31:57.362188   10102 blockchain.go:1044] imported 42 receipt(s) (0 ignored) in 5.138865ms. #77 [5f81bfa6… / 1afc0da7…]
I0310 00:31:58.185326   10102 blockchain.go:1044] imported 256 receipt(s) (0 ignored) in 50.716302ms. #333 [97564b22… / a07da7a9…]
I0310 00:31:58.226549   10102 blockchain.go:1044] imported 256 receipt(s) (0 ignored) in 39.491401ms. #589 [3c537f40… / 2919ca50…]
I0310 00:31:58.249873   10102 blockchain.go:1044] imported 175 receipt(s) (0 ignored) in 22.635145ms. #764 [4d346ba2… / 76456ff6…]

![etherbug](https://cloud.githubusercontent.com/assets/13896934/13661509/cde453ce-e658-11e5-9b67-af13f8f40845.png)

**Comment by CryptoDJ** [comment]
rebooted my Ubuntu 15.10 machine.  Ran Mist again and crashes:

...310 01:33:10.311266    2374 blockchain.go:216] Fast block: #764 [76456ff6…] TD=15821126413613
I0310 01:33:10.315444    2374 cmd.go:114] Starting Geth/v1.3.5-34b622a2/linux/go1.6
I0310 01:33:10.315587    2374 server.go:311] Starting Server
I0310 01:33:10.318197    2374 nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using NAT-PMP(192.168.1.1)
I0310 01:33:10.325522    2374 udp.go:212] Listening, enode://e17b02c79835fba239378d79806650cc24b6ae3ce6a8e10d6c9c5ba535441984bddd97a3fcbce83503633555f4d22a06bed2fe797d50a82229b62fa823a03878@174.70.116.112:30303
I0310 01:33:10.325662    2374 backend.go:526] Server started
I0310 01:33:10.325703    2374 server.go:552] Listening on [::]:30303
I0310 01:33:10.326513    2374 ipc.go:112] IPC service started (/root/.ethereum/geth.ipc)
I0310 01:33:10.328933    2374 nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using NAT-PMP(192.168.1.1)
I0310 01:33:37.217794    2374 downloader.go:288] Block synchronisation started

**Comment by musdom** [comment]
![78yfdk32](https://cloud.githubusercontent.com/assets/9629456/13663014/91a1357c-e6d9-11e5-8ef8-fd281bef494d.png)

Windows 10, using develop branch geth

**Comment by CryptoDJ** [comment]
I used shapeshift to convert Bitcoin to 1 Ether in the Mist wallet.  It crashed while doing that.  I hope I can get my 1 Ether back!

**Comment by CryptoDJ** [comment]
@musdom, are your running geth?  My geth is downloading and hope it works when finished.

**Comment by musdom** [comment]
@CryptoDJ I reverted to geth 1.3.5 that came with the wallet, and now it works again. It was stuck at "processing blocks" when I finished downloading, which was why I tried grabbing a newer geth.

**Comment by CryptoDJ** [comment]
I let the blockchain download but still get an error:

> Node type: geth
> Network: main
> Platform: linux
> 
> ...o:71] Alloted 433MB cache to /home/dev/.ethereum/chaindata
> I0310 09:57:55.696378   28842 database.go:71] Alloted 78MB cache to /home/dev/.ethereum/dapp
> I0310 09:57:55.706116   28842 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
> I0310 09:57:55.717409   28842 backend.go:362] Blockchain DB Version: 3
> I0310 09:57:55.720625   28842 blockchain.go:214] Last header: #1127223 [49ca947a…] TD=8980509772593142677
> I0310 09:57:55.720655   28842 blockchain.go:215] Last block: #1127223 [49ca947a…] TD=8980509772593142677
> I0310 09:57:55.720663   28842 blockchain.go:216] Fast block: #1127223 [49ca947a…] TD=8980509772593142677
> I0310 09:57:55.721771   28842 handler.go:92] blockchain not empty, fast sync disabled
> I0310 09:57:55.727666   28842 cmd.go:114] Starting Geth/v1.3.5-34b622a2/linux/go1.6
> I0310 09:57:55.727759   28842 server.go:311] Starting Server
> Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use (possibly another instance of geth is using the same port)

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
