### ISSUE TITLE
I send ether to the wallet contract but it doesn't show up.

### ISSUE THREAD

**Issue by avekon** [ethereum/mist#3085]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by alexvandesande** [comment]
It seems that the issue is that you are not yet synced. Please install the latest version of Mist and try syncing with the experimental Light Client: https://github.com/ethereum/mist/issues/3097
