### ISSUE TITLE
Created account on Windows 7, app closed

### ISSUE THREAD

**Issue by housemobile** [ethereum/mist#309]
Running Windows 7
Windows64 0.5.1

I created a new account. Entered the password the 2nd time. Confirmed the password, hit ok, the whole app closed.

I re-opened it and the new account is there.

**Comment by D-Nice** [comment]
I've had issues of it crashing myself, especially if I'm about to send a transaction, and then cancel it, happens about every ~10 cancels I'd say. Closes without any message.

**Comment by luclu** [comment]
Hi @housemobile, @D-Nice how is 0.7.2 behaving in this regard? Do you still have this issue?

**Comment by D-Nice** [comment]
Have not noticed these issues in 0.7.2, but haven't done the same high volume of transactions either.

**Comment by alexvandesande** [comment]
We've done many improvements since 0.5.1, app is more stable now
