### ISSUE TITLE
balance not updated in spite of sync ok and bloks ok on etherscan

### ISSUE THREAD

**Issue by stbregeon** [ethereum/mist#3091]
Etereum wallet 0.90
windows 8.1
geth 1.70
4 318 402 bloks synchronized

I made 2 transactions in  bloks 4 250 797 and 4 316 246
when I look on etherscan, my wallets and blocks are ok

I synchronise evry day my ethereum wallet, but balances doesn't updated  in spite of synchro is ok . i'm synchronizing blok 4 318 402 and my transactions are mined in blocks 4 250 797 et 4 316 246

I don't understand why my balances are not ok. they stay at 0.00

Does anyone know the problem and the solution ?

is it possible somes bloks are not synchronised on my laptop ? 
( I have already reset my sync once)

regards

**Comment by evertonfraga** [comment]
Hi, we have just launched [Mist v0.9.1](https://github.com/ethereum/mist/releases/v0.9.1), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)
