### ISSUE TITLE
Mist v0.9.0

### ISSUE THREAD

**Issue by warsameahmed** [ethereum/mist#3093]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

v0.9.0 of the Mist client does not indicate that an update is available. About Mist shows v0.9.0, however, check for updates indicates You're running the latest version.

**Comment by alexvandesande** [comment]
Has it updated already?
