### ISSUE TITLE
can't find any peers

### ISSUE THREAD

**Issue by fusenn** [ethereum/mist#310]
win64 7, no firewall or AV, been working fine, no computer reboot, just app restart, when restarted always 0 peers.

**Comment by D-Nice** [comment]
This may be a bug that is currently being looked into.

Please see https://github.com/ethereum/mist/issues/292 and try some of the recommendations there. What I'd recommend is running the geth node in the ethereum wallet folder, and using CLI arguments --fast --cache 512 on it, as mentioned in the above link.

**Comment by taoteh1221** [comment]
See above-mentioned thread:
>Solved. It was necessary to synchronize clock with "time.nist.gov" in windows time setting

https://github.com/ethereum/mist/issues/292#issuecomment-194012754

**Comment by swt83** [comment]
I can confirm that simply rebooting your computer solves this problem.

**Comment by popiahalex** [comment]
i had this problem on my os el capitan too...
