### ISSUE TITLE
Can't properly import existing contracts

### ISSUE THREAD

**Issue by tnla** [ethereum/mist#311]
I have imported existing Mist wallet (created in Mist on other PC) - https://i.imgur.com/GG4Ol9G.png

The imported Wallet shows up in Mist with the correct balance - https://i.imgur.com/JBKeLxO.png

But when I click on it, there's no interface to interact with the contract - https://i.imgur.com/oSv4gjH.png Also, clicking on "SEND" and selecting the Wallet doesn't work (clicking on the blue SEND button after entering address and amount does nothing).

Deleting the Mist data directory and reinstalling Mist didn't help.

**Windows version: Windows 8 Pro (6.2 build 9200)
Mist version: 0.5.1**

**Comment by alexvandesande** [comment]
Thanks for the report, this will be fixed on the next version.
