### ISSUE TITLE
Ether sent to my Wallet but never received.

### ISSUE THREAD

**Issue by BoredAmish** [ethereum/mist#3117]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Latest Version
Win10
IDK
Number of blocks synchronized: IDK
```

**Comment by cryptojunky** [comment]
Did you check your address / transaction on https://etherscan.io/
Your wallet may not be caught up in blocks. If it shows on etherscan and not in your wallet wait till blockchain finishes downloading.

**Comment by BoredAmish** [comment]
It finally showed up but now I've forgotten my password. I have a back-up of the keystore. Is there a way to reset my password using my email address and/or the keystore?

**Comment by cryptojunky** [comment]
There is no way to change your password without knowing your previous password. 

Backup your keystore file and application data to a thumb drive and secure it safely. 

Keep trying on your password, even if it takes hours, days, weeks. (Generally in crypto if you lose your password, you lose your coins.) Ive heard some try to brute-force attack your password for a fee. But that would be a last resort. Keep trying and for future reference always write down your password first than type it in.
