### ISSUE TITLE
impossible to launch ethereum wallet 0.9.1 since 2 days !

### ISSUE THREAD

**Issue by stbregeon** [ethereum/mist#3121]
v0.9.1 with sinc light client
geth 1.7
windows 8.1

Hello

it'is impossible tu launch ethereum wallet 0.9.1 since 2 days. 

Do you know the reason ?

I  reinstall seral time but it doesn't start.

I reinstall prévious version, ethereum vallet start but balance stay at 0.00

regards

**Comment by Proteles** [comment]
I have same issue.  Mist starts up with splash screen,.  On clean installs (minus renewing complete blockchain) Mist downloads node, downloads swarm, geth begins to catch up with current block, but whenever you click "Launch Application" the button animates, yet nothing happens.. Splash screen doesn't go away, and Application does not launch.  I've tried numerous installs all with the same effect.

**Comment by Proteles** [comment]
0.9.2 still experiencing the same problem.. why was this issue closed??
