### ISSUE TITLE
deploy a contrat with v0.9.1 ?

### ISSUE THREAD

**Issue by stbregeon** [ethereum/mist#3124]
Version: `0.9.1
windows 8.1
Node version: `geth 1.7.0` 
Number of blocks synchronized: 4 335 957
```
has anyone succeeded in deploying
a crypto currency on v0.9.1 with the tutorial? 
are there somes corrections to do ?


regards

**Comment by hellodeng** [comment]
I've created two contracts which are always in errors (pending), and never deployed

**Comment by stbregeon** [comment]
idem

**Comment by jalechu** [comment]
I've created two contracts 6 days ago and still have 0 of 12 confirmations :(

**Comment by junorouse** [comment]
Can I get your  transaction hash?

**Comment by jalechu** [comment]
Yes, here:
0x76f16d259c4f40f98df4aab0bb5fa56b0b4d28177c488277948342f520d20ec6
<http://etherscan.io/tx/0x76f16d259c4f40f98df4aab0bb5fa56b0b4d28177c488277948342f520d20ec6>

Thank you

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-04 14:11 GMT+02:00 Juno Im <notifications@github.com>:

**Comment by jalechu** [comment]
Yes, here:
0x76f16d259c4f40f98df4aab0bb5fa56b0b4d28177c488277948342f520d20ec6
<http://etherscan.io/tx/0x76f16d259c4f40f98df4aab0bb5fa56b0b4d28177c488277948342f520d20ec6>

Thank you

**Comment by pedromello** [comment]
I successfully did it in the private network, I had to change a small part of the code. I used the simpliest code and add some code from the page itself. Hope it helps. But before you read the code, look at this instructions to create a better issue request next time :)

## To help make Mist (Ethereum Wallet) better please file issue with the following basic descriptions:

- **What do you run? binary from releases or the development version from the commandline**
- **Which version do you used? You can find that in the VERSION file in the Mist folder**
- **What OS you're on?**
- **Provide a log file if necessary, you can find that in the Mist data folder (Linux: ~/.config/Mist/*.log, Windows: %APPDATA%/Roaming/Mist/*.log, MacOSX: ~/Library/Application Support/Mist/*.log)**
- **Ideally also a screenshot, if its an interface issue**

`
contract MyToken {

    event Transfer(address indexed from, address indexed to, uint256 value);
  
    /* This creates an array with all balances */
    mapping (address => uint256) public balanceOf;
    string public name;
    string public symbol;
    uint8 public decimals;

    /* Initializes contract with initial supply tokens to the creator of the contract */
    function MyToken(
        uint256 initialSupply
        ) {
        balanceOf[msg.sender] = initialSupply;              // Give the creator all initial tokens
        balanceOf[msg.sender] = initialSupply;              // Give the creator all initial tokens
        name = tokenName;                                   // Set the name for display purposes
        symbol = tokenSymbol;                               // Set the symbol for display purposes
        decimals = decimalUnits;                            // Amount of decimals for display purposes
    }

    /* Send coins */
    function transfer(address _to, uint256 _value) {
        require(balanceOf[msg.sender] >= _value);           // Check if the sender has enough
        require(balanceOf[_to] + _value >= balanceOf[_to]); // Check for overflows
        balanceOf[msg.sender] -= _value;                    // Subtract from the sender
        balanceOf[_to] += _value;                           // Add the same to the recipient
        
        /* Notify anyone listening that this transfer took place */
        Transfer(msg.sender, _to, _value);
    }
}
`

**Comment by stbregeon** [comment]
hello @pedromello 
i try your code, but the firt line (event Transfer... is not accept by ethereum 
i use v0.9.1 with beta sync ; grth 1.7.1 main network on windows 8.1

regards

**Comment by stbregeon** [comment]
hello 
i am looking for the code instruction which allow me to definie the token older in my contract  ; 
the the tutorial, when i deploy a contract, 
- i can't go to the page admin of my contract
- i can't manage the contrat
- i can't associate the contrat with my mean account

![ethereum contrat no token holder](https://user-images.githubusercontent.com/32129560/31282813-fef9a240-aab3-11e7-979c-bbda0c5870d9.PNG)

**Comment by data2** [comment]
This issue has existed both for 0.9.0 and now for 0.9.1. Basically, makes mist useless for anything but the most basic uses...

**Comment by lyons88** [comment]
I'm having trouble with contracts never being picked up, then disappearing.

Mist 0.9.1 macOS 10.12.5

node
node.log
node.log.0
node.log.1
node.log.2
node.log.3
node.log.4
