### ISSUE TITLE
Sync node slow to none

### ISSUE THREAD

**Issue by Voorr** [ethereum/mist#3138]
Most of my ethers are in a wallet contract and not in the etherbase, which I can't access through myetherwallet, if I'm correct. I would really like to access and transfer the ethers.

- Downloading blocks became slower and slower the last two months, to nearly nothing.
- I can't install the latest version of mist, because my company computer blocks it because of the swarm
- 150.000 blocks to go. 
- usually have 2-5 peers connected 

Version: `0.8.10`
OS & Version: windows
Node version: `geth 1.7.0` 
Number of blocks synchronized: 4,200.311

[Mist_Node_Log.zip](https://github.com/ethereum/mist/files/1367087/Mist_Node_Log.zip)

**Comment by evertonfraga** [comment]
Hi @Voorr, let me help you. 

You can try to start latest Mist pointing swarm to a remote url: 
`C:\Program Files\Mist\Mist.exe" --swarmurl="http://swarm-gateways.net`

Then you could make use of the Light Client, at `Develo > Sync with light client`.

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.


If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
