### ISSUE TITLE
Import Pre-sale accounts

### ISSUE THREAD

**Issue by webdvlpr** [ethereum/mist#315]
I am attempting to import ethereum_wallet_backup.json and I am receiving the Wrong Password! prompt

I have used the pyethrecover tool and it is confirming I have the correct password. 

I did create a password with spaces. Is this the issue?

OSX - Ethereum Wallet Version 0.5.1

**Comment by nithum** [comment]
I am having the same issue (Wrong Password but pyethrecover and pyethsale both say it's fine) and my password does not contain spaces. Also OSX, Ethereum Wallet Version 0.5.1.

**Comment by actuallymentor** [comment]
Same here. OSX.

**Comment by alexvandesande** [comment]
This is a known problem and we are looking into it: #182

**Comment by alexvandesande** [comment]
A clarification: it's not a password error probably. You can still import your presale with the command line tools and it will be available in the wallet

**Comment by actuallymentor** [comment]
Indeed the 'geth import wallet' does work. But the interface gave me a heart attack.

**Comment by alexvandesande** [comment]
@actuallymentor @webdvlpr @nithum could you please download the [latest Wallet release, 0.5.2](https://github.com/ethereum/mist/releases/tag/0.5.2) and tell me if the problem persists?

**Comment by actuallymentor** [comment]
Wallet is already imported (through command line).

**Comment by webdvlpr** [comment]
Same here. Already imported through command line.

**Comment by buddhanature** [comment]
I am having trouble importing my pre-sale file into my ethereum wallet. It is saying wrong password. I'm fairly confident I know the password. I am running OS 10.9.5. I am seeing that others have had problems with MACs. Have the wallet updates resolved these issues? Thanks for you help. Trying not to freak out.

**Comment by luclu** [comment]
@buddhanature please make sure you are using 0.7.2.
If you do, try the following: #436
and give me a small ping-back on the outcome.
