### ISSUE TITLE
Node crash 

### ISSUE THREAD

**Issue by mowliv** [ethereum/mist#316]
Crashing repeatedly after ubuntu upgrade to latest, and also just bought a tiny amount of ether on shapeshift, so maybe that did it? Mist is also in the midst of downloading production transitions (about 20% done).

After a reboot, the crashes stopped.

---
Node type: geth
Network: main
Platform: linux

...I0310 20:28:10.513689    7274 database.go:71] Alloted 433MB cache to /home/mowliv/.ethereum/chaindata
I0310 20:28:10.569729    7274 database.go:71] Alloted 78MB cache to /home/mowliv/.ethereum/dapp
I0310 20:28:10.612577    7274 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0310 20:28:10.613128    7274 backend.go:362] Blockchain DB Version: 3
I0310 20:28:10.614052    7274 blockchain.go:214] Last header: #280277 [616c7b49…] TD=1261523307444081154
I0310 20:28:10.618805    7274 blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I0310 20:28:10.619201    7274 blockchain.go:216] Fast block: #282180 [6e280a38…] TD=1274909414106740235
I0310 20:28:10.626718    7274 cmd.go:114] Starting Geth/v1.3.5-34b622a2/linux/go1.6
I0310 20:28:10.627152    7274 server.go:311] Starting Server

**Comment by meng89** [comment]
looks like the same:

Node type: geth
Network: main
Platform: linux

...I0311 19:07:52.890344    1192 database.go:71] Alloted 433MB cache to /home/chenmeng/.ethereum/chaindata
I0311 19:08:07.483898    1192 database.go:71] Alloted 78MB cache to /home/chenmeng/.ethereum/dapp
I0311 19:08:07.686875    1192 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0311 19:08:07.732818    1192 backend.go:362] Blockchain DB Version: 3
I0311 19:08:08.112668    1192 blockchain.go:214] Last header: #1128738 [919c9c4f…] TD=9007782758594188917
I0311 19:08:08.112696    1192 blockchain.go:215] Last block: #1128739 [f22bdf20…] TD=9007801013978460358
I0311 19:08:08.112705    1192 blockchain.go:216] Fast block: #1128738 [919c9c4f…] TD=9007782758594188917
I0311 19:08:08.482576    1192 handler.go:92] blockchain not empty, fast sync disabled
I0311 19:08:08.508168    1192 cmd.go:114] Starting Geth/v1.3.5-34b622a2/linux/go1.6
I0311 19:08:08.558381    1192 server.go:311] Starting Server

**Comment by mowliv** [comment]
Can also generate this simply by these steps:

1. Install mist
2. Take machine offline
3. Run mist -- crashes during initiation

Node type: geth
Network: main
Platform: linux

...I0313 18:57:16.510605    2135 database.go:71] Alloted 433MB cache to /home/mowliv/.ethereum/chaindata
I0313 18:57:16.754667    2135 database.go:71] Alloted 78MB cache to /home/mowliv/.ethereum/dapp
I0313 18:57:16.763003    2135 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0313 18:57:16.780340    2135 backend.go:362] Blockchain DB Version: 3
I0313 18:57:16.791856    2135 blockchain.go:214] Last header: #0 [d4e56740…] TD=17179869184
I0313 18:57:16.792212    2135 blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I0313 18:57:16.792339    2135 blockchain.go:216] Fast block: #0 [d4e56740…] TD=17179869184
I0313 18:57:16.811237    2135 cmd.go:114] Starting Geth/v1.3.5-34b622a2/linux/go1.6
I0313 18:57:16.813787    2135 server.go:311] Starting Server

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
