### ISSUE TITLE
Mist/geth hanging on the last 1% of blocks... not syncing...

### ISSUE THREAD

**Issue by wrisx** [ethereum/mist#3167]
Tried several times to sync Rinkeby... 

Just before reaching the 100%, it just stops syncing... 

Some bug in the system?

**Comment by SnoopyDogy** [comment]
I meet same issue and i have made request to create wallet for my acccount (Main Account Etherbase) but not work.

**Comment by lyons88** [comment]
I have the same issue, unless I sync to the light client, or I run geth console from the command line, and let geth sync first, then launch mist.

**Comment by jkondratowicz** [comment]
It looks like this is related to the Byzantium fork, because sync fails around block 4370000:
```
INFO [10-17|10:47:33] Imported new block headers               count=0    elapsed=2.913ms   number=4369727 hash=cd789c…198dd0 ignored=192
INFO [10-17|10:47:34] Imported new block headers               count=64   elapsed=10.743ms  number=4369919 hash=a273d7…faed8d ignored=128
WARN [10-17|10:47:35] Rolled back headers                      count=144  header=4369919->4369855 fast=0->0 block=0->0
WARN [10-17|10:47:35] Synchronisation failed, dropping peer    peer=1118980bf48b0a36 err="retrieved hash chain is invalid"
```

I'm using the latest version of the wallet (0.9.2) so I'm confused why it's broken.

**Comment by SnoopyDogy** [comment]
The size of the file chaindata is actually is 27,3 Go, what is the normal size?

**Comment by Anoxis** [comment]
@SnoopyDogy i checked size of my chain directory - 51Gb

**Comment by IvanMilev** [comment]
Hello I have the same problem. I have update to the new wallet under Mac OS X. And now my sync process stays at block 4370000 and cannot sync further. I has been like that for the past 3 days. Any suggestions?

**Comment by LAXXLA** [comment]
Hi,
same problem for me. I'm using the last version 0.9.2.. Sync stopped by 74%
I have three accounts at the moment and i see by all of them 0,00 ether!!
Although I need to have several ether.

Thanks for the advice.

**Comment by justchilling** [comment]
Stuck at 4369855
Multiple attempts on light syncmode. Normal sync might take just too many days.

**Comment by gelbwald** [comment]
I'm also stuck with syncmode=light, no warning message, though. Precisely at block 4369919.

**Comment by justchilling** [comment]
Hi 
This is happening due to the _Ethereum hard fork_. Geth has to be updated before 4370000.
Sometimes it may show ethereum as latest version but still the old geth version, I removed and updated to ethereum unstable release, tried with some issues before successfully updating to stable 1.7.2

**Comment by evertonfraga** [comment]
It seems this is due to state entries import. Give it a time (sometimes, a lot of time), and it'll eventually finish. 

You can also use the experimental Light client (Develop > Sync with the Light client), a mode that lets you use the blockchain without syncing GBs worth of data.

Should you have any other question, please reopen the issue.

**Comment by evertonfraga** [comment]
Also, update to 0.9.3
