### ISSUE TITLE
Node (wallet 0-5-1) crashed

### ISSUE THREAD

**Issue by h2002al** [ethereum/mist#317]
Hello,

This morning my wallet 0-5-1 crashed since the first minute it was opened. Bellow the screenshot of error (I have windows 10)
![eth2](https://cloud.githubusercontent.com/assets/4286283/13694234/b4aec172-e753-11e5-86db-9084c1c0e938.png)
:

![ethereum wallet crashed](https://cloud.githubusercontent.com/assets/4286283/13694215/5ef1e084-e753-11e5-8d6c-4866e8e32070.png)

Closed the initial "box" using the "x" at the up right corner of it and reopened the wallet/node in the same way (clicking the exe icon). The wallet/node was opened correctly and worked without problems for about 1 hour. Then closed regularly by me (with the mist command) because needed to go at work.

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
