### ISSUE TITLE
64bit Linux zip v0.9.2 - wrong files?

### ISSUE THREAD

**Issue by pingram3541** [ethereum/mist#3177]
- [ X ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.2`
OS & Version: linux (deb based distro)
Node version: `geth 0.0.0 - unknown` 
Number of blocks synchronized: not applicable
```
URL: https://github.com/ethereum/mist/releases/tag/v0.9.2

Upon attempting to upgrade from 0.9.1 to 0.9.2 the 64bit Linux zip appears to be a version of Mist.  When extracting and it is almost identical to the file structure of the Mist archive.  There is no ethereumwallet executable which is seen in the previous 0.9.1 zip.

Also, what are the best practices to install from zip, upgrade from zip, are we expected to simply replace the extracted folder and that's it?

**Comment by pingram3541** [comment]
Hmm, very strange.  I had tried this on a second machine, different Linux distros even and had the same result I reported above but now on both machines the checksum matches and the extracted files are in line with the previous versions structure.  I have no explanation except that I must have been hallucinating somehow.  Sorry for the false alarm.

**Comment by evertonfraga** [comment]
Regarding the false alarm: Mist and EthereumWallet projects share most of its codebase. No hallucinations going on :)

**Comment by pingram3541** [comment]
I later found it was an issue with a drive formatted NTFS on Linux not correctly showing the contents of the uncompressed archive or not extracting properly to the volume.  So yes, I was hallucinating missing files when they weren't actually missing =)
