### ISSUE TITLE
ECONNRESET during block downloading freezing downloads

### ISSUE THREAD

**Issue by mowliv** [ethereum/mist#318]
Mist stops downloading blocks after I get this console error:

NODECONNECTOR ERROR { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

Then I have to restart mist to get it to continue downloading the 1M+ blocks. Quit and restart gets it rolling again. On wifi but AFAIK not having service interruptions.

Running ubuntu 14.04.4 with some updates

**Comment by luclu** [comment]
Do you still encounter this error in version 0.7.5?
This version introduces a complete refactor of the IPC-communication an most likely solves this issue.
I will close for now, but please report back if it isn't solved for you.
