### ISSUE TITLE
Change tokens in mist and meteor-dapp-wallet

### ISSUE THREAD

**Issue by moeinzed** [ethereum/mist#3189]
I forked go-ethereum and i changed `ether` to something else. it works.
But when i changed ether to that thing in mist and meteor-dapp-wallet and run them in the Send section and balance section ether is still there. Where they come from?

**Comment by evertonfraga** [comment]
It comes from the meteor-dapp-wallet repo itself.

You can fork it also and change all the "Ether" occurrences.

**Comment by evertonfraga** [comment]
https://github.com/ethereum/meteor-dapp-wallet/search?utf8=%E2%9C%93&q=ether&type=

**Comment by moeinroid** [comment]
@evertonfraga Yes i changed all of them but they are still there.

**Comment by moeinzed** [comment]
Look at this images, i changed all ethers in mist and meteor-dapp-wallet, but these are here!
![screenshot from 2017-10-22 09-32-51](https://user-images.githubusercontent.com/32568011/31859003-8157bf78-b6f4-11e7-8a77-060464afe3be.png)
![screenshot from 2017-10-22 09-33-00](https://user-images.githubusercontent.com/32568011/31859004-81c20504-b6f4-11e7-8a1a-b4ed5ce38453.png)

**Comment by zedzodazi** [comment]
And when i build it, in `build/2a69da6959ef4ecf09ca4a2e70764b6985c391fe.js` there is this:
`o=["wei","kwei","Mwei","Gwei","szabo","finney","femtoether","picoether","nanoether","microether","milliether","nano","micro","milli","ether","grand","Mether","Gether","Tether","Pether","Eether","Zether","Yether","Nether","Dether","Vether","Uether"]`
Where they come from? there are not in mist or meteor-dapp-wallet!
