### ISSUE TITLE
Sync seems in a broke state.

### ISSUE THREAD

**Issue by 14lox** [ethereum/mist#319]
Using OSX client for the first time, it syncs all but a few of the 1M+ blocks. Then stops. No issue with network here. It still says 25 peers. 
The `chaindata` folder contains 520 `ldb` files. It also cotains `CURRENT`, an empty `LOCK`, `LOG`, `LOG.old` and a `MANIFEST` file. 
I restarted the app and after searching for peers is now stuck here for 20 mins + 
<img width="512" alt="screen shot 2016-03-11 at 01 22 45" src="https://cloud.githubusercontent.com/assets/1490398/13698272/dae21c12-e727-11e5-91b7-f7c3bc321410.png">
How can i kick it back into working?

**Comment by frozeman** [comment]
Try syncing your computers time, as mist uses this to determine whether your on the latest block or not.

**Comment by 14lox** [comment]
Left it on overnight. It synced without any action.
