### ISSUE TITLE
2 ethereum have not been sent to my wallet from etherminer. got both confirmations that they have been send to my mist etheruem wallet, but no sign of my ethereum!!!!!!

### ISSUE THREAD

**Issue by kevin2121** [ethereum/mist#3202]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
2 ethereum have not been sent to my wallet from etherminer. got both confirmations that they have been send to my mist etheruem wallet, but no sign of my ethereum!!!!!!

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by achempion** [comment]
Have you checked it on some of an ethereum blockchain browsing websites? Is transaction exists? Is your account balance right?

**Comment by alexvandesande** [comment]
This was likely a sync issue. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.


If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
