### ISSUE TITLE
Cannot send any ETH or tokens from etherbase account, but other accounts work fine. 

### ISSUE THREAD

**Issue by kieranstolorz** [ethereum/mist#3205]
```
Version: `0.9.2`
OS & Version: osx Sierra
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4,424,668
```

My node is able to sync, and I am able to send tokens and ETH to and from multiple accounts on my ethereum wallet - all of them except for my etherbase account. When I try to send any tokens or ETH from my etherbase account, it shows up in my log at the bottom but stays on 0/12 confirmations without ever advancing and then I get the message "ethereum node transaction couldnt be successfully executed" about 5-10 minutes later. This problem has persisted for 3 days now.

I have tried sending with the maximum amount of gas and still no success - any ideas?

Thanks!

**Comment by osolow** [comment]
Following your post I'm having the same exact issue...

**Comment by kieranstolorz** [comment]
Thanks so much! This works perfectly.
