### ISSUE TITLE
Will pay Ether if you can fix this.

### ISSUE THREAD

**Issue by Hsmyth1998** [ethereum/mist#3207]
I recently transferred my ethereum wallet to my "D' drive from my "C" drive as per the "IMineBlocks" youtube tutorial found here>>"https://www.youtube.com/watch?v=1fHeUUbWthI&t=284s". After this my ethereum wallet was syncing EXTREMELY slowly (only about 100 blocks and hour). So I deleted my chain data folder and it began to quick sync however it only gets to within 70-200 blocks of being completed and then stops.

When I Launched application it slowed my 8.9 ether in the account and then I minimised it  for about 20 minutes and when I clicked back into it my ether was gone and the wallet is still yet to sync....

I do have a copy of my keystores.

I WILL PAY a portion of my ether to someone how solves this and walks me through it.

**Comment by HomeOfSourceCode** [comment]
try this, is working for me:

Delete folder content of %appdata%\Ethereum\geth\
run "%appdata%\Ethereum Wallet\binaries\Geth\unpacked" geth --syncmode=light
wait until synched and let it run

Start wallet

**Comment by achempion** [comment]
Have you tried light mode? Update Mist, remove all your chain data and run it with the lightmode option. I'll get to full sync with less than 5 hours.

**Comment by marcgarreau** [comment]
As mentioned, please try syncing with light mode. (In the menu, Develop > Sync with Light client (beta).) Reopen the issue if you're still having trouble.
