### ISSUE TITLE
Unable to create Wallet contract

### ISSUE THREAD

**Issue by dvoretsa** [ethereum/mist#3220]
![error](https://user-images.githubusercontent.com/33178767/32134923-5dc485ea-bbff-11e7-94bd-ecef4b9451ea.jpg)

Hi!

I downloaded and started Ethereum wallet 0.9.2. I've wait for full blockchein sync. I've create additional account and transfered 1,04 ether to it. After that I've push the button "Add wallet contract" because I need to see all transaction details. I've enter the password of account and push the button "send transaction". After that I see only message "Creating" and my balance has lower for 0.01 ether. But nothing happens. I restarted the wallet and the comp but nothing changes.

Screenshot and logs attached

What is the problem?

Regards,
Andrey.

```
Version: `0.9.2`
OS & Version: Windows 10 Enterprise
Node version: `geth 0.0.0` 
Number of blocks synchronized: 4445745
```
[logs.zip](https://github.com/ethereum/mist/files/1424282/logs.zip)

**Comment by jontis** [comment]
I have this too, on linux ubuntu 16.10
geth 1.7.2

I also have this if they are related:
https://github.com/ethereum/mist/issues/3222
[https://github.com/ethereum/mist/issues/3222](url)

**Comment by jenniferdejonge** [comment]
Andrey,
I have the same problem.
did you find a way to solve it?

**Comment by dvoretsa** [comment]
Hi!

Yes, I have solved the issue. Here is descibed how:
https://github.com/ethereum/mist/issues/2845

Open:
Develop -> Toggle developer tools -> Ethereum Wallet

In the console:
Wallets.find().fetch()
Wallets.remove("_id")

Regards,

Andrey.



2017-11-03 11:45 GMT+03:00 jenniferdejonge <notifications@github.com>:

**Comment by evertonfraga** [comment]
Hi all, fix is on its way.

Please refer to this link for any further discussion: #3269.
