### ISSUE TITLE
ERC20 tokens wont show up 

### ISSUE THREAD

**Issue by kiahmed** [ethereum/mist#3221]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.2` (eth wallet)
OS & Version: windows 2012 R2
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4446251
```

I have 5k ERC20 token (TNT) on this address 0xb0156f46f85353Ba51E43A34B1908cAAddB9d297 but wallet dont show it even though I added the right contract for the token. MyEtherWallet does , but I dont  wanna use it every time. Any idea?

**Comment by achempion** [comment]
Have you added the token to mist via "Watch token" function?

**Comment by solutionjet** [comment]
yes i did

**Comment by mkmathur08** [comment]
Hello All I am facing the same problem with this wallet. It is not showing tokens. Also "View on Etherscan" button is also not working. how to see the token received on my address. on etherscan it is showing the tokens but in wallet it is not showing up please help.

**Comment by dcnl1980** [comment]
Same here. On metamask the tokens are there. Also if you make a wallet contract it's not working. I use the latest geth.

**Comment by solutionjet** [comment]
we need a resolution for this . After all this time and funding ethereum wallet still hasn't improved much. We should be able to add any ERC token and see its balance. I dont want to extract my private key every time and upload to MyEtherWallet. Hows that convenient and safe?

**Comment by UGatgithub** [comment]
Same issue with the Wallet - if I add the contracts in Mist the tokens show up and Mist stores the contracts I added, Ethereum Wallet does not store them.

**Comment by Tyntesfield** [comment]
I have this issue too, on Mac. Reinstalled the Ethereum wallet from scratch to get the light sync feature on Geth 1.8.1 and now I can't see the tokens. Deleted the token contracts and added them again. No joy. Something is amiss.

**Comment by jontis** [comment]
Me too, 
geth 1.8.1
mist 0.9.3

Added custom tokens that show up with correct name but not their amount in the wallet.

ERC20 Contract: | 0x9e88613418cf03dca54d6a2cf6ad934a78c7a17a

**Comment by disasterovich** [comment]
Same problem
version 0.9.3

I add a token, but the balance is zero in mist wallet. 
etherscan.io show non zero balance

**Comment by cuteca812** [comment]
Same problem
version 0.9.3
ERC20 Contract:  0x7f61C888BB603F22A941b314234ca2d9eEda2bFB

I add a token, but the balance is zero in mist wallet.
etherscan.io show non zero balance

**Comment by Tyntesfield** [comment]
I have a solution to this problem - at least on a Mac in the Ethereum wallet.
Let the wallet sync (I use the Light Client Beta), then go to the Develop menu and switch it to the Ropsten test network. Let it sync again. Then quit the wallet. Reopen it, re-sync on the main net and see if the tokens show up. I had to do this twice before it worked but it all looks good now.

**Comment by cuteca812** [comment]
@Tyntesfield 
my issue is solved.  thanks for your guide.

**Comment by fishmc** [comment]
Added custom tokens that show up with correct but not their name, amount in the wallet.I can get the accounts list.(on ethereum)

**Comment by fishmc** [comment]
success show up on infura,but in geth (on main ethereum )

**Comment by marcgarreau** [comment]
Responded to your new issue, @fishmc. Closing this one due to inactivity (please reopen new issues if appropriate). In general, your wallet will only show accurate balances after your node is fully synced. This should be a better user experience with the more recent feature additions to Mist.
