### ISSUE TITLE
Failing Sync

### ISSUE THREAD

**Issue by benue505** [ethereum/mist#3228]
Version: `0.9.2`
OS & Version: windows 8.1
Node version: `geth 1.6.6` 
Number of blocks synchronized: 0

![image](https://user-images.githubusercontent.com/33226581/32176567-f574ee58-bd7f-11e7-8157-73e2f57e0e5b.png)
![image](https://user-images.githubusercontent.com/33226581/32176613-1d83e19c-bd80-11e7-8075-e256b52744e7.png)

My ethereum node has not once fully complete sync, it just remains irresponsive for hours un-end, i have left it overnight on some occasions and found that the systems has rebooted itself sometime during the night. I also sent some eth  to my wallet and that has just not appeared. I have tried to run the geth manually on the command line (see screenshots above) that seem to work, however, does that mean I have run the process manually each time before running in GUI mode?? Please advise.

**Comment by marcgarreau** [comment]
- Re: ETH not appearing in the wallet - the node needs to be fully synced to see the funds in your wallet.
- Running geth from the command line is a fine option. Have you tried the light client mode, though? From the Mist menu, select Develop > Sync with Light client (beta). (Light mode can also be used via the command line with the `--syncmode=light` flag.) Sometimes the light mode can take a little while to find peers.

Please reopen the issue if you still have trouble.

**Comment by benue505** [comment]
I have tried all the options listed still no joy. I gave up eventually.
    On Monday, November 13, 2017, 4:07:53 PM GMT, Marc Garreau <notifications@github.com> wrote:  
 
    
   - Re: ETH not appearing in the wallet - the node needs to be fully synced to see the funds in your wallet.
   - Running geth from the command line is a fine option. Have you tried the light client mode, though? From the Mist menu, select Develop > Sync with Light client (beta). (Light mode can also be used via the command line with the --syncmode=light flag.) Sometimes the light mode can take a little while to find peers.

Please reopen the issue if you still have trouble.
