### ISSUE TITLE
ERC20 tokens wont show up "View on Etherscan" not working Also Wallet contract is showing creating from almost 15 days" not able to delete 2nd account.

### ISSUE THREAD

**Issue by mkmathur08** [ethereum/mist#3229]
ERC20 tokens wont show up

Version: `0.9.2` (eth wallet)
OS & Version: windows 10 enterprise
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4458924
I have 	2,500 EXMR and 73,302,470 EDOGE ERC20 token (EXMR/EDOGE) on this address 0x972D09fe0104840898834ac5dAb50C2b0f4139A7 but wallet dont shows it even though I added the right contract for the token.

Also I have added a new account by mistake and trying to delete it but there is no option to delete.

View on Etherscan" not working option is not working

Wallet contract is showing creating from almost 15 days and doing nothing. 

Request you to please help.

**Comment by mitch8128** [comment]
im having the same issue

**Comment by nicksavers** [comment]
Duplicate of https://github.com/ethereum/mist/issues/3230

**Comment by mkmathur08** [comment]
closing because issue is open using id #3230
