### ISSUE TITLE
ERC20 tokens wont show up "View on Etherscan" not working Also Wallet contract is showing creating from almost 15 days" not able to delete 2nd account.

### ISSUE THREAD

**Issue by mkmathur08** [ethereum/mist#3230]
Version: `0.9.2` (eth wallet)
OS & Version: windows 10 enterprise
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4458924
I have 	2,500 EXMR and 73,302,470 EDOGE ERC20 token (EXMR/EDOGE) on this address 0x972D09fe0104840898834ac5dAb50C2b0f4139A7 but wallet dont shows it even though I added the right contract for the token.

Also I have added a new account by mistake and trying to delete it but there is no option to delete.

View on Etherscan" not working option is not working

Wallet contract is showing creating from almost 15 days and doing nothing. 

Request you to please help.
[ETH Issue.docx](https://github.com/ethereum/mist/files/1428079/ETH.Issue.docx)

**Comment by mkmathur08** [comment]
Any help on this issue ?

**Comment by nicksavers** [comment]
You can remove keys from the keys directory in `%APPDATA%/Ethereum`
See: https://ethereum.stackexchange.com/a/109

**Comment by mkmathur08** [comment]
@nicksavers the link shows up the backup process ... but my problem is it is not showing ERC20 tokens after adding up but when i check on etherscan.io i can see tokens are there on my address. Along with other two problem I am facing wallet contract keep showing  creation of something i dont know what is that. 3rd one is whenever i click on "View on Etherscan" i wont work.

I shared an attachement for ref. please help

**Comment by mkmathur08** [comment]
@@nicksavers Thank you .... Default account created by mistake issue I resolved after going through the link you have shared. Thanks again.  Now Left with the issues but my problem is it is not showing ERC20 tokens after adding up but when i check on etherscan.io i can see tokens are there on my address. Along with other two problem I am facing wallet contract keep showing creation of something i dont know what is that. 3rd one is whenever i click on "View on Etherscan" i wont work.

**Comment by nicksavers** [comment]
> even though I added the right contract for the token

@mkmathur08 Did you add it on **WATCH TOKEN**?

**Comment by mkmathur08** [comment]
@nicksavers Yes i did ...for ref i attached document with screenshot. please check.

**Comment by evertonfraga** [comment]
Regarding wallet creation issue: the fix is on its way.

The issue is: when using the light client, it currently does not return the address of the created wallet contract from `getTransactionReceipt` RPC call. 

This pull request (https://github.com/ethereum/mist/pull/3265) aims to fix that. From preliminary tests, it works well. Now I'm tweaking the Wallet code to account for this change. 

Refer to this issue for discussion: #3269.

**Comment by mkmathur08** [comment]
awaiting for the fix ... thanks for update

**Comment by evertonfraga** [comment]
It's up already @mkmathur08. Please update to 0.9.3.
