### ISSUE TITLE
Ether not show up after converting BTC to ETH from Shapeshift.io

### ISSUE THREAD

**Issue by h-nasu** [ethereum/mist#3236]
I currently have two problems.

1. Can not see the Ether that have converted from Shapeshift.io.
2. Can not connect to any website when running Mist.

I downloaded new Mist and followed the instruction for creating new account by entering the password. The starting screen showed the button for converting BTC to ETH. I have followed the instructions and send some BTC to the address that provided. I waited for while, but I had to turn off Mist to use my gmail.
After I started Mist I see 3 wallets probably created while ago, and none of those have any Ether in them. I contacted shapeshift.io and they informed me the transaction was completed but seems like the ether was send to the address that I do not have on my Mist.
https://etherscan.io/tx/0xe9473cbba610bfaec7d82c5813910123d7b3acb6f27ab531d5c91e6424f1a171

Why I do not see this address and account on my Mist?
I really have problem running Mist as it seems taking over internet on my Mac and can not do other things on internet. Is there any way to prevent this?

Version: `0.9.2`
OS & Version: OSX Sierra
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4467677

**Comment by evertonfraga** [comment]
Hi @h-nasu, it seems your blockchain hasn't finished syncing. 

In such cases, you can enable the `Develop > Sync with light client` experimental option, to expedite the expected result.

Should you have any questions, please reopen this issue.
