### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by lnguy** [ethereum/mist#325]
Node type: geth
Network: main
Platform:Win32
... flag provided but not defined -fast

**Comment by Doppelbock42** [comment]
Wallet 5.1. Worked fine until today. Tried restarting but nothing seems to fix it.

![node crash](https://cloud.githubusercontent.com/assets/17707735/13723950/a48968c0-e829-11e5-84c3-1925c70073ff.JPG)

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
