### ISSUE TITLE
Missing ETH

### ISSUE THREAD

**Issue by Aqeel313** [ethereum/mist#3253]
Version: `0.8.10`
OS & Version: windows/
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

I missing my ETH 


Hash: | 0x4ac7f6a67a0f48d425560c8069ec4bbc71659ff3da197ed9dae563f782a8da3d
-- | --
4462436Â \| 44378 Confirmations
2017-10-31 07:28:34 (7 days ago)
ethermine
0xb77Ae9eF27eB4Eb8F2D705789A6Bf87Cb1BcE4aF
0.5990052254064447 Ether ($179.72)
0.000168 Ether ($0.05)
3786564
8 GWei
50,000
21,000

**Comment by marcgarreau** [comment]
I see the successful transaction on Etherscan. Not seeing the funds in your wallet is generally due to not having your node fully synced. If you're fully synced and still not seeing the ETH, please reopen the issue and provide any additional details you can.
