### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by samofrench** [ethereum/mist#326]
Node type: geth
Network: mainnet

...55.855875   17912 blockchain.go:216] Fast block: #1126235 [6db20d84…] TD=8962864689693300013
I0310 00:15:56.097115   17912 handler.go:92] blockchain not empty, fast sync disabled
I0310 00:15:56.355957   17912 cmd.go:114] Starting Geth/v1.3.5/darwin/go1.5.1
I0310 00:15:56.518500   17912 server.go:311] Starting Server
I0310 00:15:57.005895   17912 nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv2-IP1
I0310 00:15:57.836393   17912 udp.go:212] Listening, enode://f4bfacdacafe0027ff10539596b48fa4ddf136ba34e114e76366dfb0e9bf15d2bbdf48cf4ee078d54a25d065b148caa839e909ef039c70cc72b75137cb21af9a@71.227.174.229:30303
I0310 00:15:57.852188   17912 backend.go:526] Server started
I0310 00:15:57.894207   17912 server.go:552] Listening on [::]:30303
I0310 00:15:58.047029   17912 nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv2-IP1
I0310 00:15:58.103585   17912 ipc.go:112] IPC service started (/Users/Sam/Library/Ethereum/geth.ipc)

**Comment by HelixiR** [comment]
+1

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
