### ISSUE TITLE
Wallet Contract Renaming Proposal

### ISSUE THREAD

**Issue by D-Nice** [ethereum/mist#327]
I'm seeing a lot of issues where users are sending Ethers into contracts from their wallet stub contracts, and then the contract receiving the money, if they're supposed to send it back to the wallet contract, it fails due to the contract not assigning enough gas for the wallet contract to receive the ether and store it after its code runs.

The issue surrounding this is the fact that most contracts are written in solidity, and make use of the .send method, where only about ~2000 gas is allowed for it to be completed successfully. So there's a part developers of contracts can play, however, this doesn't fix the large amount of DApps already live, that are using this function.

Hence, to avoid confusion, I propose that the "Wallet Contracts" section should be renamed to Vault or Savings account or something similar, where ether is meant to be stored, and to encourage them to withdraw to their personal accounts first and then spend, rather than spending directly from the wallet. Until this issue is fixed, I think it's the best band-aid, because calling it a wallet, encourages people to spend from it. Just renaming it, will discourage that use.

Not to mention, a number of blockchain explorers don't even properly track internal contract transactions yet, so this causes further issues when spending with the "wallet contract".

Hope this is taken into consideration.

**Comment by alexvandesande** [comment]
Yes, we have many usability issues with people not understanding the wallet. I like the Vault name and I think we'll use it once we rewrite the wallet contract (it was written before frontier and it could use some upgrades)

**Comment by msam4444** [comment]
I made this mistake sending ether to my contract wallet in mist, but I sent it from ethereumwallet.com. Is there a way I get my ether back, or redirected to another wallet or somehow be able to pay the gas for ether to be delivered?  There should be an option if possible for recipient to pay the gas.

**Comment by alexvandesande** [comment]
@msam4444 your case sounds like something different than the one in this thread. Would you care to expand your situation in a new issue?

**Comment by msam4444** [comment]
Here is the link to my issue:
https://github.com/ethereum/mist/issues/408#issuecomment-199862774

**Comment by frozeman** [comment]
@msam4444 this is not related
