### ISSUE TITLE
How to reset the ether password?

### ISSUE THREAD

**Issue by invisibleNexus** [ethereum/mist#3277]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `newest`
OS & Version: windows10
Node version: `geth newest` 
Number of blocks synchronized: 0
```

**Comment by Jlafinancial1** [comment]
yes that password I must have forgotten ,,how do we reset with no link/right

**Comment by alexvandesande** [comment]
We have multiple "wrong password" threads and I suggest taking a look at them, as Ill merge this into that one: #3513

But some suggestions:

* Try using  [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com) to unlock the password and see if it's a geth/mist issue. If you can't there then it's really a password issue
* Mist never creates an account for you automatically. We do however use accounts from geth, so if you have previously installed Geth, and created an account there without thinking, that might be the one.
* It's not possible to recover ether without a password or change the password. You might consider hiring someone to brute force your password for you but make sure you find a reputable source. If they are able to unlock it, **they might claim all the money in it and you'll be without any legal recourse**.
