### ISSUE TITLE
Cannot execute Wallet on Ubuntu (latest version 14.xxx)

### ISSUE THREAD

**Issue by FernandoMartinelli** [ethereum/mist#328]
Hi, I'm booting the latest Version of ubuntu from a USB stick and am not able to run the wallet. Since it has no extension Ubuntu doesn't know what to do with the file. Looking for a service online to run the file was no use either.

Please Help since I want to execute my wallet on a virgin Ubuntu to avoid any chances of being hacked.

Best,
Fernando

**Comment by jcrain** [comment]
I'm having a similar issue with ubuntu 14.0.4. The wallet appears so sync and then the wallet opens to a blank screen.

**Comment by CryptoDJ** [comment]
Same with Ubuntu 15.10.  It opens to a blank screen or just hangs at the splash screen.

**Comment by FernandoMartinelli** [comment]
I actually cannot run the executable since my Ubuntu does not recognize the
file without any extension. How are you doing to at least run that
mist-wallet file?

Thanks for your help!
Fernando

Am Samstag, 12. März 2016 schrieb Amir Abrams :

> Same with Ubuntu 15.10. It opens to a blank screen or just hangs at the
> splash screen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/mist/issues/328#issuecomment-195696625>.
>


-- 
Fernando

**Comment by FernandoMartinelli** [comment]
Any news about this issue? I still cannot run my wallet on UBUNTU =\

**Comment by jcrain** [comment]
Yea I still have the same issue, seams to download the blockchain and then I get a blank screen

**Comment by luclu** [comment]
@FernandoMartinelli Linux does not depend on a subfix for execution. Though the file needs the execution flag.

If you encounter problems with a blank screen make sure to check out https://github.com/ethereum/mist/issues/599!
I will close this for now.
