### ISSUE TITLE
Making me redownload blocks after already installing and using the wallet.

### ISSUE THREAD

**Issue by ImToastyFresh** [ethereum/mist#3283]
I finished downloading the blocks and started mining for awhile I then had to restart my system for a reason and when I opened up the wallet again to check my balance it wiped my balanced and started downloading the blocks again. All 4.4million blocks that took a good few hours last time to download is now downloading again. 

I feel scammed in some sense as what I mined is now gone from my wallet even though the address is the same as before.

Does anyone know why this would happen and is there anyone I can get my ether back?

Thanks.

**Comment by dakkafex** [comment]
Your ether should still just be there, in the location you have set to download to should also cointain a folder called keystore, which is where your wallet basically is.

Balance wont show until the whole chain is downloaded

**Comment by alexvandesande** [comment]
Yes, you have to continuously download new blocks. As the blockchain is quite large, you might consider using a web wallet.

Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
