### ISSUE TITLE
Unable to see tokens in my Eth Mist Wallet despite the transactions being confirmed and the wallet synchronised

### ISSUE THREAD

**Issue by donskalottle** [ethereum/mist#3285]
- [x ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.2`
OS & Version: windows 10 Pro
Node version: `geth 1.7.1` 
Number of blocks synchronized: in sync.
```

https://github.com/ethereum/mist/issues/3012
 
^ This is exactly the problem I have, can anyone help me resolve my issue? Desperately needing help ASAP. Thanks.

<!--

**Comment by 0-0-0-** [comment]
Essentially I have a version of this problem as well. Client claims its synched but shows no Peers
