### ISSUE TITLE
WALLET STILL CREATING!

### ISSUE THREAD

**Issue by lefiguier** [ethereum/mist#3286]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

GOOD MORNING EVERYONE,
I am a noob, in crypto currency
I bought yesterday ethereum on coinbase and I send it directly on my Ether account, I see my ethers on etherscan but I cannot see, send... ETH on my account/wallet...
I need your help to send my ETH to buy cashaa 
thank you in advance :)

Le figuier

```
Version: `0.9.2`
OS & Version: osx
Node version: `geth 1.7.2` 
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
Please activate `Develop > Sync with Light Client`, so you can see your balances in a simple and quick way.
