### ISSUE TITLE
Taking forever to install blocks after having them already installed.

### ISSUE THREAD

**Issue by ImToastyFresh** [ethereum/mist#3289]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.2`
OS & Version: windows/linux/osx
Node version: `geth 1.7.2` 
Number of blocks synchronized: 0
```

I have had a problem before this which in turn has created this problem but I had already installed all the blocks and used the wallet completely fine then everything got reset, balance was cleared and I had to redownload all the blocks but this time it has been left downloading for about 30hours now and I have only just gotten a quarter of the way. 

The first time I did this it only took about 3 hours so it is extremely weird for it to suddenly take this long for no reason at all. It is also strange how my wallet balance was cleared when this happened as well, I had 5 ether and its all gone now. I am not too fussed about that I just want this stupid downloading process to get over and done with because it's doing my head in.

I really hope I can get some help.

Thanks,
Toasty.

**Comment by evertonfraga** [comment]
Hi, we have launched [Mist v0.9.2](https://github.com/ethereum/mist/releases/v0.9.2), with Light Client integration (beta). 

**What does that mean?**
- Sync times reduced by an order of magnitude while staying safe.
- Much smaller storage required. 

**How to activate?**
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)


I'm closing this issue. Should you have any trouble, please refer to this canonical issue: https://github.com/ethereum/mist/issues/3097
