### ISSUE TITLE
No more Ether after Transfer

### ISSUE THREAD

**Issue by invisibleNexus** [ethereum/mist#3298]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.2`
OS & Version: windows10
Node version: `geth 1.7.2` 
Number of blocks synchronized: over 4.200.000 blocks
```
I forgot the Password to access the wallet. Any idea how to reset the password?

**Comment by david340804** [comment]
The password for a wallet cannot be reset, as it's key to the security of the ecosystem that nobody else can mess with your account. Your best hope is https://ethereum.stackexchange.com/questions/97/how-can-i-recover-or-reset-a-lost-wallet-password
Best of luck :)

**Comment by alexvandesande** [comment]
* Try using  [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com) to unlock the password and see if it's a geth/mist issue. If you can't there then it's really a password issue
* Mist never creates an account for you automatically. We do however use accounts from geth, so if you have previously installed Geth, and created an account there without thinking, that might be the one.
* It's not possible to recover ether without a password or change the password. You might consider hiring someone to brute force your password for you but make sure you find a reputable source. If they are able to unlock it, **they might claim all the money in it and you'll be without any legal recourse**.
