### ISSUE TITLE
Mist Wallet window is blank

### ISSUE THREAD

**Issue by chfast** [ethereum/mist#330]
The content of the Window is blank. Menu works. Debug console does not work.

**Comment by aliensyntax** [comment]
I've been experiencing this same issue. I fixed it on Mist 0.5.1. Beta 9 with `./Ethereum-Wallet –ignore-gpu-blacklist`, but when I switched over to 0.5.2. the same blank screen had returned. Also, I can no longer use Mist Wallet 0.5.1. using this command. I do not know if that is a result of the recent changes in 0.5.2. or if it's something I've done recently. The only thing I did lately is install the Rust Parity implementation. I'm using Linux Mint 17.1 Rebecca 14.04.3 LTS, Trusty Tahr, and have a Radeon HD 8670. Solution?

**Comment by ShawnKimble** [comment]
Same issue, Ubuntu 15.10, loads to a blank white screen.  Using ./Ethereum-Wallet –ignore-gpu-blacklist fixes the issue.

**Comment by panicape** [comment]
Hi ShawnKimble, how did you set this blacklist thing? and what is this for?
I'm getting the same issue

**Comment by ShawnKimble** [comment]
I don't know what it does, but I used this command to launch the program, and it resolved the blank screen issue

./Ethereum-Wallet –ignore-gpu-blacklist

**Comment by ShawnKimble** [comment]
Hmm.  Actually it no longer seems to resolve the issue.  I'm now back to a blank screen after launch.

**Comment by panicape** [comment]
mmmmm, it is a tricky thing... are you using another wallet? By the way... the account that you set in the wallet is the same you use in ethereum node, don't you?

**Comment by ShawnKimble** [comment]
I'm using geth via console and jaxx.io as I can't get Mist to work.

**Comment by taoteh1221** [comment]
@shawnkimble See if you have proprietary video drivers in "additional drivers". If you are currently using " xorg" drivers you'll get a blank screen etc. Switch from the xorg drivers over to proprietary ones. That should fix your issue.

**Comment by ShawnKimble** [comment]
@taoteh1221 you were correct, I had the Xorg drivers set, once I changed that to fglrx and applied the change, Mist now displays properly.  Thanks!

**Comment by taoteh1221** [comment]
@ShawnKimble Your welcome, glad it worked.

**Comment by panicape** [comment]
@taoteh1221 Do you know how can i know what drivers am i using and how i could change it? thanks

**Comment by taoteh1221** [comment]
On Ubuntu, look for "additional drivers". If available for easy switching, they should show there along with what driver you are using now.

**Comment by chrispez** [comment]
@taoteh1221 Thanks taoteh, solved an issue that was bugging me for days! Changing to nvidia proprietary helped Mist render correctly in Ubuntu.

**Comment by taoteh1221** [comment]
@chrispez Your welcome, glad it helped! :smile:

**Comment by tjayrush** [comment]
I noticed a similar thing when switching between testnet and mainnet (or visa versa), but I also noticed that the blank white screen only occurred when I had the Developer | Toggle Develop Tools | Wallet UI turned on. As soon as turned the Wallet UI off, the screen displayed properly.

**Comment by chfast** [comment]
Looks to be working in 0.7.1.

**Comment by luclu** [comment]
If affected please look here: https://github.com/ethereum/mist/issues/599
Make sure to update to 0.7.4.
Further discussion will happen over here: https://github.com/ethereum/mist/issues/75
I will close this as duplicate.
