### ISSUE TITLE
ETH didnt come

### ISSUE THREAD

**Issue by 22005** [ethereum/mist#3308]
I send ETH from my wallet to by some tokens to  0xD380f49184F0fC05bb891d83bd44A6755b107677
 transaction 0x76f7f30a9c5d667bc6b09529ad5d1acacd377847a7eaf7d335efacc9ceb70ca7 it was on 19 th November. ETH left my wallet but didn't came to this address.

**Comment by 3esmit** [comment]
Are you synced to network?

**Comment by david340804** [comment]
Make sure the recipient wallet is up to date on the network, it looks like that transaction was successful based on https://etherscan.io/tx/0x76f7f30a9c5d667bc6b09529ad5d1acacd377847a7eaf7d335efacc9ceb70ca7
The recipient account has only one transaction in its history: receiving your 0.124 so it's still there

**Comment by marcgarreau** [comment]
Thanks Ricardo and David for responding. Yep, @22005, your transaction was successful. The geth node just needs to be fully synced to see the balance in your wallet. Light mode is the quickest way to sync a node and can be done by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. Closing this issue; please reopen if you still have trouble.

**Comment by 22005** [comment]
the translation was from my purse "myetherwallet" in my purse on the stock exchange "cryptonator"

**Comment by 22005** [comment]
"myetherwallet" mode "Light client"
