### ISSUE TITLE
Ethash folder on windows

### ISSUE THREAD

**Issue by Tekarihoken** [ethereum/mist#331]
Hello,
I have just seen that the Ethash folder is located in the folder %AppData folder and not in %AppData\Roaming or %AppData\Local as it should be.
This is not a big issue but it make the software not conform to windows devellopment good practice.
Regards,

**Comment by luclu** [comment]
Kindly check if still valid and reopen an issue on the `ethash`-repo: https://github.com/ethereum/ethash
I will close this as this is not related to Mist.
