### ISSUE TITLE
Missing balance after installing 0.9.2

### ISSUE THREAD

**Issue by alfredgb** [ethereum/mist#3312]
I'm writing because I lost my balance after installing 0.9.2. That's all I did. I installed the new version since the old version prompted me to install a new one. Could someone help me find out if I lost it all or if there is a way to get it back?
Thanks,
Alfred.

- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by fcladf7** [comment]
Same thing for me.
I have 0.5 ETH but since the last update my account shows 0.
