### ISSUE TITLE
Mist crashes after adding tokens

### ISSUE THREAD

**Issue by footloosejava** [ethereum/mist#3316]
Mist crashes after adding tokens. Only two tokens added, OMG and DATA, and causes Mist to crash shortly after opening with this error message:

> X:\...\Ethereum-Wallet-win64-0-9-3\resources\app.asar\node_modules\solc\soljson.js:1
> (function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path"
> 
> Error: "toString()" failed
>     at Uint8Array.Buffer.toString (buffer.js:503:11)
>     at StringDecoder.utf8Text [as text] (string_decoder.js:180:16)
>     at StringDecoder.write (string_decoder.js:64:46)
>     at readableAddChunk (_stream_readable.js:166:31)
>     at Socket.Readable.push (_stream_readable.js:136:10)
>     at Pipe.onread (net.js:560:20)

**Comment by footloosejava** [comment]
Actually ... crashes now even after tokens removed. GETH works fine. GETH + MIST fails with error on report above.

**Comment by DroidR17A** [comment]
I'm having the same problem on Windows 10. I've tried win 64 0.9.2 and 0.9.3. Geth loads and runs fine, as does Ethereum Wallet - until I add tokens to the watch list, at which point CPU spikes and Geth's memory usage goes up x10+.

See attached screen shots:...

Geth running normally...
![gethnormal](https://user-images.githubusercontent.com/34201102/35458676-22542aea-0292-11e8-9728-487ae872f487.png)

Add Tokens to watch list, CPU spikes to 100%...
![cpuspikes](https://user-images.githubusercontent.com/34201102/35458673-2208b51a-0292-11e8-82cb-cf2ba33bfafe.png)

Geth memory usage spikes, pipe closes and Ethereum Wallet crashes.
![gethmemerror](https://user-images.githubusercontent.com/34201102/35458675-2230f502-0292-11e8-8599-e66ec79d689a.png)

With 6 tokens loaded, it crashes within 60 seconds of opening Ethereum Wallet.

**Comment by DroidR17A** [comment]
I'm having the same problem on Windows 10 with Ethereum Wallet. I've tried win 64 0.9.2 and 0.9.3. Geth loads and runs fine, as does Ethereum Wallet - until I add tokens to the watch list, at which point CPU spikes and Geth's memory usage goes up x10+.

See attached screen shots:...

Geth running normally...
![gethnormal](https://user-images.githubusercontent.com/34201102/35458676-22542aea-0292-11e8-9728-487ae872f487.png)

Add Tokens to watch list, CPU spikes to 100%...
![cpuspikes](https://user-images.githubusercontent.com/34201102/35458673-2208b51a-0292-11e8-82cb-cf2ba33bfafe.png)

Geth memory usage spikes, pipe closes and Ethereum Wallet crashes.
![gethmemerror](https://user-images.githubusercontent.com/34201102/35458675-2230f502-0292-11e8-8599-e66ec79d689a.png)

With 6 tokens loaded, it crashes within 60 seconds of opening Ethereum Wallet.
