### ISSUE TITLE
Creation of the contrat has 0 confirmation

### ISSUE THREAD

**Issue by basaa88** [ethereum/mist#3317]
Version: `0.9.2`
OS & Version: osx
Node version: `geth 1.7.3-stable` 
Number of blocks synchronized: 4 610 675

- My transaction is not confirmed

I created a token and deployed using Mist, but it's been 20 hours and there is still no confirmation but apparently the contrat has been created.

When I open the Mist devtool, the console show this error:
**Uncaught TypeError: Cannot read property 'toLowerCase' of undefined**

And on the top of that I'm creating a wallet but the creation is stuck too (Creating... looping)

**Comment by evertonfraga** [comment]
This should be fixed in latest 0.9.3 version. Thanks.
