### ISSUE TITLE
Cannot call contract functions without sending a transaction

### ISSUE THREAD

**Issue by slavik0329** [ethereum/mist#332]
There doesn't seem to be a way to call a contract function for reading values without having to create a transaction, whereas in geth I can do: `contract.function.call();`

**Comment by D-Nice** [comment]
There definitely is, you just need to set the function as a constant in your contract. Here's an example:

`    function totalParticipants() constant returns (uint count) {
        count = participants.length;
    }`

You can even have inputs if needed, for cycling through an array for example.

**Comment by slavik0329** [comment]
Setting the function as constant did the trick! I don't know how I would have figured this out without your help. The only mention of constant is as a variable modifier in the Solidity documentation.

Thanks again!
