### ISSUE TITLE
One wallet, 2 different balances ?

### ISSUE THREAD

**Issue by Sovxx** [ethereum/mist#3321]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: linux
Node version: `geth 1.7.2-stable-1db4ecdc` 
Number of blocks synchronized: 4,615,053
```

I am using light mode.
Looks like I am sync, but mist shows two different ETH balances on the same page

![image](https://user-images.githubusercontent.com/12556923/33223045-91cdad18-d15c-11e7-9bbf-76b4b538f8bc.png)
But the balances are the same in EUR
![image](https://user-images.githubusercontent.com/12556923/33223055-a66718ae-d15c-11e7-8305-6edb664fb10b.png)

Is it just... a round number thing ?

**Comment by craigdevoy** [comment]
You are right about it being a rounded number thing. 

If you open up your Chrome console. 

Copy/Paste this:
var ethBalance = 0.005;

Then Copy/Paste this:
ethBalance.toFixed(2); 

Will output: "0.01"

**Comment by evertonfraga** [comment]
On the top right the Wallet shows your balance with a fixed amount of decimals. In the middle it shows the entire number, without rounding.

Hope that answers your question. But if not, please reopen this issue.
