### ISSUE TITLE
Stuck at 99% sync on Win10.1709

### ISSUE THREAD

**Issue by alpinemountain** [ethereum/mist#3333]
Version: 0.9.3
OS & Version: Windows 10 Version 1709
Number of blocks synchronized: "214 blocks left"

Syncing never progresses beyond 99%, even after leaving for 24 hours.  Have tried reinstalling Windows 10 and just installing: https://github.com/ethereum/mist/releases/download/v0.9.3/Ethereum-Wallet-installer-0-9-3.exe

Still same result.  Nothing interesting in logs... last log entry from 30 seconds ago is:

INFO [11-26|19:51:44] Imported new state entries               count=1863 elapsed=7.019ms   processed=15953218 pending=31344 retry=1    duplicate=1744 unexpected=7027

![mist-screenshot](https://user-images.githubusercontent.com/10806332/33250053-1851d4b8-d2e3-11e7-8686-f6daae9b7a53.png)

**Comment by justinbass** [comment]
Any resolution here? Mine is stuck as well for several days, stock install on Win7.

**Comment by anitatwelve12** [comment]
last few hundred are not getting synced ... as the blocks are increasing faster than syncing. its becoming frustrating now , this is my third time.. no luck.
