### ISSUE TITLE
Botch app made by amateurs

### ISSUE THREAD

**Issue by Zexx1000** [ethereum/mist#3343]
The developers of MIST must be coming from the Linux community. 
Because only them can display a splash screen and think that it makes the program
visual and user-friendly.

Here are some of the improvements that need to be added to Mist 
to make it a slightly better app:

1. Allow the user to choose the folder for his blockchain and keys:
    - Maybe the user don't have enough space on his disk.
    - Maybe he feels more secure using another location, with the rest of his data
        that is being automatically backed up.
    Instead the app picks a location and immediately starts downloading before
    the setup has even started.

2. Download works like children have written it. It somehow manages to push
    the disk usage to 100%. I don't know how, because my internet is much
    slower than my disk, so no amount of download can slow down my disk.
    Seems the program is writing and reading a lot of small chunks simultaneously, 
    instead of using read/write buffers. Did I buy this much RAM
    to sit there unused?

3. There's no pause button. Since disk is pushed to 100% bandwidth I can't do anything
    else while the program is downloading. Starting any other program is basically 
    impossible. Adding the Pause button would enable users to freeze the program for 
    a short period of time to start some other app.

4. Sync will often come to 99.99% and then get stuck for hours. Constantly doing 
    something, but never finishing. WTF is this? Is it mining ETH for someone else
    using my computer? I killed the damn app.

5. On the next startup Mist displays just the download progress bar. Nothing else.
    And it's stuck again. There are no buttons on this window, just a picture. 
    No Close, no Pause, not even the [X] icon in the top left corner so that
    you can close the program. After waiting for hours without any progress,
    I killed the damn program from the Process Monitor.
    
    What kind of a stinking app is this?
    So many problems before I even started to use it.

**Comment by 37** [comment]
Don't like something? Fix it and send a pull request.

**Comment by Taloz** [comment]
While I may not agree with your derogatory title, I do agree with most of your suggested changes. Number 2 seems to be a problem with one of the binaries that Mist downloads (probably Swarm) and number 3 may not be possible due to the separate binaries I mentioned earlier.

@37 Your comment adds little to the discussion. Did you ever consider that @Zexx1000 may not have the time to invest in such a contribution and just wanted to inform others on how the app could be improved?

**Comment by Zexx1000** [comment]
Should I also make my own shoes? Or my own hammer and nails? Not everyone is a developer. And even those who are, don't use this or that programming language, or aren't familiar with certain frameworks.

So, if you start doing software, don't ask from your users to fix it. They don't know the internals of the software as well as those who already spent lots of time working on it. What you should ask from your users is feedback. And then value it.

**Comment by Zexx1000** [comment]
@Taloz I used a bit stronger language because I was angry. I agree that number 3 may not be fully possible, but maybe reducing the thread priority of a sub-process would enable implementing a semi-pause. It's funny that @37 gave himself thumbs up. A bit lame if you ask me.

**Comment by 37** [comment]
@Taloz you're right. I took issue with the tone of this ticket, though UI / UX suggestions are perfectly valid. 

> Botch app made by amateurs 
> Should I also make my own shoes? Or my own hammer and nails? 
> What kind of a stinking app is this?
> WTF is this? Is it mining ETH for someone else using my computer? I killed the damn app.
> 37 gave himself a thumbs up. A bit lame if you ask me.

@Zexx1000 Please read some of the [open-source contribution guidelines](https://opensource.guide/how-to-contribute/) and general etiquette tips around professional development. *I don't say this to insult you*, rather we are apart of a community and we work together to make better software. Some of the issue you have raised **are** worth discussing, so thanks for that, though the ticket is equally useful without snide little remarks. It will probably receive more attention from developers if you don't shit all over us first.

**Comment by Zexx1000** [comment]
@37 seems to me that it attracted more attention by me being direct. I wouldn't even have to open this thread if you were critical about the app yourself. I am a developer myself (fortunately I don't have to use JS in my work). Whenever I'm not a user of the app I'm developing, it's not good, unless I have a very demanding project manager. But when I'm using the app myself, frequently, it has to evolve to satisfy my high standards. Because I want to use a good app. So the question is:
- Are the devs using this app? Every day?

Because if they don't, it would explain how those basic issues, which are visible from the outer space, could slip by. 

Another thing. As a dev, I always appreciated user input, because that would motivate me to fix things or add features. It would usually give me a different perspective on the problem. It would show me what the users want and not just what I want.

Unfortunately, users don't report enough issues. I wanted them to report more. Because that's what motivates you to make a better app.

We need more feedback, not less. Not just in programming. I wish people were more critical about our "modern" medicine. So that it's not so crappy. So that it becomes worthy of the year 2017. Instead, people just tolerate that botch they call "medicine" and pay enormous money for totally outdated stinking solutions. That's what you get without feedback. Too much blind respect to doctors and medicine, too little criticism. I don't want that in IT (although it's present).

**Comment by evertonfraga** [comment]
Suggestions are valid, although already planned or duplicated. 

Please use better language, and let's try to keep a positive mood around.
