### ISSUE TITLE
Wallet doesn't work for MAc

### ISSUE THREAD

**Issue by Anhelme** [ethereum/mist#3345]
Ethereum Wallet always cannt download some hundred of blocks. It download 4mln blocks and stop.
It show 0 Ether on my bill. I made transaction some month ago. Why Ethereum Wallet cann't show correct Ether count after processing almost all blocks?
I see taht global problem, and it was 3 month ago. Why you cann't fix it? HOW I CAN USE ETHEREUM??
Please recommend to me normal ethereum wallet

**Comment by Anhelme** [comment]
Can I use https://www.myetherwallet.com/? Is it safe? Or it used for own risk. I prefer use default native apps

**Comment by marcgarreau** [comment]
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting. 

Also, yes, you can absolutely access your wallet and send transactions within MyEtherWallet. It is safe to use, but type in the URL yourself - do not use links you find in Slack channels, emails, etc. There are many phishing sites out in the wild. Be careful!
