### ISSUE TITLE
Ethereum node connected - STUCK

### ISSUE THREAD

**Issue by LogJosh** [ethereum/mist#3349]
Literally as the title says, yesterday i could open the wallet with no issues at all, i come back to my pc and fire up the wallet and it is stuck at 'Ethereum node connected' screen. could this be a firewall issue?

**Comment by markkeulen** [comment]
I have got exactly the same problem. Using latest version of macos. Help would be apprecited

**Comment by vguilfu** [comment]
Same issue and I need to access it before the 7th.

**Comment by LogJosh** [comment]
ok i think i have found a solution, add the exception to the entire Ethereum folder in windows defender . then launch it . it still gets stuck there but trust me , leave it open for a bit, go play some games or research some crypto, it should work. it has for me a couple of times in a row now, good luck :)

**Comment by matthiasdix** [comment]
Same issue (Win10, Ethereum Wallet 0.9.3). I tried deleting my chain data with "geth removedb" (both regular and light). Now Application is starting, but (light) syncing is not starting...

**Comment by markkeulen** [comment]
could you explain what you mean by add the exception? I'm using a mac

**Comment by powapete** [comment]
Same problem here (Win 7 Pro, Eth wallet 0.9.3). Started with light sync a few days ago. Windows Defender is swiched off.

**Comment by oezgueracar** [comment]
I'm on Windows 10 with Eth wallet 0.9.3. 

Same problem. Tried deleting every folder and uninstalling. Lightning client doesn't work at all. Also trying to download with peers gets stuck just like in the old days.

**Comment by cryptojunky** [comment]
Same issue,

I deleted geth file here: C:\Users\USERNAME\AppData\Roaming\Ethereum Wallet\binaries\Geth\unpacked {delete single file that says geth]

Deleted ethereum win-unpacked from zip file. 

Redownload ethereum and run again. It will download updated geth file automatically and sync should start withing 5 or so minutes.

**Comment by maverick85** [comment]
Same problem on macOS High Sierra as described here, this issue is common to Win and Mac users.

https://github.com/ethereum/mist/issues/3355

**Comment by etalot** [comment]
Windows 10, same issue.

**Comment by fulldecent** [comment]
Syncing will take a long time. Some of the people here seeing this issue are "stuck" just because they have not waited the full 7 days to sync. And some people may have waited the full seven days but another issue (connectivity, peer issues) have conspired against them. In these cases, the "stuck" experience is consistent with Mist's full node functionality and this issue is not actionable.

HOWEVER, if you believe that Mist should start and open right away and then sync later, then please consider #3476. That issue is actionable and changes the user experience and the design of the Mist project. Please give us a comment or thumbs up there if you think that actionable solution helps you.

**Comment by guoxuesong** [comment]
@fulldecent 

The log does not grow, the dir 'geth' keeps the same size for a long time, how do you think about it ? 

Is it because cannot found peer ? Whatever, it should print something in the log. The last log line I got is 

> Failed to retrieve current release       err="can't fetch trie key ....: no suitable peers available"

What does it mean ?

**Comment by kotmatpockuh** [comment]
still appears

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097

**Comment by yefeister** [comment]
I am having the same problem after I closed the wallet.
![ethereumwallet](https://user-images.githubusercontent.com/6027784/38477210-0f2058a0-3be4-11e8-9417-1566a8f83673.png)

**Comment by yefeister** [comment]
The issue was resolved by adding Ethereum folders to the exception list of the Windows Defender program.

**Comment by leekwiyoung** [comment]
Windows 10, 같은 문제.
