### ISSUE TITLE
Ability needed to delete watched contracts outside of contract view

### ISSUE THREAD

**Issue by D-Nice** [ethereum/mist#335]
I myself and other people I've seen are having issues with adding contracts, and said contracts not being able to open in the contract view when clicked on, just showing a blank page. Another issue is greyed out contracts, from private or testnets, that can't be deleted while on the mainnet. 
Also, I've seen some people accidentally adding their wallet addresses even, and stuck with them on their watch contract page, where they've asked me for help deleting them, but I'd rather they not risk doing more damage, by deleting certain files from their AppData/Roaming/Mist directory to remedy this.

Therefore I request an option be added on the main contract view, where all contracts are visible, to allow for removing contracts on the watched list, it could be similar to one of the deposit ether icons when you click on an address.

**Comment by Yerontour** [comment]
With version 0.4.0 it works fine, but with version 0.5.1 I've the blank page issue.

**Comment by frozeman** [comment]
Try this script in the wallet console and see if it fixes it: https://gist.github.com/frozeman/ed41008f4d30900da3e8

**Comment by D-Nice** [comment]
It works on 0.5.2
However, I think the ability should still be there, to allow contracts to be deleted from the main page.

**Comment by alexvandesande** [comment]
fixed on latest
