### ISSUE TITLE
Wrong password that I never introduced, fix it !!!

### ISSUE THREAD

**Issue by Madebyivan** [ethereum/mist#3354]
Wrong password that I never introduced, fix it !!!

**Comment by Madebyivan** [comment]
So many people I can not be wrong, can you give a solution ??? thank you, it is not good to keep the money from us !!!!

**Comment by Jlafinancial1** [comment]
ya me too.... I would not forget my password .... what do we do with our frozen funds????

**Comment by Foxcor** [comment]
I confirm the problem.
geth v1.7.2  can not decode key files, does not accept the password written on paper.
At first I could not send ETH, I decided to check the keys, but they do not work. 
![geth](https://user-images.githubusercontent.com/30261332/33666674-d1e445b2-daab-11e7-9899-a14b498ede09.jpg)

**Comment by tobiv** [comment]
Have you tried with MyEtherWallet?

**Comment by Foxcor** [comment]
@tobiv 
Yes. No results

**Comment by kooweele** [comment]
Me too, I have hardcopied my password. Now it's giving me "Wrong Password" error when trying to send Ether away. 

THIS IS A TRAP.

**Comment by anormore** [comment]
This is a known and COMPLETELY ignored issues by the dev team. Apparently 8 days ago, they reopened a bug report. Good luck, and welcome to hell.

**Comment by kooweele** [comment]
Very irresponsible not to fix this bug and still getting ppl to use it ; some crypto-BS sites still peddle this wallet without a clue.


Sent from Yahoo Mail for iPhone


On Thursday, December 21, 2017, 23:03, anormore <notifications@github.com> wrote:


This is a known and COMPLETELY ignored issues by the dev team. Apparently 8 days ago, they reopened a bug report. Good luck, and welcome to hell.

**Comment by alexvandesande** [comment]
I'm sorry you're having issues with password. This bug has been a hard one to figure out as each user seems to have a different cause. Please check this thread with possible solutions: https://github.com/ethereum/mist/issues/669

And fill this form: https://goo.gl/forms/jznmHV6Fpui7Ijds1 to help us gather data on the issue

I am merging all issues into a single canonical
