### ISSUE TITLE
Importing contract wallet (REWARDING WHOEVER SHOWS ME HOW TO RESOLVE THIS)

### ISSUE THREAD

**Issue by RRapo** [ethereum/mist#3357]
```
Version: `0.9.3`
OS & Version: osx high Sierra 10.13.1
Number of blocks synchronized: 4.665,151
```
Hi all, 
I am trying to import a contract wallet after having deleted all the data from my laptop.

I have the keystore file so I am able to recover my main account (in theory this should give me access to the contract wallet) but when I try to import the contract wallet I get something like: "You do not own the contract...you can add it as watch only".

However, when I add the contract as watch-only and try to interact with it (execute) nothing happens.

I can do it up to the point where I have the following options: "write to contract: remove owner, is owner, etc". My main doubt is how to go from here to having the funds of this wallet back in my main account. many thanks in advance.

I AM NOT SURE I AM ALLOWED TO THIS BUT I WILL, AS A SIGN OF APPRECIATION, I WILL TRANSFER SOME ETHER TO WHOEVER HELP ME FINDING THE SOLUTION FOR THIS ISSUE.

Complete novice here. Can anyone point me in the right direction?

Thank you all

R

**Comment by RRapo** [comment]
No one?

**Comment by shazow** [comment]
@RRapo If you have your keystore files (they look like `UTC--...somedate...--somehash`), then you can put them in your `~/Library/Ethereum/keystore` folder and Mist should pick it up next time you run it.

**Comment by RRapo** [comment]
Hi @shazow , thank you for your reply. I do have the keystore file to the main account and I am able to add it to mist. From there, I am able to add the smart contract (as I have it's address) as "watch-only". Then I have some options to write on it like remove owner, add owner, kill...etc etc but I am not sure which one to choose in order to transfer the funds in the smart contract to the main account.

**Comment by shazow** [comment]
@RRapo I don't believe you should have to add anything beyond putting the key in the keystore directory. Watch-only won't let you perform transactions on it, since it's _watch only_.

This is the wrong place for asking these kinds of questions, please create a question on the Ethereum StackExchange: https://ethereum.stackexchange.com/

**Comment by RRapo** [comment]
@shazow I used to be able to simply import the smart contract but now, whenever I try to do it, it says I am not the owner of the contract (although I am!!). Do you think I might have done something that locked me out of the contract permanently? This is harder than I thought it would be. I have made the same question on the link you have showed me but the answer provided were not clear enough unfortunately https://ethereum.stackexchange.com/questions/32044/import-contract-wallet

**Comment by shazow** [comment]
I'll respond on the StackExchange questions, please close this issue.
