### ISSUE TITLE
Incorrect toast message when sending from a contract

### ISSUE THREAD

**Issue by greggdourgarian** [ethereum/mist#336]
newbie here so maybe i don't get it but when i send some either from my contract using Ethereum wallet, the Windows toast message that pops up uses the wrong tense of the verb to send to report what just happened.   It says "Send payment" instead of "Payment sent".  And the text below it has the same issue.

**Comment by alexvandesande** [comment]
Thanks for catching that! I've changed it on develop and will fix on the next release

**Comment by greggdourgarian** [comment]
great to see the quick responses on these...
