### ISSUE TITLE
Node crashed

### ISSUE THREAD

**Issue by cryptoanon** [ethereum/mist#337]
![default](https://cloud.githubusercontent.com/assets/6435009/13727079/d4ce9426-e8f4-11e5-9548-76c60fd3eca6.png)

**Comment by ncavet** [comment]
![screen shot 2016-03-13 at 10 38 20 am](https://cloud.githubusercontent.com/assets/3806002/13729641/c9688002-e907-11e5-81b2-60ce6234338d.png)

**Comment by ncavet** [comment]
This seems to occur when you have a geth instance already running or set to auto load. I was able to fix with this:

launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.ethereum.plist

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
