### ISSUE TITLE
Recover private key for MEW

### ISSUE THREAD

**Issue by RonBrown1963** [ethereum/mist#3373]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by tobiv** [comment]
You don't get a private key from Mist. Use the keystore file and password to send from MyEtherWallet.

**Comment by marcgarreau** [comment]
@RonBrown1963 I'm sorry, there's nothing the Mist team can do to help you retrieve a lost private key generated by MyEtherWallet. As @tobiv mentioned, new wallets generated by Mist instead provide a keystore file, encrypted with a password of your choosing.
