### ISSUE TITLE
Packages should not be encrypted

### ISSUE THREAD

**Issue by step21** [ethereum/mist#338]
At least on Windows, in all past releases, the unpacked files always show up as encrypted, on the file system level. If there is not a particular reasons for that, I think this should be removed in the future as it only can cause problems down the line (unless the user is deliberately encrypting them).

**Comment by luclu** [comment]
Do you mean the `asar`-file? Those get created by https://www.npmjs.com/package/electron-packager.
The whole packaging will get some serious overhaul: https://github.com/ethereum/mist/issues/561
I will close this for now.
