### ISSUE TITLE
How to change the Ethereum-Wallet datadir on Windows?

### ISSUE THREAD

**Issue by realuser** [ethereum/mist#3385]
I installed `Ethereum-Wallet-installer-0-9-3.exe` on Window 10 . During the installation it asked me where I want to store the blockchain, I chose a directory.  Now I wish to change this directory to another folder on another drive, however it's not clear where or how I can do this.  

Other solutions mention running geth first with a `--datadir` flag or creating symlinks but this seems cumbersome.  Since the installer asked the question, I'm guessing this is configurable.  I'm not sure if the installer stored the information in a configuration file or in the registry.  I do see the folder I chose in the following registry key: 
`Computer\HKEY_CURRENT_USER\Software\Ethereum Ethereum-Wallet\NODEDATADIR`

Can I just change this value? Or if not, where I can correctly change the datadir value?

```
Version: `0.9.3`
OS & Version: `Window 10 Pro 64-bit Version 1703`
Node version: `geth 1.7.2-stable-1db4ecdc` 
Number of blocks synchronized: unknown
```

**Comment by realuser** [comment]
Also I notice the Start Menu shortcut for Ethereum Wallet located in 
`C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Ethereum Wallet`

Has the following Target:
`"C:\Program Files\Ethereum-Wallet\Ethereum Wallet.exe" --node-datadir="D:\mycustomfolder"`

So that makes me wonder if I can just close ethereum, physically move the datadir, and then change the `--node-datadir` flag in the shortcut

**Comment by alexvandesande** [comment]
Thanks. While you can change the datadir by starting your own node, we don't believe this is a very good solution for most GUI users and we are working on making the sync unnecessary or faster.

Thanks!

**Comment by realuser** [comment]
Thanks, my point is that I'm wondering if the standard rhetoric of needing to start your own node separately first is actually necessary. For example, as you suggest and also this comment https://github.com/ethereum/mist/issues/572#issuecomment-217543502 suggests running `geth.exe --datadir "D:\Ethereum"` first and then starting Ethereum-Wallet.

However, since you can pass a `--node-datadir` parameter (note the `node-` prefix) which to my understanding gets forwarded to geth, can you skip the step of separately starting geth and instead just pass `--node-datadir="D:\mycustomfolder"` directly to Ethereum-Wallet?

I guess I'm asking if this officially works or if there might be some problem with doing that.

**Comment by eddievhfan1984** [comment]
I've done it that way myself. It properly starts from the last checkpoint when I did the manual execution of geth. I could consider this a useful workaround (especially as part for a shortcut) for now.

**Comment by fiddybux** [comment]
https://ethereum.stackexchange.com/questions/2551/how-to-set-a-different-datadir-in-mist?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

This has the answer. Rather convoluted to say the least!

**Comment by earthvisitoruk** [comment]
alex xcan you tell me how come i can not send any ethereum in my ethereum wallet because it will not sync and like others wrong password keeps coming up i am new to this and find it hard to write in cmd and i am trying to set up a pi3 for mining and still having trouble there too so i need to know how to get ethereum wallet synced i have deleted in the  geth fold 5 time and still not sync not if i had not ethereum in there it would sync straight away any help anyone please
