### ISSUE TITLE
Long Term Support?

### ISSUE THREAD

**Issue by 2Belette** [ethereum/mist#3388]
Is mist already a Long Term Support project?
If not, any plan to do propose an LTS version?

Many thanks

**Comment by evertonfraga** [comment]
Hi @2Belette, we have no ways to provide a LTS version, as Mist/Wallet are still experimental/beta and we are somewhat coupled to [Geth](https://github.com/ethereum/go-ethereum), which has frequent releases.

once we get there, we can re-evaluate. Cheers!
