### ISSUE TITLE
0.5.2 - Mac OS X send not hanging anymore, but...

### ISSUE THREAD

**Issue by jacogr** [ethereum/mist#339]
Ok, so the hanging issue when going to send Ether is not fixed. The app is actually responsive. I can now -

1. Select the sender when "depositing"
2. Enter the amount
3. Enter my password

Seds however never happen. Once the password has been entered, it goes back to the send screen (not the wallet screen) and nothing happens, no transactions occur. Developer UI/console shows no issues.

**Comment by frozeman** [comment]
Does the money move? Did you got an error in the background, that the Node connection was lost? Which you may oversaw? This will stop confirmation window, from successfully sending the ok back to the wallet window.

**Comment by jacogr** [comment]
The money doesn't move. I've tried from a number of accounts.

It really logs nothing at all. However when exiting, it does now say that a timeout occurred on 'eth_sendTransaction' (Only pops up in red when exiting, never visible before trying to exit)

Something seriously went wonky with 0.5+ - reverted to 0.4 last night and everything is fine. With 0.5.1 (never tried 0.5.0 I started getting the send UI hanging, now with 0.5.2 cannot send at all). 

Clock is syned with Apple's timeservers, geth runs happily in the background when I start it (I can interact with the APIs to it), it is just Mist that seems to be very unhappy for some reason or another.

**Comment by jacogr** [comment]
As commented elsewhere - on my other Mac, same issues. Here I can see the blocks falling behind (with geth happily running in a terminal).

Timeservers synced to default Apple ones (as per default install), I'm in South Africa, time servers are in Europe, Mist downloaded from US (GitHub) is not working at all in this version. 2 machines, both having issues.

**Comment by luclu** [comment]
@jacogr could you kindly check if version 0.7.4 (bundles geth 1.4.4) resolves this issue?

**Comment by luclu** [comment]
Make sure to try 0.7.5.
I will close this for now as of inactivity.
