### ISSUE TITLE
Is Ethereum Wallet project doomed or dead yet?

### ISSUE THREAD

**Issue by MaSansky99** [ethereum/mist#3398]
So I have been trying to use the ethereum wallet for quite some time now (since the very beginning). But I have to be honest. It sucks. It always did and the way year-old issues are still keep popping up, I expect it will suck for eternity.

For months my balance shows 0, last blocks don't sync, Ether in wallet contracts can not be transferred back, no support, the list goes on and on. And I am not the only one. There's hundreds of issues in this repository, and the only ones with reactions are "me too". No solutions, no help. Nothing.

Too bad. I always thought the Ethereum project was promising. The sole reason I invested in it from the beginning.

**Comment by unknown1235** [comment]
This wallet have never stopped giving me issues.  From the beginning till today.
Every time I use this wallet has been a nightmare.  Basically waste a whole day trying to get it working and stuff.

For syncing, when it gets close to the last block, it will stop and start state importing.  That takes hours.  There is an console command you can use to monitor the number of states it imported.  I think its got to import about 30 million or something.  Not sure can't remember but literally no progression bar or any notification to tell you whats going on.  So you just sit there thinking if it stopped working or something.

**Comment by evertonfraga** [comment]
Hi all, we have a great influx of issues, and we're working on internal
changes to deal with those.

Please hang on :)


--
Everton Fraga

**Comment by cryptchain** [comment]
lol it's really really bad

**Comment by inflexionist** [comment]
I would like to ask the same question as @cryptchain ... How long do we need to hang on?  can you explain what the actual problem is with syncing.

**Comment by evertonfraga** [comment]
@inflexionist @cryptchain 
In order to solve sync problems, for now you have these options:
1- Try to use the light client (Develop > Sync with Light Client)
2- download Geth 1.9.3 and run it separately: `geth --syncmode light`, then open Mist. in this exact order.

**Comment by inflexionist** [comment]
December 5 Pető Zoltán @micahaza states that the --light mode is buggy and not to use it on the Mist Gitter channel. It seems that the problems with light sync are causing low network usage. Can you comment on that?

**Comment by inflexionist** [comment]
@evertonfraga  thanks for proposing a suggestion.  I appreciate your efforts

**Comment by evertonfraga** [comment]
Geth's full/fast sync usually take a lot of time to sync. And they require dozens of GB from your storage.

Geth's Light Client is currently the way out: you download ~40MB instead. It is still experimental, but it has this huge benefit.

Soon we'll release an updated mist with support for Geth 1.7.3, and I'm hoping this pain point won't hurt anymore.

**Comment by Trophonix** [comment]
@evertonfraga On light mode, it supposedly successfully syncs, but my balances remain outdated.

**Comment by thijstriemstra** [comment]
> Hi all, we have a great influx of issues, and we're working on internal changes to deal with those.

So why do most of the issues have no response at all?

**Comment by erperejildo** [comment]
When is the final version going to be released?
Should we use a different wallet to keep our ETHs saved?

**Comment by Riifta** [comment]
Mist sucks. It continually fails to download blocks no matter what you do and the amount of babysitting I have to do every time I launch it to get it to sync is crazy. It's not ready for prime time in it's current state and the bugs persist for ages. 

It's a real shame as Ethereum is probably the most exciting cryptocurrency platform around. The wallet issues are really hurting uptake of it though.

**Comment by evertonfraga** [comment]
@Riifta Mist spawns a Geth instance, which is the responsible for the current slowness in blockchain download. 

https://github.com/ethereum/go-ethereum/

I'm closing this.

**Comment by Garito** [comment]
Be honest and close this project, dude
Too much complains, no solutions (same questions for months, perhaps years)
