### ISSUE TITLE
Ethereum Mist Wallet - Very Disappointing...

### ISSUE THREAD

**Issue by godman84** [ethereum/mist#3407]
The Ethereum Mist Wallet is garbage. I'm running the 0.9.3 wallet stored on a SSD with plenty of free space on Windows 10, 64 Bit. The wallet hardly ever syncs (Light or Regular mode). For the amount of developers that are dedicated to this project, I'm surprised that you were unable to create something more unique; it's very disappointing. Ether Coins are currently trading at ~450 USD; surely that should be some incentive for you to do better.

I own ARK. Their wallet is far superior than Etherium Mist. Just saying...

**Comment by footloosejava** [comment]
I find it works great most of the time. I have never had a syncing issue. Did you do a fresh sync from scratch after deleting the chain data? Define 'hardly ever syncs'.

**Comment by MaSansky99** [comment]
@footloosejava Congratulations. You must be the one satisfied user. Maybe you could use your knowledge to help the rest of us (almost 900 open issues)

**Comment by inflexionist** [comment]
@footloosejava can you elaborate on "works great most of the time"... do you mean that you can sync 99.99% of the blockchain and then it doesn't work?  are you actually able to sync the entire chain most of the time.  care to tell us what the details of your config are?  Without any real information how are we supposed to perpetuate the use of the Ethereum.  

There are a significant number of potential users willing to get behind this technology and support it by running full nodes but it seems that there is no support from the developers.  As far as i can tell there is total radio silence on the acknowledgment of these problems and issues are closed with no real resolutions suggested.

@footloosejava, are you a developer on the Ethereum project?

**Comment by godman84** [comment]
I'm glad others agree with me. Very disappointing!

**Comment by devcrp123** [comment]
Worst platform EVER! The recommended fee for sending coins out of the mist app and into my desktop wallet is 1 full Ether coin (LOL). The lowest allowed is 0.05 Ether, and the transaction doesn't even work. Now I can't get any of my coins out until they update the app to version 0.9.4. 

Don't get scammed. Wait for the 0.9.4

**Comment by Trophonix** [comment]
I am also having crazy issues. Never syncs (the number keeps going up as if it's syncing slower than blocks are being created) on normal mode, and on light mode it says it's synced but my balances stay outdated no matter what I try.

**Comment by nn111** [comment]
0.9.3 on osx 
Wallet is not syncing in normal or light ... multiple installs and chaindata and lightchaindata deleted ...
Normal is always 100 or so blocks behind  and light does not find peers.
Hope you solve it .

**Comment by thijstriemstra** [comment]
> Ether Coins are currently trading at ~450 USD; surely that should be some incentive for you to do better.

No it's exactly why it's a piece of shit, they already cashed out.

**Comment by pingram3541** [comment]
Crickets...and somehow this currency has #2 position in market cap???  Gawd I hope someone comes along and fixes this soon.

**Comment by daniel723777** [comment]
worse wallet I've ever used...and saying I used it is an overstatement.  as soon as I can locate the eth and erc I put on it....I'll move it and delete this wallet once and for all. you wasted enough of my time

**Comment by alexvandesande** [comment]
We are sorry  about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
