### ISSUE TITLE
Ethers don't appear in my wallet

### ISSUE THREAD

**Issue by 06101970** [ethereum/mist#3408]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by tobiv** [comment]
Check out https://www.reddit.com/r/ethereumnoobies/ they can help you better.
