### ISSUE TITLE
BACKUP option does not use the geth --datadir

### ISSUE THREAD

**Issue by DcyMatrix** [ethereum/mist#341]
Using the '**Ethereum Wallet Version 0.5.2 64bit Binary Download Version on Ubuntu 14.04LTS**'
I am starting geth with the command:

`geth --datadir "/media/whahaha/DATA/.ethereum" --ipcpath "~/.ethereum/geth.ipc" --cache "1024" --maxpeers "150"`

But when using the 'Backup Accounts'.
It will show the `--ipcpath "~/.ethereum/geth.ipc"` directory, and not the geth
 `--datadir "/media/whahaha/DATA/.ethereum"` Where the wallets are actually located.

So people risk backing up the wrong directory if they are not paying closely attention.

**Comment by frozeman** [comment]
I can't know the daatdir you used on the node, from mist... as mist didn't start the node. I would also consider this an edge case, because if you know how to set the datadir, you know what to back up obviously...

**Comment by DcyMatrix** [comment]
@frozeman Understood :-)

p.s: Love the Ethereum Wallet!

**Comment by racer8** [comment]
fair enough - maybe a warning anyway?
