### ISSUE TITLE
Remove Swarm from init process

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/mist#3424]
As Swarm is not live yet, we can pull it from the regular initialization process. We should keep it at hand putting a toggle option at the end of the Develop menu.

### Develop menu
(…) all options we have today
`---------------` (separator)
[ √ ] Enable Swarm

- [x] Remove swarm from the init process.
- [x] Add toggle item on Develop menu.
- [x] Enable `File > Upload to swarm` only if Swarm is on.
- [x] Think of the best way to inform the user if it tries to access a `bzz://` url.
- [x] Persist choice using lokiDB

**Comment by ryanio** [comment]
Sounds good.

I think we'll also want to present the user connection info or errors while enabling. Not sure if we have a good spot for this, or if it warrants a simple pop-up window with the info that then hides upon success. I can play around with something simple after accomplishing the tasks above.

**Comment by evertonfraga** [comment]
Sure thing. 

Thinking of a general solution, we could present a window containing live logs. Aiming for simplicity, we could even fire up a terminal with `tail -f [logfile]` (and equivalents for all OSes). This could be a quick way to display what's happening to the users.

**Comment by AkliOnet** [comment]
A nice terminal ...
