### ISSUE TITLE
How do I contribute translations?

### ISSUE THREAD

**Issue by actuallymentor** [ethereum/mist#343]
Hello,

I'd love to help in translating. Which file or folder do you keep language files?

**Comment by frozeman** [comment]
https://github.com/ethereum/meteor-dapp-wallet/tree/master/app/i18n

**Comment by alexvandesande** [comment]
Also: 
https://github.com/ethereum/mist/blob/develop/interface/i18n/app.en.i18n.json
https://github.com/ethereum/mist/blob/develop/interface/i18n/mist.en.i18n.json
https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/i18n/app.en.i18n.json
https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/i18n/wallet.en.i18n.json
