### ISSUE TITLE
What is the wallet password if you press skip when installing

### ISSUE THREAD

**Issue by mgeth** [ethereum/mist#3432]
What is the wallet password if you press skip in "Protect your account" window when installing? I can not transfer ethers because its asking password which I have never set.

![protect_acc](https://user-images.githubusercontent.com/34536052/33982574-9efb672a-e0b9-11e7-90bd-b74e9a1307a9.png)

Version: `0.9.3`
OS & Version: windows
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4730166

**Comment by tobiv** [comment]
Strange that there even is a Skip button!

**Comment by tobiv** [comment]
Ah I see there is actually no account created. So Skip means "Skip creating account". Go to menu `File` » `New Account` to start over – in this dialog the password is not allowed to be empty.

**Comment by mgeth** [comment]
No, Main account is created successfully even I press "Skip" button. I already transferred funds to main account but I can not send funds to another account because it's asking password.

**Comment by tobiv** [comment]
I assume you have tried with blank password?

**Comment by mgeth** [comment]
Yes

**Comment by mgeth** [comment]
"Wrong password" message when I tried to use blank password

**Comment by mgeth** [comment]
Is there any suggestion how to solve this problem?

**Comment by Stoyvo** [comment]
^ Also seen this issue, ETH is stuck in wallet.

**Comment by mgeth** [comment]
This must be reported as a bug!!!

**Comment by thijstriemstra** [comment]
> No, Main account is created successfully even I press "Skip" button. I already transferred funds to main account

rekt. Nobody seems to think this is an issue, what a total shitshow.

**Comment by ethtester** [comment]
Does this affect previous versions also?

**Comment by mehmetcanbalci** [comment]
Same for me , i choose skip and it created etherbase account , now ether stucked.
Wtf!

**Comment by mehmetcanbalci** [comment]
This is a serious bug !!! so how systems definess default password ? eth stuck in address.
need help from developers

**Comment by dennis97519** [comment]
Should I just delete the keystore for this account with unknown password if I have no ether in it?

**Comment by mehmetcanbalci** [comment]
My suggestion Just delete it and create new one with password that defined
by you ,because Passwordless account will be headache for you once you have
put some tokens in to it.

**Comment by dennis97519** [comment]
Is there any side effects in deleting the account shown as "MAIN ACCOUNT (ETHERBASE)" in mist client? Or is that just the 0th account listed by geth?

**Comment by mehmetcanbalci** [comment]
When you skip password , it assigns somehow. And tokes will be locked if
you deposit to that account

**Comment by danoplack** [comment]
what has worked in the past is to start a geth.exe node in administrator terminal (cmd, powershell, or equivalent) using command line options to change the empty password.
        (https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts)
Alternatively, one might try to unlock it with the Geth command line arguments and just press enter when it asks for the password, this has worked in the past for me but haven't tried it in a long while for I learned to dislodge my head from it very cozy abode deep in my anus prior to using computers after a solid fifth or sixth time thinking I lost all my ETH to a certain conspiracy betwixt my own laziness and a rather familiar beast that many hath named the wallet whom bears a supreme immunity to unlock attempts not unlike the powers endowed to a poop dollar.

**Comment by mehmetcanbalci** [comment]
Need to find out how wallet assings passwords when we choose skip. I tried
geth cli to unlock but noway.

On Dec 29, 2017 12:17 AM, "danoplack" <notifications@github.com> wrote:

what has worked in the past is to start a geth.exe node in administrator
terminal (cmd, powershell, or equivalent) using command line options to
change the empty password.
(https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts)
Alternatively, one might try to unlock it with the Geth command line
arguments and just press enter when it asks for the password, this has
worked in the past for me but haven't tried it in a long while for I
learned to dislodge my head from it very cozy abode deep in my anus prior
to using computers after a solid fifth or sixth time thinking I lost all my
ETH to a certain conspiracy betwixt my own laziness and a rather familiar
beast that many hath named the wallet whom bears a supreme immunity to
unlock attempts not unlike the powers endowed to a poop dollar.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ethereum/mist/issues/3432#issuecomment-354351880>, or mute
the thread

**Comment by evertonfraga** [comment]
Hi all, I'm one of the developers of the project. I've just tried to reproduce this issue without success in the following setups. When skipping it didn't create any account.

- MacOS - mist 0.9.3
- Linux - mist 0.9.3

While trying to reproduce this issue and help you guys, I please ask you to answer this set of questions, so we can outline the issue and move on. Please fill out the form thoroughly.
https://goo.gl/forms/jznmHV6Fpui7Ijds1

Let's move the conversation to this single place:  https://github.com/ethereum/mist/issues/3097

Thank you.

**Comment by JWSV** [comment]
I just ran into this problem today.  I deposited a large dollar amount of ethereum into my wallet that when I installed, I skipped the password creation, Thinking I could enter later when I needed too - big F******* Mistake...Now, the wallet wants a password to send out my ethereum.  I am using windows 7 x64 with wallet version 0.9.3 .

**Comment by jinmiao** [comment]
Me too.

What is the wallet password if you press skip in "Protect your account" window when installing? 
I can not transfer ethers because its asking password which I have never set.
