### ISSUE TITLE
WTF! I have a 150.00 dollars in ETH from my coinbase account and my wallet has not recived it and I'm pissed! Really!?! Hours on end!

### ISSUE THREAD

**Issue by MarkPate2120** [ethereum/mist#3439]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
If you want to move your funds right away, try using MyEtherWallet.com or metamask. 

Currently, when using Mist you have to wait for sync to finish to see/send your funs.
