### ISSUE TITLE
Ethereum-Wallet-linux64-0-5-2 Ubuntu 14.04 LTS send hangs and fails

### ISSUE THREAD

**Issue by forgetso** [ethereum/mist#344]
When trying to send funds the transaction fails and the client loses the connection to the network as the blocks stop syncing. Connection is restored by restarting Mist but Ether total has not changed and funds are not sent.

**Comment by taoteh1221** [comment]
Similar issue on Ubuntu 14.04 LTS / Mist v0.5.2 with an Acer Aspire V3112PC2P6, no issue on my much more powerful desktop machine w/ same setup. Restarting syncs to current block, BUT stops syncing after that...never syncs again at all. Setting up port forwarding on my router 30303 to 30303 for the machine ip address fixed the issue. FYI, my desktop machine is fine with _no port forwarding_, even though running same versions of Ubuntu / Mist.

**Comment by taoteh1221** [comment]
Upon further review at least in my case, it looks like punching a hole through my router for port 30303 only helped temporarily. It seems to be my laptop is not a fast enough CPU (it's a low end model), and it causes the block synchronization to stall permanently after the application is fully running.

**Comment by taoteh1221** [comment]
FYI, geth is syncing ok in the background when this disconnect with Mist happens for me...just Mist does not detect the blocks syncing in geth anymore.

**Comment by luclu** [comment]
Please update to geth 1.4.4 / Ethereum-Wallet 0.7.4 as this issue should be fixed!
I will close for now, but feel free to discuss a solution with me if you still encounter problems!

**Comment by untz** [comment]
I have the latest wallet 0.7.4 and issue is still identical. Ubuntu 16.04 LTS 64bit
