### ISSUE TITLE
Funds transfered to Test Network Account

### ISSUE THREAD

**Issue by ivanminero** [ethereum/mist#3440]
Hello.

I did by mistake a transfer to a test network account and I don't see the funds, is there any way to solve it?.

Thanks.

```
Version: `0.9.3`
OS & Version: osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 1.423.765
```

**Comment by footloosejava** [comment]
First things first. Until someone chimes in here that really knows what they are talking about:

* DO NOT USE YOUR WALLET ON THE LIVE OR TEST NETWORK

WAIT FOR A PRO AND AGREED ANSWER.

That doesn't mean there is hope. Just don't make it worse until you know if/what can be done.

**Comment by footloosejava** [comment]
OK. NOW HERE IS WHAT I THINK. 

You sent it to a test network address. Doesn't matter. You sent it to an address effectively and that means that your funds are lost forever.

I hope you didn't lose much.

**Comment by evertonfraga** [comment]
Hi @ivanminero,

Private keys can be used on whichever network you'd like, as long as the private key file is on the right directory. First head to `File > Backup > Accounts...`

browsing in upper directories you'll find:
```
+-keystore (1)
+- rinkeby
     +- keystore (2)
```

Copy your private key file from (2) to (1). It should then appear on your main net wallet.

**Comment by ivanminero** [comment]
Hi @evertonfraga,

Thanks, I have followed your instructions, I can see now all the wallets in keystone level and displayed in main network, but I still can't see the funds, I have checked in Etherscan and were successfully transferred: https://etherscan.io/address/0x668bf74F782caa83899bb551abAfDC516403F78f

Is there anything else I could do to see the funds?.

Thanks.
Regards.

**Comment by evertonfraga** [comment]
Wait until sync — hint: use the new version to sync quickly.
