### ISSUE TITLE
Okay after two days i finely received ETH to my Wallet, I want to move what i have back to my coinbase wallet but when I type in the send to address i get a red shild and can not send

### ISSUE THREAD

**Issue by MarkPate2120** [ethereum/mist#3441]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by tobiv** [comment]
What's the address? Have you tried copy–pasting it?

**Comment by MarkPate2120** [comment]
Yeah, I did try that. Finally after several logouts and reboots and syncing with the ETH network I was able to make the transfer happen. I sill had to manually type the address in.
