### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by gigamike** [ethereum/mist#3457]
Guys,

I tried downloading Etheruem Wallet Mist version 0.9.3 on Mac. Every time i download/sync its very slow and at the same time when i shutdown my Mac it resets. I already tried deleting the chaindata but didnt work. Ether node Geth 1.7.2 . Network Main Network. Check Sync with Light Client (Beta). Im worried about this one coz there is already someone transferred on account on my wallet but wont reflect coz maybe because of this sync.

Any ideas?

Thanks in advance

**Comment by bechtech** [comment]
same shit!

**Comment by evertonfraga** [comment]
Sorry for that guys, let me reason it. Geth, the software that syncs with the blockchain under the hood downloads the block headers and over 70M state entries, similar to database records.

The current behavior is: stop at `CURRENT_BLOCK - 100` while downloading those millions of records. I know it's not feasible for a user that only wants to make a few transactions, and we're actively working on better solutions. 

Consider using http://myetherwallet.com if you need to make transactions in a hurry.

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more informations.
