### ISSUE TITLE
Mist fills all my hard disk mac capacity , can I use my json file in other Lighter wallet? how? 

### ISSUE THREAD

**Issue by dingxiaomai** [ethereum/mist#3459]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: /osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
Yes, go to `Develop > Sync with Light Client`.

**Comment by nadimaj** [comment]
Can someone please answer dlingxiamomai's other question?

> can I use my json file in other Lighter wallet? how?

Thanks

**Comment by dingxiaomai** [comment]
Thanks nadimaj. 
Hope somebody can reply me this question. :)

**Comment by nadimaj** [comment]
@dingxiaomai 

I have tried everything now to make sync work reliablly. Forget about ending this sync. End this nightmare by uninstalling Mist forever (keep your keys obviously!!!)

You can run MyEtherWallet locally and not have to ever send your key or type a password online. Download the offline version from here: https://github.com/kvhnuke/etherwallet (Click clone or download - the green button)

In the dist folder, launch index.html and import your wallet file from one of the top options. Your wallet type is JSON/keystore. Enter your private key password and et voila. You don't even need to be online. You can use etherscan.io to check any transactions you make. No blockchain to sync!

Good luck

**Comment by evertonfraga** [comment]
1. Go to `File/Accounts > Backup > Accounts`
2. Copy/move the json files from that directory
3. Follow the instructions on https://myetherwallet.com
