### ISSUE TITLE
just update new mist wallet 10.0 and keep showing passward error

### ISSUE THREAD

**Issue by goodstuff001** [ethereum/mist#346]
just update new mist wallet 10.0 and keep showing passward error. i just sent 5 hours ago and it is good but after i udate the new 10.0 mist wallet my password is wrong. will there be a fix for this bug? thanks

**Comment by alexvandesande** [comment]
is this the import presale or when sending and unlocking accounts?

**Comment by luclu** [comment]
Please have a look at this and report back here! #669
I will close this for now. Feel free to continue to discuss here!
