### ISSUE TITLE
transaction dont get confirmations after hours

### ISSUE THREAD

**Issue by sakis123** [ethereum/mist#3460]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

Version: `0.9.3`
OS & Version: windows 10
Node version: `geth 0.0.0` unknown
Number of blocks synchronized: all

i make a send transaction but after many hours i dont get any confirmation 
i make the same transaction after 2 hours with the max fees but still nothing no confirmations
what should i do?

**Comment by SoranM** [comment]
I am having the same problem

**Comment by ymene** [comment]
I had the same problem and managed to solve it after a lot of trying. You can find a step by step guide on how to fix this issue [here](https://steemit.com/ethereum/@crusam/guide-on-how-to-deal-with-stucked-ethereum-transactions), together with an explanation, why this is happening in the first place. Its a bit fiddly, but hopefully it helps with your situation as well! Let me know there, if the guide helped you!

**Comment by SoranM** [comment]
Did not work for me, It gave me a hash, but when checking, nothing is shown, the hash does not work, even after 10 mins, its still not there, cant send anything from this ethereum wallet or geth....

**Comment by sakis123** [comment]
after days the transaction made it self , suddenly i have 1100 confirmations from the first transaction i made
