### ISSUE TITLE
0.9.3 Time not synced - Linux Fail

### ISSUE THREAD

**Issue by pingram3541** [ethereum/mist#3461]
Not all distros use "ntp" service, please fix this.

```
xxxxxxx@kali:~/# timedatectl status
    Local time: Tue 2017-12-19 14:14:17 PST
    Universal time: Tue 2017-12-19 22:14:17 UTC
    RTC time: Tue 2017-12-19 22:14:18
    Time zone: America/Tijuana (PST, -0800)
    System clock synchronized: yes
    systemd-timesyncd.service active: yes
    RTC in local TZ: no
```

**Comment by evertonfraga** [comment]
Hi @pingram3541,

Mist has to perform this check so that Geth doesn't "silently fail" when the clock is not adjusted (it's their requirement). We've created a temporary flag to run on systems that do not rely on NTP.

Run mist with `--skiptimesynccheck`to bypass the check.

**Comment by pingram3541** [comment]
It's not performing a very reliable check that my system's time is in sync.  That is the problem, not me not knowing to use a custom flag every time to bypass a poorly implemented check.

This time sync issue is being reported to directly affect other major functions of the wallet such as syncing and peer connections and needs to be addressed sooner than later.

**Comment by jacksenechal** [comment]
This issue is similar to https://github.com/ethereum/mist/issues/583. I'm experiencing the described issue when I try to run mist on Arch.

I've submitted a [PR](https://github.com/fjl/os-timesync/pull/9) to update the os-timesync node module that mist uses to detect whether the time is synced.

CC @alexvandesande @luclu

**Comment by evertonfraga** [comment]
@jacksenechal thanks for the contribution there. I'm following it and will update it asap on Mist.

**Comment by evertonfraga** [comment]
Thanks for your contribution @jacksenechal. It'll be in the next Mist version.

**Comment by evertonfraga** [comment]
It is now live! please update :)
