### ISSUE TITLE
Node Crashed

### ISSUE THREAD

**Issue by mikerotman** [ethereum/mist#3462]
I received this when I try to run Etherium Wallet: 

Node type: geth
Network: main
Platform: darwin

...I1219 16:32:17.761186    2454 database.go:71] Alloted 433MB cache to /Users/(NAME)/Library/Ethereum/chaindata

**Comment by evertonfraga** [comment]
It looks like your Geth node was standing still and Mist considered it have timed out. 

Please try updating to the latest software and trying again. Thank you.
