### ISSUE TITLE
mist hangs at starting screen "Started Swarm"

### ISSUE THREAD

**Issue by filiprashev** [ethereum/mist#3465]
3 days ago I installed the new mist 0.9.3 and after installation shows sreen "Started Swarm" and it hangs there.

Before that I used 0.9.2. and it was ok. But now even the o.9.2 is not opening.

![started swarm](https://user-images.githubusercontent.com/32187124/34209649-b1f08e6e-e59b-11e7-91d3-8dd67ba16fd7.png)

```
Version: `Mist-installer-0-9-3
OS & Version: windows 10. 64bi




When creating this issue, if possible add the following to your report:
- Screenshots
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
- Log files
  - Go to the menu `Develop -> Show log files`
  - Zip and upload `all.log` and any other appropriate `category/*.log` files

 -->

**Comment by haniewais** [comment]
Hello, I'm also getting this error. Running Mist 0.9.3 on OSX

In the console I get an error: Failed to load resource: net::ERR_FILE_NOT_FOUND
/sockjs/info?cb=wrvj7chyy9

As a note, I have the sync with lite client turned on.

Attaching screen shots

![screen shot 2017-12-20 at 4 05 17 pm](https://user-images.githubusercontent.com/13974295/34231183-953942b6-e5a0-11e7-8775-26b0e564f1dc.png)
![screen shot 2017-12-20 at 4 05 34 pm](https://user-images.githubusercontent.com/13974295/34231184-95489216-e5a0-11e7-8542-87bf0bfd9cff.png)
![screen shot 2017-12-20 at 4 07 15 pm](https://user-images.githubusercontent.com/13974295/34231185-9557590e-e5a0-11e7-8ba1-b96407c09749.png)

I waited a little longer and it finally popped up with the "Launch Application"

**Comment by UGatgithub** [comment]
Same for me - I think it is an issue appearing due to the fact that there are not enough peers for the light client mode available, so once a peer to peer connection is established, the Launch application will appear. See also: https://github.com/ethereum/go-ethereum/issues/15454
