### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by kingsleyhk** [ethereum/mist#3469]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

Hello,

I just installed the Ethereum Wallet and already took 2 days for sync. But it stopped on downloading chain structure 36,296 of 44,019 more than 10 hours. Attached photo fyi.

May I know how can I fix it please?

Thank you.

Cheers,
Kingsley
![screen shot 2017-12-21 at 4 59 24 pm](https://user-images.githubusercontent.com/34738902/34250765-d4106662-e678-11e7-8fe5-8e080efe5a7d.png)

```
Version: `0.9.3`
OS & Version: MacOS Sierra version 10.12.6
Node version: `geth 0.0.0` 
Number of blocks synchronized: 4,767,056 of 4,770,149
```

**Comment by bwidmann** [comment]
Follow 
https://github.com/ethereum/mist/wiki#start-the-node-manually
to get better  debug info.

Open firewall port 30303 on both tcp&udp

**Comment by Tommyfare** [comment]
i have the same problem. i cant sync for days. 
firewall is opened and i tried to start the node manually. nothing helps.

**Comment by genosse** [comment]
Same shit, bro. It does not work for me too. Complete halt just for 100-200 last blocks. I've tried to remove and reinstall everything, tried to start it on different PCs.
Nothing helps. Developers, could you explain this?

**Comment by Vikvek** [comment]
I found something!
http://puu.sh/yMIZY/0f37b51130.png
Synch ended by other party, so node timeouts us

**Comment by NorbertSandor** [comment]
Same issue here :(

**Comment by evertonfraga** [comment]
@genosse @Vikvek @NorbertSandor 

Sorry for that guys, let me reason it. Geth, the software that syncs with the blockchain under the hood downloads the block headers and over 70M state entries, similar to database records.

The current behavior is: stop at `CURRENT_BLOCK - 100` while downloading those millions of records. I know it's not feasible for a user that only wants to make a few transactions, and we're actively working on better solutions. 

Consider using http://myetherwallet.com if you need to make transactions in a hurry.

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more informations.
