### ISSUE TITLE
Issue with mist wallet 0.5.2

### ISSUE THREAD

**Issue by keuge** [ethereum/mist#347]
I get some kind of a bug.
Been trying to send eth from contract wallet to one of owners wallet and get approval requests that copying each other.
http://snag.gy/W5Wr2.jpg 
And i already typed second approval from owners wallet and now its wanted something more and nothing happening.
Update!
Its been 5 hours till its started and still this approving windows stand here.
I cant do anything now. I cant sent eth from contract wallet to another wallet because all the requests with sending ethere stuck in queue with 0 approving iterations. I have already clicked 10 times to button approve and aprroved with owner wallet and each time it withdrawn from me fee for this operation but still nothing fixes.
http://snag.gy/DNHLz.jpg 
Please help!!

**Comment by alexvandesande** [comment]
Try restarting your wallet please

**Comment by keuge** [comment]
Done that about 15 times. Nevermind. I was just transferred all my eth from contract wallet to account wallet back and created again new wallet contract.

I hope this will never happend.

**Comment by pacifics** [comment]
The same problem for me. Three days and I am still waiting for the approval of a transfer from the wallet.

**Comment by luclu** [comment]
Could you kindly update to the latest version 0.7.4 and check if you still encounter this issue?
