### ISSUE TITLE
Unusual NAT-PMP traffic and can't find nodes

### ISSUE THREAD

**Issue by muhfugen** [ethereum/mist#3470]
<img width="1680" alt="screen shot 2017-12-21 at 4 36 29 pm" src="https://user-images.githubusercontent.com/31422329/34277911-64c87c5a-e66d-11e7-84fd-d3046757ad8e.png">
```
Version: `0.9.3`
OS & Version: Windows Server 2016 build 1607
Node version: `geth 0.0.0` Who knows, you failed to set the appropriate metadata for the program so it shows nothing in properties. There is a folder in the same directory with the version 1.7.2
Number of blocks synchronized: 0
```

Ethereum Wallet is unable to find peers. My firewall by default blocks all outgoing connections, i've created whitelist rules for outbound connections to ports TCP/30303 and UDP/30303. Besides these well documented requirements I've noticed it also tried to create HTTP/HTTPS connections to `api.github.com`, `http://raw.githubusercontent.com`, `http://gethstore.blob.core.windows.net`, `http://min-api.cryptocompare.com` and `http://cryptocompare.com`. I created URL filter rules to permit access to these sites.

The computer it is running on has 3 NICs, two of which are not connected to networks with routes to the internet (10.12.7.0/24 and 10.11.0.0/16), and one of which has a route to the internet the internet (10.5.0.0/16). On my firewall I can see that it is trying to send traffic from its NIC in 10.5.0.0/16 to 10.11.0.1 with the destination port of UDP 5351. 

If it matters the gateway for the 10.5.0.0/16 network is a Cisco Firepower Threat Defense cluster and the 10.11.0.1 box is a Cisco Catalyst 3750E. Neither supports NAT-PMP.

Why is it trying to communicate to a non-existant address with NAT-PMP? Does it require me to manually create incoming NAT rules? And why am I unable to sync with other nodes? Is it getting confused as to which NIC to use even though two of them don't have gateways assigned?

Attached is a screenshot of the firewall log.

**Geth console**
```
SourceSansPro-ExtraLightIt.otf Failed to load resource: net::ERR_FILE_NOT_FOUND
/sockjs/info?cb=4zujfp9p0p Failed to load resource: net::ERR_FILE_NOT_FOUND
C:\Program Files\Ethereum-Wallet\resources\app.asar\modules\preloader\include\consoleLogCapture.js:40 Connect to node... @ file:///C:/Program%20Files/Ethereum-Wallet/resources/app.asar/interface/wallet/f436c0013b65de4b957bfca3c6a86082c1d23f0e.js:329:211)
f436c00….js:329 startNode: 33.199951171875ms
f436c00….js:187 Uncaught invalid address
```

**node.log**
```
INFO [12-21|16:12:20] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9
INFO [12-21|16:12:20] Allocated cache and file handles         database=F:\\Ethereum\\geth\\chaindata cache=1024 handles=1024
INFO [12-21|16:12:22] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Engine: ethash}"
INFO [12-21|16:12:22] Disk storage enabled for ethash caches   dir=F:\\Ethereum\\geth\\ethash count=3
INFO [12-21|16:12:22] Disk storage enabled for ethash DAGs     dir=C:\\Users\\Administrator.BIXNOOD\\AppData\\Ethash count=2
INFO [12-21|16:12:22] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [12-21|16:12:22] Loaded most recent local header          number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [12-21|16:12:22] Loaded most recent local full block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [12-21|16:12:22] Loaded most recent local fast block      number=0 hash=d4e567…cb8fa3 td=17179869184
INFO [12-21|16:12:22] Loaded local transaction journal         transactions=0 dropped=0
INFO [12-21|16:12:22] Regenerated local transaction journal    transactions=0 accounts=0
INFO [12-21|16:12:23] Starting P2P networking 
INFO [12-21|16:12:26] UDP listener up                          self=enode://739b55456ef1d3a04c1b0b76e2ca2bcbee5c076b147dff4cce9b4e557700acd2ecf678dec15c1b1ed408e0cb6832d38741365c7b2f9b7c6837379e3bbf12d042@[::]:30303
INFO [12-21|16:12:27] RLPx listener up                         self=enode://739b55456ef1d3a04c1b0b76e2ca2bcbee5c076b147dff4cce9b4e557700acd2ecf678dec15c1b1ed408e0cb6832d38741365c7b2f9b7c6837379e3bbf12d042@[::]:30303
INFO [12-21|16:12:27] IPC endpoint opened: \\.\pipe\geth.ipc 
```

**Comment by muhfugen** [comment]
After leaving it running for a while, it found 1 peer, transfered ~1% of the blocks, then lost the peer and stopped.

**Comment by evertonfraga** [comment]
Hi @muhfugen, thanks for the detailed report.

That "Geth console" is actually the Wallet stdout. You can see the reason for unsuccessful connection attempts by starting geth manually with an increased loglevel.

Example: 
`geth --cache 2048 --verbosity 4` (or verbosity 5)

Furthermore, this repository takes care of the desktop application that manages Geth. You should report on their repository to have accurate answers about networking layer.
https://github.com/ethereum/go-ethereum/issues


Thanks.
