### ISSUE TITLE
been months and still can't sync.

### ISSUE THREAD

**Issue by kallan4446** [ethereum/mist#3471]
When I first tried months ago the sync would stop at 4,370,000 and despite removing chaindata server times it would never ever get beyond that point.

A couple of weeks ago A new version was released saying the issued had been fixed.

Now all I get is one more block. It now stops at 4,370,001 instead of 4,370,000. 

I have of course tried deleting the chain data a couple of times and I always run into the same issue at the same place.

How can this be so weak? I thought this was the wallet to use. Is there a better Ethereum wallet as this was is driving me nuts.

Kerry

**Comment by dgn127** [comment]
I'm on a fully updated Mac trying to use the Mist Wallet (newest version)

I'm having the same problem, a couple months ago I was able to get the wallet up and running AND OPEN, by removing the chaindata. Actually there was a possibility to view logs through the tabs but that is now gone. So I have removed the chaindata through the Library Folder. 

Mist will:
 startup 
connect to peers
download chaindata 
at the end of downloading it will say it is connecting to peers
then hang. If I click the Launch Application it will freeze. Before it would download chaindata after launching the application.
I can verify my wallet contents on Etherscan.io but I need to get my tokens out of this wallet.

Please fix this problem!!!
Thank you,
~d

**Comment by darbla76** [comment]
I have tried to create a wallet contract on Ethereum Wallet but it has been days since i created it and it says it is still "creating..."
the number of blocks left quite often changes and looks to be almost complete, but then it restarts - like now it is just sitting on 4822 left with 0% downloaded.

the worst part is i already transferred some ETH to this wallet from my Exodus wallet thinking it would be set up in time.

Any advice on how to fix this - if that's possible.  If I hadn't already transferred I would just delete it entirely as it's ridiculous.

**Comment by genosse** [comment]
Same shit, bro. It does not work for me too. Complete halt just for 100-200 last blocks. I've tried to remove and reinstall everything, tried to start it on different PCs.
Nothing helps. Developers, could you explain this?

**Comment by powpig** [comment]
The way I got around this is to run it in Light Mode.

Download and install the latest version of Geth if you haven't already.
Go to the Geth file and Create a Shortcut.
Open the Properties of the Shortcut and for Target, paste in:
**"C:\Program Files\Geth\geth.exe" --light**
Double click the Shortcut and run the Light Mode.
Let it go for a few minutes (sometimes a bit longer) until the Geth window is loading blocks.
Then just open the Ethereum Wallet and you should be sync'd or at least able to send & receive as if you are sync'd.
This works for Windows, no idea on Macs.

**Comment by genosse** [comment]
Does not work for me, I am still waiting to sync, it just stucks with "Looking for peers..." message

**Comment by powpig** [comment]
genosse  -  If you're responding to me, sounds like you're not following the directions I posted above.
If the Geth is loading blocks, then you are connected to peers, otherwise it wouldn't be loading blocks.  
Just disregard the "Looking for peers..." message and launch the Ethereum Wallet.

**Comment by genosse** [comment]
Finally light mode worked for me

**Comment by genosse** [comment]
Sorry. It does not work after restart. Same message:
`ERROR[12-24|03:28:36] Failed to retrieve current release       err="can't fetch trie key 80bace31c97b672967ed85d1050bcdab68cf944f2dec7f80c53e4e34feb79b6e: no suitable peers available"`

**Comment by NorbertSandor** [comment]
I can sync but I have serious problems with syncing as well.
Syncing seems to be a very I/O intensive operation.

First I tried to store the block chain data on an SSD. It was a big mistake, it resulted in writing of 15TB+ data on the SSD! I stopped it because it would have definitely killed the SSD.
Then I tried with a HDD as well but it is very-very slow and seems to read and write way too much. It seems it will never complete...

**Comment by nadimaj** [comment]
https://github.com/ethereum/mist/issues/2466#issuecomment-353246353

**Comment by brainyclown10** [comment]
OMG @powpig's solution worked for me!! I was stuck at like 128 blocks remaining and after downloading Mist and running it, my Wallet and Mist were up to date in around 10-20 minutes. Looks like there might be an issue with Ethereum Wallet that doesn't exist with Mist.

**Comment by lowlanda** [comment]
Same issue here, light mode not working. It worked a week ago and I was able to transfer ETH from my mining pool. Today it's broken again it seems.

@powpig 
It tries to download entire blockchain, but it's doing something now at least. Should I leave geth window running in background when running Ethereum Wallet?

Cheers

**Comment by lowlanda** [comment]
Got within 9 blocks of the end, then stopped

**Comment by nadimaj** [comment]
Yawn. I don't know why people bother. Since I stopped using the official wallet, I've resolved my battle with constipation.

**Comment by lowlanda** [comment]
MyEtherWallet you reckon? At this point I'm desperate enough to get adventurous.

I read through all the warnings etc on their website, scared me if I'm honest. But, if it's the only way to access my locked up ether, then what choice do I have..

**Comment by nadimaj** [comment]
@lowlanda I faced the same dilemma as you about online security. I think people who trust the online version are too trusting. You can run MyEtherWallet locally and not have to ever send your key or type a password online. Download the offline version from here: https://github.com/kvhnuke/etherwallet (Click clone or download - the green button)

In the dist folder, launch index.html and import your wallet file from the "Send Ether/Tokens" option. Your wallet type is JSON/keystore. Enter your private key password et voila and begin using your wallet. You can use etherscan.io to check any transactions you make. No blockchain to sync! Happy days, and happy shitting!

**Comment by lowlanda** [comment]
I'm reading through your instruction in other thread. So far so good.

What's your ETH address, I'll send you small donation

Thanks!

**Comment by nadimaj** [comment]
Can I ask for something in exchange? Please do me a favour and video-capture your actions using BandiCam or Debut and upload to YouTube for others to see with some good tags. Let's help the world!

**Comment by lowlanda** [comment]
I'm testing it now, and will at least link people to your solution.

Silly question.. do I need to do anything once I'm finished using MyEtherWallet? For some reason I feel like I'm leaving a door open lol

**Comment by nadimaj** [comment]
No, just close down. I'm putting the whole thing (along with my keys) on one or more external drives and locking away.  I know the feeling, using MEW certainly challenged my concept of Blockchain.

**Comment by lowlanda** [comment]
Cheers.

Bit scary though, 20mins and still "pending", no confirmations. I'm certainly missing that little screen from Ethereum Wallet atm!

**Comment by nadimaj** [comment]
I'd guess you're sending to one of the exchanges and suffering because they need 6 billion confirmations or something. My first transaction took a while too

**Comment by lowlanda** [comment]
Oh, I think made the gas price way too low. Not used to this yet. Thought I was paying 0.000021 TxFee, but actually paying 0.00000002

Oops

**Comment by lowlanda** [comment]
Ok everyone, this solution worked ok! Just make sure you set your gas properly ;)

(fyi, I did successfully sync Ethereum Wallet using --fast, but now I get "unable to connect to socket: timeout" errors when trying to send funds. Absolutely useless...)

Big thanks to nadimaj!

**Comment by evertonfraga** [comment]
Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.
