### ISSUE TITLE
Add instructions to install dependencies on Linux

### ISSUE THREAD

**Issue by PanderMusubi** [ethereum/mist#3473]
Please, add to the README that if you would like to run the application from a zip file with a build for Linux, do first:

    apt-get install libgconf2-4

Only then it is possible to run `ethereumwallet`

- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: linux
Node version: `geth 0.0.0` (got auto installed)
Number of blocks synchronized: 0
```

**Comment by 4356Surf** [comment]
Thank you for this!

**Comment by evertonfraga** [comment]
Done, thanks
