### ISSUE TITLE
How to Import Account?

### ISSUE THREAD

**Issue by powpig** [ethereum/mist#3475]
I'm running the Light Client Mode for my Etherium Wallet.
I want to Import Account, an ETH wallet address I have elsewhere and control the private key to.
Under File up top, I have an option for Import Account but it's grayed out and unclickable.  
Next to it is Ctrl + I but nothing happens when I try that.
Is there some way to activate this option so I can Import my Account or is there some other way to do it, perhaps by adding it manually to the Backup file?

Thanks

``
Version: `0.9.3`
OS & Version: windows10
Node version: `geth 1.7.3 
Last block synchronized: 4777006
[No] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

**Comment by crichez** [comment]
You should be able to move your backup straight to your keystore directory. On Windows, it will be located at `C:\Users\<username>\AppData\roaming\Ethereum\keystore\`

If you want to move it graphically, run `%appdata%` and you can navigate to that directory, then drag & drop.

I'm not sure why the option was disabled in your UI, so there might be something else going on, but this is worth a shot!

**Comment by powpig** [comment]
Thanks for the suggestion but though I have the Private Key, I don't have an entire file like the others in that Keystore Directory.

**Comment by Tri125** [comment]
I have the same problem. I followed the instructions [here](https://ethereum.stackexchange.com/questions/465/how-to-import-a-plain-private-key-into-geth-or-mist). The account is successfully imported with Geth but when I launch Mist the account isn't there.

**Comment by evertonfraga** [comment]
The Light Client is still experimental. please disable it for a moment (`Develop > [x] sync with the light client`), import, then enable it again!

Thank you

**Comment by Tri125** [comment]
Please actually look into this issue before closing. This isn't related to the Light client.
