### ISSUE TITLE
Certificates are stored on the users harddisk in plain text

### ISSUE THREAD

**Issue by uvoz** [ethereum/mist#3481]
We noticed on both mac and linux machines that certificates are stored in plaintext.
To our opinion, this is a serious security issue that must be addressed.
This is as unsafe as one can imagine and sure way to lose all your ETH on a rainy day!

Version: all
OS & Version: linux/osx

```

<!--

Check the already existing issues to keep duplicates at a minimum.


You'll find possible solutions for these common issues below on Mist Wiki: https://github.com/ethereum/mist/wiki.

- Ether is not shown in the wallet
- I send ether to the wallet contract but it doesn't show up
- Mist is synchronized but is stuck during the last part
- "Your computers time is out of sync!" error
- Unable to find peers
- My transaction is not confirmed
- Account can't be unlocked
- Unable to import pre-sale wallet
- Bind address already in use


When creating this issue, if possible add the following to your report:
- Screenshots
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
- Log files
  - Go to the menu `Develop -> Show log files`
  - Zip and upload `all.log` and any other appropriate `category/*.log` files

 -->

**Comment by tonyp12** [comment]
Are you talking about the keystore file?
They are encrypted with the password you used when you created it.
So for some to hack it, the would need that file AND your password,
brute force a password probably would take years.

**Comment by uvoz** [comment]
A happy 2018 tonyp12! This must be one of the reasons why half the planet is buying a Trezor.
Your private keystore is perfectly safe even when exposed because it would take a million years to solve a couple of primes. Would you publish your keystore-file here to give it a try?

Thanks for your answer. I feel a bit safer now,,
