### ISSUE TITLE
Token Creation - Tx Unconfirmed for 15 days

### ISSUE THREAD

**Issue by eduinvestor** [ethereum/mist#3482]
Hi,
I created a smart contract to create my own token on 9th Dec, but it hasn't been confirmed yet.
Can I accelerate the transaction or cancel it and send it again with a higher fee?

Version of Ethereum Wallet: 0.9.3
OS: Windows 10
My Wallet: https://etherscan.io/address/0xfb62f0881162e31b92e71f47c7eb89bef4ed3baf

![tokenunconfirmed1](https://user-images.githubusercontent.com/30580652/34327773-7d85ff76-e8cd-11e7-9220-8a74afc258a2.PNG)
![tokenunconfirmed2](https://user-images.githubusercontent.com/30580652/34327774-7da47ae6-e8cd-11e7-9760-80644532241c.PNG)

#

**Comment by evertonfraga** [comment]
It seems you managed to create contracts. Should you still run into trouble, get in touch.

**Comment by navaid9** [comment]
I created a smart contract to create my own token I try it before it hasn't been confirmed yet.
Can I accelerate the transaction or cancel this because tell me the right solotion

**Comment by eduinvestor** [comment]
Yes, I managed to do it in my 4th try
