### ISSUE TITLE
Wallet missing after starting computer after several months

### ISSUE THREAD

**Issue by Sciparon** [ethereum/mist#3483]
```
Version: `downloaded 6th of March`
OS & Version: windows
```

Hi everyone,

now part of the group of people who have lost their wallet/are scared they lost it. I'd like some help with reconstructing what might have happened. The situation does not make sense to me as there are two wallets involved, and I wonder if they are linked by any chance.

Here's the background:

I bought some ether beginning of March and installed the Etherum Wallet on my win 7 laptop. Downloaded the whole blockchain, transferred the ether on it. Did a backup of the wallet. 
Afterwards I have not used the laptop again until a week ago. 

Now after a while, naturally, I wanted to check if everythings alright and turn the laptop on. Then 

1) The Ethereum Wallet had some weird crash, took a while to start again and I was shocked to see that my account wasn't there anymore.

2) I restored the account with my json file, but the wallet was empty. https://etherscan.io/address/0xb151c4770357227534e861d2d283f1d613c1C776

3) I checked the transfer website and discovered that I transferred the Ether when I bought it to another address, not the one for which i have the json file:
https://etherscan.io/address/0xfa32d49ff74c51b5fe380604db0dd166eb6a065d
This is not a contract wallet, correct?

Buuut: Here's the thing, I can't recall creating a second account for my ether transfer. I also wonder why I would have done this anyway if I had an original wallet? Maybe one of you has a clue. Also there was no json file or any backup whatsoever on the harddrive related to the address that contains the ether. Could it never have been backed up if i didn't do it explicitly? If so this is ridicolous.

I do not have a JSON or any other backup of this second wallet, but I wrote down a password. If there's no JSON or key though I assume that I cannot get it back, even with the password - is that correct?

Thanks for anyone who might have a clue, excuses for my sh*tty memory!

**Comment by cryptojunky** [comment]
Well the wallet that has your ether was transferred into the wallet 284 days ago, does that sound about the time you first got your ether?

Check here to see if your backups are in your keystore folder ( make sure you checked off view hidden files and folders:

C:\Users\YOUR_USER_NAME\AppData\Roaming\Ethereum\keystore

Did you back up to a external harddrive or usb thumb drive, or somewhere on your pc the original before you crashed?

It looks like when it crashed it or you may have started with a fresh install of ethereum replacing your keystore file with a new one that is showing 0 balance and transactions. If you have your backup from your original address drop it in the keystore folder in path above and restart ethereum.

**Comment by tonyp12** [comment]
If still not finding it use Recuva deepscan to find a file UTC--
If that fail, use Recuva Scan Contents.. and look for string {"address":
Use Win10 cmd find "crypto" filename , to view that part it if it's now hiding in large file that "overwritten" it.

**Comment by numero41** [comment]
Hello, could it be related to this issue?
https://github.com/kvhnuke/etherwallet/issues/1528

**Comment by numero41** [comment]
https://github.com/kvhnuke/etherwallet/issues/1539

**Comment by evertonfraga** [comment]
I can see there were some transfers out of the original account. Glad that worked.

**Comment by MissKV** [comment]
i can get right way to search in Racuva? what kind o doc shell i looks for? thank you
