### ISSUE TITLE
Pls help me to check why cant i get my ETHER in Mywallet

### ISSUE THREAD

**Issue by jingkehan** [ethereum/mist#3485]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows8.1
Node version: `geth 1.7.0` 
Number of blocks synchronized: 4,792,807
```

**Comment by cryptojunky** [comment]
Did you check you wallet address on etherscan.io
Is your wallet synced with the network?

**Comment by jingkehan** [comment]
Yes, I can see my ETH address on etherscan.io .
I can't sync with the internet,it's always show me 100block left ,peer number is zero!
Is there any way let sync quickly and completed?
I'm in China.

**Comment by bechtech** [comment]
0.9.3 这个win版本有问题，总是到最后差不多永远同步不了。以前版本没这个问题。

**Comment by cryptojunky** [comment]
There are many complaints of not fully syncing. I have seen same issues too. You can try to sync with light mode. Be patient for it to start. it will sync.

**Comment by jingkehan** [comment]
OK....give up....
Useing Keystore file in myetherwallet.com
Now I can see my ETHER，thanks everyone.
