### ISSUE TITLE
please kindly check the "Config folder" on macOS

### ISSUE THREAD

**Issue by WillZhuang** [ethereum/mist#3487]
```
Version: `develop`
OS & Version: osx
```

in page [https://github.com/ethereum/mist](https://github.com/ethereum/mist), please kindly check he Config on macOS below:
==================================
Config folder
......

macOS ~/Library/Application\ Support/**Ethereum\ Wallet**

......

==================================

**Comment by evertonfraga** [comment]
Hello, what is the actual issue? Please feel free to reopen or create a new one, with more details. 

Thanks.
