### ISSUE TITLE
I sent my bitcoin to a temporary address which never transfer it in my ethereum wallet

### ISSUE THREAD

**Issue by diegobutti** [ethereum/mist#3488]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by 4356Surf** [comment]
This same thing has happened to me. Setting up an ubuntu box now rather than trying to run this on windows system.

**Comment by alexvandesande** [comment]
Do you meant shapeshift/ changelly? Contact them about your bitcoins.
