### ISSUE TITLE
Malwarebytes and Wallet 0.5.2 (Beta 10)

### ISSUE THREAD

**Issue by Daruhshie** [ethereum/mist#349]
Not sure where else to ask this question, so I'll drop it here. Yesterday I installled the Wallet 0.5.2 (Beta 10) for windows. Malwarebytes keeps blocking geth.exe on inbound and outbound ports. The wallet however works just fine sending and receiving ETH. Souldn't the wallet just not work if those ports are blocked? Should I add geth.exe to the exceptions or doesn't this matter? Thanks in advance.

**Comment by luclu** [comment]
Thank you for reporting!
It got pooled over here: https://github.com/ethereum/mist/issues/573
I will close this for now.
