### ISSUE TITLE
JNT Token

### ISSUE THREAD

**Issue by rranjan27** [ethereum/mist#3491]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows
Node version: `geth 1.7.2` 
Number of blocks synchronized:1,501,445
```
I have transferred JNT token to my wallet, though Etherscan detects correctly the number of JNT tokens my wallet has, but I cannot see the tokens under custom contract. I have added JNT contract address and as explained in their medium article. Please help!!

**Comment by evertonfraga** [comment]
Hi @rranjan27, you have to be fully synced with the network in order to see updated balances.
