### ISSUE TITLE
money did not come in the purse

### ISSUE THREAD

**Issue by reloosave** [ethereum/mist#3493]
https://etherscan.io/tx/0xc242e60b97c96bb7f04f8a57752865564828b8c2892e51f5b863b3f639db4357
0xd54543C3aa710002F398cA80b252D1Cd48B116DB
![tcdbu3wtln8](https://user-images.githubusercontent.com/34959778/34454632-4c68f2ec-ed80-11e7-9709-4518a1e129db.jpg)

money did not come in the purse

**Comment by evertonfraga** [comment]
You have to be in sync with the network in order to see correct balances.

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.
