### ISSUE TITLE
Application Won't Launch

### ISSUE THREAD

**Issue by PlantDr430** [ethereum/mist#3494]
- [X ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.1` & 0.9.3
OS & Version: windows 64, Pro
Node version: `geth 1.7.3` 
Number of blocks synchronized: 4,822,853
```
I am using Mist 0.9.1 and I have tried 0.9.3 on Windows 10 Pro and have last mined 4,822,853 block. However, when I try to click "launch application" nothing happens
I can't access the Mist UI, even waiting for multiple hours after clicking "launch application". Can anyone help me

![image](https://user-images.githubusercontent.com/29610303/34454938-9628ef8e-ed32-11e7-83a6-d164c92c4d48.png)

**Comment by slavkosky** [comment]
I'm having this exact problem, same version (latest official release), windows 10 Creators

**Comment by lowlanda** [comment]
Ethereum Wallet is broken atm.

If you need to access/send funds, see issue #2466 and follow the instructions about using MyEtherWallet

**Comment by evertonfraga** [comment]
Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.
