### ISSUE TITLE
ERC-20 tokens is not shown in the wallet

### ISSUE THREAD

**Issue by AndrewStones** [ethereum/mist#3495]
- [X] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: osx
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4824361
```

Have a problems with receiving ERC-20 tokens from Bankex to my Mist Wallet. When I add a custom BKX token, zeros appear next to it. The BKX tokens also did not shown in my wallet. Etherscan says that tokens has already transferred to my account 1 day ago. 

<img width="932" alt="2017-12-30 12 26 43" src="https://user-images.githubusercontent.com/34959860/34454844-b77030a6-ed84-11e7-9404-ff207d9d2539.png">

<img width="1065" alt="2017-12-30 17 07 27" src="https://user-images.githubusercontent.com/34959860/34454884-58fd5d04-ed85-11e7-90cf-d8b02a511640.png">

<img width="988" alt="2017-12-30 17 20 14" src="https://user-images.githubusercontent.com/34959860/34454912-c80e4b90-ed85-11e7-9bcd-47cae555e008.png">

The test shows failures in
**Permissions / web3.eth.accounts:**
Cannot read property 'accounts' of undefined
Cannot read property 'getAccounts' of undefined
web3.createBatch is not a function
**Permissions / web3.eth.coinbase:**
Cannot read property 'coinbase' of undefined
Cannot read property 'getCoinbase' of undefined
web3.createBatch is not a function
**Permissions / web3 parameter validation:**
AssertionError: expected [Function] to throw error including 'Payload, or some of its content properties are invalid. Please check if they are valid HEX with \'0x\' prefix.' but got 'Cannot read property \'sendTransaction\' of undefined
Permissions / web3.eth.attributes:
expected { Object (currentProvider) } to have keys '_requestManager', 'bzz', 'currentProvider', 'eth', 'db', 'shh', 'net', 'personal', 'settings', 'version', 'providers', and '_extend'

Also the console writes an error every time I add or change any custom token:
**Uncaught TypeError: Cannot read property 'toLowerCase' of undefined**

<img width="1129" alt="2017-12-30 17 09 07" src="https://user-images.githubusercontent.com/34959860/34454868-08491416-ed85-11e7-9608-0199284c2e0a.png">

[node.log](https://github.com/ethereum/mist/files/1594444/node.log)

**Comment by coachstevecosta** [comment]
I am having the same issue - did you resolve it yet?

**Comment by AndrewStones** [comment]
@coachstevecosta the issue hasn't been resolved yet =( I do not have any ideas basically

**Comment by evertonfraga** [comment]
Hi @AndrewStones, in order to see correct balances, you must be in sync with the network. 

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.

**Comment by AndrewStones** [comment]
@evertonfraga Hi! It is not the reason of sync. I still have this problem with node v.1.8.1 (5 147 956 blocks). Please re-open this issue.

**Comment by theyosh** [comment]
@evertonfraga Hi, the problem is the error when you want to save a token. I have the same error:

2a3fe1c….js:340 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.Helpers.getENSName (2a3fe1c….js:340)
    at 2a3fe1c….js:319
    at Array.forEach (<anonymous>)
    at Function.A.each.A.forEach (2a3fe1c….js:1)
    at updateBalances (2a3fe1c….js:319)
    at Object.a (2a3fe1c….js:427)
    at Object.click .dapp-modal-buttons button.ok (2a3fe1c….js:204)
    at 2a3fe1c….js:91
    at Function.e._withTemplateInstanceFunc (2a3fe1c….js:91)
    at f.View.<anonymous> (2a3fe1c….js:91)
    at 2a3fe1c….js:89
    at Object.f._withCurrentView (2a3fe1c….js:89)
    at f._DOMRange.<anonymous> (2a3fe1c….js:89)
    at HTMLButtonElement.<anonymous> (2a3fe1c….js:89)
    at HTMLElement.dispatch (2a3fe1c….js:74)
    at HTMLElement.g.handle (2a3fe1c….js:74)

This error is always there. Even when I am in sync with network.
So when editing or adding a new token, the above JS error will be thrown

**Comment by theyosh** [comment]
And when it is in sync the following error is thrown:

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.Helpers.getENSName (2a3fe1c2c11d1412008f44881c705bf418e50ca0.js:340)
    at 2a3fe1c2c11d1412008f44881c705bf418e50ca0.js:319
    at Array.forEach (<anonymous>)
    at Function.A.each.A.forEach (2a3fe1c2c11d1412008f44881c705bf418e50ca0.js:1)
    at updateBalances (2a3fe1c2c11d1412008f44881c705bf418e50ca0.js:319)
    at observeLatestBlocks (2a3fe1c2c11d1412008f44881c705bf418e50ca0.js:319)
    at connectToNode (2a3fe1c2c11d1412008f44881c705bf418e50ca0.js:336)
    at 2a3fe1c2c11d1412008f44881c705bf418e50ca0.js:377
    at 2a3fe1c2c11d1412008f44881c705bf418e50ca0.js:187
