### ISSUE TITLE
Minor display issue in txns listing when switching from Mainnet to Testnet

### ISSUE THREAD

**Issue by mtbitcoin** [ethereum/mist#350]
When you switch from either mainnet to testnet (or vice versa) the transactions that were carried out in the previous network is also displayed in the newly switched network. So, this creates a bit of confusion because you know see transactions that did not occur on the present networkid. Ideally the txns listing should only show transactions that occurred in the current network

**Comment by luclu** [comment]
closed in favor of https://github.com/ethereum/mist/issues/541.
Copied comment.
