### ISSUE TITLE
Etherum Wallet sync problem

### ISSUE THREAD

**Issue by taekten** [ethereum/mist#3500]
- [yes ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
I made the mistake of transferring ETH to Mist wallet before cpmpleting sync like many others.  Ethscan says it was received but I cannot finish sync for the life of me.  I have tried a lot of different things including --lite client, manually starting geth, deleting chaindata and restarting sync, unlock command, tried to access through myethereumwallet but cannot access with my keystore file says "wrong password" but I know it's the right password, also I tried launching the application and letting it sync from there with no avail.  I am to the point where I have to manually start geth to get it to start sync.  If do not, I get a "node connection error:'("  it will start downloading chain data but geth crashes after about 30 seconds. it gets shorter and shorter everytime. Also it is curious that I cannot view logfile. "Show log file (using external node)" is displayed.  When geth crashes it dumps a bunch of white text and closes in less than a second, but it looks all normal before.  Also I cannot access geth via cmd.exe using the file directories in troubleshooting guides nor the one that does correspond with my computers path to the geth.exe.  I have been running other operations by creating a shortcut and modifying the target.  been trying since the Dec 18 to get this figured out.  I wonder if I'll ever get access. Almost willing to give up and sell my ETH and not support it anymore.  How do they plan to keep devs and users with this sort of problem with something as fundamental as a wallet.  Especially since the dev control is through the wallet. 

Here's a new one while writing this.  It is now in a perpetual state of importing new state entries with 25 peers connected and downloading no blocks.  

```
Version: `0.9.3`
OS & Version: windows 10
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4787317
```

![capture1](https://user-images.githubusercontent.com/35044389/34500348-5d78a0fa-efd8-11e7-963d-19badbf67f95.PNG)
![sad](https://user-images.githubusercontent.com/35044389/34500684-cc22bdf0-efd9-11e7-86c6-1050b8ff3a3a.png)
![asadssd](https://user-images.githubusercontent.com/35044389/34500800-45584406-efda-11e7-8253-142a8f39c55b.png)

**Comment by evertonfraga** [comment]
Hi! We have an updated version with improved syncing. After downloading version 0.11.0, please enable the Light Client (`Develop > Sync with light client)`

I am closing this thread, if you still have any trouble **please feel free** to file a new issue or comment in an open one that better describes your situation.
