### ISSUE TITLE
Ethereum Wallet Broken! Use MyEtherWallet as workaround - See issue #2466

### ISSUE THREAD

**Issue by lowlanda** [ethereum/mist#3504]
Ethereum Wallet is is clearly broken broken at present. We've all tried many, many ideas and solutions with no success, for varying reasons. I tried a sync using geth --light, but could only get within 9 blocks. I then got fully sync'd with --fast mode, could see balance but then got "Unable to connect: timeout" errors within Ethereum Wallet. I hope they fix it soon, because it's great when it works, but WAY too many problems right now, as the myriad of sync issues here proves.

Go to issue #2466 and check out nadimaj 's post about downloading/using MyEtherWallet.

I went through it and successfully found my balance and was able to make transactions. It might be a little scary at 1st (I was scared lol), but it does work if you follow nadimaj's instructions.

1 small tip when sending Ether, make sure you set a high enough gas price. I used 60 Gwei today, and it went through almost instantly. Used 21 Gwei last night, and it took hours..

Big thanks to @nadimaj 

Good luck!

**Comment by lowlanda** [comment]
Is the wallet is fixed now?

**Comment by Excruciates** [comment]
No!
