### ISSUE TITLE
You call this a Wallet?

### ISSUE THREAD

**Issue by Kuhein** [ethereum/mist#3506]
Nice guys, 

For the last 3 days I cannot open my Wallet."No peers, with peers, re downloading" still nothing.
I know that its gonna take a few more day until this shit will connect but I find it disturbing that I cannot transfer my money when I need.
Very disappointing, I'll take my money out, of course if that's gonna be possible this month.

**Comment by lowlanda** [comment]
We're all suffering, and wasted days, it's sucks.

If you need to access/transfer ether, check out issue #2466 and follow instructions to download MyEtherWallet. I used it, works great as a temporary alternative.

**Comment by Kuhein** [comment]
Thank you lowlanda

**Comment by foen** [comment]
https://github.com/ethereum/mist/releases
download the 64bit version fixes the sync issue

**Comment by Kuhein** [comment]
foen, keep that advice for you, I'm not touching "shiest" again. Thank you Iowlanda, I've usend myetherwallet to transfer, screw this myst crap.

Ticket can be closed.

**Comment by CPUMANSTER** [comment]
Before you even start downloading the eth blockchain consider your hardware.
>Ssd is required >=256GB
Modern four core or better cpu.
Memory >=8GB ram.
Open/forwarded port 30303 tcp and udp. You may have problems getting peers if not allowed from outside.
Use a light client if this is not acceptable.

**Comment by Kuhein** [comment]
I7 4790K
24Gb Ram
4x512Gb SSd
Ports opened

I got it covered, is just a shitty wallet, that's all.

**Comment by Riifta** [comment]
Similar specs, similar problems too.

I get it to work each time I launch by looking for errors in the log file
and manually removing corrupted headers the wallet downloads then
relaunching it. It's tedious but the only way I can get it to work.

I don't trust Mist in the slightest in its current state.

**Comment by modabasi** [comment]
I have lots of coins, lots of wallets and this is the one and only wallet that makes me mad each and every time I try to use it!

**Comment by marienuac** [comment]
why do people keep suggesting a website as an alternate for a desktop wallet......

**Comment by lowlanda** [comment]
Cos the wallet is broken atm, and we need to access our ether. It's just an alternative solution. I'd prefer to use Ethereum Wallet, but I can't right now. I'm sure there are other alternatives, MyEtherWallet was suggested, I tested it and it works.

Cheers :)

**Comment by ryanio** [comment]
Hey, we just released a new version (`0.11.0`) that has new syncing features - please give it a try! If you have any new problems that you can reproduce, please create a new issue with the details on how 
we can help. Thanks!
