### ISSUE TITLE
My ethereum wallet on OS  crashes

### ISSUE THREAD

**Issue by Joan1006** [ethereum/mist#351]
Good morning. Today my ethereum wallet which was open several days was closed and when i try to restart it it crashes. The message is:
Node type: geth
Network: main
Platform: darwin

...I0314 11:28:20.130600   18600 database.go:71] Alloted 433MB cache to /Users/joanplancade/Library/Ethereum/chaindata
Fatal: blockchain db err: read /Users/joanplancade/Library/Ethereum/chaindata/401867.log: result too large

What can I do?

**Comment by Amauche** [comment]
Kill geth process and restart it. ;)

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
