### ISSUE TITLE
Please help - Stuck at 4,370,001 for months now 

### ISSUE THREAD

**Issue by kallan4446** [ethereum/mist#3512]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows
Node version: `Geth/v1.6.6-stable-10a45cb5/windows-amd64/go1.8.3
[node.log.zip.zip](https://github.com/ethereum/mist/files/1607652/node.log.zip.zip)
[node.log.zip.zip](https://github.com/ethereum/mist/files/1607654/node.log.zip.zip)
` 
Number of blocks synchronized: 4,370,001
```

**Comment by justnonamenoname** [comment]
you need to delete Ethereum Wallet in your AppData Roaming
Ethererum uses old geth.exe

**Comment by evertonfraga** [comment]
Hi @kallan4446,

Please tell us what is the creation date of AppData Roaming Ethereum Wallet directory.

Your answer is highly appreciated here. Thank you.

**Comment by chriscrutt** [comment]
try deleting the ethchain which is located at `~/AppData/Roaming/Ethereum` and re-download it using `geth --fast` in a command prompt, if you receive an error make sure you close Mist and wait a minute, then try again

**Comment by evertonfraga** [comment]
pinging @kallan4446 

Please tell us what is the creation date of AppData Roaming Ethereum Wallet directory, so I can troubleshoot it. Thanks

**Comment by kallan4446** [comment]
The date on my Ethereum wallet directory was the current date at the time I was told to delete it. It seems the date recorded by Windows is the date it is last accessed.

When I deleted it, and restarted the program, a new ehtereum wallet directory was created and it seems to be working. It has restarted to download blacks, and it is not yet up to date, but progressing normally.

Hope this helps

Kerry
