### ISSUE TITLE
Lost Ether from Gatehub to Changelly

### ISSUE THREAD

**Issue by TonyDun** [ethereum/mist#3515]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
Apologies to post here but I don't know many groups and this is where I learn the most. Maybe one of you can guide me to the right place.
**Trying to regain my ether**
Lost Ether when transacting from Gatehub to Changelly. The Changelly address was an old one that I had already used. 
By the time I could understand the problem the Changelly page closed and Gatehub had already initiated the transaction.
The details are below

TX   Hash: | A166D0520E320282241BBF08D896ACD81F6FD7C81AA101AD3F83CAEA3496464A
-- | --
Time: | Jan   4, 2018 10:14:50 PM
Type: | sent

Sent to address

Address | 0x740c3c4a3edd27194cbeade0ff15ed9bfe9320a8
-- | --
Network | Ethereum
Deleted | 0

**Comment by evertonfraga** [comment]
Hi @TonyDun, I am sorry to say that this is not the proper place to talk about GateHub. There are indeed lots of people around this forum revealing bad experienced about that product. 

Maybe you can tag them in this issue, or get help from official community channels... 

I am closing this issue. Cheers.
