### ISSUE TITLE
Sent 0.11 ETH from GDAX to Gatehub and it is missing

### ISSUE THREAD

**Issue by jfermes** [ethereum/mist#3521]
Hi all,

Hope you can help me. I created a new Gatehub account. My EU BANK gateway is pending for activation. Since I wanted to buy some XRP to activate my wallet, I transfered 0.11 ETH from my GDAX wallet to my Gatehub ETH wallet. Previously I activated the ETH gateway on Gatehub. GDAX says the transaction has been done succesfully but I cannot see the ETH on Gatehub. 

Why i don't received my ETH on my gatehub Account?
Do I have to activate the XRP wallet (having 20 XRP) before transferring any other cryptocurrency like ETH? The problem is that I cannot activate my XRP wallet if I cannot buy XRP, this is why I transferred ETH first. I read the support and it says that you can activate the wallet buying XRP with another cryptocurrency like ETH.

To those who had the same problem, how mych time did you wait until the transaction was succesfully done?

Thank you very much!

**Comment by bozgoren** [comment]
It seems this question is for gatehub? You will use their services and support. It is better to ask them. For all this type of problem what i do is, i check the height when it is send. (block number). Then i check the receiving wallet height. (block number). Generally I see that receiving wallet didnot synchronize there yet. People here cannot know the status of gatehub wallet.

**Comment by jfermes** [comment]
Yes, I already sent before asking here. Finally I got the ETH on Gatehub. It delayed more than expected. The fact is that they sent me a link to "Trust" my Wallet. Thank you anyway.
