### ISSUE TITLE
Can't send ether. Fully synced. Always 0 of 12...

### ISSUE THREAD

**Issue by plizer** [ethereum/mist#3522]
Hi!

I hope someone can help me here. I have a ethereum wallet and want to send ether to another address. But there is no way to do this! I set to maximum transfer costs, but it seems to be not enough, because I never get any confirmations (0 of 12 for days...)

Is there a way to set the transfer costs higher as the gliders limit?

Im very happy for any help!

**Comment by plizer** [comment]
The ethereum wallet seems to correct the glider price. Its much higher now. Do I really have to pay 40$ to make a transaction???

An old transaction still have 0 / 12 with a fee of: 0,007778652 ETHER. Shouldnt be 7,5$ enough to get that confirmations or is there another problem?

**Comment by david340804** [comment]
Do you have the transaction ID? https://ethgasstation.info/ shows a fee of $1.22 for a confirmation time of 5min

**Comment by alexvandesande** [comment]
I've had issues with the amounts of peers and sometimes your peer not forwarding your transaction? Maybe that's it?

**Comment by marcgarreau** [comment]
This may fall into a category of issues resolved with the [0.11.0 release](https://github.com/ethereum/mist/releases/tag/v0.11.0). Please give that a try and open if a new issue if appropriate.
