### ISSUE TITLE
Windows client never syncs

### ISSUE THREAD

**Issue by fixethereumwallet** [ethereum/mist#3523]
After trying 3 laptops (Intel 6700hq, 4570, 3610QM), five desktops (mix of 8700K, 7500 and 1090T AMD) and a collection of Hyper-V VMs my router now reports I have in total downloaded 3.5TB of blockchain data in various attempts to get this program to work, some attempts more desperate than others but all failed...
Obviously removedb has been used several times, including completely clean installs of W10, W7, 2012 R2 in both just after installation state and after full updates...

Has anyone ever gotten this to work? Is there a region lock?... Are there CPU requirements other than x86-64?
On the 8700K systems the sync freezes every 10.000 blocks or less, I've never seen it do more. When it freezes it requires to be closed and re-opened to get it to download a few more blocks before freezing again.
The 6700hq laptop did the entire sync all the way up to 4,167,670. and after that refuses to update even 1 more block, nor will it let me start the application...
It does let me set up an account, when dragging a backup file into the program the program just closes without any notification, perhaps useful to setup some error handling there.
I heard Ethereum was supposed to be decentralized, but searching the internet I find hundreds if not thousands of others who have never gotten this program to even work once and being forced to abandon Ethereum or use an online wallet, defeating the purpose of a decentralized system...

The GETH command-line works perfectly fine, syncing away for days without any crashes/freezes/lockups.
I've gotten this program to show my balance 1 time, after making Geth sync the blockchain and quickly starting Wallet while closing Geth, but it refused to update even 1 block and just froze up two minutes later...

How do you run this program without it crashing/freezing/closing to just work?

**Comment by chriscrutt** [comment]
one suggestion would be to reinstall geth and mist (which it seems you have done). I have a Mac and had the same problem, this is how I fixed it:

1. delete ethchain, located here on windows `~/AppData/Roaming/Ethereum`

2. open a command prompt and type `geth --fast` and let it download everything. also if you want it to go even faster you can do `geth --fast --cache 8000`, replace `8000` with the max MB of memory you want used.

3. It's ok to open Mist now, if you'd like you can to ^C in the command prompt to stop Geth (gradually) and then open Mist and have it run on its own... if you encounter any problems with Mist downloading the blockchain just run `geth` in the command prompt and it will download and update.

**Comment by fixethereumwallet** [comment]
Thanks for the reply, have tried all that but no luck...

1, did that several times including geth removedb and manually deleting the folder, using clean installs and different computers, none worked.

2, Tried Geth, Geth --fast and cache values ranging from 1024 all the way up to ridiculous values on a hypervisor (including cache 204800 on a 256GB RAM server...) none worked.

3, Running geth while Mist is open gives me so many errors in both Geth and Mist, Mist usually just freezes and requires Taskkill to kill it when I do this.

I'll try a different type of VM later today but so far nothing seems to work...
I even tried downloading over a VPN and even through an entirely different provider to exclude any issues there...

**Comment by chriscrutt** [comment]
awe, I guess it might just work on Mac: [https://github.com/ethereum/mist/issues/3533](https://github.com/ethereum/mist/issues/3533)

**Comment by evertonfraga** [comment]
Hi @fixethereumwallet, 

I want to help with those Windows fixes. I'll put this issue in our backlog and we'll come back to it later.

**Comment by evertonfraga** [comment]
Hi @fixethereumwallet would you please confirm those two information:

1. How did you install the wallet (.exe or .zip)?
1. What's the geth version being used (Develop > Node > Geth (x.x.x)?

**Comment by pajendame** [comment]
Ive been there for a while. Here is my experience. Tryed to sync for 2 weeks, the blocks keep rising without succes. i think this is the solution, in any case it worked for me. Reinstall clean windows 10 on a new ssd HDD. The wallet synced in 24 hours with a good fiber 300Mbs connection. Even if u choose to install Mist o another partition, the wallet creates a folder on C partition where ur Windows is, a preety large folder that need to download +10gb. So if u dont have Windows installed on a SSD Disk and a minimum 100Mbs coonection dont even bother triyng - u will fail .
i hope this will help u - it worked for me.

Any small donation would be highly appreciated
ETH Wallet adress : 0x40Bb5a49A9448eEb17bAbf273A6e176E806d7334

**Comment by evertonfraga** [comment]
Or: you can enable the light client, under Develop menu. This solves all space and bandwidth problems.
