### ISSUE TITLE
Password Requirements

### ISSUE THREAD

**Issue by ryanwoods1706** [ethereum/mist#3527]
I'm wondering when did mist wallet implement the password requirements of 8 characters of a new account? I remember about a year or so ago i created a wallet, and I didn't remember it being there when I created my wallet.

**Comment by evertonfraga** [comment]
I can confirm later, but IIRC it was around 0.8.8


--
Everton Fraga

**Comment by ryanwoods1706** [comment]
When was 0.8.8 released roughly? @evertonfraga

**Comment by simon66** [comment]
@ryanwoods1706 
Looking at the [release page here](https://github.com/ethereum/mist/releases/tag/v0.8.8), version `0.8.8` was released on `Dec 16, 2016`

Based on the [comments from this release here](https://github.com/ethereum/mist/releases/tag/v0.8.10), we know that the `8 chars min` password length was first introduced on version `v0.8.10`.

**Comment by marcgarreau** [comment]
Closing this issue; please open a new one if appropriate.
