### ISSUE TITLE
I have sent tokens to my ERC20 wallet iso my token contract. can this be repaired?

### ISSUE THREAD

**Issue by Zicky888** [ethereum/mist#3532]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
Please describe your issue in more details. use the comment box to explain what happened.

Thank you

**Comment by Zicky888** [comment]
Hi,

With the token conversion of CarboncoinI’ve stated my ether wallet address in stead of my token contract address in my ether wallet. 

In Etherscan I can see that my tokens are in my wallet but in my token contract of CCE (carboncoinether tokens) the number is zero.

So what has to happen that the tokens should be in my carboncoinether token contract. Yet how to do this is something I don’t know.

Please advise.

Kind regards,
Dick

**Comment by alexvandesande** [comment]
I'm sorry it's not clear. The most important question is: what sort of wallet the tokens currently reside on? Is it a contract of some sort? Is it someone's else wallet?

**Comment by marcgarreau** [comment]
If I understand the issue correctly, you just "watched" the wrong token address. You would just need to delete the watched token contract and perform the action again with the correct address.
