### ISSUE TITLE
ETHEREUM WALLET - GNT - custom token is grey!

### ISSUE THREAD

**Issue by GitHubVale46** [ethereum/mist#3535]
I have Ethereum Wallet. When I try to watch GNT token, i add it, but when added, token becomes grey.
I allso cant see my GNT coins anymore!
PLEASE HELP!  :(

![image](https://user-images.githubusercontent.com/30480139/34692720-60720bf0-f4c1-11e7-87e6-f48428366dff.png)

**Comment by andi448** [comment]
Same problem here with Storj token.

**Comment by evertonfraga** [comment]
Hi! It seems this is a sync issue. We have an updated version with improved syncing. After downloading version 0.10.0, please enable the Light Client (`Develop > Sync with light client)`.

Please let me know

**Comment by andi448** [comment]
It worked for me.
