### ISSUE TITLE
Unable to send coins

### ISSUE THREAD

**Issue by cac58** [ethereum/mist#3536]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

My wallet is synced I've been trying to send to coinbase for over a week. the last time I sent was 25 Dec what can I do to get coins to my coinbase wallet?

**Comment by evertonfraga** [comment]
Hi @cac58 this is probably due to sync issues.

Please refer to #3097 for more information and troubleshooting.
