### ISSUE TITLE
Node syncing stalled at block 3569960

### ISSUE THREAD

**Issue by vishalsood** [ethereum/mist#3538]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows
Node version: `geth 1.7.3` 
Number of blocks synchronized: 3569960
```

It can't seem to find a good peer. Here are some example logs. I have already tried removing db and starting again. I am doing fast sync.

WARN [01-08|09:35:13] Synchronisation failed, retrying err="block download canceled (requested)"
WARN [01-08|09:39:54] Rolled back headers count=57 header=3569954->3569954 fast=3569960->3569960 block=0->0
WARN [01-08|09:39:54] Synchronisation failed, dropping peer peer=7e81d6f67c5c8d28 err="retrieved hash chain is invalid"
WARN [01-08|09:40:54] Rolled back headers count=112 header=3569954->3569954 fast=3569960->3569960 block=0->0
WARN [01-08|09:40:54] Synchronisation failed, dropping peer peer=f122c0825846bbd4 err="retrieved hash chain is invalid"
WARN [01-08|09:42:25] Synchronisation failed, retrying err="block header download canceled (requested)"
WARN [01-08|09:42:56] Synchronisation failed, retrying err="block download canceled (requested)"
WARN [01-08|09:43:29] Synchronisation failed, dropping peer peer=76906dc1c32c680e err="action from bad peer ignored"
WARN [01-08|09:44:27] Rolled back headers count=49 header=3569954->3569954 fast=3569960->3569960 block=0->0
WARN [01-08|09:44:27] Synchronisation failed, dropping peer peer=214733e0ec4cc848 err="retrieved hash chain is invalid"
WARN [01-08|09:54:09] Rolled back headers count=68 header=3569954->3569954 fast=3569960->3569960 block=0->0
WARN [01-08|09:54:09] Synchronisation failed, dropping peer peer=8cca25d44598cec3 err="retrieved hash chain is invalid"
WARN [01-08|09:59:48] Synchronisation failed, dropping peer peer=715708e9e4f1fa8f err=timeout
WARN [01-08|09:59:53] Rolled back headers count=55 header=3569954->3569954 fast=3569960->3569960 block=0->0
WARN [01-08|09:59:53] Synchronisation failed, dropping peer peer=4755dde00e4b8c15 err="retrieved hash chain is invalid"
WARN [01-08|10:01:05] Synchronisation failed, dropping peer peer=be27797969bd1b19 err=timeout
WARN [01-08|10:04:23] Synchronisation failed, dropping peer peer=52c9be6a539f6b25 err="action from bad peer ignored"
WARN [01-08|10:16:07] Rolled back headers count=191 header=3569954->3569954 fast=3569960->3569960 block=0->0
WARN [01-08|10:16:07] Synchronisation failed, dropping peer peer=6a3b5c3ee0eff99e err="retrieved hash chain is invalid"
WARN [01-08|10:16:08] Synchronisation failed, retrying err="block download canceled (requested)"
WARN [01-08|10:16:15] Rolled back headers count=121 header=3569954->3569954 fast=3569960->3569960 block=0->0
WARN [01-08|10:16:15] Synchronisation failed, dropping peer peer=64e4dd3f53e5c01e err="retrieved hash chain is invalid"
WARN [01-08|10:17:50] Rolled back headers count=68 header=3569954->3569954 fast=3569960->3569960 block=0->0
WARN [01-08|10:17:50] Synchronisation failed, dropping peer peer=c2ea6347c30dca72 err="retrieved hash chain is invalid"

**Comment by evertonfraga** [comment]
Please search for the solution in the https://github.com/ethereum/go-ethereum repository.
