### ISSUE TITLE
Ethereum Wallet Password Issue

### ISSUE THREAD

**Issue by hvteng** [ethereum/mist#3539]
Hi Ladies and Gents

I am very new to this. So Thanks in advance.

I have been doing some mining for the last few months. And I finally decided to Tx some Ether around. Here is the trouble, I don't recall I ever had a password to enable Tx.

I have a keystore file, but not a password. 

My current version of Ethereum Wallet in 0.9.3, I think I started with 0.9.0 or later. Windows 10 64 bit.

What do I have to do to recover the password, I can not recall any Pass Phrases. (I don't think there was a phrase.)

Many Thanks.

**Comment by evertonfraga** [comment]
Hi @hvteng, can you recall what version of Geth or Mist did you have when you've created that account? 

Please go to the keystore file Properties and point us what the creation date is. 

There's an effort to outline these issues happening here: #3513. You are very welcome to join us.

**Comment by evertonfraga** [comment]
I'm closing in favor of #3513.
