### ISSUE TITLE
No reaction clicking Ethereumwallet.exe [Win 8.1]

### ISSUE THREAD

**Issue by ETHER86** [ethereum/mist#354]
Nothing happens at all - no window opening - absolutely nothing.

Am i missing sofware to run this on my system? There are no logs in mist folder aswell - its not starting at all.

Can someone help me?

EDIT: GETH is not starting - iam stuck at "starting server" nothing happens from there on

**Comment by lookie21** [comment]
same shit is happening to me

**Comment by lookie21** [comment]
could you try running it from the zip file and tell me what it says

**Comment by luclu** [comment]
Could you kindly update to the latest version 0.7.4 and check if you still encounter this issue?
Also make sure to extract the zip a prior.

**Comment by luclu** [comment]
Please update to `0.8.1`. Make sure your firewall is configured correctly.
