### ISSUE TITLE
Despite of transferring funds over a day ago, Parity wallet and the account remains on zero balance. And for my surprise I realized today that it took twice what I designated to be transfer. 

### ISSUE THREAD

**Issue by group-1-engineering** [ethereum/mist#3541]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
Hi @group-1-engineering,

it looks like you are talking about https://github.com/paritytech/parity, another project. Would you open this same issue there?
