### ISSUE TITLE
I have sent 0.21 ether to my Bittrex account and i did not recieved it. On my mist account the transaction appears to be completed but they are not recieved on my bittrex account. Please help!

### ISSUE THREAD

**Issue by cilu87** [ethereum/mist#3542]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by sebastienrocks** [comment]
Bittrex probably needs more time to validate the transaction on their end. Exchanges often take more time then the actual transaction.
Wait a few hours and have a look again. If you can't see your funds on your Bittrex wallet, but the transaction went through (and the destination wallet is correct), then it's most unlikely to be an Ethereum related problem.

**Comment by evertonfraga** [comment]
Hi @cilu87, 

Unfortunately, there are no means of canceling transactions that already went through. If you do have the transaction hash, you can get in touch with the Bittrex support. Note that many exchanges are bloated with new users and it might take some time.

I'm closing this issue, should you have anything related to Mist don't hesitate opening a new issue.

**Comment by cilu87** [comment]
I will try there. Thank you! I hope i will solve the problem.

**Comment by cilu87** [comment]
I have received all my ETH back. No fee paid, I will tri it again.
