### ISSUE TITLE
Transaction never went through and ether is gone!

### ISSUE THREAD

**Issue by bubbleguppies** [ethereum/mist#3545]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
I have tried to send out 5 ethers on Saturday, December 16, 2017 2:18 PM and this is what is still shown (25 days ago, 0 Confirmations). My ether is gone and has never transferred. Can you please help me find my 5 ethers? Also, I have been trying to update my wallet to the version below and it has taken days. I am try the command /geth --fast --cache=1024 console in the terminal and it has taken days. Can you please walk me through a way to speed up the process. 

Thank you.

```
Version: `0.9.3`
OS & Version: osx
Node version: `geth 1.7.3` 
Number of blocks synchronized: 4,760,997
```

**Comment by cilu87** [comment]
I have the same problem. I have sent on Bittrex. they told me that i should contact the bittrex for the missing eth. :(

**Comment by bubbleguppies** [comment]
I actually transferred mine to binance and I contacted them and they said it is an issue with my wallet not them. They did not receive the ether on their end. Hoping it is just a update issue.

**Comment by alexvandesande** [comment]
You should start by looking at your account history on etherscan.io. Your ether can't be "gone" either the transaction was never picked up and you still have it or it went through. Most likely the interface wasn't updating or connecting correctly at the time
