### ISSUE TITLE
there is no more synchronization

### ISSUE THREAD

**Issue by stbregeon** [ethereum/mist#3546]
version 0.9.3
gpl-3.0
geth 1.7.2
synch with light beta
block  4 885 562
windows 8

There is no more peers and no more synchronisation.  it's very hard to work on the wallet.

This afternoon, after 3 hours, there is a firt sync but  peers don't stay unitl the end of the sync et the sync stopped.

Is someone know why ?

best regards

- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by bubbleguppies** [comment]
hello I believe u need to download the latest geth version at 1.7.3 hope this works

**Comment by stbregeon** [comment]
tanks a lot
where can i find it ?

**Comment by bubbleguppies** [comment]
https://geth.ethereum.org/downloads/

**Comment by stbregeon** [comment]
Ok
and in what repertory do I have to install it ?

**Comment by stbregeon** [comment]
C:\Users\user\AppData\Roaming\Ethereum Wallet\binaries\Geth ?
