### ISSUE TITLE
problem to send coins "etc"

### ISSUE THREAD

**Issue by sakis123** [ethereum/mist#3549]
I am trying to send my balance to another address but i get the message : The method personal_sendTransaction does not exist/is not available

Version: `0.0.0`
OS & Version: windows 10
Node version: `geth 0.0.0` 
Number of blocks synchronized: all

**Comment by 9607835** [comment]
The geth server has the personal based api's removed so that it won't work with the mist wallet or any tutorials, so you have to add it back in...
`geth [...] --rpc --rpcport [...] --rpcaddr "0.0.0.0" --rpcapi "eth,net,web3,admin,personal" [...]`
now the tutorials should work.

**Comment by 350050183** [comment]
I met the same error.

Start Node with:
geth --identity "CSQNodeName" --rpc --rpccorsdomain "*" --datadir ~/.ethereum_private --rpcapi "eth,net,web3,admin,personal" --shh --dev console

Then start Ethereum Wallet with CMD:
/Applications/Ethereum\ Wallet.app/Contents/MacOS/Ethereum\ Wallet --rpc  ~/.ethereum_private/geth.ipc

In Wallet try to create an contract will promoted this: "The method personal_sendTransaction does not exist/is not available"

**Comment by sakis123** [comment]
i work on windows 10 , can any one help me i still have the same problem/error

**Comment by sakis123** [comment]
the solution for me was to take the file of the private key and give it to an other wallet ....
very simple but i did't know that i have this option ....
