### ISSUE TITLE
Couldn't start an Ethereum Node

### ISSUE THREAD

**Issue by pablox43** [ethereum/mist#355]
Started Ethereum wallet V 5.2. I get the little windows that says "Starting Ethereum Node". After a couple of minutes, I get the message below. 

![error_snip](https://cloud.githubusercontent.com/assets/8853151/13752298/7514fdc2-e9e4-11e5-8691-f92e9785567f.PNG)
Here are my PC details.

![system](https://cloud.githubusercontent.com/assets/8853151/13752399/e6daa920-e9e4-11e5-9d5d-380b6e488cc1.PNG)

Let me know if you need more information. Thanks!

**Comment by Amauche** [comment]
Same problem on OSx:

Node type: geth
Network: main
Platform: darwin

...I0314 18:11:57.793272   64650 database.go:71] Alloted 433MB cache to /Users/mohamed/Library/Ethereum/chaindata
Fatal: blockchain db err: resource temporarily unavailable (check if another instance of geth is already running with the same data directory '/Users/mohamed/Library/Ethereum')

**Comment by Amauche** [comment]
Node type: geth
Network: main
Platform: darwin

...I0314 18:11:57.793272   64650 database.go:71] Alloted 433MB cache to /Users/amauche/Library/Ethereum/chaindata
Fatal: blockchain db err: resource temporarily unavailable (check if another instance of geth is already running with the same data directory '/Users/amauche/Library/Ethereum')

**Comment by i90rr** [comment]
Check if it's related to #307

**Comment by Amauche** [comment]
Kill geth process and restart it. ;)

**Comment by alexvandesande** [comment]
Try installing a node manually by following these instructions: http://ethereum.org/cli
