### ISSUE TITLE
Slow sync causing many issues

### ISSUE THREAD

**Issue by mydigitalself** [ethereum/mist#3551]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

I filed this yesterday: https://github.com/ethereum/mist/issues/3544

TLDR: Slow sync is causing wallets not so show balances properly or transactions not to confirm.

Solution: Wait a very long long time for your wallet to sync and get to 0 blocks remaining or look to use an alternative wallet such as Parity.

And have been hanging around on `ethereum/welcome` and `ethereum/mist` for the last 24 hours.

Within that period, here's just a sampling of messages of people experiencing this problem. Other than people asking where to buy Ether, it's pretty much the # 1 problem people are coming into the channel for, so perhaps it would be good to investigate further. If you are creating a viable wallet for people to use, it shouldn't be this painful.

I'm very happy to help get involved in a "product management" level, I have a lot of experience in this field, so just shout.

https://gitter.im/ethereum/welcome?at=5a56dffd61a861c927fbd034
> Hi I send etherium from Kraken to another exchange called alticion trade it been 10hrs still my etherium hasn't reflected address is fine what could be the issue

https://gitter.im/ethereum/welcome?at=5a56f487ce68c3bc74a3bf80
>So I got ether into the Ethereum Wallet and now I cannot get it out no matter what I do! WTF do you have to do to actually get the ether to send - Say back to coinable or something

https://gitter.im/ethereum/welcome?at=5a56c2ce290a1f4561742cde
>Is anyone able to help me? My wallet still shows an empty balance. 

https://gitter.im/ethereum/welcome?at=5a56ad7c232e79134defc2bb
>I have the same problem, one day ago I've sent eth from coinjar to myetherwallet, accodring to coinjar it was succesfull but it doesnt shop up yet. what to do

https://gitter.im/ethereum/mist?at=5a568a4d232e79134def10c4
> sigh, I synced 150 blocks in the last 19 hrs ish....

https://gitter.im/ethereum/mist?at=5a568a4d232e79134def10c4
> In the past month or so, I've installed Ethereum Wallet on 3 machines. Each time, it has gotten stuck like that. 

https://gitter.im/ethereum/mist?at=5a5699965a9ebe4f75704a35
> I am stuck syncing as well

**Comment by pinney** [comment]
After more than a week of ...

Ethereum node needs to sync, please wait...

running the 'splash window" not the 'browser'

mist --syncmode fast --cache=4096

Downloading block 4,886,204 of 4,886,908

Downloading block 4,886,826 of 4,886,977, 
Downloading chain structure 9,229 of 25,783

Downloading block 4,886,826 of 4,886,977, 
Downloading chain structure 166,275 of 180,141

Downloading block 4,887,246 of 4,887,570

Downloading block 4,887,516 of 4,887,615, 
Downloading chain structure 1,354 of 2,683

Downloading block 4,887,516 of 4,887,615, 
Downloading chain structure 145,400 of 158,630

Downloading block 4,887,516 of 4,887,615, 
Downloading chain structure 172,804 of 180,059

Downloading block 4,887,516 of 4,887,615, 
Downloading chain structure 242,612 of 248,555

Downloading block 4,887,553 of 4,887,848

Downloading block 4,887,691 of 4,887,848, 
Downloading chain structure 144,112 of 157,253

Downloading block 4,887,878 of 4,888,210

Downloading block 4,887,955 of 4,888,231

Downloading block 4,888,194 of 4,888,272

Downloading block 4,888,194 of 4,888,280

Downloading block 4,888,204 of 4,888,286, 
Downloading chain structure 701 of 5,041

Downloading block 4,888,204 of 4,888,309

Downloading block 4,888,204 of 4,888,338, 
Downloading chain structure 1,948 of 3,884

Downloading block 4,888,204 of 4,888,338, 
Downloading chain structure 17,194 of 19,328

Downloading block 4,888,204 of 4,888,338, 
Downloading chain structure 26,980 of 33,583

Downloading block 4,888,204 of 4,888,588

Downloading block 4,888,326 of 4,888,737

Downloading block 4,888,598 of 4,888,782, 
Downloading chain structure 5,845 of 11,035

Downloading block 4,888,598 of 4,888,782, 
Downloading chain structure 130,471 of 147,655

Downloading block 4,888,598 of 4,888,782, 
Downloading chain structure 239,025 of 257,069

Downloading block 4,889,098 of 4,889,313, 
Downloading chain structure 441,605 of 450,522

Downloading block 4,889,512 of 4,889,626

Downloading block 4,889,512 of 4,889,678

Downloading block 4,889,512 of 4,889,785

Downloading block 4,889,514 of 4,890,094

Downloading block 4,889,903 of 4,890,094

Downloading block 4,889,984 of 4,890,135

Downloading block 4,889,984 of 4,890,163, 
Downloading chain structure 216 of 1,277

cat /proc/version
Linux version 4.9.0-5-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04)

**Comment by ainsleys** [comment]
So i think the problem (if there is one) was of available memory. And i do not think it has anything to do with Mist browser though I tried again using geth only and waited until I was fully synced before opening mist. Here is what I did. 

I was able to successfully sync on a Macbook Pro, Sierra, 16mb ram. Steps I took:
1- free up machine from all other noncritical memory-using tasks
2- delete chaindata folder
3- fast sync using geth
4- do *not* open Mist browser until process is completed.

I synced before 24 h had passed.

**Comment by nched** [comment]
the problem is not only that it syncs pretty slow on a fast machine, but the syncing also blockes all other internet traffic. It is one of the most aggreesive p2p implementations and from a user perspective it is pretty bad practice. Many other major wallets, starting from bitcoin, implement the syncing much better. It is pretty unusable at this point, but that's why it is 0.x and not 1.x

**Comment by evertonfraga** [comment]
Hi, @mydigitalself thanks for your thorough emphasis on the importance of this issue.

We're fully aware of it and although blockchain syncing is done by Geth (https://github.com/ethereum/go-ethereum), we're developing a way around it, via remote nodes instead of having to do such an entire sync.

I'll find ways to communicate better what we've been working on ;)
