### ISSUE TITLE
The balance does not appear in desktop wallet!

### ISSUE THREAD

**Issue by SergMos77** [ethereum/mist#3552]
Hi all.
I transferred from the exchange to my wallet (on my desktop: Ethereum-Wallet-win32-0-9-3) - etherium, but the balance does not appear! 
what to do?, pls HELP!

**Comment by cryptroneum** [comment]
Same problem with no answer in reach. It should not be this difficult!

**Comment by cryptroneum** [comment]
I looked up malance on etherscan and the coin is there but does not show on the wallet balance*


Sent from Mail for Windows 10

**Comment by cryptroneum** [comment]
It,s arrived !

Sent from Mail for Windows 10

**Comment by marcgarreau** [comment]
The [0.11.0 release](https://github.com/ethereum/mist/releases/tag/v0.11.0) improves this experience. Please give that a try and open if a new issue if appropriate.
