### ISSUE TITLE
UTT tokens are not displayed

### ISSUE THREAD

**Issue by levcoin88** [ethereum/mist#3553]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

I translated my UTT tokens into my Ethereum wallet.
UTT tokens are not displayed.
what to do?

```
Version: `9.3`
OS & Version: windows 10

```

**Comment by levcoin88** [comment]
I translated my UTT tokens into my Ethereum wallet.
UTT tokens are not displayed.
what to do?

**Comment by evertonfraga** [comment]
Hi @levcoin88, you have to click on `Contracts > Watch tokens`. From there, insert the token data (Address, token symbol and amount of decimals).

Feel free to reopen this issue should you still run into problems.
