### ISSUE TITLE
Mist and/or ethereum wallet wont fully sync

### ISSUE THREAD

**Issue by jarbanas** [ethereum/mist#3555]
I've tried almost all I can including deleting chaindata multiple times, fast sync, etc, etc.  I get to the last 100-200 blocks and it just grind to a halt.  Seems to be a major issue right now (please see past 30 posts). What is going on.  Can anyone please suggest an alternate solution other than using myetherwallet.com?

**Comment by Kostem5** [comment]
Same here, I've been attempting to sync since Dec 15. It always stops 50-300 blocks short. My problem is that I transferred some eth to the wallet, and now I can't get to them. Suggestions?

**Comment by evertonfraga** [comment]
Hi all, sorry for this behavior. Geth (software that syncs to the network) halts on 100-200 blocks before while downloading another big and complementary chunk of data, the State Entries. Today this number is as high as 70M. Please try using the Light Client (`Develop > Sync with Light Client`)

Please follow conversation here: https://github.com/ethereum/mist/issues/3097

**Comment by yihaient** [comment]
@evertonfraga your solution did not work and I have tried every way.
