### ISSUE TITLE
Clean up deprecated warnings in the contract compiler

### ISSUE THREAD

**Issue by nareddyt** [ethereum/mist#3556]
- [X -- asked by other people a month ago] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: Windows 10 version 1709
Node version: Not sure, whatever is packaged with the latest version of Mist
Number of blocks synchronized: 1,577,340 on **RINKEBY**
```

I started the [official tutorial for creating a contract using Mist](https://ethereum.org/token), but some of the code in the tutorial causes compiler warnings. Specifically, the function:

```
    /* Send coins */
    function transfer(address _to, uint256 _value) {
        /* Add and subtract new balances */
        balanceOf[msg.sender] -= _value;
        balanceOf[_to] += _value;
    }
```
causes the following compiler warning:

```
 No visibility specified. Defaulting to "public".
    function transfer(address _to, uint256 _value)  {
    ^
Spanning multiple lines.
```

After doing a quick google search, this seems to be a deprecated warning that needs to be cleaned up on the compiler. Not entirely sure what the following github repo is, but they had the same issue and they fixed it: [https://github.com/ConsenSys/Tokens/issues/85](https://github.com/ConsenSys/Tokens/issues/85)

Adding `public` to the end of the function resolves the compiler warning, as follows:

```
  function transfer(address _to, uint256 _value) public {
     ...
  }
```

If we do not want to remove the warning, should we update the docs to include the public phrase? I can imagine it being confusing for new developers!

**Comment by evertonfraga** [comment]
Thanks for reporting @nareddyt,

Today, it's recommended to use [Remix](https://remix.ethereum.org) in order to create and compile contracts. This section will be deprecated soon.
