### ISSUE TITLE
"Send everything" does not send everything

### ISSUE THREAD

**Issue by piotrmb** [ethereum/mist#356]
After using this functionality there are still some remains on the account - I think it should be just 0.0, not 0.000000000000017181 Ether.

Account: 0xE76EaD3b758580Bc4a79eccE04D7c88e061E299a
TxHash:  0x6c671344417f3878d9df9cd3d422a50020f5bf11d7b6de0b5af892f9860be7de

![send_all](https://cloud.githubusercontent.com/assets/17673547/13755297/e48e2f6c-ea1a-11e5-87ad-ed5593cb0c8a.png)

**Comment by piotrmb** [comment]
I did more tests, so I can specify it a bit more. This issue occurs only when you change the fee you want to pay for the transfer. Amount is recalculated but this calculation is not precise.
Before fee change:
![send_all_2](https://cloud.githubusercontent.com/assets/17673547/13756742/abe13b1c-ea21-11e5-9787-1ddf0b4e9f4a.png)
After fee change:
![send_all_3](https://cloud.githubusercontent.com/assets/17673547/13756755/b5f15ce0-ea21-11e5-907f-9c200db9a23d.png)

**Comment by alexvandesande** [comment]
Thanks. That was indeed the case when some irrational numbers were used as a fee multiplier. It will be fixed on the next version.

**Comment by nipponese** [comment]
I am using 0.8.10 and this issue is still occurring.
