### ISSUE TITLE
Send Transaction stuck since 07 January 

### ISSUE THREAD

**Issue by MISA72** [ethereum/mist#3561]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: osx
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4,899,732
```

![schermata 2018-01-13 alle 05 43 49](https://user-images.githubusercontent.com/35347699/34902855-ca590364-f824-11e7-9be5-5862f74337d1.png)
![schermata 2018-01-13 alle 05 43 54](https://user-images.githubusercontent.com/35347699/34902856-ca7694e2-f824-11e7-9923-38e64c05a5d5.png)
[node.log](https://github.com/ethereum/mist/files/1628065/node.log)

**Comment by ryanio** [comment]
Hey, we have released a new version (`0.11.0`) that should be more stable - please give it a try. If you have any new problems that you can reproduce, please create a new issue with the details on how we can help. Thanks!
