### ISSUE TITLE
No clear user feedback/info about the size of the ethereum chain causes system problems

### ISSUE THREAD

**Issue by danoctavian** [ethereum/mist#3563]
```
Version: `10.13.2`
OS & Version: osx
Node version: `geth 0.9.3` 
Number of blocks synchronized: don't recall
```

On Mac OS, the space taken by the chaindata directory is presented in the mac system information section as `System` data (which normally is under 100gb but it bubbled up to 225gb+ and my hdd size is 250GB). This is very confusing because it took me a while to realize it was the mist wallet that was eating all my space on my computer. 

Thus it took me a while to realize and diagnose the problem. at that point. i could no longer do an `ls` command on my system. 

Downloading the entire chain by itself is something that breaks the user experience - no app should take hundreds of GB of space, but this is by itself a harder problem to solve.

Maybe a warning upfront about the required space for the chain is needed and clear info at all times about how much space in MB it is taking on the Hard disk is necessary.

**Comment by stresskiller** [comment]
or at least ask for a disk that has enough disk space during setup installation ...

**Comment by evertonfraga** [comment]
Hi all. 

This shouldn't be a pressing issue anymore, as we use a combination of Light with Remote syncing.

**Comment by evertonfraga** [comment]
Please feel free to reopen this issue should you have any consideration about it.
