### ISSUE TITLE
24h clock make an endless "downloading chain structure" (working fine with 12h clock)

### ISSUE THREAD

**Issue by pachalaa** [ethereum/mist#3564]
It was impossible to download the entire chain structure until I change my clock settings from 24 hours to 12 hours.

```
Version: `0.9.3`
OS & Version: osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 4,901,726
```

**Comment by RamblinWreck77** [comment]
My clock is set to 12h, and I'm getting this exact bug.
