### ISSUE TITLE
Ether Doesn't show in wallet

### ISSUE THREAD

**Issue by itisammar** [ethereum/mist#3565]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

Hey guys, idk if this is the right place to ask but basically in the summer i shapeshifted some of my btc to my mist wallet (through the in app fund with bitcoin option) but now that i'm booting the wallet p again i see that i have 0.00 ether, i remember filing a claim with shapeshift and they sent me an etherscan that they did send my 0.07 ethers over to my wallet, but it still shows that ive never received or sent anything from my wallet, what do i do / who do i contact????

my account: 
![desktop screenshot 2018 01 13 - 23 34 53 52](https://user-images.githubusercontent.com/35407846/34914865-7752ba30-f92c-11e7-937c-f5a0a062e72e.png)

Etherscan:

![desktop screenshot 2018 01 13 - 23 34 38 09](https://user-images.githubusercontent.com/35407846/34914869-84f71686-f92c-11e7-9d92-b2f6fc7056ec.png)

_

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
