### ISSUE TITLE
Senting coins to another wallet

### ISSUE THREAD

**Issue by cac58** [ethereum/mist#3567]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

I have been trying to send coins to another wallet with no luck I've tried different amounts still no luck. how can I increase the fuel amount? That might help with my problem. My Ethereum Wallet is synced.. Please help with this problem

**Comment by marcgarreau** [comment]
This may fall into a category of issues resolved with the [0.11.0 release](https://github.com/ethereum/mist/releases/tag/v0.11.0). Please give that a try and open if a new issue if appropriate.
