### ISSUE TITLE
Synchronisation sehr sehr langsam

### ISSUE THREAD

**Issue by Sebestien** [ethereum/mist#3571]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows 64Bit 10
Node version: `geth 1.7.3
Number of blocks synchronized:
4913504

Seit min 2 Wochen keine oder nur sehr sehr langsame Synchronisierung

Alle im Netz auffindbare Methoden ausprobiert. 
 3 x Ethereum Wallet alles gelöscht neu aufgesetzt.  
Synchronisation geht gut bis ca 4.300.000 Blöke 
danach ist Schluss.

Bitte Beheben
```

-

 -->

**Comment by Sebestien** [comment]
Ich habe alles von 6 Tagen nochmal gelöscht. Und neu Installiert konfiguriert.
Heute endlich hat es geklappt. Wallet ist synchronisiert!!!

**Comment by ryanio** [comment]
We have released a new version (`0.11.0`) that has new syncing features - please give it a try! If you have any new problems that you can reproduce, please create a new issue with the details on how 
we can help. Thanks!
