### ISSUE TITLE
Confused with getting my etherums on the working mist wallet

### ISSUE THREAD

**Issue by Ipoman** [ethereum/mist#3577]
Okay so this happened to me:

I downloaded and installed mist. Created account and sended etherums on this adress. After this when money couldnt reach the wallet I realized that it needs to first donwload all these blocks. Then I tried to download all but I did not have enough space on the disc C: which was the destination folder for the files.

So now I have problem that I cannot download the blocks on the disc C: and if I change the destination folder to other disc with more space I'll loose the wallets that are already in the application that has download destination on folder C:.

So can I somehow change the wallet to this new mist application that has other destination for the donwloaded files. Or can I somehow change the destination folder without loosing the wallets that I alredy sended the money to?

Thanks!

**Comment by imar2016** [comment]
All you need to do is backup your wallet files from the keystore folder and reinstall to the path you are after.

**Comment by marcgarreau** [comment]
You can also get around storage issues by using a remote node in release 0.11.0. Please give that a try and open a new issue if appropriate.
