### ISSUE TITLE
Funds wrongly sent to Test Network

### ISSUE THREAD

**Issue by jaclynchan** [ethereum/mist#3578]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
Hi I am Jaclyn here, I think I have accidentally send my ethereum from another wallet to the Test Network as this is my first time on this...
Can you please help and I am so worry now...TQ so much

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
You can use the testnet key file to claim that ether. Copy from testnet keystore directory into the main one.

**Comment by jaclynchan** [comment]
Hi, the problem is I cant even choose the Network under Develop button...

[image1.jpeg]

Best Regards
Jaclyn Chan 😊

On 17 Jan 2018, at 5:00 AM, Ev <notifications@github.com<mailto:notifications@github.com>> wrote:


You can use the testnet key file to claim that ether. Copy from testnet keystore directory into the main one.

**Comment by jaclynchan** [comment]
Hi, the testnet keystore directory means the testnet address?



Best Regards
Jaclyn Chan 😊

On 17 Jan 2018, at 5:00 AM, Ev <notifications@github.com<mailto:notifications@github.com>> wrote:


You can use the testnet key file to claim that ether. Copy from testnet keystore directory into the main one.

**Comment by jaclynchan** [comment]
Hi, I have copied the key file fm the testnet to the main net keystore folder..

So do I need to delete the other original main net key file?

Tks

Best Regards
Jaclyn Chan 😊

On 17 Jan 2018, at 5:00 AM, Ev <notifications@github.com<mailto:notifications@github.com>> wrote:


You can use the testnet key file to claim that ether. Copy from testnet keystore directory into the main one.
