### ISSUE TITLE
Can't Launch wallet (...flag provided but not defined: -syncmode)

### ISSUE THREAD

**Issue by Reiva** [ethereum/mist#3582]

**Comment by evertonfraga** [comment]
Hi @Reiva, please inform the following:
```
- [ ] Mist/Ethereum Wallet Version: `0.0.0`
- [ ] OS & Version: windows/linux/osx
- [ ] Node version: `geth 0.0.0` 
```

When creating this issue, if possible add the following to your report:
- Screenshots
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
- Log files
  - Go to the menu `Develop -> Show log files`
  - Zip and upload `all.log` and any other appropriate `category/*.log` files

**Comment by marcgarreau** [comment]
Cleaning up stale issues; more recent releases of mist + geth have addressed related issues. Please reopen/open a new ticket if appropriate.
