### ISSUE TITLE
MEGA THREAD: Chain structure download Never ending

### ISSUE THREAD

**Issue by Frustrated101** [ethereum/mist#3584]
Version: `0.9.3`
OS & Version: windows
Node version: `geth 1.7.2` 
Number of blocks synchronized: 4,923,949 of 4,924,718

I am 7 days into the sync. Problem is the "chain structure" download. I truly believe ethereum developers are clueless about how to create an ecosystem that people can use at all. Feels like pre-MSDos days of computers. This has been an issue for ethereum for years and with every new version there is a promise that the new version will solve this problem.

I have done some research since I am stuck like everyone else. There are 2 stages to the sync: Stage 1: download the block chain up until the last 1024 blocks or so. Stage 2: download the chain structure. Most people are able to complete the first part. During the first part you can exit the wallet if you want and restart. However, during the second stage you have to keep the wallet open at all times until the entire 'chain structure' is downloaded and processed. Otherwise it restarts from the beginning. Stage 2 is the part that most people have problems with. Unfortunately I keep running into problems like "network error" or "no peers" during the second stage. Each time the error is different. I usually get up to 11 million mark of chain structure after 12 hours or so, and then I get the error. Sometimes the etherum wallet closes automatically. So I have to restart the process from the beginning. My hardware has enough excess capacity to run the program. I am going to do a last run after fragmenting my harddrive. Any suggestions?

**Comment by smilekk** [comment]
same issue....

**Comment by majurius** [comment]
Same issue. Tried the "Sync with Light" option but it can't connect to peers. How the hell is eth even this popular, yet there's no working client for it!?

**Comment by NorbertSandor** [comment]
Same issue, without solution for months.
(Ethereum Wallet doesn't finish syncing, Parity keeps freezing/exiting on my computer :( )

**Comment by NorbertSandor** [comment]
On my PC now it is downloading the chain structure: 20,300,000 of 20,335,000.
Does anybody know where can I see the current size of the chain structure?

It is very annoying that downloading is at progress (at last) but I have no idea when it will be over?
It is not user-friendly at all to display an ever-growing progressbar.
I hope that it will really synchronize this time...

Besides, I tried command line geth as well and it failed to synchronize too :(

**Comment by Frustrated101** [comment]
@NorbertSandor two things. Don't feel bad about command line geth failing. It fails for most people. What most people do is use geth command line fast sync to get them pretty ahead but then continue using the GUI. 
The latest chain structure number I've seen is a bit over 50 million

**Comment by Frustrated101** [comment]
I am so frustrated after fiddling with this nonsense. I am going to buy a brand new computer for $1200 and dedicate it to this garbage of wallet.

**Comment by evertonfraga** [comment]
Hi all, this is the proper mega thread: https://github.com/ethereum/mist/issues/3097

In this sync mode there are over 70M state entries. Please try to use the Light Client, as state in the link above.

I'm closing this as discussion should follow from that canonical place.

**Comment by ChristBKK** [comment]
Does anyone know the current chain structure? I am at 135 MIO
