### ISSUE TITLE
Withdrew ETH from GateHub to Metamask Wallet and has not come through

### ISSUE THREAD

**Issue by OsmondC** [ethereum/mist#3585]
Hi,
I've sent my ETH from my Gatehub wallet to my Metamask wallet.
In Gatehub it shows the transaction as successful but its been over 8 hours now and no ETH is showing in my metamask wallet.

My XRP now is less than 20 as well from this transaction - is this an issue for it not clearing?
I've run the TX hash on sites and no records are showing.

Any ideas here guys?

**Comment by evertonfraga** [comment]
Hi @OsmondC,

It looks other people had problems with the same Gatehub service (https://github.com/ethereum/mist/issues?utf8=✓&q=is%3Aissue+gatehub).

In that case, Metamask is not the one to blame. And note that this is the repository of another ethereum client, Mist. 

Thanks.
