### ISSUE TITLE
Stuck for days... please help

### ISSUE THREAD

**Issue by Abelluz** [ethereum/mist#3587]
Version: `0.9.3`
OS & Version: Mac osx High Sierra
Node version: `geth 0.0.0` 
Number of blocks synchronized: 2,306,567
```

This is the error that comes every time I try to open Ethereum Mist.

Could anyone help please?? :)

![eth mist error](https://user-images.githubusercontent.com/35565834/35099504-7f0eb952-fc58-11e7-81ab-c4f5371e1eaf.png)

**Comment by Abelluz** [comment]
![eth mist error](https://user-images.githubusercontent.com/35565834/35099640-0bd5581e-fc59-11e7-98d5-e6f46021562f.png)

**Comment by evertonfraga** [comment]
Hi @Abelluz, this is strange indeed. 

Are you starting Geth manually? Have you tried resetting the blockchain?

**Comment by marcgarreau** [comment]
Cleaning up stale issues; more recent releases of mist + geth have addressed related issues. Please reopen/open a new ticket if appropriate.
