### ISSUE TITLE
Node Crashed

### ISSUE THREAD

**Issue by optonerd50** [ethereum/mist#359]
As requested by the Error box I'm supplying the following info:

Node type:geth
network:main
Platform:win32

...I0314 20:26:22.699201   4424 database.go:71]  Alloted 433 MB cache to  C:\Users etc.

**Comment by alexvandesande** [comment]
Thanks for reporting. To reduce duplication of issues I will be merging all these threads into a single issue: https://github.com/ethereum/mist/issues/243
