### ISSUE TITLE
Ether was there then gone

### ISSUE THREAD

**Issue by devon-custard** [ethereum/mist#3592]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
I did, no answer

```
Version: `0.9.3
OS & Version: Windows 10
Node version: `geth 1.7.2` 
Number of blocks synchronized: Dont know
```
Hey, complete noob here so I dont mind being shot down. I thought I would have a crack at mining to see what it was about. I downloaded Geth, let the blockchain sync over night, crated and account and installed mist. Then let my PC do some mining for a few hours. Imagine my surprise (and skepticism) that it looked like I had a few ether. However, I came back a bit later and now my wallet is empty. I have a screen shot of the the successful solve. Or have I got the wrong end of the stick?

![capture2](https://user-images.githubusercontent.com/35572284/35108975-f248c7c8-fc6c-11e7-8909-c8e7c0a0f837.PNG)

**Comment by porpoisepor** [comment]
I don't think this is a Mist issue.

I'm assuming you're trying to mine in a pool. If that's the case your screenshot shows you didn't configure the address of the pool you're supposed to send your solutions to. Even if everything was setup correctly, you would have to be mindful of your pool payment scheme. Some of them pay after a set period of time contributing, some of them pay after a set amount of work done.
 
If it's the case that you downloaded the default script in some website and ran it without checking what it does, watch out. Someone could make you mine for them or even hack you if you don't pay attention.

Now, if you're NOT trying to mine in a pool, just solo mining, then it would just be statistically very unlikely that you would solve a block right away within a few hours with that much hashing power. Not impossible, just unlikely. To give you an idea, you would have to mine for almost 8 years on average to solve a block. This would assume the difficulty would not increase over that time, which is false, and that there won't be a change in the protocol (proof of work / proof of stake) during that period of time, which is false (I hope).

Either way, I recommend you check out the EtherMining subreddit. They have a very detailed FAQ and introduction about the whole mining process and the community will very likely help you if you get stuck when trying to mine.

**Comment by marcgarreau** [comment]
@porpoisepor nailed this response (a long while ago). I hope that got you on the right path @devon-custard. Been a while, so closing the issue. Please reopen if appropriate.
