### ISSUE TITLE
Dear Ethereum, YOUR WALLETS ARE NOT WORKING.  Syncing stuck, 0 balance. Many complaints. Are you going to address this?

### ISSUE THREAD

**Issue by lt100** [ethereum/mist#3594]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by lt100** [comment]
Nobody seems to care. WHAT is going on?!

**Comment by imar2016** [comment]
This has been raised to death....i dont know when they will get around to addressing this, but i have been trying to sync for months....yes MONTHS

**Comment by ShamanReaper** [comment]
Yeah here also unable to sync. Not sure of other wallets. May have to buy a nano ledger s to overcome this problem

**Comment by shopifymatt** [comment]
Shamanreaper, good luck with that. I attempted to do that this morning and I'm getting hit with the wrong password bug. Can't even transfer my funds out, this is getting out of hand.

**Comment by kinther** [comment]
I just kicked my wallet back up and tried to sync.  It started to sync and I got about 66 blocks before it simply just stopped.  Then it showed "0 Waiting for blocks", then I see a higher number.  The number keeps incrementing but I never seem to synchronize any blocks again despite having 10 peers.

If I restart the wallet client, it just sits there and doesn't seem to sync at all.  Did somebody push a bad commit in this new version?

**Comment by lnaie** [comment]
same here! there is no official answer about it while the devs have time for icos, conferences, etc.

**Comment by djw55** [comment]
This has long been out of hand. I've spent the past two days trying everything I could. Get about 75 blocks away and it shits itself.

**Comment by VladimirAmiorkov** [comment]
For an project of this magnitude, its a shame that its "core" wallet is not usable for 995 of the people. I have tried times and times over to work with this projects own wallet with 0% success rate. What a shame.

**Comment by evertonfraga** [comment]
Mist spawns a Geth instance, responsible for syncing with the blockchain. Please refer to their repository in order to get help directly from the source.

I'm closing this for now. Let's keep a constructive discussion on this canonical issue: https://github.com/ethereum/mist/issues/3097

https://github.com/ethereum/go-ethereum
