### ISSUE TITLE
stop abusing githubusercontent.com for updates

### ISSUE THREAD

**Issue by nonchip** [ethereum/mist#3603]
the mist binary tries to download https://raw.githubusercontent.com/ethereum/mist/master/clientBinaries.json on startup, while blocking all other activity.

this is discouraged by github and the request usually times out (at least as far as I could tell on my hosts; and nope, not behind a proxy/etc), likely because of the high amount of mist instances out there clogging it.

please consider using a proper cdn to cache that file.

**Comment by evertonfraga** [comment]
Fair enough, good suggestion.

**Comment by nonchip** [comment]
I mean it's not critical, but it might be helpful because a) less waiting for the client to notice it's timing out and b) greater chance of it not timing out at all and noticing a possible update sooner.

Also, I don't know if they really would, but github might complain about and/or block that kind of usage if it stresses their servers too much.

**Comment by evertonfraga** [comment]
Yeah, I get it. There were situations in the past (ethereum node bugs) that was important the user got an updated version even before the launch. 

We're refactoring the startup process at this moment and we might get rid of this mandatory step.

**Comment by devzl** [comment]
Hope this will be removed as soon as possible, it just hangs for a dozen seconds on every start up of Mist/Ethereum Wallet

**Comment by evertonfraga** [comment]
Hi all, I wanted to say this request was shipped in the latest version.

We're still requesting from a Github endpoint, but:
A) it does not block the startup process anymore.
B) changed the endpoint we check data against, reducing the transported payload size by 94%. From my tests, none of the requests hit the timeout. 

Pull request: https://github.com/ethereum/mist/pull/3909
Download links: https://github.com/ethereum/mist/releases/tag/v0.11.0
