### ISSUE TITLE
Watch token bug

### ISSUE THREAD

**Issue by fuorissimo** [ethereum/mist#3605]
Hello, i have MIST V. 0.9.3

I have add a token to watch: CND CINDICATOR. On blockchain, transaction is ok: token are availible.
But after sync my MIST, token don't appair. I read that this bug is old many month: why you don't resolve? 

How i can to have back my token?

![cattura di schermata 703](https://user-images.githubusercontent.com/35644089/35189459-212a24bc-fe4b-11e7-8715-07183a1ff125.png)

**Comment by ryanio** [comment]
Sorry to hear you’re having trouble. 

A few questions to help me debug:

What is your public Ethereum address?
What is the full contract address?
Is your Mist fully sync’d? What block number does it show?

Thanks

**Comment by fuorissimo** [comment]
Hello, thank you for reply.

What is your public Ethereum address? **0xbB95EfBed81C5DC0DF84DE3C52022F5f3A439DF0**
What is the full contract address? **0xd4c435f5b09f855c3317c8524cb1f586e42795fa**
Is your Mist fully sync’d? What block number does it show? **look screenshot**

There is another bug, also reported by other people. When you restart MIST, the Watch Token disappears, becomes transparent and needs to be re-inserted. **look screenshot**
If you explain how to move my address to another Wallet, I thank you.

![cattura di schermata 706](https://user-images.githubusercontent.com/35644089/35194425-b040a7ee-feb3-11e7-8f42-5156dd7933dd.png)

![cattura di schermata 707](https://user-images.githubusercontent.com/35644089/35194430-ba136cac-feb3-11e7-83ed-ff649f5ceae3.png)

**Comment by jawadski** [comment]
I have the same issue with CV tokens??

**Comment by fuorissimo** [comment]
![cattura di schermata 712](https://user-images.githubusercontent.com/35644089/35279823-831bc018-004e-11e8-8f5a-a8ecd801e15e.png)

**Comment by achempion** [comment]
@fuorissimo you are on the "Elements" tab, "Console" is the next one
It seems like you are having 10 errors in console.

**Comment by fuorissimo** [comment]
![cattura di schermata 733](https://user-images.githubusercontent.com/35644089/35453601-20923600-02cb-11e8-9447-7a4992a1da05.png)

**Comment by Melatonin6751** [comment]
Downloaded both new versions for windows 0.9.3.  Used the watch token to add my ZRX.  Was able to receive ETH and send with no problems.  With my ZRX, added it with my Watch Token, I can see it.  Move my cursor over the bar where it shows my total coins, touch the send  button and allows me to add the address for sending how much I want to send.  It tells me what the estimate fees will be, first I clicked send everything with both apps, then I subtracted what the fees will be to send a smaller amount.  But when I touch the blue button at the bottom of the screen to send, NOTHING HAPPENS.  I used Etherscan to get the information to add ZRX using WATCH TOKEN on the Ether Wallet and Mist.  When I saw that I need MIST also, once I ran that app it picked up the three accounts, the names are different, but the addresses are correct.  Even tried to add a contract for the ZRX address but it says my password is wrong, him, used the same password for all three accounts when created.

Any help would be greatly appreciated.

![see my zrx](https://user-images.githubusercontent.com/35876503/35475798-d4a64a76-0359-11e8-9ee7-4efac126a9ce.png)
![cant do nothing with it](https://user-images.githubusercontent.com/35876503/35475799-e8190e36-0359-11e8-979e-e879ddc0f90b.png)

**Comment by Melatonin6751** [comment]
Just to give an update to above issues, I restarted Mist and had no problem with Watch Token in displaying my ZRX.  But still cannot transfer them.

**Comment by ryanio** [comment]
@Melatonin6751 Thanks for the full description. Can you try opening the dev console and send a screenshot of what's in there after you click the send button? To see if there are any visible errors (Develop -> Toggle developer tools -> Ethereum wallet)

**Comment by Melatonin6751** [comment]
Hear is my screen shot
![screenshot eth](https://user-images.githubusercontent.com/35876503/35632771-6527883a-065c-11e8-9e1a-cdca7f4d2783.png)
![screenshot eth](https://user-images.githubusercontent.com/35876503/35632795-71be4d18-065c-11e8-8b24-2c83075990bd.png)

**Comment by Melatonin6751** [comment]
![screenshot eth](https://user-images.githubusercontent.com/35876503/35632929-e77ccfb6-065c-11e8-8af6-d8ad85ee1d6d.png)

**Comment by Melatonin6751** [comment]
![screenshot eth](https://user-images.githubusercontent.com/35876503/35633006-15782280-065d-11e8-94c7-3da9fea26a33.png)

**Comment by Melatonin6751** [comment]
![screenshot eth](https://user-images.githubusercontent.com/35876503/35633084-412a62f8-065d-11e8-8be3-6f7f975bf40f.png)

**Comment by evertonfraga** [comment]
Hi @Melatonin6751, sorry for the delay.

In order to make any transfer in the ethereum platform, you need a little ether, to pay for the gas. 
The interface does not even let you transfer ZRX token because it knows the account has no ether.

**Comment by Melatonin6751** [comment]
Still having trouble.  Put gas in the wallet, when I touch send, goes through all the motions, but not sending them.
![pic1](https://user-images.githubusercontent.com/35876503/37246282-8a781736-245b-11e8-81e8-e8fdf5d04679.png)
![pic2](https://user-images.githubusercontent.com/35876503/37246286-90da9b3a-245b-11e8-8f2b-d94c1d6b406e.png)
![pic3](https://user-images.githubusercontent.com/35876503/37246288-94c7a01c-245b-11e8-8cd4-da55ba5dcd24.png)
![pic4](https://user-images.githubusercontent.com/35876503/37246289-99210ffe-245b-11e8-9eeb-b2589d0c8f1b.png)
![pic5](https://user-images.githubusercontent.com/35876503/37246291-9d6d432a-245b-11e8-97f3-5b1ef1b30cab.png)

**Comment by Melatonin6751** [comment]
You will probably ask for this next.
![pic6](https://user-images.githubusercontent.com/35876503/37246325-508b7a26-245c-11e8-9f73-cf7ec4956ae7.png)
![pic7](https://user-images.githubusercontent.com/35876503/37246327-5507692a-245c-11e8-9b4c-4e03d62a67a0.png)
![pic8](https://user-images.githubusercontent.com/35876503/37246330-5939969e-245c-11e8-9bb2-002dc22e26c5.png)

**Comment by Melatonin6751** [comment]
The latest transactions have a different address that I am trying to send it to.  And it's saying account 1 and the ZRX are in account 2.  HELP
![pic9](https://user-images.githubusercontent.com/35876503/37246407-57842426-245d-11e8-90b1-7f4f70647876.png)

**Comment by Melatonin6751** [comment]
Hello @ryanlo Ryan Ghods?  Learned how to get feedback to you I hope.  Uploaded a bunch of screenshots to my problem.  Please Help.

**Comment by Melatonin6751** [comment]
Hello @evertonfraga, put gas in the tank.

**Comment by Melatonin6751** [comment]
Hello @evertonfraga, put gas in the tank.  Still having problems, maybe you can help?

**Comment by evertonfraga** [comment]
I think I realized what happened: you have ether on "Account 1", and ZRX on "Account 2". 

From current token implementations, the account moving tokens should pay for the transaction gas. So I recommend you transferring part of your balance to "Account 2", so you'll be able to transfer it elsewhere. 

Should you encounter any other problem, please reopen this issue. Thanks!

**Comment by Melatonin6751** [comment]
Hello @evertonfraga , It worked.

**Comment by evertonfraga** [comment]
Great! :)
