### ISSUE TITLE
CHANGE WALLET

### ISSUE THREAD

**Issue by fuorissimo** [ethereum/mist#3606]
I'm really sick of Mist Wallet's bugs. I decided to change wallet. How can I keep my address, but on another wallet?

**Comment by marcgarreau** [comment]
Each wallet generated produces a keystore file. You can use that keystore file to access your wallet on MyEtherWallet, for example. Keystore files are found in different places based on your OS:
- Mac: ~/Library/Ethereum/keystore
- Linux: ~/.ethereum/keystore
- Windows: %APPDATA%/Ethereum/keystore

I'm closing this issue, but let me know if you have further questions.
