### ISSUE TITLE
Sent ETH to address, but next time I opened the wallet it made me create a new address.

### ISSUE THREAD

**Issue by RandyRandalman** [ethereum/mist#3610]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

While initially downloading the block chain, I jumped ahead and launched the application. At the time it generated an address for me which I sent about .04 ETH that I expected to transfer whenever everything was synced up. At some point I closed out of the app, but when I reopened it later there was no wallet on the app. I checked the keystore folder and it was blank. The app generated a new wallet for me that has a different address than the one I sent my ETH too.

Is there anyway for me to recover that address, or at least the ETH I sent to it?

Here's the etherscan of the first of two transfers I made to the address that no longer exists for me
https://etherscan.io/tx/0xd407d94a28bd4e7e690ff87bc3172bd1ed387de15bb57576f99586a507d84beb

```
Version: `0.9.3`
OS & Version: windowsNode version: `geth 1.7.2` 
Number of blocks synchronized: 0
```

**Comment by RandyRandalman** [comment]
Problem somehow solved itself, sorry

**Comment by evertonfraga** [comment]
Hi @RandyRandalman, how are you? Mind sharing how did the problem was solved?
