### ISSUE TITLE
Memory leek in latest 9.3 mist wallet .dev

### ISSUE THREAD

**Issue by marksaitis** [ethereum/mist#3614]
Hi,

1. Latest 2017 Nov 9.3 mist wallet .deb has a memory leak on ubuntu 16.04
2. Seems like it is geth binary - keeps growing until it eats 100% of memory and crashes. At least it could restart after a crash - I wouldn't care. But how can I sync 100GB chaindata if the dmn thing crashes every few minutes and needs constant baby sitting
3. Reproduce it yourself, I said enough.

BONUS(Rhetorical):
1. How come core tools of multimillion tech have such issues?
2. Why nobody tests for such obvious issues? Quality control hello?
3. In such fintech, why isn't there a scheme of bug hunting "first found, first paid". In ethers. That could speed up the progress of soft tools no? The whole tech should have incentives.

Thank you for your attention. I write online only when I am really frustrated. I hope somebody reads this one day...

**Comment by N-B-V** [comment]
I'm also sitting with the same issue with my Mist/Geth - both the latest version.

I have ubuntu setup on a linode8192 system, i was able to sync to about 4 000 000 blocks and then it started. geth now runs for about 60 -120 seconds before the ram is maxed out and its killed.

While having geth active and monitoring the task manager it shows me that slowly picks up pace and runs through all the RAM and then just kills the process.

it does the same when running Mist. Sometimes, mist does not even close completely but just sits there doing nothing and i have to close it via task manager.

**Comment by evertonfraga** [comment]
Hi @marksaitis, sad to know that. 

This repository regards to Mist and not Geth. Would you mind heading to their repository asking them about that?

https://github.com/ethereum/go-ethereum/issues

Thank you
