### ISSUE TITLE
Created symbolic juncture directory so that I could get AppData off my C drive and now can't update nodes

### ISSUE THREAD

**Issue by thedonquixotic** [ethereum/mist#3615]
```
Version: `0.9.3`
OS & Version: windows
Node version: `geth 1.6.5` 
Number of blocks synchronized: 0
```

I can't access log files. 

I opened mist after months being closed, and started updating. I swiftly ran out of room on my SSD C drive. I already had Mist and Geth etc installed on my O drive (where I keep my programs), but it seemed that mist was saving the blocks to AppData on my C Drive. I looked up how to move it. The only thing I could find was a thing recommending creating a symlink

So I created a symbolic link using this script: `mklink /J C:\Users\thedo\AppData\Roaming\Ethereum O:\Programs\Ethereum\Data`

I open up my Mist wallet, and the load screen says this:
![image](https://user-images.githubusercontent.com/9451726/35241127-17136e94-ff7b-11e7-94ee-bf820d95be91.png)

Which makes sense and follows from about where my wallet was before I tried to fix things. 

But then I open it up and it says that number before quickly flashing to this:

![image](https://user-images.githubusercontent.com/9451726/35240811-437bb4e2-ff7a-11e7-8678-e50ddb51d74e.png)

I'm guessing there's something wrong with my symlink? It appears to be working. I made it a juncture directory link since that seemed to be the best way to go. 

Also before trying to symlink I tried using this script fix I found in this issue thread: 

https://github.com/ethereum/mist/issues/210

And I the script I tried was this: start .\resources\node\geth\geth.exe --datadir ".\Ethereum"

It seem to do anything. Though geth.exe wasn't in the same folder as my mist wallet. I could only see a geth.exe in the root of my programs Ethereum folder. So I clicked that and it proceeded to install geth. I then ran the script again on it there and it seemed to do nothing when I opened my Mist Wallet. So that's when I decided to try the symlink thing. 

Having a blockchain download to user data folders on their C drive seems like a bad idea. I'm just a web designer/dev so I know this is outside my field of knowledge but this really should be fixed I think, or at least documented an official workaround

**Comment by thedonquixotic** [comment]
Just a small update. I've tried opening and reopening the mist wallet application multiple times. Sometimes it updates the blocks. Sometimes it remains stuck. Whenever I open it up it is generally around the same place but never the exact same numbers, and the numbers seem to be going up and down without me being able to tell why. 

I can confirm though that nothing is being saved on my C drive in the AppData folder. The sym link seems to be working then. Except though that it isn't...

Should I like delete my blockchain and restart it fresh or something? I just want to update my wallet so I can extract the ethereum that I pool mined.

**Comment by thedonquixotic** [comment]
I think I found the log? Node.log inside the Roaming/Ethereum Wallet folder?

**Comment by alexvandesande** [comment]
It seems an issue with syncing, not related to your symlink. Everyone is having it at the moment, and we are working for better solutions to this.

Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.


If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097

**Comment by thedonquixotic** [comment]
Awesome, thanks Alex!

**Comment by thedonquixotic** [comment]
@alexvandesande So I tried switching to light mode and it didn't help. I sought help on the gitter though and people also suggested the MyEtherWallet. I can't open my keystore there because it seems that my password is different than what I thought it was.

In the process of doing this I was taking a look at my log file and it doesn't seem from what I can tell from it that the problem is the network being slow or something. I can link you the log file if that would help.

**Comment by thedonquixotic** [comment]
Specifically this part seems relevant 

`INFO [02-05|21:54:43] Block synchronisation started 
WARN [02-05|21:54:47] Rolled back headers                      count=144 header=4369855->4369855 fast=0->0 block=0->0
WARN [02-05|21:54:47] Synchronisation failed, dropping peer    peer=a979fb575495b8d6 err="retrieved hash chain is invalid"`

**Comment by thedonquixotic** [comment]
Looking around online it looks like this might be the DB being corrupted or something? I read that starting geth.exe and then the wallet afterwards helps. I'm trying that now. I'll see how far it gets in the morning. 

So this looks like it's going to be my only way to access my eth, so I'm trying to figure this out. I don't remember my password, I think it was probably set by the mining pool automatically.
