### ISSUE TITLE
Percentage of blockchain sync not calculated correctly

### ISSUE THREAD

**Issue by jebbgrenham** [ethereum/mist#3618]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: Mint 18.1
Node version: `geth 0.9.3` 
Number of blocks synchronized: n-860,000
```
What happens:
1. Open new install of wallet
2. Start sync; sync any percentage of blockchain
3. Close wallet
4. Open wallet
5. Look at percentage sync top centre, it will have reset to 0% despite having already downloaded some of the blockchain

What should happen:
1. Open new install of wallet
2. Start sync, sync to 25% (random value)
3. Close wallet
4. Open wallet
5. Look at percentage and see 25% (or wherever you left off).

Just to be clear, the block count is correct and the synced blocks previously downloaded remain synced, it's just that the % synced calc is miscalculating by basing the percentage on the difference between blocks NOT synced and the block height, rather than blocks synced and the block height.  Easy fix for someone with a few minutes.

**Comment by evertonfraga** [comment]
Hi, @jebbgrenham thanks for noticing. In the past, a user would start the wallet, quickly sync from where it left off (0% to 100%) and start using normally. So, although it might sound a little different, It is calculated for every start, and it was meant to be that way. 

This whole progress bar would become obsolete after our remote node integration and Light client integration efforts, so keep posted ;)

**Comment by evertonfraga** [comment]
Tha latest geth version has fixed the behavior and now it knows where the state sync has stopped.
