### ISSUE TITLE
Test wallet does not update blocks / EXP not arrives and not reflected at http://www.gander.tech/

### ISSUE THREAD

**Issue by DmitryShadow** [ethereum/mist#3619]
Hi guys! 

need your help on following issue:

1) Yesterday I installed the wallet Expanse.Wallet-0.8.9-mac.zip. 
Mac OS Sierra 10.12.6
For the quick start launched the **Testnet version**. After generating the EXP address in the wallet sent EXP to it from Criptopia.

2) After couple of hours when I checked the wallet, I saw that the number of blocks did not changed and it didn't find the peers.

![image](https://user-images.githubusercontent.com/35764121/35327530-e06b38d6-010a-11e8-9a77-83c5fb555800.png)

3) I tried to run the connection using manual commands from this forum, but my Mac does not recognize them. I didn't installed any firewalls as far as I remember.

4) Finally I switched to **mainnetwork**. And tried to import **testnet** account using the keystore from the testnet version.

I downloaded it here:  
![image](https://user-images.githubusercontent.com/35764121/35327954-f8796046-010b-11e8-95d3-e54b654a625b.png)
As a results, the keys are same, but Exp address for receiving in main and testnet are different.

5) moreover, I can not find the transaction at http://www.gander.tech/
Transaction ID: 0x24022a442d729650b753b9671e64fd6e2929761743cb1f7929902c36ec0352fe 

![image](https://user-images.githubusercontent.com/35764121/35328087-4f4224bc-010c-11e8-887d-a75a2caa26d6.png)

Can you pls suggest what can be done?

Thanks and regards,
Dmitry

**Comment by evertonfraga** [comment]
Hi @DmitryShadow,

Tihs is the repository of the original Mist browser. It looks like you want help/information about a Mist fork within the Expanse organization.

You should do that on the following link: https://github.com/expanse-org/mist

Thanks for reaching out and good luck!
