### ISSUE TITLE
Not mining on testnet

### ISSUE THREAD

**Issue by Giusepp3** [ethereum/mist#3620]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: osx 10.13.3
Node version: `geth 1.7.2` 
Number of blocks synchronized: 0
```

I've tried to test the testnet, i would mine some ether because there is non-sense to spend 
real money for fake money, but it seems not working, when i press start mining, it do nothing.

However you should solve the problem that every time it needs to open a new window in full screen it creates a new black screen and after not even close it.

i'll upload log files and a screen recording

thanks.

[log and screen recording.zip](https://github.com/ethereum/mist/files/1659502/log.and.screen.recording.zip)

**Comment by evertonfraga** [comment]
Hi @Giusepp3,

actually it does not make any sense to spend real money on test money :)

It has become difficult to mine in that Ropsten test network. But there's a thing called Faucet, that you can get test ether.

**Ropsten network**
http://faucet.ropsten.be:3001

**Rinkeby network**
http://faucet.rinkeby.io
