### ISSUE TITLE
My Ethereum Wallet will not sync 100% I have checked all threads and nothing gives a clear step by step instruction in getting the wallet to sync.

### ISSUE THREAD

**Issue by yihaient** [ethereum/mist#3621]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by yihaient** [comment]
I have tried every method from not launching the app to launching the app before it downloads all nodes and blocks. I have the latest updates on Ethereum Wallet and Mac OS - Please help thank you.

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
