### ISSUE TITLE
Dealing with sendMultiSig contract method call

### ISSUE THREAD

**Issue by khelle** [ethereum/mist#3624]
Hi, today I received following transaction from Bitstamp https://etherscan.io/tx/0x344d4ef6bedbd7ef6e591c833c5df1652503ef4c1e4027764c63a79dcc4b62e1 . If I am not mistaken this is generated by multisig contract available in mist client. Where can I find ABI file to deal with this contract transaction programmatically? If I am wrong and this is not parity-generated multisig address, please say that and close this issue.

**Comment by evertonfraga** [comment]
Hello @khelle,

The Ethereum Wallet contract does not have `sendMultisig` function. Here are their resources:
- Wallet contract solidity code: https://github.com/ethereum/meteor-dapp-wallet/blob/develop/Wallet.sol
- Generated Wallet ABI: https://gist.github.com/evertonfraga/5791b2d698ab1d762e1f357c92ea484a

After a little research, it's most likely a BitGo wallet contract: 

1. https://github.com/search?q=sendmultisig+pragma+solidity&type=Code&utf8=✓
1. https://etherscan.io/address/0xf2c32e69a914433d75e8c43e120bdd45b2fbe0c2#code

I'm closing it. Please reopen or comment as you see fit.
