### ISSUE TITLE
Ethereum Wallet - clarifications questions

### ISSUE THREAD

**Issue by cryptojsta** [ethereum/mist#3625]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
Hi guys,
I have few questions regarding the use of the Ethereum Wallet I downloaded from your website.

1. I transferred some ether to this wallet yet I cannot see it.
There is a message in the wallet saying **"Accounts can't display incoming transactions, but can receive, hold and send Ether. To see incoming transactions, create a wallet contract to store Ether"**. Does it mean that I **have** to create a wallet contract in order to see the ether?
Note that the transaction is successful according to etherchain.org.

2. The wallet is not 100% syncing. Download few new blocks every day but never 100%. Why?

3. A combination of 1. and 2. - If I fully sync the wallet, do I still need to create a wallet contract in order to see my ether?

Thank you!

```
Version: `0.9.3`
OS & Version: windows
```

**Comment by ryanio** [comment]
Hey cryptojsta, thanks for your Qs.

1. You'll see the ether updated in your balance, you just won't see individual transactions in the transaction list for incoming.

2. Sorry about the sync issues. Please refer to this issue here with some more information and ways to help: #3097

3. You'll see your ether once you're fully sync'd, or at least sync'd to the latest block with your most up to date transactions.

**Comment by cryptojsta** [comment]
Thanks ryanio for the inputs!
Regarding 3 - It always downloads some blocks (but not all of them) and I am still seeing 0 in my balance (and again, ethechain.com shows the entire balance). Do I have to fully sync it atleast once or as soon as the relevant block synced, I should see it?

**Comment by ryanio** [comment]
As soon as the relevant block is sync'd you should see it. Sorry about the trouble, we're currently working on on the sync issues on the dev team in Mist/Ethereum Wallet so we should have something soon. Meanwhile, if you need immediate access to your funds you can try using https://myetherwallet.com

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
