### ISSUE TITLE
Failed to start mist in private network

### ISSUE THREAD

**Issue by YuAS44** [ethereum/mist#3628]
Version: `0.0.0`
OS & Version: Ubuntu 
Node version: `geth 1.7.3` 
Number of blocks synchronized: 0
Mist version 0.9.3
I need help to understand what to do in that case: I tried to work with mist in private network using
these 2 commands
geth --dev --rpc --rpcaddr "0.0.0.0" --rpcapi "admin,debug,miner,shh,txpool,personal,eth,net,web3" console
mist.exe --rpc http://localhost:8545
![screenshot from 2018-01-27 22-31-04](https://user-images.githubusercontent.com/35664880/35475780-6dfe4f56-03b5-11e8-9691-578626627f52.png)

**Comment by alexvandesande** [comment]
You tried to execute the command in the *geth console* not in your system console. Open another terminal to run mist.

**Comment by YuAS44** [comment]
I tried this in Konsole and in tty1. 
In Konsole --> no such command
In tty1 no reply (see image.ppn)
![image 2](https://user-images.githubusercontent.com/35664880/35781970-129522d6-0a02-11e8-946a-80f004367d09.png)
