### ISSUE TITLE
Mist cant start because node.dll is missing from your computer..

### ISSUE THREAD

**Issue by lookie21** [ethereum/mist#363]
Ok just formatted my computer not too long ago installed mist and I cant seem to open it..

**Comment by frozeman** [comment]
The file node.dll should be in the ethereum wallet folder. Not sure why you get that error.




>

**Comment by lookie21** [comment]
yes I noticed its really strange..

**Comment by lookie21** [comment]
Ok so I noticed when I go into properties of any file it says this Idk if this is normal..

"this file came from another computer and might be blocked to help this computer"

**Comment by alexvandesande** [comment]
Please redownload the latest version and try again. Did you have an antivirus warning?

Open again if the problem persists

**Comment by kingteddy** [comment]
So I'm having the same issue. "No Ethereum node binary found!". This comes up when I try to open Mist. Re-downloaded a couple times now.

**Comment by luclu** [comment]
@kingteddy what OS are you running? (also version 0.7.4?)

**Comment by kingteddy** [comment]
Just got it to work. Thanks

**Comment by jesuscript** [comment]
having exactly the same issue (node.dll). Windows 7 x64. How do you fix this?

**Comment by evertonfraga** [comment]
@jesuscript could you provide us more info?

Is node.dll in the Wallet/Mist folder?
What version have you downloaded, 0.8.1?
