### ISSUE TITLE
no sync 

### ISSUE THREAD

**Issue by Scrooge69** [ethereum/mist#3631]
- [ I have installed mist v9.0.3 but still I have problems sync nodes.
I can not see me ETH which I send to my wallet and I can not touch them.
] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `9.0.3`
OS & Version: 10.11.6 osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 4,724.000
```

**Comment by ryanio** [comment]
Hey scrooge69, sorry about the sync issues. Please refer to this issue here with some more information and ways to help: #3097

**Comment by great999** [comment]
stupid wallet
never sync

**Comment by pajendame** [comment]
Ive been there for a while. Here is my experience. Tryed to sync for 2 weeks, the blocks keep rising without succes. i think this is the solution, in any case it worked for me. Reinstall clean windows 10 on a new ssd HDD. The wallet synced in 24 hours with a good fiber 300Mbs connection. Even if u choose to install Mist o another partition, the wallet creates a folder on C partition where ur Windows is, a preety large folder that need to download +10gb. So if u dont have Windows installed on a SSD Disk and a minimum 100Mbs coonection dont even bother triyng - u will fail .
i hope this will help u - it worked for me.

Any small donation would be highly appreciated
ETH Wallet adress : 0x40Bb5a49A9448eEb17bAbf273A6e176E806d7334

**Comment by Scrooge69** [comment]
Thx

Alexander van den Heuvel
