### ISSUE TITLE
ether not received !

### ISSUE THREAD

**Issue by great999** [ethereum/mist#3632]
[log.zip](https://github.com/ethereum/mist/files/1671236/log.zip)
[log.zip](https://github.com/ethereum/mist/files/1671237/log.zip)

I did not received the Ether in my ethereum wallet! 
The transaction looks ok !
https://etherscan.io/address/0x7d6909d715c097Fd5DBCf368c9C44b9e71d9E1e5

```
Version: `0.9.3`
OS & Version: windows 7 
Node version: `geth 1.7.2` 
Number of blocks synchronized: 0
```

**Comment by great999** [comment]
this must be the worst wallet ever!
they have tons of money and beta version for ethereum wallet!
when will be the version 1??
greedy and lazy!

**Comment by marcgarreau** [comment]
Mist/Ethereum Wallet requires your local geth node to be synced before your balance will be properly displayed. If you want to access your funds without waiting to sync, you can use your keystore file and password to use your wallet with service like MyEtherWallet. I'm closing this issue, but please free to ask additional questions or provide additional details.
