### ISSUE TITLE
drive space problem

### ISSUE THREAD

**Issue by great999** [ethereum/mist#3633]
ethereum wallet need a lot of drive space! but does not make you choose where to save all the data! the wallet save all on C:\ drive and that's  not ok because the space is limited on drive C ; you have to change that soon 

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by marcgarreau** [comment]
We agree! This is on our roadmap and will be addressed at some point. Importantly, the next geth release (1.8) will use fewer resources - stay tuned. Closing the issue as this is already documented.

**Comment by great999** [comment]
5 GB on drive C is full with ethereum shit ! I dont need that! Now I dont have any free space! Its all blocked!   because of you!

**Comment by evertonfraga** [comment]
@great999 please take a look at our Code of Conduct. Let's keep this all positive. This is the repository where Mist is built and improved, not a trollbox. 

https://github.com/ethereum/mist/blob/develop/CODE_OF_CONDUCT.md
