### ISSUE TITLE
accidently transferred Ethereum to Rinkeby test network how do i get it back please help me 

### ISSUE THREAD

**Issue by iPahul** [ethereum/mist#3634]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by marcgarreau** [comment]
I'm sorry to say that no one has the ability to reverse a confirmed transaction. Sorry for the headache 😞

**Comment by Taledeyo** [comment]
It's happened to me too.I'm don't get notthing and loose time for
notthing.I don't belive it...feel bad.😕

เมื่อ 1 ก.พ. 2018 4:05 AM "Marc Garreau" <notifications@github.com> เขียนว่า
