### ISSUE TITLE
File Menu: Backup: Accounts Justs opens Finder in Mac OS X 10.13.3

### ISSUE THREAD

**Issue by gemarti** [ethereum/mist#3635]
Version: `0.9.3`
Mac OS X 10.13.3
Node version: `geth 1.7.3 Stable` 
Number of blocks synchronized: 4,993,501
```

When I click FILE: BACKUP : ACCOUNT the only thing that happens is my finder window opens to ~/Library/Ethereum/Keystore

There isn't an option to backup the account to another location, such as a USB stick.

**Comment by evertonfraga** [comment]
That's the expected behavior. Your private keys should be lying in that
directory if they were created while on the main network. You can back them
up using your preferred method: copying to an external drive, printing, etc.




--
Everton Fraga

**Comment by gemarti** [comment]
I aware of how to manually back up a file. Seems like poor design to have a menu option to backup only to open the finder window. But if you say that's the expected behavior then I'll live with that.
