### ISSUE TITLE
Help!!! the eth dos not show up in my wallet? the payment are done but two of them so total of 0,4 ethr didnt show in my wallet??

### ISSUE THREAD

**Issue by misterxxx2017** [ethereum/mist#3638]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

OS & Version: windows

Number of blocks synchronized: 0
Help!!! the eth dos not show up in my wallet? the payment are done but two of them so total of 0,4 ethr didnt show in my wallet??

Check the already existing issues to keep duplicates to a minimum.

You'll find possible solutions for these common issues below on Mist Wiki: https://github.com/ethereum/mist/wiki.

- Ether is not shown in the wallet
- I send ether to the wallet contract but it doesn't show up
- My transaction is not confirmed

When creating this issue, if possible add the following to your report:
- Screenshots
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
- Log files
  - Go to the menu `Develop -> Show log files`
  - Zip and upload `all.log` and any other appropriate `category/*.log` files

worker name is arjan
mail adres misterxxx2017@protonmail.com

Total paid: 0.603184263994 ETH
--

3 | 2018-01-27 22:11:06 | 0.20170186315 ETH | Confirmed
2 | 2018-01-20 11:00:23 | 0.200728274559 ETH | Confirmed
1 | 2018-01-15 07:22:15 | 0.200754126285 ETH | Confirmed

There where three payments, and 1 is in my wallet, the other 2 
payments are not.

**Comment by alexvandesande** [comment]
This sounds like a sync issue, but you're not giving us a lot of information.

Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
