### ISSUE TITLE
I sent ethereum but it's  not shown on my wallet

### ISSUE THREAD

**Issue by memo1316** [ethereum/mist#3639]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

[](url)
[url=https://ibb.co/cOEyeR][img]https://preview.ibb.co/ifaRYm/error.png[/img][/url][https://ibb.co/hqbN66](url)

**Comment by alexvandesande** [comment]
Not enough information, so I am assuming it's a problem with syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
