### ISSUE TITLE
I open a new account and tried to fund it but my deposit went right into my coinbase account instead... 

### ISSUE THREAD

**Issue by Edgardoga** [ethereum/mist#3640]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
Hi @Edgardoga, I'll put this on our backlog so it'll be properly investigated.

Thank you for letting us know.

**Comment by evertonfraga** [comment]
Hi @Edgardoga, we've made additional tests and the services we use and integration on Wallet are operating normally. 

After creating the account, do you recall clicking it, then on fund account?

Additionally, did you manage to move funds out of the coinbase account? How was the coinbase account created, after all?
