### ISSUE TITLE
I recently purchased KRIOScoin (a new etherium based token) directed to  deposit in my ethereum wallet, but it never showed up. Do I need to configure my account differently to receive those kind of tokens? 

### ISSUE THREAD

**Issue by jimgwies** [ethereum/mist#3642]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by marcgarreau** [comment]
Two things: 1) you'll need to "watch" a new token, 2) your node must be synced to view latest balances.

re: 1) In the wallet, click on the "Contracts" tab, then scroll down to Custom Tokens and click "Watch Token". From there, you can enter the token details. I think this is your token address: https://etherscan.io/token/0xeef8102a0d46d508f171d7323bceffc592835f13.
