### ISSUE TITLE
Chromium / Electron vulnerability affecting Mist Browser Beta v0.9.3 and lower

### ISSUE THREAD

**Issue by bmann** [ethereum/mist#3643]
This is an issue to reference regarding this blog post: https://blog.ethereum.org/2017/12/15/security-alert-chromium-vulnerability-affecting-mist-browser-beta/

The current version of Mist uses Chromium 58 because of infrequent updates by the Electron project.

The dev team is considering switching to the [Brave project's Muon fork of Electron](https://github.com/brave/muon) which updates more frequently.

This issue was created from this Twitter thread: https://twitter.com/bmann/status/958435382844014592

**Comment by bmann** [comment]
@alexvandesande ideally this should reference a branch or any other visible work being done on this.

A question I have is where work / planned items are discussed, since they don't seem to be reflected in Github issues?

**Comment by alexvandesande** [comment]
This is addressed by https://github.com/ethereum/mist/pull/3296 which is updating to 1.7.11
