### ISSUE TITLE
How to Recovery password or no way.Can't sent/withdraw. 

### ISSUE THREAD

**Issue by alfamatrix** [ethereum/mist#3649]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows10 
Node version: `geth 0.0.0` 
Number of blocks synchronized: full sync - 5+ milions blocks

When i created my Ethereum-Wallet-win64-0.7.2 at year 2016,month of May I not remember to set any password for that wallet.
Now I'm upgraded to last wallet version0.9.3
```

**Comment by alfamatrix** [comment]
When i created my Ethereum-Wallet-win64-0.7.2 at year 2106,month of May,I not remember to set any password for that wallet.

**Comment by alfamatrix** [comment]
Still nothing,why not take an attention for this problem??????

**Comment by simon66** [comment]
@alfamatrix 
If you don't have your private keys and you don't know your wallet password, then there is no way to recover it.
Do you have your private keys?

**Comment by alfamatrix** [comment]
Mean's UTC. 
Is that private key?

**Comment by alfamatrix** [comment]
Mean's UTC.
Is that private key?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-02-28 18:51 GMT+02:00 simon66 <notifications@github.com>:

**Comment by simon66** [comment]
@alfamatrix 
No, the UTC file is your wallet.
Is your wallet encrypted?

You don't have to follow these steps, but both sites are trusted. Always check the URL before uploading your wallet.

1) Go to https://www.mycrypto.com/ or https://www.myetherwallet.com/
2) Click on `Send Ether & Tokens`
3) Click on `Keystore / JSON File`
4) Upload your wallet

If the site asks for a password, then your wallet is encrypted and you can't recover the private key (Unless you have the password).

**Comment by alfamatrix** [comment]
Thanks for the help.
The bad thing is that my wallet is encrypted.
If had some version of mist without needing password then I can sent eth
and then i will can turn my dao tockens back to eth.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-02-28 20:51 GMT+02:00 simon66 <notifications@github.com>:

**Comment by simon66** [comment]
@alfamatrix 
Fortunately thats not how encryption works (This is great news for everyone but somewhat of a bad news for you).
Once your wallet is encrypted, you will need to decrypt it in order for it to be usable.
You can use tools to recover your wallet (by brute forcing the password), but that might take a long time (if your password was long).

**Comment by alfamatrix** [comment]
Hi again.
Where to find "tools to recover my wallet",or how to do that.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-02 22:02 GMT+02:00 simon66 <notifications@github.com>:

**Comment by simon66** [comment]
@alfamatrix 
I never worked with this tools before, but there are quite a lot of tutorials online on how to use it.
You can find it here: https://ethereum.stackexchange.com/questions/97/how-can-i-recover-or-reset-a-lost-wallet-password#answer-105

This issue can be closed since it's no longer related to `Mist` 👍

**Comment by rgouzal** [comment]
I am having the same issue, the first time I installed the mist wallet it did not ask me to enter the password it automatically created a wallet for me and it was there already but did not ask me to put any password. so what is the solution?

Note: I can access the mist wallet and see my wallet balance, but having problem to sync getting an error regarding websocket being closed.

![eth-mist](https://user-images.githubusercontent.com/13728193/74616227-0614ba80-5140-11ea-8e8f-7491149fa265.PNG)

**Comment by 0x01Brain** [comment]
Note I can access the mist wallet and see my wallet balance, but having problem to sync getting an error regarding websocket being closed.
