### ISSUE TITLE
Hello, I bought etherum from Indacoin few weeks ago [...]

### ISSUE THREAD

**Issue by krityendras80** [ethereum/mist#3652]
Hello, I bought etherum from Indacoin few weeks ago and I used Classic Etherum key that I installed in Chrome and it does'nt show any coin in my wallet as I hoped that it was ETH but it was ETC. I reported to Indacoin and said they cannot help. What can I do to revivew ETH or I can also hve ETC so that I don't lose my money.

**Comment by evertonfraga** [comment]
Hi @krityendras80, I'll try to help you.

Lots of people get confused by ETC thinking they're the maintained by the Ethereum Foundation.

If you bought ETC from Indacoin, you should be able to:
1. Head to ethereum classic website
1. Choose one of the "ETC Wallets"
1. Import your keys 
1. Claim your ETC tokens and do whatever you want with it :)


I'm closing this issue as it is off-topic to this repository purpose. But feel free to chime in.
