### ISSUE TITLE
Wallet cannot sync on normal mode and high service fees on light client

### ISSUE THREAD

**Issue by royky21** [ethereum/mist#3655]
I see many others are posting the same issues but it was never solved.

I just started to use the mist client and on my mac 24/7 for the past MONTH to sync with the network but it can never finished downloading the last 200 blocks or so.

When I finally learnt that i can switch to the light client, my account balance finally shows up correctly, however, it shows a minimum fee of 0.15 ETH to make a transaction.

This is getting really frustrating and I'm not able to do anything with wallet. Is that the way the team is trying to lock up ETH in users' wallet? How can a promising coin be doing such things.

**Comment by royky21** [comment]
I see many others are posting the same issues but it was never solved.

I just started to use the mist client and on my mac 24/7 for the past MONTH to sync with the network but it can never finished downloading the last 200 blocks or so.

When I finally learnt that i can switch to the light client, my account balance finally shows up correctly, however, it shows a minimum fee of 0.15 ETH to make a transaction.

This is getting really frustrating and I'm not able to do anything with wallet. Is that the way the team is trying to lock up ETH in users' wallet? How can a promising coin be doing such things.

**Comment by royky21** [comment]
Btw, my geth version is 1.7.2

**Comment by coralnode** [comment]
A number of similar threads on this forum have reported this problem since months ago, but no ETH developer has even dropped a comment.

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. 

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
