### ISSUE TITLE
never ending sync attempt

### ISSUE THREAD

**Issue by unknownhostname** [ethereum/mist#3656]
[node.log](https://github.com/ethereum/mist/files/1687426/node.log)
I think everyone who tried at least 1 time to sync the ethereum blockchain got this problem.

A never ending sync from a company that creates "smart wallets", "smart" contracts and unstoppable apps.

**Comment by unknownhostname** [comment]
Another node.log file.
[node.log](https://github.com/ethereum/mist/files/1687442/node.log)

**Comment by unknownhostname** [comment]
Another screen without geth.
![eth1](https://user-images.githubusercontent.com/29194467/35730779-48edd24a-080b-11e8-8e78-d0b759cdd92e.png)

**Comment by evertonfraga** [comment]
Hi @unknownhostname, sorry for this experience. 

Under the hoods, Geth is downloading the state entries, like database records. There are over 70M to be downloaded total. If you feel comfortable, you can start Geth manually and keep track of the progress.

Please refer to [this issue](https://github.com/ethereum/mist/issues/3097) for more information and our [Wiki](https://github.com/ethereum/mist/wiki) for troubleshooting steps.
