### ISSUE TITLE
"insufficient funds for gas * price + value" when transferring from contract wallet to account

### ISSUE THREAD

**Issue by nauvillain** [ethereum/mist#3657]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: linux
Node version: `geth 0.0.0` 
Number of blocks synchronized: 5,013,910
```
this the 0.9.3 deb package shipped for linux - not sure what geth version is associated with it

I have an account wallet - with 0 ETH, and a contract wallet, with about 0.21 ETH.
I want to send the 0.21ETH out. I see that I should first transfer the money to the Account wallet.
So I do that:
I open my Ethereum wallet with  "ethereumwallet --syncmode fast"
I copy the Account address
I go to the contract wallet, press Send
I paste the account address in the To field
I enter an amount (for instance 0.1 ETH)
I select the cheapest amount of gas (or any other amount)
I click Send
I get a window in which it estimates the gas used, and prompts for my password
then I get 'insufficient funds for gas*price + value 

Also, at the top of that window, it shows 'you want to transfer 0 ETH' which is clearly incorrect.
[2018-02-01 17:57:08.126] [ERROR] ipcProviderBackend - Send request failed { code: -32000,
  message: 'insufficient funds for gas * price + value' }
[all.zip](https://github.com/ethereum/mist/files/1687542/all.zip)

**Comment by nauvillain** [comment]
![send1](https://user-images.githubusercontent.com/3031628/35737175-a85c3f4a-07f8-11e8-81b7-bd49e98fb2d2.png)
![wallets1](https://user-images.githubusercontent.com/3031628/35737178-aa648982-07f8-11e8-86b9-5572960a6c40.png)

It looks like the 'send' window shows 'my wallet' with 0.21 ETH, but displays the main account, which has 0 ETH. 
Any idea how to fix that?

**Comment by nauvillain** [comment]
![windows](https://user-images.githubusercontent.com/3031628/35738891-13aad9c8-07fe-11e8-8d11-5e2b68dfe6ec.PNG)

I've tried on Windows in light mode (as I don't have enough disk space) and it is slightly better, in that the 'max' shows 0 and not 0.21; so no surprise when I press send and the password window shows zero. But it's still incorrect and I am still stuck.

**Comment by evertonfraga** [comment]
> It looks like the 'send' window shows 'my wallet' with 0.21 ETH, but displays the main account, which has 0 ETH.

it seems this is a quirk, trust the names and balances.

**Comment by evertonfraga** [comment]
>  I see that I should first transfer the money to the Account wallet.
It is not currently possible for contracts to pay for gas costs, so you should always keep some changes (we call it "gas money") in order to operate the wallet contracts.

You can easily solve that by borrowing/buying ether from another account/service to that account.
