### ISSUE TITLE
Ethereum wallet address

### ISSUE THREAD

**Issue by borysmb** [ethereum/mist#3658]
Who can I ask for support?
I have relaunched the Ethereum Wallet application and want to access my wallet.  I am given the option to open a new wallet but there does not appear to be an option to open an existing wallet.

**Comment by borysmb** [comment]
Any guidance please? I tried to email info@ethereum.org but returned address not recognised.

**Comment by borysmb** [comment]
Dear marcgarreau - can you help, please?

**Comment by borysmb** [comment]
@marcgarreau - Hello Marc, please advise or direct me to the appropriate support function if you are able. Thank you

**Comment by marcgarreau** [comment]
Closing this issue to respond in your duplicate issue.

**Comment by borysmb** [comment]
The issue is still open - if in duplicate, please could you respond to the "new" issue #3671 

Thank you
