### ISSUE TITLE
Mist 0.5.2 on OSX EL Capitan syncs at launch but can't create a wallet. JS error in console.

### ISSUE THREAD

**Issue by johnpitchers** [ethereum/mist#366]
I'm getting a JS error in the developer console (Develop > Toggle Developer Tools > Wallet UI). It appears sockjs may be needed to open a web socket? 

Mist syncs at launch and then nothing. Trying to add a wallet contract and Mist shows "Creating..." but never gets anywhere. Geth running in terminal, I can see the blocks updating on my node but Mist's header shows an old block number and "xx minutes since last block" in red. It never updates.

Any help would be appreciated.

![misterror](https://cloud.githubusercontent.com/assets/6889409/13799064/0f4d5df8-eb57-11e5-8190-f451496ea638.png)

**Comment by luclu** [comment]
Please update to version 0.7.4 as this issue should be resolved!
