### ISSUE TITLE
Sync problem and OS

### ISSUE THREAD

**Issue by sr005307** [ethereum/mist#3660]
My cpu is G1850, 8GB RAM... // 128GB ssd * 2
WIndows 10 64Bit.
MIST newest version
=======================
I have a Sync problem.

Because my C:\ is full, I used another D drive(128GB ssd)
I linked to D: ethereum. It worked fine just before Current Block - 100 or so.

So I tried again and again. Rebooting on and on...
It never synced. I cannot understand why there are so many Chain Structures... 

ETH has blocks already... and what the Chain Structures for?? 
and Why mist downloads Chain Structures from number 1 every time I resetting MIST??

===================
SO I decided to format my C and raid as 256GB drive....
I'll do it next week..

Do you guys have any solutions?? for example... using ubuntu is better than using windows??
or Windows 7 is better than Windows 10??
[Actually My goal is to make ERC20 token.. is there simplist way with/without MIST sync??
p.s.. I already used Parity, and it su*ks... Sorry Parity developers..]

**Comment by pajendame** [comment]
Ive been there for a while. Here is my experience. Tryed to sync for 2 weeks, the blocks keep rising without succes. i think this is the solution, in any case it worked for me. Reinstall clean windows 10 on a new ssd HDD. The wallet synced in 24 hours with a good fiber 300Mbs connection. Even if u choose to install Mist o another partition, the wallet creates a folder on C partition where ur Windows is, a preety large folder that need to download +10gb. So if u dont have Windows installed on a SSD Disk and a minimum 100Mbs coonection dont even bother triyng - u will fail .
i hope this will help u - it worked for me.

Any small donation would be highly appreciated
ETH Wallet adress : 0x40Bb5a49A9448eEb17bAbf273A6e176E806d7334

**Comment by evertonfraga** [comment]
Hi @sr005307, after you've opened this thread we released a new version. Please try version 0.10.0 and see if this problem persists.

Make sure to enable the light client:
![30986199-ff885216-a468-11e7-82ec-e66aeb859ab8](https://user-images.githubusercontent.com/47108/30986236-1b7779a2-a469-11e7-8907-7e6b1aa16609.png)
