### ISSUE TITLE
mist can't find IPC: Moved Ethereum Folder to External SSD, geth running ok

### ISSUE THREAD

**Issue by jordimorris** [ethereum/mist#3661]
I followed Method 2 of this tutorial in order to move the Ethereum folders from local drive to external SSD drive

https://ethereum.stackexchange.com/questions/3307/in-mist-browser-how-can-i-move-the-data-blockchain-to-another-drive-on-mac-osx?rq=1

I'm running geth using:
geth --ipcdisable --fast

The issue is when I run Mist as it doesn't sync up or start, displays the following message:

Node type: geth
Network: main
Platform: darwin (Architecture x64)

...WARN [02-03|14:34:42] No etherbase set and no accounts found as default 
Fatal: Error starting protocol stack: datadir already used by another process

**Comment by ryanio** [comment]
Hey, we have released a new version (`0.11.0`) that should be more stable - please give it a try. If you have any new problems that you can reproduce, please create a new issue with the details on how we can help. Thanks!
