### ISSUE TITLE
Тестовый кошелёк 

### ISSUE THREAD

**Issue by DieHard8** [ethereum/mist#3662]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by DieHard8** [comment]
0x33ef0B3C291f127b29bcdb41e02d3dBF459bb980 как вывести с этого кошелька эфир? 

TxHash	Блок	Возраст	От		Для	Значение	[TxFee]
0x5cfde6ea385bd3da9e1edb58cd528ac642f604bb82e079d6e0e16a1c42f28c40	4713193	54 дня 7 часов назад	Ethermine	В	0x33ef0b3c291f127b29bcdb41e02d3dbf459bb980	0.045302401451213 эфира	0.000021
0x1976eea3a59cffd267913d5fdaf7129229f7442002ea5f7c3be27f4cd25c0884	4656358	64 дня 2 часа назад	Ethermine	В	0x33ef0b3c291f127b29bcdb41e02d3dbf459bb980	0.014698310049218 эфира	0.000021

**Comment by DieHard8** [comment]
Кто решит проблему ?

**Comment by marcgarreau** [comment]
Sorry, no one on this team speaks Russian. It looks like you were asking about how to withdraw from a wallet. Looking at etherscan, it appears you were successful, so I'm closing this issue. Please reopen in English if you still have an issue.
