### ISSUE TITLE
how can i get tokens sent to the wrong address

### ISSUE THREAD

**Issue by Noewi22** [ethereum/mist#3663]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by simon66** [comment]
If the token transfer was successful, then there is no way to recover it. It's sort of like giving money to the wrong person. The only way to get it back, is to find the original owner of the wallet you sent the token to.
If you can find that transaction on `https://etherscan.io`, you can leave a comment there in hopes that the wallet holder will read it, and refund your tokens.
