### ISSUE TITLE
Choosing folder at install

### ISSUE THREAD

**Issue by alexis26** [ethereum/mist#3664]
I read many many topics, tips n tricks, tutos, video (...) about moving folders, syncing with other place, symbolic link (etc...)

So, I decided to open it to ask you to (finally) propose this choice (the possibility of choosing the directory) during the installation ...
I don't think it will take a lot of time but it will make life easier for many people ...

... and with a sync size of a full hdd now, I even think it should be a priority!

sincerely,

**Comment by marcgarreau** [comment]
We know the size of the download is troublesome; this is something the geth team is working to address for the next release. The Mist UI does not offer a way to customize the download location, but you can try running a your own geth node via the command line and specify the `--datadir` flag (https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options). Mist will connect to your already running instance of geth.
