### ISSUE TITLE
Unable to add metamask account to Ethereum Wallet 0.9.3

### ISSUE THREAD

**Issue by dimimile18** [ethereum/mist#3665]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: ios
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```
How can add a metamask or myetherwallet existing account to the Ethereum Wallet 0.9.3?

Thank you in advance.

 -->

**Comment by evertonfraga** [comment]
Hi @dimimile18, here's how:

1. Click on account options (**…**) and confirm your master password
<img width="358" alt="screen shot 2018-03-28 at 12 49 38 am" src="https://user-images.githubusercontent.com/47108/38007956-7a166238-3222-11e8-8621-be80c37f3de1.png">

2. Click to copy that scrambled text (in my case, **c063f9...**)
<img width="359" alt="screen shot 2018-03-28 at 12 49 19 am" src="https://user-images.githubusercontent.com/47108/38008013-c3702bbc-3222-11e8-82ea-b6652f31e0dd.png">

3. Heads down to the terminal. please run `geth console`, then:
```
personal.importRawKey('c0693f...', 'your-new-password')
```

After that, your account should appear in Ethereum Wallet, when running on `main net`.

If you need any help executing these commands in a terminal, please let us know.
