### ISSUE TITLE
Stuck at "Creating contract"

### ISSUE THREAD

**Issue by doofie** [ethereum/mist#3668]
I've tried creating a contract/token based on the sample given by ethereum website. change the name and deploy the contract. However on my ethereum wallet, it kept saying its "Creating Contract". And it's like stuck for the longest time and it shows 0 confirmation. 

however when i go to etherscan, it shows the contract is created and it has already been confirmed. 

How do i get ethereum wallet to be updated of the contract? I've already sync the ethereum wallet

**Comment by evertonfraga** [comment]
Are you syncing with the light client?

There's a known (though fixed in the code) behavior that could prevent contracts from being shown as created. That should happen in the light client only. 

But as a workaround, you can copy the contract address and try to "Import wallet" and see if that work for you. Please let me know.

**Comment by doofie** [comment]
Hi,

i'm not using the light client at all. 

how do you import the wallet? It says i need the file? Which i don't have? I do have the contract address though, because when i check etherscan, it's shown that the contract was created.

Below is the pic of contract that's always in creating stage, even though i can see it on etherscan

<img width="654" alt="bug" src="https://user-images.githubusercontent.com/35016032/35873887-0ec21fce-0ba6-11e8-9b13-318d332a2206.png">

**Comment by ChristianLysne** [comment]
Same issue here. Using light client, version 1.8.1 of geth, version 0.9.3 of Ethereum Wallet. 
Etherscan says contract is created, but Ethereum Wallet shows "0 of 12 Confirmations"

**Comment by evertonfraga** [comment]
@doofie @ChristianLysne if you are sure your wallet contract has been published, you can go to "Add wallet contract" > Import contract > then paste the address of your wallet contract.

the following version will ship with a fix that eases this process.
