### ISSUE TITLE
Ethereum/Mist Wallet

### ISSUE THREAD

**Issue by borysmb** [ethereum/mist#3671]
I've asked for help in ethereum/Mist (https://github.com/ethereum/mist/issues/3658 still open) before filing this issue.  I'm not getting a reply/any guidance.  My issue is as follows:

I have relaunched the Ethereum Wallet application and want to access my wallet. I am given the option to open a new wallet but there does not appear to be an option to open an existing wallet. 
Who can I ask for support?

**Comment by marcgarreau** [comment]
Mist/Ethereum Wallet recognizes wallets by the keystore files saved in default locations determined by geth. For example, mainnet keystores on a Mac are stored in `~/Library/Ethereum/keystore/`. If you have a keystore file for an account already, just add that keystore file to the appropriate directory. If you only have a private key, you can use a service like MyEtherWallet to access the wallet, then download this keystore file.

**Comment by borysmb** [comment]
Thank you, but I don’t know what or who “geth” is. If I want to use MyEtherWallet to access the wallet and download the “keystore file”, how do I do this?

**Comment by marcgarreau** [comment]
geth is the go-ethereum client; it's the local ethereum node that your machine runs to connect to and interact with the ethereum network.

On MyEtherWallet, click on "View Wallet Info", then select "Private key" or whichever options applies to you. Once you unlock the wallet, you will see a button to download the keystore file.

**Comment by borysmb** [comment]
Hi Marc

 

This isn’t working.  I can see under the wallet address of my ethereum wallet in etherscan, and it shows the transactions, (ether in and out) and under “token tracker” 1,000 AMB, which is what I am trying to access.

 

I can’t complete the re-launch of the ethereum/mist wallet app, though when I did previously I couldn’t open the wallet that I can see in etherscan.  The ethereum/mist wallet uses a huge amount of space and pretty much stops everything else from working.

 

Given I can see it in etherscan, is there anything I can do from there?

 

Thanks

 

Borys

**Comment by marcgarreau** [comment]
Sorry, etherscan is useful for reading data, but not sending transactions. Do you have your keystore file? When you create a wallet in Mist, you are prompted to make a backup of the file.

I'm closing this issue, because I don't believe there is a bug with Mist. Feel free to continue asking questions, though.

**Comment by borysmb** [comment]
Marc

Thanks. I will review all this again when I get my laptop back. For now
I’ve been trying on my old machine but it’s just too slow.

Thanks

Borys
