### ISSUE TITLE
Tell me whats wrong ?

### ISSUE THREAD

**Issue by garethplayford** [ethereum/mist#3672]
Can someone tell me whats wrong with my PC?

1: My internet speed.

![down3](https://user-images.githubusercontent.com/29194467/35850938-5ab5a05a-0b1e-11e8-8e15-26efbfd46b21.png)

2: Wallet sync 24 hours ago.

![download1](https://user-images.githubusercontent.com/29194467/35850952-697d0434-0b1e-11e8-9537-8e31f95ecf0a.png)

3: Wallet sync now.

![download2](https://user-images.githubusercontent.com/29194467/35850969-729f1db8-0b1e-11e8-9866-b1e978399787.png)

I'm wondering when this will end? the sync.

**Comment by navaid9** [comment]
i am new bee my dear friend what is how to try again to start again new

**Comment by garethplayford** [comment]
I did start with light version sync, after light version sync I switched to normal .. today I woke up and its fully synced .... I guess I'm just lucky

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in **Light mode**, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com)

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
