### ISSUE TITLE
Failed Transfer

### ISSUE THREAD

**Issue by jheezy925** [ethereum/mist#3674]
Version: 0.9.3
OS & Version: Windows 10
Node version: Geth 1.7.2
Number of blocks synchronized: 5,054,120

I sent some funds on February 3rd to ShapeShift and it stayed at 0 of 12 confirmations, fine, so I waited and waited. Now it is the 8th and ShapeShift never received the ETH transfer. I saved my wallet key and re-installed/re-sync'd the wallet but still no luck. Etherscan doesn't even show the Tx https://etherscan.io/address/0x61f496d92d6e13a00a4d24a84225819d29bd6c8b
but my ETH is gone from the wallet..

**Comment by marcgarreau** [comment]
ETH can't just vanish -- if a transaction did eventually successfully send funds to Shapeshit, but Shapeshift didn't send anything back, you will need to contact Shapeshift support to get that sorted out. Hope you got it sorted out, but please provide more details if not.
