### ISSUE TITLE
Full sync ETH still zero

### ISSUE THREAD

**Issue by dendrees** [ethereum/mist#3675]
I have bought some new ether. Did a full sync no eth was added to the wallet.
Removed the block chain and did a full sync again, still nothing.
Re-installed the latest version and did a full sync again. Now my ether is completely gone even the previous ether is not showing up? Need some help please.

**Comment by simon66** [comment]
Hi @dendrees 
Go to https://etherscan.io/ and paste your `0x...` wallet address on the search field. Let us know if your ETH is still there. If you transferred to the correct address, there's no way it would disappear (unless your wallet has been compromised).

**Comment by evertonfraga** [comment]
Hi! We have an updated version with improved syncing. After downloading version 0.10.0, please enable the Light Client (`Develop > Sync with light client)`

I am closing this thread, if you still have any trouble **please feel free** to file a new issue or comment in an open one that better describes your situation.
