### ISSUE TITLE
"Insufficient funds for gas * price + value”

### ISSUE THREAD

**Issue by OperationNine** [ethereum/mist#368]
I have deployed the following smart contract and deposited 2 Ether into this below contract:

![c92b8d6e8674e9d7059fb925e6774b7c98b671319e121e3d86 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17868193/13801580/f1b2da3e-eb7e-11e5-85b8-3596b9d7cbc3.png)

When I was trying to send the 2 Ether from the Contract back to my Main wallet within the 1 hour time period I received this following error message:

![c92b8d6e8674e9d7059fb925e6774b7c98b671319e121e3d86 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/17868193/13801590/0dc883ea-eb7f-11e5-8d1a-977bc8c9ddfe.png)

Now that the time has been more than 1 hour when I am trying to request my Ether I have received the same error message.

**Comment by Canalytic** [comment]
Did you find a solution to this problem?  I am experiencing the same issue.
