### ISSUE TITLE
error

### ISSUE THREAD

**Issue by leechu84** [ethereum/mist#3682]
Version: `0.9.3`
Windows 10
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0

i have this massage about error. please help me

![eth](https://user-images.githubusercontent.com/36338340/36064865-f8d36a80-0e91-11e8-99df-6743fe4b0185.jpg)

**Comment by marcgarreau** [comment]
Geth 1.8.1 syncing with light mode should dramatically improve this experience. Once it find peers (could take a few min), you should be soaring. Let me know if that doesn't resolve your issue.

**Comment by philsmd** [comment]
Hmm, this problem could be interesting also for our investigation of #3513

@leechu84 as we can see in your error message you are using the "dev" network. 
This is actually very strang, if you are not using this feature intentionally, we should defintely investigate this problem carefully.

Did you select this option intentionally? Did you click on the "Solo network" menu option within the Develop/Network context menu?
@leechu84 can you please explain how you ended up with that error message? was this a clean/fresh install? What settings did you change? did you select main or test network? did you completely sync your node? any details could help troubleshooting these problems
