### ISSUE TITLE
Most recent Windows build is completely broken

### ISSUE THREAD

**Issue by LevyImage** [ethereum/mist#3685]
The only executable in the build is Ethereum Wallet.exe.
Geth executable is not included so none of the existing documentation is applicable to troubleshoot why this fucking node won't sync. A week to get past 5 million blocks downloaded and then this fucking wallet freezes after downloading 50 million chain structure. Been at this for weeks now just to get a working fucking node and I'm sick of it.

**Comment by LevyImage** [comment]
Not to mention, to get past 5 million blocks downloaded, the wallet freezed after about each 5K to 100K blocks downloaded. This is the worst wallet/node build I've dealt with out of all altcoins I've handled to date.

**Comment by lowlanda** [comment]
Is this STILL broken?

I gave up couple months ago, but assumed things would at least be progressing now

**Comment by hobbitlap** [comment]
I am totolly not able to sync and see my 0.2 ETH transfered from nanopool ...
I see them in etherscan, but cannot get my local wallet to sync and see it to trasnfert it OUT of the shit !!!!

**Comment by LevyImage** [comment]
So here's what happened, I said F it, and transferred to an exchange via offline transaction hash generated by myetherwallet. I had the same private keys from my was paper wallet into this official online wallet. Since I keep the original file contents and file name. I rebuilt that file to import when I first installed this official wallet. So after I had completed an out tx using myetherwallet's node, all of a sudden... my own node sync'd.  I don't know if coincidence or just luck after trying literally close to 500 times to sync the wallet. But that's what happened shortly after I made this issue. Sync'ing a full node is still obviously a massive issue however. So this issue should be left open until officially solved.

**Comment by marcgarreau** [comment]
Geth 1.8.1 syncing with light mode should dramatically improve this experience. Once it find peers (could take a few min), you should be soaring. Sorry for the pain-in-the-ass experience.

**Comment by LevyImage** [comment]
I don't want light mode, I want a full node, and from docs I read, once you pick a full node you can't go  to light mode and vis versa. Is this no longer true? Are both interchangeable?

**Comment by marcgarreau** [comment]
Light sync data is stored separately in a `lightchaindata` directory. It is my understanding that all syncing modes are greatly improved in geth 1.8.X, though.
