### ISSUE TITLE
Good day I send an amount of ETH to this adress 0x30040A0052BFf5aB63163610Ed42d2aDe69ded3f but until now it's not reflecting to my account how can I full it back.

### ISSUE THREAD

**Issue by Fortunato0605** [ethereum/mist#3686]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by simon66** [comment]
Hi @Fortunato0605 
Do you have any more info on this issue?
Looking at the transaction (https://etherscan.io/address/0x30040A0052BFf5aB63163610Ed42d2aDe69ded3f) the ETH was successfully transferred to the address. Are you the owner of `0x30040A0052BFf5aB63163610Ed42d2aDe69ded3f ` and do you have access to that wallet?

The only way to pull back that ETH is if you are the owner of that wallet, or you have access to that wallet.

**Comment by simon66** [comment]
@Fortunato0605 
If you are the owner of `0x30040A0052BFf5aB63163610Ed42d2aDe69ded3f` and you're not seeing that balance on `Mist`, that means you are not 100% synced with the network.
Please download the latest `Mist` Wallet and switch to `Light mode`.
Switching to `Light Mode` will allow you to view your balance/transactions without having to be locally synced to the network.

**Comment by marcgarreau** [comment]
@simon66 is correct @Fortunato0605, your balance will not be accurately reflected until your node is fully synced. The fastest way to do that is to make sure you're using geth 1.8.1 and syncing via light mode. Closing this issue, but feel free to ask additional questions if you get stuck.
