### ISSUE TITLE
Fails to sync on first run. Reaches block 10,240 and crashes.

### ISSUE THREAD

**Issue by pyskell** [ethereum/mist#3690]
- [] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: Windows 7
Node version: `whichever version is prepackaged with mist 0.9.3` 
Number of blocks synchronized: 10,240
```
On first run, clean install, I'm greeted with this screen:
![image](https://user-images.githubusercontent.com/9665963/36316555-a21780e8-1308-11e8-87f4-f9a4fae458a2.png)

It freezes at this point, after about a minute frozen I clicked "Launch Application" a couple times, nothing happened, and it crashed after a couple minutes, didn't notice at first.

Restarted and it starting downloading `swarm` and a new version of `geth` I believe `1.7.2` but I could be mistaken. After this "Launch Application" worked and syncing seemed to progress.

My guess is that whatever version of geth it ships with had an issue that the new version fixed.

I don't have an `all.log` or `category` folder with log files so I've attached the `node.log` files. Let me know if these help or if you need other files.
[node_logs.zip](https://github.com/ethereum/mist/files/1731934/node_logs.zip)

Just did a third run to get to the above log files and I'm unable to find peers. My system clock is up to date so not sure what's wrong here.

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting. We also removed swarm by default on the last version so it might help a bit there.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com)

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
