### ISSUE TITLE
Not a new Issue 

### ISSUE THREAD

**Issue by LM-Launch14** [ethereum/mist#3692]
- [ x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `10.13.1 `
OS & Version: osx
Node version: `geth 1.7.@` 
Number of blocks synchronized: 5,103,215
```

- Ether is not shown in the wallet
CORRECT THE DAMN THING NEVER CATCHES UP - in 90 days I have only been able to get it to Sync once.

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. This is typically an issue of geth taking a while to download many state entries before it can finalize the last blocks. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within MyEtherWallet.

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
