### ISSUE TITLE
I am syncing last 10 days to find ethereum in my wallet. Started 1000x and number of blocks that need to sync always goes up so can not be reached. Please help

### ISSUE THREAD

**Issue by vojnik011** [ethereum/mist#3695]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0` 
OS & Version: windows 7 home premium
Node version: win-ia32-unpacked
Number of blocks synchronized: 5,106,543 of 5,106,691


- Screenshot
![eth screenshot](https://user-images.githubusercontent.com/36565510/36341287-605c6832-1405-11e8-8fba-8205245c9770.png)

**Comment by tlechauve** [comment]
Same here, we need answer please or at least a workaround to manage our ethereum.

**Comment by tlechauve** [comment]
@pajendame, do you mean that without a fiber connection you can't sync your wallet ? i have a 10Mbs connection :(

Is there an alternative ?

**Comment by pajendame** [comment]
with that connection i think its posible but it will take a long time to download 60gb+ of blockchain

**Comment by tlechauve** [comment]
Currently my folder weight is 63GB, its downloading but never reach the end of block chain ...

**Comment by pajendame** [comment]
yes mate, been there done that :) for over 2 weeks i have waited to finish. Until i move windows to a new ssd. it took me only aprox 2 days to fully sync.

**Comment by beetelguice** [comment]
I like to know if there is site that the full chain can be downloaded and the move to an existing not as of ye synched wallet

**Comment by evertonfraga** [comment]
Hi all! We have an updated version with improved syncing. After downloading version 0.11.0, please enable the Light Client (`Develop > Sync with light client)`

I am closing this thread, if you still have any trouble **please feel free** to file a new issue or comment in an open one that better describes your situation.
