### ISSUE TITLE
Unable to attach to remote geth:no known transport for URL scheme "c"

### ISSUE THREAD

**Issue by Trace1712** [ethereum/mist#3701]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows10 64bit
Node version: `geth 1.8.1` 
```
<!--
- Unable to find peers
I am using the commond
geth attach
it shows Fatal:Unable to attach to remote geth:no known transport for URL scheme "c"
![bug](https://user-images.githubusercontent.com/32445760/36460415-2c9aa784-16f3-11e8-9347-73332cc49d82.png)
when I click on Run tests it shows
![runtest](https://user-images.githubusercontent.com/32445760/36460522-ba18dc2a-16f3-11e8-99b7-1cab570be5fc.png)
my version is the lastest
--！>
thanks for help

**Comment by MarcoRudolph** [comment]
Node version: geth 1.8.2

**Comment by MarcoRudolph** [comment]
Fix: geth attach ipc:\\.\pipe\geth.ipc

**Comment by dkackman** [comment]
@MarcoRudolph you need one more backslash
`geth attach ipc:\\.\pipe\geth.ipc`

**Comment by evertonfraga** [comment]
Added ipc syntax for windows to our wiki: https://github.com/ethereum/mist/wiki#connecting-mist-to-a-local-test-network-from-the-command-line

**Comment by kariukitito** [comment]
@dkackman, thanks...

**Comment by chamodmalintha** [comment]
thanks...

**Comment by neerajksharma00** [comment]
thanks....

**Comment by youcefmegoura** [comment]
`geth attach ipc://./pipe/geth.ipc` : on Windows OS*
