### ISSUE TITLE
I can't backup my Accounts

### ISSUE THREAD

**Issue by InkYang** [ethereum/mist#3705]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows
Node version: `geth 1.8.1` 
Number of blocks synchronized: 0
```

Hello everyone,
There are some problems in my ethereum wallet, once I backup my Accounts, it would open a folder: keystore but nothing in the folder. How can I backup my Accounts?

**Comment by ncsolar** [comment]
Do you see accounts in the Mist wallet tab?

**Comment by evertonfraga** [comment]
Hi @InkYang, here's a guide to back up your keystores: https://github.com/ethereum/go-ethereum/wiki/Backup-&-restore#backup--restore

Make sure you are backing up an account from the main network. I am closing this issue, but feel free to reopen it should you still have any considerations.
