### ISSUE TITLE
I can't create contract?

### ISSUE THREAD

**Issue by jsgang** [ethereum/mist#3706]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

I created contract,but not success? how to create contract?

**Comment by ryanio** [comment]
Hello, for contracts we recommend using [remix.ethereum.org](https://remix.ethereum.org) - thanks!
