### ISSUE TITLE
existing Ethereum Wallet on fresh windows installation

### ISSUE THREAD

**Issue by sam1138** [ethereum/mist#3707]
goodmorning

I have a question: if I want to make a fresh installation of windows or I want to move my ethereum wallet and start mining on another pc or in the worst case a hdd failuire, what is the procedure to restore my existing account (geth and ethereum wallet)?

thanks in advance for the help

David
```
Version: `0.9.3`
OS & Version: windows 10 64 bit
Node version: geth 1.8.1
Number of blocks synchronized: stuck at 65 blocks left
pc cable connected
internet speed: around 14 Mbps
Number of blocks synchronized: 5152860
```

**Comment by ncsolar** [comment]
This seems like a good answer https://ethereum.stackexchange.com/questions/946/how-to-backup-mist-wallets

**Comment by alexvandesande** [comment]
Go into `file > backup > accounts` and look for all folders called `keystore` (they might be inside other folders, like `rinkeby` of `ropsten`) and see if you find any wallet files (they usually begin with UTC).
