### ISSUE TITLE
Transaction didn't make it to bittrex. Cant find help.

### ISSUE THREAD

**Issue by Chefjeff42** [ethereum/mist#3709]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

Version: `0.9.3`
OS & Version: windows 10
Node version: `geth 1.8.1` 
Number of blocks synchronized: 5162214

https://etherscan.io/tx/0xcdd7662d26df9703bf84ec1760c750aee6dd8fcecb3b8837ac9ea8284fd6ddd7
Tried to make this transaction from my software wallet but its not show in my transactions nor did it make it to bittrex. Any help please?

**Comment by ncsolar** [comment]
Looks to me that your transaction failed, the GAS was to pay for the transaction was deducted from your ETH and that is the total you see in your address

**Comment by Chefjeff42** [comment]
Right but it should have carried back over to my wallet and it’s not even
showing in my transactions on my wallet and I have no idea on how to get it
back. Please I will take any help or advice

**Comment by ncsolar** [comment]
You sent the ETH from 0x05b70a6cb0600529F2F051bae676F37f66d5e7ab that is your address wallet right?

**Comment by Chefjeff42** [comment]
Yep that is my wallet address and I am synced to current blocks. I can send
you any screen shots of my wallet or anything you might need

**Comment by ncsolar** [comment]
I don't think i understand your problem, you have now in the same amount you had before you did that transaction minus GAS cost

**Comment by Chefjeff42** [comment]
No It should but it’s not appearing in my wallet like the transaction got
lost in the ether for lack of better term. The transaction doesn’t show in
my software wallet either

**Comment by simon66** [comment]
Hi @Chefjeff42 
Looking at your address (https://etherscan.io/address/0x05b70a6cb0600529f2f051bae676f37f66d5e7ab), your transaction failed due to insufficient gas (Which costed you `0.000021 ether`).
The full ethereum amount (0.636350476985705481ETH) is still present in your wallet. 
One of the reasons you might still see 0 ETH on your software wallet, is that you're not fully synced with the blockchain.

**Comment by Chefjeff42** [comment]
No I’m fully synced should I maybe try remove dB and do a full new sync?

**Comment by simon66** [comment]
@chefjeff42
No need.
Can you take a screenshot of mist showing that your balance is ‘0 ETH’?

**Comment by Chefjeff42** [comment]
You know I thought I was synced but I may have been wrong or something
might have gotten corrupted. I went to sync last night and my block was
only 5105xxx or somewhere in that neighborhood. I will give it some time to
sync and see what happens

**Comment by simon66** [comment]
@Chefjeff42 
Update to the latest version of `Mist` and switch to `light mode`. This way, you don't have to download the whole blockchain in order to see your balance/transactions (The blockchain will still be downloaded in the background).

**Comment by Chefjeff42** [comment]
Well crap that did it. I gues even though it was saying I was synced up the
most recent blocks weren’t showing that

**Comment by simon66** [comment]
@Chefjeff42 
Glad that it worked :)
There is a syncing issue with Mist, but that should be solved in the next release or so.
I guess this issue can be closed.
