### ISSUE TITLE
65 blocks left for 3 days!

### ISSUE THREAD

**Issue by Yubsep** [ethereum/mist#3712]
I already downloaded ~99.9% of full chain, **but there are 65 blocks left for 3 days!**
I had read all issues about synchronizing and trying many of solutions except one "Light Client Beta".
I just want any solution to get a full chain without using Light Client Beta. **Any help?!**

![opop](https://user-images.githubusercontent.com/17319861/36752234-2337c146-1c0b-11e8-8810-fe0ccb387dca.png)

**Comment by ncsolar** [comment]
What version of Geth are you running?

**Comment by Yubsep** [comment]
@ncsolar Geth 1.8.1

**Comment by ncsolar** [comment]
I think i noticed a discrepancy between what Mist shows and what i see Geth is showing in the terminal, according to Mist there are still blocks to download, but it shows up to date on the terminal for me, maybe is this for you too?

**Comment by Yubsep** [comment]
@ncsolar Yes, it's exactly what happens.

**Comment by evertonfraga** [comment]
Please enable the light client (Develop menu > Sync with light client). It is faster by an order of magnitude. 

It'll be the default setting soon.

**Comment by Yubsep** [comment]
@evertonfraga Ok, Thank you for interesting!
