### ISSUE TITLE
Are all my money gone because is sent my ETH before the wallet was fully synced?

### ISSUE THREAD

**Issue by Konneman** [ethereum/mist#3714]
I've been so tired of the ETH wallet since start, its always been buggy, ive lost alot of money and now ive just had enough.

Problem: I had 28 eu worth of ETH in my Ethereum wallet, my wallet wasnt synced (had no idea if it needed to be, and still dont know). But i sent all my ETH to my JAXX wallet which is a multi wallet that  can have like 15 different coins... The Money dissapeared from my wallet, and when i clicked on the transaction it said "Sorry, we are unable to locate this Transaction Hash".. After waiting maybe 2 hours i tried to sync the wallet which OF COURSE didnt work, because it never does, maybe 1/10 times.. After some google research i decided to save my Keystore file and Reinstall the wallet and resync it from the beginning, i installed it and added my keystore. The wallet still say 0.00 ETH/EU but now i cant see the transaction i made.....

the new wallet is almost fully synced, at 99%..- Will the money i sent appear in my ETH wallet or at the place were i sent it.

When i check the Adress i sent my ETH towards it says theres nothing there, and i payed the full FEE, meaing i couldnt pay more fee then i did.

This is the adress i sent my ETH towards: https://etherscan.io/address/0xd8118f7197f123b4c9b89a8fa6b4d7b7db041121

Are my money lost forever because of the extremly bad Ethereum wallet? Or do you guys have any suggestions of what to do......

The most wierd thing of it all is that after i sent the ETH, this is the  "transaction adress" that popped up

https://etherscan.io/tx/0x67790ea1ecb5c0ce832670ab3a4412b4574819655ed4a9041df63e28650e642b

and according to Etherscan.io thats not even a ETH transaction....

**Comment by Konneman** [comment]
If i check my wallets adress: https://etherscan.io/address/0x7A6C30baddbCbCf4A5152e332e4A8863B1026F05

it says i have 32 usd. But my wallet is ALL empty.... 25k more blocks to go then its fully synced, will my money appear then? Or what is up, i dont understand this walelt at all...

**Comment by Konneman** [comment]
My wallet is now fully synced but says i have 0.00 USD, while the link i just sent says i have 32 USD? I have no idea what to do now...... Please i need some help...

**Comment by marcgarreau** [comment]
The wallet you linked to does indeed contain around $32 worth of ETH. Mist/Ethereum Wallet should reflect this is you are 1) on mainnet, 2) fully synced, 3) and have that wallet imported or created with the app.

**Comment by Konneman** [comment]
Hello Marcgarreau,

1) im on the mainet 2) im now fully synced and 3) i have Exacly that wallet imported in my Ethereum wallet. but it still only shows that i have 0.00 ETh.......

**Comment by Konneman** [comment]
now it says i have 130 blocks left, but just some minutes ago it was fully synced, do i need to click on some update button or something after its fully synced?

**Comment by marcgarreau** [comment]
No, the balance will update when the node is fully synced. The fastest way to sync is with the light mode (found under the "Develop" menu) if you have updated to geth 1.8.1.

**Comment by Konneman** [comment]
I restarted the app and now it says "Downloading block 5,171,640 of 5,171,712"

**Comment by marcgarreau** [comment]
You can always access your wallet using a service that utilizes a remote node, like MyEtherWallet or MyCrypto. Thanks for your support.

**Comment by Konneman** [comment]
I can, how do i do that? Dont i need some sort of Json file for that?

**Comment by marcgarreau** [comment]
Wallets created with Mist/Ethereum Wallet produce a keystore file. You can view them through the menu -> File -> Backup -> Accounts. You'll see one file for each wallet you have (they begin with "UTC"). That keystore file + your password can be used to manage your wallet from MyEtherWallet . com or MyCrypto . com.

**Comment by Konneman** [comment]
finally it fucking worked, now i NEVER have to use the WORST wallet ever created in the history of Cryptovalue.. there is a reason there is thousands and thousands of threads about this Wallet, my Tip to everyone, dont ever USE this wallet, there is PLENTY of others that works way faster and dosent have to sync for daaaaays to work.

**Comment by marcgarreau** [comment]
Thanks for your support.
