### ISSUE TITLE
geth take long long time to connect to peers

### ISSUE THREAD

**Issue by sam1138** [ethereum/mist#3716]
hi as in subject I have this issue: geth thake a lot of time to find peers and stays in the condition you can see in the screenshot attached

second question: is it true that I have to wait geth to be sincronized before to start mining?

thanks for support and answers
![immagine](https://user-images.githubusercontent.com/36677861/36812309-1431980e-1cd1-11e8-8a32-d37601dd65bc.jpg)

Version: `0.9.3`
OS & Version: windows 10 64 bit
Node version: geth 1.8.1
pc cable connected
internet speed: around 14 Mbps
Number of blocks synchronized: 5152860

**Comment by evertonfraga** [comment]
Hi @sam1138, I'm afraid you'll get more information on Geth repository: https://github.com/ethereum/go-ethereum

this repository is the home of Mist or Ethereum Wallet.
