### ISSUE TITLE
Yobit.net Deposit issue

### ISSUE THREAD

**Issue by mwaqar17** [ethereum/mist#3718]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

I have deposited LHCOIN tokens to yobit exchange, It is successful in my account and also showing in LHCOIN exchange address. Checked via etherscan.io  I have contacted support but they are not responding.

**Comment by simon66** [comment]
Hi @mwaqar17 
I'm a bit confused. What is the issue here? You transferred LHCOIN to YoBit but it's not showing on YoBit?

**Comment by mwaqar17** [comment]
Actually I am new in this crypto field. I wanted to exchange my token. I transferred token to address given by yobit exchange for deposit. It have gone almot 3 days. It is still not showing up in my account balance. and they are also not responding to my ticket.

**Comment by simon66** [comment]
Yea, you need to contact YoBit support and not Mist.

YoBit Twitter: https://twitter.com/YobitExchange?
YoBit Support: https://yobit.net/en/support/

**Comment by mwaqar17** [comment]
I have tired alot...no response from any side, what to do now ?

**Comment by simon66** [comment]
My only advice for you is to start using better exchanges. If you google YoBit, you will see that there's a lot of bad press. Keep trying to get a hold of them, but there's nothing `Mist` or the Ethereum team can do to help you.
Best of luck recovering your tokens.

**Comment by marcgarreau** [comment]
thanks for helping out with issues @simon66 👏 

@mwaqar17 I'm sorry to say this is indeed not an issue we can help you with from our side. You will have to rely on the Yobit team. Good luck - hoping they get back to you soon.
