### ISSUE TITLE
Ethereum Mist Wallet crashes

### ISSUE THREAD

**Issue by vollkommenegal2017** [ethereum/mist#3720]
- [X] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: win 7, x64
Node version: `geth 1.8.1` 
Number of blocks synchronized: 5178186
```

The software crashes while sync since 2 days now. Completly. No error message.
Balances of ETH and other tokens/contracts are shown correctly at programm start.
1-2 minutes lafter the program crashes.

Sorry, can't say more than that. Normally it's working fine.
200 GB free disk space, 10 GB free RAM, reboot changed nothing

Ah, there was a message shown some days ago. I should update to v0.9.4, but when I "check for updates..." everything is ok and https://github.com/ethereum/mist/releases also shows v0.9.3 as the latest version.

Any suggetions what I can do now?!

**Comment by simon66** [comment]
Hi @vollkommenegal2017 
This is a know issue which the `Mist` team is working hard to fix. In the mean time, you should download the latest version of `Mist` and switch to `Light Mode`.
This will allow you to view/transfer your funds without having to fully sync with the network.

**Comment by vollkommenegal2017** [comment]
I tried this

https://www.reddit.com/r/ethereum/comments/669cn9/how_to_use_the_geth_light_client_in_combination/

but it doesn't work.

I guess,  I will have to wait for v0.9.4  :-)

**Comment by simon66** [comment]
Hi @vollkommenegal2017 
Keep in mind that the post you mentioned is 10 months old :P
Are you using `Mist GUI` or are you using `Geth CLI`?

I don't have `Mist` running on my machine but this is how you unable `Light Mode`. (This picture might be a bit outdated).
![Mist Light Mode](https://andersguide.files.wordpress.com/2017/06/ethereum-light-client-setup2.png)

Let me know if that works

**Comment by vollkommenegal2017** [comment]
Great news.

Yes, it's 10 months old, but a friend helped me and it's working now. I have access to my ETH and other tokens. *whoop* *whoop*
