### ISSUE TITLE
Password incorrect + Eth in account only when light sync active

### ISSUE THREAD

**Issue by TheJeepee** [ethereum/mist#3722]
Installed Ethereum Wallet Mist, let it download all blocks before using it. Opened Ethbase (first wallet), set password, send ETH from Binance 1 hour ago, ETH is in that account when sync with light is active, but not when it is not. Cant send ETH forward because "Incorrect Password". I use copy paste for my password and I know it to be correct. 

What to do? Can't also open geth console, because Win 10 seems shutting it down when I try open it.

**Comment by TheJeepee** [comment]
Hi @simon66 

Got it open in MyEtherWallet, but balance is 0 ETH. Unfortunately I dont have private key.

**Comment by simon66** [comment]
@TheJeepee 
Would you mind posting the ETH address? This way I can see the transaction history.

**Comment by TheJeepee** [comment]
0x774e18452e355aAD2E15f88b1130AC841e2c4cE4

**Comment by simon66** [comment]
@TheJeepee 
Looking at https://etherscan.io, I see that your ETH is in that address (0.2897 ETH). Are you sure you uploaded the correct address to `https://www.myetherwallet.com/` or `https://www.mycrypto.com/`?

**Comment by TheJeepee** [comment]
Ah, that was my mistake. That was wrong one. Now uploaded the correct one, but giving me wrong password.

**Comment by TheJeepee** [comment]
But I still do have my Private key, can I solve it with it? UTC file one?

**Comment by simon66** [comment]
@TheJeepee 
Then in that case, your password is wrong. Make sure that when you copied your password, you didn't add any other characters to it (Like an extra space)
Your UTC file is your wallet. Your private key is inside of it, but since your wallet is encrypted, you cannot extract the `private key` unless you know your `password`.
