### ISSUE TITLE
Wallet reset when used "geth --fast --cache=2048 --port=0" command

### ISSUE THREAD

**Issue by entropy187** [ethereum/mist#3727]
Hey guys, so im using the mist wallet, and for 3 hours ive been trying to receive my ether. its in etherscan, but not the wallet. so i tried refreshing/syncing by using geth --fast --cache=2048 --port=0... but i closed the wallet first.. it seems to be loading the blocks now BUT my previous wallet signed in is reset? and previously i couldnt even back up the account. is my ether gone? 

I only had Appdata/Roaming/Ethereum Wallet folder though but thats about it

**Comment by simon66** [comment]
Hi @entropy187 
What operating system are you using?

**Comment by entropy187** [comment]
thank you @simon66 i initially did as you requested but it wasnt doing anything for 15minutes, so i re downloaded the blocks and selected that, and balance is reflected. i am also happy that i managed to find my old account backup on my PC
