### ISSUE TITLE
Blockchain fully synced, eth balance still 0, everything works when I access my wallet from myethwallet.com

### ISSUE THREAD

**Issue by RazerBoy1** [ethereum/mist#3728]
Hey lads. I've downloaded/installed the mist ether wallet. I then started mining on the new wallet ( https://www.etherchain.org/account/0x21C503cb82AE4f770D2DB66bA589b2086187c2aB ). You can clearly see 2 transactions were already made. The block chain is fully synced (http://prntscr.com/in71e0 ) and I've tried restarting multiple times, but yet my balance still remains at 0 (https://prnt.sc/in6m0r ). BUT when I open my wallet on myetherwallet.com with my keystore file and password I can clearly see my balance (http://prntscr.com/in6r02 ). 
Even if I try to download the keystore file from myetherwallet.com and go to my mist wallet and do "File" -> "Import accounts" it doesn't work. 
On this thread https://github.com/ethereum/mist/issues/2584 I found someone saying to run "geth console" and then to type the command web3.eth.getBalance('0x21C503cb82AE4f770D2DB66bA589b2086187c2aB'). I did, the return result was 0 (https://prnt.sc/in6u6o). This is one of threads that looked super related to the problem I'm having after like 1 to 2 hours of googling it, also looked through this https://github.com/ethereum/mist/issues. And the funny part is, it ended in the guy who needed help saying "no help whatsoever. what a fucking disappointment that ethereum is", which I found really funny lol. With 3 thumbs up! I added the 4th for the lulz. All of the threads end in basically no answer or a answer which doesn't solve the issue (person who asks for help gives up), since the issue might be a bug/bugs in the application...
So what can I do now. I can clearly see the transactions on the block chain, I can clearly see the balance in myetherwallet, but I can't figure out why it doesn't show up on my Mist wallet. I know this isn't a BIG ISSUE, since I can always use myetherwallet, but I'd still rather have a local wallet. So if anyone could help me, I'd be very grateful! Might be a geth bug/issue?

I've now send my eth to binance from myetherwallet.com. It of course worked (https://etherscan.io/address/0x8a7a881b5941ab7a97b10837f1c6994c29239ae4).

Also posted on gitter.im. If I get an answer there I'll update my post here also, if other people experience the same issues...

**Comment by simon66** [comment]
Hi @RazerBoy1 
After looking at your screenshots, `Mist` was not fully synced with the network
![not syned](https://image.ibb.co/eHEJYS/download.png)
You're still missing around 65 blocks. There are users who are having issues fully syncing with the blockchain (As you can see in the issues page).
If you're still unable to view your balances, switch to Mist `Light Mode`. This will allow you to view/transfer your balance without having to fully sync with the network.

**Comment by RazerBoy1** [comment]
But isn't the wallet still suppose to show the transactions you already have. Like on the picture you can see I'm on block 5201761. My initial 2 transactions to my wallet were made a lot before that. block 5157026 and 5199082. Shouldn't this already be shown, since it already has that information. I'm asking this since I never get a full sync on the wallet. It always stops about 50-60 blocks before ending.

For instance. If I made a transaction on block 1 (yes, the very first block of eth) of 1 eth to my wallet. And then left the wallet alone to this day. Then synch the wallet to block 5201761 and be 50 blocks off the full synch. Would I see the balance or no? 

I always thought you see the balance after you've passed the block it was mined on. Or am I being dumb :D?

**Comment by marcgarreau** [comment]
Your thinking is not dumb :) After syncing most of the blocks, geth syncs the blockchain _state_. Its quite a large download and is required before the wallet will show you accurate balances. As @simon66 suggested, Light mode is the quickest way to get there. Closing the issue, but please feel free to continue the conversation if needed.

**Comment by RazerBoy1** [comment]
Thank you for your help. I was able to resolve my issues with this :). At least I think so http://prntscr.com/inbt73. Looks good to me now :). I won't know for sure until the next week (when I get my next payout from ethermine). But I am fairly confident that it has worked. Since it now actually tells me which block I am on and how much time has passed since the last block.

**Comment by simon66** [comment]
@RazerBoy1 
Glad to see that its working 👍
