### ISSUE TITLE
Checksum mismatch in dowloaded node!

### ISSUE THREAD

**Issue by stbregeon** [ethereum/mist#3730]
version 0.9.3
gpl-3.0
geth ?? no longeur since this morning
synch with light beta
block 4 ?? no longeur since this morning !
windows 8

This morning a  message has apperead : 
cheksum mismath in dowloaded node ! 
MDS : 3080558f77ea924596379d3dfsdcd
please install the geth node version 1.8.2 manually

where i can find the geth 1.8.2 ?
and where I downlowd it (witch  directory ? )

thank ypou very much ? 

![geth node 1 8 2](https://user-images.githubusercontent.com/32129560/37034153-995a47d0-2148-11e8-836f-40f92cb143e4.JPG)

**Comment by evertonfraga** [comment]
I am on this, thanks for reporting, Stephanie.

**Comment by stbregeon** [comment]
thank you very much, Everton

**Comment by INTERESTING-OMG** [comment]
I have the same question! I fond the 1.8.2geth and download it . It hava a serious problems. I use the private chain and  deploy contracts on it , when I restart the mist the contract missing...
sorry I am not good at English..
Now,I want use the old version and the question hanppened!

**Comment by evertonfraga** [comment]
@INTERESTING-OMG those are different issues. would you please open a new issue, describing your problem? 

thank you

**Comment by INTERESTING-OMG** [comment]
@evertonfraga Ok

**Comment by edumb** [comment]
Good Morning. I'm using google translator to speed it up. For me it was giving the same problem reported, so I downloaded geth 1.8.2 at https://geth.ethereum.org/downloads/ .. During the installation of this version, my antivirus detected the following file:

![worm](https://user-images.githubusercontent.com/33008443/37036718-422aaaf4-212f-11e8-855c-09c98aee5ad5.jpg)

**Comment by evertonfraga** [comment]
@edumb o Mist não baixa o geth neste diretório. Você fez o download do Geth por onde?

**Comment by evertonfraga** [comment]
Hi, checksum problem identified and solved. Somehow, our script hasn't updated the windows 32 and 64 checksums, leading to "Checksum mismatch" error to the users.

**Affected systems: Windows 32 and 64bit** (Linux and Mac checksums are OK)

**Affected users:** whoever updated to Geth 1.8.2 within Mist/Wallet interface in the short span of *2018-03-06 01:56 CET* to *2018-03-06 15:02 CET*

**Steps to solve:** Restart Mist or Ethereum Wallet. It should acknowledge the new checksum from this remote file. If you have already downloaded the latest Geth version, it'll check against its `md5` checksum and things should be fine.

Sorry for this inconvenience.

**Comment by evertonfraga** [comment]
@edumb de qualquer maneira, siga os passos acima para resolver e você não precisa usar essa versão que acusou vírus.

**Comment by edumb** [comment]
I did the download in this directory: https://github.com/ethereum/mist/releases...

Ok...I'll try to reinstall

**Comment by SHKhan83** [comment]
I'm getting this error for version 0.11.1.  Can anyone please help me?  I'm using Windows 10 and geth is fully synchronized.
![checksum mismatch](https://user-images.githubusercontent.com/49203190/55572005-af8fc080-56d4-11e9-88ea-3790f474e1b1.png)
