### ISSUE TITLE
Тестовый кошелёк.

### ISSUE THREAD

**Issue by DieHard8** [ethereum/mist#3733]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by DieHard8** [comment]
Как вывести свой эфир с майнинга , с тестового кошелька.

**Comment by DieHard8** [comment]
![desktop screenshot 2018 03 05 - 20 01 13 36](https://user-images.githubusercontent.com/36109154/37049812-2c30eee4-2183-11e8-963a-7992353ffbce.png)

**Comment by DieHard8** [comment]
![desktop screenshot 2018 03 06 - 21 13 36 96](https://user-images.githubusercontent.com/36109154/37049858-522cfc28-2183-11e8-81c2-c73661d1d979.png)

**Comment by DieHard8** [comment]
Как вернуть свой эфир ???????

**Comment by simon66** [comment]
Hi @DieHard8 
I hope I understood your question. You're having issues displaying your ETH and transactions on `Mist`, right?
You will need to sync with the network in order to view your balances and transactions on `Mist`. Optionally, you can switch to `Light Mode` so speed up the process. `Light Mode` allows you to send/view your balance without having to fully sync with the network.
This is how you switch to `Light Mode`
![Mist Light Mode](https://image.ibb.co/cZxaDS/Capture.png)

**Comment by alexvandesande** [comment]
It seems you accidentally sent ether to your test account. When sending to incorrect networks (including test networks and classic) your account exists on all of them simultaneously. Go into `file > backup > accounts` and look for all folders called `keystore` (they might be inside other folders, like `rinkeby` of `ropsten`) and see if you find any wallet files (they usually begin with UTC). Put all of them in your main `keystore` folder and restart mist.

**Comment by DieHard8** [comment]
Здравствуйте . Большое, человеческое СПАСИБО.



>Среда,  7 марта 2018, 21:28 +03:00 от Alex Van de Sande <notifications@github.com>:
>
>It seems you accidentally sent ether to your test account. When sending to incorrect networks (including test networks and classic) your account exists on all of them simultaneously. Go into file > backup > accounts and look for all folders called keystore (they might be inside other folders, like rinkeby of ropsten) and see if you find any wallet files (they usually begin with UTC). Put all of them in your main keystore folder and restart mist.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Александр Лянченко
aleksandr.lyanchenko@mail.ru

**Comment by DieHard8** [comment]
Эфир увидел. Вывести на кошелёк смогу ?


>Четверг,  8 марта 2018, 0:08 +03:00 от Александр Лянченко <aleksandr.lyanchenko@mail.ru>:
>
>Здравствуйте . Большое, человеческое СПАСИБО.
>
>
>
>>Среда,  7 марта 2018, 21:28 +03:00 от Alex Van de Sande < notifications@github.com >:
>>
>>It seems you accidentally sent ether to your test account. When sending to incorrect networks (including test networks and classic) your account exists on all of them simultaneously. Go into file > backup > accounts and look for all folders called keystore (they might be inside other folders, like rinkeby of ropsten) and see if you find any wallet files (they usually begin with UTC). Put all of them in your main keystore folder and restart mist.
>>—
>>You are receiving this because you were mentioned.
>>Reply to this email directly,  view it on GitHub , or  mute the thread .
>
>
>С уважением,
>Александр Лянченко
>aleksandr.lyanchenko@mail.ru


С уважением,
Александр Лянченко
aleksandr.lyanchenko@mail.ru

**Comment by DieHard8** [comment]
Забыл пароль - где посмотреть ?



>Среда,  7 марта 2018, 21:28 +03:00 от Alex Van de Sande <notifications@github.com>:
>
>It seems you accidentally sent ether to your test account. When sending to incorrect networks (including test networks and classic) your account exists on all of them simultaneously. Go into file > backup > accounts and look for all folders called keystore (they might be inside other folders, like rinkeby of ropsten) and see if you find any wallet files (they usually begin with UTC). Put all of them in your main keystore folder and restart mist.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Александр Лянченко
aleksandr.lyanchenko@mail.ru
