### ISSUE TITLE
exeeds block gas limit when i want to sent from ethereum wallet

### ISSUE THREAD

**Issue by nick3527** [ethereum/mist#3737]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `?.?.?` it says its the newest version i tried to update it 03/07-2018
OS & Version: windows
Node version: `geth 1.8.2` 
Number of blocks synchronized: ???
```
well guys i have this issue i have some ether on my account i want to pull out to sell it.... but when i try to send it to a site where i can sell it... it just says "exeeds block gas limit" wtf does that mean? what can i do to get it to work???? its like alot of ether we are talking....... -.-

**Comment by nick3527** [comment]
Hello @simon66 no i wasent fylly synced and now when i logged in my 20 ether is gone  -.- is there any way to get that back it's not on the account I tried sending it too when the error came up it's just gone.....

**Comment by simon66** [comment]
@nick3527 
Whats the wallet address? We might be able to see the transaction online.

**Comment by nick3527** [comment]
i hope you can find it -.- 
the adress is a0645d4e7f9bdfc3f3053217b288a8d37cbce323
there was 20.00 ether on it last evening but when i logged on after i gave up on trying to withdraw... it was like 1 hour after i last checked the balance was 00.00
and i was really pissed

**Comment by simon66** [comment]
Hi @nick3527 
That address posted has 0 ETH. There are no transactions on that account (ever).
Are you sure thats the correct address?

**Comment by nick3527** [comment]
yup im positive -.- i can also see alot of other people on the forum having same issue guess ill never use this wallet again
it cost me 14 grand thanks

**Comment by nick3527** [comment]
and yeah i can see it has 0 ether on balance thats the issue i dont know where the 20 ethereum went..... thats the problem

**Comment by simon66** [comment]
Hi @nick3527 
The issue here is not related with the wallet nor Ethereum. From that address you gave me, there was never any ETH deposited to it. Where did you buy ETH from?

**Comment by nick3527** [comment]
i mined it and when i had a good sum of ether i downloaded the wallet and it found my geth adress by it self and my balance was allready in....

**Comment by nick3527** [comment]
its suppose to find any adresses by it self so i didnt think anymore of it

**Comment by nick3527** [comment]
but now its gone

**Comment by simon66** [comment]
@nick3527 
Looking at Etherscan, no transactions was ever sent to address `0xa0645d4e7...`
What site you used to mine? If thats really your address, the mining pool never paid you out.

**Comment by nick3527** [comment]
i used my own pc with ethminer applied to my cmd and run it like that never had problems

**Comment by simon66** [comment]
Ah, so you mined it locally. I'm not too familiar with local mining, so this is as much help as I can give :(
@evertonfraga or anyone from the Mist team might be able to help you out. They should reply in the next few days or so.
Don't give up on finding those ETH's! 20 of them is quite a lot :P

**Comment by nick3527** [comment]
yup thats why im pretty mad and i need to find them do you guys pay for lost transactions? or what can i do? like really im not native english and in my country thats like a years salery.....

**Comment by marcgarreau** [comment]
thanks for triaging @simon66. @nick3527 are you sure this mining was done on mainnet and not a testnet or solo network? mining is quite difficult to do on mainnet with an average PC these days. Simon is correct in saying that the address you shared has never had any ETH transaction in or out of it.

**Comment by nick3527** [comment]
yup its synchroniset and all it is running fine but i dont know how they can be gone i have no clue but ive read about lot of bugs on your wallet after i couldnt withdraw and lost my balance..... its alot of money.....

**Comment by nick3527** [comment]
i have synched geth and ethminer to the network so there is nothing there....

**Comment by marcgarreau** [comment]
I'm sorry for your trouble, but that wallet never had any funds in it. If the address you shared ever did, you would see them via etherscan here: https://etherscan.io/address/0xa0645d4e7f9bdfc3f3053217b288a8d37cbce323. Check the coinbase address provided to your miner, and see if you have any logs of successful blocks mined. Double-check that you weren't using a private network (instead of mainnet). 

I have very little information to work with. Closing the issue and will reopen if you can produce evidence of a potential bug. Feel free to continue the conversation.

**Comment by nick3527** [comment]
i know i should have taken a picture the only witness i have is my mom se saw it but dont know if that can be used..... what can i do? honestly its 14 grand

**Comment by simon66** [comment]
Hi @nick3527
When did you mine these coins and how long did you mine for? I have a feeling you either mined on a test net or you mined it to the wrong address.
I can answer with 100% confidence that no ETH was ever deposited to that address you provided.

**Comment by nick3527** [comment]
for a long time and i can hear this conversation goes no where..... have a good day and fuck you too..... wont EVER use this shitty program again... and no good pr will come from me......

**Comment by nick3527** [comment]
you dont even know if i used a rig? you dont know anything about my mining station and now you tell me that.... wow..... amazing.... dont konw any of my parts or anything...... this wallet cost me 14 k its not your money so ofc you dont care.... fucking scammers

**Comment by marcgarreau** [comment]
Our code is all open source. No one's trying to scam you. Let us know if you can find any additional details, like another account that may be linked to your mining rewards, etc. Good luck.

**Comment by simon66** [comment]
@nick3527 
Wow, I did not see that coming. Ever heard the saying "don't bite the hand that feeds you"?
It's like @marcgarreau said, the whole project is open sourced, if you think anyone is scamming you, please feel free to study the code and inform the users as to how you got scammed. This looks like a user error and not a software error.
Best of luck.
