### ISSUE TITLE
splash screen should allow the user to perform some action in case of errors

### ISSUE THREAD

**Issue by philsmd** [ethereum/mist#3742]
Whenever I see an error in the splash screen for instance this one "Ethereum node connection error:'(" I don't understand what should be done and if I need to wait until the connection is established etc.

I would recommend to show a message with a better description what is going on and also allow the user to perform some action, for instance let the user close the window with a button etc.

BTW I think there should be at least a space between "error" and ":'("

---

hmm, nevermind it seems to be added here ONLY for the single connection error (in the code I see many cases for errors in the splash screen!): c6e5e7279dbd2fac91467a40500af3358f79273a
the problem with the ":'(" is still present with newest version
Furthermore, I think there should also be an alternative option to close the window if also retrying to reconnect fails.

**Comment by marcgarreau** [comment]
Resolved via remote node connection in the 0.11.0 release. Thanks for originally reporting it.
