### ISSUE TITLE
Generate better release notes / change log

### ISSUE THREAD

**Issue by bitpshr** [ethereum/mist#3743]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: 0.9.4
OS & Version: N/A
Node version: N/A
Number of blocks synchronized: N/A
```

This issue arose from [this comment](https://github.com/ethereum/mist/pull/3015#issuecomment-371945108) by @evertonfraga.

Currently, the only list of developer-focused changes between releases exists in a manually-written change log section in the [notes for each release](https://github.com/ethereum/mist/releases/tag/v0.9.3). This is both tedious and prone to human error; various PRs and commits could be unintentionally omitted and downstream developers miss out on information on important changes. Traditional `CHANGELOG.md` files fall victim to the same issues.

It'd be nice to use [release](https://github.com/zeit/release) to automate the process of version bumping, git tagging, and GitHub releasing. This would both guarantee that notes for every release have a detailed list of code changes with commit references, and force a strict adherence to semver.

I am working on a PR now, so feel free to assign this issue to me.

**Comment by fsilva22** [comment]
+1 for using `release`. It just automates the manual process of tagging and releasing, with the bonus of a very thorough and organized changelog. Let me know if I can help, this would be a big win.
