### ISSUE TITLE
Wallet screen should provide sortable list view of accounts

### ISSUE THREAD

**Issue by xor-freenet** [ethereum/mist#3745]
The bulky icon view may be nice for first time users but is inconvenient for managing multiple accounts:
- the account name isn't fully visible if the accounts have a long name.
- it's not possible to selectively sort by field such as e.g.:
  - account name
  - balance
  - address
   - creation date (to judge which accounts are cycled into a sufficient amount of backups)
   - number of received/sent transactions (to avoid re-use).
   - passwort hint (see #3744)

Thus I would suggest providing the option to switch to a list view and having it contain columns as suggested above.

(I have not used the contract-based wallets yet, if they also use an icon-view then this issue applies to them as well of course.)

**Comment by evertonfraga** [comment]
I've moved this suggestion to the proper repository 😉
