### ISSUE TITLE
Transaction not completed since more than 2 days with maximum fees

### ISSUE THREAD

**Issue by lnguy** [ethereum/mist#375]
Hello,

How do I deal with a failed transaction issue:
1 Contract not created
2. Deposit not received by a Contrat listed in dapps.ethercasts.com (Dynamic Pyramid). I have sent a message bu they are not replying on Bitcointalk
Thanks

**Comment by alexvandesande** [comment]
Are you using the Official wallet? How many peers do you have? In which block are you?

**Comment by lnguy** [comment]
Yes I have used the Ethereum Wallet. Block 1139848
<https://etherscan.io/block/1139848> and 1149868
<https://etherscan.io/block/1149868>

Thanks

2016-03-16 18:57 GMT+01:00 Alexandre Van de Sande <notifications@github.com>
:

**Comment by alexvandesande** [comment]
Your wallet is very behind and has not synced up since homestead. Have you downloaded any wallet since version 0.5? This might be the culprit
