### ISSUE TITLE
Why does it take a few tries before the Mist and Ethereum Wallet loads, and why does it take forever for the sync to occur and why does it run so slowly?

### ISSUE THREAD

**Issue by CaravacaCruzCreations** [ethereum/mist#3752]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0` 
Number of blocks synchronized: 0
```

**Comment by simon66** [comment]
Hi @CaravacaCruzCreations 
You can read all about the syncing issues here #3673

**Comment by sluTTYusr** [comment]
Honestly this piece of software is such letdown... every time you fire it up it's like a lottery if it will work or not. 
Even with the light client feature... 0 peers, waiting for blocks since 45 minutes now.

**Comment by marcgarreau** [comment]
Cleaning up stale issues; more recent releases of mist + geth have addressed related issues. Please reopen/open a new ticket if appropriate.
