### ISSUE TITLE
I did not receive the ETH

### ISSUE THREAD

**Issue by Wonderboo** [ethereum/mist#3753]
I was testing the Ethereum Wallet, and today Ethermine was sent Ether for Ethereum Wallet, but I did not receive anything and I do not know if I have to do anything.

I hope help. Thank you

**Comment by mattlbailey** [comment]
I have the same issue. I sent my ETH to my wallet on March 10th and it still does not have any confirmations. I tried again on March 11th and a third time on March 13th, and it still has not sent.

**Comment by songjunyan** [comment]
yes i do

**Comment by Wonderboo** [comment]
Do I need to create a contract to normalize? For when I try to create the error "exceeds gas block limits"

**Comment by simon66** [comment]
@Wonderboo 
Thats your wallet address? There's no need to create a contract in order to see your balance.

**Comment by marcgarreau** [comment]
@Wonderboo you can receive funds without having to do anything (including using Ethereum Wallet). To verify if you properly received the funds, you can use a block explorer like etherscan.io and search for your address. The transactions are public and you would see any incoming funds.

**Comment by Eric201803** [comment]
[ Ethereum Wallet] I have the same issue,I can not see my balance  unless using light wallet(beta). My ethereum wallet version 0.10.0
i think it is like a bug.

**Comment by evertonfraga** [comment]
@Eric201803 not a bug. Light Client (beta) syncs super fast, while other methods take a while (hours, days)z
