### ISSUE TITLE
No peers at all

### ISSUE THREAD

**Issue by sluTTYusr** [ethereum/mist#3756]
No peers at all.
2 different systems, Windows 10 and Solus, same problem. 
Worked yesterday, nothing changed on systems and network.

```
Version: `0.9.3`
OS & Version: windows & linux
Node version: `geth 1.8.2` 
Number of blocks synchronized: 5 266 978
```

**Comment by ZeeFF** [comment]
same problem here.  Ethereum Wallet 0.9.3 . 
It was 65 blocks left with 70% yesterday now its 65 block with 36%.
Maybe you should reward ppl who keep the nodes up ffs.

**Comment by evertonfraga** [comment]
Please update to version 0.10.0 and make sure to enable `Develop > Sync with light client`. It changes lives 😉

**Comment by sluTTYusr** [comment]
@evertonfraga Why has this been closed? 
The issue is not resolved. 
It wasn't with the light node in 0.9.3 and this did not change with the default light node in 0.10
Still no peers for hours and lucky to get 1 at all... never >1
