### ISSUE TITLE
Rinkeby and Ropsten are broken on new sync

### ISSUE THREAD

**Issue by Ranguvar** [ethereum/mist#3757]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: Windows 10 v1803 b17115.1
Node version: `geth 1.8.2` 
Number of blocks synchronized: 0
```
node.log:
INFO [03-17|12:20:37] Maximum peer count                       ETH=25 LES=0 total=25
INFO [03-17|12:20:37] Starting peer-to-peer node               instance=Geth/v1.8.2-stable-b8b9f7f4/windows-amd64/go1.9.2
INFO [03-17|12:20:37] Allocated cache and file handles         database=C:\\Users\\ranguvar\\AppData\\Roaming\\Ethereum\\geth\\chaindata cache=768 handles=1024
INFO [03-17|12:20:38] Persisted trie from memory database      nodes=355 size=65.27kB time=0s gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B

Screenshot: https://imgur.com/a/HjMqx

This happens every time after selecting Rinkeby or Ropsten.

**Comment by marcgarreau** [comment]
This may fall into a category of issues resolved with the [0.11.0 release](https://github.com/ethereum/mist/releases/tag/v0.11.0). Please give that a try and open if a new issue if appropriate.
