### ISSUE TITLE
Doesn't start on Windows 8.1 x64

### ISSUE THREAD

**Issue by Undland** [ethereum/mist#376]
0.5.1 and 0.5.2 nothing happens when i click on Ethereum-Wallet.exe. Starts two "COM Surrogate" in task manager processes, but closes in two seconds. Folder AppData\Roaming\Mist is created, but empty.

**Comment by luclu** [comment]
@Undland could you please try version 0.7.2 ([link](https://github.com/ethereum/mist/releases))?

**Comment by Undland** [comment]
Same thing

**Comment by luclu** [comment]
Please remove the following folder and try again: (Backup the keystore-folder if it contains Ether)
`AppData\Roaming\Mist`
`AppData\Roaming\Ethereum`

**Comment by Undland** [comment]
same thing agane

**Comment by luclu** [comment]
@Undland this is not an issue with your provider. The problem lies somewhere with your installation or the wallet. 
Did you follow my instructions on the win 8.1 pc?
What kind of error do you see on the win 7 pc?

**Comment by Undland** [comment]
7.3 same thing!
Yes. I delete folders Mist and Ethereum.
http://img.prntscr.com/img?url=http://i.imgur.com/boLazyk.png

**Comment by Undland** [comment]
0.7.4 and no changes

**Comment by Undland** [comment]
Upgraded to WIn 10, works well

**Comment by luclu** [comment]
awesome! Might have had some problem with some low-level system files. But I don't want to poke the dead.
