### ISSUE TITLE
Not able to view balance unless on Light client (Beta). 

### ISSUE THREAD

**Issue by CaptainMorgans** [ethereum/mist#3761]
* [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.9.3`
OS & Version: windows
Node version: `geth 1.8.2`
Number of blocks synchronized: 65 blocks left 
```

[all-log.zip](https://github.com/ethereum/mist/files/1823884/all-log.zip)

See logs ZIPPED above.

Not able to view balance unless on Light client (Beta). 

I have a pending contract creation and my balances are not showing. 

At one point the wallet had completed the sync and this problem still persisted.

**Comment by CaptainMorgans** [comment]
![wallet synced](https://user-images.githubusercontent.com/3514724/37581206-27ba697c-2b50-11e8-80ca-625e1620598e.JPG)

The wallet has Synced on the main network but the balance is still 0. 

There is a pending transaction which I would like to clear, but can't do this until the wallet is working as expected. 

See below for pending transaction.

![pending transaction](https://user-images.githubusercontent.com/3514724/37581263-72ce1684-2b50-11e8-91ee-8efcaf21c017.JPG)

**Comment by CaptainMorgans** [comment]
Will this prevent me from deploying a new contract? 

And how can I "over-write" this contract deployment?

**Comment by evertonfraga** [comment]
I am closing this issue. **Please feel free** to reopen should you still have some considerations about it.
