### ISSUE TITLE
Imported wallet contract gets stuck every time in 'importing' status. 

### ISSUE THREAD

**Issue by ShineOnShineBright** [ethereum/mist#3764]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

Ok been going circles with this , hope someone can help. 

I've tried many times to bring my wallet contract back but each time it gets stuck in 'importing'. 

When I import my smart contract address I get notification that this contract is owned by my main account. But after that I'm in endless waiting room. 
I've waited some hours as I imagine it would take some time as the program goes through what is in this contract. Am I assuming this correctly ? 

I opened the U/I debugging console on the side while doing another try.  
The following log message came right as I click to 'create' -  'form submission canceled because the form is not connected'. 

I had very difficult time in the first place to make the contract. It usually ended in that similar state 'pending' - until it finally got through. 

Is my only chance to keep endlessly trying for the program to connect to it or is there some solution to this ? 

Really hope some can help. Would be truly appreciated. 

 -->

ISSUE SOLVED. 
Strangely enough after trying to get this work all day, the first try after this post and it suddenly worked... Don't know still why though it wouldn't for so many attempts...

**Comment by ChristBKK** [comment]
I have the same problem. Mh so I need to try it super often then it works? :D
