### ISSUE TITLE
Cannot Get my Ether in Ether wallet

### ISSUE THREAD

**Issue by Mutavchiev** [ethereum/mist#3765]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by philsmd** [comment]
For the default --fast sync mode you need to wait very long for the whole blocks and state tries to finish syncing.
I would suggest that you switch to the (beta) light syncing mode (use the Develop menu to select this syncing option).

**Comment by Mutavchiev** [comment]
i have still 1 000 000 blocks to wait for....

**Comment by Mutavchiev** [comment]
Done, thank you buddy
