### ISSUE TITLE
Poll: Should we implement AppImage for Linux builds?

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/mist#3767]
Users have reported numerous ([1](https://github.com/ethereum/mist/issues/3313), [2](https://github.com/ethereum/mist/issues/1418), [3](https://github.com/ethereum/mist/issues/2930))  dependency issues while using our `.deb` bundling format. 

We can get rid of the `.deb` issues altogether by migrating to a self-contained app model that does not require installation. It also works with several distros, making available to Fedorians, Arch-ians and so on.

"Download an application, make it executable, and run! No need to install. No system libraries or system preferences are altered. Can also run in a sandbox like Firejail"
https://appimage.org

Please use reactions (👍 👎), comments are allowed. 

Thank you!

**Comment by probonopd** [comment]
Should be rather easy as electron-builder can produce AppImages natively.

**Comment by evertonfraga** [comment]
Thanks for chiming in @probonopd. And congrats on the project :)

**Comment by thekevinb** [comment]
I'm OK with .appimage .  It has worked easily for the other two programs that I use that come that way.

BTW, I'm on Ubuntu.

**Comment by 3esmit** [comment]
We should verify if AppImage provide meets security requirements for blockchain applications (opensource + tamper proof).
If so I think is a great thing to be used because its a good pattern for linux distros using applications files packed together with required libraries - but this might increase the size of file (because libraries are packed with file) however reduces problem with bad dependencies (privously installed shared objects might be tampered or in wrong version?)

**Comment by ktecho** [comment]
I used the .deb. Worker perfectly for me in Ubuntu 18.04 (beta).

Disappointed to not find .deb in latest version.

**Comment by jlmargason** [comment]
Maintain the .deb and maybe add a .rpm. I don't like this idea, I don't understand why you don't have an official PPA so that this can stay up to date with the rest of my system. 

AppImage sounds bloaty, and bloaty isn't very sexy. Secure automatic updates with the native package manager would be very sexy..

**Comment by probonopd** [comment]
> AppImage sounds bloaty, and bloaty isn't very sexy. 

Are you talking about verifyable facts here or are you just guessing blindly?

**Comment by jlmargason** [comment]
I don't think I made any guesses, I just described what it sounded like. I really don't care if the package is twice as large but I want it to work with my native package manager. I don't think this is too much to ask from a serious software project.

**Comment by probonopd** [comment]
@jlmargason there are examples where the AppImage is actually _smaller_ than a normal installation. Think of AppImage like what is known as a "portable application" on Windows or an `.app` inside a `.dmg` disk image on the Mac. A package manager is not really needed for AppImages, as there is no installation and the files are "managed" by drag-and-drop. The advantage is that you can use the same file across many distribution (without having to re-download the same software for each distribution), and the application stays a separate entity from the OS (is not "baked in") and hence easy to move, remove, copy, etc.

**Comment by jlmargason** [comment]
I understand how it works, I'm a Linux Engineer. The fact that there is no installation is the issue. I want the software be installed on my system and conform to the XDG standard. 

Using AppImage is great for systems that the .deb packages won't work on, and I'm sure many other edge cases, but I don't think it should be the official delivery strategy for all Linux systems.

**Comment by nagydani** [comment]
I think that the amount of work required to maintain both .appimage and .deb is within the means of the team. The two are really for different purposes and having an installed deb package that is kept up to date with the rest of the system is an important benefit for some users and system administrators.

**Comment by jnfaerch** [comment]
My 2 cents worth: Used .deb version on Ubuntu 17.10 without problems.
There seems to be a snap version but I cannot get it to run (might be bogus: "automatic plant watering based on node, koa, and a vue client" by developer obedm503 :)
The appImage runs but I'd rather install it as .deb or (working) snap in order to get regular updates automagically.

**Comment by jnfaerch** [comment]
@alexstaj Just uninstall the deb version (or don't!), download the 0.10 and run it via the program file. (Ubuntu 17.10)

**Comment by chipkreis** [comment]
Linux Mint 18.3 64 bit, no issues with .deb.  Seems like the barrier to entry is lower with a .deb or .rpm, IMHO.

**Comment by alexstaj** [comment]
Agreed.  If it's easy please release a deb in addition to appimage or until
appimage is available.

also will the appinage be able to use my exsting chain downloaded with the
deb and just continue where it left off?

**Comment by chipkreis** [comment]
@alexstaj it looks like that is all in the .ethereum directory within your home directory.

**Comment by ktecho** [comment]
I think if you want for people to start thinking in the appimage, just release that appimage package.

If not, you should have released the .deb

**Comment by GJames1977** [comment]
I just wanted to say as a Ubuntu 16.04 LTS Linux user I definately prefer a managed software installation (via a package manager) which is also easily updateable rather than just a standalone executable binary.

I think it would be good if a .deb package was still released until an alternative installation package has been decided/implemented for platforms that curently have no issue/s with .deb. Maybe for now it just needs to be clear which platforms have known problems with .deb releases?

Any chance a .deb package can be released for version 0.10.0?

**Comment by probonopd** [comment]
It's not either-or. AppImage and deb are addressing very different use cases.

**Comment by evertonfraga** [comment]
Alright, I'm closing the poll. That was a fruitful discussion.

We'll do our best to provide a `.deb` for 0.10.0 soon, probably tagged as 0.10.1 due to semantic versioning best practices.

We're still interested in provide a portable and more universal linux installation, so that may come after the .deb is resolved.

**Comment by GJames1977** [comment]
@probonopd assuming your last comment is addressed to me, yes understood, as I say I just prefer some form of software 'package' than just a standalone executable binary.

@evertonfraga thanks for the reply around trying to provide a .deb release for 0.10.0

**Comment by dllud** [comment]
Any ETA for the .deb files corresponding to the 0.10.0 release? I would like to update my system, but I definitely prefer to wait for those .deb to keep it all nice and tidy.

A Ubuntu PPA (and a Debian repo) would be much handy. As @jlmargason points out, using your distro's package manager is the best way to keep your system secure and up-to-date.

Native package support for other distros, such as Fedora and Arch, can probably be achieved with your current build system or using something like [SUSE's Open Build Service](http://openbuildservice.org/).
Your end goal though, should be to find a packager/maintainer for each major distro and have your package added into their main repos. It shouldn't be that hard. Do notice that you already have packagers on [Arch AUR](https://aur.archlinux.org/packages/?O=0&SeB=nd&K=ethereum+wallet&outdated=&SB=n&SO=a&PP=50&do_Search=Go) and [openSUSE Build Service](https://build.opensuse.org/search?utf8=%E2%9C%93&search_text=mist&commit=Submit+Query&issue_tracker=bnc&issue=&project=1&package=1&name=1&attrib_type_id=) (nothing yet on Fedora's Copr though).

**Comment by rushsteve1** [comment]
A bit late to the discussion but I maintain an unofficial Flatpak version of Mist for Flathub.
https://github.com/flathub/org.ethereum.Mist

**Comment by inn0vative1** [comment]
Why get rid of the .deb file before you have a replacement in place? To remove the .deb option while you're still thinking about what to do next? That was a mistake as that left many people stranded. Any ETA on that 0.10.1?

**Comment by kylegordon** [comment]
Pretty annoyed that the .deb was removed without having a valid replacement available.

The packaging issues that have been linked at the start are architecture related issues. Such as in https://github.com/ethereum/mist/issues/3313 the user is checking libappindicator1 and being told that the x64 (default) version is installed, ignoring the need for the i386 version, and then trying to install Mist:i386

The use of a PPA or correctly configured repository should resolve these issues.

Nonetheless, if AppImage supports wins this poll, I would strongly suggest ensuring reproducible builds are available.

ie, https://wiki.debian.org/ReproducibleBuilds/About

**Comment by Tas-sos** [comment]
Create .deb package and nothing else! Also add it to the official repositories ( Debian & ubuntu ).
And of course continue to give zip or tarball archives for all GNU/Linux distributions.
If you have problems, check out the community for help. :smile:

**Comment by MattTwinkleToes** [comment]
now that the .deb has vanished and that there is no appimage, how are linux users supposed to upgrade their broken old versions and get access to their eth?

**Comment by evertonfraga** [comment]
I had some personal issues to take care of and was out for a while – I apologize.
We've restored `.deb` distribution format for version 0.11.0. We couldn't ship it before, as there were some major changes in the pipeline, which I recommend you to take a look :)

Let me know of anything linux related.

**Comment by kylegordon** [comment]
@evertonfraga no need to apologize. Personal and family should always come first :-)

Thank you for reinstating .deb support. One successful upgrade on Ubuntu 18.04 here :+1:

**Comment by jnfaerch** [comment]
@evertonfraga Thanks. Installed and running smoothly on Ubuntu 18.04 +1
