### ISSUE TITLE
retryConnection does absolutely nothing

### ISSUE THREAD

**Issue by philsmd** [ethereum/mist#3779]
I'm pretty sure that hitting the retry connection button from the splash screen does nothing at all.
The problem is that there is no receiver for that retryConnection "signal".

There is only the send ('retryConnection', ...) left in code, see:
https://github.com/ethereum/mist/blob/f94d8f19166a81ee71d51788052b16d845374dd6/interface/client/templates/popupWindows/splashScreen.js#L298

the code does not have any listener like this anymore:
```
ipcMain.on('retryConnection', () => {
  kickStart();
});
```

the on('retryConnection', ...) is now missing completely within the code

This problem was introduced already by this commit: https://github.com/ethereum/mist/pull/3370/

**Comment by marcgarreau** [comment]
Sure enough; looks like it didn't survive a merge or reshuffling. Will stuff it back in. If 'layered nodes' is included in the next release, the splashScreen will have been ripped out entirely, but if we patch before that release, it'll be accounted for. Thanks for catching it.

**Comment by marcgarreau** [comment]
this'll end up being a `wontfix` given that we're doing QA for the next release which won't include the splash screen. thank you for the report nonetheless!
