### ISSUE TITLE
Mist closes after creating a new account

### ISSUE THREAD

**Issue by mpolavieja** [ethereum/mist#378]
I am using Mist version 0.5.2 on Windows 7 Home Premium (64 bits)

Mist closes without warning when creating an account.  Is this normal?  I open Mist after that and the new account is there.

I created another new account and the same thing happened

**Comment by luclu** [comment]
@mpolavieja does this behaviour still occurs on version 0.7.2?

**Comment by luclu** [comment]
I will close this for inactivity. Please update to 0.7.4 and retry. Feel free to come back and discuss!
