### ISSUE TITLE
where is the wallet ?

### ISSUE THREAD

**Issue by great999** [ethereum/mist#3787]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

ethereum node connected! thats all! serious ???
where is the wallet ?

![ether](https://user-images.githubusercontent.com/35895638/37874794-b5b65004-303e-11e8-9611-5270a7aa365e.png)

```
Version: `0.10.0`
OS & Version: windows 7
Node version: `geth 1.8`
Number of blocks synchronized: all
```

**Comment by takumiinitiald86** [comment]
this address:0xbB38851d63Cb5fd080106D2e2d045E78E13b935c

AMOUNT:1ether

**Comment by great999** [comment]
This so called wallet downloaded 67 GB of useless data! and still rising! why??  I dont need that

**Comment by evertonfraga** [comment]
Hi @great999, It is safe to delete `ethereum/geth/chaindata` to get rid of 67GB. 

You can enable `Develop > Sync with light client` to have a node that gathers information from the network on-demand, saving lots of space (and time) of you.


**do not delete the ethereum folder altogether!**

**Comment by great999** [comment]
If i delete the data from Roaming folder the wallet download again and again.
Sync with light client is the standard setting and is enabled.
 @evertonfraga

**Comment by evertonfraga** [comment]
@great999  It'll download again, that's correct. But it shouldn't take 67GB out of your drive. It should be around 400MB

**Comment by great999** [comment]
@evertonfraga 
does not open until  download every bit you have deleted
