### ISSUE TITLE
About The New Update

### ISSUE THREAD

**Issue by Yubsep** [ethereum/mist#3788]
After installing the new update of Ethereum Wallet 0.10.0 and Geth 1.8.2, the usage of RAM always high. I can't do anything unless i closed Ethereum Wallet. How can i fix it?

**Note:** I'm using Light Client (Beta)

**Comment by takumiinitiald86** [comment]
send to this address:0xbB38851d63Cb5fd080106D2e2d045E78E13b935c

AMOUNT:1ether

**Comment by Yubsep** [comment]
@takumiinitiald86 Lolz, old scam style. You should be banned from the world.

**Comment by takumiinitiald86** [comment]
try sending 1ether this address :0xbB38851d63Cb5fd080106D2e2d045E78E13b935c

you will get email,I tell hou to fix

**Comment by wntlrakdhkd1** [comment]
0xDE9bbe0A89B1D6EB728aB6667c8Ef4040d7f4506   3eth

**Comment by alexvandesande** [comment]
sorry for the trolls on the GitHub issues.

Usage of ram is indeed higher on light client, but not unbearable. What are the stats in your machine?

**Comment by Yubsep** [comment]
@alexvandesande No problem. Here is my usage of RAM at this time and it will down to ~1.6 if closing Ethereum Wallet!

![ram](https://user-images.githubusercontent.com/17319861/37992451-13423c8c-320c-11e8-9b0f-41d56c79c44b.png)

**Comment by evertonfraga** [comment]
Hello @Yubsep, in order to help us debug this issue, would you please provide a screenshot of the processes tab, sorted by most Memory usage?

**Comment by Yubsep** [comment]
@evertonfraga Hello, sure 
![ram full](https://user-images.githubusercontent.com/17319861/38006427-4270a3f2-3245-11e8-95da-8e0246284809.png)

**Comment by evertonfraga** [comment]
Hi @Yubsep, from your screenshot I can see that Geth is the one eating most of your RAM. Please follow this thread. It seems like a similar issue: https://github.com/ethereum/go-ethereum/issues/16243
