### ISSUE TITLE
Problem with a contract

### ISSUE THREAD

**Issue by Mutavchiev** [ethereum/mist#3789]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

I have made a contract 4 days ago. When i check in etherscan its complete, but in my wallet stays as still creating! Can someone helps me?

 -->

**Comment by takumiinitiald86** [comment]
do you try sending to that address

**Comment by alexvandesande** [comment]
If it's on etherscan then you indeed created it, it's just a matter of synchronization.

 If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com)

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
