### ISSUE TITLE
Issue with the App Ethereum Wallet

### ISSUE THREAD

**Issue by nadaf23** [ethereum/mist#3791]
Hi, Team

Actually i have a problem with the application "Ethereum Wallet" I have try installing old versions and new versions.

ERROR: RETRY CONNECTION
![rrrrrrrrrrrrrrrrrrrrtthher](https://user-images.githubusercontent.com/37818186/37938656-fb9f09f0-312c-11e8-9e43-16c5d0e5dccb.jpg)

**Comment by evertonfraga** [comment]
Hi @nadaf23, please take a look at this guide: 
https://github.com/ethereum/mist/wiki#unable-to-find-peers

**Comment by nadaf23** [comment]
Hi, Evertonfraga. 

Do i can use the tokens created?

How i can do?

Do u can help me?

Thanks.

![tokens](https://user-images.githubusercontent.com/37818186/38168440-d015546a-3519-11e8-996f-8f7b17771f3d.jpg)

**Comment by nadaf23** [comment]
Good Evening.

Team Github. I have the same problem with the RETRY CONNECTION. Please, i need support for solve my problem. 

PD: I can work with the created tokens?

**Comment by alexvandesande** [comment]
Seems like an error with the light client finding peers. I hope it has been solved.
