### ISSUE TITLE
ETH transfer

### ISSUE THREAD

**Issue by Jeetsingh1944** [ethereum/mist#3797]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
[all.log.zip](https://github.com/ethereum/mist/files/1850792/all.log.zip)
![screen shot mist](https://user-images.githubusercontent.com/34196471/37952174-751c35e4-318e-11e8-9ac3-c91eda672ae9.png)
![screent shot main screen](https://user-images.githubusercontent.com/34196471/37952175-755efed8-318e-11e8-9dee-1a125bb41f3d.png)

```
Version: `1.1.0`
OS & Version: windows
Node version: `geth 1.8.2`
Number of blocks synchronized: 
```

**Comment by Jeetsingh1944** [comment]
I am unable to see ether i transferred in this account from bitstamp.net. Please check and get back to me. Thanks

**Comment by philsmd** [comment]
It doesn't seem that you finished syncing. that is why you do not see the transaction yet.

If the syncing doesn't finsh and/or you are in a hurry, you can change to the light mode using the "Develop" menu option.

**Comment by marcgarreau** [comment]
Yep, @Jeetsingh1944, exactly what @philsmd said; your node must be fully synced to see your proper balance and make transactions. I'm closing this issue, but please reopen if you still have trouble after you fully sync your node. Using the "Light" mode (within the "Develop" menu) is indeed the quickest way to get there.

**Comment by Jeetsingh1944** [comment]
HI,

I am unable to sync it fully since then. Every time i get close to complete
to sync, it stops sync. I still cannot see ETH in my account. I am bit
worried and dont n0w what to do. Please help me on urgent bases. Thanks

Kind regards


*Navdeep Sachdeva*

**Comment by marcgarreau** [comment]
First, if you want to verify your funds are in your account, try looking up your wallet address on etherscan.io. All transactions to/from the account will be visible there.

As for syncing, have you tried with "Light" mode? The option is found in the "Develop" menu. Latest release of Mist/Ethereum Wallet uses this setting by default. While syncing "fast" mode, geth must download a large amount of state data (different than block header data) right before you finish syncing.
