### ISSUE TITLE
Avast Blocking eth.exe

### ISSUE THREAD

**Issue by jsgalt** [ethereum/mist#380]
I could not get a screen shot of it, but basically it blocked eth.exe and WinRAR.exe which was odd. when I run Eth, it says :

¬\AppData\Roaming\Ethereum\chaindataFatal: blockchain db err: Access is denied.

**Comment by jsgalt** [comment]
Actually still getting this right after I disabled Avast, Maybe its something else? Running win7 

![screenshot 1458178042](https://cloud.githubusercontent.com/assets/9690531/13833630/35f1a5e4-ebad-11e5-8ccf-5833ea664499.jpg)

**Comment by obscuren** [comment]
Is your machine in a corporate network?

**Comment by jsgalt** [comment]
No, its my home computer. though im using Google's DNS instead of my ISP's

**Comment by Undland** [comment]
same error

**Comment by More-decentral** [comment]
My antivirus software Avast has false positive reports. It moved a couple of blockchain files (xxxxxx.ldb) under ~/Library/Ethereum/Chaindata/ to an isolated area (virus chest). Even after I made the software to restore those files, my Ethereum Wallet still cannot run properly. Any advices on how to fix it? Thanks.

**Comment by luclu** [comment]
@More-decentral you might need to add an exception the the chaindata-folder in your AV. Please have a look at the "Antivirus false positive reports".

**Comment by alexvandesande** [comment]
Thanks for reporting. We're merging these issues into #573
