### ISSUE TITLE
 uninstall mist/geth on my mac ?

### ISSUE THREAD

**Issue by keithofaptos** [ethereum/mist#3801]
How do i completely uninstall mist/geth on my mac ? i am interested in running this program later,but am not ready for it yet! Also i can't figure out how to stop it, and my laptop has went from a jack rabbit to a turtle! I looked on github, youtube, google and found nothing that works.it's not on port 30303 ...

**Comment by keithofaptos** [comment]
*Still NEED HELP*
Does Mist use a particular  port number ,or PID ? If I knew what that is I could pause it 
in terminal , hopefully until I figure out how to run Mist/geth ...

I'm on a Macbook Pro ,High Sierra,Ver.10.13.3
downloaded : Ethereum-Wallet-macosx-0-10-0.dmg 

Have spent the last 9 hrs learning a lot about terminal command (bash).
Which is useful.
And am quite ready to figure this out ... ASAP PLS THX.
This has been quite frustrating I'll add.

MAYBE it would be a good idea to put a little something in the Wiki regarding this. (!)
-and if I missed it in the Wiki , send me the URL link pls.
-or a kill switch on the Mist screen?

This is all I was able to find in wiki : (FOR ME IS NOT ENOUGH)
Mac:
Open Terminal app and run:
lsof -i tcp:30303
lsof -i udp:30303
Identify the PID (process ID) that's making the port 30303 busy and kill the process:
kill <NUMBER FOUND IN PREVIOUS COMMAND>. eg: kill 2121
Linux:
Open your preferred console and run
netstat -vanp tcp | grep 30303
Identify the PID related to the port number and kill the process:
kill <NUMBER FOUND IN PREVIOUS COMMAND>

**Comment by 7Ds7** [comment]
To uninstall Mist is just like any other app just delete Mist.app  it should get rid of Mist and it's own instance of geth.

If you have any other instance of geth installed, maybe with homebrew, try `brew uninstall`.
You can also do `which geth` on the command line to see where geth resides

Furthermore the folder `~/Library/Ethereum` contains the chain data as well as your wallets keys, so if you have some make sure you save them before removing this folder.

The reason for your Mac sluggish behaviour have more probabilities to do with the OSx upgrade for High Sierra than mist.

**Comment by BenStolman** [comment]
Brew uninstall geth worked for me

**Comment by ryanio** [comment]
Please let us know if you still have any issues related to this.
