### ISSUE TITLE
No ETH in Ethereum Wallet after 4 hours

### ISSUE THREAD

**Issue by MoldovanFlorinela** [ethereum/mist#3805]
![screenshot_1](https://user-images.githubusercontent.com/37934859/38141827-ab9bb61a-3442-11e8-98af-cd273a13237a.png)
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```Windows 7 Home Premium 32 - Bit Operating System
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

Does not open the wallet !!?? What is the issue and what should i do ??? Thank you !

**Comment by MoldovanFlorinela** [comment]
I've just made this wallet ,downloaded and installed .Because i bought some ethereum and wanted to store him in this wallet .I opened the interface once ,closed and after when i wanted to open again the wallet i got this on my desktop screen and doesn't show me my account .

**Comment by MoldovanFlorinela** [comment]
If i reinstalling the wallet app i lose my wallet adress ?

**Comment by MoldovanFlorinela** [comment]
I've succesfully opened my wallet but i am waiting since 3 hours ago to receive my ETH ! How long do i still have to wait ?

**Comment by evertonfraga** [comment]
Hi @MoldovanFlorinela, 

please provide more information about your wallet installation:

1. Wallet version (File > About Ethereum Wallet)
1. Make sure `Develop > Sync with light client` menu is enabled.

> If i reinstalling the wallet app i lose my wallet address?
No, you don't lose it, although we strongly recommend backing up your accounts, to protect yourself from many kinds of threats: computer breaks, etc etc.

**Comment by MoldovanFlorinela** [comment]
Hi ! Ethereum wallet 0-10-0 ,windows 7 serv pack 1 32 bits ! it aloweded me to launch the aplication after a while and ive purchased ETH from wallet " BUY ETHER " through Changelly ,Simplex the payment was succefully approved but my wallet ballance after 4 hours is still 0.00 ?! Sinc with light client is enabled . What should i do to receive my ETH or how much it takes until i'll receive my coins ?  Simplex wrote to me that they've sent my coins ! Thank you very much !

**Comment by MoldovanFlorinela** [comment]
![screenshot_2](https://user-images.githubusercontent.com/37934859/38148539-90e86d00-345f-11e8-872e-1aa3871da76e.png)
![screenshot_3](https://user-images.githubusercontent.com/37934859/38148545-95522764-345f-11e8-84de-37052b413d6b.png)

**Comment by MoldovanFlorinela** [comment]
Done +1: ive just received my ETH , thank you very much for ur time and help :)..

**Comment by evertonfraga** [comment]
Yay, great!

**Comment by MoldovanFlorinela** [comment]
Thank you very much :)..

**Comment by je112413** [comment]
pls
