### ISSUE TITLE
No ETH in Ethereum Wallet after 4 hours ? 

### ISSUE THREAD

**Issue by MoldovanFlorinela** [ethereum/mist#3806]
* [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

Ive created this wallet today , and i've bought some ETH trough " buy ether " from wallet via Simplex .They payment was approved 4 hours ago but i am still waiting to receive it to my wallet ! How much time do i have to wait for my ETH ? Thank you !

**Comment by MoldovanFlorinela** [comment]
Done , ive just received my ETH ...

**Comment by evertonfraga** [comment]
Closing in favor of #3805
