### ISSUE TITLE
--rpcpath ignored by Mist when connecting to private network

### ISSUE THREAD

**Issue by jctaillandier** [ethereum/mist#3809]
Version: `0.0.0`
OS & Version: linux Ubuntu bash on Windows 10
Node version: `geth 1.8.1`
Number of blocks synchronized: 500 something (private network)

I know this issue is recurrent but I couldn't find answers from previous ones.

I have a geth node running my private network in the background. On another window I run:
`./Mist.exe  --rpcpath /Path/to/endpoint.ipc (which I took from my node running in background)`

But then while launching, Mist keeps trying to connect to:
`{"path":"\\\\.\\pipe\\geth.ipc"}`
Then obviously:
```
[2018-03-31T10:07:44.558] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-31T10:07:45.559] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2018-03-31T10:07:46.560] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
```
And it keeps re trying until I get that message saying Mist couldn't connect to node.

**Comment by PhilippLgh** [comment]
Please see https://github.com/ethereum/mist-shell/issues/7 for progress on this issue
