### ISSUE TITLE
blockchain db err: Access is denied.

### ISSUE THREAD

**Issue by jsgalt** [ethereum/mist#381]
![screenshot 1458178042](https://cloud.githubusercontent.com/assets/9690531/13833989/e93c7b4e-ebb0-11e5-8052-81936579e355.jpg)

**Comment by rfikki** [comment]
win32 is currently not supported. But, from the message it seems that you do not have an etherbase set and no accounts found for your node.

**Comment by jsgalt** [comment]
Oh I thought I was on 64

So you are saying that if I have an etherbase then the node might work? seems odd given that I could not even get the wallet open to create the accounts. Maybe its the processor system thing.

**Comment by jsgalt** [comment]
My computer thinks it is 64 bit 
![screenshot 1458245359](https://cloud.githubusercontent.com/assets/9690531/13859618/e8ddcace-ec49-11e5-96ac-23812fe60878.jpg)

**Comment by bas-vk** [comment]
I don't believe the error has anything to do with having an etherbase or not.

The last message is more interesting. It seems that geth is not able to access the directory where it stores its data (`~\AppData\Roaming\Ethereum`). Could you verify that this directory exists and has a subdirectory `chaindata`? Also make sure that you can write to that directory.

Geth will store its data in this directory. This cannot be shared by multiple geth clients running at the same time. Do you already have a geth instance running?

**Comment by jsgalt** [comment]
I see no geth instances running. I also see no Ethereum folder in Roaming.

**Comment by jsgalt** [comment]
Ah fixed it by  making appdata and roaming not hidden. Not sure if that's safe or not, I think I messed with the default settings at some point.

**Comment by cytos** [comment]
Does someone have a solution for my problem? #524 :/ I have win 64 it says 32 etc

**Comment by bas-vk** [comment]
@cytos, your issue doesn't seem to be related to this issue and since the problem has been solved I will close this one.
