### ISSUE TITLE
Deployed contracts and custom tokens disappeared after update from 0.9.3 to 0.10.0

### ISSUE THREAD

**Issue by Boterick** [ethereum/mist#3811]
* [x] I would have asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue, but the gitter forum locks me out, reporting "Only GitHub users can join this room"... yet I am a GitHub user... as is evident here.

```
Version: `0.10.0`
OS & Version: windows
Node version: `geth 1.7.3`
Number of blocks synchronized: 1
```

<!--

All of my wallet contracts, deployed contracts, and custom tokens associated with my ongoing token sale have disappeared since upgrading from Mist 0.9.3 to 0.10.0

I still have use of 0.9.3, as I was using this from an uninstalled folder. However the installation of 0.10.0 has caused all to disappear from 0.9.3 version also.

Main wallet shows Ether balance as before, but with no token balance, and with no ability to send tokens, which I had before.

I have tried manually adding custom token contract from information on Etherscan, but it does not pick up token balances.

I urgently need to reinstate all.

Update: I used a Windows System restore point from a few days prior to the Mist update, to attempt to undo the Mist update. The Mist application has gone back to 0.9.3 now as intended, but my contracts still do not appear.

**Comment by themaxX4** [comment]
I can just talk for the v0.10.0, the wallet does not want to synchronize (always stuck to 65 blocks left) and I can't manage my tokens.

**Comment by ryanio** [comment]
Hey, unfortunately this will happen again in `0.11.0` since we moved from using wallet.ethereum.org to a local version for security, but we have new syncing features that should fix your problems once you add your tickets and contracts again. Please give it a try! If you have any new problems that you can reproduce, please create a new issue with the details on how we can help. Thanks!
