### ISSUE TITLE
Sync stuck

### ISSUE THREAD

**Issue by dgrl** [ethereum/mist#3813]
Hi

Can someone explain to me why the eth wallet is not syncing at all 
Have issues with the wallet since december 
The very very first sync ( first time use ) was not an issue at all 
Afte rclosing the wallet for a day sync issues arisez

I am stuck on block 4.872.452 since the day it was generated 

HELP HELP HELP I HAVE A ** LOAD OF ETH AND CANT GET IT ANYMORE

Version i uses is new 1 
Ethereum-Wallet-win64-0-10-0 
and also Ethereum-Wallet-win64-0-9-3

**Comment by alexvandesande** [comment]
Sorry about the trouble syncing. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com)

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
