### ISSUE TITLE
ERC20 base Token 

### ISSUE THREAD

**Issue by nomantariq18** [ethereum/mist#3817]
can i send other coins which is ERC20 based, on Ethereum address ?

**Comment by marcgarreau** [comment]
Yep, you can receive and send ERC20 tokens to wallets created in Mist/Ethereum Wallet. If you have tokens in a wallet, you will see the option to send ETH or the tokens within the wallet send page. You can also accomplish the same thing in MyCrypto/MyEtherWallet/etc. Good luck!
