### ISSUE TITLE
ethereum wallet (mist) or other wallets ??

### ISSUE THREAD

**Issue by sam1138** [ethereum/mist#3818]
sorry for my ignorance but my question:

can I use mandatory ethereum wallet (mist) or I can choose from other wallets available?

in this last case I still need to sync with geth??

thanks for answer

David

```
Version: `0.10.0`
OS & Version: windows 10 64 bit
Node version: `geth 1.8.2`
Number of blocks synchronized: 5362152
```

**Comment by alexvandesande** [comment]
You can use any wallet you want. I don't know why you'd think Mist is mandatory.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com)
