### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by pro-respirator** [ethereum/mist#382]
I've just deposited some ether into the mist wallet, but upon sending them, I found that the password that I wrote down doesn't seem to be correct. I assume that I probably just wrote it wrong, but I've guessed every variant of it that I can think of so I think that's pretty much out of the question as a solution. Is there any way to manually recover the password

**Comment by alexvandesande** [comment]
[There are tools that will brute force your password](https://github.com/ryepdx/pyethrecover) if you remember anything about it, but these are technical. You can also try using the [command line](http://ethereum.org/cli) to check if your password is wrong or if it's a client issue.

Other than that, if you truly forgot, there are no recovery options.
