### ISSUE TITLE
Raspberry Pie Build

### ISSUE THREAD

**Issue by eMiner49er** [ethereum/mist#3821]
Version: 0.10.0
OS & Version: linux (Raspberry Pie)
Node version: geth 0.10.0
Number of blocks synchronized: 0

Please make a build for Raspberry Pie 

Thanks!

**Comment by ryanio** [comment]
Hello, you should be able to follow our linux instructions to get this running. Please let us know if you have any problems that you can reproduce, you can create a new issue with the details on how 
we can help. Thanks!
