### ISSUE TITLE
I have deposit ICO tokens on my eth wallet, but the nubmer of tokens is shown 0 thats HQX token, it is shown in etherscan but not in my wallet. What shell I do? Checked 100 times accuracy of contract number and other stuff, but could not fins where the problems come from. Custom token is shown but number of them is 0

### ISSUE THREAD

**Issue by dbmezzy** [ethereum/mist#3824]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx macOS Sierra 10.12.6
Node version: `0.10.0`
Number of blocks synchronized: 0
```

**Comment by ryanio** [comment]
Hey, we just released a new version (`0.11.0`) that has new syncing features - please give it a try! If you have any new problems that you can reproduce, please create a new issue with the details on how 
we can help. Thanks!
