### ISSUE TITLE
DownLoaded New Mist, Put Keystone File in folder, mist will never open

### ISSUE THREAD

**Issue by mrhoser** [ethereum/mist#383]
I Downloaded the New release, Put my Keystone file in, but the wallet never opens, take the keystone out, asked for password, will open a new wallet? Windows 7 64. Fresh Mist install. Replaced keystone file with Wallet open, But wallet then gets stuck. If I try and open Mist with the keystone file, with my funds It says, processing blocks, but wallet was synced before I put my Keystone file in. Just sits on Splash screen saying Processing blocks, please wait.

**Comment by mrhoser** [comment]
Hmm, I tied it a few more times on 0.5.1 and 0.5.2 and then it finely opened back up with 0.5.1  Is there a trick to this, I don't want to keep this on my machine.

**Comment by lookie21** [comment]
did you format your pc ?

**Comment by mrhoser** [comment]
nope

**Comment by hiddentao** [comment]
Can you open the Devtools Console when Mist is open and running and track what gets shown there? Would be good to know what (if any) Javascript errors are showing.

**Comment by frozeman** [comment]
So basically what youre saying is that it doesn't find peers and get stuck on the sync screen?
There are a few issues here with that problem. Solutions are, to stop your firewall, look at your router or start the node with `wallet/resources/node/geth/geth.exe --nat=none`.

Concerning your keystore.. where do you put it?

**Comment by mrhoser** [comment]
I tried it a few times with the same release (0.5.1) that I made the keystone file with and it finely worked with that keystone file I have saved. Working as expected now.
