### ISSUE TITLE
Ethereum Wallet will not sync

### ISSUE THREAD

**Issue by pervasivepics** [ethereum/mist#3839]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by pervasivepics** [comment]
I downloaded Ethereum Wallet over 70 days ago. Twice I sent ether to my new Ethereum address from Coinbase via GDAX. 
The Ether has never seemed to reach the address. But on Etherscan shows that the Ether has reached its address and has provided a transaction number for each time I sent Ether.
I have tried to sync the Ethereum Wallet numerous times, leaving my computer on for days at a time to no avail. I have a powerful MacBook Pro computer and reasonably strong internet connection. When its seems to load to 100% it simply starts reloading again. I have no control over my purchased Ether.
I reset my computer clock to ntp1.lsu.edu. I could not find the chaindata in my computer’s library to remove it as suggested by numerous sources. I downloaded the most recent updated version0.10.0, same thing.

**Comment by Csmatana** [comment]
I am having this issue as well on my PC Please Help!

**Comment by lorezyra** [comment]
https://github.com/ethereum/mist/issues/2466

Please define OS and version.

**Comment by pervasivepics** [comment]
OS High Sierra 10.13.4

**Comment by Csmatana** [comment]
I'm having to restart my ethereum engine to download a little at a time, any help is greatly appreciated!!

**Comment by Csmatana** [comment]
Updated get and resolved this issue.

**Comment by alexvandesande** [comment]
> The Ether has never seemed to reach the address. But on Etherscan shows that the Ether has reached its address and has provided a transaction number for each time I sent Ether.

If etherscan shows it arrived and your wallet doesn't, then it's just an issue of synchronization. If you haven’t tried syncing in Light mode, please do so by selecting the “Sync with Light client (beta)” option under the “Develop” menu tab. The feature is still in beta, but if you run into any trouble, you can usually clear it up by restarting.

If you have a time-sensitive need to move funds from your wallet, you can always access your wallet and send transactions within [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com)

We are merging all sync issues on this thread: https://github.com/ethereum/mist/issues/3097
