### ISSUE TITLE
Account address capitalization while doing initial blockchain sync

### ISSUE THREAD

**Issue by MidnightLightning** [ethereum/mist#384]
After first installing the Ethereum wallet, while syncing the blockchain, I noticed in the splash screen the capitalization of the just-generated etherbase address is mixed-case:

```
0x251E01cf6A27D0e5b80eD8ce2D59965A19366f15 ← Displayed
0x251e01cf6a27d0e5b80ed8ce2d59965a19366f15 ← Lower-cased
```

The mixed-case version isn't accepted as a valid address in a few block explorer sites, so led to some confusion as I tried to look up my new address.

**Comment by alexvandesande** [comment]
This is intended, the capitalization is used as checksums. Ether explorers should either be case insensitive or implement the checksum capitalization.

**Comment by MidnightLightning** [comment]
Ah, did not know that was a checksum; good to know. [Coinotron](https://coinotron.com) was not accepting my address in mixed-case as a payout address, and [EtherChain](https://www.etherchain.org) I thought wasn't accepting it but now is (maybe because it now has Ether in it?).
