### ISSUE TITLE
mist 0.10.0 Synced but no History/ Balance.

### ISSUE THREAD

**Issue by Nielszzz** [ethereum/mist#3840]
<img width="1382" alt="screen shot 2018-04-17 at 10 49 20" src="https://user-images.githubusercontent.com/38435206/38858894-2ab27888-422d-11e8-9e01-8519604df1c5.png">
<img width="512" alt="screen shot 2018-04-17 at 10 51 05" src="https://user-images.githubusercontent.com/38435206/38858943-46f35cc4-422d-11e8-8208-112ef48316e5.png">

Hi, maybe someone can help me please,

Macbook- Mist wallet- 0.10.0 - GPL3.0 and have this problem for 2 months now.

On my previous wallet-version could sent (sent button didn't work) tokens from my wallet to exchange. Thought that the previous version was out of date. 
Installed latest 0.10.0 (beta) version but balance and history wasn't/isn't showing up. Reset chain data multiple times, tried every command I've seen but again no. Let it run for days after syncing, but again no succes. Just want to sent my tokens from mist wallet to exchange to sell. 
Hope someone has good advice .. ?

Thx in advance ! Niels

* [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by ryanio** [comment]
Hey, we just released a new version (`0.11.0`) that has new syncing features - please give it a try! If you have any new problems that you can reproduce, please create a new issue with the details on how 
we can help. Thanks!
