### ISSUE TITLE
Please Help me with the contract in App Ethereum Wallet

### ISSUE THREAD

**Issue by nadaf23** [ethereum/mist#3841]
Hi, Team Github

I have a little issue with the contract in the App Ethereum Wallet. The contract say "Creating" since a month ago. Why?

The contract is so slow... 

Thanks for yours answers.

**Comment by marcgarreau** [comment]
Is your node fully synced? If not, that could be the issue. Otherwise, are you seeing any error output in the console? You can view the console by selecting `Develop` in the menu bar, then `Toggle Developer Tools`. If you have any error output there, please share that.

**Comment by marcgarreau** [comment]
Cleaning up stale issues. Please reopen/open a new ticket if appropriate.
