### ISSUE TITLE
Wallet contracts detect transactions for other wallets

### ISSUE THREAD

**Issue by ethernomad** [ethereum/mist#385]
Mist says that the following 2 transactions were received by my contract wallet, but these transactions send ether to addresses that are not mine.

http://etherscan.io/tx/0x893144b7ee95c6d1f997901f1935307633a8664478544df4d73fe87c790048e0
http://etherscan.io/tx/0x9bba5e0552b04b0a98dbe0cac4744452ff82046adfce24df065c33f8d583b510

**Comment by drupalnomad** [comment]
Still happening: https://ipfs.pics/QmRh51gUd7ZFnS5WzCJxNU7brmrzhS7kbs1uSBzAQfoNFc

**Comment by luclu** [comment]
@frozeman any clue on this one?

**Comment by evertonfraga** [comment]
Issue closed due to inactivity. Please reopen if problem persists.
