### ISSUE TITLE
Lost Private Key

### ISSUE THREAD

**Issue by Jeetsingh1944** [ethereum/mist#3850]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.1.0`
OS & Version: windows
Node version: `geth 1.8.2`
Number of blocks synchronized: 5510647
```
Hi,

I have lost private key of my wallet. I uninstalled my wallet and reinstalled to open new account so i can get new private key. When i reinstalled wallet again it still open my old account. Please guide me that how i can get assess to new wallet with new private key so can be secure.
Thanks

You'll find possible solutions for these common issues below on Mist Wiki: https://github.com/ethereum/mist/wiki.

[all.log (3).zip](https://github.com/ethereum/mist/files/1952625/all.log.3.zip)
![screen shot 2604](https://user-images.githubusercontent.com/34196471/39326617-1ccbc378-4985-11e8-9c1d-e7006495bcb5.png)

When creating this issue, if possible add the following to your report:
- Screenshots
- Check the console, of Mist (`CTRL/CMD + ALT + i`) and take a screenshot
- Log files
  - Go to the menu `Develop -> Show log files`
  - Zip and upload `all.log` and any other appropriate `category/*.log` files

 -->

**Comment by marcgarreau** [comment]
Generating a new keystore file requires you to have your password. If you do have the password, you can use something like the MyCrypto app to generate a new keystore file with a different password. This requires you to unlock the wallet with the original password though.
