### ISSUE TITLE
why mist need connect to www.wallet.ethreum.org in private network

### ISSUE THREAD

**Issue by zhuimengshaonian66** [ethereum/mist#3856]
it is not a issues,but i want to know some detials about the  www.wallet.ethreum.org, i connect private network by geth,why mist  need connect to www.wallet.ethreum.org in private network,  www.wallet.ethreum.org is a node ?or something?

**Comment by iquidus** [comment]
wallet.ethereum.org hosts the wallet dapp interface used by Mist (https://github.com/ethereum/meteor-dapp-wallet), if you prefer this connection is not made, you can use the Ethereum Wallet binaries instead, which contain a built in, stand-alone version of the wallet dapp.

**Comment by zhuimengshaonian66** [comment]
@iquidus  you are master
