### ISSUE TITLE
Efficient search for accounts

### ISSUE THREAD

**Issue by tamama** [ethereum/mist#3858]
Hi Mist community,

Assuming I have an organization of 100 members, each with his account. 
1) Is there an easy way to search for the account by name? (There is no such search box in the wallet so far.)
2) Also, can we have a button to sort out these accounts by their name?

Kind regards,
Tamama

![image](https://user-images.githubusercontent.com/17287685/39478446-1039d834-4d95-11e8-9ceb-8f3c5a454c20.png)

**Comment by marcgarreau** [comment]
Apologies for not responding sooner. I believe this use case in the wallet is very atypical today. That said, they are reasonable feature requests and I've added them to the wallet repo issues. Thanks for the idea!

**Comment by stvenyin** [comment]
See.
