### ISSUE TITLE
Mist doesn't attach to already running geth instance

### ISSUE THREAD

**Issue by andreafspeziale** [ethereum/mist#3859]
* [ x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

# Mist doesn't attach to already running geth instance

```
Version: `0.10.0`
OS & Version: osx
Node version: `geth 1.8.3-stable`
Number of blocks synchronized: 0
```
I usually run my geth node manually with preferred parameters.
I usually launch mist and it detects that a node is already running and attaches to it.

Now it seems it is not working anymore.

To reproduce it try simply:
- `$ geth --testnet --syncome 'fast'`
- Launch Mist from the finder

This error will be show:
[all.log](https://github.com/ethereum/mist/files/1964662/all.log)
<img width="591" alt="screen shot 2018-05-01 at 19 42 18" src="https://user-images.githubusercontent.com/7680940/39485240-7312926a-4d78-11e8-9b4b-20fe0b0b9dec.png">

Useful information are in the logs. It automatically try to access to an ipc path, but that pat is the one opened when the main network is targeted.

Thanks.

**Comment by PhilippLgh** [comment]
Please see https://github.com/ethereum/mist-shell/issues/7 for progress on this issue

**Comment by PhilippLgh** [comment]
Please see ethereum/mist-shell#7 for progress on this issue
