### ISSUE TITLE
Ethereum node needs to sync

### ISSUE THREAD

**Issue by rorman13** [ethereum/mist#386]
How long should this take before I should be worried?  I have used the wallet before but it seems to be hung on downloading since I opened it today.

Thank you

**Comment by alexvandesande** [comment]
24 hours is too long a time. Have you tried restarting it?

**Comment by rorman13** [comment]
Hello,
Thank you for the reply.  I did try restarting it two different times.  I am going to try and download the wallet on a second computer and see if it works better there.  I am considering deleting and reloading the wallet program.  Just to make absolutely sure, since there is a password and such, that would not kill the ether I had in there correct?

**Comment by zacharytamas** [comment]
I'm also having this problem. It hangs at the "Looking for peers..." step.

**Comment by swt83** [comment]
Same as issues #362 #310 #292

**Comment by hiddentao** [comment]
I get this sometimes too. And sometimes when I choose to "skip peer search" the app crashes. I'm on OS X using 0.5.2.

**Comment by zacharytamas** [comment]
I found that after I restarted my computer and then started the Wallet again it worked. :+1:

**Comment by swt83** [comment]
I can confirm that simply rebooting your computer solves this problem.

**Comment by rorman13** [comment]
I have rebooted a few times now and it is still not moving past the block from a week ago.

**Comment by popiahalex** [comment]
i had the same problem with el capitan... i delate ethereum and restore it.. wait for the download again -_-

**Comment by rorman13** [comment]
Should I try and send the ether out of the account before deleting the program.  I did try that once but the transaction is not on the blockchain.

**Comment by rorman13** [comment]
![capture_ethhung](https://cloud.githubusercontent.com/assets/17221202/14064206/5c021bfc-f3ae-11e5-9cc7-985300f3e1ca.PNG)

**Comment by rorman13** [comment]
I am not sure if I deleted all the programs but I deleted everything I could find and downloaded a new copy and clicked the application and it started up and got hung on the same block but it did not start downloading from the first block.  So it was as if some part of it was still there.  At this point I would be happy to know how to just move the Ether I have in the wallet out of there.  Does anyone know how to do that because that does not work anymore either.

**Comment by richardsj** [comment]
Bump.  "Delete everything I could find" is not a bug fix, especially in a tool that is used to handle money, wallets and valuable tokens

**Comment by rorman13** [comment]
I agree richardsj but, I was able to get my money out and now I only use a small amount of ether on the wallet.  I am going to wait awhile before more of the bugs get worked out.  I hear Coinbase is going to handle ether so I might see if they have a storage function because I have never had any issues with my BTC on there.

**Comment by lucas-wade** [comment]
Mine hangs overytime on Etherium node needs to sync. Just sits there always. Os X el Capitan.

**Comment by AMTQ** [comment]
same problem, why is this closed?
