### ISSUE TITLE
Can't find the launch node button. Please support!!

### ISSUE THREAD

**Issue by Chagz19** [ethereum/mist#3866]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by marcgarreau** [comment]
Cleaning up stale issues; Mist now supports local and remote nodes (via infura). Please reopen/open a new ticket if appropriate.
