### ISSUE TITLE
Sync always few blocks behind

### ISSUE THREAD

**Issue by fatihergan** [ethereum/mist#3869]
It's been 4 days since I started the sync. 

Sync always fall behind like 64 or 65 blocks. 

I tried both Ethereum Wallet and Mist apps. Both are the same.
I start geth.exe (which comes with the Ethereum Wallet install) with --fast --cache=2048 commands.

About 6 months ago, I've tried running geth and mist on my pc but had sync problems and I removed everything. Now I'm trying with another pc but still having the same sync problems.
Seem like you had no any improvements or whatsoever in those 6 months even though you published new versions. 
As I see I'm not the only one having these problems and It has been going on for very long time. 
Your code is s... and you know it!

```
Version: `0.10.0`
OS & Version: Windows 10
Node version: `geth 1.8.2`
Connection: 50 mbit fiber internet
Storage: 500mb/s  SSD
Firewall-Antivirus: None
```

![screenshot_2](https://user-images.githubusercontent.com/8463912/39646930-c179e5f6-4fe5-11e8-915e-68916638ead1.png)

**Comment by marcgarreau** [comment]
First recommendation: try syncing with Light mode. The option is available within the 'Develop' menu. Ultimately, the issue of syncing lies with [geth](https://github.com/ethereum/go-ethereum/). If you're still unable to sync, you can look through issues in that repo or create a new one. Closing as there's little the Mist team can do here until the next release that includes remote node integration. Good luck.
