### ISSUE TITLE
contract wallet : can't send to main wallet why??

### ISSUE THREAD

**Issue by AMONRA75** [ethereum/mist#387]
hi, 

i have a contract wallet with 12 eth but this account is watch only.
i'ts possible to unlock???

**Comment by alexvandesande** [comment]
This means you don't have the private keys to the wallet. Did you create the wallet on the same machine you are on?

**Comment by AMONRA75** [comment]
yes i have the main wallet and the contract wallet with 12 eth but is watch only

**Comment by AMONRA75** [comment]
i can remove this contract and take my funds???

**Comment by alexvandesande** [comment]
The question is not if you have your main wallet, but how did you create that wallet? Do you have the accounts that control the wallet?

Maybe you could help by putting a screenshot of your wallets dashboard where we can see your wallets and accounts. Feel free to remove any addresses or balances (although that would not be a security risk)

**Comment by luclu** [comment]
@AMONRA75 I will close for now. Feel free to stay and continue discussing.
