### ISSUE TITLE
Mist ignores parameters

### ISSUE THREAD

**Issue by Victor-Deidon** [ethereum/mist#3874]
Version: `0.10.0`
OS & Version: windows 10
Node version: `geth 1.7.3`
Number of blocks synchronized: 24451

Hi,
i'm running into a quite frustrating issue.
I have a private node on a VM that i can start geth and mine with on a private blockchain.
The issue is when i start mist and try to run Mist.exe --rpc http://192.168.x.x:8545  --swarmurl null
on another (windows 7 ) computer, Mist behaves like there was no parameters and just starts on a solo network.

Thanks for your help,
please tell me if you need any precision.

Victor

**Comment by ryanio** [comment]
Hey Victor, we just released a new version (`0.11.0`) - please give it a try. Please try connecting `--rpc` with an IPC or websockets path, since http is now deprecated. If you have any new problems that you can reproduce, please create a new issue with the details on how 
we can help. Thanks!
