### ISSUE TITLE
Mist v0.5.2 - OS El Capitan 10.11.3 - x hours since last block

### ISSUE THREAD

**Issue by Mundy35** [ethereum/mist#388]
After the upgrade from 0.5.1 to 0.5.2 mist does not sync anymore.
![screen shot 2016-03-18 at 10 37 02](https://cloud.githubusercontent.com/assets/17923710/13874007/670443f0-ecf5-11e5-9c97-13529c121941.png)

I have the latest version of Geth:
_./**geth version**
Geth
Version: 1.3.5
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.5.1/libexec_

and Geth is synchronized:
_> **eth.blockNumber**
1171528_

Screenshot from the Developer tools: 
![screen shot 2016-03-18 at 10 35 18](https://cloud.githubusercontent.com/assets/17923710/13873988/5011de64-ecf5-11e5-8243-6fd02cf3bbd3.png)

Any idea?

**Comment by alexvandesande** [comment]
How long has it been that way? Sometimes it takes about a minute for my wallet to catch up and find the latest block. If it persists more than that, try restarting the wallet.

**Comment by Mundy35** [comment]
I have this issue since the upgrade from 0.5.1 to 0.5.2. It has never worked with 0.5.2.
I have already restarted the wallet, even deinstalled and reinstalled everything (wallet + geth).
The thing is that geth is synchronised and it receives perfectly the blocks. The issue seems to come from the UI.

**Comment by swt83** [comment]
Same as issues #386 #362 #310 #292

**Comment by hiddentao** [comment]
I had a similar problem if I ran mist without first running `geth`. I'm fairly sure this due to the version of `geth` that's bundled with mist being older than the Homestead release version - thus it's unable to download past block 1,150,000 (the Homestead hard-fork block).

**Comment by johnpitchers** [comment]
Reported here 5 days ago. https://github.com/ethereum/mist/issues/366

**Comment by clund** [comment]
Solved issue with database upgrade by deleting the database and letting it download again. After shutdown and restart of Mist the following message appears. Seems like there's very little Zen with 5.2 on Mac.

Node type: geth
Network: main
Platform: darwin (Architecure x64)

...o /Users/clund/Library/Ethereum/chaindata
I0321 13:35:51.122331   15065 database.go:71] Alloted 78MB cache to /Users/christianlund/Library/Ethereum/dapp
I0321 13:35:51.142665   15065 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0321 13:35:51.143143   15065 backend.go:362] Blockchain DB Version: 3
I0321 13:35:51.145186   15065 blockchain.go:214] Last header: #770694 [35c0cb45…] TD=4879785175929831087
I0321 13:35:51.145235   15065 blockchain.go:215] Last block: #770694 [35c0cb45…] TD=4879785175929831087
I0321 13:35:51.145254   15065 blockchain.go:216] Fast block: #770694 [35c0cb45…] TD=4879785175929831087
I0321 13:35:51.145664   15065 handler.go:92] blockchain not empty, fast sync disabled
I0321 13:35:51.153274   15065 cmd.go:114] Starting Geth/v1.3.5/darwin/go1.5.1
I0321 13:35:51.153400   15065 server.go:311] Starting Server
Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use (possibly another instance of geth is using the same port)

**Comment by frozeman** [comment]
You're already running geth, maybe mist couldn't shut it down properly. Please start the "activity" app and quit geth manually and restart

**Comment by frozeman** [comment]
@Mundy35 the issue youre having, is that the Mist interface can't connect to the node. This could be because the IPC path is incorrect, but than it wouldn't have started at all. Or the IPC connection was killed from the node side (@bas-vk ?). Please restart the wallet and try a few times.

Everytime you see a IPC connection error, than the connection to the node is broken.

**Comment by Mundy35** [comment]
@frozeman I have tried several times to restart the wallet but this did not solve this issue.

**Comment by clund** [comment]
> Please start the "activity" app and quit geth manually and restart.

I assume you mean Activity Monitor. No Ethereum processes are active. Also tried:

ps aux | grep -i 'geth'
ps aux | grep -i 'eth'

No running processes matched.

It seems like Ethereum sometimes fails to close down properly and leaves the listener open. Any idea of how to shut it down manually?

**Comment by swt83** [comment]
I can confirm that simply rebooting your computer solves this problem.

**Comment by clund** [comment]
Indeed rebooting does the trick, but I would hope that a better solution is introduced in later builds.

**Comment by Mundy35** [comment]
Rebooting my computer with having only Mist running on it solved this problem for me also.
Thank you all.
