### ISSUE TITLE
Why I Can't seem mine on my private network?

### ISSUE THREAD

**Issue by Medi1** [ethereum/mist#3881]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.10.0`
OS & Version: windows/64
Node version: `geth 8.11.1`
```

 Screen shot : https://imgur.com/a/gRPeJz0

I've created a private network all fine but when I attache and miner.start(1); the kh/s show in Mist but I keep waiting and no ether got mine not a single one!!!

https://codeshare.io/GqxZ3Z this is the code of the first command line where I start geth

https://codeshare.io/2pgZYX this is the second terminal where I start mining command

I think the ERROR 'The pipe is being closed' it's the problem and that happen when opening Mist, see line 18 in the code in the first command line snippet, help!

**Comment by evertonfraga** [comment]
Hi @Medi1, why don't you use `geth --dev`, which creates a local, private network with auto-mine transaction?

Should you still have issues, please reopen this issue.
