### ISSUE TITLE
whats the Compiler version ? dose the Optimization enabled by default ? 

### ISSUE THREAD

**Issue by moesaid** [ethereum/mist#3884]
```
Version: `0.10.0`
OS & Version: osx
Node version: `geth 1.8.2`
```

hi guys i was searching for so long for these information and i couldn't find any , fond some clue as in the package.json

`"solc": "^0.4.18"`

but still what version of it as when you go confirm your code after deploying need these information
also is the optimization enabled or disabled ?

**Comment by ryanio** [comment]
Hey, thanks for the question. If you would like advanced compiler options, we recommend using [remix.ethereum.org](https://remix.ethereum.org)

I believe that [meteor-dapp-wallet](https://github.com/ethereum/meteor-dapp-wallet) may use `eth_compileSolidity` which would then depend on what the node has configured (more likely default geth settings unless you are running and attaching your own node), but I'm not 100% certain so you might want to dig a little more to get the specific answer to your question.

Please reopen if we can help further! Thanks!

**Comment by Hioln** [comment]
do you means you don't know what version for solc in eth_compileSolidity.js????
