### ISSUE TITLE
Wallet and passwords

### ISSUE THREAD

**Issue by ethercrapwallet** [ethereum/mist#3886]
If this is your first account on ethereumwallet, dont even bother sending any big amounts into it, as password you use for wallet, simply wont get recognised later, and all your money will be gone.

I've made password, and i know all my passwords im making and writing them down, tried all possible ways where i could have put Upper or lesser case, without any success, deleted UTC file hoping if ill make new one, all will work, ended up with new WALLET , and old wallet info gone with all cash , great , 1/10 service. hope tron will overtake this crap.

**Comment by alexvandesande** [comment]
We have multiple "wrong password" threads and I suggest taking a look at them, as Ill merge this into that one: #3513

**It's not possible to recover ether without a password or change the password.** But some suggestions:

* Try using  [myetherwallet](https://myetherWallet.com) or [mycrypto](https://mycrypto.com) to unlock the password and see if it's a geth/mist issue. If you can't there then it's really a password issue
* Mist never creates an account for you automatically. We do however use accounts from geth, so if you have previously installed Geth, and created an account there without thinking, that might be the one.
* If you can run python (or know someone who does) try the [Python Recovery tool](https://github.com/burjorjee/pyethrecover)
* If you can't do it yourself, you might consider hiring someone to brute force your password for you but make sure you find a reputable source. If they are able to unlock it, **they might claim all the money in it and you'll be without any legal recourse**.
