### ISSUE TITLE
Wallet hacked, how get access to ETH Wallet

### ISSUE THREAD

**Issue by Korn3105** [ethereum/mist#3887]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

Hello,

In 2017 I've participated in STORIQA ICO and obtained an amount of STQ TOKENS. These have been automatically on 16th of February 2018 (about that I've not been informed) transferred to an ETH wallet which I had probably till end of January. My EHT wallet is:

0x7474bd5e2ee50b52ecebd44812c05211b0f592a0

However, somebody has hacked my wallet account and transferred it to other ETH wallet

![2018-05-12_15-59-31](https://user-images.githubusercontent.com/39219820/39958735-64fc3586-5607-11e8-9ab3-9a98a52f1af7.png)

can you please verify, whom does belong this ETH wallet? How can I restore my ETH wallet and withdraw the amount of STQ tokens?

```
Version: `0.10.0`
OS & Version: MacSierra
Node version: `geth 1.8.2`
Number of blocks synchronized: 685,524 blocks left / 12 %
```

**Comment by marcgarreau** [comment]
Our team has no ability to identity or manage ownership rights of wallets. I'm very sorry to hear if someone has compromised your wallet, but I do still see 214k STQ tokens in your wallet you shared. Am I misunderstanding that you think these have been transferred out? Closing this issue, because there is nothing our team can address.

**Comment by Korn3105** [comment]
No, this is my wallet:

0x7474bd5e2ee50b52ecebd44812c05211b0f592a0

And then the amount of 259k STQ coins went out to this wallet, which I didn't initiate:

0x5c3a228510D246b78a3765C20221Cbf3082b44a4

How was it possible? How can I restore the password for the my ethereum wallet?
