### ISSUE TITLE
What is the current Chain Structure Size?

### ISSUE THREAD

**Issue by ChristBKK** [ethereum/mist#3891]
Hi there,

what is the current Chain Structure Size?

I am at the moment at 135 MIO.

Thanks for the Information

**Comment by bb2ebb** [comment]
hi chris, how many your chain structure currently now?

**Comment by evertonfraga** [comment]
Please try syncing with Light Client (`develop > Sync with Light Client`).

Should this fail, try using your keystore (`File > Backup > Accounts`) file with a third-party service, like https://mycrypto.com
