### ISSUE TITLE
Compilation error -    require( condition ,"message") - works in remix Ide

### ISSUE THREAD

**Issue by raky35** [ethereum/mist#3892]
* [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.10.0`
OS & Version: MacOs
Node version: `geth 0.0.0`6.0.1
Number of blocks synchronized: 0
```
Hi ,
Below contract compiles fine in Remix but fails in Mist , Please pardon me if i am missing anything.

pragma solidity ^0.4.21;
contract HelloWorld {
    uint256 counter = 5; //state variable we assigned earlier
    function add() public {  //increases counter by 1
    counter++;
    }
    function subtract() public { 
    //decreases counter by 1
    counter--;
    }
    function getCounter() public constant returns (uint256) {
     return counter;
    } 
    
    function constructer(uint256 amount)  public payable  {
    require(msg.value == amount,"Not enough Ether provided.");
    }
}
    Error on line in mist :     require((msg.value == amount),"Not enough Ether provided.");
   Error :  Could not compile source code.  Wrong argument count for function call

Thanks 
Kind Regards
raky

**Comment by marcgarreau** [comment]
The best places to get help with solidity contract debugging might be the solidity gitter channel (https://gitter.im/ethereum/solidity/) or on https://ethereum.stackexchange.com/. Good luck!
