### ISSUE TITLE
Deploy Contract raises issue ""transaction will fail" when AMOUNT is enetred 

### ISSUE THREAD

**Issue by raky35** [ethereum/mist#3897]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

i am trying to deploy a simple contract with a intention that  during deploying process Contract should hold soem ethers as well, but it fails as per attached screen. If i enter Amount as 0, then contract is created without any problem. Not sure if i am missing anything  Thanks, Kind Regards  raky
![screen shot 2018-05-17 at 12 35 43](https://user-images.githubusercontent.com/7769590/40175376-c993b2b4-59cf-11e8-9789-7e6bf82abc3b.png)
![screen shot 2018-05-17 at 12 35 57](https://user-images.githubusercontent.com/7769590/40175380-cb9c1eb6-59cf-11e8-9bc5-24bac664832d.png)

 
- Mist version 0.10.0 
- OS MacOS 
Node v8.9.4

pragma solidity ^0.4.21;

contract HelloWorld6 {
    address owner;    // current owner of the contract

    uint256 counter = 5; //state variable we assigned earlier
    function add() public {  //increases counter by 1
    counter++;
    }
    function subtract() public { 
    //decreases counter by 1
    counter--;
    }
    function getCounter() public constant returns (uint256) {
     return counter;
    } 
    
    function() payable public {
     }

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by marcgarreau** [comment]
The best places to get help with solidity contract debugging might be the solidity gitter channel (https://gitter.im/ethereum/solidity/) or on https://ethereum.stackexchange.com/. Good luck!
