### ISSUE TITLE
Menu items raise error on Windows

### ISSUE THREAD

**Issue by bas-vk** [ethereum/mist#39]
When one of the menu items (except for the entries in the Develop menu) is clicked the following alert is raised:

![screen shot 2015-08-11 at 17 01 36](https://cloud.githubusercontent.com/assets/4280775/9201239/352cdc26-404c-11e5-96ad-93ed91bc4966.png)

This is on Windows 7.

**Comment by frozeman** [comment]
This has to do with an OS X specific behaviour, but seems to be fixed in the coming release of electron..

**Comment by frozeman** [comment]
the new version fixed it, i will give you a new version to test
