### ISSUE TITLE
Does not compile when i use 'push' method on an array

### ISSUE THREAD

**Issue by zmitton** [ethereum/mist#390]
I don't think this compiler understands the push method. It wont compile when i use it, and says the method is undefined. I could be wrong but its taken me all day and I can't figure out what the problem is whit my code. I believe my code is fine, and I think its mist that has the issue.

**Comment by frozeman** [comment]
@chriseth is this something in a newer compiler version?

**Comment by zmitton** [comment]
Im running 0.3.6. the Mist browser that was released for install. Is there a newer one I can install? I dont really know how to build it from source though. This one I just downloaded as a regular program.

**Comment by frozeman** [comment]
The latest for homestead is 0.5.2, try this one. Its the wallet only, not mist: https://github.com/ethereum/mist/releases

**Comment by chriseth** [comment]
@zmitton push is only available for storage arrays, not for memory arrays. might that be the problem?

**Comment by zmitton** [comment]
seems to work better thanks @frozeman :)
