### ISSUE TITLE
What to choose to generate new crypto currency tokens? Either Mist or Ethereum wallet

### ISSUE THREAD

**Issue by sugalivijaychari** [ethereum/mist#3902]
I am planned to create a new crypto currency token via Mist Ethereum Wallet. In https://github.com/ethereum/mist/releases I found two links that are compatible to my system. One is Mist-win64-0-10-0.zip and other one is Ethereum-Wallet-linux64-0-10-0.zip. I am confused whether to install two of them or either one of them. Please tell me whether to install both of them. If not, which will be helpful to install for creating tokens.

**Comment by marcgarreau** [comment]
Mist is the wallet + browser. All you need to deploy and manage tokens is Ethereum Wallet. Good luck!
