### ISSUE TITLE
Windows 10 Ethereum Wallet 0.10.0 no peers even with Light network enabled.

### ISSUE THREAD

**Issue by StrobFX** [ethereum/mist#3907]
The wallet often crashes and can't find peers even with light network enable din develop.

**Comment by jfgreen01** [comment]
this will not get resolved as there are only 3 participants here; Look like the issue is in the hands of Marc fron Dever CO, this is why the issue will never get resolved and will still be in linger.

**Comment by marcgarreau** [comment]
Sorry for the headache - at the moment it occasionally takes a long time to locate light peers. The place to address this question is with the geth team, though. Check out their issues [here](https://github.com/ethereum/go-ethereum/issues). In Mist, the connecting screen should just hang, not crash. Please reopen with Mist crash report output if that is the case.

**Comment by StrobFX** [comment]
I was finally able to  sinc the blockchain. I used regular mode first and it took a while but always stopped like a 100 blocks before the end. Then I switched to the light network and it could sinc it all.
