### ISSUE TITLE
Initial BTC deposit overfund?

### ISSUE THREAD

**Issue by webprez** [ethereum/mist#391]
Hi guys, newbie here with a quick question. I realize when I installed and ran the Ethereum wallet app on Windows, it tells you to send ".0317" or whatever the number is of BTC toa the shown address, and that will fund the new account with 1 Ether. 

Well, I wanted to put more in, so I transferred 0.69 BTC to the shown address. However, my new account/wallet still only shows me as having 1 Ether. Did I just lose the rest of that BTC?

**Comment by YouHue** [comment]
I had that problem too. Anyone know how to retrieve that BTC?

**Comment by luclu** [comment]
@webprez did you resolve your issue?

**Comment by webprez** [comment]
@luclu No it hasn't been. The response above resolved itself naturally, and was a different problem than I experienced. If anyone has any ideas as to where my BTC has gone, please help!

**Comment by luclu** [comment]
@webprez please try to get in contact with shapeshift as they can trace and hopefully recover any lost founds. Please keep me updated on this!

**Comment by webprez** [comment]
@luclu I sent my funds from Coinbase.... are you suggesting it's an issue with them?

**Comment by luclu** [comment]
It might be - that said they will definitely be able to trace it.

**Comment by luclu** [comment]
@webprez was shapeshift's support able to assist you? I assume your issue has been solved and will close for now. Feel free to continue to discuss with me.
