### ISSUE TITLE
Iostokens not showing up in ethwallet

### ISSUE THREAD

**Issue by EOC1620** [ethereum/mist#3924]
not sure how to go about this issue. I transferred from binance to my recently downloaded eth wallet but I don't see the tokens on my desktop. I can only see the verified transaction on etherscan. any help in being able to manage my iost tokens again is greatly appreciated.

**Comment by ryanio** [comment]
Hey, we just released a new version (`0.11.0`) - please give it a try! You'll have to add the token details in the `Contracts` tab in the wallet. If you have any new problems that you can reproduce, please create a new issue with the details on how 
we can help. Thanks!
