### ISSUE TITLE
Mist

### ISSUE THREAD

**Issue by leo4msiu** [ethereum/mist#3926]
My Mist app stopped working. When you open the application, it displays an error. Has anyone faced a similar problem ? How do I access my wallet ?
![65465](https://user-images.githubusercontent.com/39776711/40742822-5538dadc-6458-11e8-8b99-76967aaa8d90.jpg)

**Comment by xianjy** [comment]
the same problem with you,how to resolve it ?

**Comment by evertonfraga** [comment]
Hi! We have an updated version with improved syncing. After downloading version v0.11.0, please enable the Light Client (`Develop > Sync with light client)`

I am closing this thread, if you still have any trouble **please feel free** to file a new issue or comment in an open one that better describes your situation.
