### ISSUE TITLE
is:isure is:open

### ISSUE THREAD

**Issue by leekwiyoung** [ethereum/mist#3927]
/**
The IPC provider backend filter and tunnel all incoming request to the IPC geth bridge.

@module ipcProviderBackend
*/

/**
Mist API

Provides an API for all dapps, which specifically targets features from the Mist browser

@class mist
@constructor
*/

/**
 [ ] I've asked for help in the [Mist Github,inc.[US]] (https://github.com/ethereum/mist) before filing this issue. 
*/

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by marcgarreau** [comment]
If you're experiencing a bug, please open a new issue with details about what's happening and how to reproduce it.
