### ISSUE TITLE
Ethereum version 0.10 for wuin 64 is: unable to find peers, dont sync the wallet and dnot download the block

### ISSUE THREAD

**Issue by maluma2** [ethereum/mist#3934]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by ryanio** [comment]
Hey, we released a new version (`0.11.0`) with new syncing features - please give it a try! If you have any new problems that you can reproduce, please create a new issue with the details on how
we can help. Thanks!
