### ISSUE TITLE
will not allow me to send coins to another walet using ethereum

### ISSUE THREAD

**Issue by Hackertalkz** [ethereum/mist#3935]
How do I get this ethereum wallet to connect to a node to send coins... I can recieve but can not send

* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by marcgarreau** [comment]
Cleaning up stale issues; more recent releases of mist + geth have addressed related issues. Please reopen/open a new ticket if appropriate.
