### ISSUE TITLE
EthereumNode - Failed to connect to node Error

### ISSUE THREAD

**Issue by QingmingZi** [ethereum/mist#3938]
when i change to rinkeby,"EthereumNode - Failed to connect to node Error: Unable to connect to socket: timeout
",mist 0.10.0,win 2008 R2
How to solve？
The server is in Silicon Valley

* [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.10.0`
OS & Version: windows 2008 R2
Node version: `geth 1.8.0`
Number of blocks synchronized: 0
```

**Comment by m3shine** [comment]
func electron

**Comment by PhilippLgh** [comment]
Please see ethereum/mist-shell#7 for progress on this issue
