### ISSUE TITLE
Mist Balance not showing correct amount

### ISSUE THREAD

**Issue by AJKennett** [ethereum/mist#394]
The correct balance is displayed on etherchain.
 However when I open my mist wallet, there are less funds 
One transaction in particular isnt showing; I believe it might have something to do with the release of homestead as thats when it happened is there any way to manually send a transaction to access the ETH that isn't showing?

**Comment by frozeman** [comment]
There is not hidden balance and the mist wallet will certainly show the correct amount on the chain right now. You can check your balance also on etherscan.io

**Comment by AJKennett** [comment]
I was running geth for mining purposes. After closing it and relaunching mist i was able to update the blockchain and the balance is now correct

**Comment by JRogiest** [comment]
Crucial to have the blockchain synchronised in your wallet and good to hear the balance is correct. You can now close the issue.
