### ISSUE TITLE
I need help with Etherium transaction issues.

### ISSUE THREAD

**Issue by superswk** [ethereum/mist#3943]
Version: `0.10.0` 
OS & Version: windows10
Node version: `geth 1.7.2`
Number of blocks synchronized: 0

Hello.
I sent it from my ether wallet to the exchange.
There was a problem with the transaction.

Transaction: 0x87eaab289ae609a98306fc86f97913d71d210c1c5a271c51bc855d7bf0759d96
"Sorry, we can not find this Transaction Hash"
 
It is not processed after several days
Thank you for your help.
 
Thank you.

**Comment by superswk** [comment]
The transmission is not successful and the balance of the ether wallet is displayed as 0. Is there a solution?

**Comment by dfkthf125** [comment]
Извините, мы не можем найти этот трюк транзакции Транзакция  0x87eaab289ae609a98306fc86f97913d71d210c1c5a271c51bc855d7bf0759d96  
такой ответ от 
![image](https://user-images.githubusercontent.com/9912853/41348994-1e78d528-6f17-11e8-93e7-1c915e195197.png)
