### ISSUE TITLE
Problem with Ethereum Wallet.

### ISSUE THREAD

**Issue by HeronDeAlejandria** [ethereum/mist#3947]
I'm new on ethereum and just for learning propuse i wan't to mine. the ethereum wallet main network sync just finished but i can't see the button "start mining (shift+command+m)" (appears on the solo network) won't appear here.

Why is that?

what should I do?

OS & Version: MacOSX Sierra
Node version: geth 1.8.10
Number of blocks synchronized: 5 738 096

<img width="497" alt="captura de pantalla 2018-06-05 a la s 15 45 17" src="https://user-images.githubusercontent.com/39846846/40999048-b6ef47ce-68d7-11e8-9026-b1b1cee9cfba.png">

**Comment by marcgarreau** [comment]
Welcome! Mining is for advanced users and is not the purpose of the wallet, therefore we removed many of the options for it.
