### ISSUE TITLE
Money not showing up in Ether wallet. Any ideas why?

### ISSUE THREAD

**Issue by davecam73** [ethereum/mist#3956]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
Hi! We have an updated version with improved syncing. After downloading version 0.11.0, please enable the Light Client (`Develop > Sync with light client)`

I am closing this thread, if you still have any trouble **please feel free** to file a new issue or comment in an open one that better describes your situation.
