### ISSUE TITLE
Can't find peer most of the time. Any one help me out?

### ISSUE THREAD

**Issue by bitbd83** [ethereum/mist#3957]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by marcgarreau** [comment]
Sorry for the headache. The best place to address this question is with the geth team. Check out their issues [here](https://github.com/ethereum/go-ethereum/issues).
