### ISSUE TITLE
problem creating new account in mist

### ISSUE THREAD

**Issue by BlockWaving** [ethereum/mist#3972]
Hi. I have just installed Ethereum Mist went fine. Now I am trying to create an account while connecting to Ropsten but nothing happens. After clicking "Add account" system required to type password and then repeat. Afterwards, window just closes and no actions.  Repeated multiple time, nothing showup and can see.   I also close and restarted Mist several time and syncing is up to date looks.  Check Mist version is 0.10.0.  What should I do with such issue?

**Comment by marcgarreau** [comment]
i was able to reproduce the issue. if you'd like an immediate solution, this appears to be resolved in the newest release. you can find that here: https://github.com/ethereum/mist#release-candidate-0110-up-for-testing.

**Comment by marcgarreau** [comment]
please open a new ticket if issue is not resolved in version 0.11.
