### ISSUE TITLE
Can't toggle back to non-light sync / long intervalls to get new blocks

### ISSUE THREAD

**Issue by theBergmann** [ethereum/mist#3977]
* [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.10.0`
OS & Version: linux
Node version: `geth 0.0.0`
Number of blocks synchronized: 5.847.012
```

<!--

Hoi, I played around with Light-Sync and have two problems to report:
- after restarting, I can't toggle back. The "developer"-menue is gone. On another attempt I had the developer menue, but not the option to toggle sync mode
- after having synced in light-mode, I only get new blocks after some minutes. 

Beside this, I'm happy that it worked. After having found peers, it really synced blazingly fast. Thanks for this!

**Comment by marcgarreau** [comment]
Changing settings can occasionally cause the app to get out of whack. Usually restarting the app resolves any odd behavior. If you're up for trying it out, the newest release candidate should provide a smoother experience: https://github.com/ethereum/mist#release-candidate-0110-up-for-testing. If you think you're experiencing a geth-specific issue, you may reach out to them [here](https://github.com/ethereum/go-ethereum/issues).
