### ISSUE TITLE
Integrate EtherID.org ipfs requests in the BROWSER bar in Mist? - Good potential? Decentralized DNS on ethereum

### ISSUE THREAD

**Issue by BL186** [ethereum/mist#398]
This is not exactly an issue but I would like to make this suggestion:

etherid.org is basically a domain name registrar smart contract on ethereum blockchain.

It would be great if on the Browse area in Mist there would be an option to choose between Main Internet (where all normal sites are available like google.com, facebook,com, etc.) and another option for etherid.org domains, where whatever you insert in the browse bar it would call the name from the etherid IPFS.

With etherid any string can be an address, even case sensitive strings are different and extensions like .com, .org, etc. are not mandatory.

I think doing this would bring more people into ethereum, as to register domain names there you need ether, thus this would attract more demand into ethereum from the whole domain name industry.

**Comment by alexvandesande** [comment]
Yes, we will add the option of custom domain resolvers on Mist.
