### ISSUE TITLE
Help find Keystore number or private No

### ISSUE THREAD

**Issue by Fayman** [ethereum/mist#3980]
*

I can send the recovery codes and I am in my account now but I don't know where to find my Keystore file number or private number....Can anyone please direct me....thank you I appreciate any help I can get at 71 its rather difficult...
Fay Ngaire Drage

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by Gonda34** [comment]
Already team! helped me
Wallet services, contact us
https://t.me/recoveryservices
braunrecovery@gmail.com

**Comment by Fayman** [comment]
I don’t have telegram so revert back to email.....I am not sure what to download for telegram as I have a small laptop Lenovo – is that a Android? Sorry way above my old head...lol
How much would it cost for you to recovery the storekey number of my etherwallet?....I do have the files on Apple laptop but that needs a clean up first its slow and says something like its full - ???? so you can see I need your help badly. Is there anyone in Brisbane who can help me please....
And price? – thanks – 
Fay Drage

Sent from Mail for Windows 10

**Comment by Gonda34** [comment]
Hi
please send  email
braunrecovery@gmail.com

2018-06-29 0:37 GMT+02:00 Fayman <notifications@github.com>:

**Comment by Fayman** [comment]
Thanks Jack....
[IntelGFXCoin.log](https://github.com/ethereum/mist/files/2148799/IntelGFXCoin.log)
The other files are on Apple laptop so I will have to download Telegram on that as well.....I will send others tomorrow via the Apple

**Comment by Fayman** [comment]
[version.pdf](https://github.com/ethereum/mist/files/2148903/version.pdf)
[ZipDLL.pdf](https://github.com/ethereum/mist/files/2148904/ZipDLL.pdf)

[version.pdf](https://github.com/ethereum/mist/files/2148905/version.pdf)
[ZipDLL.pdf](https://github.com/ethereum/mist/files/2148906/ZipDLL.pdf)

**Comment by Fayman** [comment]
Here s hoping the right file is attached.....thank you so much Jack -
