### ISSUE TITLE
Add geth console support on mist

### ISSUE THREAD

**Issue by akx20000a** [ethereum/mist#3985]
It is possible for Bitcoin QT to interact with their node console, I think adding a menu for geth ipc attach will be a great feature

+ Bitcoin Console
![bitcoin](https://user-images.githubusercontent.com/34651082/42178562-e01c2eba-7e6b-11e8-8b9a-98d21257f608.PNG)

+ Geth console
![geth](https://user-images.githubusercontent.com/34651082/42178653-2c63dcf0-7e6c-11e8-9a73-d99979bae539.PNG)

+ Github Desktop git console menu ( example )
![command](https://user-images.githubusercontent.com/34651082/42178664-3b5b8866-7e6c-11e8-819d-dbcafc642216.PNG)

**Comment by alexvandesande** [comment]
You can do this by launching your own console and then having mist connect to it. It seems to me that it makes no sense for us to add our own console, since Mist isn't for terminal oriented users.
