### ISSUE TITLE
Can't send ethereum

### ISSUE THREAD

**Issue by kazibobrik** [ethereum/mist#3987]
Hello, my transaction is not send
I change fee and try a lot of times do transaction, but nothing helps me.

```
Version: `0.10.0`
OS & Version: linux ubuntu 14.04 x64
Node version: `geth 0.0.0` - i don't know what is it
Number of blocks synchronized: 5 909 839
![2018-07-05 14 49 24](https://user-images.githubusercontent.com/40859223/42322365-d4ce39fe-8064-11e8-8b47-5228bc110e3b.png)
![2018-07-05 14 49 54](https://user-images.githubusercontent.com/40859223/42322366-d4ef4a22-8064-11e8-8992-17476e230c3e.png)
![2018-07-05 14 51 50](https://user-images.githubusercontent.com/40859223/42322367-d51107f2-8064-11e8-9ff1-a7da452ec8c3.png)

```

Look the Screenshots, please.
And I use "Sync with Light client (beta)" - maybe is this reason?

**Comment by Arkady82** [comment]
I have the same problem with 0.9.3 and 0.10.0. 
All my three transaction can't send to blockchain and can't recive confirmation
0x89f08ef02191558c20d622e44c4f563ccc4b23cbffc91e02bfec2f529645c7f6
0x6857c237f309c94a87927b48471e36e80de56151ab434ea6b8db3796432c0410
0xd86df4d0e75c3b09d1de9c324be928d49e70c540604bf272999d5114036e006b
How to cancel them? And how to send a new without problem?

**Comment by kazibobrik** [comment]
Arkady82, I change transactions fee to almost maximum and only after that my transactions where done.

**Comment by Arkady82** [comment]
Kazibobrik, thank for you reply. What was final TxFee for your transaction and have you disabled the option "Sync with Light client (beta)"? 
I make transfer from myetherwallet.com recently, with minimal Gas Price = 1 Gwei, finally TxFee was 0.000021, transaction was complete wery fast 2-5 minutes. 
But with local Etherwallet i have some problems

**Comment by kazibobrik** [comment]
1st transaction - 0.000861 ETHER
2nd transaction - 0.001764 ETHER

**Comment by kazibobrik** [comment]
And I think that better use another wallet - Coinomi ... it have fix transactions fee 0.000420 ETH

**Comment by Arkady82** [comment]
TxFee expensive (for Me), as in Bank transfer.... I think change wallet too. Thanks

**Comment by marcgarreau** [comment]
Sorry for the headache. Recent network congestion has caused high gas prices, but that's not something we can control.
