### ISSUE TITLE
installer checksum differs 

### ISSUE THREAD

**Issue by rawdez** [ethereum/mist#3989]
installer checksum differs by 1 symbol (4 @ beginning)
is it safe to run?
generated:

>   6e843e66b507a6e0f4fd8efac408e09fbe8f02fb4ee1ba867492bbfe020e27df *Mist-installer-0-11-0.exe

from Checksum (SHA256) table:

> 46e843e66b507a6e0f4fd8efac408e09fbe8f02fb4ee1ba867492bbfe020e27df

**Comment by ryanio** [comment]
Thanks guys, will add Ev on this who prepped the release

**Comment by evertonfraga** [comment]
It is fixed now, sorry for the confusion.
