### ISSUE TITLE
More information in download page for releases

### ISSUE THREAD

**Issue by tjayrush** [ethereum/mist#3990]
On this page:

https://github.com/ethereum/mist/releases

You present a long list of all sort of stuff, which is fine, but there is a huge missing piece of information that would make the task of downloading and install your product **much** easier.

Here's the problem:

   NO-ONE UNDERSTANDS THE DIFFERENCE BETWEEN
   THE WALLET AND THE MIST BROWSER.

Do we need both? What happens if we use one over the other? Why would one need a wallet but not a browser? Does one need a browser and not a wallet? Why is all this crap on a single page?

These questions rumble through my brain every time I come to this page making me fearful that I will do the wrong thing and lose all my money.

**Suggestion:** Create a much, much better download experience/page, so even users like myself (who I consider to be ultra-technical) don't experience unneeded angst and actually download Mist instread of leaving without downloading as I always do.

**Comment by alexvandesande** [comment]
Thanks for the feedback. Indeed there were larger differences between both that warranted the separation but now we are closing that gap and in the near future we will consider retiring EW
