### ISSUE TITLE
Mist RPC Issues

### ISSUE THREAD

**Issue by joeykrug** [ethereum/mist#3995]
* [X] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.11.0`
OS & Version: osx 10.13.5
Node version: `geth 1.18.12`
```

When running Mist with the RPC flag enabled it fails to connect to the node and says this:

`[2018-07-06T14:47:52.685] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)`

Then this pops up
<img width="461" alt="screen shot 2018-07-06 at 2 50 17 pm" src="https://user-images.githubusercontent.com/5925937/42401773-0becb916-812c-11e8-8d75-0baaffbdade5.png">

Logs attached:
[all.log.txt](https://github.com/ethereum/mist/files/2172062/all.log.txt)

**Comment by ryanio** [comment]
@joeykrug it looks like you were trying to connect with `http` which is being deprecated due to inability to support subscriptions, can you try launching Mist using an IPC RPC connection? i.e. `--rpc path/to/geth.ipc`

**Comment by tannutuva** [comment]
![mist rpc ipc not connecting to local node](https://user-images.githubusercontent.com/41525296/43040324-adfbd71a-8d06-11e8-8c5b-941849db669d.png)

@ryanio I am on linux64 and have a separate geth instance (1.8.12) running in a custom data-dir.  I'm starting mist with --rpc /mnt/mydir/geth.ipc which worked on 0.10.0, and it seems to half work here.  it can see the peers but won't switch over to my local geth from remote even though it's fully synced.  looks like people have having rpc issues on mac, win, and linux (on glitter and in other issues).  

I'd rather not have the node managed through mist and would like to disable the remote node functionality completely if I could.  it's much easier to run geth on the side under a restart script for any crashes and only open up mist when I need to use it.

**Comment by PhilippLgh** [comment]
https://github.com/ethereum/mist/issues/3859
