### ISSUE TITLE
Stuck at `Loading client config...` splash screen

### ISSUE THREAD

**Issue by andysign** [ethereum/mist#3997]
* [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

Today, after running the geth client for a few days without the Mist GUI attached to it I tried to run mist to bring up the GUI but so far I am looking at the `Loading client config...` splash screen.

```
Version: `0.10.0`
OS & Version: linux
Node version: `geth 1.8.11`
Number of blocks synchronized: almost all of them
```

![scr](https://user-images.githubusercontent.com/11134288/42449530-ec92631e-8378-11e8-9071-46ac65e929d9.jpeg)
[all.log](https://github.com/ethereum/mist/files/2176015/all.log)

I've tried starting mist with:

* `mist`
* `mist --rpc /home/myuser/.ethereum/geth.ipc`
* `mist --rpc http://localhost:8545`

no luck.

the geth node is almost fully synced. 

Also i ve tried with different versions of geth with 

`mist --gethpath /home/myuser/folder/ --syncmode light --skiptimesynccheck --network main --reset-tabs --rpc /...`

PS: I don't want to update to the new layered mist client because i am not focusing on connecting to light nodes or server nodes like Infura...

EDIT: 
* Issue fixed with deleting the local file: `rm -r ~/.config/Mist`

**Comment by andysign** [comment]
Actually everything is fine now...

all working fine...

the final solution for me was something like:

`~/.config/Mist`

What should I do, should I edit the original issue descr?

**Comment by marcgarreau** [comment]
glad to hear you're operational now. i'll close the issue, no more action required. thanks.
