### ISSUE TITLE
Ethereum Wallet V.0-11-0 doesn't work in Win 64 bit

### ISSUE THREAD

**Issue by BCREA** [ethereum/mist#3998]
I have downloaded the ethereum wallet in the named version, and it just doesn't work. Issues: 
- It doesn't immediately find a node (have Geth 1.8.11
- Can't create an account in Ropsten (once i've given in the password and hit "create", the system runs for ever and never really creates an account. 
- Per cmd  I could create and account but could not open it from folder Keystore.  
I so need help! Thanks. 

```
Version: `0.11.0`
OS & Version: windows pro 10, 64 bit
Node version: `geth 1.8.11`
Number of blocks synchronized: 0
```

**Comment by maluma2** [comment]
dont work the new version 0.11

**Comment by Bobubil** [comment]
I confirm, this version doosent work, the first for me

I have tu use the previous version

**Comment by pozyx** [comment]
Adding account does not work, installing 0.10, add account, and then upgrading helped.

**Comment by subwolf** [comment]
Following the advice of @pozyx I tried downgrading to 0.10 and adding an account, only:

```
[2018-07-12T15:02:58.534] [ERROR] ipcProviderBackend - Send request failed { code: -32601,
  message: 'The method personal_newAccount does not exist/is not available' }
```

Bear in mind I am going through RPC and testing local only does not work.

**Comment by JonPitchfork** [comment]
Since I upgraded to Mist 0.11.0 running on Win10 x64, I see no startup splash window and the main window opens blank but showing menus.
Task Manager shows Swarm is not running. Looks like I will have to downgrade for now.

**Comment by zzm7777** [comment]
It does not work for me either. I tried to downgrade to 0.10, but when I close the wallet and reopen 0.10 version again, it prompts said that I need to download the latest version. I reinstall the 0.11 version and it still does not work at all..

**Comment by tor777** [comment]
Does not work, it is checked on Windows 7. 32/64 Windows Windows 10 Enterprise 2016 LTSB. Disgrace to the developers.

**Comment by vollkommenegal2017** [comment]
Same here. (W7, x64)

**Comment by evertonfraga** [comment]
Hi everyone, we're aware of this issue and we've been working on a hotfix should be released soon.
Please follow from #3988.

**Comment by Casper0513** [comment]
still doesnt work on 64 bit windows have to keep closing and opening every 3 mins
