### ISSUE TITLE
"Downloading blocks" gets stuck before completion

### ISSUE THREAD

**Issue by nomadashish** [ethereum/mist#400]
![screen shot 2016-03-21 at 1 51 14 pm](https://cloud.githubusercontent.com/assets/17846266/13913406/46bd7962-ef6c-11e5-9cb4-104dcd3262dd.png)
![screen shot 2016-03-21 at 1 52 46 pm](https://cloud.githubusercontent.com/assets/17846266/13913405/46b5138a-ef6c-11e5-9332-3baaffb6458c.png)

I am using OS X 10.11.3

**Comment by nomadashish** [comment]
The two screenshots were taken at a two minute distance

**Comment by frozeman** [comment]
Its processing the state, please wait

**Comment by frozeman** [comment]
Please see here: https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide#mist-is-synchronized-but-is-stuck-during-the-last-part
