### ISSUE TITLE
Ethererm 

### ISSUE THREAD

**Issue by sleepycat81** [ethereum/mist#4001]
issue: Hung when creating new account 

Version: 0.11.0
OS & Version: windows 7

**Comment by RelicTruth** [comment]
Try uninstalling / re-installing the wallet.

**Comment by punimkani** [comment]
@RelicTruth 
0x1616A23D6822373990366e2BCadC05DAaBbAdAB7

_Sent from my Galaxy S6 Edge using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by evertonfraga** [comment]
Hi @sleepycat81, this issue has been confirmed and we're actively working on a fix. 

Please follow from #3988.
