### ISSUE TITLE
My wallet are sending ETH by itself

### ISSUE THREAD

**Issue by satoslp** [ethereum/mist#4002]
![captura de pantalla 2018-07-10 a las 8 27 33 a m](https://user-images.githubusercontent.com/41063031/42514157-56188192-841e-11e8-88de-ad6d9980f1e6.png)
![captura de pantalla 2018-07-10 a las 8 29 12 a m](https://user-images.githubusercontent.com/41063031/42514158-56437a6e-841e-11e8-9d0d-09e4550904de.png)
[-1531229620250.log](https://github.com/ethereum/mist/files/2180607/-1531229620250.log)
[-1531229620251.log](https://github.com/ethereum/mist/files/2180608/-1531229620251.log)

```
Version: `0.11.0`
OS & Version: MacOS 10.11.6 El Capitan
Node version: `geth 0.0.0`
Number of blocks synchronized: 5.939.161
```
My mist Wallet is sending ETH by itself
Is my mist wallet hacked? 2 times have sent ETH by itself to my bitso wallet, but in my mist wallet doesn't show the movement, only shows the new balance of 0 ETH, if I check https://etherscan.io/address/0x5294011678d0799c37a3d578ae966f05bdee264e the movement shows to the bitso wallet that I use for exchange to fiat, but when I check in bitso there's no movement and no ETH, as sidenote bitso was hacked july 5th

**Comment by alexvandesande** [comment]
Mist doesn't show all transactions, because not all of them generate logs. But if you don't remember making those transactions on etherscan then your private key has been compromised. Take all funds from it immediately and generate a new account in a safe environment
