### ISSUE TITLE
yarn+react: error Command failed with exit code 1

### ISSUE THREAD

**Issue by lionroy** [ethereum/mist#4009]
Hi y'all!

trying to compile this react app [ build via crete-react-app] and figuring styled-components is rather useful. worked fine last i checked. compiling error statrted after have installed babel as recommended in their babel site.. kinda normal i guess.

for >$ yarn run build
I get this -
`yarn run v1.3.2
$ react-scripts build
'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

also -
for > $ yarn start
`yarn run v1.3.2
$ react-scripts start
'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

this is the error file generated-
[yarn-error.log](https://github.com/ethereum/mist/files/2202189/yarn-error.log)

- [v ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Yarn Version: `1.3.2`
OS & Version: windows/linux/osx
Node version: `geth 8.9.2`
Number of blocks synchronized: 0
```

TYVM

**Comment by ryanio** [comment]
Hey there. I'm not sure if you opened this issue in the wrong repo, but Mist is not a react app (nor a create-react-app). It is a hybrid meteor-react app right now, but we are slowly converting it over to all react.

**Comment by lionroy** [comment]
ryanio - to be honest not sure what do you mean, and what's mist.

**Comment by lionroy** [comment]
Solved. 

Here's how.  sorta. so- 
PROBLEM - it seems installing babel changed many nodes, yet it did NOT update the yarn.lock and package.json files accordingly. 
SOLUTION - 
$ yarn info         |> made me realize some 2k files are out of date
then ran 
$ yarn upgrade  |> and it somehow sorted it but didn't compile yet
then
 $ yarn add yarn |> to actually update yarn as it was 1.3.x and required 1.7.x 


i think that's it yet, may have skipped a step or two... better read more about the cli commands i suppose.

**Comment by simoutn** [comment]
its not working for me
Still have the error : error An unexpected error occurred: "Cannot read property '1' of null".

**Comment by simoutn** [comment]
i resole the problem when i edit webpack.config.js ( i remove the addStyleEntry )

**Comment by glenpegado** [comment]
> Solved.
> 
> Here's how. sorta. so-
> PROBLEM - it seems installing babel changed many nodes, yet it did NOT update the yarn.lock and package.json files accordingly.
> SOLUTION -
> $ yarn info |> made me realize some 2k files are out of date
> then ran
> $ yarn upgrade |> and it somehow sorted it but didn't compile yet
> then
> $ yarn add yarn |> to actually update yarn as it was 1.3.x and required 1.7.x
> 
> i think that's it yet, may have skipped a step or two... better read more about the cli commands i suppose.

It worked! This has aged well

**Comment by Franklin-Graciliano** [comment]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. Help

**Comment by CoBe18** [comment]
I received the same error as Franklin-Graciliano did.

  package.json
  public
  src

Either try using a new directory name, or remove the files listed above.
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-react-app

**Comment by schroef** [comment]
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. Help

Sorry but that link shows nothing related to error code 1, only shows some yarn codes

**Comment by techev13** [comment]
> Solved.
> 
> Here's how. sorta. so-
> PROBLEM - it seems installing babel changed many nodes, yet it did NOT update the yarn.lock and package.json files accordingly.
> SOLUTION -
> $ yarn info |> made me realize some 2k files are out of date
> then ran
> $ yarn upgrade |> and it somehow sorted it but didn't compile yet
> then
> $ yarn add yarn |> to actually update yarn as it was 1.3.x and required 1.7.x
> 
> i think that's it yet, may have skipped a step or two... better read more about the cli commands i suppose.


worked for me too

**Comment by piercerhymes** [comment]
One of the issue that you may face is the server won't start if some other server is running too .
For eg. I had XAMP Running and thus my yarn couldn't start itself. Check it once.

**Comment by deSousaMateus** [comment]
(Mac) In my case, I had this problem after cloning a repo from my work project, what I had to do was 'cd ios' and run 'pod install' inside there. After this I was able to build my local copy of the project. Hope it helps someone

**Comment by syedhaseeb16** [comment]
I was facing error, I use command yarn install and then yarn upgrade, now its working
