### ISSUE TITLE
Yello "Wrong Password" label shown when entered password for pre-sale wallet

### ISSUE THREAD

**Issue by nomadashish** [ethereum/mist#401]
![screen shot 2016-03-21 at 1 55 06 pm](https://cloud.githubusercontent.com/assets/17846266/13913430/a6568d50-ef6c-11e5-911f-932ee61b55dc.png)

I checked it with pyethrecover and my password seems to be correct as I get the following log from pyethrecover:

> JoblibPasswordFoundException: JoblibPasswordFoundException
> 
> 
> 
> PasswordFoundException: 
> 
> Your seed is:
> 

^ Only pasted the relevant lines here

I am using 0.5.2 on OS X 10.11.3

**Comment by hiddentao** [comment]
Yep, this is a known issue with a fix on its way, see #182

**Comment by frozeman** [comment]
I will close that as its a duplicate
