### ISSUE TITLE
Account creation doesn't succeed and doesn't terminate

### ISSUE THREAD

**Issue by fera0013** [ethereum/mist#4018]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.11.0`
OS & Version: windows 10
Node version: `geth 1.8.12`
Number of blocks synchronized: 0
```

I start geth on my private network and try to create an account, but the account is never created and the process does not seem to terminate:

![mistaccount](https://user-images.githubusercontent.com/1273515/43033452-19b5e554-8ccb-11e8-9d16-39e045737481.JPG)

The "Generating account" dialog stays there for hours until I kill the process. Repeated trials don't change anything.

Here are the logs: 

[_logs.zip](https://github.com/ethereum/mist/files/2215982/_logs.zip)

**Comment by Kgonla** [comment]
Same problem for me, also half of the time the program do not start, just white screen with circle (Loading)
Windows Server 2008 R2

**Comment by fiddybux** [comment]
I have this issue too. Hanging on Create Account pop-up, doesn't terminate.

**Comment by magick93** [comment]
I have the same issue too, on Ubuntu.

![screenshot from 2018-07-24 15-22-19](https://user-images.githubusercontent.com/2173213/43114937-7cf44a66-8f55-11e8-973e-975918f273e9.png)

**Comment by evertonfraga** [comment]
Hi all, sorry to hear that. we’ve released an update that aims to fix that. v0.11.1. 

Thanks for reporting!
