### ISSUE TITLE
node crashed

### ISSUE THREAD

**Issue by melie** [ethereum/mist#402]
Node type: geth
Network: main
Platform: darwin

...s/andreaskanakis1/Library/Ethereum/chaindata
I0321 10:27:06.700927   16714 database.go:71] Alloted 78MB cache to /Users/andreaskanakis1/Library/Ethereum/dapp
I0321 10:27:06.721739   16714 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0321 10:27:06.723071   16714 backend.go:362] Blockchain DB Version: 3
I0321 10:27:06.728225   16714 blockchain.go:214] Last header: #1177392 [06bab8b4…] TD=9916381401492854120
I0321 10:27:06.728260   16714 blockchain.go:215] Last block: #1177392 [06bab8b4…] TD=9916381401492854120
I0321 10:27:06.728365   16714 blockchain.go:216] Fast block: #1177392 [06bab8b4…] TD=9916381401492854120
I0321 10:27:06.730163   16714 handler.go:92] blockchain not empty, fast sync disabled
I0321 10:27:06.739099   16714 cmd.go:114] Starting Geth/v1.3.5/darwin/go1.5.1
I0321 10:27:06.740386   16714 server.go:311] Starting Server
Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use (possibly another instance of geth is using the same port)

**Comment by frozeman** [comment]
Open up the "activity" app and search for geth and quit it. Then restart.
