### ISSUE TITLE
Create an Account hangs (no response after 3 hours)

### ISSUE THREAD

**Issue by rnwebb** [ethereum/mist#4025]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.11.0`
OS & Version: windows 10 64-bit pro
Node version: `<empty>`
Number of blocks synchronized: 0
```

Steps I followed:
1 downloaded Ethereum Wallet
2.  Double-clicked on the .zip file.  this opened the files
3.  Ran Ethereum Wallet.exe, which was the only .exe file in the package.  There was only a readme.md which I could not read.  Nothing has been installed (ie like a normal app) on my computer, which is wierd.
4.  clicked on 'Add account' which was the first and most obvious action to take
5.  No action after 3 hours

Please advise.

**Comment by evertonfraga** [comment]
Hi, sorry to hear that. we’ve released an update that fixed such interface bug. 

Would you please try v0.11.1?

**Comment by rnwebb** [comment]
Hi Evertonfraga,
thanks for this.  I've installed v0.11.1 from the ethereum wallet site, from the page with other versions.  It downloaded and installed successfully.  I pressed the button to create an account using the same password as before and it's hanging again.

What info can I give you?

Regards, Robyn

**Comment by evertonfraga** [comment]
Go ethereum version (Develop > ethereum node.> Geth x.x.x)

Thank you


--
Everton Fraga

**Comment by rnwebb** [comment]
The Ethereum Node is empty

**Comment by rnwebb** [comment]
thanks, the status is now 'remote' and it created the account.  The node is still <empty>, but its working so I'm leaving as it is
