### ISSUE TITLE
README.md: Deployment linux-instructions are buggy

### ISSUE THREAD

**Issue by leberknecht** [ethereum/mist#4027]
- [ X] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.
I mentioned it but apparently there was no one in the channel to pick this up 

```
Version:

current README.md on master
```

The current readme states this for deployment ( https://github.com/ethereum/mist/blob/develop/README.md#linux ):
```
Linux
$ brew install gnu-tar libicns graphicsmagick xz
```
If we replace `brew` with apt-get here, it still gives
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gnu-tar
E: Unable to locate package libicns
E: Unable to locate package xz
```

**Comment by evertonfraga** [comment]
The proper `apt` packages are:
```
icnsutils
graphicsmagick
xz-utils
gcc
g++-multilib
```

I fixed the documentation as well. Thanks for reporting!
