### ISSUE TITLE
Deploy new contract

### ISSUE THREAD

**Issue by softevolutionpro** [ethereum/mist#4036]
Hello! We have a problem to DEPLOY NEW CONTRACT, we use valid code but always loading, not finish; we´ve tried of different computers but we can finish contact, how can we solve it? thanks

**Comment by evertonfraga** [comment]
Hi @softevolutionpro, would you please send a screenshot, along with OS and Mist version?

Thank you

**Comment by softevolutionpro** [comment]
![Uploading error Ethereum.jpg…]()
-Version 0.11.00 - License GPL-3.0
-Windows 10 Pro

Thank you!

**Comment by evertonfraga** [comment]
Hi @softevolutionpro unfortunately, it seems your image hasn't finished uploading. 

But have you tried version 0.11.1 instead?

**Comment by softevolutionpro** [comment]
![error ethereum](https://user-images.githubusercontent.com/37624847/43453245-e464ac54-94b9-11e8-9596-2668884a6409.jpg)

I attached the image again.

when I want to update it tells me that I'm running the latest version

![update](https://user-images.githubusercontent.com/37624847/43453600-c5a2bef4-94ba-11e8-9ecf-9de475a5e797.jpg)


thank you!

**Comment by fredbuluku** [comment]
Eve what do you want me to contribute with here?

Regards,

Fred.

**Comment by fredbuluku** [comment]
Deployment of new contracts please share with me instructions how you want
me to help then I will assist.

Regards,

Fred.

**Comment by softevolutionpro** [comment]
Hello, I am trying to create an account but it does not generate it, It stays in the message generating account and it does not pass from there

**Comment by softevolutionpro** [comment]
I already solved the problem, thanks

**Comment by softevolutionpro** [comment]
Where can I get a code for a smart contract and to create tokens that do not have errors

**Comment by evertonfraga** [comment]
Hi @softevolutionpro, to solve your original issue, I'd like to have the console output of the wallet.

`Develop > Toggle developer tools > Ethereum Wallet`

Then change to console tab and paste here the relevant data.

**Comment by evertonfraga** [comment]
Hi @softevolutionpro, that bug was fixed in #4052. It will be shipped on the next version, 0.12.0.
