### ISSUE TITLE
CODE TO CREATE AN ICO (TOKENS)

### ISSUE THREAD

**Issue by softevolutionpro** [ethereum/mist#4042]
I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

Where can I find a code to start an ICO, offering Tokens, Pre-sale and final sale to distribute a % of the profits among the buyers of tokens

**Comment by evertonfraga** [comment]
This does not belong to the scope of this repository. I can't officially recommend you anything. But be extremely careful if you just copy-and-paste code from other projects.

Cheers.
