### ISSUE TITLE
log: result too large

### ISSUE THREAD

**Issue by Canalytic** [ethereum/mist#405]
Node type: geth
Network: test
Platform: darwin

...I0321 13:18:47.863108   72997 database.go:71] Alloted 16MB cache to /Users/Library/Ethereum/testnet/chaindata
Fatal: blockchain db err: read /Users/Library/Ethereum/testnet/chaindata/020797.log: result too large

Please help I can't start mist

**Comment by frozeman** [comment]
@karalabe 

@Canalytic the easiest is to remove the `~/Library/Ethereum` folder. But make sure to backup before the `~/Library/Ethereum/keystore` folder!
The it should resent the chain

**Comment by Canalytic** [comment]
Thanks.  Do you know if it's very easy to move the keystore folder to another system?  I had this wallet on Mac but want to move it to Linux build.

**Comment by Canalytic** [comment]
So I deleted the `~/Library/Ethereum` folder and restarted the client, have fully loaded the blockchain.  Now I want to close it and add the replace the new keystore folder with the old keystore folder, but the problem is that I not longer have a /Library/Ethereum directory.

**Comment by Canalytic** [comment]
Hi, disregard previous message, I found it.

**Comment by Canalytic** [comment]
So, I switched the keystore folder like you said, but it didn't restore my wallet.  I am only working on the testnet so its not a big deal, but I also am feeling less confident to switch over to the main blockchain with mist having these problems.  Do you know of any solution?

**Comment by luclu** [comment]
@Canalytic as frozeman pointed out - and you seem to have figured out - the `keystore`-folder contains the keys.
The error you encountered might be unsettling, but is harmless.
Just remember to backup your keys - as this is best practice anyways.

Hope you keep up your exploration mind-set and tried the newer versions as bugs tend to get ironed out approaching stable releases.

**Comment by luclu** [comment]
Assuming this has been solved, I will close for inactivity.
