### ISSUE TITLE
hard to create new account in ethereum

### ISSUE THREAD

**Issue by wangmorgan** [ethereum/mist#4050]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
Duplicate of #4012. 

please follow from here: https://github.com/ethereum/mist/issues/4012#issuecomment-414512125
