### ISSUE TITLE
Etherum wallet  v 0.11.1 doesn't connect and open 

### ISSUE THREAD

**Issue by l4ff** [ethereum/mist#4066]
Fixed now thx

**Comment by fredbuluku** [comment]
Please inform the support team about the problem they will be able to
advise.

Regards,

Fred.

**Comment by l4ff** [comment]
where?

**Comment by fredbuluku** [comment]
In the system we have no support team?then share you problem in the
telegram someone will advise you.

**Comment by l4ff** [comment]
is there any channel i can ask ?

**Comment by l4ff** [comment]
It doesn't seem to have any website or support team for the wallet

**Comment by dannylee71** [comment]
Wallet id:b4cb75be-8248-4d31-8397-7d291ce4e9ca

**Comment by evertonfraga** [comment]
Hi @l4ff,

1. click on the browse tab
<img width="73" alt="screen shot 2018-08-20 at 8 55 50 pm" src="https://user-images.githubusercontent.com/47108/44372694-7d21b200-a4bb-11e8-8db6-15d80b63b519.png">

2. go to `https://wallet.ethereum.org`
<img width="663" alt="screen shot 2018-08-20 at 8 56 08 pm" src="https://user-images.githubusercontent.com/47108/44372699-8743b080-a4bb-11e8-89bf-de4185540d58.png">

please let me know if you managed to recover those data!
