### ISSUE TITLE
i cannot see solo network

### ISSUE THREAD

**Issue by joohyeung** [ethereum/mist#4069]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.11.1`
OS & Version: windows/
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

![solonetwork](https://user-images.githubusercontent.com/41462311/44025621-90fdffb2-9f2b-11e8-9d98-02280d99814a.png)

Why can't I see a solo network?

**Comment by evertonfraga** [comment]
We've removed that option recently, in order to prevent mistakes from onboarding users.
