### ISSUE TITLE
Create account on splash-screen

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#407]
More kind of a funny one..
Creating new accounts / pressing ⌘N during sync-splash works.
Please don't mind this issue if intended.

OSX, Wallet @ latest official

![bildschirmfoto 2016-03-21 um 21 51 03 kopie](https://cloud.githubusercontent.com/assets/10135872/13933923/c150a6ca-efaf-11e5-829a-47bcedd4fbc9.jpg)

**Comment by frozeman** [comment]
This is more of an side effect, of the menu already beeing present. I don't think its a problem tho.. Thanks for pointing this out.

I will leave this issue open for discussion.
