### ISSUE TITLE
Personal_signTransaction does not exist

### ISSUE THREAD

**Issue by toffi947** [ethereum/mist#4071]
![grafik](https://user-images.githubusercontent.com/11016424/44050442-38a5ea4e-9f37-11e8-8698-1084ed2efe6a.png)

When i send Ether to a another wallet this error pop up.

Can anyone help?

**Comment by evertonfraga** [comment]
Hello, 

that method was introduced not too long ago in Geth (go-ethereum)
Please check the Geth version your system is using (`Develop > Ethereum Node > Geth (x.x.x)`)

If it's below 1.8.11, i'd recommend updating it.

**Comment by toffi947** [comment]
Thanks! The Update to 1.8 was the solution.
