### ISSUE TITLE
Wallet contract does not show ETH balance sent

### ISSUE THREAD

**Issue by msam4444** [ethereum/mist#408]
I sent some ether to my contract wallet. I see in Etherscan ether is added but it doesn't show in Mist.  I think it's out of gas. how do I add gas to my contract?  related question: does keeping a balance in a contract wallet consume gas? (maybe not a mist issue itself, but I wish there was a way it would just warn me it's out of gas and I could add gas)

Contract 0x76ba...
 Warning! An error occured during contract execution. Out Of Gas  ?

  Gas:	21000
  Gas Price:	0.00000005 Ether
  Gas Used By Transaction:	21000
  Actual Tx Cost/Fee:	0.00105 Ether
  Cumulative Gas Used:	42000
  Nonce:	6
  Input Data:	0x

**Comment by frozeman** [comment]
The transaction sending the ether needs to provide more gas when sending.. you've send 21k gas, you should send at least 50k. The transaction was reverted and should still be at the origin address.

**Comment by msam4444** [comment]
I sent this from ethereumwallet.com. It's a very basic wallet and doesn't have any options for changing gas.  It doesn't seem the transaction is reverted as a I don't see it my ethereumwallet.  Is there any way to get my ether? thanks

**Comment by frozeman** [comment]
The ethereumwallet guys are working on an update. Though they should show your amount, if it came back. please check your address in blocke explorers like etherscan.io

**Comment by msam4444** [comment]
Yes, it's there. Thanks for your help

On Wed, Mar 23, 2016 at 7:50 AM, Fabian Vogelsteller <
notifications@github.com> wrote:

> The ethereumwallet guys are working on an update. Though they should show
> your amount, if it came back. please check your address in blocke explorers
> like etherscan.io
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/mist/issues/408#issuecomment-200315023>
>



-- 
A message from the Elohim
www.rael.org
www.proswastika.org
