### ISSUE TITLE
Mist loses peers after about 1 hour connected ALWAYS - and never gets them back

### ISSUE THREAD

**Issue by BL186** [ethereum/mist#409]
Title says all, Mist gets peers but after having it opened for about 1 hour all peers are lost and Mist never gets a single one back.

Happened already multiple times, I have to restart the client to get peers again.

Using Windows 10 x64

**Comment by frozeman** [comment]
@fjl

**Comment by luclu** [comment]
@BL186 please update to version 0.7.4 and check if you are still affected. As `geth` 1.4.4 incorporated many improvements in this regard your issue is most likely fixed. I will close for now, but feel free to come back and discuss a solution.
