### ISSUE TITLE
When restarting geth, mist's ether counting is not working.

### ISSUE THREAD

**Issue by jtjisgod** [ethereum/mist#4097]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.11.1`
OS & Version: ubuntu 17.10 LTS
Node version: `geth 1.8.12-stable-37685930`
Number of blocks synchronized: 0
```

**Comment by marcgarreau** [comment]
Can you explain further? Are you running your own node before starting Mist? Any reason you're still on 1.8.12? The account balance in the wallet is not updating? Did you make a recent transaction, and has it had many confirmations?

**Comment by tomnyboi81** [comment]
Oh please help me, i been trying to get the eth thing to work. I see in my
etherscan account have alot of money in it. I want to received it to my
main wallet...please help

**Comment by tomnyboi81** [comment]
I would even pay you for your time

**Comment by jtjisgod** [comment]
@marcgarreau 
I installed geth using apt-get. So geth's version is not lastest.
and, i'm developing Dapp on my ethereum test-net. So, mining is very fast and confirm count is over 100.


Start geth -> start mist -> mining on geth -> exit geth -> start geth -> mining on geth

then, Only transactions are active ( i can send, recevie and contract ), but  updating number of my wallet is freezing.

So i confused.
is it my problem?

**Comment by marcgarreau** [comment]
@tomnyboi81 you can use any wallet service to access your funds. If you're having trouble with Mist, try MyCrypto and access your wallet by using the keystore file + password, or your private key. That make sense?

@jtjisgod does Mist have the correct value if you restart it after restarting geth? It's possible that the wallet just does not know to poll for an updated value - we have not optimized the experience for private network mining.

**Comment by jtjisgod** [comment]
Yes, It is correct when restart Mist.
And you are right, You don't have to optimizing Mist at private network.. I agree.
