### ISSUE TITLE
Install Centos 7

### ISSUE THREAD

**Issue by PauloBoaventura** [ethereum/mist#4102]
- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

I would like to know how to install in #CENTOS7, can someone send the commands?
```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by evertonfraga** [comment]
Olá Paulo, tudo bem?

A gente não publica este projeto no `yum`. Você pode fazer download dos arquivos `linux(32|64).zip`.

**Comment by PauloBoaventura** [comment]
**PT/BR**
sabe dizer como é feita? Pode informar um tutorial básico?
Precisa instalar dependencias?

**ENG** 
Can you tell me how it's done? Can you tell us a basic tutorial?
Need to install dependences?

**Comment by evertonfraga** [comment]
Hi, it's pretty straightforward: you download, unzip and run.
