### ISSUE TITLE
Ethereum Wallet : scandaleux d'inefficience

### ISSUE THREAD

**Issue by PascalDuval** [ethereum/mist#4105]
Alors je résume 
Ethereum Wallet ne ne synchronise pas bien avec le réseau
Du coup on ne voit pas ce qu'on a dans son portefeuille
Mais on fait comme si et on essaie d'envoyer, transférer des ethers le plus vite hors de cette interface où rien ne marche  (on n'est pas sûr que le FROM soit bien renseigné par l'adresse par défaut et on ne peut rien y saisir) sachant que pour elle on est à 0 !
Alors forcément tu appuies sur le bouton send et bien évidemment rien ne se passe !!
Ca fait 10 mpis que ça dure !

Je demande d'urgence aux développeurs de cette daube et à ethereum France qui prescrivent cette merde comment je transfère hors de la wallet tous mes ethers !!
Ca fait 10 moi que j'attends une version valable.

Comment je fais pour ne pas être captif de cette wallet puisqu'aucune fonction de transfert ne marche ?

PS j'ai des ethers sur  0x314769Ba7AbA87Bd31ada0910294519600c59296 (vous pouvez vérifier). Proposez une solution correcte, svp de secours. Je ne veux plus utiliser cette appli.

- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by marcgarreau** [comment]
Apologies, there are no French speakers on the team, but Google Translate has made the point clear enough. It appears you've had success moving your Ether, so I'm going to close the issue.
