### ISSUE TITLE
 Identical names of contracts and functions. Deprecated?

### ISSUE THREAD

**Issue by Soros777** [ethereum/mist#4112]
I copied the contract code from the site https://github.com/chrisdannen/Introducing-Ethereum-and-Solidity/blob/master/mytoken.sol
Pasted the code into the browser Mist on the "contracts" tab => deploy new contract. The browser gave an error: "Defining constructors as functions with the same name as the contract is deprecated".![2018-10-07 14 33 35](https://user-images.githubusercontent.com/43518259/46581885-fc594e00-ca47-11e8-82b3-0b79f20a6a33.png)
Is this a critical error, or can it be circumvented simply by replacing the contract name with MyToken1?
Will the program work correctly if the name of the function in the 15th line (perhaps the main function in the code) differs from the name of the contract?

**Comment by Soros777** [comment]
After replacing the contract name for MyToken1, a drop-down list with the name of this contract appeared in the right panel.
![2018-10-07 15 56 33](https://user-images.githubusercontent.com/43518259/46582196-f6fe0280-ca4b-11e8-8010-abfb75102351.png)
When I select it, no additional fields appear, as in the picture, as it should have been, judging from Chris Dannen's book, “Represent Ethereum and Solidity.” 
![2018-10-07 15 58 45](https://user-images.githubusercontent.com/43518259/46582201-fcf3e380-ca4b-11e8-8a00-79f810581fda.png)
Can any body help me?

**Comment by evertonfraga** [comment]
Hi @Soros777, Solidity language has evolved and now constructor functions are declared as `constructor() ...`.

That said, you'd need to change your code to something like:

```
contract MyToken {
  ...

  constructor(uint256 _supply, string _name, string _symbol, uint8 _decimals) public {
    ...
  }

  ...
}
```

**Comment by evertonfraga** [comment]
Please refer to the language reference: https://solidity.readthedocs.io/en/v0.4.25/contracts.html?highlight=constructor
