### ISSUE TITLE
Synchronization stops by itself

### ISSUE THREAD

**Issue by Soros777** [ethereum/mist#4113]
Why does synchronization stop by itself after a short while of the Mist browser?
Version Mist
: `0-11-1`
OS & Version: windows 7, 32 bit
![2018-10-07 17 55 52](https://user-images.githubusercontent.com/43518259/46583194-73e4a880-ca5b-11e8-9e51-59ec9ac30334.png)

It stops arbitrarily. Sometimes it helps to restart the Mist browser and/or change the synchronization method. Sometimes even this does not help.

**Comment by marcgarreau** [comment]
Sorry for the headache. The place to address geth syncing questions is with the geth team. Check out their issues [here](https://github.com/ethereum/go-ethereum/issues).
