### ISSUE TITLE
Mist should not alter key files

### ISSUE THREAD

**Issue by 3esmit** [ethereum/mist#4118]
I opened Mist by placing a key file inside of keystroke folder, which by mistake I moved (instead of copy), and now the Key is not being accepted in other clients (as MEW). 
I would expect that my keys are untouched by Mist, and should be "readonly" by Mist.

Any reason for altering the file structure?

**Comment by 3esmit** [comment]
Seems like was changed by other process, not Mist.

**Comment by evertonfraga** [comment]
Hi Ricardo @3esmit, hope you are good.

This is a really important thing for us. We've had reports in the past saying that their private keys were altered, and I can ensure no file operations are done on existing keystores. And Geth only does that kind of thing when explicitly told to do so. 

Do you have any clue to enlighten us?

**Comment by 3esmit** [comment]
I opened the key file on vscode (which saves automatically) to see what address was that, and I accidentally typed an additional character at end of file.
