### ISSUE TITLE
Wallet used in Testnet (Morden), does not show if Main Network is chosen

### ISSUE THREAD

**Issue by Jelle12** [ethereum/mist#413]
I bought some Ether on Poloniex and sent it to my address of my main account in testnet (Morden). The transaction showed competed successfully, but I cannot receive Ether because my main account in testnet is not visible if main network is chosen. How can I show the wallet of testnet in Main Network? Thanks, Jelle

**Comment by frozeman** [comment]
You need to copy the keystore files from `%APPDATA%/Romaing/Ethereum/testnet/keystore/myfile...` to `%APPDATA%/Romaing/Ethereum/keystore/myfile...`
