### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by housemobile** [ethereum/mist#414]
From reddit:
https://www.reddit.com/r/ethereum/comments/4bo0eg/ethereum_wallet_mistake/

It says:

'USE THE MAIN NETWORK You'll need **to** some Ether in order to create....' etc

Bold not needed.

**Comment by luclu** [comment]
fixed in #412.

**Comment by luclu** [comment]
pinging @alexvandesande

**Comment by alexvandesande** [comment]
Text now reads: "You’ll need some Ether in order to create and execute contracts. Don't worry we'll help you get some..."
