### ISSUE TITLE
ETH deposit not arrived in my ETH wallet

### ISSUE THREAD

**Issue by airrpullz85** [ethereum/mist#415]
Node type: geth
OS: windows
Network type: main
Mist version: 1.3.5

Hi @frozeman ,

On the 21/03/2016 I've make 2 two deposit to my ETH wallet address per below:
0x97292880ec2866edf593d3bfd208aac6c265f7c8

But both deposit I can't see in my ETH wallet balance.

![ether wallet_airrpullz85](https://cloud.githubusercontent.com/assets/17997525/14008224/6835b146-f1b9-11e5-8720-1c79c44f8aa5.jpg)

I've contact ShapeShift for check the transaction and from Ether network it shows the transaction are successful. You can refer below link for more details:

http://etherscan.io/address/0x97292880Ec2866eDf593D3Bfd208Aac6C265f7C8

I don't know why this happen.

Please have a look ASAP.

Seen your soonest feedback.

**Comment by JRogiest** [comment]
You transaction is correct as shown on etherscan. The reason you are not seeing it on your Mist wallet is because you need to sync your wallet. It takes a couple of days depending on your d/l speed. Keep your mist wallet on and see how many nodes your are connecting to and if the blocks are increasing.

**Comment by airrpullz85** [comment]
Hi @JRogiest ,

Thanks for the feedback.
I'll try on your advise and see its work or not.

How to check on " how many nodes your are connecting to and if the blocks are increasing " ?
Seen your soonest feedback.

**Comment by frozeman** [comment]
On the top you see the connection and block symbol, with 0, as long as youre not synced you can't see your tx, as @JRogiest pointed out
