### ISSUE TITLE
how to connect private ipc with the electron!!!

### ISSUE THREAD

**Issue by m3shine** [ethereum/mist#4153]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by PhilippLgh** [comment]
see https://github.com/ethereum/mist-shell/issues/7 for progress on geth<->electron IPC fixes
