### ISSUE TITLE
Wrong password!? How's that?

### ISSUE THREAD

**Issue by notictech** [ethereum/mist#4154]
I've installed latest version of etherium wallet (0.11.1), placed my old keystore file into ~/.ethereum/keystore, the wallet shows my real ballance, looks good. BUT, when I try to send a fund to another address, the wallet says '**Wrong password**'. What's going on? I'm sure that 1) my keystore is correct 100% 2) my **password is correct 100%.** Last time I used version 0.8 about year ago and it worked. Please HELP!

P.S.
1) I tried to downgrade back to 0.8 - it is not able to connect to the network
2) I tried to import this keystore into MyEtherWallet - the same error 'Wrong password' 
3) I noticed that when I create a new account using this password the wallet creates another address, not mine
4) My password was generated by a password manager and contains a-zA-Z0-9, #$@= etc
5) I tried to use Ubuntu 14.04 x64, Ubuntu 18.04 x64, Windows 10
6) I also tried to run personal.unlockAccount('<address>') in geth console:

_err="could not decrypt key with given passphrase"
Error: could not decrypt key with given passphrase_

**Comment by notictech** [comment]
Does anybody read the ticket?

**Comment by notictech** [comment]
It looks like the problem on a backend because I have the same issue with different clients. But I'm sure that my password is correct

**Comment by PhilippLgh** [comment]
Sorry but it looks like you are trying ti enter a wrong password. Exclude all possibilities of typos (different keyboard layout?), copy paste errors (type the pwd and don't copy) and try to think about different password that could be relevant. Make sure you are working on the correct files. So far whenever one of these "i'm 100% sure it is my password and it is not working anymore" cases was resolved it was a different password. So far we don't know any bugs and can't help without reproducable steps.
