### ISSUE TITLE
Installing the Ethereum 0.11.1 wallet to another drive then C problem: you can't backup your accounts anymore

### ISSUE THREAD

**Issue by Vertimodo** [ethereum/mist#4161]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.11.1`
OS & Version: windows 10 pro
Node version: `geth 0.0.0`
Number of blocks synchronized: 6943731
```
When you install the Ethereum wallet to another drive then C (to drive X) and when you also change the C appdata folder to another location on that X hdd drive, by adding this to the shortcut: "X:\Ethereum-Wallet\Ethereum Wallet.exe" --node-datadir="X:\Users\username\AppData\Roaming\Ethereum"  you can no longer backup your accounts when you go to "file-> backup-> accounts", as it doesn't open the needed folder to backup your keystore file.

Only the "backup-> application data"  option is functional and opens the application data folder. When you click accounts, the folder is not opened.
The keystore folder does exist in the new location X:\Users\username\AppData\Roaming\Ethereum\keystore however, but the wallet does not open it. 

I think this is a serious bug that needs a fix!
<!--

**Comment by Vertimodo** [comment]
Does anyone know a fix for this? I have seen many people posting problems VERY similar to this, yet no one posts solutions for the problem. It seems to be happening to a LOT of people. If they can't backup their keystore file, disaster is bound to happen for me and a lot of other Ethereum holders.

**Comment by PhilippLgh** [comment]
Please see ethereum/mist-shell#7 for progress on this issue
