### ISSUE TITLE
amolha7bk@gmail.com

### ISSUE THREAD

**Issue by amolha7bk** [ethereum/mist#4163]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by amolha7bk** [comment]
amolha7bk@gmail.com

**Comment by Muhammadramshan** [comment]
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
