### ISSUE TITLE
--datadir option not working

### ISSUE THREAD

**Issue by hyunsooda** [ethereum/mist#4164]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: Most recent
OS & Version:  OSX
Node version: 1.8.19-stable
Number of blocks synchronized: 0
```

Hello, I'm korean student that studying ethereum.
I know that user can set data directory using --datadir option. but my environment never working.
When I set the --datadir option, Ethereum Wallet seems to be automatically find ~/Library/Ethereum directory.
So, I have changed the contents what I have made in geth console into the ~/Library/Ethereum then Ethereum Wallet shows right accounts information but not appeard information about balance which each account has.

Can you inform how to solve this problem?

Thank you.

**Comment by Vertimodo** [comment]
#4161

**Comment by PhilippLgh** [comment]
Please see ethereum/mist-shell#7 for progress on this issue
