### ISSUE TITLE
I CAN NOT INSTALL EHT WALLET, PLEASE HELP!

### ISSUE THREAD

**Issue by Protey** [ethereum/mist#417]
Node type: geth/eth
OS: Windows 7 x64
Network type: main/test
Mist version: Wallet 0.5.2 (Beta 10)

I can not run the installation of the purse on Windows 7 x64!
nothing happens when you start the installation!
If you run the installation through the cmd.exe, here gives the following message:
C:\Ethereum-Wallet-win64-0-5-1>Ethereum-Wallet.exe
C:\Ethereum-Wallet-win64-0-5-1>CONNECT to IPC PATH: \.\pipe\geth.ipc
In Task Manager can be seen that the program is started, with a description of the electron, and at once closes

- Screenshots 
![eth1](https://cloud.githubusercontent.com/assets/6497045/14019270/c03f5272-f1f3-11e5-9312-73a897cf6282.jpg)
- Log files windows: %APPDATA%/Roaming/Mist/node.log - **havent file node.log in the folder Mist**

**Comment by luclu** [comment]
@Protey could you kindly try the latest version 0.7.3 and report if this behaviour still persists?

**Comment by Protey** [comment]
@luclu Yes, a you are were in no hurry with help...
everything worked after reinstalling windows, i do not know that there were, and what was the problem

**Comment by luclu** [comment]
Great to here it's working again!
Please close this issue.
