### ISSUE TITLE
can somebody fix this wallet once and for all?

### ISSUE THREAD

**Issue by marksaitis** [ethereum/mist#4179]
Latest ethereum wallet on debian doesn't sync. Been happening for months. In all sync modes except "full". Can somebody sort this out one time or not? A billion dollar project and still issues with basic wallet functionality.

**Comment by PhilippLgh** [comment]
this application ins being re-written. please see [https://github.com/ethereum/mist-ui](https://github.com/ethereum/mist-ui)
