### ISSUE TITLE
Mist cache issue - can't clear browser cache

### ISSUE THREAD

**Issue by BL186** [ethereum/mist#418]
I can't find how to clear cache in Mist, there is a website with updates, when I open with Chrome I see the up to date page, with Mist I still see the old page, I click to reload, remains the same.

Restart doesn't help also...

There should be an option to clear the browser cache.

is there a way to clear the cache manually in the meantime?

**Comment by luclu** [comment]
Try out `ctrl+F5` (on windows and linux).

**Comment by bellaj** [comment]
The Mist DevTools (like for chrome) can disable the cache.

Right-click and Inspect Element to open the DevTools. Now click Network in the toolbar. Finally, check the Disable cache checkbox at the top.

![mist](https://cloud.githubusercontent.com/assets/16008163/17673623/e929c752-6319-11e6-976f-f3270c6d5985.png)
