### ISSUE TITLE
Submissions 

### ISSUE THREAD

**Issue by wonkafactoryaint** [ethereum/mist#4189]
- [ ] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by marcgarreau** [comment]
👋 If you've found bug, please provide thorough details on how to reproduce it.
