### ISSUE TITLE
Hacked or System Error ?

### ISSUE THREAD

**Issue by Angeee** [ethereum/mist#4196]
hi can anyone help me first i have an issue syncing ethereum wallet and now after looking up my wallet on etherscan i can see 4.5 ether has been sent out to another address (not mine or by me) and that address has only made one transaction that is still holding the same amount of ether so if it was a hack you would think it would be gone ? 

![Capture](https://user-images.githubusercontent.com/17367687/54523608-005ca500-49c4-11e9-8841-fa529c49bc16.PNG)
![Capture2](https://user-images.githubusercontent.com/17367687/54523628-0bafd080-49c4-11e9-88cc-de11703cd28e.PNG)

- [x] I've asked for help in the [Mist Gitter](http://gitter.im/ethereum/mist) before filing this issue.

```
Version: `0.0.0`
OS & Version: windows/linux/osx
Node version: `geth 0.0.0`
Number of blocks synchronized: 0
```

**Comment by marcgarreau** [comment]
Syncing issues occasionally occur, but are not related to your wallet being compromised. If anyone has access to your keys, they have complete control of your wallet. I would recommend creating a new wallet and moving any remaining value off of this wallet if you believe its been compromised.
