### ISSUE TITLE
possibly another instance of geth is using the same port?

### ISSUE THREAD

**Issue by cjdaniel316** [ethereum/mist#421]
```
I0326 16:29:24.134309    4320 database.go:71] Alloted 16MB cache to /Users/Stix/Library/Ethereum/chaindata
I0326 16:29:24.193876    4320 database.go:71] Alloted 16MB cache to /Users/Stix/Library/Ethereum/dapp
I0326 16:29:24.201173    4320 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0326 16:29:24.201984    4320 backend.go:362] Blockchain DB Version: 3
I0326 16:29:24.205408    4320 blockchain.go:214] Last header: #1182184 [034fc8b8…] TD=10006957765000108834
I0326 16:29:24.205437    4320 blockchain.go:215] Last block: #1182184 [034fc8b8…] TD=10006957765000108834
I0326 16:29:24.205454    4320 blockchain.go:216] Fast block: #1182184 [034fc8b8…] TD=10006957765000108834
I0326 16:29:24.215288    4320 cmd.go:114] Starting Geth/v1.3.5/darwin/go1.6
I0326 16:29:24.215451    4320 server.go:311] Starting Server
Fatal: Error starting Ethereum: listen udp :30303: bind: address already in use (possibly another instance of geth is using the same port)
```

**Comment by luclu** [comment]
Hi @cjdaniel316 does this problem still occur? 
This is most likely a error causes by another open instance. 
In case of doubt a reboot should solve this issue.

Please give me a small pingback!

**Comment by frozeman** [comment]
Please check your task manager/activity tab to check if geth is already running, it might have not shut down properly last time.

**Comment by luclu** [comment]
Seams to be realted to this geth issue https://github.com/ethereum/go-ethereum/issues/1271

**Comment by ekkis** [comment]
I'm running OSX 10.11.4 (El Capitan) with 0.7.3 of the wallet and have this issue.  I've looked in the process list for "geth" or "mint" or for anything I can recognize but I don't see anything running, yet, the wallet won't start

**Comment by luclu** [comment]
Make sure to try version 0.7.4 as this comes bundled with `geth` 1.4.4 which contains a considerable amount of improvements. Try to restart your Mac beforehand.

**Comment by luclu** [comment]
Closed as of no feedback.
