### ISSUE TITLE
newbie "No Ethereum node binary found! Please start one manually."

### ISSUE THREAD

**Issue by brentpeluso** [ethereum/mist#422]
windows 32bit

Hi I am a complete newbie when it comes to this. I get this message what do I do ?

![screenshot 2016-03-26 21 47 20](https://cloud.githubusercontent.com/assets/7537688/14063754/77045350-f39c-11e5-8347-d3a2758d6e31.png)

Thanks

**Comment by hiddentao** [comment]
Ah I'm fairly sure this is because we don't build binaries for 32-bit windows - @frozeman do we support win32?

**Comment by luclu** [comment]
@brentpeluso there are 32-bit binaries since version 0.7.2
https://github.com/ethereum/mist/releases

Are those resolving the issue?

**Comment by andytudhope** [comment]
I am trying to deploy a wallet on a 32-bit windows machine (ugghhh). Still get the same issue with the 0.7.2 release. Pretty sure there isn't a version of geth that works on 32-bit Win machines, so was surprised there was a wallet for them. Doesn't want to play nicely though, exact same issue as above.

**Comment by luclu** [comment]
@andytudhope Which download link did you try?

**Comment by andytudhope** [comment]
@luclu the same you list above (https://github.com/ethereum/mist/releases)

And then the `Ethereum-Wallet-win32-0-7-2.zip` link.

**Comment by luclu** [comment]
@brentpeluso, @andytudhope sorry guys, I didn't meant to leave you behind.
Currently there is no stable support for windows 32bit. Only experimental builds.
The Ethereum-Wallet 0.7.2 does not come bundle with a node, so you will need to download geth from [here](https://github.com/ethereum/go-ethereum/releases). Use version 1.4.1 (experimental Release Candidate).
There is not yet any official 32bit-binary in the 1.4. line.

**Comment by ifateh** [comment]
hi, i am new to this and have 32bit operating system win 10. I have downloaded and unzip it having this error .
"No Ethereum node binary found! Please start one manually."
kindly help me with this

**Comment by hiddentao** [comment]
Did you unzip it to a separate folder or just double-click the ZIP file? You will need to unzip everything into a separate folder and then try running the executable.

-- 
Ramesh Nair

Director
HiddenTao Ltd (UK company no. 6807289)

http://hiddentao.com
https://github.com/hiddentao
https://www.linkedin.com/in/hiddentao


On 13 May 2016 at 18:17:26, ifateh (notifications@github.com) wrote:

hi, i am new to this and have 32bit operating system win 10. I have downloaded and unzip it having this error .
"No Ethereum node binary found! Please start one manually."
kindly help me with this

**Comment by ifateh** [comment]
i have unzip it in a separate folder

**Comment by alexvandesande** [comment]
@ifateh your wallet version is quite old, you should release a new one. But anyway, the ones in win32 don;t come with a node on it, you have to install it following the instructions at ethereum.org/cli
