### ISSUE TITLE
Warning! Error encountered during contract execution [Reverted]

### ISSUE THREAD

**Issue by tokenizando** [ethereum/mist#4228]
I am using the template in openlaw.io "bill of sale (escrow erc20 token)" and everything is fine except when i going to execute the interaction with the contract, appear in my prompt metamask the error: 
ALERT: Error en transacción. Se produjo una excepción en el código del contrato in the metamask window confirmation and then the transaction fail and you can see the error in the file attached error.doc
[error.docx](https://github.com/ethereum/mist/files/4535011/error.docx)

**Comment by holiman** [comment]
Mist is deprecated and not under development anymore
