### ISSUE TITLE
Time Out of Sync - Windows 10

### ISSUE THREAD

**Issue by kodaxx** [ethereum/mist#423]
Node type: Ethereum-Wallet binary
OS: Windows 10
Network type: Neither - did not make it that far
Mist version: Wallet 0.5.2 (Beta 10)

When I start Ethereum, I get a message stating that my clock is out of sync - I am synced to an internet time server at time.windows.com, so I'm not sure why I'm seeing this message. My computer is roughly 30 seconds ahead of what time the wallet expects it to be, causing it to close. Is there another time server I should be using?

Screenshot: http://i.imgur.com/fsGu4Uw.jpg

**Comment by kodaxx** [comment]
Update: I looked through the code and found that Mist is using pool.ntp.org as it's NTP server. Changing my internet time server from time.windows.com to pool.ntp.org has fixed this error for me and I'm now able to access Mist. I feel as if there should be some way to either, use windows default time server for Ethereum or automatically change this for Windows users? Hmm..I'll try to put some thought in it.

**Comment by frozeman** [comment]
Don't worry, the next release wont check the time difference anymore, but rather if a time server is used at all
