### ISSUE TITLE
Cannot transfer my Ethereum out of Wallet to Ledger Nano S

### ISSUE THREAD

**Issue by Firenginedriver** [ethereum/mist#4237]
Need Help.  Cannot get my Ethereum to transfer to Ledger.
"Transaction Denied"???

**Comment by bigbinda** [comment]
I'm having a similar issue but mine says "error exceeded gas limit"
My peers won't sync either

**Comment by Firenginedriver** [comment]
peers won’t sync for me either.

**Comment by holiman** [comment]
Mist is deprecated and not under development anymore. If you're experiencing problems with ethereum wallets, it would probably be better to file a ticket on github.com/ethereum/go-ethereum, which was the node that Mist used under the hood.
