### ISSUE TITLE
Excellent

### ISSUE THREAD

**Issue by NahuelStratico** [ethereum/mist#4238]
Solved. 

Here's how.  sorta. so- 
PROBLEM - it seems installing babel changed many nodes, yet it did NOT update the yarn.lock and package.json files accordingly. 
SOLUTION - 
$ yarn info         |> made me realize some 2k files are out of date
then ran 
$ yarn upgrade  |> and it somehow sorted it but didn't compile yet
then
 $ yarn add yarn |> to actually update yarn as it was 1.3.x and required 1.7.x 

i think that's it yet, may have skipped a step or two... better read more about the cli commands i suppose.

_Originally posted by @lionroy in https://github.com/ethereum/mist/issues/4009#issuecomment-406078470_

**Comment by holiman** [comment]
Mist is deprecated and not under development anymore.
