### ISSUE TITLE
No password/passphrase how to get imported to other wallet???

### ISSUE THREAD

**Issue by arenaitmx** [ethereum/mist#4239]
Hi guys. I don't have the passphrase, I configured mist on my computer so I have keystore and all that. Wondering if I can move those ethers somehow ???, thanks in advance.

PD: check the migration guide and can't find the password, is it possible to use the wallet data to import to other wallet???

**Comment by nonfungibletunji** [comment]
same problem!

**Comment by holiman** [comment]
Mist is deprecated and not under development anymore. If you're experiencing problems with ethereum wallets, it would probably be better to file a ticket on https://github.com/ethereum/go-ethereum, which was the node that Mist used under the hood. So Mist used the key management within `geth` (go-ethereum).
