### ISSUE TITLE
not able to open eter wallet

### ISSUE THREAD

**Issue by newyorknew** [ethereum/mist#4240]

**Comment by nonfungibletunji** [comment]
Mac OS X same problem

**Comment by holiman** [comment]
Mist is deprecated and not under development anymore. If you're experiencing problems with ethereum wallets, it would probably be better to file a ticket on https://github.com/ethereum/go-ethereum, which was the node that Mist used under the hood. So Mist used the key management within `geth` (go-ethereum).
