### ISSUE TITLE
Account to create New Wallet Contract upper case to lower case from 0xF to 0xf

### ISSUE THREAD

**Issue by fuzioncoin** [ethereum/mist#428]
Node type: geth (Mist GUI) Geth/v1.3.5/darwin/go1.5.1
OS: OS X Yosemite
10.10.3 (14D131)
MacBook Pro
2.2 GHz Intel Core i7
4 GB 1333 MHz DDR3
Network type: main
Mist version: 0.5.2

Hi,
Cannot create a New Wallet Contract from funded Account in Mist. Changes Account 0xF to 0xf in the GUI

1.) Pre-requisites
ACCOUNT with 1 eth

1.1) _WALLET CONTRACTS_
Click "**ADD WALLET CONTRACT**"

1.3) _New wallet contract_
Type in **"new name"**
1.4) _SELECT OWNER_
Select **"account with 1 eth"**

Select **"SINGLE OWNER ACCOUNT"**

1.5) Click **"Create"**
1.6) Screen captures
https://gyazo.com/4c496d8d61cab4a94d108a4477fbd39e
https://gyazo.com/e16ca96bf3e2abebd5bc8faf38bbd4c9
Thanks.

**Comment by luclu** [comment]
This should not be problem as the capital-letters are only part of ethereum's address correctness check.
I tried to reproduce this behaviour but couldn't confirm it.

Are you sure you typed in the right password for the transaction?
I will close this for now, but feel free to give me a small ping-back on the outcome!
