### ISSUE TITLE
error of etherum wallet

### ISSUE THREAD

**Issue by SKiuros** [ethereum/mist#429]
![blad2](https://cloud.githubusercontent.com/assets/18039211/14001267/f8c232f2-f13c-11e5-9351-2447f2eeb029.png)

![blad](https://cloud.githubusercontent.com/assets/18039211/14001271/fabfb2be-f13c-11e5-8fca-0ad6644551ec.png)

 those 2 errors, and i cannot enter any thing form etherum, i cannot enter the wallet because of those errors

**Comment by luclu** [comment]
Could you kindly try version 0.7.4 on this?
