### ISSUE TITLE
NTP time sync error

### ISSUE THREAD

**Issue by McFrankline** [ethereum/mist#430]
Node type: geth
OS: linux
Network type: main

Hi @frozeman 
I'm running Ethereum Wallet (0.5.2) and i keep getting an error message("Couldn't get time from NTP time sync server. Timeout waiting for NTP response.") when i run on my main network. A workaround is to use a vpn, which allows the node to sync fine.
 My firewalls blocks all except my predefined NTP servers. Seems to be the problem. Is there any particular ntp server that the node seeks to sync with? Can you please point me to an address so i can add it to my predefined list?

![screenshot from 2016-03-28 16-26-54](https://cloud.githubusercontent.com/assets/886449/14083199/e651cf5e-f503-11e5-9cde-657b5bbf3ec7.png)

**Comment by glesaint** [comment]
It's using pool.ntp.org today. Next release won't query NTP. 
https://github.com/ethereum/mist/commit/560de63a9c7dfa1945fc2547ca471e9aac96b120

See here on how to edit your firewall's policies http://www.pool.ntp.org/en/use.html
