### ISSUE TITLE
There is no first opening Ethereum-Wallet

### ISSUE THREAD

**Issue by vladrud34** [ethereum/mist#432]
Node type: geth/eth
OS: windows7  - 64bit
Network type: main
Mist version:  0.5.2

Help I can not establish Ethereum-Wallet-win64-0-5-2 after when will download all blocks there is no first opening 
Wallet
![3](https://cloud.githubusercontent.com/assets/18140970/14107916/54b1960e-f5c3-11e5-9c4f-c4f4bc047ff4.png)
![1](https://cloud.githubusercontent.com/assets/18140970/14107918/5d8606d4-f5c3-11e5-8d8c-d58ef4df7ef6.png)
![2](https://cloud.githubusercontent.com/assets/18140970/14107919/61dd94ea-f5c3-11e5-9567-72364f8cbe35.png)

**Comment by vladrud34** [comment]
![2016-03-29_153807](https://cloud.githubusercontent.com/assets/18140970/14108083/484a4162-f5c4-11e5-8e9f-73f2ac1120ed.png)

**Comment by frozeman** [comment]
You need to click on the blue title "use the main network"

**Comment by vladrud34** [comment]
Thanks all have turned out

2016-03-29 16:28 GMT+03:00 Fabian Vogelsteller <notifications@github.com>:
