### ISSUE TITLE
Timezone error

### ISSUE THREAD

**Issue by nerd-lab** [ethereum/mist#433]
Node type: geth
OS: windows 8.1 pro x64
Network type: main
Mist version: 0.5.2

I've got a problem with starting the Mist client. I think the issue is that it thinks I'm in a different timezone. It says my computer is 1 hour ahead. My country switched to summer time last weekend. Probably the error

Error:
![ss 2016-03-29 at 06 29 04](https://cloud.githubusercontent.com/assets/10108885/14115672/3ed6e690-f5dc-11e5-90ab-013d72278100.png)

log:
![](http://puu.sh/nYlA9.png)

**Comment by glesaint** [comment]
You might want to see this issue and its solution https://github.com/ethereum/mist/issues/397

**Comment by luclu** [comment]
@nerd-lab have you been able to solve the problem or are you still affected?

**Comment by nerd-lab** [comment]
Sorry for not answering. Yes, with Mist 0.6.2 it works flawless.
