### ISSUE TITLE
unknown transaction

### ISSUE THREAD

**Issue by lzix** [ethereum/mist#434]
Node type: geth
OS: linux
Network type: main
Mist version: 0.5.2

I'm russian and my english very bad, but I need your help.
I have account 0x69B4ae2A74a7b238E02b9bD4a877B1f5DC679C4F
Today morning I tried send 585 ETH to my poloniex account from my ubuntu home pc.
But I have some bug and now all my money sent to unknown account 0x1dd622dbb32dd1727ea8e2515f9cec48d8c42968
I not know how it possible. Everytime I opening my wallet, click to last transaction and make new.
How it possible ?
TX URL https://www.etherchain.org/tx/0x2cc7489bb2946b294847845ffb6fd575c62fbb91a53811e72267a02462a2d7b7
Thanks.

![screenshot - 29 03 2016 - 22 05 50](https://cloud.githubusercontent.com/assets/18139258/14120283/f4bbf9d2-f613-11e5-85f9-259233db0d39.png)

**Comment by luclu** [comment]
The transaction pattern of the receipient's address show similarities whit this report's: https://github.com/ethereum/mist/issues/611.
Although the timewindow from the priovious transaction is much greater. 
Did ealier version of geth unlock for the current session?

**Comment by alexvandesande** [comment]
@lzix do you know what is the address 0x1dd622dbb32dd1727ea8e2515f9cec48d8c42968? Are you sure it doesn't belong to a wallet? 

Looking at the transactions, it was a single transaction, executed a month ago, and not near any other, so it doesn't look like it was an `unlockAccount` timing attack. If you are certain you didn't initiate this transactions then I strongly recommend you create a new account on a fresh computer, create multiple keys and a contract wallet, and then move your ether to a daily limited contract. Also check your computer for keyloggers

**Comment by luclu** [comment]
@lzix I go with @alexvandesande's recommendations and will close this for now.
We can still discuss and reopen though!
