### ISSUE TITLE
Problem with Chaindata Corrupted file need help

### ISSUE THREAD

**Issue by oldpoison** [ethereum/mist#438]
Node type: geth/eth
OS: windows 8.1
Network type: main/test
Mist version: 0.5.1

well when I try to syncronize geth its says this error please need help

![problem with chaindata corrupted](https://cloud.githubusercontent.com/assets/17651457/14148060/dd90f4da-f652-11e5-9a34-5bcdcba30e2b.jpg)

**Comment by luclu** [comment]
It is a problem related to the go-client.
Please try these advices:
https://github.com/ethereum/go-ethereum/issues/1601
The devs are aware and have updated the module leveldb in develop branch.

**Comment by luclu** [comment]
I will close this for inactivity. Please update to 0.7.4 and retry. Feel free to come back and discuss!
