### ISSUE TITLE
Syncing at 23 blocks per minute?

### ISSUE THREAD

**Issue by glesaint** [ethereum/mist#439]
Node type: geth
OS: osx
Network type: main
Mist version: 0.5.2

Found no existing issue, sorry if this is a duplicate.
Mist was shutdown for ~24 hours, ~5000 blocks to synchronise when opened back.
The client is syncing at the painfully slow speed of ~23 blocks per minute.
I'm not sure, is this normal? It's very hard to make transactions when the client takes hours to start. Or is there a way to make transactions even if the node hasn't finished to sync?

Logs are below! 

![screen shot 2016-03-30 at 11 04 11 pm](https://cloud.githubusercontent.com/assets/11625163/14149914/bcec05d4-f6d0-11e5-85c6-c3a9c2c51b9d.png)
![screen shot 2016-03-30 at 11 31 12 pm](https://cloud.githubusercontent.com/assets/11625163/14149920/be85ea0e-f6d0-11e5-91e5-99588714daed.png)
[node.log.zip](https://github.com/ethereum/mist/files/195995/node.log.zip)

**Comment by JRogiest** [comment]
Depends on you connection speed. In case you have a 6mbps d/l connection it should go way faster. An alternative is to go to the terminal and type '**geth --fast**' without the apostrophe. You will need to have **geth** installed. Once it is finished open mist again.

**Comment by glesaint** [comment]
Today synced at ~66.6blocks per minute (2400 blocks in 36 minutes).
Could the speed be related to the number of peers? 
Currently at 25 peers one hour after launching the client.
Speedtest reports 11ms, 20Mbps dl, 2Mbps up (domestic).

**Comment by luclu** [comment]
@glesaint how is the latest version 0.7.2 (bundled with geth 1.3.6) behaving?

**Comment by glesaint** [comment]
@luclu after upgrade to 0.7.2, syncing at ~40blocks per minute today (1991 blocks in 50 minutes). 
Currently at 25 peers, 50 minutes after launching the client.
Speedtest reports 11ms, 27Mbps dl, 2.2Mbps up.

I've attached today's logs as well.
[node.log.zip](https://github.com/ethereum/mist/files/234730/node.log.zip)

**Comment by luclu** [comment]
It's a problem related the geth. I guess it's not the download, but the block importing into the chain's replica on your computer.
The very long processing times in your log point at the corresponding function [InsertChain](https://github.com/ethereum/go-ethereum/blob/506c9277911746dfbab0a585aee736bd3095f206/core/blockchain.go#L1097).

What hardware are you running on? What is your CPU and Harddisk utilization?

**Comment by glesaint** [comment]
@luclu I'm running on a late 2012 iMac, 2.9Ghz i5 and SATA 7200rpm disk, here's the utilization, while syncing at ~45 blocks per minute.
- Disk utilization (all processes):
- - reads in/sec - between 100 to 200
- - writes out/sec - between 2 to 20
- CPU utilization (geth): varies between 5% and 15%

**Comment by frozeman** [comment]
@karalabe @fjl you should look at this.

**Comment by glesaint** [comment]
@frozeman @luclu 
After upgrading from SATA 7200rpm to SDD, syncing at ~3000blocks per minute.
I guess it was a hardware issue, I'll close it. Thanks for the help!

**Comment by karalabe** [comment]
We're aware of abysmal hdd performance. We have 2-3 prs pending for 1.5
that will significantly improve performance (3-4x). We're also prepping
state trie pruning which should solve scalability issues for the mid-term.
