### ISSUE TITLE
problems wallet 

### ISSUE THREAD

**Issue by topoman36** [ethereum/mist#441]
Node type: eth
OS: windows
Network type: main/test
Mist version: 0.5.2

Hello, yesterday I installed the wallet of ethereum, the version 0.5.2, the problem is that I have sent a ethereum and have not reached the wallet and not what I have to do, I'm new and I'm very lost , help me please .

**Comment by hiddentao** [comment]
So you created an account within the wallet app and then ETH to that account address?  Also, where you running on the main (Homestead) network or the test (Morden) network?

**Comment by luclu** [comment]
I will close this for inactivity. Please update to 0.7.4 and retry. Feel free to come back and discuss!
