### ISSUE TITLE
Fee slider can be lowered below node minimum

### ISSUE THREAD

**Issue by karalabe** [ethereum/mist#447]
Since I knew transactions with minimum possible gas prices will go through as long as they are above the node minimums, I just pulled the slider down. Was surprised to see that it's actually way below the node minimum. Why would we do that? If Mist cannot currently retrieve the minimum accepted by the local node, it would make sense for me to temporarily hard code the minimum to prevent unexpected issues like this, at least if we start our own local node.

**Comment by chfast** [comment]
Can I configure geth to allow lower fees?

**Comment by alexvandesande** [comment]
The problem here is that Geth nodes min is the same as the default fee. This should not be the case.

**Comment by karalabe** [comment]
Why should the default fee be higher than the minimum, if the minimum is accepted by the miners? :)

**Comment by alexvandesande** [comment]
The min price for a node to forward a transaction should be lower than the min price for a node to accept it. Vitalik once proposed simply to make the min price for forwarding a random chance, where the possibility of forwarding a transaction would be feePaidByTransaction/minFeeAcceptedByMiner

**Comment by luclu** [comment]
Related to https://github.com/ethereum/mist/issues/447.

**Comment by luclu** [comment]
Related to https://github.com/ethereum/mist/issues/447.

**Comment by alexvandesande** [comment]
@luclu you just created a grandfather paradox

**Comment by luclu** [comment]
Let's leave it for time being to resolve itself.

![](https://duckduckgo.com/i/d5bf6422.png)

**Comment by alexvandesande** [comment]
closed due to paradox
