### ISSUE TITLE
UI looks cluttered on a smaller resolution screen

### ISSUE THREAD

**Issue by karalabe** [ethereum/mist#449]
If the resolution of te monitor is that _that_ big, then information on the wallet screen somehow seems to be very cluttered. I think some more visual cues / borders / guides / emphasis would help users figure out what to do.

Many screens are almost empty with just some fields and buttons which make it hard for a new user to figure out exactly what's happening. I think adding 2-3 liner tutorial like texts here and there would make everything a lot clearer and the user would know what to expect.

E.g. again en EtherAPIs we've tried to add small explanation texts. These are obvious once you "get it", but before that they would be invaluable for a new user:

![A](https://etherapis.io/images/2016-02-19-dashboard-accounts-empty.png)
![B](https://etherapis.io/images/2016-02-19-dashboard-accounts-actions.png)
![C](https://etherapis.io/images/2016-03-26-dashboard-services-empty.png)

**Comment by frozeman** [comment]
Awesome, are you coming to me with design suggestions mr. backend :P

Visual clues are useful, but at the same time the more borders you add, the more you have to decode in your brain the more messy the screen looks like.

Though thanks for you suggestions, we might take some from it :) I will keep this open...

**Comment by obscuren** [comment]
Oh careful @frozeman. @karalabe might :facepunch::nose:

**Comment by frozeman** [comment]
:feelsgood:
