### ISSUE TITLE
Copy & Paste not working

### ISSUE THREAD

**Issue by alexvandesande** [ethereum/mist#45]
Copying and pasting (specially important for getting addresses) is not working, at least not on the mac.

**Comment by robertandrewsmith** [comment]
I'm using Ubuntu 15.04.  The right click button to paste an address into Mist doesn't work.  However ctr + v does work.

**Comment by frozeman** [comment]
yes, right click buttons have to be implemented separately.. @alexvandesande does cmd + v works for you now?
