### ISSUE TITLE
mist crashes when changing to testnet on osx el capitan.

### ISSUE THREAD

**Issue by 2075** [ethereum/mist#450]
Node type: geth
OS: osx
Network type: test
Mist version: 0.6.0

I tried reinstall, nothing changed.
Syncing on mainnet takes very long time, no errors till now, though.

Is testnet working on mist since the change to Homestead?

**Comment by luclu** [comment]
@2075 how is version 0.7.2 behaving for you?

**Comment by luclu** [comment]
I will close for now, feel free to reopen anytime!
