### ISSUE TITLE
69 ETH sent to main wallet; Only 5 ETH are showing.

### ISSUE THREAD

**Issue by 2411nguyent** [ethereum/mist#451]
It's been about an hour since the transaction. Sent 3 ETH to secondary account as a test. Where is the remaining ETH? 

https://etherscan.io/address/0xf7d7b5e56680aa04339cb6688d93f4e1656adffb

Screenshots are below. Please advise.

Many thanks!

http://imgur.com/a/0dOje

------------------

Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (osx: ~/Library/Application Support/Mist/node.log, windows: %APPDATA%/Roaming/Mist/node.log, linux: ~/.config/Mist/node.log)

**Comment by karalabe** [comment]
If you look at the Mist UI, there's a big red **testnet** sign. You need to switch Mist to the main net to see the real transactions. You'll also may need to copy your testnet keys over to your mainnet folder since they are separate and you just funded your testnet account :P

**Comment by alexvandesande** [comment]
We are working to prevent this on the future: https://github.com/ethereum/meteor-dapp-wallet/pull/164

Right now the fix is opening your testnet/keystore folder and copying the contents over
