### ISSUE TITLE
Wallet 0.5.2 "eth" node crash

### ISSUE THREAD

**Issue by dobcrypto** [ethereum/mist#452]
Node type: eth
OS: windows 64
Network type: main
Mist version: 0.5.2
![4d491fab9bd94bd79dc009d5ff3a803d 1](https://cloud.githubusercontent.com/assets/16653151/14200226/0a20075c-f7f2-11e5-80e4-d63a0c8e9a8d.png)
I need to eth node, my wallet is there, but it don't work.

**Comment by luclu** [comment]
Hi @dobcrypto did this issue resolve with the latest version 0.7.2?

**Comment by dobcrypto** [comment]
@luclu don't try on the latest version 0.7.2...
