### ISSUE TITLE
Node Crashed - Can't login

### ISSUE THREAD

**Issue by bikerboy4489** [ethereum/mist#454]
Can anybody help with this. I cannot access my wallet/accounts using my master password. I have tried all versions that I have on my computer but they either crash or show the attached error message.

Any help would be great.

Thanks in advance.
![node error](https://cloud.githubusercontent.com/assets/16919164/14202266/ee7b3d3a-f7ee-11e5-9898-e928ff8a3895.JPG)

**Comment by frozeman** [comment]
This error is shown after a timeout. So it seems like it doesn't unlock the node with the master password correctly. You can try starting the node yourself in `..wallet/resources/node/eth/eth.exe --master <mypw>`

And see if it unlocks correctly, and starts the IPC server correctly.

@chriseth you might want to watch this issue as well.

**Comment by luclu** [comment]
Pooling with other issues regarding the `eth`-backend: https://github.com/ethereum/mist/issues/607

**Comment by luclu** [comment]
@bikerboy4489 can you please check if version 0.7.4 resolves **this particular** error?

**Comment by luclu** [comment]
I will close this as the eth-connection will be upgraded altogether.
