### ISSUE TITLE
Typo on Ethereum-Wallet

### ISSUE THREAD

**Issue by jdm79** [ethereum/mist#456]
Scroll down the bottom, having clicked 'send' on Ethereum-Wallet,  it says 'payed' rather than 'paid'

"Gas is <b> payed</b> by the owner of the wallet contract" 

Screenshot:
<img width="949" alt="screenshot 2016-04-01 16 13 05" src="https://cloud.githubusercontent.com/assets/11488167/14211955/9311d4c4-f828-11e5-91c7-a56c0cadaef0.png">
Node type: geth
OS: osx
Network type: main
Mist version: 0.5.2

**Comment by frozeman** [comment]
Thanks, fixed
