### ISSUE TITLE
etherbase add changed somehow

### ISSUE THREAD

**Issue by oakmaster** [ethereum/mist#458]
was using geth now eth node on windows 10 so after updating to the newest version of mist i couldnt get geth to download the blockchain i tried just using mist than geth by itself nothing but eth downloaded with no problem so i can finally open mist now for whatever reason my etherbase add is different but the contact wallet add is the same so now i cant sent any of my eth thats on that wallet anywhere when i try only the etherbase add is able to send the contract add wont even show up in the drop down i have a backup of the original etherbase add as a json backup but I have no clue how the add got changed if someone could tell me how to fix this it would be appreciated thank you

**Comment by luclu** [comment]
@oakmaster please update to version 0.7.4 / geth 1.4.4. If your issue still persists feel free to open a new issue. I will close this as the headline-change looks too ugly. ;P
