### ISSUE TITLE
Readme Correction

### ISSUE THREAD

**Issue by hitchcott** [ethereum/mist#46]
Under "Run the Wallet", the instructions go as follows:

```
$ cd interface && meteor

// and in another terminal

$ cd my/path/meteor-dapp-wallet/app && meteor
```

But doesn't this mean that two Meteor processes will be trying to run on port 3000, and second one won't start properly?

**Comment by frozeman** [comment]
the wallet branch readme states `$ cd my/path/meteor-dapp-wallet/app && meteor --port 3050`
