### ISSUE TITLE
Mist (OSX) : Node Sync Popup scaling issue between Retina & Non-Retina display

### ISSUE THREAD

**Issue by jhamel2** [ethereum/mist#461]
OS: OSX El Capitan
Mist version: 0.5.2

There is a scaling issue when you move the "Ethereum node needs to sync, please wait..." popup screen
from a Retina diplay to a non-Retina display (multiple monitors) or vice-versa.

![image](https://cloud.githubusercontent.com/assets/6559564/14237701/7e41a0a0-f9f5-11e5-8d09-a4152d32b48c.png)

**Comment by luclu** [comment]
@jhamel2 I tried to replicate this with 0.7.4 but failed. Are you able to do so?

**Comment by luclu** [comment]
@jhamel2 do you still encounter this glitch with version 0.7.5 which leveraged electron 1.2.2?

**Comment by luclu** [comment]
I will close this for now, please give me a head up if you can still reproduce this.
