### ISSUE TITLE
Cannot choose language

### ISSUE THREAD

**Issue by WXTux** [ethereum/mist#463]
Hello,

My laptop is configured with French parameters but I would like to keep the English interface for the Ethereum wallet, something I cannot do with 0.6.0 it seems.

WXTux

**Comment by WXTux** [comment]
In addition, except texts (in French) appearing at the top, all screens are now blank (empty) with 0.6.0, so wallet is not usable

Win10 64-bit

WXTux

**Comment by alexvandesande** [comment]
Merged multiple issues into #553. Thanks for reporting!
