### ISSUE TITLE
Spanish support

### ISSUE THREAD

**Issue by mpolavieja** [ethereum/mist#464]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Hello, here my 2 cents.    I don´t how to contribute so I am doing it here as an issue.  This is the translation to Spanish.   I don´t know If there are more files that should be translated.  If so, please tell me and I´ll translate them as well

{
    "app": {
        "loading": "Cargando...",
        "offline": "Imposible conectar, compruebe que tiene conexión a Internet",
        "logginIn": "Conectando..."
    },
    "error": {
        "insufficientRights": "No tiene suficientes permisos para realizar esta operación."
    },
    "buttons": {
        "ok": "OK",
        "cancel": "Cancelar",
        "save": "Guardar",
        "edit": "Editar",
        "send": "Enviar",
        "next": "Siguiente",
        "previous": "Anterior",
        "back": "Volver",
        "skip": "Ignorar",
        "sending": "Enviando...",
        "create": "Crear",
        "tryToReconnect": "Intentando reconectar"
    },
    "commonWords": {
        "you": "Usted",
        "send": "Enviar",
        "or": "o",
        "of": "de",
        "with": "con",
        "and": "y",
        "on": "en",
        "per": "por"
    }
}

**Comment by franckuestein** [comment]
@mpolavieja justo hace unos días hice un nuevo pull request con todos los strings traducidos y ahora he visto tu Issue. 😀

Aquí tienes el pull request https://github.com/ethereum/mist/pull/467 que ya está migrado. Aquí tienes todas las modificaciones y ficheros añadidos: https://github.com/ethereum/mist/commit/fd1af1c71178dcdc74eadb1c1a8cf08085fe6e70

**Comment by mpolavieja** [comment]
Gracias!!  Les echo un vistazo

Manuel Polavieja.
