### ISSUE TITLE
This version 6 has a problem

### ISSUE THREAD

**Issue by rfikki** [ethereum/mist#465]
Node type: geth
OS:WIndows 64
Network type: test
Mist version: 0.6.0

I am getting blank screen caused by the application not allowing initialization if you already have a standalone geth instance running. I do not have this problem with the previous release. You can see that the previous version runs in background the new one displays as you see in the image below:

![wallet_mist_log](https://cloud.githubusercontent.com/assets/1055929/14258228/18b39e10-fa67-11e5-9082-934c6344c907.PNG)
![wallet_6_blank](https://cloud.githubusercontent.com/assets/1055929/14258229/18b43cb2-fa67-11e5-8809-172740a9868f.PNG)

**Comment by provatidis** [comment]
on win 10 64bit home
I'm getting  blank screen also (standalone geth instance running)
![0 6 0](https://cloud.githubusercontent.com/assets/13468768/14260059/578fa5e8-fab2-11e5-9cf2-28ebd7ac07b5.png)

**Comment by SteffenIvanhoe** [comment]
Same for me on Windows 7 64bit. Only blank screens. Already with the splash window and also with the main window. Only menu is visible but no other content. Is unusable!

**Comment by luclu** [comment]
Please update to version 0.7.4 and check if still affected. I will close for now, but feel free to continue to discuss here.
