### ISSUE TITLE
osx/macos app signing

### ISSUE THREAD

**Issue by hems** [ethereum/mist#47]
classic OSX issue.

A workaround is to right click and then click "Open"

![screen shot 2015-10-14 at 16 32 23](https://cloud.githubusercontent.com/assets/27327/10488591/45aa0e44-7291-11e5-8a2b-e73a31c2a378.png)

**Comment by frozeman** [comment]
We would need a apple developer account to register a dapp i guess.
Your image doesn't work for some reason..

**Comment by obscuren** [comment]
* System Settings
* Security & Privacy
* Check "anywhere" in the **Allow apps downloaded from:** section

**Comment by hems** [comment]
@obscuren yes i know there is a couple of workarounds, but there was no issue for this problem. hence why i did it!

**Comment by hems** [comment]
@frozeman i just re-uploaded, nothing special anyway.

**Comment by frozeman** [comment]
@hems could you please download this version and see if you still get the same error?
https://dl.dropboxusercontent.com/u/20835796/Ethereum-Wallet-darwin-x64-0-3-1.zip

**Comment by hems** [comment]
@frozeman Yes, still

**Comment by hems** [comment]
@frozeman Yes i did, then it didn't. I'm not sure why ( maybe i launched the wrong one, by having both side by side ), i'm erasing all versions and downloading again.

**Comment by hems** [comment]
@frozeman Yes, still same error.

**Comment by frozeman** [comment]
can you check the bundler in the plist file?
click `show package contents` and then open to contents/info.plist.

Check there the package bundler. I now changed it to the default one from electron, which should be identified i guess...

**Comment by hems** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>BuildMachineOSBuild</key>
    <string>14D136</string>
    <key>CFBundleDisplayName</key>
    <string>Ethereum-Wallet</string>
    <key>CFBundleExecutable</key>
    <string>Electron</string>
    <key>CFBundleIconFile</key>
    <string>atom.icns</string>
    <key>CFBundleIdentifier</key>
    <string>com.electron.ethereum-wallet</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>Ethereum-Wallet</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleVersion</key>
    <string>0.3.1</string>
    <key>DTSDKBuild</key>
    <string>14D125</string>
    <key>DTSDKName</key>
    <string>macosx10.10</string>
    <key>DTXcode</key>
    <string>0632</string>
    <key>DTXcodeBuild</key>
    <string>6D2105</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.8.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSMainNibFile</key>
    <string>MainMenu</string>
    <key>NSPrincipalClass</key>
    <string>AtomApplication</string>
    <key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>
    <key>CFBundleShortVersionString</key>
    <string>0.3.1</string>
  </dict>
</plist>

**Comment by frozeman** [comment]
and still you get the warning?
hm, ok then there is nothing we can do.. for now

**Comment by hems** [comment]
@frozeman yes, anyway it's all cool. just wanted to raise this issue, it's not a real problem but would be definitely something to solve.

**Comment by hems** [comment]
@frozeman maybe this thread could have some valuable information?

https://github.com/nwjs/nw.js/issues/616

**Comment by frozeman** [comment]
We will look at this some other time again. Thanks for the link

**Comment by tymat** [comment]
bump for this.  For user adoption we should not require them to take extra steps to sign the app.   The issue linked by @hems should take care of this issue (we followed the steps for our own app and it worked nicely)

**Comment by taoeffect** [comment]
> Check "anywhere" in the Allow apps downloaded from: section

Just an FYI, this is a dangerous thing to do, and you don't need to do it.

If you want to run an unsigned app, right-click on it and click `Open`.

**Comment by hems** [comment]
I actually had an app on top of nw.js 0.8.6 and recently updated to 0.12 and tested on a new machine using El Capitan and that annoying warning didn't happen. So i guess maybe it's easier to update nw.js than go through this very boring apple procedure.

**Comment by tymat** [comment]
@hems nwsj in of itself will pass if they already signed the package.  The problem is that Mist itself is a packaged Electron app so it will have a different checksum so the entire Mist.app has to be signed specifically.

**Comment by hems** [comment]
@tymat for some reason i was thinking you guys were using nw.js, my bad.

**Comment by frozeman** [comment]
Working on this, though its not so easy as all dependencies including geth have to be signed. If somebody has more experience with this i would appreciate help.

**Comment by hems** [comment]
oh man, these things nowadays are so boring :(

**Comment by frozeman** [comment]
Reminder: https://github.com/atom/electron/issues/3871

**Comment by sethlu** [comment]
Have a check on `electron-packager` and `electron-osx-sign`. Hope these tools may assist your code-signing procedure. @jasonhinkle and I are working on a walk-through to distribute apps inside/outside the app store for Electron-based apps in the public `electron-osx-sign` [wiki](https://github.com/sethlu/electron-osx-sign/wiki).

**Comment by luclu** [comment]
@frozeman Code-Signing works with my developer certificate.

Also please note that the production certificate can only be used on the MacStore and will be auto-signed by Apple in the process. Please see [MaintainingCertificates](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html#//apple_ref/doc/uid/TP40012582-CH31-SW41).

**Comment by ajbhatia-visa** [comment]
I have this same issue and the workaround suggested here is not helpful. I am on a company MacBook Pro at work inside my company's internal network and, even though I have admin access to my machine, I do not have the ability to change security preferences, which allow only apps from the Mac App Store or identified developers. I searched on the Mac App Store also, but did not find Ethereum Wallet there.

You might say that I should discuss this with my company's admins to get an exception. However, I think it is very bad for the reputation of the Ethereum organization if its software requires security settings to be disabled. The workaround is clearly not acceptable.

**Comment by frozeman** [comment]
Reminder links:
- https://medium.com/juan-cruz-viotti/how-to-code-sign-os-x-electron-apps-in-travis-ci-6b6a0756c04a#.kzeglhtuk
- https://github.com/electron-userland/electron-builder/wiki/Code-Signing#travis-appveyor-and-other-ci-servers

**Comment by luclu** [comment]
Added to Travis, should be available in `0.8.9`.
