### ISSUE TITLE
Mist Issue - Crash

### ISSUE THREAD

**Issue by reime00396** [ethereum/mist#470]
See attached

![mist issue 4-5-2016](https://cloud.githubusercontent.com/assets/17062179/14296381/d68ac554-fb47-11e5-9246-c7de2071b505.jpg)

Here is another link to screenshot if helpful        https://ln.sync.com/dl/288724980#urgys6g5-m9w3tchb-m2rhvp38-jqzdzqsw

**Comment by tageeboy** [comment]
Same error here. Was working fine on Windows 7, went to 8.1 and it worked, but did the update to Windows 10 (all over a 2 day timeframe) and I got the error. did notice a few updates are yet to install from Microsoft, possibly related to that. Double checking firewall now to rule that out.

**Comment by tageeboy** [comment]
Manual start of geth using the command in the dialog box seemed to get it running. Trying newest releases now.

**Comment by reime00396** [comment]
I rebooted PC. Mist started like normal.. Thank you. May have been an issue when it went to sleep.

**Comment by AlphaQUp717** [comment]
how did you guy's fix it? because I tried to do an reset on my PC and still nothing.

**Comment by tageeboy** [comment]
You may want to reimage your disk and try with a fresh build. I have done
that a few times when the DAG seems to get corrupt for no reason.

**Comment by luclu** [comment]
Please make sure to update to version 0.7.4.
If you are using windows 32bit - this is unfortunately not supported yet.
I will close this for now. Feel free to continue to discuss!

**Comment by reime00396** [comment]
I moved over to Gemini exchange wallet until things imorove. Thank you.
