### ISSUE TITLE
Meteor interface refuses to build on Windows with latest version of Meteor

### ISSUE THREAD

**Issue by ldurback** [ethereum/mist#471]
When running "meteor" in the interface directory, it fails on the error

=> Exited with code: 8
W20160405-17:30:22.845(-4)? (STDERR)
W20160405-17:30:22.845(-4)? (STDERR) C:\Users\<username>\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20160405-17:30:22.845(-4)? (STDERR)                                            throw(ex);
W20160405-17:30:22.845(-4)? (STDERR)                                                  ^
W20160405-17:30:22.845(-4)? (STDERR) Error: ENOENT, no such file or directory 'C:\Users\<username>\mist\interface\.meteor\local\build\programs\server\undefined\public'
W20160405-17:30:22.845(-4)? (STDERR)     at Object.fs.mkdirSync (fs.js:654:18)
W20160405-17:30:22.845(-4)? (STDERR)     at Package (packages/tap_i18n-bundler/i18n-bundler.coffee:18:12)
W20160405-17:30:22.845(-4)? (STDERR)     at C:\Users\<username>\mist\interface\.meteor\local\build\programs\server\boot.js:249:5

Is building on Windows not supported?

**Comment by PranobSamani** [comment]
remove i18 dependency by using this command  'meteor remove tap:i18n-bundler' it should work

**Comment by luclu** [comment]
duplicate: https://github.com/ethereum/meteor-dapp-wallet/issues/147
