### ISSUE TITLE
Mist displays holdings redunantly?

### ISSUE THREAD

**Issue by Canalytic** [ethereum/mist#474]
Hi, I am wondering why when I create an asset it gets displayed two times.  This happens with both wallets and accounts.  Please see the screenshot below.
![screen shot 2016-04-06 at 9 37 54 am](https://cloud.githubusercontent.com/assets/12152939/14318589/917598ec-fbdb-11e5-9b47-4eef8e156ad8.png)

**Comment by frozeman** [comment]
Could you please write down the steps to reproduce?

**Comment by Canalytic** [comment]
Yes, of course.

  (1) I copy the address of the 'bike user' wallet I wish to send to.
  (2)  I go to Account 3, that holds 10 tokens (listed twice) and try to send to said address.
  (3)  I try to send and it says the account I want to send from is empty 
![screen shot 2016-04-07 at 1 21 19 pm](https://cloud.githubusercontent.com/assets/12152939/14360337/e1776288-fcc3-11e5-85be-1379ea0a8c2f.png)

So then I 
 
(4) go to main account and send to bike user.  Transaction successful!
(5) Then I try to send from bike user to account #2 but get error message 'the account you want to send from is empty'

So, I am really having confusion about how I can send tokens to a wallet but then when I try to send those tokens I get message that account is empty.  Maybe I am missing something here.

The problem with every token be doubly listed I am not sure is connected with this.  One thought that might be causing this is--remember when you helped me with the mist client not starting?  You said delete the app data but save the keystore files.  Currently in my keystore folder I have 3 files, and I am not sure if this is causing the problem with multiple listing of tokens, if I need to delete two of them, and if so which one(s) I should delete, the newest, oldest, etc.?  
![screen shot 2016-04-07 at 1 28 59 pm](https://cloud.githubusercontent.com/assets/12152939/14360506/b438419c-fcc4-11e5-8d5c-b608e06f5d6a.png)

**Comment by frozeman** [comment]
Don't delete your keystore!

I just tried in the latest wallet and it works fine for me and is not displayed multiple times.
Please remove the token contract, copy first the token address and re-add it in the contracts page.

**Comment by Canalytic** [comment]
Hi,

   I don't see how to remove the token contract.  I can go to the admin
page for the contract but don't see a 'remove' option.  It's so strange
because everything, everywhere is duplicate.  Even the addresses are
duplicate.

    One thing I will try today is to install mist on another computer then
try sending tokens to that mist wallet to see if they show up double.

**Comment by Canalytic** [comment]
Never mind.  I just fixed it.  I was watching the same token twice, so it
therefore showed up in wallets and accounts twice.

**Comment by Canalytic** [comment]
One thing I can't figure out is why I still also have two 'main accounts'.

**Comment by alexvandesande** [comment]
@Canalytic as fabian said, don't delete anything from keystore. But try moving one of the duplicate keys out and see if that fixes the issue

**Comment by Canalytic** [comment]
Thanks.  I fixed the issue its because I was watching the tokens twice...

**Comment by alexvandesande** [comment]
Tokens should not allow to be added twice. Something weird happened on your database. But happy to see it was resolved
