### ISSUE TITLE
Enabling a pop up for a contract like the Multisig Wallet Contract

### ISSUE THREAD

**Issue by GriffGreen** [ethereum/mist#475]
Node type: N/A
OS: N/A
Network type: N/A
Mist version: N/A

We are loving your wallet! It is a thing of beauty. It is definitely not without bugs, but we are working it really hard over in the Slock.it Slack #art_of_the_dao channel, we have about 25 people beta testing DAOs. Buying Tokens, making proposals, voting and even splitting DAOs to create new DAOs! 

The problem is we don't have a way to display the address of the newly created DAO after the user splits. **I see that you have a pop up for the Multisig Wallet Contract... Is that something we can utilize for our purposes?**
![image](https://cloud.githubusercontent.com/assets/14945613/14337479/2794c590-fc23-11e5-853f-4297ba74a92e.png)

This is what the Slack members are working on right now: https://docs.google.com/document/d/148CWgAF-AuqVykVpVF7p5kNFTCBS5RG4qjmLsKb3fqw/edit?usp=sharing

If you poked you head into our Channel you would surely get Slack's version of a Standing O :-)

Thanks again Fabian!
Griff

**Comment by frozeman** [comment]
Adding a popup doesn't really make sense, but showing logs in a list below the contract does. I will add this once i get time. This was planned anyway, but i never got to it.

**Comment by alexvandesande** [comment]
@GriffGreen I'll close this issue as the latest wallet has events shown. Please reopen this if it does not solve your problem

**Comment by GriffGreen** [comment]
Thank you!

On Mon, Apr 18, 2016 at 2:11 PM, Alexandre Van de Sande <
notifications@github.com> wrote:

> @GriffGreen <https://github.com/GriffGreen> I'll close this issue as the
> latest wallet has events shown. Please reopen this if it does not solve
> your problem
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/mist/issues/475#issuecomment-211579632>
>



-- 
Griff Green - Slock.it UG
MSc Digital Currencies
B.S. Chemical Engineering
Email: griff@slock.it
