### ISSUE TITLE
Ether Disappeared!

### ISSUE THREAD

**Issue by bikerboy4489** [ethereum/mist#476]
Ok so I'm back again and getting really frustrated. I previously posted an issue with my Etherbase account not transferring my Ether to my wallet. After several attempts the Ether just wouldn't shift. I then gave up with this as I was told to wait until a new version of Mist was released to hopefully fix the issue. After downloading the latest version (0.6.2) I have now logged in to find that the ether isn't showing at all!

If I check the account on etherchain.org it clearly shows my funds are still in there however mist is showing that the account has zero balance in it! Why is this and how do I fix it?? See screen shots to see my problem.

Thanks in advance
![transactions frozen](https://cloud.githubusercontent.com/assets/16919164/14350461/50b203fe-fcc1-11e5-88ec-15a510607684.JPG)
![07-04-2016 screen grab](https://cloud.githubusercontent.com/assets/16919164/14350465/537debf2-fcc1-11e5-9364-11e374066622.JPG)

**Comment by alexvandesande** [comment]
Your wallet is still syncing, as can be seen by the progress bar on top. Please wait for it to finish sync, which unfortunately can take a few hours, depending on where you are.

**Comment by bikerboy4489** [comment]
Unfortunately this is not the case as it doesn't do anything. I have left the computer on for over 48hours and still nothing so this case shouldn't of been closed...

**Comment by alexvandesande** [comment]
Ok. But after 48 hours is it synced or not? I need to figure out if it's a sync issue or something else.

**Comment by luclu** [comment]
@bikerboy4489 did the problem resolve for you (with the latest version 0.7.2)?

**Comment by bikerboy4489** [comment]
The 35 Ether in my wallet appeared however the 2nd account that held my other 27 Ether wouldnt pull through into the latest wallet.

The only way I could access this was by using the .json file that luckily I backed up to access it using myetherwallet.com
