### ISSUE TITLE
Overloaded function

### ISSUE THREAD

**Issue by RCasatta** [ethereum/mist#478]
Node type: geth
OS: osx
Network type: test
Mist version: 0.6.0

i have a function overloaded (same name different parameter type one uint the other address)
I can see two function in the select function dropbox but the form is the one with uint parameter, I can't access the one with the address parameter

**Comment by frozeman** [comment]
Its not supported by web3.js, so it might not work at all for now. Also looks like that the jsoninterface is wrong?

**Comment by RCasatta** [comment]
No, the jsoninterface is correct

**Comment by alexvandesande** [comment]
This is fixed. Please retest with the most recent version and re-open a new issue if this still occurs
