### ISSUE TITLE
"Contract Info" not shown for some smart contracts

### ISSUE THREAD

**Issue by fraspadafora** [ethereum/mist#479]
Node type: geth/eth 1.3.5
OS: windows 7
Network type: private
Mist version: 0.5.2

Hi,
I installed Ethereum Wallet, and I created a private network. The Ethereum Wallet is connecting to it correctly.
I deployed different contracts, and with someone I can see all the information of the contract, and I can send transactions to the functions. As showed in this screenshot:

![crowdsale contract](https://cloud.githubusercontent.com/assets/10370697/14353090/dd923f8a-fcd7-11e5-93b9-1c29d87b74f1.png)

With a different smart contract (Pay4Picture), i can't see any contract info, so I cant't send transactions to functions.
I attach the contract code and a screenshot.

```
contract Pay4Picture{

    struct Picture {
        uint price;
        uint timestamp;
        string url;
    }
    
    struct Payment{
        address account;
        string url;
    }
    
    address public owner;
    Picture[] public pictures;
    mapping(string => uint) picturePrice;
    mapping(string => address[]) payments;
    
    modifier onlyowner { if (msg.sender != owner ) throw; _ }
    
    event PictureSaved(uint timestamp, uint price, string url);
    event PicturePayed(string url, address accountBuyer, uint price);
    
    function Pay4Picture(address _owner){
        owner = _owner;
    }
    
    function savePhoto(uint price, uint timestamp, string url) onlyowner{
        pictures.push(Picture({
            price: price,
            timestamp: timestamp,
            url: url
        }));
        picturePrice[url] = price;
        PictureSaved(timestamp, price, url);
    }
    
    function downloadPicture(string url) {
        uint price = picturePrice[url];
        if(msg.value < price) throw;
        
        payments[url].push(msg.sender);
        PicturePayed(url,msg.sender,price);
    }
	
	function checkPayment(string url, address buyer) onlyowner constant returns(bool result){
		address[] addresses = payments[url];
		bool found = false;
		for(uint i=0; i<addresses.length; i++){
			if(addresses[i]==buyer){
				found = true;
				break;
			} 
		}
	}
    
}
```
![pay4picture contract](https://cloud.githubusercontent.com/assets/10370697/14353186/49270be0-fcd8-11e5-9c44-38975a23c413.png)

**Comment by frozeman** [comment]
There is not interface, if the contract, is either not deployed, or you don't have the Json interface. Please check that the contract is actually deployed at the address, by opening the console using CTRL + ALT + i and type `web3.eth.getCode('0xaddressofthecontract')`

**Comment by fraspadafora** [comment]
The contract was deployed, I found the problem.

I added to the function checkPayment:
`return found`
 Now the function is:

`function checkPayment(string url, address buyer) onlyowner constant returns(bool result){
        address[] addresses = payments[url];
        bool found = false;
        for(uint i=0; i<addresses.length; i++){
            if(addresses[i]==buyer){
                found = true;
                break;
            } 
        }
        return found;
    }`


And now it works and I can see the Contract Info.
the weird thing is that when I compiled the smart contract, Mist didn't notify me an error.

**Comment by frozeman** [comment]
Thats weird yes. Maybe it was the compiler version we used, was buggy

**Comment by fraspadafora** [comment]
I had again the same problem, when I modified the contract, but I think I found the problem.

If a function it is a constant, but receives some parameters, Mist doesn't show the Contract Info.
If you don't add "costant" to the function all is ok.

The problem happened with this function:

> function checkPayment(string url, address add) onlyowner constant returns(bool){
        bool result = false;
        address[] addresses = payments[url];
        for(uint i = 0; i<addresses.length; i++){
            if(addresses[i] == add){
                return true;
            }
        }
        return false;
}

Removing constant all works correctly.

**Comment by chejazi** [comment]
This is still a problem, and it's only applicable when strings are parameters in constant functions: 

This shows a blank interface:

`contract Test1 {
	function TestFn(string symbol) constant returns (bool result) {
		return true;
	}
}`

While this does not: 
`contract Test2 {
	function TestFn(uint num) constant returns (bool result) {
		return true;
	}
}`
