### ISSUE TITLE
After restarting client, "Progress Bar" out of sync with actual progress.

### ISSUE THREAD

**Issue by unimercio** [ethereum/mist#48]
Minor issue:  
I started the client for the first time
Progress stalled 
I closed out the client using "x"
After restarting client, "Progress Bar" is out of sync with actual progress
Client completes successfully  

BTW, It looks great. Congrats and Thanks

![screen shot 2015-10-14 at 12 57 39 pm](https://cloud.githubusercontent.com/assets/362412/10491223/6e928f0c-7273-11e5-8711-eba8fedf7091.png)

![screen shot 2015-10-14 at 1 14 29 pm](https://cloud.githubusercontent.com/assets/362412/10491679/bbbfb58c-7275-11e5-8caa-728d7c55036b.png)

**Comment by frozeman** [comment]
What you mean with "progressbar out of sync?
the progress bar doesn't start at 0% with block 0 :) 0% means the point at which you stared syncing, as the blockchain is an every growing beast...
If i would make the progress bar start at block 0 it would be always starting at around 95% or so :)

Maybe thats psychological better

**Comment by frozeman** [comment]
If you mean the highest block number, this has to do with the peers you're connected to and what information you have at this point. Its not updating the highest block all the time in the sync function.

**Comment by unimercio** [comment]
Intuitively, I assumed the progress bar represtened a percentage of the two numbers  displayed. I was expecting to see roughly 90% indicated on the bar showed in the screenshot.

Thanks for the quick response. :-)

**Comment by unimercio** [comment]
maybe 2 small horizontal bars:
block height
node block height

-----------------|
------------>    

Again just a minor issue/ non issue at best.

**Comment by unimercio** [comment]
Now that I've synced, as you mentioned, It actually becomes much less awkward.  Closing.  Cheers
