### ISSUE TITLE
Sending from Contract Fails Due to 0.00 balance in eth.coinbase wallet for Mist

### ISSUE THREAD

**Issue by supere989** [ethereum/mist#480]
Node type: geth
OS: windows
Network type: main
Mist version: 0.5.2

Mist fails to send from a contract due to owner wallet having a 0.00 balance.

This results from not having any ethereum in eth.coinbase in order to fuel the contract transfer of value.

I ran accross this issue using the "Send All" button. Which is a great button, i love it. I just didn't know that if i "Send All" from my coinbase wallet that owns the "Contract" i can't send any ETHER from the "Contract" because the "Owner" can't afford it.

Recommendation:

Disallow the Maximum amount of ETHER for the fastest Contract Transfer Gas cost from being removed from the Owner/Owners Combined coinbase until the Contract has either reached a Zero balance, has been cancelled, or has committed suicide.

**Comment by JakeBlech** [comment]
@supere989 A member in the forums said something about how the timing of the contract can be affected by connection quality. Who's your ISP? I think he was sending from like some part of Europe with iffy wifi.

**Comment by supere989** [comment]
ISP is Charter, 60/4.5. I have fixed my problem but it is still a glitch

Thanks,

Raymond Johnson

**Comment by JakeBlech** [comment]
On what planet is Charter ever 60/4.5? Aren't they like the most hated ISP in the US?

**Comment by supere989** [comment]
That's residential, I can get 100/7 but I don't want to play the $100/m

Thanks,

Raymond Johnson

**Comment by JakeBlech** [comment]
Boseman tops out at 50 for Charter here, and then we have the smaller providers.

**Comment by supere989** [comment]
I live in Pasco, so we have spectrum

Thanks,

Raymond Johnson

**Comment by JakeBlech** [comment]
Anyways, sorry, off-topic -- guess the connection thing is a different issue than what you're reporting here.

**Comment by supere989** [comment]
Yeah the problem is with contact owner gas funding having insufficient ETH
in the owner wallet to allow a contract function to execute

Thanks,

Raymond Johnson

**Comment by pharynx** [comment]
I have the exact same problem. 1.2 ether in the base account, which is linked to the wallet contract. Trying to send Ether from the contract (tried various addresses) and still get the 0.00 Ether when trying to execute the contract.
I first thought it's the problem with insufficient gas, but it is not. Are there any other known issues with contract wallets? (Mine is the standard contract wallet that came with Mist 0.5.1 ... no fancy stuff)
Any suggestions?
Thanks,
Dave

**Comment by supere989** [comment]
Just send 1 eth to your coinbase wallet and then you can move your contract
funds.

Thank You!

Raymond Johnson
509-521-8751
supere989@gmail.com

**Comment by pharynx** [comment]
Hey Raymond,

thanks for the fast answer. Tried that (actually put over 20 into the base acount) - still nothing. (Waited for enough confirmations, etc.) Ether can still go into the contract, but nothing goes out - 0.00 ETH shown in the transfer window.

Any other ideas how I could proceed?

Cheers and thanks,
Dave

**Comment by supere989** [comment]
You may need to change the owner of the Contract to the local coinbase
account. Also, It is a built in security feature that if there is more than
one owner on the contract, ETH movement has to be authorized by all owners,
this is done by a ETHER balance check on all owner coinbase wallets.

SO my recommendation is:
0. Backup your Wallet/Contract Data files (If you screw up, this is the
only thing that will save you. And I do mean...ONLY)
1. Audit your Contract for Owners
2. Identify Wallet Addresses for those Owners
3. Verify there is sufficient ETH in Each Owner wallet
4. Try again.

Let me know what you find.

-Ray

Thank You!

Raymond Johnson
509-521-8751
supere989@gmail.com

**Comment by pharynx** [comment]
Ok, looks like my main account is the only owner. It has 7 Ether. That should be enough for a transfer.

I also tried all possible amounts and speeds (in terms of Ether spent for the transaction) - nothing yet. Still 0.00 in the transfer window.

The contract accepts Ether without any problems. The main account (Etherbase) and owner of the contract, works just normal. Can send and recieve without any hickups.

:-(

**Comment by supere989** [comment]
You may have a corrupt chainstate, and or corrupt installation of Mist​

Thank You!

Raymond Johnson
509-521-8751
supere989@gmail.com

**Comment by luclu** [comment]
Opened a new issue regarding the root problem: https://github.com/ethereum/mist/issues/664. I will close this one as it got cluttered. @supere989 please feel free to join the discussion!

**Comment by platefish** [comment]
I'm not able to see the resolution to this problem in #664 can anyone please elaborate?
