### ISSUE TITLE
Empty start screen after launch

### ISSUE THREAD

**Issue by GenetiX2K** [ethereum/mist#483]
Node type: geth/eth
OS: windows 10 /64 bit
Graphics: MSI AMD Radeon R9 380

Network type: main
Mist version: 0.6.2

Install succesfull.
After launch Ether splash screen appears. After that an empty screen appears. No hangs and it can be normally closed.

![capture](https://cloud.githubusercontent.com/assets/18356472/14397766/ba8e743c-fddf-11e5-8989-bc5b7ba84b8c.PNG)

Most recent node.log
[node.log.0.txt](https://github.com/ethereum/mist/files/210864/node.log.0.txt)

**Comment by hansIanda** [comment]
I have the same issue. 

GTX 980 
Windows 10 64-bit
i7-4770k
16GB DD3 2400

**Comment by Daeidon** [comment]
Try the previous version first then the newer version and see if that fixes your issue.

**Comment by AlennGK** [comment]
Same issue, different HW, W10.

**Comment by GenetiX2K** [comment]
Mist 0.6.1 works. Executing 0.6.2 after that -> same issue.

**Comment by AsymmetryKen** [comment]
I have the same issue. Should I just run 0.6.1 for now until bug is fixed?

**Comment by Aranad** [comment]
Same issue here, 64bit LinuxMint 17.1

**Comment by Styx-** [comment]
Same with ArchLinux 4.01

**Comment by sgehrman** [comment]
same here, will try the 0.6.1 next.  W10, 980gtx

**Comment by Styx-** [comment]
Yeah 0.6.1 worked for me. Prepare yourself for the blockchain download,
it's a doozie.

**Comment by anodirium** [comment]
same issues here win 7 version 0.6.2

**Comment by luclu** [comment]
If affected please look here: https://github.com/ethereum/mist/issues/599
Make sure to update to 0.7.4.
Further discussion will happen over here: https://github.com/ethereum/mist/issues/75
I will close this as duplicate.
