### ISSUE TITLE
ETH not received in Wallet Contract after more then 3 hours

### ISSUE THREAD

**Issue by goodasdead** [ethereum/mist#486]
Node type: geth/eth
OS: osx
Network type: main
Mist version: 0.6.1

Sent ETH from an exchange over 3 hours ago. Exchange has confirmed that the transfer has been executed (providing the etherchain.org link). 

The ETH still not arrived in my Wallet Contract. I sent the ETH to the Wallet Contract instead of the Main Account as I wanted that incoming transaction detail (ironic, I know).

What can I do?

**Comment by hiddentao** [comment]
Can you find your wallet contract on https://etherchain.org/? (search for the contract address)

**Comment by goodasdead** [comment]
Hi Ramesh,
I've solved the problem. The gas needed to execute a Wallet Contract transaction vs normal Wallet (under Accounts), is greater. The exchange (and likely exchanges as a whole), do not allow enough gas for the transaction. After some back and forth with the exchange, they have allowed more gas, and the transaction executed. 
Thanks for the reply and if anyone has this issue in the future, if your address is correct, go you your exchange support and ask them to max out the gas allowed. 
D

Get Outlook for iOS

    _____________________________

**Comment by hiddentao** [comment]
Good to hear!

On 13 April 2016 at 15:50:58, goodasdead (notifications@github.com) wrote:

Hi Ramesh,
I've solved the problem. The gas needed to execute a Wallet Contract transaction vs normal Wallet (under Accounts), is greater. The exchange (and likely exchanges as a whole), do not allow enough gas for the transaction. After some back and forth with the exchange, they have allowed more gas, and the transaction executed. 
Thanks for the reply and if anyone has this issue in the future, if your address is correct, go you your exchange support and ask them to max out the gas allowed. 
D

Get Outlook for iOS

_____________________________
