### ISSUE TITLE
Failure to remove contracts

### ISSUE THREAD

**Issue by larspensjo** [ethereum/mist#488]
Mist version: 0.6.2
Running on Testnet.

I opened the console and entered the command Contracts.find().fetch(). This failed, with "Uncaught ReferenceError: Contracts is not defined" (first line in snapshot).

Next step, I clicked on the contract name, and then the trash can. There is a popup dialog where I have to enter the name of the contract, and then I press "Ok". However, the contract is still there, and there is no error message. See last line in snapshot (the contract name is "Apa").

![image](https://cloud.githubusercontent.com/assets/2412342/14409261/e8dac910-ff0d-11e5-9c0c-942b456eb845.png)

**Comment by luclu** [comment]
The `Contracts` object has been renamed to `CustomContracts`.
Please give me a small ping-back, if it worked!

**Comment by frozeman** [comment]
👍

**Comment by larspensjo** [comment]
Don't have access to my testnet now, but I can confirm that ```CustomContracts``` and ```Tokens``` seems to work.

**Comment by luclu** [comment]
Feel free to come on the gitter-channel or open a new issue for this one.
