### ISSUE TITLE
Startup dialog does not register with window manager

### ISSUE THREAD

**Issue by chriseth** [ethereum/mist#49]
This concerns "Wallet 0.3.1 (Beta 1)" - linux x64 version.
When I start `Ethereum-Wallet`, it prints the following on stdout:
```
[9217:1014/224556:ERROR:browser_main_loop.cc(189)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[9245:1014/224557:INFO:renderer_main.cc(200)] Renderer process started
[9249:1014/224557:INFO:renderer_main.cc(200)] Renderer process started
CONNECT to IPC PATH: /home/christian/.ethereum/geth.ipc
Starting geth node...
Geth connection FOUND
Checking node sync status...
Time between last block 6423307s
```
and a startup dialog window appears that first shows "Starting Ethereum node" and then "Ethereum node needs to sync, please wait... Looking for peers".

The problem is that this dialog window neither has window borders, nor does it appear in the list of windows and cannot be moved, or brought to the foreground once it is in the background. My guess is that it does not register properly with the window manager on the system.

I'm running "Linux Mint 17.1" with mdm and cinnamon.

**Comment by frozeman** [comment]
Should be fixed in 0.3.2 can you test beta2?

**Comment by frozeman** [comment]
@chriseth can you test with the latest beta 2?

**Comment by alexvandesande** [comment]
Closing since no comment was made about it since beta 2

**Comment by chriseth** [comment]
Sorry, I did not get that message. It works, but as discussed with Fabian some time ago, it would still be great to get some kind of menu.
