### ISSUE TITLE
Node Crashed 

### ISSUE THREAD

**Issue by AlphaQUp717** [ethereum/mist#490]
![untitled-1](https://cloud.githubusercontent.com/assets/18385021/14449930/f737b10a-0046-11e6-868f-ab3d8e276e51.jpg)

Not to sure whats really going on cant seem to get into my wallet be cause a box will come up saying "Node Crashed
 Node type: geth
Network: Main
Platform: win 32

on the bottom it said 
"Fatal: Blockchain db err: leveldb/storage: corrupted  or incomplete CURRENT file" 

not sure whats going on with that it was working fine a few days ago, also when I try it on a new PC the wallet will come up but with no funds as if its a brand new wallet.

**Comment by bas-vk** [comment]
Your blockchain database is corrupt. Unfortunately there is no way to recover your database.

The solution is to remove the database and synchronize again. Stop mist and remove the `chaindata` and `dapp` directories in `c:\Users\carnage\AppData\Roaming\Ethereum`. Then start mist again, it will start from scratch. Be careful not to remove the keystore directory if it contain keys that are valuable to you.
