### ISSUE TITLE
Problem wallet

### ISSUE THREAD

**Issue by gurila** [ethereum/mist#491]
Hi,

My english isn´t good but I try to explain well, I have a wallet jaxx with ether in android, I make a transaction to the initial Etherbase account from official wallet ethereum in my pc, the ether is not displayed in the new account, I synchronize the wallet with the old blockchain in another pc with the keystore folder who is in testnet folder and the money is displayed, I can´t get out the ether because he ask me a password and I don´t put any password in the past. Anybody can help me?, thanks.

**Comment by hiddentao** [comment]
"testnet folder"? Do you mean the Ethereum test network?

**Comment by gurila** [comment]
Yes, because the first synchronize in the official ethereum wallet is with the blockchain of testnet, later I synchronize with the old blockchain, thanks for all.

**Comment by hiddentao** [comment]
Accounts created on the test network will not automatically be available on the main network. Same goes for accounts created on the main network trying to be accessed on the test network. The test network and main network are effectively two completely separate networks and cannot be mixed together.

**Comment by alexvandesande** [comment]
> because he ask me a password and I don´t put any password in the past

We don't create any automatic passwords, so this is certainly one you created (or someone else using your computer). Maybe you thought you were on the testnet? Try switching to main net and do it again
