### ISSUE TITLE
Idea: alternative forum for dealing with front-line user issues

### ISSUE THREAD

**Issue by hiddentao** [ethereum/mist#492]
For front-line customer support (for Mist/Wallet) I feel like a forum would be better, e.g. using https://www.discourse.org/. This way people don’t have to sign up for Github, they can search for similar threads easier, plus it avoids the problem of Gitter where everyone’s talking about different things in one single Mist room.

**Comment by alexvandesande** [comment]
From their homepage Discourse seems much more like a gitter/slack competitor than something that would help us with community tech support..

**Comment by hiddentao** [comment]
I was thinking from the point of view of non-technical users - they would find a threaded support forum with common login option (e.g. Fb, google) far more palatable than Gitter. Alternatively, there are open source Slack competitors like [Rocket.Chat](https://rocket.chat/) which allow for embedding a "Ask us for help" form on webpages - which then connect the user to somebody in the chat room. I'm just throwing ideas out there :)

**Comment by luclu** [comment]
Examples for discourse.org:
https://community.remotestorage.io/
https://community.letsencrypt.org/

**Comment by evertonfraga** [comment]
a kind bump here :)
