### ISSUE TITLE
Question: possible to connect the Wallet to RPC via TCP socket? 

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/mist#493]
Hi, 
we have added JSON-RPC support to EthereumJ and would like to have some testdrive of the Wallet with our implementation, but we lack IPC connector. 
Is it solvable to make the Wallet to connect to RPC via TCP socket? 
Thanks! 
Anton

**Comment by luclu** [comment]
Hi Anton,

unfortunately this is currently not possible.

See https://ethereum.stackexchange.com/questions/2403/can-mist-be-attached-to-a-geth-node-on-a-different-computer-over-http-rpc

**Comment by luclu** [comment]
This will be possible as of this PR https://github.com/ethereum/mist/pull/871.
Please be patient until we release version `0.8.1` which is billed for the 19th of July.
