### ISSUE TITLE
Mist Wallet/Node running on Mac OS X no longer syncs

### ISSUE THREAD

**Issue by btcmama** [ethereum/mist#494]
Node type: geth/eth
OS: mac osx
Network type: main/test
Mist version: 0.6.2

Hi, I had my mist wallet and Ethereum node working fine for several weeks but then it suddenly stopped syncing. I've tried restarting a number of times to no avail. I've even downloaded the latest version of the Wallet that was released a few days ago and it is also frozen on the same block and won't sync from that block on either. How do I get my node to start syncing again? Thanks for the help.

**Comment by sossee** [comment]
Have you updated `geth` to Homestead? Also try simply running `$ geth` in Terminal, and inspect the messages there. It will tell you what the last block was that was synchronised, and if it seems to be running fine (i.e. the last block is a recent one), then you can open up Mist, and things should be back to normal.

**Comment by btcmama** [comment]
Hi, I tried running get in the terminal and this is what it said-- synchronization failed. See below. What should I do now?

I0416 16:59:40.588614    6916 server.go:552] Listening on [::]:30303
I0416 17:00:00.588810    6916 downloader.go:288] Block synchronisation started
I0416 17:00:04.014411    6916 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=0): checksum mismatch, want=0x0 got=0x34a0615e [file=382256.ldb]

**Comment by btcmama** [comment]
Thank you for trying to help by the way.

**Comment by luclu** [comment]
as this problem is related to geth, could you kindly give the output of `geth version`?

**Comment by btcmama** [comment]
It's still not working. Here is the info from the terminal--

I0416 16:59:38.377862    6916 blockchain.go:214] Last header: #1212039 [12f0d577…] TD=10585778027227303142
I0416 16:59:38.377893    6916 blockchain.go:215] Last block: #1212039 [12f0d577…] TD=10585778027227303142
I0416 16:59:38.377903    6916 blockchain.go:216] Fast block: #1212039 [12f0d577…] TD=10585778027227303142
I0416 16:59:38.383363    6916 cmd.go:114] Starting Geth/v1.3.3/darwin/go1.5.3
I0416 16:59:38.384070    6916 server.go:311] Starting Server
I0416 16:59:40.514718    6916 nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-IP1

**Comment by btcmama** [comment]
I have tried deleting the old blockchain but can't seem to find those files.

**Comment by luclu** [comment]
btcmama, you are still running geth 1.3.3 whitch is **not compatible anymore** with the ethereum network. 
Please update to the latest geth (commandline) or the Mist Wallet (as geth is bundled).

https://github.com/ethereum/mist/releases
https://github.com/ethereum/go-ethereum/releases

**Comment by btcmama** [comment]
I have downloaded the latest Mist wallets a number of times, including
0.7.2, but ethereum won't run, I guess because there's a conflict between
the new and old versions. Please tell me explicitly how to delete the old
one? I don't understand how to do it and I've done lots of searches on it.
Thank you.

**Comment by btcmama** [comment]
Also, please don't close this issue until you've confirmed that it is resolved. I don't know how to do what you are saying.

**Comment by luclu** [comment]
don't worry, we are still here. It's just that this issue is formally closed as the reason is found and understood. So lets resolve the problem together...

Please give me some details on what software packages (geth / Mist / Ethereum Wallet) you installed and which channels you used (github releases / brew).

**Comment by btcmama** [comment]
Thank you for not giving up. I have downloaded all the latest Mist 
wallets for MAC at one time or another, 0.5.2, 0.6.2, and just 
downloaded the latest 0.7.2, I think, today. When I tried to download 
the newer version of geth 1.4 and open it, this is what the box says 
basically cannot execute binary file:

Last login: Sat Apr 23 21:11:46 on ttys000
Stephanies-Mac-mini:~ StephanieAlexander1$ 
/Users/StephanieAlexander1/Downloads/geth-1.4.0-rc-8241fa5-ios-7.0-framework\ 
3/Geth.framework/Versions/A/Geth ; exit;
-bash: 
/Users/StephanieAlexander1/Downloads/geth-1.4.0-rc-8241fa5-ios-7.0-framework 
3/Geth.framework/Versions/A/Geth: cannot execute binary file
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

I uninstalled whatever version of Homebrew that I had and then just 
installed whichever one was the latest version online so my version of 
Homebrew is up to date.

I don't know how to uninstall the old version of geth.


Thanks again for the help :)

**Comment by luclu** [comment]
you are welcome ;)

You downloaded the binaries for IOS not OSX, which are these ones:
https://github.com/ethereum/go-ethereum/releases/download/v1.4.0/geth-1.4.0-rc-8241fa5-darwin-10.6-amd64.tar.bz2

Anyhow, you are better adviced to use brew.
So try the following:
1. Update brew `brew update && brew upgrade`
2. Tap into ethereums brew `brew tap ethereum/ethereum` (just in case)
3. Remove old installation `brew remove ethereum`(just in case)
4. Install geth `brew install ethereum`

Have a look over here, if there is trouble.
https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Mac

good luck
