### ISSUE TITLE
Wallet don't work at higher version and don't give me my previous wallet after started with lower version

### ISSUE THREAD

**Issue by h2002al** [ethereum/mist#495]
Nevermind. Seems resolved,

Hello,

I needed to format my laptop where worked my etherium wallet. No problem before the formatting. After the format the last version of wallet didn't work at all. Appears a blank window without nothing within when started the exe file. Then tried with version 0.4.0 and the wallet was open. Changed the keystore dhe mist to have my ether (I have to many ether stored at my wallet) and appear the below screenshot. Which don't change in time. Could you please show what must to do to fix this problem?

![pamja2](https://cloud.githubusercontent.com/assets/4286283/14551539/a8bd5f58-02d4-11e6-907f-44a45dd48ec7.png)

**Comment by alexvandesande** [comment]
0.4.0 is a very old version, it might not work at all. Try some newer versions, like 0.7.x or 0.6.x
