### ISSUE TITLE
forgot the password

### ISSUE THREAD

**Issue by PAND-or** [ethereum/mist#497]
Node type: geth
OS: windows
Network type: main
Mist version: 0.6.2

@frozeman, im lost my wallet password, but i has json backup wallet
when i send eht Mist say my password, i'll try all of my standart password, and not work it

How to change or recover my password?

I'll try to use https://github.com/ryepdx/pyethrecover
but its not work on Windows
```
C:\pyethrecover>python pyethrecover.py ---help
Traceback (most recent call last):
  File "pyethrecover.py", line 11, in <module>
    from bitcoin import *
ImportError: No module named 'bitcoin'
```

how to fix it?

**Comment by Zoltu** [comment]
There is no way to recover a lost password.  To access an Ethereum account you need the private key and the password both.  Just having one or the other is useless.

**Comment by alexvandesande** [comment]
If you have any idea on how your password was formed, some patterns and basic words, you can search for a trusted wallet recovery service that will attempt to brute force your password. 

But be careful as that might reveal information on your other passwords.

Also, it's probable that you can run pyethrecover, contact their github repo
