### ISSUE TITLE
Error Mist

### ISSUE THREAD

**Issue by Nill2016** [ethereum/mist#498]
node type: get
OS: Windows 7
Network type: main
Mist Version: 0.5.2
I'm having the following error and I am unable to solve:

![mist](https://cloud.githubusercontent.com/assets/18508654/14584839/c9c70650-0431-11e6-8ef0-7596d95997b9.png)

![mist](https://cloud.githubusercontent.com/assets/18508654/14584829/92160f44-0431-11e6-9605-c083a08d0c0c.png)

**Comment by hiddentao** [comment]
I notice that you're running an older version of Mist. Please try the [latest one](https://github.com/ethereum/mist/releases) and let us know if this still happens.

**Comment by Nill2016** [comment]
hiddentao, back up my keys and downloaded a new version of the geth. I installed the new mist wallet and continued with the same problem. Delete all data downloaded by former geth previous blocks and I'm trying to download it again with the updated version of geth and mist wallet and this very slow. Sometimes the geth not low any block.

**Comment by hiddentao** [comment]
Has it managed to sync to the latest block yet? Still got the problem?

**Comment by Nill2016** [comment]
I'm still downloading the blocks. This very slow and has no option to improve it. I believe that will take days for this work to be complete. Before this problem happens to update took about 5 minutes.

**Comment by Nill2016** [comment]
hiddentao, after many attempts managed to solve the problem of slowness in updating the mist ethereum. I used the following: geth --fast --cache = 1024 --jitvm.console. With this procedure to speed up downloading the blockchain was found a block that was invalid date that had been downloaded on 04.23.2016. Do not know why this happened, it excludes the block that had this problem and those who were written off after him. With this download began to be faster. Among download all the blocks and validate all of them were about 5 hours.

**Comment by hiddentao** [comment]
That's good to hear. If somebody else experiences this in future atleast we know one possible solution it might be.
