### ISSUE TITLE
Blank screen view after downloading all the blocks

### ISSUE THREAD

**Issue by invisiblelab** [ethereum/mist#499]
Node type: geth
OS: Linux Mint 17.3 Cinnamon 64-bit
Network type: -
Mist version: 0.6.2 - release

- Description:
Downloaded latest binary release, double-clicked "Ethereum-Wallet" and waited for all the block to download. After that i get only blank window.

- Screenshot:
![mist_console](https://cloud.githubusercontent.com/assets/18111817/14585882/044aefb8-0486-11e6-965a-1b38fc9c64ca.png)

- Log:
`I0417 10:16:55.857585   26051 flags.go:425] WARNING: No etherbase set and no accounts found as default
I0417 10:16:55.857750   26051 database.go:71] Alloted 433MB cache to /home/null/.ethereum/chaindata
I0417 10:16:56.078048   26051 database.go:71] Alloted 78MB cache to /home/null/.ethereum/dapp
I0417 10:16:56.085683   26051 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0417 10:16:56.086052   26051 backend.go:362] Blockchain DB Version: 3
I0417 10:16:56.088031   26051 blockchain.go:214] Last header: #1346117 [83b2f0c5…] TD=13913802902466150723
I0417 10:16:56.088054   26051 blockchain.go:215] Last block: #834083 [5e568256…] TD=5411963005019287108
I0417 10:16:56.088065   26051 blockchain.go:216] Fast block: #1345472 [02a24c08…] TD=13895628744163875044
I0417 10:16:56.088287   26051 handler.go:92] blockchain not empty, fast sync disabled
I0417 10:16:56.093221   26051 cmd.go:115] Starting Geth/v1.3.6-9e323d65/linux/go1.6
I0417 10:16:56.093360   26051 server.go:311] Starting Server
I0417 10:16:58.370776   26051 udp.go:212] Listening, enode://80758bcfa741333dd43ff5da877f156ee0c1bd2f5d8a9836d2260e235112909c198705f6fd3fe5c9bc45e07f3490b930dc76a27ee3fd7d4e7b4ab852c200e123@192.168.100.147:30303
I0417 10:16:58.370972   26051 server.go:552] Listening on [::]:30303
I0417 10:16:58.371111   26051 backend.go:526] Server started
I0417 10:16:58.372087   26051 ipc.go:112] IPC service started (/home/null/.ethereum/geth.ipc)
`

**Comment by frozeman** [comment]
Thanks, i think the latest release has the wrong version of web3.js included. Thanks for the screenshot. I will release a new version in the next days fixing it.

**Comment by invisiblelab** [comment]
Thank you for confirmation. Looking forward to it.

**Comment by luclu** [comment]
@invisiblelab do you still run into this in version 0.7.2?

**Comment by KentBarr** [comment]
I just experienced it in 0.7.2 on Ubuntu 16 

Apparently there's a blacklist in chromium that incorrectly blacklists certain GPUs such as the one in my AMD-powered laptop. Launching Ethereum Wallet with the blacklist disabled fixed it.

Launch with this sh script:

#!/bin/bash
echo running the Ethereum Wallet
./Ethereum-Wallet --ignore-gpu-blacklist

**Comment by luclu** [comment]
Thank you @invisiblelab!
For future references please look here: https://github.com/ethereum/mist/issues/599
