### ISSUE TITLE
Editing of contract wallet name captures wrong name

### ISSUE THREAD

**Issue by unimercio** [ethereum/mist#50]
When you:

Select a contract wallet
type in a new name "Test 1"
hit enter key
name is saved as "Test 1Test 1Test 1"

![screen shot 2015-10-14 at 6 31 17 pm](https://cloud.githubusercontent.com/assets/362412/10500060/412d757e-72a3-11e5-89df-42458d164bbd.png)

![screen shot 2015-10-14 at 6 31 45 pm](https://cloud.githubusercontent.com/assets/362412/10500065/48ef3f68-72a3-11e5-9e92-1cc15319cebe.png)

**Comment by frozeman** [comment]
Yeah i noticed that a few times, but didn't found the reason... i will look into it again.

**Comment by frozeman** [comment]
fixed in the next release
