### ISSUE TITLE
New Contracts send eth to 0x00

### ISSUE THREAD

**Issue by magoo** [ethereum/mist#500]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.6.2

Hi - 

Found a bug that burns eth. While I can repro it, I do not know exactly what causes this outcome. When creating a contract with any value, it instead sends it to 0x000. You can see the burnt eth here: https://etherchain.org/account/0x0000000000000000000000000000000000000000#txreceived
1. Move eth from main account to a wallet contract
2. Deploy new contract
3. Add seemingly any amount of eth, and switch "From:" to the wallet contract
4. Create contract with this code (doesn't appear special):  https://gist.github.com/anonymous/5e54212fd5c7161ef3d64ec7ed5f948f
5. Increase the fee towards "faster"
6. Deploy

When I return to the "Wallets" interface, it has sent the eth to 0x00. It switches from a "Creating Contract" logline to this log line, which proves the bug.
<img width="892" alt="screen shot 2016-04-17 at 7 26 15 pm" src="https://cloud.githubusercontent.com/assets/1410948/14592342/606461de-04d2-11e6-876b-d6ed04a826ee.png">

> Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot. (This may be too late, had to close mist at one point, but the TXN appears)

<img width="532" alt="screen shot 2016-04-17 at 7 29 45 pm" src="https://cloud.githubusercontent.com/assets/1410948/14592385/cdbbc394-04d2-11e6-9e7c-e2d072bf6128.png">

logs: https://gist.github.com/mag00/e2d7fbef4150f3f57b67f92c9ceef952

I had tested my contract on testnet, and it worked fine. It seems this bug only surfaces on the main network.

**Comment by mag00** [comment]
I just repro'd without needing to adjust the slider.

1. Move eth from main account to a wallet contract. (Click the wallet contract, then deposit)
2. Click contracts -> "Deploy new contract"
3. Switch "From:" to the wallet contract from step one
4. Create contract with this code (doesn't appear special): https://gist.github.com/anonymous/5e54212fd5c7161ef3d64ec7ed5f948f
5. Select "Simple Storage" contract from dropdown on right
6. Deploy

7. Then quickly go back to the "wallets" interface, and you'll see the transaction switch from "creating contract" to "sent to 0x00"

<img width="905" alt="screen shot 2016-04-17 at 8 22 36 pm" src="https://cloud.githubusercontent.com/assets/1410948/14593014/4c978156-04da-11e6-8e67-1d3c4a43df90.png">
<img width="898" alt="screen shot 2016-04-17 at 8 22 51 pm" src="https://cloud.githubusercontent.com/assets/1410948/14593015/4c97f956-04da-11e6-84ad-aae6733edc65.png">

Confirmed on the blockchain, so not any sort of UI trickery. 
https://etherchain.org/account/0x0000000000000000000000000000000000000000#txreceived

**Comment by alexvandesande** [comment]
> Update. I think think the issue here is if you select a contract wallet to create a contract, it breaks.

Yes, this is the issue. I will remove Wallet contracts from that list, to prevent this happening.
