### ISSUE TITLE
Mist syncs on splash, opens wallet, new contract creation freezes, wallet sync stops.

### ISSUE THREAD

**Issue by maqueen** [ethereum/mist#505]
Created a new token contract using generic template. Paid ether, etc.. But, contract won't confirm, stays grayed out and freezes wallet
![screenshot - 04182016 - 12 33 06 am](https://cloud.githubusercontent.com/assets/13737659/14658911/7e534db8-06a8-11e6-8214-10822661bcd0.png)
 sync. Did it on 0.6.2 about 6 days ago, continully shut down and periodically started again. Upgraded to 0.7.1 and problem persists.

Checked console and looked for contract to try and delete. Nothing.

**Comment by maqueen** [comment]
Bump

Can I please get some help here. It took 6 days to do initial sync, exchanged some BTC for ether to experiment with and now I've screwed around another week with issue above.

**Comment by alexvandesande** [comment]
Hi @maqueen I just tested it and wasn't able to reproduce the behavior. Can you try in on the testnet?

**Comment by frozeman** [comment]
Ok i just tried it on the latest version on the testnet:
<img width="979" alt="screen shot 2016-04-22 at 16 02 29" src="https://cloud.githubusercontent.com/assets/232662/14744755/64f0bdd6-08a8-11e6-8dd0-47c9f0f21dbe.png">
<img width="955" alt="screen shot 2016-04-22 at 16 36 12" src="https://cloud.githubusercontent.com/assets/232662/14744754/64ed9a8e-08a8-11e6-936b-cb3a18b96cc6.png">

**Comment by maqueen** [comment]
I never synced testnet so it could take days... Think there is a slight misunderstanding. Transferring BTC was just background on situation. Wallet (0.7.2 now) is simply frozen after contract creation and won't confirm.

**Comment by sekisanchi** [comment]
I suffered the same problem days ago 0.6.2 OSX probably because i shutdown in the middle. Upgrading 0.7.1 does not solve, but once I run geth from terminal without any parm and abort, it start synching again.

**Comment by maqueen** [comment]
Should I just bag the whole thing and consider it a lost cause? It really isn't worth it to spend days downloading a bunch of data, wasting time, etc. to not really get any answers.

**Comment by joelcan** [comment]
I think this may be the same issue I'm seeing on Mist 0.7.2, Ubuntu 14.04.4 LTS Trusty.
It seems to sync great when starting up, but the instant when sync completes, the GUI appears and sync stops. I'm not creating contracts or doing anything else, I'm only running the wallet.
I would like to participate int the crowdsale for "The DAO" -- is there a workaround that would allow me to accomplish this?

**Comment by luclu** [comment]
Could you kindly check if you are still affected by this in `0.8.1`?

**Comment by maqueen** [comment]
Yeah!... $300+ down the drain... ;)
