### ISSUE TITLE
Wallet missing

### ISSUE THREAD

**Issue by yagitu** [ethereum/mist#506]
My synced wallet (version 0.6.2) shows three etherbase accounts I created from 3.8.15 to 15.10.15. On 20.10.15 I created a wallet for secuity reasons 
(address: 0x8ec0d0bbce4349e2d34586e2de392caa73532d3f) and transfered 1.12 ETH to it.

After one of the last updates (I'm not shure what update, cause the wallet was not synced in the meantime) the wallet disappeared. At the moment I only see 3 Etherbase accounts. Where is my wallet?

edit:
Maybe I know what happend: I use the wallet in portable mode (start geth with -datadir option), what means the keystore folder is not in the default location. When I created the wallet, it was not stored in the keystore folder??? In the meantime I had an hdd crash, so this part is gone. If so, can I manually add the wallet contracts back now ?

**Comment by frozeman** [comment]
In one of the last version (0.3.2) or so electron changed the local storage folder on linux. Maybe thats it.

Just click the "add wallet" tab and click on "import wallet" and enter your address

**Comment by yagitu** [comment]
Thank you, it worked. I use Win7 (German version), where is the wallet stored now ?
 If I use portable Mode I expect all the data in my data folder, but it seems to be some information in C:\Users\Username\AppData\Roaming\Ethereum, that is not a good solution. Will it be changed in the next version?

**Comment by alexvandesande** [comment]
Go to accounts > backup and you'll see all the data needed for backups

**Comment by yagitu** [comment]
Thank you for comment, but it didn't answer my questions.

**Comment by alexvandesande** [comment]
Well the folders can be seen that way. Yes, unfortunately we don't have a portable mode yet.
