### ISSUE TITLE
I don't want my system language for mist

### ISSUE THREAD

**Issue by pacifics** [ethereum/mist#510]
I live and bought my computer far from my country.
It's not a problem for me if I can change the language of applications.

**Comment by luclu** [comment]
Manual selection of the gui language is not possible. It might be in the (longterm) future.
Changing the system language to your mother tongue might help in the meanwhile - hope it is available there though... :)

**Comment by frozeman** [comment]
Open the console `CMD/CTRL + ALT + i` and type `TAPi18n.setLanguage('en')`

**Comment by pacifics** [comment]
Even English ?  I use an old version of mist in order to have English
interface. So new releases are not for me.
Le 23 avr. 2016 23:26, "Fabian Vogelsteller" <notifications@github.com> a
écrit :

**Comment by pacifics** [comment]
Easy. Thank you.

**Comment by alexvandesande** [comment]
Merged multiple issues into one. Thanks for reporting!
