### ISSUE TITLE
Improve initial load times with `geth --fast`.

### ISSUE THREAD

**Issue by Zoltu** [ethereum/mist#511]
Node type: geth
OS: windows
Network type: main
Mist version: 7.0.2

For new users to Ethereum it can be a bit demoralizing to download Mist, launch it, then have to wait half a day to fully sync to the network.  While ideally Mist would operate as a lite client, in the meantime this could be significantly improved by having Mist use `geth --fast` if during startup it found no `chaindata` folder.  This isn't bullet proof as I believe if you close `Mist` (and therefore `geth`) and then re-open it you won't be able to restart in `--fast` mode but I do believe it could help improve the new user experience for many people at what I suspect is fairly low cost.

**Comment by luclu** [comment]
Related: [ethereum.stackexchange.com - Why isn't fast-sync the default](https://ethereum.stackexchange.com/questions/1845/why-isnt-fast-sync-the-default)

**Comment by hiddentao** [comment]
Just a note that Mist already always runs geth in `--fast` mode.

**Comment by luclu** [comment]
@hiddentao thank you!

Currently activated here: https://github.com/ethereum/mist/blob/8bf6225505c4a3aa73b392a4d41ca9bfc2146f46/modules/ethereumNodes.js#L184
