### ISSUE TITLE
Token Standard approve/transferFrom features

### ISSUE THREAD

**Issue by tymat** [ethereum/mist#512]
The Token standard has approve and transferFrom functions that can be used to allow users to spend from an account.  Currently the only way to make these accessible to the end user is to have them add the ABI in a separate "Watch Contract" instance.  It would be nice if the wallet had this functionality for all tokens added.

**Comment by alexvandesande** [comment]
Yes, will put it on the roadmap.

**Comment by alexvandesande** [comment]
Looking at the current standard I realize why we can't implement it now. There are some very practical aspects on what's required for it to be implemented that we need to solidify as the standard token v1.

I will modify these and then submit a ERC/EIP requesting the solidification of that code as the minimal version 1 standard.
