### ISSUE TITLE
Confusing message: downloading block x of x-n

### ISSUE THREAD

**Issue by rolandkofler** [ethereum/mist#514]
NOTE: This is a very small glitch, I mainly file it to get my hands dirty with Mist and let you know, that I intend to fix the issue.

Node type: geth
OS: linux
Network type: main
Mist version: 0.7.1

Synopsis: If nodes need to be synchronized, the splash screen shows a wrong number of  the actual block height (sometimes called "best block"). 

Hypothesis: this is because the blocksize increases, while the node syncs. The variable holding the block height then is not actual anymore.

Reproduce:
Precondition: be not in sync with the network for a while.
1. start Ethereum Wallet
2. wait
Result: downloading x of y, where y < x
Expected result: y is the current block height, it increases too.

**Comment by frozeman** [comment]
We get this information from the `eth_syncing` RPC method from `geth`. So thats not somthing mist can or should influence.

**Comment by luclu** [comment]
@alexvandesande could this be incorporated into the new splash-screen?

**Comment by alexvandesande** [comment]
I haven't seen this again since the geth sync changes

**Comment by luclu** [comment]
Currently the `eth_syncing.highestBlock` only gets updated when connecting to a fresh peer: [downloader.go#L991](https://github.com/ethereum/go-ethereum/blob/master/eth/downloader/downloader.go#L991).

**Comment by luclu** [comment]
Closing as this is node depended. AFAIK geth is trying to implement it.
