### ISSUE TITLE
Cannot load Ethereum Alarm Clock Scheduler Contract in 0.7.2 . Working in 0.6.2 .

### ISSUE THREAD

**Issue by bokkypoobah** [ethereum/mist#515]
Node type: geth
OS: linux
Network type: main
Mist version: 0.7.2

I've added a new Watch Contract for the Ethereum Alarm Clock. The Contract Address is  0x6c8f2a135f6ed072de4503bd7c4999a1a17f824b and I copied the Scheduler ABI from http://docs.ethereum-alarm-clock.com/en/latest/abi.html#scheduler-abi . This is documented in http://ethereum.stackexchange.com/questions/3347/watching-contracts-on-mist .

When loading in Ethereum Wallet 0.6.2, I get the following screen that shows the details for the Ethereum Alarm Clock Scheduler:
![ethereumwallet0 6 2-ethereumalarmclock-20160426-075122](https://cloud.githubusercontent.com/assets/17121975/14800781/74ec876a-0b87-11e6-92df-4cbfce013e67.png)

When loading in Ethereum Wallet 0.7.2, I get the following screen:
![ethereumwallet0 7 2-ethereumalarmclock_20160426-074928](https://cloud.githubusercontent.com/assets/17121975/14800786/830597ec-0b87-11e6-866c-eb979cce9e33.png)

Here is the console screen from 0.7.2:
![ethereumwallet0 7 2-console-20160426_082101](https://cloud.githubusercontent.com/assets/17121975/14800821/e7ecdd96-0b87-11e6-93df-8b1f79f7309c.png)

Here is where the error seems to be occurring in 0.7.2:
![ethereumwallet0 7 2_sources-20160426-082557](https://cloud.githubusercontent.com/assets/17121975/14800914/94a141a8-0b88-11e6-87f9-b80caf87b911.png)

Here is the node.log:
[node.log.zip](https://github.com/ethereum/mist/files/235523/node.log.zip)

Here is the console screen from the working 0.6.2 version:
![ethereumwallet0 6 2-console-20160426-083038](https://cloud.githubusercontent.com/assets/17121975/14800992/3d3bbe6a-0b89-11e6-9cdf-a96477a49f1f.png)

**Comment by bokkypoobah** [comment]
On further testing, there is a message that shows up in my terminal:

Started Ethereum Wallet 0.7.2 at 11:25:45.

[2016-04-26 11:27:18.936] [INFO] ipcProviderBackend - IPCSOCKET 8 ERROR { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Error: read ECONNRESET
    at exports._errnoException (util.js:856:11)
    at Pipe.onread (net.js:544:26)

At 11:30 I exit the Ethereum Alarm Clock Scheduler contract screen and go back in. The details are now available on the screen (now similar to the 0.6.2 screen). The IPCSOCKET error message that appeared before does not show up.

**Comment by luclu** [comment]
@bokkypoobah could you kindly check how 0.7.5's IPC-refactor plays out on this?

**Comment by bokkypoobah** [comment]
The IPC problem seems to have been fixed in 0-7-6, thanks.

There is still a general freezing problem when The DAO contract is in the contract watch list, but this is already reported in https://github.com/ethereum/mist/issues/836.
