### ISSUE TITLE
Cant send test DAO tokens

### ISSUE THREAD

**Issue by keuge** [ethereum/mist#517]
Im testing how i will send DAO tokens to other wallet. And have issue.

Here how it looks like https://snag.gy/nZbYPC.jpg.

Im sending some DAO test tokens. Approving confirms. And then nothing does not happens.
I cant see on my Account 3 wallet DAO tokens.

7.2 and 6.2 wallets have same issues

**Comment by keuge** [comment]
i have update info. I managed to send to myself ptDAO coins (0xad23d7C443382333543Dd13C3B77b99b2A7e2c6D) but cant send InfiniteTestDAO coins  (0x055343f7690A15e1B60107a9Ed12781E47cd94a5) to the same wallet. https://snag.gy/7vZ1UR.jpg

**Comment by keuge** [comment]
i guess i understand now. ptDAO is sumulation of closed sale period. So it can be sended to anyone. And InfiniteDAO has never end sale period. So i cant send them never.

Correct me if im wrong?

**Comment by alexvandesande** [comment]
Yes, the DAO won't allow tokens to be moved before the crowdsale period is over.
