### ISSUE TITLE
[OS X El Capitan] Wallet no longer stays in sync, and watched contracts interface no longer appears (related issue?)

### ISSUE THREAD

**Issue by dodgers76** [ethereum/mist#519]
Node type: geth/eth

![screen shot 2016-04-28 at 15 46 49](https://cloud.githubusercontent.com/assets/16994153/14889887/7f8d3d18-0d58-11e6-8e16-ba1d51709450.png)
(should one of these be ticked like "Main Network" is under the Network context menu?)

OS: OS X El Capitan v10.11.3
Network type: main
Mist version: 0.7.2

A few versions back my Ethereum Wallet worked as expected, but with the latest versions I've experienced problems with syncing and watching contracts. I've got the latest version of Geth, v1.3.6. I've tried restarted my wallet to reset peers, and I've also restarted my computer many times.

- Screenshots

When the Ethereum-Wallet application starts then it syncs OK up to the latest block. Once it displays the "Accounts Overview" pane, the number of peers in the top bar can vary between 0 or 5, the block number displays the latest block during the initial startup sync, but the wallet no longer carries on being in sync from that point, and the minutes since last block keeps counting upwards.

![screen shot 2016-04-28 at 16 15 27](https://cloud.githubusercontent.com/assets/16994153/14890948/84d525ca-0d5c-11e6-8dd0-900613f14080.png)

If I run geth alongside in a terminal window then it syncronises as expected, but the wallet still does not.

![screen shot 2016-04-28 at 15 29 53](https://cloud.githubusercontent.com/assets/16994153/14889317/37c004c2-0d56-11e6-96d9-efc383528fa5.png)

I'm also watching a contract for the DigixDAO Crowdsale. This used to work fine in previous versions, but now when I click to watch the contract, the interface no longer shows (even though I have the necessary JSON code provided). I'll be unable to claim any tokens until this issue is fixed =(

![screen shot 2016-04-28 at 15 38 05](https://cloud.githubusercontent.com/assets/16994153/14889589/53a6328c-0d57-11e6-90f8-a6defb78fe71.png)

Some people have said that the contract interface has just 'popped up' after 10 minutes, but I've left it much longer than that and nothing appears.

- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.

![screen shot 2016-04-28 at 15 40 23](https://cloud.githubusercontent.com/assets/16994153/14889663/a5cc81ba-0d57-11e6-9a7d-528494518343.png)

- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)

I0428 15:07:48.817861   14886 database.go:71] Alloted 433MB cache to /Users/xxxxxxxxxx/Library/Ethereum/chaindata
I0428 15:07:50.400638   14886 database.go:71] Alloted 78MB cache to /Users/xxxxxxxxxx/Library/Ethereum/dapp
I0428 15:07:50.433463   14886 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0428 15:07:50.523903   14886 backend.go:362] Blockchain DB Version: 3
I0428 15:07:50.567113   14886 blockchain.go:214] Last header: #1419771 [2e45b538…] TD=16151657423178783042
I0428 15:07:50.567154   14886 blockchain.go:215] Last block: #1419771 [2e45b538…] TD=16151657423178783042
I0428 15:07:50.567167   14886 blockchain.go:216] Fast block: #1419771 [2e45b538…] TD=16151657423178783042
I0428 15:07:50.577915   14886 handler.go:92] blockchain not empty, fast sync disabled
I0428 15:07:50.601315   14886 cmd.go:115] Starting Geth/v1.3.6/darwin/go1.5.1
I0428 15:07:50.601450   14886 server.go:311] Starting Server
I0428 15:07:51.196048   14886 udp.go:212] Listening, enode://537138248fb17084ad0cdea274a8a4a0c75b8633526a152639ab68068e65251ff74bb6858cbb9dfed6e7dc4ecf158c45717b301d0899db7a5e2e7a969cc21d13@[::]:30303
I0428 15:07:51.196250   14886 backend.go:526] Server started
I0428 15:07:51.196242   14886 server.go:552] Listening on [::]:30303
I0428 15:07:51.208716   14886 ipc.go:112] IPC service started (/Users/xxxxxxxxxx/Library/Ethereum/geth.ipc)
I0428 15:08:11.198575   14886 downloader.go:288] Block synchronisation started
I0428 15:08:37.205877   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 222 txs in 25.388636345s. #1419772 [e9bfa68a / e9bfa68a]
I0428 15:11:41.087289   14886 blockchain.go:1251] imported 27 block(s) (0 queued 0 ignored) including 783 txs in 3m3.823377238s. #1419799 [ffce7008 / e6a5d8ac]
I0428 15:11:41.458959   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 133.856048ms. #1419800 [43c03d38 / 43c03d38]
I0428 15:11:43.150769   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 22 txs in 1.558291643s. #1419801 [cb13006e / cb13006e]
I0428 15:11:43.330742   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 124.333745ms. #1419802 [b2e6dd93 / b2e6dd93]
I0428 15:11:43.531018   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 120.305676ms. #1419803 [e42275d2 / e42275d2]
I0428 15:11:52.982857   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 65.489919ms. #1419804 [983e9ba1 / 983e9ba1]
I0428 15:11:53.262454   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 275.582319ms. #1419805 [4fef1443 / 4fef1443]
I0428 15:11:53.349841   14886 blockchain.go:1251] imported 3 block(s) (0 queued 0 ignored) including 3 txs in 87.289177ms. #1419808 [7db01838 / 7d11324a]
I0428 15:11:58.204188   14886 blockchain.go:1251] imported 7 block(s) (0 queued 0 ignored) including 15 txs in 702.8233ms. #1419815 [66973cb3 / b4df5a89]
I0428 15:11:58.207987   14886 blockchain.go:1251] imported 0 block(s) (0 queued 1 ignored) including 0 txs in 3.715423ms. #1419809 [66973cb3 / 66973cb3]
I0428 15:12:31.386643   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 180.06752ms. #1419816 [416793d3 / 416793d3]
I0428 15:13:11.778672   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 26 txs in 149.725843ms. #1419817 [5d83de53 / 5d83de53]
I0428 15:13:14.809110   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 25 txs in 27.90339ms. #1419818 [84fdf9ab / 84fdf9ab]
I0428 15:13:16.977496   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 4 txs in 25.869593ms. #1419819 [2fc5dd72 / 2fc5dd72]
I0428 15:13:28.512760   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 34.850721ms. #1419820 [9e1a725c / 9e1a725c]
I0428 15:13:40.593334   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 6 txs in 75.366969ms. #1419821 [6826246b / 6826246b]
I0428 15:13:46.838907   14886 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 8 txs in 10.809054ms. #1419822 [a1c8bf4f / a1c8bf4f]

**Comment by frozeman** [comment]
Very strange, but from the logs it seems all fine..

**Comment by dodgers76** [comment]
Contract Address: 0xf0160428a8552ac9bb7e050d90eeade4ddd52843
JSON Interface: https://gist.githubusercontent.com/tymat/11887bc55c6670c92902f46a874cd6fd/raw/1c258e340383c257dc4b775962aa2d70da4c2675/Crowdsale.json

**Comment by dodgers76** [comment]
If I wanted to reinstall the Mist wallet completely in case there is a conflict anywhere, would it be safe to remove the user files in the following folders:

~/Library/Application Support/Mist
~/Library/Ethereum (apart from the Keystore folder)

**Comment by cheeseco2** [comment]
I'm having the same exact problem but on Ubuntu linux. Have we figured out a solution yet?

**Comment by jacogr** [comment]
This is related to all the other Mac issues that has been logged since 0.5.0. Unfortunately it has not been broken for a while with no progress. Well, will keep downloading each new release to continue trying.

BTW, it is not just on El Capitane, I have an older Mac that does exactly the same as well as an 10.11 version - so 0/2 working Macs in my household. As the reporter mentioned (and as mentioned in all the other bugs reported), geth works perfectly in the background, Mist just doesn't like it.

**Comment by dodgers76** [comment]
@frozeman everything appears to be working as expected with Mist 0.7.3 & 0.7.4, and Geth 1.4.4

**Comment by luclu** [comment]
awesome! I will close this.
