### ISSUE TITLE
wallet contract notifying random non-related transactions

### ISSUE THREAD

**Issue by newmzy** [ethereum/mist#522]
Node type: geth
OS: Windows 10 64 bit
Network type: main
Ethereum-Wallet-win64-0-7-2

I created a "wallet contract" in addition to my "account 1" just for interest sake, to see the difference of being able to see where transactions came from, etc. I use the "account 1" mainly as a destination for ether that I'm mining with some GPUs, so I thought I might use a "wallet contract" to differentiate payments coming from a mining pool, from those I may make myself by exchanging bitcoin for ether, etc.

Since I created the wallet contract which I named "newmz" (which is a personal nickname) - I frequently see popups about transactions, commonly for 100 ether being payed to me, or payed from me, to and from other addresses. Thankfully the actual balance of my account doesn't change - although it would be great if the 100 ether payments to my account were real! In the attached picture, none of the listed transactions were made by me and none of them had any effect on my balance. Where are they coming from?
![wallet_transactions](https://cloud.githubusercontent.com/assets/17661766/14938282/084da6de-0f51-11e6-9225-5b14d4ab78e4.jpg)

I tried to find a log for the wallet in the mist log folder but the log files are very short and just seem to repeat the startup of geth.

I'm just using the wallet, not Mist browser so I'm not sure where/how to use its console if it has one.

**Comment by luclu** [comment]
duplicate: https://github.com/ethereum/mist/issues/568

**Comment by luclu** [comment]
@newmzy can you kindly provide the transaction hashs of the 100 Ether transactions?

**Comment by luclu** [comment]
Closed as of inactivity.
