### ISSUE TITLE
Importing wallet in Mist

### ISSUE THREAD

**Issue by buha** [ethereum/mist#523]
Node type: eth
OS: Linux (Manjaro)
Network type: main
Mist version: 0.7.2

1. I moved one file from **.ethereum/keystore** and Mist interface correctly displayed only the remaining wallets. Then I drag-dropped the file into the Mist import window but it seems to never finish. It's been running for an hour. Is this normal?

2. Also, the white rectangle in the screenshot should display something relevant but I think it doesn't work well with my Gnome Dark theme so I can't see the content.

3. Is it normal that **Accounts->Backup->Accounts** only opens the file manager to **~/.ethereum**?

![screenshot from 2016-05-01 11-56-09](https://cloud.githubusercontent.com/assets/8933663/14941210/c1c99f40-0f93-11e6-9d21-7315a96d9e1c.png)

**Comment by luclu** [comment]
Please check if this behaviour still occurs on version 0.7.4 / geth 1.4.4 and make sure to follow through #669 - report on the outcome!

**Comment by luclu** [comment]
I will close this for now, but feel free to discuss a resolution for your problem with me.

**Comment by buha** [comment]
Hey, sorry for lag.
Actually, I thought the import may work with any file under **keystore** directory. No, I don't really have a pre-sale wallet so I just fed it a wallet that I created with the Mist Browser.

However, in 0.7.4 the graphics are the same, big rectangle hiding the what follows *file named*. Might have something to do with Gnome 3.20?

**Comment by luclu** [comment]
Try to just move it back to the `keystore`-folder, does this work?

For the other points the corresponding issues are those:
2. https://github.com/ethereum/mist/issues/702
3. https://github.com/ethereum/mist/issues/288

**Comment by buha** [comment]
Yes, moving back to keystore works like a charm.
I'll follow #702 for now. Thanks @luclu

**Comment by luclu** [comment]
Awesome. Then it is another bug. ;)
I created an issue here https://github.com/ethereum/mist/issues/714.
If you are interested you can follow the issues by subscribing to them (on the right pane).
