### ISSUE TITLE
Mist disagreeing with (etherscan.io && live.ether.camp) over tx outcome

### ISSUE THREAD

**Issue by vogelito** [ethereum/mist#528]
I've been testing the Multisig wallet in Mist and have been making deposit attempts with little gas, lots of gas, etc... and I think I've found a bug.

Some transactions show as invalid in Mist, but both [etherscan.io](https://etherscan.io) and [live.ether.camp](https://live.ether.camp) believe the tx execution was successful.

All three agree on the total balance of my account. Even though Mist doesn't show the right fundings...

Mist is saying:

> Transaction 0x8fabd7a91ca45352ca3b38f579947fbf86f42ecff4c41270ab97d2534c78e8a1
> THE TRANSACTION DIDN'T SEEM TO HAVE ENOUGH GAS TO EXECUTE

However, [etherscan](https://etherscan.io/tx/0x8fabd7a91ca45352ca3b38f579947fbf86f42ecff4c41270ab97d2534c78e8a1) reports:

> No errors detected during contract execution

And [live.ether.camp](https://live.ether.camp/transaction/8fabd7a91ca45352ca3b38f579947fbf86f42ecff4c41270ab97d2534c78e8a1) show it as:

> Complete

I'm on MacOSX
vogelito$ /Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth version
Geth
Version: 1.3.6
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.5.1
OS: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.5.1/libexec

Mist version: 0.6.2

**Comment by luclu** [comment]
@vogelito could you kindly check if this behaviour still surfaces with 0.7.4?
Also what parameters are you using?

**Comment by vogelito** [comment]
@luclu Here's the step-by-step of what I did:
1. I downloaded 0.7.4 in my MacOSX
2. Copied the binary to my Applications folder
3. Double clicked the binary
4. Opened the account where the issue lives and found the transaction I reported above
5. Clicked on the transaction to get the "Transaction" pop-up

I can confirm that it still has the same legend:
`THE TRANSACTION DIDN'T SEEM TO HAVE ENOUGH GAS TO EXECUTE.`

If you need/want me to provide additional data/information or do something else, I'd be happy to do so.

**Comment by luclu** [comment]
thank you @vogelito, sorry for not beeing clearer on this...
Are you able to reproduce this behaviour with a new transaction?

**Comment by shakneymons** [comment]
Hi @luclu and @vogelito  - I've had a similar issue - lower gas transactions than the 'default' setting have seemed to fail in Mist and are not shown on the transaction log but have been successfully recorded on etherscan and live.ether.camp. This is with version 0.7.4. 

I used Mist to buy DAO tokens with Ether, but only two of the four 'send' transactions have shown up in Mist 0.7.4 (both of those shown transactions were made with the 'Select Fee' at the default settings). The other two transactions Mist appeared to hang, I left Mist overnight on one of them, then I restarted it, but then they both went through at the same time as my last successful transaction according to Etherscan. I'm also running Mist on MacOS X El Capitan

Geth
Version: 1.4.4-stable
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6
OS: darwin
GOPATH=
GOROOT=/usr/local/go

As stated above, Live.ether.camp and Etherscan.io both register that all four transactions were successful and the DAO has registered that I have the right amount of tokens on https://daohub.org/creation.html. It's just Mist that's not showing up the other two transactions that appeared to fail on the transaction list. However, the amount of Ether in my account corresponds to the original amount minus all four transactions (as it should be).

I'm new to it all, but hope this made sense.
@luclu  Please let me know if you need more info.

**Comment by vogelito** [comment]
hi @luclu - yes, I just replicated this behavior with the following transaction: http://etherscan.io/tx/0xeb59a3f910315e02c8aaef7baeb9dfff2f8405ad14983b6d8cf6aabf13606294

Mist reports it as: "THE TRANSACTION DIDN'T SEEM TO HAVE ENOUGH GAS TO EXECUTE"
Etherscan and others are OK with it.

I would be more than happy to provide any additional details.

**Comment by vogelito** [comment]
I just upgraded to Mist 0.8.0 and can confirm this is still an issue.

**Comment by jakerich** [comment]
I am running 0.8.7 and can recreate this issue. I have three transactions in my "Latest Transactions" that say they did not go through. But they did. How do I clear these log messages?

**Comment by alexvandesande** [comment]
Issue here was that Mist was treating using 100% of the gas as out of gas errors
