### ISSUE TITLE
Is it possible to remove version string from built packages?

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#529]
- Node type: any
- OS: linux (arch linux)
- Network type: any
- Mist version: any

Hi there. I'm the package maintainer for several Ethereum packages in Arch Linux User repository, this also includes Mist (releases) and Mist-git (latest). I have trouble to keep installing the latest mist version from git because I have a hard time to notice when the version string keeps changing.

    cp -a "${srcdir}/${pkgname}/dist_wallet/Ethereum-Wallet-linux${_arch}-${_pkgver}/." "${pkgdir}/usr/share/${_pkgname}"

While figuering out the `$_arch` part is easy, the `$_pkgver` seems to change unpredictable. The only thing I can do about this, is checking daily if the install script still does work (or if it breaks).

Is it possible to remove version string from built packages? Or is that something electron-specific?

For reference, this is the [install script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mist-git#n85) and this is the [package at arch linux user](https://aur.archlinux.org/packages/mist-git/) repository.

**Comment by hiddentao** [comment]
The `$_pkgver` part is something we add. The version string represents the version of Mist and follows the semantic versioning standard. What difficulties do you have with it?

**Comment by luclu** [comment]
Right now version string resembles:
`0.7.2.r1.g80ec64f-1` on **Mist-git** on AUR
`0.7.2-1`                     on **Mist** on AUR
So basicly CI seems to add git-commit-hashes.

**Comment by hiddentao** [comment]
The first 3 numbers (x.y.z) of the version string are the ones that count. Would it be possible to just check those and ignore the rest?

**Comment by luclu** [comment]
https://wiki.archlinux.org/index.php/PKGBUILD#Version

**Comment by 5chdn** [comment]
@luclu please stop the confusion. I'm not talking about the github tags.

@hiddentao I'm talking about the install path.

Which basicly is _./mist/dist_wallet/Ethereum-Wallet-_ **linux64-0-7-3** _/Ethereum-Wallet_

> The `$_pkgver` part is something we add. The version string represents the version of Mist and follows the semantic versioning standard. What difficulties do you have with it?

Why are you adding it? 

Difficulties are:

- I can't determine the version string from github tags programmatically
- I can't install the binaries in Archlinux without knowing where to get them from
- I always have to verify the install script works on a daily basis because the version string seems to change without any warning. 

For insance, the git package version `0.7.2.r1.g80ec64f-1` has a version string of `0-7-3`. Do you understand what I mean?

**Comment by hiddentao** [comment]
@5chdn Understood. I'm sure we can modify our build script to not add the version string at the end. 

@frozeman Any reason why we append the version string?

**Comment by frozeman** [comment]
We add the version here: https://github.com/ethereum/mist/blob/master/gulpfile.js#L298

I add this so that people, who download a new version, know which one it is and can maintain a folder with previous versions, without that they overwrite each other.

I don't really understand where you get the git-tag from, and how is this confusing your script.
The builds are done manually, as well as the version change.

I would like to keep that in the file name, but we might do something about the mismatch in the version scripts.

I also don't understand why you run that script daily, if we only create builds so and so often.

**Comment by frozeman** [comment]
If youre trying to build develop, i mostly increase there already the version number in the `package.json`, from which the build script takes the version number.

Where do you get the tag version from?

**Comment by 5chdn** [comment]
> Where do you get the tag version from? 

      git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'

Okay, I could just patch the gulpfile for now in Line 87 to remove the version string in the path before building the wallet. https://github.com/ethereum/mist/blob/master/gulpfile.js#L87

Or I read the version number from the package.json. Thanks for the pointers.

I guess I can live with that workaround. I see there are valid reasons for including the version in the path for users manually building the wallet.

**Comment by 5chdn** [comment]
FYI, I'm using this patch as a workaround for now. https://aur.archlinux.org/cgit/aur.git/tree/mist-pathfix.patch?h=mist-git

**Comment by luclu** [comment]
@5chdn I will close this for now as a wontfix - though the naming scheme might be changed in the future.
