### ISSUE TITLE
Cannot set input data for bytecode deploys

### ISSUE THREAD

**Issue by karalabe** [ethereum/mist#532]
If I specify the bytecode of a contract to deploy, I have no means to input the constructor parameters into Mist. This might lead people to deploy non-initialized contracts wasting precious ether. I'm aware that we need the ABI to decode the constructor params, but I think that should be essential, otherwise we're going to find a lot of angry users.

**Comment by slash686** [comment]
Any progress on this?

**Comment by alexvandesande** [comment]
Is there still a good use case for byte code deployment with ABI in Mist?
