### ISSUE TITLE
Solidity compiler version missing

### ISSUE THREAD

**Issue by karalabe** [ethereum/mist#534]
One of the most important features is the ability to verify deployed contracts. However mist does not display the Solidity compiler version it uses to deploy a contract, so afterwards it's extremely hard to guess which version it was and have the contract verified by block explorers. I think we should definitely have the version number displayed when working with solidity code directly.

**Comment by evertonfraga** [comment]
Hi @karalabe, how exactly would be the best way to display Solidity version?

Only a small text around the editor would suffice? Or embed this information alongside with the contract, in some way?

**Comment by luclu** [comment]
@evertonfraga I guess the formal will be the way to go. While embedding it in some standardized way would be awesome. Is there some EIP on this? Also is there a meta-data section within contracts?

To accomplish the former we might want to use the compiler version key-value pair from the resulting `web3.eth.compile.solidity()` object ([compileContract.js#L162](https://github.com/ethereum/meteor-dapp-wallet/blob/develop/app/client/templates/elements/compileContract.js#L162)) to be node agnostic:

```javascript
var testSource='contract Test {  function double(int a) constant returns(int) { return 2*a; } }'
var testCompiled = web3.eth.compile.solidity(testSource);
console.log(testCompiled)
```
```javascript
{ Test: 
   { code: '0x6060604052602a8060106000396000f3606060405260e060020a60003504636ffa1caa8114601a575b005b6002600435026060908152602090f3',
     info: 
      { source: 'contract Test {  function double(int a) constant returns(int) { return 2*a; } }',
        language: 'Solidity',
        languageVersion: '0.3.6',
        compilerVersion: '0.3.6',
        compilerOptions: '--bin --abi --userdoc --devdoc --add-std --optimize -o /var/folders/1r/vtmg53tn17g9m35zd64lyczh0000gn/T/solc777625456',
        abiDefinition: [Object],
        userDoc: [Object],
        developerDoc: [Object] } } }
```

**Comment by luclu** [comment]
This might be obsolete due to solidity's version-pragma requirement.
