### ISSUE TITLE
Deploying a contract from bytecode doesn't add a watch for it

### ISSUE THREAD

**Issue by karalabe** [ethereum/mist#537]
If I deploy a contract from Solidity code, it's automatically added as a watched contract. However if I deploy from bytecode, no contract is added to be watched. The reason is similar to the constructor particularization issue that the ABI is missing. I however think that it should be requested from the user and added as a watch. Without the ABI doing bytecode deploys isn't particularly useful. With it however it does become useful.

(Side note, it's important to allow bytecode deploys to enable using local compilers and/or bytecode opposed to some baked in version from the wallet).

**Comment by stvenyin** [comment]
EVM only Excute  Internal Transcation

**Comment by stvenyin** [comment]
or ABI  is missing constructor  
function。
