### ISSUE TITLE
Client lock up / MacOSX

### ISSUE THREAD

**Issue by clund** [ethereum/mist#542]
Node type: geth
OS: osx
Network type: main
Mist version: 0.7.0

Client locks up for 30+ secs when selecting (clicking on) a Contract (to watch) and then locks up every so often while displaying the contract.

**Comment by clund** [comment]
Issue remains in 0.7.2. Could be related to sync'ing, since there is also a long freeze when the client opens.

**Comment by luclu** [comment]
Thank you, this is supposed to be fixed in the next release.
See this [Pull-Request](https://github.com/ethereum/meteor-dapp-wallet/pull/161). ;)

**Comment by luclu** [comment]
I will close this for now as this issue has been resolved in 0.7.4.
If you still encounter problem I will reopen!
