### ISSUE TITLE
Not showing DAO token balance

### ISSUE THREAD

**Issue by clund** [ethereum/mist#543]
Node type: geth
OS: osx
Network type: main
Mist version: 0.7.0

DAO tokens are not showing after adding a new custom token (to watch). Tokens acquired from wallet address and confirmed on daohub.org, but not showing up under custom tokens:

![screen shot 2016-05-02 at 15 41 38](https://cloud.githubusercontent.com/assets/1596463/14955745/5de8eba4-107c-11e6-9176-b6615e9e7bf1.png)

Followed the guide found here : https://forum.daohub.org/t/faqs-about-the-d-q-a/37

**Comment by super83** [comment]
Try update your wallet to the current version: 0.7.2
It work for me with the new update version.

**Comment by clund** [comment]
Does the trick, thanks!

Also lists the tokens under the Send tab.
