### ISSUE TITLE
Function deposit - UX improvement suggestion

### ISSUE THREAD

**Issue by randomobserver** [ethereum/mist#55]
Deposit button opens a transfer screen with destination and source fields filled automatically. Now, the default behaviour is to set the source address as the recently created account, which leads to the scenario where source field == destination field. Maybe it would be better to set the source always to some other local address with balance > 0 and if such doesn't exist the wallet should inform user that she has to buy ether or mine or import private keys of an account with non-zero balance.

**Comment by frozeman** [comment]
we add than you will always have the source being the accounts page you cam from. this should help with this as well.
