### ISSUE TITLE
Add password visibility toggle on creation

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#554]
For accessability and control reasons as requested in https://github.com/ethereum/mist/issues/241 and #596.

Already implemented on onboarding-screen but missing on in-wallet account-creation.

**Comment by luclu** [comment]
Ongoing PR: https://github.com/ethereum/mist/pull/893

**Comment by luclu** [comment]
@evertonfraga could you have a look at this while implementing that new screen?

**Comment by evertonfraga** [comment]
@luclu sure! 👍

**Comment by luclu** [comment]
ongoing PR: 814

**Comment by luclu** [comment]
merged with #1023
