### ISSUE TITLE
Problem seeing my DAO tokens into MIST

### ISSUE THREAD

**Issue by Constantin22** [ethereum/mist#556]
I have a problem seeing my DAO tokens in my MIST account.

I bought my tokens from a JAxx account and then i imported the jaxx account into my MIST. The problem is that i can't see them in my account. I bought some DAO tokens directly from my MIST account and i can see them but the ones bought with my JAXX account i can't.  I will appreciate if anyone can help me.

**Comment by SWKStudios** [comment]
This might be related to JAXX giving out a new address for each new deposit. If your funds are broken down into several addresses then you might have sent out funds via several address instead of just one.

http://themerkle.com/using-the-jaxx-wallet-for-crowdsales-and-token-purchases/

Maybe someone else will help you more, but keep in mind your tokens are probably associated with several addresses.

**Comment by Constantin22** [comment]
I've done everything by the book, i imported the Jaxx account into MIST. The Token doesn't appear. My MIST seems to work properly since i bought some DAO directly from it and they appear, but the ones i bought via Jaxx account, not.

**Comment by Constantin22** [comment]
My tokens are associated with one address that i found in my transaction history in my JAXX, but after i imported my jaxx account in my MIST i still cannot see my tokens

**Comment by alexvandesande** [comment]
We had issues with tokens display on version 0.7.1 Have you updated to 0.7.2?

**Comment by actuallymentor** [comment]
Had the same issue, 0.7.2 works though. The 0.7.2 release though gives an 'unidentified developer' warning on mac. Forgot to sign?

**Comment by Constantin22** [comment]
I use the 0.7.2 version. After i imported the JAXX account into my MIST, the account appear but can't see my tokens.
 I transfer an small amount of ETH from POLONIEX into my MIST. My smartphone aplication saw them in my account, ask me if i want to transfer the amount from my HD account into my NON HD account, i ve done that and the amount are into my phone aplication.
 Also i bought a small amount of DAO directly from my MIST, and those tokens are visible. The only problem it s that i can't see my bought from my jaxx smartphone aplication. 

NO ONE can tell what to do.

**Comment by Constantin22** [comment]
@alexvandesande . Indeed i've an mistake first when i want to watch token. On the contract address i put the address where i can see my tokens not the contract address where i send the tokens(daohub). An grey label appear but i can't interact with it. Could be the problem?
![screenshot_3486723857623485762345](https://cloud.githubusercontent.com/assets/19175935/15042822/09be6b7a-12d0-11e6-9de9-0699b2fc8708.png)

**Comment by alexvandesande** [comment]
@Constantin22 The greyed out DAO is a contract that is not on the main chain. Maybe a testnet thing? I don't know what the 0x3ddb3.. contract has

**Comment by Constantin22** [comment]
@alexvandesande 0x3dDB3dA60Ac5dB24904F58e60571Ae74404C7c94 this is the address where i can see my tokens i put it on "contract address" by mistake.

**Comment by alexvandesande** [comment]
Ok, then that's a different issue we have to fix which is how to delete unwanted disabled contracts: https://github.com/ethereum/mist/issues/530

If that's the only issue remaining I'd like to close this one

**Comment by Constantin22** [comment]
No. that's one of the issues. I don;t know if this is the reason that i can't see my tokens in MIST. I just suposse thet could be the issue, but i'm not 100% sure.

**Comment by Constantin22** [comment]
Ok i've done it. It seems tha i have to import another private key related with the address. Now the only problem remain how to delete unwanted contracts. Plus, i have some unicorns who disapear.

**Comment by luclu** [comment]
@Constantin22 please have a look here on how to delete unwanted contract with the console: https://github.com/ethereum/mist/issues/686#issuecomment-221383570

**Comment by luclu** [comment]
I will close this for now.
