### ISSUE TITLE
Mist syncs on open but then stops syncing as soon as homepage launches

### ISSUE THREAD

**Issue by bamos01** [ethereum/mist#558]
Node type: geth
OS: OSX
Network type: main
Mist version: 0.7.2

Screenshot of my console log:

![screenshot 2016-05-04 06 30 54](https://cloud.githubusercontent.com/assets/8769182/15011986/0966ab96-11c3-11e6-8752-eb58cb257a24.png)

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by tayvano** [comment]
1 reports of same happening on El Capitan here: https://www.reddit.com/r/ethereum/comments/4hsv88/problem_with_sending_from_the_ethereum_wallet/

2 reports of same happening on Yosemite 0.7.2 here: http://ethereum.stackexchange.com/q/3606/300

**Comment by bamos01** [comment]
some more info- the blocks seem to be dowloading in the background (When i restart its up to date) and geth works fine on this computer.  The problem is that the new blocks stop updating as soon as the home screen shows.

**Comment by Walkingmage** [comment]
I have the same issue on Windows 7 x64 with mist 0.7.2.
I have also tried to run geth-1.4.0-rc-8241fa5-windows-4.0-amd64.exe (with mist) with the same result.

**Comment by Walkingmage** [comment]
If I run geth-1.4.0-rc-8241fa5-windows-4.0-amd64.exe mist starts syncing after a few minutes

**Comment by davebryson** [comment]
Seeing the same exact error on El Capitan with Mist 0.7.2.  It's a problem whether I run mist with the included geth or a separate instance of geth.   Blockchain is actually in sync but the UI is out of sync.  Overall the UI seems a bit more sluggish compared to previous versions.

**Comment by Walkingmage** [comment]
Syncing works for me if I use geth-1.4.1-rc-4b9de75 with mist on Windows

**Comment by bamos01** [comment]
Confirming that It works for me too after upgrading to geth 1.4 and then attaching mist to separate geth instance

**Comment by ZedsterX** [comment]
I am having the same problem as davebryson states above.  The program opens and syncs up but then stops syncing.  This was actually happening to me on 0.5.2. I then upgraded to 0.7.2 with the same results.  This happens with the included node or if i run my own.  I am running geth version 1.4.3 (just out minutes ago) on win 7 64bit

**Comment by dwking2000** [comment]
Having same issue. Wallet syncs on startup and then refuses to process new blocks as soon as home screen is up. If I attempt to send ETH, I see the message that says "can't estimate your gas usage" in the UI. I try to send anyway and transaction fails.  If I open the Console I see this error regarding IPC Connection:

IPC Connection Error Object"": code: "EPIPE"errno: "EPIPE"syscall: "write"__proto__: Object(anonymous function) @  Ethereum-Wallet-macosx-0-7-3/Ethereum-Wallet.app/Contents/Resources/app.asa…:17

Wallet 0.7.3
OSX Yosemite 10.10.5

In the past weeks I was able to run geth in background via cmd line and with the previous version of Mist I was using (before 0.7.3) was able to connect to geth and I was able to send ETH. Previous version of Mist did not sync on it's own, so I had to run geth in background. Version of geth that I was using and still using now is: 1.3.6

**Comment by tayvano** [comment]
@dwking2000 the gas usage is a different issue that results in attempting to "send everything" to a contract. Send a hair less than everything and it should go thru. 

I am still on 0.7.2 and 1.3.6 and able to sync using geth, as long as I'm not watching the dao contract. Sometimes I have to restart mist a couple of times to get the UI to update though.

**Comment by dwking2000** [comment]
@tayvano In my case I am not sending everything, just a .5 test ETH to another address I own.

**Comment by dwking2000** [comment]
Fixed my problem. @tayvano Thanks for the suggestion about the DAO contract. I was not watching the contract because I had read there were issues with watching it, BUT I *DID* have theDAO token under Watch Token.

I just removed theDAO token from Watch Token and restarted Mist. Now Mist is syncing on it's own (I did not run geth in the background).

I sent test eth to myself and everything went smoothly.

**Comment by luclu** [comment]
Please update to version 0.7.4. which includes geth 1.4.4 (6 months of improvements). Please ping me back on the outcome!

**Comment by ZedsterX** [comment]
I personally had my account hacked shortly after getting the wallet working and I minutes after. I lost all my ether.  I am forced to give up

**Comment by bamos01** [comment]
This works!!
