### ISSUE TITLE
Splash window is positioned inappropriately and can't be moved

### ISSUE THREAD

**Issue by tom-seddon** [ethereum/mist#56]
(This may be related to #49.)

Running mist in a Linux VM. X server is XQuartz 2.7.8 on Mac OS X

The splash window comes up in an annoying place (as if it just looks at the desktop rect to decide where to put it, rather than asking Xinerama/XRandR/etc. for display details), and it can't then be moved.

Thanks,

--Tom

Photo of offending window:

![mist_splash](https://cloud.githubusercontent.com/assets/1269020/10576417/0c6716c2-765b-11e5-953a-ea57a76caa58.jpg)

My display arrangement:

![my_screens](https://cloud.githubusercontent.com/assets/1269020/10576421/0fef2762-765b-11e5-9246-3d458dae0b4d.png)

**Comment by frozeman** [comment]
Thanks for that screen.
We position it entered in the screen, and i guess this is problematic for the linux window manager.

**Comment by hiddentao** [comment]
Why do we need the splash window to show separately like that? What if we just show the full window with a splash view in the middle? In my opinion this would also give people confidence that the app has started up properly. It will also allow us to optionally show more info during the splash process.

**Comment by luclu** [comment]
@hiddentao though that would not solve the problem (yet) as the electron shell doen't remember its last position.

Besides this problem isn't something new but actually depends on the window manager or even deeper the display server as with X and its Xinerama mode for multi-heads (merging multiple monitors to one logical).

Perhaps this route could be worth a shot `electronScreen.getPrimaryDisplay()` for non Xinerama-like modes as OP seams to have.

**Comment by luclu** [comment]
@tom-seddon do you still encounter this issue with `0.8.1` (electron `1.2.5`)?
