### ISSUE TITLE
Bump extremly slow sync #518

### ISSUE THREAD

**Issue by robonix** [ethereum/mist#566]
pleas review issue #518 - I don't know if bumping is allowed here (if not I understand that this post will be deleted) but I'm quite anxious about missing the chance of being ahead of the curve of those that learn how to program solidity before it becomes popular. As a result I want to get started ASAP but my ethereum wallet won't sync up :(

**Comment by robonix** [comment]
seems like #545 is referring to the same problem

**Comment by luclu** [comment]
Thank you @robonix. I'm definietly with you on this one. 
The Mist and Go-Team are aware of this issue. There are currently ongoing efforts in geth. 
Please try to run the [RC release](https://github.com/ethereum/go-ethereum/releases) of geth (1.4.1) as this contains 6 months of substantial changes under the hood.
Please give me a small ping back on things.

**Comment by luclu** [comment]
I will close this for now assuming geth 1.4.4 (bundled in 0.7.4) solved this for you and as this is a duplicate. ;)
