### ISSUE TITLE
Check Incoming and Outgoing wallet address

### ISSUE THREAD

**Issue by HelixiR** [ethereum/mist#567]
Node type: geth
OS: windows
Network type: main
Mist version: 0.7.2

Disallow send coins from ACC1->ACC1.
Check if wallet Outgoing have same address Incoming wallet.

**Comment by luclu** [comment]
@HelixiR could you kindly close this issue and reopen it on the [wallet dapp's](https://github.com/ethereum/meteor-dapp-wallet) repository?

**Comment by luclu** [comment]
Moved it.
