### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lfranken** [ethereum/mist#569]
For some reason when transfering ETH to DOAorg I get this error.
Any idea what I can do?

![schermafbeelding 2016-05-05 om 22 24 46](https://cloud.githubusercontent.com/assets/19213521/15056196/b2753790-1310-11e6-995f-c231c13cf49b.png)

**Comment by luclu** [comment]
duplicate of https://github.com/ethereum/mist/issues/281

**Comment by alexvandesande** [comment]
duplicate
