### ISSUE TITLE
Splash window is a bit hard to read

### ISSUE THREAD

**Issue by tom-seddon** [ethereum/mist#57]
I found the splash window a bit hard to read. To my eyes, the text doesn't stand out very strongly at all against the background.

Thanks,

--Tom

![low_contrast](https://cloud.githubusercontent.com/assets/1269020/10576552/ee4935b6-765b-11e5-9d61-0a5031e9a9ea.png)

**Comment by frozeman** [comment]
We are not focusing on mist for now, so forgive the splash screen :) It will be changed.
@alexvandesande concerning the skip search, this is how it looks on windows and linux. It seems like the splash screen window is a bit smaller as on mac
