### ISSUE TITLE
Can't Import Wallet

### ISSUE THREAD

**Issue by bikerboy4489** [ethereum/mist#570]
Hi,

I'm hoping someone can shed some light on an issue I'm having. I recently downloaded the latest 7.2 wallet and since doing so my wallet (not account) has changed to 'view only' so I cannot touch the Ether that is in the account.

I assumed this was because I had to import the .JSON file as it shows which one of my previous accounts is the owner however I have left this running for over 24 hours and it doesn't seem to be importing.

I have attached a screenshot of the window that is displayed - the unique image on the right is changing rapidly as if it is searching for my account.
![importing wallet file](https://cloud.githubusercontent.com/assets/16919164/15067524/eb2baa44-1368-11e6-878f-1590b52844f0.JPG)

How long does this usually take or has something gone wrong?

Thanks

**Comment by luclu** [comment]
@bikerboy4489 thanks for reporting. As the wallet-importing won't take longer than some seconds there is something wrong.
Please give me some details to clearify.
Which version did you use before you switched to 0.7.2?
Have you already imported the json-file in question?
Is this the account that is greyed out and not usable right now?

**Comment by bikerboy4489** [comment]
Hi luclu.

Ok so that's a great question, originally I was using 0.7.1 before this which had the same issue. When I downloaded the latest version it wasn't prompting me for my password like it usually does to access the wallet, I believe this was due to it automatically opening Geth. When I switch the account to C + + it then prompts me for the password which then simply freezes on 'UNLOCKING' window and goes no further. It doesn't download the blocks at the top of the window and the wallet is greyed out as you mentioned...

I'm trying to move the Ether to an account so I can use it.

Thanks in advance

**Comment by bikerboy4489** [comment]
I did drag and drop the JSON file in to the \AppData\Roaming\Ethereum\keystore file as from what I understand this would mean that it would automatically be recognized as me being the owner of that wallet however this doesn't seem to be the case for me.

**Comment by callmetau** [comment]
I'vw had the same problem. Had to extract my private key and make the password easier for Mist to import my pre-sale wallet. I had lots of special symbols like'`~=!/ and so on. This bug is still not fixed... If you see "importing" at least your password is right.

**Comment by luclu** [comment]
@bikerboy4489, @callmetau please make sure you are using 0.7.2. 
If you do, try the following: https://github.com/ethereum/mist/issues/436
and give me a small ping-back on the outcome.

**Comment by luclu** [comment]
Also please have a look at this and report back here! #669

**Comment by luclu** [comment]
I will close this for now, but will stay here to assist you in problems regarding Mist/geth.
Also make sure to try this update of #669:
> if you still can't unlock your account try this service: https://www.myetherwallet.com (they implemented a "wallet viewer" following the official wallet-specs; it's client-side; source-code)
