### ISSUE TITLE
Malware infected Ethereum wallet directory on Mac

### ISSUE THREAD

**Issue by More-decentral** [ethereum/mist#574]
A malware called **win32:Duqu-K [Rtk]** has been found by anti-virus software Avast on my Mac.  It was found under: **~/Library/Ethereum/chaindata/449638.ldb**

After seeing this notice from the antivirus software, I was unable to launch my Ethereum wallet app. The app indicated that I needed to run some commands at terminal, but the commands were covered by white highlight so that I could not read them. So I didn't run the commands by copy-and-paste. 

Then I restarted my Mac to see if I can relaunch my Ethereum wallet app.   I was surprised to see that my Mac was unable to restart. The Mac stopped at the Apple logo screen with the thin installation bar paused at about 25%.  It won't continue even after a 15-minute wait.  

Have you encountered a similar situation like this?  Any advices on how to resolve this issue and prevent this happen again?  Thank you.

(I am planning to take my Mac to Apple store.)

Node type: geth
OS: osx 10.10
Network type: main
Mist version: 0.7.2

**Comment by alexvandesande** [comment]
merging it on #573
