### ISSUE TITLE
Cannot delete unwanted accounts in wallet

### ISSUE THREAD

**Issue by MrMontana** [ethereum/mist#577]
The title says it all.

**Comment by obscuren** [comment]
The titles leaves a lot to guess. Could you provide some details on what to do to reproduce your issue?

**Comment by MrMontana** [comment]
I set up 2 accounts in my wallet in addition to the ETHERBASE account but I want to delete one of the ones I set up and can't find an option to do so.

**Comment by Denton-L** [comment]
If you are running Linux or Mac, go into ~/.ethereum/keystore/ If you are running Windows, go to %APPDATA%\Ethereum. Open both files in your favourite editor. These represent your accounts and you can find the addresses listed as the first element in the JSON object.

You may delete whichever account you *do not* want and when you reload Mist, it will be gone.

**Comment by myownman** [comment]
I would like to see an in-app ability for this feature to increase UX, unless someone can tell me why it's less secure to include such an option.

Account clutter for newbies is a real problem, as evidenced by my girlfriend. Despite the possible consequences of drunken/random clicking about on the desktop, I see no reason not to pack it in to the next update.

If the reason this hasn't been dealt with for years is a fear of erasing a life sentence... is a HUGE, RED notification "ARE YOU THUPERDUPER SHURE? var BALANCE WILL BE LOST FOREVS" not enough to absolve any guilt to the dev that pushes this update?

**Comment by evertonfraga** [comment]
You can accomplish that by accessing: Accounts > Backup > Accounts. Then
you identify the file which name matches the address of the account tou
want to remove.

You just have to move the file out from that directory, and it'll do the
trick, doesn't need to delete the file.

**Comment by bracklanna** [comment]
This is really basic functionality that ought to be supported through the GUI.

Forcing users to dig around in JSON files to match wallet ID strings is a recipe for disaster.

**Comment by 3dianbiz** [comment]
In windows.

Go to:
C:\Users\(Username)\AppData\Roaming\Ethereum\testnet\keystore

Choose the file you want to delete...name similar to this "UTfdfsdfsdf51-38.603194500Z--5094749ew0d41dde548cbbd9c4dfdsfsdf097b9836c"
