### ISSUE TITLE
No Ethereum node binary found.

### ISSUE THREAD

**Issue by optonerd50** [ethereum/mist#578]
Node type: eth
OS: windows/
Mist version: 0.5.1

"No ethereum node binary found." That's the message I'm getting now. Was out of town for 11 days and needed to get Mist 5.1 going again. Was synching all day yesterday. But when I get back from dinner last night and re-started it, it gives me that message. Where did my binary go? Am using a Windows 8 laptop. Thanks

windows: %APPDATA%/Roaming/Mist/node.log
here goes

I0506 20:36:36.505332 2236 database.go:71] Alloted 433MB cache to C:\Users\SteveXXXX\AppData\Roaming\Ethereum\chaindata
I0506 20:36:47.350396 2236 database.go:71] Alloted 78MB cache to C:\Users\SteveXXXX\AppData\Roaming\Ethereum\dapp
I0506 20:36:47.398478 2236 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0506 20:36:47.461119 2236 backend.go:362] Blockchain DB Version: 3
I0506 20:36:47.493134 2236 blockchain.go:214] Last header: #1397235 [6d35a4e9…] TD=15442854853681856584
I0506 20:36:47.493134 2236 blockchain.go:215] Last block: #1397235 [6d35a4e9…] TD=15442854853681856584
I0506 20:36:47.493134 2236 blockchain.go:216] Fast block: #1397235 [6d35a4e9…] TD=15442854853681856584
I0506 20:36:47.525296 2236 handler.go:92] blockchain not empty, fast sync disabled
I0506 20:36:47.537303 2236 cmd.go:114] Starting Geth/v1.3.5/windows/go1.5.1
I0506 20:36:47.537303 2236 server.go:311] Starting Server
I0506 20:36:47.679097 2236 udp.go:212] Listening, enode://a974fd9bf3c61c20b31591bed370009a7bda56b86abe763aad89d9e262cb73705c74f3045b5ee9d982b49be53ad235ad19a08d3b89203ac852975f16ce42dfe0@[::]:30303
I0506 20:36:47.679097 2236 backend.go:526] Server started
I0506 20:36:47.680103 2236 server.go:552] Listening on [::]:30303
I0506 20:36:47.680103 2236 ipc.go:112] IPC service started (\.\pipe\geth.ipc)
I0506 20:37:17.680977 2236 downloader.go:288] Block synchronisation started
I0506 20:37:45.519085 2236 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 5.5299381s. #1397236 [798ca50a / 798ca50a]
I0506 20:37:52.390658 2236 blockchain.go:1251] imported 25 block(s) (0 queued 0 ignored) including 87 txs in 6.8705719s. #1397261 [4d9232d8 / 62741a89]
I0506 20:37:56.911273 2236 blockchain.go:1251] imported 8 block(s) (0 queued 0 ignored) including 71 txs in 4.519619s. #1397269 [0e4b1dc7 / dd7b12a1]

**Comment by luclu** [comment]
@optonerd50 How is the latest version [0.7.2](https://github.com/ethereum/mist/releases) behaving for you?
Also is it possible for you to use geth as a backend - as eth's support is currently only experimental and likely to break.

**Comment by optonerd50** [comment]
Thank you Luclu, I will be glad to try latest version.  Should I save the keystore folder?  Also I noticed another odd thing.  When I click on geth, the command prompt only comes up for a fraction of a second and closes.  Perhaps that is another symptom.

**Comment by optonerd50** [comment]
Found the node!  I went to my ethereum folder, resources/node/eth/ and clicked on eth.exe  Up came the dos command prompt.  Entered password.  Then I thought I'd try Ethereum-Wallet.exe.  It has found the node and is synching.  I lost quite a few blocks.  Took up at around 100,000.  But that is ok.
