### ISSUE TITLE
Ether Balance Not Updating

### ISSUE THREAD

**Issue by withtbird2** [ethereum/mist#579]
Node type: eth
OS: windows 7 64bit
Network type: main
Mist version: 0.7.2

I transferred ETH from Kraken to my new mist wallet then purchased DAO tokens. No problem. I did this a second time but the ETH from Kraken never "appeared" in my wallet (not updating). Etherscan shows all ok (below)
![image](https://cloud.githubusercontent.com/assets/19240549/15093141/215019e6-1433-11e6-8c6a-0c78a0fc310f.png)

I can see my correct balance on Etherscan...but not in my wallet...what to do?

**Comment by Neonian** [comment]
I have the same issue, but my was sent on the test network. blockchain explorer finds the transaction but it does not show up on my balance....
0x0A412CB4991C9c60d82C75382d70E5AaecDc3BE3 if anyone wants to check...
Have i done something wrong or....?

**Comment by withtbird2** [comment]
Here is my address: 0xFEdE0Cbaa5A05338569620813403e8CeECeDDDCE

For some reason only Etherscan has all 8 transactions listed. Etherscan has the correct wallet balance. I thought this build of Mist had this bug fixed.....Also, I have all of my DAO tokens on this wallet. Where can I stash them before this wallet just stops loading....

![image](https://cloud.githubusercontent.com/assets/19240549/15103224/9d594f5a-155d-11e6-8e56-e494a2037d50.png)

**Comment by withtbird2** [comment]
make that 9 transactions...

**Comment by withtbird2** [comment]
Neoian,

Did you receive any help? Any info???

Withtbird2

**Comment by Neonian** [comment]
not until now....got some other issues and no word on them either....I hope i get some feed back

**Comment by withtbird2** [comment]
It would not hurt if you downloaded Recuva onto a flash drive then from the
flash drive try to recover deleted files for the period in question. If
nothing else you can get a timeline of what was going on. Its laborious as
you may have to "click" on a few thousand files. Note: During recovery save
all files to an external drive, in the near term...while you sort things
out. I'm not sure if  restoring deleted files is a great idea as you may
overwrite a file that should otherwise not be overwritten (I'm just not
smart enough to answer that one).

**Comment by withtbird2** [comment]
Good news! If you go onto MyEtherWallet.com and open your Mist wallet using
your private key (.json file) you can access your ETH. Make sure you backup
your Mist wallet keys to a file...then access that file using
MyEtherWallet.com.

I got all my 1001 ETH back! So happy. Still not sure if my DAO tokens are
in danger.....

1) www.myetherwallet.com
2) click on View Wallet Info
3) ckick on Json or Keystore file
4) locate Json or Keystore file from your Mist wallet backup

This should allow you to see your Mist wallet balance

Use the "Send" Transaction" tab to send ETH back to yourself!
