### ISSUE TITLE
Bounty offer for Mist help

### ISSUE THREAD

**Issue by klm23** [ethereum/mist#580]
I can't get Mist 7.2 to work on my win10 64 machine. Posted all over the place, got many suggestions tried adjusting firewalls using a VPN, etc., etc...getting tired of writing about what is wrong and uploading screen shots. I am very heavily invested in ETH and The DAO crowdsale. Is there someone to whom I can please offer an ethereum bounty ahead of time to call me and trouble shoot with me over the phone?

ISSUE SOLVED I NEEDED TO RESYNC MY COMPUTER CLOCK WITH THE INTERNET

**Comment by 5chdn** [comment]
I can give you remote hands if you tell me how to contact you.

**Comment by klm23** [comment]
Thank you.  What would you like for a bounty and what do you need from me.
Phone number?--(I can call you to save you the expense) email is
kenmogul23@gmail.com, do I need to download software to make remote hands
work?  I have never used remote hands but I am somewhat familiar with "Team
Viewer" (that is already installed on my machine)

On Sun, May 8, 2016 at 8:12 AM, Afri Schoedon <notifications@github.com>
wrote:

> I can give you remote hands if you tell me how to contact you.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/mist/issues/580#issuecomment-217712773>
>



-- 
Ken Mogul
12768 Aviano Dr
Naples, FL 34105-4931
kenmogul23@gmail.com
Home: 239-384-9358
Text only-no voice (678) 664-8523

**Comment by FelixA** [comment]
Just using the 0.62 wallet seemed fine enough for me

**Comment by 5chdn** [comment]
for future reference, the issue was: https://github.com/ethereum/mist/issues/94 a.k.a. `no seed nodes found`. Had to start the client with verbosity `9` to get to that message.
