### ISSUE TITLE
Wallet!!!

### ISSUE THREAD

**Issue by MrMontana** [ethereum/mist#585]
Every time I open my wallet do I have to sync it? At this point it looks to take a few days!!!

**Comment by Denton-L** [comment]
Yes, the Ethereum blockchain is continuously growing (on average by one block every 12 seconds). If you do not leave your client open 24/7, it must sync to "catch up" with the state of the blockchain every time it's opened.

Alternatively, you may look for a so called "lightweight client". These clients can operate without having the whole blockchain so you would not have to spend as much time syncing up changes.

**Comment by luclu** [comment]
@MrMontana as @Denton-L pointed out [light-client-functionality](https://github.com/zsfelfoldi/go-ethereum/wiki/Light-Ethereum-Subprotocol-%28LES%29) is planned and will be added in several client-implementations - including [geth](https://github.com/ethereum/go-ethereum) (Mist's backend) - in the future. 
Unfortunately you will need to keep you blockchain synced until this is achieved.
