### ISSUE TITLE
Wallet stops syncing using ETH

### ISSUE THREAD

**Issue by Neonian** [ethereum/mist#589]
Node type: eth
OS: /windows 64
Network type: main/test
Mist version: 0.7.2.

When i start syncing the wallet, it just stops after a few blocks, left it over night to snyc but it didnt even get over 350k block. 
If i skip peer search and go straight to the wallet, it says i have 0% of the blockchain downloaded,
but somehow i got the whole test blockchain downloaded, but sadly it does not show my ETH balance.

![wallet](https://cloud.githubusercontent.com/assets/19249152/15118507/bbd7df46-160c-11e6-8a48-ba2644987fdd.png)

in console i get 4 errors; (when i open the console during the loading screen)

file:///C:/Users/Goran/Desktop/Ethereum-Wallet-win64-0-7-2/resources/sounds/bip.mp3 Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/Goran/Desktop/Ethereum-Wallet-win64-0-7-2/resources/sounds/bloop.mp3 Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/Goran/Desktop/Ethereum-Wallet-win64-0-7-2/resources/sounds/invite.mp3 Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///sockjs/info?cb=wd6ltrs1cf Failed to load resource: net::ERR_FILE_NOT_FOUND

Or if i skip peer search and then open the console;

Failed to load resource: net::ERR_FILE_NOT_FOUND
file:///C:/Users/Goran/Desktop/Ethereum-Wallet-win64-0-7-2/resources/app.as…/wallet/packages/ethereum_dapp-styles/fonts/SourceSansPro-ExtraLightIt.otf Failed to load resource: net::ERR_FILE_NOT_FOUND
085e9d7….js:303 Connect to node...
085e9d7….js:344 Node started syncing, stopping app operation
085e9d7….js:344 Restart app operation again
085e9d7….js:303 Connect to node...

**Comment by luclu** [comment]
@Neonian currently the `eth`-backend is only experimentally supported and likely to be broken. For now please try to run the `geth`-one and give me a small ping-back if that is working for you.
Please update your issue-title to include `eth` --> `Wallet stops syncing using eth`

**Comment by Neonian** [comment]
I tried geth node, but that does not work either. Geth 1.3.6(Go)  is chosen as default in the wallet, and if i start it manually (resources / node/ geth) it start loading but then it stops after a few sec. 

ty for your help

**Comment by Neonian** [comment]
@luclu
New; After leaving geth alone for a few min, something start happening. Geth node is downloading something (i think), but very slow.

 
![geth working](https://cloud.githubusercontent.com/assets/19249152/15140951/ddfd95c0-169d-11e6-9a6a-9888832701c2.png)

**Comment by Neonian** [comment]
@luclu

and then it fails; No peers to keep download active
![geth failed](https://cloud.githubusercontent.com/assets/19249152/15141286/96bbd4e0-169f-11e6-995a-dd5ef5cc80a5.png)

**Comment by luclu** [comment]
@Neonian Please try the freshly released geth 1.4.2 [link](https://github.com/ethereum/go-ethereum/releases).

**Comment by Neonian** [comment]
@luclu
do i just copy it over the older geth in my node folder?

**Comment by luclu** [comment]
That should work, though I would not recommend it. Just run it externally, by double-clicking or using the command-prompt.

**Comment by Neonian** [comment]
@luclu will do, ty very much for all your help, i will report back what happened. For now it seems to download with no problems, hope that continues.

**Comment by Neonian** [comment]
@luclu
Got in "issue" ...or is it?...it stoped downloading when i got this; 
![gthnew](https://cloud.githubusercontent.com/assets/19249152/15176495/a30dcfce-176b-11e6-94f6-93134cd98cd3.png)

but after i restarted geth it went on like nothing happened...
i will download the rest of the blockchain, see if it is broken, and report back

**Comment by obscuren** [comment]
@Neonian it should recover after that log statement. Did you assume it just failed and stopped the instance or did you wait for ~30secs?

**Comment by Neonian** [comment]
@obscuren
i waited...till i made a fresh cup of coffee...so a lil more then 5,7 min...
But i did get word from my internet provider that "some working is being done that could mess up my line for a min or so", could that be the issue? 
It is working now tho...

ty for your quick reply :+1:

**Comment by mamba911** [comment]
help please...

 I do not understand , what happens to my wallet. not update my payments and I get this error, any solution ?

![error jpeg](https://cloud.githubusercontent.com/assets/20615808/17163415/1530e070-538d-11e6-8120-fa377c44788c.jpg)
