### ISSUE TITLE
Account Locked: account just created 

### ISSUE THREAD

**Issue by lbg** [ethereum/mist#594]
Node type: geth-1.4.1-rc-4b9de75-windows-4.0-amd64
OS: windows 10
Network type: main
Mist version: Ethereum-Wallet-win64-0-7-2

I just created a new account (0xcE2Cd268e789758545E6a358EC4F99101DC50ee2) and sent some eth to check if it was working properly. Then tried to send then back from this new account and got the error message: Account Locked

Tried several times to do it and no success.

Then also tried to send a simple transaction from other account that was already working properly and got the same error message. Account Locked!

Screenshot and log attached.

[node.log.zip](https://github.com/ethereum/mist/files/256032/node.log.zip)

I need them working well to participate in the DAO Crowdsale! Please help supporting!

Thanks guys!

Cheers

![2016-05-09 12](https://cloud.githubusercontent.com/assets/8105455/15130214/0775199a-161d-11e6-89a2-cc3ee4d34707.png)

**Comment by luclu** [comment]
Hi @lbg thank you for reporting! Could you kindly include a screenshot of the error message in question?

**Comment by lbg** [comment]
Sure!

Screenshot attached.
![2016-05-09 6](https://cloud.githubusercontent.com/assets/8105455/15149215/0af15836-169f-11e6-9840-b9e88e2858c8.png)

**Comment by luclu** [comment]
@fjl could you have a look?
[account_manager.go#L40](https://github.com/ethereum/go-ethereum/blob/290e851f57f5d27a1d5f0f7ad784c836e017c337/accounts/account_manager.go#L40)
[account_manager.go#L145](https://github.com/ethereum/go-ethereum/blob/290e851f57f5d27a1d5f0f7ad784c836e017c337/accounts/account_manager.go#L145)

**Comment by fjl** [comment]
Accounts are locked until you unlock them. AFAIK mist unlocks the account before sending a transaction from the account. This is the reason for the password prompt.

**Comment by fjl** [comment]
Accounts are locked until you unlock them. AFAIK mist unlocks the account before sending a transaction from the account. This is the reason for the password prompt.

**Comment by fjl** [comment]
Accounts are locked until you unlock them. AFAIK mist unlocks the account before sending a transaction from the account. This is the reason for the password prompt.

**Comment by fjl** [comment]
Accounts are locked until you unlock them. AFAIK mist unlocks the account before sending a transaction from the account. This is the reason for the password prompt.

**Comment by luclu** [comment]
@lbg do you actually get to see a password-prompt?

**Comment by lbg** [comment]
Yea, i do. I put it, hit enter and the error message (account is locked)
comes out.

**Comment by lbg** [comment]
@fjl , what AFAIK stands for? How to unlock my wallet in this case?

**Comment by luclu** [comment]
@lbg could you please run geth and try to unlock your account?
You can do this with `geth.exe --unlock <wallet-address>`.
AFAIK = As far as I know

**Comment by luclu** [comment]
Also please have a look at this and report back here! #669

**Comment by luclu** [comment]
Please make sure to update to `0.8.1` as the error messages were broken in earlier version and always fell back to the - often misleading - "wrong password" alert - regardless of the real error (#664).

**Comment by testerguy** [comment]
Hi, I'm getting the same problem with both Mist and Geth. I am sure I noted the passwords down correctly.
