### ISSUE TITLE
Ethereum-Wallet-win64-0-7-2, stuck at Downloading block 1,473,060 of 1,488,731 for two days?

### ISSUE THREAD

**Issue by igorkiev36** [ethereum/mist#595]
Node type: geth/eth
OS: windows 7 64
Network type: main/test
Mist version: win64-0-7-2

antivirus and firewall   disabled
correct system time on the computer
after upgrading wallet synchronization has started and then stopped

wallet/resources/nodes/geth/geth.exe   

J:\>Ethereum-Wallet-win64-0-7-2\Ethereum-Wallet-win64-0-7-2\resources\node\geth\
geth.exe
I0510 02:59:45.591813    5464 database.go:71] Alloted 16MB cache to C:\Users\Igo
r\AppData\Roaming\Ethereum\chaindata
I0510 02:59:45.654817    5464 database.go:71] Alloted 16MB cache to C:\Users\Igo
r\AppData\Roaming\Ethereum\dapp
I0510 02:59:45.668817    5464 backend.go:314] Protocol Versions: [63 62 61], Net
work Id: 1
I0510 02:59:45.670818    5464 backend.go:362] Blockchain DB Version: 3
I0510 02:59:45.673818    5464 blockchain.go:214] Last header: #1473060 [884b3387
:] TD=17941820431144297511
I0510 02:59:45.673818    5464 blockchain.go:215] Last block: #1473060 [884b3387:
] TD=17941820431144297511
I0510 02:59:45.673818    5464 blockchain.go:216] Fast block: #1473060 [884b3387:
] TD=17941820431144297511
I0510 02:59:45.682818    5464 cmd.go:115] Starting Geth/v1.3.6/windows/go1.5.1
I0510 02:59:45.682818    5464 server.go:311] Starting Server
I0510 02:59:47.846942    5464 udp.go:212] Listening, enode://ba0af69f114b3cd9dc6
139d1006c8234dd662c98edbc96a846e5cc9ae1056b2c611bec26afeb433a6b6ce7daa21314e1cc3
359c3d4e970c15d7d8723fc8f9323@0.0.0.0:30303
I0510 02:59:47.851942    5464 server.go:552] Listening on [::]:30303
I0510 02:59:47.851942    5464 backend.go:526] Server started
I0510 02:59:47.852942    5464 ipc.go:112] IPC service started (\\.\pipe\geth.ipc)
I0510 03:00:07.852086    5464 downloader.go:288] Block synchronisation started

node.log
I0510 03:22:19.727265    1712 backend.go:526] Server started
I0510 03:22:19.728265    1712 ipc.go:112] IPC service started (\\.\pipe\geth.ipc)
I0510 03:22:19.729265    1712 server.go:552] Listening on [::]:30303
I0510 03:22:39.729409    1712 downloader.go:288] Block synchronisation started
I0510 03:22:59.166521    1712 downloader.go:267] Synchronisation failed: leveldb/table: corruption on data-block (pos=990567): checksum mismatch, want=0x98447063 got=0x38aa5ea7 [file=035779.ldb]

Any help much appreciated.

**Comment by luclu** [comment]
Your local blockchain replica seems to be corrupted:
> `Synchronisation failed: leveldb/table: corruption on data-block (pos=990567): checksum mismatch, want=0x98447063 got=0x38aa5ea7 [file=035779.ldb]`
Newer versions of `geth` will have a better fault-recovery. For now please try to remove the file `035779.ldb` in the `chaindata`-folder under `%APPDATA%/Ethereum/`. If this is not working for you remove the whole `chaindata`-folder. Unfortunately you would need to resync afterwards.
