### ISSUE TITLE
verify password after creation

### ISSUE THREAD

**Issue by david-sg** [ethereum/mist#596]
I have created several accounts- with what I thought were confirmed passwords- usually I will send a little ether into them, then back out, to verify the passwords. Once or twice i was lazy and didnt do this - after putting in a little ether, I couldn't get the ether out..

It would be good if you could confirm the password of the account without having to do a transaction.

**Comment by luclu** [comment]
@david-sg we are aware of this inconvinience and will be adressing this in a future release.
Here is already a issue regarding this problem: https://github.com/ethereum/mist/issues/554

**Comment by alexvandesande** [comment]
On the future we will allow you to sign arbitrary texts to prove ownership of an account, which will also prove your password works
