### ISSUE TITLE
Font hard to read

### ISSUE THREAD

**Issue by larspensjo** [ethereum/mist#598]
Node type: geth
OS: windows
Network type: main
Mist version: 0.7.1

I got an error, and there was a dialog displaying information. However, the color of the fonts makes it hard to read:
![image](https://cloud.githubusercontent.com/assets/2412342/15147685/22c52ff0-16c2-11e6-9be6-745d80788460.png)
Notice the blue font after "If you", and the command displayed on the line above "Or report an issue".

**Comment by luclu** [comment]
Thanks for reporting!
related: https://github.com/ethereum/mist/issues/139

**Comment by chevdor** [comment]
Looking similar on OSX

**Comment by luclu** [comment]
related: https://github.com/ethereum/mist/issues/702 (gnome dark theme)

**Comment by evertonfraga** [comment]
I believe this issue was solved on #772, and went live on 0.7.5 release.
