### ISSUE TITLE
Couldn't start Ethereum Node.

### ISSUE THREAD

**Issue by jackwinters** [ethereum/mist#60]
Splash screen says "Are you already running a node? Make sure your IPC path is set to the default: $ geth --ipcpath"
.....
geth is installed but not running.

**Comment by frozeman** [comment]
this means he tried to start a node, couldn't and then timed out.
What machine you're on? Which geth version you have installed? Can you start geth yourself first?

**Comment by jackwinters** [comment]
Mac with Go 1.1.3 installed if I start the wallet without starting geth then it gives the error.
Mac with Go 1.1.3 installed If I start geth myself with the ipcpath argument set then it works
I upgraded via homebrew latest version and both work so guess this was just a versioning thing

**Comment by frozeman** [comment]
It should include its own node.
Could you try the version which will be released soon?
https://www.dropbox.com/sh/8mu15dkxlj8phu4/AACfurTFTyAg0k22g39Vgj1ka?dl=0

**Comment by alexvandesande** [comment]
Closed issue since it's an old thread that has been addressed since
