### ISSUE TITLE
mist wallet get stuck at splash screen 

### ISSUE THREAD

**Issue by mangeshralegankar** [ethereum/mist#602]
Node type: geth
OS: windows 8.1 Pro

I am following below sequence of commands to run mist & wallet in development mode. 

start 3 command line console 
1> C:\mist\interface>meteor 
Gives below message 
[[[[[ C:\mist\interface ]]]]]

=> Started proxy.
=> Meteor 1.3.2.4 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.

2> C:\mist\meteor-dapp-wallet\app>meteor --port 3050 
Give below message
[[[[[ C:\mist\meteor-dapp-wallet\app ]]]]]

=> Started proxy.
=> Meteor 1.3.2.4 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3050/
   Type Control-C twice to stop.

3> electron . --mode wallet 
Below messages with out external geth 
←[32m[2016-05-10 18:52:52.088] [INFO] main - ←[39mStarting in Wallet mode
←[33m[2016-05-10 18:52:52.354] [WARN] nodeConnector - ←[39mNODECONNECTOR ERROR { [Error: connect ENOENT \\.\pipe\
c]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '\\\\.\\pipe\\geth.ipc' }
Error: connect ENOENT \\.\pipe\geth.ipc
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
←[32m[2016-05-10 18:52:56.872] [INFO] ipcCommunicator - ←[39mBackend language set to:  en
←[33m[2016-05-10 18:52:58.072] [WARN] nodeConnector - ←[39mNODECONNECTOR ERROR { [Error: connect ENOENT \\.\pipe\
c]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '\\\\.\\pipe\\geth.ipc' }
Error: connect ENOENT \\.\pipe\geth.ipc
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
←[32m[2016-05-10 18:52:58.131] [INFO] main - ←[39mNode type:  geth
←[32m[2016-05-10 18:52:58.136] [INFO] main - ←[39mNetwork:  main
←[32m[2016-05-10 18:52:58.143] [INFO] ethereumNodes - ←[39mStart node from C:\mist\nodes\geth/win32-x64/geth.exe
←[32m[2016-05-10 18:52:58.181] [INFO] ethereumNodes - ←[39mStopping nodes...
←[32m[2016-05-10 18:52:58.186] [INFO] ethereumNodes - ←[39mStarting geth node...
←[32m[2016-05-10 18:53:29.875] [INFO] main - ←[39mGeth connection FOUND
←[32m[2016-05-10 18:53:29.924] [INFO] checkNodeSync - ←[39mChecking node sync status...

after this below windows appear and gets stuck 2nd window 
![image](https://cloud.githubusercontent.com/assets/11441749/15150490/08c1c518-16eb-11e6-9df3-2ffa9c005b0b.png)

![image](https://cloud.githubusercontent.com/assets/11441749/15150502/1646db10-16eb-11e6-8bf8-d72329a05bbc.png)

Below message with external geth (C:\GETH>geth --identity "Computer"  --datadir "myChain" --port "30303" --ipcapi "admin,db,eth,debug,miner,net,shh
,personal,web3" --autodag --networkid 666666666 --nat=none console)
←[32m[2016-05-10 18:46:03.080] [INFO] main - ←[39mStarting in Wallet mode
←[32m[2016-05-10 18:46:08.442] [INFO] ipcCommunicator - ←[39mBackend language set to:  en
←[32m[2016-05-10 18:46:09.660] [INFO] main - ←[39mGeth connection FOUND
←[32m[2016-05-10 18:46:09.686] [INFO] checkNodeSync - ←[39mChecking node sync status...
![image](https://cloud.githubusercontent.com/assets/11441749/15150441/d7ec2244-16ea-11e6-9abe-5a92fb3282b2.png)

After this it gets stuck at splash screen.  

Node.log
I0510 19:48:02.768726   11072 flags.go:425] WARNING: No etherbase set and no accounts found as default
I0510 19:48:02.771728   11072 database.go:71] Alloted 433MB cache to C:\Users\mangeshr\AppData\Roaming\Ethereum\chaindata
I0510 19:48:02.801747   11072 database.go:71] Alloted 78MB cache to C:\Users\mangeshr\AppData\Roaming\Ethereum\dapp
I0510 19:48:02.832770   11072 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0510 19:48:02.832770   11072 backend.go:362] Blockchain DB Version: 3
I0510 19:48:02.832770   11072 blockchain.go:214] Last header: #0 [d4e56740…] TD=17179869184
I0510 19:48:02.832770   11072 blockchain.go:215] Last block: #0 [d4e56740…] TD=17179869184
I0510 19:48:02.832770   11072 blockchain.go:216] Fast block: #0 [d4e56740…] TD=17179869184
I0510 19:48:02.840773   11072 cmd.go:115] Starting Geth/v1.3.6/windows/go1.5.1
I0510 19:48:02.840773   11072 server.go:311] Starting Server
I0510 19:48:04.940125   11072 udp.go:212] Listening, enode://d79b9dfc559de0ac46c6495d0d5c53f316163c3decd648aa351f0eb6bc7e4e3d66ee8679e4ce353bb825a1b66744674d85e2c8a75e5ee5f1f3ad77ec9f0c7b3f@[::]:30303
I0510 19:48:04.941124   11072 server.go:552] Listening on [::]:30303
I0510 19:48:04.941124   11072 backend.go:526] Server started
I0510 19:48:04.941124   11072 ipc.go:112] IPC service started (\\.\pipe\geth.ipc)

Any help much appreciated.

**Comment by luclu** [comment]
@mangeshralegankar what versions of node and meteor are you running?

**Comment by mangeshralegankar** [comment]
@luclu 
Below are the versions 
Node : v4.4.4
Meteor : 1.3.2.4

**Comment by luclu** [comment]
From first post:

> Meteor 1.3.2.4 is available. Update this project with 'meteor update'.

Did the update solve your problem?

**Comment by mangeshralegankar** [comment]
After your comment I updated meteor but  issue still persists same way as per my first post.

**Comment by luclu** [comment]
Are you trying to just use the app or to develop?
If you only develop DApps you can stick to [Mist](https://github.com/ethereum/mist/releases/tag/0.3.6) for now.

**Comment by luclu** [comment]
I will close this for now as the relevance for others doesn't seem to be given, but we can still discuss on here!
