### ISSUE TITLE
everytime I launch Mist Wallet it will make me re enter password and give me new etherbase address

### ISSUE THREAD

**Issue by Jimboney25** [ethereum/mist#604]
OSX el cap

Im trying to get some theDAO tokens and transfer eth to my mist wallet but everytime I launch wallet it will go back to downloading the last few blocks and then make me re enter password and give me a whole new etherbase account address.Not really sure whats going on with that, I sent a small amount of eth to an address im not sure if I ave access to any longer.

**Comment by luclu** [comment]
Please provide these information:
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

**Comment by Jimboney25** [comment]
eth, osx, main,0.7.2

**Comment by luclu** [comment]
Please have a look at [this issue](https://github.com/ethereum/mist/issues/607). As the eth-backend is currently only experimentally supported, you might want to use the geth-backend for now.

Could you kindly change the title to 'Eth-backend will make me [...]'?

**Comment by Jimboney25** [comment]
im sorry, I guess i wasnt 100% sure, how do I check which node type?

**Comment by Jimboney25** [comment]
When I launch the application it does say eth node needs to sync, how do I use geth backend?

**Comment by luclu** [comment]
Go to menu --> development --> ethereum node --> geth. Also make sure to update to the new and shine 0.7.3 ;)

**Comment by luclu** [comment]
@Jimboney25 Can you please give me an update on this issue with version 0.7.4?
