### ISSUE TITLE
eth-backend: password dialog blocks Mist until synced

### ISSUE THREAD

**Issue by bikerboy4489** [ethereum/mist#606]
I am using the latest version (0.7.2) which allows me to login using GETH which will show me my wallet as 'watch only'. The wallet owner is currently under the ETH Ethereum Node however whenever I switch to this, I enter my password which is correct and it begins to open as all the accounts switch and it now shows the wallet as a folder so I can access it. This is where the problem starts as the 'unlocking' window never disappears and the blocks won't download therefore I cannot transfer the Ether to my other accounts...

I can see that some sort of error is occurring as you can see below but I don't know what this means.
![login fail 11-05-2016](https://cloud.githubusercontent.com/assets/16919164/15179627/e9164272-1774-11e6-95c6-e05c8cb990f6.JPG)

Anyone else experiencing this? I need a solution!

**Comment by luclu** [comment]
@bikerboy4489 currently the support for the `eth`-backend is very limited (https://github.com/ethereum/mist/issues/607). Yout might want to wait until the *eth* has synced as you can see in Mist's node info. I will try to replicate this in the meantime.

**Comment by luclu** [comment]
Version `0.8.8` comes bundled with eth `1.2.9`. You might need to remove the nodes config folder though if an earlier version of eth has been used before. (Make sure to backup your `keystore` folder a prior).
This will be fixed in a future release.
