### ISSUE TITLE
Incorrect / inconsistent custom token number display

### ISSUE THREAD

**Issue by allmails888** [ethereum/mist#608]
Node type: geth
OS: windows
Network type: main
Mist version: 0.7.3

Custom token display icon shows incorrect token number
![mist error](https://cloud.githubusercontent.com/assets/17685229/15205811/0c467be4-184d-11e6-9d4a-4809bb7ef65f.png)

**Comment by luclu** [comment]
Thank you for reporting @allmails888. This bug did surface by the use of DAO's function `createTokenProxy()`, which allows to buy tokens with the DAO as owner.
The Ethereum Wallet is adding these to everybody's token balance. As someone used this function to buy 100 token your balance is shown +100.
We are currently working to resolve this.

**Comment by luclu** [comment]
PR https://github.com/ethereum/meteor-dapp-wallet/pull/196

**Comment by alexvandesande** [comment]
Fixed on develop
