### ISSUE TITLE
No eth visible 

### ISSUE THREAD

**Issue by VasileCatana** [ethereum/mist#609]
Node type: eth
OS: windows
Network type: main
Mist version: 0.7.2
Source is : 1st from the Exchange platform Cracken, 2nd from my wallet (mobile phone app)

**Comment by VasileCatana** [comment]
Hey Guys and girls,
I had sent to my walet from  different sources eth and at this Moment,a day after the Transaction the Balance is still Zero.
Can someone give me a help here, please.
1st Transaction id : 	0x21ca750f862683de02ce9b0435624f9941947ffb707e312b9c7b506bfaf3c280
2nd Transaction ID : x17782e682e11a86b73a9b8a57d56a437b2b6444a67870193c9cd4b3604b09e39
Thanks,
Vasile

**Comment by luclu** [comment]
@VasileCatana Please edit the first post to include these information:
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Also specify the source of the transaction (i.e. exchange, other wallet, client).

**Comment by VasileCatana** [comment]
Node type: eth
 OS: windows
 Network type: main
 Mist version: 0.7.2
 Source is : 1st from the Exchange platform Cracken, 2nd from my wallet (mobile phone app)
I still have not received my eth on the wallet id 0x05c98D52842adA2386dCaaCE81495BcFB72664AE
what should i do ? 
Vasile

**Comment by luclu** [comment]
Thank you @VasileCatana. First of all your ether is **not** lost. Although please make sure you have a backup of all addresses (menu --> accounts --> backup --> accounts).

Please have a look at [this issue](https://github.com/ethereum/mist/issues/607). As the eth-backend is currently only experimentally supported, you might want to use the geth-backend for now.

**Comment by VasileCatana** [comment]
Hey Luca,
I am using a geth version... Is there other way how can I see and manage my
ETH besside  this wallet ?
12 мая 2016 г. 2:07 PM пользователь "Luca Zeug" <notifications@github.com>
написал:

**Comment by luclu** [comment]
Can your please upload a zip of your node.log?

**Comment by VasileCatana** [comment]
Hey ! What is that ?
16 мая 2016 г. 8:56 PM пользователь "Luca Zeug" <notifications@github.com>
написал:

**Comment by luclu** [comment]
Go to menu --> accounts --> backup --> application data, zip the node.log and upload and drop it here.

**Comment by VasileCatana** [comment]
Hey Luca,
Here it goes,
Thx,
Vasile

**Comment by luclu** [comment]
@VasileCatana you might need to use the github frontend for this.

**Comment by luclu** [comment]
@VasileCatana I will close this issue for now to tidy up the issue-tracker. But I will still be here for you until your problem is resolved!
