### ISSUE TITLE
Collision Found on Blockies.js

### ISSUE THREAD

**Issue by alexvandesande** [ethereum/mist#61]
I found out that these two addresses generate the same pumpkin looking avatars:
```html
<img width="350" alt="screen shot 2015-10-22 at 11 28 59 am" src="https://cloud.githubusercontent.com/assets/112898/10666979/a3c22b56-78b3-11e5-8dcc-19bd9e6f73b5.png">
```
* 0x163b948e79a4108b7146c58102ecb965fbed6973
* 0x38cd6ac0e09c517ab75267c6bc76e5bb8baf14d0

They don't just look the same I've checked and they actually produce the same code: 
```html
background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABY0lEQVR4Xu2aMRIBQRBFbe4CMneQyMScwCWETuISTkCoZBJ3cAg55QD6Bb+6apUnbX9n5+/v39MzM8wus9ek+B1Pqyo8+th2cy3fcZAAFWAK6AGaoFXgOwN/XwbTQp8SSHU8fT9cB6QDSEC4klQBsJRNFWoKUC+QMqwH6AFZO91ugtf9tuwF0hRYnu/RI27rRYQn8CABKsAU0APIKJK4JmgVGHkZdCkM2+JJ/n+w9gL2AiPvBfQAPaA+GtMEQwZ+vgrQBGjDgvDEb/p8wuOmKE2ABiC8BAADKcGEVwG0DiAJE8OENwVMgZqBVGGE1wNSD0hzmPDdHhIrgCZAEiS8BDTvJ6gAPaD5qqweEF5x0QS7TZCOx0nC9IW6j8bS98P7AekAEtB8Nph+IBWgB8AVmVRieoAe0Hs/IFUoNkPUrlL8sZvSX8r4/PCM8ASWAOoGiUGKqwBTQA+gLNEEKwasAs1l8A1UJr4guMBztQAAAABJRU5ErkJggg==')`
```
This is certainly a bug in the blockies.js generator: https://github.com/alexvandesande/blockies 

This is the [rand seed generator](https://github.com/alexvandesande/blockies/blob/master/blockies.js):

```js
       function seedrand(s) {
		randseed = 0;
		for(var i = 0; i < s.length; i += 2) {
			var h = (s.charCodeAt(i) << 8) | s.charCodeAt(i + 1);
			randseed ^= h;
		}
	}
	function rand() {
		var n = (Math.sin(randseed++) + 1) / 2; // Move range from -1 - 1 to 0 - 1
		var r = n * 10000; // Remove first few digits since they tend to have low entropy
		n = r - Math.floor(r);
		return n;
	}

```

**Comment by karalabe** [comment]
My guess https://www.reddit.com/r/ethereum/comments/3prtgo/post_your_wallet_identicon_and_ill_give_1_eth_to/cw8tpda

**Comment by alexvandesande** [comment]
Thanks peter!

**Comment by frozeman** [comment]
@alexvandesande could you provide peter with your repo. @karalabe could you provide a PR  for blockies.js?

@alexvandesande i improved you comment, so its better readable.

**Comment by karalabe** [comment]
Short term easy solution is to generate a better seed input in the wallet/mist. This can be done via:

```
bytes = [];
for(var i=0; i< hex.length-1; i+=2){
    bytes.push(parseInt(hex.substr(i, 2), 16));
}
str = String.fromCharCode.apply(String, bytes);
```

Long term harder solution is to get a patch in upstream. One solution would be to take the seed the user provides, hash it with any relatively cheap hash function (md5 is fine, collision resistance is not that important), and then convert that into a proper seed (possibly via the above mechanism).

**Comment by frozeman** [comment]
I don't follow.
We just pass a string to the `blocks.create` func.
Which calls:
```js
function seedrand(s) {
		randseed = 0;
		for(var i = 0; i < s.length; i += 2) {
			var h = (s.charCodeAt(i) << 8) | s.charCodeAt(i + 1);
			randseed ^= h;
		}
	}
```
And manipulates the `randseed` int. 
Where should i put you example code?

**Comment by karalabe** [comment]
Take the string you pass (hex) and convert it with my above code to a proper binary string, and pass that to `blocks.create`
