### ISSUE TITLE
Unable to pass an array of addresses in contract constructor parameters

### ISSUE THREAD

**Issue by sammy007** [ethereum/mist#610]
Node type: geth
OS: osx
Network type: test
Mist version: 0.7.3
Geth: 1.4.3

I am unable to pass an array of addresses as ctor param. You can see how contract deployed with broken `address[]` value.

![screen shot 2016-05-12 at 13 27 00](https://cloud.githubusercontent.com/assets/7374093/15208497/4a15babe-1845-11e6-8ec8-06e61c00fa44.png)
![screen shot 2016-05-12 at 13 20 24](https://cloud.githubusercontent.com/assets/7374093/15208382/a67c4530-1844-11e6-9729-7fd324b9aa7f.png)

**Comment by evertonfraga** [comment]
First of all, sorry for the immense delay. 

It seems that only works with double-quotes. I've opened an issue on the corresponding repository: https://github.com/ethereum/meteor-dapp-wallet/issues/382
