### ISSUE TITLE
DAOhub user claims his wallet to be hacked

### ISSUE THREAD

**Issue by FelixA** [ethereum/mist#611]
One of the users at DAOhub claims that his MIST wallet has been hacked.
You can find the discussion here:
https://forum.daohub.org/t/urgent-buying-dao-using-mist-has-hacked/1742

This is his post:

> Dear Team 
I am not really sure this issue happened by Mist which downloaded from Github or Dao contact however all my ETH has gone to wrong eth address.
Please look and help me now I can't even move myself...my whole world is collapsed..
Basically I had 7218 ETH and buy a DAO I did practice with 1 ETH so you can see the transaction below with 1 ETH
But what happened is after I confirmed that DAO contact has done successfully.
I tried to send 2218 eth to same DAO address but after I confirmed it... I don't see any transaction after the practice of 1 ETH but all my ETH has been gone away..
Totally shocked .. then I checked from block chain of my eth address and found it sent to all to the below weird address.
https://etherchain.org/account/0xc5d431ee2470484b94ce5660aa6ae835346abb19#txreceived29
I am totally clueless now how could this happened whether Mist has been hacked which downloaded from Github
then must be warned as critical issue to globally or it's something error with DAO contract which buying progress.
Please investigate for this incident and help me to get back my ETH. Those ETH has been mining for long time with whole my effort.......
> 

I hope you guys could investigate this a bit further and provide your opinion if this problem in any way might affect other user accounts

**Comment by bas-vk** [comment]
I'm really sorry for your lost Patrick.

Some vital details are missing to give a comprehensive answer. I assume the wallet and node are run as is with the default setting and not using a custom configured node.

The most likely option is that a piece of malware has either stolen the password (and possibly the key) or has been waiting for an opportunity to steal the ether. When the initial 1 ether was send the account was unlocked for 2 seconds. These 2 seconds give malware a window to submit malicious transactions. There is unfortunately nothing that we can do at this time.

Some advice:
1. verify that the check sum of the downloaded wallet zip matches the one on the release page.
2. clean up your computer, or better reinstall (don't forget to make backups of valuable keys)
3. don't use any of your keys anymore. Generate new keys and transfer funds to them. Update contracts that depend on these possible compromised keys.
4. store such amounts of ether in a multisig wallet

**Comment by pat-kim** [comment]
Appreciated all I am the Patrick

Basically geth node was not running at that time probably only geth in mist was running on.

1. so after 1 eth transaction, 2nd transaction attempt I typed same eth destination for DAO.
2. I typed password for the 2nd transaction.

then here is possibility from perspective for attacker from my guessing at the moment.

3. Once an account is unlocked for 2 secs , attacker changed transaction information via local RPC of geth running by mist.

Would this scenario be possible based on current situation >

**Comment by pat-kim** [comment]
I have proved the hacker using 2 second of unlock window for stealing eth even if geth account is locked. 
Please refer my findings 

https://forum.daohub.org/t/urgent-buying-dao-using-mist-has-hacked/1742

**Comment by pat-kim** [comment]
another serious finding was even after 2 sec of unlock window, actually 3 sec

hacker's transaction was succeed please refer the my findings below.

https://forum.daohub.org/t/urgent-buying-dao-using-mist-has-hacked/1742/61?u=patrick

**Comment by bokkypoobah** [comment]
I have just reproduced this issue and have sent a email to bounty@ethdev.com with the full details to reproduce it.

**Comment by pat-kim** [comment]
even the following release has nothing info about 2 sec unlock which means for miners or pool are significantly exposed this vulnerability....no offense please please would not mention we knew that just released it's your fault as didn't know it...   

https://github.com/ethereum/mist/releases

**Comment by D-Nice** [comment]
This is a pretty significant vulnerability, in the meantime, if unlocking accounts, make sure geth is not exposing RPC on any public interface, or at least use CORS if you must.

**Comment by BL186** [comment]
What is the risk of this for all of us? Does this mean that anyone doing a transaction now in Mist is vulnerable to being hacked?

What precautions can we make to avoid this risk?

**Comment by pat-kim** [comment]
@D-Nice and @BL186 it's not only risk for RPC obviously IPC a well..

It's seems they are working on to make a new transaction method..see below..

https://forum.daohub.org/t/urgent-buying-dao-using-mist-has-hacked/1742/114?u=patrick

**Comment by alexvandesande** [comment]
SignAndSendTransaction is now included on the latest release
