### ISSUE TITLE
When I download the blockchain for my mist wallet my ani-virus puts some blocks in the quarantine some "win32:duqu-k infection" ....any thoughts on what that is or is it harmfull?

### ISSUE THREAD

**Issue by FriGo74** [ethereum/mist#615]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by alexvandesande** [comment]
Thanks for the report, we're merging all those into one

**Comment by FriGo74** [comment]
Into where ? Can you send me link?

**Comment by luclu** [comment]
@FarzadHashemi have a look just over @alexvandesande post. You will find some additional info and help. ;)
