### ISSUE TITLE
Not syncing new blocks After 0.7.3

### ISSUE THREAD

**Issue by Wat3v4** [ethereum/mist#616]
![screen shot 2016-05-12 at 8 40 45 pm](https://cloud.githubusercontent.com/assets/17217522/15224414/3f6221bc-188a-11e6-8f66-f67d640518e4.png)
Node type: geth
OS: osx
Network type: main
Mist version: 0.7.3

Hey!
So i updated to latest and it worked fine.. but today I tired to enter my mist and it open up the wallet interface without a problem after syncing all blocks and nodes. 
but once in mist, the upper row where it usually says "X time since last block" is just keep counting without syncing blocks.. 
it shows all my wallets and everything but I can't do anything with it as it is like its "not connected to the network" 
my geth version is 1.3.6 if that makes any difference.. 
Any idea what can i do to fix it?

Edit:
I just noticed that each time that i close and reopen the mist, it sync to the latest block, and then stop.. 
so block sync stuck only in the most UI itself, not in the little node sync window when opening the wallet..

Update, when trying to send ETH to anywhere it gives me this error:
"Connection error: Couldn't connect to node on IPC"
![screen shot 2016-05-12 at 10 52 49 pm](https://cloud.githubusercontent.com/assets/17217522/15228468/61f846bc-189d-11e6-9c8b-c029a6d0c5b7.png)

Update 2:
as @swt83 suggested, deleting the "watch token" of the DAO and letting mist work for some time, restore the sync with the nodes and the blocks. 
I guess watching the DAO tokens in mist create some kind of bug. 
So i Guess it solves it.

**Comment by luclu** [comment]
Hi @Wat3v4 please verify that your OS is time-synced propably. This might help you: https://github.com/ethereum/mist/issues/397

**Comment by Wat3v4** [comment]
Thats usually an issue for windows computers not for Mac.. 
How to do that for MacOS?

**Comment by luclu** [comment]
You are right. Please give the output of the node.log (menu --> accounts --> backup --> application-data).

**Comment by Wat3v4** [comment]
What do you mean? you want the whole node.log file uploaded here?
Is it safe for me :0 ?

**Comment by Wat3v4** [comment]
Posted some updates..

**Comment by luclu** [comment]
Thank you @Wat3v4 for the detailed updates.
The same issue just happend to my Wallet. After sync on splash the GUI stalled.

<img width="1101" alt="unbenannt-1" src="https://cloud.githubusercontent.com/assets/10135872/15229179/1d2e67da-1890-11e6-918c-6e0d1798b6da.png">

Though in my case the IPC-connection seems to be functional as unlocking accounts and transfering ether still works. But updates on the GUI stalled.

**Comment by Wat3v4** [comment]
This happened after trying to invest some in the DAO.. 
Same for you?

**Comment by vmatekole** [comment]
Hi, I have 0.7.3, using Geth 1.3.6 and have similar issue. Although my status states the number of mins till the last block. On restart, Mist catches up but once again it hangs. What's more frustrating is I cannot send any Ether from any of my accounts as Mist complains it cannot communicate with Geth. Mist occasionally hits 100% CPU, I have tried Geth 1.3.6 and Geth 1.4.3 and deleted my chaindata.
Finally, I also have invested in DAO too...


```
...22:48:59.640546   12548 downloader.go:288] Block synchronisation started
I0512 22:49:02.728252   12548 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 1.082405103s. #1505796 [e5d5a2db / e5d5a2db]
I0512 22:49:02.926845   12548 blockchain.go:1251] imported 12 block(s) (0 queued 0 ignored) including 94 txs in 198.411029ms. #1505808 [e4d8fc77 / 77fa5f3a]
I0512 22:49:08.458482   12548 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 22.746102ms. #1505809 [f83a4a50 / f83a4a50]
I0512 22:49:13.514167   12548 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 11 txs in 30.691014ms. #1505810 [383a942d / 383a942d]
I0512 22:49:17.579381   12548 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 9.989883ms. #1505811 [92cd45c7 / 92cd45c7]
I0512 22:49:18.954563   12548 blockchain.go:1251] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 7.160831ms. #1505812 [fcf76dd5 / fcf76dd5]
<img width="996" alt="mist" src="https://cloud.githubusercontent.com/assets/424339/15230140/9d0ee098-1894-11e6-9c3b-32ad7e6067a7.png">

**Comment by Wat3v4** [comment]
Maybe it has something to do with having DAO tokens related to the mist wallet.. 
Hopefully it will get fixed soon..

**Comment by vmatekole** [comment]
Hey all, I ran Geth 1.4.3 and left Mist running and it eventually sprang into life, I can send Eth now. No further issues.

**Comment by Wat3v4** [comment]
How did you update to this geth? and did you let it work on the wallet UI open or the little window of searching nodes?

**Comment by luclu** [comment]
As @vmatekole noticed, running an external instance of geth ([link](https://github.com/ethereum/go-ethereum/releases)) seems worth a shot.

**Comment by swt83** [comment]
I also am unable to send ETH, because after bootup sequence I can no longer sync.

**Comment by swt83** [comment]
Removing the watch contract for the DAO cleared up this issue for me.  It was causing debilitating lag.

**Comment by Wat3v4** [comment]
@luclu How do I install this on a mac?

@swt83 Thanks! I am trying this now, hopefully it will solve it for me.
Are you also running geth 1.4.3?

**Comment by Wat3v4** [comment]
Update 2:
as @swt83 suggested, deleting the "watch token" of the DAO and letting mist work for some time, restore the sync with the nodes and the blocks. 
I guess watching the DAO tokens in mist create some kind of bug. 
So i Guess it solves it.

**Comment by Terminator-Barbapappa** [comment]
I didn't invest in the DAO yet so no watch contract but my wallet won't sync. If I check the log files I see it keeps pulling in blocks but this doesn't show up in the UI and I can't send funds. 

I posted my original issue here: https://github.com/ethereum/mist/issues/630

**Comment by bigcoinme** [comment]
Same issue here, even after deleting the "watch token" of The DAO letting mist work for some time, restore the sync with the nodes and the blocks...
Any help's appreciated, thanks

**Comment by FaguiCurtain** [comment]
I am running MIST 0.7.4 (updated this morning) on MacOS.
same problem, cannot sync. I bought some DAO tokens like many people.

on the Github HP, it says, 

If you still have the "Invalid Date" error or is stuck at "Waiting for blocks" for a long period of time, then you might have a corrupted database and might need to sync it again. Go to your Ethereum folder (access it via accounts > backup > accounts), delete (or simply rename) the folder chain data and start the app again.

my questions:
1) how do i delete the watch token ??? 
2) where exactly is the folder chain data ? should i use the terminal to do that ?

thank you

**Comment by luclu** [comment]
Hey everyone, please make sure you update to 0.7.4 as this bundles geth 1.4.4 which has several under-the-hood improves regarding syncing.
You might want to unwatch (delete) "The DAO"-Contract for now.

**Comment by FaguiCurtain** [comment]
how do we unwatch it please ? whats the command on geth ?

**Comment by luclu** [comment]
@FaguiCurtain hover over the token and click on the trash-bin-symbol.

**Comment by FaguiCurtain** [comment]
luclu, i've updated to 0.7.4 and reinstalled GETH on my MacOS
I deleted the chaindata, and restarted it. 
now my wallet is stuck at block 1,464,740 and i saw a popup from my AV software (AVAST) telling me something is corrupted with geth, and looks like some files have been quarantined.

**Comment by luclu** [comment]
@FaguiCurtain please look here: https://github.com/ethereum/mist/issues/573

**Comment by olivierstern** [comment]
Same IPC connection problem I am unable to solve.

**Comment by luclu** [comment]
Also we are currently working on a refactor of the ipc-routines, which should solve several cases of connection timeouts. I will keep you updated.

**Comment by luclu** [comment]
Could you kindly update to version `0.8.1` and check if you are still affected?

**Comment by luclu** [comment]
Closed as of inactivity.
