### ISSUE TITLE
Cannot drop backup wallet

### ISSUE THREAD

**Issue by racer8** [ethereum/mist#617]
Node type: geth
OS: windows
Network type: main
Mist version: 0.7.3

I cannot drag and drop my presale wallet. The file icon turns into a stop sign as I move it over the wallet or import window

**Comment by racer8** [comment]
Managed to load via CLI

**Comment by luclu** [comment]
@racer8 good to here you could solve this. I tried to replicate this, but failed. I will close this for now, but will reopen if some new information on this surfaces.
