### ISSUE TITLE
Shows correct balance in wallet, says i have no eth on send screen

### ISSUE THREAD

**Issue by HoodPope** [ethereum/mist#628]
Node type: geth/eth
OS: osx
Network type: main
Mist version: 0.6.2

Hey guys trying to send Eth out to someone, have more than 3x what i am trying to send but when i try to send it it says "we cant estimate your gas usage properly as you need at least 1 eth in your account"....this message is permanently displayed at the bottom of my send screen 

any help would be great, thanks

**Comment by hughht5** [comment]
I had this. Either you're not synced up or you have nothing in your etherbase account. I synced and moved 2ETH into the etherbase account and the issue dissapeared. I'm not sure which one solved it.

**Comment by HoodPope** [comment]
thanks for reply....i def have eth in account and also have synced many times..

keep getting this message
“couldn’t connect to the node, did it crash in background"

any help would be great, thanks

**Comment by hiddentao** [comment]
While running the wallet, in a terminal shell type "ps aux | grep geth" and ensure that geth is running.

**Comment by luclu** [comment]
@HoodPope also please update to version 0.7.4.

**Comment by pharynx** [comment]
I have Ether stuck in my contract wallet, with the etherbase wallet as the owner and the same password as the etherbase, and always get 0.00 ETH as a balance when trying to send any amount from the contract wallet. Have lots of ETH in the main wallet ...

**Comment by luclu** [comment]
@pharynx you will need a small amount of Ether in your coinbase account to invoke the contract wallet transaction.
Also please make sure to update to `0.8.1` as the error messages were broken in earlier version and always fell back to the - often misleading - "wrong password" alert - regardless of the real error (#664).
