### ISSUE TITLE
Mist 0.7.3

### ISSUE THREAD

**Issue by matthewdlowe** [ethereum/mist#629]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.7.3

Hi,

I'm using Mist version 0.7.3 on OSx and it keeps crashing before syncing with any nodes.  Is there anything I can do to troubleshoot?

**Comment by luclu** [comment]
@mattewdlowe thank you for reporting. We are aware of this problem and currently working on its solution. I will keep you updated. Please edit your title and post to the correct version number (0.7.3 or 0.7.2?) - we are not yet at 7.3.2. ;)

**Comment by matthewdlowe** [comment]
Thanks, have updated my post is 0.7.3 :)

**Comment by luclu** [comment]
@matthewdlowe please try out the new release 0.7.4 and give me a small ping-back!

**Comment by matthewdlowe** [comment]
Hi Luca,

I've tried copying the 0.7.4 Ethereum Wallet over the top of 0.7.3 and I'm still getting the same issue.  Do I need to reinstall Geth or is there something else I may be missing.

**Comment by luclu** [comment]
You only need to reinstall/update geth if you are running an external instance. `Ethereum-Wallet` 0.7.4 comes bundled with `geth` 1.4.4.

**Comment by matthewdlowe** [comment]
So do I just simply copy and paste the Mist Ethereum Wallet over the top of where it currently sits on my Mac?

**Comment by luclu** [comment]
yes!

**Comment by luclu** [comment]
I will close this for now, but will still be here to assist you!
