### ISSUE TITLE
Mist doesn't stay synced. Can't send funds.

### ISSUE THREAD

**Issue by Terminator-Barbapapa** [ethereum/mist#630]
Node type: geth
OS: osx
Network type: main
Mist version: 0.7.3

I'm sorry if this question has been posted before but i have seen a number of issues regarding this and no solutions yet.

When starting my Ethereum-Wallet everything is fine. It syncs all the blocks perfectly. But when the UI opens it stops syncing. The counter at the top just keeps running up. '1 min since last block', '2 min since last block', '15 min since last block' and so on. This means I can't send any funds. If I try this, after putting in my password, the blue box at the bottom just keeps saying 'sending...'.

Does anyone has the answer to this problem? I've seen they issue reported several times but I didn't see any solution.

Cheers!

**Comment by calummaciver** [comment]
+1 0.7.3 not syncing and unable to send funds. OSX

**Comment by m0se** [comment]
Several people had this issue so far with Ethereum Wallet 0.7.2 and 0.7.3 from what have seen. For me switching from geth 01.3.6 (shipped with EW) to geth 0.1.4.3-rc solved the issue.
But there are a few other things that helped other peoples with this. http://ethereum.stackexchange.com/questions/3606/why-cant-i-send-eth/3905

Although since I switched to the most recent geth release candidate I started to experience this #622 but I'm not sure if this would happen to everyone using Ethereum Wallet 0.7.3 with geth 0.1.4.3 -- Anyhow #622 is only a bit annoying/confusing, but basic wallet functions work like a charm and time since last block resets every 30-40s and doesn't go up to minutes or hours since I switched geth.

**Comment by Terminator-Barbapappa** [comment]
Thanks for the reply :) I installed geth this afternoon with help from this link: https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Mac

Doesn't that mean I have the latest geth version?

**Comment by m0se** [comment]
Ethereum Wallet brings and uses it's own geth binary and thats 0.1.3.6 for EW 0.1.7.2+0.1.7.3

If you have a newer version of geth outside of EW you can start that first and EW will not start it's own geth but connect to the geth you started. What I missed in my previous post is that there is no geth build of 0.1.4.3 for Mac, so you probably need to try 0.1.4.1 I think.

You should probably by able to switch EW's geth for a newer version as well instead starting geth your self and then EW. In EW for osx geth is inside the Ethereum-Wallet.app I think it is `Ethereum-Wallet.app/Framewors/node/geth/geth`.

**Comment by Terminator-Barbapappa** [comment]
It's fixed! I installed geth with help from the link in my last comment and then started geth manually in the terminal by typing in 'geth'. Then just open Ethereum Wallet and it will keep in sync. Hope this helps other people with the same problem. Thanks m0se for your help.

**Comment by cryptojunky** [comment]
Had same issue on windows. After a lot of online searching it seems to be a known issue. The problem was from creating a DAO token to "watch the DAO" after removing the token and restarting the ethereum wallet everything worked fine. I setup another DAO token and it locked up again. Removed it and Voila.

**Comment by Terminator-Barbapapa** [comment]
I know this is also a problem. But that was not the case. I had no DAO tokens or a watch contract.

**Comment by bigcoinme** [comment]
Same issue here.
OS : Linux (Ubuntu 16.04)
Mist 0.7.3
Unable to send ETH to the DAO address even after deleting the "watch token" for The DAO and letting mist work for some time, restore the sync with the nodes and the blocks.

**Comment by Terminator-Barbapapa** [comment]
Did you update geth to the latest version and let it run in the background before starting up Mist?

**Comment by bigcoinme** [comment]
Yes, geth is the latest version and is running on background before Mist is started.
I've managed to send the ETH to the DAO contract but now the transactions are refused with the following error message "An error occurred during contract execution: Out of gas"

**Comment by Terminator-Barbapapa** [comment]
Are you trying to send everything in the account? That doesn't work when you try to send to a contract I believe.

**Comment by bigcoinme** [comment]
Yes... ok, so I'll try to send only a part of what I have in my account...

**Comment by cryptojunky** [comment]
Terminator is correct.

This is from another website. Hope it helps.

When buying tokens, make sure you take into account that you will need a few fractions of additional ETH to pay for the GAS of the transaction. Some users have reported errors if they send their entire wallet balance as there was not enough to pay the gas (transaction fee). After sending, wait a few minutes to confirm the transaction on the blockchain, which can be monitored in the MIST wallet under recent transactions.

FYI: And you can check your balance daohub.org/creation page by putting in your ethereum address once you send your ether to the dao.

**Comment by bigcoinme** [comment]
Thanks guys, it worked now that I hadn't selected "Send everything" ;-)

**Comment by luclu** [comment]
Hey, I will close this for now, but feel free to continue discussing!
