### ISSUE TITLE
Problem importing kryptokit-wallet

### ISSUE THREAD

**Issue by comodore90** [ethereum/mist#631]
Hola amigos, perdonenme por escribir en Castellano, queria comentar cuando importo mis UTC a la carpeta keystore. Aparece mi monedero en el programa mist de windows, el problema radica en que mist me cambia las letras de mi llave publica, es decir es la misma llave publica tiene el mismo orden numeracion y letras , pero hay letras que las cambia por mayuscula, conviertiendola en otra billetera diferente.

**Comment by luclu** [comment]
from google translator:
> **Mist error, when importing my other purse UTC me change the public key**

> Hello friends, forgive me for writing in Castilian, I wanted my comment when I import the keystore UTC folder. my purse appears in the mist windows program, the problem is that mist I change the lyrics of my public key, ie is the same public key has the same order numbers and letters, but letters that changed to uppercase, conviertiendola in a different wallet.

**Comment by comodore90** [comment]
Hello friends I try to explain myself better , I use the wallet ethereum kryptokit online, when I backup the kryptokit wallet, I import the downloaded file ( UTC ) windows to mist
keystore folder) , the problem is when I compare my wallet address the mist I change the lowercase letters capitalized , wallet kryptokit example 0xf44bbcf8fd499ec9b87b8b6a ....... which makes me mist 0xf44bBCF8FD499Ec9B87b8B6a ... when I look at the blockchain Kryptokit wallet is all perfect. but the same wallet in mist makes me less of ethereum even get to see in my wallet mist 30 ether , to me after a few days it 0 ether , I thought I had to download all the blockchain to be updated, but the Restraint end my copy of kryptokit is not updated in mist .

**Comment by luclu** [comment]
I have not used Kryptokit myself..
Is the wallet a `.json`-file?
If yes, try out [https://www.myetherwallet.com/](https://www.myetherwallet.com/#view-wallet-info).
Also look at these tips: #669!

**Comment by comodore90** [comment]
hello, if a JSON file, but supposedly should be compatible with mist , with only the keystore import folder.
I the first time I was 30 ether amount in both portfolios in the mist and kryptokit , acquired after more ether , where I get all correpto kryptokit , the fact is that my portfolio mist with the same backup
JSON ) is not actulico with my new ether I got , look at my address and was different from Kryptokit , then can 'll do a catch so you can see as mist changes the address ,
(Same address but changing lowercase to uppercase letters ) have not caution because my ethereun with kryptokit sure , but can also work with my same address myetherwallet.com

**Comment by luclu** [comment]
@comodore90 could you please try to move the `json`-file into the `keystore`-folder (menu --> accounts --> backup --> accounts)?

**Comment by comodore90** [comment]
![img_20160525_011359 1](https://cloud.githubusercontent.com/assets/19351288/15558798/37aa93de-22dd-11e6-88d7-942ea36b0456.jpg)
![img_20160525_002005 1](https://cloud.githubusercontent.com/assets/19351288/15558823/68d3e21c-22dd-11e6-96d2-3af012290bf3.jpg)


Hello and many thanks for answering your collaboration ,
Right, I move the Json to the keystore carpteta , the same route that explains me . In sending photos you can see the change of direction with a capital letter . Anyway I wait to download all blockchain of ethereum , have if any upgrade purse

**Comment by luclu** [comment]
Cool, please give me some notice on the outcome when you are fully synced!

**Comment by comodore90** [comment]
Hello thank you very much for answering me , although I download 99 % of the chain block is still not updated. It's very strange

**Comment by luclu** [comment]
How did this turn out? 
I will close this for now as I expect it to be solved after being fully synced. Please give me some ping-back if you still encounter this issue.

**Comment by comodore90** [comment]
Hello friend thanks for the help but in the end , I realized I had to put my Json without paswords and me , it worked , but in the end I myetherwallet , waiting to leave mist betas
