### ISSUE TITLE
The problem with backup keyfile after crashing system

### ISSUE THREAD

**Issue by RostSP** [ethereum/mist#637]
OS: osx
Network type: main
Mist version: 0.7.3

I have backup keyfile from Ethereum Wallet 0.5.1. I have a password. I used it and I'm sure it's correct.
After crash my HDD i've installed Ethereum Wallet 0.5.1. Put the saved keyfile into ~/Library/Ethereum/keystore folder but i cant use the account because my password is wrong.

I tried to import from the menu accounts import menu (it's not presale account but i had to try all possible ways) print my password and nothing happens 2 hours change of colors and IMPORTING.
I tried to unlock the account from GETH 
/Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth 

$ geth --unlock "46d6dfb413f39d14f42ad60305872bbef033440a"
I0513 22:10:00.087971 ethdb/database.go:82] Alloted 128MB cache and 1024 file handles to /Users/RostOk/Library/Ethereum/chaindata
Fatal: Could not open database: resource temporarily unavailable

I have no idea what could i do. Could you help?

**Comment by m0se** [comment]
Have you checked the content of the key file? It should contain something like this:
```
{"address":"f8261056da4a91c2771023adde33b9c03f2147e0","Crypto":{"cipher":"aes-128-ctr","ciphertext":"2da93f9978ac59ba1132d023e0340ad4d27badee46f233e706c81c357d582a4d","cipherparams":{"iv":"da63b9e68ae3da3fcb1e4a7dd01d9771"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":262144,"p":1,"r":8,"salt":"928e80573626f6f39e975d6fa001a7e43605b4cdafd1a6caa79cd063720e4bd4"},"mac":"b4fe214544a6fefe3b7acfe03a0f7f313371b955da0e172be300642856f9b874"},"id":"b9e84c81-2840-4dbe-aa42-7b09923c222d","version":3}
```

Did you do the unlock attempt with geth while the Ethereum Wallet was running? The error looks like the files are in use already or something. I just tried, when I change the content of key file to complete nonsens, I still get asked for the password 3 times and then get a error like this:
```
Fatal: Unlock account '0' (0xf8261056da4a91c2771023adde33b9c03f2147e0) failed: invalid character 'd' looking for beginning of value
```

What happens when you create a new account with `geth account new` and then unlock that new account with geth does that work? If not the problem is probably not with the key file.

**Comment by RostSP** [comment]
Yes the keyfile is readable and conteis all information like address, cipher, ciphertext etc.
I tried to unlock with myetherwallet.com but it tells that password is wrong. It's really mystic situation because password is coped i didn't put it manually. I tried to hack it with pyethrecover-master  but it gives me a lot of errors.

**Comment by RostSP** [comment]
The error
Fatal: Could not open database: resource temporarily unavailable
appears because Wallet was opened, but when i close it and try to unlock it doesn't ask the password and start to synchronisation without asking any password

**Comment by RostSP** [comment]
I resolved!! Like always the problem was in the password, not in the program!
Word automatically change some symbols!
