### ISSUE TITLE
I thought I needed give the quantity of bitcoins, but it was the quantity in ethers!!!

### ISSUE THREAD

**Issue by kiralxiii** [ethereum/mist#641]
Hi!

I sent 0,1 Bitcoins with but I was confussed because I needed sent +-0,02bitcoins for have 0,1 ethers!!!
Its my fault, beacause english is not my first language and is the first time I use my bitcoin's wallet.

I need help, because seems I lost my 0,1 bitcoins and only I recived 0,1 ethers to my wallet!!! :(

**Comment by D-Nice** [comment]
This is something you should likely take up with shapeshift.io, as they're the service that converts your bitcoins into ether.

**Comment by luclu** [comment]
Hi @kiralxiii as @D-Nice kindly summed up, please get in contact with shapeshift. They will be able to trace your transaction and give a more meaningful answer. I will close this for now. Fell free to keep us updated!
