### ISSUE TITLE
cannt open mist.

### ISSUE THREAD

**Issue by ff8776228** [ethereum/mist#644]
Node type: geth
OS: windows64
Network type: main/test
Mist version: 0.7.3

![550055466759528395](https://cloud.githubusercontent.com/assets/19385137/15299601/a9f1e6de-1bd7-11e6-80cf-f68c1f8e8ae4.jpg)

**Comment by luclu** [comment]
@ff8776228 please download version 0.7.4 and check if the issue still remains.
If it persists remove the `%APPDATA%\Roaming\Mist`-folder and restart.

**Comment by luclu** [comment]
I will close this for now, but will still be here to assist you.
