### ISSUE TITLE
BTC to ETH not appearing in my wallet

### ISSUE THREAD

**Issue by alvarocker** [ethereum/mist#647]
Hello everybody,
I just made a deposit using the Shifty interface, BTC to ETH, the transaction was successful but I´m not being able to see the ETH in my wallet. This may be related with that Mist keeps syncing for a few days now. Right now I´m stocked at "804.594 blocks left".

Any guidance or advice will be highly appreciated. 

Thanks!
Wallet ver: 0.7.3
OS Windows 10 64bits
2MBPS download speed

**Comment by luclu** [comment]
@alvarocker you need to sync to the block, that was created at the time you made the transaction. Please try to run geth 1.4.3 ([link](https://github.com/ethereum/go-ethereum/releases)) and the start the Ethereum-Wallet to bypass the bundled older version of geth until a newer bundle is releases (very soon).

**Comment by alvarocker** [comment]
@luclu Thanks!, I´m trying Geth now. Any idea how long should it take with my download speed?

**Comment by luclu** [comment]
You are welcome, Ethereum-Wallet 0.7.4 has just been released - geth 1.4.4 is bundled with this. Make sure to update!
For the download times, I guess you will need to wait some hours - not much more. I will cloe this for now!
