### ISSUE TITLE
Mac app closes after start

### ISSUE THREAD

**Issue by bluster11** [ethereum/mist#65]
The Mac version doesn't open. It can't run Geth. When i open the wallet it crash and it closes.

**Comment by frozeman** [comment]
Does this also happens when you don't run a node yourself?

**Comment by bluster11** [comment]
I tried it without run a node. Is the node built in the wallet?

**Comment by frozeman** [comment]
yes it is.

can you run it in the commanline with `open Ethereum-Wallet.app`?

**Comment by bluster11** [comment]
No the same problem.

**Comment by frozeman** [comment]
Ok i need some more information. Did you get any log output when running from the console?

**Comment by bluster11** [comment]
From the console,no. Only when i run it direct by clicking the app icon.

**Comment by frozeman** [comment]
okie... can you please try?

**Comment by bluster11** [comment]
I get this

Process:               geth [6470]
Path:                  /Applications/Ethereum-Wallet.app/Contents/Resources/node/geth/geth
Identifier:            geth
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        Electron [6466]
Responsible:           geth [6470]
User ID:               502

Date/Time:             2015-11-03 17:18:20.980 +0200
OS Version:            Mac OS X 10.11.1 (15B42)
Report Version:        11
Anonymous UUID:        B3388C97-6C74-E0D8-CCD6-D89C8AE8D3F2

Sleep/Wake UUID:       2739ADD8-AE50-4CD6-8893-B2AEF0AA0458

Time Awake Since Boot: 31000 seconds
Time Since Wake:       27000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /Applications/Ethereum-Wallet.app/Contents/Resources/node/geth/geth
  Reason: image not found

Binary Images:
    0x7fff6a94d000 -     0x7fff6a983f5f  dyld (360.17) <03673B53-B8B7-34D1-ADCE-F449E78E39CC> /usr/lib/dyld
    0x7fff92bab000 -     0x7fff92bacffb  libSystem.B.dylib (1225.1.1) <59F79CA0-5D86-359D-A235-4F257409109E> /usr/lib/libSystem.B.dylib

**Comment by frozeman** [comment]
Perfect, thanks for the log. Can you try restarting your computer and running it again?

**Comment by bluster11** [comment]
Yes give me a min please and sorry for the delay.

**Comment by bluster11** [comment]
Nothing.The same problem.

**Comment by frozeman** [comment]
Thanks for the log, we are looking into it

**Comment by obscuren** [comment]
If you have brew installed, please run `brew install gmp`

**Comment by bluster11** [comment]
i don't have it installed

**Comment by bluster11** [comment]
any other idea?

**Comment by frozeman** [comment]
The only way is to install geth manually and run it before the wallet. Not sure why its not starting the node on your system.

Alternatively you can start the eth node. To manually force this go to `~/Library/Application Support/Mist` and edit the `node` file and change the containing text from `geth` to `eth`. If none exists, just create a simple text file and write `eth` inside. Note that the file shouldn't have a file ending.

**Comment by bluster11** [comment]
Nothing.By the way thank you for your help.I will wait for the final Mac version.

**Comment by frozeman** [comment]
No problem. But could you describe more what is "nothing"? Its hard to fix this if i have no information.

**Comment by bluster11** [comment]
Sorry for the delay.Can you send me a printscreen of your workable Mac version?A printscreen from your ~/Library/Application Support/Mist to see what files you have and check them with mine.

**Comment by frozeman** [comment]
I don't think this will help

<img width="478" alt="screen shot 2015-11-17 at 12 03 33" src="https://cloud.githubusercontent.com/assets/232662/11209725/3eeef6e4-8d23-11e5-979e-72cc8aac5e77.png">

**Comment by frozeman** [comment]
rather clean your `~/Library/Ethereum folder` (except you keys) and resync

**Comment by bluster11** [comment]
I don't have Ethereum folder

**Comment by nameone** [comment]
I had the same issue, I installed gmp via: 'brew install gmp' as suggested by obscuren and the wallet now runs. I also noticed that a node file has now been created in ~/Library/Application Support/Mist with the text "geth" Thanks guys! 

![screen shot 2015-12-04 at 11 44 58](https://cloud.githubusercontent.com/assets/8471733/11589012/e8ef2edc-9a7c-11e5-8f71-0ca7f94521dd.png)

**Comment by keznerve** [comment]
Hi i have no Mist folder in my  Library/Application support or no Ethereum  folder in my Library. I presume i need Brew and to do what is suggested above?

**Comment by keznerve** [comment]
heres what happened when i tried to run brew gmp


brew install gmp
Error: The following formula:
  gmp
cannot be installed as a a binary package and must be built from source.
To continue, you must install Xcode or the CLT from:
  https://developer.apple.com/downloads/

unknown-e0-f8-47-0f-9e-f8:~ williams$ brew install gmp
Error: The following formula:
  gmp
cannot be installed as a a binary package and must be built from source.
To continue, you must install Xcode or the CLT from:
  https://developer.apple.com/downloads/

**Comment by jonpspitz** [comment]
I have same issue. Not tech savvy. Just want to buy some ether :)

**Comment by keznerve** [comment]
i got it going in the end. following the advice here. after loading homebrew and tinkering with some folders on my mac.

**Comment by bluster11** [comment]
Can someone explain me what exactly i have to do, to make it works?

**Comment by frozeman** [comment]
The best solution is to install a local node and all its dependencies: `bash <(curl https://install-geth.ethereum.org -L)`

**Comment by bluster11** [comment]
I did it.Check please the images http://prntscr.com/9ujvff
I presses Yes (Y) and i got this http://prntscr.com/9ujvmj
What's wrong?

**Comment by frozeman** [comment]
Press enter?
Btw you can drag your screenshots simply into github and it uploads them and adds them here, no need for prntscr

**Comment by bluster11** [comment]
![1](https://cloud.githubusercontent.com/assets/8303532/12548802/804dd8d4-c361-11e5-9966-16d823597d91.png)

**Comment by frozeman** [comment]
So you know what to do :)
http://brew.sh

**Comment by bluster11** [comment]
![2](https://cloud.githubusercontent.com/assets/8303532/12549819/80154c9c-c368-11e5-93a6-5a3b018b4934.png)

It asks me for password.What password?I try to write but i can't.
We need more easy installation Ethereum wallets.Because with this type o wallet the users who are not tech savvy will have problem to install it.
Do you plan to build a mobile Ethereum wallet?For android and ios?
Unfortunately it's impossible to make it works and i have to stay with the exchanges wallets, like Poloniex.To have my coins in the exchanges.

**Comment by frozeman** [comment]
This `gmp` dependency will be removed on the next feature release version of geth (the one after the homestead release) and then you can simple start the wallet, without all this.

Its still beta, as you can see. Use exchanges for now.

**Comment by bluster11** [comment]
Ok thank you!!

**Comment by frozeman** [comment]
Referencing this issue: https://github.com/ethereum/mist/issues/65

**Comment by bulibasa** [comment]
I installed brew, I run this line in terminal: 

 /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 

and now my macbook pro is not starting, the screen is on but no login and the cooler is at maximum speed :( nothing happens 
please help!

**Comment by maverick3000** [comment]
Just to confirm this appears to be working now. Currently updating nodes. Thanks for the help Frozeman

**Comment by bulibasa** [comment]
nameone - can you please help me to install - same issue, I am not able to get the node started - you said; "I installed gmp via: brew install gmp as suggested by obscuren and the wallet now runs. "

I have a node.log in my Mist folder but the node doesn't start

**Comment by bulibasa** [comment]
frozeman - I managed to start the Enter master password screen but when I input a password the screen said: "password wrong, try again" :( what am I am doing wrong?

**Comment by sushilraghav** [comment]
Is there someone who can help me or can create a cryptocoin based on ETH Fork or BTC Fork or X11 or IOAT Fork ? Contact me at skype : sushilraghav
