### ISSUE TITLE
Can't copy address to clipboard 

### ISSUE THREAD

**Issue by murraci** [ethereum/mist#650]
Node type: geth
OS: osx
Network type: main
Mist version: 0.7.4

Title says it all. Can't copy my account address to send myself ether from an exchange.

**Comment by mightyroy** [comment]
I got this bug too. Cant copy address to clipboard. Instead, the copied text is "https://www.ethereum.org"
version 0.7.4 Mac Osx version.

**Comment by rfikki** [comment]
Same issue in windows

**Comment by alexnegru** [comment]
i can also confirm for windows version

**Comment by gcmartinelli** [comment]
Also confirm on Windows 8

**Comment by gamarin2** [comment]
Same issue here. MAC OS X.

**Comment by tnla** [comment]
Same on Windows 8

**Comment by luclu** [comment]
to sum it up:
___
Copy address to clipboard broken on **main-net only**.

Both ways of interaction are affected:
1. cmd/ctrl + c on address(-div)
2. Copy address-button

Nothing is written to clipboard. (Last copy is preserved).
Also this alert shows twice:

<img width="368" alt="unbenannt-1" src="https://cloud.githubusercontent.com/assets/10135872/15363786/2622235c-1d1a-11e6-823e-769ea301a6a5.png">

**Comment by luclu** [comment]
pull-request: https://github.com/ethereum/meteor-dapp-wallet/pull/192

**Comment by Nogreedy** [comment]
Same issue on  Windows 7/64 bits. Neither "Copy to clipboard" button, nor CTRL+C works.

**Comment by knocte** [comment]
Same issue in Ubuntu 16.04 (Mist version 0.7.4).

**Comment by knocte** [comment]
In version 0.7.3 the bug is not present, so this is a regression.

**Comment by DaneoK1** [comment]
please fix it asap!

I love suggestions e.g. with DAO contract - use version 0.6X to stop watching,
now "wanna copy to clipboard" - please use 0.7.3! LOL
Yes, I have them all installed already ))

**Comment by luclu** [comment]
There will be a dedicated hotfix-release very soon!

**Comment by BGSmilev** [comment]
For the laymen among us, would such a hotfix require a re-install of the Wallet i currently have? If yes - is there a guide somewhere i can follow in how to do it without loosing the content of that Wallet :)

**Comment by luclu** [comment]
@BGSmilev no worries your key are always retained whatever version you launch.
This will be a regular version (0.7.5).

**Comment by luclu** [comment]
Just found a workaround. I'm not sure if this is intended. @evertonfraga  👯 
On the Wallet/Contract-overview-screen right-click on a wallet/contract then cmd/ctrl+c.

**Comment by mightyroy** [comment]
Where is the key file stored? If I just deplete the wallet from OSx applications, my key file will be safe because it's stored in some other path?

**Comment by novoviking** [comment]
At the main screen, click the account you want to copy its address.
at the new opened page go to Edit in the tools bar, click on "Select All"
Then click ctrl+c
finally open notepad, and past to it. all the contents will appear, where you can copy the address

**Comment by BGSmilev** [comment]
@novoviking Thanks - that does indeed work as a temporary solution. Looking forward to the new version with the hotfixes now ;)

**Comment by chalachala** [comment]
any expected time frame on when the next release is coming out?

**Comment by neo-thematrix** [comment]
I confirm the same problem described above of no copy address option working.  Tried on Ubuntu 15.02 and Windows 10 Surface Pro 3.

**Comment by fineartcommodities** [comment]
Same issue on Windows 10/64 bits with mist 0.7.4, bug not present in mist 0.7.3.

**Comment by A7DC** [comment]
What I used to get around it:

On the wallet tab: Cmd+a > cmd+c > post into a text file > copy the wallet address

**Comment by speedery** [comment]
I have the same issue on Ubuntu 16.04 version 0.7.4

**Comment by kungfualden** [comment]
Thanks everyone for the contributions. I'm lucky I found you guys. I was totally lost and a bit frustrated.

**Comment by marcofranssen** [comment]
Another workarround is to open the developer tools, find the element on the UI and copy paste from the developer tools.

**Comment by kungfualden** [comment]
Thanks buddy,

Also my workaround is to click on withdraw tab and copy address from there. And go back to deposit tab and paste address

**Comment by alexvandesande** [comment]
Solved on latest release
