### ISSUE TITLE
Myst:  pwds created on Frozen 0.9.36 not being accepted.

### ISSUE THREAD

**Issue by boondogger** [ethereum/mist#653]
This issue is worrysome.

Passwords Created on frozen 0.9.36 not accepted by mist.
Yes they are entered correctly.

passwords used for mining...and worked fine using geth/ubuntu.
several passswords several accounts.

No caps/ No special characters.....some character repetition.
kept pwds simple for quick tweaking.

Node type: geth 
OS: ubuntu14.04 frozen 0.6.36  /windows 7/64 (myst)
Network type: main
Mist version: latest

No issues with crowdsale pwd/keystores....worked fine.

help!

**Comment by luclu** [comment]
@boondogger thanks for reporting, please help me to understand this issue.
Could you please verify that `geth` 1.4.4 can unlock the account in question?

**Comment by boondogger** [comment]
Cannot...
.trying to rebuild system in ubuntu and rebuild  frozen...rrrrr.
Hoping a work around!

-------- Original message --------

**Comment by boondogger** [comment]
Not sure where to find geth version...myst file is win64-0-5-1

-------- Original message --------

**Comment by luclu** [comment]
here you go:
`Ethereum-Wallet` https://github.com/ethereum/mist/releases/tag/0.7.4
`geth` https://github.com/ethereum/go-ethereum/releases/tag/v1.4.4
please update both!

**Comment by boondogger** [comment]
thanks, you rock!

will try tonight!

**Comment by boondogger** [comment]
to clarify.

doesnt myst have latest version of geth prepackaged?  or is 1.4.4 a patch?

thanks.

d

**Comment by luclu** [comment]
Mist - currently only cointaining on DApp `Ethereum-Wallet` - thus `Ethereum-Wallet` is bundled with `geth`. Version 0.7.4 comes with `geth` 1.4.4.
Please try out the wallet. If this is not working try `geth` standalone. On terminal run `geth --unlock <account>`.

**Comment by luclu** [comment]
Also please have a look at this and report back here! #669

**Comment by luclu** [comment]
I will close this for now, but will stay here to assist you in problems regarding Mist/geth.
Also make sure to try this update of #669:
> if you still can't unlock your account try this service: https://www.myetherwallet.com (they implemented a "wallet viewer" following the official wallet-specs; it's client-side; source-code)

**Comment by boondogger** [comment]
Hey luca.

still no luck.

The accounts were generated in first week of august last year on the 
frozen geth release, ubuntu14.04

Is it possible the keystores may have been altered?

5 accounts have balances

all accounts have same password.

I loaded geth 09.36 and tried to unlock accounts using all three of my 
standard passwords (geth wouldnt sync) but i would get mac errors 
indicating pwd decrypt issue.


i used

for ( var i = 0; i < eth.accounts.length; i++ ) try { personal.unlockAccount(eth.accounts[i], "password"); console.log("unlocked " + eth.accounts[i]); } catch (err) { console.error("Unable to unlock account: " + eth.accounts[i] + " " + err); }

to cycle accounts through individual passwords, and get MAC error at 
each iteration.


the keystores were generated on an ubuntu machine, copied to usb in aug, 
then eventually transfered to windows 7 machine.

is it possible that windows would change the keystore files in any way?

Is the filename required to be not changed? ( i added act balance to 
keystore file name)


would you be able to look at one and tell me if is corrupt?


thanks,

dumbfounded.

(password was written down so something doesnt jive)
