### ISSUE TITLE
Not a valid Win32 application for the wallet, error: expected identifier, string or number

### ISSUE THREAD

**Issue by Darumbal** [ethereum/mist#656]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment]
@Darumbal unfortunately win32 is **not offically supported** yet.

That said, there is a cross-platform-build of `geth` [link](https://github.com/ethereum/go-ethereum/releases/tag/v1.4.1) and a `bring-your-own-node`-version of the `Ethereum-Wallet` [link](https://github.com/ethereum/mist/releases/tag/0.7.4). You can rename the geth-binary to `geth.exe` and move it into `Ethereum-Wallet`'s `resources/node/geth/`-folder.

Though this is not recommended as geth `1.4.1` (RC) misses an important security fix.
As win32 is not supported I will close this for now.
