### ISSUE TITLE
Copy address to clipboard broken

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#658]
Node type: geth/eth
OS: osx
Network type: main
Mist version: 0.7.4

Copy address to clipboard broken on **main-net only**.
Both ways of interaction are affected:
1. `cmd/ctrl + c` on address(-div)
2. `Copy address`-button

Nothing is written to clipboard. (Last copy is preserved).
Also this alert shows twice:

<img width="368" alt="unbenannt-1" src="https://cloud.githubusercontent.com/assets/10135872/15362506/a2c3f21e-1d15-11e6-9829-8d0e6e078be4.png">

**Comment by rfikki** [comment]
https://github.com/ethereum/mist/issues/650
