### ISSUE TITLE
Live Price Feed Distorts USD Balance Accounting

### ISSUE THREAD

**Issue by robertandrewsmith** [ethereum/mist#66]
This is a bug, but also a feature request.

In the Wallet Section of Mist, beneath LATEST TRANSACTIONS, it appears that some information is wrong for each transaction shown including some details shown in the TRANSACTIONS pop-up window. USD price is wrong for each transaction Amount & Gas Price.  I can confirm this by looking up each transaction event's TIME in a Block Explorer, then hunting down the Open Close High and Low PRICE  for that time period in chart with historical data. What a pain in the butt!

1. THE USD PRICE IS WRONG.
2. WALLET USERS SHOULD NOT HAVE TO HUNT ELSEWHERE FOR PRICE HISTORY.
 
I would like to see Ethereum blockchain transaction events are linked from every block to a data store with the global price index (e.g. www.ethereumwisdom.com has such an index) -  such that Block Explorers & MIST WALLET can accurately represent the cost of ETH in FIAT.  After all, that is how financial accounting is done.

Please fix then help your friendly Accountants, Bookkeepers, and Financial professionals who must have this accurate information. :-)

**Comment by frozeman** [comment]
Hm. The idea was just to represent any ether displayed in the current USD/BTC value, not to store historical data.

This would be very complicated as you can even have the wallet closed, so you would need to fetch this historical data from past logs as well.

We will think about it.

**Comment by robertandrewsmith** [comment]
Thanks for thinking about it....

BTW: www.ethereumwisdom.com is made by Davide Gessa (www.github.com/dakk - he wrote ethpool) gessadavide@gmail.com, and by openbitlab.com.  Ping him to see if he can automate a dump of price history to IPFS.  Mist could then query the file based on the time of transaction events, and pull discrete price history data to local storage.

Or maybe there is another better way?

**Comment by alexvandesande** [comment]
Having historical price information is a good feature request and I've been told that's very important for accountants. But doing multiple requests to an api constantly is a complicated issue. We'll revisit this issue when we have ifs integration and some external oracle available.

**Comment by robertandrewsmith** [comment]
That's fine Alex, as long as you continue to keep this beta.  Any official wallet which doesn't keep  accurate price history information - well it's just not a "wallet" - it's a crippled account browser.   

I'd like to recommend you therefore remove live price "updating" of "historical" price event information for the next beta update  - this is simply a "bug" until it is removed.

I hope this gets more priority soon, after the next beta release.  Please, kindly, thank you.  :-)

**Comment by frozeman** [comment]
The live price has mainly the advantage of people being able to type in 1EUR and send the respective amount in ether.
I think what you're looking for is BALNCE https://consensys.net/ventures/spokes/

**Comment by robertandrewsmith** [comment]
I think you misunderstand what I am saying.  You can keep people being able to type 1EUR to send the respective amount in ether for your beta update, but then you need to either fix the corresponding price change updates happening in the LATEST TRANSACTIONS event ledger (no reason EUR value should change), otherwise please remove this bug (side effect) from happening.

Also, BALANC3 will be nice, when eventually it is released. However one should not have to expect users to also run (in parallel) BALANC3 which will be a paid subscription service.  You have to think of Mist like a single end-user app for the total Ethereum experience - it might be the only one-click download effort users will ever make to try it out.  And if it doesn't live up to their experience it will be abandoned. Therefore such a feature as knowing how much you've spent -  will require fiat value frozen to ether price in some form.  

Incidentally, accountants are developers - they develop budgets and forecasts - the financials used to base salary for staff and contractors, and for establishing program funding.  It's therefore a little unfair to diminish the importance of price history.  Have either of you contacted ethereumwisdom.com as I suggested above?  Maybe their developer would like to offer you help on the IPFS and Oracle side of things with an API, or plug-in.

Thanks for further considering my issue.  Truly.

**Comment by frozeman** [comment]
added in 81d2130
