### ISSUE TITLE
Multisig support for subtokens

### ISSUE THREAD

**Issue by taoteh1221** [ethereum/mist#660]
Node type: geth
OS: linux
Network type: main
Mist version: 0.7.4

It would be really great if there was a multisig security option to protect subtokens (TheDAO, Unicorns, etc)? I believe right now there is not an available security option yet for subtokens in multisig wallets?

**Comment by luclu** [comment]
@taoteh1221 could you kindly close this and reopen in the wallet-DApp [repo](https://github.com/ethereum/meteor-dapp-wallet/issues)?

**Comment by taoteh1221** [comment]
@luclu Ok, doing that now.
