### ISSUE TITLE
Transfered .08 Bitcoin exchanged to only .08 Ether Newbie help

### ISSUE THREAD

**Issue by Radar166** [ethereum/mist#661]
I am new to github and the whole crypto currency thing.  I transfered .08 bitcoin into the Ethereieum wallet on startup  when it asked to fund your wallet and it converted it into only .08 Ether.  Help Please.

If I posted this in the wrong place please let me know.

Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.7.4

**Comment by luclu** [comment]
Hi @Radar166, please have look here: https://github.com/ethereum/mist/issues/641
I will close this for now as this is a duplicate. But please feel free to update here on the outcome.

**Comment by Radar166** [comment]
@luclu Awesome thank you for the help on this one :).
