### ISSUE TITLE
Another Wrong Password Incident with 2 accounts

### ISSUE THREAD

**Issue by garatodd** [ethereum/mist#662]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by garatodd** [comment]
I am VERY new to this and wanted to do a wallet through whom ethereum seems to trust.  I made 1 account ans started mining.  No problem, but as soon as I wanted to try to transfer an Ether... I got wrong password... ok... maybe my mistake... on the second account i set up and made sure to type the same password twice and made a new account.  Got some ether in it.... again wrong password....

I am connected. restarted windows a few times....

Here's the kick both passwords are only a numbers.  I did not use any letters.  It set up my account both times.  I am testing and wanted to keep the passwords simple and memorable b4 higher security.  I would like to recover my 5 Ether.  Please help.  Thank you

**Comment by garatodd** [comment]
Did the accounts maybe add letters to my password or something to force it to create an account?

**Comment by luclu** [comment]
@garatodd please provide these information in your first post:

Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

**Comment by garatodd** [comment]
Mist Ethereum Wallet? (It finds peers and then loads for a long time)
Windows 7 64
?
ethereum wallet  win 64 0 7 2

I only downloaded the file and unpacked it and ran the executable

**Comment by luclu** [comment]
@garatodd please update to 0.7.4 [link](https://github.com/ethereum/mist/releases/tag/0.7.4).

**Comment by luclu** [comment]
Also please have a look at this and report back here! #669

**Comment by garatodd** [comment]
I am trying update first.  Synching Blocks now.  Haven't done anything with cmd.  I run my miner with gpushack's ethOS.  I like Graphic Interfacing... I am a novice to that stuff and generally have little time to learn atm.... I will begin to try the second walkthrough of cmd if update doesn't work.  Thanks

**Comment by luclu** [comment]
How did it turn out?

**Comment by garatodd** [comment]
It didn't seem to work. I haven't restarted computer yet to try that. I was away from the computer most of the day. I will try again in a couple of hours

**Comment by luclu** [comment]
Make sure to try this update of #669:
> if you still can't unlock your account try this service: https://www.myetherwallet.com (they implemented a "wallet viewer" following the official wallet-specs; it's client-side; source-code)

**Comment by garatodd** [comment]
Alright, 
I have restarted windows a few times
tried opening the files using myetherwallet  

still getting wrong password.... I am almost sure there is some bug that altered or designated me a password since I only used numbers....

is there any brute force service you suggest outside of the "pyth" or "plyth" thing?

We are only talking a few ethereum... although it still would be nice to get them back if cheap enough.

**Comment by luclu** [comment]
@garatodd could you kindly try to load the json-file with myetherwallet.com as described in #669?

**Comment by luclu** [comment]
I will close this for now as of inactivity.
