### ISSUE TITLE
Linux x32 package 0.7.4 does not have node binary

### ISSUE THREAD

**Issue by alex-ll** [ethereum/mist#663]
Linux x32 package 0.7.4 does not have node binary:

alex@mur ~/tmp/Ethereum-Wallet-linux32-0-7-4 $ ls resources/
app.asar  atom.asar
alex@mur ~/tmp/Ethereum-Wallet-linux32-0-7-4 $

**Comment by luclu** [comment]
proposed fix: https://github.com/ethereum/mist/pull/665
Binary will be published afterwards.

**Comment by luclu** [comment]
@alex-ll please test the new binary [link](https://github.com/ethereum/mist/releases/download/0.7.4/Ethereum-Wallet-linux32-0-7-4.zip) which comes bundled with a `geth` node.
