### ISSUE TITLE
Wrong password

### ISSUE THREAD

**Issue by visualmagic** [ethereum/mist#666]
Node type: geth
OS: windows/osx
Network type: main
Mist version: 0.7.4

Password not working on transfer.

I am absolutely typing it the same as when I signed up...

Only have a couple hours to buy this DAO - what do I do?

**Comment by visualmagic** [comment]
To add to this issue...

I imported 2 x pre-sale wallets. For one (which only had 100 ETH) the password worked. The other (with over 1000 ETH) the password is not working - it is as if each was assigned a password.

I have always been able to import these into Kraken with the same passwords since the beginning.

Now for some reason I can't. It's llike the Ethereum Wallet has 'locked' my json file inside it, and has changed the password on me.

Please help.

**Comment by luclu** [comment]
Please have a look at this and report back here! #669

**Comment by luclu** [comment]
I will close this for now - as this is most likely not an issue with the software. We can still continue to discuss your solution here!
