### ISSUE TITLE
transactions not being broadcast, blocks are being updated

### ISSUE THREAD

**Issue by david-sg** [ethereum/mist#667]
Node type: eth 1.2.4
OS: windows 10
Network type: main
Mist version: 0.7.4

Submitted transactions are not being broadcast, with 10 peers connected and blocks updating. 

[LOG.txt](https://github.com/ethereum/mist/files/271744/LOG.txt)
-------
Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by jackcasey** [comment]
I get exactly the same on the same version and OS.
The transaction sits there unconfirmed and not appearing at etherscan and then just disappears after some time.

**Comment by jackcasey** [comment]
I have managed to send ETH by quitting mist, installing geth with homebrew, running mist and then sending less than the full amount (I was using the 'send everything' tickbox). This worked.

**Comment by luclu** [comment]
@david-sg, @jackcasey please verify or specify the node-backend you are using to isolate the issue.
The `eth`-backend is currently only experimentally supported and various problems are known: https://github.com/ethereum/mist/issues/607.
Please use the the `geth`-backend for now as this is the development priority for now.

**Comment by luclu** [comment]
I will close this for now as of inactivity. The eth-backend will be upgraded soon - until then please still to geth.
