### ISSUE TITLE
WRONG PASSWORD

### ISSUE THREAD

**Issue by Jimakaveli4** [ethereum/mist#668]
Im trying to enter the password i used while creating my account on ethereum and its saying wrong password.

**Comment by luclu** [comment]
Please have a look at this and report back here! https://github.com/ethereum/mist/issues/669

**Comment by luclu** [comment]
I will close this for now - as this is most likely not an issue with the software. We can still continue to discuss your solution here!

**Comment by Jimakaveli4** [comment]
Do you know how long it takes to show payment.  I purchased 2 ethereum but its not yet showing. 

Regards Langat

 
 
  On Thu, May 19, 2016 at 3:08 PM, Luca Zeug<notifications@github.com> wrote:   
I will close this for now - as this is most likely not an issue with the software. We can still continue to discuss your solution here!

**Comment by luclu** [comment]
Make sure to use version 0.7.4 and your node is synced. If you encounter problems with shapeshift head over to there support. They are very helpful in tracing the your transaction and assisting in your problem.

**Comment by Jimakaveli4** [comment]
Okay thanks for the info. 

 
 
  On Thu, May 19, 2016 at 3:30 PM, Luca Zeug<notifications@github.com> wrote:   
Make sure to use version 0.7.4 and your node is synced. If you encounter problems with shapeshift head over to there support. They are very helpful in tracing the your transaction and assisting in your problem.
