### ISSUE TITLE
Add advanced mode

### ISSUE THREAD

**Issue by larspensjo** [ethereum/mist#67]
I really like beta 3! But it can be difficult to understand for users that just want a wallet. Suggestions how to make the app really easy to use for beginners, while still allowing advanced users:

Start the app in "normal mode", but allow the user to switch to "advanced mode". When in normal mode:

1. In "Send funds" screen, hide the "Deploy contract", "Data field" and "Select fee" (but still show the fee).
1. In the "Wallets" screen, hide option "Add accounts".
1. In the "Add tokens" screen, only allow addition of predefined tokens.
1. Disable the "Develop" menu (make it gray).
1. The status in the header (showing peers, block etc) is replaced with a lamp. Using red, yellow and green.
1. The "Execute contract" can be simplified. E.g. a beginner doesn't need to understand the concept of "gas usage".

**Comment by alexvandesande** [comment]
The newer version will be easier to use and will tackle most of these complexity issues. 

Adding an "advanced mode" is like trying to use this method to clean up a mess: https://media.giphy.com/media/3ELDuBKag7o8E/giphy.gif

It's not actually solving the underlying design issue, just trying to cover up the mess with a drape. We are trying to tackle each individual problem.

> In "Send funds" screen, hide the "Deploy contract", "Data field" and "Select fee" (but still show the fee).
> The "Execute contract" can be simplified. E.g. a beginner doesn't need to understand the concept of "gas usage".

These screens have been simplified on the next version

> In the "Wallets" screen, hide option "Add accounts".
> Disable the "Develop" menu (make it gray).

I don't believe these add too much complexity as you can ignore these buttons

> In the "Add tokens" screen, only allow addition of predefined tokens.

There aren't any popular tokens out there for this to be possible and if there were this is too early days to allow a "preferred" list of tokens. We might revisit this in a year if there are any tokens that have reached universal consensus

> The status in the header (showing peers, block etc) is replaced with a lamp. Using red, yellow and green.

Good point, the status bar has been a victim of feature creep

**Comment by larspensjo** [comment]
Sounds good, you are doing an excellent job. I look forward to next version!
