### ISSUE TITLE
Transaction not being reflected in my wallet 

### ISSUE THREAD

**Issue by PascalQ** [ethereum/mist#676]
Hi,

A bit lost, for the first time a transaction is not reflected in my wallet so it seems the ETH are nowhere, can anyone help?
the TRX: 0x5146259450baf455a6723b255fe24eae609a4781df7905f02edbfc818ba93559

**Comment by luclu** [comment]
Look here - The EVM was unable to run your transaction: 
http://etherscan.io/tx/0x5146259450baf455a6723b255fe24eae609a4781df7905f02edbfc818ba93559
So nothing happend, but you lost the specified gas.
Is the contract a wallet contract?

**Comment by PascalQ** [comment]
Thanks for helping.
Yes it is a contract wallet.
No a big deal for the gas but where are the ETH? because there are not in the wallet from where I sent and not in the one where I wanted them to arrived, it is a bit confusing.

**Comment by luclu** [comment]
No worries man, your precious ether is still there. Just count it up!
http://etherscan.io/address/0x0064c13eefdb075e334fff6736a305cc6561d059
