### ISSUE TITLE
Your stub contract has no original wallet address set, please restart your wallet!

### ISSUE THREAD

**Issue by paulmorriss** [ethereum/mist#68]
(I know there's another issue with the same error, but that seemed to be a version mismatch, whereas I think I'm up to date.)
I'm running geth 1.3.1 on Ubuntu. The blockchain is all synced.
I haven't set ETHERBASE or created any accounts.

I downloaded the Wallet v 0.3.5. I created an account, which seems to also set ETHERBASE. WHen I try to add a wallet I get the "Your stub contract..." error (screenshot below). I exited the wallet and went back in and it said "creating" below "contract based wallets" and then I got the error again. I exited and went back in the error wasn't there.

![wallet](https://cloud.githubusercontent.com/assets/3678824/10998387/b33b3fde-848c-11e5-98f4-17f2ac3bd707.png)

**Comment by frozeman** [comment]
You need to sync you node first.

**Comment by paulmorriss** [comment]
The node is synced.

**Comment by frozeman** [comment]
Are you on the main net? Could you check the browser console and type `originalContractAddress`, and see if you get `0x273930d21e01ee25e4c219b63259d214872220a2`?

As well as see the errors and send me the return of this variable `walletStubABICompiled`

**Comment by paulmorriss** [comment]
Yes, I'm on the main net. Here's the output from the console:

Connect to node...
8a433d8665bba4cbea3603bc89b5921c3f4b76e9.js:286 Use Main-net wallet as code base for stubs on address:  0x273930d21e01ee25e4c219b63259d214872220a2

8a433d8665bba4cbea3603bc89b5921c3f4b76e9.js:290 EVENT LOG:  Checking Deposits and ConfirmationNeeded for 0x30426aed1d7f4c60094ce2f0397b39091866e652 (_id: dSdtS5Yf9gxo6suJb) from block # 519073

8a433d8665bba4cbea3603bc89b5921c3f4b76e9.js:290 EVENT LOG:  Object

8a433d8665bba4cbea3603bc89b5921c3f4b76e9.js:290 EVENT LOG:  Deposit for 0x30426aed1d7f4c60094ce2f0397b39091866e652 arrived in block: #519073 200000000000000000

originalContractAddress
"0x273930d21e01ee25e4c219b63259d214872220a2"

walletStubABICompiled
"0x606060405260026101086000505560405161015638038061015683398101604052805160805160a051919092019190808383815160019081018155600090600160a060020a0332169060029060038390559183525061010260205260408220555b82518110156100eb57828181518110156100025790602001906020020151600160a060020a03166002600050826002016101008110156100025790900160005081905550806002016101026000506000858481518110156100025790602001906020020151600160a060020a0316815260200190815260200160002060005081905550600101610060565b81600060005081905550505050806101056000508190555061010f62015180420490565b61010755505050506031806101256000396000f3003660008037602060003660003473273930d21e01ee25e4c219b63259d214872220a261235a5a03f21560015760206000f3"

**Comment by frozeman** [comment]
Looks perfectly fine, you still get the error? 
Can you check the console when you get the error?

**Comment by paulmorriss** [comment]
When I exited it again and started it again it was ok and hasn't happened
since.
I know an unreproducible bug is hard to fix but I thought it worth
reporting.
Paul

On Tuesday, November 17, 2015, Fabian Vogelsteller <notifications@github.com>
wrote:

> Looks perfectly fine, you still get the error?
> Can you check the console when you get the error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/mist/issues/68#issuecomment-157392045>.
>


-- 
Paul Morriss
http://paulmorriss.com

**Comment by frozeman** [comment]
It probably has to do with your chain was not synced, or an RPC error.
