### ISSUE TITLE
Newbie problems with receiving inital balance (shapeshift)

### ISSUE THREAD

**Issue by mbthedude** [ethereum/mist#684]
I wanted to try out Ethereum so downloaded the Ether Wallet that runs the Mist front end. During the initial startup it advises to transfer a minimum of .25 - 1 Ether and provides the link to Shapeshift IO for a BTC to Ether transfer.

I arranged to send some Crypto via this method as the Wallet was working its way through updating the blocks on my computer and the transaction clock was counting down. The clock reached Zero before the blocks had finished synchronising on my computer so no the transaction shows as expired even though the BTC have left my Bitcoin Core local wallet.

I have traced the transaction address on Bitcoin Block Explorer which shows the Address and Hash as being valid. If I put in my Ether Address that was used as the Send part of the transaction and validate it through Etherchain.org it reports the Account is "Not Found"

As it not gone through an exchange that I have signed up to I am not sure where I can trace the transaction or make sure the BTC isn't lost.

Can you give any advice?

Thanks

Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment]
Please try to get in contact with shapeshift as they are able to trace your transaction. They can provide meaningful insides into this. Please give me a small pingback on the outcome!

**Comment by luclu** [comment]
I created some pool with tips on this: https://github.com/ethereum/mist/issues/687

**Comment by mbthedude** [comment]
Hi Luca,

I got some feedback from them it seems the transaction never went to them
due to not enough mining fees. I have zapped the unconfirmed transaction
from my wallet and then tried the whole process again this time it
completed fine.

Thanks for the advice

**Comment by luclu** [comment]
Good tho hear this @mbthedude!
