### ISSUE TITLE
Can’t delete a Watch Contract if (address == some owned wallet)

### ISSUE THREAD

**Issue by mhenders** [ethereum/mist#686]
I have Ethereum Wallet 0.7.4 running under Mac OS X. 

Wanting to monitor some DAO Tokens, I created a "Watch Contract" and inadvertently specified my ETH Wallet address, instead of the DAO address. This resulted in a Custom Contracts entry labeled "DAO Tokens" in which I see my own ETH account balance. (Later I figured out how to correctly setup the monitor with a Watch Token.)

The problem is that Ethereum Wallet will not allow me to delete the mis-configured Watch Contract I created—i.e. the one showing my own ETH wallet account balance. 

In the past, when clicking on a contract, I was presented with a detail view in which I could delete the contract (after typing in, "delete"). With this particular contract, however, I'm taken back to the default "wallet view" in the application—i.e. I'm not shown the "contract" detail view that contains the delete service. It's as if the app sees this particular Watch Contract as a symlink to my ETH base account.

I've also discovered that having this un-deleteable contract (that shows my own account ETH balance), has the effect that my DAO Tokens watch token displays TWICE the actual balance of tokens I own. I know this is related to the un-deletable watch contract because having setup the Watch Token in Ethereum on another Mac (running the same wallet), I am shown the correct DAO balance.

I tried replacing ~/Library/Ethereum on the problematic Mac with the contents of the folder on the correctly working Mac, but when Ethereum Wallet launches, it STILL shows that un-deleteable Watch Contract. 

So I'm at a loss as to how to clean up that installation, and was hoping someone here could help

**Comment by luclu** [comment]
Thank you @mhenders. You found some bug there!

How to reproduce:
1. Watch a contract with some of you own wallet address (and a random json)
2. Try to delete it (--> no delete button)

**Comment by mhenders** [comment]
Thanks @luclu for the reply — and really glad to hear it's a bug and not something stupid on my part! :-) I'm new at Ethereum and even newer at The Dao, so I was sure I'd done something horribly wrong.

**Comment by derektiffany** [comment]
@mhenders 

> So I'm at a loss as to how to clean up that installation, and was hoping someone here could help

If you choose Develop -> Toggle Developer Tools -> Wallet UI -> console you should be able to use the javascript console to remove the undesired contract in question by using the CustomContracts collection to find (and remove).

For example ...
```
CustomContracts.find().fetch(); // returns all watched contracts
var idToRemove = CustomContracts.findOne(name: 'DAO Tokens', address: '0x123...').fetch(); // allows for searching in case you have a bunch
CustomContracts.remove(idToRemove); // make sure you have the right one ... you won't get the 'delete' prompt
```

I did something similar at one point and cleaned up the install via the above.

**Comment by mhenders** [comment]
Hi @derektiffany — Thanks so much for that, but I'd be terrified to try it. With my luck, I'm pretty sure I'd end up deleting my entire wallet! Hopefully another option is to just wait for a version to be released that fixes the bug?

**Comment by luclu** [comment]
PR: https://github.com/ethereum/mist/issues/686

---

Also another workaround:

1. remove wallet contract
2. remove custom contract
3. import wallet contract
