### ISSUE TITLE
Bitcoin to Ether conversion problem (shapeshift)

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#687]
There have been several reports of users supposedly not receiving Ether after despositing Bitcoin through shapeshift in the Wallet.

If you are **affected** please do the following:
1. Make sure `Ethereum-Wallet` is **fully synced** to the block containing the transaction.
2. **Wait some more minutes** (~30min) as sometimes low liqudity among others causes the transaction to be delayed.
3. Use a blockexplorer (e.g. [Etherscan.io](https://etherscan.io)) to check the balance of your account.
4. Please **get in contact with shapeshift** as they are able to **trace and recover any funds**.

**Comment by asaparson** [comment]
I don't know if this is helpful but users who are unsure if they received their Ether because of issues with Mist can check etherscan.io before they attempt number 3. If they search their account's public key, they'll see a deposit if one was made.

**Comment by luclu** [comment]
Thank you @asaparson, I added this to the list.

**Comment by sclarke001** [comment]
@luclu ShapeShift wrote: "You will need to contact the Ethereum Support Team. We have no way to recover funds that were sent in a successful transactions."

I used a Test-net account for the transfer.  Would there be a way to recover the transaction? https://www.etherchain.org/tx/0xec7a225a7b1221cb1d7f7126682eb8e337365904ca501cc010b60ed12d48c014

**Comment by luclu** [comment]
@sclarke001 try to copy the json-file of your wallet from the test-net `keystore`-folder to the main-net one.

**Comment by sclarke001** [comment]
that worked, thanks!

**Comment by hanebauer** [comment]
I have the same problem with buying ETH via Bitcoin (Mist Wallet).

**Comment by hanebauer** [comment]
https://blockchain.info/address/1JqSRdQ5ySt1TYnWdNbdpcMU1t7HNk44YV
