### ISSUE TITLE
Couldn't start an Ethereum node

### ISSUE THREAD

**Issue by oneala** [ethereum/mist#695]
I am trying to find a fix for days, i have what everyone suggested here on other websites but i am not able to fix this at all.. at this point i give up and post a new issue/help request here. I really don't understand what is causing the problem..

PLEASE HELP!!!

Node type: geth/eth
OS: win10 64
Network type: main
Mist version: 0.0.0

Screenshots
https://gyazo.com/b08102f4bd11f5745287bc6db3f0525f
https://gyazo.com/c20b4c0155f2762412c91548e2893bd7

[node.logs.zip](https://github.com/ethereum/mist/files/278100/node.logs.zip)

**Comment by luclu** [comment]
Please make sure to be on version 0.7.4 and check that this is no firewall issue.

**Comment by Kojee** [comment]
It could be an error in the PC clock, try to set a different site from where you synchronize the clock.
Go on the clock on the bottom right corner, edit and then on the tabs press Internet hour.
Names may be different because my windows version is 7 and it's not in english but it's more or less the same.

**Comment by ChristianBF** [comment]
Same problem here, sholutions above dont work

**Comment by oneala** [comment]
The thing is that i had the same problem on win7 and i recently installed win10 but the problem persist. All this hapen when i upgraded from Ethereum-Wallet-win64-0-7-2 to Ethereum-Wallet-win64-0-7-3. 

I tried to turn off firewall, sync time zone but still cannot open it. :(

**Comment by luclu** [comment]
@oneala please try to delete the Mist folder `%appdata%\roaming\Mist` and start 0.7.4.

**Comment by ChristianBF** [comment]
@luclu There is no foulder found in my case :(

**Comment by oneala** [comment]
@luclu didn't worked :( ...

**Comment by jordimorris** [comment]
exactly the same error windows that I had also running on win10 64bits. 

What I did...
-removed the entire ethereum folder
-install ethereum mist 6.2 wallet
-blockchain data downloaded and validated in two phases, it took long but worht it

I'm ready for using dao tokens

keep us posted

**Comment by oneala** [comment]
OK @jordimorris , ill do the same right now! thanks!

**Comment by oneala** [comment]
same thing.. i have deleted everything and started from scratch with 6.2 wallet https://gyazo.com/f0bfe93b3bb9c77b375d0a27807ce6fd

**Comment by jordimorris** [comment]
I forgot one thing to mention. As the error showed some messages regarding the cache, I also followed  some, not all of the following steps to clean the cache on windows 10. 

http://www.makeuseof.com/tag/7-hidden-windows-caches-clear/

all the best mate

**Comment by luclu** [comment]
Does version `0.7.5` solve your issues? It includes a complete overhaul of the IPC-communication - the mean by which the wallet connects to the (geth) node.

**Comment by oneala** [comment]
since then i am doing it separately , i start get do sync blockchain and after that i start the wallet and it works, did not got the 0.7.5 version yet

**Comment by jordimorris** [comment]
While the invalid data or the flaws alike are gone in 7.5, the application seems to get stuck/frozen for interval times making it unusable. I keep running 6.2 the most stable so far on my computer
