### ISSUE TITLE
No Transactions listed in MIST GUI

### ISSUE THREAD

**Issue by mruepp** [ethereum/mist#697]
Node type: geth/eth
OS: osx
Network type: main/test
Mist version: 0.7.4

I did the following:
1. Bought DAO Tokens by using a wallet address created on the DAO Wizard Page. The Download Wallet Button did not work but only provided JSON text to cop/past.
2. I pasted it in a TXT File called DAOHub.txt and copied it into the Mist keystore Folder additionally to the Main Account (Etherbase).
3. The DAO Wallet appeared.
4. Later I bought Ether directly from coinimal and sent it to the DAO Wallet created before.
5. I sent ETH from the Wallet to the DAO to buy additional token.

The First transaction started and after a while, it dissapeared but no ETH was withdrawn.
A few minutes later I started the second transaction which worked, as far as I got additional DAO Tokens listed in my  Wallet and the respective Amount withdrawn from my Wallet.

When I look at the Wallet, no Transactions are shown. Not on the Wallet Page or on the Main Wallets Page.
I checked with another Mist installation and there the Transaction is shown on the Wallet Page and on the Main Wallets Page of the Ethereum-Wallet GUI.

The Transaction is listed on etherscan.io, however.

**Comment by luclu** [comment]
Assuming you followed these steps (on the daohub.org):
Step 1 : Choose your Currency --> ETH
Step 2 : Your Ethereum Account --> I want to create a new Ethereum account here in the browser, to import later in any wallet. 

You need to import the wallet within Mist --> menu --> accounts --> import presale wallet.
Make sure you keep the json-subfix.

I will close this for now as this is not a general problem. Feel free to stay here and discuss a solution for you problem with me.

**Comment by mruepp** [comment]
Actually import presale wallet was not working. The Dao Download of the json also not, it showed the json to copy/paste, not downloading it as file. I had to copy/paste it in a textfile which I named DAOHubwhatever.txt Copying the Textfile into keystore folder worked at the end, I have my Account in the Mist and it is also working but I can not see my transactions.
I hardly think that this issue is correlated with the naming of the DAO Wallet account file but think this is another issue, actually.

<img width="1136" alt="screen shot 2016-05-24 at 17 28 55" src="https://cloud.githubusercontent.com/assets/10906913/15509796/128f7b36-21d5-11e6-91d0-c4c4e514d9d4.png">

**Comment by luclu** [comment]
I removed the screenshot as a precaution as I guess it was your valid address?

**Comment by mruepp** [comment]
I see my transactions on etherscan.io but on my wallet gui there are no recent transactions listed. Actually it shows "no transactions yet". 
And no, this was a random wallet I generated for demonstration purpose.

**Comment by luclu** [comment]
Is your wallet fully synced?

**Comment by mruepp** [comment]
Sure, I am mining two days long.
1. Created Wallet on the DAO Page, then sent eth from bity.com with the wallet address I created. Worked so far.
2. Imported the Wallet File called DAOHub.txt into Mist by copying into keystore folder (osx)
2. Load ETH from coinimal.com to the DAO Wallet, received it, ok.
3. Sent ETH from the DAO Wallet to the DAO Address (reduced the transaction cost), but transaction got not through, the transaction just vanished.
4. Sent ETH from the DAO Wallet to the DAO Address with the cost slider on default position. Transaction vanished as well but lateron I received the DAO Tokens. So it worked but is not listed on the Mist Wallet Pages of the OSX Client.

**Comment by mruepp** [comment]
What I forgot: After I imported the Wallet, I accidentially created a Wallet Contract instead of adding the dao contract to the watched contract. The wallet contract was created successfully and the costs for the wallet contract were taken from the DAO - imported Wallet which had 0,1 ETH on it by default. This transaction also not got saved in the history.

This is the only thing uncommon I did.
