### ISSUE TITLE
unreadable text on gnome dark theme

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#702]
As reported in this issue: https://github.com/ethereum/mist/issues/523

![](https://cloud.githubusercontent.com/assets/8933663/14941210/c1c99f40-0f93-11e6-9d21-7315a96d9e1c.png)

**Comment by evertonfraga** [comment]
@alexvandesande so what's the plan here? 
• should we respect the OS theme – maybe investing time adapting to dark themes, there should be a way to gather this from electron
• or impose our colors in the background?

i should have a VM with this to see if/how that issue spreads throughout mist.

**Comment by alexvandesande** [comment]
Ideally we should respect the dark theme choice and increase contrast a bit, only for these users. Do you have a ubuntu VM to test this?

**Comment by luclu** [comment]
Alternatively we Could enforce `darkTheme: false`. Thought I myself being a dark-UI lover would be very disappointed.
But you could use this attribute for testing without a VM.
