### ISSUE TITLE
electron 1.0.1 bugs

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#703]
branch: `develop` (actually PR https://github.com/ethereum/mist/pull/700)
electron: `1.0.1`

Must be a problem [upstream](https://github.com/electron/electron/issues/1507) as [this](https://github.com/ethereum/mist/blob/develop/modules/menuItems.js#L343) is the correct `accelerator: 'CommandOrControl+Shift+1'` ([docs](http://electron.atom.io/docs/api/accelerator/)) and did work in `0.7.4`.

<img width="633" alt="bildschirmfoto 2016-05-25 um 01 47 55" src="https://cloud.githubusercontent.com/assets/10135872/15523476/f3b475f4-221a-11e6-865d-2d39d0547ecd.png">

---

Also missing mining icon:

<img width="617" alt="bildschirmfoto 2016-05-25 um 01 51 29" src="https://cloud.githubusercontent.com/assets/10135872/15523511/3a82604a-221b-11e6-8a8b-0568760f2b66.png">

**Comment by xMrWhite** [comment]
This behavior is inconsistent across OS X apps, see calendar vs safari 
![Calendar](http://puu.sh/p8Du7/0ac0236755.png). 
Notice the show spelling and grammar. 
![Safari](http://puu.sh/p8D7L/5b4c647951.png)

**Comment by luclu** [comment]
thank you @xMrWhite this seems to be a different behaviour.

As it was working in `0.37.2`
and is broken in `1.0.1`.

<img width="355" alt="unbenannt-1" src="https://cloud.githubusercontent.com/assets/10135872/15651240/a5bd2126-267e-11e6-99f3-7773d1f0e6c1.png">
