### ISSUE TITLE
[question] Shouldn't Private Keys be encrypted?

### ISSUE THREAD

**Issue by lyricalpolymath** [ethereum/mist#709]
OS: osx 10.9
Mist version: 0.7.4

Hi,
I was under the [impression](http://www.ethdocs.org/en/latest/account-management.html) that private keys in /Library/Ethereum/keystore
were supposed to be encrypted, right?

When I open them with a text editor they are readable json.
even the salt is readable.

- **Is that the correct behaviour or is it a bug?**

- **is it safe to store the keys like this (readable json) or it's better to encrypt them before backing them up?**

- **can someone do something with the keyfile if they don't have the password that was used to generate it?**

thanks
b.

ps. I'll take the chance also to thank you all for the amazing work you are doing on this system! :)

**Comment by frozeman** [comment]
Yes they are encrypted, @fjl @Gustav-Simonsson you want to give an explanation.

**Comment by fjl** [comment]
See https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition for details about the key file format. The short version is that each file contains a section called "crypto" which holds the actual ciphertext and all public parameters.

It should be safe to store the key in this format without encrypting it further.
Note that the file includes the Ethereum address in plain text form.

If the key file is stolen th attacker could brute-force the passphrase. This is true for encrypted storage scheme. We use scrypt to derive the encryption key to make brute-force slow in this case.

**Comment by lyricalpolymath** [comment]
thanks@frozeman and @fjl  for your reply...and for pointing out to the wiki.
That's an interesting resource, although the [web3 secret storage definition](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition) assumes a lot of previous knowledge of cryptography to understand it :)

you should add this is explanation you just gave here to the top of the article, as an introduction, and probably also to the [ethdocs keyfile documentation](http://ethdocs.org/en/latest/account-management.html#keyfiles)

thanks!
