### ISSUE TITLE
Could not find block zero

### ISSUE THREAD

**Issue by DaGitNah** [ethereum/mist#712]
Node type: geth
OS: Windows 10 x32
Network type: main
Mist version: 0.5.1

\AppData\Roaming\Ethereum\Chaindata
Fatal: chain db corrupted. Could not find block 0

**Comment by luclu** [comment]
@DaGitNah make sure to use the latest version 0.7.4 as 0.5.1 bundles an ancient version of geth.

Windows 32bit is **currently not supported** - that said you should be able to run it by downloading [Ethereum-Wallet 0.7.4 win32](https://github.com/ethereum/mist/releases/tag/0.7.4) and [geth 1.4.1-RC win32](https://github.com/ethereum/go-ethereum/releases/tag/v1.4.1). You will need to copy `geth.exe` into `Ethereum-Wallet\resources\nodes\geth\`. If possible try to get your hands onto another PC / OS as `geth 1.4.1-RC` is not up-to-date and contains a [security-vulnerability](https://blog.ethereum.org/2016/05/17/security-alert-geth-suffers-from-a-very-low-probable-dos-attack-vector-update-immediately/).

You might need to delete the `chaindata`-folder to startup.
