### ISSUE TITLE
Block hash 1,148,910 failure

### ISSUE THREAD

**Issue by fjoes** [ethereum/mist#713]
Well, I was asked to kindly report this... 

Node type: geth
Network: main
Platform: darwin (Architecure x64)

...I0525 20:52:09.448215 cmd/utils/flags.go:687] You're one of the lucky few that will try out the JIT VM (random). If you get a consensus failure please be so kind to report this incident with the block hash that failed. You can switch to the regular VM by setting --jitvm=false
I0525 20:52:09.448349 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to /Users/mark/Library/Ethereum/chaindata
Fatal: Could not open database: resource temporarily unavailable

**Comment by luclu** [comment]
What version are you currently using? Also are you running any externally launched instance of `geth`?

**Comment by fjoes** [comment]
Version 0.7.4, no externally launched geth 's

**Comment by luclu** [comment]
@fjl could you have a look at this?

**Comment by fjl** [comment]
The messages are unrelated. The second message tells you that another geth instance is already using the database.

**Comment by luclu** [comment]
@fjoes make sure you didn't run geth twice. 
I will close this for now.
