### ISSUE TITLE
error/infinite import of wallet-file

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#714]
The import of non-presale-wallets will cause a stalling/infinite import dialog.
Affected wallets (web3-secret-storage version 1 to 3):
- myethereumwallet.com
- kryptokit https://github.com/ethereum/mist/issues/631
- Mist wallets (create wallet, move out of `keystore` and import)

We could also change the menu-label from `import Pre-sale Accounts` to `import Wallet`.

**Comment by alexvandesande** [comment]
@luclu what's the status on this?

**Comment by luclu** [comment]
There is an outstanding design decision - I would like to get your input at. 

As you know the import-wallet view will ask for a password after the drop event, but as
web3-secret-storage-files just need to be copied it is not needed. Which gives me three possibilites:
 1. let the user input the password regardless of the wallet type and use the code at `ipc_import-etc` to decide on the procedure
 2. get some js to figure out the wallet type before proceeding to the password screen
 3. use user input elements to let the user decide on the wallet type
 4. create a second menuitem for web3-files

I would clearly prefer 2. but can't figure out a way to include `fs` to read and evaluate the json file for its type within meteor's onboarding js code (clientside). 
Which leaves me with new ipc-command and evaluation before the user might be prompt for a password.

**Comment by hiddentao** [comment]
(2) is the most elegant solution, but (3) is a decent fallback.

**Comment by luclu** [comment]
Implemented basic functionality of (2). Import of web3 as well as presale files is now possible. The former will directly show the importing animation as a dummy for 750ms.
