### ISSUE TITLE
wrong password

### ISSUE THREAD

**Issue by georgetsn** [ethereum/mist#716]
hello,

i cant make transactions every time i get the yellow message wrong password 
my password is 100% correct.

i try to unlock my acc from geth but it takes too long  is that normal?

**Comment by luclu** [comment]
@georgetsn please try out these recommendations and give me a ping-back. https://github.com/ethereum/mist/issues/669

**Comment by georgetsn** [comment]
im trying to unlock my account
`Unlocking account 0x75aA58C266e3f89497456e6aac704094b818cEA2 | Attempt 1/3
`

**Comment by georgetsn** [comment]
nothing works, i will try to move keystorefiles to another computer

**Comment by luclu** [comment]
Do you get an error message or is the dialog just freezing?

**Comment by georgetsn** [comment]
i've failed to unlock my acc , maybe there is no solution :/     anyway thanks for help :)

**Comment by luclu** [comment]
Could you try opening it with myethereumwallet.com as suggested in #669?

**Comment by georgetsn** [comment]
my pc is freezing when i press "unlock wallet" i cant do this process

**Comment by luclu** [comment]
...you will only need to copy the json-wallet from the `keystore`-folder for this process.

**Comment by luclu** [comment]
I will close this issue for now but feel free to stay and discuss a solution for your problems.
