### ISSUE TITLE
Send ether from wallet contract when owner has 0.00 balance

### ISSUE THREAD

**Issue by larrysmith1000** [ethereum/mist#717]
Does anyone know of a way to send funds from a wallet contract when the owner of the wallet has a 0.00 balance?  I understand that the owner has to pay the transaction fee, but that presents a problem when the owner has a 0.00 balance.

The wallet contract can't even send funds to the owner, which should be an exception to the rule.

This is like going to a bank machine, and having to pay the transaction fee with cash prior to being able to withdraw funds from your own account.  No cash, sorry, you can't withdraw cash then.

If this is not possible, then users should be warned that if they transfer all their funds to a contract they own, they will not be able to get the funds back without getting funds from another source.  This is especially true since there is a button that says, "send everything".

Imagine if every account on the blockchain click send everything to store all their funds in a contract wallet.  Then the blockchain would be frozen.  No accounts would have funds to withdraw their funds from their wallets.

Thanks in advance if you send a solution.

**Comment by luclu** [comment]
@larrysmith1000 Thank you for this suggestion. Could you kindly reopen this issue on the [dapp-repo](https://github.com/ethereum/meteor-dapp-wallet)?
