### ISSUE TITLE
Couldn't Start an ethereum node - or fatal error

### ISSUE THREAD

**Issue by Maikelinho** [ethereum/mist#718]
Node type: geth/eth
OS: windows
Network type: main/
Mist version: 0.0.0

![2016-05-26 1](https://cloud.githubusercontent.com/assets/19591744/15576167/e5055a36-2356-11e6-8821-3ebad36f3009.png)

Hello,

I can't get into my Ethereum Wallet anymore since today.

Can somebody help me?

**Comment by luclu** [comment]
@Maikelinho please update to version 0.7.4 bundling geth 1.4.4. This sould help.

**Comment by Maikelinho** [comment]
Doesn't really help, it made a new account, but just before the new account popped up, i saw my old account. Also, my previous transactions are still visible in the wallet.
