### ISSUE TITLE
Allow pasting of password in "Enter Master Password

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/mist#72]
It would be nice to be able to paste into the password field in this prompt.

![screen shot 2015-11-19 at 10 46 20 am](https://cloud.githubusercontent.com/assets/824194/11278949/ddc2830c-8eaa-11e5-854b-f22540aa186c.png)

**Comment by frozeman** [comment]
This is not working as the app menu is not instantiated at the time (which will add the past functionality)
I will think about adding it.

**Comment by pipermerriam** [comment]
I use a password manager for all of my passwords.  My master password is 50
characters of hard to type randomness so it would be a really nice
improvement.  Thanks

**Comment by frozeman** [comment]
Ok i understand, fixed in the latest develop
