### ISSUE TITLE
Few questions on update

### ISSUE THREAD

**Issue by ethertothemoon** [ethereum/mist#720]
Node type: geth/eth
OS: windows
Network type: main
Mist version: win64-0-7-4

Hi, I spent the last few days trying to solve an issue, which appears to be solved, but I had some questions to help me learn what I did to solve and to learn the wallet in general.

As far as the issue, when I restarted my computer a few days ago, I began to get the error "no ethereum node binary found"  A few minutes ago, I clicked on eth.exe in resources//node/eth/, and then I clicked on ethereum-wallet.exe, and it seems to be working and syncing.

Here are my questions:

1. I believe I first tried to upgrade from version 0-7-2 to 0-7-4.  I am used to upgrades, but this seems to be a new install of 0-7-4, while still keeping the files from 0-7-2.  Can I now safely delete the files from 0-7-2?   

2. What did I do by clicking on eth.exe?

3. I read another post with the same error, and they recommended deleting the Ethereum folder in Appdata and backing up the keystore folder or whole Ethereum folder.  I was going to backup the Ethereum folder but it was like 2 gb in size.  Would this folder get recreated if I deleted it?    

4. Another post recommended deleting the Mist folder.  What would this do?  Is this safe for the wallet to continue to run?

5. If I have the passcodes from one wallet, would this allow me to open up another wallet on my phone and move the ether to the new wallet without having to send ether?

Thanks for any help you can provide.

**Comment by luclu** [comment]
Hi @ethertothemoon, feel free to stay and discuss with me.

1. You can saftely delete the binaries as the configurations and most importantly the wallets are store under `%APPDATA%\roaming\Ethereum` and `%APPDATA%\roaming\Mist`.
2. You externally started the **eth**-node. Mist should connect to this as it is started. If you don't do this Mist will launch the node. But the **eth**-node is experimental and several bugs are know: https://github.com/ethereum/mist/issues/607. I highly recommend you to stick to the **geth**-node for now.
3. Deleting this folder is the last resourt. It contains a replica of the blockchain as currently no light-client functionality is implemented (yet) this grows huge (currently up to 16Gb).
4. This is currently serving caches and holding logs for the current Wallet session. This might change in the future.
5. You can have copies of the wallet's json-file on abitrarily many devices - no difference.

**Comment by ethertothemoon** [comment]
Thank you for the detailed response!
