### ISSUE TITLE
No access to new account

### ISSUE THREAD

**Issue by rbrtwy** [ethereum/mist#722]
Node type: eth
OS: windows
Network type: main
Mist version: 0.5.2

I started downloading the blockchain about 2 days ago.  But I am still only on block 1,473,915 of 1,591,713.  Should it take this long to download?  Also, when I first started downloading the blockchain, I was given the option of depositing bitcoin (which would be converted to eth).  I received confirmation that the deposits went through o.k., but I cannot get into my wallet.  On the "Load it up!" screen, I try to go to "Main account (etherbase)", but the option is not highlighted.  On the screen where it shows the deposit confirmations, I have an option "Ethereum Wallet" but it only drops down to "About Ethereum Wallet" or "Quit Ethereum Wallet".  There is no actual "Wallet" like I've seen on other screenshots of the screen.  A screen shot of my "wallet" is below:

![screen](https://cloud.githubusercontent.com/assets/19600750/15596932/1a49361a-2391-11e6-8654-8e32a5fc2c86.jpg)

**Comment by luclu** [comment]
@rbrtwy please update to the latest version 0.7.4. This should solve your problems. Also make sure to stick to the **geth**-node as **eth** support is currently only experimental and contains several bugs. I will close this for now. Ping me back on the outcome!

**Comment by rbrtwy** [comment]
@luclu Thank you for responding.  Just want to ask to be safe - before doing the update, do I need to back up my keystore files?  If so, I cannot get access to it within Mist.  Is there a way to go into the folder through file explorer and back it up that way?

**Comment by luclu** [comment]
You don't need to backup your `keystore`-folder for an update as this is not touched by it - although it is a good idea to have a backup anyways. ;) (you will need to backup any newly created wallet address (json-file) only once)
The folder is located under `%APPDATA%\roaming\Ethereum`.

**Comment by rbrtwy** [comment]
@luclu Thank you so much.  This should the last question for now - is there an upgrade "button"?  Or do I just download 0.7.4 and open it, and that is the upgrade process?  Do I need to delete the old version before I open 0.7.4?  Thanks again.

**Comment by luclu** [comment]
No worries @rbrtwy you are welcome to ask any question (you can also you [gitter](https://gitter.im/ethereum/mist?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for this).
You can just start the new version and delete the old one.
