### ISSUE TITLE
After loading a presale json file into Mist 0.7.4, the Main account in the wallet (etherbase), which has DAO tokens in it, doesn`t show said DAO tokens anymore. 

### ISSUE THREAD

**Issue by Quazoo** [ethereum/mist#723]
Few weeks back i downloaded Mist and send some ETH to it. Then i bought some DAO tokens, which showed up nicely in the Main account. Today i loaded a presale json file into Mist and i got the second account. But now the DAO tokens are gone from Mist. I can`t send them from the Mainaccount.

Mist 0.7.4 Windows 10 x64

**Comment by luclu** [comment]
@Quazoo please make sure you are watching the DAO token. You can also use a blockchain-explorer like etherscan.io to check the tokens balance. Ping me back on the outcome!

**Comment by Quazoo** [comment]
@luclu thanks. Indeed i had to readd the DAO token as watched. I can now again see and send the DAO tokens from the main account.
