### ISSUE TITLE
DAO Token Balance Discrepancies 

### ISSUE THREAD

**Issue by larrysmith1000** [ethereum/mist#725]
Hi -

The amount of DAO Tokens listed as a balance in various places in Mist Ethereum Wallet are different.  First, the balance for me given on daohub is: 28,000

On the account view it shows the correct balance: 28,000
On the contract view under "Custom Tokens" it says: 9,555.588549...
On the DAO view (when you click on The DAO contract under custom contracts) it says: 6755.588549...

See attached screenshots.
![capture1](https://cloud.githubusercontent.com/assets/19583370/15600588/ca026a3c-239f-11e6-96cd-635ba515cad0.PNG)
![capture2](https://cloud.githubusercontent.com/assets/19583370/15600591/cdb0758e-239f-11e6-8f5a-9bfedd767a42.PNG)
![capture3](https://cloud.githubusercontent.com/assets/19583370/15600593/d0113412-239f-11e6-8e1d-89755158a0b0.PNG)

Not sure if this is a contract coding issue, or Mist Wallet issue.

**Comment by luclu** [comment]
Thank you for reporting @larrysmith1000. 
We are aware of this issue and will fix it in the next version: https://github.com/ethereum/mist/issues/608
I will close this as a duplicate.
