### ISSUE TITLE
How to Import Ethereum Wallet

### ISSUE THREAD

**Issue by jamon2** [ethereum/mist#730]
Node type: geth
OS: windows
Network type: main
Mist version: 0.7.4

I'm a total newbie. I downloaded the Ethereum Wallet this morning and deposited some Ether using Bitcoin, then sent some Ether to The DAO. While trying to copy my Ether address, the Ethereum Wallet hung up so I closed it. When I tried to reopen it I couldn't find an application file to open. I re-opened the Ethereum-Wallet application file that I had originally downloaded, and it re-downloaded the entire Ethereum blockchain and started a new wallet. Now I can't figure out how to find my original wallet that has ETH in it. I'm hoping to find the wallet files from this morning and import them to my new wallet (or just access them from my original wallet). Any advice on how to find and use these files would be greatly apprecieated!

**Comment by luclu** [comment]
@jamon2 I'm not quite sure what the question you have is.
You will find that the wallet-files are stored under `%APPDATA%\roaming\Ethereum` in a folder called `keystore`. There is also another folder called `chaindata` cointaining the replica of the blockchain. Those folders are persistent over any session regardless which version of the **Ethereum-Wallet** you evoked to start. There is no way your client needs to sync the complete blockchain twice unless you deleted the `%APPDATA%\roaming\Ethereum`-folder which in turns will delete your wallet-files unless you have a backup of those.
Hope that helps to clarify things. Feel free to stay here. I will close this for now as it doesn't seem to be a generic problem.
