### ISSUE TITLE
OSX Notification that 0,0000001 DAO Token were sent to address....

### ISSUE THREAD

**Issue by mruepp** [ethereum/mist#731]
Node type: geth/eth
OS: osx
Network type: main/test
Mist version: 0.7.4

When I run the Mist wallet, it hangs occasionally. Two times now I got the OSX Notification that 0,000001 DAO Token get sent to some account which I was not able to see completely.

After that I clicked on the notification the wallet got focus but hang.  This is a very big concern for me.

Also the Wallet is basically not usable because the interace hangs all the time and I don´t see my past transfers as well. I wether see the past ETH transfers but the Wallet also shows "No Transactions yet" despite I sent ETH to the DAO Account

**Comment by luclu** [comment]
Thank you for reporting @mruepp. Please have a look at https://github.com/ethereum/mist/issues/726
I will close this for now as a duplicate.
