### ISSUE TITLE
Copy adress to clipboard does not work, copies nothing

### ISSUE THREAD

**Issue by Guido1234** [ethereum/mist#733]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by LeeBlues** [comment]
Linux 64 ubuntu 0.7.4 has same issue!!

**Comment by speedery** [comment]
same issue with Ubuntu 16.04 64bit

**Comment by Undland** [comment]
same issue in Win10 x64. It can not be worse than this bug. When will he stop suffering from such childhood diseases?

**Comment by Nogreedy** [comment]
Known issue - bug
#650 
#690

**Comment by luclu** [comment]
Thanks for reporting. I will close this as it is a duplicate as @Nogreedy pointed out.
