### ISSUE TITLE
Getting "The account you want to send from is empty" when sending DAO tokens

### ISSUE THREAD

**Issue by badmoon64** [ethereum/mist#736]
Please help if you can.  I am trying to send my DAO tokens to a exchange.  I go to "Main account (Etherbase)" on the main screen.  It shows 0.0 Ether up top, and below that it shows "The DAO 100,000"
So all looks OK so far.  Then I click on "Send".  Another screen pops up:  "From" on the left says "Main Account (Etherbase)  0.00 Ether.  It the "o" box to the right I put the address I am sending to.  Then the LOWER RIGHT BOX I toggle from "Either - 0.00"  to the "The DAO" box that drops below it.  Then I click on "Send everything" box on lower LEFT side.  I correctly fills the number of my DAO tokens.  "You want to send x.00000etc Ð of The DAO"   BUT... the box in the upper right "From" will NOT toggle to show the DAO.   Make any sense.  Any help from this smart group would be most appreciated.

**Comment by badmoon64** [comment]
Another thought.  I did not "add data" if that matters

**Comment by badmoon64** [comment]
[wallet pic.docx](https://github.com/ethereum/mist/files/287960/wallet.pic.docx)

**Comment by naut** [comment]
I had the same problem and found out why this was happening:

In order to send DAO tokens the wallet you're sending from has to have some ether to pay for the transaction cost.

It should tell you how much ether is needed in the send window. 

Cheers.

**Comment by badmoon64** [comment]
Worked!   Thanks.

**Comment by techyeth** [comment]
HI,
can i know the reason behind i am not getting my ether balance,,instead i follow the same process,,i really get stuck.:)
