### ISSUE TITLE
Block synchronisation on startup taking long time, progress not displayed correctly

### ISSUE THREAD

**Issue by calummaciver** [ethereum/mist#737]
Node type: geth
OS: osx
Network type: main
Mist version: 0.7.4
Hardware/Bandwidth: SSD drive and 360 Mbit/s download

Have been trying to sync up my node for around 8 hours with a few restarts. Attached the logs from the latest restart. The progress bar is also incorrect which does not help - "Downloading block 1,571,748 of 1,549,976". 

![screen shot 2016-05-28 at 21 55 00](https://cloud.githubusercontent.com/assets/879525/15630006/6b82c37a-2521-11e6-84a4-6e0e0f43e6ee.png)

[node.txt](https://github.com/ethereum/mist/files/288011/node.txt)

**Comment by webdevotion** [comment]
Also seeing this issue on Mac OS 10.11.5 with version 0.7.3.

![screen shot 2016-05-30 at 13 40 11](https://cloud.githubusercontent.com/assets/50583/15648624/10149ddc-266c-11e6-8420-92922dcfae5c.png)

**Comment by luclu** [comment]
Thank you for reporting @calummaciver!
As this is a know issue: https://github.com/ethereum/mist/issues/504 I will close this as a duplicate.

@webdevotion could you kindly reopen your comment as a new issue?
