### ISSUE TITLE
cannot send ETH or DAO Tokens from MIST. Unknown transactions shown. Wrong balances shown.

### ISSUE THREAD

**Issue by FaguiCurtain** [ethereum/mist#739]
Node type: geth/eth
OS: MAC OS X 10.11.5 (ElCapitan)
Network type: main
Mist version: 0.7.4

Hello, please I really need your help !!

I start to have a long history of trouble with MIST. 
my MIST could not sync, so i had to reinstall it from zero after saving keystore folder, and deleting everything. Finally it could sync, although AVAST is quarantining some files and i had to manually restore them a few times.

So now i do see my balances in my wallet finally [](url)
<img width="1100" alt="capture d ecran 2016-05-29 a 10 40 02" src="https://cloud.githubusercontent.com/assets/11316512/15631091/ee85101a-2590-11e6-83b2-7992b76747c4.png">

however on that screen, the balances shown for DAO tokens are wrong
<img width="1100" alt="capture d ecran 2016-05-29 a 10 39 41" src="https://cloud.githubusercontent.com/assets/11316512/15631092/1070ab58-2591-11e6-8011-840ea1f31421.png">

then i wanted to give a try and send 100 DAO tokens to my Kraken account using maximum fee to speed up things.
However it seems i copied/paste the wrong address, (because i clicked on the "select" button from my chrome browser in Kraken web page, but it didn't work well) and tried sending them to myself !!!

<img width="583" alt="capture d ecran 2016-05-29 a 10 04 57" src="https://cloud.githubusercontent.com/assets/11316512/15631096/7bdd4d7e-2591-11e6-82a9-4263b456da59.png">
So its been "confirming" forever, I didn't notice at first i input the wrong address, i did a screenshot and restarted MIST. Then i realized my mistake, and wanted to try sending those 100 tokens to the right address, but the same problem occured:
<img width="1046" alt="capture d ecran 2016-05-29 a 10 26 56" src="https://cloud.githubusercontent.com/assets/11316512/15631101/ac62f7aa-2591-11e6-9800-b3c94224441e.png">

Finally, i made this screenshot, and restarted again, and tried sending ETH instead of DAO tokens....
and the same thing is happening 

<img width="1101" alt="capture d ecran 2016-05-29 a 11 23 03" src="https://cloud.githubusercontent.com/assets/11316512/15631104/c761ca2c-2591-11e6-9d79-0cf4cff9766e.png">

Of note, also i see some unknown transactions to me in MIST browser, as shown here:

<img width="1104" alt="capture d ecran 2016-05-29 a 10 38 22" src="https://cloud.githubusercontent.com/assets/11316512/15631108/e1c61e54-2591-11e6-88c6-3080f31bceda.png">

I'm really afraid my ETH or DAO is lost / hacked... please help thanks !!

**Comment by FaguiCurtain** [comment]
here are the etherscan links
http://etherscan.io/address/0x8C18906cA6133925281fc8e8d249eadCa22eD029
http://etherscan.io/token/TheDAO?a=0x8c18906ca6133925281fc8e8d249eadca22ed029

**Comment by alexvandesande** [comment]
Your computer is not compromised. All of those are known bugs, you happened to have all of them at the same time. The only real dealbreaked here I don't understand is why it's always confirming, it seems something wrong with your geth version.

Have you tried a previous version of the wallet?

**Comment by FaguiCurtain** [comment]
In a previous problem (no sync) , i was told to install the latest version of GETH and MIST...I certainly don't want to reverse that.

**Comment by FaguiCurtain** [comment]
i see that someone to solve his problem tried sending a higher amount of mone

**Comment by FaguiCurtain** [comment]
small update: 
i got a message from my MIST browser that some transactions were not executed
i'm trying to send a new 1 ETH transaction, still "confirming", no progress there

<img width="1106" alt="capture d ecran 2016-05-29 a 12 34 10" src="https://cloud.githubusercontent.com/assets/11316512/15631249/2c603320-259a-11e6-8916-88578a294872.png">
<img width="1101" alt="capture d ecran 2016-05-29 a 12 33 16" src="https://cloud.githubusercontent.com/assets/11316512/15631251/357fada0-259a-11e6-8aa3-2a61fc93f09a.png">

**Comment by FaguiCurtain** [comment]
i hope its not due to a password / key problem and the ETH/DAO are still available to me...

**Comment by FaguiCurtain** [comment]
and now, to make matters worse, i tried to open MIST again today, and send a higher volume transaction to Polo . This time it didn't accept my (complex) password. I typed it twice. I didn't want to try one more time because i was afraid it would lock my account. I am now waiting for instructions to do anything

**Comment by FaguiCurtain** [comment]
ok some of the issues are solved, not all of them:

i can now send transactions (whew !!!). I don't know why suddenly its possible. I tried sending a transaction with a higher quantity and higher fee and it went in immediately. However i don't see the transactions above as being executed at the same time the new one went it.

I still see transactions which don't belong to me, and one screen is showing the wrong balance in tokens (the other is ok), as per previous screenshots.

**Comment by AlmostConsultant** [comment]
I confirm to have my wallet in the same state in windows 10 (wrong token balance, showing foreign transactions going to dao address, mist rewriting recipient address by the dao one). My wallet on another computer is the same, except it shows correct balance of tokens.

**Comment by luclu** [comment]
The falsely reported accumulated token balance has been fixed in version 0.7.5.
Those transactions are due to the logging of contract's events. This can be turned of on per contract basis in version 0.7.5.
