### ISSUE TITLE
Adding  an authorise boolean for token transaction in multisig wallet contract

### ISSUE THREAD

**Issue by olivierstern** [ethereum/mist#742]
It would be a great feature to add a boolean in the multisig wallet contract that prevent transaction of token without the confirmation requirements in order to protect the tokens owned by the contract. For the moment it is only possible to set a max ether per day. Since there might be many different tokens with different value, a simple yes or no authorization field to allow or prevent token transaction without confirmations would be a great feature fo securing tokens. What is your opinion ?

**Comment by luclu** [comment]
@olivierstern Thank you for this idea. Although you better post this suggestion on the wallet-dapp's repo [link](https://github.com/ethereum/meteor-dapp-wallet). I will close this one here!
