### ISSUE TITLE
"Pick A Function" dropdown is black

### ISSUE THREAD

**Issue by linagee** [ethereum/mist#744]
Node type: geth
OS: linux
Network type: main
Mist version: 0.7.4

- Screenshots
![screenshot_2016-05-29_13-12-19](https://cloud.githubusercontent.com/assets/636551/15635579/496c9df0-259f-11e6-86b7-38aa5ff1d63e.png)

If I wait for a long time, of course it gets really really slow. But if I quickly open Ethereum Wallet and pull down the Pick A Function, it's black.

I've had to use the --ignore-gpu-blacklist in the past. I see it's included in the code now to use that by default.

**Comment by luclu** [comment]
@linagee thank you for reporting!
As I don't know about Electron/Chromium's internals let's try to isolate this issue.

1. Have you already been affected by this issue in earlier version of the Wallet? 
2. What desktop-shell are you using?
3. Have you been changing its themes in the past?
4. Is this also happening using proprietary graphic-drivers (could rule out 2.+3.)?
5. Does this happen with *The DAO*'s minimal JSON-interface?

**Comment by luclu** [comment]
@linagee who is version `0.7.5` working for you? We updated electron to `1.2.2`..

**Comment by luclu** [comment]
This might be fixed upstream in electron.
