### ISSUE TITLE
ACCOUNT IN MIST WALLET LOCKED

### ISSUE THREAD

**Issue by MrMontana** [ethereum/mist#745]
Node type: geth
OS: linux/windows
Network type: main
Mist version: 0.7.4

Hi All,

Last night I set up a contract to watch my token which in turn allows me to move it to exchanges and other wallets etc. When looking to move DAO from my Mist Wallet to Kraken it asked me to input my password...I did this 3 times incorrectly (which is an issue in itself) it then had a red block pop up that said the account is locked.

Now I know my password will be one of a few so will eventually get it right BUT need to know how long the account is locked for and do I have to do something to unlock it? Also...how many tries do you get?

Any help is appreciated.

Cheers

**Comment by luclu** [comment]
This is a generic call-back alert you experienced. Which means that the `unlockAccount`-function - which will internally ask three times for a user-input - returned the current state of the locked account.
There is no timeout or grace period implemented so you are good to go and retry whenever you want to.
I will close this for now. Feel free to stay and discuss.
