### ISSUE TITLE
Need Ethereum- Mist Wallet to run on OS X 10.8.5

### ISSUE THREAD

**Issue by SFIII** [ethereum/mist#747]
I'm not going to upgrade my computer and buy all new software just to run this wallet application. Thanks.

**Comment by luclu** [comment]
@SFIII the **Ethereum-Wallet** is build on top of **[electron-shell](http://electron.atom.io/)** which in turn leverages chromium and the VP8-Javascript-engine. According to [electron's docs](http://electron.atom.io/docs/development/build-instructions-osx/) OS X 10.8 is supported though I have no experience running on this legacy OS-version. 
Furthermore Apple ceased the official support for Mountain-Lion as it reached its end of lifecycle.

That said we can't afford to support legacy Operation Systems. You might want to get in contact with your Apple Reseller / Support.
That said, could you please state what kind of problems you are experiencing?

**Comment by SFIII** [comment]
Just simply that there's a circle with a line across it and I'm not 
permitted to open or install it.  Yes, Apple ceased support but a lot of 
people still use Mountain Lion. AND it is still supported by all major 
software companies which means that I dont' have to upgrade (yet) and I 
get a mostly trouble-free operating system. Upgrading often means that 
software stops working, and when you are invested heavily in fancy 
software, you tend to not upgrade very often.

Segue
