### ISSUE TITLE
Allow watching the same contract several times

### ISSUE THREAD

**Issue by chevdor** [ethereum/mist#748]
This is a **Feature Request**, not an issue.

In the current version (0.7.4), when you add a new entry to watch a contract, you provide:
- name
- address
- json interface

If you decide to watch the same contract with another interface, it replaces the previous 'watch'.

I think it would be good a ADD a new entry instead of replacing the old.

In the context of the DAO for instance, one may want to use the mimimal interface for daily business (while keeping is simpler and more secure) but also use the full interface.
Since we can name the watched contracts, I would typically have 2 "watches" set on the same contract, one with the minimal interface and one with the full one.

**Comment by alexvandesande** [comment]
This is a feature that will be better served by building a custom interface for the Mist Browser. We are not going to add complex contract features to the wallet

**Comment by chevdor** [comment]
ok, where is the repo for the "Mist Browser" so I can fill that in?
