### ISSUE TITLE
Starting Wallet and immediately crash (yesterday was okay)

### ISSUE THREAD

**Issue by szormok10** [ethereum/mist#752]
I use the newest wallet for 2 weeks. Yesterday I have started mining (wallet still working) and today was the first payout (I don't know it is important or not, just few information).

Today I want to start wallet and appear only 2 second "starting ethereum node" and quit. I have tried older version, restart, reinstall, full uninstall etc. The problem still exist.

Please help me or give me some tip! (my key has a copy)
Thanks

Node type: eth
OS: osx
Network type: main
Mist version: 0.7.4

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment]
@szormok10 please try to switch to **geth** as a backend as the integration of **eth** is currently only experimental and several bugs are know: https://github.com/ethereum/mist/issues/607
I will close this for now. Feel free to stay and discuss.
