### ISSUE TITLE
When changing --datadir location to external SD card in Geth, Mist will not start

### ISSUE THREAD

**Issue by bitcoinmeetups** [ethereum/mist#755]
When changing --datadir location to external SD card in Geth, Mist will not start.

There are at least two questions on ethereum.stackexchange.com regarding this issue already.

Mine:

http://ethereum.stackexchange.com/questions/4472/i-run-geth-with-this-command-when-i-try-to-start-mist-i-get-this-error-message (ignore the blockchain corrupt thing, Geth is running fine so that is probably an irrelevant non-issue)

And someone else's

http://ethereum.stackexchange.com/questions/1865/running-out-of-storage-space-want-to-move-mist-chaindata

So basically:

This is the command I use to run Geth:

geth --datadir /media/user/sdcard/chaindata --ipcdisable console

The command specifies that the blockchain data should be downloaded to the SD card rather than to the internal hard drive. It works fine for running Geth itself.

But when I try to start Mist I get [various] error messages.

Why do I get the error message(s) and more importantly, what should I do to be able to make Mist actually run when I start Geth the way I do as specified above?

---

Kindly let me know if this issue has been rectified already.

**Comment by luclu** [comment]
@bitcoinmeetups as Mist leverages IPC-sockets it won't be able to connect to geth if the sockets location (in the datadir) has been changed from its defaults.
There are several ways you can go about this:

1. use symlinks to point to the new location `ln -s`
2. leave geth's `--ipcpath`-flag pointing to the default location
3. build from `develop`-branch as this includes the possibilty to pass those flags like `--datadir` from Mist to its internal geth-node (https://github.com/ethereum/mist/pull/689)
4. wait for the release of 0.7.5

Feel free to discuss on this! Altough I will close for now.
