### ISSUE TITLE
Node Crashed, please create an issue....

### ISSUE THREAD

**Issue by GitJeffHub** [ethereum/mist#756]
Node type: geth
OS: windows
Network type: main
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minimum.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
![image](https://cloud.githubusercontent.com/assets/19667266/15674526/3d2b9ee8-270b-11e6-8491-71e78b7e1a2d.png)

=========================================
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log
=========================================

**Comment by luclu** [comment]
@GitJeffHub please specify which version you tried to run.

**Comment by luclu** [comment]
@GitJeffHub I will close this for now as of inactivity and suspect this to be solved in some way.
If you still encounter this issue please ping me back!

**Comment by GitJeffHub** [comment]
Thanks Luca,

Installing the newer version of Mist took care of things.

Best,
Jeff Stewart
703-304-1683 (Cell)

**Comment by luclu** [comment]
awesome!
