### ISSUE TITLE
Change data folder

### ISSUE THREAD

**Issue by nikolaygit** [ethereum/mist#759]
How can a user change the data folder?

Reasoning: if the drive on which the data folder is currently stored does not have enough free space the user cannot use Mist browser.

**Comment by luclu** [comment]
Please use the search before filing an issue:
https://github.com/ethereum/mist/issues/572
https://github.com/ethereum/mist/issues/270
https://github.com/ethereum/mist/issues/755
https://github.com/ethereum/mist/issues/682

**Comment by nikolaygit** [comment]
thanks! Now I know better which keywords I should have used.
