### ISSUE TITLE
Contract Wallet transaction issue

### ISSUE THREAD

**Issue by cmditch** [ethereum/mist#76]
I sent ether to my newly created account on the gui. I then Added a Wallet, and transferred ether from the owner account to the Contract Based Wallet - this worked fine.

I tried sending ether to the wallet from another account with no success though. Despite showing up on the blockchain, the balance has not updated. 

https://etherscan.io/address/0x727c8217b0005e3e5362103bd80976f6fd3bb99d

As you can see, the account has 52 ether, despite having 6 txs of 72.9979 Ether going in, and only 2 ether going out.

I understand this may simply be my ignorance on ethereum transactions, and I apologize if so, please correct my confusion if that's the case. Thanks!

Edit: I realize this wallet is a contract and not an account. I must be mistaken in thinking you can transact with this wallet like you would an account.

**Comment by frozeman** [comment]
I assume for some transactions you simply send to less gas, so it reverts the transaction and never "sends" it.

**Comment by frozeman** [comment]
We will add an `outOfGas` property at some point, so this should be then less of a problem
