### ISSUE TITLE
Accounts missing from 0.7.4

### ISSUE THREAD

**Issue by efox29** [ethereum/mist#761]
Node type: geth
OS: windows
Network type: main
Mist version: 0.7.4

I've been using mist 0.6.1 and 0.6.2 since I reported issue #525. I've had watch contracts up for the DOA. I have not deleted them.

I recently upgraded to 0.7.4 and it asked me to create a new account (as if this was the first time), and I did. After a few days of hangs, today I was finally able to get into the wallet. However, none of the accounts are there.

When I look at the the backup folder, I see what I think are my keys. I see 5 files (which sounds like my missing wallets).

I was led to believe that mist wallet automatically finds the accounts (and I have had not had any issues going from 0.6.1 to 0.7.2 and back. It's just 0.7.4.

How can get my accounts back into 0.7.4 ?

**Comment by luclu** [comment]
@efox29 are these fife files located under `%APPDATA%\roaming\Ethereum\keystore`?

**Comment by efox29** [comment]
@luclu correct.

**Comment by efox29** [comment]
@luclu do you have any suggestions ? I'd like to collect my DAO tokens so I can participate but I am still unable to get access to my wallet which I've used to buy DAO tokens.

**Comment by luclu** [comment]
@efox29 if you regard yourself as tech-savvy you I would love you to open up the dev-console in **Ethereum-Wallet** `0.7.4` by hitting `Ctrl+Alt+i` and type `web3.eth.accounts`. Does this show all of your account addresses?

If not please try those two things:
1. Create a backup of the `keystore`-folder and remove the `%APPDATA%\Ethereum`-folder, restore the keyfiles after that. You might have to resync after this - to avoid this also backup the `chaindata`-folder.
2. If you want to participate in the "The DAO" proposals right now I recommend to try out [myetherwallet.com](https://www.myetherwallet.com/#the-dao).

**Comment by efox29** [comment]
@luclu it displays nothing. 

When pressing `Ctrl+Alt+i` it opens up the Audits tab of the Developer tools.
When I click on the console tab, and I enter 'web3.eth.accounts' the text I have entered disappears, and nothing is displayed.

I'll wait a few hours before moving onto deleting the Ethereum folder in case you have some other things you want to try.

**Comment by efox29** [comment]
@luclu I first deleted the entire Ethereum folder (made a copy of keystore and chaindata). I started up Mist again and it loaded nor did I have to resync anything. I was able to see the "new" addresses (not the ones I really want to see) and everything was fine. When I went into '%APPDATA%', the Ethereum folder (which I deleted before), is not even there.

I deleted the Mist folder as well in the same section and restarted Mist. Same thing, it starts up with no issues and with no resync. Looks like it can see the blockchain somewhere even though I deleted chaindata.

**Comment by efox29** [comment]
@luclu I have installed Mist on my laptop (previously was not installed) and synced the blockchain and then copied my keys over. Mist on my laptop took it. I can see my previous accounts along with whatever balance was there.

I cannot repeat that process on my desktop. Even though I have deleted the Mist folder and Ethereum folder from '%APPDATA'.

How can I delete all traces on Mist wallet on my desktop to repeat the success I had with my laptop (which never had Mist installed).

**Comment by luclu** [comment]
good to hear!
What does happen when you open `menu -> accounts -> backup -> accounts` in **Ethereum-Wallet** on the desktop-pc?

**Comment by efox29** [comment]
@luclu  On the desktop, when I go to 'menu -> accounts -> backup -> accounts', I see 4 folders and a file.

1. chaindata
2. dapp
3. keystore
4. nodes
5. nodekey (file)

Basically I see what I have seen in the past.

But..

The other day I created 2 new accounts the other day to see if I could get them to be seen. They are seen. Those 2 new accounts show up in Mist. They do **NOT** show up in the keystore though. When I look into my keystore in 'menu -> accounts -> backup -> accounts', I see 5 accounts (my missing 5 accounts), and the date they were modified was March and April. 

So where exactly are private keys being held ?

**Comment by luclu** [comment]
I'm not quite sure if I can follow you on this. There is only one `keystore` under the active users `%APPDATA%\Ethereum`-folder. Try to delete:

 - `%APPDATA%\Ethereum`
 - `%APPDATA%\Mist`

Then start it again. Did you mix up users accounts by any chance?

**Comment by efox29** [comment]
@luclu I have deleted both folders as you have said. 

I just started Mist 0.7.4 again. The wallet is synced. I did not have to resync. When I try manually entering in the Ethereum folder, this is what I get..

[https://i.imgur.com/NfduwB1.png](url)

Notice that it cannot find the Ethereum folder (which includes chaindata and keystore) and yet my wallet has 3 addresses, and is fully synced to the network.

**Comment by luclu** [comment]
@efox29 please excuse my late reply.
It seems that your environment variable `$HOME` was changed. This might happen if you install some application as [this thread](http://www.hpmuseum.org/forum/thread-5998-post-53919.html) suggests:
> Unfortunately $HOME was set to C:\Users\<me>\AppData\Roaming\SPB_Data by OrCAD\PSpice.

Do you still encounter problems using the latest version `0.8.2`?
