### ISSUE TITLE
Mist frozen/Won't Sync

### ISSUE THREAD

**Issue by SteveLongoria** [ethereum/mist#763]
I can't access my mist wallet since it won't sync!

Node type: geth/eth
OS: linux
Network type: main
Mist version: 0.7.4, 0.7.3, 0.7.2

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
![screenshot from 2016-06-01 12 57 57](https://cloud.githubusercontent.com/assets/17738181/15723690/81139f50-27f8-11e6-9b9d-88f102a1f4dd.png)

- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log
[node.log.zip](https://github.com/ethereum/mist/files/294267/node.log.zip)

**Comment by luclu** [comment]
@SteveLongoria could you please post the log after running version 0.7.4?
Also try to run `geth --nat=none` and upload its output.

**Comment by ziomar1** [comment]
same issue and 
geth gives me "command not found"

**Comment by JRogiest** [comment]
@ziomar1 Install geth first. https://github.com/ethereum/go-ethereum/wiki/Building-Ethereum

**Comment by ziomar1** [comment]
I tried already but got error at the end of procedure 
make: *** [geth] Error 2

and it does't work
don't know what to do

**Comment by luclu** [comment]
@ziomar1 you don't need to compile anything yourself! Please use the binaries we released. If you just want to use the [**Ethereum-Wallet**](https://github.com/ethereum/mist/releases) take this link and use the version corresponding to your OS - beware that win32 comes without **geth** bundled - all other binaries are bundled with **geth** `1.4.5`.
If you instead want to use the client standalone I recommend you [**geth**](https://github.com/ethereum/go-ethereum/releases) - but most likely this is nothing for you expept you are developing. In this case please make yourself familiar with the ecosystem and ethereum's components first.

**Comment by ziomar1** [comment]
did everything already

I'm with ubuntu and the last version of your mist wallet and I can tell you that sync with the blocks is an INFINITE procedure, if you kindly can pont me how to speed up this procedure it will be fantastic, else I have to giveup because I can't keep my computer on for 3 months.

Yhank you

**Comment by AlessandroCrepaldi** [comment]
On ubuntu I synced my node using geth --fast and it completed in a reasonable time. 

After 3 days I opened mist and it took just the time to catch up with the missed blocks.

Note that if you want to use the --fast option you need to have a "brand new" data file. I think mist will look for the default one (correct me pls) so I would just take a backup copy of what you got so far on an SD/Usb and get rid of what you have in the default datafile folder.

**Comment by ziomar1** [comment]
the main thing is that if I try to type geth --fast to my terminal, it simply says "command not found" even if as I said I install it already

**Comment by AlessandroCrepaldi** [comment]
zio, have you tried to follow the instructions here : 

https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu

for the installation on ubuntu ? - what happen if you type `whereis geth` or `where geth` ?

**Comment by ziomar1** [comment]
Yes I followed those instructions,

if I type whereis geth I get "geth:" and nothing more, quite weird

**Comment by AlessandroCrepaldi** [comment]
what about `sudo geth` ? same issue ? ... it's really quite weird ... can you locate geth from the mist installation ?

**Comment by ziomar1** [comment]
I redid all the installation procedure from the beginnig and not it geth works!

I'm running geth --fast
I would like to ask you how long is a "reasonable time" 

Thx

**Comment by luclu** [comment]
Good to hear. About 6-40 hours depending on your hardware configuration.
Thanks @AlessandroCrepaldi 👍

**Comment by SteveLongoria** [comment]
[logfile.zip](https://github.com/ethereum/mist/files/298682/logfile.zip)
