### ISSUE TITLE
Is there a way to get ETH out of mist wallet contract w/o syncing

### ISSUE THREAD

**Issue by rafajafar** [ethereum/mist#764]
Syncing takes way too damn long, even with --fast after removedb it's shit the bed on me three times after a small internet blip on my end. I'm fed up. How do I get my ETH out of the contract wallet given the json wallet I have?

**Comment by JRogiest** [comment]
Use the following site https://www.myetherwallet.com/#send-transaction
No need to sync, select JSON format, input PW and send it to where you need it to go /new address...

**Comment by rafajafar** [comment]
I tried that yesterday but the money in the JSON wallet was less than the contract wallet. There isn't a JSON wallet for the contract created by Mist that is associated with the main wallet.

**Comment by rafajafar** [comment]
This is my JSON wallet: https://etherscan.io/address/0xcbfcf709040fac1a445d23b34cfc8be620a92f78

This was created as a "contract" wallet or something from Mist: https://etherscan.io/address/0xd042a7920b6fdf93e8842794d3c932d6cd4d36ad

I don't have a JSON file for that contract. How do I get that ether out?

**Comment by luclu** [comment]
@rafajafar your balance might be inconsistent if you are not fully synced.
Also wallet contracts don't depend on any seperate json-file as only the private key of the owner account can access its funds. There might be no easy way out without fully syncing. Otherwise you will need some command-line magic.

**Comment by rafajafar** [comment]
Well I mean, I tried to rebuild the entire database with --fast, but around block 720,000 it started taking minutes to process each batch of blocks. Up to that point it was fine. I resync'd my clock, tried all the tips in the issues here for Window 10 (including page file adjustments), and I even sacrificed a chicken in a hoodoo ritual.

The same thing happened when I tried downloading the block chain (from May 30th, 1.6GB file) and importing it by file last night. This would not be an issue if it doesn't also make my disk usage go to 100% and kill my ability to use this particular computer.

**Comment by rafajafar** [comment]
Windows 10 Pro
Core i5
8gigs RAM passed  shallow RAM test this morning.
Spinning disc hard drive... NOT solid state. 
No malware detected last night.
Mostly just chrome and google services competing for space.

**Comment by luclu** [comment]
The first 500.000 blocks will sync much faster then the later ones due to the increasing number of transactions. This can get very slow when using a mechanical HDD as this issues summurizes: https://github.com/ethereum/mist/issues/518

This will be improved in the future. Also look out for Light-client-functionality though this won't be available in the short term.

👎 for the poor chicken... seriously unappropiate, man.

**Comment by rafajafar** [comment]
Chicken was mostly for fun... did it still in the off-chance it worked. He wound up being very delicious.

Alright wellll, this is a big pain. Is there a service, maybe via Azure, that you know of where I can log into a full chaindata?

**Comment by luclu** [comment]
I personaly have no experience with Azure but it could be worth a shoot. Though be dedious...

**Comment by rafajafar** [comment]
Yeah I mean if I can just get the ETH from the contract wallet to the main wallet, I'd be set. I'll have to look into that RPC thing. Thanks.

**Comment by JDSBali21** [comment]
Hi Rafajafar.... 

Did you ever manage getting your Ether out of the wallet contract? It looks it.

I am currently having this same exact problem. I can not synch the block chain, and I can not move the Ether from the contract wallet to the main account. 

I would like to know what ended up working for you.

Thanks

**Comment by rafajafar** [comment]
Oh man I'm sorry this was so long ago. Yes I did but I can't remember. Wish
I could help.
