### ISSUE TITLE
Cannot hide Mist window in Mac OS X using cmd-H

### ISSUE THREAD

**Issue by mico** [ethereum/mist#765]
Node type: geth
OS: osx 
Network type: main
Mist version: 0.7.3

Cannot hide Mist windows by choosing "Hide Mist" in menu or using cmd-H hotkey.
It's only application on Mac OS X which didn't support this feature.

**Comment by luclu** [comment]
@mico please update to the latest version 0.7.4 as this feature was introduces only recently.
