### ISSUE TITLE
mist wallet sync

### ISSUE THREAD

**Issue by dragonu19** [ethereum/mist#766]
Hi guys,
I am new to this, pls help.
I did not sync my mist wallet and I transfered some eth from kraken to my wallet. It's showing me 0 eth. I try to sync but is very slow.. after 20 hours I still have 900 000 blocks left. Have I lost the eth that I trasfered or I must wait full sync (a few days I think) ?
Thank you!

**Comment by JRogiest** [comment]
@dragonu19 Lots of info regarding your problem online. Don't panic - just check further and search. It's a great way to learn.... But it's not lost as long as you used the correct address for the transfer. Your mist wallet just needs to synchronise. Patience my friend and as soon as it is done your Ether will appear. Alternatively, You can also check your address on a blockexplorer. Feel free to close the issue if you are satisfied.

**Comment by luclu** [comment]
I delete the duplicate posts. Please don't hijack non-related issues in the future.

**Comment by luclu** [comment]
@dragonu19 how did it end up being synced?
I will close this for now, but feel free to come back if you still experience any problem!
