### ISSUE TITLE
Error starting wallets ETH Window 8. Help !!!

### ISSUE THREAD

**Issue by killerplay** [ethereum/mist#77]
I found a wallet ETH for windows 8 , set up his wallet and the contract , but it worked after I removed a few games , and I do not need a wallet program has stopped working , gives an error Are you already running a node? Make sure your IPC path is set to the default: $ geth --ipcpath \\. \ Pipe \ geth.ipc. Individual files geth not work immediately close , what do I do ?      
      Я установил бумажник ETH для окна 8,создал свой бумажник и контракт, все работало но после того как я удалил несколько игр и не нужных мне программ бумажник перестал работать. выдаёт ошибку  Are you already running a node? Make sure your IPC path is set to the default: $ geth --ipcpath \\.\pipe\geth.ipc . отдельно файл geth не работает сразу закрывается, что мне делать ? 
    Если можете то дайте ответ на Русском языке. Спасибо.
    If you can give the answer to the Russian language. Thank you.

**Comment by frozeman** [comment]
Please restart and try again. Or did you have win32 bit? For this one we don't have a node, or you need to compile to yourself.

**Comment by Bubleek** [comment]
Добрый день. В папке где у вас gath создайте текстовый файл внутрь напишите следующие строки:
`Путь к файлу\gath\geth.exe --verbosity 5 
pause`
Затем переименуйте файл и измените ему расширение на .bat, запускайте и смотрите что пишет в консоли. Результат сюда скиньте!

**Comment by frozeman** [comment]
Google translate:
```
Good afternoon. In the folder where you have gath create a text file inside, write the following lines:
`File path \ gath \ geth.exe --verbosity 5

pause`
Words path to replace the real path of the conductor. Then, rename the file and change it to an extension .bat, run and watch that writes to the console. The result here throw off!
```

Thanks for the hint, but next time in english? :)

**Comment by Bubleek** [comment]
@frozeman Yes, he need help on russian.

**Comment by juneadler** [comment]
hi there, I downloaded the latest Ethereum-Wallet-win64-0-5-1 
then unzipped, and ran the Ethereum-Wallet.exe file, after clicking, nothing happens. 

not sure what's happening, so I go into CMD mode and type Ethereum-Wallet.exe
then, screen says 

CONNECT to IPC PATH: \\.\pipe\geth.ipc

and stays there for at least 30 minutes with no sign of progress. 
what is supposed to happen and am I doing something incorrect?

thanks

**Comment by frozeman** [comment]
@bas-vk any idea about @juneadler comment?

**Comment by juneadler** [comment]
anyone?

**Comment by frozeman** [comment]
It might be a firewall, router issue youre having. Try starting the node yourself. You can find it in the `resources/node/geth` folder:
`geth.exe --nat=none`

**Comment by juneadler** [comment]
would future releases provide error log so we can better understand the issue?

**Comment by frozeman** [comment]
In your case there is no error, besides that it doesn't find peers, which is probably your router or firewall.
There is not much the node or mist can do/show.

For when the node doesn't start, we show logs in the latest 0.5.1 release

**Comment by jedibojan** [comment]
Hi guys.
Same problem here as @juneadler .
When I run `geth.exe --nat=none`, the node does connect to peers and starts syncing, but the wallet is unresponsive. 
The only thing displayed when I run it from cmd prompt is: 
CONNECT to IPC PATH: \.\pipe\geth.ipc
I'm using Win8.1(64bit)

Thanks in advance.

**Comment by luclu** [comment]
Please make sure to update to the latest version.
I will close this and link to https://github.com/ethereum/mist/issues/292 as these issues are duplicates.
