### ISSUE TITLE
Block Sync starts evertime from the beginning

### ISSUE THREAD

**Issue by Mang00** [ethereum/mist#771]
Node type: geth
OS: windows
Network type: main
Mist version: 0.7.4

In the last week i downloaded the Node-Block several times and everytime its says its finished. Then i click on lunch app and then my wallet starts the sync from the beginning (Block 1 of 1mio). I synced it with cmd geth--fast without fast , with the normal wallet sync and always the same shit. I have to download the blocks new. I need for these Blocks nearly 24h to sync with my shitty connection and now i'm done. 

I cant understand why i always have to start the sync from the beginning. 
![error](https://cloud.githubusercontent.com/assets/10058819/15789708/f63582c2-29cd-11e6-9246-a9bfc5823f4a.PNG)

[node.zip](https://github.com/ethereum/mist/files/298221/node.zip)

![finished](https://cloud.githubusercontent.com/assets/10058819/15789657/ba93cd3c-29cd-11e6-8663-4fa882bb295e.PNG)

**Comment by Mang00** [comment]
In the screenshot the path of the chain is not correct but that is just because i copied the folder before everything is deleted again

**Comment by luclu** [comment]
@Mang00 from the logs it doesn't look like it is syncing from the beginning rather it is continuing at the last block - number 151,496 since the last launch of geth.
But the progressbar will always start from the beginning. Just hang in there.
