### ISSUE TITLE
Mist keeps freezing during sync

### ISSUE THREAD

**Issue by justinireland** [ethereum/mist#773]
OS: windows 7 x64
Network type: main
Mist version: 0.7.4

Every time I launch mist it starts downloading the blocks but after no more than 10 minutes it freezes on a block. If I close and restart it will pick up syncing where it left off but after ~10m it freezes again.

To clarify, the program itself still shows as responding in the process manager so it isnt frozen at the system level but it does not appear to be doing anything.

**Comment by luclu** [comment]
@justinireland are you by any chance watching the "The DAO"-contract?
Also does this happen if you leave the splash-screen open or only on the main GUI?

**Comment by justinireland** [comment]
I haven't even gotten as far as to view anything as this happens during the
initial loading of the application.

**Comment by JRogiest** [comment]
Until they workout the heavy disk I/O  a HDD would likely result in a slow down/stand still depending on the hardware used. Current work around is to install the blockchain on a SSD.

Other work around is to download blockchain using the terminal command line geth --fast

**Comment by justinireland** [comment]
Same thing happens when I run geth --fast. After a few minutes it freezes.

**Comment by aross** [comment]
I have a SSD and this happens to me as well (I'm on a Mac).  If I close and re-open the app, the sync picks up where it left off, but then freezes and some point again.  I generally have to close/re-open the app 10-20 times before the sync finishes and I can use it.

**Comment by swt83** [comment]
Same issue for me on OSX.  Freezes partway through sync.  Rolling back to 0.7.3 seems to solve the issue.

**Comment by luclu** [comment]
We will release `0.7.5` very soon. This will have a refactor of the event-logging and IPC-connection to geth included!

In the meantime it would be great if you could check the new bundle from today (version `0.7.4` + geth `1.4.6`) which should fix a whole bunch of sync-issues on the network-layer. Here is the [**link**](https://www.reddit.com/r/ethereum/comments/4mtnz3/geth_146_edge_making_sync_great_again/).

**Comment by Nogreedy** [comment]
@luclu 
@alexvandesande 
Hello,
I run Mist 0.7.4 on my Windows 64 bits.
I have some freezes (yes, I watch DAO...) on Mist and some sync-issues....
Can you confirm please, if it's safe to replace current geth version (programmes\Ethereum-Wallet\resources\node\geth) by the new one (Geth 1.4.6 "EDGE" ) ?

**Comment by luclu** [comment]
@Nogreedy yes you can do that - it is safe. But please keep track of this when you raise issues or comment.

**Comment by MrDroth** [comment]
Keep getting stuck at block 1,436,598 on the newest beta. It starts syncing by saying 1,43... of 1,70...When I get to 1,436,598 it says 1,436,598 of 1,498,361.

What the heck is going on?
![capture](https://cloud.githubusercontent.com/assets/19916581/16034415/aa6241cc-31df-11e6-8016-ee68ab2e6912.PNG)

**Comment by luclu** [comment]
@MrDroth please try [this](https://github.com/ethereum/mist/issues/773#issuecomment-224047138) ☝️ and report back.

**Comment by luclu** [comment]
Could you kindly update to `0.8.1` and give me a heads up?

**Comment by luclu** [comment]
Closed as of inactivity.

**Comment by donrickman** [comment]
this still happens and there hundreds of post all over for this issue. Any work around?
