### ISSUE TITLE
password no longer working, other passwords work fine

### ISSUE THREAD

**Issue by shawn-j** [ethereum/mist#774]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

I'm a noob so i hope i did this right lol

My etherbase password worked fine for import, and for the first few transactions.  Now it doesn't work at all, in any version of mist or geth, 32 & 64 bit.  Other passwords all work fine.  Is this a bug?  What info do i need to paste here to help?  Thanks

**Comment by luclu** [comment]
With *import* do you mean some presale-wallet at the on-boarding-screen?

**Comment by shawn-j** [comment]
I imported my presale wallet using the same password.  That worked fine, and the first few transactions worked fine too.  Now it just says "wrong password".  And i've verified that  i'm still using the correcy password.

**Comment by luclu** [comment]
During the on-boarding process you were asked to enter and confirm a password just one step **before** you imported your presale-wallet. That password corresponds to your *etherbase*-account. You might have used the same or confused them. 

Try to use those other passwords for it or to recap what you could have used.

**Comment by shawn-j** [comment]
I've already tried all the other passwords many times, tried every combination i can think of

My etherbase pw worked for import, and that same password worked for the first few transactions.  Now it doesn't work, and no other pw i've used works either

**Comment by luclu** [comment]
Ok, so if you don't have any ether in that account I would just remove it from the keystore-folder.

**Comment by shawn-j** [comment]
A lot of ether is there, and all my dao is tied to that address

**Comment by luclu** [comment]
Make sure to try out [these](https://github.com/ethereum/mist/issues/669) recommendations.

**Comment by shawn-j** [comment]
Yes i already tried all that, and a suggestion from stack exchange

**Comment by luclu** [comment]
Also please make sure to update to 0.8.1 as the error messages were broken in earlier version and always fell back to the - often misleading - "wrong password" alert - regardless of the real error (#664).
