### ISSUE TITLE
Mist dosn't open

### ISSUE THREAD

**Issue by JHenriqueVissotto** [ethereum/mist#775]
Node type: Ethereum Wallet
OS: windows 7 64
Network type: main
Mist version: 0.7.4

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- print: http://s33.postimg.org/5ln3y4o33/prob2.png
- log: https://drive.google.com/open?id=0B20QIEw-WlYkaVlTRE85b2ZHeGs

**Comment by luclu** [comment]
@JHenriqueVissotto make sure to use the binary corresponding to your OS - the win32 one is not bundled with a node - as we don't officially support win32 yet - only the 64bit.

**Comment by JHenriqueVissotto** [comment]
Of course!!!

The problem isn't in my computer not...

[image: Imagem inline 1]






2016-06-04 7:52 GMT-03:00 Luca Zeug <notifications@github.com>:

**Comment by luclu** [comment]
Make sure you are timesynced with a ntp-server.

**Comment by luclu** [comment]
Also did you extract the zip before evoking **Ethereum-Wallet.exe**?

**Comment by JHenriqueVissotto** [comment]
So, when will you fix this problem??

2016-06-04 20:53 GMT-03:00 J Henrique Vissotto <jhenrique.vissotto@gmail.com

**Comment by luclu** [comment]
Which problem?

**Comment by JHenriqueVissotto** [comment]
For me do you ask what's the problem!?!? I who ask for you what the
problem!!!

I simply installed the mist, version 32 and 64, version 0.7.4, 0.7.3,
0.7.2, ...




2016-06-08 12:22 GMT-03:00 Luca Zeug <notifications@github.com>:

**Comment by JHenriqueVissotto** [comment]
And don't work! Don't opening. Don't run...

I don't know why!

2016-06-13 5:25 GMT-03:00 J Henrique Vissotto <jhenrique.vissotto@gmail.com>
:

**Comment by luclu** [comment]
@JHenriqueVissotto for a start please try to cooperate with me answering these questions so we can isolate your issue:
> Please make sure you are timesynced with a ntp-server.

and
> Also did you extract the zip before evoking **Ethereum-Wallet.exe**?

**Comment by JHenriqueVissotto** [comment]
Yes! I can and I will cooperate! And yes again for 2 twos questions!

Also, the same problem is ocurring in several of the instances of the
Amazon’s VPS, in other words, this problem isn’t in my computer…
The Mist already worked in my PC in 1 or 2 mounths ago, but now, no more…


2016-06-13 8:32 GMT-03:00 Luca Zeug <notifications@github.com>:

**Comment by luclu** [comment]
1. Where is your Mist app folder located at?
2. Does it contain the file `geth.exe` under `nodes\geth`? I assume you still get the error from your initial post.
3. Do you have special characters in your username?
4. Do you changed the userfolders location from its defaults? (via GPO, etc)
5. What OS do you run on Amazon VPS?

**Comment by luclu** [comment]
Also make sure to test this with the latest release 0.7.5.
https://github.com/ethereum/mist/releases/tag/0.7.5

**Comment by luclu** [comment]
I will close this for now as we could not isolate/find the issue.
