### ISSUE TITLE
Fatal

### ISSUE THREAD

**Issue by zhuga** [ethereum/mist#777]
Node type: geth
Network: main
Platform: linux (Architecure x64)

...I0605 10:14:27.777503 cmd/utils/flags.go:687] You're one of the lucky few that will try out the JIT VM (random). If you get a consensus failure please be so kind to report this incident with the block hash that failed. You can switch to the regular VM by setting --jitvm=false

I0605 10:14:27.782693 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to /home/user/.ethereum/chaindata
Fatal: Could not open database: open /home/user/.ethereum/chaindata/MANIFEST-577745: input/output error

**Comment by luclu** [comment]
Hi @zhuga, could you kindly reopen this issue on [go-ethereum's issue tracker](https://github.com/ethereum/go-ethereum/issues)?
