### ISSUE TITLE
Latest mist freezes 90s after startup if "The DAO" is added to watched contracts.

### ISSUE THREAD

**Issue by LukaszOls** [ethereum/mist#778]
Node type: geth
OS: windows 8.1 64-bit
Network type: main
Mist version: v0.7.4

This seems to be affecting large number of users and is a known issue. Allegedly downgrading Mist to version 0.6.2 helps is go away. However, I didn't see this problem here in the list of issues therefore I add it as such issue makes the current version of mist unusable to everyone who has the DAO contract added.

In addition to the discussion on daohub ( https://forum.daohub.org/t/dao-contract-crashing-mist/1119/21 ) I would llike to provide the following additional information.

During first 89 or so seconds Mist works fine. All parts of the GUI seem to be accessible. Process explorer shows Mist as launching one main and 3 child processes. All of them consume less than 1% of the CPU and under 100MB or RAM altogether. 

After the issue happens one of the processes jumps up to 25% CPU (what on a quad core machine might suggest it is stuck doing endless work in one thread). Memory used slowly grows and after another minute goes up from original 50MB to over 350MB and 500MB later. The main process also  ups its memory usage to 250MB. I'm attaching a screenshot from task manager.

I've attached the visual studio debugger to Mist in this state, but unfortunately I have no idea how to obtain symbols (or whether it can even be debugged in such way)for node.dll. So I can't provide any more information about the issue other than it is reproducible and node.log is empty.
![image](https://cloud.githubusercontent.com/assets/19762237/15806452/8431b6d6-2b3b-11e6-90ef-10d13bd4ec8e.png)

**Comment by LukaszOls** [comment]
I'm also adding the console from Mist. It remained responsive for few seconds while the issue was ongoing and it seemed to log a a lot of warnings shown below (I have no idea if this is helpful or not - If someone asks me I can perform some other tests).
![image](https://cloud.githubusercontent.com/assets/19762237/15806539/36bb2dd6-2b3d-11e6-9a23-945d53840207.png)

**Comment by LukaszOls** [comment]
The problem appears only with the original binary bundle or if chrome is used as a browser when the development version of the app is started via meteor and command line(http://localhost:3050 when running a development code).

However, when the same app is accessed using Firefox, it slows down and becomes unresponsive for few seconds, then spews a bunch of messages saying a transaction to send some ether didn't work, and after it runs fine... The address to which those ethers where to be sent starts 0x2e... unfortunately it happened so quickly I didn't manage  to get a screenshot and now that I used Firefox with the app the problem doesn't re-appear.

Unfortunately after I used Firefox to connect to the app the problem went away and I can't replicate it in Firefox or in the development version started by running meteor and electron in separate command line windows. Original binary app

**Comment by LukaszOls** [comment]
If anyone is interested (it doesn't seem anyone is from the amount of developer engagement in this issue that is potentially affecting all users using 7.4 version that added The DAO to watched contracts). The messages that pop up when Chrome would've crashed look like this on Firefox:
![image](https://cloud.githubusercontent.com/assets/19762237/16069636/e07f381c-32c7-11e6-88cc-e00f42c7ea7c.png)
Maybe it will give someone an idea how this can be fixed.

**Comment by luclu** [comment]
@LukaszOls could you please check if this behaviour still occurs in version `0.7.5`?
The IPC-communication got a complete overhaul and the event-logging can now be enabled/disabled on per-contract base.

**Comment by chevdor** [comment]
I still see the issue in 0.7.5. I am using Mist 0.7.5 on OS X.

I can add a watch on the contract (I tested using the full.json interface).
At first it works all fine, I can see all the method, call them, all normal. After a few seconds (blocks?), the list box with the contract methods and all the properties disappear and no longer show up.

Since 0.7.4, it is possible to click the trashcan next to the watched DAO contract and stop watching it. After a restart of Mist, all goes then back to normal.
