### ISSUE TITLE
Buying ETH via Bitcoin failed

### ISSUE THREAD

**Issue by hjsteen** [ethereum/mist#779]
I have tried to buy ETH via Bitcoin transaction. The Bitcoin transaction was successful but I never received the ETH....I have attached the related Bitcoin transaction, which includes the receiving address that was given by the Wallet for the transaction

![proof transaction for eth](https://cloud.githubusercontent.com/assets/19764020/15807241/e6930aba-2b58-11e6-88b9-953394aac34f.JPG)

Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment]
Please try to get in contact with shapeshift as they are able to trace your transaction. They can provide meaningful insides into this. Please give me a small pingback on the outcome!
Also have a look at this one: https://ethereum.stackexchange.com/questions/1717/how-to-recover-btc-that-wasnt-converted-into-eth-by-shifty-via-mist

I created some pool with tips on this: https://github.com/ethereum/mist/issues/687
I will close this for now, but feel free to keep me updated on the progress.
