### ISSUE TITLE
private-net mode not working under linux?

### ISSUE THREAD

**Issue by chiarelli** [ethereum/mist#787]
Node type: geth
OS: linux
Network type: NULL
Mist version: 0.7.4

O Modo PRIVATE-NET não está funcional em distros linux?
Apenas na compilação destinada para Windows consegui acessar essa funcionalidade, ou seja, inicio o "geth" com as configurações personalizadas e ao iniciar o mist ele roda no modo PRIVATE-NET. Ao fazer o mesmo procedimento na distro linux GNU-Ubuntu ocorre um erro.

**Comment by luclu** [comment]
from google-translator:
> Die PRIVATE-NET-Modus ist in Linux-Distributionen nicht funktionsfähig ?
Nur bei der Erstellung für Windows könnte diese Funktionalität zugreifen, dh den Anfang "Geth" mit benutzerdefinierten Einstellungen und starten Sie den Nebel läuft es in PRIVATE-NET-Modus. Dadurch tritt das gleiche Verfahren in Linux-Distribution Ubuntu GNU-ein Fehler auf.

**Comment by luclu** [comment]
To use private-nets you have to start **geth** with the appropiate flags `--networkid`, etc. externally and connect **Mist/Ethereum-Wallet** to it.

**Comment by netchiarelli** [comment]
Hello luclu,

I used the same configuration as the geth in both distros:

`geth --identity "MyNodeName" --genesis ~ / CustomGensis.json --rpc --rpcport "8000" --rpccorsdomain "*" --datadir "/ home / raphael / ethereum-private_network" --ipcapi "admin db , eth, debug, miner, net, shh, txpool, personal, web3 "--rpcapi" db, eth, net, web3 "--autodag --networkid 1900 --nat" any "console`

However, only in the compilation for windows 7 PRIVATE-NET mode is functional, while in GNU-Ubuntu the **mist** returns an exception.

**Comment by luclu** [comment]
What kind of exception do you encounter?

**Comment by netchiarelli** [comment]
The following screenshot:

![exception-mist](https://cloud.githubusercontent.com/assets/8763928/15840429/4ae965b4-2c20-11e6-89ae-a3c7c90af3b4.png)

![exception-mist-2](https://cloud.githubusercontent.com/assets/8763928/15840431/4e4c8d4e-2c20-11e6-939b-48f30f470fb4.png)

**Comment by luclu** [comment]
The last line states that the port `30303` is already used. Make sure there is no other instance of geth running `pgrep geth` / `pkill geth`.

**Comment by netchiarelli** [comment]
There is no other instance of running geth, I had already seen it before, but the build for Windows 7 this problem does not occur.

**Comment by luclu** [comment]
Could you try to append geth with the `--ipcpath`-flag parsing the default location of the ipc-socket.

**Comment by netchiarelli** [comment]
luclu, I did what you asked adding `--ippath` but there was the same problem.

**Comment by luclu** [comment]
What happens when you only start Mist with default settings?

**Comment by netchiarelli** [comment]
**mist** starts normally.

**Comment by luclu** [comment]
Can you try to strip down your geth flags or build them up with networkid 2 (morden testnet) - to isolate the issue?

**Comment by netchiarelli** [comment]
Do you believe that this could be a bug in the Linux build?

For now I can only run **PRIVATE-NET** mode in windows ...

I hope the developer solve this problem in the next update for linux distros.

**Comment by luclu** [comment]
I don't really thing so, but it could be...

If you want to spare some time helping try to strip down your command-flags one by one - to isolate the issue.
> Can you try to strip down your geth flags or build them up with `--networkid 2` (morden testnet) - to isolate the issue?

**Comment by armed10** [comment]
I am currently experiencing the same issue. I think the wallet might not be able to find the geth.ipc file, possibly expecting it somewhere else. If it then starts its own geth instance, this will fail due to the port being in use.

**Comment by luclu** [comment]
@armed10 this might be related to https://github.com/ethereum/mist/issues/1165.

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
