### ISSUE TITLE
Small typo: "Sharing a Identity"

### ISSUE THREAD

**Issue by tcoulter** [ethereum/mist#79]
From here: https://github.com/ethereum/mist/blob/fc9d8d9f756f902a07b98f3e84e8f72e4c7b3b98/interface/client/templates/layout/browserBar_accounts.html#L4

Should be "sharing **an** identity".

**Comment by alexvandesande** [comment]
Thanks for all the issues Tim!

**Comment by alexvandesande** [comment]
Thanks, merged
