### ISSUE TITLE
Node Crashed

### ISSUE THREAD

**Issue by choncou** [ethereum/mist#790]
Node type: geth
Network: main
Platform: darwin

...I0607 22:31:14.513161     554 database.go:71] Alloted 433MB cache to /Users/choncou/Library/Ethereum/chaindata
I0607 22:31:14.580394     554 database.go:71] Alloted 78MB cache to /Users/choncou/Library/Ethereum/dapp
I0607 22:31:14.582801     554 backend.go:314] Protocol Versions: [63 62 61], Network Id: 1
I0607 22:31:14.583090     554 backend.go:362] Blockchain DB Version: 3
I0607 22:31:14.585425     554 blockchain.go:214] Last header: #1664569 [6d4a923c…] TD=25639082192734557573
I0607 22:31:14.585448     554 blockchain.go:215] Last block: #1663154 [3a2054e8…] TD=25573937557108814911
I0607 22:31:14.585455     554 blockchain.go:216] Fast block: #1663406 [fddc7c00…] TD=25585305309594562535
I0607 22:31:14.585713     554 handler.go:92] blockchain not empty, fast sync disabled
I0607 22:31:14.590340     554 cmd.go:114] Starting Geth/v1.3.5/darwin/go1.5.1
I0607 22:31:14.590450     554 server.go:311] Starting Serve

**Comment by luclu** [comment]
Make sure to update! Please reopen if you still encounter the issue.
