### ISSUE TITLE
Send bitcoin to expired Ethereum Mist Wallet. It is lost now. How can i return my bitcoin back to me. address

### ISSUE THREAD

**Issue by Alexsov** [ethereum/mist#791]
Hi. I send bitcoin to an expired Ethereum Wallet Mist address  which was expired (issued more than 10 min) from coinbase accaunt and bitcoin never came back and i dont see nothing in my Ethereum wallet. anyone had this problem?

**Comment by Alexsov** [comment]
Hi. I send bitcoin to an expired Ethereum Wallet Mist address  which was expired (issued more than 10 min) from coinbase accaunt and bitcoin never came back and i dont see nothing in my Ethereum wallet. anyone had this problem?

**Comment by luclu** [comment]
Do you mean shape-shift by any chance or does coinbase already support Ether?
Make sure to have a look at these resources: https://github.com/ethereum/mist/issues/687

**Comment by luclu** [comment]
I will close this for now as for inactivity. Feel free to reach out to me again if you are not in the know.
