### ISSUE TITLE
Improve spacing on block info

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/mist#795]
<img width="224" alt="alterar espacamentos" src="https://cloud.githubusercontent.com/assets/47108/15914203/440d0912-2db5-11e6-9da9-37b9cb853023.png">

OS: linux/windows/osx
Mist version: 0.7.4

**Comment by luclu** [comment]
Also try to cut off your internet connection to see the line wrap on blocktimes >1min.

**Comment by evertonfraga** [comment]
Fixed
