### ISSUE TITLE
Unable to build wallet for all platforms

### ISSUE THREAD

**Issue by hiddentao** [ethereum/mist#798]
I've determined this to be a problem within `electron-packager`. If you do `gulp wallet` without specifying a single platform it builds all platform folders, but they don't all contain all necessary source resources.

**Comment by luclu** [comment]
Do you have all dependencies like `wine` installed. If my setup misses `wine` they all scew up: https://github.com/ethereum/mist/issues/704

**Comment by luclu** [comment]
Ah, let's just kill this once for all..

**Comment by luclu** [comment]
Building `--platform all` on linux will result in broken OSX package. Running `--platform darwin` seperately will build successfully.
