### ISSUE TITLE
Node Keeps Persistently Crashing/Disconnecting

### ISSUE THREAD

**Issue by PatrickMockridge** [ethereum/mist#799]
Node type: geth
OS: OSX Yosemite 10.10
Network type: main
Mist version: 0.7.4

I've been trying to send Ether for most of the day but my Mist Wallet is refusing 

Error output from my Geth Node in the Terminal (geth 1.4.5):

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45cd371]

goroutine 1526 [running]:
panic(0x4a967e0, 0xc8200141b0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
github.com/ethereum/go-ethereum/eth/filters.(*Filter).bloomFilter(0xc82ab03c00, 0x0, 0x3bccf884bafd8c68)
	/private/tmp/ethereum-20160524-99100-1y3egi2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:208 +0xf1
github.com/ethereum/go-ethereum/eth/filters.(*Filter).getLogs(0xc82ab03c00, 0x163b68, 0x163f4f, 0xc82868f600, 0x18, 0x20)
	/private/tmp/ethereum-20160524-99100-1y3egi2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:137 +0x157
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc82ab03c00, 0x162010, 0x16e35f, 0x4, 0xc82d9d4000, 0x56a, 0x800)
	/private/tmp/ethereum-20160524-99100-1y3egi2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:109 +0x391
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc82ab03c00, 0x155cc0, 0x16e35f, 0x3, 0xc82c524000, 0x1c1c, 0x2000)
	/private/tmp/ethereum-20160524-99100-1y3egi2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x574
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc82ab03c00, 0xf4240, 0x16e35f, 0x2, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20160524-99100-1y3egi2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x574
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc82ab03c00, 0xf4240, 0x1986df, 0x1, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20160524-99100-1y3egi2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x574
github.com/ethereum/go-ethereum/eth/filters.(*Filter).mipFind(0xc82ab03c00, 0x61a80, 0x1986df, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20160524-99100-1y3egi2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:111 +0x574
github.com/ethereum/go-ethereum/eth/filters.(*Filter).Find(0xc82ab03c00, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20160524-99100-1y3egi2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/filter.go:91 +0x1bd
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).GetFilterLogs(0xc820120210, 0xc82a8650b0, 0x22, 0x0, 0x0, 0x0)
	/private/tmp/ethereum-20160524-99100-1y3egi2/build/_workspace/src/github.com/ethereum/go-ethereum/eth/filters/api.go:534 +0xf1
reflect.Value.call(0x49b0440, 0x4b974e8, 0x13, 0x4be6c28, 0x4, 0xc82a865110, 0x2, 0x2, 0x0, 0x0, ...)
	/usr/local/opt/go/libexec/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x49b0440, 0x4b974e8, 0x13, 0xc82a865110, 0x2, 0x2, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/reflect/value.go:303 +0xb1
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc82009b980, 0xbfed6d8, 0xc82beb0720, 0xbfed5c0, 0xc827494960, 0xc8209bb180, 0x0, 0x0, 0xc772395d75f3aa00)
	/private/tmp/ethereum-20160524-99100-1y3egi2/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:322 +0x1260
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc82009b980, 0xbfed6d8, 0xc82beb0720, 0xbfed5c0, 0xc827494960, 0xc8209bb180)
	/private/tmp/ethereum-20160524-99100-1y3egi2/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:344 +0x277
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
	/private/tmp/ethereum-20160524-99100-1y3egi2/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:215 +0xc85
➜  ~ 

What I see in the browser console:
<img width="550" alt="screen shot 2016-06-09 at 15 20 37" src="https://cloud.githubusercontent.com/assets/18012054/15932987/c45bb528-2e55-11e6-9cfe-8233ea0cbc37.png">

**Comment by murraci** [comment]
Same has just started happening for me after I started watching the DAO contract. 

Node type: geth
OS: OSX El Capitan 10.11.5
Network type: main
Mist version: 0.7.4

**Comment by luclu** [comment]
Please check if you still encounter this issue with version `0.7.5` as this contains a complete refactor of the IPC-communication.

**Comment by luclu** [comment]
Closed as of inactivity. Please check if you still encounter his issue with `0.8.0`.
