### ISSUE TITLE
Odd UI when there are zero accounts (perhaps extra button)

### ISSUE THREAD

**Issue by tcoulter** [ethereum/mist#80]
See screenshot:

<img width="938" alt="screen shot 2015-12-08 at 1 36 49 pm" src="https://cloud.githubusercontent.com/assets/92629/11669314/e9c892ee-9db0-11e5-97ab-642840ecb11a.png">

I have no accounts registered yet. In this case, "Remain Anonymous" and "Continue with 0 Account" appear to do the same thing, and the latter is confusing because of its English as well as its function (I assume that when I have an account it means "continue with account selected"). When there are no accounts to select, this choice should likely be hidden.

**Comment by alexvandesande** [comment]
We are going to change that UI substantially..
