### ISSUE TITLE
Ether never arrived withdrawing from Gatehub (out of gas)

### ISSUE THREAD

**Issue by rdonnelly236** [ethereum/mist#801]
Recently I transferred 354 ETH from my Gatehub account to my Ethereum wallet set up through github.com/ethereum/mist/releases. The ETH never arrived in my account. Gatehub says that everything went well on their end, and I should contact you. Here are the details:

**Comment by frozeman** [comment]
Transaction hash? They should give you one, or its somewhere in their interface.

Are you synced your node?

**Comment by rdonnelly236** [comment]
This is the response I received from Gatehub:


Gregor Gololicic (GateHub)
Jun 10, 18:05 EEST 

Hi Rick, Gregor here. I checked your transaction on the system and it was successfully withdrawn from our system on the time of the withdrawal. Reason why the balance is not shown on your receiving account is due to a contract error shown here: http://etherscan.io/tx/0x6b09265fab5291f43a9b3eac8d9851000babca2a37a3e71f72080188cde9f04d <http://etherscan.io/tx/0x6b09265fab5291f43a9b3eac8d9851000babca2a37a3e71f72080188cde9f04d> 
Can you explain to me what is this contract? Is it a mist wallet? I would like to help you retrieve any lost funds but I must emphasize this is not an error on our part.

**Comment by luclu** [comment]
Hi @rdonnelly236,
as you can see the red line following the link to etherscan.io
`Warning! An error occured during contract execution. Out Of Gas`
this transaction did never happen on the network on was rejected - thus the sender still has the amount of ether in question. 

Please reply kindly refering to this github-issue.
This problem is not new as some exchanges have been affected in the past specifing a transaction fee in their systems which is too low.

Please give me a small heads-up on the outcome!

**Comment by luclu** [comment]
I moved the issue title to its body and shorted the title.

**Comment by rdonnelly236** [comment]
Hello Luca,

Thanks to you, Gatehub was able to successfully transfer my ETH from their exchange to my mist wallet. Many thanks for all of your help. I am hoping you can help me with a couple of other things. 

1) When I try to transfer my ETH from my contract wallet to my main account, it asks for my password. When I put in the password that I think it is, it says that the password is incorrect. Is there a way to reset the password?

2) I would like to transfer some DAO tokens that I currently am holding in Poloniex to my mist wallet. Would you recommend me transferring into my contract wallet or the main account?

3) When I try to copy the address, it says that it is copied to my clipboard, but it does not paste it. What would you recommend?

I really appreciate whatever help you can give to me.

Many Thanks,

RIck Donnelly

**Comment by luclu** [comment]
Hallo Rick, that is good to hear!

regarding your questions.
1. Make sure you use the password of the owner account. You can see this in the contract's details withing Mist or a blockchain explorer.
2. Contract wallet have the advantage of a better security model when using its multisigniture feature. This feature is currently not available for subtoken thus there is no benefit for using them over normal accounts. This will be added soon: https://github.com/ethereum/dapp-bin/pull/62
3. This is a known bug https://github.com/ethereum/mist/issues/650, that will be fixed on the next release. Current workaround are linked in that issue.

I will close this for now, but feel free to hang around or join the gitter channel for further questions.

**Comment by rdonnelly236** [comment]
I tried to transfer 158 eth from my contract wallet to my main account and nothing happened for days. Then today I got this:


I have no idea where it went to. It is not in my main account and it is not in my exchange. Please help me find the missing eth. 

Many Thanks,

Rick Donnelly

**Comment by gGololicic** [comment]
GateHub here, regarding the issue as our conclusion: the Mist wallet contracts is requiring much higher fee than in our initial testing so we had to increase the max fee needed for transaction.

**Comment by mubashirqasim** [comment]
I am having the same issue, I transferred ETH from Gatehub wallet through to their gatehub fifth gateway to cryptopia account but the transaction has not gone through yet. Any clue what might have happened?

**Comment by oojacoboo** [comment]
Same issue, and sent another transaction from coinbase that went through in a few minutes.
