### ISSUE TITLE
lost bitcoin during conversion

### ISSUE THREAD

**Issue by tunage** [ethereum/mist#802]
I installed the wallet for first time, the shifty gui asked me to deposit btc in order to receive eth

Send 0.00072433   Bitcoin to 
14YEXbVMzsudExtL2E6aKMpC7SLxgedM8n

It will be converted into 0.02  Ether, and sent to
0xc3f462fa930440a9f28a7300c2ad19cd8a2e95af

I sent to much and the balance is  https://live.blockcypher.com/btc/address/14YEXbVMzsudExtL2E6aKMpC7SLxgedM8n/

How do I retrieve my balance?

There is nothing in the wallet GUI that will grant me access to the btc address.

**Comment by luclu** [comment]
@tunage the balance in your wallet will get updated as soon as you sync to the blockchain height at which that transaction was commited. You can also have a look at your Ether-balance using a blockchain-explorer like [etherscan.io](etherscan.io) using your address.

**Comment by tunage** [comment]
That wallet was synced hours ago.

This is the interface that stole my money

http://pix.toile-libre.org/upload/original/1465646088.png

**Comment by tunage** [comment]
once again, how do I access this ->  https://live.blockcypher.com/btc/address/14YEXbVMzsudExtL2E6aKMpC7SLxgedM8n/  balance?

The SHIFTY GUI automatically threw it there and now I cannot reach it.

There is no place within the GUI to import a btc balance from a specific address. Only perform a new transaction (feed it more btc, no phucking way).

**Comment by luclu** [comment]
Please follow the recommendations ☝️ 
> 3 . Use a blockexplorer (e.g. [Etherscan.io](https://etherscan.io)) to check the balance of your account.
4 . Please **get in contact with shapeshift** as they are able to **trace and recover any funds**.

**Comment by tunage** [comment]
A trouble ticket with shapeshift solved the issue.

I would highly recommend removing their code.  Especially till they get the bugs worked out.

**Comment by luclu** [comment]
Good to hear you could solve it. We will look into this.
