### ISSUE TITLE
BigNumber Error while trying to vote using Mist

### ISSUE THREAD

**Issue by chevdor** [ethereum/mist#803]
Node type: geth
OS: osx
Network type: main
Mist version: 0.7.4

I start Mist with --mode mist
I browse to the DAPP: https://vote.daohub.org/#<MyDAOContractAddress>
<MyDAOContractAddress> is the address of the contract holding my DAO tokens.
I provide <MyDAOContractAddress> without '0x'

<MyDAOContractAddress> was created from the account <MyDAOAccountAddress>

As a result, I see 0 proposal available. Checking out the dev console, I see the error:
bignumber.js:1177 Uncaught BigNumber Error: new BigNumber() not a base 16 number:
...

If I browse to https://vote.daohub.org I can see the proposals but still cannot vote: the voting buttons are greyed out.
I see in the console that the 'checking for vote' is using the account <MyDAOAccountAddress>.

**Comment by Kojee** [comment]
It may be an exception where the number is not seen as an hex and so it triggers the exception.
This may be solved with a conversion or a cast to hex.

**Comment by chevdor** [comment]
Yes except that the number was an hex. It is a valid contract address without 0x.

**Comment by Kojee** [comment]
Report the bug to bignumber.js maker

**Comment by chevdor** [comment]
I am sure it will find its way...

**Comment by luclu** [comment]
@chevdor Thank you for reporting.
Those errors are better being handled over at web3.js's [repo](https://github.com/ethereum/web3.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20BigNumber).

I will close this.
