### ISSUE TITLE
Copy address does not work

### ISSUE THREAD

**Issue by marcofranssen** [ethereum/mist#806]
Node type: geth/eth
OS: windows
Network type: main/test
Mist version: 0.7.4

When using the copy address button, the address is not copied onto the clipboard. Same applies for selecting the address and using ctrl+c. The UI however tells that the address is copied to the clipboard in both situations.

**Comment by hellwolf** [comment]
Confirmed, including Linux client.

**Comment by luclu** [comment]
Thanks for reporting, though I will close this as a duplicate of https://github.com/ethereum/mist/issues/650
