### ISSUE TITLE
Avast deleted a "virus" it found in the chain. Now the wallet wont open.

### ISSUE THREAD

**Issue by KikiKite** [ethereum/mist#807]
Hi,

My antivirus software (Avast) thought it found a virus in the Ethereum chain and deleted it... now the wallet wont open. What do I need to do to rebuild the chain so I can open the wallet?

I have attached the error messages, and node logs.

Thanks
K

Node type: eth
OS: osx
Network type: main/test
Mist version: 0.0.0
![screen shot 2016-06-13 at 8 50 26 am](https://cloud.githubusercontent.com/assets/19894760/15993940/6e96c1d6-3149-11e6-8fe0-5b2b296bdb85.png)
![screen shot 2016-06-13 at 8 52 41 am](https://cloud.githubusercontent.com/assets/19894760/15993941/70eec488-3149-11e6-8196-046014a781dc.png)
[Node Logs.zip](https://github.com/ethereum/mist/files/310993/Node.Logs.zip)

**Comment by luclu** [comment]
@KikiKite please have a look at these recommendations: https://github.com/ethereum/mist/issues/573
Unfortunately some AV solutions will do this. I will close for now.
