### ISSUE TITLE
Option to let Mist use a remote geth/eth instance on another machine

### ISSUE THREAD

**Issue by slothbag** [ethereum/mist#809]
I currently run multiple geth instances on the LAN, they are always fully sync'd.  It would be great if Mist could connect to the RPC on those nodes instead of having to also sync on the local workstation.

**Comment by luclu** [comment]
Unfortunately this is currently not possible.
See https://ethereum.stackexchange.com/questions/2403/can-mist-be-attached-to-a-geth-node-on-a-different-computer-over-http-rpc

**Comment by luclu** [comment]
This will be possible as of this PR https://github.com/ethereum/mist/pull/871.
Please be patient until we release version `0.8.1` which is billed for the 19th of July.
