### ISSUE TITLE
getCoinbase() exposes the etherbase account, when it should be hidden

### ISSUE THREAD

**Issue by tcoulter** [ethereum/mist#81]
If an dapp calls `web3.eth.getCoinbase()`, the user's etherbase account will be exposed to the dapp, even though Mist makes efforts to hide all available accounts unless they are explicitly allowed.

To reproduce:

1) Write a simple dapp that calls `web3.eth.getCoinbase()`. You'll see that the etherbase address is exposed to the dapp, when it shouldn't be.

**Comment by alexvandesande** [comment]
This is a good point. getCoinbase should not be the way to get access to it.

**Comment by frozeman** [comment]
We will leave that for later, when we work on mist more..

**Comment by evertonfraga** [comment]
Fixed in 0.8.8
