### ISSUE TITLE
Ether Lost! etherchain shows duped transaction?

### ISSUE THREAD

**Issue by Nawkinger** [ethereum/mist#810]
Hello,

after buying more Ether today, to my suprise 8.4 Ether are lost.

Etherchain shows that a transaction from 15 days ago got duplicated. It is not shown in the wallet though.
![etherlost1](https://cloud.githubusercontent.com/assets/19915462/16019599/07dd8a18-31aa-11e6-9472-a838278dfe21.jpg)

https://etherchain.org/account/0x5a65752D0a317A5F4fC33c0F27d2c62369569F13#txsent

How did this happen? I didn't confirm with any passwort.
Is there anyway to get it back?

**Comment by luclu** [comment]
What version are you currently running?
Also make sure to be synced with the network.

**Comment by luclu** [comment]
@Nawkinger [etherscan.io](http://etherscan.io/address/0x5a65752D0a317A5F4fC33c0F27d2c62369569F13) as well as [etherchain.org](https://etherchain.org/account/0x5a65752D0a317A5F4fC33c0F27d2c62369569F13) show two transaction to the same address `0x4586Af2Da7e95e821DF24e9DAdD7D05BBAe0b7Ad` with the amount of 8.4 Ether. You might have executed it twice.
I will close this for now as it doesn't appear to be a problem with the Wallet. I will stay here to assist you if I can.
