### ISSUE TITLE
No Ethers got, Blockchain is in Sync. 

### ISSUE THREAD

**Issue by Abhijith68** [ethereum/mist#812]
Hello,

I have been mining for two days but haven't received a Single Ether. My blockchain is in Sync.

Thanks in Advance!

Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment]
@Abhijith68 what instructions did you follow to set up your mining rig?

If you have any issues with mining please head over to https://forum.ethereum.org/categories/mining this is by far a better place to pitch your question - as there is much expertise lurking around.

This is Mist's issue-tracker, the place to file bug-reports for the wallet frontend. I will close this for now.

**Comment by luclu** [comment]
Here are some more resources to get you running:
> Also, your best form of help on mining is outside of the Ethereum Foundation, though we do have some miners here now.
https://gitter.im/ethereum/minercommunitysupport
https://www.reddit.com/r/ethermining
http://ethereum.stackexchange.com/?tags=mining
