### ISSUE TITLE
Missing transactions on wallet contracts

### ISSUE THREAD

**Issue by ScrambleKid** [ethereum/mist#818]
Node type: geth
OS: osx
Network type: main
Mist version: 0.7.4

Like many [over here](https://github.com/ethereum/mist/issues/425), I am experiencing sync issues with Mist.

When Mist starts up I am presented with the 'Client v1.4.4-00000000 seems older than upstream release ...' error on the loading window:
![screen shot 2016-06-14 at 16 50 52](https://cloud.githubusercontent.com/assets/9610120/16050036/e802c958-3251-11e6-9a46-952186d3c642.png)

The Mist client loads after syncing but becomes very slow and unresponsive after a minute or two (could be memory leak).

I have two Accounts and two Wallet Contracts. One of my Wallet Contracts has DAO Tokens. I have a custom contract for The Dao and custom tokens too. I deleted Unicorns. 

There are also missing transactions (in Mist) for one of my wallet contracts.

Example of a "missing" transaction that is not showing in the list for my wallet contract or in balances on Mist: https://etherchain.org/tx/0xcb309cbef68c24c64ee68b206dfe96d50fc1f1cc7a43be6463e5cbc6034c71c3

I also can not copy addresses (console suggests command is being called recursively).

Console:
![screen shot 2016-06-14 at 17 05 13](https://cloud.githubusercontent.com/assets/9610120/16050094/34f22330-3252-11e6-9167-fc348cc6bb88.png)

[node.log.zip](https://github.com/ethereum/mist/files/314386/node.log.zip)

**Comment by luclu** [comment]
Thank you @ScrambleKid for reporting all of these issues.

A new version that should solve all of these bugs is ought to be released very soon (1-2 days if no serious problem gets spotted). I will give you some notice so you can check if it is alright.

**Comment by ScrambleKid** [comment]
@luclu Thanks! Looking forward to the new release 🚀

**Comment by splix** [comment]
+1

**Comment by luclu** [comment]
Please recheck those issues using version `0.7.5`.

**Comment by luclu** [comment]
Make sure to update to `0.8.1` for HF-chain.
