### ISSUE TITLE
Want use My Watch-Only Accounts

### ISSUE THREAD

**Issue by bocybox** [ethereum/mist#819]
Hello, Please I have one account witch I have two adress, 
How can I use my watch-only account?

![myetherwallet cx](https://cloud.githubusercontent.com/assets/19808453/16050281/93b3d86c-324a-11e6-8848-4eb6496beba7.jpg)

I want use my ether but I cant access to yhem, please show me what to do?

**Comment by luclu** [comment]
Hello @bocybox,
do you have `json`-files of these wallets? Try to load them in Mist. To do this go to menu -> accounts -> backup -> accounts and drop them in this folder.

**Comment by bocybox** [comment]
Hi thinks for answer me, but I dont have json-files.
I try to fing it in my account without success.
You tell me to go to menu -> accounts -> backup -> accounts and drop them in this folder.
But where can I find menu?

**Comment by luclu** [comment]
Could be that you mixed up software here. MyEthereumWallet is somewhat different than Ethereum-Wallet. ;)
I can only help you with the later one.

**Comment by bocybox** [comment]
ok thinks so much.

**Comment by luclu** [comment]
Ok, I will close this for now. Feel free to join our gitter chat if you have any questions!
