### ISSUE TITLE
Splash window is called "Electron" in the window list on Linux Mint

### ISSUE THREAD

**Issue by chriseth** [ethereum/mist#82]

**Comment by frozeman** [comment]
Is this in the build version?

**Comment by chriseth** [comment]
I think I used the release version: https://github.com/ethereum/mist/releases/tag/0.3.7

**Comment by gcmartinelli** [comment]
On Ubuntu the 0.3.8 version has a Popup that is also called Electron
http://imgur.com/rj3txUl

**Comment by frozeman** [comment]
Thanks will fix
