### ISSUE TITLE
Lost funds from Main Account

### ISSUE THREAD

**Issue by alper** [ethereum/mist#824]
OS: osx

The funds I wanted to save were listed in Ethereum Wallet in the "Main Account".
I backed up the accounts from Wallet using the backup feature.
I then deleted all the files related to AlethZero ~/.ethereum since those do not seem to be used by Ethereum Wallet anyway.
Restarting Ethereum Wallet first necessitated a multi hour sync and then it did not show me the funds I had anymore under Main Account.
Restoring the backup I made did not solve the problem and I have no idea where this wallet/account has gone.

It's a negligible amount of money so I don't really care about that but:
- Why doesn't the backup actually backup?
- Where did the money go?
- Any possibility of accessing it again?

**Comment by luclu** [comment]
Please check which backend you are using in the menu -> development -> Ethereum node. I highly recommend you to use geth for now. You might need to copy your accounts to `~/Library/Ethereum/keystore` afterwards. Also we just released `0.7.5.`. Make sure to update as it contains a whole lot of improvements under the hood!
I will close this for now, but will stay here to assist you.
