### ISSUE TITLE
wallet not opening

### ISSUE THREAD

**Issue by mikepancake** [ethereum/mist#826]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

---

I was having issues with the wallet crashing on macOS right when I opened it. I then installed homebrew, and built the geth using port 3555. I was able to open mist at this point and it began to sync. However once it was done syncing, I closed terminal and it sent me back to square one. The wallet would not open again, so I ran through the same process and it worked again. Is there any way to ensure my wallet will open once I close terminal? Or will I always need to run Terminal in order to sync my wallet?

---

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment]
So you are one of the brave ones trying out 10.12 already?
Please fill out the version block and correct the title to a oneliner.

**Comment by mikepancake** [comment]
Do you mind explaining that a little more? I don't have a lot of knowledge surrounding this, so any explanation you can give is very helpful. 

Thank you

**Comment by luclu** [comment]
OS X will be rebranded to macOS with the upcoming release of version 10.12.
Please fill out this block and truncate the issue title.
> Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

**Comment by mikepancake** [comment]
My apologies, I only reffered to it as macOS out of habit. I am running OSX still

**Comment by luclu** [comment]
>  Please fill out this block and truncate the issue title.

Please do this as repeatedly instructed and reopen the issue, if you need assistance.
