### ISSUE TITLE
Memory Leak in 0.7.5

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#837]
Node type: geth 1.4.7
OS: linux / windows / osx
Network type: main / test
Mist version: 0.7.5
#### Normal launch

Memory footprint of geth fastly climbs to over 1.5 GB when launched through Mist/Ethereum Wallet.
No watched contracts.

---
#### geth standalone

Running geth standalone will only use about 0.5 GB.

---
#### geth standalone + connecting the wallet
- no updates on the wallet screen
- geth terminal output freezes
- geth climbs over 3.5 GB continuing...
- closing the wallet will leave geth frozen

Trying to reproduce this it works as expected with 0.8 GB on geth **but** and 20 min frame with no output where geth completelly stalled (no processed blocks, no terminal output).

<img width="1920" alt="bildschirmfoto 2016-06-16 um 15 14 51 kopie" src="https://cloud.githubusercontent.com/assets/10135872/16118103/c181824e-33d5-11e6-8142-1c6f39e9acbd.png">

<img width="1920" alt="bildschirmfoto 2016-06-16 um 15 14 51 kopie2" src="https://cloud.githubusercontent.com/assets/10135872/16118263/868ebfc0-33d6-11e6-902a-d50fff97c1a6.png">

**Comment by fjl** [comment]
@luclu please do the following while geth uses that much memory:

```text
geth --exec 'debug.stacks()' attach > geth.stacks
```

and paste geth.stacks in a gist.

**Comment by A2be** [comment]
@fjl I was the one who described this problem in some detail in the https://gitter.im/ethereum/mist chat page late yesterday US time.  

I'm pretty new to github, open source, and linux, but have a lot of development and test experience.  

With your helpful info `geth --exec 'debug.stacks()' attach > geth.stacks,` I will try to do that later today and figure out how to attach files to the right place in github so you'll have what you want.

**Comment by fjl** [comment]
You can upload the file at https://gist.github.com

**Comment by luclu** [comment]
Here are some dumps. Though I could **not yet** reproduce that memory leak.
All on windows 7 x64.

1. geth standalone - acting normal. 
 https://gist.github.com/luclu/cc7f755353b92ff213994db97b793ba4
2. geth standalone - mist attached right after geth started - **geth frozen (no block transaction anymore)**
 https://gist.github.com/luclu/7beecf9846f57ae86795b67211a9d533
3. geth standalone - mist killed - **geth outputs block processing again, starting where it left before**
 https://gist.github.com/luclu/d9022c6478b06bba4fdad5100311ec54

The only difference to the memory leak from the top post is that 2. only takes 130 MB memory and at 3. it climbs to 300 or 700 MB (don't recall). Still this could be related - as it froze, too.

**Comment by larrysmith1000** [comment]
I can't reproduce this.  I see what Luclu sees.

I noticed that Geth is randomly testing Virtual Machine options: "--jitvm", and when I was randomly selected for --jitvm, I initially saw a fast climb in resources to 1GB while in Wallet, but then it dropped back to 600MB.  Only reason I was keeping an I is because I had the Memleak issues with 7.4.

**Comment by A2be** [comment]
@luclu I wrote you an email with some linux noob questions.  

I've not yet been able to run the `geth --exec 'debug.stacks()' attach > geth.stacks` command you suggested, but am fairly certain that the problem will reliably occur on my linux machine.

**Comment by luclu** [comment]
If **geth**'s memory footprint should grow over 2+ GB, please run this command as @fjl suggested:
```
geth --exec 'debug.stacks()' attach > geth-stacks.txt
```

@A2be you either need to navigate to the `Mist-0.7.5/resources/nodes/geth`-folder beforehand or install geth globally by adding the [PPA](https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu)

**Comment by jstefanop** [comment]
Here is the same issue on Mac OS

https://gist.github.com/jstefanop/54afc2204032010a8a8d02013f29e833

**Comment by luclu** [comment]
Linking related issue: https://github.com/ethereum/mist/issues/726 (Memory Leak (Interaction with Ethereum Wallet / Electron))

**Comment by A2be** [comment]
I still need to do the recreate on my linux machine.  But the DAO attack and following events has delayed me, as I suspect, all of us.

**Comment by jstefanop** [comment]
what is going on with this?? In light of recent DAO events it seems rather strange that the mist wallet all of a sudden stops working. This should be #1 priority and patched ASAP.

**Comment by bigcoinme** [comment]
Is there a workaround for this issue?
I'm trying to open the The DAO contract since 5 days but unable to open it because of this identical issue on my Linux box.

**Comment by jstefanop** [comment]
@bigcoinme nope and the devs seem like they don't give a crap, I'm pretty sure it only effects the DTH's or people watching the DAO contract. You can try deleting the DAO from the database files, but not sure how to do that. My current work around is to drain all the ether from my DAO Token address to a new address, and upload my address key myetherwallet to access the DAO Tokens. I usually don't trust private keys with online wallets, but since only my DAO Tokens are at risk doing it this way I really don't care.

**Comment by egzumer** [comment]
It looks like its because of DAO contracts being watched on wallets version 7 and newer. Wallet 6.2 with geth 1.4.10 works just fine.

**Comment by frozeman** [comment]
Yeah this might be because of log filters etc. Please try the latest version

**Comment by egzumer** [comment]
>  Please try the latest version

I have the latest release 0.8.1.
