### ISSUE TITLE
Transaction Failed part 2

### ISSUE THREAD

**Issue by Eisenkopf89** [ethereum/mist#84]
Hello,
i made two days ago this transaction:

http://etherscan.io/tx/0xc5e763d3b1bbc8daa0e48beaeb5abbc2e0fa303d4bdaa54890124e67f5937b8b

124.84128972 ETHER for an exchange but they never get the Ether. Is there a way to get them back? here is also the block information i get from the transaction:

http://etherscan.io/block/0xc15c81732768924b12c49f25b2b558052f8cc9eb68daeb15971df8d7722ab83c

It would be nice if there is any way to get my Ether back on my wallet.

Here is the transaction page.

https://shapeshift.io/status.html?depoAddr=0x4c377aed8d87831212351598647b8caeab8f390c&withAddr=1Bjos17or3VhKYV86ec4nM7T972kVWcJFx&coinInShort=ETH&coinOutShort=BTC&coinIn=Ether&coinOut=Bitcoin

Thanks for your help!

With best regards
Eisenkopf89

Edit:

This is from the shapeshift support:

The deposit address we provided to you (as you can see on the status link you have provided to us) is 0x4c377aed8d87831212351598647b8caeab8f390c. When you look that up on the ether explorer, it shows error in account as seen in this link, as I provided in my last message: https://etherchain.org/account/0x4c377aed8d87831212351598647b8caeab8f390c
This means this address never received funds. If it showed funds, we would know that our system had some issue and that we had received funds and we could assist further if that were the case. Due to the fact that no funds have posted to that address, there is nothing we can do on our side.
This is a broadcast issue with your wallet. We can see, since you provided those screen shots, that you sent money. But your wallet did not properly broadcast the funds to our deposit address, as seen in the link I posted above.
As the ether team member you have spoken with says that funds were sent, you can prove them them that this did not occur with the link I provided above, as it shows that there is error and does not show funds. They should be able to help assist you to find and retrieve these funds.
Please let me know if you have any questions about this.

Is there any way to know ans see what happend with my ether??? If you need screenshots i can give it to you!

**Comment by frozeman** [comment]
I'm not sure if multiple post make it more clear ;)

https://github.com/ethereum/meteor-dapp-wallet/issues/82#issuecomment-168646715
