### ISSUE TITLE
Ethereum wallet frozen on splash screen

### ISSUE THREAD

**Issue by TiratroN2** [ethereum/mist#842]
Hi.
I tried several version of Ethereum wallet mist , but everytime problem is the same: 
![empty screen](https://cloud.githubusercontent.com/assets/19977880/16121950/e19681fc-33ed-11e6-8c52-97dfee5328a1.jpg)
Tried first run geth.exe . Starting normaly. After that i run again Ethereum-wallet.exe and again- only white spash screen and nothing happens.
No errors indicated, no nothing. 

I work with Windows 7 x64

**Comment by luclu** [comment]
@TiratroN2 could you try out these recommendations, please? https://github.com/ethereum/mist/issues/599

**Comment by luclu** [comment]
@frozeman can you enlight me on the differnt `Ethereum Wallet.exe` processes on windows?
I can reproduce this ☝️ behaviour if I kill the right one.

**Comment by TiratroN2** [comment]
With --ignore-gpu-blacklist  and without him - everything is the same.

←[32m[2016-06-16 23:53:21.373] [INFO] main - ←[39mStarting in Wallet mode
←[33m[2016-06-16 23:53:21.872] [WARN] nodeConnector - ←[39mNODECONNECTOR ERROR { [Error: connect ENOENT \\.\pipe\geth.ipc]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'connect',
  address: '\\\\.\\pipe\\geth.ipc' }
Error: connect ENOENT \\.\pipe\geth.ipc
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
←[32m[2016-06-16 23:53:23.034] [INFO] ipcCommunicator - ←[39mBackend language set to:  bg

**Comment by TiratroN2** [comment]
Video driver 15.12 Crimson
Ethereum Wallet 0.7.5  last version
Starting from prompt

←[32m[2016-06-18 00:14:04.074] [INFO] main - ←[39mRunning in production mode: true
←[32m[2016-06-18 00:14:04.277] [INFO] main - ←[39mStarting in Wallet mode
←[32m[2016-06-18 00:14:08.083] [INFO] Windows - ←[39mCreating commonly-used windows
←[32m[2016-06-18 00:14:08.083] [INFO] Windows - ←[39mCreate window: loading, owner: notset
←[32m[2016-06-18 00:14:11.562] [INFO] updateChecker - ←[39mCheck for update...
←[32m[2016-06-18 00:14:14.729] [INFO] Windows - ←[39mCreate window: main, owner: notset
←[32m[2016-06-18 00:14:15.072] [INFO] Windows - ←[39mCreate window: splash, owner: notset
←[32m[2016-06-18 00:14:18.827] [INFO] updateChecker - ←[39mApp is up-to-date.

And that is all. Nothing more. No screen, no nothing.

**Comment by luclu** [comment]
@TiratroN2 could you kindly check how version `0.8.0` is behaving on this?
