### ISSUE TITLE
Mist wont open, geth still running in background, says cannot connect to geth.

### ISSUE THREAD

**Issue by rafajafar** [ethereum/mist#843]
Node type: geth
OS: windows
Network type: main
Mist version: 0.7.5

This is what happens when I start up Mist with this new version. Happens when run as administrator or not.

Log File: [node.txt](https://github.com/ethereum/mist/files/318744/node.txt)

![c11](https://cloud.githubusercontent.com/assets/5505214/16122548/84930e22-33b5-11e6-8a5c-11b994bd057a.PNG)

![c12](https://cloud.githubusercontent.com/assets/5505214/16122559/8a5c1ac4-33b5-11e6-831e-be600477e131.PNG)

![c13](https://cloud.githubusercontent.com/assets/5505214/16122562/8d6cc6aa-33b5-11e6-91a0-617edfda730f.PNG)

![c14](https://cloud.githubusercontent.com/assets/5505214/16122563/9028ffa8-33b5-11e6-85ea-9bd9ebaf00ff.PNG)

**Comment by HighTower79** [comment]
I do get the same error messages. 
I tried the --ignore-gpu-blacklist parameter and to let the wallet download a new blockchain from scratch. No difference.

**Comment by rafajafar** [comment]
Suddenly started working after 4th try. No idea why. No clock sync. Just ran it.

**Comment by luclu** [comment]
Thanks for reporting, I will keep you updated as soon as I get more info on this issue.

**Comment by luclu** [comment]
This might be related to https://github.com/ethereum/mist/pull/841
Please try this PR if familiar with git/developing. Otherwise I have to put you off to wait for the next release.

**Comment by bigcoinme** [comment]
Exactly same issue here!
Couldn't connect to node? See the logs for more:
Node type: geth
Network: main
Platform: linux (Architecure x64)

...um/chaindata
I0619 21:45:58.899879 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to /home/userid/.ethereum/dapp
I0619 21:45:59.146247 eth/backend.go:172] Protocol Versions: [63 62 61], Network Id: 1
I0619 21:45:59.162885 eth/backend.go:201] Blockchain DB Version: 3
I0619 21:45:59.225250 core/blockchain.go:206] Last header: #1734366 [3c632676…] TD=28993350184019213052
I0619 21:45:59.228626 core/blockchain.go:207] Last block: #1734366 [3c632676…] TD=28993350184019213052
I0619 21:45:59.228653 core/blockchain.go:208] Fast block: #1734366 [3c632676…] TD=28993350184019213052
I0619 21:45:59.491724 eth/handler.go:110] blockchain not empty, fast sync disabled
I0619 21:45:59.699825 p2p/server.go:313] Starting Server
I0619 21:46:00.350090 p2p/discover/udp.go:217] Listening, enode://8ce8408f07be6e6235ad408fc2de847ce28070d6a3966716b819241f22bb190df6995ebf2db760e2a804927c32c0f7b7222765b4576908e71a2f068935bcc092@[::]:30303
I0619 21:46:00.427028 p2p/server.go:556] Listening on [::]:30303
I0619 21:46:49.864872 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to /home/userid/.ethereum/chaindata

**Comment by luclu** [comment]
Could you kindly update to `0.8.1` and check if you are still affected?

**Comment by luclu** [comment]
Closed as of inactivity.
