### ISSUE TITLE
Contracts missing after loading 0.7.5, Won't show in any previous versions. 

### ISSUE THREAD

**Issue by 9600-** [ethereum/mist#844]
Node type: geth
OS: Windows 10
Network type: main
Mist version: 0.7.5

I've updated to the newest release of MIST (0.7.5) and upon on first load, the contracts took a second to populate the UI (DAO and Demo Contract Wallet), but after a restart of the wallet, I can no longer see any contracts, and only Etherebase account is showing. 

How do I load the contracts back into MIST?
Thank you,
9600

**Comment by 9600-** [comment]
Somehow, another process was using  the "chaindata" folder after 0.7.5 crashed on the same session. A complete reboot seems to have solved the issue, with the contracts showing up after a little while. 

However, the client has a habit of crashing (and becoming unresponsive) when being minimized or utilized over RDP.

**Comment by 9600-** [comment]
Sames issues, only UI freezing, menus are okay, and DAO tokens are not showing for the Etherbase account. Very erratic performance. Lots of corroborating issues here:

https://www.reddit.com/r/ethereum/comments/4oa3dk/new_ethereum_wallet_075_the_im_sorry_for_074/

**Comment by adamvp** [comment]
Same issue!

**Comment by JeffreyBPetersen** [comment]
Same issue, multisig contract disappeared and is now perpetually "Importing..." when entering the address in again.

**Comment by Beervangeer** [comment]
same here and cant watch TOKENS anymore, please help !

**Comment by luclu** [comment]
I can confirm. Token and contracts disappear on 0.7.5@OSX. I currently don't see a pattern.

**Comment by 9600-** [comment]
Has anyone successfully been able to send a transaction from their 0.7.5 affected wallet? I'm hearing lots of anecdotal complaints of password verification issues...

**Comment by 9600-** [comment]
Note: loading the wallet data with 0.7.4 still results with the missing contracts/tokens. 

I'm aware the contract still exists in the blockchain, but fear I may lose the ability to withdraw from that multi sig wallet from mist. Can someone suggest a procedure for importing/withdrawing from geth?

**Comment by 9600-** [comment]
Note: Wallet contract was created using the included wizard in V 0.5.1, Tokens are DAO.

**Comment by 9600-** [comment]
Was able to import contract and transfer all ETH to my etherbase account using 0.7.2. 
Am only missing DAO tokens at this time.

**Comment by 9600-** [comment]
Re added the DAO contract and watcher. 
There is some condition upon loading 0.7.5 that clears the contract content amidst the UI lockups and hung GETH instances.

**Comment by 9600-** [comment]
Can confirm. Every time I re-load 0.7.5, all contracts are cleared and must be re-added. Will continue using 0.7.4 until this is resolved.

**Comment by dennyuel** [comment]
using mac latest version and this update works fine for me. fast and responsive every way. So could be on windows only?

**Comment by bigcoinme** [comment]
Exactly same issue here.
Node type: geth
Network: main
Platform: linux (Architecure x64)

**Comment by davedavis** [comment]
Can confirm.
All watched tokens are removed after restart of Mist/Geth.

**Comment by dsystems-io** [comment]
I can confirm the same issue here. Restarting Mist clears all watched contracts and tokens. Have had this issue in versions 0.7.4, 0.7.5, and 0.7.6.

Node type: Geth
Network: Main
Platform: Ubuntu 14.04 x64

**Comment by tinodj** [comment]
It seems this is back in 0.9.0 on MacOS. Just updated and after restart nothing is there. Tried several times importing contracts and adding watched tokens but it is not better.

**Comment by staticfrost** [comment]
just not just on mac but windows 10 too.

**Comment by BigBearB** [comment]
Dear Evertonfraga,

You are a genius.  Please, please, please make the wallet work for ERC20 without us having to use v. 8.10.
Please ?

**Comment by staticfrost** [comment]
@alexvandesande what!?

**Comment by cangea** [comment]
Same here..
