### ISSUE TITLE
Danish Translation

### ISSUE THREAD

**Issue by tpberntsen** [ethereum/mist#845]
Working on a translation into Danish.

**Comment by luclu** [comment]
Awesome @tpberntsen! I'll be there if you need some technical help. ;)

**Comment by ChihChengLiang** [comment]
hi @tpberntsen , 
I wrote a guide on translations, see if this helps:
https://github.com/ethereum/mist/wiki/Translation-and-i18n-Guide

**Comment by luclu** [comment]
I will close this as of inactivity. Feel free to file a pull-request any time or ping us on gitter for help.
