### ISSUE TITLE
Mist Keystone issue

### ISSUE THREAD

**Issue by sykong36** [ethereum/mist#846]
My key stone account file is not updating. I made several transaction ,but when I copied it and pasted at new mist wallet on new computer It shows original amount that I imported from Jason file. Key stone account file is always same date ( modification date at window) even I did transfer either. The original wallet shows the latest amount. but not key stone file. Please help..

**Comment by luclu** [comment]
@sykong36 I'm not sure if I understand you correctly.
The files in your `keystore`-folder contain the information about your accounts address as well it's private key which you need to move funds. The Ether or token are not saved in the file but on the blockchain. Make sure to have an up-to-date client, thus a fully synced wallet to see the current balance.

I will close this for now. I will stay here to assist you though.

**Comment by sykong36** [comment]
Thank you. I got it
