### ISSUE TITLE
Random Transactions in Wallet List

### ISSUE THREAD

**Issue by larrysmith1000** [ethereum/mist#848]
Yay! 7.5 is out.  Thank you!

I'm not sure if this is purposeful functionality, when watching TheDAO, but when I open Ethereum Wallet after having been closed for a few days, I see a bunch of transactions all sent to TheDAO popup and listed in the "Latest Transactions" window.  They are from random address.  The DAOToken transfers are successful transfers to TheDAO.  The Ether transfers are unsuccessful transfers to TheDAO.

It's not a huge deal as long as the number of transactions with the DAO doesn't become ridiculous.  It just scared me at firsts to hear all these transaction notifications dinging while I was on the toilet.  I had to run to the computer to make sure I wasn't getting attacked.  Office-mates thought it was hilarious.

Here is a screenshot:
![weirdtransactions](https://cloud.githubusercontent.com/assets/19583370/16138078/b026a966-33ee-11e6-959c-c9b3dcb38c78.PNG)

**Comment by luclu** [comment]
@larrysmith1000 this is showing all [events](https://solidity.readthedocs.io/en/latest/contracts.html#events) triggered by "The DAO". Most of them are not very useful for a normal user. For now please just disable event-watching in that contract in 0.7.5.
