### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#85]
Hello,

I would like to request a feature: Minimize to tray. I dont want to close the wallet, but also dont want to have it open all the time. 

Cheers.

**Comment by HelixiR** [comment]
+1

**Comment by frozeman** [comment]
Works on OSX, which os you use?

**Comment by 5chdn** [comment]
In linux there is no tray icon available.

Archlinux with MateDesktop.

**Comment by MaximoMax** [comment]
Yep. That would be awesome. Want to keep it running always, but the extra window bothers me while working, I like to keep everything as cleaned up as possible.

**Comment by anime2399** [comment]
I would like this also in the Windows client

**Comment by david340804** [comment]
+1 on Windows
