### ISSUE TITLE
Windows Installer

### ISSUE THREAD

**Issue by hiddentao** [ethereum/mist#850]
OS: windows
 
It's clear from numerous user reports that we need an EXE installer for windows. `https://www.npmjs.com/package/electron-windows-installer` will probably do the job, but we need a code signing certificate if we are to get past Windows' security.

Someone in the foundation needs to do this for us - https://msdn.microsoft.com/en-us/library/windows/hardware/hh801887.aspx

**Comment by luclu** [comment]
Done, PR https://github.com/ethereum/mist/pull/1159.
