### ISSUE TITLE
Can't withdraw from Ethereum Wallet 0.7.4 Mac

### ISSUE THREAD

**Issue by ryancharleston** [ethereum/mist#853]
Trying to send 1.36 ETH from my Ethereum Wallet on a Mac to an online exchange wallet and nothing happens. My ETH never gets sent. I've tried 3 times and nothing happens. Is this a bug?

**Comment by luclu** [comment]
@ryancharleston please be more specific about your process and any alerts/errors. Use a blockchainexplorer to verify the transactions status and also try with the latest version 0.7.5.

**Comment by ryancharleston** [comment]
This is the transaction - 
http://etherscan.io/tx/0x82104eeb072325c93b9cf3b783e6703124495be819f48057282b27af3b1ce7a2

**Comment by ryancharleston** [comment]
Just upgraded to 0.7.5 and tried again - http://etherscan.io/tx/0xef0935af0553c769b7b7e99343f81c8016dfa14dcc75a7c67cd862f0e506de29

**Comment by luclu** [comment]
Great!
