### ISSUE TITLE
Couldn't connecto to node [solved by reboot]

### ISSUE THREAD

**Issue by fineartcommodities** [ethereum/mist#854]
Ethereum-Wallet-win64-0-7-5, main mode.
Till 06.18.2016 all running fine.
06.19.2016, 11:30 AM, all wallets disappear!
Got this error on screen.

![er](https://cloud.githubusercontent.com/assets/17668554/16176675/9e361f7a-3614-11e6-8a53-e4314f1b9fd1.png)

Have try previous version of mist till 0-6-2 without  success.

**Comment by luclu** [comment]
@fineartcommodities don't worry about your wallets they will still be under `%appdata%\Ethereum\keystore`. Please try to reboot your computer for start.

**Comment by fineartcommodities** [comment]
Thak you, rebooted and working.
