### ISSUE TITLE
incorrect receiving address on 'execute contract' page 

### ISSUE THREAD

**Issue by dcsvt** [ethereum/mist#857]
I'm trying to send my DAO from my Ethereum Wallet to an exchange, I put the correct receiving address when I was filling up the form, but after I clicked the 'send', on the next 'execute contract' page, the receiving address appeared is not the one I put in, automatically became the DAO crowdsale address a while ago where we deposited our Ethers into, the one on the DAO website.

I've tried restarting my application several times, also updated to the latest version 0.7.5. The problem still persists. 

Has anyone experienced the same problem or know the solution? 

Thanks.

**Comment by luclu** [comment]
@dcsvt please check the transaction details with a blockchainexplorer like [etherscan.io](https://etherscan.io).
Also note that many exchanges will take up over 100 confirmations to display your desposit.

**Comment by dcsvt** [comment]
thanks for responding but that was not my question

**Comment by luclu** [comment]
Don't worry, this completely normal as you interact - by means of your transaction you are confirming - with the contract of "The DAO" instructing it to "send" your Token to the exchange.
What happens on low level is you instruct a change of ownership within that contracts mapping `owners` variable.
