### ISSUE TITLE
0.6.1 does not sync

### ISSUE THREAD

**Issue by ORIELLY** [ethereum/mist#858]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment]
Please update to version 0.7.5. There have been substantial improvements in the 0.7 line. We can't support legacy versions.

**Comment by ORIELLY** [comment]
how can I update , If I back up with last sync I made were all ethers are not reflected completely will I recover all my ethers inclusive those not reflected?

**Comment by luclu** [comment]
Use those links: https://github.com/ethereum/mist/releases
No ether will be affected as not the ether but your right to access it is saved in the accounts keyfile in the keystore folder. Make sure to backup this -> menu -> accounts -> backup -> accounts.

**Comment by ORIELLY** [comment]
ok thanks will do and advise

**Comment by ORIELLY** [comment]
hello luclu, I downloaded version 7.5 and I opened it and stays hanged in looking for peers,i have done nothing yet with old keyfile how should I proceed since the new version did not ask for anything ?

**Comment by ORIELLY** [comment]
would appreciate help asap I have hours and nothing no sync

**Comment by luclu** [comment]
Please have a look at these recommendations: https://github.com/ethereum/mist/issues/876
