### ISSUE TITLE
Calculated gas is not enough?

### ISSUE THREAD

**Issue by kobigurk** [ethereum/mist#86]
I followed [avsa's post](https://blog.ethereum.org/2015/12/07/ethereum-in-practice-part-3-how-to-build-your-own-transparent-bank-on-the-blockchain/), and have both a [mintable token](https://frontier.ether.camp/account/e6069d0158fddf0fd9b13f8f9fe69829c4b869ed) and a [democracy DAO](https://frontier.ether.camp/account/4676b720c02e5089664d9cac6ed55054ee2a6e63).

The last part, of executing the proposal with the mintToken bytes partially fails - the proposal gets closed but the token isn't transferred.

Examining the situation reveals this [transaction](https://frontier.ether.camp/transaction/24c20c8a3b7881), which has 2 internal transactions in which the 2nd internal one, the minting, fails. 
The gas calculated by mist (I think after adding more 10000) was *66266*.
This is the tx receipt:
```
{
  blockHash: "0xd30cb74cee6f736bf711afc706678d783e989f69767954595683f677c1d30be0",
  blockNumber: 680133,
  contractAddress: null,
  cumulativeGasUsed: 70645,
  gasUsed: 39375,
  logs: [{
      address: "0x4676b720c02e5089664d9cac6ed55054ee2a6e63",
      blockHash: "0xd30cb74cee6f736bf711afc706678d783e989f69767954595683f677c1d30be0",
      blockNumber: 680133,
      data: "0x0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000070a08231000000000000000000000000556b2b8d4c0da3433544756c237503cc0000000000000000000000000000000000000000000000000000000000000000",
      logIndex: 0,
      topics: ["0xd220b7272a8b6d0d7d6bcdace67b936a8f175e6d5c1b3ee438b72256b32ab3af"],
      transactionHash: "0x24c20c8a3b7881a67317903f8b6d1c0f2f5a6b30d5b713a89a747d47c6d3ac05",
      transactionIndex: 1
  }],
  transactionHash: "0x24c20c8a3b7881a67317903f8b6d1c0f2f5a6b30d5b713a89a747d47c6d3ac05",
  transactionIndex: 1
}
```

Adding more gas made it work perfectly, like in this [transaction](https://frontier.ether.camp/transaction/67f623c1a883ca).

The weird thing is that in the successful tx, the gas used is only *41330*.

What's going on here? :O

**Comment by alexvandesande** [comment]
Some transactions require more gas than they spend, sometimes because there's a refund on the middle of the transaction. Mist is not putting enough gas on transactions, this will be fixed on the next release. Add at least 100,000 to any transaction. If in doubt, put 500k to 1 million gas.
