### ISSUE TITLE
"add wallet contract" button disappeared

### ISSUE THREAD

**Issue by luclu** [ethereum/mist#860]
Node type: geth
OS: linux (Ubuntu 14.04 x64)
Network type: main
Mist version: 0.7.5.

<img width="1101" alt="unbenannt-1" src="https://cloud.githubusercontent.com/assets/10135872/16180512/3a9c227a-3687-11e6-99b8-ef788a09a5c8.png">

**Comment by AnmarHub** [comment]
I have the same issue here. I'm on the latest version of Ethereum Wallet 0.8.6 using Windows 7  64bit. I don't see "Add Wallet Contract" under "Wallet Contracts" header. My Wallet does not show my balance in my Main Account either. It shows 0.00 balance and my Wallet Contract is not there at all which used to have the most funds of Ether there. I need to import my Wallet Contract so I can retrieve my Ether funds and when I try to do so by clicking on "Watch Contract" and input my Wallet contract name and address and click OK it says "Couldn't parse JSON Interface". I don't know how and where do I get my JSON Interface from.

**Comment by luclu** [comment]
@AnmarHub you will need to have fully synced before you can access this functionality.

**Comment by AnmarHub** [comment]
Thanks for your reply. I appreciate it.

**Comment by cooperka** [comment]
I have the exact same issue on the latest Mist v0.9.0. My node is **fully synced**; last block was 30 seconds ago. I'm trying to re-add a contract associated with my account, but the "Add Wallet Contract" button is missing like in the OP's screenshot. Any advice @luclu?

**Comment by cooperka** [comment]
Found a workaround! I clicked on my Account and there's another link there to create a Wallet Contract. See screenshot, I just clicked that hyperlink and imported it. Phew :sweat_smile: 

![screenshot from 2017-08-19 11-22-39](https://user-images.githubusercontent.com/2047062/29488036-fbdda862-84d0-11e7-8095-25e1e9ca293d.png)
