### ISSUE TITLE
transaction did not 'broadcast' to shapeshift address but ether left wallet

### ISSUE THREAD

**Issue by nic-f** [ethereum/mist#861]
Node type: geth 1.3.6 (go)
OS: windows 64
Network type: main
Mist version: 0-7-4

Can someone please help me recover my ether? I will split the 41 ether with you because I cannot do it myself.

My wallet: 

0x1bFc02A85A33a49459F2a6b6330F1428512d7a96

address I tried to send to:

0x270434d3a4dbfd7e68498ebc81cb30c14a5eb6d5

![capture1](https://cloud.githubusercontent.com/assets/20006410/16187978/3fc54d12-370e-11e6-8bb2-cc7f47c4e064.JPG)

![capture2](https://cloud.githubusercontent.com/assets/20006410/16188034/7f6ed622-370e-11e6-9b6b-7a0ef3cc9001.JPG)

[node.zip](https://github.com/ethereum/mist/files/322991/node.zip)

**Comment by nic-f** [comment]
sorry, I think this log has the details
[node.log.zip](https://github.com/ethereum/mist/files/323375/node.log.zip)

**Comment by nic-f** [comment]
sorry I think this has the log details for the transaction in question. See time 21:09:52
[node.log.zip](https://github.com/ethereum/mist/files/323389/node.log.zip)

**Comment by luclu** [comment]
As the recipient account [0x270434d3a4dbfd7e68498ebc81cb30c14a5eb6d5](http://etherscan.io/address/0x270434d3a4dbfd7e68498ebc81cb30c14a5eb6d5) didn't receive any fund the transaction has not been broadcasted. Make sure to use the default transaction fee for now. Ones too low might be rejected by the network as no miner picks it up.

But tracing your later transaction [0xf30a187faf43fc951ef21206259ed99bb57f1a0b1cc59607047b91dca9e7dcee](http://etherscan.io/tx/0xf30a187faf43fc951ef21206259ed99bb57f1a0b1cc59607047b91dca9e7dcee) you seem to have eventually send the 41 Ether to shapeshift's [0x9e6316f44baeeee5d41a1070516cc5fa47baf227](http://etherscan.io/address/0x9e6316f44baeeee5d41a1070516cc5fa47baf227).

I will close this for now as this seems to be solved.
If you are not sure about the whereabouts of your Ether reach out to shapeshift refering to this valid 41 Ether transaction [0xf30a187faf43fc951ef21206259ed99bb57f1a0b1cc59607047b91dca9e7dcee](http://etherscan.io./tx/0xf30a187faf43fc951ef21206259ed99bb57f1a0b1cc59607047b91dca9e7dcee).
