### ISSUE TITLE
Mist Wallet 0.7.5 on OSX unusable

### ISSUE THREAD

**Issue by mruepp** [ethereum/mist#862]
Node type: geth/eth
OS: osx
Network type: main/test
Mist version: 0.7.5

Downloaded and started Mist Wallet OSX. The GUI is unresponsive. After a while opened, the gui completely vanish.
I have the DAO Contract and Token installed. Besides I have only one empty contract and three wallets installed.

I am not able to remove the DAO Contract or to do anything, click on wallets or whatever. Not responsive.

This is a bad thing despite whats going on with the dao and users are requested to act on the contract however!!!

Node Log shows activity.

I0620 19:23:12.314659 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 13.406341ms. #1739864 [8225d8e1 / 8225d8e1]
I0620 19:23:13.336529 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 14.895525ms. #1739864 [d1f8cd74 / d1f8cd74]
I0620 19:23:20.440918 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 6.383098ms. #1739865 [5898c557 / 5898c557]
I0620 19:23:39.793519 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 8 txs in 18.945882ms. #1739866 [dda4b7e5 / dda4b7e5]
I0620 19:23:50.260671 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 5.813396ms. #1739867 [5f9b863d / 5f9b863d]
I0620 19:24:01.386127 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 6 txs in 15.339826ms. #1739868 [cd3dce03 / cd3dce03]
I0620 19:24:16.146392 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 4 txs in 10.998964ms. #1739869 [296c8b8f / 296c8b8f]
I0620 19:24:52.715539 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.100677ms. #1739870 [a403d181 / a403d181]
I0620 19:24:59.255520 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 5.507458ms. #1739871 [72c21285 / 72c21285]
I0620 19:25:02.519165 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 12 txs in 149.313142ms. #1739872 [66f011e9 / 66f011e9]
I0620 19:25:04.038605 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 12 txs in 152.030089ms. #1739872 [6edd77f9 / 6edd77f9]
I0620 19:25:35.626436 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 9.119911ms. #1739873 [e3c4d252 / e3c4d252]
I0620 19:25:40.447713 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 16 txs in 31.477348ms. #1739874 [be2440c0 / be2440c0]
I0620 19:25:56.398371 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 5.640308ms. #1739875 [77168e0c / 77168e0c]
I0620 19:26:04.462773 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 11.581526ms. #1739876 [7a3fdcec / 7a3fdcec]
I0620 19:26:24.696416 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 7.925125ms. #1739877 [88535df1 / 88535df1]
I0620 19:26:33.294629 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 14 txs in 32.179477ms. #1739878 [da275751 / da275751]
I0620 19:26:33.676422 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 14 txs in 32.873052ms. #1739878 [3d1404f3 / 3d1404f3]
I0620 19:26:56.893254 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 15.535193ms. #1739879 [ff1b1fe1 / ff1b1fe1]
I0620 19:27:32.706126 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 6 txs in 16.79592ms. #1739880 [e1a206b4 / e1a206b4]
I0620 19:27:33.454842 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 6 txs in 13.830429ms. #1739880 [d483fb9e / d483fb9e]
I0620 19:27:38.293192 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 8 txs in 17.745937ms. #1739881 [090c83c0 / 090c83c0]
I0620 19:27:39.444903 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 8 txs in 18.265054ms. #1739881 [fdc20c17 / fdc20c17]
I0620 19:27:46.971937 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 15.574955ms. #1739882 [38073e64 / 38073e64]
I0620 19:27:51.622084 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 14.112153ms. #1739883 [cb2c3c0c / cb2c3c0c]
I0620 19:27:52.389423 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 14.545816ms. #1739883 [93d12be2 / 93d12be2]
I0620 19:29:18.717502 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 11.671799ms. #1739884 [e493c3ef / e493c3ef]
I0620 19:29:25.756590 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 5.621382ms. #1739885 [79141fd3 / 79141fd3]
I0620 19:29:46.105924 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 19 txs in 31.631766ms. #1739886 [47b6c436 / 47b6c436]
I0620 19:29:54.873817 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.085614ms. #1739887 [b31d9aa6 / b31d9aa6]
I0620 19:29:59.893249 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 24.713957ms. #1739888 [726978fd / 726978fd]
I0620 19:30:01.614981 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.177278ms. #1739889 [ba0ee7fe / ba0ee7fe]
I0620 19:30:25.491354 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 5.245555ms. #1739890 [88ee0844 / 88ee0844]
I0620 19:30:52.404901 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 14 txs in 33.675959ms. #1739891 [1b9d4bdd / 1b9d4bdd]
I0620 19:30:55.045744 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.241009ms. #1739892 [1a4fd356 / 1a4fd356]
I0620 19:31:15.745646 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 9 txs in 14.187326ms. #1739893 [28bc17a1 / 28bc17a1]
I0620 19:31:22.588824 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 14.255948ms. #1739894 [b3843514 / b3843514]

**Comment by mitchellcash** [comment]
I confirm I am also seeing this issue. The application splash screen seems to work okay, it loads the blocks, connects to peers etc.

However, when the application itself starts it is immediately unresponsive and frozen. I have let it sit for some time to no avail.

**Comment by webdevotion** [comment]
Coming from 0.7.3 I installed 0.7.5 ( which is now called _Ethereum Wallet_ opposed to _Ethereum-Wallet_ ).  It fixed another bug for me ( #281 ) but introduced an unresponsive UI.  Not immediately but after a couple minutes of usage.

I also have the DAO contract in my wallet.  

@mruepp FWIW - I believe the latest advice is to not do anything re: DAO.  
Go to the DAO slack channel for some advice ( and FUD ).

**Comment by mruepp** [comment]
@webdevotion 
Thx I am on the slack channel already and did nothing. There was a situation friday when devs speculated about users joining a split to secure their tokens...

**Comment by nortcele** [comment]
Same for me. Can't do anything with Ethereum Wallet 0.7.5 on OS X 10.11.5.

**Comment by knocte** [comment]
Same for me on Ubuntu Linux 16.04 LTS (both 0.7.5 and 0.7.6).

**Comment by knocte** [comment]
I have found a workaround: `mv ~/.config/Mist ~/.config/MistBackup`

This, of course, means that you will need to re-watch all contracts (e.g. DAO), and other things. But maybe by doing this we can pinpoint the exact setting that makes Mist get unresponsive.

**Comment by nortcele** [comment]
Version 0.7.6 still show the same behavior and is unusable on OS X 10.11.5.

**Comment by iethereumny** [comment]
Same for me. Reverted back to 0.7.4 in order to access my wallets.

**Comment by mruepp** [comment]
Started 0.7.4 and removing the Dao contract resolved the issue for all versions after 0.7.4

**Comment by knocte** [comment]
Why did you close the issue? You might have found a workaround, but the fact that people here are being affected demonstrates there's a real bug to solve.

**Comment by mitchellcash** [comment]
@knocte I am yet to try the latest release but agree, at the time this was closed it was still an issue for me. I could remove the contract but what if I wanted to keep the contract.

**Comment by knocte** [comment]
Exactly, this is not a "technical support ticket", this is a bug tracking tool. Please reopen the issue.
