### ISSUE TITLE
copy to clipboard failing

### ISSUE THREAD

**Issue by mowliv** [ethereum/mist#865]
Node type: geth 1.3.6
OS: osx
Network type: main
Mist version: 0.7.4

Click copy address from a contract wallet page, get the copied to clipboard message (twice) but then address isn't on the clipboard. Clipboard unchanged. Happens with base wallet as well.

![image](https://cloud.githubusercontent.com/assets/4602829/16211642/9f253f90-36f7-11e6-94d3-0ce6a2346307.png)

**Comment by JimmyMow** [comment]
+1

**Comment by luclu** [comment]
Please update to version `0.7.5`. This has been fixed https://github.com/ethereum/mist/issues/650

**Comment by mowliv** [comment]
Confirmed - thanks.
