### ISSUE TITLE
Basic funds move gets "Insufficient funds for gas * price + value”

### ISSUE THREAD

**Issue by mowliv** [ethereum/mist#866]
Node type: geth 1.3.6
OS: osx
Network type: main
Mist version: 0.7.4

Playing with mac version. Tried sending funds from base wallet to simple contract wallet. Worked fine. But then tried sending funds back to base wallet, and get error **"Insufficient funds for gas * price + value”**. 

Not sure what I'm missing here, or if there's a bug. I am checking the "send all funds" and leaving the fee slider alone.

Console window:

/Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/modules/preloader/console-log-capture…:17 Providing gas:  54447  + 100000
/Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/modules/preloader/console-log-capture…:17 Finally choosen gas 154447
/Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/modules/preloader/console-log-capture…:17 Send Ether
/Applications/Ethereum-Wallet.app/Contents/Resources/app.asar/modules/preloader/console-log-capture…:17 Error: Insufficient funds for gas * price + value(…) undefined

**Comment by luclu** [comment]
Please have a look at https://github.com/ethereum/mist/issues/664. This happens when your coinbase balance - the account you pay for contract execution from - is too low.
I will close this as a duplicate. Feel free to subscribe to the other issue to get updates.

**Comment by mowliv** [comment]
@luclu Shouldn't the app prevent someone from doing what I just did? I transferred all funds into the contract wallet I just created, thinking that was where I would do all transactions from. I used the "transfer everything" checkbox. Sure would be nice if it warned me to leave a little behind. Silly jackpot I'm in now. How much do I need in the main wallet (I think that's same thing as coinbase balance) to be able to spend small amounts out of contract wallet?

**Comment by luclu** [comment]
You are right. I added this to the other issue:
> Additionally there should be a warning if a transaction should deplete the etherbase account to a balance that would not allow to execute transfers from contract wallets.

**Comment by mowliv** [comment]
Cool, thanks!

**Comment by crypt61** [comment]
I am getting the error "Insufficient funds for gas * price + value”. However, I have a balance of 0.090948
ETH, and the "max total" of the transaction is 0.076000. That seems to be plenty of funds to complete the transaction. What am I missing? Thank you for your help.

**Comment by tlossen** [comment]
@crypt61 same here

**Comment by OpakAlex** [comment]
same issue. (Пишите нормальный софт заебали пидары)

**Comment by kolinko** [comment]
Same issue.

Trying to send a tx (trade order to etherDelta), and even with a high gasprice above 30 gwei, I get the error. I guess this is related to high network load due to CryptoKittens...

**Comment by Spiv13** [comment]
Had same error.
Thrying to send 0.05 ETH from an account with 2.10 ETH.
Must be a glitch???

**Comment by avloss** [comment]
same here - created a secondary account, put some ether there, now can take it out, nor spend!

**Comment by nitso** [comment]
Same here. Let me buy those kitties!

**Comment by Sultanite007** [comment]
Got the same problem. Cannot send any transaction and I have the available funds

**Comment by crypt61** [comment]
Here is the response from MetaMask...

Hello, 

There is currently a combination of both a backlog in pending transactions on the network as well as rising competition for gas prices with CryptoKitties. Unfortunately this is causing some transactions with lower gas prices to take longer to process or even fail. Unfortunately there is little to be done about this besides waiting for any pending transactions to go through or show as failed/rejected. This waiting period can take up to 24 hours during congested network times such as this. 

For your refernece in using gas with Dapps such as CryptoKitties, Ether Delta and others: https://support.metamask.io/kb/article/25-transaction-submission-best-practices-on-etherdelta-and-dapps/

**Comment by StarNeit** [comment]
same error.

insufficient funds for gas * price + value

any solution yet?

**Comment by Spiv13** [comment]
@StarNeit 
In my case, it just solved itself.
I guess there was just some congestion at the time as it was suggested by others.

**Comment by zcc1234567** [comment]
same error,
I use goland call smartcontract,got this error "insufficient funds for gas * price + value",but the account that I use to call contract has enough eth (100eth)。

**Comment by SirPhemmiey** [comment]
Any solution for this please?
