### ISSUE TITLE
Ether Account does not load up with Ether

### ISSUE THREAD

**Issue by Robinhomestudies** [ethereum/mist#867]
Node type: geth 1.4.7
OS: osx
Network type: main
Mist version: 0.7.5

Hello I'am pretty new to Crypto currency. However before I started investigating in Ether I've checked all available Videos to make it easy to get started. 
Downloaded the latest version of Ethereum-Wallet. Installed and account created.

**Now I've tried to fill up my Ether Main Account with Ether.** 

My Ether Account: 0x9514b58e08E5d5462A6eBBC4AF66c6d8A9895413

**here's one of the transactions which has been made:**
https://etherscan.io/tx/0x991700ccaa92ce0e0fc729148a0603265639115f2de09606c2a2c64f87480e9d

The Ether doesn't show up in my Wallet I did 3 transactions. Two direct in the Wallet change bitcoin to ether. Once I've tryed it by Shapeshift.io without success.
I copied my Ethereum-Wallet accounts number and copied it into the change field acc. Shapeshift the amount is changed to ether and send to my account but I don't see it as amount nether can I create a Wallet-contract due to I have no Ether.

I'am getting pretty upset with the Wallet but I'am very keen to start investigating in Ether. 

What can I do or what am I doing wrong?

Looking forward to your support.

thanks Robin

P.S if this question has already be released please let me know where to find.

**Comment by luclu** [comment]
Hi Robin, your funds will be displayed as soon as your local client synced to the block height at which you made those transactions. Please check if the synchronization is completed.

**Comment by Robinhomestudies** [comment]
Hi luca, Thanks for your support. It worked.

have a nice day.



*Robin Gut*


*home**studies*
Online Sprachschule

*Telefon*:        043 537 86 09
*Skype*:          robin.homestudies
*Mail*:             robin.gut@homestudies.ch
*Website*:       www.homestudies.ch

*Folgen Sie uns und bleiben Sie informiert. So verpassen Sie keine
Rabatt-Aktion oder aktuelle News von homestudies.*

  <https://www.facebook.com/pages/homestudies/377137895741192>
<https://plus.google.com/u/0/+homestudiesCHhomestudies/posts>
<http://www.linkedin.com/company/homestudies?trk=prof-following-company-logo>
  <https://twitter.com/homestudiesblog/>

2016-06-21 13:39 GMT+02:00 Luca Zeug <notifications@github.com>:
