### ISSUE TITLE
'select contract' on deploy contract pane disappeared

### ISSUE THREAD

**Issue by mrmayfield** [ethereum/mist#868]
I am running into this error after clicking 'Deploy', but my GUI doesn't show a 'select contract' menu

Version 0.7.4 on OSX

<img width="1440" alt="screen shot 2016-06-21 at 11 40 54 am" src="https://cloud.githubusercontent.com/assets/7200471/16241982/307b9658-37a5-11e6-9fb4-df53a728fb35.png">
<img width="1265" alt="screen shot 2016-06-21 at 11 40 31 am" src="https://cloud.githubusercontent.com/assets/7200471/16241983/307c64b6-37a5-11e6-9087-7a0c4dca0b34.png">

**Comment by luclu** [comment]
Thank you for reporting. 
Is this persistent/reproducible?

**Comment by mrmayfield** [comment]
Yes it's persistent, I can't get around it.

**Comment by mrmayfield** [comment]
Okay, I've found a way around it. If I start to change the text, then the dropbox to select a contract appears.

**Comment by luclu** [comment]
Ah, that's the default behaviour to prevent deploying of that placeholder contract - my oversight. It's not a bug though. ;)

**Comment by mrmayfield** [comment]
Is there a reason why we wouldn't want the default contract to be deployed?

**Comment by MELCHEZEDEK776** [comment]
youre talking about the hard fork right? I just read something,


https://steemit.com/ethereum/@innuendo/there-can-be-no-freedom-without-responsibility

Whether Ether forks due the cash flow people are forgetting the movement
that is slowly building around us, Virtually, I think a new set of adoptive
rules should be drafted as they will in the contracts\communities. Either
way, true code reveals itself eventually.

**Comment by manipulator01** [comment]
@luclu I am getting the same error. It's a bug. I tried everything I can but I cannot get around it.

note: I am not trying to deploy placeholder contract. I am trying to deploy the contract that I wrote
