### ISSUE TITLE
small GUI issues (0.7.5)

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/mist#869]
Node type: geth
OS: linux Debian 8
Network type: main/test
Mist version: 0.7.5

(tested `Ethereum-Wallet-linux64-0-7-5` on Debian 8, with [this](https://gist.github.com/drandreaskrueger/912e704cfc86fd757277a5fd9bd372d4) configuration)

---

Created an account address in mist, new account not shown in mist until I restart geth and mist.

---

creating wallet contract:

Your GUI keeps on saying "wrong password". The correct reason is shown in the CLI:

> [2016-06-22 01:13:47.778] [INFO](ui: popup) - Estimated gas:  1962239 null
> [2016-06-22 01:14:20.327] [INFO](ui: popup) - Choosen Gas:  0x2dc6c0 0x2dc6c0
> [2016-06-22 01:14:22.217] [ERROR] ipcProviderBackend - Send request failed 
> { code: -32000, message: 'Insufficient funds for gas \* price + value' }

Sent more money, then it worked.

_Warning: opinion. 0.03924478 ETH - Really?  For creating 1 contract address?  0.46 Euro is much IMHO. Yes fiatbanks are less useful than a wallet contract lol (but some even give you money if you open an account). Would all this become only cheaper by ETH price dropping? Is it planned to correct contract prices, with rising ETH-price?_

---

All dialogs all missing an important function, e.g.

> Backup your wallet contract address!
> Make sure to write down the wallet contract address:

Not possible to right click "copy". Clipboard only works by keyboard.

---

Other than that:  Great work. A beautiful piece of software!

**Comment by luclu** [comment]
@drandreaskrueger thank you for the neat writeup!
> Your GUI keeps on saying "wrong password". `Insufficient funds for gas * price + value`

This is a known issue, here is the bug report: https://github.com/ethereum/mist/issues/664
> Created an account address in mist, new account not shown in mist until I restart geth and mist.

`0.7.5`seems to produce inconsistencies in its database. Might be related to https://github.com/ethereum/mist/issues/859? - pinging @hiddentao 
> Not possible to right click "copy". Clipboard only works by keyboard.

Yes I like to see this, too. It has been proposed in https://github.com/ethereum/mist/issues/145.

**Comment by luclu** [comment]
I pooled your issues in the linked bug reports. Will close this for now. Feel free to stay if you have questions or join our gitter channel.

**Comment by drandreaskrueger** [comment]
> I pooled your issues in the linked bug reports.

Great. Thanks a lot. Well done.

So (a) I was right, but (b) not the first one to notice those :-)

Yes, I am in your gitter channel.

> This can get cheaper if miners choose to process transactions at a lower gas price  

I see.

I am wondering to deploy at e.g. 1/10 of the default gas price, and just hope that some miner would pick it up? Technically possible?

**Comment by luclu** [comment]
> I am wondering to deploy at e.g. 1/10 of the default gas price, and just hope that some miner would pick it up? Technically possible?

While it might be possible there is the risk of it getting stuck and being dropped by the network. Unfortunately I am totally unaware of those mechanisms. You could give it a try! I would be interested in the outcome. ;)

You can monitor pending transactions here: [etherscan.io/txsPending](http://etherscan.io/txsPending)
And the network status as well as the gas price here: [ethstats.net](https://ethstats.net/)

**Comment by drandreaskrueger** [comment]
# Saving money on gas

> You could give it a try! I would be interested in the outcome. ;)

My first attempts with the [original WalletContract](https://github.com/ethereum/dapp-bin/blob/master/wallet/wallet.sol) were inconclusive.  I do not know how exactly to deploy as mist was doing that for me (would like to try, any hints? How deploy that wallet.sol correctly, manually?)

So: 
* Default contractwallet sol code, but 1 not 20 GWei.  
* ETH from unlocked: 0x58b23611225bba3601bcd76ac7517e185559b6a0  
* gasPrice: 0x003b9aca00 == 1 000 000 000 decimal  
* transaction: 0x760521674fc57baabe34654e9585d8965f54c7d528b3aa37318f1a8c231d2287  
* transaction: 0x57ba41228f721a9fc1eb524f99c7229baef4c26987b939f0cdc4e7a64445ebd4  
* both: no success  

Not want to spend money for testing (and haven't looked into --testnet which can behave differently, anyways). So I wrote a simpler contract.

Here is a log. 

> You can monitor pending transactions here: etherscan.io/txsPending
> And the network status as well as the gas price here: ethstats.net

Useful, thanks.

I have tried:


### (1) Standard, via 'mix-ide' (default is gas price 20 Gwei).

To deploy has cost 0.00128116 ETH = 0.0152 eurocent.  

A very important contract. Try it:

    geth attach
    TheAnswer_Expensive = web3.eth.contract([{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"inputs":[],"type":"constructor"}]).at("0x09a682102cd8c3ec63a9bffc62b7d01ad21d486c")
    TheAnswer_Expensive.get()




### (2) Manual override: 

* switch off "Gas price Default 20 GWei"
* choose 10 Gwei instead of 20 Gwei

Now:
* I get a txId
* No message from the network whatsoever ("too little gas to bother us")
* The txId is nowhere to be found!
* my balance is untouched

http://etherscan.io/tx/0x46b46437be3f35d97c66af89c741a24bb162c4f7f880b8e41c9680c45c4104d1



### (3) Manual override: 15Gwei instead of 20Gwei

0xf084754f8ee70becf0350fa78e8f50a3d967acb0e9192b8306e0aeb11c481f2f
http://etherscan.io/tx/0xf084754f8ee70becf0350fa78e8f50a3d967acb0e9192b8306e0aeb11c481f2f

* same as above


### (4) Manual override: 19Gwei instead of 20Gwei

http://etherscan.io/tx/0x00922be5ef22fa993a6fafaaa71719c2ce6a84d8b3517c0be39afc2c7d30e98b

* same as above

Edit: Got confirmed later, is on the chain!


### (5) retried original, just to exclude other reasons. Only change: 20Gwei again.

http://etherscan.io/tx/0x0529c370dd9349be39fafc4828a086d00eac8cf6be7756229620ccfa5cf1c300

ALSO NOTHING! Weird.

Edit: Got confirmed later, is on the chain!


### (6) switch on "Gas price Default 20 GWei"

http://etherscan.io/tx/0x7dacbd0163b385b0572a52ceee01c71d42bae7098555372c84d256d980015c6d

strange, very strange.

Edit: Got confirmed later, is on the chain!



**Restarting geth.**


### (7) Manual override: 10Gwei instead of 20Gwei

0x750fdc582c3effdab1279ecae56b8c9d44d2be233d9faab73b30aa93bd916c4b

Took a while, but yes, it worked. 

http://etherscan.io/tx/0x750fdc582c3effdab1279ecae56b8c9d44d2be233d9faab73b30aa93bd916c4b

To deploy has now cost 0.00064058 ETH = 0.0076 eurocent.


**Compare :-)**

    geth attach
    TheAnswer_Cheaper = web3.eth.contract([{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"inputs":[],"type":"constructor"}]).at("0x3ef712c51225734ecf0520d4a85e3e3a8396155f")
    TheAnswer_Cheaper.get()

Same same, but half as expensive.



### (8) Manual override: 5Gwei instead of 20Gwei
	
http://etherscan.io/tx/0x92b07bd4ed3d857101443c3a3243b36716b9eaff61b5a4372ba80b42490176ac

Took quite a while but I got it deployed!!!

    geth attach
    TheAnswer_Cheapest = web3.eth.contract([{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"inputs":[],"type":"constructor"}]).at("0xf3ba3aa63292800da8678cce32385d3bf17fd70f")
    TheAnswer_Cheapest.get()



### (9) Manual override: 3Gwei instead of 20Gwei

http://etherscan.io/tx/0x872baca27d9da3e776a9f5f10332a753afb3924fcae47cf6ad6c09e4a0ba49eb

nothing - yet.




## So, looks like

(a) Yes, I can deploy with 10Gwei or even 5Gwei instead of the 20Gwei `mix-ide` default.
(b) Transactions can disappear into nowhere, and without a trace. 
(c) Not even a block explorer knows them then. They are not [pending](http://etherscan.io/txsPending). But then they suddenly get confirmed.
(d) Perhaps the node default settings are censoring transaction broadcasting below a certain gas price? 
(e) The default 20 Gwei is also no guarantee that it will get deployed.
(f) There are too few error messages when something fails.
(g) Random restarting of 'geth' seems to just be a good idea.  "Have you tried switching it off and on again".



P.S.:


```
// Contract to check how cheap it can get. Careful:
// Took 'Deep Thought 7.5 million years to compute and check the answer'
//
contract TheAnswer
{
	function TheAnswer() { // This is funny: Switch on 'Display Gas Estimation' Ctrl-G -->  
	}
	function get() constant returns (uint) {
		return 42;
	}
}
```

Or simply ask http://fourfollow.com/home/supercomputer

**Comment by luclu** [comment]
Such a pitty that I already closed this one!
