### ISSUE TITLE
Crash when attempting to rename an imported contract wallet

### ISSUE THREAD

**Issue by Chris-Harbo** [ethereum/mist#87]
When renaming an imported wallet after entering the first character the Wallet freezes.and has to be shutdown and relaunched.

see attached screenshots for before and after

![screenshot 2015-12-15 00 49 34](https://cloud.githubusercontent.com/assets/12041783/11788979/66d4ccc0-a2c6-11e5-99da-7f96034a5be2.png)

![screenshot 2015-12-15 00 50 08](https://cloud.githubusercontent.com/assets/12041783/11788988/6980ab7e-a2c6-11e5-99e7-2773b0b2b19b.png)

Using Win7 and Ethereum-Wallet-win64-0-3-7

**Comment by luclu** [comment]
Fixed as of `0.8.1`.
