### ISSUE TITLE
Ethereum Wallet shows no balance even after transactions are completed

### ISSUE THREAD

**Issue by renwang1612** [ethereum/mist#872]
![ethereum wallet](https://cloud.githubusercontent.com/assets/14651235/16259719/f9f9de90-3831-11e6-86d0-5e9110a56744.png)

I have just set up my ethereum wallet on Windows 8, and after three transactions (two of which are using the Ethereum Wallet itself), I changed bitcoin into 10 ETH, and received nothing in the wallet. Is there a bug?

Thanks.

**Comment by MELCHEZEDEK776** [comment]
I've been having the same problem, in fact I lost 5 Ether yesterday using jaxx and shapeshift... Very Disappointing.

**Comment by renwang1612** [comment]
I asked around. If you go and check your wallet address using a block
explorer, you may see the true amount of coins inside. But in order to see
it in the wallet, it takes a 20GB sync.

On Wednesday, June 22, 2016, Christopher Ryan Butler <
notifications@github.com> wrote:

> I've been having the same problem, in fact I lost 5 Ether yesterday using
> jaxx and shapeshift... Very Disappointing.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ethereum/mist/issues/872#issuecomment-227680506>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AN-PY81w8b9XuaW28U0CbnVa3Bx353Y-ks5qOPXrgaJpZM4I7htL>
> .
>


-- 
Ren Wang

Graduate/PhD Student

Department of Electrical & Computer Engineering, Boston University
8 Saint Mary's Street, Boston, MA 02215
T (617)-987-7669

**Comment by luclu** [comment]
> But in order to see it in the wallet, it takes a 20GB sync.

That's right. During the next months the [light-client](https://github.com/zsfelfoldi/go-ethereum/wiki/Light-Ethereum-Subprotocol-(LES)) functionality will be added - thus you won't have to download a local replica of the chain.
