### ISSUE TITLE
Adding accounts does not work

### ISSUE THREAD

**Issue by debris** [ethereum/mist#873]
Node type: geth
OS: osx
Network type: main
Mist version: 0.7.4

Adding accounts does not work. After entering password twice, nothing happens

*edit. The same issue exists with presale wallets

**Comment by luclu** [comment]
@debris could you please check if keyfiles are getting created? Got to `menu -> accounts -> backups -> accounts`.

**Comment by frozeman** [comment]
It looks like the IPC connection breaks. Accounts should get added. Can you give more details? E.g. look in the console CMD + i ?

**Comment by debris** [comment]
> @debris could you please check if keyfiles are getting created? Got to menu -> accounts -> backups -> accounts.

Keyfiles are getting created. What's more. When I restart mist, all accounts are properly displayed.

> It looks like the IPC connection breaks. Accounts should get added. Can you give more details? E.g. look in the console CMD + i ?

Only the first line is suspicious, the rest looks fine.

```
file:///sockjs/info?cb=25_6jaijhd Failed to load resource: net::ERR_FILE_NOT_FOUND
/Users/marek/Downloads/Ethereum-Wallet-macosx-0-7-4/Ethereum-Wallet.app/Contents/Resources/app.asar…:17 Connect to node...
a43895c….js:318 startNode: 7.400ms
/Users/marek/Downloads/Ethereum-Wallet-macosx-0-7-4/Ethereum-Wallet.app/Contents/Resources/app.asar…:17 Node started syncing, stopping app operation
a43895c….js:401 renderAccountPage: 75.370ms
```

**Comment by luclu** [comment]
@debris I created a bug report for this here: https://github.com/ethereum/mist/issues/859. You can subscribe to that one if you like. 
I will close this as a duplicate.
