### ISSUE TITLE
Wrong Password in 0.7.5

### ISSUE THREAD

**Issue by gald89** [ethereum/mist#875]
Node type: geth
OS: windows
Network type: main
Mist version: 0.7.5

Attempting to transfer funds (using the 'Send All' option) from my private wallet always fails and shows up a 'Wrong Password' message even when the password is correct. This was attempted multiple times (closing and reopening mist each time).

Transaction worked perfectly when run immediately afterwards using Mist 0.5.2

**Comment by webdevotion** [comment]
Does your password contain special characters? 
I believe there was a problem in Mist in previous versions.
_( friend of mine had his wallet locked because of this )_

**Comment by luclu** [comment]
@gald89 this is a misleading error message. It pops up if you don't have enough funds in your etherbase account. I will close this and append it to this bug pool: https://github.com/ethereum/mist/issues/664.
