### ISSUE TITLE
Copy paste fails for Version 0.7.4

### ISSUE THREAD

**Issue by joshuad31** [ethereum/mist#877]
Node type: geth / mist wallet
OS: windows
Network type: main
Mist version: 0.7.4

When attempting to copy paste addresses a message pops up that clearly states "copied to clipboard" and another duplicate message also appears.  Address never copied to clipboard and pasting fails.

https://www.youtube.com/watch?v=zJuvzWKZOIw

**Comment by luclu** [comment]
This is fixed in `0.7.5` https://github.com/ethereum/mist/issues/650
