### ISSUE TITLE
wallet will not open now !

### ISSUE THREAD

**Issue by seot1** [ethereum/mist#879]
Node type: geth/eth
OS: win 10
Network type: ?
Mist version: geth64 0.9.17

very frustrating. wallet is unable to open now. i get the following error messages upon booting:

1st
![ether-wallet-prob0](https://cloud.githubusercontent.com/assets/20125496/16334375/630f3a4a-39b5-11e6-91b4-c1602503002d.png)

and then....
![ether-wallet-prob1](https://cloud.githubusercontent.com/assets/20125496/16334269/bc479798-39b4-11e6-8f29-2251f78770c2.png)

and then this pops up.
![ether-wallet-prob2](https://cloud.githubusercontent.com/assets/20125496/16334273/c4966dc0-39b4-11e6-8960-def0ee731571.png)

**Comment by luclu** [comment]
Hey @seot1 your geth version is nearly one year old and incompatible with the current network. Please update geth to `1.4.8` ([releases](https://github.com/ethereum/go-ethereum/releases)) and the Ethereum-Wallet to `0.7.5 ([releases](https://github.com/ethereum/mist/releases)).

**Comment by seot1** [comment]
thats so much for the response! do i simply just install over the current install?

**Comment by luclu** [comment]
Yes, you only need to delete your current Mist/geth folder/binary. Settings, accounts and the blockchain are stored under `%APPDATA%\Ethereum`. 
I advise you to delete the `%APPDATA%\Ethereum\chaindata` folder. A new complete sync will trigger geth's `--fast` option to considerably speed up the syncing.

**Comment by seot1** [comment]
Thanks, but please answer. I am at this page https://github.com/ethereum/mist/releases
I know to dload the wallet but I want to know if I will retain my SAME wallet address. I am very nervous of loosing my coin with this update. Please help me. I will even pay you..

**Comment by luclu** [comment]
Open your file browser and go to this address: `%APPDATA%\Ethereum`.
This is the config folder for your node. It contains a folder called `keystore` - this is were all your accounts are saved. You should backup those files.
Alternatively you can open the Ethereum-Wallet and go to `menu -> accounts -> backup -> accounts`.

The application folder with the `Ethereum-Wallet.exe` is exchangable - you can delete it or download newer versions any time - without beeing too careful. ;)

**Comment by seot1** [comment]
i can't use the alternative method because my wallet wont even open!
i can't even find the %APPDATA%\Ethereum... i'm using win10. please help me....

please tell me how to do this in win10. as i said before i'll pay you. i'll pay anyone that knows how to do this.

this is crazy. i dload a wallet and it doesn't work after a short period of time for no fault of my own. no easy want to update the wallet? omg

**Comment by seot1** [comment]
an i just save the keystone folder?? i read this somewhere on the net.

i want to preserve my same ether address. very important because i have dao's associated with my ether address. thanks
