### ISSUE TITLE
watch token and watch contracts disappear

### ISSUE THREAD

**Issue by bvris** [ethereum/mist#886]
Node type: geth/eth
OS: windows 10 64bit
Network type: main
Mist version: 0.7.5 and 0.7.6, 64bit

Both custom token (The DAO) and watch contract (The DAO) disappear when i restart the program. I add and it shows up fine but when i restart the program - everything is gone and need to create token and contract again.

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment]
This is a known issue: https://github.com/ethereum/mist/issues/844
But, does this happen every single time to you?

**Comment by bvris** [comment]
Yes, every single time.

**Comment by luclu** [comment]
Please append the issue #844 with that information:
> Both custom token (The DAO) and watch contract (The DAO) disappear **every time** I restart the program. I add and it shows up fine but when i restart the program - everything is gone and need to create token and contract again.

I will close this to keep duplicates low and have all information at one single place.
