### ISSUE TITLE
Developer Tools operate on their own hidden copy of the dapp page, instead of the displayed copy

### ISSUE THREAD

**Issue by interfect** [ethereum/mist#89]
I'm trying to develop the frontend for a dapp with the Mist 0.3.6 browser. I'm browsing to a file:// URL which has my app's page, which I'm editing and re-loading to test my changes.

I think that Mist is running two separate copies of my dapp page: one in the actual browser, and one in the Developer Tools:
- I've added some code to my page that prints out the same random number to both the page and the console on page load. When I open developer tools, the number displayed in the console there is different than the one on the page.
- Deleting or modifying elements from the element inspector in the developer tools does not affect the running page.
- Trying to change element contents from the Javascript console does not affect the running page.
- The Mist refresh button in the address bar and the Reload option in the right-click menu do not appear to re-load the running page. Changes made to my file on disk are not reflected in the page I see in front of me, and the on-load logic doesn't run. Instead, the invisible page used by the Developer Tools is re-loaded, and new console output is printed there.

Unfortunately, this situation makes the Developer Tools somewhat useless, because I can't use them to interrogate or debug the page I am actually looking at.

**Comment by interfect** [comment]
Workaround: Use the little "+" button to add the dapp to Mist. This problem only seems to occur in the "Browse" mode on the left side.

Another symptom of the problem is that the page version of the dapp can't see web3.eth.accounts[0], even when the account is turned on for the dapp, while the Developer Tools version can.

**Comment by frozeman** [comment]
Thanks, will look at it after my holidays.

**Comment by evertonfraga** [comment]
I don't believe this is an issue anymore.
