### ISSUE TITLE
Missing Ether

### ISSUE THREAD

**Issue by rdonnelly236** [ethereum/mist#890]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by rdonnelly236** [comment]
I setup an ethereal/mist account because I read that it is safer than leaving eth in an exchange. I have 2 wallets, a contract wallet and a main account. I tried several times to transfer the 158 ether from from my contract wallet to the main account. Suddenly they disappeared. Now I have 0 in my contract account. I cannot get any help from anybody.

**Comment by luclu** [comment]
Please provide the addresses in question.

**Comment by rdonnelly236** [comment]
Hello Luca,

I greatly, greatly appreciate you getting back to me and looking into this for me. The contract wallet, named rdonnelly236, has the number:

0x26163e12F20652102ED4462adE3631b53De5dBf

The main account has the number:

0xD8B52fbb9C260bCA6D49111A3E4A53FAf0379fB3

 Please let me know if you need any additional information.

Gratefully,

Rick

**Comment by luclu** [comment]
@rdonnelly236 you are welcome.
What version of the wallet are you using?

The provided contract wallet address `0x26163e12F20652102ED4462adE3631b53De5dBf` does not seem to be a valid address: http://etherscan.io/address/0x26163e12F20652102ED4462adE3631b53De5dBf

**Comment by rdonnelly236** [comment]
I forgot a number. Here is the correct number:

0x26163e12F240652102ED4462adE3631b53De5dBf

I am using the version 0.7.4

**Comment by luclu** [comment]
Looking at the [internal](http://etherscan.io/address/0x26163e12F240652102ED4462adE3631b53De5dBf#internaltx) (contract transactions), the 158.26000005 Ether was send to the address [0x4ebc33d06bfd0a8c24450b659d69b445f854f76b](http://etherscan.io/address/0x4ebc33d06bfd0a8c24450b659d69b445f854f76b).

**Comment by rdonnelly236** [comment]
Many, many thanks for researching this for me. I really appreciat it……Rick Donnelly

**Comment by luclu** [comment]
> Looking at the [internal](http://etherscan.io/address/0x26163e12F240652102ED4462adE3631b53De5dBf#internaltx) (contract) transactions, the 158.26000005 Ether was send to the address [0x4ebc33d06bfd0a8c24450b659d69b445f854f76b](http://etherscan.io/address/0x4ebc33d06bfd0a8c24450b659d69b445f854f76b).

Unfortunately the Ether might be lost if you don't have ownership over that account's private key.

I will close this for now.

**Comment by rpfly** [comment]
Hi @luclu - I am having this same issue after installing Mist application. I made no transfers. But ETH is no longer found in my Mist or Ether Wallet.

Kind Regards if you're able to help.

Thanks!
