### ISSUE TITLE
Ether sends to random address? Mist wallet looses Ether.

### ISSUE THREAD

**Issue by WireGhost** [ethereum/mist#898]
Tried transferring from Mist wallet to Jaxx and it sent to a random address. Don't know what to do, very disappointed in the Mist wallet. Instead of sending to the address of my other wallet, it sent to completely different one. How does this happen? Transaction was to be from 0x5ef47dd109c02c3264f16efa93a2512b48b0e9e4 to 0x649DC0330f27235DCb5835b92711510cB1Ff7e9, but it ended up sending to 0xe16171A65715841DF329a582A5DfFA17f900aC8d and tracing the transaction (0x16644ce4c8dad700252c74d24cc5fb67071d9fc95b50a8a73d736f6e12e3aa38) shows sent to that address."Jun
26
Sent
Account 2 ? 0xe16171A65715841DF329a582A5DfFA17f900aC8d
2 hours ago -9.99474 ETHER " Have no way of requesting or reversing or even figuring out why the address changed to something totally different. Signed up at Etherscape.io to watch that address, try to see if I could contact that address, or anything but no dice. Don't have or know that address, and exactly how that went from sending from 0x5e to 0x649..to an 0xe16..address. . Lost 9.994 ETH. Is this a bug?
Listed the from to address's, transaction #. On OSX Mavericks Mist stopped syncing, so I started a mist wallet on a Windows 10 PC. Works, or thought it did. When I copied pasted my send to address it went through sending, then I noticed I wasn't receiving. The pasted address was my correct "to" one, as I have nothing that even remotely resembles the other address. I don't do my BTC on that PC. Version of Wallet is Win64 0-7-2. Was hoping it was just a transaction # or something, but it's been over an hour, the transaction is closing on 500 confirmations. Just shows my account now empty from the send. Scary. Not sure how to stop, attack chain transaction or attempt to reverse this.Not sure why it would accept and randomize on lack of quote to a totally diff address, though. I see the the TX on Etherscan: and as time passes, it seems lost. With "no error's", I don't get it. I don't trust it. It's a bit disheartening. The to: contract: 0xe16171a65715841df329a582a5dffa17f900ac8d nowhere to be found in the entirety of the W10 root C:\ directory, even when searched "0xe1617". Above was from what looks like a cli, but through the gui it accepted and actually sent, to whom, I don't know.
TxHash: 0x16644ce4c8dad700252c74d24cc5fb67071d9fc95b50a8a73d736f6e12e3aa38
Block Height: 1776253 (819 block confirmations)
TimeStamp : 3 hrs 16 mins ago (6/26/2016 6:14:16 PM)
From: 0x5ef47dd109c02c3264f16efa93a2512b48b0e9e4
To: Contract 0xe16171a65715841df329a582a5dffa17f900ac8d
No errors detected during contract execution
Value: 9.99474 Ether ($137.83)
Gas: 21000
Gas Price: 0.00000002 Ether
Gas Used By Transaction: 21000
Actual Tx Cost/Fee: 0.00042 Ether ($0.01)
Cumulative Gas Used: 320778
Nonce: 2
Input Data: 0x

6/27
Still stuck here. Any ideas? I'm going through all the files, keystores, trying to find this address. Keep coming up with nothing remotely close. Have no clue what could have happened. Would try to replace the Ether, but what if it happens again? What to do that could have possibly prevented? Is it a bug? Seriously confused and seems a bit shady. So, why after 10 years of BTC with no incidents at all, does two months of ETH on a mist wallet immediately dump all the Ether into, well "Ether". Pardon the pun.

“MaximoMax commented 4 minutes ago
Could you please move to a different thread? This one is about not being able to send at all, not about ethers being sent to unknown addresses.
(Sorry to hear that, though..)”

So, as requested, I transferred to a different thread. I'm still trying to figure this out and recover the transaction or get some sort of insight/advice. Previous issue was posted here: https://github.com/ethereum/mist/issues/367#issuecomment-228617539

Would appreciate any help or advice. I would like to add Ether, but now I'm a bit freaked out. Sorry for hogging the previous issue 367. The wallet would not send "ethers" .  If you check the Blockchain, it'll show it. The one time it does though, it goes to some completely random address not at all associated with the local mist wallet. Real bummer. Sketchy.

**Comment by luclu** [comment]
As this conversation was moved I will copy the past posts here.

---

> Tried transferring from Mist wallet to Jaxx and it sent to a random address. Don't know what to do, very disappointed in the Mist wallet. Instead of sending to the address of my other wallet, it sent to completely different one. How does this happen? Transaction was to be from 0x5ef47dd109c02c3264f16efa93a2512b48b0e9e4 to 0x649DC0330f27235DCb5835b92711510cB1Ff7e9, but it ended up sending to 0xe16171A65715841DF329a582A5DfFA17f900aC8d and tracing the transaction (0x16644ce4c8dad700252c74d24cc5fb67071d9fc95b50a8a73d736f6e12e3aa38) shows sent to that address."Jun
26
Sent
Account 2 ? 0xe16171A65715841DF329a582A5DfFA17f900aC8d
2 hours ago -9.99474 ETHER " Have no way of requesting or reversing or even figuring out why the address changed to something totally different. Signed up at Etherscape.io to watch that address, try to see if I could contact that address, or anything but no dice. Don't have or know that address, and exactly how that went from sending from 0x5e to 0x649..to an 0xe16..address. . Lost 9.994 ETH. Is this a bug? 

@WireGhost could you please update your post to be more detailed (versions used, addresses in question, step to reproduce)?

> Listed the from to address's, transaction #. On OSX Mavericks Mist stopped syncing, so I started a mist wallet on a Windows 10 PC. Works, or thought it did. When I copied pasted my send to address it went through sending, then I noticed I wasn't receiving. The pasted address was my correct "to" one, as I have nothing that even remotely resembles the other address. I don't do my BTC on that PC. Version of Wallet is Win64 0-7-2. Was hoping it was just a transaction # or something, but it's been over an hour, the transaction is closing on 500 confirmations. Just shows my account now empty from the send. Scary. Not sure how to stop, attack chain transaction or attempt to reverse this. 

Are you in control of [0xe16171A65715841DF329a582A5DfFA17f900aC8d](http://etherscan.io/address/0xe16171A65715841DF329a582A5DfFA17f900aC8d)?
You might copied the wrong address or your copy command didn't pick the new selection, so the old one stayed in the clipboard?

> No, I'm not in control of that address, I have no "0xe" address on ETH. The copy and paste was a copy and paste from my notepad with only the  0x649DC0330f27235DCb5835b92711510cB1Ff7e9 address. Did find this which alarms me: https://forum.ethereum.org/discussion/4743/eth-sent-to-wrong-address-how-1-eth-reward

> Did find this which alarms me: https://forum.ethereum.org/discussion/4743/eth-sent-to-wrong-address-how-1-eth-reward

Hmm, this was due to some wrong code of the user. He forgot the quotation mark on the address:
```javascript
eth.sendTransaction({from:eth.coinbase, to:eth.accounts[0x7efd7bafbad1817f6c7a2017bd6acbcb634ad058], value: web3.toWei(14, "ether")})
```
So `eth.accounts[0x7efd7bafbad1817f6c7a2017bd6acbcb634ad058]` used account number zero as `eth.accounts[0]`.

> Not sure why it would accept and randomize on lack of quote to a totally diff address, though. I see the the TX on Etherscan: and as time passes, it seems lost. With "no error's", I don't get it. I don't trust it. It's a bit disheartening. The to: contract: 0xe16171a65715841df329a582a5dffa17f900ac8d nowhere to be found in the entirety of the W10 root C:\ directory, even when searched "0xe1617". Above was from what looks like a cli, but through the gui it accepted and actually sent, to whom, I don't know. 

TxHash:	0x16644ce4c8dad700252c74d24cc5fb67071d9fc95b50a8a73d736f6e12e3aa38
  Block Height:	1776253 (819 block confirmations)
  TimeStamp :	3 hrs 16 mins ago (6/26/2016 6:14:16 PM)
  From:	0x5ef47dd109c02c3264f16efa93a2512b48b0e9e4
  To:	Contract 0xe16171a65715841df329a582a5dffa17f900ac8d
 No errors detected during contract execution
  Value:	9.99474 Ether ($137.83)
  Gas:	21000
  Gas Price:	0.00000002 Ether
  Gas Used By Transaction:	21000
  Actual Tx Cost/Fee:	0.00042 Ether ($0.01)
  Cumulative Gas Used:	320778
  Nonce:	2
  Input Data:	0x

> Still stuck here. Any ideas? I'm going through all the files, keystores, trying to find this address. Keep coming up with nothing.

**Comment by WireGhost** [comment]
Sorry about the "hijacking", it started under the premise of not sending, and I just found that thread.

**Comment by luclu** [comment]
No worries about that. ;) 
Did you solve this? I haven't really dived into this yet..

**Comment by WireGhost** [comment]
No, unfortunately I did not solve, I'm just getting a bit overly frustrated over something I cannot figure out. It's been distracting me from work and other projects. Don't want to waste everyone else's time as well, for what seems to be an issue only I've experienced. Appreciate everyone's time.

**Comment by WireGhost** [comment]
Quick question, does Mist have a Private Key or Seed? On Live.ether.camp, it is showing the following option. "Transfer Balance
Transfer balance to a third party
Receiver

Value

Private Key

Hide characters as you type:

**Comment by luclu** [comment]
Not sure what you mean, could you please include a link or even better a screenshot?

**Comment by WireGhost** [comment]
On https://live.ether.camp/account/e16171A65715841DF329a582A5DfFA17f900aC8d under Transfer Balance,(at top right) it gives an option window with address for receiver, Value, and Private Key, seed or Hash. Not sure why. But wondering if there's a private key. Tried from text format of keystone back-ups, but none show valid
