### ISSUE TITLE
Node type (geth/eth) cannot be changed during blockchain sync

### ISSUE THREAD

**Issue by jldinh** [ethereum/mist#90]
I fully synced my geth node, then switched to the eth node for a try.
After restarting the wallet, it is now stuck syncing the eth node (which does not seem to be using the already downloaded blockchain), and there is no option to switch back to geth.
Therefore, the wallet is unusable until the eth sync completes, which is not very user-friendly.

**Comment by frozeman** [comment]
`eth` and `geth` are two implementations of an ethereum full node, one in c++ and one in go. They aren't using the same database nor data structure.

You have to decide which node you want to use and stick with it. They both have also their own key store.

Switching nodes, is only for the advanced user. `geth` is fully tested, `eth` not so much yet.

**Comment by jldinh** [comment]
I understand, but it would be nice to be able to change the node type
without having to wait for a full sync of the default node. This would save
time, disk space and bandwidth.
As far as I can see, it is not possible currently.

**Comment by frozeman** [comment]
sure would be nice, but it would mean that we rewrite two full nodes completely. Want to wait a year? :)

**Comment by jldinh** [comment]
I wasn't suggesting modifying the nodes, just making the geth/eth toggle in the wallet accessible while it is waiting for the node to sync in the background. Currently the toggle is only accessible once the main window has opened (i.e.: after the node is synced), so if you want to use eth, you need to sync a geth node for nothing, before you are allowed to switch to eth.

**Comment by frozeman** [comment]
This is already the case in the latest develop
