### ISSUE TITLE
IPS blocking inbound trojan connections to MIST client

### ISSUE THREAD

**Issue by ethereumtesting** [ethereum/mist#900]
client 0.7.5

"MALWARE-CNC Win.Trojan.Gigade variant inbound connection attempt" [Impact: Vulnerable] From "redacted" tcp} 1.34.187.138:30303 (taiwan republic of china)->

cross post: http://ethereum.stackexchange.com/questions/6579/ips-blocks-malware-cnc-trojans-on-mist-0-7-5

**Comment by luclu** [comment]
What is the software / IPS-portal? that is notifying you on this?

Please look at https://github.com/ethereum/mist/issues/573. Some user of the network uploaded chunks of malware to the blockchain through the transaction data. This gets picked up by several AVs. We recommend to add exceptions to the `chaindata` folder.

**Comment by ethereumtesting** [comment]
I've seen the IPS block numerous inbound connections....

**It is snort rule:**  
https://www.snort.org/rule_docs/1-31123

**within the IPS the rule looks like this:**
alert tcp $EXTERNAL_NET [1024:] -> $HOME_NET any (msg:"MALWARE-CNC Win.Trojan.Gigade variant inbound connection attempt"; flow:to_client,established,no_stream; content:"x"; depth:1; dsize:2<>4; pcre:"/^x\d{1,3}$/"; metadata:impact_flag red; reference:url,virustotal.com/en/file/5cb874e5ef2a8613123284b66e9fb51387a14528b50e4a9aac4fd613dfc9bc1a/analysis/; classtype:trojan-activity; sid:31123; rev:2; )

**Comment by luclu** [comment]
Ah Ok. Don't worry about it to much. It is harmless. It is more like trolling the blockchain. ;)
We are investigating a different decoding in the mid-term future to stop this all together from popping up.
