### ISSUE TITLE
Mist stalls during Test/Main toggle

### ISSUE THREAD

**Issue by agnewpickens** [ethereum/mist#902]
Node type: geth 1.4.8
windows 7 64
Network type: main/test
Mist version: 0.7.6

After about two hours of running 0.7.6 with Geth 1.4.8, I experienced a complete stall toggling from Test to Main.  I shut down 0.7.6 to launch Geth 1.4.8 by itself so I could toggle to Main. I noticed that after shutdown of 0.7.6, there were still instances of Electron running in my task manager.  Upon trying to relaunch 0.7.6, I got an error connecting to node and my Win 7 completely locked up on me.  I have since reverted to 0.7.4 with geth 1.4.6 and my Mist is syncing, albeit slowly.

**Comment by luclu** [comment]
Could you please launch the wallet via the terminal to see any unusual logs? 
Also are you at that moment of the stall still able to open the console with `CTRL+ALT+i`?

**Comment by agnewpickens** [comment]
How do I launch Mist from terminal on Win 7?  Do I change directory to the Eth folder and what command do I use?  I have opened Geth 1.4.8 from taskbar and launched 0.7.6 Mist the regular way and it seems to work OK now.  I had put Geth 1.4.8 in the wallet folder, apparently that wasn't enough, it is syncing now, but it looks like 0.7.6 won't connect to node unless I launch Geth first.  Mist 0.7.4 with Geth 1.4.6 doesn't behave that way for me.  It launches with just the Geth added to the wallet folder.

**Comment by agnewpickens** [comment]
If I open Geth before launching Mist, I am completely unable to toggle to Test, I will let this sync for a while and see if I can get into Test, right now I am unable to toggle over to Test.

**Comment by agnewpickens** [comment]
I used ctrl+shift+2 keyboard control and checkmark is next to Test, but Mist is not toggling over, so toggling issue is still there.

**Comment by luclu** [comment]
>If I open Geth before launching Mist, I am completely unable to toggle to Test [...]

This is normal behaviour as the wallet does not control geth if it only connected to it.

**Comment by agnewpickens** [comment]
Then there is still no way to get to Test using the Mist 0.7.6 Wallet with Geth 1.4.9, if I launch Geth first, it will not toggle to Test at all and if I do not launch Geth first, I now get a node connection error.

**Comment by agnewpickens** [comment]
Will try 0.8.0 and see if I have better luck there, the last two Mist releases have not worked on my Windows 7.  I am still using 0.7.4.
