### ISSUE TITLE
0.7.6 wallet smart contracts don't refresh

### ISSUE THREAD

**Issue by jamespotkukelkka** [ethereum/mist#906]
Node type: geth/eth
OS: windows 10
Network type:/test
Mist version: 0.7.6
0.7.6 wallet smart contracts don't refresh. When I go away from contract and come back, contracts UI refreshes but it does not refresh otherwise.

**Comment by luclu** [comment]
@jamespotkukelkka I can't quite follow you. What do you mean by "[smart] contracts don't refresh"?

**Comment by luclu** [comment]
Closed as of inactivity.
