### ISSUE TITLE
Can't debug any source code

### ISSUE THREAD

**Issue by lucasansei** [ethereum/mist#913]
Node type: geth
OS: ubuntu 14.04
Network type: test
Mist version: 0.7.6.

I'm trying to deploy a blockchain organization following this tutorial: https://ethereum.org/dao#the-code however all I get is "Could not compile source code" and "Error: e.message.replace is not a function". And this happens in every single source code I try to deploy.
Screenshot: http://imgur.com/OU0U369
Screenshot console: http://imgur.com/Xb0veTG

Log:
[log.zip](https://github.com/ethereum/mist/files/341581/log.zip)

**Comment by luclu** [comment]
Thank you for reporting.

Currently the top line slipped out of the code's id. 
```javascript
 contract owned { address public owner;
```
This is fixed in https://github.com/ethereum/ethereum-org/pull/271.
