### ISSUE TITLE
unlockAccountAndSendTransaction

### ISSUE THREAD

**Issue by zikilemini** [ethereum/mist#916]
Hello,
I am working on a Dapp which should work in a browser i was asking myself how to unlock acounts in order to send transactions.

I saw there is few usefull methods in web3.personal but the one you use web3.personal.unlockAccountAndSendTransaction seems to not exist in my web3 object i i never seen it before.

How and why you can use this ? Can i somehow use it too to secure my Dapp ?

**Comment by luclu** [comment]
Make sure to update to the latest version of [web3.js](https://www.npmjs.com/package/web3) -> `npm update --save web3`.
Also feel free to join the developer chat to receive answers for those kind of questions way faster: https://gitter.im/ethereum/web3.js
