### ISSUE TITLE
Suggestions for Mist developer

### ISSUE THREAD

**Issue by greggdourgarian** [ethereum/mist#919]
1.   TestNet account copy-to-clipboard warning relaxation.   When on TestNet, an attempt to copy to the clipboard an account number generates a warning message about not sending real Ether.  While this is fine for a first attempt, it's quite a pain if you are coding and are constantly copying addresses to the clipboard.   Provide a checkbox 'Do not show this message again' which if the user checks causes the prompt to no longer appear.

2.   Easier account copy-to-clipboard.   Throughout Mist, wherever possible, provide an small copy icon by account numbers so that they can be easily copied to the clipboard.  Currently, it can be quite a hassle as there are few places where you can actually do a copy.

3.  Display contract data more flexibly.   Provide bulk hex display of contract data.  Provide hex display of individual fields. 

4.  Display account number as well as name.  When showing an account name, it's often very helpful to see the account number as well.

**Comment by luclu** [comment]
Thank you @greggdourgarian for those valuable suggestions!

Could you kindly modularize those into their own issues on the https://github.com/ethereum/meteor-dapp-wallet/issues repo?

**Comment by greggdourgarian** [comment]
will do, tx
