### ISSUE TITLE
Confusing message when importing wallet

### ISSUE THREAD

**Issue by paulmorriss** [ethereum/mist#92]
I created a wallet in one version of the Wallet application and then downloaded version 0.3.7. In order to move the one simple wallet I'd created from the previous version I created a new wallet and chose Import wallet option. It says "Import an existing (multisignature) wallet". However it appeared to import my simple wallet correction - certainly the balance was what I'd expect, though the name had gone. In fact can this option be used to import simple wallets too? In which case the message is misleading. If it can't import simple ones then it should have failed when I tried to.

**Comment by molecular** [comment]
sounds like a problem with the semantics of the parantheses in "Import an existing (multisignature) wallet". Guessing they are supposed to mean "_also_ multisignature" and the feature _can_ in fact import simple wallets.

Just chipping in to say I stumbled across this point, too.

**Comment by frozeman** [comment]
We can definitely improve that text

**Comment by luclu** [comment]
The whole process got improved in current versions!
