### ISSUE TITLE
'Internal error opening backing store for indexedDB.open.'

### ISSUE THREAD

**Issue by brunoamancio** [ethereum/mist#925]
**Node type:** geth
**OS:** windows
**Network type:** main
**Mist version:** 0.7.6

I mined for some time to test the ethereum wallet, now I have 1.04 ETH. I sent it to another address and it displays some errors. I think it might interest somebody around here.. =)

**\- Screenshots**
![misty_error](https://cloud.githubusercontent.com/assets/3150473/16600510/bb59fdf6-4307-11e6-9460-9fd1785f9db4.png)

![misty_error2](https://cloud.githubusercontent.com/assets/3150473/16600795/44c81cd4-4309-11e6-90f0-89191e7d2797.png)

I press SEND, type the password and it stays like the image below for sometime.

![misty_error3](https://cloud.githubusercontent.com/assets/3150473/16600929/ee2165a6-4309-11e6-85e0-a7e701ca81ed.png)

Then >>>

![misty_error4](https://cloud.githubusercontent.com/assets/3150473/16600931/f0468744-4309-11e6-8fcc-49dc8ef715d4.png)

After some time, it works, but the failures are there:

![misty_error5](https://cloud.githubusercontent.com/assets/3150473/16601016/6b701174-430a-11e6-8b20-552c22d9826f.png)

**\- Log files** (as ZIP archive)
[Logs.zip](https://github.com/ethereum/mist/files/348673/Logs.zip)

**\-   windows:** %APPDATA%/Roaming/Mist/node.log
[Node.zip](https://github.com/ethereum/mist/files/348681/Node.zip)

**Comment by luclu** [comment]
Could you please check via `console -> resources -> IndexedDB` about how many items it contains.
If there are > 1000 this might be related to this DB running out of space.

**Comment by JohnAllen** [comment]
In Chrome it's: 

- Open dev tools
- Click Application
- Look for Storage & IndexedDB
- Highlight each item there
- They allow you to delete them

Worked for me 👍
