### ISSUE TITLE
Create a wallet contract with ethereum but password doesn't work

### ISSUE THREAD

**Issue by ilyesbd** [ethereum/mist#926]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

---

Hello, 

I am trying to create a wallet on ethereum app but when I try to conduct my first transaction, it asks me for a password that i don't have...it keeps on saying that the password is incorrect.

is it a common issue? or where do I generate a password?

I have tried the password I have registered with and it wouldn't work either.

Thanks,

Ilyes

**Comment by luclu** [comment]
@ilyesbd could you please check if you have the same account multiple times in your `keystore`? You might be affected by this issue https://github.com/ethereum/mist/issues/780.

**Comment by luclu** [comment]
This is most likely related to  #664.
Could you please check if you have enough Ether in your first account (etherbase)?

**Comment by luclu** [comment]
Could you please have a try with `0.8.1` and post its error?

**Comment by evertonfraga** [comment]
Closing upon inactivity. Please reopen if needed.
