### ISSUE TITLE
Usability issues (getting started): can't receive eth

### ISSUE THREAD

**Issue by molecular** [ethereum/mist#93]
I'm sorry if this is the wrong place for user issues, but I don't know where else to go.

Let me describe my problems as an "average user" on getting started.

Firstly (after starting mist and waiting for it to sync) I made an account (basically the only option) and then tried sending eth to the account address (hex). Only later did I see the message "Your stub contract has no original wallet address set, please restart your wallet!" Gladly I hadn't confirmed the withdraw on the exchange yet (and it was a small amount).

That's has been very confusing so far and even made me a little anxious: why display an "address" (hex string) below something called "Etherbase, 0.00 ETHER" that cannot be used for receiving eth?!?

Secondly, when trying to "create a wallet" as instructed, I ran into #68. Which I worked around by running geth seperately, then restarting mist (I'm very proud as an "average user" to being able to figure that one out).

Next, after entering wallet name, selecting "Etherbase - 0.00 ETHER" as owner (so that's some kind of an identity, I guess?) and "simple wallet" I can finally see the "Create contract" page with a contract. What confuses me here is that it seems to cost money to create a contract (makes sense), yet I need to create a contract to be able to receive money. Unsure wether this will work or not I enter my password. Unfortunately the "create contract" page simply remains open and just sits there as if I had done nothing. There is no feedback whatsoever. I'm not even sure I entered the correct password, let alone what to do now. Gladly I see "Confirmed Transaction" on the terminal I started the wallet from, so at least now I'm confident I have entered the correct passphrase.

Since nothing else happens for what seems like a long time, I decide to restart the wallet (this time again without geth) and retry the whole process. Weirdly, #68 doesn't happen. After doing the "create wallet" process about 5 times (and then either hitting "cancel" or restarting the wallet) I can now see "my test wallet" in "Wallet Overview". yay! It says it's "being created". So I'll just wait.

I'm basically left hanging now, really unsure about things. My best guess is that I'm waiting for a generous miner to mine my wallet creation contract for no fee.

Again: sorry for making an issue about this since it's probably just me not understanding things, but maybe this report can help make mist better for the "average user"

EDIT: addendum: To see wether my new wallet (being "created") would persist, I restarted mist. Aaaaaand, it's gone. Tried creating another one and now I'm getting a red popup box saying: "Account does not exist or account balance too low". Why does the same action lead to different results and more importantly, how can I create a wallet? 

I'm left even more confused now.

**Comment by frozeman** [comment]
You can simply receive money in you ether base account, no need to create a wallet contract here. Additionally you need ether in your account to create a wallet contract. The advantage of the contract is mainly that you can see incoming transactions (and have multisig), which on accounts you will only see the balance change.

**Comment by molecular** [comment]
Can you explain what "please create a wallet to store ether" is supposed to tell me, then?

![image](https://cloud.githubusercontent.com/assets/589745/11913287/5d4de10e-a65f-11e5-8cfe-e1bcc6d1453b.png)

**Comment by frozeman** [comment]
This is the second part of the sentence, the first one explains why. But we can do definitely better here. @alexvandesande want to improve the texts in the wallet?

**Comment by molecular** [comment]
yes, please make clear that it's possible to receive ether with the "base account". The sentence is misleading as is. Thank you!

**Comment by cryptocool** [comment]
You clowns still haven`t fixed the wording? Version 0.5.2
Accounts can't display incoming transactions, but hold and send ether. To see incoming transactions create a wallet contract to store ether.
To english speaking users this is confusing ... create a wallet to store ether?
How can the wallet know the balance if the transactions are not accounted for?
Teenage developers, what can I say?

**Comment by alexvandesande** [comment]
@cryptocool the current wording is "Accounts are password protected keys that can hold ether, secure ethereum-based tokens or coins and control contracts. Accounts can't display incoming transactions."

Feel free to make an actual contribution instead of calling out names.

**Comment by WebEpic** [comment]
How about: 

```Accounts can't display incoming transactions, but can **receive**, hold and send ether. To see incoming transactions create a wallet contract to store ether.```

**Comment by nishimurablades** [comment]
Hi, I have a similar problem i have sent ether to the etherbase account twice using shapeshiter and once using zerogox, my wallet is sitting on 144 blocks 77%. It has been sitting around this amount for the last 2 days. Can anyone help me uderstand why I dont seem to receive the ether?

**Comment by samredway** [comment]
I'm still a little confused (the wording is not at all clear and the current wording I have in my Ethereum wallet is: "Accounts can't display incoming transactions, but hold and send ether. To see incoming transactions create a wallet contract to store ether.")
Anyway I went to the testnet and though I'd just try experimenting.
I created an account and did some mining then I created a second account. I transferred ether from one to the other ... It shows that there is a transaction but in neither wallet has the balance changed to reflect the transaction. So I'm not really sure what is going on. 
Surely I could expect that if I send ether from one account to another I should expect the ethereum in the one wallet to decrease and a proportionate (excepting the fee) increase in the other?

**Comment by alexvandesande** [comment]
@samredway the balance should definitely update. Are you synced up? Does restarting mist solve it?

**Comment by srmojuze** [comment]
Hi, it would be great to change the message to "Accounts can't display incoming transactions, but **can receive**, hold and send ether. To see incoming transactions create a wallet contract to store ether." Thanks.

**Comment by DustinWehr** [comment]
Agree with @srmojuze and @WebEpic suggestion. It's confusing and anxiety producing as is.

**Comment by luclu** [comment]
@srmojuze I created a PR at https://github.com/ethereum/meteor-dapp-wallet/pull/372

**Comment by molecular** [comment]
The wording from @luclu PR is much clearer, however I'm still confused on one point regarding receiving ETH using an account: does the money magically appear or what does "cannot see incoming transactions" mean? Will there be no visible record with a date saying *when* the money arrived? Certainly there has to be some kind of transaction on the blockchain? Why can I not see where / when / how the money arrived?

**Comment by FreddDagg** [comment]
Agree with @molecular - How is "Incoming" defined? Is it by confirmations?
At what point is a transaction no longer 'incoming' and then magically appears in the account?
Why not put the most important info first (what it can do), then the exception, lastly the alternative. 

"**Accounts can receive, hold and send Ether**, but won't display incoming transactions until they are fully confirmed. To see incoming transactions, create a wallet contract to store Ether."

**Comment by Fcases** [comment]
so with eth at this price it means you need 165$ to see incoming trx ?

**Comment by cgruber** [comment]
Yeah - this seems like a fairly hard-to-understand limitation on simple (non-contract) accounts.  Especially given that I can trivially plug in an account to https://etherscan.io and see a transaction list, but I can't in the core wallet?  Somewhere above it said "the first sentence explains why" but I would argue with that.  The first sentence explains _that_ you can't see txn in a non-contract wallet, not why.  What is the underlying reason for not having even a simple transaction list accessible for a given non-contract account? It seems ludicrous that I should have to go to a blockchain browser for this.

**Comment by frozeman** [comment]
There is no RPC method for querying transactions to an account. Ethereum is not build that way. And there were lengthy discussion about in the go-ethereum repo.
The reasons etherscan can do that, is that they execute every block and store that data in their now database, a local running dapp can't do that.

**Comment by frozeman** [comment]
And we will most likely switch to wallet as library again, so that deploying the wallet will be cheaper.
The price is rising faster, than we can adopt, sorry.

**Comment by molecular** [comment]
thanks @frozeman. Finally a plausible explanation for the state of things. It's still weird and hard to understand for a newbie, but at least I know there's a valid technical reason for how things are. It's much easier to accept now. Thanks for clearing that up.
