### ISSUE TITLE
Transactions fail without displaying errors

### ISSUE THREAD

**Issue by baobabKoodaa** [ethereum/mist#931]
Node type: geth
OS: windows
Network type: main
Mist Wallet 0.7.6 (Beta 20)

When I try to make transactions, they show up for about 5 minutes in the transaction list with 0 confirmations. Then they just disappear completely with no notification about what happened. I think the user should get some kind of notification when a transaction fails. I don't think it's good practice for transactions to simply disappear from a financial application.

Also, I would like to transfer some Ether.

I am connected to the network and "current block" is constantly either the same as the one on Etherscan or 1 ahead of it.

I tried restarting the Wallet app multiple times.

There is nothing interesting in JavaScript console or in the log file.

My transactions don't show up in Etherscan.

EDIT: After waiting several hours I used MyEtherWallet.com to make a transaction from the same account. When I did that, all of my earlier transaction attempts IMMEDIATELY executed (the ones that I thought were dead and wouldn't show up anywhere). For example, this link would say "no transaction found" or something like that: http://etherscan.io/tx/0x868070755694137ef8ce0c3fcab1bcffd152ec33c1240feb22685414cbafadf8

Now it displays the transaction that was executed later.

Take a look at the first 6 transactions on this account:
http://etherscan.io/address/0xd87dfb24fefd44e5d1f441fa086c724e53a73dfb

One of them is the transaction I made on MyEtherWallet, the other 5 are transactions that I tried to make hours earlier with Mist. They all show the exact same timestamp. How did this happen?

**Comment by Phistr90** [comment]
I have the same problem with the new Mist browser. Triedto send a tx but it didnt get through.

Maybe something wrong with the nonce?

**Comment by luclu** [comment]
PR: https://github.com/ethereum/meteor-dapp-wallet/pull/260
