### ISSUE TITLE
Mist Wallet auto setups main account without asking for password

### ISSUE THREAD

**Issue by baobabKoodaa** [ethereum/mist#932]
Node type: geth
OS: windows
Network type: main
Mist Wallet 0.7.6 (Beta 20)

When I launched the Wallet for the first time it took 10 hours and when it was done it had set up some kind of "main account" without asking for a password. I'm guessing this is because 6 months ago I tried running geth I set up some kind of test account when I did that? I don't have access to that account anymore, so I'm guessing I don't have access whatever "main account" is, either.

I don't think Mist Wallet should auto load any old accounts from the computer without asking the user (if that's what happened). I don't think it should setup some account which the user may not access. I'm sure someone at some point transfers money to such an account, only to realize later they can't access it.

**Comment by luclu** [comment]
When Mist/Ethereum-Wallet starts it will connect to a node which is in charge of the account management. You can easily delete that keyfile if you don't want to use it anymore. To do so go to the menu -> accounts -> backup -> accounts and remove the corresponding `json`-file in geth's `keystore`-folder.

**Comment by luclu** [comment]
Assuming this to be solved.

**Comment by baobabKoodaa** [comment]
Hi luclu! My issue wasn't about "how to delete an account", it was that the wallet shouldn't entice people to accidentally transfer funds to accounts they are unable to access. When a new user sees "main account" the first time they use the Wallet, it's natural for them to assume "this must be my account, I should transfer funds here". Someone at some point is going to lose ETH because of this.
