### ISSUE TITLE
Wallet should have ability to check which accounts are accessible

### ISSUE THREAD

**Issue by baobabKoodaa** [ethereum/mist#933]
Node type: geth
OS: windows
Network type: main
Mist Wallet 0.7.6 (Beta 20)

A user may have multiple accounts visible in their Mist Wallet GUI without knowing which accounts are accessible (for example, if they have forgotten the password to some account). The only way to check in the GUI which accounts are accessible is to transfer some funds into an account, then try to send funds out of the account. If an account is not accessible, those funds are lost. I think the user should be able to check if an account is accessible without risking funds.

**Comment by luclu** [comment]
This is a feature I would like to see being implemented as it could prevent many password related problems. Which include:
 - pre-wallet users did setup accounts in geth; starting the wallet which pops up with [additional](https://github.com/ethereum/meteor-dapp-wallet/issues/248) accounts; send money; but forgot about password/don't understand the relation to the client

**Comment by alexvandesande** [comment]
It will. Adding signing messages is on our roadmap and you'll be able to use it to test passwords. Thanks!
