### ISSUE TITLE
Skipping flash-screen progress loader shows empty screen

### ISSUE THREAD

**Issue by obscuren** [ethereum/mist#936]
When I started _mist_ and skipped the fancy loading screen it came up with an empty, brownish window. In the lower _left_ corner it did however display the network status (block no., peer count and block time).

I've only seen this on **linux** and I'm not sure if this is a linux only issue.

**From Gitter convo with @alexvandesande**

> The empty screen with brownish background is because sometimes it will open without any visible tabs. Not sure why yet.

**Comment by alexvandesande** [comment]
Wow, that's an old bug! Thanks for the help jeff, the problem is solved 😉
