### ISSUE TITLE
0.8.0 broken Win64 release

### ISSUE THREAD

**Issue by raymens** [ethereum/mist#937]
Node type: geth/eth
OS: windows
Network type: main/test
Mist version: 0.8.0

The 0.8.0 release for Win64 is twice as small as the Win32 package. There seems to be a broken build.
*Mist.exe* is named *.Mist.exe.~55d9052f* etc.

(https://github.com/ethereum/mist/releases/download/0.8/Mist-win64-0-8-0.zip)

**Comment by luclu** [comment]
Thank you for reporting - it seems that several files are corrupted. I will keep you updated.

**Comment by luclu** [comment]
The release binaries should be fixed now.
