### ISSUE TITLE
Shasum 256 checksums not correct for OSX

### ISSUE THREAD

**Issue by gfunksound** [ethereum/mist#938]
Node type: geth
OS: osx
Network type: main
Mist version: 0.8.0

Correct version should be: 09d75f4e3d521c796e22fd5ca20f2a20cbac48fe306b85f21e9653d42090123e

but when I run in Terminal

shasum -a 256 /filelocation I get:

shasum -a 256 /Users/justinwu/Desktop/Ethereum-Wallet-macosx-0-8-0.zip 
6cad5f808d0eeb4f2f92eacf60e6e04a9944ab52bd1d87bfbe9431230b1a975a  /Users/justinwu/Desktop/Ethereum-Wallet-macosx-0-8-0.zip

What's the problem? I have not opened the zip because it does not match the shasum posted.

Please advise

**Comment by luclu** [comment]
Thank you for reporting - it seems that several files are corrupted. I will keep you updated.

**Comment by luclu** [comment]
Some release binaries were broken, as well as the checksum. They should be healthy now.

**Comment by LukeMonson** [comment]
I just checked my osx download and did not open because the shasum does not match the posted one.

**Comment by root-io** [comment]
Same issue with 0.8.3 :/

```
Error: sha256 mismatch
Expected: b5fba40142090010e34f2fad332e481c63af19eb857d74370cf3eab3475a6f7a
Actual: e915e66a774cd9af320b746bfd907cc9f678d0d39e75643f35488925e177fefa
```

**Comment by luclu** [comment]
Thank you @root-io, the Ethereum Wallet ones did mismatch.
