### ISSUE TITLE
Won't connect to peers on windows

### ISSUE THREAD

**Issue by buggie77** [ethereum/mist#94]
Hi, I git the startup screen for more than hour in this state and fw is opened on W7 x64, Looking for peers... what Im doing wrong ? thanks (version 0.3.7)

**Comment by frozeman** [comment]
it is either updating your DB in the background, if you had a already a geth node running, or it didn't work. could you try to run a gteh node standalone on your win and see what it says?
int could also be that you never allowed the connections to the geth node, so it never gets any peers

**Comment by buggie77** [comment]
I1219 19:21:46.446609    4380 database.go:71] Alloted 16MB cache to
C:\Users\MyUser\AppData\Roaming\Ethereum\chaindata
I1219 19:21:46.459610    4380 database.go:71] Alloted 16MB cache to
C:\Users\MyUser\AppData\Roaming\Ethereum\dapp
I1219 19:21:46.469610    4380 backend.go:314] Protocol Versions: [63 62
61], Net
work Id: 1
I1219 19:21:46.469610    4380 backend.go:362] Blockchain DB Version: 3
I1219 19:21:46.469610    4380 blockchain.go:214] Last header: #0
[d4e56740.] TD=
17179869184
I1219 19:21:46.469610    4380 blockchain.go:215] Last block: #0 [d4e56740.]
TD=1
7179869184
I1219 19:21:46.470610    4380 blockchain.go:216] Fast block: #0 [d4e56740.]
TD=1
7179869184
I1219 19:21:46.476611    4380 cmd.go:114] Starting
Geth/v1.3.2/windows/go1.5.1
I1219 19:21:46.476611    4380 server.go:311] Starting Server
I1219 19:21:48.628734    4380 udp.go:204] Listening,
enode://9d996d3903492c0c1ae
4548ac81c56f26745f0681abcdc8ddb8f4ce8239e934bc0656d7f2805284a25db1f96c696a73fbae
933eb76537bace0c7d61c69725b9c@0.0.0.0:30303
I1219 19:21:48.629734    4380 backend.go:526] Server started
I1219 19:21:48.630734    4380 ipc.go:112] IPC service started
(\\.\pipe\geth.ipc
)
I1219 19:21:48.629734    4380 server.go:552] Listening on [::]:30303

so is running

**Comment by frozeman** [comment]
Ok good, then can you start the node externally and then start the wallet?

**Comment by buggie77** [comment]
yes, I did, wallet started with skipping the nodes search but : 0 peers /
46 years since last block - thnx

**Comment by frozeman** [comment]
Then you seem to not connect to the outside, this might be a firewall problem or something

**Comment by buggie77** [comment]
I'll try to connect outside through 4g router later, let you know, thanks

**Comment by buggie77** [comment]
Today I started the wallet and it immediately started to download
blockchain :-)

**Comment by whatsdis** [comment]
still the same issue just says looking and stuck like that

**Comment by dinkargupta** [comment]
facing the same issues. have tried all of these measures... even outside firewall it's not working..

**Comment by frozeman** [comment]
Please try running `wallet/resources/nodes/geth/geth.exe` from the command line tool (cmd) and see what errors your get

**Comment by dinkargupta** [comment]
Thanks.. I tried 3 options with this geth.exe
1) --datadir <dir> --networkid 23
2) --datadir <dir>
3) --testnet

all work well and the node starts fine on console.. then on launching the Ethereum-Wallet.exe, I keep getting the 'Looking for peers' message.

Output:

I0113 23:11:08.298017    2376 database.go:71] Alloted 16MB cache to C:\Users\<userid>\AppData\Roaming\Ethereum\testnet\chaindata
I0113 23:11:08.338028    2376 database.go:71] Alloted 16MB cache to C:\Users\<userid>\AppData\Roaming\Ethereum\testnet\dapp
I0113 23:11:08.355151    2376 backend.go:314] Protocol Versions: [63 62 61], Network Id: 2
I0113 23:11:08.358589    2376 genesis.go:89] Genesis block already in chain. Writing canonical number
I0113 23:11:08.359657    2376 backend.go:362] Blockchain DB Version: 3
I0113 23:11:08.361901    2376 blockchain.go:214] Last header: #14 [1ff7b45b.] TD=1971072
I0113 23:11:08.361901    2376 blockchain.go:215] Last block: #14 [1ff7b45b.] TD=1971072
I0113 23:11:08.361901    2376 blockchain.go:216] Fast block: #14 [1ff7b45b.] TD=1971072
I0113 23:11:08.376791    2376 cmd.go:114] Starting Geth/v1.3.3/windows/go1.5.1
I0113 23:11:08.378261    2376 server.go:311] Starting Server
I0113 23:11:10.881393    2376 udp.go:204] Listening, enode://907ddf36f3c6401d7d007f4d1cf458572f85a1b4e6071ad0198335f532e74c0c074634ab9e1077c3b812f5dae09fc3
I0113 23:11:10.882395    2376 server.go:552] Listening on [::]:30303
I0113 23:11:10.882395    2376 backend.go:526] Server started
I0113 23:11:10.882395    2376 ipc.go:112] IPC service started (\\.\pipe\geth.ipc)

Any options I am missing /you would recommend ?

**Comment by frozeman** [comment]
Does the node ever starts to process/import blocks? if not then it doesn't get peers to sync from. It might be a network issue on your side.

**Comment by dinkargupta** [comment]
I will check again but shouldn't be. I am not behind firewall. This is not working even on home wifi network - everything else works fine (maven repositories, docket repositories.. etc.). Any verbose output type options on geth that I can use to check where it's failing ?

**Comment by dinkargupta** [comment]
Ok.. finally. Here seems to be the issue
network port tcp:30302 could not be mapped: no UPnP or NAT-PMP router discovered

**Comment by frozeman** [comment]
@fjl any idea?

**Comment by dinkargupta** [comment]
some more details (tried again but still same result)

I am on windows 8.1. I have enabled network discovery on the network connection (this could have stopped connections to outside network). Have also allowed the connections to public network on windows firewall (UPnP based).

just ran the geth again as 
geth --datadir "D:\Ethereum 0.9.41\datadir" --networkid "23" --verbosity "5"

and the same result

flags.go:425] WARNING: No etherbase set and no accounts found as default
database.go:71] Alloted 16MB cache to D:\eclipse\Ethereum 0.9.41\datadir\chaindata
database.go:71] Alloted 16MB cache to D:\eclipse\Ethereum 0.9.41\datadir\dapp
backend.go:314] Protocol Versions: [63 62 61], Network Id: 23
backend.go:362] Blockchain DB Version: 3
blockchain.go:214] Last header: #0 [d4e56740.] TD=17179869184
blockchain.go:215] Last block: #0 [d4e56740.] TD=17179869184
blockchain.go:216] Fast block: #0 [d4e56740.] TD=17179869184
cmd.go:114] Starting Geth/v1.3.3/windows/go1.5.1
server.go:311] Starting Server
nat.go:109] network port udp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
udp.go:204] Listening, enode://7322da466f5425e7a2e8a8c8a0681de44af9b3d7aa048257302aa133ec00d2cbb0c8a2b7aa906f189cb68d4ee6b43c04a1898b561f3d983666f1682ee0788886@[::]:30303
backend.go:526] Server started
server.go:552] Listening on [::]:30303
ipc.go:112] IPC service started (\\.\pipe\geth.ipc)
nat.go:109] network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
table.go:336] no seed nodes found
table.go:336] no seed nodes found
table.go:336] no seed nodes found
table.go:336] no seed nodes found

**Comment by fjl** [comment]
Are you trying to work with a private chain? `--networkid=23` wont get you on the main chain.

**Comment by dinkargupta** [comment]
Yes.. Working with testnet

**Comment by dinkargupta** [comment]
Well well well !! just like everything else, stupid mistake.. the following worked on command line
geth --testnet --networkid 23 --datadir D:\Ethereum 0.9.41\datadir --verbosity 5

I was able to create a account and check balance on the console. 

BUT
the wallet client is still looking for peers. When I start Ethereum-Wallet.exe, I have to skip peer search and then on the UI, nothing is there are 0 peers.. so can't do much.

interestingly when I looked at the source code, the ethereumNodes.js uses the following flags when starting geth 
'--testnet', '--fast'

but when I used these flags on command line I can't get geth started properly and the UPnP issues come up

something to consider ?

**Comment by frozeman** [comment]
I think you misunderstand something here. You don't need to use the `--testnet` flag, if you're providing a network id. the testnet flag simply sets a genesis block and a testnet id (the one of the official testnet).

Concerning startup @karalabe you have any idea why he could have that problem?
btw, @dinkargupta  you're using the geth version 1.3.3, right?

**Comment by dinkargupta** [comment]
Yes you are right.. but I guess the documentation got me confused a bit. 
I am using Geth 1.3.3 but still not able to connect to testnet. I have a dev node running now after following this command

geth --dev --networkid 54345 --datadir D:\eclipse\Ethereum 0.9.41\datadir --mine --minerthreads 4

All I want to do is instead of the dev node, connect to testnet and work there..

BTW, what led me here was not command line geth issues.. I was running the Ethereum-Wallet app as mentioned in https://blog.ethereum.org/2015/12/03/how-to-build-your-own-cryptocurrency/ but it is not working.. When I checked the code in ethereumNode.js (on mist main branch it used --testnet and --fast as options for starting geth..

**Comment by frozeman** [comment]
It looks like there is some issue with windows, i will try next week myself.

**Comment by fjl** [comment]
@dinkargupta note: `--dev` disables p2p connectivity.

**Comment by Bubleek** [comment]
> It looks like there is some issue with windows, i will try next week myself.

Hi to all! I have same issue with Loocing for peers... And can't started and can't connect no peers net.
I use win7x64 with geth version 1.3.3. And i use --verbosity 5 and --dev flags. I do some test and paste my output here:
`D:\ETH\Ethereum-Wallet-win32-x64-0-3-9\resources\node\geth>D:\ETH\Ethereum-Walle
t-win32-x64-0-3-9\resources\node\geth\geth.exe --dev --verbosity 5
I0211 12:14:28.641752    2664 flags.go:502] dev mode enabled
I0211 12:14:28.642752    2664 database.go:71] Alloted 16MB cache to C:\Users\Use
r\AppData\Local\Temp\ethereum_dev_mode\chaindata
I0211 12:14:28.724757    2664 database.go:71] Alloted 16MB cache to C:\Users\Use
r\AppData\Local\Temp\ethereum_dev_mode\dapp
I0211 12:14:28.768759    2664 backend.go:314] Protocol Versions: [63 62 61], Net
work Id: 1
I0211 12:14:28.769759    2664 statedb.go:264] (+) cd2a3d9f938e13cd947ec05abc7fe7
34df8dd826
I0211 12:14:28.769759    2664 state_object.go:184] cd2a3d9f938e13cd947ec05abc7fe
734df8dd826: #0 1606938044258990275541962092341162602522202993782792835301376 (+
 1606938044258990275541962092341162602522202993782792835301376)
I0211 12:14:28.770759    2664 statedb.go:264] (+) e6716f9544a56c530d868e4bfbacb1
72315bdead
I0211 12:14:28.770759    2664 state_object.go:184] e6716f9544a56c530d868e4bfbacb
172315bdead: #0 1606938044258990275541962092341162602522202993782792835301376 (+
 1606938044258990275541962092341162602522202993782792835301376)
I0211 12:14:28.770759    2664 statedb.go:264] (+) 000000000000000000000000000000
0000000002
I0211 12:14:28.771759    2664 state_object.go:184] 00000000000000000000000000000
00000000002: #0 1 (+ 1)
I0211 12:14:28.771759    2664 statedb.go:264] (+) 000000000000000000000000000000
0000000003
I0211 12:14:28.771759    2664 state_object.go:184] 00000000000000000000000000000
00000000003: #0 1 (+ 1)
I0211 12:14:28.772759    2664 statedb.go:264] (+) dbdbdb2cbd23b783741e8d7fcf51e4
59b497e4a6
I0211 12:14:28.773759    2664 state_object.go:184] dbdbdb2cbd23b783741e8d7fcf51e
459b497e4a6: #0 1606938044258990275541962092341162602522202993782792835301376 (+
 1606938044258990275541962092341162602522202993782792835301376)
I0211 12:14:28.774759    2664 statedb.go:264] (+) b9c015918bdaba24b4ff057a92a387
3d6eb201be
I0211 12:14:28.775760    2664 state_object.go:184] b9c015918bdaba24b4ff057a92a38
73d6eb201be: #0 1606938044258990275541962092341162602522202993782792835301376 (+
 1606938044258990275541962092341162602522202993782792835301376)
I0211 12:14:28.775760    2664 statedb.go:264] (+) 2ef47100e0787b915105fd5e3f4ff6
752079d5cb
I0211 12:14:28.776760    2664 state_object.go:184] 2ef47100e0787b915105fd5e3f4ff
6752079d5cb: #0 1606938044258990275541962092341162602522202993782792835301376 (+
 1606938044258990275541962092341162602522202993782792835301376)
I0211 12:14:28.777760    2664 statedb.go:264] (+) 1a26338f0d905e295fccb71fa9ea84
9ffa12aaf4
I0211 12:14:28.778760    2664 state_object.go:184] 1a26338f0d905e295fccb71fa9ea8
49ffa12aaf4: #0 1606938044258990275541962092341162602522202993782792835301376 (+
 1606938044258990275541962092341162602522202993782792835301376)
I0211 12:14:28.779760    2664 statedb.go:264] (+) 000000000000000000000000000000
0000000001
I0211 12:14:28.780760    2664 state_object.go:184] 00000000000000000000000000000
00000000001: #0 1 (+ 1)
I0211 12:14:28.781760    2664 statedb.go:264] (+) 000000000000000000000000000000
0000000004
I0211 12:14:28.782760    2664 state_object.go:184] 00000000000000000000000000000
00000000004: #0 1 (+ 1)
I0211 12:14:28.783760    2664 statedb.go:264] (+) e4157b34ea9615cfbde6b4fda41982
8124b70c78
I0211 12:14:28.784760    2664 state_object.go:184] e4157b34ea9615cfbde6b4fda4198
28124b70c78: #0 1606938044258990275541962092341162602522202993782792835301376 (+
 1606938044258990275541962092341162602522202993782792835301376)
I0211 12:14:28.784760    2664 statedb.go:264] (+) 6c386a4b26f73c802f34673f7248bb
118f97424a
I0211 12:14:28.785760    2664 state_object.go:184] 6c386a4b26f73c802f34673f7248b
b118f97424a: #0 1606938044258990275541962092341162602522202993782792835301376 (+
 1606938044258990275541962092341162602522202993782792835301376)
I0211 12:14:28.787760    2664 genesis.go:89] Genesis block already in chain. Wri
ting canonical number
I0211 12:14:28.788760    2664 backend.go:362] Blockchain DB Version: 3
I0211 12:14:28.788760    2664 backend.go:389] ethash used in test mode
I0211 12:14:28.790760    2664 blockchain.go:214] Last header: #0 [fd4af92a:] TD=
131072
I0211 12:14:28.791760    2664 blockchain.go:215] Last block: #0 [fd4af92a:] TD=1
31072
I0211 12:14:28.791760    2664 blockchain.go:216] Fast block: #0 [fd4af92a:] TD=1
31072
I0211 12:14:28.800761    2664 cmd.go:114] Starting Geth/v1.3.3/windows/go1.5.1
I0211 12:14:28.800761    2664 server.go:311] Starting Server
I0211 12:14:30.961885    2664 nat.go:109] network port udp:53134 could not be ma
pped: goupnp: SOAP request got HTTP 500 Internal Server Error
I0211 12:14:31.265902    2664 udp.go:204] Listening, enode://21127a86229455429b8
4d60eab905c03cae26f022e0d33cc3cc2674b661f0d79028f3913420d639a2c17656edd8e843987a
9a55b6a25ae320d458067f62b6025@0.0.0.0:53134
I0211 12:14:31.452913    2664 server.go:552] Listening on [::]:50907
I0211 12:14:31.452913    2664 whisper.go:160] Whisper started
I0211 12:14:31.453913    2664 backend.go:526] Server started
I0211 12:14:31.454913    2664 ipc.go:112] IPC service started (\\.\pipe\geth.ipc
)
I0211 12:14:31.467913    2664 nat.go:109] network port tcp:50907 could not be ma
pped: goupnp: SOAP request got HTTP 500 Internal Server Error`

But now i use proxy and i don't know how i can setup proxy settings to this app(username and pass)?
frozeman, are you try searching bugs with windows?

**Comment by frozeman** [comment]
@fjl ?

**Comment by Bubleek** [comment]
**@frozeman** ???
**@fjl** ???

**Comment by Bubleek** [comment]
`I0211 18:44:12.887854    4080 nat.go:109] network port udp:30303 could not be ma
pped: no UPnP or NAT-PMP router discovered
I0211 18:44:12.896854    4080 udp.go:204] Listening, enode://0db298db882f30f8609
e01a9a3e28a3b3b7e4044c0be2b2d5780a6212b4eab2ede08c452aa6008df1647c36df83b8647524
eff0bccb467b4e9b804c42f88afbf@0.0.0.0:30303
I0211 18:44:12.897854    4080 backend.go:526] Server started
I0211 18:44:12.897854    4080 ipc.go:112] IPC service started (\\.\pipe\geth.ipc
)
I0211 18:44:12.898854    4080 server.go:552] Listening on [::]:30303
I0211 18:44:12.898854    4080 nat.go:109] network port tcp:30303 could not be ma
pped: no UPnP or NAT-PMP router discovered`
Still can't connect to peer net in my home too.
Any ideas?

**Comment by fjl** [comment]
--dev mode disables network connectivity. If you want to connect to the testnet, use --testnet.

**Comment by fjl** [comment]
I'll add a warning log message to indicate that it won't connect in this mode on the develop branch. But it'll be a while before the message makes its way into the bundled geth that comes with the wallet.

**Comment by Bubleek** [comment]
**@fjl** Thx. When i use --nat any flag it's good way or not? I should wait when i see `no seed nodes found` strigs or it still don't working correctly?

**Comment by fjl** [comment]
If you see 'no seed nodes found' your clock is probably wrong. Try enabling internet time sync in system settings.

**Comment by fjl** [comment]
If you see 'no seed nodes found' your clock is probably wrong. Try enabling internet time sync in system settings.

**Comment by fjl** [comment]
If you see 'no seed nodes found' your clock is probably wrong. Try enabling internet time sync in system settings.

**Comment by fjl** [comment]
If you see 'no seed nodes found' your clock is probably wrong. Try enabling internet time sync in system settings.

**Comment by Bubleek** [comment]
@fjl My windows don't have time sinc function or this func not working correctly because government change  winter\sunny time so fast.

**Comment by Bubleek** [comment]
Flag '--port XX' not working correctly! Only when server started it can change port number then nat.go still using port 30303. And i think some program or windows fierwall block this port then NAT mapping not working for me...

**Comment by Bubleek** [comment]
Yes! iI start download blocks!

**Comment by frozeman** [comment]
fucking windows... :P

**Comment by Bubleek** [comment]
**@frozeman** Yes, fu**ng windows! I'm spend all evenig time to understanding what happen. Now i want setup proxy for geth becouse on my work my internet connection under proxy. Any ideas about setup proxy(user name and pass) for geth?

**Comment by Joter85** [comment]
As my router doesn't support UPnP, solution for me was setting geth --nat extip

> geth --nat extip:(YOUR_PUBLIC_IP) --maxpeers "50"

**Comment by Bubleek** [comment]
@Joter85 Thsnks! It may help too. I'll try setup ext ip for geth. But now mist workig normaly.

**Comment by punit167** [comment]
Here is what fixed my problem.
I'm running windows 7, 64 bit. 
Do you see the annoying little popup when windows says "do you want to allow this NEW SOFTWARE access to network"? Well since Mist is run as an exe, and is not officially installed, it never got access to the network as you never got that popup. 
From firewall settings, find "Allow programs through windows firewall". Go to Change Settings, and click "Allow another program". On the next popup, click Browse, and navigate to and select Mist.exe. The program got added as Electron in my system.

I ran Mist again.. and things were different immediately, I saw TEST-NET appearing on top and it started downloading blocks soon after.

Hope this helps.

**Comment by NuCash** [comment]
Hello,
I have built litecoin based scrypt coin and compiled windows-qt using USE_UPNP=-, 
Wallet has been compiled successfully and running well.
The problem is now that peers don't connect, 
I tried running a client on local machine and other on vps [windows server], 
I tried adding local ips of both machines in .conf at both end, 
From day one wallet shows out of sync and 7 days behind.
Not able to mine genesis block too.
Any suggestion please.
