### ISSUE TITLE
Wallet synchronization just kills my computer

### ISSUE THREAD

**Issue by egzumer** [ethereum/mist#942]
OS: windows
Network type: main
Mist version: 0.8.0

Computer is unusable when wallet is synchronizing and synchronization takes forever after approximately 1 week offline. I have intel i3, SSD.

[node.txt](https://github.com/ethereum/mist/files/354727/node.txt)

**Comment by luclu** [comment]
The logs look fine. 
Could you please check if the memory footprint of the `geth.exe` is skyrocking? It might be related to this issue https://github.com/ethereum/mist/issues/837.

**Comment by egzumer** [comment]
Memory goes up to 0.6 - 1GB, disk usage up to 30MB/s, processor around 30%. Even if geth it's being run from command line with "geth --rpc" its just the same as running gui wallet. Computer becomes almost unusable. It runs really sluggish, sometimes when I type something on my keyboard I have to wait for letters to appear on the screen. It all happens only while syncing, and when I stop geth problem disappears.
At the same time I also have 13 chrome browser pages opened and ethminer running on GPU.

Does it supposed to take so long to sync? As you can see from the node.txt it takes up to 26mins to sync 2048 blocks. Maybe its just so resources consuming process?

**Comment by luclu** [comment]
You are right. Try these [recommendations](https://github.com/ethereum/go-ethereum/issues/2770#issuecomment-230240557) for a start.

**Comment by luclu** [comment]
I will close this for now as it should be resolved. Please try out this if you still encounter problems:
>Please try to do a fresh re-sync now that the [state-clearing](https://www.reddit.com/r/ethereum/comments/5fob4s/state_clearing_100_complete/) did finish. 
>
>Doing a fresh sync will reduce the blockchain replica on your computer to ~10G and won't take much longer than 1h on a SSD.
>
>Please make sure to have the [latest version of Mist / Ethereum Wallet](https://github.com/ethereum/mist/releases) installed and follow [this how-to](https://ethereum.stackexchange.com/questions/6554/i-am-having-trouble-doing-the-initial-sync-of-ethereum-wallet-what-can-i-do-to/6555#6555) to reset the chaindata folder and initiate the fresh sync.
