### ISSUE TITLE
Mist localisation is not applied

### ISSUE THREAD

**Issue by chevdor** [ethereum/mist#945]
Node type: geth
OS: OS X
Network type: n/a
Mist version: 0.8.0

The following applies for both running in Mist mode or in the default mode.
When choosing another language than english, I can see on OS X the menus being localised properly.
However, the wallet itself is not localised.

![screen_shot_2016-07-09_at_17_09_15](https://cloud.githubusercontent.com/assets/738724/16708548/239da47e-45f8-11e6-9e84-b49bfd61705b.png)
![screen_shot_2016-07-08_at_23_21_16](https://cloud.githubusercontent.com/assets/738724/16708549/23a2db2e-45f8-11e6-96e5-856955883d74.png)

**Comment by luclu** [comment]
I can confirm this on OSX.

**Comment by alexvandesande** [comment]
We had to read the tap-bundler so this is still open

**Comment by luclu** [comment]
@alexvandesande this problem seems to persist with `0.8.2`: https://github.com/ethereum/mist/issues/1161

**Comment by h3ll0fr13nd** [comment]
![image](https://cloud.githubusercontent.com/assets/21191966/22644681/c6853afa-ec63-11e6-8b4d-8e7c0c343c38.png)
This is the terminal output when changing the language from the default startup to another language using the [View]=>[Change Language] menu.

**Comment by frozeman** [comment]
The issue here is that `numeral.js` doesn't support nl and therefore crashes the language switching as it seems. This happens in line https://github.com/ethereum/mist/blob/develop/interface/client/appStart.js#L85
@luclu when youre back could you take a look?

**Comment by frozeman** [comment]
@h3ll0fr13nd does it switch the interface language for you?

**Comment by h3ll0fr13nd** [comment]
![image](https://cloud.githubusercontent.com/assets/21191966/22645803/2a85ae2c-ec69-11e6-8c59-5bd1e0de89f2.png)
It does translate the sidebar, but not the wallet; see above screenshot. numeral.language seems to expect two inputs.

**Comment by frozeman** [comment]
Yeah the wallet doesn't get the language setting yet, we need to set this in the user agents locale and the wallet would need to react to that.
