### ISSUE TITLE
please enable network time synchronization in system settings 

### ISSUE THREAD

**Issue by rockparvez1** [ethereum/mist#947]
Node type: geth
OS: windows

C:\Geth>geth --rpc
I0710 12:39:11.690198 cmd/utils/flags.go:687] You're one of the lucky few that w
ill try out the JIT VM (random). If you get a consensus failure please be so kin
d to report this incident with the block hash that failed. You can switch to the
 regular VM by setting --jitvm=false
I0710 12:39:11.691197 ethdb/database.go:82] Alloted 128MB cache and 1024 file ha
ndles to C:\Users\parvez\AppData\Roaming\Ethereum\chaindata
I0710 12:39:11.816769 ethdb/database.go:169] closed db:C:\Users\parvez\AppData\R
oaming\Ethereum\chaindata
I0710 12:39:11.820787 ethdb/database.go:82] Alloted 128MB cache and 1024 file ha
ndles to C:\Users\parvez\AppData\Roaming\Ethereum\chaindata
I0710 12:39:11.859801 ethdb/database.go:82] Alloted 16MB cache and 16 file handl
es to C:\Users\parvez\AppData\Roaming\Ethereum\dapp
I0710 12:39:11.914550 eth/backend.go:172] Protocol Versions: [63 62 61], Network
 Id: 1
I0710 12:39:11.915556 eth/backend.go:201] Blockchain DB Version: 3
I0710 12:39:12.246808 eth/backend.go:247] WARNING: Wrote default ethereum genesi
s block
I0710 12:39:12.247789 core/blockchain.go:206] Last header: #0 [d4e56740.] TD=171
79869184
I0710 12:39:12.247789 core/blockchain.go:207] Last block: #0 [d4e56740.] TD=1717
9869184
I0710 12:39:12.247789 core/blockchain.go:208] Fast block: #0 [d4e56740.] TD=1717
9869184
I0710 12:39:12.248791 p2p/server.go:313] Starting Server
I0710 12:39:13.904735 p2p/discover/udp.go:217] Listening, enode://0400e0cd47ff5d
2dd11e0cb70f46713758f48f7d0f6ba9c8a29239bbb89aba7d74461a358d83c36d4e02dcaed3b74e
b6effcd75503d8f459dbd8ee3adaef418e@[::]:30303
I0710 12:39:13.907736 p2p/server.go:556] Listening on [::]:30303
I0710 12:39:13.911738 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc
I0710 12:39:13.918743 node/node.go:366] HTTP endpoint opened: http://localhost:8
545
I0710 12:50:11.820878 p2p/discover/ntp.go:58] ----------------------------------
---------------------------------------------
I0710 12:50:11.821902 p2p/discover/ntp.go:59] System clock seems off by -41.2448
6574s, which can prevent network connectivity
I0710 12:50:11.821902 p2p/discover/ntp.go:60] Please enable network time synchro
nisation in system settings
I0710 12:50:11.822905 p2p/discover/ntp.go:61] ----------------------------------
---------------------------------------------
I0710 13:00:39.455839 p2p/discover/ntp.go:58] ----------------------------------
----------------------------------------------
I0710 13:00:39.456613 p2p/discover/ntp.go:59] System clock seems off by -41.2546
61649s, which can prevent network connectivity
I0710 13:00:39.456613 p2p/discover/ntp.go:60] Please enable network time synchro
nisation in system settings
I0710 13:00:39.456613 p2p/discover/ntp.go:61] ----------------------------------
----------------------------------------------

**Comment by luclu** [comment]
@rockparvez1 geth will only warn you with those log lines:
```
System clock seems off by -XXXXXs, which can prevent network connectivity
Please enable network time synchronisation in system settings
```
Mist will show you an alert.
But it is only in the users control to follow this advice as time-synchronization is OS-specific and some people might even have a reason for not using it.

I will close this for now. Feel free to ask further questions.

**Comment by ramsesmanx** [comment]
geth finish the sincronization if that alert keep on cmd?

**Comment by luclu** [comment]
@ramsesmanx most certainly not. You will have to enable OS's timesync to be accepted by peers.

**Comment by ramsesmanx** [comment]
how can i do that? i´ve Windows 10

**Comment by luclu** [comment]
Have a look at [this guide](http://www.tenforums.com/tutorials/6410-clock-synchronize-internet-time-server-windows-10-a.html). If it is already enabled, please disable it and re-enable it once.

**Comment by arifoxs** [comment]
Hallo, i arif from indonesia i want to test my office server but i do not have root access i can try to build geth from source and run it, and successfully run create account but i am confused, there is warning like above, 

> WARN System clock seems off by -41.24486574s, which can prevent network connectivity
> WARN Please enable network time synchronisation in system settings

while i do not have access Root so I can not synchronize the time, and this is only use for experiment only, does it matter if the warning exists?

**Comment by Marow** [comment]
I had Ubuntu 16.04 and the same error... what can i do to fix it

**Comment by pannous** [comment]
see https://github.com/ethereum/go-ethereum/issues/14717 for linux
