### ISSUE TITLE
"Wrong password" in transaction when account has no Ether (same password works when account has Ether)

### ISSUE THREAD

**Issue by leonardoalt** [ethereum/mist#948]
Node type: geth
OS: linux
Network type: main
Mist version: 0.8.0

I created a new account, and didn't transfer anything to it.
Then I went and try the "Nutella statement" (https://ethereum.github.io/stake-voice/?proposal=Nutella%20is%20overrated). I linked my new account with the poll and voted. After typing my password for the transaction, it says wrong password. 

After transferring some Ether to this new account, I tried the same and it **worked** (copy pasted passwd both times).

The console doesn't show any error when I get the "wrong passwd" error, only the gas:
`/home/---/Mist-linux64-0-8-0/resources/app.asar/modules/preloader/include/consoleLogCapt…:44 Choosen Gas:  0x1ea2d 125485 @ file:///home/---/Mist-linux64-0-8-0/resources/app.asar/interface/72e28bdeb9e53941da7ddd0224722efb7339d70b.js:283:2957)`

I guess it was correct not to allow my transaction, but the error message was misleading.

**Comment by luclu** [comment]
Thanks for reporting @leonardoalt 
This is a known bug that is ought to be fixed in the next release https://github.com/ethereum/mist/issues/664

I will keep this open for now as this remains on the first page and is more likely to be found.

**Comment by luclu** [comment]
We will try to catch this error by `string` for now. But to ensure compatibility to other nodes these [error codes](https://github.com/ethereum/wiki/wiki/JSON-RPC-Error-Codes-Improvement-Proposal) should be implemented by the nodes.

**Comment by luclu** [comment]
Could you please have a try with `0.8.1` and post its error message?

**Comment by leonardoalt** [comment]
Thanks for the update @luclu 
Now I get the message "Account does not exist or account balance too low"
Looks good!

**Comment by luclu** [comment]
>  Now I get the message "Account does not exist or account balance too low"

This happens when an account has 0 balance or simply does not exist (yet), i.e. there’s no state object in the state trie.
