### ISSUE TITLE
Please stop renaming, re-releasing, re-building, re-packaging already published releases.

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#949]
Please stop renaming, re-releasing, re-building, re-packaging [...] already published releases. There is no way for me to figure out if you 

- re-build an already released package
- re-name a tag
- do whatever makes the published checksum invalid
- change already published checksums

unless you bump the version. This is now the fifth time in 48h I have to update the 0.8.0 package for arch linux. I was hesitant to report this as an issue, but I would like to inform you, it's very difficult to for me to monitor this in my free time closely and I would like to encourage you to just bump the version number and remove messed up builds in future.

Unfortunately, github does not show any message like "edited 2 hours ago" on the release page. I have to run the install scripts every day to make sure you did not change anything in a release. Please give this a first, or second thought and excuse me if this sounds a bit annoyed, but I wont be able to contribute and maintain the package if this consumes so much time to re-check if everything is still working.

Thanks!

**Comment by luclu** [comment]
I'm sorry for the inconvenience this caused - we will try to improve on this.
Currently there are several proposals to switch to an advanced testing/packaging infrastructure as outlined in https://github.com/ethereum/mist/issues/561
Those include changes to mitigate:
 - packaging errors (switch to TravisCI)
 - checksum errors (use gulp.js to automate this)
 - broken packages (add UI testing)

---

Also you could either use selfoss to subscribe to github's release.atom feed or use the github-api to watch for changes.
