### ISSUE TITLE
Create contract (TOKEN %) "CONFIRMING..." Persist after more than an hour

### ISSUE THREAD

**Issue by taotech4096** [ethereum/mist#95]
![issue](https://cloud.githubusercontent.com/assets/15895498/11918104/d2be59fe-a723-11e5-9a66-70a3e06cf569.png)

**Comment by frozeman** [comment]
very odd, try restarting the wallet. i guess the geth node didn't respond properly

**Comment by taotech4096** [comment]
Thanks,
I restarted it and made the operation again and now it works..
