### ISSUE TITLE
Mist wallet 0.5.2 no access on OSX

### ISSUE THREAD

**Issue by wllmkn** [ethereum/mist#952]
No access to my wallet since a week. Is there another version? Pls. Let me know I would like to have access to my wallet at anytime.

Node type: geth 1.3.5 (Go)
OS:osx 10.11.5
Network type: main/test

![schermafbeelding 2016-07-11 om 18 38 02](https://cloud.githubusercontent.com/assets/20403578/16738621/c04b1618-4796-11e6-97b6-ffd9c3c918f4.png)

**Comment by luclu** [comment]
@wllmkn please update to the latest version at https://github.com/ethereum/mist/releases.

**Comment by wllmkn** [comment]
You closed this issue? Downloading Ethereum-Wallet-macosx-0-8-0.zipt it said that this Sw comes from an unknown developer and it's not allowed to download other than  Apps from appstore.

**Comment by wllmkn** [comment]
Pls help.

**Comment by luclu** [comment]
No worries @wllmkn, I'm still here.
I closed this as `0.5.2` is regarded as legacy we can't support any more.

You will need to dismiss the alert - as this is caused by missing code-signing for OSX. 
We will add this in future releases as outlined in https://github.com/ethereum/mist/issues/561.

**Comment by wllmkn** [comment]
Yes, but updating doesn't seem to be a solution, in my case.

**Comment by wllmkn** [comment]
Dis miss alert, How? I don't understand. Maybe I missed earlier issues, but at this moment I still don't have access. There are no accounts  and no ethers anymore. 0.5.2 may be is regarded as a legacy, but at least it worked.

**Comment by luclu** [comment]
@wllmkn please adjust your gatekeeper settings as described [here](https://support.apple.com/en-us/HT202491).

**Comment by wllmkn** [comment]
Thank you. ok, I did that and then again the download. But still I have an empty wallet...? no ethers to do anything. Though I made a back up just before the wallet 'disappeard'.

![schermafbeelding 2016-07-11 om 18 38 02](https://cloud.githubusercontent.com/assets/20403578/16831705/ba9bd27c-49a6-11e6-9874-031b5075e983.png)

**Comment by luclu** [comment]
Good to hear this worked. Now you have to put your `json`-keyfiles into the `keystore` folder (go to menu -> accounts -> backup -> accounts).

**Comment by wllmkn** [comment]
![schermafbeelding 2016-07-14 om 11 20 14](https://cloud.githubusercontent.com/assets/20403578/16834648/1913435e-49b5-11e6-92a8-d2947d5a9672.png)

 I did this, nothing happens? 

I only have these in keystorefolder. Where can I locate the Json- files?

![schermafbeelding 2016-07-14 om 11 22 43](https://cloud.githubusercontent.com/assets/20403578/16834713/622ee110-49b5-11e6-96c6-209fc8e001db.png)

**Comment by wllmkn** [comment]
thank you btw

**Comment by luclu** [comment]
Could you please rename (same as backup and delete) your `~/Library/Application Support/Mist` folder and restart?

**Comment by wllmkn** [comment]
Please I am not a developer and I haven't done yet the  json-keyfiles into the keystore folder. Now ~/Library/Application Support/Mist ?

**Comment by wllmkn** [comment]
The wallet I have now is Ethereum-Wallet-macosx-0-5-2.

**Comment by wllmkn** [comment]
Is there another version I can download and then it works?

**Comment by wllmkn** [comment]
![schermafbeelding 2016-07-14 om 15 55 04](https://cloud.githubusercontent.com/assets/20403578/16841889/8ee0886e-49db-11e6-9601-56c561b304e2.png) > ??

**Comment by wllmkn** [comment]
@luclu Where can I find this folder?

**Comment by wllmkn** [comment]
@luclu are you still there?

**Comment by wllmkn** [comment]
i'm still stuck at the "json-keyfiles into the keystore folder (go to menu -> accounts -> backup -> accounts)."

**Comment by wllmkn** [comment]
it's not that I just have a few bucks on my ether wallet so could anyone at least pls update. I am waiting for alomst three weeks.

**Comment by luclu** [comment]
Sorry @wllmkn,
Let's start over just to make it smooth:

1. remove old configuration files (just to rule out something is broken): rename (same as backup and delete) your `~/Library/Application Support/Mist` folder
2. download Ethereum-Wallet `0.8.1`
3. start it and go to menu -> accounts -> backup -> accounts
4. copy your `json`-keyfiles into the `keystore` folder
5. wait until the wallet is synced

**Comment by wllmkn** [comment]
Thank you. .3 doesn't work (nothing happens) so I could not do 4.

**Comment by wllmkn** [comment]
Thank you. 
Nothing happens at .3, so I could not do 4.
BTW I can not find Etherwallet in my programs folder after opening.

**Comment by luclu** [comment]
That is rather weird. Try this command line for 3:
```bash
open -a finder ~/Library/Ethereum/keystore
```

**Comment by wllmkn** [comment]
I only have a keystore within the etherwalletbackup I made weeks ago

**Comment by wllmkn** [comment]
I searched in finder with no result...

**Comment by wllmkn** [comment]
Yes..

![schermafbeelding 2016-08-07 om 13 21 12](https://cloud.githubusercontent.com/assets/20403578/17462101/2d1ef0f0-5ca2-11e6-8dab-5984416b7429.png)

**Comment by wllmkn** [comment]
Somehow there are no json files, as I said before... Where should they be.

**Comment by wllmkn** [comment]
Am I held for a fool here? I am asked to do something and then there is no answer...

**Comment by luclu** [comment]
@wllmkn sorry for the delay. I will reopen this as it will get lost again otherwise!

> Sorry, nothing happens at .3, so I could not do 4...

This means that no `keystore` folder is yet available. (See https://github.com/ethereum/mist/issues/1100)

In the past:

1. did you use to specify a different `--datadir`?
2. did you use eth as backend?

To solve your issue you will have to create the keystore folder (create a new account as this will trigger it for you). 
After this you will have to re-import the backup of your json-files.

Should you have used 1. or 2. in the past, you will be able to re-import the files from the different datadir (1.) / from eth's keys (2.).

**Comment by wllmkn** [comment]
Did not use 1 or 2. Thank you. I will create a new account.

**Comment by wllmkn** [comment]
I created a new account, then went to 'accounts -> backup -> accounts'  which showed the keystore folder with the UTC file in it. I copied the UTC.... files into this folder and wait for syncing. Os that correct?

**Comment by wllmkn** [comment]
Finally it worked! My Ethers are 'back', but I my contracts are still gone. Somewhere.

**Comment by luclu** [comment]
I'm glad your situation is resolved! To get the contracts back you can use etherscan.io. Just input your account addresses - you will be served with all created contracts in the transaction list. To reimport wallet contracts simply click on add wallet contract followed by import in Ethereum Wallet.

**Comment by wllmkn** [comment]
It worked. You can close this ticket now. Thank you!
