### ISSUE TITLE
Missing Wallet and ethers updating to Mist Beta 0.8.0

### ISSUE THREAD

**Issue by wllmkn** [ethereum/mist#954]
After updating to Mist Beta 0.8.0 my accounts and ethers seemed disappeared.

Node type: geth
OSX 10.11.5

Is this the same as #915?

I am puzzling now for a few hours, please could you help me with a simple and straight sollution?

**Comment by luclu** [comment]
Does your case pattern to this issue: https://github.com/ethereum/mist/issues/844 ?

**Comment by wllmkn** [comment]
My accounts, tokens, ethers don't show up so maybe yes.

**Comment by luclu** [comment]
I will close this in favour of your second issue: #952.
