### ISSUE TITLE
Display human readable function signature for transactions when possible.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/mist#955]
### What is the problem

Currently, when sending a transaction the raw bytecode of the transaction data is shown in the data field.

<img width="446" alt="screen shot 2016-07-11 at 1 33 28 pm" src="https://cloud.githubusercontent.com/assets/824194/16744017/493988b8-476c-11e6-9dfb-1d77c0476cf7.png">

While showing the bytecode is better than showing nothing, the bytecode is not very helpful to most users and does not expose much useful data in it's raw form.

Ideally, if the transaction that is being sent is calling a function on a contract, the human readable call signature of that function should be shown.
### How could this be fixed.

I suggest querying the human readable version of the 4-byte function signature using the following approach.
1. If the transaction is being executed against a contract who's ABI is known, first look through the function signatures for that contract and see if the first 4 bytes of transaction data match the 4byte signature for any of the contract functions declared within the contract ABI.
2. Next look in a local hard-coded mapping of _common_ function signatures (to be determined what constitutes common).  Current db of ~2000 signatures is 83kb as a json file. (https://gist.github.com/pipermerriam/79429c2163969ff732d5f2aabaaaf0e5)
3. Next query the API of https://www.4byte.directory/ to see if the signature is present in that database (see notes below about this).
### Displaying the function signature

When a human readable signature can be found, I propose displaying it in one of the following ways within the "Execute Contract" modal.
1. In the main title text "Execute Contract" add a sub-title below it that shows the human readable function signature.
2. In the display at the top of the page that shows the two contract icons with the arrow between them and the 4-byte functions signature below them, add the human readable version below the 4-byte function signature.
3. Change the text _"You are about to execute a function on a contract.  This might involve transfer of value"_ to _"You are about to execute the function `transfer(address,uint256)` on a contract.  This might involve the transfer of value"_
4. In the _Data_ section, change the header to be _Data `transfer(address,uint256)`_.
### Thoughts on querying the `4byte.directory` API.

This is a project that I have authored myself.  I'm not in a position to determine whether it is acceptable to add a query to this API, but I will add the following information to hopefully help people make an informed decision.
- The API is hosted on heroku and has simplistic infrastructure.  I expect it to be reliable and stable for the foreseeable future.
- I have no plans to modify the API in a breaking manner.  Any breaking changes will be implemented under a new version namespace.
- I have no plans to implement any authentication or restrictions to the API.  It is open to the internet for any to use with no terms or restrictions.
- The project is open source: https://github.com/pipermerriam/ethereum-function-signature-registry

Ultimately, I'd like to move the database into an Ethereum contract.  The reason it is not currently implemented that way is due to limited string parsing and validation utilities available in solidity.  Because of this, validating that the input strings are appropriately normalized function signatures is prohibitive.
### Implementation

I would plan on taking on the implementation of this feature within the Mist codebase.

**Comment by alexvandesande** [comment]
Yes, this really needs to be done. Also, having the signature would allow us to show the parameters of the function in human readable format. Here's a design for the new improved page:

<img width="773" alt="screen shot 2016-07-12 at 9 00 38 am" src="https://cloud.githubusercontent.com/assets/112898/16766258/6bff9970-480f-11e6-8cc6-d01b777fd14c.png">

* If the full ABI is known, then we can also use the variable names for instead of number (1), (2) on the parameter lists: "To", "Value", "Some Flag" etc

* If it's known standard we could include more details: a transfer from a known coin could very well include the amount of tokens being transferred - **only if there's no ether being transferred**.
