### ISSUE TITLE
Problems with balance

### ISSUE THREAD

**Issue by m0rani** [ethereum/mist#956]
Node type: geth
OS: windows
Network type: main

Mist version: 0.8.0

Hello, I have a problem. Yesterday, I downloaded mist wallet and then went into it and entered the password 2 times. Then appeared Main account (Etherbase) 0x70d835478e7a7958f14E6562BeCaF069E0C81fF9 and I copied the address and sent him eth from poloniex here https://etherchain.org/tx/0x4a70c9916c8fa241db2113cfee1150680c2558ecf65729256b67b75b2016c687 transaction number. The site https://etherchain.org/ seen that the funds are in balance https://etherchain.org/account/0x70d835478e7a7958f14e6562becaf069e0c81ff9. But in the wallet mist, I do not see them. Where is my etner and how to send it back to the stock exchange?
![mist](https://cloud.githubusercontent.com/assets/20412629/16755741/605de036-4832-11e6-9ceb-0574b1ca68ef.jpg)

**Comment by m0rani** [comment]
Unfortunately it is impossible to add a zip file, all the time an error "we don’t support that file type"

**Comment by luclu** [comment]
@m0rani just wait until your node is synced (up to the block at which your transaction was created).
