### ISSUE TITLE
Password Wrong

### ISSUE THREAD

**Issue by stic82** [ethereum/mist#957]
Mist 0.8.0
Windows
Main Network
node: geth

Hi, 
i get wrong password message. But i use this password for my btw wallet to so it is right.
can t send out any etc with this release:(
I have 2 Accounts inside with same pw.

Also on my Windows 8 Wallet freezes after opening: https://github.com/ethereum/mist/issues/958. Can t use it on Windows.

**Comment by lssilva** [comment]
I have the same issue here, I think the problem is related that after the latest upgrade it won't accept too easy password. For example when creating account with the wallet app it rejects but if we create using mist browser it accept but then it says wrong password 

To reproduce the bug create an account using mist with a simple password and try to vote

**Comment by stic82** [comment]
My PW is not easy.. It has symbol and all it need to be safe..
I have a lot of money in their:( little panic over here:(

**Comment by lssilva** [comment]
I checked other issue and my problem was not enough ETH, seems the bug is the error message, maybe all errors will be shown wrong password. You can always try to unlock your account using the geth console or the wallet app and check if it works

**Comment by stic82** [comment]
have try to send 1 eth..
which wallet app?

**Comment by stic82** [comment]
by the way thanks for your support:)

**Comment by luclu** [comment]
Hi @stic82,
the current "wrong password" alert is broken, as the error string emitted by geth did change.
The current errors are as following https://github.com/ethereum/mist/issues/664:
>
 - `could not decrypt key with given passphrase` (wrong password)
 - `multiple keys match address` (multiple copies of the same accounts)
 - `Insufficient funds for gas * price + value` (not enough ether in etherbase account to invoke contract transaction)
 - `Unable to connect to socket: timeout` (node terminated, etc; used to be `CONNECTION ERROR`)

The ongoing PR is https://github.com/ethereum/mist/pull/959.

In future releases we propose to use [error codes](https://github.com/ethereum/wiki/wiki/JSON-RPC-Error-Codes-Improvement-Proposal) to ensure consistency and compatibility to other nodes.

**Comment by luclu** [comment]
Try to rule out all of the above, fall back to `0.7.3` or look through the following recommendations https://github.com/ethereum/mist/issues/669.

**Comment by joshterrill** [comment]
Yeah I'm having a hard time deploying a contract. Just to test, I typed my password into notepad, copied it to my clipboard, created a test wallet on testnet, pasted my password in, works fine. Then I go and try to deploy a contract, paste my password in, it says wrong password. So should I just switch to `0.7.3`?

**Comment by stic82** [comment]
My Password was right. Was able to use it. Think it has to do with wrong error message.

**Comment by luclu** [comment]
Could you please have a try with `0.8.1` and post its error message?

**Comment by luclu** [comment]
Could you please give the `geth account update` command a try?
This might be helpful as [this post](https://github.com/ethereum/mist/issues/982#issuecomment-247409749) suggests.

**Comment by evertonfraga** [comment]
Issue closed due to inactivity. Please reopen if needed.
