### ISSUE TITLE
Ethereum Wallet Freeze after Starting

### ISSUE THREAD

**Issue by stic82** [ethereum/mist#958]
Mist 0.8.0
Windows
Main Network
node: geth

Wallet loading all blocks start and freeze.. i have to close with task manager.

After starting wallet theire are also no node and block is showing 0

Never had trouble with versions before.
Tested all.

**Comment by luclu** [comment]
Could you please start the wallet via command line and post its output?

**Comment by luclu** [comment]
Do older version work for you?

**Comment by stic82** [comment]
Not since i have tryed the 0.8.0 Version. Same trouble over theire.
Task Manager showing multiple Electron running but i opened only one time.
Thanks for your support!

**Comment by stic82** [comment]
Version 0.7.3 is running and not freezing but no nodes and Blocks are not getting downloaded after starting. 
So i can t use this one too

**Comment by luclu** [comment]
Please try the following:

1. reboot to have a clean state
2. start `0.8.0`
3. after some minutes close it
4. paste `%appdata%\Ethereum\Mist\node.log`'s content here

**Comment by stic82** [comment]
Hi, was trying to do it but 
%appdata%\Ethereum\Mist\node Mist is missing inside.
%appdata%\Ethereum\..
theire is a nodes folder
Folder inside Ethereum:
blockchain
chaindata
d4e567..
dapp
extra
keystore
natspec
nodes
state

**Comment by luclu** [comment]
Please rename the `%appdata%\Ethereum\Mist` folder and try to restart.

**Comment by stic82** [comment]
now theire is a new ethereum folder and it is downloading blockchain again

**Comment by stic82** [comment]
By the Way, i found the Mist Folder. It is standing alone inside %APPDATA%/Roaming/Mist
So Mist is not inside Ethereum.

Here is Log file of node inside Mist Folder:
I0714 07:31:20.008488 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to C:\Users\User\AppData\Roaming\Ethereum\chaindata
I0714 07:31:23.261674 ethdb/database.go:169] closed db:C:\Users\User\AppData\Roaming\Ethereum\chaindata
I0714 07:31:23.262813 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to C:\Users\User\AppData\Roaming\Ethereum\chaindata
I0714 07:31:23.431139 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to C:\Users\User\AppData\Roaming\Ethereum\dapp
I0714 07:31:23.435380 eth/backend.go:172] Protocol Versions: [63 62 61], Network Id: 1
I0714 07:31:23.435380 eth/backend.go:201] Blockchain DB Version: 3
I0714 07:31:23.435867 core/blockchain.go:206] Last header: #1881786 [8a898644…] TD=37217341192413992076
I0714 07:31:23.435867 core/blockchain.go:207] Last block: #1881786 [8a898644…] TD=37217341192413992076
I0714 07:31:23.435867 core/blockchain.go:208] Fast block: #1881786 [8a898644…] TD=37217341192413992076
I0714 07:31:23.436367 eth/handler.go:110] blockchain not empty, fast sync disabled
I0714 07:31:23.437383 p2p/server.go:313] Starting Server
I0714 07:31:23.475166 p2p/discover/udp.go:217] Listening, enode://da0d10b03f55419567a2b1ad4c2231657231267fef39e471166bc40cdc652837a71dc65de455b390b13e0dcda9a6c8e83a0ad60b4420111c19ed019f68cb48cb@87.175.195.108:30303
I0714 07:31:23.475667 p2p/server.go:556] Listening on [::]:30303
I0714 07:31:23.475667 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc
I0714 07:32:13.475680 eth/downloader/downloader.go:320] Block synchronisation started
I0714 07:32:17.206431 core/blockchain.go:964] imported 8 block(s) (0 queued 0 ignored) including 29 txs in 1.6559994s. #1881794 [1b17d443 / 8664ddaa]

**Comment by luclu** [comment]
The log looks good so far. Keep me updated on the outcome.

**Comment by luclu** [comment]
> By the Way, i found the Mist Folder. It is standing alone inside %APPDATA%/Roaming/Mist
So Mist is not inside Ethereum.

You are right! Thank you

How did the resync turn out?

**Comment by stic82** [comment]
Finally i Five up with ethereum wallet. 
I Tried new Mist Release and Works Great. 0.8.1

I did bot finish the resync. Using old data with Mist now
