### ISSUE TITLE
Howto MIST connect Node on Diffrent Maschine

### ISSUE THREAD

**Issue by 1xhabit** [ethereum/mist#963]
Hello Folks, 

i'was now read and read and ask dr. google but i'was not found any howto to connect my ether node.
i'dont like to have a node on my laptop, so i'was setup a node to a linux server. 

but where is a graphic client for a node what not run on my laptop and connect to my node? it will be really nice if for example MIST will give this option to add a node on a different machine and don't start a local geth or eth instance. 

or Maybe someone what is more familiar with this configuration can write a howto, maybe there is some client what will exactly do this. but i'dont was found. for that i'write here to the developers 'cause i'thing they are very familiar with this. 

my client operation system is mac os x and my ethereum node is running at a linux server.  i'hope there is someone out there what have a solution for me and can give me a howto to do that. 

Thanks all and thanks for all developers for the great job around ethereum 
xhabit

**Comment by luclu** [comment]
This will be possible as of this PR https://github.com/ethereum/mist/pull/871.
Please be patient until we release version `0.8.1` which is billed for the 19th of July.
