### ISSUE TITLE
Ethereum-Wallet 0.8 unusable

### ISSUE THREAD

**Issue by mruepp** [ethereum/mist#965]
Node type: geth/eth
OS: osx
Network type: main/test
Mist version: 0.8.0

Ethereum Wallet Interface is completely unusable. Is there any way to fix this? Is even unable to Quit the App.

Since 0.7.5 I can not interact with my wallet. This is really bad.

```javascript
I0713 17:08:49.087901 node/node.go:296] IPC endpoint opened: /Users/michael/Library/Ethereum/geth.ipc
I0713 17:08:49.168686 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-IP1
I0713 17:08:49.330162 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-IP1
I0713 17:09:59.089485 eth/downloader/downloader.go:320] Block synchronisation started
I0713 17:10:24.320745 core/blockchain.go:964] imported 2 block(s) (0 queued 0 ignored) including 5 txs in 2.225968302s. #1878179 [422dc750 / f0f15b60]
I0713 17:10:32.300205 core/blockchain.go:964] imported 4 block(s) (0 queued 0 ignored) including 7 txs in 22.283744ms. #1878183 [6c4823a7 / 070d53af]
I0713 17:10:38.633344 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 8 txs in 19.363904ms. #1878184 [c8613b98 / c8613b98]
I0713 17:10:39.964663 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 7 txs in 15.242563ms. #1878185 [b3d550f0 / b3d550f0]
I0713 17:10:40.292589 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 7 txs in 11.744261ms. #1878185 [039f5deb / 039f5deb]
I0713 17:10:53.809924 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 6.249297ms. #1878186 [5974689b / 5974689b]
I0713 17:10:59.234147 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 13.271631ms. #1878187 [6419d79c / 6419d79c]
I0713 17:11:10.758997 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 1 txs in 4.490608ms. #1878188 [a1fc39e3 / a1fc39e3]
I0713 17:11:13.607741 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 8.853106ms. #1878189 [f0f6f942 / f0f6f942]
I0713 17:11:39.342479 core/blockchain.go:964] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 8.6611ms. #1878190 [4d8043ed / 4d8043ed]
```

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by luclu** [comment]
>Ethereum Wallet Interface is completely unusable. Is there any way to fix this? Is even unable to Quit the App.

Please provide some guideline to reproduce this / be more descriptive in on the current behaviour.

**Comment by mruepp** [comment]
I have a standard installation of OSX 10.11.5, Java 8u92 JDK installed. I downloaded Ethereum Wallet 0.7.4 and put the Folder into /Applications
I added three wallets and watched the dao contract and tokens. Since 0.7.5 to 0.8.0 when I start the wallet, the GUI is completely irresponsive. I can´t click on icons, scroll, change to contracts, etc. I can open the Developer Tools Window however. I can not close nor Quit the Application, nothing happens. The Wallet does not respond. When opened for a while, the Interface gets all white. What Information do you exactly need?

**Comment by luclu** [comment]
Please unwatch the "The DAO" contract as described in this issue: https://github.com/ethereum/mist/issues/778.
You might want to watch it after you fully synced with the network.

**Comment by mruepp** [comment]
Can confirm by starting 0.7.4 ans removing the dao contract, all went back to normal
