### ISSUE TITLE
Ethereum node needs to sync,Please wait....

### ISSUE THREAD

**Issue by happyqq** [ethereum/mist#969]
Node type: Ethereum-Wallet.exe
OS: windows
Network type: main/test
Mist version: 0.8.0

when I start my application,It still show message: "Ethereum node needs to sync,Please wait.... Downloading block 1,204,690 of 1,884,516" or "looking for peers“, but the number " 1,204,690 " no changed
why?

when I lanuched the application ,I add account, enter the password,but i can't find my created account,
application no errors ,no message show

C:\Users\Administrator\AppData\Roaming\Ethereum\chaindata\log
```python
=============== Jul 15, 2016 (CST) ===============
00:12:36.820110 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
00:12:36.830111 version@stat F·[13 325 894 230] S·3GiB[355MiB 612MiB 1GiB 448MiB] Sc·[3.25 6.13 1.76 0.04]
00:12:36.831111 db@open opening
00:12:36.842111 journal@recovery F·1
00:12:36.846111 journal@recovery recovering @7003
00:12:36.951117 version@stat F·[13 325 894 230] S·3GiB[355MiB 612MiB 1GiB 448MiB] Sc·[3.25 6.13 1.76 0.04]
00:12:36.975119 db@janitor F·1464 G·0
00:12:36.975119 db@open done T·144.0083ms
00:12:36.976119 table@compaction L1·1 -> L2·7 S·14MiB Q·25971907
00:12:37.312138 table@build created L2@7007 N·9377 S·2MiB "blo..-td,v4700622":"blo..ody,v18741195"
00:12:37.627156 table@build created L2@7008 N·9996 S·2MiB "blo..der,v18012370":"blo..ody,v11031239"
00:12:37.912172 table@build created L2@7009 N·10143 S·2MiB "blo..der,v10850363":"blo..ody,v20044174"
00:12:38.179188 table@build created L2@7010 N·9976 S·2MiB "blo..der,v19123555":"blo..der,v2233495"
00:12:38.258192 table@build error I·46542 "leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]"
00:12:38.258192 table@build exiting (corruption detected)
00:12:38.258192 table@build revert @7007
00:12:38.259192 table@build revert @7008
00:12:38.260192 table@build revert @7009
00:12:38.261192 table@build revert @7010
```

**Comment by luclu** [comment]
Could you kindly post the content of `%appdata%\Mist\node.log`?

**Comment by happyqq** [comment]
I0715 18:18:46.705521 cmd/utils/flags.go:687] You're one of the lucky few that will try out the JIT VM (random). If you get a consensus failure please be so kind to report this incident with the block hash that failed. You can switch to the regular VM by setting --jitvm=false
I0715 18:18:46.729522 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to C:\Users\Administrator\AppData\Roaming\Ethereum\chaindata
I0715 18:18:47.298555 ethdb/database.go:169] closed db:C:\Users\Administrator\AppData\Roaming\Ethereum\chaindata
I0715 18:18:47.307555 ethdb/database.go:82] Alloted 512MB cache and 1024 file handles to C:\Users\Administrator\AppData\Roaming\Ethereum\chaindata
I0715 18:18:47.394560 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to C:\Users\Administrator\AppData\Roaming\Ethereum\dapp
I0715 18:18:47.407561 eth/backend.go:172] Protocol Versions: [63 62 61], Network Id: 1
I0715 18:18:47.408561 eth/backend.go:201] Blockchain DB Version: 3
I0715 18:18:47.413561 core/blockchain.go:206] Last header: #1204690 [25ae879f…] TD=10440297138264790823
I0715 18:18:47.413561 core/blockchain.go:207] Last block: #1204690 [25ae879f…] TD=10440297138264790823
I0715 18:18:47.413561 core/blockchain.go:208] Fast block: #1204690 [25ae879f…] TD=10440297138264790823
I0715 18:18:47.417562 eth/handler.go:110] blockchain not empty, fast sync disabled
I0715 18:18:47.422562 p2p/server.go:313] Starting Server
I0715 18:18:48.854644 p2p/nat/nat.go:111] mapped network port udp:30303 -> 30303 (ethereum discovery) using UPNP IGDv1-IP1
I0715 18:18:49.251667 p2p/discover/udp.go:217] Listening, enode://6bfdfd26b47cb64a44ca1ffb30b79128e250fb33a9d673e5599999d8acc718a8f35ad9b10b26b9398eef903852728792af1c8c8f620c39506185b548b5613994@116.24.160.215:30303
I0715 18:18:49.260667 p2p/server.go:556] Listening on [::]:30303
I0715 18:18:49.260667 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc
I0715 18:18:49.281668 p2p/nat/nat.go:111] mapped network port tcp:30303 -> 30303 (ethereum p2p) using UPNP IGDv1-IP1
I0715 18:18:59.261239 eth/downloader/downloader.go:320] Block synchronisation started
I0715 18:19:25.165721 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:20:13.135464 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:21:00.141153 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:21:13.365909 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:21:21.307364 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:21:43.150613 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:21:56.785393 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:22:10.335168 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:22:17.566582 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:22:27.164130 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:22:41.595956 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:22:56.750823 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:23:10.532611 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:23:18.239052 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:23:28.978666 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:23:38.127189 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:23:52.246997 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:24:03.042614 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:24:23.107762 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:24:25.171880 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:24:33.929381 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:24:50.555332 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:24:55.789631 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:25:07.028274 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:25:37.067992 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:25:57.241146 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:26:09.665857 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:26:18.043336 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:26:25.802780 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:26:42.209718 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]
I0715 18:26:47.608027 eth/downloader/downloader.go:299] Synchronisation failed: leveldb/table: corruption on data-block (pos=1853865): checksum mismatch, want=0xb584e6 got=0x9584e6 [file=004825.ldb]

**Comment by luclu** [comment]
Your local blockchain replica seems to be corrupted:
> `Synchronisation failed: leveldb/table: corruption on data-block (pos=990567): checksum mismatch, want=0x98447063 got=0x38aa5ea7 [file=035779.ldb]`

Newer versions of `geth` will have a better fault-recovery. For now please try to remove the file `035779.ldb` in the `chaindata`-folder under `%APPDATA%/Ethereum/`. If this is not working for you remove the whole `chaindata`-folder. Unfortunately you would need to resync afterwards.

**Comment by happyqq** [comment]
Thanks,I will try it again
