### ISSUE TITLE
How to install mist binaries in linux?

### ISSUE THREAD

**Issue by 5chdn** [ethereum/mist#97]
I see there is a release, for example beta4: https://github.com/ethereum/mist/releases/tag/0.3.7
Which contains binaries for mist and geth.

The geth binary works well stand-alone, i can put it anywhere and run it as a node, like:

    install -m 755 "$srcdir/Ethereum-Wallet-linux-x64-0-3-7/resources/node/geth/geth" "/usr/bin/geth"

But trying the same with the mist browser does strange stuff. What I have tried so far:

    install -m 755 "$srcdir/Ethereum-Wallet-linux-x64-0-3-7/Ethereum-Wallet" "/usr/bin/mist"
    install -m 755 "$srcdir/Ethereum-Wallet-linux-x64-0-3-7/libnode.so" "/usr/lib/libnode.so"
 
This fails with:

    ~ $ mist
    [2586:1228/133648:FATAL:content_main_runner.cc(721)] Check failed: base::i18n::InitializeICU(). 
    Aborted (core dumped)

It's obviously missing something. Now I wonder, is this desired behaviour that the 57MB binary does not work stand-alone? If yes, what else do I have to install besides `geth`, `libnode.so` and `Ethereum-Wallet`? And where does mist look for those extras?

I'm trying to create an Archlinux package. And by the way, is the official name Ethereum Wallet or Mist Browser?

**Comment by frozeman** [comment]
The binary is basically a electron package, you might want to check there on how to run them on arch linux (which i never tried).

The current release is the Ethereum Wallet, but its basically mist with only one dapp loaded as interface.

**Comment by 5chdn** [comment]
Thanks, copying the electron packaging workflow worked out.

For reference: https://aur.archlinux.org/packages/mist/

**Comment by frozeman** [comment]
Thanks, so this can be used to install on arch linux easily?
Nice thanks

**Comment by 5chdn** [comment]
Yes, using any [AUR helper](https://wiki.archlinux.org/index.php/AUR_helpers) for the [user repository](https://wiki.archlinux.org/index.php/Arch_User_Repository) allows you to install mist, e.g. 

    $ yaourt -S mist

will install mist, libnode, geth and any dependencies.
