### ISSUE TITLE
Account tab does not show in Mist browser

### ISSUE THREAD

**Issue by nhq9765** [ethereum/mist#973]
Node type: geth/eth
OS: windows 10
Network type: main
Mist version: 0.8.0

It used to show before and then it disappeared and then it showed again and now it has disappeared again.
![can not see account tab](https://cloud.githubusercontent.com/assets/20408104/16873805/7c82e5da-4a63-11e6-81dd-661fdc9f206b.JPG)

The account tab which shows under the Browse section.

**Comment by radekradekradek** [comment]
I have the same issue, but on Windows 8.1. 

Node type: geth/eth
OS: windows 8.1
Network type: main
Mist version: 0.8.1

![mist](https://cloud.githubusercontent.com/assets/17460038/16903000/ea586774-4c3e-11e6-973e-dde7cb6807a6.png)

**Comment by tjayrush** [comment]
Same issue on Mac 10.10.5. When I first start up in Mist 0.8.0, I can see my accounts, but when I sometimes click (not consistent) on browse section it disappears. Cannot see it again until I quit and restart Mist, in which case the accounts always reappear.

**Comment by stic82** [comment]
Same here. After First succesful try today My Account does not shown in mist.

**Comment by RandomLetter** [comment]
Same issue as well

**Comment by alexvandesande** [comment]
Those are very different issues:

@nhq9765 your tabs are at full, click the < button
@radekradekradek are you missing accounts (we can't see on the screenshot) or the accounts tab (those were renamed wallets)

The other comments seem related to not seeing accounts. It's a different bug so I'll close this one.
