### ISSUE TITLE
Effectively deal with large amount of tabs

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/mist#974]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.8.0

![screen shot 2016-07-16 at 4 04 39 am](https://cloud.githubusercontent.com/assets/47108/16893311/b0df1f5e-4b0a-11e6-9035-209f2c0ff80a.png)

**Comment by evertonfraga** [comment]
Here I see:
- [ ] scroll on tab area.
- [ ] make network info more compact. its height is sometimes unpredictable due to texts in different situations.

@alexvandesande take a look here please.

**Comment by alexvandesande** [comment]
Scroll on the tab area is a good solution but we need to see how it works on Windows and other OSs as it might force a visible ugly scroll bar

**Comment by evertonfraga** [comment]
Yes, of course.

actually this isn't solved in any comparable browser. on horizontal-laid
tabs, they are shrunk and both the name and icon becomes hidden.
I'll try to set up some OSX-style scrollbars, and keep an eye on the
right-handed elements, like those we have with the wallet.


--
Everton Fraga
21 999-279-999

**Comment by evertonfraga** [comment]
It is done, released in 0.9.0
