### ISSUE TITLE
OSX data location other than ~/Library to exclude chaindata from TimeMachine Backup

### ISSUE THREAD

**Issue by PacketSmuggler** [ethereum/mist#978]
My OSX Mist install writes its data here:
```bash
/Users/me/Library/Ethereum

du -m
12347	./chaindata
1	./dapp
1	./keystore
6	./nodes
12352	.
```

When backing up using Time Machine it treats `~/Library` as part of the system, it's not visible in the Exclude/Include dialog, and therefore it's not possible to exclude this 12 gig of content which really doesn't need to be backed up. We should have the option of using a location other than `~/Library` to store our data, or at least the chaindata.

---

Node type: geth/eth
OS: osx
Network type: main
Mist version: 0.8.0

**Comment by luclu** [comment]
You are right @PacketSmuggler this is rather unfortunate. `~/Library` is ought to be a configuration folder. 
On the other hand many vendors of for example cgi software - where built-in assets easily bubble up to several GBs - also use this folder.

Unfortunately this is unlikely to change as the `chaindata`'s folder is subject to the node and this convention is shared accross all OS.

Luckily there are two easy workarounds for this:

1. show `~/Library` in the Finder via this command: `chflags nohidden ~/Library` and exclude it from TimeMachine
2. change geth's data folder via these [flags](https://github.com/ethereum/mist/issues/927#issuecomment-231692551) passed to Mist

**Comment by Barthelemy** [comment]
If one wants to exclude only the chain-data and not the whole Library folder, they can mv ~/Library/Ethereum/chain-data to a visible folder (e.g. $HOME) and symlink to it from there. Then, one can exclude the chain-data folder from Time Machine.

// Start by quitting Ethereum-wallet
cd $someplaceVisibleToTM
mv ~/Library/Ethereum/ .
ln -s $someplaceVisibleToTM/chaindata ~/Library/Ethereum
// now exclude $someplaceVisibleToTM/chaindata from TM
