### ISSUE TITLE
Ethereum wallet > 0.7.4 immediately closes when launching

### ISSUE THREAD

**Issue by ngburke** [ethereum/mist#983]
Node type: geth
OS: windows 10 64-bit
Network type: main
Mist version: 0.7.5+

I had previously been running on an old version of Ethereum-Wallet r0.5.2 with no problems. With the fork coming up, I wanted to upgrade. Downloaded r0.8.1 win-64 and fired it up and it immediately terminated (no splash screen at all). After a binary search on the version that this behavior started, i found I was able to successfully launch r0.7.4, but 0.7.5+ exhibited the same problem.

I tried a number of things, first deleted the chaindata in the Ethereum folder. Using the geth packaged with r0.8.1, I was able to re-sync the blockchain no problem. Unfortunately, the Ethereum-Wallet.exe still instantly crashed. I then got rid of the AppData/Roaming/Mist folder and re-launched 0.8.1 and 0.7.5, stiil the same problem. 

I deleted /AppData/Roaming/Mist/node.log, and when I launch a working version (0.7.4), a new node.log appears. When deleting this again and running 0.8.1 or 0.7.5 no node.log file is even created, Looking for some help please, let me know if I can provide more information.

**Comment by luclu** [comment]
Thank you for this neat issue description. 👍 
Could you please start `Ethereum-Wallet.exe` from the terminal and post its output?

**Comment by ngburke** [comment]
When launching from the command line, it shows no output in the terminal - just a blank line. When I press return a second time, I'm back to the command prompt.

![crash](https://cloud.githubusercontent.com/assets/7350691/16903184/e2e2d06e-4c2b-11e6-8b25-0b627df0f323.png)

**Comment by luclu** [comment]
hmm, could you append it with `--loglevel trace`?

**Comment by ngburke** [comment]
Tried that, same result no output. Here is a screenshot showing the 0.8.1 w/ trace (blank) vs. 0.7.4 (looks nice).

![trace](https://cloud.githubusercontent.com/assets/7350691/16903232/3ed293f4-4c2d-11e6-8c71-2d4adb5406bf.png)

**Comment by luclu** [comment]
This seems to be related to node.js not being able to load some library within the electron framework: https://github.com/electron/electron/issues/6437#issuecomment-232213938

**Comment by ngburke** [comment]
I tried downloading node.js v6.3.0 and it appears to have 'started' (can get to the node command prompt). I can confirm that I am running wireless LAN which looks similar to the setup that the other person at https://github.com/nodejs/node/issues/5588. 

Is there anything I can do to work around this? It was non-obvious to me how node.js and the ethereum wallet are dependent (I didn't seem to have node.js installed on my system before, maybe its something that gets bundled at build?). Is the problem still considered open at this time?

**Comment by mhaythem** [comment]
I have the same issue 
any help please

**Comment by luclu** [comment]
We might have to wait for https://github.com/electron/electron/issues/6437 for now. Perhaps they will come up with some workaround - otherwise the next release should fix this hopefully.

**Comment by netprofit** [comment]
same problem for me too: node starts ok, finds peers, starts syncing and then crashes. Using Mist 0.8.1, which I installed yesterday (OS windows 10 64bit) Y.day everything was working fine. Problem only started this morning. Only difference to what's reported by others is that when I first opened the program the wallet did open and I got this message:

404
File not found
The site configured at this address does not contain the requested file.
If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.
Read the full documentation for more information about using GitHub Pages.
GitHub Status — @githubstatus

I then closed the program and when I restarted it, I got the crashing on launch problem.

**Comment by ngburke** [comment]
I'm concerned with the fork happening that I'll end up on the wrong side of that if I don't update to 0.8.1 soon. Can someone educate me on whether using a working version 0.7.4 will by default mean I am on the 'fork' side of the fence?

**Comment by luclu** [comment]
@ngburke I you had any version of Mist/Ethereum-Wallet <`0.8.1` syncing the block transition from bock `1,9199,999` to `1,920,000` your node will now be on the non-HF chain - regardless if you run `0.8.1` after the transition. In that case you will have to remove the `chaindata` folder and initiate a full resync AFAIK.

Unfortunately this means you cannot use any older version until this issue is fixed.

**Comment by luclu** [comment]
@ngburke could you please try to backup the `%appdata%\Mist` folder and delete the mist.lokidb file?

**Comment by ngburke** [comment]
I did a search in %appdata%\Roaming\Mist for mist.lokidb and found no file with that name.

**Comment by netprofit** [comment]
@ngburke the file is definitely there (in the roaming folder)

@ luclu having deleted the mist.lokidb file, my wallet (0.8.1 running on Windows 10 64 bit) opened successfully, so the fix works but having closed the wallet the problems (wallet crashing immediately following syncronisation reoccurs or the synchronisation process not even starting) reoccur and so it's necessary to delete the mist.lokidb file again in order for the wallet to open.

**Comment by mhaythem** [comment]
after deleting mist.lokidb the mist open opened successfully (WIN7 64)
thanks

**Comment by luclu** [comment]
@ngburke ok, I just wanted to make sure https://github.com/ethereum/mist/issues/1002 is not related.

---

@netprofit @mhaythem you are experiencing issue https://github.com/ethereum/mist/issues/1002. 
Please follow that issue as **this one is unrelated**. You can unsubscribe on the right sidebar if you want.

**Comment by netprofit** [comment]
@luclu ok, thanks. Nevertheless, your suggested fix (delete mist.lokidb) did work.

**Comment by ngburke** [comment]
Confirmed fixed in 0.8.4

**Comment by Doncharly** [comment]
https://kiboplatform.net/DonKibo

https://kiboplatform.net/es/advantages.html

http://huaco2016.wixsite.com/kibo-ingledoncharly

*KIBO. Loto Registracion Only 10 Ethereum Unique Pay*
*Skype Carlos.Silva522*

2016-10-02 4:46 GMT-05:00 Nathaniel Burke <notifications@github.com>:
