### ISSUE TITLE
Unable to delete watched contract

### ISSUE THREAD

**Issue by obscuren** [ethereum/mist#986]
Node type: na
OS: all
Network type: na
Mist version: any

When you’ve an account with address `X` (with account I mean key w/ prv key), then add a contract **Watch contract** and specify the address of this watch contract as `X`; now every time you click on that icon in the **Watched contract** list it will link to the actual account. This prevents the Watched contract from being deleted.

* https://www.dropbox.com/s/milgqgw1as6qum6/Screenshot%202016-07-18%2013.44.26.png?dl=0
* https://www.dropbox.com/s/nd0svd1832ywpam/Screenshot%202016-07-18%2013.45.04.png?dl=0

**Comment by obscuren** [comment]
Duplicate https://github.com/ethereum/mist/issues/686

Sorry!

**Comment by luclu** [comment]
fixed: https://github.com/ethereum/mist/issues/686#issuecomment-233494479
