### ISSUE TITLE
The "provided maximum fee" doesn't auto update

### ISSUE THREAD

**Issue by stephantual** [ethereum/mist#99]
windows 10, mist 037
if I use a multisig wallet and try to call a function on it, the "provided maximum fee" doesn't auto fill. 

Furthermore, it's not obvious it's something the user can modify as the UX is obtuse (it appears as a link, not as an input field).

screenshot:
https://infinit.io/_/VXZcspP

**Comment by stephantual** [comment]
So I'm getting this sense that this is closely related to https://github.com/ethereum/go-ethereum/issues/2100

... it's very confusing as the key is not only accepted, but actually you get the 'this key is an owner of the multisig wallet' message when importing the contract.

**Comment by frozeman** [comment]
I can't see the screenshot, but i guess you're talking about the confirmation window? The changeable gas field was made on purpose to look like text, because you normally wouldn't need to edit it.

i also noticed that sometimes it couldn't calculate correctly, when executing custom contracts, im not yet sure what it is. will look into this once i get to it again.

**Comment by stephantual** [comment]
Sorry for the late reply. Yes, the confirmation window.

**Comment by alexvandesande** [comment]
@stephantual do you also have a "transaction will not execute warning"? Usually when it provides 0 gas, it's because the transaction wouldnt be able to execute anyway

**Comment by gcmartinelli** [comment]
I believe my input is related to this. It is confusing to have Step #1 where you decide the "most amount of money that might be used to process" and on Step #2 this value gets changes to "Estimated fee consumption" with a field below (which I didn't know I could edit until reading this thread) with a NEW value for "maximum fee". 
Screenshot: http://imgur.com/QagefJk

**Comment by frozeman** [comment]
This is something people  need to understand for now, when using ethereum.
The concept of gas is so that you provide gas, and only a part of it will actually be used.
