### ISSUE TITLE
macbook pro freezing up with 8.1 version

### ISSUE THREAD

**Issue by supersparx** [ethereum/mist#996]
Node type: geth/eth
OS: linux/windows/osx
Network type: main/test
Mist version: 0.0.0

Please check the already existing issues, before creating an issue. We would like to keep duplicates at a minumim.
Read the https://github.com/ethereum/wiki/wiki/Mist-Troubleshooting-Guide first, where we summarized a few of the known issues.

Add the following to issue, when possible:

- Screenshots
- Check the console, of Mist (CTRL/CMD + ALT + i) and take a screenshot.
- Log files (as ZIP archive)
-   osx: ~/Library/Application Support/Mist/node.log (Open Home folder > Show View Options > Show Library Folder)
-   windows: %APPDATA%/Roaming/Mist/node.log
-   linux: ~/.config/Mist/node.log

**Comment by supersparx** [comment]
i have deleted chain data and resynced the node still no access because freezing and getting hot and then after a while the mist interface just goes blank.

**Comment by luclu** [comment]
Please, at least fill out the basic info and pretend you were search other issues.

**Comment by luclu** [comment]
Remove the "The DAO" contract while syncing for a start. 
You could also you https://myethereumwallet.com to send those DAO token.

**Comment by supersparx** [comment]
Ok how do I remove.  Can I somehow just put in my keys to myethereum wallet

**Comment by luclu** [comment]
Use `0.6.2` to remove the contract as it still misses the event-logging.
